var pairs =
{
"abr-type":{"command":1,"(cisco":1,"standard":1}
,"command":{"ospfv3":1,"revert":1,"syntax":1,"mode":1}
,"ospfv3":{"area":1}
,"area":{"border":1,"actively":1,"ibm":1,"configured":1}
,"border":{"router":1}
,"router":{"(abr)":1,"considered":1,"mode":1,"ipv6":1}
,"(abr)":{"type":1}
,"type":{"parameter":1,"default":1,"allows":1,"ibm":1,"cisco":1}
,"parameter":{"command":1}
,"revert":{"abr":1}
,"abr":{"type":1,"types":1,"area":1,"using":1,"default":1}
,"default":{"setting":1,"abr":1}
,"setting":{"(cisco)":1}
,"(cisco)":{"specifying":1}
,"specifying":{"abr":1}
,"allows":{"better":1}
,"better":{"functioning":1}
,"functioning":{"multi-vendor":1}
,"multi-vendor":{"environment":1}
,"environment":{"abr":1}
,"types":{"cisco":1}
,"cisco":{"(rfc":1,"specify":1,"implementation":1,"command":1}
,"(rfc":{"3509)":1,"2328)":1}
,"3509)":{"router":1}
,"considered":{"abr":1}
,"actively":{"attached":1,"connected":1}
,"attached":{"backbone":1,"command":1}
,"backbone":{"area":1,"need":1}
,"ibm":{"(rfc":1,"standard)":1,"standard":1,"specify":1,"implementation":1}
,"configured":{"case":1,"backbone":1}
,"case":{"configured":1}
,"need":{"actively":1}
,"connected":{"standard":1}
,"standard":{"(rfc":1,"parameters":1,"specify":1,"abr":1}
,"2328)":{"router":1}
,"syntax":{"abr-type":1}
,"(cisco":{"ibm":1}
,"standard)":{"abr-type":1}
,"parameters":{"cisco":1}
,"specify":{"alternative":1,"standard":1}
,"alternative":{"abr":1}
,"using":{"cisco":1,"ibm":1}
,"implementation":{"default":1,"standard":1}
,"mode":{"router":1,"examples":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"ipv6":{"ospf":1}
,"ospf":{"(config-router)":1}
,"(config-router)":{"abr-type":1}
}
;Search.control.loadWordPairs(pairs);
