var pairs =
{
"differentiated":{"services":1}
,"services":{"(diffserv)":1,"code":1}
,"(diffserv)":{"mechanism":1}
,"mechanism":{"classify":1}
,"classify":{"manage":1}
,"manage":{"network":1}
,"network":{"traffic":1}
,"traffic":{"provide":1,"engineering":1,"prioritized":1,"example":1,"precedence":1,"diffserv":1}
,"provide":{"quality":1}
,"quality":{"service":1}
,"service":{"(qos)":1,"providers":1,"(tos)":1}
,"(qos)":{"guarantees":1}
,"guarantees":{"service":1}
,"providers":{"diffserv":1}
,"diffserv":{"extends":1,"enables":1,"redefines":1,"uses":1}
,"extends":{"resource":1}
,"resource":{"reservation":1}
,"reservation":{"protocol":1}
,"protocol":{"traffic":1}
,"engineering":{"(rsvp-te)":1}
,"(rsvp-te)":{"diffserv":1}
,"enables":{"traffic":1}
,"prioritized":{"class":1}
,"class":{"certain":1}
,"certain":{"kinds":1}
,"kinds":{"traffic":1}
,"example":{"voice":1}
,"voice":{"traffic":1}
,"precedence":{"types":1}
,"types":{"traffic":1}
,"redefines":{"bits":1}
,"bits":{"type":1}
,"type":{"service":1}
,"(tos)":{"field":1}
,"field":{"packet":1,"qos":1}
,"packet":{"header":1}
,"header":{"diffserv":1}
,"uses":{"differentiated":1}
,"code":{"point":1}
,"point":{"(dscp)":1}
,"(dscp)":{"field":1}
,"qos":{"priority":1}
,"priority":{"supports":1}
,"supports":{"levels":1}
,"levels":{"classification":1}
,"classification":{"defined":1}
,"defined":{"rfc":1,"rfcs":1}
,"rfc":{"2474":1}
,"2474":{"multi-protocol":1}
,"multi-protocol":{"label":1}
,"label":{"switching":1}
,"switching":{"(mpls)":1}
,"(mpls)":{"support":1}
,"support":{"defined":1}
,"rfcs":{"3270":1}
,"3270":{"4124":1}
}
;Search.control.loadWordPairs(pairs);
