var pairs =
{
"network":{"synchronization":1,"routes":1}
,"synchronization":{"command":1,"bgp":1,"network":1,"parameters":1,"following":1}
,"command":{"enable":1,"disable":1,"syntax":1,"mode":1}
,"enable":{"igp":1}
,"igp":{"synchronization":1}
,"bgp":{"static":1,"(config-router)":1,"(config)":1}
,"static":{"network":1,"routes":1}
,"routes":{"parameter":1,"command":1,"router":1,"ipv6":1}
,"parameter":{"command":1}
,"disable":{"synchronization":1}
,"syntax":{"network":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"router":1,"address":1,"examples":1,"configure":1}
,"router":{"mode":1,"configuration":1,"bgp":1}
,"address":{"family":1}
,"family":{"mode":1}
,"examples":{"following":1}
,"following":{"example":1}
,"example":{"enables":1}
,"enables":{"igp":1}
,"configuration":{"mode":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1,"address-family":1}
,"(config-router)":{"network":1}
,"ipv6":{"unicast":1}
,"unicast":{"address-family":1,"(config-af)":1}
,"address-family":{"mode":1,"ipv6":1}
,"(config-af)":{"network":1}
}
;Search.control.loadWordPairs(pairs);
