var pairs =
{
"show":{"mpls-tp":1}
,"mpls-tp":{"loss-measurement":1}
,"loss-measurement":{"command":1,"(meg-name":1,"meg2":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"statistics":1}
,"statistics":{"ietf":1}
,"ietf":{"itut":1,"form":1}
,"itut":{"loss":1,"form":1}
,"loss":{"measurement":1}
,"measurement":{"session":1}
,"session":{"command":1}
,"syntax":{"ietf":1}
,"form":{"show":1}
,"(meg-name":{"name":1}
,"name":{"me-name":1,"mep-id":1,"meg":1,"1-48":1,"name":1}
,"me-name":{"name)":1,"maintenance":1,"me1":1}
,"name)":{"itut":1}
,"mep-id":{"<1-8191>)":1}
,"<1-8191>)":{"parameters":1}
,"parameters":{"meg-name":1}
,"meg-name":{"maintenance":1}
,"maintenance":{"entity":1}
,"entity":{"group":1,"(me)":1}
,"group":{"(meg)":1,"end":1}
,"(meg)":{"name":1}
,"meg":{"name":1}
,"1-48":{"characters":1}
,"characters":{"me-name":1,"<1-8191>":1}
,"(me)":{"name":1}
,"<1-8191>":{"maintenance":1}
,"end":{"point":1}
,"point":{"(mep)":1}
,"(mep)":{"identifier":1}
,"identifier":{"command":1}
,"mode":{"exec":1,"examples":1}
,"exec":{"mode":1}
,"examples":{"show":1}
,"meg2":{"me-name":1}
}
;Search.control.loadWordPairs(pairs);
