var pairs =
{
"ripng_enable_nbr_delete":{"function":1,"(u_int32_t":1}
,"function":{"disables":1,"called":1}
,"disables":{"ripng":1}
,"ripng":{"routing":1}
,"routing":{"neighbor":1}
,"neighbor":{"function":1,"syntax":1,"address":1,"already":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"neighbor":1}
,"syntax":{"int":1}
,"int":{"ripng_enable_nbr_delete":1,"instance":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"int":1,"virtual":1}
,"instance":{"struct":1,"instance":1,"number":1,"cannot":1}
,"struct":{"pal_in6_addr":1}
,"pal_in6_addr":{"*addr":1}
,"*addr":{"char":1}
,"char":{"*ifname)":1}
,"*ifname)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1,"exist":1}
,"default":{"value":1}
,"value":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"parameter":1}
,"parameter":{"instance":1}
,"number":{"addr":1}
,"addr":{"neighbor":1}
,"address":{"ifname":1,"invalid":1}
,"ifname":{"interface":1}
,"interface":{"name":1}
,"name":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"rip_api_set_err_address_invalid":1}
,"rip_api_set_err_address_invalid":{"neighbor":1}
,"invalid":{"rip_api_set_err_invalid_value":1}
,"rip_api_set_err_invalid_value":{"neighbor_prefix":1}
,"neighbor_prefix":{"null":1}
,"null":{"rip_api_set_err_nbr_static_exist":1}
,"rip_api_set_err_nbr_static_exist":{"neighbor":1}
,"already":{"table":1}
,"table":{"rip_api_set_err_nbr_static_not_exist":1}
,"rip_api_set_err_nbr_static_not_exist":{"static":1}
,"static":{"node":1}
,"node":{"exist":1}
,"exist":{"rip_api_set_err_process_not_exist":1,"rip_api_set_success":1}
,"rip_api_set_err_process_not_exist":{"instance":1}
,"cannot":{"found":1}
,"found":{"rip_api_set_err_vr_not_exist":1}
,"rip_api_set_err_vr_not_exist":{"virtual":1}
,"rip_api_set_success":{"call":1}
,"call":{"successful":1}
}
;Search.control.loadWordPairs(pairs);
