var pairs =
{
"ldp_id":{"data":1,"\u002F*holdtime":1}
,"data":{"structure":1}
,"structure":{"defined":1}
,"defined":{"ldpd\u002Fldpd.h":1}
,"ldpd\u002Fldpd.h":{"file":1}
,"file":{"definition":1}
,"definition":{"struct":1}
,"struct":{"ldp_id":1}
,"\u002F*holdtime":{"thread":1}
,"thread":{"adjacency":1,"*t_holdtime":1}
,"adjacency":{"*\u002Fstruct":1,"targeted":1,"family":1}
,"*\u002Fstruct":{"thread":1}
,"*t_holdtime":{"ifdef":1}
,"ifdef":{"have_snmp":1}
,"have_snmp":{"\u002F*timestamp":1}
,"\u002F*timestamp":{"last":1}
,"last":{"hello":1}
,"hello":{"packet":1}
,"packet":{"received":1}
,"received":{"*\u002Fpal_time_t":1}
,"*\u002Fpal_time_t":{"hello_received":1}
,"hello_received":{"endif":1}
,"endif":{"\u002F*have_snmp":1}
,"\u002F*have_snmp":{"*\u002F\u002F*hold":1}
,"*\u002F\u002F*hold":{"time":1}
,"time":{"*\u002Fu_int16_t":1}
,"*\u002Fu_int16_t":{"holdtime":1}
,"holdtime":{"\u002F*flag":1}
,"\u002F*flag":{"track":1}
,"track":{"whether":1}
,"whether":{"adjacency":1}
,"targeted":{"peer":1}
,"peer":{"*\u002Fu_char":1}
,"*\u002Fu_char":{"targeted_peer":1,"family":1}
,"targeted_peer":{"\u002F*ldp":1}
,"\u002F*ldp":{"adjacency":1}
,"family":{"*\u002Fu_char":1}
}
;Search.control.loadWordPairs(pairs);
