var pairs =
{
"lldp_api_delete_agent":{"function":1,"(u_char":1}
,"function":{"called":1,"succeeds":1}
,"called":{"delete":1}
,"delete":{"lldp":1}
,"lldp":{"agent":1}
,"agent":{"port":1,"ifp":1}
,"port":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"lldp_api_delete_agent":1}
,"(u_char":{"*mac":1}
,"*mac":{"struct":1}
,"struct":{"interface":1}
,"interface":{"*ifp)":1,"structure":1,"found":1}
,"*ifp)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"mac":1,"none":1}
,"mac":{"mac":1,"address":1}
,"address":{"lldp":1}
,"ifp":{"interface":1}
,"structure":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"lldp_api_success":1}
,"lldp_api_success":{"function":1}
,"succeeds":{"lldp_api_err_lldp_if_not_exist":1}
,"lldp_api_err_lldp_if_not_exist":{"interface":1}
,"found":{"lldp_api_err_onm_if_not_exist":1}
,"lldp_api_err_onm_if_not_exist":{"onmd":1}
,"onmd":{"found":1}
}
;Search.control.loadWordPairs(pairs);
