var pairs =
{
"show":{"debugging":1}
,"debugging":{"ipv6":1,"information":1,"status":1,"mribv6":1}
,"ipv6":{"mrib":1,"multicast":1}
,"mrib":{"command":1,"show":1,"(vrf":1,"debugging":1,"ipc":1}
,"command":{"display":1,"syntax":1,"mode":1,"show":1}
,"display":{"ipv6":1,"routes":1}
,"multicast":{"debugging":1}
,"information":{"command":1}
,"syntax":{"show":1}
,"(vrf":{"name":1}
,"name":{"parameters":1}
,"parameters":{"vrf":1}
,"vrf":{"display":1}
,"routes":{"vpn":1}
,"vpn":{"routing\u002Fforwarding":1}
,"routing\u002Fforwarding":{"instance":1}
,"instance":{"command":1}
,"mode":{"exec":1,"privileged":1,"examples":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"examples":{"following":1}
,"following":{"sample":1}
,"sample":{"output":1}
,"output":{"show":1}
,"status":{"mribv6":1}
,"mribv6":{"event":1,"fib":1,"pim":1,"nsm":1,"mrib":1}
,"event":{"debugging":1}
,"fib":{"message":1}
,"message":{"debugging":1}
,"pim":{"register":1}
,"register":{"message":1}
,"nsm":{"ipc":1}
,"ipc":{"message":1}
}
;Search.control.loadWordPairs(pairs);
