var pairs =
{
"peer_ebgp_multihop_set":{"function":1,"(struct":1}
,"function":{"sets":1,"called":1,"successful":1}
,"sets":{"ebgp":1}
,"ebgp":{"multihop":1}
,"multihop":{"configuration":1,"ttl":1}
,"configuration":{"function":1,"(-19)":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"ebgp-multihop":1}
,"ebgp-multihop":{"syntax":1}
,"syntax":{"int":1}
,"int":{"peer_ebgp_multihop_set":1}
,"(struct":{"bgp_peer":1}
,"bgp_peer":{"*peer":1}
,"*peer":{"u_int8_t":1}
,"u_int8_t":{"ttl)":1}
,"ttl)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"peer":1,"none":1}
,"peer":{"bgp":1,"ttl":1,"peer-group":1}
,"bgp":{"peer":1}
,"ttl":{"ebgp":1,"value":1}
,"value":{"255>":1,"bgp_api_set_success":1}
,"255>":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"bgp_api_set_success":{"function":1}
,"successful":{"(0)":1}
,"(0)":{"bgp_api_set_err_peer_group_has_the_flag":1}
,"bgp_api_set_err_peer_group_has_the_flag":{"peer":1}
,"peer-group":{"member":1,"configuration":1}
,"member":{"change":1}
,"change":{"peer-group":1}
}
;Search.control.loadWordPairs(pairs);
