var pairs =
{
"rip_route_default_add":{"function":1,"(u_int32_t":1}
,"function":{"generates":1,"called":1}
,"generates":{"default":1}
,"default":{"route":1,"value":1}
,"route":{"routing":1}
,"routing":{"information":1}
,"information":{"protocol":1}
,"protocol":{"(rip)":1}
,"(rip)":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"default-information":1}
,"default-information":{"syntax":1}
,"syntax":{"int":1}
,"int":{"rip_route_default_add":1,"instance)":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"int":1,"virtual":1,"exist":1}
,"instance)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"value":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"parameter":1}
,"parameter":{"instance":1}
,"instance":{"number":1,"output":1,"cannot":1}
,"number":{"instance":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"rip_api_set_err_process_not_exist":1}
,"rip_api_set_err_process_not_exist":{"instance":1}
,"cannot":{"found":1}
,"found":{"rip_api_set_err_network_exist":1}
,"rip_api_set_err_network_exist":{"network":1}
,"network":{"already":1}
,"already":{"table":1}
,"table":{"rip_api_set_err_vr_not_exist":1}
,"rip_api_set_err_vr_not_exist":{"vr_id":1}
,"exist":{"rip_api_set_success":1}
,"rip_api_set_success":{"call":1}
,"call":{"successful":1}
}
;Search.control.loadWordPairs(pairs);
