var pairs =
{
"hal_if_get_hwaddr":{"function":1,"(char":1}
,"function":{"gets":1,"fails":1,"succeeds":1}
,"gets":{"hardware":1}
,"hardware":{"address":1}
,"address":{"interface":1,"case":1,"syntax":1,"hwaddr_len":1,"length":1}
,"interface":{"media":1,"name":1,"index":1}
,"media":{"access":1}
,"access":{"control":1}
,"control":{"(mac)":1}
,"(mac)":{"address":1}
,"case":{"ethernet":1}
,"ethernet":{"requirements":1}
,"requirements":{"caller":1}
,"caller":{"provide":1}
,"provide":{"buffer":1}
,"buffer":{"large":1}
,"large":{"enough":1}
,"enough":{"hold":1}
,"hold":{"address":1}
,"syntax":{"int":1}
,"int":{"hal_if_get_hwaddr":1,"ifindex":1,"*hwaddr_len)":1}
,"(char":{"*ifname":1}
,"*ifname":{"unsigned":1}
,"unsigned":{"int":1}
,"ifindex":{"u_char":1,"interface":1}
,"u_char":{"*hwaddr":1}
,"*hwaddr":{"int":1}
,"*hwaddr_len)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifname":1,"hwaddr":1}
,"ifname":{"interface":1}
,"name":{"ifindex":1}
,"index":{"output":1}
,"output":{"parameters":1}
,"hwaddr":{"hardware":1}
,"hwaddr_len":{"hardware":1}
,"length":{"return":1}
,"return":{"value":1}
,"value":{"function":1}
,"fails":{"hal_success":1}
,"hal_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
