var pairs =
{
"receiving":{"channel":1,"end":1,"frame":1}
,"channel":{"frames":1,"ether":1}
,"frames":{"layer-2":1,"filter":1,"trill":1,"frame":1,"written":1}
,"layer-2":{"software":1}
,"software":{"forwarder":1}
,"forwarder":{"snoops":1}
,"snoops":{"trill":1}
,"trill":{"data":1,"channel":1,"module":1,"control":1,"data\u002Fcontrol":1}
,"data":{"frames":1,"frame":1}
,"filter":{"trill":1}
,"frame":{"passed":1,"differentiated":1,"check":1,"differentiate":1,"trill":1,"addition":1}
,"passed":{"trill":1}
,"module":{"further":1}
,"further":{"processing":1}
,"processing":{"trill":1}
,"control":{"frames":1,"frame":1}
,"written":{"socket":1}
,"socket":{"addition":1,"frame":1}
,"addition":{"receiving":1,"check":1}
,"end":{"socket":1}
,"differentiated":{"using":1}
,"using":{"trill":1}
,"data\u002Fcontrol":{"ether":1}
,"ether":{"type":1}
,"type":{"channel":1,"receiving":1,"frame":1,"invokes":1}
,"check":{"made":1}
,"made":{"ether":1,"channel":1}
,"differentiate":{"trill":1}
,"invokes":{"appropriate":1}
,"appropriate":{"parser":1}
,"parser":{"function":1}
}
;Search.control.loadWordPairs(pairs);
