var pairs =
{
"ipi_mpls_debugging_handle":{"function":1,"(u_char":1}
,"function":{"turns":1}
,"turns":{"debugging":1}
,"debugging":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ipi_mpls_debugging_handle":1,"enable)":1}
,"(u_char":{"protocol":1}
,"protocol":{"u_char":1,"protocol":1,"owns":1}
,"u_char":{"msg_type":1}
,"msg_type":{"int":1,"error":1}
,"enable)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"protocol":1}
,"owns":{"entries":1}
,"entries":{"ipi_proto_nsm":1}
,"ipi_proto_nsm":{"ipi_proto_ldp":1}
,"ipi_proto_ldp":{"ipi_proto_bgp":1}
,"ipi_proto_bgp":{"ipi_proto_rsvp":1}
,"ipi_proto_rsvp":{"msg_type":1}
,"error":{"warning":1}
,"warning":{"debug":1}
,"debug":{"notice":1}
,"notice":{"enable":1}
,"enable":{"true":1}
,"true":{"false":1}
,"false":{"return":1}
,"return":{"value":1}
,"value":{"status":1}
,"status":{"call":1}
,"call":{"call":1,"successful":1}
,"successful":{"returns":1}
,"returns":{"cannot":1}
,"cannot":{"send":1}
,"send":{"close":1}
,"close":{"signal":1}
,"signal":{"mpls":1}
,"mpls":{"forwarder":1}
}
;Search.control.loadWordPairs(pairs);
