var pairs =
{
"multiple":{"bvids":1,"bvid":1,"isids":1}
,"bvids":{"per":1,"monitored":1}
,"per":{"maintenance":1,"bvla":1}
,"maintenance":{"association":1}
,"association":{"connectivity":1}
,"connectivity":{"fault":1}
,"fault":{"management":1}
,"management":{"provider":1,"daemon":1}
,"provider":{"backbone":1,"instance":1}
,"backbone":{"bridges":1,"port":1}
,"bridges":{"supports":1}
,"supports":{"multiple":1}
,"bvid":{"per":1,"isid-to-bvid":1}
,"bvla":{"mep":1}
,"mep":{"means":1,"however":1,"stacking":1,"either":1,"customer":1,"provider":1}
,"means":{"bvlan":1}
,"bvlan":{"domain":1}
,"domain":{"configured":1,"mep":1}
,"configured":{"multiple":1}
,"monitored":{"using":1}
,"using":{"single":1}
,"single":{"mep":1}
,"however":{"cbp":1}
,"cbp":{"mep":1,"ensured":1}
,"stacking":{"takes":1}
,"takes":{"place":1}
,"place":{"concept":1}
,"concept":{"primary":1}
,"primary":{"isid":1,"secondary":1}
,"isid":{"secondary":1,"introduced":1,"receive":1,"cbp":1,"mapped":1}
,"secondary":{"isid":1,"vids":1,"isids":1}
,"introduced":{"concepts":1,"chapter":1}
,"concepts":{"primary":1}
,"vids":{"introduced":1}
,"chapter":{"service":1}
,"service":{"domain":1}
,"either":{"mep":1}
,"customer":{"backbone":1}
,"port":{"down":1,"able":1}
,"down":{"mep":1}
,"instance":{"port":1}
,"able":{"monitor":1}
,"monitor":{"multiple":1}
,"isids":{"send":1,"identified":1,"located":1}
,"send":{"frames":1}
,"frames":{"via":1,"secondary":1}
,"via":{"primary":1}
,"receive":{"frames":1}
,"ensured":{"secondary":1}
,"identified":{"primary":1}
,"mapped":{"bvid":1}
,"isid-to-bvid":{"mapping":1}
,"mapping":{"information":1,"primary":1}
,"information":{"managed":1}
,"managed":{"nsm":1}
,"nsm":{"check":1,"module":1}
,"check":{"mapping":1}
,"located":{"nsm":1}
,"module":{"error":1}
,"error":{"message":1}
,"message":{"sent":1}
,"sent":{"operator":1}
,"operator":{"oam":1}
,"oam":{"network":1}
,"network":{"management":1}
,"daemon":{"(onmd)":1}
}
;Search.control.loadWordPairs(pairs);
