var pairs =
{
"isis_clear_interface_counters":{"syntax":1,"(u_int32_t":1}
,"syntax":{"int":1}
,"int":{"isis_clear_interface_counters":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1,"*ifname":1}
,"char":{"*ifname)":1}
,"*ifname)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"*ifname":{"interface":1}
,"interface":{"name":1,"given":1}
,"name":{"output":1,"exist":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"isis_api_set_err_vr_not_exist":1}
,"isis_api_set_err_vr_not_exist":{"exist":1}
,"exist":{"isis_api_set_err_if_not_exist":1,"isis_api_set_success":1}
,"isis_api_set_err_if_not_exist":{"interface":1}
,"given":{"name":1}
,"isis_api_set_success":{"call":1}
,"call":{"successful":1}
}
;Search.control.loadWordPairs(pairs);
