var pairs =
{
"nsm_bridge_uni_set_name":{"function":1,"(struct":1}
,"function":{"sets":1,"called":1,"succeeds":1}
,"sets":{"name":1}
,"name":{"uni":1,"nsm_err_uni_duplicate_entry":1,"nsm_l2_err_invalid_arg":1}
,"uni":{"function":1,"command":1,"uni_type":1,"type":1,"send":1,"already":1,"interface":1,"type\u002Fsvlan":1,"cannot":1}
,"called":{"ethernet":1}
,"ethernet":{"uni":1}
,"command":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"nsm_bridge_uni_set_name":1}
,"(struct":{"interface":1}
,"interface":{"*ifp":1,"pointer":1,"already":1,"configuration":1}
,"*ifp":{"char":1}
,"char":{"*uni_name":1,"*uni_type":1,"*evc_id)":1}
,"*uni_name":{"char":1}
,"*uni_type":{"u_int16_t":1}
,"u_int16_t":{"svlan_id":1}
,"svlan_id":{"char":1,"svlan":1}
,"*evc_id)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"none":1}
,"ifp":{"interface":1}
,"pointer":{"uni_name":1}
,"uni_name":{"name":1}
,"uni_type":{"uni":1}
,"type":{"root":1,"leaf":1}
,"root":{"uni":1,"svlan_id":1}
,"send":{"service":1,"receive":1}
,"service":{"frames":1}
,"frames":{"points":1,"root":1}
,"points":{"evc":1}
,"evc":{"leaf":1,"identifier":1}
,"leaf":{"uni":1,"svlan":1}
,"receive":{"service":1}
,"svlan":{"identifier":1,"null":1,"rooted":1}
,"identifier":{"<2-4094>":1,"output":1}
,"<2-4094>":{"evc_id":1}
,"evc_id":{"evc":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_err_uni_exists":1}
,"nsm_err_uni_exists":{"uni":1}
,"already":{"name":1}
,"nsm_err_uni_duplicate_entry":{"uni":1}
,"nsm_l2_err_invalid_arg":{"operation":1}
,"operation":{"appropriate":1}
,"appropriate":{"interface":1}
,"configuration":{"nsm_pro_vlan_err_invalid_mode":1,"nsm_err_invalid_svlan_or_evc_id":1}
,"nsm_pro_vlan_err_invalid_mode":{"operation":1}
,"nsm_err_invalid_svlan_or_evc_id":{"svlan":1}
,"null":{"nsm_err_invalid_evc_uni_type":1}
,"nsm_err_invalid_evc_uni_type":{"uni":1}
,"rooted":{"multipoint":1}
,"multipoint":{"nsm_err_unipair_list_create_fail":1}
,"nsm_err_unipair_list_create_fail":{"uni":1}
,"type\u002Fsvlan":{"pair":1}
,"pair":{"cannot":1}
,"cannot":{"created":1,"added":1}
,"created":{"nsm_err_unipair_list_add_fail":1}
,"nsm_err_unipair_list_add_fail":{"uni":1}
,"added":{"nsm_pro_vlan_err_hal_err":1,"hal":1}
,"nsm_pro_vlan_err_hal_err":{"uni":1}
,"hal":{"nsm_l2_err_none":1}
,"nsm_l2_err_none":{"function":1}
}
;Search.control.loadWordPairs(pairs);
