var pairs =
{
"snmp":{"restart":1,"multicast":1}
,"restart":{"mribd":1,"snmp":1}
,"mribd":{"command":1,"parameters":1}
,"command":{"restart":1,"syntax":1,"mode":1}
,"multicast":{"routing":1}
,"routing":{"information":1}
,"information":{"base":1}
,"base":{"(mrib)":1}
,"(mrib)":{"command":1}
,"syntax":{"snmp":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"configure":1,"examples":1}
,"configure":{"mode":1,"terminal":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"snmp":1}
}
;Search.control.loadWordPairs(pairs);
