var pairs =
{
"cfm_add_mip":{"function":1,"(struct":1}
,"function":{"adds":1,"succeeds":1,"fails":1}
,"adds":{"maintenance":1}
,"maintenance":{"intermediate":1,"level":1}
,"intermediate":{"point":1}
,"point":{"(mip)":1}
,"(mip)":{"port":1}
,"port":{"syntax":1,"port":1,"vid":1}
,"syntax":{"include":1}
,"include":{"cfm_api.h":1}
,"cfm_api.h":{"s_int32_t":1}
,"s_int32_t":{"cfm_add_mip":1}
,"(struct":{"cfm_port":1}
,"cfm_port":{"*port":1}
,"*port":{"u_int16_t":1}
,"u_int16_t":{"vid":1,"level)":1}
,"vid":{"u_int16_t":1,"vlan":1}
,"level)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"port":1,"none":1}
,"vlan":{"<1-4094>":1}
,"<1-4094>":{"level":1}
,"level":{"maintenance":1,"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"pointer":1}
,"pointer":{"cfm_mip":1}
,"cfm_mip":{"struct":1}
,"struct":{"function":1}
,"succeeds":{"null":1}
,"null":{"function":1}
}
;Search.control.loadWordPairs(pairs);
