var pairs =
{
"nsm_server_send_evc_update":{"check":1,"(struct":1}
,"check":{"service":1}
,"service":{"type":1,"vlan":1}
,"type":{"encodes":1}
,"encodes":{"fields":1}
,"fields":{"invokes":1}
,"invokes":{"nsm":1}
,"nsm":{"server\u2019s":1,"server":1}
,"server\u2019s":{"send":1}
,"send":{"message":1}
,"message":{"api":1}
,"api":{"call":1}
,"call":{"s_int32_t":1}
,"s_int32_t":{"nsm_server_send_evc_update":1}
,"(struct":{"nsm_server_entry":1}
,"nsm_server_entry":{"*nse":1}
,"*nse":{"struct":1,"nsm":1}
,"struct":{"interface":1,"nsm_svlan_reg_info":1}
,"interface":{"*ifp":1,"structure":1}
,"*ifp":{"u_int16_t":1}
,"u_int16_t":{"evc_id":1}
,"evc_id":{"struct":1,"evc":1}
,"nsm_svlan_reg_info":{"*svlan_info":1}
,"*svlan_info":{"cindex_t":1}
,"cindex_t":{"cindex)":1}
,"cindex)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"*nse":1,"svlan_info":1,"none":1}
,"server":{"entry":1}
,"entry":{"ifp":1}
,"ifp":{"reference":1}
,"reference":{"interface":1}
,"structure":{"evc_id":1}
,"evc":{"identifier":1}
,"identifier":{"output":1}
,"output":{"parameters":1}
,"svlan_info":{"service":1}
,"vlan":{"info":1}
,"info":{"output":1}
}
;Search.control.loadWordPairs(pairs);
