var pairs =
{
"validation":{"example":1}
,"example":{"shows":1}
,"shows":{"number":1}
,"number":{"configured":1}
,"configured":{"vcs":1}
,"vcs":{"status":1}
,"status":{"show":1}
,"show":{"mpls":1,"ldp":1}
,"mpls":{"vc-table":1}
,"vc-table":{"count":1}
,"count":{"-------------------------------num":1,"----------------------------------------------num":1}
,"-------------------------------num":{"pws":1}
,"pws":{"25000":1,"inactive":1,"-------------------------------#":1}
,"25000":{"active":1,"oam-only":1,"[up":1}
,"active":{"pws":1}
,"oam-only":{"pws":1}
,"inactive":{"pws":1}
,"-------------------------------#":{"show":1}
,"ldp":{"mpls-l2-circuit":1}
,"mpls-l2-circuit":{"count":1}
,"----------------------------------------------num":{"signaled":1}
,"signaled":{"pws":1}
,"[up":{"25000]":1}
,"25000]":{"----------------------------------------------":1}
}
;Search.control.loadWordPairs(pairs);
