var pairs =
{
"ipi_mpls_init_all_handles":{"function":1,"(struct":1}
,"function":{"creates":1,"ignored":1}
,"creates":{"netlink":1,"ftn":1}
,"netlink":{"socket":1}
,"socket":{"user-space":1,"return":1}
,"user-space":{"process":1}
,"process":{"communicate":1}
,"communicate":{"mpls":1}
,"mpls":{"forwarder":1,"handles":1}
,"forwarder":{"creates":1,"intercepts":1}
,"ftn":{"ilm":1}
,"ilm":{"tables":1}
,"tables":{"mpls":1}
,"intercepts":{"packets":1}
,"packets":{"types":1}
,"types":{"mpls":1}
,"handles":{"appropriately":1}
,"appropriately":{"subsequent":1}
,"subsequent":{"executions":1}
,"executions":{"function":1}
,"ignored":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ipi_mpls_init_all_handles":1}
,"(struct":{"lib_globals":1}
,"lib_globals":{"*zg":1}
,"*zg":{"u_char":1,"pointer":1}
,"u_char":{"protocol)":1}
,"protocol)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"*zg":1,"status":1}
,"pointer":{"lib":1}
,"lib":{"globals":1}
,"globals":{"protocol":1}
,"protocol":{"protocol":1,"owns":1}
,"owns":{"entries":1}
,"entries":{"ipi_proto_nsm":1}
,"ipi_proto_nsm":{"ipi_proto_ldp":1}
,"ipi_proto_ldp":{"ipi_proto_bgp":1}
,"ipi_proto_bgp":{"ipi_proto_rsvp":1}
,"ipi_proto_rsvp":{"output":1}
,"output":{"parameters":1}
,"status":{"call":1}
,"call":{"socket":1,"cannot":1}
,"return":{"value":1}
,"value":{"status":1}
,"cannot":{"send":1}
,"send":{"initial":1}
,"initial":{"request":1}
,"request":{"forwarder":1}
}
;Search.control.loadWordPairs(pairs);
