var pairs =
{
"cfm_send_ping2":{"function":1,"(struct":1}
,"function":{"called":1,"two":1,"succeeds":1,"fails":1}
,"called":{"ping":1}
,"ping":{"ethernet":1,"request":1}
,"ethernet":{"mac":1}
,"mac":{"command":1,"address":1,"mac":1}
,"command":{"send":1}
,"send":{"loopback":1}
,"loopback":{"message":1,"transmission":1,"reply":1,"mep":1,"already":1}
,"message":{"mac":1}
,"address":{"source":1,"allowed":1}
,"source":{"mep":1}
,"mep":{"function":1,"associated":1,"source_mep_id":1,"tlv_type":1,"found":1,"active":1,"null":1}
,"two":{"signatures":1}
,"signatures":{"identical":1}
,"identical":{"except":1}
,"except":{"first":1}
,"first":{"additional":1,"signature":1}
,"additional":{"parameters":1}
,"parameters":{"second":1,"bridge":1}
,"second":{"signature":1}
,"signature":{"zebos-xp":1,"syntax":1}
,"zebos-xp":{"built":1}
,"built":{"itu":1}
,"itu":{"y.1731":1}
,"y.1731":{"support":1}
,"support":{"otherwise":1,"cfm_api_err_bridge_not_found":1,"pointer":1}
,"otherwise":{"first":1}
,"syntax":{"include":1}
,"include":{"cfm_api.h":1}
,"cfm_api.h":{"s_int32_t":1,"struct":1}
,"s_int32_t":{"cfm_send_ping2":1}
,"(struct":{"onmd_bridge":1}
,"onmd_bridge":{"*bridge":1}
,"*bridge":{"u_char":1}
,"u_char":{"*md_name":1,"*mac":1}
,"*md_name":{"u_int8_t":1,"s_int8_t":1}
,"u_int8_t":{"level":1,"tlv_type":1,"tx_interval":1,"tx_lbm_count":1,"reply_timeout":1}
,"level":{"u_int16_t":1,"level":1,"vid":1}
,"u_int16_t":{"vid":1,"source_mep_id":1,"tlv_indicator":1,"tlv_indicator)":1}
,"vid":{"u_char":1,"vlan":1,"configured":1}
,"*mac":{"u_int16_t":1}
,"source_mep_id":{"u_int8_t":1,"source":1,"ambiguous":1}
,"tlv_type":{"u_int16_t":1,"tlv":1}
,"tlv_indicator":{"u_int8_t":1,"test":1,"invalid":1}
,"tx_interval":{"u_int8_t":1,"transmission":1,"cfm_api_err_none":1}
,"tx_lbm_count":{"u_int8_t":1,"time":1}
,"reply_timeout":{"struct":1,"time":1,"greater":1}
,"struct":{"cfm_lb":1,"return":1}
,"cfm_lb":{"**ret_lb)":1,"*cfm_send_ping2":1,"struct":1,"structure":1}
,"**ret_lb)":{"include":1}
,"*cfm_send_ping2":{"(struct":1}
,"s_int8_t":{"level":1}
,"tlv_indicator)":{"input":1}
,"input":{"parameters":1}
,"bridge":{"bridge":1,"ping":1,"exist":1}
,"request":{"executed":1}
,"executed":{"md_name":1}
,"md_name":{"name":1}
,"name":{"host":1}
,"host":{"mep":1}
,"associated":{"level":1}
,"vlan":{"<1-4094>":1}
,"<1-4094>":{"mac":1}
,"tlv":{"type":1}
,"type":{"tlv_indicator":1}
,"test":{"pattern":1}
,"pattern":{"values":1}
,"values":{"test_pattern_indicator":1}
,"test_pattern_indicator":{"enum":1}
,"enum":{"onmd\u002Fcfm\u002Fcfm_lb.h":1}
,"onmd\u002Fcfm\u002Fcfm_lb.h":{"test_tlv_pattern_1":1}
,"test_tlv_pattern_1":{"test_tlv_pattern_2":1}
,"test_tlv_pattern_2":{"test_tlv_pattern_3":1}
,"test_tlv_pattern_3":{"test_tlv_pattern_4":1}
,"test_tlv_pattern_4":{"tx_interval":1}
,"transmission":{"interval":1,"reply_timeout":1}
,"interval":{"tx_lbm_count":1}
,"time":{"loopback":1}
,"reply":{"ret_lb":1}
,"ret_lb":{"pointer":1}
,"pointer":{"cfm_lb":1}
,"return":{"value":1}
,"value":{"without":1}
,"without":{"itu":1}
,"cfm_api_err_bridge_not_found":{"bridge":1}
,"exist":{"list":1}
,"list":{"found":1}
,"found":{"cfm_api_err_mep_mcast_mac_not_allowed":1,"cfm_api_err_vid_not_configured_for_ma":1,"cfm_api_err_mep_not_found":1,"cfm_api_mep_not_active":1}
,"cfm_api_err_mep_mcast_mac_not_allowed":{"mac":1}
,"allowed":{"platform":1}
,"platform":{"cfm_api_err_md_not_found":1}
,"cfm_api_err_md_not_found":{"found":1}
,"cfm_api_err_vid_not_configured_for_ma":{"vid":1}
,"configured":{"cfm_api_err_ma_not_found":1}
,"cfm_api_err_ma_not_found":{"found":1}
,"cfm_api_err_mep_not_found":{"mep":1}
,"cfm_api_mep_not_active":{"mep":1}
,"active":{"cfm_api_err_lb_not_found":1}
,"cfm_api_err_lb_not_found":{"loopback":1}
,"null":{"cfm_api_lbi_already_active":1,"function":1}
,"cfm_api_lbi_already_active":{"loopback":1}
,"already":{"cfm_api_err_mep_ambiguous":1}
,"cfm_api_err_mep_ambiguous":{"source_mep_id":1}
,"ambiguous":{"cfm_api_err_invalid_tlv_indicator":1}
,"cfm_api_err_invalid_tlv_indicator":{"tlv_indicator":1}
,"invalid":{"cfm_api_err_invalid_reply_int":1}
,"cfm_api_err_invalid_reply_int":{"reply_timeout":1}
,"greater":{"tx_interval":1}
,"cfm_api_err_none":{"function":1}
,"succeeds":{"itu":1,"null":1}
,"structure":{"function":1}
}
;Search.control.loadWordPairs(pairs);
