var pairs =
{
"cfm_1dm_rx":{"structure":1,"{\u002F*back":1}
,"structure":{"onmd\u002Fcfm\u002Fcfm_dm.h":1}
,"onmd\u002Fcfm\u002Fcfm_dm.h":{"defines":1}
,"defines":{"delay":1}
,"delay":{"measurement":1}
,"measurement":{"(1dm)":1}
,"(1dm)":{"receive":1}
,"receive":{"frame":1}
,"frame":{"member":1}
,"member":{"description":1}
,"description":{"mep":1}
,"mep":{"back":1,"dm_rx_while":1,"*\u002Fstruct":1}
,"back":{"pointer":1}
,"pointer":{"mep":1}
,"dm_rx_while":{"thread":1}
,"thread":{"receiving":1,"*dm_rx_while":1}
,"receiving":{"1dm":1}
,"1dm":{"frames":1}
,"frames":{"given":1,"received":1}
,"given":{"duration":1}
,"duration":{"dm_rmep_list":1,"*\u002Fstruct":1}
,"dm_rmep_list":{"linked":1}
,"linked":{"list":1}
,"list":{"rmep":1,"*dm_rmep_list":1}
,"rmep":{"information":1}
,"information":{"1dm":1}
,"received":{"dynamically":1}
,"dynamically":{"kept":1}
,"kept":{"dm_active":1,"*\u002Fstruct":1}
,"dm_active":{"cli":1}
,"cli":{"blocking":1}
,"blocking":{"struct":1,"*\u002Fu_int8_t":1}
,"struct":{"cfm_1dm_rx":1}
,"{\u002F*back":{"pointer":1}
,"*\u002Fstruct":{"cfm_mep":1,"thread":1,"list":1}
,"cfm_mep":{"*mep":1}
,"*mep":{"\u002F*thread":1}
,"\u002F*thread":{"receiving":1}
,"*dm_rx_while":{"\u002F*this":1}
,"\u002F*this":{"linked":1}
,"*dm_rmep_list":{"\u002F*for":1}
,"\u002F*for":{"cli":1}
,"*\u002Fu_int8_t":{"dm_active":1}
}
;Search.control.loadWordPairs(pairs);
