var pairs =
{
"igmp":{"last-member-query-count":1,"layer-3":1,"proxy":1}
,"last-member-query-count":{"command":1,"<2-7>":1,"parameter":1}
,"command":{"last-member":1,"applies":1,"return":1,"syntax":1,"mode":1}
,"last-member":{"query-count":1}
,"query-count":{"value":1}
,"value":{"command":1,"interface":1,"default":1}
,"applies":{"interfaces":1}
,"interfaces":{"configured":1}
,"configured":{"igmp":1}
,"layer-3":{"multicast":1}
,"multicast":{"protocols":1}
,"protocols":{"igmp":1}
,"proxy":{"parameter":1}
,"parameter":{"command":1,"<2-7>":1}
,"return":{"default":1}
,"default":{"value":1,"default":1,"last":1}
,"interface":{"command":1,"mode":1,"(config-if)":1}
,"syntax":{"igmp":1}
,"<2-7>":{"igmp":1,"specify":1}
,"specify":{"last":1}
,"last":{"member":1}
,"member":{"query":1}
,"query":{"count":1}
,"count":{"value":1}
,"mode":{"interface":1,"example":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"(config-if)":{"igmp":1}
}
;Search.control.loadWordPairs(pairs);
