var pairs =
{
"area":{"types":1,"description":1,"central":1,"areas":1,"default":1,"routers":1,"containing":1}
,"types":{"summary":1,"ospf":1}
,"summary":{"table":1,"area":1}
,"table":{"1-2":1}
,"1-2":{"summarizes":1}
,"summarizes":{"types":1}
,"ospf":{"areas":1,"connect":1}
,"areas":{"area":1,"ospf":1}
,"description":{"lsa":1}
,"lsa":{"handling":1}
,"handling":{"backbone":1}
,"backbone":{"regular":1,"area":1}
,"regular":{"accepts":1}
,"accepts":{"intra-area":1,"inter-area":1,"external":1}
,"intra-area":{"inter-area":1,"routes":1}
,"inter-area":{"external":1,"intra-area":1}
,"external":{"routes":1,"systems":1}
,"routes":{"backbone":1,"default":1,"external":1,"type":1}
,"central":{"area":1}
,"connect":{"none":1}
,"none":{"stub":1}
,"stub":{"accepts":1,"area":1,"totally":1}
,"default":{"route":1}
,"route":{"accept":1,"injected":1,"totally":1,"send":1,"nssa":1,"type":1}
,"accept":{"routes":1}
,"systems":{"reach":1}
,"reach":{"outside":1}
,"outside":{"networks":1,"area":1}
,"networks":{"routers":1}
,"routers":{"area":1}
,"injected":{"abr":1}
,"abr":{"type":1,"nssa":1}
,"type":{"lsas":1,"nssa":1}
,"lsas":{"replaced":1,"originate":1}
,"replaced":{"default":1}
,"totally":{"stub":1}
,"send":{"traffic":1}
,"traffic":{"outside":1}
,"nssa":{"stub":1,"asbr":1,"abr":1,"totally":1}
,"containing":{"asbr":1}
,"asbr":{"accepts":1,"convert":1}
,"originate":{"nssa":1}
,"convert":{"type":1}
}
;Search.control.loadWordPairs(pairs);
