var pairs =
{
"spb_api_set_lsp_gen_interval":{"function":1,"(char":1}
,"function":{"sets":1,"implements":1,"succeeds":1}
,"sets":{"minimum":1}
,"minimum":{"interval":1}
,"interval":{"regenerating":1,"interval":1,"seconds":1,"outside":1}
,"regenerating":{"lsp":1}
,"lsp":{"function":1}
,"implements":{"isis-spb":1}
,"isis-spb":{"lsp-gen-interval":1}
,"lsp-gen-interval":{"command":1}
,"command":{"syntax":1}
,"syntax":{"include":1}
,"include":{"spbd\u002Fisis-spb\u002Fspb_isis_api.h":1}
,"spbd\u002Fisis-spb\u002Fspb_isis_api.h":{"int":1}
,"int":{"spb_api_set_lsp_gen_interval":1,"level":1}
,"(char":{"*bridge_name":1}
,"*bridge_name":{"char":1}
,"char":{"*tag":1}
,"*tag":{"int":1}
,"level":{"u_char":1,"instance":1,"constants":1,"istype_l2":1,"interval":1,"supported":1}
,"u_char":{"interval)":1}
,"interval)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bridge_name":1,"none":1}
,"bridge_name":{"bridge":1,"tag":1}
,"bridge":{"name":1}
,"name":{"tag":1}
,"tag":{"instance":1,"level":1,"null":1,"exist":1}
,"instance":{"area":1,"level":1,"configuration":1,"tag":1}
,"area":{"tag":1}
,"constants":{"spbd\u002Fisis-spb\u002Fspb_isis_types.h":1}
,"spbd\u002Fisis-spb\u002Fspb_isis_types.h":{"istype_l1":1}
,"istype_l1":{"level":1}
,"istype_l2":{"level":1}
,"seconds":{"<1-120>":1}
,"<1-120>":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"spb_api_err_arg_null":1}
,"spb_api_err_arg_null":{"bridge_name":1}
,"null":{"spb_isis_api_set_error":1,"port":1,"spb_api_err_config_update":1,"spb_api_err_isis_instance_not_found":1}
,"spb_isis_api_set_error":{"isis":1}
,"isis":{"master":1}
,"master":{"null":1}
,"port":{"instance":1}
,"configuration":{"null":1,"exists":1}
,"spb_api_err_config_update":{"isis":1}
,"exists":{"spb_api_err_isis_master_not_found":1}
,"spb_api_err_isis_master_not_found":{"isis":1}
,"spb_api_err_isis_instance_not_found":{"given":1}
,"given":{"instance":1,"interval":1,"level":1}
,"exist":{"spb_api_err_invalid_value":1}
,"spb_api_err_invalid_value":{"given":1}
,"outside":{"range":1}
,"range":{"(1-120)":1}
,"(1-120)":{"spb_isis_set_err_invalid_is_type":1}
,"spb_isis_set_err_invalid_is_type":{"given":1}
,"supported":{"spb_isis_api_set_success":1}
,"spb_isis_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
