var pairs =
{
"bridge":{"max-age":1,"value":1,"root":1,"enforce":1,"<1-32>":1,"group":1,"<6-40>":1,"maximum":1}
,"max-age":{"command":1,"6-40":1,"forward-delay":1,"<6-40>":1,"parameters":1,"(config)":1}
,"command":{"maximum":1,"restore":1,"syntax":1,"mode":1}
,"maximum":{"age":1,"time":1}
,"age":{"bridge":1,"maximum":1,"greater":1,"parameter":1,"seconds":1}
,"value":{"used":1,"maximum":1,"hello":1,"forward":1,"sufficiently":1,"bridge":1}
,"used":{"instances":1}
,"instances":{"maximum":1}
,"time":{"seconds":1,"plus":1}
,"seconds":{"(if":1,"configure":1,"listen":1,"command":1}
,"(if":{"bridge":1}
,"root":{"bridge)":1,"propagated":1,"bridge":1}
,"bridge)":{"message":1}
,"message":{"considered":1}
,"considered":{"valid":1}
,"valid":{"prevents":1}
,"prevents":{"frames":1}
,"frames":{"looping":1}
,"looping":{"indefinitely":1}
,"indefinitely":{"value":1}
,"greater":{"twice":1}
,"twice":{"value":1}
,"hello":{"time":1}
,"plus":{"less":1}
,"less":{"twice":1}
,"forward":{"delay":1}
,"delay":{"minus":1}
,"minus":{"allowable":1}
,"allowable":{"range":1}
,"range":{"max-age":1}
,"6-40":{"seconds":1}
,"configure":{"value":1,"mode":1,"terminal":1}
,"sufficiently":{"high":1}
,"high":{"frame":1}
,"frame":{"generated":1}
,"generated":{"root":1}
,"propagated":{"leaf":1}
,"leaf":{"nodes":1}
,"nodes":{"without":1}
,"without":{"exceeding":1}
,"exceeding":{"maximum":1}
,"parameter":{"command":1}
,"restore":{"default":1}
,"default":{"value":1,"default":1}
,"enforce":{"following":1}
,"following":{"relationships":1}
,"relationships":{"hello-time":1}
,"hello-time":{"max-age":1}
,"forward-delay":{"(bridge_forward_delay":1}
,"(bridge_forward_delay":{"1.0":1}
,"1.0":{"seconds)":1}
,"seconds)":{">=bridge_max_age":1,"command":1}
,">=bridge_max_age":{"bridge_max_age":1}
,"bridge_max_age":{">=2":1}
,">=2":{"(bridge_hello_time":1}
,"(bridge_hello_time":{"1.0":1}
,"syntax":{"bridge":1}
,"<1-32>":{"max-age":1,"specify":1}
,"<6-40>":{"bridge":1,"specify":1,"default":1}
,"parameters":{"<1-32>":1}
,"specify":{"bridge":1,"maximum":1}
,"group":{"<6-40>":1}
,"listen":{"root":1}
,"mode":{"configure":1,"examples":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"bridge":1}
}
;Search.control.loadWordPairs(pairs);
