var pairs =
{
"trill_get_rbridgebase_unimultipath_enable":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"status":1}
,"status":{"unicast":1}
,"unicast":{"trill":1}
,"trill":{"multipathing":1,"identifier":1,"instance":1}
,"multipathing":{"syntax":1,"return":1}
,"syntax":{"int":1}
,"int":{"trill_get_rbridgebase_unimultipath_enable":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"integer":1}
,"u_int32_t":{"instance":1,"*ret)":1}
,"instance":{"u_int32_t":1,"integer":1,"output":1,"trill_api_get_error":1,"found":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"ret":1}
,"integer":{"contains":1}
,"contains":{"trill":1}
,"identifier":{"instance":1}
,"output":{"parameters":1}
,"ret":{"pointer":1}
,"pointer":{"status":1}
,"return":{"value":1}
,"value":{"trill_api_get_success":1}
,"trill_api_get_success":{"valid":1}
,"valid":{"instance":1}
,"trill_api_get_error":{"valid":1}
}
;Search.control.loadWordPairs(pairs);
