var pairs =
{
"port":{"gvrp":1,"ports":1}
,"gvrp":{"command":1,"port":1,"enable":1,"disable":1,"switch":1}
,"command":{"enable":1,"syntax":1,"mode":1}
,"enable":{"disable":1,"(if_name":1,"enables":1,"eth0":1}
,"disable":{"gvrp":1,"(if_name":1,"disables":1}
,"ports":{"bridge":1,"added":1}
,"bridge":{"command":1,"if_name":1}
,"syntax":{"port":1}
,"(if_name":{"all)":1}
,"all)":{"port":1,"parameters":1}
,"parameters":{"enable":1}
,"enables":{"gvrp":1}
,"switch":{"disable":1,"ports":1}
,"disables":{"gvrp":1}
,"added":{"recently":1}
,"recently":{"configured":1}
,"configured":{"bridge":1}
,"if_name":{"specify":1}
,"specify":{"name":1}
,"name":{"interface":1}
,"interface":{"command":1}
,"mode":{"configure":1,"examples":1}
,"configure":{"mode":1,"terminal":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"port":1}
,"eth0":{"configure":1}
}
;Search.control.loadWordPairs(pairs);
