var pairs =
{
"neighbor":{"allowas-in":1,"(a.b.c.d":1,"address":1,"peer-group":1,"remote-as":1,"10.10.0.3":1,"10.10.0.1":1,"3ffe:15:15:15:15":1}
,"allowas-in":{"command":1,"neighbor":1,"<1-10>":1,"parameters":1,"configure":1}
,"command":{"advertise":1,"scenario":1,"configure":1,"reset":1,"syntax":1,"command":1,"applies":1,"mode":1}
,"advertise":{"prefixes":1}
,"prefixes":{"(routes)":1,"autonomous":1,"arrive":1,"router":1,"dropped":1,"side":1,"containing":1,"vrfs":1,"numbers":1}
,"(routes)":{"even":1}
,"even":{"source":1}
,"source":{"prefixes":1}
,"autonomous":{"system":1}
,"system":{"(as)":1,"number":1}
,"(as)":{"number":1}
,"number":{"command":1,"connected":1,"default":1,"times":1,"advertised":1,"hub":1}
,"scenario":{"two":1}
,"two":{"routers":1,"vrfs":1}
,"routers":{"different":1,"advertises":1,"vrf":1,"hub":1}
,"different":{"locations":1}
,"locations":{"autonomous":1}
,"connected":{"via":1}
,"via":{"isp":1}
,"isp":{"once":1,"tagged":1,"passes":1}
,"once":{"prefixes":1}
,"arrive":{"branch":1}
,"branch":{"isp":1}
,"tagged":{"customer\u2019s":1}
,"customer\u2019s":{"number":1}
,"default":{"isp":1,"command":1}
,"passes":{"prefixes":1}
,"router":{"prefixes":1,"uses":1,"advertises":1,"receive":1,"mode":1,"bgp":1}
,"dropped":{"router":1}
,"uses":{"number":1}
,"side":{"control":1}
,"control":{"number":1}
,"times":{"number":1,"allow":1}
,"advertised":{"specifying":1}
,"specifying":{"number":1}
,"hub":{"spoke":1}
,"spoke":{"configuration":1}
,"configuration":{"vpn":1,"parameter":1}
,"vpn":{"(provider":1}
,"(provider":{"edge)":1}
,"edge)":{"router":1}
,"advertises":{"prefixes":1,"neighboring":1,"routers":1}
,"containing":{"duplicate":1}
,"duplicate":{"numbers":1}
,"numbers":{"command":1,"routers":1,"(customer":1}
,"configure":{"two":1,"terminal":1}
,"vrfs":{"router":1,"receives":1}
,"receive":{"advertise":1}
,"receives":{"prefixes":1}
,"neighboring":{"routers":1}
,"vrf":{"receives":1,"vrf_a":1}
,"(customer":{"edge)":1}
,"parameter":{"command":1,"used":1}
,"reset":{"default":1}
,"syntax":{"neighbor":1}
,"(a.b.c.d":{"x:x":1}
,"x:x":{":x:x":1}
,":x:x":{"word)":1,"ipv6":1}
,"word)":{"allowas-in":1}
,"<1-10>":{"neighbor":1,"number":1}
,"parameters":{"a.b.c.d":1}
,"a.b.c.d":{"ipv4":1}
,"ipv4":{"neighbor":1,"vrf":1}
,"address":{"x:x":1,"word":1,"family":1}
,"ipv6":{"neighbor":1,"vrf":1}
,"word":{"name":1}
,"name":{"peer":1}
,"peer":{"group":1,"groups":1}
,"group":{"information":1,"<1-10>":1}
,"information":{"create":1}
,"create":{"peer":1}
,"groups":{"refer":1}
,"refer":{"neighbor":1}
,"peer-group":{"neighbor":1}
,"remote-as":{"commands":1}
,"commands":{"parameter":1}
,"used":{"command":1}
,"applies":{"peers":1}
,"peers":{"specified":1}
,"specified":{"group":1}
,"allow":{"advertisement":1}
,"advertisement":{"number":1}
,"mode":{"router":1,"address":1,"example":1}
,"family":{"mode":1}
,"example":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"bgp":{"(config-router)":1,"7657":1}
,"(config-router)":{"neighbor":1,"address-family":1}
,"10.10.0.3":{"allowas-in":1}
,"7657":{"(config-router)":1}
,"address-family":{"ipv4":1,"ipv6":1}
,"vrf_a":{"(config-router-af)":1}
,"(config-router-af)":{"neighbor":1}
,"10.10.0.1":{"allowas-in":1}
,"3ffe:15:15:15:15":{"allowas-in":1}
}
;Search.control.loadWordPairs(pairs);
