var pairs =
{
"g8031":{"configure":1}
,"configure":{"switching":1,"mode":1,"terminal":1}
,"switching":{"command":1,"mode":1,"(eps)":1,"eps-id":1}
,"command":{"enter":1,"syntax":1,"mode":1}
,"enter":{"g8031":1}
,"mode":{"ethernet":1,"configure":1,"examples":1}
,"ethernet":{"protection":1}
,"protection":{"switching":1}
,"(eps)":{"link":1}
,"link":{"provider":1,"eps-id":1,"<1-4094>":1}
,"provider":{"backbone":1}
,"backbone":{"bridging":1,"g8031":1,"backbone":1,"bridge":1,"(g8031-config-switching)":1}
,"bridging":{"supported":1}
,"supported":{"zebic":1}
,"zebic":{"releases":1}
,"releases":{"command":1}
,"syntax":{"g8031":1}
,"eps-id":{"eps_id":1,"eps":1,"bridge":1}
,"eps_id":{"bridge":1}
,"bridge":{"<1-32>":1,"backbone":1,"(<1-32>":1,"bridge":1,"command":1,"(g8031-config-switching)":1}
,"<1-32>":{"g8031":1,"bridge":1}
,"(<1-32>":{"backbone)":1}
,"backbone)":{"parameters":1}
,"parameters":{"eps-id":1}
,"eps":{"link":1}
,"<1-4094>":{"bridge":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"g8031":1}
,"(g8031-config-switching)":{"(config)":1}
}
;Search.control.loadWordPairs(pairs);
