var pairs =
{
"trill_af_vlan_nsm_add":{"function":1,"(struct":1}
,"function":{"sends":1}
,"sends":{"designated":1}
,"designated":{"vlan":1}
,"vlan":{"information":1}
,"information":{"nsm":1}
,"nsm":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"trill_af_vlan_nsm_add":1}
,"(struct":{"trill_if_level":1}
,"trill_if_level":{"*ifl)":1}
,"*ifl)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"*ifl":1,"none":1}
,"*ifl":{"specifies":1}
,"specifies":{"pointer":1}
,"pointer":{"parent":1}
,"parent":{"interface":1}
,"interface":{"level":1}
,"level":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"trill_api_set_success":1}
,"trill_api_set_success":{"trill_api_set_err_no_nsm_cilent":1}
}
;Search.control.loadWordPairs(pairs);
