var pairs =
{
"isis_restart_level_timer_unset":{"call":1,"(u_int32_t":1}
,"call":{"implements":1,"successful":1}
,"implements":{"parameter":1}
,"parameter":{"restart-timer":1}
,"restart-timer":{"command":1}
,"command":{"reset":1}
,"reset":{"maximum":1}
,"maximum":{"timer":1}
,"timer":{"wait":1}
,"wait":{"lsp":1}
,"lsp":{"database":1}
,"database":{"synchronization":1}
,"synchronization":{"default":1}
,"default":{"syntax":1,"value":1}
,"syntax":{"int":1}
,"int":{"isis_restart_level_timer_unset":1,"level)":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1,"tag":1}
,"char":{"*tag":1}
,"*tag":{"int":1}
,"level)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"value":{"non-vr":1,"isis_api_set_err_instance_not_exist":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"tag":{"area":1,"level":1,"exist":1}
,"area":{"tag":1}
,"level":{"is-is":1,"output":1,"invalid":1}
,"is-is":{"level":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"isis_api_set_err_instance_not_exist":{"given":1}
,"given":{"area":1,"is-is":1}
,"exist":{"isis_api_set_err_invalid_is_type":1,"isis_api_set_success":1}
,"isis_api_set_err_invalid_is_type":{"given":1}
,"invalid":{"isis_api_set_err_vr_not_exist":1}
,"isis_api_set_err_vr_not_exist":{"exist":1}
,"isis_api_set_success":{"call":1}
}
;Search.control.loadWordPairs(pairs);
