var pairs =
{
"show":{"nsm":1}
,"nsm":{"client":1,"clients":1}
,"client":{"command":1,"information":1,"parameters":1,"nsm":1,"imi":1,"onmd":1}
,"command":{"display":1,"syntax":1,"mode":1,"displays":1}
,"display":{"nsm":1}
,"information":{"command":1}
,"syntax":{"show":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"privileged":1,"example":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"example":{"command":1}
,"displays":{"details":1}
,"details":{"currently":1}
,"currently":{"connected":1}
,"connected":{"nsm":1}
,"clients":{"including":1}
,"including":{"services":1}
,"services":{"requested":1}
,"requested":{"protocols":1}
,"protocols":{"statistics":1}
,"statistics":{"connection":1}
,"connection":{"time":1}
,"time":{"show":1,"thu":1}
,"imi":{"socket":1}
,"socket":{"service":1}
,"service":{"interface":1,"router":1,"vrf":1,"messsage":1,"request":1,"bridge":1,"vlan":1}
,"interface":{"service":1}
,"router":{"service":1}
,"vrf":{"service":1}
,"messsage":{"received":1}
,"received":{"sent":1}
,"sent":{"connection":1}
,"thu":{"jul":1}
,"jul":{"11:03:12":1,"11:03:15":1}
,"11:03:12":{"2010":1}
,"2010":{"last":1}
,"last":{"message":1}
,"message":{"read":1,"write":1}
,"read":{"service":1,"oam":1}
,"request":{"last":1}
,"write":{"link":1}
,"link":{"nsm":1}
,"onmd":{"socket":1}
,"bridge":{"service":1}
,"vlan":{"service":1}
,"11:03:15":{"2010":1}
,"oam":{"lldp":1}
,"lldp":{"msg":1}
,"msg":{"last":1}
}
;Search.control.loadWordPairs(pairs);
