var pairs =
{
"bidirectional":{"forwarding":1}
,"forwarding":{"commands":1}
,"commands":{"chapter":1,"used":1,"bfd":1}
,"chapter":{"includes":1}
,"includes":{"commands":1,"following":1}
,"used":{"configure":1}
,"configure":{"manage":1}
,"manage":{"bfd":1}
,"bfd":{"base":1,"auth":1,"disable":1,"echo":1,"gtsm":1,"interval":1,"multihop-peer":1,"notification":1,"session":1,"slow-timer":1,"key":1,"show":1,"interface":1,"snmp":1}
,"base":{"module":1}
,"module":{"network":1}
,"network":{"includes":1}
,"following":{"commands":1}
,"auth":{"type":1}
,"type":{"bfd":1}
,"disable":{"bfd":1}
,"echo":{"bfd":1,"interval":1}
,"interval":{"bfd":1}
,"gtsm":{"bfd":1,"ttl":1}
,"ttl":{"bfd":1}
,"multihop-peer":{"bfd":1,"a.b.c.d":1,"x:x":1}
,"a.b.c.d":{"bfd":1,"show":1}
,"x:x":{":x:x":1}
,":x:x":{"bfd":1}
,"notification":{"bfd":1}
,"session":{"bfd":1,"show":1,"a.b.c.d":1,"ipv6":1}
,"slow-timer":{"debug":1}
,"debug":{"bfd":1}
,"key":{"key":1,"chain":1}
,"chain":{"send-lifetime":1}
,"send-lifetime":{"show":1}
,"show":{"bfd":1,"debugging":1}
,"interface":{"show":1}
,"ipv6":{"show":1}
,"debugging":{"bfd":1}
,"snmp":{"restart":1}
,"restart":{"bfd":1}
}
;Search.control.loadWordPairs(pairs);
