var pairs =
{
"switchport":{"beb":1}
,"beb":{"provider-network":1}
,"provider-network":{"command":1,"bvlan":1}
,"command":{"sets":1,"syntax":1,"mode":1}
,"sets":{"layer":1}
,"layer":{"interface":1}
,"interface":{"provider":1,"mode":1,"eth0":1}
,"provider":{"network":1}
,"network":{"port":1}
,"port":{"(pnp)":1,"associate":1,"add":1,"<2-4094>":1}
,"(pnp)":{"per":1}
,"per":{"802.1ah":1}
,"802.1ah":{"standard":1}
,"standard":{"command":1}
,"syntax":{"switchport":1}
,"bvlan":{"(none":1,"identifies":1,"add":1}
,"(none":{"((add":1}
,"((add":{"remove)":1}
,"remove)":{"<2-4094>))":1}
,"<2-4094>))":{"parameters":1}
,"parameters":{"bvlan":1}
,"identifies":{"bvlans":1}
,"bvlans":{"none":1}
,"none":{"remove":1}
,"remove":{"vlan":1,"remove":1}
,"vlan":{"associations":1,"pnp":1}
,"associations":{"pnp":1}
,"pnp":{"port":1}
,"associate":{"vlans":1}
,"vlans":{"pnp":1}
,"add":{"add":1,"vlan":1}
,"<2-4094>":{"vid":1}
,"vid":{"b-vlan":1}
,"b-vlan":{"added":1,"command":1}
,"added":{"remove":1}
,"mode":{"interface":1,"examples":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"switchport":1}
}
;Search.control.loadWordPairs(pairs);
