var pairs =
{
"contents":{"document":1}
,"document":{"contains":1}
,"contains":{"chapters":1}
,"chapters":{"appendices":1}
,"appendices":{"chapter":1}
,"chapter":{"introduction":1,"data":1,"restart":1,"is-is":1,"overload":1,"passive":1,"vlog":1,"administrative":1}
,"introduction":{"chapter":1}
,"data":{"structures":1}
,"structures":{"databases":1}
,"databases":{"chapter":1}
,"restart":{"signaling":1}
,"signaling":{"chapter":1}
,"is-is":{"traffic":1,"command":1,"snmp":1}
,"traffic":{"engineering":1}
,"engineering":{"chapter":1}
,"overload":{"bit":1}
,"bit":{"chapter":1}
,"passive":{"interface":1}
,"interface":{"chapter":1}
,"vlog":{"support":1}
,"support":{"chapter":1}
,"administrative":{"distance":1}
,"distance":{"chapter":1}
,"command":{"api":1}
,"api":{"chapter":1}
,"snmp":{"api":1,"traps":1}
}
;Search.control.loadWordPairs(pairs);
