var pairs =
{
"nsm_get_rcvaddress_type":{"function":1,"(struct":1}
,"function":{"checks":1}
,"checks":{"whether":1}
,"whether":{"mac":1}
,"mac":{"address":1}
,"address":{"static":1}
,"static":{"dynamic":1}
,"dynamic":{"syntax":1}
,"syntax":{"int":1}
,"int":{"nsm_get_rcvaddress_type":1,"*type)":1}
,"(struct":{"rcvaddr_index":1}
,"rcvaddr_index":{"*rcvaddr":1,"structure":1}
,"*rcvaddr":{"int":1}
,"*type)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"rcvaddr":1,"type":1}
,"rcvaddr":{"pointer":1}
,"pointer":{"rcvaddr_index":1}
,"structure":{"output":1}
,"output":{"parameters":1}
,"type":{"rcvaddress":1,"return":1}
,"rcvaddress":{"type":1}
,"return":{"values":1}
,"values":{"always":1}
,"always":{"nsm_api_get_success":1}
}
;Search.control.loadWordPairs(pairs);
