var pairs =
{
"ethernet":{"lmi":1}
,"lmi":{"async-msg-interval":1}
,"async-msg-interval":{"command":1,"<1-3>":1,"parameters":1}
,"command":{"configure":1,"syntax":1,"mode":1}
,"configure":{"minimum":1,"terminal":1}
,"minimum":{"interval":1}
,"interval":{"asynchronous":1,"value":1}
,"asynchronous":{"message":1,"messages":1}
,"message":{"timer":1}
,"timer":{"used":1}
,"used":{"elmi":1}
,"elmi":{"parameter":1,"disabled":1}
,"parameter":{"values":1}
,"values":{"timers":1,"command":1}
,"timers":{"default":1}
,"default":{"values":1,"elmi":1,"interface":1}
,"syntax":{"ethernet":1}
,"<1-3>":{"ethernet":1,"minimum":1}
,"parameters":{"<1-3>":1}
,"value":{"asynchronous":1}
,"messages":{"command":1}
,"mode":{"interface":1,"default":1}
,"interface":{"mode":1,"examples":1,"eth1":1}
,"disabled":{"default":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth1":{"(config-if)":1}
,"(config-if)":{"ethernet":1}
}
;Search.control.loadWordPairs(pairs);
