var pairs =
{
"pim4_api_vif_bidir_nbr_filter_set":{"function":1,"(u_int32_t":1}
,"function":{"configures":1,"executes":1}
,"configures":{"pim":1}
,"pim":{"vif":1,"vrf":1}
,"vif":{"bidirectional":1,"found":1}
,"bidirectional":{"neighbor":1}
,"neighbor":{"filter":1}
,"filter":{"access-list":1,"name":1,"output":1}
,"access-list":{"name":1}
,"name":{"syntax":1,"interface":1,"neighbor":1}
,"syntax":{"int":1}
,"int":{"pim4_api_vif_bidir_nbr_filter_set":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1}
,"char":{"*ifname":1,"*filter)":1}
,"*ifname":{"char":1}
,"*filter)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"ifname":1}
,"ifname":{"name":1}
,"interface":{"filter":1,"found":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"pim_api_set_err_wrong_value":1}
,"pim_api_set_err_wrong_value":{"invalid":1}
,"invalid":{"value":1}
,"value":{"given":1}
,"given":{"pim_api_set_err_wrong_vrf":1}
,"pim_api_set_err_wrong_vrf":{"pim":1}
,"vrf":{"interface":1}
,"found":{"pim_api_set_error":1,"pim_api_set_err_vif_not_exist":1,"pim_api_success":1}
,"pim_api_set_error":{"bsr":1}
,"bsr":{"information":1}
,"information":{"found":1}
,"pim_api_set_err_vif_not_exist":{"vif":1}
,"pim_api_success":{"function":1}
,"executes":{"properly":1}
}
;Search.control.loadWordPairs(pairs);
