var pairs =
{
"clear":{"ldp":1}
,"ldp":{"statistics":1,"advertise-labels":1,"neighbors":1}
,"statistics":{"advertise-labels":1,"command":1}
,"advertise-labels":{"command":1,"statistics":1,"clear":1,"prefix_acl":1,"specify":1}
,"command":{"clear":1,"clears":1,"syntax":1,"mode":1}
,"clears":{"count":1}
,"count":{"per":1}
,"per":{"operation":1}
,"operation":{"filtered":1}
,"filtered":{"advertisement":1}
,"advertisement":{"list":1}
,"list":{"command":1,"advertise-labels":1}
,"syntax":{"clear":1}
,"prefix_acl":{"clear":1,"peer_acl":1,"specify":1}
,"peer_acl":{"parameters":1,"specify":1}
,"parameters":{"advertise-labels":1}
,"specify":{"access":1,"permitted":1,"destinations":1,"given":1,"ldp":1}
,"access":{"list":1}
,"permitted":{"destinations":1}
,"destinations":{"prefix_acl":1,"labels":1}
,"labels":{"advertised":1}
,"advertised":{"specify":1}
,"given":{"neighbor":1}
,"neighbor":{"peer_acl":1}
,"neighbors":{"receive":1}
,"receive":{"advertisements":1}
,"advertisements":{"command":1}
,"mode":{"privileged":1,"example":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"example":{"clear":1}
}
;Search.control.loadWordPairs(pairs);
