var pairs =
{
"rip":{"adjacency":1,"enabled":1,"particular":1,"interface":1,"receive":1,"packets":1,"passive":1,"advertisements":1,"event":1,"packet":1,"send":1}
,"adjacency":{"show":1,"configure":1}
,"show":{"interface":1,"rip":1,"run":1}
,"interface":{"brief":1,"administratively":1,"eth0":1,"command":1,"confirm":1,"enable":1,"network":1,"sure":1,"show":1,"fxp0":1,"disabled":1,"address":1,"configured":1,"using":1,"either":1,"eth1":1}
,"brief":{"command":1}
,"command":{"sure":1,"shutdown":1,"show":1,"router":1,"passive":1}
,"sure":{"interface":1,"rip":1}
,"administratively":{"shutdown":1}
,"shutdown":{"remove":1,"command":1,"configured":1,"show":1}
,"remove":{"configuration":1,"firewall":1}
,"configuration":{"using":1,"setting":1}
,"using":{"shutdown":1,"show":1,"command":1,"ipchains":1}
,"configured":{"configure":1,"passive":1,"ripv1":1}
,"configure":{"terminal":1,"router":1}
,"terminal":{"(config)":1,"type":1,"monitor":1}
,"(config)":{"interface":1,"debug":1}
,"eth0":{"(config-if)":1,"interface":1,"sure":1}
,"(config-if)":{"shutdown":1}
,"confirm":{"rip":1}
,"enabled":{"interface":1,"poisoned":1}
,"enable":{"rip":1}
,"particular":{"interface":1}
,"network":{"command":1}
,"fxp0":{"line":1}
,"line":{"protocol":1}
,"protocol":{"routing":1,"rip":1}
,"routing":{"protocol":1}
,"receive":{"rip":1,"version":1}
,"packets":{"send":1,"passive":1}
,"send":{"rip":1,"version":1}
,"passive":{"interface":1,"(as":1}
,"disabled":{"split":1}
,"split":{"horizon":1}
,"horizon":{"enabled":1}
,"poisoned":{"reversed":1}
,"reversed":{"interface":1}
,"address":{"10.15.0.60\u002F16":1}
,"10.15.0.60\u002F16":{"sure":1}
,"run":{"command":1}
,"router":{"rip":1,"configured":1,"ripv2":1,"running":1}
,"(as":{"shown":1}
,"shown":{"above)":1}
,"above)":{"remove":1}
,"setting":{"using":1}
,"advertisements":{"sent":1,"turn":1}
,"sent":{"received":1}
,"received":{"interface":1}
,"either":{"packet":1}
,"packet":{"sniffer":1,"detail":1,"remove":1}
,"sniffer":{"(such":1}
,"(such":{"ethereal":1}
,"ethereal":{"tcp":1}
,"tcp":{"dump)":1}
,"dump)":{"zebos-xp":1}
,"zebos-xp":{"log":1,"logging":1}
,"log":{"messages":1}
,"messages":{"verify":1}
,"verify":{"rip":1,"whether":1}
,"turn":{"zebos-xp":1}
,"logging":{"type":1,"message":1}
,"type":{"configure":1,"terminal":1}
,"debug":{"rip":1}
,"event":{"(config)":1}
,"detail":{"display":1}
,"display":{"logging":1,"existing":1}
,"message":{"terminal":1}
,"monitor":{"router":1}
,"ripv1":{"router":1}
,"ripv2":{"results":1,"follows":1}
,"results":{"rip":1}
,"running":{"ripv2":1}
,"follows":{"interface":1}
,"eth1":{"rip":1}
,"version":{"1-compatible":1,"verify":1}
,"1-compatible":{"rip":1}
,"whether":{"firewall":1}
,"firewall":{"present":1,"blocks":1,"display":1,"configurations":1}
,"present":{"firewall":1}
,"blocks":{"udp":1}
,"udp":{"packet":1}
,"existing":{"firewall":1}
,"configurations":{"linux":1,"using":1}
,"linux":{"ipchains":1}
,"ipchains":{"flush":1}
,"flush":{"existing":1}
}
;Search.control.loadWordPairs(pairs);
