var pairs =
{
"ethernet":{"virtual":1,"environment":1,"services":1}
,"virtual":{"connection":1}
,"connection":{"ethernet":1,"(evc)":1}
,"(evc)":{"logical":1}
,"logical":{"relationship":1}
,"relationship":{"user":1,"uni-and":1}
,"user":{"network":1}
,"network":{"interfaces":1}
,"interfaces":{"provider-based":1}
,"provider-based":{"ethernet":1}
,"environment":{"establishes":1}
,"establishes":{"communication":1}
,"communication":{"relationship":1}
,"uni-and":{"uni-n":1}
,"uni-n":{"devices":1}
,"devices":{"three":1}
,"three":{"types":1}
,"types":{"metro":1}
,"metro":{"ethernet":1}
,"services":{"provided":1}
,"provided":{"evc":1}
,"evc":{"point-to-point":1}
,"point-to-point":{"multipoint-to-multipoint":1}
,"multipoint-to-multipoint":{"rooted-multipoint":1}
}
;Search.control.loadWordPairs(pairs);
