var pairs =
{
"spb":{"mst":1,"mstp":1,"connect":1,"calculates":1}
,"mst":{"configuration":1}
,"configuration":{"chapter":1}
,"chapter":{"shows":1,"addition":1,"shortest":1}
,"shows":{"configure":1}
,"configure":{"mstp":1}
,"mstp":{"(multiple":1,"spb":1,"calculates":1}
,"(multiple":{"spanning":1}
,"spanning":{"tree":1,"tree)":1}
,"tree":{"protocol)":1,"(cist)":1,"(ist)":1,"instances":1}
,"protocol)":{"work":1}
,"work":{"spb":1}
,"connect":{"bridges":1}
,"bridges":{"single":1}
,"single":{"common":1}
,"common":{"internal":1}
,"internal":{"spanning":1}
,"(cist)":{"supports":1}
,"supports":{"automatic":1}
,"automatic":{"determination":1}
,"determination":{"region":1}
,"region":{"choosing":1,"mstp":1,"ensures":1,"spb":1,"perform":1}
,"choosing":{"maximum":1}
,"maximum":{"possible":1}
,"possible":{"extent":1}
,"extent":{"connectivity":1}
,"connectivity":{"calculated":1}
,"calculated":{"cist":1}
,"cist":{"provides":1}
,"provides":{"cst":1}
,"cst":{"(common":1}
,"(common":{"spanning":1}
,"tree)":{"interconnecting":1}
,"interconnecting":{"regions":1}
,"regions":{"internal":1}
,"(ist)":{"within":1}
,"within":{"region":1}
,"calculates":{"number":1,"symmetric":1}
,"number":{"independent":1}
,"independent":{"multiple":1}
,"multiple":{"spanning":1}
,"instances":{"(mstis)":1}
,"(mstis)":{"within":1}
,"ensures":{"frames":1}
,"frames":{"given":1}
,"given":{"vlan":1}
,"vlan":{"identifier":1,"assigned":1}
,"identifier":{"(vid)":1}
,"(vid)":{"assigned":1}
,"assigned":{"mstis":1,"symmetric":1}
,"mstis":{"ist":1}
,"ist":{"within":1}
,"symmetric":{"sets":1,"spt":1}
,"sets":{"shortest":1}
,"shortest":{"path":1}
,"path":{"trees":1,"bridging":1}
,"trees":{"(spts)":1}
,"(spts)":{"rooted":1}
,"rooted":{"bridge":1}
,"bridge":{"within":1}
,"spt":{"within":1}
,"perform":{"procedures":1}
,"procedures":{"chapter":1}
,"addition":{"chapter":1}
,"bridging":{"-mac":1}
,"-mac":{"configuration":1}
}
;Search.control.loadWordPairs(pairs);
