var pairs =
{
"port":{"mvrp":1,"ports":1}
,"mvrp":{"command":1,"selected":1,"enable":1,"disable":1,"switch":1,"interfaces":1}
,"command":{"enable":1,"syntax":1,"mode":1,"structure":1}
,"enable":{"disable":1,"(if_name":1,"enables":1,"mvrp":1,"eth1":1}
,"disable":{"mvrp":1,"(if_name":1,"disables":1,"eth1":1}
,"selected":{"port":1,"interface":1}
,"ports":{"bridge":1,"added":1}
,"bridge":{"command":1,"if_name":1}
,"syntax":{"port":1}
,"(if_name":{"all)":1}
,"all)":{"port":1,"parameters":1}
,"parameters":{"enable":1}
,"enables":{"mvrp":1}
,"switch":{"disable":1,"ports":1}
,"disables":{"mvrp":1}
,"added":{"recently":1}
,"recently":{"configured":1}
,"configured":{"bridge":1}
,"if_name":{"identity":1}
,"identity":{"interface":1}
,"interface":{"default":1,"command":1,"bridge":1}
,"default":{"setting":1,"command":1}
,"setting":{"disabled":1}
,"disabled":{"default":1}
,"mode":{"configure":1,"examples":1}
,"configure":{"mode":1,"terminal":1}
,"examples":{"enable":1}
,"structure":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"port":1}
,"eth1":{"enable":1,"disable":1}
,"interfaces":{"command":1,"bridge":1}
}
;Search.control.loadWordPairs(pairs);
