var pairs =
{
"mpls":{"api":1,"functions":1,"forwarding":1,"interface":1,"fib":1,"qos":1}
,"api":{"following":1,"functions":1}
,"following":{"mpls":1}
,"functions":{"mpls":1,"functions":1,"description":1}
,"description":{"hal_mpls_init":1}
,"hal_mpls_init":{"function":1}
,"function":{"initializes":1,"deinitializes":1,"creates":1,"deletes":1,"enables":1,"disables":1,"updates":1,"clears":1,"adds":1,"removes":1,"sets":1,"binds":1,"unbinds":1,"reserves":1,"releases":1}
,"initializes":{"mpls":1}
,"forwarding":{"plane":1,"hal_mpls_disable_interface":1,"hal_mpls_if_update_vrf":1}
,"plane":{"hal_mpls_deinit":1,"hal_mpls_vrf_create":1}
,"hal_mpls_deinit":{"function":1}
,"deinitializes":{"mpls":1}
,"hal_mpls_vrf_create":{"function":1}
,"creates":{"vrf":1}
,"vrf":{"table":1,"mpls":1,"entries":1}
,"table":{"hal_mpls_vrf_destroy":1,"hal_mpls_enable_interface":1,"hal_mpls_ftn_entry_delete":1,"hal_mpls_ilm_entry_add":1,"hal_mpls_ilm_entry_delete":1,"hal_mpls_send_ttl":1}
,"hal_mpls_vrf_destroy":{"function":1}
,"deletes":{"vrf":1,"specified":1,"fib":1,"vpls":1}
,"hal_mpls_enable_interface":{"function":1}
,"enables":{"interface":1,"disables":1}
,"interface":{"mpls":1,"points":1,"virtual":1,"hal_mpls_vpls_if_unbind":1,"hal_mpls_qos_reserve":1}
,"hal_mpls_disable_interface":{"function":1}
,"disables":{"interface":1,"mapping":1}
,"hal_mpls_if_update_vrf":{"function":1}
,"updates":{"vrf":1}
,"points":{"hal_mpls_clear_fib_table":1}
,"hal_mpls_clear_fib_table":{"function":1}
,"clears":{"mpls":1,"vrf":1}
,"fib":{"entries":1,"(ftn\u002Film)":1,"entry":1}
,"entries":{"matching":1}
,"matching":{"specified":1}
,"specified":{"identifier":1,"ftn":1,"entry":1,"ilm":1}
,"identifier":{"hal_mpls_clear_vrf_table":1,"hal_mpls_ftn_entry_add":1}
,"hal_mpls_clear_vrf_table":{"function":1}
,"hal_mpls_ftn_entry_add":{"function":1}
,"adds":{"specified":1,"fib":1,"vpls":1}
,"ftn":{"entry":1,"table":1}
,"entry":{"ftn":1,"ilm":1,"peer":1,"(ftn\u002Film)":1,"hal_mpls_vpls_del":1,"hal_mpls_vpls_if_bind":1,"interface":1}
,"hal_mpls_ftn_entry_delete":{"function":1}
,"removes":{"specified":1}
,"hal_mpls_ilm_entry_add":{"function":1}
,"ilm":{"entry":1,"table":1}
,"hal_mpls_ilm_entry_delete":{"function":1}
,"hal_mpls_send_ttl":{"function":1}
,"sets":{"new":1}
,"new":{"ttl":1}
,"ttl":{"value":1}
,"value":{"packets":1}
,"packets":{"hal_mpls_local_pkt_handle":1,"hal_mpls_vc_init":1}
,"hal_mpls_local_pkt_handle":{"function":1}
,"mapping":{"locally":1}
,"locally":{"generated":1}
,"generated":{"packets":1}
,"hal_mpls_vc_init":{"function":1}
,"binds":{"interface":1,"vpls":1}
,"virtual":{"circuit":1}
,"circuit":{"hal_mpls_vc_deinit":1,"hal_mpls_vc_fib_add":1}
,"hal_mpls_vc_deinit":{"function":1}
,"unbinds":{"interface":1,"vpls":1}
,"hal_mpls_vc_fib_add":{"function":1}
,"(ftn\u002Film)":{"entry":1,"hal_mpls_vpls_add":1}
,"peer":{"hal_mpls_vc_fib_delete":1}
,"hal_mpls_vc_fib_delete":{"function":1}
,"hal_mpls_vpls_add":{"function":1}
,"vpls":{"entry":1}
,"hal_mpls_vpls_del":{"function":1}
,"hal_mpls_vpls_if_bind":{"function":1}
,"hal_mpls_vpls_if_unbind":{"function":1}
,"hal_mpls_qos_reserve":{"function":1}
,"reserves":{"mpls":1}
,"qos":{"resources":1}
,"resources":{"creation":1,"tear":1}
,"creation":{"lsp":1}
,"lsp":{"hal_mpls_qos_release":1}
,"hal_mpls_qos_release":{"function":1}
,"releases":{"mpls":1}
,"tear":{"down":1}
,"down":{"lsp":1}
}
;Search.control.loadWordPairs(pairs);
