var pairs =
{
"related":{"documents":1,"document":1}
,"documents":{"commands":1}
,"commands":{"resource":1}
,"resource":{"reservation":1}
,"reservation":{"protocol-traffic":1,"protocol":1}
,"protocol-traffic":{"engineering":1}
,"engineering":{"(rsvp-te)":1,"developer":1}
,"(rsvp-te)":{"label":1}
,"label":{"distribution":1,"switching":1}
,"distribution":{"protocol":1}
,"protocol":{"(ldp)":1,"traffic":1,"command":1,"developer":1}
,"(ldp)":{"part":1}
,"part":{"document":1}
,"document":{"instead":1,"multi-protocol":1}
,"instead":{"resource":1}
,"traffic":{"command":1,"engineering":1}
,"command":{"reference":1}
,"reference":{"resource":1,"label":1,"network":1}
,"developer":{"guide":1}
,"guide":{"label":1,"following":1,"multi-protocol":1,"architecture":1,"installation":1,"network":1,"zebos-xp":1}
,"following":{"guides":1}
,"guides":{"related":1}
,"multi-protocol":{"label":1}
,"switching":{"configuration":1,"developer":1,"software":1}
,"configuration":{"guide":1}
,"software":{"forwarder":1}
,"forwarder":{"developer":1}
,"architecture":{"guide":1}
,"installation":{"guide":1}
,"network":{"services":1}
,"services":{"module":1}
,"module":{"command":1,"developer":1}
,"zebos-xp":{"technical":1}
,"technical":{"manuals":1}
,"manuals":{"available":1}
,"available":{"licensed":1}
,"licensed":{"customers":1}
,"customers":{"http:\u002F\u002Fwww.ipinfusion.com\u002Fsupport\u002Fdocument_list":1}
}
;Search.control.loadWordPairs(pairs);
