var pairs =
{
"ospf6_if_transmit_delay_set":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"called":1,"succeeds":1}
,"sets":{"estimated":1}
,"estimated":{"time":1}
,"time":{"takes":1}
,"takes":{"transmit":1}
,"transmit":{"link":1,"delay":1}
,"link":{"state":1}
,"state":{"update":1}
,"update":{"packet":1}
,"packet":{"interface":1}
,"interface":{"function":1,"name":1,"instance":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"ipv6":1}
,"ipv6":{"ospf":1}
,"ospf":{"transmit-delay":1}
,"transmit-delay":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf6_if_transmit_delay_set":1,"instance_id":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1}
,"char":{"*name":1}
,"*name":{"int":1}
,"instance_id":{"u_int32_t":1,"interface":1}
,"u_int32_t":{"seconds)":1}
,"seconds)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"exist":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"name":1}
,"name":{"interface":1,"instance_id":1}
,"instance":{"255>":1,"outside":1}
,"255>":{"seconds":1}
,"seconds":{"transmit":1,"65535>":1,"outside":1}
,"delay":{"seconds":1}
,"65535>":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf6_api_set_err_vr_not_exist":1}
,"ospf6_api_set_err_vr_not_exist":{"virtual":1}
,"exist":{"ospf6_api_set_err_if_instance_id_invalid":1}
,"ospf6_api_set_err_if_instance_id_invalid":{"given":1}
,"given":{"instance":1,"seconds":1}
,"outside":{"range":1}
,"range":{"ospf6_api_set_err_if_transmit_delay_invalid":1,"ospf6_api_set_success":1}
,"ospf6_api_set_err_if_transmit_delay_invalid":{"given":1}
,"ospf6_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
