var pairs =
{
"isis_lsp_mtu_unset":{"call":1}
,"call":{"unsets":1,"successful":1}
,"unsets":{"high-priority":1}
,"high-priority":{"tag":1}
,"tag":{"syntax":1,"output":1}
,"syntax":{"int":1}
,"int":{"isis_high_priority_tag_unset":1}
,"isis_high_priority_tag_unset":{"(u_int32_t":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1,"*tag":1}
,"char":{"*tag)":1}
,"*tag)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"*tag":{"is-is":1}
,"is-is":{"instance":1}
,"instance":{"area":1,"exist":1}
,"area":{"tag":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"isis_api_set_err_vr_not_exist":1}
,"isis_api_set_err_vr_not_exist":{"exist":1}
,"exist":{"isis_api_set_err_instance_not_exist":1,"isis_api_set_success":1}
,"isis_api_set_err_instance_not_exist":{"isis":1}
,"isis":{"instance":1}
,"isis_api_set_success":{"call":1}
}
;Search.control.loadWordPairs(pairs);
