var pairs =
{
"crypto":{"map":1}
,"map":{"local-address":1,"ipsec":1,"[map-name]":1,"interface-id":1,"map1":1}
,"local-address":{"command":1,"[interface-id]":1,"parameters":1,"p7p1":1}
,"command":{"specify":1,"remove":1,"configuration":1,"syntax":1,"mode":1}
,"specify":{"interface":1}
,"interface":{"used":1}
,"used":{"crypto":1,"router":1}
,"ipsec":{"traffic":1}
,"traffic":{"form":1,"peers":1}
,"form":{"command":1}
,"remove":{"command":1}
,"configuration":{"command":1}
,"syntax":{"crypto":1}
,"[map-name]":{"local-address":1}
,"[interface-id]":{"crypto":1}
,"parameters":{"map-name":1}
,"map-name":{"name":1}
,"name":{"identifies":1}
,"identifies":{"crypto":1}
,"interface-id":{"specify":1}
,"router":{"send":1}
,"send":{"traffic":1}
,"peers":{"command":1}
,"mode":{"configure":1,"example":1}
,"configure":{"mode":1}
,"example":{"zebos":1}
,"zebos":{"(config)":1}
,"(config)":{"crypto":1}
,"map1":{"local-address":1}
}
;Search.control.loadWordPairs(pairs);
