var pairs =
{
"related":{"documents":1}
,"documents":{"except":1}
,"except":{"otherwise":1}
,"otherwise":{"noted":1}
,"noted":{"guide":1}
,"guide":{"multi-protocol":1,"command":1}
,"multi-protocol":{"label":1}
,"label":{"switching":1,"distribution":1}
,"switching":{"command":1}
,"command":{"reference":1,"references":1}
,"reference":{"details":1,"rsvp-te":1,"border":1,"open":1,"intermediate":1,"network":1,"zebos-xp":1}
,"details":{"commands":1}
,"commands":{"used":1}
,"used":{"configurations":1}
,"configurations":{"guide":1,"label":1}
,"references":{"details":1}
,"distribution":{"protocol":1}
,"protocol":{"command":1}
,"rsvp-te":{"command":1}
,"border":{"gateway":1}
,"gateway":{"protocol":1}
,"open":{"shortest":1}
,"shortest":{"path":1}
,"path":{"first":1}
,"first":{"command":1}
,"intermediate":{"system-to-intermediate":1}
,"system-to-intermediate":{"system":1}
,"system":{"command":1}
,"network":{"services":1}
,"services":{"module":1}
,"module":{"command":1}
,"zebos-xp":{"technical":1}
,"technical":{"manuals":1}
,"manuals":{"available":1}
,"available":{"licensed":1}
,"licensed":{"customers":1}
,"customers":{"http:\u002F\u002Fwww.ipinfusion.com\u002Fsupport\u002Fdocument_list":1}
}
;Search.control.loadWordPairs(pairs);
