var pairs =
{
"mep":{"mismatch":1,"implementing":1,"associated":1}
,"mismatch":{"variables":1,"state":1,"normal":1}
,"variables":{"following":1,"local":1}
,"following":{"variables":1}
,"local":{"mep":1}
,"state":{"machines":1}
,"machines":{"pbb-te":1,"indicate":1}
,"pbb-te":{"mep":1,"mas":1}
,"implementing":{"traffic":1}
,"traffic":{"field":1,"fields":1}
,"field":{"mmccmreceived":1,"tied":1}
,"mmccmreceived":{"mmccmdefect":1,"boolean":1}
,"mmccmdefect":{"mmccmtime":1,"boolean":1}
,"mmccmtime":{"disablelocdefect":1,"time":1,"equal":1}
,"disablelocdefect":{"mmlocdefect":1,"boolean":1,"true":1}
,"mmlocdefect":{"mmccmreceived":1,"variable":1,"boolean":1}
,"boolean":{"flag":1,"disables":1}
,"flag":{"true":1,"cleared":1}
,"true":{"rcvdtrafficbit":1,"either":1,"protection":1,"(force":1,"true":1}
,"rcvdtrafficbit":{"match":1}
,"match":{"presenttraffic":1}
,"presenttraffic":{"mmccmdefect":1,"received":1}
,"cleared":{"mep":1}
,"indicate":{"ccms":1,"presentmmloc":1}
,"ccms":{"traffic":1}
,"fields":{"matching":1}
,"matching":{"presenttraffic":1}
,"received":{"period":1}
,"period":{"3.5":1,"50ms":1}
,"3.5":{"times":1}
,"times":{"configured":1}
,"configured":{"ccm":1}
,"ccm":{"transmission":1,"correct":1}
,"transmission":{"rate":1}
,"rate":{"mmccmtime":1}
,"time":{"used":1,"taken":1,"50ms":1,"restoration":1,"gives":1,"(3.5":1,"1.25":1}
,"used":{"initiate":1}
,"initiate":{"mmccmwhile":1}
,"mmccmwhile":{"timer":1}
,"timer":{"time":1}
,"taken":{"remote":1}
,"remote":{"beb":1}
,"beb":{"(backbone":1}
,"(backbone":{"edge":1}
,"edge":{"bridge)":1}
,"bridge)":{"send":1}
,"send":{"ccm":1}
,"correct":{"information":1}
,"information":{"traffic":1}
,"tied":{"target":1}
,"target":{"protection":1}
,"protection":{"switching":1,"switch":1,"group":1,"groups":1,"entity":1}
,"switching":{"time":1}
,"50ms":{"mismatch":1,"(4.75":1}
,"normal":{"prior":1}
,"prior":{"completion":1}
,"completion":{"protection":1}
,"switch":{"simplest":1,"failure)":1}
,"simplest":{"case":1}
,"case":{"mmccmtime":1}
,"equal":{"detection":1}
,"detection":{"time":1}
,"restoration":{"procedure":1,"transfer":1}
,"procedure":{"time":1}
,"transfer":{"time":1}
,"gives":{"time":1}
,"(3.5":{"*ccm":1}
,"*ccm":{"interval":1,"interval)":1}
,"interval":{"restoration":1}
,"1.25":{"*ccm":1}
,"interval)":{"result":1}
,"result":{"value":1}
,"value":{"maximum":1}
,"maximum":{"50ms":1}
,"(4.75":{"*ccmtime":1}
,"*ccmtime":{"(ccminterval)":1}
,"(ccminterval)":{"10ms)":1}
,"10ms)":{"disablelocdefect":1}
,"disables":{"indication":1}
,"indication":{"mmlocdefect":1}
,"variable":{"always":1}
,"always":{"pbb-te":1}
,"mas":{"part":1}
,"part":{"protection":1}
,"group":{"pbb-te":1,"mmlocdefect":1}
,"associated":{"working":1,"protection":1}
,"working":{"entity":1}
,"entity":{"protection":1}
,"groups":{"monitoring":1,"pbb-te":1,"assigned":1}
,"monitoring":{"tesi":1}
,"tesi":{"assigned":1}
,"assigned":{"disablelocdefect":1}
,"either":{"p.sf":1}
,"p.sf":{"(protection":1}
,"(protection":{"switch":1}
,"failure)":{"lop":1}
,"lop":{"(loss":1}
,"(loss":{"protection)":1}
,"protection)":{"true":1}
,"(force":{"switch)":1}
,"switch)":{"true":1}
,"presentmmloc":{"period":1}
}
;Search.control.loadWordPairs(pairs);
