var pairs =
{
"internet":{"group":1}
,"group":{"management":1,"defined":1}
,"management":{"protocol":1}
,"protocol":{"(igmp)":1,"allows":1,"protocol":1,"independent":1}
,"(igmp)":{"ipv4":1}
,"ipv4":{"protocol":1}
,"allows":{"hosts":1}
,"hosts":{"add":1}
,"add":{"remove":1}
,"remove":{"themselves":1}
,"themselves":{"multicast":1}
,"multicast":{"group":1,"transmission":1,"traffic":1,"routing":1,"(pim)":1,"listener":1}
,"defined":{"rfc":1}
,"rfc":{"3376":1}
,"3376":{"igmp":1}
,"igmp":{"enables":1}
,"enables":{"receivers":1}
,"receivers":{"register":1,"task":1}
,"register":{"want":1}
,"want":{"receive":1}
,"receive":{"particular":1}
,"particular":{"multicast":1}
,"transmission":{"route":1}
,"route":{"multicast":1}
,"traffic":{"source":1}
,"source":{"receivers":1}
,"task":{"left":1}
,"left":{"multicast":1}
,"routing":{"protocol":1}
,"independent":{"multicast":1}
,"(pim)":{"multicast":1}
,"listener":{"discovery":1}
,"discovery":{"(mld)":1}
,"(mld)":{"multicast":1}
}
;Search.control.loadWordPairs(pairs);
