var pairs =
{
"vpn":{"tunneling":1,"significant":1,"interfaces":1,"tunnel":1}
,"tunneling":{"vpn":1,"form":1}
,"significant":{"applications":1}
,"applications":{"support":1}
,"support":{"(others":1}
,"(others":{"include":1}
,"include":{"private":1}
,"private":{"router":1,"networks":1}
,"router":{"customer":1}
,"customer":{"isp":1}
,"isp":{"ability":1}
,"ability":{"multiple":1,"several":1,"tear":1}
,"multiple":{"customers":1}
,"customers":{"potentially":1}
,"potentially":{"overlapping":1}
,"overlapping":{"private":1}
,"networks":{"immediately":1}
,"immediately":{"adjacent":1}
,"adjacent":{"isp)":1}
,"isp)":{"simple":1}
,"simple":{"vpn":1}
,"form":{"(preferably":1}
,"(preferably":{"ability":1}
,"several":{"tunnels":1}
,"tunnels":{"once":1}
,"once":{"within":1}
,"within":{"single":1,"interact":1}
,"single":{"vr)":1}
,"vr)":{"endpoints":1}
,"endpoints":{"looking":1,"logical":1}
,"looking":{"routing":1}
,"routing":{"protocols":1,"option":1}
,"protocols":{"point-to-point":1,"treat":1}
,"point-to-point":{"point-to-multipoint":1}
,"point-to-multipoint":{"connections":1,"interfaces":1}
,"connections":{"(the":1}
,"(the":{"latter":1}
,"latter":{"case":1}
,"case":{"tunnel":1,"vpn":1}
,"tunnel":{"two":1,"passed":1,"down.)":1}
,"two":{"endpoints)":1}
,"endpoints)":{"endpoints":1}
,"logical":{"interfaces":1}
,"interfaces":{"almost":1,"typical":1,"regardless":1,"dynamic":1}
,"almost":{"indistinguishable":1}
,"indistinguishable":{"standard":1}
,"standard":{"interface":1}
,"interface":{"appropriate":1,"names":1,"example":1,"virtual":1,"fastethernet":1}
,"appropriate":{"class":1}
,"class":{"interface":1}
,"names":{"administrators":1}
,"administrators":{"choose":1}
,"choose":{"reflect":1}
,"reflect":{"nature":1}
,"nature":{"interface":1}
,"example":{"interface":1}
,"virtual":{"instead":1}
,"instead":{"interface":1,"using":1}
,"fastethernet":{"routing":1}
,"treat":{"interfaces":1}
,"typical":{"point-to-point":1}
,"regardless":{"encapsulation":1}
,"encapsulation":{"method":1}
,"method":{"ability":1}
,"tear":{"down":1}
,"down":{"vpn":1}
,"dynamic":{"may":1}
,"may":{"requirement":1}
,"requirement":{"protocol":1}
,"protocol":{"allows":1}
,"allows":{"vpns":1}
,"vpns":{"discover":1,"interfere":1,"operate":1}
,"discover":{"vpns":1}
,"interfere":{"even":1}
,"even":{"within":1}
,"interact":{"across":1}
,"across":{"vrs":1}
,"vrs":{"routes":1}
,"routes":{"cross":1}
,"cross":{"vpns":1}
,"operate":{"normally":1}
,"normally":{"routing":1}
,"option":{"drop":1}
,"drop":{"packets":1}
,"packets":{"certain":1,"destined":1}
,"certain":{"destinations":1}
,"destinations":{"instead":1}
,"using":{"default":1}
,"default":{"route":1}
,"route":{"provided":1,"unencrypted":1}
,"provided":{"(it":1}
,"(it":{"advantageous":1}
,"advantageous":{"packets":1}
,"destined":{"end":1}
,"end":{"vpn":1}
,"passed":{"default":1}
,"unencrypted":{"case":1}
}
;Search.control.loadWordPairs(pairs);
