var pairs =
{
"ospf_graceful_restart_unset":{"function":1,"(struct":1}
,"function":{"disables":1,"called":1,"succeeds":1}
,"disables":{"graceful":1}
,"graceful":{"restart":1}
,"restart":{"resets":1,"grace-period":1}
,"resets":{"grace":1}
,"grace":{"period":1}
,"period":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"ospf":1}
,"ospf":{"restart":1,"structure":1,"sso":1}
,"grace-period":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf_graceful_restart_unset":1}
,"(struct":{"ospf_master":1}
,"ospf_master":{"*om)":1}
,"*om)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"pointer":1,"none":1}
,"pointer":{"master":1}
,"master":{"ospf":1}
,"structure":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf_api_set_success":1}
,"ospf_api_set_success":{"function":1}
,"succeeds":{"ospf_api_set_err_gr_not_supported":1}
,"ospf_api_set_err_gr_not_supported":{"ospf":1}
,"sso":{"enabled":1}
}
;Search.control.loadWordPairs(pairs);
