var pairs =
{
"overview":{"several":1}
,"several":{"virtual":1}
,"virtual":{"lan":1}
,"lan":{"(vlan)":1}
,"(vlan)":{"interfaces":1}
,"interfaces":{"configured":1,"physical":1,"once":1,"created":1,"two":1,"vlan":1,"directly":1}
,"configured":{"single":1,"trunks":1}
,"single":{"ethernet":1}
,"ethernet":{"interface":1}
,"interface":{"once":1,"functions":1,"nsm":1,"zebos-xp":1}
,"once":{"created":1,"vlan":1}
,"created":{"vlan":1,"kernel":1}
,"vlan":{"interface":1,"interfaces":1,"ids":1}
,"functions":{"physical":1}
,"physical":{"interface":1,"interfaces":1,"connectivity":1}
,"nsm":{"recognizes":1}
,"recognizes":{"vlan":1}
,"kernel":{"addresses":1}
,"addresses":{"assigned":1}
,"assigned":{"zebos-xp":1}
,"zebos-xp":{"commands":1,"routing":1}
,"commands":{"used":1,"configure":1}
,"used":{"configure":1}
,"configure":{"display":1,"switch":1}
,"display":{"vlan":1}
,"routing":{"protocols":1}
,"protocols":{"rip":1}
,"rip":{"ospf":1}
,"ospf":{"bgp":1}
,"bgp":{"run":1}
,"run":{"across":1}
,"across":{"networks":1}
,"networks":{"using":1}
,"using":{"vlan":1}
,"two":{"systems":1}
,"systems":{"physical":1}
,"connectivity":{"(either":1}
,"(either":{"directly":1}
,"directly":{"connected":1}
,"connected":{"connected":1,"switch)":1,"switch":1}
,"switch)":{"communicate":1}
,"communicate":{"via":1}
,"via":{"vlan":1}
,"ids":{"belong":1}
,"belong":{"network":1}
,"network":{"physical":1}
,"switch":{"corresponding":1,"configured":1,"commands":1,"ports":1,"beyond":1}
,"corresponding":{"ports":1}
,"ports":{"switch":1,"trunks":1}
,"trunks":{"associated":1,"depend":1}
,"associated":{"vlans":1}
,"vlans":{"switch":1}
,"depend":{"type":1}
,"type":{"switch":1}
,"beyond":{"scope":1}
,"scope":{"document":1}
}
;Search.control.loadWordPairs(pairs);
