var pairs =
{
"overview":{"bfd":1}
,"bfd":{"base":1,"functionality":1,"attached":1,"uses":1,"determines":1}
,"base":{"module":1}
,"module":{"interacts":1}
,"interacts":{"nsm":1}
,"nsm":{"interface":1}
,"interface":{"virtual":1}
,"virtual":{"router":1}
,"router":{"specific":1}
,"specific":{"information":1}
,"information":{"bfd":1}
,"functionality":{"available":1,"handling":1}
,"available":{"privilege":1,"non-pvr":1}
,"privilege":{"(pvr)":1}
,"(pvr)":{"context":1}
,"context":{"default":1,"available":1,"bfd":1,"apply":1,"provide":1}
,"default":{"context":1}
,"non-pvr":{"context":1}
,"attached":{"associated":1}
,"associated":{"bfd":1}
,"uses":{"vr-id":1}
,"vr-id":{"determine":1,"request":1}
,"determine":{"context":1}
,"apply":{"bfd":1}
,"handling":{"client":1}
,"client":{"requests":1}
,"requests":{"bfd":1}
,"determines":{"appropriate":1}
,"appropriate":{"context":1}
,"provide":{"service":1}
,"service":{"using":1}
,"using":{"vr-id":1}
,"request":{"sent":1}
}
;Search.control.loadWordPairs(pairs);
