var pairs =
{
"rbridge2":{"show":1}
,"show":{"trill":1}
,"trill":{"topology":1,"paths":1}
,"topology":{"rbridge":1}
,"rbridge":{"instance":1}
,"instance":{"trill":1}
,"paths":{"campus":1}
,"campus":{"wide":1}
,"wide":{"rbridges":1}
,"rbridges":{"system":1}
,"system":{"metric":1}
,"metric":{"next-hop":1}
,"next-hop":{"interface":1}
,"interface":{"snpa":1}
,"snpa":{"aaaa.aaaa.aaaa":1}
,"aaaa.aaaa.aaaa":{"aaaa.aaaa.aaaa":1,"eth1":1}
,"eth1":{"5254.002a.5962":1}
,"5254.002a.5962":{"bbbb.bbbb.bbbb":1,"cccc.cccc.cccc":1}
,"bbbb.bbbb.bbbb":{"--cccc.cccc.cccc":1}
,"--cccc.cccc.cccc":{"cccc.cccc.cccc":1}
,"cccc.cccc.cccc":{"eth2":1}
,"eth2":{"5254.006e.54d7":1}
,"5254.006e.54d7":{"dddd.dddd.dddd":1,"eeee.eeee.eeee":1,"aaaa.aaaa.aaaa":1}
,"dddd.dddd.dddd":{"aaaa.aaaa.aaaa":1}
,"eeee.eeee.eeee":{"cccc.cccc.cccc":1}
}
;Search.control.loadWordPairs(pairs);
