var pairs =
{
"bridge-group":{"instance":1,"(<1-32>)":1,"(config-if)":1}
,"instance":{"priority":1,"multiple":1,"lan":1,"lower":1,"(<1-63>)":1,"identifier":1,"(config-if)":1}
,"priority":{"command":1,"multiple":1,"tiebreaker":1,"case":1,"interface":1,"<0-240>":1,"lower":1,"increments":1,"128":1}
,"command":{"priority":1,"syntax":1,"mode":1}
,"multiple":{"spanning":1}
,"spanning":{"tree":1}
,"tree":{"instance":1,"protocol":1}
,"protocol":{"uses":1}
,"uses":{"port":1}
,"port":{"priority":1,"forward":1,"root":1,"instance":1}
,"tiebreaker":{"determine":1,"lower-numbered":1}
,"determine":{"port":1}
,"forward":{"frames":1}
,"frames":{"particular":1}
,"particular":{"instance":1}
,"lan":{"port":1}
,"root":{"port":1}
,"lower":{"value":1}
,"value":{"implies":1,"means":1,"port":1}
,"implies":{"better":1}
,"better":{"priority":1}
,"case":{"priority":1}
,"interface":{"index":1,"preferred":1,"mode":1,"eth2":1}
,"index":{"serve":1}
,"serve":{"tiebreaker":1}
,"lower-numbered":{"interface":1}
,"preferred":{"others":1}
,"others":{"command":1}
,"syntax":{"bridge-group":1}
,"(<1-32>)":{"instance":1}
,"(<1-63>)":{"priority":1}
,"<0-240>":{"parameters":1,"port":1}
,"parameters":{"<1-32>":1}
,"<1-32>":{"bridge":1}
,"bridge":{"identifier":1,"<1-63>":1}
,"identifier":{"backbone":1,"<0-240>":1}
,"backbone":{"backbone":1,"bridge":1}
,"<1-63>":{"multiple":1}
,"means":{"greater":1}
,"greater":{"likelihood":1}
,"likelihood":{"becoming":1}
,"becoming":{"root":1}
,"increments":{"default":1}
,"default":{"default":1,"value":1}
,"128":{"command":1}
,"mode":{"interface":1,"example":1}
,"example":{"(config)":1}
,"(config)":{"interface":1}
,"eth2":{"(config-if)":1}
,"(config-if)":{"bridge-group":1}
}
;Search.control.loadWordPairs(pairs);
