var pairs =
{
"mpls":{"ilm-entry":1}
,"ilm-entry":{"vpnpop":1,"label":1,"100":1}
,"vpnpop":{"command":1,"specify":1,"200":1}
,"command":{"create":1,"delete":1,"supported":1,"syntax":1,"mode":1}
,"create":{"ilm":1}
,"ilm":{"entry":1,"table":1,"index":1}
,"entry":{"ilm":1,"match":1,"created":1,"updated":1}
,"table":{"vpn":1,"match":1}
,"vpn":{"pop":1}
,"pop":{"incoming":1}
,"incoming":{"interface":1,"label":1}
,"interface":{"bound":1,"name":1}
,"bound":{"upon":1}
,"upon":{"receipt":1}
,"receipt":{"labeled":1}
,"labeled":{"packet":1}
,"packet":{"mpls-enabled":1,"may":1}
,"mpls-enabled":{"router":1}
,"router":{"lookup":1}
,"lookup":{"done":1}
,"done":{"based":1}
,"based":{"incoming":1}
,"label":{"ilm":1,"ifname":1,"incoming":1,"value":1,"label":1,"configure":1}
,"match":{"found":1,"error":1}
,"found":{"packet":1}
,"may":{"either":1}
,"either":{"label-switched":1}
,"label-switched":{"downstream":1}
,"downstream":{"popped":1}
,"popped":{"passed":1}
,"passed":{"option":1,"ilm":1}
,"option":{"command":1}
,"delete":{"ilm":1}
,"error":{"message":1}
,"message":{"displays":1}
,"displays":{"command":1}
,"supported":{"zebic":1}
,"zebic":{"releases":1}
,"releases":{"command":1}
,"syntax":{"mpls":1}
,"ifname":{"(vpnpop)":1,"a.b.c.d":1,"incoming":1,"outgoing":1}
,"(vpnpop)":{"label":1}
,"a.b.c.d":{"(a.b.c.d\u002Fm":1,"a.b.c.d)":1,"a.b.c.d":1,"(<1-4294967295>":1,"nexthop":1,"fec":1,"mask":1}
,"(a.b.c.d\u002Fm":{"a.b.c.d":1}
,"a.b.c.d)":{"(<1-4294967295>":1}
,"(<1-4294967295>":{"mpls":1,"parameters":1}
,"parameters":{"label":1}
,"value":{"ifname":1,"<16-1048575>":1,"indicates":1,"passed":1}
,"name":{"vpnpop":1,"a.b.c.d":1}
,"specify":{"pop":1}
,"configure":{"outgoing":1,"mode":1,"terminal":1}
,"outgoing":{"label":1,"interface":1}
,"<16-1048575>":{"value":1}
,"indicates":{"explicit":1,"implicit":1}
,"explicit":{"null":1}
,"null":{"value":1,"ifname":1}
,"implicit":{"null":1}
,"nexthop":{"ipv4":1}
,"ipv4":{"address":1}
,"address":{"a.b.c.d":1}
,"fec":{"ilm":1}
,"created":{"a.b.c.d\u002Fm":1,"plus":1,"command":1}
,"a.b.c.d\u002Fm":{"fec":1}
,"plus":{"mask":1}
,"mask":{"a.b.c.d":1,"forwarding":1,"<1-429496725>":1}
,"forwarding":{"equivalence":1}
,"equivalence":{"class":1}
,"class":{"mask":1}
,"<1-429496725>":{"ilm":1}
,"index":{"update":1,"value":1,"used":1}
,"update":{"ilm":1}
,"updated":{"ilm":1}
,"used":{"new":1}
,"new":{"ilm":1}
,"mode":{"configure":1,"examples":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"mpls":1}
,"100":{"eth0":1}
,"eth0":{"vpnpop":1}
,"200":{"eth1":1}
,"eth1":{"1.2.3.4":1}
,"1.2.3.4":{"10.10.0.0\u002F24":1}
}
;Search.control.loadWordPairs(pairs);
