var pairs =
{
"bridge":{"mac-priority-override":1,"<1-32>":1,"group":1}
,"mac-priority-override":{"command":1,"mac-address":1}
,"command":{"mac":1,"unset":1,"syntax":1,"mode":1}
,"mac":{"priority":1,"interface":1,"address":1,"static":1}
,"priority":{"override":1,"<0-7>":1,"priority":1,"value":1,"(config)":1}
,"override":{"parameter":1,"command":1,"static-priority-override":1,"priority":1}
,"parameter":{"command":1}
,"unset":{"mac":1}
,"syntax":{"bridge":1}
,"<1-32>":{"mac-priority-override":1,"specify":1}
,"mac-address":{"mac":1,"enter":1,"1111.1111.1111":1}
,"interface":{"ifname":1,"interface":1,"information":1,"eth1":1}
,"ifname":{"vlan":1}
,"vlan":{"vlanid":1,"add":1,"static":1}
,"vlanid":{"(static":1,"parameters":1}
,"(static":{"static-priority-override":1}
,"static-priority-override":{"static-mgmt":1,"mac":1}
,"static-mgmt":{"static-mgmt-priority-overide)":1,"mac":1}
,"static-mgmt-priority-overide)":{"priority":1}
,"<0-7>":{"bridge":1,"priority":1}
,"parameters":{"<1-32>":1}
,"specify":{"bridge":1}
,"group":{"mac-address":1}
,"enter":{"mac":1}
,"address":{"hhhh.hhhh.hhhh":1}
,"hhhh.hhhh.hhhh":{"format":1}
,"format":{"interface":1}
,"information":{"vlan":1}
,"add":{"values":1}
,"values":{"associated":1}
,"associated":{"single":1}
,"single":{"vlan":1}
,"static":{"mac":1,"entry":1,"management":1,"priority":1}
,"entry":{"static-mgmt":1}
,"management":{"static-mgmt-priority-override":1,"priority":1}
,"static-mgmt-priority-override":{"mac":1}
,"value":{"command":1}
,"mode":{"configuration":1,"examples":1}
,"configuration":{"mode":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"bridge":1}
,"1111.1111.1111":{"interface":1}
,"eth1":{"vlan":1}
}
;Search.control.loadWordPairs(pairs);
