var pairs =
{
"hal_vlan_add_vid_to_port":{"function":1,"(char":1}
,"function":{"adds":1,"succeeds":1}
,"adds":{"vlan":1}
,"vlan":{"port":1,"egress":1}
,"port":{"syntax":1}
,"syntax":{"int":1}
,"int":{"hal_vlan_add_vid_to_port":1,"ifindex":1}
,"(char":{"*name":1}
,"*name":{"unsigned":1}
,"unsigned":{"int":1,"short":1}
,"ifindex":{"unsigned":1,"interface":1}
,"short":{"vid":1}
,"vid":{"enum":1,"vlan":1}
,"enum":{"hal_vlan_egress_type":1}
,"hal_vlan_egress_type":{"egress)":1}
,"egress)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"name":1,"none":1}
,"name":{"bridge":1,"ifindex":1}
,"bridge":{"name":1}
,"interface":{"index":1}
,"index":{"vid":1}
,"egress":{"egress":1,"tagged\u002Funtagged":1}
,"tagged\u002Funtagged":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"hal_err_vlan_not_exists":1}
,"hal_err_vlan_not_exists":{"hal_err_vlan_port_not_exists":1}
,"hal_err_vlan_port_not_exists":{"hal_success":1}
,"hal_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
