var pairs =
{
"hsl_ifmgr_l2_ethernet_create":{"function":1,"(char":1}
,"function":{"creates":1}
,"creates":{"layer":1}
,"layer":{"ethernet":1}
,"ethernet":{"interface":1}
,"interface":{"syntax":1,"name":1}
,"syntax":{"int":1}
,"int":{"hsl_ifmgr_l2_ethernet_create":1,"send_notification":1}
,"(char":{"*name":1}
,"*name":{"hsl_mac_address_t":1}
,"hsl_mac_address_t":{"mac":1}
,"mac":{"u_int16_t":1,"mac":1,"address":1}
,"u_int16_t":{"mtu":1}
,"mtu":{"u_int32_t":1,"maximum":1}
,"u_int32_t":{"speed":1,"duplex":1,"flags":1}
,"speed":{"u_int32_t":1,"duplex":1}
,"duplex":{"u_int32_t":1,"duplex":1,"mode":1}
,"flags":{"void":1,"send_notification":1}
,"void":{"*sys_info":1}
,"*sys_info":{"int":1}
,"send_notification":{"struct":1,"indicates":1}
,"struct":{"hsl_if":1}
,"hsl_if":{"**ppifp)":1}
,"**ppifp)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"name":1,"sys_info":1}
,"name":{"interface":1,"mac":1}
,"address":{"mtu":1}
,"maximum":{"transmission":1}
,"transmission":{"unit":1}
,"unit":{"speed":1}
,"mode":{"flags":1}
,"indicates":{"whether":1}
,"whether":{"send":1}
,"send":{"notification":1}
,"notification":{"protocol":1}
,"protocol":{"modules":1}
,"modules":{"ppifp":1}
,"ppifp":{"output":1}
,"output":{"parameters":1}
,"sys_info":{"system":1}
,"system":{"information":1}
,"information":{"return":1}
,"return":{"values":1}
}
;Search.control.loadWordPairs(pairs);
