var pairs =
{
"bridge":{"g8031":1,"<1-32>":1,"backbone":1,"(<1-32>":1,"bridge":1,"eps-id":1}
,"g8031":{"eps-id":1}
,"eps-id":{"command":1,"eps-id":1,"working-port":1,"bridge":1,"parameters":1,"eps":1}
,"command":{"create":1,"delete":1,"syntax":1,"mode":1}
,"create":{"ethernet":1}
,"ethernet":{"protection":1}
,"protection":{"switching":1,"port":1,"ports":1,"link":1,"eps":1,"group":1}
,"switching":{"(eps)":1}
,"(eps)":{"link":1}
,"link":{"link":1,"bound":1,"recreate":1,"command":1,"eps-id":1,"<1-4094>":1}
,"bound":{"working":1}
,"working":{"protection":1,"eps":1,"port":1}
,"port":{"once":1,"protection-port":1,"instance":1}
,"once":{"working":1}
,"ports":{"created":1,"delete":1}
,"created":{"cannot":1}
,"cannot":{"changed":1}
,"changed":{"change":1}
,"change":{"working":1}
,"delete":{"eps":1,"protection":1}
,"eps":{"link":1,"path":1}
,"recreate":{"form":1}
,"form":{"command":1}
,"syntax":{"bridge":1}
,"<1-32>":{"g8031":1,"bridge":1}
,"working-port":{"ifname":1,"interface":1,"eth0":1}
,"ifname":{"protection-port":1,"(instance":1,"interface":1}
,"protection-port":{"ifname":1,"interface":1,"eth1":1}
,"(instance":{"<1-63>":1}
,"<1-63>":{"bridge":1,"protection":1}
,"backbone":{"g8031":1,"backbone":1,"bridge":1}
,"(<1-32>":{"backbone)":1}
,"backbone)":{"g8031":1}
,"parameters":{"bridge":1}
,"<1-4094>":{"working-port":1}
,"interface":{"working":1,"name":1,"protection":1}
,"path":{"ifname":1}
,"name":{"working":1,"protection":1}
,"instance":{"protection":1,"<1-63>":1,"command":1,"(config)":1}
,"group":{"instance":1}
,"mode":{"configure":1,"examples":1}
,"configure":{"mode":1,"terminal":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"bridge":1}
,"eth0":{"protection-port":1}
,"eth1":{"instance":1}
}
;Search.control.loadWordPairs(pairs);
