var pairs =
{
"i_beb2":{"i_beb2":1,"configure":1,"(config)":1,"(config-vlan)":1,"(config-if)":1}
,"configure":{"terminal":1,"mode":1,"bridge":1,"spanning":1,"s-vlan":1,"instance":1,"eth2":1,"interface":1,"0003.ff7e.20d4":1,"svlan":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"vlan":1,"service":1,"interface":1}
,"mode":{"i_beb2":1,"provider-rstp":1,"rstp":1,"i_beb1":1,"pip":1,"cnp":1}
,"(config)":{"bridge":1,"spanning-tree":1,"vlan":1,"pbb":1,"interface":1}
,"bridge":{"beb":1,"cnp-4":1,"i_beb2":1,"name":1,"state":1,"i_beb1":1,"group":1}
,"beb":{"mac":1,"(backbone":1,"vlan":1,"pip":1,"vip":1,"customer-network":1}
,"mac":{"0001.0001.0001":1}
,"0001.0001.0001":{"protocol":1}
,"protocol":{"provider-mstp":1}
,"provider-mstp":{"configure":1}
,"(backbone":{"edge":1}
,"edge":{"bridge)":1}
,"bridge)":{"i_beb2":1}
,"spanning-tree":{"mode":1}
,"provider-rstp":{"configure":1}
,"spanning":{"tree":1}
,"tree":{"mode":1}
,"rstp":{"i_beb1":1}
,"i_beb1":{"(config)":1,"(pbb-isid)":1}
,"cnp-4":{"priority":1}
,"priority":{"61440":1,"bridge":1}
,"61440":{"assigning":1}
,"assigning":{"priority":1}
,"vlan":{"database":1,"configure":1,"type":1,"pip":1,"cnp":1}
,"database":{"enter":1,"mode":1}
,"(config-vlan)":{"vlan":1,"exit":1}
,"type":{"service":1,"associate":1}
,"service":{"point-point":1,"type":1,"instance":1}
,"point-point":{"bridge":1}
,"name":{"ipi3":1,"isid1":1}
,"ipi3":{"configure":1,"i_beb2":1}
,"s-vlan":{"service":1}
,"associate":{"name":1,"bridge":1,"eth1":1,"b-vlan":1,"eth2":1}
,"state":{"enable":1}
,"enable":{"configure":1}
,"pbb":{"isid":1}
,"isid":{"list":1,"name":1,"allow":1,"i_beb2":1}
,"list":{"enter":1}
,"instance":{"configure":1,"i-component":1,"i_beb1":1,"port)":1,"allowed":1,"egress-port":1,"mapping":1,"i_beb2":1}
,"(pbb-isid)":{"isid":1,"exit":1}
,"isid1":{"i-component":1,"creates":1}
,"i-component":{"configure":1,"bridge":1}
,"creates":{"vip":1}
,"vip":{"port":1,"instance":1}
,"port":{"service":1,"i_beb2":1}
,"exit":{"exit":1,"service":1,"vlan":1,"interface":1}
,"interface":{"eth1":1,"mode":1,"i_beb2":1,"pip":1,"eth2":1,"cnp":1,"eth3":1}
,"eth1":{"enter":1,"bridge":1,"i_beb2":1,"configure":1}
,"(config-if)":{"shutdown":1,"switchport":1,"bridge-group":1,"exit":1}
,"shutdown":{"administratively":1,"shut":1}
,"administratively":{"shut":1}
,"shut":{"down":1}
,"down":{"interface":1}
,"switchport":{"configure":1,"mode":1,"beb":1}
,"eth2":{"layer":1,"enter":1,"bridge":1}
,"layer":{"port":1}
,"bridge-group":{"associate":1}
,"group":{"i_beb2":1}
,"pip":{"configure":1,"(provider":1,"associate":1,"backbone-source-mac":1,"i_beb2":1}
,"(provider":{"instance":1}
,"port)":{"i_beb2":1}
,"b-vlan":{"eth1":1}
,"backbone-source-mac":{"0003.ff7e.20d4":1}
,"0003.ff7e.20d4":{"configure":1,"pip":1}
,"allowed":{"map":1}
,"map":{"isid":1}
,"allow":{"ingress":1}
,"ingress":{"egress":1}
,"egress":{"frames":1,"port":1}
,"frames":{"isid":1}
,"cnp":{"configure":1,"(customer":1,"associate":1}
,"(customer":{"network":1}
,"network":{"port)":1}
,"customer-network":{"svlan":1}
,"svlan":{"add":1,"service":1}
,"add":{"instance":1}
,"egress-port":{"eth1":1}
,"mapping":{"specify":1}
,"specify":{"egress":1}
,"eth3":{"enter":1}
}
;Search.control.loadWordPairs(pairs);
