var pairs =
{
"ethernet":{"local":1,"virtual":1,"forum":1}
,"local":{"management":1}
,"management":{"interface":1}
,"interface":{"(e-lmi)":1,"(uni)":1}
,"(e-lmi)":{"operation":1}
,"operation":{"administration":1,"based":1}
,"administration":{"maintenance":1}
,"maintenance":{"(oam)":1}
,"(oam)":{"protocol":1}
,"protocol":{"communications":1}
,"communications":{"two":1}
,"two":{"user-to-network":1}
,"user-to-network":{"interface":1}
,"(uni)":{"instances":1}
,"instances":{"e-lmi":1}
,"e-lmi":{"provides":1}
,"provides":{"uni":1}
,"uni":{"ethernet":1}
,"virtual":{"connection":1}
,"connection":{"(evc)":1}
,"(evc)":{"status":1}
,"status":{"information":1}
,"information":{"customer":1,"enables":1}
,"customer":{"edge":1}
,"edge":{"devices":1,"operation":1}
,"devices":{"information":1}
,"enables":{"automatic":1}
,"automatic":{"configuration":1}
,"configuration":{"customer":1,"defined":1}
,"based":{"configuration":1}
,"defined":{"metro":1}
,"metro":{"ethernet":1}
,"forum":{"(mef)":1}
}
;Search.control.loadWordPairs(pairs);
