var pairs =
{
"precision":{"time":1}
,"time":{"protocol":1,"synchronization":1}
,"protocol":{"(ptp)":1,"synchronizes":1}
,"(ptp)":{"protocol":1}
,"synchronizes":{"clocks":1}
,"clocks":{"throughout":1}
,"throughout":{"computer":1}
,"computer":{"network":1}
,"network":{"lan":1}
,"lan":{"ptp":1}
,"ptp":{"achieves":1}
,"achieves":{"clock":1}
,"clock":{"accuracy":1,"slave":1,"defined":1}
,"accuracy":{"sub-microsecond":1}
,"sub-microsecond":{"range":1}
,"range":{"making":1}
,"making":{"suitable":1}
,"suitable":{"measurement":1}
,"measurement":{"control":1}
,"control":{"systems":1}
,"systems":{"time":1}
,"synchronization":{"achieved":1}
,"achieved":{"packets":1}
,"packets":{"transmitted":1}
,"transmitted":{"received":1}
,"received":{"session":1}
,"session":{"master":1}
,"master":{"clock":1}
,"slave":{"clock":1}
,"defined":{"ieee":1}
,"ieee":{"1588v2":1}
}
;Search.control.loadWordPairs(pairs);
