var pairs =
{
"debug":{"ipv6":1,"mld":1,"vpn":1}
,"ipv6":{"mld":1}
,"mld":{"command":1,"specific":1,"layer-3":1,"debugging":1,"debug":1,"decode":1,"encode":1,"events":1,"fsm":1,"tib":1,"(vrf":1,"decoding":1,"encoding":1,"finite":1,"tree":1}
,"command":{"enable":1,"applies":1,"disable":1,"syntax":1,"mode":1}
,"enable":{"debugging":1}
,"debugging":{"mld":1,"debugging":1,"specific":1}
,"specific":{"component":1}
,"component":{"mld":1}
,"applies":{"interfaces":1}
,"interfaces":{"configured":1}
,"configured":{"mld":1}
,"layer-3":{"multicast":1}
,"multicast":{"protocols":1}
,"protocols":{"parameter":1}
,"parameter":{"command":1}
,"disable":{"mld":1}
,"syntax":{"debug":1}
,"decode":{"debug":1}
,"encode":{"debug":1}
,"events":{"debug":1,"fsm":1}
,"fsm":{"debug":1}
,"tib":{"debug":1,"parameters":1}
,"(vrf":{"name":1}
,"name":{"debug":1,"decode":1,"encode":1,"events":1,"fsm":1,"tib":1}
,"parameters":{"debug":1}
,"decoding":{"encode":1}
,"encoding":{"events":1}
,"finite":{"state":1}
,"state":{"machine":1}
,"machine":{"(fsm)":1}
,"(fsm)":{"tib":1}
,"tree":{"information":1}
,"information":{"base":1}
,"base":{"(tib)":1}
,"(tib)":{"vrf":1}
,"vrf":{"debug":1}
,"vpn":{"routing\u002Fforwarding":1}
,"routing\u002Fforwarding":{"instance":1}
,"instance":{"command":1}
,"mode":{"privileged":1,"configure":1,"example":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"configure":{"mode":1,"terminal":1}
,"example":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"debug":1}
}
;Search.control.loadWordPairs(pairs);
