var pairs =
{
"layer":{"routing":1,"(l3)":1,"router":1,"header":1,"switch":1,"routers":1,"switches":1,"bridge":1,"2\u002Flayer":1}
,"routing":{"layer":1,"table":1,"protocol":1,"function":1,"functions":1}
,"(l3)":{"routers":1}
,"routers":{"typically":1,"layer":1,"historically":1,"throughput":1,"increasing":1,"fail":1,"switches":1}
,"typically":{"used":1}
,"used":{"provide":1}
,"provide":{"connectivity":1,"flexibility":1}
,"connectivity":{"different":1}
,"different":{"lans":1,"customers":1,"combinations":1}
,"lans":{"layer":1}
,"router":{"discards":1,"strip":1,"layer":1,"implementation":1,"absolute":1,"(figure":1}
,"discards":{"mac":1}
,"mac":{"headers":1,"address":1,"header":1}
,"headers":{"indexes":1}
,"indexes":{"further":1}
,"further":{"packet":1}
,"packet":{"making":1,"finds":1,"arp":1,"new":1,"port":1}
,"making":{"decisions":1}
,"decisions":{"based":1}
,"based":{"layer":1}
,"header":{"extracts":1,"packet":1,"transmits":1}
,"extracts":{"layer\u20113":1}
,"layer\u20113":{"header":1}
,"finds":{"matching":1}
,"matching":{"destination":1}
,"destination":{"address":1}
,"address":{"routing":1,"packet":1}
,"table":{"identifies":1,"routing":1,"populated":1}
,"identifies":{"new":1}
,"new":{"mac":1}
,"arp":{"cache":1}
,"cache":{"wraps":1}
,"wraps":{"packet":1}
,"transmits":{"packet":1}
,"port":{"associated":1}
,"associated":{"destination":1}
,"populated":{"statically":1}
,"statically":{"configured":1}
,"configured":{"command":1,"absolute":1}
,"command":{"line":1}
,"line":{"interface":1}
,"interface":{"entries":1}
,"entries":{"routing":1}
,"protocol":{"messages":1}
,"messages":{"neighboring":1}
,"neighboring":{"routers":1}
,"strip":{"layers":1}
,"layers":{"(physical":1}
,"(physical":{"data":1}
,"data":{"link":1}
,"link":{"network)":1}
,"network)":{"intrinsically":1}
,"intrinsically":{"complicated":1}
,"complicated":{"layer":1}
,"switch":{"layer":1,"router":1,"(figure":1,"multiple":1}
,"historically":{"implement":1}
,"implement":{"routing":1}
,"function":{"software":1}
,"software":{"often":1}
,"often":{"results":1}
,"results":{"limited":1}
,"limited":{"packet-forwarding":1}
,"packet-forwarding":{"rates":1}
,"rates":{"however":1}
,"however":{"improvements":1}
,"improvements":{"vlsi":1}
,"vlsi":{"circuit":1}
,"circuit":{"technology":1}
,"technology":{"allowed":1}
,"allowed":{"layer":1}
,"functions":{"implemented":1}
,"implemented":{"rapidly":1}
,"rapidly":{"hardware":1}
,"hardware":{"enabling":1}
,"enabling":{"wire-speed":1}
,"wire-speed":{"performance":1}
,"performance":{"similar":1,"layer":1}
,"similar":{"performance":1}
,"switches":{"result":1,"layer":1,"zebos-xp":1}
,"result":{"along":1}
,"along":{"complexity":1}
,"complexity":{"next-generation":1}
,"next-generation":{"layer":1}
,"throughput":{"routers":1}
,"increasing":{"architecture":1}
,"architecture":{"required":1}
,"required":{"flexible":1}
,"flexible":{"enough":1}
,"enough":{"accommodate":1}
,"accommodate":{"demands":1,"changing":1}
,"demands":{"different":1,"single":1}
,"customers":{"accommodate":1}
,"changing":{"demands":1}
,"single":{"customer":1,"command":1}
,"customer":{"whose":1}
,"whose":{"requirements":1}
,"requirements":{"may":1}
,"may":{"change":1}
,"change":{"time":1,"modes":1}
,"time":{"typical":1}
,"typical":{"layer":1}
,"fail":{"provide":1}
,"flexibility":{"optimal":1}
,"optimal":{"configuration":1}
,"configuration":{"integrated":1,"different":1}
,"integrated":{"solution":1}
,"solution":{"layer":1}
,"bridge":{"groups":1}
,"groups":{"around":1,"hybrid":1}
,"around":{"zebos-xp":1}
,"zebos-xp":{"hybrid":1,"configured":1}
,"hybrid":{"switch":1,"layer":1}
,"implementation":{"allows":1}
,"allows":{"easy":1}
,"easy":{"configuration":1}
,"combinations":{"routers":1}
,"absolute":{"layer":1}
,"(figure":{"1-1)":1,"1-2)":1}
,"1-1)":{"absolute":1}
,"multiple":{"bridge":1}
,"2\u002Flayer":{"switch":1}
,"1-2)":{"easily":1}
,"easily":{"change":1}
,"modes":{"single":1}
}
;Search.control.loadWordPairs(pairs);
