var pairs =
{
"overview":{"passive-interface":1}
,"passive-interface":{"command":1}
,"command":{"put":1,"interfaces":1,"particular":1,"removes":1,"open":1,"reference":1,"stop":1,"(without":1}
,"put":{"interfaces":1,"passive":1}
,"interfaces":{"particular":1,"put":1,"passive":1,"configuring":1,"difficult":1}
,"particular":{"interface":1}
,"interface":{"passive":1,"name":1,"put":1,"isp":1,"interfaces":1,"name)":1}
,"passive":{"mode":1,"interface":1,"using":1}
,"mode":{"interface":1,"form":1}
,"name":{"address":1}
,"address":{"used":1,"specified":1}
,"used":{"command":1,"solve":1}
,"form":{"command":1}
,"removes":{"interfaces":1,"particular":1}
,"specified":{"removes":1,"details":1}
,"details":{"command":1}
,"open":{"shortest":1}
,"shortest":{"path":1}
,"path":{"first":1}
,"first":{"command":1}
,"reference":{"issue":1}
,"issue":{"passive-interface":1}
,"stop":{"routers":1}
,"routers":{"becoming":1,"large":1}
,"becoming":{"ospf":1}
,"ospf":{"neighbors":1}
,"neighbors":{"particular":1}
,"isp":{"large":1}
,"large":{"enterprise":1,"number":1}
,"enterprise":{"networks":1}
,"networks":{"distribution":1}
,"distribution":{"routers":1}
,"number":{"interfaces":1}
,"configuring":{"passive":1,"interfaces":1}
,"difficult":{"passive-interface":1}
,"(without":{"interface":1}
,"name)":{"used":1}
,"solve":{"problem":1}
,"problem":{"configuring":1}
,"using":{"single":1}
,"single":{"command":1}
}
;Search.control.loadWordPairs(pairs);
