var pairs =
{
"arp":{"command":1,"entry":1,"a.b.c.d":1,"requests":1,"10.10.10.10":1}
,"command":{"create":1,"syntax":1,"mode":1}
,"create":{"static":1}
,"static":{"group":1}
,"group":{"arp":1}
,"entry":{"parameter":1,"command":1,"mac":1,"hhhh.hhhh.hhhh":1}
,"parameter":{"remove":1}
,"remove":{"static":1}
,"syntax":{"arp":1}
,"a.b.c.d":{"mac":1,"parameters":1,"specify":1}
,"mac":{"(alias":1,"specify":1,"(hardware)":1}
,"(alias":{"arp":1}
,"parameters":{"a.b.c.d":1}
,"specify":{"address":1,"mac":1,"response":1}
,"address":{"arp":1,"command":1}
,"(hardware)":{"address":1}
,"hhhh.hhhh.hhhh":{"format":1}
,"format":{"alias":1}
,"alias":{"specify":1,"(config)":1}
,"response":{"arp":1}
,"requests":{"address":1}
,"mode":{"configure":1,"examples":1}
,"configure":{"mode":1,"terminal":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"arp":1}
,"10.10.10.10":{"0010.2355.4566":1}
,"0010.2355.4566":{"alias":1}
}
;Search.control.loadWordPairs(pairs);
