var pairs =
{
"targeted-peer":{"ipv6":1}
,"ipv6":{"command":1,"ldp":1,"x:x":1,"address":1,"3ffe":1}
,"command":{"specify":1,"send":1,"specific":1,"syntax":1,"mode":1}
,"specify":{"targeted":1,"ipv6":1}
,"targeted":{"ipv6":1,"session":1,"hello":1,"peer":1}
,"ldp":{"peer":1,"session":1,"(config-router)":1}
,"peer":{"targeted":1,"command":1}
,"session":{"ldp":1,"non-directly":1}
,"non-directly":{"connected":1}
,"connected":{"lsrs":1}
,"lsrs":{"command":1}
,"send":{"targeted":1}
,"hello":{"messages":1}
,"messages":{"specific":1}
,"specific":{"addresses":1,"targeted":1}
,"addresses":{"command":1}
,"syntax":{"targeted-peer":1}
,"x:x":{":x:x":1}
,":x:x":{"targeted-peer":1,"parameter":1,"specify":1}
,"parameter":{"x:x":1}
,"address":{"targeted":1}
,"mode":{"router":1,"example":1}
,"router":{"mode":1,"ldp":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"(config-router)":{"targeted-peer":1}
}
;Search.control.loadWordPairs(pairs);
