var pairs =
{
"link-state":{"advertising":1,"database":1,"advertisement":1}
,"advertising":{"flooding":1,"router":1}
,"flooding":{"used":1,"link-state-advertisements":1,"two":1,"effectively":1,"procedure":1,"mechanisms":1,"scope":1}
,"used":{"distribute":1,"determine":1,"application-specific":1,"directly":1}
,"distribute":{"synchronize":1,"opaque":1,"information":1}
,"synchronize":{"link-state":1}
,"database":{"ospf":1,"communicate":1,"flooding":1,"description":1,"link":1}
,"ospf":{"routers":1,"autonomous":1,"opaque":1,"functionality":1,"link-state":1,"topology":1,"indirectly":1,"domain":1,"lsas":1}
,"routers":{"flooding":1,"contents":1,"area":1,"directly":1,"link-local":1,"ipv4":1}
,"link-state-advertisements":{"(lsas)":1}
,"(lsas)":{"exchanged":1}
,"exchanged":{"adjacent":1}
,"adjacent":{"ospf":1,"device":1}
,"contents":{"lsa":1}
,"lsa":{"describe":1,"communicate":1,"adjacent":1,"neighbors":1,"traffic":1,"period":1,"arrives":1,"acknowledged":1,"determine":1,"based":1,"header":1,"types":1,"type":1,"summary":1,"routers":1,"designated":1,"inter-area-prefix":1,"abr":1,"inter-area-router":1,"areas":1,"as-external":1,"asbr":1,"intra-area-prefix":1,"n\u002Fa":1,"link-state":1,"originated":1,"hello":1,"neighbor":1,"link":1,"sequence":1,"checksum":1,"length":1}
,"describe":{"individual":1}
,"individual":{"network":1}
,"network":{"component":1,"router":1,"excessive":1,"lsa":1}
,"component":{"(that":1}
,"(that":{"router":1}
,"router":{"link":1,"generates":1,"starts":1,"stores":1,"replaces":1,"encounters":1,"lsa":1,"abr":1,"belongs":1,"segment":1,"identifier":1,"originating":1}
,"link":{"external":1,"state":1,"leave":1,"lsa":1,"link":1,"local":1,"advertising":1}
,"external":{"destination)":1,"lsa":1,"route":1}
,"destination)":{"router":1}
,"generates":{"modifies":1}
,"modifies":{"lsa":1}
,"communicate":{"change":1,"lsa":1}
,"change":{"throughout":1}
,"throughout":{"network":1,"ospf":1}
,"starts":{"process":1,"link":1}
,"process":{"forwarding":1,"called":1}
,"forwarding":{"lsa":1}
,"device":{"upon":1}
,"upon":{"receipt":1}
,"receipt":{"lsa":1,"newly":1}
,"neighbors":{"store":1,"store-and-forward":1,"during":1,"connected":1,"outside":1}
,"store":{"information":1}
,"information":{"link":1,"neighbors":1,"standard":1,"field":1,"throughout":1,"ipv6":1,"area":1,"entire":1}
,"state":{"database":1,"advertisement":1,"update":1,"request":1,"acknowledgement":1,"address":1}
,"store-and-forward":{"activity":1}
,"activity":{"continues":1}
,"continues":{"until":1}
,"until":{"devices":1}
,"devices":{"receive":1}
,"receive":{"update":1}
,"update":{"process":1,"packet":1,"packets":1}
,"called":{"reliable":1}
,"reliable":{"flooding":1}
,"two":{"steps":1,"instances":1}
,"steps":{"taken":1}
,"taken":{"ensure":1}
,"ensure":{"flooding":1,"reliability":1}
,"effectively":{"transmits":1}
,"transmits":{"changes":1}
,"changes":{"without":1}
,"without":{"overloading":1}
,"overloading":{"network":1}
,"excessive":{"quantities":1}
,"quantities":{"lsa":1}
,"traffic":{"router":1}
,"stores":{"lsa":1}
,"period":{"time":1}
,"time":{"propagating":1,"new":1,"seconds":1}
,"propagating":{"information":1}
,"during":{"time":1}
,"new":{"copy":1}
,"copy":{"lsa":1,"outdated":1,"lsdb":1}
,"arrives":{"router":1}
,"replaces":{"stored":1}
,"stored":{"version":1}
,"version":{"however":1}
,"however":{"new":1}
,"outdated":{"discarded":1}
,"discarded":{"ensure":1}
,"reliability":{"link":1}
,"advertisement":{"acknowledged":1,"summary":1,"header":1}
,"acknowledged":{"multiple":1,"separately":1}
,"multiple":{"acknowledgements":1}
,"acknowledgements":{"grouped":1}
,"grouped":{"together":1}
,"together":{"single":1}
,"single":{"acknowledgement":1,"summary-lsa":1}
,"acknowledgement":{"packet":1,"received":1}
,"packet":{"acknowledgement":1,"retransmitted":1,"received":1,"type":1}
,"received":{"original":1,"lsa":1}
,"original":{"link":1}
,"retransmitted":{"link":1}
,"packets":{"flooded":1}
,"flooded":{"throughout":1,"type":1,"totally":1,"stub":1,"according":1}
,"autonomous":{"system":1}
,"system":{"based":1,"type":1,"ospfv3":1}
,"based":{"type":1,"rfc":1}
,"type":{"flooding":1,"lsa":1,"link-state":1,"ipv4":1,"router":1,"network":1,"summary":1,"asbr":1,"external":1,"deprecated":1,"nssa":1,"translated":1,"abr":1,"n\u002Fa":1,"link-local":1,"area-local":1,"opaque":1,"always":1,"function":1,"discovers":1,"describes":1,"requests":1,"provides":1,"acknowledges":1}
,"procedure":{"starts":1}
,"separately":{"router":1}
,"encounters":{"two":1}
,"instances":{"lsa":1}
,"determine":{"recent":1,"instance":1}
,"recent":{"sequence":1,"opaque":1}
,"sequence":{"number":1}
,"number":{"age":1,"assigned":1}
,"age":{"checksum":1,"time":1}
,"checksum":{"fields":1,"checksum":1,"lsa":1}
,"fields":{"used":1}
,"instance":{"recent":1,"lsa":1}
,"opaque":{"lsas":1,"lsa":1}
,"lsas":{"zebos-xp":1,"class":1,"provide":1,"consist":1,"limited":1,"byte":1,"contained":1}
,"zebos-xp":{"supports":1}
,"supports":{"ospf":1}
,"rfc":{"5250":1}
,"5250":{"opaque":1}
,"class":{"lsas":1}
,"provide":{"mechanism":1,"opaque":1}
,"mechanism":{"extend":1}
,"extend":{"ospf":1}
,"functionality":{"opaque":1}
,"consist":{"standard":1}
,"standard":{"lsa":1,"ospf":1}
,"header":{"followed":1,"ospf":1,"shown":1,"field":1}
,"followed":{"32-bit":1}
,"32-bit":{"field":1}
,"field":{"used":1,"may":1,"description":1}
,"application-specific":{"information":1}
,"mechanisms":{"used":1}
,"limited":{"portion":1}
,"portion":{"ospf":1}
,"topology":{"information":1}
,"may":{"used":1}
,"directly":{"ospf":1,"attached":1}
,"indirectly":{"application":1}
,"application":{"distribute":1}
,"domain":{"following":1}
,"following":{"three":1}
,"three":{"opaque":1}
,"types":{"(described":1,"lsa":1,"instead":1}
,"(described":{"table":1}
,"table":{"1-3)":1,"1-3":1}
,"1-3)":{"lsa":1}
,"summary":{"table":1,"lsa":1}
,"1-3":{"summarizes":1}
,"summarizes":{"lsa":1}
,"ipv4":{"name":1,"application-specific":1,"link":1}
,"name":{"ipv6":1,"generated":1}
,"ipv6":{"name":1,"addresses":1,"prefixes":1,"area":1}
,"generated":{"advertises":1}
,"advertises":{"flooded":1}
,"area":{"routers":1,"router":1,"area":1,"belongs":1,"(inter-area":1,"intra-area":1,"sends":1,"type":1}
,"attached":{"interfaces":1}
,"interfaces":{"(intra-area":1}
,"(intra-area":{"routes)":1}
,"routes)":{"indicates":1,"abrs":1}
,"indicates":{"router":1}
,"abr":{"asbr":1,"route":1,"leaves":1}
,"asbr":{"area":1,"summary":1,"backbone":1,"redistributed":1,"inside":1}
,"belongs":{"type":1}
,"designated":{"router":1}
,"segment":{"neighbors":1}
,"connected":{"link":1}
,"leave":{"area":1}
,"inter-area-prefix":{"lsa":1}
,"route":{"neighbors":1,"asbr":1,"entire":1,"redistributed":1}
,"outside":{"area":1}
,"(inter-area":{"routes)":1}
,"abrs":{"originate":1}
,"originate":{"single":1}
,"summary-lsa":{"known":1}
,"known":{"inter-area":1}
,"inter-area":{"destination":1,"routes":1}
,"destination":{"intra-area":1}
,"intra-area":{"routes":1,"inter-area":1}
,"routes":{"advertised":1}
,"advertised":{"area":1,"regular":1}
,"regular":{"areas":1}
,"areas":{"flooded":1,"type":1}
,"totally":{"stub":1}
,"stub":{"areas":1,"transit":1}
,"inter-area-router":{"lsa":1}
,"backbone":{"area":1}
,"sends":{"lsa":1}
,"as-external":{"lsa":1}
,"redistributed":{"external":1,"nssa":1}
,"entire":{"autonomous":1}
,"deprecated":{"n\u002Fa":1}
,"n\u002Fa":{"n\u002Fa":1,"type":1,"link":1,"application-specific":1}
,"nssa":{"external":1,"route":1,"type":1,"nssa":1,"area":1}
,"inside":{"nssa":1}
,"translated":{"type":1}
,"leaves":{"nssa":1}
,"link-local":{"addresses":1,"opaque":1}
,"addresses":{"list":1,"link":1}
,"list":{"ipv6":1}
,"local":{"type":1,"ipv6":1,"copy":1}
,"intra-area-prefix":{"lsa":1}
,"prefixes":{"stub":1}
,"transit":{"networks":1}
,"networks":{"ipv4":1}
,"area-local":{"opaque":1}
,"ospfv3":{"provide":1}
,"instead":{"unknown":1}
,"unknown":{"lsa":1}
,"always":{"accepted":1}
,"accepted":{"local":1}
,"lsdb":{"flooded":1}
,"according":{"flooding":1}
,"scope":{"encoded":1}
,"encoded":{"lsa":1}
,"byte":{"common":1}
,"common":{"header":1}
,"shown":{"intable":1}
,"intable":{"1-4":1}
,"1-4":{"lsa":1}
,"description":{"age":1,"packet":1}
,"seconds":{"lsa":1}
,"originated":{"options":1}
,"options":{"optional":1}
,"optional":{"capabilities":1}
,"capabilities":{"type":1}
,"function":{"performed":1}
,"performed":{"lsa":1}
,"hello":{"packet":1}
,"discovers":{"maintains":1}
,"maintains":{"neighbor":1}
,"neighbor":{"relationships":1,"link":1}
,"relationships":{"database":1}
,"describes":{"lsas":1}
,"contained":{"router\u0027s":1}
,"router\u0027s":{"link":1}
,"request":{"packet":1}
,"requests":{"current":1}
,"current":{"instance":1}
,"provides":{"current":1}
,"acknowledges":{"receipt":1}
,"newly":{"received":1}
,"address":{"link":1}
,"identifier":{"router":1}
,"originating":{"lsa":1}
,"assigned":{"lsa":1}
,"length":{"length":1,"lsa":1}
}
;Search.control.loadWordPairs(pairs);
