var pairs =
{
"peer_prefix_list_set":{"function":1,"(struct":1}
,"function":{"sets":1,"called":1,"successful":1}
,"sets":{"peer\u0027s":1,"prefix-list":1}
,"peer\u0027s":{"prefix-list":1}
,"prefix-list":{"filter":1,"syntax":1,"name":1}
,"filter":{"sets":1,"peer":1,"filter_in":1,"peer-group":1}
,"peer":{"function":1,"bgp":1,"afi":1,"active":1,"peer-group":1,"(-22)":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"prefix-list":1}
,"syntax":{"int":1}
,"int":{"peer_prefix_list_set":1}
,"(struct":{"bgp_peer":1}
,"bgp_peer":{"*peer":1}
,"*peer":{"afi_t":1}
,"afi_t":{"afi":1}
,"afi":{"safi_t":1,"address":1}
,"safi_t":{"safi":1}
,"safi":{"u_int32_t":1,"subsequent":1}
,"u_int32_t":{"direct":1}
,"direct":{"u_int8_t":1,"direction":1,"value":1,"filter_out":1}
,"u_int8_t":{"*name)":1}
,"*name)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"peer":1,"none":1}
,"bgp":{"peer":1}
,"address":{"family":1}
,"family":{"identifier":1}
,"identifier":{"safi":1,"direct":1}
,"subsequent":{"address":1}
,"direction":{"filter":1}
,"filter_in":{"filter_out":1}
,"filter_out":{"name":1,"peer-group":1}
,"name":{"prefix-list":1,"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"bgp_api_set_success":1,"invalid":1}
,"bgp_api_set_success":{"function":1}
,"successful":{"(0)":1}
,"(0)":{"bgp_api_set_err_peer_inactive":1}
,"bgp_api_set_err_peer_inactive":{"peer":1}
,"active":{"(-17)":1}
,"(-17)":{"bgp_api_set_err_invalid_value":1}
,"bgp_api_set_err_invalid_value":{"direct":1}
,"invalid":{"(-2)":1}
,"(-2)":{"bgp_api_set_err_invalid_for_peer_group_member":1}
,"bgp_api_set_err_invalid_for_peer_group_member":{"peer":1}
,"peer-group":{"member":1,"configuration":1}
,"member":{"direct":1,"outgoing":1,"(-18)":1,"change":1}
,"outgoing":{"filter":1}
,"(-18)":{"bgp_api_set_err_peer_filter_conflict":1}
,"bgp_api_set_err_peer_filter_conflict":{"distribute-list":1}
,"distribute-list":{"already":1}
,"already":{"configured":1}
,"configured":{"peer":1}
,"(-22)":{"bgp_api_set_err_peer_group_has_the_flag":1}
,"bgp_api_set_err_peer_group_has_the_flag":{"peer":1}
,"change":{"peer-group":1}
,"configuration":{"(-19)":1}
}
;Search.control.loadWordPairs(pairs);
