var pairs =
{
"show":{"bgp":1}
,"bgp":{"paths":1,"path":1,"(ipv4":1,"(ipv6)":1,"ipv4":1}
,"paths":{"command":1,"show":1,"parameters":1,"address":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"bgp":1}
,"path":{"information":1,"[0x81fa578:0]":1}
,"information":{"command":1}
,"syntax":{"show":1}
,"(ipv4":{"ipv6)":1}
,"ipv6)":{"(unicast":1}
,"(unicast":{"multicast":1,"multicast)":1}
,"multicast":{"paths":1,"multicast":1,"prefixes":1}
,"(ipv6)":{"paths":1}
,"ipv4":{"(unicast":1,"ipv4":1,"routes":1,"unicast":1}
,"multicast)":{"paths":1}
,"parameters":{"ipv4":1}
,"routes":{"ipv6":1,"unicast":1}
,"ipv6":{"ipv6":1,"routes":1}
,"unicast":{"unicast":1,"prefixes":1,"paths":1}
,"prefixes":{"multicast":1,"command":1}
,"mode":{"privileged":1,"exec":1,"example":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"example":{"show":1}
,"address":{"refcnt":1}
,"refcnt":{"path":1}
,"[0x81fa578:0]":{"(239)":1}
}
;Search.control.loadWordPairs(pairs);
