var pairs =
{
"rsvp_api_trunk_set_ext_tunnel_id":{"call":1,"(struct":1}
,"call":{"sets":1,"successful":1}
,"sets":{"extended":1}
,"extended":{"tunnel":1}
,"tunnel":{"trunk":1,"output":1}
,"trunk":{"syntax":1,"rsvp":1,"extended":1}
,"syntax":{"int":1}
,"int":{"rsvp_api_trunk_set_ext_tunnel_id":1}
,"(struct":{"rsvp_trunk":1}
,"rsvp_trunk":{"*trunk":1}
,"*trunk":{"struct":1}
,"struct":{"prefix":1}
,"prefix":{"*id)":1}
,"*id)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"trunk":1,"none":1}
,"rsvp":{"trunk":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"rsvp_err_invalid_args":1}
,"rsvp_err_invalid_args":{"arguments":1}
,"arguments":{"invalid":1}
,"invalid":{"rsvp_success":1}
,"rsvp_success":{"call":1}
}
;Search.control.loadWordPairs(pairs);
