var pairs =
{
"tunnel":{"dmac":1,"dmac\u002Fmac":1,"broadcom":1,"mac":1}
,"dmac":{"command":1,"parameter":1}
,"command":{"destination":1,"supports":1,"remove":1,"syntax":1,"tunneled":1,"mode":1}
,"destination":{"mac":1,"address":1}
,"mac":{"address":1,"tunnel":1,"destination":1,"format":1,"1213.2322.123":1}
,"address":{"tunneled":1,"command":1,"mac":1}
,"tunneled":{"packets":1}
,"packets":{"command":1,"sent":1}
,"supports":{"ip-in-ip":1}
,"ip-in-ip":{"tunneling":1}
,"tunneling":{"broadcom":1}
,"broadcom":{"option":1,"(config)":1,"(config-if)":1}
,"option":{"command":1}
,"remove":{"destination":1}
,"syntax":{"tunnel":1}
,"dmac\u002Fmac":{"mac":1}
,"parameter":{"mac":1}
,"format":{"default":1}
,"default":{"specific":1}
,"specific":{"mac":1}
,"sent":{"destination":1}
,"mode":{"interface":1,"examples":1}
,"interface":{"mode":1,"tunnel":1}
,"examples":{"broadcom":1}
,"(config)":{"interface":1}
,"(config-if)":{"tunnel":1}
}
;Search.control.loadWordPairs(pairs);
