var pairs =
{
"ethernet":{"cfm":1}
,"cfm":{"pbb":1,"frames":1}
,"pbb":{"lmm":1}
,"lmm":{"command":1,"configured":1,"link-level":1,"mpid":1,"frames":1,"observed":1,"transmission":1}
,"command":{"configure":1,"line":1,"syntax":1,"mode":1}
,"configure":{"loss":1}
,"loss":{"measurement":1}
,"measurement":{"messaging":1,"interval":1}
,"messaging":{"(lmm)":1}
,"(lmm)":{"cfm":1}
,"frames":{"host":1,"domain":1,"sent":1,"(rmepid)":1}
,"host":{"remote":1}
,"remote":{"mep":1}
,"mep":{"specified":1,"enter":1,"(mepid)":1,"required":1}
,"specified":{"lmm":1}
,"configured":{"unicast":1}
,"unicast":{"multicast":1,"rmepid":1,"unicast":1,"lmm":1,"frames":1}
,"multicast":{"frames":1,"duration":1,"multicast":1,"lmm":1}
,"domain":{"type":1,"isid":1}
,"type":{"(vlan":1,"initiate":1}
,"(vlan":{"service":1}
,"service":{"instance)":1,"instance":1}
,"instance)":{"measurement":1}
,"interval":{"bridge":1,"lmm":1,"including":1,"100":1,"milliseconds":1,"second":1,"seconds":1,"backbone":1}
,"bridge":{"type":1,"backbone":1,"integer":1,"<1-32>":1,"ethernet":1}
,"initiate":{"lmm":1}
,"link-level":{"mep":1}
,"enter":{"vlan_id":1}
,"vlan_id":{"command":1,"isid":1}
,"line":{"command":1}
,"syntax":{"ethernet":1}
,"mpid":{"mepid":1,"identity":1,"unicast":1,"multicast":1}
,"mepid":{"unicast":1,"multicast":1}
,"rmepid":{"rmepid":1,"duration":1,"remote":1}
,"duration":{"<5-60>":1,"duration":1,"lmm":1,"domain-name":1}
,"<5-60>":{"domain-name":1}
,"domain-name":{"domain_name":1,"name":1,"abc":1,"ipi":1}
,"domain_name":{"((vlan":1}
,"((vlan":{"vlan_id":1}
,"isid":{"isid)":1,"integer":1,"interval":1}
,"isid)":{"((interval":1}
,"((interval":{"4))":1}
,"4))":{"(bridge":1}
,"(bridge":{"<1-32>":1}
,"<1-32>":{"backbone)":1,"command":1}
,"backbone)":{"ethernet":1,"parameters":1}
,"parameters":{"mpid":1}
,"identity":{"source":1}
,"source":{"mep":1}
,"(mepid)":{"multicast":1}
,"sent":{"unicast":1,"rmepid":1}
,"required":{"unicast":1}
,"(rmepid)":{"duration":1}
,"observed":{"seconds":1}
,"seconds":{"<5-60>":1,"backbone":1}
,"name":{"maintenance":1}
,"maintenance":{"domain":1}
,"integer":{"identifies":1,"range":1}
,"identifies":{"associated":1,"vlan":1,"bridge":1}
,"associated":{"service":1}
,"instance":{"vlan":1}
,"vlan":{"integer":1,"interval":1}
,"transmission":{"interval":1}
,"including":{"lmm":1}
,"100":{"milliseconds":1}
,"milliseconds":{"lmm":1}
,"second":{"lmm":1}
,"backbone":{"identifies":1,"bridge":1}
,"range":{"identifies":1}
,"mode":{"exec":1,"privileged":1,"examples":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"examples":{"ethernet":1}
,"abc":{"vlan":1}
,"ipi":{"isid":1}
}
;Search.control.loadWordPairs(pairs);
