var pairs =
{
"permit":{"interface":1,"selective":1}
,"interface":{"port-channel":1,"mode":1,"policy":1}
,"port-channel":{"command":1,"<1-4096>":1,"503":1}
,"command":{"permit":1,"remove":1,"syntax":1,"mode":1}
,"selective":{"access":1}
,"access":{"port":1,"denied":1}
,"port":{"channel":1}
,"channel":{"interfaces":1,"number":1}
,"interfaces":{"general":1}
,"general":{"access":1}
,"denied":{"form":1}
,"form":{"command":1}
,"remove":{"permission":1}
,"permission":{"command":1}
,"syntax":{"permit":1}
,"<1-4096>":{"permit":1,"parameters":1,"port":1}
,"parameters":{"<1-4096>":1}
,"number":{"command":1}
,"mode":{"role":1,"example":1}
,"role":{"interface":1,"name":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"role":1}
,"name":{"dearborn":1}
,"dearborn":{"(config-role)":1}
,"(config-role)":{"interface":1}
,"policy":{"deny":1}
,"deny":{"(config-role-interface)":1}
,"(config-role-interface)":{"permit":1}
}
;Search.control.loadWordPairs(pairs);
