var pairs =
{
"configure":{"terminal":1,"mode":1,"(config-if)":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"router":1,"keychain":1,"privileged":1}
,"mode":{"(config)":1,"(config-router)":1,"return":1,"add":1,"configure":1,"text":1,"rip":1}
,"(config)":{"router":1,"key":1,"interface":1}
,"router":{"rip":1,"mode":1}
,"rip":{"define":1,"routing":1,"process":1,"authentication":1,"packets":1}
,"define":{"rip":1}
,"routing":{"process":1}
,"process":{"enter":1,"(config-router)":1}
,"(config-router)":{"network":1,"redistribute":1,"exit":1}
,"network":{"10.10.10.0\u002F24":1}
,"10.10.10.0\u002F24":{"associate":1,"rip":1}
,"associate":{"network":1}
,"redistribute":{"connected":1}
,"connected":{"enable":1,"routes":1}
,"enable":{"redistributing":1,"ripv2":1}
,"redistributing":{"connected":1}
,"routes":{"(config-router)":1}
,"exit":{"quit":1}
,"quit":{"router":1}
,"return":{"configure":1}
,"key":{"chain":1,"add":1,"(30)":1,"(config-keychain-key)":1,"string":1,"(40)":1}
,"chain":{"moon":1,"mars":1}
,"moon":{"enter":1,"(config-keychain)":1,"(config-keychain-key)":1}
,"keychain":{"management":1}
,"management":{"mode":1}
,"add":{"keys":1,"authentication":1}
,"keys":{"key":1}
,"(config-keychain)":{"key":1}
,"authentication":{"key":1,"eth1":1,"(config-if)":1,"mode":1}
,"(30)":{"key":1}
,"(config-keychain-key)":{"key-string":1,"accept-lifetime":1,"send-lifetime":1,"end":1}
,"key-string":{"ipi":1,"earth":1}
,"ipi":{"specify":1,"received":1,"sent":1}
,"specify":{"password":1,"time":1,"interface":1,"key":1,"authentication":1}
,"password":{"(ipi)":1,"(earth)":1}
,"(ipi)":{"specified":1}
,"specified":{"key":1}
,"accept-lifetime":{"12:00:00":1}
,"12:00:00":{"mar":1}
,"mar":{"2003":1}
,"2003":{"14:00:00":1,"specify":1,"(config-keychain-key)":1,"12:00:00":1,"(config-keychain)":1}
,"14:00:00":{"mar":1}
,"time":{"period":1}
,"period":{"during":1}
,"during":{"authentication":1}
,"string":{"ipi":1,"earth":1}
,"received":{"case":1,"noon":1}
,"case":{"key":1}
,"noon":{"march":1}
,"march":{"march":1,"2003":1,"noon":1}
,"send-lifetime":{"12:00:00":1}
,"sent":{"case":1,"noon":1}
,"(40)":{"key":1}
,"earth":{"specify":1,"received":1,"sent":1}
,"(earth)":{"specified":1}
,"end":{"enter":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"interface":{"eth0":1,"want":1,"specify":1}
,"eth0":{"specify":1,"interface":1}
,"want":{"configure":1}
,"(config-if)":{"rip":1}
,"mars":{"enable":1,"authentication":1}
,"ripv2":{"authentication":1}
,"eth1":{"interface":1}
,"text":{"specify":1,"default":1}
,"packets":{"step":1}
,"step":{"optional":1}
,"optional":{"text":1}
,"default":{"mode":1}
}
;Search.control.loadWordPairs(pairs);
