var pairs =
{
"count-to-infinity":{"distance-vector":1,"problem":1}
,"distance-vector":{"routing":1,"algorithm":1}
,"routing":{"problem":1}
,"problem":{"tells":1,"caused":1,"solved":1}
,"tells":{"path":1}
,"path":{"somewhere":1,"part":1}
,"somewhere":{"know":1}
,"know":{"path":1}
,"part":{"count-to-infinity":1,"segment":1}
,"caused":{"link":1}
,"link":{"failure":1}
,"failure":{"partitions":1}
,"partitions":{"network":1}
,"network":{"two":1,"partitioned":1}
,"two":{"segments":1}
,"segments":{"network":1}
,"partitioned":{"devices":1}
,"devices":{"part":1}
,"segment":{"cannot":1,"distance-vector":1}
,"cannot":{"reach":1}
,"reach":{"devices":1}
,"algorithm":{"adjusts":1}
,"adjusts":{"distance":1}
,"distance":{"value":1}
,"value":{"slowly":1}
,"slowly":{"upwards":1}
,"upwards":{"toward":1}
,"toward":{"infinity":1}
,"infinity":{"count-to-infinity":1}
,"solved":{"split":1}
,"split":{"horizon":1}
,"horizon":{"methods":1}
}
;Search.control.loadWordPairs(pairs);
