var pairs =
{
"hal_mpls_enable_interface":{"function":1,"(struct":1}
,"function":{"enables":1,"fails":1,"succeeds":1}
,"enables":{"interface":1}
,"interface":{"mpls":1,"already":1,"new":1,"identifier":1}
,"mpls":{"forwarding":1}
,"forwarding":{"interface":1}
,"already":{"mpls-enabled":1}
,"mpls-enabled":{"api":1}
,"api":{"used":1}
,"used":{"change":1}
,"change":{"association":1}
,"association":{"label":1}
,"label":{"space":1}
,"space":{"new":1,"bound":1,"identifier":1}
,"new":{"label":1,"ilm":1}
,"bound":{"interface":1}
,"ilm":{"table":1}
,"table":{"created":1}
,"created":{"new":1}
,"identifier":{"syntax":1,"label_space":1,"output":1}
,"syntax":{"int":1}
,"int":{"hal_mpls_enable_interface":1}
,"(struct":{"if_ident":1}
,"if_ident":{"*if_ident":1,"interface":1}
,"*if_ident":{"unsigned":1}
,"unsigned":{"short":1}
,"short":{"label_space)":1}
,"label_space)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"if_ident":1,"none":1}
,"label_space":{"label":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"hal_mpls_interface_err":1}
,"hal_mpls_interface_err":{"function":1}
,"fails":{"hal_success":1}
,"hal_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
