var pairs =
{
"adding":{"deleting":1}
,"deleting":{"bridge":1,"s-vlan":1}
,"bridge":{"vlan":1,"may":1,"ib-beb":1,"vlan-level":1}
,"vlan":{"following":1,"added":1,"i-beb":1}
,"following":{"figure":1}
,"figure":{"displays":1}
,"displays":{"flow":1}
,"flow":{"followed":1}
,"followed":{"bridge":1}
,"added":{"removed":1}
,"removed":{"port":1}
,"port":{"port":1,"type":1,"module":1}
,"type":{"adding":1}
,"s-vlan":{"b-vlan":1,"segments":1}
,"b-vlan":{"port":1,"bridges":1,"segment":1,"bridge":1}
,"module":{"triggers":1}
,"triggers":{"update":1}
,"update":{"database":1}
,"database":{"time":1}
,"time":{"event":1}
,"event":{"adding":1}
,"i-beb":{"bridge":1}
,"may":{"s-vlan":1,"b-vlan":1,"s-vlans\u002Fbridge":1}
,"segments":{"b-vlan":1}
,"bridges":{"b-beb":1}
,"b-beb":{"bridge":1}
,"segment":{"single":1}
,"single":{"b-vlan":1}
,"ib-beb":{"may":1}
,"s-vlans\u002Fbridge":{"(s)":1}
,"(s)":{"b-vlans\u002Fbridge":1}
,"b-vlans\u002Fbridge":{"bridge":1}
,"vlan-level":{"provisioning":1}
,"provisioning":{"applies":1}
,"applies":{"hardware":1}
,"hardware":{"changes":1}
,"changes":{"immediately":1}
,"immediately":{"meaning":1}
,"meaning":{"hal":1}
,"hal":{"messages":1}
,"messages":{"sent":1}
,"sent":{"forwarding":1}
,"forwarding":{"plane":1}
,"plane":{"shown":1}
}
;Search.control.loadWordPairs(pairs);
