var pairs =
{
"nsm_vlan_add_beb_port":{"function":1,"(struct":1}
,"function":{"called":1}
,"called":{"beb":1}
,"beb":{"port":1}
,"port":{"default":1}
,"default":{"vid":1}
,"vid":{"syntax":1,"enum":1,"mode":1}
,"syntax":{"nsm_vlan_add_beb_port":1}
,"(struct":{"interface":1}
,"interface":{"*ifp":1,"vid":1}
,"*ifp":{"nsm_vid_t":1}
,"nsm_vid_t":{"vid":1}
,"enum":{"nsm_vlan_port_mode":1}
,"nsm_vlan_port_mode":{"mode":1,"sub_mode":1}
,"mode":{"enum":1,"sub_mode":1}
,"sub_mode":{"bool_t":1,"output":1}
,"bool_t":{"iterate_members":1,"notify_kernel)":1}
,"iterate_members":{"bool_t":1}
,"notify_kernel)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"none":1}
,"ifp":{"pointer":1}
,"pointer":{"interface":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"result_success":1}
}
;Search.control.loadWordPairs(pairs);
