var pairs =
{
"bfd":{"command":1,"functions":1,"commands":1,"user":1,"echo":1,"transmission":1,"process":1,"slow":1}
,"command":{"api":1,"reference":1,"functions":1}
,"api":{"bfd":1}
,"functions":{"defined":1,"described":1}
,"defined":{"chapter":1}
,"chapter":{"called":1,"function":1}
,"called":{"bfd":1}
,"commands":{"described":1}
,"described":{"bidirectional":1,"chapter":1}
,"bidirectional":{"forwarding":1}
,"forwarding":{"detection":1}
,"detection":{"command":1}
,"reference":{"following":1}
,"following":{"bfd":1}
,"function":{"application":1}
,"application":{"bfd_add_user_session":1}
,"bfd_add_user_session":{"adds":1}
,"adds":{"ipv4":1,"ipv6":1}
,"ipv4":{"bfd":1,"interface":1}
,"user":{"session":1}
,"session":{"bfd_del_user_session":1,"bfd_add_ipv6_user_session":1,"bfd_del_ipv6_user_session":1,"bfd_echo_interval_set":1}
,"bfd_del_user_session":{"deletes":1}
,"deletes":{"ipv4":1,"ipv6":1}
,"bfd_add_ipv6_user_session":{"adds":1}
,"ipv6":{"bfd":1,"interface":1}
,"bfd_del_ipv6_user_session":{"deletes":1}
,"bfd_echo_interval_set":{"sets":1}
,"sets":{"bfd":1,"minimum":1,"multihop":1,"slow":1}
,"echo":{"mode":1}
,"mode":{"transmission":1,"interfaces":1,"setting":1}
,"transmission":{"interval":1,"reception":1}
,"interval":{"single-hop":1,"default":1,"peer":1}
,"single-hop":{"sessions":1}
,"sessions":{"interface":1}
,"interface":{"bfd_echo_interval_unset":1,"bfd_proto_interval_set":1,"bfd_proto_interval_unset":1,"bfd_proto_multihop_interval_set":1,"bfd_proto_multihop_interval_unset":1,"default":1,"bfd_protol_multihop_ipv6_interval_unset":1,"bfd_proto_slow_timer_unset_interface":1}
,"bfd_echo_interval_unset":{"resets":1}
,"resets":{"bfd":1,"multihop":1}
,"default":{"value":1,"values":1}
,"value":{"sessions":1,"hello":1,"particular":1}
,"bfd_proto_interval_set":{"sets":1}
,"minimum":{"bfd":1}
,"reception":{"intervals":1}
,"intervals":{"value":1,"hello":1}
,"hello":{"multiplier":1}
,"multiplier":{"sessions":1,"default":1,"ipv4":1,"ipv6":1}
,"bfd_proto_interval_unset":{"resets":1}
,"values":{"sessions":1,"hello":1,"bfd_protol_multihop_ipv6_interval_set":1,"bfd_echo_mode_set":1}
,"bfd_proto_multihop_interval_set":{"sets":1}
,"multihop":{"interval":1}
,"peer":{"timer":1,"timers":1}
,"timer":{"values":1,"interfaces":1,"value":1,"particular":1}
,"bfd_proto_multihop_interval_unset":{"resets":1}
,"timers":{"hello":1}
,"bfd_protol_multihop_ipv6_interval_set":{"sets":1}
,"bfd_protol_multihop_ipv6_interval_unset":{"resets":1}
,"bfd_echo_mode_set":{"sets":1}
,"interfaces":{"bfd":1}
,"process":{"bfd_echo_mode_unset":1,"bfd_proto_slow_timer_set":1,"bfd_proto_slow_timer_unset":1,"bfd_proto_slow_timer_set_interface":1}
,"bfd_echo_mode_unset":{"removes":1}
,"removes":{"bfd":1}
,"setting":{"interfaces":1}
,"bfd_proto_slow_timer_set":{"sets":1}
,"slow":{"timer":1}
,"bfd_proto_slow_timer_unset":{"removes":1}
,"bfd_proto_slow_timer_set_interface":{"sets":1}
,"particular":{"interface":1}
,"bfd_proto_slow_timer_unset_interface":{"unsets":1}
,"unsets":{"slow":1}
}
;Search.control.loadWordPairs(pairs);
