var pairs =
{
"pim6_api_register_source_address_set":{"function":1,"(u_int32_t":1}
,"function":{"configures":1,"executes":1}
,"configures":{"source":1}
,"source":{"address":1}
,"address":{"register":1,"source":1,"registers":1}
,"register":{"messages":1}
,"messages":{"syntax":1}
,"syntax":{"int":1}
,"int":{"pim6_api_register_source_address_set":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"vrf_id_t":1,"virtual":1}
,"vrf_id_t":{"vrf_id":1}
,"vrf_id":{"struct":1,"vpn":1}
,"struct":{"pal_in6_addr":1}
,"pal_in6_addr":{"*source_addr)":1}
,"*source_addr)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"vrf_id":1}
,"vpn":{"routing\u002Fforwarding":1}
,"routing\u002Fforwarding":{"instance":1}
,"instance":{"source_addr":1}
,"source_addr":{"address":1}
,"registers":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"pim_api_set_err_wrong_vr":1}
,"pim_api_set_err_wrong_vr":{"pim":1}
,"pim":{"master":1,"vrf":1}
,"master":{"found":1}
,"found":{"pim_api_set_err_wrong_vrf":1,"pim_api_set_success":1}
,"pim_api_set_err_wrong_vrf":{"pim":1}
,"vrf":{"interface":1}
,"interface":{"found":1}
,"pim_api_set_success":{"function":1}
,"executes":{"properly":1}
}
;Search.control.loadWordPairs(pairs);
