var pairs =
{
"show":{"running-config":1}
,"running-config":{"aaa":1}
,"aaa":{"command":1,"settings":1,"all)":1}
,"command":{"display":1,"syntax":1,"modes":1}
,"display":{"aaa":1,"configured":1}
,"settings":{"running":1,"command":1}
,"running":{"configuration":1}
,"configuration":{"command":1}
,"syntax":{"show":1}
,"all)":{"parameters":1}
,"parameters":{"display":1}
,"configured":{"default":1}
,"default":{"settings":1}
,"modes":{"executive":1}
,"executive":{"mode":1}
,"mode":{"examples":1}
,"examples":{"show":1}
}
;Search.control.loadWordPairs(pairs);
