var pairs =
{
"primary":{"filter":1}
,"filter":{"command":1,"fixed":1,"style":1,"default":1,"(fixed":1,"lsp":1,"shared-explicit":1}
,"command":{"filter":1,"syntax":1,"mode":1}
,"fixed":{"shared":1,"filter":1,"fixed":1}
,"shared":{"style":1,"filter":1,"reservation":1}
,"style":{"lsp":1,"identifies":1,"designates":1,"used":1,"prevent":1,"default":1}
,"lsp":{"shared":1,"prevent":1,"using":1,"shared-explicit":1,"default":1}
,"identifies":{"shared":1}
,"reservation":{"environment":1,"flows":1,"distinct":1,"request":1}
,"environment":{"creates":1}
,"creates":{"single":1}
,"single":{"reservation":1}
,"flows":{"senders":1}
,"senders":{"mixed":1}
,"mixed":{"fixed":1}
,"designates":{"distinct":1}
,"distinct":{"reservation":1}
,"request":{"created":1}
,"created":{"data":1}
,"data":{"packets":1}
,"packets":{"particular":1}
,"particular":{"sender":1}
,"sender":{"fixed":1}
,"used":{"style":1}
,"prevent":{"rerouting":1,"lsp":1}
,"rerouting":{"lsp":1}
,"using":{"bandwidth":1}
,"bandwidth":{"parameter":1}
,"parameter":{"reset":1}
,"reset":{"configured":1}
,"configured":{"filter":1}
,"default":{"command":1,"fixed":1}
,"syntax":{"primary":1}
,"(fixed":{"shared-explicit)":1}
,"shared-explicit)":{"primary":1,"parameters":1}
,"parameters":{"fixed":1}
,"shared-explicit":{"shared-explicit":1,"filter":1}
,"mode":{"trunk":1,"examples":1}
,"trunk":{"mode":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"rsvp-trunk":1}
,"rsvp-trunk":{"mytrunk":1}
,"mytrunk":{"(config-trunk)":1}
,"(config-trunk)":{"primary":1}
}
;Search.control.loadWordPairs(pairs);
