var pairs =
{
"hold-priority":{"command":1,"value":1,"<0-7>":1,"parameter":1,"(config)":1}
,"command":{"configure":1,"helps":1,"revert":1,"syntax":1,"mode":1}
,"configure":{"hold":1,"terminal":1}
,"hold":{"priority":1}
,"priority":{"value":1,"determines":1,"high":1,"command":1,"highest":1}
,"value":{"trunk":1,"command":1,"hold":1,"once":1,"session":1}
,"trunk":{"case":1}
,"case":{"insufficient":1}
,"insufficient":{"bandwidth":1}
,"bandwidth":{"remove":1,"done":1}
,"remove":{"less":1}
,"less":{"important":1,"likely":1}
,"important":{"existing":1}
,"existing":{"lsp":1}
,"lsp":{"free":1,"holds":1,"configured":1,"less":1,"facility-backup":1}
,"free":{"bandwidth":1}
,"done":{"preempting":1}
,"preempting":{"signaled":1}
,"signaled":{"lsps":1}
,"lsps":{"hold":1}
,"determines":{"degree":1}
,"degree":{"lsp":1}
,"holds":{"onto":1}
,"onto":{"reservation":1}
,"reservation":{"session":1,"command":1}
,"session":{"lsp":1,"configured":1,"preempt":1}
,"configured":{"successfully":1,"hold":1}
,"successfully":{"hold":1}
,"high":{"existing":1}
,"likely":{"give":1}
,"give":{"reservation":1}
,"helps":{"identify":1}
,"identify":{"attributes":1}
,"attributes":{"frr":1}
,"frr":{"backup":1}
,"backup":{"lsp":1}
,"facility-backup":{"protection":1}
,"protection":{"method":1}
,"method":{"parameter":1}
,"parameter":{"command":1,"<0-7>":1}
,"revert":{"default":1}
,"default":{"hold-priority":1,"default":1,"hold":1}
,"syntax":{"hold-priority":1}
,"<0-7>":{"hold-priority":1,"value":1}
,"mode":{"bypass":1,"default":1}
,"bypass":{"mode":1}
,"highest":{"value":1}
,"once":{"session":1}
,"preempt":{"examples":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"rsvp-bypass":1}
,"rsvp-bypass":{"(config-bypass)":1}
,"(config-bypass)":{"hold-priority":1}
}
;Search.control.loadWordPairs(pairs);
