var pairs =
{
"process":{"flow":1}
,"flow":{"configure":1}
,"configure":{"on-demand":1,"supported":1}
,"on-demand":{"session":1,"sessions":1}
,"session":{"commands":1,"interval":1,"intermediate":1,"on-demand":1,"passes":1}
,"commands":{"provided":1,"necessary":1,"configured":1}
,"provided":{"require":1}
,"require":{"enter":1}
,"enter":{"meg":1}
,"meg":{"name":1,"given":1,"ensure":1}
,"name":{"name":1,"interval":1}
,"interval":{"desired":1,"packets":1}
,"desired":{"packets":1}
,"packets":{"options":1,"need":1,"hal":1}
,"options":{"proactive":1}
,"proactive":{"session":1,"sessions":1}
,"need":{"configured":1}
,"configured":{"commands":1,"error":1,"proactive":1}
,"necessary":{"configure":1}
,"supported":{"zebos-xp":1}
,"zebos-xp":{"integrated":1}
,"integrated":{"management":1}
,"management":{"interface":1}
,"interface":{"shell":1}
,"shell":{"(imish)":1}
,"(imish)":{"imish":1}
,"imish":{"uses":1}
,"uses":{"mpls":1,"hal":1,"forward":1}
,"mpls":{"onm":1,"label":1}
,"onm":{"module":1}
,"module":{"manage":1}
,"manage":{"on-demand":1}
,"sessions":{"configuration":1,"maintained":1}
,"configuration":{"complete":1}
,"complete":{"oamd":1}
,"oamd":{"validates":1,"invokes":1,"uses":1,"hal":1}
,"validates":{"meg":1}
,"given":{"commands":1}
,"error":{"returned":1}
,"returned":{"next":1,"operational":1,"attempt":1}
,"next":{"validations":1}
,"validations":{"performed":1}
,"performed":{"tunnel":1}
,"tunnel":{"datalink":1}
,"datalink":{"section":1}
,"section":{"associated":1}
,"associated":{"meg":1,"forward":1,"bidirectional":1}
,"ensure":{"error":1}
,"operational":{"status":1}
,"status":{"required":1}
,"required":{"entity":1}
,"entity":{"down":1}
,"down":{"error":1}
,"attempt":{"made":1}
,"made":{"initiate":1}
,"initiate":{"lm\u002Fdm":1}
,"lm\u002Fdm":{"session":1,"statistics":1}
,"intermediate":{"node":1}
,"node":{"arguments":1}
,"arguments":{"validated":1}
,"validated":{"oamd":1}
,"invokes":{"hal":1}
,"hal":{"api":1,"responsible":1,"forward":1,"updates":1,"computes":1}
,"api":{"start":1,"retrieve":1}
,"start":{"session":1}
,"maintained":{"duration":1,"until":1}
,"duration":{"configured":1}
,"until":{"command":1}
,"command":{"issued":1}
,"issued":{"terminate":1}
,"terminate":{"oamd":1}
,"retrieve":{"lm\u002Fdm":1}
,"statistics":{"send":1}
,"send":{"mplsonm":1}
,"mplsonm":{"display":1}
,"display":{"hal":1}
,"responsible":{"constructing":1}
,"constructing":{"packet":1}
,"packet":{"payload":1}
,"payload":{"attaching":1}
,"attaching":{"gach":1}
,"gach":{"headers":1}
,"headers":{"mpls":1}
,"label":{"stack":1}
,"stack":{"hal":1}
,"forward":{"reverse":1,"request":1}
,"reverse":{"path":1}
,"path":{"information":1,"two-way":1}
,"information":{"uses":1,"oamd":1}
,"request":{"response":1}
,"response":{"packets":1}
,"updates":{"counters":1}
,"counters":{"message":1}
,"message":{"timestamps":1,"computes":1}
,"timestamps":{"message":1}
,"computes":{"total":1,"one-way":1}
,"total":{"transmit":1}
,"transmit":{"loss":1}
,"loss":{"receive":1,"session":1}
,"receive":{"loss":1}
,"passes":{"information":1}
,"one-way":{"delay":1}
,"delay":{"associated":1}
,"two-way":{"round-trip":1}
,"round-trip":{"delays":1}
,"delays":{"associated":1}
,"bidirectional":{"channels":1}
}
;Search.control.loadWordPairs(pairs);
