var pairs =
{
"vlan":{"callbacks":1,"bridge":1,"port":1,"classifier":1}
,"callbacks":{"following":1,"callbacks":1,"description":1}
,"following":{"table":1}
,"table":{"displays":1}
,"displays":{"vlan":1}
,"description":{"add_vlan":1}
,"add_vlan":{"add":1}
,"add":{"vlan":1,"mac-based":1,"subnet-based":1,"protocol-based":1}
,"bridge":{"delete_vlan":1,"set_vlan_port_type":1}
,"delete_vlan":{"delete":1}
,"delete":{"vlan":1,"mac-based":1,"subnet-based":1,"protocol-based":1}
,"set_vlan_port_type":{"vlan":1}
,"port":{"type":1,"add_vlan_to_port":1,"delete_vlan_from_port":1,"set_mac_prio_over":1}
,"type":{"(access\u002Ftrunk\u002Fhybrid)":1}
,"(access\u002Ftrunk\u002Fhybrid)":{"set_default_pvid":1}
,"set_default_pvid":{"default":1}
,"default":{"vlan":1,"pvid":1}
,"add_vlan_to_port":{"add":1}
,"delete_vlan_from_port":{"remove":1}
,"remove":{"vlan":1}
,"set_mac_prio_over":{"mac":1}
,"mac":{"priority":1}
,"priority":{"override":1}
,"override":{"set_dot1q_state":1}
,"set_dot1q_state":{"disable":1}
,"disable":{"dot1q":1}
,"dot1q":{"set_default_pvid":1}
,"pvid":{"vlan_mac_classifier_add":1}
,"vlan_mac_classifier_add":{"add":1}
,"mac-based":{"vlan":1}
,"classifier":{"vlan_ipv4_classifier_add":1,"vlan_proto_classifier_add":1,"vlan_mac_classifier_delete":1,"vlan_ipv4_classifier_delete":1,"vlan_proto_classifier_delete":1}
,"vlan_ipv4_classifier_add":{"add":1}
,"subnet-based":{"vlan":1}
,"vlan_proto_classifier_add":{"add":1}
,"protocol-based":{"vlan":1}
,"vlan_mac_classifier_delete":{"delete":1}
,"vlan_ipv4_classifier_delete":{"delete":1}
,"vlan_proto_classifier_delete":{"delete":1}
}
;Search.control.loadWordPairs(pairs);
