var pairs =
{
"nsm_pvlan_api_host_association_clear_all":{"function":1,"(struct":1}
,"function":{"clears":1,"succeeds":1}
,"clears":{"primary":1}
,"primary":{"secondary":1}
,"secondary":{"vlan":1}
,"vlan":{"configurations":1}
,"configurations":{"host":1}
,"host":{"port":1}
,"port":{"syntax":1}
,"syntax":{"int":1}
,"int":{"nsm_pvlan_api_host_association_clear_all":1}
,"(struct":{"interface":1}
,"interface":{"*ifp)":1,"pointer":1,"found":1}
,"*ifp)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"none":1}
,"ifp":{"interface":1}
,"pointer":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"result_ok":1}
,"result_ok":{"function":1}
,"succeeds":{"nsm_vlan_err_ifp_not_bound":1}
,"nsm_vlan_err_ifp_not_bound":{"nsm":1}
,"nsm":{"local":1}
,"local":{"interface":1}
,"found":{"nsm_pvlan_err_provider_bridge":1}
,"nsm_pvlan_err_provider_bridge":{"nsm_pvlan_err_invalid_mode":1}
,"nsm_pvlan_err_invalid_mode":{"nsm_vlan_err_vlan_not_found":1}
,"nsm_vlan_err_vlan_not_found":{"nsm_pvlan_err_not_secondary_vlan":1}
}
;Search.control.loadWordPairs(pairs);
