var pairs =
{
"hsl_ifmgr_set_duplex":{"function":1,"(hsl_ifindex_t":1}
,"function":{"sets":1}
,"sets":{"duplex":1}
,"duplex":{"mode":1,"hsl_bool":1,"duplex":1}
,"mode":{"interface":1,"send_notification":1}
,"interface":{"syntax":1,"index":1}
,"syntax":{"int":1}
,"int":{"hsl_ifmgr_set_duplex":1,"duplex":1}
,"(hsl_ifindex_t":{"ifindex":1}
,"ifindex":{"int":1,"interface":1}
,"hsl_bool":{"send_notification)":1}
,"send_notification)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifindex":1,"none":1}
,"index":{"duplex":1}
,"send_notification":{"indicates":1}
,"indicates":{"whether":1}
,"whether":{"send":1}
,"send":{"notification":1}
,"notification":{"protocol":1}
,"protocol":{"modules":1}
,"modules":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
}
;Search.control.loadWordPairs(pairs);
