var pairs =
{
"mld":{"snooping":1,"(vrf":1}
,"snooping":{"command":1,"enabled":1,"specified":1,"mld":1,"parameter":1,"(config)":1}
,"command":{"enable":1,"given":1,"globally":1,"syntax":1,"mode":1}
,"enable":{"mld":1}
,"given":{"configure":1,"vlan":1}
,"configure":{"mode":1,"terminal":1}
,"mode":{"mld":1,"configure":1,"interface":1,"vlan":1}
,"enabled":{"switch":1,"vlan":1,"command":1}
,"switch":{"level":1}
,"level":{"command":1,"mld":1}
,"vlan":{"interface":1,"parameter":1}
,"interface":{"level":1,"command":1,"mode":1,"example":1,"vlan1.1":1}
,"parameter":{"command":1,"vrf":1}
,"globally":{"disable":1}
,"disable":{"mld":1}
,"specified":{"interface":1}
,"syntax":{"mld":1}
,"(vrf":{"name":1}
,"name":{"snooping":1,"default":1}
,"vrf":{"specify":1,"name":1}
,"specify":{"vrf":1}
,"default":{"mld":1}
,"example":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"mld":1,"interface":1}
,"vlan1.1":{"(config-if)":1}
,"(config-if)":{"mld":1}
}
;Search.control.loadWordPairs(pairs);
