var pairs =
{
"show":{"running-config":1,"running":1}
,"running-config":{"interface":1}
,"interface":{"ipv6":1,"ifname":1,"eth1":1}
,"ipv6":{"command":1,"protocol":1,"ospf":1,"pim":1,"rip":1,"information":1}
,"command":{"show":1,"syntax":1,"mode":1}
,"running":{"system":1}
,"system":{"status":1}
,"status":{"configuration":1}
,"configuration":{"specified":1}
,"specified":{"ipv6":1}
,"protocol":{"command":1,"independent":1,"(rip)":1}
,"syntax":{"show":1}
,"ifname":{"ipv6":1}
,"ospf":{"show":1,"display":1,"interface":1}
,"pim":{"show":1,"display":1}
,"rip":{"parameters":1,"display":1}
,"parameters":{"ospf":1}
,"display":{"open":1,"protocol":1,"routing":1}
,"open":{"shortest":1}
,"shortest":{"path":1}
,"path":{"first":1}
,"first":{"(ospf)":1}
,"(ospf)":{"ipv6":1}
,"information":{"pim":1,"rip":1,"protocol":1,"command":1}
,"independent":{"multicast":1}
,"multicast":{"(pim)":1}
,"(pim)":{"ipv6":1}
,"routing":{"information":1}
,"(rip)":{"ipv6":1}
,"mode":{"privileged":1,"example":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"example":{"show":1}
,"eth1":{"ipv6":1,"switchport":1}
}
;Search.control.loadWordPairs(pairs);
