var pairs =
{
"neighboring":{"lsr":1}
,"lsr":{"rtr1":1}
,"rtr1":{"commands":1,"router":1,"show":1}
,"commands":{"section":1}
,"section":{"display":1}
,"display":{"graceful":1}
,"graceful":{"restart":1}
,"restart":{"information":1,"state":1}
,"information":{"neighboring":1}
,"router":{"restarted":1}
,"restarted":{"gracefully":1}
,"gracefully":{"rtr1":1}
,"show":{"ldp":1,"mpls":1}
,"ldp":{"graceful-restart":1,"rtr1":1}
,"graceful-restart":{"==================================================================peer":1,"===================================================================peer":1}
,"==================================================================peer":{"address":1}
,"address":{"name":1}
,"name":{"restart":1}
,"state":{"timer":1}
,"timer":{"value":1}
,"value":{"2.3.4.5":1,"1.2.3.4":1}
,"2.3.4.5":{"eth1":1}
,"eth1":{"capable":1,"10.10.10.53":1}
,"capable":{"helper_mode":1,"operational":1}
,"helper_mode":{"115":1}
,"115":{"(re-connect":1,"(recovery":1}
,"(re-connect":{"time)":1}
,"time)":{"===================================================================rtr1":1,"===================================================================after":1}
,"===================================================================rtr1":{"show":1}
,"mpls":{"forwarding-table":1}
,"forwarding-table":{"===================================================================codes":1}
,"===================================================================codes":{"-selected":1}
,"-selected":{"ftn":1}
,"ftn":{"-stale":1,"-bgp":1,"-cli":1,"-ldp":1,"-rsvp-te":1,"-snmp":1,"-igp-shortcut":1,"-mpls-tp":1,"-sr-ospf":1,"-sr-isis":1,"-sr-cli":1,"code":1}
,"-stale":{"ftn":1}
,"-bgp":{"ftn":1}
,"-cli":{"ftn":1}
,"-ldp":{"ftn":1}
,"-rsvp-te":{"ftn":1}
,"-snmp":{"ftn":1}
,"-igp-shortcut":{"-unknown":1}
,"-unknown":{"ftn":1}
,"-mpls-tp":{"map":1}
,"map":{"ftn":1}
,"-sr-ospf":{"ftn":1}
,"-sr-isis":{"ftn":1}
,"-sr-cli":{"ftn":1}
,"code":{"fec":1}
,"fec":{"ftn-id":1}
,"ftn-id":{"tunnel-id":1}
,"tunnel-id":{"pri":1}
,"pri":{"lsp-type":1}
,"lsp-type":{"out-label":1}
,"out-label":{"out-intf":1}
,"out-intf":{"nexthop":1}
,"nexthop":{"2.3.4.5\u002F32":1}
,"2.3.4.5\u002F32":{"lsp_default":1}
,"lsp_default":{"eth1":1,"53121":1}
,"10.10.10.53":{"3.4.5.6\u002F32":1,"20.20.20.0\u002F24":1,"==================================================================after":1}
,"3.4.5.6\u002F32":{"lsp_default":1}
,"53121":{"eth1":1}
,"20.20.20.0\u002F24":{"lsp_default":1}
,"==================================================================after":{"completion":1}
,"completion":{"ldp":1,"rtr2":1}
,"===================================================================peer":{"address":1}
,"(recovery":{"time)":1}
,"===================================================================after":{"completion":1}
,"rtr2":{"show":1}
,"1.2.3.4":{"eth1":1}
,"operational":{"(no":1}
,"(no":{"timers":1}
,"timers":{"running)":1}
,"running)":{"3.4.5.6":1,"===================================================================":1}
,"3.4.5.6":{"eth2":1}
,"eth2":{"capable":1}
}
;Search.control.loadWordPairs(pairs);
