var pairs =
{
"radius":{"source-interface":1,"server":1,"client":1}
,"source-interface":{"command":1,"hostname":1,"parameters":1,"myhost":1}
,"command":{"local":1,"syntax":1,"mode":1}
,"local":{"address":1}
,"address":{"sent":1,"command":1,"hostname":1}
,"sent":{"packets":1}
,"packets":{"radius":1}
,"server":{"parameter":1}
,"parameter":{"clear":1}
,"clear":{"local":1}
,"syntax":{"radius":1}
,"hostname":{"port":1,"specify":1,"format":1}
,"port":{"radius":1,"specify":1,"number":1}
,"parameters":{"hostname":1}
,"specify":{"radius":1}
,"client":{"dotted":1,"port":1}
,"dotted":{"address":1}
,"format":{"port":1}
,"number":{"default":1,"1812":1}
,"default":{"port":1}
,"1812":{"command":1,"(config)":1}
,"mode":{"configure":1,"examples":1}
,"configure":{"mode":1,"terminal":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"radius":1}
,"myhost":{"1812":1}
}
;Search.control.loadWordPairs(pairs);
