var pairs =
{
"isis":{"restart":1,"request":1,"daemon":1}
,"restart":{"suppress-adjacency":1,"suppress":1}
,"suppress-adjacency":{"command":1,"isis":1,"parameters":1,"(config)":1}
,"command":{"enable":1,"syntax":1,"mode":1}
,"enable":{"isis":1}
,"request":{"adjacency":1}
,"adjacency":{"suppressed":1,"configure":1}
,"suppressed":{"isis":1}
,"daemon":{"process":1}
,"process":{"starts":1}
,"starts":{"restarts":1}
,"restarts":{"until":1,"command":1}
,"until":{"link":1}
,"link":{"state":1}
,"state":{"packet":1}
,"packet":{"database":1}
,"database":{"(lspdb)":1}
,"(lspdb)":{"synchronizes":1}
,"synchronizes":{"parameter":1}
,"parameter":{"disable":1}
,"disable":{"suppress-adjacency":1}
,"syntax":{"isis":1}
,"parameters":{"none":1}
,"none":{"default":1}
,"default":{"default":1,"isis":1}
,"mode":{"configure":1,"example":1}
,"configure":{"mode":1,"terminal":1}
,"example":{"following":1,"enables":1}
,"following":{"example":1}
,"enables":{"disables":1}
,"disables":{"isis":1}
,"suppress":{"adjacency":1}
,"terminal":{"(config)":1}
,"(config)":{"isis":1}
}
;Search.control.loadWordPairs(pairs);
