var pairs =
{
"ethernet":{"lmi":1}
,"lmi":{"global":1}
,"global":{"command":1,"(bridge":1,"(config)":1,"bridge":1}
,"command":{"enable":1,"supported":1,"parameter":1,"disable":1,"syntax":1,"mode":1,"executed":1}
,"enable":{"elmi":1}
,"elmi":{"global-level":1,"command":1,"disabled":1,"globally":1}
,"global-level":{"bridge":1}
,"bridge":{"command":1,"default":1,"supported":1,"issue":1,"parameter":1,"configure":1,"(config)":1}
,"supported":{"default":1,"add":1}
,"default":{"bridge":1,"elmi":1,"examples":1}
,"add":{"bridge":1}
,"issue":{"command":1}
,"parameter":{"along":1,"indicate":1,"<1-32>":1}
,"along":{"command":1}
,"disable":{"elmi":1}
,"syntax":{"ethernet":1}
,"(bridge":{"<1-32>":1}
,"<1-32>":{"ethernet":1,"parameters":1,"parameter":1}
,"parameters":{"bridge":1}
,"indicate":{"bridge-group":1,"actual":1}
,"bridge-group":{"parameter":1,"used":1}
,"actual":{"bridge-group":1}
,"used":{"bridging":1}
,"bridging":{"command":1}
,"mode":{"configure":1,"default":1}
,"configure":{"mode":1,"terminal":1}
,"disabled":{"default":1}
,"examples":{"command":1}
,"executed":{"enable":1}
,"globally":{"default":1}
,"terminal":{"(config)":1}
,"(config)":{"ethernet":1}
}
;Search.control.loadWordPairs(pairs);
