var pairs =
{
"show":{"gmrp":1}
,"gmrp":{"timer":1}
,"timer":{"display":1,"values":1,"if_name":1,"eth4":1,"timer":1,"value":1}
,"display":{"gmrp":1}
,"values":{"specified":1,"interface":1}
,"specified":{"interface":1}
,"interface":{"modify":1,"command":1,"eth4":1}
,"modify":{"lines":1}
,"lines":{"displayed":1}
,"displayed":{"(output":1}
,"(output":{"modifier":1,"redirection":1}
,"modifier":{"token)":1}
,"token)":{"save":1,"command":1}
,"save":{"output":1}
,"output":{"file":1,"command":1}
,"file":{"(output":1}
,"redirection":{"token)":1}
,"command":{"syntax":1,"mode":1,"displaying":1}
,"syntax":{"show":1}
,"if_name":{"parameter":1,"displays":1}
,"parameter":{"if_name":1}
,"displays":{"name":1}
,"name":{"interface":1}
,"mode":{"exec":1,"example":1}
,"exec":{"privileged":1,"mode":1}
,"privileged":{"exec":1}
,"example":{"following":1}
,"following":{"output":1}
,"displaying":{"gmrp":1}
,"eth4":{"show":1,"timer":1}
,"value":{"(centiseconds)":1}
,"(centiseconds)":{"------------------------------------------join":1}
,"------------------------------------------join":{"leave":1}
,"leave":{"leave":1,"1000":1}
}
;Search.control.loadWordPairs(pairs);
