var pairs =
{
"rip":{"split-horizon":1}
,"split-horizon":{"command":1,"action":1,"rip":1,"poisoned":1,"parameter":1}
,"command":{"perform":1,"helps":1,"omits":1,"includes":1,"disable":1,"syntax":1,"mode":1}
,"perform":{"split-horizon":1}
,"action":{"interface":1}
,"interface":{"command":1,"mode":1,"eth0":1}
,"helps":{"avoid":1}
,"avoid":{"including":1}
,"including":{"routes":1}
,"routes":{"updates":1,"learned":1,"reachable":1}
,"updates":{"sent":1,"sets":1}
,"sent":{"gateway":1,"neighbor":1}
,"gateway":{"learned":1}
,"learned":{"using":1,"neighbor":1}
,"using":{"split":1,"poisoned":1}
,"split":{"horizon":1}
,"horizon":{"command":1,"poisoned":1}
,"omits":{"routes":1}
,"neighbor":{"updates":1,"using":1}
,"poisoned":{"parameter":1,"rip":1,"performs":1,"reverse":1,"command":1}
,"parameter":{"command":1,"poisoned":1}
,"includes":{"routes":1}
,"sets":{"metrics":1}
,"metrics":{"infinity":1}
,"infinity":{"thus":1}
,"thus":{"advertising":1}
,"advertising":{"routes":1}
,"reachable":{"parameter":1}
,"disable":{"function":1}
,"function":{"command":1}
,"syntax":{"rip":1}
,"performs":{"split-horizon":1}
,"reverse":{"default":1}
,"default":{"split":1}
,"mode":{"interface":1,"examples":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"rip":1}
}
;Search.control.loadWordPairs(pairs);
