var pairs =
{
"configure":{"terminal":1,"mode":1}
,"terminal":{"enter":1}
,"enter":{"configure":1}
,"mode":{"(config)":1,"return":1}
,"(config)":{"route-map":1,"as-path":1,"router":1}
,"route-map":{"mul_inst":1,"multiple":1,"mode":1,"multi_inst":1}
,"mul_inst":{"permit":1,"apply":1}
,"permit":{"define":1,"definition":1}
,"define":{"route-map":1,"routing":1,"neighbor":1}
,"multiple":{"instance":1}
,"instance":{"permit":1}
,"definition":{"sequence":1}
,"sequence":{"number":1}
,"number":{"(config)":1,"200":1,"(config-router)":1}
,"as-path":{"prepend":1}
,"prepend":{"200":1,"number":1}
,"200":{"200":1,"prepend":1,"two":1,"define":1,"(config-router)":1}
,"two":{"times":1}
,"times":{"as_path":1}
,"as_path":{"attribute":1}
,"attribute":{"bgp":1}
,"bgp":{"update":1,"200":1}
,"update":{"message":1}
,"message":{"(config-route-map)":1}
,"(config-route-map)":{"exit":1}
,"exit":{"exit":1,"route-map":1}
,"return":{"configure":1}
,"router":{"bgp":1}
,"routing":{"process":1}
,"process":{"number":1}
,"(config-router)":{"neighbor":1}
,"neighbor":{"172.1.2.111":1,"172.2.4.114":1}
,"172.1.2.111":{"remote-as":1,"address":1}
,"remote-as":{"100":1,"400":1}
,"100":{"define":1,"number":1}
,"address":{"100":1,"400":1}
,"172.2.4.114":{"remote-as":1,"address":1,"route-map":1}
,"400":{"define":1,"number":1}
,"apply":{"route-map":1}
,"multi_inst":{"outbound":1}
,"outbound":{"routes":1}
}
;Search.control.loadWordPairs(pairs);
