var pairs =
{
"associated":{"bidirectional":1,"tunnels":1,"via":1,"east":1,"tunnel":1}
,"bidirectional":{"tunnel":1,"data":1}
,"tunnel":{"associated":1,"reverse":1,"tunnels":1,"associated-group":1,"two":1}
,"tunnels":{"support":1,"forward":1,"associated":1}
,"support":{"bidirectional":1}
,"data":{"flow":1}
,"flow":{"two":1}
,"two":{"unidirectional":1,"tunnels":1}
,"unidirectional":{"tunnels":1,"lsp":1}
,"forward":{"tunnel":1,"component":1,"reverse":1}
,"reverse":{"tunnel":1,"component":1,"components":1}
,"via":{"lsps":1}
,"lsps":{"tunnel":1}
,"associated-group":{"least":1}
,"least":{"unidirectional":1}
,"lsp":{"consists":1}
,"consists":{"forward":1}
,"component":{"reverse":1,"forward":1}
,"components":{"may":1}
,"may":{"traverse":1}
,"traverse":{"either":1}
,"either":{"different":1}
,"different":{"nodes":1,"links":1}
,"nodes":{"different":1,"example":1,"associated":1}
,"links":{"node":1}
,"node":{"link":1,"west":1,"overlapping":1}
,"link":{"nodes":1}
,"example":{"shown":1}
,"shown":{"below":1}
,"below":{"structure":1}
,"structure":{"similar":1}
,"similar":{"co-routed":1}
,"co-routed":{"tunnel":1}
,"east":{"node":1}
,"west":{"node":1}
,"overlapping":{"nodes":1}
}
;Search.control.loadWordPairs(pairs);
