var pairs =
{
"introduction":{"chapter":1}
,"chapter":{"provides":1,"hardware":1,"platform":1}
,"provides":{"overview":1}
,"overview":{"zebos-xp":1,"features":1}
,"zebos-xp":{"integrates":1,"integrated":1,"platform":1,"system":1}
,"integrates":{"various":1}
,"various":{"platforms":1}
,"platforms":{"includes":1,"integration":1}
,"includes":{"overview":1}
,"features":{"platform":1}
,"platform":{"integration":1,"abstraction":1}
,"integration":{"describes":1,"allows":1,"feature":1}
,"describes":{"system":1}
,"system":{"architecture":1,"(os)":1,"forwarding":1}
,"architecture":{"zebos-xp":1}
,"integrated":{"variety":1}
,"variety":{"platforms":1}
,"allows":{"rapidly":1}
,"rapidly":{"configure":1}
,"configure":{"full":1}
,"full":{"metro":1}
,"metro":{"ethernet":1}
,"ethernet":{"switching":1}
,"switching":{"traffic":1}
,"traffic":{"management":1}
,"management":{"solutions":1}
,"solutions":{"without":1}
,"without":{"costly":1}
,"costly":{"software":1}
,"software":{"hardware":1}
,"hardware":{"development":1,"abstraction":1,"chapter":1,"services":1,"operating":1}
,"development":{"associated":1,"zebos-xp":1}
,"associated":{"complex":1}
,"complex":{"device":1}
,"device":{"development":1}
,"feature":{"following":1}
,"following":{"components":1}
,"components":{"hardware":1}
,"abstraction":{"layer":1}
,"layer":{"(hal)":1,"hal":1,"(hsl)":1,"hsl":1,"pal":1,"communicates":1,"socket":1,"figure":1}
,"(hal)":{"control":1,"communicates":1}
,"control":{"plane":1}
,"plane":{"interface":1,"chapter":1,"forwarding":1}
,"interface":{"communicate":1,"hardware":1}
,"communicate":{"hardware":1}
,"hal":{"hardware":1}
,"services":{"layer":1}
,"(hsl)":{"interface":1}
,"operating":{"system":1}
,"(os)":{"communicates":1}
,"communicates":{"directly":1,"operating":1,"control":1}
,"directly":{"control":1}
,"hsl":{"platform":1}
,"forwarding":{"table":1,"plane":1}
,"table":{"updates":1}
,"updates":{"chapter":1}
,"pal":{"socket":1}
,"socket":{"communication":1}
,"communication":{"layer":1}
,"figure":{"1-1":1}
,"1-1":{"shows":1}
,"shows":{"zebos-xp":1}
}
;Search.control.loadWordPairs(pairs);
