var pairs =
{
"aggregate-address":{"x:x":1,"3ffe":1}
,"x:x":{":x:x\u002Fm":1}
,":x:x\u002Fm":{"command":1,"aggregate-address":1,"as-set":1,"summary-only":1,"aggregate":1}
,"command":{"configure":1,"creates":1,"disable":1,"syntax":1,"mode":1}
,"configure":{"bgp":1,"terminal":1}
,"bgp":{"aggregate":1,"routing":1,"routes":1,"100":1}
,"aggregate":{"entries":1,"entry":1,"ipv6":1}
,"entries":{"aggregates":1}
,"aggregates":{"used":1}
,"used":{"minimize":1}
,"minimize":{"size":1}
,"size":{"routing":1,"path":1}
,"routing":{"tables":1,"table":1}
,"tables":{"aggregation":1}
,"aggregation":{"combines":1,"information":1}
,"combines":{"characteristics":1}
,"characteristics":{"several":1}
,"several":{"different":1}
,"different":{"routes":1}
,"routes":{"advertises":1,"available":1,"neighbors":1,"updates":1}
,"advertises":{"single":1,"prefix":1}
,"single":{"route":1}
,"route":{"command":1,"consisting":1}
,"creates":{"aggregate":1}
,"entry":{"bgp":1,"advertising":1}
,"table":{"more-specific":1}
,"more-specific":{"bgp":1,"routes":1}
,"available":{"specified":1}
,"specified":{"range":1}
,"range":{"using":1}
,"using":{"summary-only":1}
,"summary-only":{"parameter":1,"aggregate-address":1,"as-set":1,"filter":1}
,"parameter":{"advertises":1,"creates":1,"reduce":1,"useful":1,"command":1}
,"prefix":{"suppressing":1,"as-set":1}
,"suppressing":{"more-specific":1}
,"neighbors":{"as-set":1}
,"as-set":{"parameter":1,"aggregate-address":1,"summary-only":1,"parameters":1,"generate":1}
,"advertising":{"path":1}
,"path":{"route":1,"information":1}
,"consisting":{"elements":1}
,"elements":{"contained":1}
,"contained":{"paths":1}
,"paths":{"summarized":1,"aggregated":1}
,"summarized":{"as-set":1}
,"reduce":{"size":1}
,"information":{"listing":1,"results":1,"parameter":1,"summary-only":1}
,"listing":{"number":1}
,"number":{"once":1}
,"once":{"even":1}
,"even":{"included":1}
,"included":{"multiple":1}
,"multiple":{"paths":1}
,"aggregated":{"as-set":1}
,"useful":{"aggregation":1}
,"results":{"incomplete":1}
,"incomplete":{"path":1}
,"disable":{"function":1}
,"function":{"command":1}
,"syntax":{"aggregate-address":1}
,"parameters":{"x:x":1}
,"ipv6":{"prefix":1,"(config-router-af)":1}
,"generate":{"path":1}
,"filter":{"specific":1}
,"specific":{"routes":1}
,"updates":{"command":1}
,"mode":{"address":1,"default":1}
,"address":{"family":1}
,"family":{"mode":1}
,"default":{"disabled":1}
,"disabled":{"examples":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"router":{"bgp":1}
,"100":{"(config-router)":1}
,"(config-router)":{"neighbor":1,"address-family":1}
,"neighbor":{"2.2.2.2":1,"3.3.3.3":1}
,"2.2.2.2":{"remote-as":1}
,"remote-as":{"100":1,"200":1}
,"3.3.3.3":{"remote-as":1}
,"200":{"(config-router)":1}
,"address-family":{"ipv6":1}
,"(config-router-af)":{"aggregate-address":1}
,"3ffe":{":\u002F32":1}
,":\u002F32":{"as-set":1}
}
;Search.control.loadWordPairs(pairs);
