var pairs =
{
"bgp":{"extended":1,"speakers":1}
,"extended":{"community":1,"range":1}
,"community":{"attribute":1,"value":1,"transitive":1,"type":1}
,"attribute":{"bgp":1,"provides":1,"support":1}
,"provides":{"mechanism":1,"extended":1,"means":1}
,"mechanism":{"labeling":1}
,"labeling":{"information":1}
,"information":{"carried":1}
,"carried":{"bgp-4":1}
,"bgp-4":{"provides":1}
,"range":{"routes":1}
,"routes":{"addition":1}
,"addition":{"type":1}
,"type":{"field":1,"four-byte":1}
,"field":{"allows":1}
,"allows":{"policy":1}
,"policy":{"usage":1}
,"usage":{"based":1}
,"based":{"application":1}
,"application":{"community":1}
,"value":{"used":1}
,"used":{"provides":1}
,"means":{"specify":1}
,"specify":{"whether":1}
,"whether":{"particular":1}
,"particular":{"community":1}
,"transitive":{"non-transitive":1}
,"non-transitive":{"across":1}
,"across":{"autonomous":1}
,"autonomous":{"system":1}
,"system":{"(as)":1}
,"(as)":{"boundary":1}
,"boundary":{"supported":1}
,"supported":{"opaque":1}
,"opaque":{"extended":1}
,"four-byte":{"specific":1,"numbers":1}
,"specific":{"extended":1}
,"support":{"bgp":1}
,"speakers":{"four-byte":1}
}
;Search.control.loadWordPairs(pairs);
