var pairs =
{
"isis_net_unset":{"call":1,"(u_int32_t":1}
,"call":{"implements":1,"successful":1}
,"implements":{"parameter":1}
,"parameter":{"net":1}
,"net":{"command":1,"network":1,"invalid":1}
,"command":{"unconfigure":1}
,"unconfigure":{"network":1}
,"network":{"entity":1}
,"entity":{"title":1}
,"title":{"syntax":1,"string":1}
,"syntax":{"int":1}
,"int":{"isis_net_unset":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1,"tag":1}
,"char":{"*tag":1,"*net)":1}
,"*tag":{"char":1}
,"*net)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1,"isis_api_set_err_vr_not_exist":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"tag":{"is-is":1,"net":1,"isis_api_set_err_net_wrong_format":1}
,"is-is":{"instance":1}
,"instance":{"area":1,"exist":1}
,"area":{"tag":1,"address":1}
,"string":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"isis_api_set_err_vr_not_exist":{"exist":1}
,"exist":{"isis_api_set_err_instance_not_exist":1,"given":1}
,"isis_api_set_err_instance_not_exist":{"is-is":1}
,"given":{"tag":1}
,"isis_api_set_err_net_wrong_format":{"format":1}
,"format":{"net":1}
,"invalid":{"isis_api_set_err_net_invalid_length":1}
,"isis_api_set_err_net_invalid_length":{"length":1}
,"length":{"area":1}
,"address":{"less":1,"configured":1}
,"less":{"octets":1}
,"octets":{"octets":1,"isis_api_set_err_system_id_not_configured":1}
,"isis_api_set_err_system_id_not_configured":{"system":1}
,"system":{"area":1,"matched":1}
,"configured":{"isis_api_set_err_system_id_not_mathced":1}
,"isis_api_set_err_system_id_not_mathced":{"system":1}
,"matched":{"existing":1}
,"existing":{"nets":1}
,"nets":{"isis_api_set_success":1}
,"isis_api_set_success":{"call":1}
}
;Search.control.loadWordPairs(pairs);
