var pairs =
{
"overview":{"zebos-xp":1}
,"zebos-xp":{"provides":1,"daemons":1,"support":1,"component":1,"comes":1}
,"provides":{"platform":1}
,"platform":{"independence":1,"abstraction":1,"functions":1,"isolate":1}
,"independence":{"utilizing":1}
,"utilizing":{"platform":1}
,"abstraction":{"layer":1}
,"layer":{"(pal)":1}
,"(pal)":{"collections":1}
,"collections":{"api":1}
,"api":{"functions":1}
,"functions":{"supported":1,"implemented":1}
,"supported":{"platform":1}
,"implemented":{"system":1}
,"system":{"services":1,"pal":1}
,"services":{"platform":1}
,"isolate":{"zebos-xp":1}
,"daemons":{"operating":1}
,"operating":{"system":1,"systems":1}
,"pal":{"allows":1,"module":1,"modules":1}
,"allows":{"zebos-xp":1}
,"support":{"number":1}
,"number":{"operating":1}
,"systems":{"management":1,"porting":1}
,"management":{"protocols":1}
,"protocols":{"moreover":1}
,"moreover":{"complexity":1}
,"complexity":{"component":1}
,"component":{"handled":1,"just":1}
,"handled":{"pal":1}
,"module":{"allows":1,"fulfills":1,"common":1}
,"just":{"call":1}
,"call":{"compile":1,"zebos-xp":1}
,"compile":{"time":1}
,"time":{"options":1}
,"options":{"link":1}
,"link":{"appropriate":1}
,"appropriate":{"pal":1}
,"fulfills":{"call":1}
,"comes":{"production-quality":1}
,"production-quality":{"fully-tested":1}
,"fully-tested":{"pal":1}
,"common":{"operating":1}
,"porting":{"efforts":1}
,"efforts":{"non-supported":1}
,"non-supported":{"platforms":1}
,"platforms":{"modeled":1}
,"modeled":{"pal":1}
}
;Search.control.loadWordPairs(pairs);
