var pairs =
{
"weight":{"command":1,"value":1,"<0-4294967295>":1,"(<0-4294967295>":1,"400":1}
,"command":{"weights":1,"first":1,"specifies":1,"valid":1,"delete":1,"syntax":1,"mode":1}
,"weights":{"routing":1}
,"routing":{"table":1,"protocol":1,"process":1}
,"table":{"weight":1}
,"value":{"used":1,"preferred":1,"command":1}
,"used":{"assist":1}
,"assist":{"best":1}
,"best":{"path":1}
,"path":{"selection":1}
,"selection":{"assigned":1}
,"assigned":{"locally":1}
,"locally":{"router":1}
,"router":{"several":1}
,"several":{"routes":1}
,"routes":{"common":1,"higher":1,"routing":1,"apply":1}
,"common":{"destination":1}
,"destination":{"routes":1}
,"higher":{"weight":1}
,"preferred":{"command":1}
,"first":{"match":1}
,"match":{"clause":1,"commands":1,"command":1,"criteria":1,"defined":1,"as-path":1}
,"clause":{"match":1}
,"commands":{"conditions":1}
,"conditions":{"redistributing":1}
,"redistributing":{"routes":1}
,"protocol":{"match":1}
,"specifies":{"match":1,"redistribution":1}
,"criteria":{"redistribution":1,"met":1,"routed":1}
,"redistribution":{"allowed":1,"actions":1}
,"allowed":{"current":1}
,"current":{"route-map":1}
,"route-map":{"command":1,"mode":1,"rmap1":1}
,"actions":{"performed":1}
,"performed":{"match":1}
,"met":{"command":1}
,"valid":{"bgp":1}
,"bgp":{"parameter":1}
,"parameter":{"command":1,"<0-4294967295>":1}
,"delete":{"entry":1}
,"entry":{"command":1}
,"syntax":{"weight":1}
,"<0-4294967295>":{"weight":1,"specify":1}
,"(<0-4294967295>":{"parameter":1}
,"specify":{"weight":1}
,"mode":{"route-map":1,"examples":1}
,"examples":{"following":1}
,"following":{"configuration":1}
,"configuration":{"routes":1}
,"apply":{"access-list":1}
,"access-list":{"weight":1}
,"400":{"packets":1}
,"packets":{"match":1}
,"defined":{"criteria":1}
,"routed":{"normal":1}
,"normal":{"routing":1}
,"process":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"route-map":1}
,"rmap1":{"permit":1}
,"permit":{"(config-route-map)":1}
,"(config-route-map)":{"match":1,"weight":1}
,"as-path":{"(config-route-map)":1}
}
;Search.control.loadWordPairs(pairs);
