var pairs =
{
"isis_area_addr":{"data":1,"{u_char":1}
,"data":{"structure":1}
,"structure":{"contains":1,"*\u002F}":1}
,"contains":{"is-is":1}
,"is-is":{"manual":1}
,"manual":{"area":1}
,"area":{"address":1,"addresses":1}
,"address":{"information":1,"[isis_area_addr_len_max]":1}
,"information":{"definition":1}
,"definition":{"struct":1}
,"struct":{"isis_area_addr":1}
,"{u_char":{"length":1}
,"length":{"u_char":1}
,"u_char":{"address":1}
,"[isis_area_addr_len_max]":{"\u002F*manual":1,"u_int32_t":1}
,"\u002F*manual":{"area":1}
,"addresses":{"*\u002Fstruct":1}
,"*\u002Fstruct":{"isis_recv_area_addr":1}
,"isis_recv_area_addr":{"{u_char":1}
,"u_int32_t":{"count":1}
,"count":{"\u002F*count":1}
,"\u002F*count":{"lsp\u0027s":1}
,"lsp\u0027s":{"using":1}
,"using":{"structure":1}
}
;Search.control.loadWordPairs(pairs);
