var pairs =
{
"ospf_vlink_message_digest_key_unset":{"function":1,"(u_int32_t":1}
,"function":{"deletes":1,"called":1,"succeeds":1}
,"deletes":{"md5":1}
,"md5":{"authentication":1}
,"authentication":{"key":1}
,"key":{"virtual":1,"identifier":1,"exist":1}
,"virtual":{"interface":1,"router":1,"link":1}
,"interface":{"function":1,"parameters":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"area":1}
,"area":{"virtual-link":1,"network":1}
,"virtual-link":{"message-digest-key":1}
,"message-digest-key":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf_vlink_message_digest_key_unset":1,"proc_id":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"int":1,"virtual":1}
,"proc_id":{"struct":1,"process":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"area_id":1,"peer_id":1}
,"area_id":{"struct":1,"area":1}
,"peer_id":{"u_char":1,"neighbor":1}
,"u_char":{"key_id)":1}
,"key_id)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1,"configured":1}
,"router":{"non-virtual-router":1,"key_id":1,"found":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"proc_id":1}
,"process":{"ospf":1,"valid":1,"exist":1}
,"ospf":{"instance":1}
,"instance":{"65535>":1}
,"65535>":{"area_id":1}
,"network":{"belongs":1}
,"belongs":{"peer_id":1}
,"neighbor":{"router":1}
,"key_id":{"key":1}
,"identifier":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf_api_set_success":1}
,"ospf_api_set_success":{"function":1}
,"succeeds":{"ospf_api_set_err_process_id_invalid":1}
,"ospf_api_set_err_process_id_invalid":{"given":1}
,"given":{"process":1,"virtual":1}
,"valid":{"(outside":1}
,"(outside":{"65535":1}
,"65535":{"bounds)":1}
,"bounds)":{"ospf_api_set_err_process_not_exist":1}
,"ospf_api_set_err_process_not_exist":{"given":1}
,"exist":{"ospf_api_set_err_vlink_not_exist":1,"ospf_api_set_err_if_param_not_configured":1,"ospf_api_set_err_vr_not_exist":1}
,"ospf_api_set_err_vlink_not_exist":{"given":1}
,"link":{"exist":1}
,"ospf_api_set_err_if_param_not_configured":{"specified":1}
,"specified":{"interface":1,"key":1}
,"configured":{"ospf_api_set_err_md5_key_not_exist":1}
,"ospf_api_set_err_md5_key_not_exist":{"specified":1}
,"ospf_api_set_err_vr_not_exist":{"virtual":1}
}
;Search.control.loadWordPairs(pairs);
