var pairs =
{
"features":{"following":1,"soam":1}
,"following":{"features":1}
,"soam":{"full":1}
,"full":{"implementation":1}
,"implementation":{"mef":1}
,"mef":{"(service":1}
,"(service":{"oam)":1}
,"oam)":{"fault":1}
,"fault":{"management":1}
,"management":{"used":1}
,"used":{"detect":1}
,"detect":{"verify":1}
,"verify":{"localize":1}
,"localize":{"notify":1}
,"notify":{"faults":1}
,"faults":{"performance":1}
,"performance":{"monitoring":1,"parameter":1}
,"monitoring":{"including":1}
,"including":{"performance":1,"discovering":1}
,"parameter":{"measurements":1}
,"measurements":{"auto-discovery":1}
,"auto-discovery":{"including":1}
,"discovering":{"service":1}
,"service":{"aware":1,"oam":1}
,"aware":{"network":1}
,"network":{"elements":1}
,"elements":{"within":1}
,"within":{"provider":1}
,"provider":{"networks":1}
,"networks":{"supports":1}
,"supports":{"intra-and":1}
,"intra-and":{"inter-provider":1}
,"inter-provider":{"service":1}
}
;Search.control.loadWordPairs(pairs);
