var pairs =
{
"mstp_api_revision_number":{"function":1,"(char":1}
,"function":{"sets":1,"succeeds":1,"fails":1}
,"sets":{"configuration":1}
,"configuration":{"revision":1}
,"revision":{"level":1}
,"level":{"bridge":1,"used":1}
,"bridge":{"recomputes":1,"rev_num":1,"output":1}
,"recomputes":{"related":1}
,"related":{"port":1}
,"port":{"roles":1}
,"roles":{"syntax":1}
,"syntax":{"int":1}
,"int":{"mstp_api_revision_number":1}
,"(char":{"*name":1}
,"*name":{"u_int16_t":1}
,"u_int16_t":{"rev_num)":1}
,"rev_num)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"name":1,"none":1}
,"name":{"name":1,"bridge":1}
,"rev_num":{"mstp":1}
,"mstp":{"configuration":1}
,"used":{"bridge":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"result_ok":1}
,"result_ok":{"function":1}
,"succeeds":{"result_error":1}
,"result_error":{"function":1}
}
;Search.control.loadWordPairs(pairs);
