var pairs =
{
"lldp":{"mib":1,"maintains":1,"client":1,"part":1,"implementation":1,"uses":1,"state":1,"local":1,"receive":1}
,"mib":{"lldp":1,"information":1,"implementation":1,"module":1,"retrieves":1,"entities":1}
,"maintains":{"two":1}
,"two":{"maintenance":1}
,"maintenance":{"information":1}
,"information":{"bases":1,"retrieved":1,"protocol":1,"remote":1,"lldp":1}
,"bases":{"(mib)":1}
,"(mib)":{"local":1}
,"local":{"lldp":1,"mib":1}
,"retrieved":{"mib":1,"lldpdu":1}
,"implementation":{"nsm":1,"includes":1,"lldp":1}
,"nsm":{"remote":1,"callback":1}
,"remote":{"lldp":1,"lldpdu":1}
,"lldpdu":{"received":1}
,"received":{"remote":1,"lldp":1}
,"client":{"implemented":1}
,"implemented":{"zebos-xp":1}
,"zebos-xp":{"lldp":1}
,"part":{"onmd":1}
,"onmd":{"daemon":1}
,"daemon":{"lldp":1}
,"includes":{"protocol":1}
,"protocol":{"lldp":1,"state":1}
,"module":{"files":1}
,"files":{"lldp":1}
,"uses":{"nsm":1}
,"callback":{"apis":1}
,"apis":{"retrieve":1}
,"retrieve":{"parameters":1}
,"parameters":{"local":1,"stored":1}
,"state":{"machines":1,"machine":1}
,"machines":{"work":1}
,"work":{"independently":1}
,"independently":{"unique":1}
,"unique":{"socket":1}
,"socket":{"implementation":1}
,"retrieves":{"information":1}
,"machine":{"statistics":1}
,"statistics":{"variables":1}
,"variables":{"tlv":1,"detailed":1}
,"tlv":{"parameters":1}
,"stored":{"remote":1}
,"receive":{"state":1}
,"detailed":{"information":1}
,"entities":{"supported":1}
,"supported":{"refer":1}
,"refer":{"ieee":1}
,"ieee":{"802.1ab-2005":1}
,"802.1ab-2005":{"station":1}
,"station":{"media":1}
,"media":{"access":1}
,"access":{"control":1}
,"control":{"connectivity":1}
,"connectivity":{"discovery":1}
,"discovery":{"specification":1}
,"specification":{"clause":1}
}
;Search.control.loadWordPairs(pairs);
