var pairs =
{
"mstp_api_delete_instance":{"function":1,"(char":1}
,"function":{"deletes":1,"succeeds":1,"fails":1}
,"deletes":{"bridge":1}
,"bridge":{"instance":1,"cannot":1}
,"instance":{"syntax":1,"instance":1,"identifier":1,"cannot":1}
,"syntax":{"int":1}
,"int":{"mstp_api_delete_instance":1,"instance)":1}
,"(char":{"*name":1}
,"*name":{"int":1}
,"instance)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"name":1,"none":1}
,"name":{"name":1,"bridge":1}
,"identifier":{"<1-63>":1}
,"<1-63>":{"constants":1}
,"constants":{"mstpd\u002Fmstp_config.h":1}
,"mstpd\u002Fmstp_config.h":{"spbm_instance_id":1}
,"spbm_instance_id":{"shortest":1}
,"shortest":{"path":1}
,"path":{"bridging":1}
,"bridging":{"-mac":1}
,"-mac":{"mstp_te_mstid":1}
,"mstp_te_mstid":{"traffic":1}
,"traffic":{"engineering":1}
,"engineering":{"msti":1}
,"msti":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"result_ok":1}
,"result_ok":{"function":1}
,"succeeds":{"result_error":1}
,"result_error":{"function":1}
,"fails":{"mstp_err_bridge_not_found":1}
,"mstp_err_bridge_not_found":{"bridge":1}
,"cannot":{"found":1}
,"found":{"mstp_err_instance_not_found":1}
,"mstp_err_instance_not_found":{"instance":1}
}
;Search.control.loadWordPairs(pairs);
