var pairs =
{
"cfm_vsm_send":{"function":1,"(struct":1}
,"function":{"called":1}
,"called":{"ethernet":1}
,"ethernet":{"cfm":1}
,"cfm":{"vsm":1}
,"vsm":{"command":1}
,"command":{"send":1}
,"send":{"vendor-specific":1}
,"vendor-specific":{"(vsm)":1}
,"(vsm)":{"oam":1}
,"oam":{"frames":1}
,"frames":{"syntax":1}
,"syntax":{"include":1}
,"include":{"cfm_vsm.h":1}
,"cfm_vsm.h":{"s_int32_t":1}
,"s_int32_t":{"cfm_vsm_send":1}
,"(struct":{"onmd_bridge":1}
,"onmd_bridge":{"*bridge":1}
,"*bridge":{"u_int8_t":1}
,"u_int8_t":{"*md_name":1}
,"*md_name":{"u_int16_t":1}
,"u_int16_t":{"vid":1}
,"vid":{"u_int32_t":1,"vlan":1}
,"u_int32_t":{"mepid":1,"rmepid)":1}
,"mepid":{"u_int32_t":1,"source":1}
,"rmepid)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bridge":1,"none":1}
,"bridge":{"bridge":1,"source":1,"found":1}
,"source":{"mep":1}
,"mep":{"resides":1,"<1-8191>":1,"found":1,"active":1}
,"resides":{"md_name":1}
,"md_name":{"maintenance":1}
,"maintenance":{"domain":1}
,"domain":{"name":1}
,"name":{"vid":1}
,"vlan":{"<1-4094>":1}
,"<1-4094>":{"mepid":1}
,"<1-8191>":{"rmepid":1,"output":1}
,"rmepid":{"remote":1}
,"remote":{"mep":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"cfm_bridge_not_found":1}
,"cfm_bridge_not_found":{"bridge":1}
,"found":{"list":1,"cfm_domain_not_found":1,"cfm_ma_not_found":1,"cfm_mep_not_found":1,"cfm_api_mep_not_active":1}
,"list":{"found":1}
,"cfm_domain_not_found":{"found":1}
,"cfm_ma_not_found":{"found":1}
,"cfm_mep_not_found":{"mep":1}
,"cfm_api_mep_not_active":{"mep":1}
,"active":{"cfm_memory_not_allocated":1}
,"cfm_memory_not_allocated":{"memory":1}
,"memory":{"allocation":1}
,"allocation":{"fails":1}
,"fails":{"cfm_rmep_not_found":1}
,"cfm_rmep_not_found":{"rmep":1}
,"rmep":{"found":1}
}
;Search.control.loadWordPairs(pairs);
