var pairs =
{
"vr\u002Fvrf":{"namespaces":1}
,"namespaces":{"multiple":1,"vrf":1}
,"multiple":{"forward":1}
,"forward":{"information":1}
,"information":{"base":1}
,"base":{"(fib)":1,"zebos-xp":1}
,"(fib)":{"tables":1}
,"tables":{"x86":1}
,"x86":{"platforms":1}
,"platforms":{"(using":1}
,"(using":{"linux":1}
,"linux":{"kernel":1,"namespaces":1,"stack":1}
,"kernel":{"versions":1}
,"versions":{"3.0":1}
,"3.0":{"later)":1}
,"later)":{"supported":1}
,"supported":{"using":1}
,"using":{"linux":1,"namespace":1}
,"vrf":{"essentially":1,"routes":1}
,"essentially":{"mapped":1}
,"mapped":{"network":1}
,"network":{"namespace":1}
,"namespace":{"forwarding":1,"concept":1}
,"forwarding":{"information":1}
,"zebos-xp":{"supports":1}
,"supports":{"segregation":1}
,"segregation":{"vrf":1}
,"routes":{"control":1}
,"control":{"plane":1}
,"plane":{"level":1}
,"level":{"extended":1}
,"extended":{"fib":1}
,"fib":{"linux":1}
,"stack":{"using":1}
}
;Search.control.loadWordPairs(pairs);
