var pairs =
{
"lldp":{"tx-max-credit":1,"frames":1,"agent":1}
,"tx-max-credit":{"command":1,"<1-10>":1,"parameters":1,"maximum":1,"(lldp-agent)":1}
,"command":{"maximum":1,"syntax":1,"mode":1}
,"maximum":{"value":1}
,"value":{"transmission":1,"command":1,"default":1}
,"transmission":{"credit":1}
,"credit":{"signifies":1,"default":1}
,"signifies":{"number":1}
,"number":{"consecutive":1}
,"consecutive":{"lldp":1}
,"frames":{"transmitted":1}
,"transmitted":{"form":1}
,"form":{"command":1}
,"default":{"value":1}
,"syntax":{"lldp":1}
,"<1-10>":{"lldp":1,"(lldp-agent)":1}
,"parameters":{"tx-max-credit":1}
,"mode":{"lldp":1,"examples":1}
,"agent":{"mode":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"interface":{"eth0":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"lldp-agent":1}
,"lldp-agent":{"(lldp-agent)":1}
,"(lldp-agent)":{"lldp":1,"exit":1}
}
;Search.control.loadWordPairs(pairs);
