var pairs =
{
"bridge-group":{"priority":1,"<1-32>":1}
,"priority":{"command":1,"bridge":1,"indicates":1,"<0-240>":1,"parameters":1,"range":1,"values":1,"(config)":1}
,"command":{"port":1,"syntax":1,"mode":1}
,"port":{"priority":1}
,"bridge":{"lower":1,"becoming":1,"group":1}
,"lower":{"priority":1}
,"indicates":{"greater":1}
,"greater":{"likelihood":1}
,"likelihood":{"bridge":1,"interface":1}
,"becoming":{"root":1,"root)":1}
,"root":{"command":1}
,"syntax":{"bridge-group":1}
,"<1-32>":{"priority":1,"specify":1}
,"<0-240>":{"bridge-group":1,"specify":1}
,"parameters":{"<1-32>":1}
,"specify":{"bridge":1,"port":1}
,"group":{"<0-240>":1}
,"range":{"lower":1}
,"interface":{"becoming":1,"mode":1,"eth1":1}
,"root)":{"priority":1}
,"values":{"increments":1}
,"increments":{"default":1}
,"default":{"default":1,"priority":1}
,"mode":{"interface":1,"example":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth1":{"(config-if)":1}
,"(config-if)":{"bridge-group":1}
}
;Search.control.loadWordPairs(pairs);
