var pairs =
{
"satop":{"overview":1,"creates":1}
,"overview":{"telecoms":1}
,"telecoms":{"based":1}
,"based":{"time":1}
,"time":{"division":1}
,"division":{"multiplexing":1}
,"multiplexing":{"(tdm)":1}
,"(tdm)":{"technologies":1}
,"technologies":{"(t1\u002Fe1":1,"support":1}
,"(t1\u002Fe1":{"sonet\u002Fsdh)":1}
,"sonet\u002Fsdh)":{"technology":1}
,"technology":{"best":1}
,"best":{"suited":1}
,"suited":{"transmit":1}
,"transmit":{"constant":1}
,"constant":{"bit":1}
,"bit":{"rate":1}
,"rate":{"traffic":1}
,"traffic":{"digitized":1}
,"digitized":{"voice":1}
,"voice":{"video":1,"quality":1}
,"video":{"packets":1,"transmission":1}
,"packets":{"tdm":1,"incoming":1}
,"tdm":{"technologies":1,"signals":1,"packet":1,"requires":1,"signal":1,"stream":1}
,"support":{"small":1}
,"small":{"transmission":1}
,"transmission":{"delay":1,"mobile":1,"achieved":1}
,"delay":{"small":1,"variation":1}
,"variation":{"two":1}
,"two":{"key":1}
,"key":{"parameters":1}
,"parameters":{"voice":1}
,"quality":{"video":1}
,"mobile":{"back-haul":1}
,"back-haul":{"transitions":1}
,"transitions":{"packet-type":1}
,"packet-type":{"infrastructures":1}
,"infrastructures":{"important":1}
,"important":{"efficiently":1}
,"efficiently":{"carry":1}
,"carry":{"tdm":1}
,"signals":{"packet":1}
,"packet":{"switched":1,"formats":1,"losses":1,"(satop)":1}
,"switched":{"network":1}
,"network":{"requires":1}
,"requires":{"ability":1,"low":1}
,"ability":{"convert":1}
,"convert":{"tdm":1}
,"formats":{"maintaining":1}
,"maintaining":{"accurate":1}
,"accurate":{"synchronization":1}
,"synchronization":{"information":1}
,"information":{"circuits":1}
,"circuits":{"addition":1}
,"addition":{"tdm":1,"encapsulation":1}
,"low":{"latency":1}
,"latency":{"jitter":1}
,"jitter":{"reliable":1}
,"reliable":{"transmission":1}
,"achieved":{"guaranteeing":1}
,"guaranteeing":{"adequate":1}
,"adequate":{"bandwidth":1}
,"bandwidth":{"prioritization":1}
,"prioritization":{"buffering":1}
,"buffering":{"along":1}
,"along":{"end-to-end":1,"payload":1}
,"end-to-end":{"path":1}
,"path":{"minimize":1}
,"minimize":{"packet":1}
,"losses":{"delays":1}
,"delays":{"reordering":1}
,"reordering":{"structure":1}
,"structure":{"agnostic":1}
,"agnostic":{"tdm":1}
,"(satop)":{"encapsulation":1}
,"encapsulation":{"method":1,"provides":1}
,"method":{"used":1}
,"used":{"transparently":1}
,"transparently":{"carrying":1,"transported":1}
,"carrying":{"tdm":1}
,"signal":{"without":1}
,"without":{"processing":1}
,"processing":{"ds0":1}
,"ds0":{"time-slot":1}
,"time-slot":{"satop":1}
,"creates":{"packets":1}
,"incoming":{"tdm":1}
,"stream":{"includes":1}
,"includes":{"suitable":1}
,"suitable":{"header":1}
,"header":{"structure-agnostic":1}
,"structure-agnostic":{"transport":1}
,"transport":{"structural":1}
,"structural":{"overhead":1}
,"overhead":{"present":1}
,"present":{"transparently":1}
,"transported":{"along":1}
,"payload":{"data":1}
,"data":{"addition":1}
,"provides":{"mechanisms":1}
,"mechanisms":{"location":1}
,"location":{"utilization":1}
}
;Search.control.loadWordPairs(pairs);
