var pairs =
{
"ethernet":{"cfm":1}
,"cfm":{"mep":1}
,"mep":{"domain":1,"command":1,"(mepid)":1,"specify":1}
,"domain":{"tx-lbm-status":1,"(domain_name)":1,"specify":1,"ascii":1,"abc":1}
,"tx-lbm-status":{"command":1,"(false":1,"specify":1,"true":1,"false":1}
,"command":{"configure":1,"syntax":1,"mode":1}
,"configure":{"counters":1}
,"counters":{"loopback":1}
,"loopback":{"message":1}
,"message":{"(lbm)":1}
,"(lbm)":{"transmission":1}
,"transmission":{"mep":1,"allowed":1}
,"syntax":{"ethernet":1}
,"(mepid)":{"domain":1}
,"(domain_name)":{"tx-lbm-status":1}
,"(false":{"true)":1}
,"true)":{"[bridge":1}
,"[bridge":{"<1-32>":1}
,"<1-32>":{"backbone]":1,"backbone":1}
,"backbone]":{"parameters":1}
,"parameters":{"mep":1}
,"specify":{"integer":1,"name":1,"lbm":1,"next":1,"bridge":1}
,"integer":{"identifies":1}
,"identifies":{"host":1}
,"host":{"mep":1}
,"name":{"maintenance":1}
,"maintenance":{"domain":1}
,"ascii":{"format":1}
,"format":{"tx-lbm-status":1}
,"lbm":{"transmission":1,"cannot":1,"sent":1}
,"allowed":{"false":1}
,"false":{"specify":1,"bridge":1}
,"next":{"lbm":1}
,"cannot":{"sent":1}
,"sent":{"true":1,"bridge":1}
,"true":{"specify":1,"bridge":1}
,"bridge":{"specify":1,"range":1,"backbone":1,"(config-if)":1}
,"range":{"<1-32>":1}
,"backbone":{"specify":1,"command":1}
,"mode":{"interface":1,"example":1}
,"interface":{"mode":1,"eth1":1}
,"example":{"(config)":1}
,"(config)":{"interface":1}
,"eth1":{"(config-if)":1}
,"(config-if)":{"ethernet":1}
,"abc":{"tx-lbm-status":1,"vid":1}
,"vid":{"tx-lbm-status":1}
}
;Search.control.loadWordPairs(pairs);
