var pairs =
{
"nsm_api_mpls_tp_if_unset":{"function":1,"(u_int32_t":1}
,"function":{"resets":1,"called":1,"executed":1}
,"resets":{"(unconfigures)":1}
,"(unconfigures)":{"mpls-tp":1}
,"mpls-tp":{"capability":1,"provider-interface":1,"provider":1,"active":1}
,"capability":{"interface":1}
,"interface":{"function":1,"index":1,"exist":1,"configured":1,"cannot":1}
,"called":{"mpls-tp":1}
,"provider-interface":{"cli":1}
,"cli":{"command":1}
,"command":{"syntax":1}
,"syntax":{"int":1}
,"int":{"nsm_api_mpls_tp_if_unset":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1}
,"u_int32_t":{"ifindex)":1}
,"ifindex)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"(vr)":1,"exist":1}
,"(vr)":{"instance":1}
,"instance":{"ifindex":1}
,"ifindex":{"outgoing":1}
,"outgoing":{"interface":1}
,"index":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_api_set_success":1}
,"nsm_api_set_success":{"function":1}
,"executed":{"properly":1}
,"properly":{"nsm_api_set_err_if_not_exist":1}
,"nsm_api_set_err_if_not_exist":{"interface":1}
,"exist":{"nsm_api_set_err_vr_not_exist":1,"nsm_api_unset_err_if_not_mpls_tp_cap":1}
,"nsm_api_set_err_vr_not_exist":{"virtual":1}
,"nsm_api_unset_err_if_not_mpls_tp_cap":{"interface":1}
,"configured":{"mpls-tp":1}
,"provider":{"nsm_err_ls_on_loopback":1}
,"nsm_err_ls_on_loopback":{"unable":1}
,"unable":{"enable":1,"disable":1}
,"enable":{"label":1}
,"label":{"switching":1}
,"switching":{"loopback":1,"nsm_mpls_tp_ftn_ilm_exists":1}
,"loopback":{"nsm_failure":1}
,"nsm_failure":{"unable":1}
,"disable":{"label":1}
,"nsm_mpls_tp_ftn_ilm_exists":{"mpls-tp":1}
,"active":{"interface":1}
,"cannot":{"unset":1}
}
;Search.control.loadWordPairs(pairs);
