var pairs =
{
"mrib4_api_rt_limit_thresh_set":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"used":1}
,"sets":{"threshold":1}
,"threshold":{"route":1,"value":1,"exceeds":1}
,"route":{"multicast":1,"entries":1,"threshold":1,"limit":1}
,"multicast":{"route":1,"route-limit":1,"routes":1,"routing":1}
,"entries":{"mrib\u002Fmfib":1}
,"mrib\u002Fmfib":{"function":1}
,"used":{"implement":1,"mrib_api_set_err_wrong_vrf":1,"mrib_api_set_err_rt_thresh_exceed_rt_limit":1}
,"implement":{"multicast":1}
,"route-limit":{"command":1,"number":1}
,"command":{"syntax":1}
,"syntax":{"int":1}
,"int":{"mrib4_api_rt_limit_thresh_set":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"vrf_id_t":1,"virtual":1}
,"vrf_id_t":{"vrf_id":1}
,"vrf_id":{"u_int32_t":1,"vpn":1}
,"u_int32_t":{"rt_limit":1,"rt_thresh)":1}
,"rt_limit":{"u_int32_t":1,"route-limit":1}
,"rt_thresh)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"vrf_id":1,"used":1}
,"vpn":{"routing\u002Fforwarding":1}
,"routing\u002Fforwarding":{"instance":1}
,"instance":{"rt_limit":1,"used":1}
,"number":{"number":1,"multicast":1,"routes":1}
,"routes":{"added":1}
,"added":{"multicast":1}
,"routing":{"table":1}
,"table":{"rt_thresh":1}
,"rt_thresh":{"threshold":1}
,"value":{"generate":1}
,"generate":{"warning":1}
,"warning":{"message":1}
,"message":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"mrib_api_set_err_wrong_vr":1}
,"mrib_api_set_err_wrong_vr":{"invalid":1}
,"invalid":{"virtual":1,"vpn":1}
,"mrib_api_set_err_wrong_vrf":{"invalid":1}
,"mrib_api_set_err_rt_thresh_exceed_rt_limit":{"route":1}
,"exceeds":{"configured":1,"current":1}
,"configured":{"route":1}
,"limit":{"mrib_api_set_err_rt_limit_exceed_rts":1,"exceeds":1}
,"mrib_api_set_err_rt_limit_exceed_rts":{"route":1}
,"current":{"number":1}
}
;Search.control.loadWordPairs(pairs);
