var pairs =
{
"rip2_get_if_stat_addr":{"function":1,"(int":1}
,"function":{"returns":1}
,"returns":{"address":1}
,"address":{"system":1,"specified":1,"return":1,"rip_api_get_success":1}
,"system":{"indicated":1}
,"indicated":{"subnet":1}
,"subnet":{"syntax":1}
,"syntax":{"int":1}
,"int":{"rip2_get_if_stat_addr":1}
,"(int":{"pid":1}
,"pid":{"struct":1,"rip":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"*addr":1,"*outaddr)":1}
,"*addr":{"struct":1}
,"*outaddr)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"pid":1,"outaddr":1}
,"rip":{"process":1}
,"process":{"addr":1}
,"addr":{"address":1}
,"specified":{"interface":1}
,"interface":{"output":1}
,"output":{"parameters":1}
,"outaddr":{"address":1}
,"return":{"values":1}
,"values":{"rip_api_get_error":1}
,"rip_api_get_error":{"call":1}
,"call":{"find":1,"finds":1}
,"find":{"address":1}
,"rip_api_get_success":{"call":1}
,"finds":{"address":1}
}
;Search.control.loadWordPairs(pairs);
