var pairs =
{
"without":{"default":1}
,"default":{"passive":1,"passive-interface":1}
,"passive":{"interface":1,"result":1}
,"interface":{"default":1,"name":1}
,"passive-interface":{"feature":1,"command":1}
,"feature":{"two":1}
,"two":{"methods":1}
,"methods":{"obtain":1}
,"obtain":{"routing":1}
,"routing":{"information":1}
,"information":{"connected":1}
,"connected":{"interfaces":1}
,"interfaces":{"router":1,"result":1,"manually":1,"adjacency":1,"(eth1":1}
,"router":{"configure":1,"redistribute":1,"(abr)":1}
,"configure":{"ospf":1}
,"ospf":{"router":1,"interfaces":1}
,"redistribute":{"connected":1}
,"result":{"large":1}
,"large":{"number":1,"type-1":1}
,"number":{"type-5":1}
,"type-5":{"lsas":1}
,"lsas":{"flooded":1,"type-1":1}
,"flooded":{"domain":1,"area":1}
,"domain":{"configure":1}
,"manually":{"passive":1,"passive\u2011interface":1}
,"type-1":{"link-state":1,"lsa":1}
,"link-state":{"lsas":1}
,"area":{"area":1,"border":1}
,"border":{"router":1}
,"(abr)":{"creates":1}
,"creates":{"type-3":1}
,"type-3":{"lsas":1}
,"lsa":{"floods":1}
,"floods":{"backbone":1}
,"backbone":{"possible":1,"thereby":1}
,"possible":{"however":1}
,"however":{"unique":1}
,"unique":{"summarization":1}
,"summarization":{"abr":1}
,"abr":{"level":1}
,"level":{"injects":1}
,"injects":{"summary":1}
,"summary":{"route":1}
,"route":{"backbone":1}
,"thereby":{"reducing":1}
,"reducing":{"processing":1}
,"processing":{"overhead":1}
,"overhead":{"solution":1}
,"solution":{"problem":1}
,"problem":{"configure":1}
,"passive\u2011interface":{"command":1}
,"command":{"interface":1}
,"name":{"interfaces":1}
,"adjacency":{"desired":1}
,"desired":{"above":1}
,"above":{"illustration":1}
,"illustration":{"user":1}
,"user":{"run":1}
,"run":{"passive-interface":1}
,"(eth1":{"eth2":1}
,"eth2":{"eth3":1}
,"eth3":{"eth4)":1}
,"eth4)":{"except":1}
,"except":{"eth0":1}
}
;Search.control.loadWordPairs(pairs);
