var pairs =
{
"trill_get_rbridge_snoopingport_addr":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"address":1}
,"address":{"multicast":1,"return":1}
,"multicast":{"router":1}
,"router":{"detected":1}
,"detected":{"port":1}
,"port":{"syntax":1,"number":1,"entry":1}
,"syntax":{"int":1}
,"int":{"trill_get_rbridge_snoopingport_addr":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"integer":1}
,"u_int32_t":{"instance":1,"baseport":1}
,"instance":{"u_int32_t":1,"integer":1,"baseport":1}
,"baseport":{"u_char":1,"integer":1,"trill_api_get_error":1,"found":1}
,"u_char":{"**ret)":1}
,"**ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"ret":1}
,"integer":{"contains":1,"containing":1}
,"contains":{"trill":1,"rbridge":1}
,"trill":{"identifier":1,"instance":1}
,"identifier":{"instance":1}
,"containing":{"port":1,"address":1}
,"number":{"port":1}
,"entry":{"contains":1}
,"rbridge":{"management":1}
,"management":{"information":1}
,"information":{"output":1}
,"output":{"parameters":1}
,"ret":{"octet":1}
,"octet":{"string":1}
,"string":{"containing":1}
,"return":{"value":1}
,"value":{"trill_api_get_success":1}
,"trill_api_get_success":{"valid":1}
,"valid":{"instance":1}
,"trill_api_get_error":{"valid":1}
}
;Search.control.loadWordPairs(pairs);
