var pairs =
{
"architecture":{"mrp":1}
,"mrp":{"application":1,"participant":1,"attribute":1}
,"application":{"operates":1,"component":1,"exchange":1,"running":1,"expired":1}
,"operates":{"networks":1}
,"networks":{"bridges":1}
,"bridges":{"support":1}
,"support":{"basic":1}
,"basic":{"extended":1}
,"extended":{"filtering":1}
,"filtering":{"services":1}
,"services":{"single":1}
,"single":{"mrp":1}
,"participant":{"per":1,"mrp":1,"component":1,"two":1,"generates":1}
,"per":{"port":1}
,"port":{"mrp":1,"information":1,"role":1,"designated":1,"flushed":1,"however":1,"message":1}
,"component":{"mrp":1,"pdus":1,"state":1,"called":1}
,"attribute":{"declaration":1,"propagation":1,"associated":1,"registrar":1}
,"declaration":{"(mad)":1}
,"(mad)":{"associated":1}
,"associated":{"port":1,"participant":1}
,"information":{"propagates":1,"among":1,"maintained":1}
,"propagates":{"among":1}
,"among":{"participants":1}
,"participants":{"within":1,"across":1}
,"within":{"bridge":1,"participant":1}
,"bridge":{"mrp":1,"mad":1}
,"propagation":{"(map)":1}
,"(map)":{"component":1}
,"pdus":{"destined":1}
,"destined":{"group":1}
,"group":{"mac":1}
,"mac":{"address":1}
,"address":{"specific":1}
,"specific":{"mrp":1}
,"exchange":{"information":1}
,"across":{"bridge":1}
,"mad":{"component":1}
,"state":{"machines":1,"machine":1}
,"machines":{"running":1,"define":1,"attribute":1,"differ":1}
,"running":{"within":1,"ensure":1}
,"define":{"declarations":1}
,"declarations":{"registrations":1}
,"registrations":{"attribute":1}
,"two":{"state":1}
,"registrar":{"state":1,"alternate":1}
,"machine":{"second":1,"state":1,"leave":1}
,"second":{"applicant":1}
,"applicant":{"state":1}
,"differ":{"depending":1}
,"depending":{"topology":1}
,"topology":{"scenario":1}
,"scenario":{"example":1}
,"example":{"shared":1}
,"shared":{"media":1}
,"media":{"point-to-point":1}
,"point-to-point":{"lan":1}
,"lan":{"mrp":1}
,"ensure":{"optimal":1}
,"optimal":{"operation":1}
,"operation":{"component":1}
,"called":{"leaveall":1}
,"leaveall":{"associated":1,"message":1,"timer":1}
,"generates":{"leaveall":1}
,"message":{"once":1,"sent":1}
,"once":{"leaveall":1}
,"timer":{"run":1}
,"run":{"application":1}
,"expired":{"avoid":1}
,"avoid":{"data":1}
,"data":{"loops":1}
,"loops":{"transition":1}
,"transition":{"port":1}
,"role":{"alternate":1,"transitions":1}
,"alternate":{"root":1}
,"root":{"port":1}
,"designated":{"information":1,"alternate":1}
,"maintained":{"registrar":1}
,"flushed":{"stored":1}
,"stored":{"state":1}
,"leave":{"message":1}
,"sent":{"port":1}
,"however":{"port":1}
,"transitions":{"designated":1}
}
;Search.control.loadWordPairs(pairs);
