var pairs =
{
"system":{"components":1,"component":1}
,"components":{"following":1,"system":1}
,"following":{"table":1}
,"table":{"lists":1}
,"lists":{"pal":1}
,"pal":{"equivalents":1,"equivalent":1}
,"equivalents":{"system":1}
,"component":{"pal":1}
,"equivalent":{"services":1}
,"services":{"pal_services":1}
,"pal_services":{"types":1}
,"types":{"pal_types":1}
,"pal_types":{"sockets":1}
,"sockets":{"pal_sockets":1}
,"pal_sockets":{"memory":1}
,"memory":{"pal_memory":1}
,"pal_memory":{"string":1}
,"string":{"pal_string":1}
,"pal_string":{"stdlib":1}
,"stdlib":{"pal_stdlib":1}
,"pal_stdlib":{"configuration\u002Fstorage":1}
,"configuration\u002Fstorage":{"pal_config":1}
,"pal_config":{"interfaces":1}
,"interfaces":{"pal_interfaces":1}
,"pal_interfaces":{"logging":1}
,"logging":{"pal_log":1}
,"pal_log":{"route":1}
,"route":{"pal_route":1}
,"pal_route":{"daemonization":1}
,"daemonization":{"pal_daemon":1}
}
;Search.control.loadWordPairs(pairs);
