var pairs =
{
"zebos2":{"verify":1}
,"verify":{"input":1,"synchronous":1}
,"input":{"source":1}
,"source":{"show":1}
,"show":{"synce":1}
,"synce":{"input-sources":1,"details":1}
,"input-sources":{"interface":1}
,"interface":{"name":1}
,"name":{"eth9":1,"eth10":1,"eth11":1}
,"eth9":{"esmc":1}
,"esmc":{"status":1}
,"status":{"is-selected-source":1}
,"is-selected-source":{"ql_prc":1,"ql_ssu_a":1,"ql_ssu_b":1}
,"ql_prc":{"priority":1}
,"priority":{"hold-off":1}
,"hold-off":{"(ms)":1}
,"(ms)":{"300":1}
,"300":{"wait-to-restore":1}
,"wait-to-restore":{"(mins)":1}
,"(mins)":{"signal":1}
,"signal":{"fail":1}
,"fail":{"external":1}
,"external":{"commands":1}
,"commands":{"none":1,"force":1,"lockout":1}
,"none":{"interface":1}
,"eth10":{"esmc":1}
,"ql_ssu_a":{"priority":1,"clock":1}
,"force":{"interface":1}
,"eth11":{"esmc":1}
,"ql_ssu_b":{"priority":1}
,"lockout":{"verify":1}
,"synchronous":{"ethernet":1}
,"ethernet":{"details":1}
,"details":{"show":1,"interface":1}
,"clock":{"state":1}
,"state":{"locked":1}
}
;Search.control.loadWordPairs(pairs);
