var pairs =
{
"ospf6_set_admin_stat":{"function":1,"(char":1}
,"function":{"sets":1,"succeeds":1,"fails":1}
,"sets":{"administrative":1}
,"administrative":{"status":1}
,"status":{"ospfv3":1,"administrative":1,"ospf6_api_status_enabled":1}
,"ospfv3":{"process":1}
,"process":{"router":1,"tag":1,"cannot":1,"exist":1}
,"router":{"syntax":1,"exist":1}
,"syntax":{"int":1}
,"int":{"ospf6_set_admin_stat":1,"status)":1}
,"(char":{"*tag":1}
,"*tag":{"int":1}
,"status)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"tag":1,"none":1}
,"tag":{"ospfv3":1,"status":1}
,"ospf6_api_status_enabled":{"enabled":1}
,"enabled":{"ospf6_api_status_disabled":1}
,"ospf6_api_status_disabled":{"disabled":1}
,"disabled":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"ospf6_api_set_success":1}
,"ospf6_api_set_success":{"function":1}
,"succeeds":{"ospf6_api_set_error":1}
,"ospf6_api_set_error":{"function":1}
,"fails":{"ospf6_api_set_err_vr_not_exist":1}
,"ospf6_api_set_err_vr_not_exist":{"virtual":1}
,"virtual":{"router":1}
,"exist":{"ospf6_api_set_err_process_cant_initiate":1}
,"ospf6_api_set_err_process_cant_initiate":{"process":1}
,"cannot":{"initiate":1}
,"initiate":{"ospf6_api_set_err_process_not_exist":1}
,"ospf6_api_set_err_process_not_exist":{"ospf":1}
,"ospf":{"process":1}
}
;Search.control.loadWordPairs(pairs);
