var pairs =
{
"unicast":{"command":1,"continuity":1,"rmpid":1,"disable":1}
,"command":{"enable":1,"mode":1}
,"enable":{"disable":1,"enable":1,"continuity":1}
,"disable":{"unicast":1,"disable":1,"continuity":1}
,"continuity":{"checking":1,"check":1}
,"checking":{"(cc)":1,"state":1}
,"(cc)":{"syntax":1}
,"syntax":{"unicast":1}
,"rmpid":{"rmepid":1,"state":1}
,"rmepid":{"state":1,"remote":1}
,"state":{"(enable":1,"continuity":1,"enable":1,"unicast":1}
,"(enable":{"disable)":1}
,"disable)":{"parameters":1}
,"parameters":{"rmepid":1}
,"remote":{"mep":1}
,"mep":{"state":1,"configuration":1,"down":1}
,"check":{"state":1}
,"mode":{"interface":1,"examples":1}
,"interface":{"ethernet":1,"eth1":1}
,"ethernet":{"cfm":1}
,"cfm":{"pbb":1}
,"pbb":{"mep":1}
,"configuration":{"mode":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth1":{"(config-if)":1}
,"(config-if)":{"ethernet":1}
,"down":{"mpid":1}
,"mpid":{"domain-name":1}
,"domain-name":{"abc":1}
,"abc":{"bridge":1}
,"bridge":{"(config-if-eth-cfm-pbb-mep)":1}
,"(config-if-eth-cfm-pbb-mep)":{"unicast":1}
}
;Search.control.loadWordPairs(pairs);
