var pairs =
{
"smi_alarm_callback_t":{"typedef":1}
,"typedef":{"defines":1,"void":1}
,"defines":{"signature":1}
,"signature":{"callback":1}
,"callback":{"function":1}
,"function":{"write":1,"zebos_smi_client_set_alarm_callback":1}
,"write":{"process":1}
,"process":{"alarm":1}
,"alarm":{"received":1,"smi_api_module":1,"alarm":1,"identifier":1,"data":1,"smi":1}
,"received":{"smi":1}
,"smi":{"server":1}
,"server":{"register":1,"fills":1}
,"register":{"function":1}
,"zebos_smi_client_set_alarm_callback":{"syntax":1}
,"syntax":{"typedef":1}
,"void":{"(*smi_alarm_callback_t)":1,"*data)":1}
,"(*smi_alarm_callback_t)":{"(smi_alarm":1}
,"(smi_alarm":{"alarm":1}
,"smi_api_module":{"module":1,"data":1}
,"module":{"void":1,"protocol":1}
,"*data)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"alarm":1,"none":1}
,"identifier":{"shown":1}
,"shown":{"smi_alarm":1,"smi_api_module":1,"smi_msg_alarm":1}
,"smi_alarm":{"module":1}
,"protocol":{"client":1}
,"client":{"shown":1}
,"data":{"alarm":1,"shown":1,"corresponding":1}
,"smi_msg_alarm":{"depending":1}
,"depending":{"type":1}
,"type":{"alarm":1}
,"fills":{"data":1}
,"corresponding":{"member":1}
,"member":{"variables":1}
,"variables":{"structure":1}
,"structure":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"none":1}
}
;Search.control.loadWordPairs(pairs);
