var pairs =
{
"ptp_set_state":{"function":1,"(void":1}
,"function":{"sets":1}
,"sets":{"ptp":1}
,"ptp":{"state":1,"interface":1}
,"state":{"syntax":1}
,"syntax":{"include":1}
,"include":{"ptpd\u002Fptp_fsm.h":1}
,"ptpd\u002Fptp_fsm.h":{"void":1,"ieee":1}
,"void":{"ptp_set_state":1}
,"(void":{"*data":1}
,"*data":{"ptp_states_e":1}
,"ptp_states_e":{"new_state)":1}
,"new_state)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"data":1,"none":1}
,"data":{"pointer":1}
,"pointer":{"ptp":1}
,"interface":{"(internally":1}
,"(internally":{"cast":1}
,"cast":{"struct":1}
,"struct":{"ptp_ifp":1}
,"ptp_ifp":{"new_state":1}
,"new_state":{"constants":1}
,"constants":{"defined":1}
,"defined":{"ptp_states":1}
,"ptp_states":{"enum":1}
,"enum":{"ptpd\u002Fptp_fsm.h":1}
,"ieee":{"1588-2008":1}
,"1588-2008":{"standard":1}
,"standard":{"explanation":1}
,"explanation":{"states":1}
,"states":{"ptp_master":1}
,"ptp_master":{"ptp_uncalibrated":1}
,"ptp_uncalibrated":{"ptp_slave":1}
,"ptp_slave":{"ptp_listening":1}
,"ptp_listening":{"ptp_pre_master":1}
,"ptp_pre_master":{"ptp_passive":1}
,"ptp_passive":{"ptp_initializing":1}
,"ptp_initializing":{"ptp_disable":1}
,"ptp_disable":{"ptp_faulty":1}
,"ptp_faulty":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"none":1}
}
;Search.control.loadWordPairs(pairs);
