var pairs =
{
"session":{"performance":1,"basis":1,"table":1,"bfdcounterdiscontinuitytime":1}
,"performance":{"table":1,"counts":1}
,"table":{"bfd":1,"(bfdsessperftable)":1,"augment":1,"therefore":1,"bfdsessindex":1,"created":1,"objects":1,"read-only":1,"functions":1}
,"bfd":{"session":1,"performance":1,"sessions":1,"maintains":1}
,"(bfdsessperftable)":{"used":1}
,"used":{"collecting":1,"indicate":1,"retrieve":1,"return":1}
,"collecting":{"bfd":1}
,"counts":{"per":1}
,"per":{"session":1}
,"basis":{"table":1}
,"augment":{"bfd":1}
,"therefore":{"index":1}
,"index":{"table":1,"array":1}
,"bfdsessindex":{"entry":1}
,"entry":{"table":1}
,"created":{"bfd-enabled":1}
,"bfd-enabled":{"node":1}
,"node":{"every":1}
,"every":{"bfd":1}
,"bfdcounterdiscontinuitytime":{"used":1}
,"indicate":{"potential":1}
,"potential":{"discontinuity":1}
,"discontinuity":{"counter":1}
,"counter":{"objects":1,"object":1}
,"objects":{"table":1}
,"read-only":{"type":1}
,"type":{"operations":1}
,"operations":{"allowed":1}
,"allowed":{"session":1}
,"functions":{"used":1}
,"retrieve":{"bfd":1}
,"sessions":{"bfd":1}
,"maintains":{"array":1}
,"array":{"two":1,"used":1,"returned":1}
,"two":{"32-bit":1}
,"32-bit":{"value":1,"versions":1,"object":1}
,"value":{"support":1,"user":1}
,"support":{"64-bit":1}
,"64-bit":{"32-bit":1,"object":1}
,"versions":{"counter":1}
,"object":{"snmp":1,"0th":1}
,"snmp":{"requests":1}
,"requests":{"received":1}
,"received":{"32-bit":1,"64-bit":1}
,"0th":{"index":1,"1st":1}
,"return":{"value":1}
,"user":{"snmp":1}
,"1st":{"index":1}
,"returned":{"user":1}
}
;Search.control.loadWordPairs(pairs);
