var pairs =
{
"ospf_area_shortcut_unset":{"function":1,"(u_int32_t":1}
,"function":{"removes":1,"called":1,"succeeds":1}
,"removes":{"shortcut":1}
,"shortcut":{"mode":1,"syntax":1}
,"mode":{"specified":1}
,"specified":{"area":1}
,"area":{"function":1,"shortcut":1,"output":1,"backbone":1,"exist":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"area":1}
,"syntax":{"int":1}
,"int":{"ospf_area_shortcut_unset":1,"proc_id":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"int":1,"virtual":1}
,"proc_id":{"struct":1,"process":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"area_id)":1}
,"area_id)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"found":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"proc_id":1}
,"process":{"ospf":1,"exist":1}
,"ospf":{"instance":1,"area":1}
,"instance":{"65535>":1}
,"65535>":{"area_id":1}
,"area_id":{"ospf":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf_api_set_err_process_not_exist":1}
,"ospf_api_set_err_process_not_exist":{"given":1}
,"given":{"process":1,"area":1}
,"exist":{"ospf_api_set_success":1,"ospf_api_set_err_vr_not_exist":1}
,"ospf_api_set_success":{"function":1}
,"succeeds":{"ospf_api_set_err_area_is_backbone":1}
,"ospf_api_set_err_area_is_backbone":{"given":1}
,"backbone":{"ospf_api_set_err_area_not_exist":1}
,"ospf_api_set_err_area_not_exist":{"given":1}
,"ospf_api_set_err_vr_not_exist":{"virtual":1}
}
;Search.control.loadWordPairs(pairs);
