var pairs =
{
"bgp_router_id_unset":{"function":1}
,"function":{"unsets":1,"called":1,"successful":1}
,"unsets":{"bgp":1}
,"bgp":{"router":1,"router-id":1,"*bgp)":1,"bgp":1,"instance":1}
,"router":{"afterward":1,"picked":1}
,"afterward":{"new":1}
,"new":{"router":1}
,"picked":{"interface":1}
,"interface":{"address":1}
,"address":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"bgp":1}
,"router-id":{"a.b.c.d":1}
,"a.b.c.d":{"syntax":1}
,"syntax":{"int":1}
,"int":{"router_id_unset":1}
,"router_id_unset":{"(struct":1}
,"(struct":{"bgp":1}
,"*bgp)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bgp":1,"none":1}
,"instance":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"bgp_api_set_success":1}
,"bgp_api_set_success":{"function":1}
,"successful":{"(0)":1}
}
;Search.control.loadWordPairs(pairs);
