var pairs =
{
"validation":{"verify":1}
,"verify":{"mpls":1}
,"mpls":{"forwarding":1,"forwarding-table":1,"ilm-table":1,"ftn-table":1}
,"forwarding":{"table":1}
,"table":{"static":1}
,"static":{"entry":1}
,"entry":{"mpls":1,"fec":1}
,"forwarding-table":{"codes":1}
,"codes":{"-selected":1}
,"-selected":{"ftn":1,"ilm":1}
,"ftn":{"-stale":1,"-bgp":1,"-cli":1,"-ldp":1,"-rsvp-te":1,"-snmp":1,"-igp-shortcut":1,"-mpls-tp":1,"-sr-ospf":1,"-sr-isis":1,"-sr-cli":1,"code":1,"entry":1}
,"-stale":{"ftn":1,"ilm":1}
,"-bgp":{"ftn":1}
,"-cli":{"ftn":1,"ilm":1}
,"-ldp":{"ftn":1}
,"-rsvp-te":{"ftn":1}
,"-snmp":{"ftn":1}
,"-igp-shortcut":{"-unknown":1}
,"-unknown":{"ftn":1}
,"-mpls-tp":{"map":1,"code":1}
,"map":{"ftn":1}
,"-sr-ospf":{"ftn":1}
,"-sr-isis":{"ftn":1}
,"-sr-cli":{"ftn":1}
,"code":{"fec":1,"push":1}
,"fec":{"ftn-id":1,"ilm-id":1,"20.1.1.0\u002F24":1}
,"ftn-id":{"tunnel-id":1}
,"tunnel-id":{"pri":1}
,"pri":{"lsp-type":1}
,"lsp-type":{"out-label":1,"20.1.1.0\u002F24":1}
,"out-label":{"out-intf":1,"in-intf":1}
,"out-intf":{"nexthop":1}
,"nexthop":{"20.1.1.0\u002F24":1,"lsp-type":1,"addr":1}
,"20.1.1.0\u002F24":{"lsp_default":1,"1024001":1,"row":1}
,"lsp_default":{"1024001":1,"mpls":1}
,"1024001":{"eth1":1,"1024001":1,"n\u002Fa":1,"nexthop":1}
,"eth1":{"10.1.1.2":1,"label":1}
,"10.1.1.2":{"mpls":1,"lsp_default":1,"cross":1}
,"ilm-table":{"codes":1}
,"ilm":{"-stale":1,"-cli":1,"-mpls-tp":1}
,"ilm-id":{"in-label":1}
,"in-label":{"out-label":1}
,"in-intf":{"out-intf":1}
,"n\u002Fa":{"eth1":1,"matched":1}
,"ftn-table":{"primary":1}
,"primary":{"ftn":1}
,"row":{"status":1}
,"status":{"active":1,"oper":1,"out-segment":1}
,"active":{"owner":1}
,"owner":{"cli-sr":1}
,"cli-sr":{"action-type":1,"persistent":1,"intf":1}
,"action-type":{"redirect":1}
,"redirect":{"tunnel":1}
,"tunnel":{"exp-bits":1,"protected":1}
,"exp-bits":{"0x0":1}
,"0x0":{"incoming":1}
,"incoming":{"dscp":1}
,"dscp":{"none":1}
,"none":{"tunnel":1}
,"protected":{"lsp":1}
,"lsp":{"qos":1}
,"qos":{"resource":1}
,"resource":{"description":1}
,"description":{"n\u002Fa":1}
,"matched":{"bytes:0":1}
,"bytes:0":{"pkts:0":1,"pushed":1}
,"pkts:0":{"bytes:0":1,"cross":1}
,"pushed":{"pkts:0":1}
,"cross":{"connect":1}
,"connect":{"intf":1,"code":1}
,"intf":{"-in":1,"eth1":1}
,"-in":{"label":1}
,"label":{"out-segment":1,"1024001":1}
,"out-segment":{"owner":1}
,"persistent":{"admin":1}
,"admin":{"status":1}
,"oper":{"status":1}
,"addr":{"10.1.1.2":1}
}
;Search.control.loadWordPairs(pairs);
