var pairs =
{
"lock":{"report":1,"condition":1}
,"report":{"mpls":1,"(lkr)":1}
,"mpls":{"lock":1}
,"(lkr)":{"messages":1}
,"messages":{"generated":1,"suppress":1}
,"generated":{"server":1}
,"server":{"layer":1}
,"layer":{"entity":1,"above":1}
,"entity":{"administratively":1}
,"administratively":{"locked":1}
,"locked":{"communicates":1,"condition":1}
,"communicates":{"locked":1}
,"condition":{"client-layer":1,"fault":1}
,"client-layer":{"entities":1}
,"entities":{"lkr":1}
,"lkr":{"messages":1}
,"suppress":{"alarms":1}
,"alarms":{"network":1}
,"network":{"layer":1}
,"above":{"level":1}
,"level":{"administrative":1}
,"administrative":{"locks":1}
,"locks":{"occurs":1}
,"occurs":{"helps":1}
,"helps":{"differentiate":1}
,"differentiate":{"lock":1}
,"fault":{"condition":1}
}
;Search.control.loadWordPairs(pairs);
