var pairs =
{
"hal_vlan_classifier_add":{"function":1,"(struct":1}
,"function":{"adds":1,"succeeds":1}
,"adds":{"vlan":1}
,"vlan":{"classification":1}
,"classification":{"group":1,"rule":1}
,"group":{"syntax":1}
,"syntax":{"int":1}
,"int":{"hal_vlan_classifier_add":1}
,"(struct":{"hal_vlan_classifier_rule":1}
,"hal_vlan_classifier_rule":{"*rule_ptr":1}
,"*rule_ptr":{"u_int32_t":1}
,"u_int32_t":{"ifindex":1,"refcount)":1}
,"ifindex":{"u_int32_t":1,"interface":1}
,"refcount)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"rule_ptr":1,"none":1}
,"rule_ptr":{"vlan":1}
,"rule":{"ifindex":1}
,"interface":{"index":1}
,"index":{"refcount":1}
,"refcount":{"reference":1}
,"reference":{"count":1}
,"count":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"hal_err_vlan_classifier_add":1}
,"hal_err_vlan_classifier_add":{"hal_success":1}
,"hal_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
