var pairs =
{
"show":{"bridge":1}
,"bridge":{"command":1,"parameters":1,"minimum":1,"bridge":1,"cvlan":1}
,"command":{"display":1,"syntax":1,"mode":1,"bridge":1}
,"display":{"basic":1}
,"basic":{"configuration":1}
,"configuration":{"information":1,"show":1}
,"information":{"bridge":1}
,"syntax":{"show":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"following":1}
,"following":{"sample":1}
,"sample":{"output":1}
,"output":{"show":1}
,"minimum":{"configuration":1}
,"cvlan":{"svlan":1}
,"svlan":{"bvlan":1}
,"bvlan":{"port":1}
,"port":{"mac":1}
,"mac":{"fwd":1}
,"fwd":{"timeout":1}
,"timeout":{"eth2":1}
,"eth2":{"0002.b328.5255":1}
,"0002.b328.5255":{"eth1":1}
,"eth1":{"0002.b328.5254":1}
}
;Search.control.loadWordPairs(pairs);
