var pairs =
{
"sw3":{"sw3":1,"configure":1,"(config)":1,"(config-vlan)":1,"(config-if)":1}
,"configure":{"terminal":1,"mode":1,"interface":1,"eth1":1,"eth2":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"vlan":1}
,"mode":{"sw3":1,"trunk":1}
,"(config)":{"bridge":1,"vlan":1,"interface":1,"ethernet":1}
,"bridge":{"protocol":1,"rstp":1,"sw3":1,"create":1,"group":1}
,"protocol":{"rstp":1}
,"rstp":{"vlan-bridge":1,"vlan-aware":1}
,"vlan-bridge":{"create":1}
,"create":{"bridge":1,"vlan":1,"default":1}
,"vlan-aware":{"bridge":1}
,"vlan":{"database":1,"configure":1,"bridge":1,"allow":1}
,"database":{"enter":1}
,"(config-vlan)":{"vlan":1,"exit":1}
,"exit":{"exit":1,"vlan":1}
,"interface":{"eth1":1,"mode":1,"eth2":1,"switch":1}
,"eth1":{"configure":1,"sw3":1,"switch":1,"bridge":1}
,"(config-if)":{"switchport":1,"bridge-group":1}
,"switchport":{"configure":1,"mode":1,"trunk":1}
,"switch":{"port":1}
,"port":{"sw3":1}
,"bridge-group":{"configure":1}
,"group":{"sw3":1}
,"trunk":{"configure":1,"sw3":1,"allowed":1}
,"allowed":{"vlan":1}
,"allow":{"vlans":1}
,"vlans":{"interface":1}
,"eth2":{"configure":1,"sw3":1,"bridge":1,"mode":1}
,"ethernet":{"cfm":1}
,"cfm":{"default-md-level":1}
,"default-md-level":{"entry":1}
,"entry":{"vid":1}
,"vid":{"level":1}
,"level":{"mip-creation":1,"table":1}
,"mip-creation":{"default":1}
,"default":{"bridge":1,"level":1}
,"table":{"control":1}
,"control":{"mip":1}
,"mip":{"creation":1}
,"creation":{"permissions":1}
}
;Search.control.loadWordPairs(pairs);
