var pairs =
{
"pbb":{"mep":1,"configuration":1}
,"mep":{"mpid":1,"configuration":1,"syntax":1,"<1-8191>":1}
,"mpid":{"command":1,"mpid":1,"((vlan":1,"mep":1,"(config-cfm-pbb-mep)":1}
,"command":{"enter":1,"mode":1}
,"enter":{"ethernet":1}
,"ethernet":{"cfm":1}
,"cfm":{"pbb":1}
,"configuration":{"mode":1}
,"mode":{"configure":1,"ethernet":1,"examples":1}
,"configure":{"given":1}
,"given":{"mep":1}
,"syntax":{"pbb":1}
,"((vlan":{"vlan_id":1}
,"vlan_id":{"isid":1}
,"isid":{"isid)":1,"service":1}
,"isid)":{"parameters":1}
,"parameters":{"mpid":1}
,"<1-8191>":{"vlan":1}
,"vlan":{"vlan":1,"vlanid":1,"<1-4094>":1}
,"vlanid":{"vlan":1}
,"<1-4094>":{"isid":1}
,"service":{"instance":1}
,"instance":{"isid":1,"<1-16777214>":1}
,"<1-16777214>":{"command":1}
,"examples":{"(config-ether-cfm-pbb)":1}
,"(config-ether-cfm-pbb)":{"pbb":1}
}
;Search.control.loadWordPairs(pairs);
