var pairs =
{
"mac":{"address":1,"addresses":1,"added":1,"either":1}
,"address":{"authentication":1,"configured":1}
,"authentication":{"authentication":1,"mac":1,"username":1,"succeeds":1}
,"addresses":{"supported":1,"incoming":1}
,"supported":{"using":1}
,"using":{"radius":1}
,"radius":{"server":1}
,"server":{"contains":1,"authentication":1}
,"contains":{"database":1}
,"database":{"valid":1}
,"valid":{"users":1}
,"users":{"mac-auth":1}
,"mac-auth":{"option":1}
,"option":{"enabled":1}
,"enabled":{"interface":1,"case":1}
,"interface":{"source":1}
,"source":{"mac":1,"address":1}
,"incoming":{"frame":1}
,"frame":{"sent":1}
,"sent":{"authentication":1}
,"username":{"password":1}
,"password":{"source":1}
,"configured":{"radius":1}
,"succeeds":{"otherwise":1,"source":1}
,"otherwise":{"fails":1}
,"fails":{"authentication":1}
,"added":{"forwarding":1,"restricted":1}
,"forwarding":{"table":1,"enabled":1}
,"table":{"forwarding":1,"discarded":1}
,"case":{"failure":1}
,"failure":{"source":1}
,"either":{"added":1}
,"discarded":{"added":1}
,"restricted":{"vlan":1}
}
;Search.control.loadWordPairs(pairs);
