var pairs =
{
"ospf6_enable_db_summary_opt":{"function":1,"(u_int32_t":1}
,"function":{"enables":1,"called":1,"succeeds":1}
,"enables":{"ospfv3":1}
,"ospfv3":{"database":1,"process":1}
,"database":{"summary":1}
,"summary":{"list":1}
,"list":{"optimization":1}
,"optimization":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"enable":1}
,"enable":{"db-summary-op":1}
,"db-summary-op":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf6_enable_db_summary_opt":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1}
,"char":{"*tag)":1}
,"*tag)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"exist":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"tag":1}
,"tag":{"ospfv3":1,"output":1}
,"process":{"tag":1,"exist":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"ospf6_api_set_err_vr_not_exist":1}
,"ospf6_api_set_err_vr_not_exist":{"virtual":1}
,"exist":{"ospf6_api_set_err_process_not_exist":1,"ospf6_api_set_success":1}
,"ospf6_api_set_err_process_not_exist":{"process":1}
,"ospf6_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
