var pairs =
{
"interfaces":{"rip":1}
,"rip":{"client":1,"directly":1,"management":1,"neighbors":1}
,"client":{"bfd":1}
,"bfd":{"communication":1,"using":1,"client":1,"rip":1,"graceful":1}
,"communication":{"required":1}
,"required":{"two":1,"specify":1}
,"two":{"modules":1}
,"modules":{"rip":1}
,"directly":{"interacts":1}
,"interacts":{"bfd":1}
,"using":{"bfd":1}
,"management":{"interface":1}
,"interface":{"bfd":1,"provides":1}
,"provides":{"forwarding":1}
,"forwarding":{"plane":1}
,"plane":{"liveliness":1}
,"liveliness":{"detection":1}
,"detection":{"rip":1}
,"neighbors":{"typically":1}
,"typically":{"module":1}
,"module":{"creates":1}
,"creates":{"deletes":1}
,"deletes":{"updates":1}
,"updates":{"sessions":1}
,"sessions":{"required":1}
,"specify":{"bfd":1}
,"graceful":{"restart":1}
,"restart":{"parameters":1}
,"parameters":{"session":1}
}
;Search.control.loadWordPairs(pairs);
