var pairs =
{
"overview":{"port":1}
,"port":{"mirroring":1,"network":1,"commonly":1}
,"mirroring":{"used":1}
,"used":{"network":1}
,"network":{"switches":1,"packets":1,"monitoring":1,"appliances":1,"traffic":1}
,"switches":{"send":1}
,"send":{"copies":1}
,"copies":{"network":1}
,"packets":{"seen":1}
,"seen":{"switch":1}
,"switch":{"port":1}
,"monitoring":{"connection":1,"network":1}
,"connection":{"switch":1}
,"commonly":{"used":1}
,"appliances":{"require":1}
,"require":{"monitoring":1}
,"traffic":{"intrusion-detection":1}
,"intrusion-detection":{"system":1}
,"system":{"zebos-xp":1}
,"zebos-xp":{"spanning":1}
,"spanning":{"tree":1}
,"tree":{"protocol":1}
,"protocol":{"modules":1}
,"modules":{"support":1}
,"support":{"port":1}
}
;Search.control.loadWordPairs(pairs);
