var pairs =
{
"multi":{"protocol":1}
,"protocol":{"label":1,"traffic":1}
,"label":{"switching":1,"distribution":1,"switch":1,"switched":1}
,"switching":{"protocols":1,"(mpls)":1}
,"protocols":{"multi-protocol":1,"features":1}
,"multi-protocol":{"label":1}
,"(mpls)":{"operates":1}
,"operates":{"layer":1}
,"layer":{"operated":1,"(data":1,"(network":1,"virtual":1}
,"operated":{"traditional":1}
,"traditional":{"definitions":1}
,"definitions":{"layer":1}
,"(data":{"link":1}
,"link":{"layer)":1}
,"layer)":{"layer":1,"mpls":1}
,"(network":{"layer)":1}
,"mpls":{"modules":1,"module":1,"multi":1,"high-level":1,"high":1,"onm":1,"software":1,"routing":1}
,"modules":{"provide":1}
,"provide":{"integration":1}
,"integration":{"enterprise":1}
,"enterprise":{"edge":1}
,"edge":{"core":1}
,"core":{"communications":1}
,"communications":{"equipment":1}
,"equipment":{"zebos-xp":1}
,"zebos-xp":{"mpls":1}
,"module":{"supports":1,"interacts":1,"configure":1,"providing":1,"establishes":1,"de-multiplexes":1}
,"supports":{"following":1}
,"following":{"protocols":1,"summarizes":1}
,"features":{"label":1}
,"distribution":{"protocol":1}
,"traffic":{"engineering":1,"engineered":1}
,"engineering":{"resource":1,"differentiated":1}
,"resource":{"reservation":1}
,"reservation":{"protocol-traffic":1}
,"protocol-traffic":{"engineering":1}
,"differentiated":{"services":1}
,"services":{"layer":1}
,"virtual":{"private":1}
,"private":{"network":1}
,"network":{"layer":1,"mpls-tp":1}
,"mpls-tp":{"operation":1}
,"operation":{"administration":1}
,"administration":{"management":1}
,"management":{"information":1}
,"information":{"mpls":1,"required":1,"handles":1,"oam":1,"base":1}
,"switch":{"developer":1}
,"developer":{"guide":1}
,"guide":{"figure":1}
,"figure":{"2-8":1}
,"2-8":{"shows":1}
,"shows":{"mpls":1}
,"high-level":{"architecture":1}
,"architecture":{"mpls":1,"following":1,"imish":1}
,"high":{"level":1}
,"level":{"architecture":1}
,"summarizes":{"architecture":1}
,"imish":{"provides":1,"oamd":1,"display":1}
,"provides":{"commands":1,"configuration":1,"necessary":1}
,"commands":{"configure":1,"proactive":1}
,"configure":{"mpls\u002Fmpls-tp":1,"on-demand":1}
,"mpls\u002Fmpls-tp":{"on-demand":1,"transport":1,"oam":1}
,"on-demand":{"oams":1,"oam":1,"proactive":1}
,"oams":{"module":1}
,"interacts":{"mpls":1,"nsm":1}
,"onm":{"interface":1,"send":1}
,"interface":{"oamd":1,"imish":1}
,"oamd":{"module":1,"performs":1,"uses":1,"mpls":1,"send":1,"registering":1,"mpls\u002Fmpls-tp":1,"further":1}
,"oam":{"mpls":1,"functionality":1,"session":1,"activities":1,"payload":1,"payloads":1}
,"performs":{"oam":1,"on-demand":1}
,"functionality":{"oamd":1}
,"uses":{"mpls":1,"pal":1}
,"send":{"results":1,"receive":1,"oam":1}
,"results":{"active":1,"end-user":1}
,"active":{"on-demand":1}
,"session":{"imish":1}
,"display":{"results":1}
,"end-user":{"oamd":1}
,"proactive":{"oam":1,"oams":1}
,"activities":{"provides":1}
,"configuration":{"show":1}
,"show":{"commands":1}
,"nsm":{"mpls\u002Fmpls-tp":1,"houses":1,"nsm":1,"installs":1}
,"transport":{"path":1}
,"path":{"information":1,"(lsp)":1,"rsvp-te":1,"module":1,"sends":1}
,"required":{"transmit":1,"transport":1,"process":1}
,"transmit":{"oam":1}
,"payload":{"act":1,"uses":1,"transmission":1,"received":1}
,"act":{"received":1}
,"received":{"oam":1,"oamd":1,"transport":1}
,"pal":{"send":1,"interface":1}
,"receive":{"oam":1}
,"payloads":{"via":1,"mpls":1,"received":1}
,"via":{"mpls":1}
,"software":{"forwarder":1,"forwarder\u002Fhardware":1}
,"forwarder":{"nsm":1,"provides":1,"aids":1,"transmits":1}
,"houses":{"mpls\u002Fmpls-tp":1,"mpls":1}
,"handles":{"oamd":1}
,"providing":{"required":1}
,"transmission":{"reception":1}
,"reception":{"ldp":1}
,"ldp":{"distributes":1,"sends":1,"sessions":1,"rsvp-te":1}
,"distributes":{"labels":1}
,"labels":{"peers":1}
,"peers":{"form":1,"(t-ldp)":1}
,"form":{"label":1}
,"switched":{"path":1}
,"(lsp)":{"nsm":1}
,"routing":{"information":1}
,"base":{"ldp":1}
,"sends":{"ftn\u002Film":1,"oamd":1}
,"ftn\u002Film":{"obtained":1,"nsm":1}
,"obtained":{"result":1}
,"result":{"lsp":1}
,"lsp":{"signaling":1}
,"signaling":{"nsm":1}
,"installs":{"routes":1,"mpls":1}
,"routes":{"mpls":1,"similar":1}
,"forwarder\u002Fhardware":{"used":1,"pal":1}
,"used":{"forward":1}
,"forward":{"data":1}
,"data":{"packets":1}
,"packets":{"module":1}
,"establishes":{"ldp":1,"traffic":1}
,"sessions":{"non-directly":1}
,"non-directly":{"connected":1}
,"connected":{"peers":1}
,"(t-ldp)":{"rsvp-te":1}
,"rsvp-te":{"establishes":1,"queries":1,"sends":1}
,"engineered":{"label":1}
,"queries":{"cspf":1}
,"cspf":{"compute":1}
,"compute":{"explicit":1}
,"explicit":{"routes":1}
,"similar":{"ldp":1}
,"necessary":{"apis":1}
,"apis":{"oamd":1}
,"aids":{"oamd":1}
,"registering":{"callbacks":1}
,"callbacks":{"required":1}
,"process":{"incoming":1}
,"incoming":{"oam":1}
,"transmits":{"oam":1}
,"de-multiplexes":{"mpls\u002Fmpls-tp":1}
,"further":{"processing":1}
}
;Search.control.loadWordPairs(pairs);
