var pairs =
{
"contents":{"guide":1}
,"guide":{"contains":1}
,"contains":{"chapters":1}
,"chapters":{"chapter":1}
,"chapter":{"introduction":1,"internal":1,"messages":1,"label":1,"constrained":1,"network":1,"quality":1,"mpls":1,"differentiated":1,"refresh":1,"fast":1,"command":1,"management":1,"point-to-multipoint":1}
,"introduction":{"chapter":1}
,"internal":{"structures":1}
,"structures":{"chapter":1}
,"messages":{"chapter":1}
,"label":{"switched":1,"pool":1}
,"switched":{"router":1}
,"router":{"roles":1}
,"roles":{"chapter":1}
,"constrained":{"shortest":1}
,"shortest":{"path":1}
,"path":{"first":1}
,"first":{"chapter":1}
,"network":{"services":1}
,"services":{"module":1,"chapter":1}
,"module":{"chapter":1}
,"pool":{"manager":1}
,"manager":{"chapter":1}
,"quality":{"service":1}
,"service":{"chapter":1}
,"mpls":{"forwarder":1}
,"forwarder":{"chapter":1}
,"differentiated":{"services":1}
,"refresh":{"reduction":1}
,"reduction":{"chapter":1}
,"fast":{"reroute":1}
,"reroute":{"chapter":1}
,"command":{"api":1}
,"api":{"chapter":1}
,"management":{"information":1}
,"information":{"base":1}
,"base":{"api":1}
,"point-to-multipoint":{"services":1}
}
;Search.control.loadWordPairs(pairs);
