var pairs =
{
"ospf_if_transmit_delay_set":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"called":1,"succeeds":1}
,"sets":{"transmit":1}
,"transmit":{"delay":1}
,"delay":{"interval":1}
,"interval":{"(seconds)":1,"seconds":1,"outside":1}
,"(seconds)":{"current":1}
,"current":{"interface":1}
,"interface":{"configuration":1,"exists":1,"name":1}
,"configuration":{"stored":1}
,"stored":{"regardless":1}
,"regardless":{"whether":1}
,"whether":{"real":1}
,"real":{"interface":1}
,"exists":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"ospf":1}
,"ospf":{"transmit-delay":1}
,"transmit-delay":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf_if_transmit_delay_set":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1}
,"char":{"*name":1}
,"*name":{"u_int32_t":1}
,"u_int32_t":{"delay)":1}
,"delay)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"found":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"name":1}
,"name":{"interface":1,"delay":1}
,"seconds":{"65535>":1}
,"65535>":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf_api_set_success":1}
,"ospf_api_set_success":{"function":1}
,"succeeds":{"ospf_api_set_err_if_transmit_delay_invalid":1}
,"ospf_api_set_err_if_transmit_delay_invalid":{"given":1}
,"given":{"interval":1}
,"outside":{"range":1}
,"range":{"ospf_api_set_err_vr_not_exist":1}
,"ospf_api_set_err_vr_not_exist":{"virtual":1}
}
;Search.control.loadWordPairs(pairs);
