var pairs =
{
"show":{"debug":1}
,"debug":{"beb":1}
,"beb":{"command":1,"node":1,"(sno":1,"sno":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"debugging":1}
,"debugging":{"information":1}
,"information":{"beb":1}
,"node":{"type":1}
,"type":{"command":1,"port":1}
,"syntax":{"show":1}
,"(sno":{"6))":1}
,"6))":{"parameters":1}
,"parameters":{"sno":1}
,"sno":{"specify":1,"printing":1}
,"specify":{"type":1}
,"port":{"customer":1,"virtual":1,"provider":1,"vipxref":1,"command":1}
,"customer":{"network":1,"backbone":1}
,"network":{"port":1}
,"virtual":{"instance":1}
,"instance":{"port":1}
,"provider":{"instance":1}
,"vipxref":{"pip2vip":1}
,"pip2vip":{"customer":1}
,"backbone":{"port":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"show":1}
,"printing":{"cnp":1}
,"cnp":{"nodes":1}
,"nodes":{"========================================================sid":1}
,"========================================================sid":{"icompid":1}
,"icompid":{"port_num":1}
,"port_num":{"service_type":1}
,"service_type":{"srv_stat":1}
,"srv_stat":{"ref_port":1}
,"ref_port":{"svlans":1}
,"svlans":{"========================================================":1}
}
;Search.control.loadWordPairs(pairs);
