var pairs =
{
"ethernet":{"oam":1}
,"oam":{"remote-loopback":1}
,"remote-loopback":{"{supported":1,"support":1,"enable":1,"supported":1,"timeout":1}
,"{supported":{"timeout}":1,"timeout":1}
,"timeout}":{"command":1,"parameters":1}
,"command":{"configure":1,"remove":1,"syntax":1,"default":1,"mode":1}
,"configure":{"remote":1,"terminal":1}
,"remote":{"loopback":1,"dte":1}
,"loopback":{"interface":1,"support":1,"timeout":1,"supported":1,"state":1,"administratively":1}
,"interface":{"form":1,"command":1,"mode":1,"eth1":1}
,"form":{"command":1}
,"remove":{"remote-loopback":1}
,"support":{"interface":1,"timeout":1}
,"syntax":{"ethernet":1}
,"timeout":{"<1-10>}":1,"specify":1,"value":1,"configured":1,"configure":1}
,"<1-10>}":{"ethernet":1}
,"parameters":{"supported":1}
,"supported":{"specify":1,"timeout":1,"configure":1}
,"specify":{"configure":1,"remote":1,"number":1}
,"value":{"<1-10>":1}
,"<1-10>":{"specify":1}
,"number":{"seconds":1}
,"seconds":{"dte":1}
,"dte":{"wait":1,"respond":1,"remains":1,"responds":1}
,"wait":{"remote":1}
,"respond":{"ethernet":1}
,"enable":{"command":1}
,"default":{"default":1,"state":1}
,"state":{"remote":1,"until":1}
,"configured":{"local":1}
,"local":{"dte":1}
,"remains":{"remote":1}
,"until":{"remote":1}
,"responds":{"user":1}
,"user":{"stops":1}
,"stops":{"remote":1}
,"administratively":{"command":1}
,"mode":{"interface":1,"examples":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth1":{"(config-if)":1}
,"(config-if)":{"ethernet":1}
}
;Search.control.loadWordPairs(pairs);
