var pairs =
{
"ospf":{"authentication":1,"packet":1}
,"authentication":{"three":1,"null":1,"(md5)":1,"configure":1,"type":1,"used":1}
,"three":{"types":1}
,"types":{"ospf":1}
,"null":{"(type":1}
,"(type":{"routing":1,"uses":1,"cryptographic":1}
,"routing":{"exchanges":1}
,"exchanges":{"network":1}
,"network":{"authenticated":1,"message":1,"router":1}
,"authenticated":{"simple":1}
,"simple":{"text":1}
,"text":{"(type":1}
,"uses":{"clear-text":1}
,"clear-text":{"passwords":1}
,"passwords":{"password":1}
,"password":{"neighbors":1}
,"neighbors":{"communicate":1}
,"communicate":{"network":1}
,"message":{"digest":1}
,"digest":{"authentication":1,"basis":1}
,"(md5)":{"(type":1}
,"cryptographic":{"authentication":1}
,"configure":{"key":1,"authentication":1}
,"key":{"key":1,"identifier":1,"ospf":1}
,"identifier":{"neighbors":1}
,"router":{"generates":1}
,"generates":{"message":1}
,"basis":{"key":1,"per-area":1,"additionally":1}
,"packet":{"adds":1,"configure":1}
,"adds":{"ospf":1}
,"type":{"per-interface":1,"different":1,"interface":1,"overrides":1,"authentication":1,"specified":1,"area":1}
,"per-interface":{"basis":1}
,"per-area":{"basis":1}
,"additionally":{"interface":1}
,"interface":{"area":1,"authentication":1}
,"area":{"authentication":1,"used":1}
,"used":{"together":1}
,"together":{"interface":1}
,"different":{"area":1}
,"overrides":{"area":1}
,"specified":{"interface":1}
}
;Search.control.loadWordPairs(pairs);
