var pairs =
{
"bgp_scan_time_unset":{"function":1,"(struct":1}
,"function":{"resets":1,"called":1}
,"resets":{"next-hop":1}
,"next-hop":{"scan":1}
,"scan":{"time":1,"interval":1}
,"time":{"default":1}
,"default":{"value":1}
,"value":{"seconds":1,"bgp_api_set_success":1}
,"seconds":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"bgp":1}
,"bgp":{"scan-time":1,"*bgp)":1,"bgp":1,"instance":1}
,"scan-time":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"bgp_scan_time_unset":1}
,"(struct":{"bgp":1}
,"*bgp)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bgp":1,"none":1}
,"instance":{"case":1}
,"case":{"otherwise":1}
,"otherwise":{"null":1}
,"null":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"bgp_api_set_success":{"api":1}
,"api":{"successful":1}
,"successful":{"(0)":1}
,"(0)":{"bgp_api_set_error":1}
,"bgp_api_set_error":{"modify":1}
,"modify":{"scan":1}
,"interval":{"fails":1}
,"fails":{"(-1)":1}
}
;Search.control.loadWordPairs(pairs);
