var pairs =
{
"status":{"commands":1,"manual":1,"transmitted":1}
,"commands":{"status":1,"related":1}
,"related":{"configurations":1}
,"configurations":{"statically":1}
,"statically":{"configured":1}
,"configured":{"mpls":1,"(static":1}
,"mpls":{"pws":1,"l2-circuit":1}
,"pws":{"mpls":1}
,"l2-circuit":{"name":1}
,"name":{"vc-id":1}
,"vc-id":{"peer-ip":1}
,"peer-ip":{"control-word":1}
,"control-word":{"tunnel-id":1}
,"tunnel-id":{"tunnel-id":1,"(manual":1}
,"(manual":{"(pw-status":1}
,"(pw-status":{"(refresh-time))":1}
,"(refresh-time))":{"parameter":1}
,"parameter":{"description":1}
,"description":{"pw-status":1}
,"pw-status":{"enables":1}
,"enables":{"status":1}
,"manual":{"configured":1}
,"(static":{"pw)":1}
,"pw)":{"disable":1}
,"disable":{"omit":1}
,"omit":{"reconfigure":1}
,"reconfigure":{"refresh-time":1}
,"refresh-time":{"time":1}
,"time":{"seconds":1}
,"seconds":{"status":1}
,"transmitted":{"periodically":1}
,"periodically":{"fault":1}
,"fault":{"occurred":1}
,"occurred":{"range":1}
,"range":{"<0-65535>":1}
,"<0-65535>":{"default":1}
,"default":{"600":1}
,"600":{"seconds":1}
}
;Search.control.loadWordPairs(pairs);
