var pairs =
{
"configure":{"terminal":1,"mode":1,"advertisement":1,"priority":1}
,"terminal":{"enter":1}
,"enter":{"configure":1}
,"mode":{"(config)":1,"specify":1,"enter":1}
,"(config)":{"router":1}
,"router":{"vrrp":1,"within":1,"(config-router)":1,"mode":1}
,"vrrp":{"eth0":1,"instance":1,"session":1,"router":1}
,"eth0":{"create":1,"(config-router)":1}
,"create":{"vrrp":1}
,"instance":{"interface":1}
,"interface":{"eth0":1}
,"(config-router)":{"virtual-ip":1,"preempt":1,"advertisement-interval":1,"enable":1,"exit":1,"priority":1}
,"virtual-ip":{"10.10.10.81":1,"10.10.10.82":1}
,"10.10.10.81":{"owner":1}
,"owner":{"virtual":1}
,"virtual":{"address":1,"router":1}
,"address":{"vrrp":1}
,"session":{"define":1,"router":1,"(config-router)":1,"two":1}
,"define":{"default":1}
,"default":{"state":1}
,"state":{"(owner)":1}
,"(owner)":{"vrrp":1}
,"within":{"virtual":1}
,"preempt":{"true":1,"mode":1}
,"true":{"preempt":1}
,"specify":{"highest":1}
,"highest":{"priority":1}
,"priority":{"function":1,"200":1}
,"function":{"backup":1}
,"backup":{"master":1,"router":1}
,"master":{"master":1,"unavailable":1}
,"unavailable":{"(config-router)":1}
,"advertisement-interval":{"100":1}
,"100":{"configure":1,"centi":1}
,"advertisement":{"interval":1}
,"interval":{"100":1}
,"centi":{"seconds":1}
,"seconds":{"(value":1}
,"(value":{"multiple":1}
,"multiple":{"(config-router)":1}
,"enable":{"enable":1,"vrrp":1}
,"exit":{"exit":1,"router":1}
,"10.10.10.82":{"virtual":1}
,"200":{"configure":1,"(less":1}
,"(less":{"255)":1}
,"255)":{"backup":1}
,"two":{"router":1}
}
;Search.control.loadWordPairs(pairs);
