var pairs =
{
"definition":{"struct":1}
,"struct":{"elmi_ifp":1,"elmi_bridge":1,"elmi_master":1,"elmi_port":1,"elmi_vlan_bmp":1,"list":1,"elmi_uni_info":1}
,"elmi_ifp":{"{struct":1}
,"{struct":{"interface":1}
,"interface":{"*ifp":1}
,"*ifp":{"struct":1}
,"elmi_bridge":{"*br":1}
,"*br":{"struct":1}
,"elmi_master":{"*elmim":1}
,"*elmim":{"struct":1}
,"elmi_port":{"*port":1}
,"*port":{"struct":1}
,"elmi_vlan_bmp":{"*vlan_bmp":1}
,"*vlan_bmp":{"struct":1}
,"list":{"*evc_status_list":1,"*cevlan_evc_map_list":1}
,"*evc_status_list":{"\u002F\u002F\u002F<list":1}
,"\u002F\u002F\u002F<list":{"elmi_evc_status":1,"ce-vlan":1}
,"elmi_evc_status":{"nodes":1}
,"nodes":{"struct":1}
,"elmi_uni_info":{"*uni_info":1}
,"*uni_info":{"struct":1}
,"*cevlan_evc_map_list":{"\u002F\u002F\u002F<list":1}
,"ce-vlan":{"evc":1}
,"evc":{"mapping":1,"asysnchronous":1}
,"mapping":{"node":1}
,"node":{"u_int32_t":1}
,"u_int32_t":{"ifindex":1}
,"ifindex":{"u_int16_t":1}
,"u_int16_t":{"pvid":1}
,"pvid":{"bool_t":1}
,"bool_t":{"active":1}
,"active":{"u_int8_t":1}
,"u_int8_t":{"dev_addr":1,"elmi_enabled":1,"uni_mode":1,"port_type":1,"bw_profile_level":1}
,"dev_addr":{"[elmi_mac_addr_len]":1}
,"[elmi_mac_addr_len]":{"u_int8_t":1}
,"elmi_enabled":{"\u002F\u002F\u002F<flag":1}
,"\u002F\u002F\u002F<flag":{"indicate":1}
,"indicate":{"elmi":1,"uni-c\u002Funi-n":1,"profile":1}
,"elmi":{"enable\u002Fdisable":1}
,"enable\u002Fdisable":{"state":1}
,"state":{"u_int8_t":1}
,"uni_mode":{"\u002F\u002F\u002F<flag":1}
,"uni-c\u002Funi-n":{"mode":1}
,"mode":{"u_int8_t":1}
,"port_type":{"u_int8_t":1}
,"bw_profile_level":{"\u002F\u002F\u002F<flag":1}
,"profile":{"type":1}
,"type":{"\u002F\u002F\u002F(per":1}
,"\u002F\u002F\u002F(per":{"uni\u002Fevc\u002Fevccos)":1}
,"uni\u002Fevc\u002Fevccos)":{"\u002F*field":1}
,"\u002F*field":{"maintain":1}
,"maintain":{"configured":1,"single":1}
,"configured":{"polling":1,"status":1}
,"polling":{"time":1,"verification":1,"counter":1}
,"time":{"interval":1}
,"interval":{"*\u002Fu_int8_t":1}
,"*\u002Fu_int8_t":{"polling_time":1,"polling_verification_time":1,"enable_pvt":1,"asynchronous_time":1}
,"polling_time":{"\u002F*field":1}
,"verification":{"time":1}
,"polling_verification_time":{"\u002F*field":1}
,"status":{"counter":1}
,"counter":{"threshold":1}
,"threshold":{"value":1}
,"value":{"*\u002Fs_int8_t":1,"*\u002Fu_int16_t":1}
,"*\u002Fs_int8_t":{"status_counter_limit":1}
,"status_counter_limit":{"\u002F*flag":1}
,"\u002F*flag":{"disable":1}
,"disable":{"pvt":1}
,"pvt":{"*\u002Fu_int8_t":1}
,"enable_pvt":{"\u002F*field":1}
,"*\u002Fu_int16_t":{"polling_counter_limit":1}
,"polling_counter_limit":{"\u002F*field":1}
,"single":{"evc":1}
,"asysnchronous":{"timer":1}
,"timer":{"*\u002Fu_int8_t":1}
}
;Search.control.loadWordPairs(pairs);
