var pairs =
{
"clear":{"bgp":1,"outgoing":1,"incoming":1}
,"bgp":{"*use":1,"connection":1,"*clear":1,"*in":1,"*out":1,"*soft":1,"*ipv4":1,"clear":1}
,"*use":{"command":1}
,"command":{"reset":1,"syntax":1,"mode":1}
,"reset":{"bgp":1}
,"connection":{"peers":1}
,"peers":{"command":1}
,"syntax":{"clear":1}
,"*clear":{"bgp":1}
,"*in":{"clear":1,"prefix-filter":1}
,"prefix-filter":{"clear":1,"push":1}
,"*out":{"clear":1}
,"*soft":{"clear":1}
,"*ipv4":{"(unicast":1,"unicast":1}
,"(unicast":{"multicast)":1}
,"multicast)":{"clear":1,"prefix-filter":1,"soft":1}
,"soft":{"clear":1,"parameters":1,"reconfig":1}
,"parameters":{"incoming":1}
,"incoming":{"advertised":1,"outgoing":1}
,"advertised":{"routes":1}
,"routes":{"cleared":1,"soft":1,"multicast":1,"prefix-filter":1}
,"cleared":{"prefix-filter":1}
,"push":{"prefix-list":1}
,"prefix-list":{"orf":1}
,"orf":{"inbound":1}
,"inbound":{"soft":1,"update":1}
,"reconfig":{"clear":1,"inbound":1,"outbound":1}
,"outgoing":{"advertised":1,"routes":1}
,"update":{"soft":1,"ipv4":1,"command":1}
,"outbound":{"update":1}
,"ipv4":{"clear":1}
,"multicast":{"multicast":1,"prefixes":1}
,"prefixes":{"unicast":1,"clear":1}
,"unicast":{"unicast":1,"prefixes":1,"prefix-filter":1}
,"mode":{"privileged":1,"examples":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"examples":{"clear":1}
}
;Search.control.loadWordPairs(pairs);
