var pairs =
{
"bridge":{"spanning-tree":1,"parameter":1,"command":1,"<1-32>":1,"group":1,"bridge-forward":1,"forwarding":1,"ports":1}
,"spanning-tree":{"command":1,"enable":1}
,"command":{"enable":1,"syntax":1,"mode":1}
,"enable":{"spanning":1,"bridge":1,"(bridge-forward":1,"enables":1,"configure":1,"bridge-forward":1}
,"spanning":{"tree":1}
,"tree":{"protocol":1}
,"protocol":{"bridge":1}
,"parameter":{"disable":1,"default":1}
,"disable":{"spanning":1}
,"syntax":{"bridge":1}
,"<1-32>":{"spanning-tree":1,"specify":1}
,"(bridge-forward":{"parameters":1}
,"parameters":{"<1-32>":1}
,"specify":{"bridge":1}
,"group":{"enable":1}
,"enables":{"spanning":1}
,"bridge-forward":{"puts":1,"option":1}
,"puts":{"ports":1}
,"ports":{"specified":1,"blocking":1}
,"specified":{"bridge":1}
,"forwarding":{"state":1}
,"state":{"default":1,"command":1}
,"default":{"bridge-forward":1,"behavior":1}
,"option":{"entered":1}
,"entered":{"using":1}
,"using":{"parameter":1}
,"behavior":{"put":1}
,"put":{"bridge":1}
,"blocking":{"state":1}
,"mode":{"configure":1,"examples":1}
,"configure":{"mode":1,"terminal":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"bridge":1}
}
;Search.control.loadWordPairs(pairs);
