var pairs =
{
"nsm_api_mpls_tp_ilm_swap_unconfig":{"function":1,"internal":1,"(u_int32_t":1}
,"function":{"validates":1,"called":1,"nsm_api_mpls_tp_ilm_swap_unconfig":1,"executed":1}
,"validates":{"deletes":1}
,"deletes":{"specified":1}
,"specified":{"ilm":1}
,"ilm":{"entry":1,"cannot":1}
,"entry":{"tunnel\u0027s":1,"exist":1}
,"tunnel\u0027s":{"lsp":1}
,"lsp":{"transit":1,"structure":1,"forward":1}
,"transit":{"nodes":1}
,"nodes":{"function":1}
,"called":{"ilm-entry":1}
,"ilm-entry":{"swap":1,"label":1}
,"swap":{"command":1,"label":1}
,"command":{"command":1,"ilm-entry":1,"nsm_mplstp_ilm_swap_unconfig":1}
,"label":{"ifname":1,"output":1,"invalid":1}
,"ifname":{"swap":1,"calls":1}
,"calls":{"internal":1,"function":1}
,"internal":{"command":1,"commands":1}
,"nsm_mplstp_ilm_swap_unconfig":{"calls":1}
,"commands":{"outside":1}
,"outside":{"scope":1}
,"scope":{"document":1}
,"document":{"refer":1}
,"refer":{"source":1}
,"source":{"file":1}
,"file":{"nsm\u002Fmplstp\u002Fnsm_mplstp_cli.c":1}
,"nsm\u002Fmplstp\u002Fnsm_mplstp_cli.c":{"syntax":1}
,"syntax":{"int":1}
,"int":{"nsm_api_mpls_tp_ilm_swap_unconfig":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"struct":1,"virtual":1}
,"struct":{"mpls_tp_lsp":1}
,"mpls_tp_lsp":{"*lsp":1}
,"*lsp":{"u_char":1,"pointer":1}
,"u_char":{"dir":1}
,"dir":{"u_int32_t":1,"identifies":1}
,"u_int32_t":{"in_ifindex":1,"in_label":1,"out_ifindex":1,"out_label)":1}
,"in_ifindex":{"u_int32_t":1,"incoming":1}
,"in_label":{"u_int32_t":1,"incoming":1}
,"out_ifindex":{"u_int32_t":1}
,"out_label)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"(vr)":1,"exist":1}
,"(vr)":{"instance":1}
,"instance":{"*lsp":1}
,"pointer":{"mpls-tp":1}
,"mpls-tp":{"lsp":1,"provider":1,"datalink":1}
,"structure":{"dir":1}
,"identifies":{"nhlfe":1}
,"nhlfe":{"lsp":1}
,"forward":{"reverse":1}
,"reverse":{"in_ifindex":1}
,"incoming":{"interface":1,"label":1,"mpls-tp":1,"provider":1}
,"interface":{"index":1,"cannot":1,"operating":1,"nsm_api_set_err_mpls_tp_in_if_no_dl":1,"nsm_api_set_err_mpls_tp_out_dl_id_not_set":1,"nsm_api_set_err_mpls_tp_in_dl_id_not_set":1,"nsm_api_set_err_mpls_tp_assoc_ilm_del":1}
,"index":{"in_label":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_api_set_success":1}
,"nsm_api_set_success":{"function":1}
,"executed":{"properly":1}
,"properly":{"nsm_api_set_err_vr_not_exist":1}
,"nsm_api_set_err_vr_not_exist":{"virtual":1}
,"exist":{"nsm_api_set_err_mpls_tp_ilm_not_exists":1,"nsm_api_set_err_mpls_tp_invalid_out_label":1,"outgoing":1,"incoming":1}
,"nsm_api_set_err_mpls_tp_ilm_not_exists":{"ilm":1}
,"nsm_api_set_err_mpls_tp_invalid_out_label":{"outgoing":1}
,"outgoing":{"label":1,"mpls-tp":1,"provider":1}
,"invalid":{"nsm_api_set_err_mpls_tp_invalid_in_label":1,"nsm_api_set_err_mpls_tp_out_if_loopback":1}
,"nsm_api_set_err_mpls_tp_invalid_in_label":{"incoming":1}
,"nsm_api_set_err_mpls_tp_out_if_loopback":{"outgoing":1}
,"provider":{"interface":1}
,"cannot":{"loopback":1,"unconfigured":1}
,"loopback":{"nsm_api_set_err_mpls_tp_in_if_loopback":1,"nsm_api_set_err_mpls_tp_out_if_non_gmpls_dc":1}
,"nsm_api_set_err_mpls_tp_in_if_loopback":{"incoming":1}
,"nsm_api_set_err_mpls_tp_out_if_non_gmpls_dc":{"outgoing":1}
,"operating":{"gmpls":1}
,"gmpls":{"data-control":1}
,"data-control":{"mode":1}
,"mode":{"nsm_api_set_err_mpls_tp_in_if_non_gmpls_dc":1,"nsm_api_set_err_mpls_tp_out_if_no_dl":1}
,"nsm_api_set_err_mpls_tp_in_if_non_gmpls_dc":{"incoming":1}
,"nsm_api_set_err_mpls_tp_out_if_no_dl":{"mpls-tp":1}
,"datalink":{"exist":1}
,"nsm_api_set_err_mpls_tp_in_if_no_dl":{"mpls-tp":1}
,"nsm_api_set_err_mpls_tp_out_dl_id_not_set":{"local-interface-id":1}
,"local-interface-id":{"outgoing":1,"incoming":1}
,"nsm_api_set_err_mpls_tp_in_dl_id_not_set":{"local-interface-id":1}
,"nsm_api_set_err_mpls_tp_assoc_ilm_del":{"bound":1}
,"bound":{"tunnel":1}
,"tunnel":{"ilm":1}
}
;Search.control.loadWordPairs(pairs);
