var pairs =
{
"hal_bridge_set_state":{"function":1,"(char":1}
,"function":{"sets":1,"succeeds":1}
,"sets":{"state":1}
,"state":{"bridge":1}
,"bridge":{"bridge":1,"disabled":1,"name":1}
,"disabled":{"behaves":1}
,"behaves":{"dumb":1}
,"dumb":{"switch":1}
,"switch":{"syntax":1}
,"syntax":{"int":1}
,"int":{"hal_bridge_set_state":1}
,"(char":{"*name":1}
,"*name":{"u_int16_t":1}
,"u_int16_t":{"enable)":1}
,"enable)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"name":1,"none":1}
,"name":{"bridge":1,"enable":1}
,"enable":{"enable\u002Fdisable":1}
,"enable\u002Fdisable":{"spanning":1}
,"spanning":{"tree":1}
,"tree":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"hal_err_bridge_not_exists":1}
,"hal_err_bridge_not_exists":{"hal_success":1}
,"hal_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
