var pairs =
{
"internet":{"world\u2019s":1,"uses":1,"computers":1,"decisions":1,"engineering":1}
,"world\u2019s":{"largest":1}
,"largest":{"computer":1}
,"computer":{"network":1}
,"network":{"serving":1}
,"serving":{"universities":1}
,"universities":{"commercial":1}
,"commercial":{"interests":1}
,"interests":{"government":1}
,"government":{"agencies":1,"agency":1}
,"agencies":{"private":1}
,"private":{"individuals":1}
,"individuals":{"internet":1}
,"uses":{"transmission":1}
,"transmission":{"control":1}
,"control":{"protocol\u002Finternet":1}
,"protocol\u002Finternet":{"protocol":1}
,"protocol":{"(tcp\u002Fip)":1}
,"(tcp\u002Fip)":{"protocols":1}
,"protocols":{"internet":1}
,"computers":{"devices":1}
,"devices":{"run":1}
,"run":{"different":1}
,"different":{"operating":1}
,"operating":{"systems":1}
,"systems":{"government":1}
,"agency":{"single":1}
,"single":{"person":1}
,"person":{"corporate":1}
,"corporate":{"entity":1}
,"entity":{"controls":1}
,"controls":{"internet":1}
,"decisions":{"methods":1}
,"methods":{"standards":1}
,"standards":{"made":1,"groups":1}
,"made":{"standards":1}
,"groups":{"based":1}
,"based":{"input":1}
,"input":{"users":1}
,"users":{"internet":1}
,"engineering":{"task":1}
,"task":{"force":1}
,"force":{"(ietf)":1}
,"(ietf)":{"request":1}
,"request":{"comments":1}
,"comments":{"(rfc)":1}
}
;Search.control.loadWordPairs(pairs);
