var pairs =
{
"overview":{"routing":1}
,"routing":{"information":1,"protocols":1,"table.)":1}
,"information":{"base":1,"topology":1}
,"base":{"(rib)":1,"(fib)":1}
,"(rib)":{"data":1}
,"data":{"structure":1}
,"structure":{"stored":1}
,"stored":{"network":1}
,"network":{"device":1,"destinations":1,"immediately":1,"topology":1}
,"device":{"lists":1}
,"lists":{"routes":1}
,"routes":{"particular":1,"rib":1,"added":1}
,"particular":{"network":1}
,"destinations":{"metrics":1}
,"metrics":{"(distances)":1}
,"(distances)":{"associated":1}
,"associated":{"routes":1}
,"rib":{"contains":1,"discovering":1,"commands":1,"called":1}
,"contains":{"information":1}
,"topology":{"network":1,"primary":1}
,"immediately":{"around":1}
,"around":{"maintaining":1}
,"maintaining":{"rib":1}
,"discovering":{"network":1}
,"primary":{"purpose":1}
,"purpose":{"dynamic":1}
,"dynamic":{"routing":1}
,"protocols":{"bgp":1}
,"bgp":{"rip":1}
,"rip":{"ospf":1}
,"ospf":{"static":1}
,"static":{"fixed":1}
,"fixed":{"routes":1}
,"added":{"rib":1}
,"commands":{"rib":1}
,"called":{"routing":1,"forwarding":1}
,"table.)":{"forwarding":1}
,"forwarding":{"information":1,"table.)":1}
,"(fib)":{"used":1}
,"used":{"find":1}
,"find":{"proper":1}
,"proper":{"interface":1}
,"interface":{"input":1,"forward":1}
,"input":{"interface":1}
,"forward":{"packet":1}
,"packet":{"contrast":1}
,"contrast":{"ribs":1}
,"ribs":{"fibs":1}
,"fibs":{"optimized":1}
,"optimized":{"fast":1}
,"fast":{"lookup":1}
,"lookup":{"destination":1}
,"destination":{"addresses":1}
,"addresses":{"fib":1}
,"fib":{"called":1}
}
;Search.control.loadWordPairs(pairs);
