var pairs =
{
"nsm_sr_api_disable":{"function":1,"(u_int32_t":1}
,"function":{"disables":1,"syntax":1,"succeeds":1}
,"disables":{"segment":1}
,"segment":{"routing":1,"signalling":1}
,"routing":{"(sr)":1,"global":1}
,"(sr)":{"globally":1}
,"globally":{"device":1}
,"device":{"de-initializing":1}
,"de-initializing":{"segment":1}
,"global":{"block":1}
,"block":{"(srgb)":1}
,"(srgb)":{"notifying":1}
,"notifying":{"sr-enabled":1}
,"sr-enabled":{"protocols":1}
,"protocols":{"segment-routing":1}
,"segment-routing":{"mpls":1}
,"mpls":{"command":1,"igp_proto":1}
,"command":{"calls":1}
,"calls":{"function":1}
,"syntax":{"int":1}
,"int":{"nsm_sr_api_disable":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int8_t":1,"virtual":1,"exist":1}
,"u_int8_t":{"*fwd_proto":1,"*igp_proto)":1}
,"*fwd_proto":{"u_int8_t":1}
,"*igp_proto)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"identifier":1}
,"identifier":{"<0-255>":1}
,"<0-255>":{"fwd_proto":1}
,"fwd_proto":{"protocol":1}
,"protocol":{"used":1}
,"used":{"forwarding":1,"segment":1}
,"forwarding":{"plane":1}
,"plane":{"mpls":1}
,"igp_proto":{"igp":1}
,"igp":{"protocol":1}
,"signalling":{"ospf":1}
,"ospf":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_success":1}
,"nsm_success":{"function":1}
,"succeeds":{"nsm_api_set_err_vr_not_exist":1}
,"nsm_api_set_err_vr_not_exist":{"vr_id":1}
,"exist":{"nsm_err_internal":1}
,"nsm_err_internal":{"internal":1}
,"internal":{"error":1}
,"error":{"nsm_sr_err_command_not_configured":1}
,"nsm_sr_err_command_not_configured":{"enabled":1}
}
;Search.control.loadWordPairs(pairs);
