var pairs =
{
"terminal":{"monitor":1,"command":1,"current":1}
,"monitor":{"command":1,"(all":1}
,"command":{"enable":1,"used":1,"syntax":1,"mode":1}
,"enable":{"viewing":1}
,"viewing":{"debug":1}
,"debug":{"messages":1,"output":1}
,"messages":{"terminal":1}
,"used":{"without":1,"pvr":1,"either":1}
,"without":{"either":1}
,"either":{"optional":1,"parameter":1}
,"optional":{"parameters":1}
,"parameters":{"may":1,"word":1}
,"may":{"used":1}
,"pvr":{"user":1,"context":1,"debugging":1}
,"user":{"non-pvr":1,"enables":1,"command":1}
,"non-pvr":{"user":1}
,"enables":{"debug":1}
,"output":{"terminal":1}
,"current":{"context":1}
,"context":{"used":1,"contains":1,"include":1}
,"parameter":{"may":1}
,"syntax":{"terminal":1}
,"(all":{"word":1}
,"word":{"parameters":1,"used":1}
,"contains":{"name":1}
,"name":{"included":1}
,"included":{"debugging":1}
,"debugging":{"session":1}
,"session":{"used":1,"command":1}
,"include":{"pvr":1}
,"mode":{"privileged":1,"example":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"example":{"terminal":1}
}
;Search.control.loadWordPairs(pairs);
