var pairs =
{
"bfd_event_session":{"bfd_event_session":1,"enumeration":1,"{bfd_event_session_admin_down":1}
,"enumeration":{"defines":1}
,"defines":{"session":1}
,"session":{"events":1,"administratively":1,"creation":1,"maximum":1}
,"events":{"constant":1}
,"constant":{"description":1}
,"description":{"bfd_event_session_admin_down":1}
,"bfd_event_session_admin_down":{"session":1}
,"administratively":{"configured":1}
,"configured":{"down":1}
,"down":{"bfd_event_session_down":1,"message":1}
,"bfd_event_session_down":{"initial":1,"bfd_event_session_init":1}
,"initial":{"state":1}
,"state":{"session":1,"successful":1}
,"creation":{"bfd_event_session_init":1}
,"bfd_event_session_init":{"transits":1,"bfd_event_session_up":1}
,"transits":{"init":1,"state":1}
,"init":{"reception":1}
,"reception":{"down":1}
,"message":{"remote":1}
,"remote":{"peer":1}
,"peer":{"bfd_event_session_up":1}
,"bfd_event_session_up":{"transits":1,"bfd_event_session_max":1}
,"successful":{"completion":1}
,"completion":{"three-way":1}
,"three-way":{"handshake":1}
,"handshake":{"bfd_event_session_max":1}
,"bfd_event_session_max":{"session":1}
,"maximum":{"definition":1}
,"definition":{"enum":1}
,"enum":{"bfd_event_session":1}
,"{bfd_event_session_admin_down":{"bfd_event_session_down":1}
}
;Search.control.loadWordPairs(pairs);
