var pairs =
{
"ldp_snmp_api_set_label_type":{"call":1,"(struct":1}
,"call":{"sets":1}
,"sets":{"label":1}
,"label":{"type":1}
,"type":{"used":1}
,"used":{"ldp":1}
,"ldp":{"entity":1}
,"entity":{"syntax":1,"ldp":1,"intval":1,"default":1,"return":1}
,"syntax":{"int":1}
,"int":{"ldp_snmp_api_set_label_type":1}
,"(struct":{"ldp_entity":1}
,"ldp_entity":{"*entity":1}
,"*entity":{"s_int32_t":1}
,"s_int32_t":{"intval)":1}
,"intval)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"entity":1}
,"intval":{"label":1}
,"default":{"value":1}
,"value":{"snmp_ag_lbl_type_generic":1}
,"snmp_ag_lbl_type_generic":{"(1)":1}
,"(1)":{"allowed":1}
,"allowed":{"output":1}
,"output":{"parameters":1}
,"return":{"values":1}
,"values":{"ldp_success":1}
,"ldp_success":{"ldp_error":1}
}
;Search.control.loadWordPairs(pairs);
