var pairs =
{
"show":{"rip":1}
,"rip":{"statistics":1,"routing":1}
,"statistics":{"command":1,"specify":1,"(ifname":1,"eth1":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"information":1}
,"information":{"rip":1,"specific":1,"displayed":1}
,"specify":{"interface":1}
,"interface":{"name":1,"command":1,"information":1}
,"name":{"display":1,"interface":1,"eth1":1}
,"specific":{"interface":1}
,"syntax":{"show":1}
,"(ifname":{"parameters":1}
,"parameters":{"ifname":1}
,"ifname":{"name":1}
,"displayed":{"command":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"following":1}
,"following":{"output":1}
,"output":{"displays":1}
,"displays":{"rip":1}
,"routing":{"table":1}
,"table":{"destination":1}
,"destination":{"network":1}
,"network":{"nexthop":1}
,"nexthop":{"metric":1}
,"metric":{"reach":1}
,"reach":{"show":1}
,"eth1":{"interface":1,"sent":1}
,"sent":{"multicast":1,"unicast":1}
,"multicast":{"updates":1,"requests":1}
,"updates":{"sent":1,"recv":1}
,"requests":{"sent":1,"recv":1}
,"unicast":{"updates":1,"requests":1}
,"recv":{"multicast":1,"unicast":1,"bad":1}
,"bad":{"packets":1,"routes":1}
,"packets":{"recv":1}
}
;Search.control.loadWordPairs(pairs);
