var pairs =
{
"nsm_pvlan_api_set_port_mode":{"function":1,"(struct":1}
,"function":{"sets":1,"succeeds":1}
,"sets":{"private":1}
,"private":{"vlan":1}
,"vlan":{"mode":1,"nsm_pvlan_err_provider_bridge":1}
,"mode":{"(host":1,"mode":1}
,"(host":{"promiscuous)":1}
,"promiscuous)":{"interface":1,"output":1}
,"interface":{"syntax":1,"*ifp":1,"pointer":1,"found":1}
,"syntax":{"int":1}
,"int":{"nsm_pvlan_api_set_port_mode":1}
,"(struct":{"interface":1}
,"*ifp":{"enum":1}
,"enum":{"nsm_pvlan_port_mode":1}
,"nsm_pvlan_port_mode":{"mode)":1}
,"mode)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"none":1}
,"ifp":{"interface":1}
,"pointer":{"mode":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"result_ok":1}
,"result_ok":{"function":1}
,"succeeds":{"nsm_vlan_err_ifp_not_bound":1}
,"nsm_vlan_err_ifp_not_bound":{"nsm":1}
,"nsm":{"local":1}
,"local":{"interface":1}
,"found":{"nsm_vlan_err_bridge_not_found":1,"nsm_vlan_err_bridge_not_vlan_aware":1}
,"nsm_vlan_err_bridge_not_found":{"specified":1}
,"specified":{"bridge":1}
,"bridge":{"found":1,"aware":1}
,"nsm_vlan_err_bridge_not_vlan_aware":{"bridge":1}
,"aware":{"vlan":1}
,"nsm_pvlan_err_provider_bridge":{"nsm_vlan_err_invalid_mode":1}
,"nsm_vlan_err_invalid_mode":{"result_error":1}
,"result_error":{"nsm_pvlan_err_invalid_mode":1}
}
;Search.control.loadWordPairs(pairs);
