var pairs =
{
"oam_api_lps_group_scheme_set":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"fails":1,"succeeds":1}
,"sets":{"protection":1}
,"protection":{"scheme":1,"mode":1}
,"scheme":{"protection-group":1,"protection":1,"unidirectional":1,"invalid":1}
,"protection-group":{"identified":1,"name":1,"lookup":1}
,"identified":{"protection-group":1}
,"name":{"syntax":1,"scheme":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"oam_api_lps_group_scheme_set":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"instance":1,"found":1}
,"char":{"*grp_name_str":1}
,"*grp_name_str":{"lps_scheme":1}
,"lps_scheme":{"scheme)":1}
,"scheme)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"instance":{"grp_name_str":1}
,"grp_name_str":{"protection-group":1}
,"mode":{"scheme":1}
,"unidirectional":{"permanent":1,"selector":1}
,"permanent":{"unidirectional":1,"bidirectional":1}
,"selector":{"bidirectional":1,"output":1}
,"bidirectional":{"permanent":1,"selector":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"oam_api_set_err_invalid_lps_scheme":1}
,"oam_api_set_err_invalid_lps_scheme":{"protection":1}
,"invalid":{"oam_api_set_err_vr_not_exist":1}
,"oam_api_set_err_vr_not_exist":{"vr_id":1}
,"found":{"oam_api_set_error_psc_grp_lookup":1}
,"oam_api_set_error_psc_grp_lookup":{"protection-group":1}
,"lookup":{"fails":1}
,"fails":{"oam_api_lps_set_error":1,"due":1}
,"oam_api_lps_set_error":{"function":1}
,"due":{"internal":1}
,"internal":{"errors":1}
,"errors":{"memory":1}
,"memory":{"failure":1}
,"failure":{"oam_api_lps_set_success":1}
,"oam_api_lps_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
