var pairs =
{
"ospf6_set_area_te_enabled":{"function":1,"(char":1}
,"function":{"sets":1,"succeeds":1,"fails":1}
,"sets":{"value":1}
,"value":{"indicates":1}
,"indicates":{"whether":1}
,"whether":{"traffic":1}
,"traffic":{"engineering":1}
,"engineering":{"enabled":1,"status":1}
,"enabled":{"given":1,"ospf6_api_status_disabled":1}
,"given":{"area":1}
,"area":{"syntax":1,"identifier":1}
,"syntax":{"int":1}
,"int":{"ospf6_set_area_te_enabled":1,"status)":1}
,"(char":{"*tag":1}
,"*tag":{"struct":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"area_id":1}
,"area_id":{"int":1,"area":1}
,"status)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"tag":1,"none":1}
,"tag":{"ospfv3":1,"area_id":1}
,"ospfv3":{"process":1}
,"process":{"tag":1}
,"identifier":{"ipv4":1}
,"ipv4":{"address":1}
,"address":{"format":1}
,"format":{"status":1}
,"status":{"traffic":1,"ospf6_api_status_enabled":1}
,"ospf6_api_status_enabled":{"enabled":1}
,"ospf6_api_status_disabled":{"disabled":1}
,"disabled":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"ospf6_api_set_success":1}
,"ospf6_api_set_success":{"function":1}
,"succeeds":{"ospf6_api_set_error":1}
,"ospf6_api_set_error":{"function":1}
}
;Search.control.loadWordPairs(pairs);
