var pairs =
{
"configure":{"6pe":1}
,"6pe":{"solutions":1,"routers":1,"ipv4":1}
,"solutions":{"section":1}
,"section":{"explains":1}
,"explains":{"interconnect":1}
,"interconnect":{"ipv6":1}
,"ipv6":{"islands":1,"provider":1,"reachability":1}
,"islands":{"mpls-enabled":1,"mpls":1}
,"mpls-enabled":{"ipv4":1}
,"ipv4":{"cloud":1,"mpls":1,"illustration":1}
,"cloud":{"approach":1}
,"approach":{"relies":1}
,"relies":{"ipv6":1}
,"provider":{"edge":1,"network":1}
,"edge":{"(6pe)":1,"routers":1}
,"(6pe)":{"routers":1}
,"routers":{"dual":1,"exchange":1,"6pe1":1,"router":1}
,"dual":{"stack":1}
,"stack":{"connect":1}
,"connect":{"ipv6":1}
,"mpls":{"core":1,"6pe":1,"provider":1,"cloud":1}
,"core":{"necessary":1,"using":1,"ipv4":1}
,"necessary":{"run":1}
,"run":{"ipv4":1}
,"exchange":{"ipv6":1}
,"reachability":{"information":1}
,"information":{"transparently":1}
,"transparently":{"core":1}
,"using":{"multi-protocol":1}
,"multi-protocol":{"border":1}
,"border":{"gateway":1}
,"gateway":{"protocol":1}
,"protocol":{"(mp-bgp)":1}
,"(mp-bgp)":{"ipv4":1}
,"illustration":{"ce1":1}
,"ce1":{"ce2":1}
,"ce2":{"customer":1}
,"customer":{"edge":1}
,"6pe1":{"6pe2":1}
,"6pe2":{"ipv6":1}
,"router":{"core":1}
,"network":{"6pe":1}
}
;Search.control.loadWordPairs(pairs);
