var pairs =
{
"pal_kernel_ipv6_forwarding_get":{"function":1,"(s_int32_t":1}
,"function":{"gets":1,"succeeds":1,"fails":1}
,"gets":{"state":1}
,"state":{"ipv6":1,"pointer":1,"return":1}
,"ipv6":{"forwarding":1}
,"forwarding":{"kernel":1}
,"kernel":{"api":1}
,"api":{"call":1}
,"call":{"result_t":1}
,"result_t":{"pal_kernel_ipv6_forwarding_get":1}
,"(s_int32_t":{"*state)":1}
,"*state)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"none":1,"state":1}
,"none":{"output":1}
,"output":{"parameters":1}
,"pointer":{"state":1}
,"return":{"value":1}
,"value":{"result_ok":1,"function":1}
,"result_ok":{"function":1}
,"succeeds":{"value":1}
}
;Search.control.loadWordPairs(pairs);
