var pairs =
{
"vr\u002Fvrf":{"configuration":1}
,"configuration":{"different":1}
,"different":{"modes":1}
,"modes":{"logically":1}
,"logically":{"subdivides":1}
,"subdivides":{"physical":1,"routing":1}
,"physical":{"router":1}
,"router":{"multiple":1,"execute":1,"independently":1,"vrf":1,"time":1}
,"multiple":{"virtual":1,"vrfs":1,"routing":1}
,"virtual":{"routers":1,"router":1}
,"routers":{"allowing":1}
,"allowing":{"virtual":1}
,"execute":{"separate":1}
,"separate":{"instances":1}
,"instances":{"routing":1}
,"routing":{"protocol":1,"tables":1}
,"protocol":{"virtual":1}
,"independently":{"monitored":1}
,"monitored":{"managed":1}
,"managed":{"user":1}
,"user":{"inside":1}
,"inside":{"virtual":1}
,"vrf":{"logically":1}
,"tables":{"multiple":1,"(ribs)":1}
,"vrfs":{"multiple":1,"supporting":1}
,"supporting":{"multiple":1}
,"(ribs)":{"co-existing":1}
,"co-existing":{"within":1}
,"within":{"router":1}
}
;Search.control.loadWordPairs(pairs);
