var pairs =
{
"provider":{"bridges":1,"edge":1,"network":1}
,"bridges":{"(peb":1}
,"(peb":{"pcb)":1}
,"pcb)":{"peb1":1}
,"peb1":{"-edge":1,"(config-ether-cfm)":1}
,"-edge":{"-sys1":1}
,"-sys1":{"conf":1}
,"conf":{"enter":1}
,"enter":{"configure":1,"vlan":1,"isis-spb":1,"cvlan":1,"mst":1,"spb":1,"interface":1}
,"configure":{"mode":1,"bridge":1,"vlan":1,"interface":1,"port":1}
,"mode":{"(config)":1,"(config-vlan)":1,"(isis-spb-config)":1,"(config-cvlan-registration)":1,"(config-mst)":1,"(spb-config)":1,"manual":1,"(config-if)":1,"provider-network":1,"customer-edge":1}
,"(config)":{"bridge":1,"vlan":1,"isis-spb":1,"cvlan":1,"spanning-tree":1,"spb":1,"interface":1,"ethernet":1}
,"bridge":{"protocol":1,"spbv":1,"(config)":1,"state":1,"(config-vlan)":1,"enter":1,"spb":1,"instance":1,"(config-if)":1,"create":1}
,"protocol":{"spbv":1}
,"spbv":{"svlan":1,"provider":1,"associate":1,"instance":1,"vlan":1,"mode":1,"bvlan":1}
,"svlan":{"edge":1,"100":1,"200":1,"300":1,"400":1}
,"edge":{"configure":1,"bridge":1,"hybrid":1}
,"vlan":{"database":1,"type":1,"bridge":1,"100":1,"(config-vlan)":1,"200":1,"300":1,"400":1,"service":1,"associate":1,"spbv":1,"spvid":1,"add":1,"allow":1,"registration":1}
,"database":{"enter":1,"mode":1}
,"(config-vlan)":{"vlan":1,"exit":1}
,"type":{"customer":1,"service":1,"provider":1,"character-string":1}
,"customer":{"bridge":1,"vlan":1,"edge":1}
,"state":{"enable":1}
,"enable":{"configure":1,"enable":1,"spb":1,"multicast":1}
,"100":{"type":1,"service":1,"map":1,"(config-cvlan-registration)":1,"associate":1,"spbv":1,"spvid":1,"ect":1,"allow":1,"transmit":1,"mip-creation":1,"crosscheck":1,"local-vid":1,"bridge":1}
,"service":{"multipoint-multipoint":1,"vlan":1,"ma-type":1}
,"multipoint-multipoint":{"bridge":1}
,"200":{"type":1,"service":1,"map":1,"(config-cvlan-registration)":1,"associate":1,"spbv":1,"spvid":1,"ect":1,"allow":1,"transmit":1}
,"300":{"type":1,"service":1,"map":1,"(config-cvlan-registration)":1,"associate":1,"spbv":1,"spvid":1,"ect":1,"allow":1,"transmit":1}
,"400":{"type":1,"service":1,"map":1,"(config-cvlan-registration)":1,"associate":1,"spbv":1,"spvid":1,"ect":1,"allow":1,"transmit":1}
,"exit":{"vlan":1,"exit":1,"isis-spb":1,"mst":1,"spb":1,"interface":1,"etherent":1,"cfm":1}
,"isis-spb":{"configuration":1,"mode":1,"multi-topology-id":1,"system-id":1,"system":1}
,"configuration":{"bridge":1,"enter":1}
,"(isis-spb-config)":{"isis-spb":1,"exit":1}
,"multi-topology-id":{"3996":1}
,"3996":{"mtid":1,"associate":1,"(spb-config)":1}
,"mtid":{"(isis-spb-config)":1,"3996":1}
,"system-id":{"11.11.11.11.11.11":1}
,"11.11.11.11.11.11":{"isis-spb":1}
,"system":{"identifier":1}
,"identifier":{"(isis-spb-config)":1}
,"cvlan":{"registration":1,"svlan":1}
,"registration":{"table":1,"mode":1,"map1":1}
,"table":{"map1":1}
,"map1":{"bridge":1,"associate":1,"interface":1}
,"(config-cvlan-registration)":{"cvlan":1,"exit":1}
,"map":{"customer":1}
,"spb":{"enable":1,"bridge":1,"configuration":1,"mode":1,"interface":1}
,"spanning-tree":{"mst":1}
,"mst":{"configuration":1,"mode":1}
,"(config-mst)":{"bridge":1,"exit":1}
,"instance":{"spbv":1,"(config-mst)":1}
,"associate":{"bridge":1,"vlan":1,"base":1,"map1":1}
,"(spb-config)":{"bridge":1,"exit":1}
,"manual":{"spbv":1,"spvid":1,"(spb-config)":1}
,"spvid":{"allocation":1,"3619":1,"3611":1,"3612":1,"3613":1,"3614":1}
,"allocation":{"mode":1}
,"bvlan":{"spvid":1,"100":1,"200":1,"300":1,"400":1}
,"3619":{"associate":1,"(spb-config)":1}
,"base":{"vlan":1}
,"3611":{"associate":1,"(spb-config)":1}
,"3612":{"associate":1,"(spb-config)":1}
,"3613":{"associate":1,"(spb-config)":1}
,"3614":{"associate":1,"(spb-config)":1}
,"ect":{"associate":1,"algorithm":1,"mtid":1}
,"algorithm":{"(spb-config)":1,"mtid":1}
,"interface":{"eth2":1,"mode":1,"layer":1,"part":1,"(config-if)":1,"eth1":1,"eth3":1}
,"eth2":{"enter":1}
,"(config-if)":{"switchport":1,"bridge-group":1,"spb":1,"shutdown":1,"exit":1,"ethernet":1}
,"switchport":{"configure":1,"mode":1,"provider-network":1,"customer-edge":1}
,"layer":{"(config-if)":1}
,"bridge-group":{"configure":1}
,"part":{"bridge":1}
,"provider-network":{"configure":1,"allowed":1}
,"port":{"type":1,"accept":1}
,"network":{"(config-if)":1}
,"allowed":{"vlan":1}
,"add":{"100":1,"200":1,"300":1,"400":1}
,"allow":{"vlan":1,"vlans":1}
,"transmit":{"interface":1}
,"shutdown":{"bring":1}
,"bring":{"interface":1}
,"eth1":{"enter":1}
,"eth3":{"enter":1}
,"customer-edge":{"hybrid":1,"vlan":1}
,"hybrid":{"configure":1,"(config-if)":1,"acceptable-frame-type":1,"allowed":1}
,"acceptable-frame-type":{"configure":1}
,"accept":{"frame":1}
,"frame":{"types":1}
,"types":{"(config-if)":1}
,"vlans":{"created":1}
,"created":{"interface":1}
,"ethernet":{"cfm":1}
,"cfm":{"domain-name":1,"mode":1,"mep":1}
,"domain-name":{"type":1}
,"character-string":{"name":1}
,"name":{"md1":1}
,"md1":{"level":1,"(config-ether-cfm)":1,"vlan":1}
,"level":{"mip-creation":1,"peb1":1}
,"mip-creation":{"default":1}
,"default":{"bridge":1,"create":1}
,"create":{"domain":1,"maintenance":1,"down":1}
,"domain":{"level":1,"md1":1}
,"(config-ether-cfm)":{"service":1,"mep":1,"exit":1}
,"ma-type":{"string":1}
,"string":{"ma-name":1}
,"ma-name":{"ma1":1}
,"ma1":{"vlan":1,"inside":1}
,"maintenance":{"association":1}
,"association":{"ma1":1}
,"inside":{"md1":1}
,"mep":{"crosscheck":1,"peb2":1,"down":1,"(config-if-eth-cfm-mep)":1,"mode":1}
,"crosscheck":{"mpid":1,"mep":1}
,"mpid":{"vlan":1,"(config-ether-cfm)":1,"active":1}
,"peb2":{"mpid":1}
,"etherent":{"cfm":1}
,"down":{"mpid":1,"mep":1}
,"active":{"true":1}
,"true":{"domain":1}
,"local-vid":{"100":1}
,"(config-if-eth-cfm-mep)":{"multicast":1,"exit":1}
,"multicast":{"state":1,"(config-if-eth-cfm-mep)":1}
}
;Search.control.loadWordPairs(pairs);
