var pairs =
{
"transmission":{"eth-lm":1,"framework":1,"pair":1,"period":1}
,"eth-lm":{"ccm":1}
,"ccm":{"transmission":1,"accomplished":1,"sent":1,"pdu":1}
,"accomplished":{"within":1}
,"within":{"mep":1}
,"mep":{"ccm":1,"carries":1,"receiving":1,"detects":1}
,"framework":{"users":1}
,"users":{"enable":1}
,"enable":{"ccm":1}
,"pair":{"meps":1}
,"meps":{"once":1}
,"once":{"enabled":1}
,"enabled":{"ccm":1}
,"sent":{"mep":1}
,"carries":{"frame":1}
,"frame":{"counters":1}
,"counters":{"needed":1}
,"needed":{"dual-ended":1}
,"dual-ended":{"eth-lm":1}
,"pdu":{"transmits":1}
,"transmits":{"period":1}
,"period":{"value":1,"configured":1,"defect":1}
,"value":{"equal":1}
,"equal":{"ccm":1}
,"configured":{"performance":1,"value":1}
,"performance":{"monitoring":1}
,"monitoring":{"application":1}
,"application":{"transmitting":1}
,"transmitting":{"mep":1}
,"receiving":{"mep":1}
,"detects":{"unexpected":1}
,"unexpected":{"period":1}
,"defect":{"condition":1}
,"condition":{"ccm":1}
}
;Search.control.loadWordPairs(pairs);
