var pairs =
{
"bgp":{"confederation":1,"bestpath":1}
,"confederation":{"nodes":1,"solves":1,"as-members":1,"boundary":1,"prepended":1,"unaware":1,"ass":1,"identifier":1,"peers":1}
,"nodes":{"running":1}
,"running":{"ibgp":1,"node":1}
,"ibgp":{"protocols":1,"full":1,"running":1,"sessions":1,"mesh":1}
,"protocols":{"interconnected":1}
,"interconnected":{"forming":1}
,"forming":{"full":1}
,"full":{"mesh":1,"ibgp":1}
,"mesh":{"among":1,"network":1,"route-reflector":1}
,"among":{"confederation":1,"themselves":1,"ibgp":1}
,"solves":{"ibgp":1}
,"network":{"complexity":1}
,"complexity":{"inefficiency":1}
,"inefficiency":{"splitting":1}
,"splitting":{"large":1}
,"large":{"autonomous":1}
,"autonomous":{"system":1}
,"system":{"(as)":1}
,"(as)":{"domain":1}
,"domain":{"smaller":1,"as_confed_*segments":1}
,"smaller":{"domains":1}
,"domains":{"called":1}
,"called":{"member-ass":1,"intra-confederation":1}
,"member-ass":{"member-ass":1,"form":1}
,"form":{"ebgp":1}
,"ebgp":{"connections":1,"sessions":1,"speakers":1}
,"connections":{"among":1}
,"themselves":{"thus":1}
,"thus":{"preventing":1,"ebgp":1}
,"preventing":{"full-mesh":1}
,"full-mesh":{"connections":1}
,"node":{"ebgp":1}
,"sessions":{"within":1,"sessions":1,"behave":1,"terms":1}
,"within":{"single":1,"member-as":1}
,"single":{"confederation":1}
,"as-members":{"called":1}
,"intra-confederation":{"ebgp":1}
,"behave":{"ibgp":1}
,"terms":{"preserving":1}
,"preserving":{"next_hop":1}
,"next_hop":{"med":1}
,"med":{"modify":1}
,"modify":{"as_path":1}
,"as_path":{"as_confed_sequence":1,"confederation":1}
,"as_confed_sequence":{"as_confed_set":1}
,"as_confed_set":{"updates":1}
,"updates":{"sent":1}
,"sent":{"confederation":1}
,"boundary":{"router":1}
,"router":{"external":1}
,"external":{"domain":1}
,"as_confed_*segments":{"removed":1}
,"removed":{"as_path":1}
,"prepended":{"number":1}
,"number":{"thus":1}
,"speakers":{"outside":1}
,"outside":{"confederation":1}
,"unaware":{"confederation":1}
,"ass":{"within":1}
,"member-as":{"full":1}
,"route-reflector":{"configuration":1}
,"configuration":{"required":1}
,"required":{"commands":1}
,"commands":{"bgp":1}
,"identifier":{"bgp":1}
,"peers":{"bgp":1}
,"bestpath":{"compare-confed-aspath":1}
,"compare-confed-aspath":{"used":1}
,"used":{"support":1}
,"support":{"bgp":1}
}
;Search.control.loadWordPairs(pairs);
