var pairs =
{
"messages":{"mribd":1,"sections":1,"mrib4_msg_igmp":1}
,"mribd":{"messages":1,"notify":1}
,"sections":{"follow":1}
,"follow":{"show":1}
,"show":{"data":1}
,"data":{"structures":1}
,"structures":{"pim":1}
,"pim":{"-mribd":1,"igmp":1,"mld":1}
,"-mribd":{"ipc":1}
,"ipc":{"messages":1}
,"mrib4_msg_igmp":{"message":1,"{\u002F*ifindex":1}
,"message":{"sent":1,"struct":1}
,"sent":{"mribd":1}
,"notify":{"pim":1}
,"igmp":{"join\u002Fleave":1}
,"join\u002Fleave":{"message":1,"related":1}
,"struct":{"mrib4_msg_igmp":1,"mrib6_msg_mld":1}
,"{\u002F*ifindex":{"*\u002Fu_int32_t":1}
,"*\u002Fu_int32_t":{"ifindex":1}
,"ifindex":{"\u002F*filter":1}
,"\u002F*filter":{"mode":1}
,"mode":{"(include":1}
,"(include":{"exclude)":1}
,"exclude)":{"*\u002Fu_int16_t":1}
,"*\u002Fu_int16_t":{"filt_mode":1,"num_srcs":1}
,"filt_mode":{"define":1}
,"define":{"mrib4_msg_igmp_filt_mode_incl":1,"mrib4_msg_igmp_filt_mode_excl":1,"mrib6_msg_mld_filt_mode_incl":1,"mrib6_msg_mld_filt_mode_excl":1}
,"mrib4_msg_igmp_filt_mode_incl":{"define":1}
,"mrib4_msg_igmp_filt_mode_excl":{"\u002F*number":1}
,"\u002F*number":{"sources":1}
,"sources":{"*\u002Fu_int16_t":1}
,"num_srcs":{"\u002F*group":1}
,"\u002F*group":{"address":1}
,"address":{"*\u002Fstruct":1}
,"*\u002Fstruct":{"pal_in4_addr":1,"pal_in6_addr":1}
,"pal_in4_addr":{"grp_addr":1,"src_addr_list":1}
,"grp_addr":{"\u002F*prefix":1,"\u002F*source":1}
,"\u002F*prefix":{"length":1}
,"length":{"default":1}
,"default":{"*\u002Fu_int8_t":1}
,"*\u002Fu_int8_t":{"prefixlen":1}
,"prefixlen":{"\u002F*source":1}
,"\u002F*source":{"addresses":1}
,"addresses":{"list":1}
,"list":{"*\u002Fstruct":1}
,"src_addr_list":{"[1]":1}
,"[1]":{"mrib6_msg_mld":1}
,"mrib6_msg_mld":{"message":1,"{\u002F*ifindex":1}
,"mld":{"join\u002Fleave":1}
,"related":{"information":1}
,"information":{"struct":1}
,"mrib6_msg_mld_filt_mode_incl":{"define":1}
,"mrib6_msg_mld_filt_mode_excl":{"\u002F*number":1}
,"pal_in6_addr":{"grp_addr":1,"src_addr_list":1}
}
;Search.control.loadWordPairs(pairs);
