var pairs =
{
"reverse":{"path":1}
,"path":{"forwarding":1,"back":1}
,"forwarding":{"(rpf)":1}
,"(rpf)":{"algorithm":1}
,"algorithm":{"checks":1}
,"checks":{"unicast":1}
,"unicast":{"routing":1,"rpf":1}
,"routing":{"information":1}
,"information":{"base":1}
,"base":{"(rib)":1}
,"(rib)":{"determine":1}
,"determine":{"whether":1,"source":1}
,"whether":{"shortest":1}
,"shortest":{"path":1}
,"back":{"source":1}
,"source":{"address":1,"denial-of-service":1,"addresses":1}
,"address":{"incoming":1}
,"incoming":{"multicast":1}
,"multicast":{"packet":1}
,"packet":{"unicast":1}
,"rpf":{"helps":1}
,"helps":{"determine":1}
,"denial-of-service":{"attacks":1}
,"attacks":{"rejects":1}
,"rejects":{"packets":1}
,"packets":{"unexpected":1}
,"unexpected":{"source":1}
}
;Search.control.loadWordPairs(pairs);
