var pairs =
{
"rmon_set_alarm_start_up":{"function":1,"(struct":1}
,"function":{"sets":1,"succeeds":1,"fails":1}
,"sets":{"alarm":1}
,"alarm":{"start-up":1,"entry":1,"type":1,"falling":1,"rising":1,"-3)":1}
,"start-up":{"type":1,"alarm":1}
,"type":{"alarm":1,"(rising":1}
,"entry":{"syntax":1,"index":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"rmon_set_alarm_start_up":1}
,"(struct":{"rmon_master":1}
,"rmon_master":{"*rm":1}
,"*rm":{"struct":1}
,"struct":{"rmon_alarmgroup":1}
,"rmon_alarmgroup":{"*rmon_alarm":1}
,"*rmon_alarm":{"u_int32_t":1}
,"u_int32_t":{"index":1,"startup)":1}
,"index":{"u_int32_t":1,"alarm":1,"startup":1}
,"startup)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"pointer":1,"none":1}
,"pointer":{"rmon":1,"alarm":1}
,"rmon":{"master":1}
,"master":{"rmon_alarm":1}
,"rmon_alarm":{"pointer":1}
,"startup":{"start-up":1}
,"(rising":{"alarm":1}
,"falling":{"alarm":1}
,"rising":{"falling":1}
,"-3)":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"rmon_api_set_success":1}
,"rmon_api_set_success":{"function":1}
,"succeeds":{"rmon_api_set_failure":1}
,"rmon_api_set_failure":{"function":1}
}
;Search.control.loadWordPairs(pairs);
