var pairs =
{
"radius-server":{"deadtime":1}
,"deadtime":{"command":1,"default":1,"min":1,"parameter":1,"(config)":1}
,"command":{"specify":1,"cause":1,"deadtime":1,"syntax":1,"mode":1}
,"specify":{"number":1}
,"number":{"minutes":1}
,"minutes":{"radius":1,"(24":1}
,"radius":{"server":1,"authentication":1,"response":1}
,"server":{"responding":1,"skipped":1}
,"responding":{"authentication":1}
,"authentication":{"requests":1,"improve":1}
,"requests":{"passed":1,"radius":1,"maximum":1}
,"passed":{"requests":1}
,"improve":{"radius":1}
,"response":{"times":1}
,"times":{"servers":1}
,"servers":{"unavailable":1,"skipped":1}
,"unavailable":{"command":1,"servers":1}
,"cause":{"unavailable":1}
,"skipped":{"immediately":1,"transaction":1}
,"immediately":{"form":1}
,"form":{"command":1}
,"default":{"value":1,"deadtime":1}
,"value":{"command":1,"range":1}
,"syntax":{"radius-server":1}
,"min":{"radius-server":1,"length":1}
,"parameter":{"min":1}
,"length":{"time":1}
,"time":{"(in":1}
,"(in":{"minutes)":1}
,"minutes)":{"radius":1}
,"transaction":{"requests":1}
,"maximum":{"1440":1}
,"1440":{"minutes":1,"default":1}
,"(24":{"hours)":1}
,"hours)":{"enter":1}
,"enter":{"value":1}
,"range":{"1440":1}
,"mode":{"configure":1,"examples":1}
,"configure":{"mode":1,"terminal":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"radius-server":1}
}
;Search.control.loadWordPairs(pairs);
