var pairs =
{
"rsvp_api_loop_detection_set":{"call":1,"(struct":1}
,"call":{"sets":1}
,"sets":{"loop":1}
,"loop":{"detection":1}
,"detection":{"syntax":1,"flag":1}
,"syntax":{"void":1}
,"void":{"rsvp_api_loop_detection_set":1}
,"(struct":{"rsvp":1}
,"rsvp":{"*rsvp":1,"rsvp":1,"instance":1}
,"*rsvp":{"u_char":1}
,"u_char":{"val)":1}
,"val)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"rsvp":1,"none":1}
,"instance":{"val":1}
,"val":{"value":1}
,"value":{"loop":1,"none":1}
,"flag":{"rsvp_loop_detect_enabled":1}
,"rsvp_loop_detect_enabled":{"rsvp_loop_detect_disabled":1}
,"rsvp_loop_detect_disabled":{"rsvp_loop_detect_enabled_all":1}
,"rsvp_loop_detect_enabled_all":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
}
;Search.control.loadWordPairs(pairs);
