var pairs =
{
"zebos_smi_client_lib_create":{"function":1}
,"function":{"allocates":1,"calls":1,"call":1,"succeeds":1,"falis":1}
,"allocates":{"initializes":1}
,"initializes":{"memory":1}
,"memory":{"smi":1}
,"smi":{"client":1,"sequence":1}
,"client":{"application":1,"structure":1}
,"application":{"returns":1,"syntax":1,"single":1,"multi-threaded":1}
,"returns":{"pointer":1}
,"pointer":{"global":1,"smiclient_globals":1}
,"global":{"smi":1}
,"structure":{"passed":1}
,"passed":{"parameter":1}
,"parameter":{"later":1}
,"later":{"function":1}
,"calls":{"first":1}
,"first":{"function":1}
,"call":{"smi":1}
,"syntax":{"struct":1}
,"struct":{"smiclient_globals":1}
,"smiclient_globals":{"*zebos_smi_client_lib_create":1,"function":1}
,"*zebos_smi_client_lib_create":{"(bool_t":1}
,"(bool_t":{"set_mutex":1}
,"set_mutex":{"char":1,"whether":1}
,"char":{"*lsr_name)":1}
,"*lsr_name)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"set_mutex":1}
,"whether":{"client":1}
,"single":{"threaded":1}
,"threaded":{"multi-threaded":1,"lsr_name":1}
,"multi-threaded":{"pal_true":1,"smi":1}
,"pal_true":{"client":1}
,"sequence":{"requests":1}
,"requests":{"pal_false":1}
,"pal_false":{"client":1}
,"lsr_name":{"logical":1}
,"logical":{"switch":1}
,"switch":{"router":1}
,"router":{"name":1}
,"name":{"return":1}
,"return":{"values":1}
,"values":{"pointer":1}
,"succeeds":{"null":1}
,"null":{"function":1}
}
;Search.control.loadWordPairs(pairs);
