var pairs =
{
"service":{"pbb-te":1,"instance":1}
,"pbb-te":{"command":1,"ma-type":1,"csi_id":1,"mode":1,"domain":1,"ma1":1}
,"command":{"create":1,"delete":1,"syntax":1,"mode":1}
,"create":{"maintenance":1}
,"maintenance":{"association":1}
,"association":{"(ma)":1,"name":1}
,"(ma)":{"pbb":1}
,"pbb":{"service":1}
,"instance":{"form":1,"command":1,"tesid":1,"<1-42949675>":1}
,"form":{"command":1}
,"delete":{"pbb":1}
,"syntax":{"service":1}
,"ma-type":{"(primary-vid":1,"type":1}
,"(primary-vid":{"string":1}
,"string":{"integer":1,"character":1}
,"integer":{"vpn-id)":1,"integer":1,"vpn-id":1}
,"vpn-id)":{"ma-name":1}
,"ma-name":{"ma_name":1,"maintenance":1}
,"ma_name":{"te-sid":1,"maintenance":1}
,"te-sid":{"tesid":1,"te_sid":1,"identifies":1,"mip-creation":1}
,"tesid":{"mip-creation":1,"traffic":1}
,"mip-creation":{"(none":1,"specify":1,"default":1}
,"(none":{"default":1}
,"default":{"explicit":1,"specify":1}
,"explicit":{"defer)":1,"specify":1}
,"defer)":{"service":1,"parameters":1}
,"csi_id":{"te-sid":1,"maintenance":1}
,"te_sid":{"mip-creation":1}
,"parameters":{"ma-type":1}
,"type":{"maintenance":1}
,"name":{"primary-vid":1,"ma_name":1,"te-sid":1,"command":1}
,"primary-vid":{"primary":1}
,"primary":{"vid":1}
,"vid":{"string":1,"default":1,"bridge":1,"ports":1,"pass":1}
,"character":{"string":1}
,"vpn-id":{"vpn":1}
,"vpn":{"ma-name":1}
,"identifies":{"traffic":1}
,"traffic":{"engineering":1}
,"engineering":{"service":1}
,"<1-42949675>":{"mip-creation":1}
,"specify":{"mip":1}
,"mip":{"creation":1,"may":1,"created":1}
,"creation":{"permission":1,"deferred":1}
,"permission":{"value":1}
,"value":{"none":1}
,"none":{"specify":1}
,"may":{"created":1}
,"created":{"vid":1}
,"bridge":{"explicit":1,"backbone":1}
,"ports":{"vid":1}
,"pass":{"defer":1}
,"defer":{"control":1}
,"control":{"mhf":1}
,"mhf":{"creation":1}
,"deferred":{"corresponding":1}
,"corresponding":{"variable":1}
,"variable":{"enclosing":1}
,"enclosing":{"csi_id":1}
,"mode":{"ethernet":1,"examples":1}
,"ethernet":{"cfm":1}
,"cfm":{"pbb-te":1}
,"examples":{"(config)":1}
,"(config)":{"ethernet":1}
,"domain":{"ipi":1}
,"ipi":{"level":1}
,"level":{"bridge":1}
,"backbone":{"(config-ether-cfm-pbb-te)":1}
,"(config-ether-cfm-pbb-te)":{"service":1}
,"ma1":{"te-sid":1}
}
;Search.control.loadWordPairs(pairs);
