var pairs =
{
"bgp_timers_set":{"function":1,"(struct":1}
,"function":{"sets":1,"called":1,"successful":1}
,"sets":{"bgp":1}
,"bgp":{"configuration":1,"syntax":1,"*bgp":1,"bgp":1,"instance":1,"keepalive":1,"holdtime":1}
,"configuration":{"timer":1}
,"timer":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"timers":1}
,"timers":{"bgp":1}
,"syntax":{"int":1}
,"int":{"bgp_timers_set":1}
,"(struct":{"bgp":1}
,"*bgp":{"u_int32_t":1}
,"u_int32_t":{"keepalive":1,"holdtime)":1}
,"keepalive":{"u_int32_t":1,"bgp":1,"time":1}
,"holdtime)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bgp":1,"none":1}
,"instance":{"keepalive":1}
,"time":{"seconds":1,"keep":1,"exceeds":1,"infinite":1,"less":1,"(-58)":1,"value":1,"equal":1,"(-79)":1}
,"seconds":{"65535":1}
,"65535":{"holdtime":1,"output":1,"(-2)":1}
,"holdtime":{"bgp":1,"seconds":1,"equal":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"bgp_api_set_success":1,"65535":1,"(-57)":1,"equal":1}
,"bgp_api_set_success":{"function":1}
,"successful":{"(0)":1}
,"(0)":{"bgp_api_set_err_invalid_value":1}
,"bgp_api_set_err_invalid_value":{"hold":1}
,"hold":{"time":1}
,"keep":{"alive":1}
,"alive":{"time":1}
,"exceeds":{"maximum":1}
,"maximum":{"value":1}
,"(-2)":{"bgp_api_set_err_infinite_hold_time_value":1}
,"bgp_api_set_err_infinite_hold_time_value":{"hold":1}
,"infinite":{"value":1}
,"(-57)":{"bgp_api_set_warn_hold_and_keepalive_invalid":1}
,"bgp_api_set_warn_hold_and_keepalive_invalid":{"configured":1}
,"configured":{"holdtime":1}
,"equal":{"hold":1,"less":1,"keep":1}
,"less":{"times":1,"(-59)":1,"equal":1}
,"times":{"keepalive":1}
,"(-58)":{"bgp_api_set_err_invalid_hold_time":1}
,"bgp_api_set_err_invalid_hold_time":{"hold":1}
,"(-59)":{"bgp_api_set_err_hold_less_equal_keepalive":1}
,"bgp_api_set_err_hold_less_equal_keepalive":{"hold":1}
}
;Search.control.loadWordPairs(pairs);
