var pairs =
{
"rip2_get_next_peer_rcv_bad_packets":{"function":1,"(int":1}
,"function":{"returns":1}
,"returns":{"number":1}
,"number":{"rip":1,"discarded":1,"packets":1}
,"rip":{"response":1,"process":1}
,"response":{"packets":1}
,"packets":{"next":1,"return":1,"discarded":1}
,"next":{"peer":1}
,"peer":{"discarded":1,"address":1}
,"discarded":{"invalid":1,"rip":1,"rip_api_get_success":1}
,"invalid":{"syntax":1}
,"syntax":{"int":1}
,"int":{"rip2_get_next_peer_rcv_bad_packets":1,"indexlen":1,"*value)":1}
,"(int":{"pid":1}
,"pid":{"struct":1,"rip":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"*addr":1}
,"*addr":{"int":1}
,"indexlen":{"int":1,"future":1}
,"*value)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"pid":1,"value":1}
,"process":{"addr":1}
,"addr":{"peer":1}
,"address":{"indexlen":1}
,"future":{"output":1}
,"output":{"parameters":1}
,"value":{"number":1}
,"return":{"values":1}
,"values":{"rip_api_get_error":1}
,"rip_api_get_error":{"call":1}
,"call":{"find":1,"finds":1}
,"find":{"number":1}
,"rip_api_get_success":{"call":1}
,"finds":{"number":1}
}
;Search.control.loadWordPairs(pairs);
