var pairs =
{
"ethernet":{"virtual":1}
,"virtual":{"connection":1}
,"connection":{"(evc)":1}
,"(evc)":{"association":1}
,"association":{"two":1}
,"two":{"instances":1,"unis":1}
,"instances":{"user-to-network":1}
,"user-to-network":{"interface":1}
,"interface":{"(uni)":1}
,"(uni)":{"three":1}
,"three":{"types":1}
,"types":{"evc":1}
,"evc":{"point-to-point":1,"exactly":1,"two":1,"unis":1,"leaf":1}
,"point-to-point":{"evc":1}
,"exactly":{"two":1}
,"unis":{"associated":1,"designated":1}
,"associated":{"multipoint":1,"rooted-multipoint":1}
,"multipoint":{"evc":1}
,"rooted-multipoint":{"evc":1}
,"designated":{"root":1,"leaf":1}
,"root":{"unis":1,"uni":1}
,"leaf":{"root":1,"uni":1}
,"uni":{"send":1}
,"send":{"service":1,"receive":1}
,"service":{"frames":1}
,"frames":{"points":1,"root":1}
,"points":{"evc":1}
,"receive":{"service":1}
}
;Search.control.loadWordPairs(pairs);
