var pairs =
{
"configure":{"bfd":1,"terminal":1,"mode":1,"targeted":1,"label-switching":1}
,"bfd":{"ldp":1,"session":1,"enabled":1,"configuration":1}
,"ldp":{"lsp":1,"enter":1,"mode":1,"session":1,"provider":1,"force-explicit-null":1,"fec":1,"lsp-ping-intvl":1,"(config-if)":1}
,"lsp":{"bfd":1,"configuration":1}
,"configuration":{"pe1":1,"configuration":1,"configure":1,"pe2":1}
,"pe1":{"pe-1":1}
,"pe-1":{"configure":1,"(config)":1,"(config-router)":1,"(config-router-targeted-peer)":1,"(config-if)":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"router":1,"interface":1}
,"mode":{"pe-1":1,"return":1,"eth2":1,"(config)":1,"(config-router)":1,"(config-if)":1,"configuration":1,"pe2":1,"eth1":1}
,"(config)":{"router":1,"interface":1,"mpls":1,"exit":1}
,"router":{"ldp":1,"force-explicit-null":1}
,"(config-router)":{"targeted-peer":1,"exit":1}
,"targeted-peer":{"ipv4":1}
,"ipv4":{"3.3.3.3":1,"enable":1,"1.1.1.1":1}
,"3.3.3.3":{"configure":1}
,"targeted":{"ldp":1}
,"session":{"pe2":1,"ldp":1}
,"pe2":{"loopback":1,"pe2":1,"configure":1,"(config)":1,"(config-router)":1,"(config-router-targeted-peer)":1,"(config-if)":1}
,"loopback":{"address":1}
,"address":{"pe-1":1,"pe2":1}
,"(config-router-targeted-peer)":{"exit":1}
,"exit":{"exit":1,"router":1,"interface":1,"configure":1}
,"return":{"configure":1}
,"interface":{"eth2":1,"mode":1,"pe1":1,"eth1":1,"pe2":1}
,"eth2":{"enter":1,"pe-1":1,"(config-if)":1}
,"(config-if)":{"label-switching":1,"enable-ldp":1,"exit":1}
,"label-switching":{"configure":1,"provider":1,"(config-if)":1}
,"provider":{"interface":1}
,"enable-ldp":{"ipv4":1}
,"enable":{"ldp":1}
,"mpls":{"bfd":1}
,"force-explicit-null":{"lsp-ping-intvl":1,"configured":1}
,"lsp-ping-intvl":{"min-rx":1}
,"min-rx":{"300":1}
,"300":{"min-tx":1,"multiplier":1}
,"min-tx":{"300":1}
,"multiplier":{"configure":1}
,"fec":{"entries":1}
,"entries":{"note":1}
,"note":{"bfd":1,"explicit-null":1}
,"enabled":{"particular":1,"egress":1}
,"particular":{"fec.pe-1":1}
,"fec.pe-1":{"pe-1":1}
,"explicit-null":{"enabled":1}
,"egress":{"router":1}
,"configured":{"mpls":1}
,"eth1":{"enter":1,"pe2":1}
,"1.1.1.1":{"configure":1}
}
;Search.control.loadWordPairs(pairs);
