var pairs =
{
"clock-selection":{"mode":1}
,"mode":{"command":1,"(ql-enabled":1,"configure":1,"example":1,"ql-enabled":1}
,"command":{"determine":1,"syntax":1,"mode":1}
,"determine":{"whether":1}
,"whether":{"quality":1}
,"quality":{"level":1}
,"level":{"(ql)":1,"criteria":1}
,"(ql)":{"criteria":1}
,"criteria":{"selecting":1}
,"selecting":{"clock":1}
,"clock":{"command":1,"ql-disabled":1}
,"syntax":{"clock-selection":1}
,"(ql-enabled":{"ql-disabled)":1}
,"ql-disabled)":{"parameters":1}
,"parameters":{"ql-enabled":1}
,"ql-enabled":{"quality":1}
,"ql-disabled":{"quality":1}
,"configure":{"synchronous":1}
,"synchronous":{"ethernet":1}
,"ethernet":{"mode":1}
,"example":{"(config)":1}
,"(config)":{"synce":1}
,"synce":{"(config-synce)":1}
,"(config-synce)":{"clock-selection":1}
}
;Search.control.loadWordPairs(pairs);
