var pairs =
{
"debug":{"pim":1}
,"pim":{"command":1,"events":1,"debug":1,"(vrf":1}
,"command":{"enable":1,"disable":1,"syntax":1,"mode":1}
,"enable":{"debugging":1}
,"debugging":{"pim":1}
,"events":{"option":1}
,"option":{"command":1}
,"disable":{"debugging":1}
,"syntax":{"debug":1}
,"(vrf":{"name":1}
,"name":{"debug":1,"parameters":1,"specify":1,"vpn":1}
,"parameters":{"vrf":1}
,"vrf":{"vpn":1}
,"vpn":{"routing\u002Fforwarding":1}
,"routing\u002Fforwarding":{"instance":1}
,"instance":{"name":1,"command":1}
,"specify":{"name":1}
,"mode":{"exec":1,"privilege":1,"configure":1,"example":1}
,"exec":{"mode":1}
,"privilege":{"exec":1}
,"configure":{"mode":1}
,"example":{"debug":1}
}
;Search.control.loadWordPairs(pairs);
