var pairs =
{
"ripng_offset_list_unset":{"function":1,"(u_int32_t":1}
,"function":{"removes":1,"called":1}
,"removes":{"offset":1}
,"offset":{"list":1,"value":1,"char":1}
,"list":{"offset":1,"name":1,"exist":1}
,"value":{"removed":1,"non-vr":1}
,"removed":{"routing":1}
,"routing":{"metric":1}
,"metric":{"function":1,"char":1,"metric":1,"offset":1,"null":1,"range":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"offset-list":1}
,"offset-list":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ripng_offset_list_unset":1,"instance":1,"metric":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"int":1,"virtual":1}
,"instance":{"char":1,"instance":1,"number":1,"cannot":1}
,"char":{"*alist":1,"*direct_str":1,"*ifname)":1,"*ifname":1}
,"*alist":{"char":1}
,"*direct_str":{"int":1}
,"*ifname)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1,"exist":1}
,"default":{"value":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"parameter":1}
,"parameter":{"instance":1}
,"number":{"alist":1}
,"alist":{"access":1}
,"access":{"list":1}
,"name":{"direct_str":1,"output":1}
,"direct_str":{"packet":1}
,"packet":{"direction":1}
,"direction":{"int":1,"metric":1}
,"*ifname":{"interface":1}
,"interface":{"name":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"rip_api_set_err_invalid_value":1}
,"rip_api_set_err_invalid_value":{"access_list_str":1}
,"access_list_str":{"direction":1}
,"null":{"rip_api_set_err_metric_invalid":1}
,"rip_api_set_err_metric_invalid":{"metric":1}
,"range":{"ripng_metric_infinity":1}
,"ripng_metric_infinity":{"rip_api_set_err_offset_not_exist":1}
,"rip_api_set_err_offset_not_exist":{"offset":1}
,"exist":{"rip_api_set_err_process_not_exist":1,"rip_api_set_success":1}
,"rip_api_set_err_process_not_exist":{"instance":1}
,"cannot":{"found":1}
,"found":{"rip_api_set_err_vr_not_exist":1}
,"rip_api_set_err_vr_not_exist":{"virtual":1}
,"rip_api_set_success":{"successful":1}
}
;Search.control.loadWordPairs(pairs);
