var pairs =
{
"ipsec_crypto_isakmp_disable":{"function":1,"(u_int32_t":1}
,"function":{"disable":1,"successful":1}
,"disable":{"ike":1}
,"ike":{"local":1}
,"local":{"system":1}
,"system":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ipsec_crypto_isakmp_disable":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"struct":1,"virtual":1}
,"struct":{"ipsec_crypto_isakmp":1}
,"ipsec_crypto_isakmp":{"*isakmp)":1}
,"*isakmp)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"isakmp":1,"none":1}
,"isakmp":{"isakmp":1,"value":1}
,"value":{"vr_id":1}
,"virtual":{"router":1}
,"router":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"ipsec_api_success":1}
,"ipsec_api_success":{"function":1}
,"successful":{"ipsec_api_error":1}
,"ipsec_api_error":{"error":1}
}
;Search.control.loadWordPairs(pairs);
