var pairs =
{
"show":{"debug":1}
,"debug":{"trill":1}
,"trill":{"command":1,"parameters":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"debugging":1}
,"debugging":{"settings":1}
,"settings":{"command":1}
,"syntax":{"show":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"privileged":1,"interface":1,"configure":1,"example":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"interface":{"mode":1}
,"configure":{"mode":1}
,"example":{"(config-if)":1}
,"(config-if)":{"show":1}
}
;Search.control.loadWordPairs(pairs);
