var pairs =
{
"down":{"mep":1,"mpid":1}
,"mep":{"sw1":1,"crosscheck":1,"vlan":1,"down":1,"mode":1,"assign":1}
,"sw1":{"sw1":1,"configure":1,"(config)":1,"(config-vlan)":1,"(config-cfm-vlan)":1,"(config-ether-cfm)":1,"(config-if)":1,"(config-if-eth-cfm-mep)":1}
,"configure":{"terminal":1,"mode":1,"vlan":1,"interface":1,"eth2":1,"time":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"vlan":1,"cfm":1}
,"mode":{"sw1":1,"create":1,"trunk":1}
,"(config)":{"bridge":1,"vlan":1,"ethernet":1,"interface":1}
,"bridge":{"protocol":1,"rstp":1,"sw1":1,"create":1,"configure":1,"add":1,"enter":1,"group":1}
,"protocol":{"rstp":1}
,"rstp":{"vlan-bridge":1,"vlan-aware":1}
,"vlan-bridge":{"create":1}
,"create":{"bridge":1,"vlan":1,"domain":1,"type":1,"down":1}
,"vlan-aware":{"bridge":1}
,"vlan":{"database":1,"configure":1,"bridge":1,"primary":1,"sw1":1,"(vid)":1,"mode":1,"mip-creation":1,"enable":1,"allow":1,"local-vid":1,"local":1,"interval":1}
,"database":{"enter":1}
,"(config-vlan)":{"vlan":1,"exit":1}
,"exit":{"exit":1,"vlan":1,"cfm":1,"ethernet":1,"interface":1}
,"ethernet":{"cfm":1}
,"cfm":{"configure":1,"vlan":1,"domain-name":1,"mode":1,"mep":1}
,"primary":{"vlan":1}
,"(config-cfm-vlan)":{"add":1,"exit":1}
,"add":{"vid":1,"secondary":1}
,"vid":{"bridge":1}
,"secondary":{"vlan":1}
,"(vid)":{"sw1":1}
,"domain-name":{"type":1}
,"type":{"character-string":1,"integer":1}
,"character-string":{"name":1}
,"name":{"domain1":1}
,"domain1":{"level":1,"vlan":1}
,"level":{"mip-creation":1,"setting":1,"mipcreation":1}
,"mip-creation":{"default":1}
,"default":{"bridge":1,"sw1":1,"create":1}
,"domain":{"domain1":1}
,"setting":{"mip":1}
,"mip":{"creation":1}
,"creation":{"permissions":1}
,"permissions":{"default":1}
,"(config-ether-cfm)":{"service":1,"mep":1,"exit":1,"vlan":1}
,"service":{"ma-type":1}
,"ma-type":{"integer":1}
,"integer":{"ma-name":1,"mip":1}
,"ma-name":{"200":1}
,"200":{"vlan":1}
,"crosscheck":{"mpid":1,"remote":1}
,"mpid":{"151":1,"152":1,"associate":1}
,"151":{"vlan":1}
,"enable":{"crosscheck":1,"enable":1,"multicast":1}
,"remote":{"mep":1}
,"interface":{"eth2":1,"trunk":1,"sw1":1,"mode":1}
,"eth2":{"configure":1,"sw1":1,"switch":1,"bridge":1}
,"(config-if)":{"switchport":1,"bridge-group":1,"ethernet":1,"exit":1}
,"switchport":{"configure":1,"mode":1,"trunk":1}
,"switch":{"port":1}
,"port":{"sw1":1}
,"bridge-group":{"configure":1}
,"group":{"sw1":1}
,"trunk":{"interface":1,"sw1":1,"allowed":1}
,"allowed":{"vlan":1}
,"allow":{"vlans":1}
,"vlans":{"interface":1}
,"152":{"active":1}
,"active":{"true":1}
,"true":{"domain":1}
,"local-vid":{"bridge":1}
,"assign":{"mpid":1}
,"associate":{"domain1":1}
,"local":{"vid":1}
,"(config-if-eth-cfm-mep)":{"multicast":1,"exit":1}
,"multicast":{"state":1,"continuity":1}
,"state":{"enable":1}
,"continuity":{"checking":1}
,"checking":{"(cc)":1}
,"(cc)":{"interface":1}
,"mipcreation":{"default":1}
,"interval":{"configure":1}
,"time":{"interval":1}
}
;Search.control.loadWordPairs(pairs);
