var pairs =
{
"ldp_snmp_api_set_entity_row_status":{"call":1,"(struct":1}
,"call":{"sets":1}
,"sets":{"row":1}
,"row":{"status":1}
,"status":{"ldp":1,"permitted":1}
,"ldp":{"entity":1,"org":1,"idx":1,"index":1}
,"entity":{"syntax":1,"row_status":1,"ldp":1,"return":1}
,"syntax":{"int":1}
,"int":{"ldp_snmp_api_set_entity_row_status":1}
,"(struct":{"ldp_entity":1}
,"ldp_entity":{"**org_entity":1}
,"**org_entity":{"s_int32_t":1}
,"s_int32_t":{"row_status":1}
,"row_status":{"struct":1,"value":1}
,"struct":{"ldp_id":1}
,"ldp_id":{"*ldpid":1}
,"*ldpid":{"u_int32_t":1,"ldp":1}
,"u_int32_t":{"*idx)":1}
,"*idx)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"org_entity":1,"entity":1}
,"org_entity":{"ldp":1}
,"org":{"entity":1}
,"value":{"row":1}
,"permitted":{"values":1}
,"values":{"include":1,"ldp_success":1}
,"include":{"following":1}
,"following":{"snmp_ag_row_createandgo":1}
,"snmp_ag_row_createandgo":{"snmp_ag_row_createandwait":1}
,"snmp_ag_row_createandwait":{"snmp_ag_row_active":1}
,"snmp_ag_row_active":{"snmp_ag_row_notready":1}
,"snmp_ag_row_notready":{"snmp_ag_row_notinservice":1}
,"snmp_ag_row_notinservice":{"snmp_ag_row_destroy":1}
,"snmp_ag_row_destroy":{"*ldpid":1}
,"idx":{"ldp":1}
,"index":{"output":1}
,"output":{"parameters":1}
,"return":{"values":1}
,"ldp_success":{"ldp_error":1}
}
;Search.control.loadWordPairs(pairs);
