var pairs =
{
"ethernet":{"oam":1}
,"oam":{"remote-failure":1}
,"remote-failure":{"command":1,"{critical-event":1,"critical-event":1}
,"command":{"define":1,"reset":1,"syntax":1,"mode":1}
,"define":{"action":1}
,"action":{"remote":1,"command":1,"error-disable-interface":1,"specify":1}
,"remote":{"failure":1,"event":1}
,"failure":{"detected":1,"error-disable-interface":1,"event":1,"trigger":1}
,"detected":{"form":1,"default":1}
,"form":{"command":1}
,"reset":{"action":1}
,"syntax":{"ethernet":1}
,"{critical-event":{"dying-gasp":1}
,"dying-gasp":{"link-fault}":1,"specify":1,"event":1}
,"link-fault}":{"action":1}
,"error-disable-interface":{"ethernet":1,"parameters":1,"specify":1}
,"parameters":{"critical-event":1}
,"critical-event":{"specify":1,"action":1}
,"specify":{"remote":1,"action":1,"disable":1}
,"event":{"critical":1,"dying-gasp":1,"link-fault":1,"action":1,"detected":1}
,"critical":{"link":1}
,"link":{"event":1}
,"link-fault":{"specify":1,"event":1}
,"disable":{"interface":1}
,"interface":{"remote":1,"events":1,"mode":1,"eth1":1}
,"default":{"remote":1,"command":1}
,"trigger":{"interface":1}
,"events":{"default":1}
,"mode":{"interface":1,"examples":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth1":{"(config-if)":1}
,"(config-if)":{"ethernet":1}
}
;Search.control.loadWordPairs(pairs);
