var pairs =
{
"rmon_coll_history_validate":{"function":1,"(u_int32_t":1}
,"function":{"checks":1,"succeeds":1}
,"checks":{"history":1}
,"history":{"control":1}
,"control":{"parameters":1,"entry":1}
,"parameters":{"already":1,"index":1,"none":1}
,"already":{"interface":1,"present":1}
,"interface":{"syntax":1,"index":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"rmon_coll_history_validate":1}
,"(u_int32_t":{"index":1}
,"index":{"u_int32_t":1,"history":1,"ifindex":1,"output":1}
,"u_int32_t":{"ifindex)":1}
,"ifindex)":{"input":1}
,"input":{"parameters":1}
,"entry":{"index":1,"already":1}
,"ifindex":{"interface":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"zero":1}
,"zero":{"(0)":1}
,"(0)":{"function":1}
,"succeeds":{"result_error":1}
,"result_error":{"entry":1}
}
;Search.control.loadWordPairs(pairs);
