var pairs =
{
"trill_get_rbridge_esadi_confidence":{"function":1,"(u_int32_t":1}
,"function":{"gets":1}
,"gets":{"rbridge":1}
,"rbridge":{"esadi":1}
,"esadi":{"confidence":1}
,"confidence":{"syntax":1}
,"syntax":{"int":1}
,"int":{"trill_get_rbridge_esadi_confidence":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"integer":1}
,"u_int32_t":{"instance":1,"vlanindex":1,"*ret)":1}
,"instance":{"u_int32_t":1,"integer":1,"vlanindex":1,"found":1}
,"vlanindex":{"u_int32_t":1,"integer":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"*ret":1}
,"integer":{"contains":1,"containing":1}
,"contains":{"trill":1}
,"trill":{"identifier":1,"instance":1}
,"identifier":{"instance":1}
,"containing":{"vlan":1,"return":1}
,"vlan":{"index":1}
,"index":{"output":1}
,"output":{"parameters":1}
,"*ret":{"integer":1}
,"return":{"value":1}
,"value":{"return":1,"trill_api_get_success":1}
,"trill_api_get_success":{"valid":1}
,"valid":{"instance":1}
,"found":{"trill_api_get_error":1}
,"trill_api_get_error":{"invalid":1}
,"invalid":{"instance":1}
}
;Search.control.loadWordPairs(pairs);
