var pairs =
{
"show":{"mpls-tp":1}
,"mpls-tp":{"rps":1}
,"rps":{"protection-group":1,"protection":1}
,"protection-group":{"summary":1}
,"summary":{"command":1,"information":1,"parameters":1,"total":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"summary":1}
,"information":{"configured":1}
,"configured":{"mpls-tp":1,"------------------------------------------------------------------------------group-name":1}
,"protection":{"groups":1}
,"groups":{"command":1,"configured":1}
,"syntax":{"show":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"exec":1,"examples":1}
,"exec":{"mode":1}
,"examples":{"show":1}
,"total":{"number":1}
,"number":{"groups":1}
,"------------------------------------------------------------------------------group-name":{"primary-meg":1}
,"primary-meg":{"pri-me":1}
,"pri-me":{"name\u002Fid":1}
,"name\u002Fid":{"backup-meg":1,"oper-status":1}
,"backup-meg":{"bkp-me":1}
,"bkp-me":{"name\u002Fid":1}
,"oper-status":{"------------------------------------------------------------------------------abc":1}
,"------------------------------------------------------------------------------abc":{"meg1":1}
,"meg1":{"meg2":1}
,"meg2":{"def":1}
,"def":{"meg3":1}
,"meg3":{"meg3":1}
}
;Search.control.loadWordPairs(pairs);
