var pairs =
{
"mstp_api_set_port_bpdufilter":{"function":1,"(char":1}
,"function":{"sets":1}
,"sets":{"port":1}
,"port":{"bpduguard":1,"syntax":1,"mstp_port_portfast_bpdufilter_enabled":1,"found":1,"grouped":1}
,"bpduguard":{"filter":1}
,"filter":{"cist":1,"port":1,"used":1}
,"cist":{"port":1}
,"syntax":{"int":1}
,"int":{"mstp_api_set_port_bpdufilter":1}
,"(char":{"*name":1}
,"*name":{"char":1}
,"char":{"*ifname":1}
,"*ifname":{"u_char":1}
,"u_char":{"portfast_bpdufilter)":1}
,"portfast_bpdufilter)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"name":1,"none":1}
,"name":{"name":1,"bridge":1,"portfast_bpdufilter":1}
,"bridge":{"ifname":1,"bpdu":1,"bridge":1,"exist":1}
,"ifname":{"interface":1}
,"interface":{"name":1}
,"portfast_bpdufilter":{"bpdu":1}
,"bpdu":{"filter":1}
,"mstp_port_portfast_bpdufilter_enabled":{"mstp_port_portfast_bpdufilter_disabled":1}
,"mstp_port_portfast_bpdufilter_disabled":{"mstp_port_portfast_bpdufilter_default":1}
,"mstp_port_portfast_bpdufilter_default":{"default":1}
,"default":{"specified":1}
,"specified":{"bridge":1}
,"used":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"result_error":1}
,"result_error":{"port":1}
,"found":{"port":1}
,"grouped":{"bridge":1}
,"exist":{"result_ok":1}
,"result_ok":{"port\u0027s":1}
,"port\u0027s":{"bpdu":1}
}
;Search.control.loadWordPairs(pairs);
