var pairs =
{
"syslog":{"configuration":1,"standard":1,"server":1,"servers":1}
,"configuration":{"overview":1}
,"overview":{"syslog":1}
,"standard":{"logging":1}
,"logging":{"program":1,"messages":1,"file":1}
,"program":{"messages":1}
,"messages":{"allows":1,"system":1,"syslog":1,"either":1}
,"allows":{"separation":1}
,"separation":{"software":1}
,"software":{"generates":1,"reports":1}
,"generates":{"messages":1}
,"system":{"stores":1}
,"stores":{"software":1}
,"reports":{"analyzes":1}
,"analyzes":{"provides":1}
,"provides":{"devices":1}
,"devices":{"otherwise":1}
,"otherwise":{"unable":1}
,"unable":{"communicate":1}
,"communicate":{"means":1}
,"means":{"notify":1}
,"notify":{"administrators":1}
,"administrators":{"problems":1}
,"problems":{"performance":1}
,"performance":{"zebos-xp":1}
,"zebos-xp":{"supports":1,"messages":1,"executes)":1}
,"supports":{"logging":1}
,"server":{"addition":1,"(the":1}
,"addition":{"logging":1}
,"file":{"console":1}
,"console":{"(local":1}
,"(local":{"ssh\u002Ftelnet":1}
,"ssh\u002Ftelnet":{"console)":1}
,"console)":{"zebos-xp":1}
,"either":{"logged":1,"configured":1}
,"logged":{"local":1}
,"local":{"syslog":1}
,"(the":{"machine":1}
,"machine":{"zebos-xp":1}
,"executes)":{"remote":1}
,"remote":{"syslog":1}
,"servers":{"remote":1,"either":1}
,"configured":{"addresses":1}
,"addresses":{"(ipv4":1}
,"(ipv4":{"ipv6)":1}
,"ipv6)":{"hostname":1}
}
;Search.control.loadWordPairs(pairs);
