var pairs =
{
"mac-based":{"vlan":1}
,"vlan":{"classifiers":1,"bridge":1,"classifier":1,"create":1,"dut":1,"add":1,"ids":1,"configuration":1}
,"classifiers":{"dut":1}
,"dut":{"configure":1,"(config)":1,"(config-if)":1}
,"configure":{"terminal":1,"mode":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"interface":1}
,"mode":{"dut":1,"(if":1,"trunk":1}
,"(config)":{"bridge":1,"vlan":1,"interface":1}
,"bridge":{"protocol":1,"dut":1,"enable":1}
,"protocol":{"rstp":1}
,"rstp":{"vlan-bridge":1,"bridge":1}
,"vlan-bridge":{"create":1}
,"create":{"rstp":1,"mac-based":1,"group":1}
,"enable":{"vlan":1}
,"classifier":{"rule":1,"group":1,"activate":1}
,"rule":{"mac":1,"(mac":1,"create":1,"group":1}
,"mac":{"0000.0000.2222":1}
,"0000.0000.2222":{"vlan":1,"sent":1}
,"(mac":{"0000.0000.2222":1}
,"sent":{"vlan":1}
,"group":{"add":1,"rules":1,"dut":1,"interface":1,"switched":1}
,"add":{"rule":1,"enable":1,"switching":1}
,"rules":{"(add":1}
,"(add":{"rule":1}
,"interface":{"xe2":1,"mode":1,"trunk":1,"xe1":1,"xe4":1}
,"xe2":{"enter":1,"bridge":1,"packets":1}
,"(config-if)":{"switchport":1,"bridge-group":1,"vlan":1,"exit":1,"end":1}
,"switchport":{"switch":1,"mode":1,"trunk":1}
,"switch":{"layer":1}
,"layer":{"mode":1}
,"(if":{"using":1}
,"using":{"zebos-xp":1}
,"zebos-xp":{"hybrid":1}
,"hybrid":{"layer-2\u002Flayer-3":1}
,"layer-2\u002Flayer-3":{"module)":1}
,"module)":{"dut":1}
,"bridge-group":{"associate":1}
,"associate":{"interface":1}
,"trunk":{"switching":1,"mode":1,"allowed":1}
,"switching":{"characteristics":1}
,"characteristics":{"interface":1}
,"allowed":{"vlan":1}
,"ids":{"port":1}
,"port":{"dut":1}
,"activate":{"activate":1,"group":1}
,"packets":{"matching":1}
,"matching":{"group":1}
,"switched":{"vlan":1}
,"exit":{"exit":1,"interface":1,"vlan":1}
,"xe1":{"enter":1,"bridge":1}
,"configuration":{"mode":1}
,"xe4":{"enter":1,"bridge":1}
,"end":{"exit":1}
}
;Search.control.loadWordPairs(pairs);
