var pairs =
{
"vlan":{"state":1,"bridge":1,"<2-4094>":1,"enable":1,"disable":1,"configuration":1,"database":1,"name":1}
,"state":{"command":1,"particular":1,"indicates":1,"vlan":1,"disable":1,"enable":1}
,"command":{"enables":1,"syntax":1,"mode":1}
,"enables":{"disables":1}
,"disables":{"state":1}
,"particular":{"vlan":1}
,"bridge":{"default":1,"supported":1,"<1-32>":1,"group":1,"name":1}
,"default":{"bridge":1,"bridge)":1}
,"supported":{"hardware":1}
,"hardware":{"platforms":1}
,"platforms":{"command":1}
,"syntax":{"vlan":1}
,"<2-4094>":{"name":1,"bridge":1}
,"name":{"word":1,"vlan2":1}
,"word":{"(state":1}
,"(state":{"(enable":1}
,"(enable":{"disable))":1}
,"disable))":{"(for":1,"parameters":1}
,"(for":{"default":1}
,"bridge)":{"vlan":1,"(config-vlan)":1}
,"<1-32>":{"name":1,"specify":1}
,"parameters":{"<1-32>":1}
,"specify":{"bridge":1}
,"group":{"state":1}
,"indicates":{"operational":1}
,"operational":{"state":1}
,"enable":{"sets":1,"state":1,"(for":1}
,"sets":{"vlan":1}
,"disable":{"sets":1,"state":1}
,"mode":{"vlan":1,"examples":1}
,"configuration":{"mode":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"vlan":1}
,"database":{"(config-vlan)":1}
,"(config-vlan)":{"vlan":1}
,"vlan2":{"state":1}
}
;Search.control.loadWordPairs(pairs);
