var pairs =
{
"bridge":{"hello-time":1,"root":1,"protocol":1,"instance":1,"enforce":1,"<1-32>":1,"group":1}
,"hello-time":{"command":1,"time":1,"max-age":1,"<1-10>":1,"parameters":1,"(config)":1}
,"command":{"hello-time":1,"allowable":1,"syntax":1,"mode":1}
,"time":{"seconds":1,"always":1,"bridge":1}
,"seconds":{"(if":1,"however":1,"default)":1,"default":1,"command":1}
,"(if":{"bridge":1}
,"root":{"bridge)":1}
,"bridge)":{"bridges":1}
,"bridges":{"bridged":1}
,"bridged":{"lan":1}
,"lan":{"exchange":1}
,"exchange":{"bridge":1}
,"protocol":{"data":1}
,"data":{"units":1}
,"units":{"(bpdus)":1}
,"(bpdus)":{"low":1}
,"low":{"value":1}
,"value":{"parameter":1,"delays":1,"used":1,"hello":1,"hold":1,"seconds":1}
,"parameter":{"leads":1,"restore":1}
,"leads":{"excessive":1}
,"excessive":{"traffic":1}
,"traffic":{"network":1}
,"network":{"higher":1}
,"higher":{"value":1}
,"delays":{"detection":1}
,"detection":{"topology":1}
,"topology":{"change.this":1}
,"change.this":{"value":1}
,"used":{"instances":1}
,"instances":{"configure":1}
,"configure":{"bridge":1,"mode":1,"terminal":1}
,"instance":{"name":1}
,"name":{"using":1}
,"using":{"command":1}
,"allowable":{"range":1}
,"range":{"values":1}
,"values":{"1-10":1}
,"1-10":{"seconds":1}
,"however":{"sure":1}
,"sure":{"value":1}
,"hello":{"time":1,"bpdu":1}
,"always":{"greater":1}
,"greater":{"value":1}
,"hold":{"time":1}
,"default)":{"parameter":1}
,"restore":{"default":1}
,"default":{"value":1,"default":1}
,"enforce":{"following":1}
,"following":{"relationships":1}
,"relationships":{"hello-time":1}
,"max-age":{"forward-delay":1}
,"forward-delay":{"(bridge_forward_delay":1}
,"(bridge_forward_delay":{"1.0":1}
,"1.0":{"seconds)":1}
,"seconds)":{">=bridge_max_age":1,"command":1}
,">=bridge_max_age":{"bridge_max_age":1}
,"bridge_max_age":{">=2":1}
,">=2":{"(bridge_hello_time":1}
,"(bridge_hello_time":{"1.0":1}
,"syntax":{"bridge":1}
,"<1-32>":{"hello-time":1,"specify":1}
,"<1-10>":{"bridge":1,"specify":1}
,"parameters":{"<1-32>":1}
,"specify":{"bridge":1,"hello":1}
,"group":{"<1-10>":1}
,"bpdu":{"interval":1}
,"interval":{"seconds":1}
,"mode":{"configure":1,"examples":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"bridge":1}
}
;Search.control.loadWordPairs(pairs);
