var pairs =
{
"rfc":{"5602":1}
,"5602":{"rfc":1,"defines":1}
,"defines":{"objects":1}
,"objects":{"modeling":1}
,"modeling":{"edge-to-edge":1}
,"edge-to-edge":{"services":1}
,"services":{"carried":1}
,"carried":{"mpls":1}
,"mpls":{"network":1}
,"network":{"object":1}
,"object":{"type":1}
,"type":{"syntax":1}
,"syntax":{"access":1}
,"access":{"function":1}
,"function":{"pwmplsmplstype":1}
,"pwmplsmplstype":{"bits":1}
,"bits":{"read-write":1}
,"read-write":{"nsm_mpls_set_pw_mpls_mpls_type":1,"nsm_mpls_set_pw_mpls_exp_bits_mode":1,"nsm_mpls_set_pw_mpls_exp_bits":1,"nsm_mpls_set_pw_mpls_ttl":1,"nsm_mpls_set_pw_mpls_lcl_ldp_id":1,"nsm_mpls_set_pw_mpls_lcl_ldp_entty_ix":1,"nsm_mpls_set_pw_mpls_outbd_lsr_xc_ix":1,"nsm_mpls_set_pw_mpls_outbd_tnl_ix":1,"nsm_mpls_set_pw_mpls_outbd_tnl_lcl_lsr":1,"nsm_mpls_set_pw_mpls_outbd_tnl_peer_lsr":1}
,"nsm_mpls_set_pw_mpls_mpls_type":{"pwmplsexpbitsmode":1}
,"pwmplsexpbitsmode":{"integer":1}
,"integer":{"read-write":1}
,"nsm_mpls_set_pw_mpls_exp_bits_mode":{"pwmplsexpbits":1}
,"pwmplsexpbits":{"unsigned32":1}
,"unsigned32":{"read-write":1}
,"nsm_mpls_set_pw_mpls_exp_bits":{"pwmplsttl":1}
,"pwmplsttl":{"unsigned32":1}
,"nsm_mpls_set_pw_mpls_ttl":{"pwmplslocalldpid":1}
,"pwmplslocalldpid":{"mplsldpidentifier":1}
,"mplsldpidentifier":{"read-write":1}
,"nsm_mpls_set_pw_mpls_lcl_ldp_id":{"pwmplslocalldpentityindex":1}
,"pwmplslocalldpentityindex":{"unsigned32":1}
,"nsm_mpls_set_pw_mpls_lcl_ldp_entty_ix":{"pwmplsoutboundlsrxcindex":1}
,"pwmplsoutboundlsrxcindex":{"mplsindextype":1}
,"mplsindextype":{"read-write":1}
,"nsm_mpls_set_pw_mpls_outbd_lsr_xc_ix":{"pwmplsoutboundtunnelindex":1}
,"pwmplsoutboundtunnelindex":{"mplstunnelindex":1}
,"mplstunnelindex":{"read-write":1}
,"nsm_mpls_set_pw_mpls_outbd_tnl_ix":{"pwmplsoutboundtunnellcllsr":1}
,"pwmplsoutboundtunnellcllsr":{"mplslsridentifier":1}
,"mplslsridentifier":{"read-write":1}
,"nsm_mpls_set_pw_mpls_outbd_tnl_lcl_lsr":{"pwmplsoutboundtunnelpeerlsr":1}
,"pwmplsoutboundtunnelpeerlsr":{"mplslsridentifier":1}
,"nsm_mpls_set_pw_mpls_outbd_tnl_peer_lsr":{"pwmplsoutboundifindex":1}
,"pwmplsoutboundifindex":{"interfaceindexorzero":1}
,"interfaceindexorzero":{"read-write":1}
}
;Search.control.loadWordPairs(pairs);
