var pairs =
{
"starting":{"client":1}
,"client":{"creating":1,"application":1,"protocol":1}
,"creating":{"api":1}
,"api":{"client":1}
,"application":{"start":1}
,"start":{"client":1}
,"protocol":{"modules":1}
,"modules":{"calling":1}
,"calling":{"zebos_smi_client_start":1}
,"zebos_smi_client_start":{"example":1}
,"example":{"unsigned":1}
,"unsigned":{"int":1}
,"int":{"errflag":1}
,"errflag":{"char":1,"=zebos_smi_client_start":1}
,"char":{"*ipaddr":1,"ipaddr_str":1}
,"*ipaddr":{"=null":1}
,"=null":{"\u002F\u002Ffrom":1}
,"\u002F\u002Ffrom":{"command":1}
,"command":{"line":1}
,"line":{"char":1}
,"ipaddr_str":{"[16]":1}
,"[16]":{"pal_snprintf":1}
,"pal_snprintf":{"(ipaddr_str":1}
,"(ipaddr_str":{"sizeof":1}
,"sizeof":{"(ipaddr_str)":1}
,"(ipaddr_str)":{"argv":1}
,"argv":{"[1])":1}
,"[1])":{"ipaddr":1}
,"ipaddr":{"=ipaddr_str":1}
,"=ipaddr_str":{"errflag":1}
,"=zebos_smi_client_start":{"(azg":1}
,"(azg":{"ipaddr)":1}
}
;Search.control.loadWordPairs(pairs);
