var pairs =
{
"mrib_snmp_api_nh_index":{"structure":1,"{unsigned":1}
,"structure":{"used":1}
,"used":{"provide":1}
,"provide":{"nexthop":1}
,"nexthop":{"index":1}
,"index":{"information":1}
,"information":{"access":1}
,"access":{"ipmroutenexthoptable":1}
,"ipmroutenexthoptable":{"resides":1}
,"resides":{"mribd\u002Fmrib_snmp_api.h":1}
,"mribd\u002Fmrib_snmp_api.h":{"file":1}
,"file":{"struct":1}
,"struct":{"mrib_snmp_api_nh_index":1,"pal_in4_addr":1,"pal_in6_addr":1}
,"{unsigned":{"int":1}
,"int":{"len":1}
,"len":{"u_int32_t":1}
,"u_int32_t":{"group_addr_type":1,"source_addr_type":1,"ifindex":1,"addr_type":1}
,"group_addr_type":{"struct":1}
,"pal_in4_addr":{"group":1,"source":1,"addr":1}
,"group":{"ifdef":1}
,"ifdef":{"have_mrib_ipv6":1}
,"have_mrib_ipv6":{"struct":1}
,"pal_in6_addr":{"group6":1,"source6":1,"addr6":1}
,"group6":{"endif":1}
,"endif":{"\u002F*have_mrib_ipv6":1}
,"\u002F*have_mrib_ipv6":{"*\u002Fu_int32_t":1,"*\u002F}":1}
,"*\u002Fu_int32_t":{"group_prefix_len":1,"source_prefix_len":1}
,"group_prefix_len":{"u_int32_t":1}
,"source_addr_type":{"struct":1}
,"source":{"ifdef":1}
,"source6":{"endif":1}
,"source_prefix_len":{"u_int32_t":1}
,"ifindex":{"u_int32_t":1}
,"addr_type":{"struct":1}
,"addr":{"ifdef":1}
,"addr6":{"endif":1}
}
;Search.control.loadWordPairs(pairs);
