var pairs =
{
"intermediate":{"system":1}
,"system":{"intermediate":1,"(is-is)":1}
,"(is-is)":{"interior":1}
,"interior":{"gateway":1}
,"gateway":{"protocol":1}
,"protocol":{"(igp)":1}
,"(igp)":{"floods":1}
,"floods":{"link":1}
,"link":{"state":1}
,"state":{"information":1}
,"information":{"throughout":1,"routing":1,"base":1}
,"throughout":{"network":1}
,"network":{"routers":1,"information":1,"packets":1,"destination":1}
,"routers":{"is-is":1}
,"is-is":{"router":1,"uses":1}
,"router":{"independently":1}
,"independently":{"builds":1}
,"builds":{"database":1}
,"database":{"network\u0027s":1,"constructing":1}
,"network\u0027s":{"topology":1}
,"topology":{"aggregating":1}
,"aggregating":{"flooded":1}
,"flooded":{"network":1}
,"routing":{"information":1}
,"base":{"(rib)":1}
,"(rib)":{"calculated":1}
,"calculated":{"database":1}
,"constructing":{"shortest":1}
,"shortest":{"path":1}
,"path":{"tree":1,"first":1,"network":1}
,"tree":{"(spt)":1}
,"(spt)":{"open":1}
,"open":{"shortest":1}
,"first":{"(ospf)":1}
,"(ospf)":{"is-is":1}
,"uses":{"dijkstra":1}
,"dijkstra":{"algorithm":1}
,"algorithm":{"find":1}
,"find":{"best":1}
,"best":{"path":1}
,"packets":{"forwarded":1}
,"forwarded":{"based":1}
,"based":{"computed":1}
,"computed":{"ideal":1}
,"ideal":{"path":1}
,"destination":{"defined":1}
,"defined":{"international":1}
,"international":{"organization":1}
,"organization":{"standardization":1}
,"standardization":{"(iso)":1}
,"(iso)":{"10589":1}
}
;Search.control.loadWordPairs(pairs);
