var pairs =
{
"network":{"x:x":1,"address":1,"data":1,"command":1,"advertised":1,"specified":1,"dynamically":1,"sourced":1,"learned":1,"distance":1,"172.26.0.0\u002F16":1,"172.10.0.0":1,"172.16.1.0\u002F24":1}
,"x:x":{":x:x":1,":x:x\u002Fm":1}
,":x:x":{"command":1,"ipv6":1}
,"command":{"specify":1,"specifies":1,"works":1,"remove":1,"syntax":1,"mode":1}
,"specify":{"networks":1,"backdoor":1,"bgp":1}
,"networks":{"advertised":1}
,"advertised":{"bgp":1,"network":1,"known":1}
,"bgp":{"routing":1,"border":1,"backdoor":1,"(config-router)":1,"200":1}
,"routing":{"process":1,"table":1,"protocols":1}
,"process":{"unicast":1}
,"unicast":{"network":1}
,"address":{"without":1,"matches":1,"family":1}
,"without":{"mask":1}
,"mask":{"accepted":1,"derived":1}
,"accepted":{"falls":1}
,"falls":{"natural":1}
,"natural":{"boundary":1,"class-boundary":1}
,"boundary":{"class":1}
,"class":{"class-boundary":1}
,"class-boundary":{"mask":1,"backdoor":1}
,"derived":{"address":1}
,"matches":{"natural":1}
,"backdoor":{"parameter":1,"route":1,"network":1,"specify":1,"(config-router)":1}
,"parameter":{"specify":1,"enables":1,"command":1,"allow":1}
,"route":{"bgp":1,"specified":1,"preferred":1,"even":1,"learned":1,"word":1,"map":1,"backdoor":1}
,"border":{"router":1}
,"router":{"provide":1,"backdoor":1,"network":1,"mode":1,"bgp":1,"rip":1}
,"provide":{"better":1}
,"better":{"information":1}
,"information":{"network":1}
,"data":{"advertised":1}
,"table":{"include":1}
,"include":{"route":1}
,"specified":{"network":1,"backdoor":1}
,"specifies":{"networks":1}
,"works":{"network":1}
,"known":{"router":1}
,"enables":{"route":1}
,"preferred":{"route":1,"backdoor":1}
,"even":{"greater":1}
,"greater":{"distance":1}
,"distance":{"network":1,"200":1}
,"dynamically":{"assigned":1}
,"assigned":{"administrative":1}
,"administrative":{"distance":1}
,"200":{"ensuring":1,"parameter":1,"(config)":1}
,"ensuring":{"igp":1}
,"igp":{"learned":1}
,"learned":{"routes":1,"external":1,"ebgp":1}
,"routes":{"preferred":1}
,"sourced":{"local":1}
,"local":{"router":1}
,"external":{"routers":1}
,"routers":{"route":1}
,"ebgp":{"backdoor":1,"(distance":1}
,"remove":{"entry":1}
,"entry":{"command":1}
,"syntax":{"network":1}
,":x:x\u002Fm":{"network":1,"backdoor":1,"route-map":1}
,"route-map":{"word":1,"ipi":1}
,"word":{"(backdoor":1,"name":1}
,"(backdoor":{"network":1,"parameters":1}
,"parameters":{"x:x":1}
,"ipv6":{"prefix":1}
,"prefix":{"<network>":1}
,"<network>":{"example":1}
,"example":{"3ffe":1}
,"3ffe":{"backdoor":1}
,"name":{"route":1}
,"map":{"command":1}
,"mode":{"router":1,"address":1,"examples":1}
,"family":{"mode":1}
,"examples":{"(config)":1}
,"(config)":{"router":1,"network":1,"neighbor":1}
,"(config-router)":{"network":1}
,"172.26.0.0\u002F16":{"router1":1}
,"router1":{"receives":1,"chooses":1,"learn":1}
,"receives":{"updates":1}
,"updates":{"172.10.0.0":1}
,"172.10.0.0":{"via":1,"(config)":1,"backdoor":1}
,"via":{"two":1,"rip":1}
,"two":{"routing":1}
,"protocols":{"rip":1}
,"rip":{"(distance":1,"(config)":1}
,"(distance":{"120)":1,"20)":1}
,"120)":{"ebgp":1}
,"20)":{"router1":1}
,"chooses":{"shorter":1}
,"shorter":{"route":1}
,"allow":{"router1":1}
,"learn":{"172.10.0.0":1}
,"neighbor":{"3.3.3.3":1}
,"3.3.3.3":{"remote-as":1}
,"remote-as":{"500":1}
,"500":{"(config)":1}
,"172.16.1.0\u002F24":{"route-map":1}
}
;Search.control.loadWordPairs(pairs);
