var pairs =
{
"bgp":{"g-shut":1,"ipv4":1,"graceful":1,"100":1}
,"g-shut":{"command":1,"bgp":1,"parameters":1,"configure":1}
,"command":{"gracefully":1,"bring":1,"details":1,"syntax":1,"mode":1}
,"gracefully":{"shut":1}
,"shut":{"down":1}
,"down":{"bgp":1}
,"ipv4":{"ipv6":1}
,"ipv6":{"sessions":1}
,"sessions":{"router":1}
,"router":{"bgp":1,"completion":1,"mode":1}
,"graceful":{"shutdown":1}
,"shutdown":{"feature":1}
,"feature":{"reduces":1,"border":1}
,"reduces":{"packet":1}
,"packet":{"loss":1}
,"loss":{"during":1}
,"during":{"maintenance":1}
,"maintenance":{"activity":1}
,"activity":{"parameter":1,"using":1}
,"parameter":{"command":1}
,"bring":{"sessions":1}
,"completion":{"maintenance":1}
,"using":{"bgp":1}
,"details":{"graceful":1}
,"border":{"gateway":1}
,"gateway":{"protocol":1}
,"protocol":{"developer":1}
,"developer":{"guide":1}
,"guide":{"command":1}
,"syntax":{"bgp":1}
,"parameters":{"none":1}
,"none":{"default":1}
,"default":{"disabled":1}
,"disabled":{"command":1}
,"mode":{"router":1,"examples":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"100":{"(config-router)":1}
,"(config-router)":{"bgp":1}
}
;Search.control.loadWordPairs(pairs);
