var pairs =
{
"debug":{"bgp":1,"information":1,"inbound":1,"outbound":1}
,"bgp":{"command":1,"troubleshooting":1,"debug":1,"(all":1,"bfd":1,"dampening":1,"events":1,"filters":1,"fsm":1,"keepalives":1,"mpls":1,"nht":1,"nsm":1,"updates":1,"vpls":1,"bidirectional":1,"finite":1,"multiprotocol":1,"virtual":1}
,"command":{"enable":1,"without":1,"disable":1,"syntax":1,"mode":1}
,"enable":{"bgp":1,"debugging":1}
,"troubleshooting":{"functions":1}
,"functions":{"command":1}
,"without":{"parameters":1}
,"parameters":{"turn":1,"used":1}
,"turn":{"normal":1}
,"normal":{"bgp":1}
,"information":{"parameter":1}
,"parameter":{"command":1}
,"disable":{"function":1}
,"function":{"command":1}
,"syntax":{"debug":1}
,"(all":{"debug":1,"undebug":1}
,"bfd":{"debug":1,"undebug":1,"enable":1}
,"dampening":{"debug":1,"undebug":1,"enable":1,"events":1}
,"events":{"debug":1,"undebug":1,"enable":1,"filters":1}
,"filters":{"debug":1,"undebug":1,"enable":1,"fsm":1}
,"fsm":{"debug":1,"undebug":1,"enable":1}
,"keepalives":{"debug":1,"undebug":1,"enable":1,"mpls":1}
,"mpls":{"debug":1,"undebug":1,"enable":1}
,"nht":{"debug":1,"undebug":1,"enable":1,"nsm":1}
,"nsm":{"debug":1,"undebug":1,"enable":1,"messages":1}
,"updates":{"debug":1,"(in":1,"undebug":1,"enable":1,"vpls":1}
,"(in":{"out)":1}
,"out)":{"debug":1}
,"vpls":{"debug":1,"undebug":1,"parameters":1,"enable":1}
,"undebug":{"bgp":1}
,"used":{"form":1}
,"form":{"turns":1}
,"turns":{"debugging":1}
,"debugging":{"bgp":1,"nsm":1}
,"bidirectional":{"forwarding":1}
,"forwarding":{"detection":1}
,"detection":{"dampening":1}
,"finite":{"state":1}
,"state":{"machine":1}
,"machine":{"(fsm)":1}
,"(fsm)":{"keepalives":1}
,"multiprotocol":{"label":1}
,"label":{"switching":1}
,"switching":{"(mpls)":1}
,"(mpls)":{"nht":1}
,"messages":{"updates":1}
,"inbound":{"updates":1}
,"outbound":{"updates":1}
,"virtual":{"private":1}
,"private":{"lan":1}
,"lan":{"service":1}
,"service":{"(vpls)":1}
,"(vpls)":{"command":1}
,"mode":{"privileged":1,"configure":1,"examples":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"configure":{"mode":1}
,"examples":{"debug":1}
}
;Search.control.loadWordPairs(pairs);
