var pairs =
{
"debug":{"support":1,"output":1}
,"support":{"protocol":1}
,"protocol":{"modules":1}
,"modules":{"vlog":1,"ospfv2":1}
,"vlog":{"build":1}
,"build":{"allows":1}
,"allows":{"operators":1}
,"operators":{"enable":1}
,"enable":{"debugging":1}
,"debugging":{"specific":1,"vr-specific":1,"protocol":1}
,"specific":{"context":1,"type":1,"virtual":1}
,"context":{"bgp":1,"specific":1}
,"bgp":{"ospfv2":1,"context-sensitive":1}
,"ospfv2":{"ospfv3":1,"isis":1}
,"ospfv3":{"is-is":1,"ripng":1}
,"is-is":{"rip":1}
,"rip":{"ripng":1,"bgp":1}
,"ripng":{"commands":1,"rip":1}
,"commands":{"entered":1}
,"entered":{"global":1}
,"global":{"configure":1}
,"configure":{"mode":1,"system":1}
,"mode":{"allow":1}
,"allow":{"user":1}
,"user":{"configure":1,"logged":1,"may":1}
,"system":{"specific":1}
,"type":{"debugging":1}
,"vr-specific":{"debug":1}
,"output":{"written":1,"including":1}
,"written":{"terminals":1}
,"terminals":{"user":1}
,"logged":{"pvr":1}
,"pvr":{"user":1}
,"may":{"view":1}
,"view":{"debug":1}
,"including":{"generated":1}
,"generated":{"context":1}
,"virtual":{"routers":1}
,"routers":{"debugging":1}
,"isis":{"ospfv3":1}
}
;Search.control.loadWordPairs(pairs);
