var pairs =
{
"efm_oam_show_status":{"function":1,"(struct":1}
,"function":{"gets":1,"implements":1}
,"gets":{"interface":1}
,"interface":{"status":1,"*ifp":1,"structure":1}
,"status":{"function":1,"command":1}
,"implements":{"show":1}
,"show":{"ethernet":1}
,"ethernet":{"oam":1}
,"oam":{"status":1}
,"command":{"syntax":1}
,"syntax":{"void":1}
,"void":{"efm_oam_show_status":1}
,"(struct":{"interface":1}
,"*ifp":{"struct":1}
,"struct":{"cli":1}
,"cli":{"*cli)":1,"pointer":1,"structure":1}
,"*cli)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"cli":1}
,"ifp":{"pointer":1}
,"pointer":{"interface":1,"cli":1}
,"structure":{"output":1,"return":1}
,"output":{"parameters":1}
,"return":{"values":1}
,"values":{"none":1}
}
;Search.control.loadWordPairs(pairs);
