var pairs =
{
"hal_apbf_rule_status_get":{"function":1,"(struct":1}
,"function":{"creates":1}
,"creates":{"message":1}
,"message":{"sends":1,"output":1}
,"sends":{"hsl":1}
,"hsl":{"apbf":1}
,"apbf":{"rule":1}
,"rule":{"counter":1,"status":1,"message":1,"returns":1}
,"counter":{"information":1}
,"information":{"hardware":1}
,"hardware":{"syntax":1}
,"syntax":{"int":1}
,"int":{"hal_apbf_rule_status_get":1}
,"(struct":{"hal_apbf_rule_status":1}
,"hal_apbf_rule_status":{"*rule_status":1}
,"*rule_status":{"struct":1}
,"struct":{"hal_apbf_acl_id_status":1}
,"hal_apbf_acl_id_status":{"*status)":1}
,"*status)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"rule_status":1,"status":1}
,"rule_status":{"rule":1}
,"status":{"key":1,"64-bit":1}
,"key":{"hal_rule_msg":1}
,"hal_rule_msg":{"hal":1}
,"hal":{"rule":1}
,"output":{"parameters":1}
,"64-bit":{"count":1}
,"count":{"number":1}
,"number":{"packets":1}
,"packets":{"hit":1}
,"hit":{"particular":1}
,"particular":{"rule":1}
,"returns":{"hsl_success":1}
,"hsl_success":{"success":1}
,"success":{"hsl_failure":1}
,"hsl_failure":{"failure":1}
}
;Search.control.loadWordPairs(pairs);
