var pairs =
{
"ospf6_get_next_if_hello_interval":{"function":1,"(char":1}
,"function":{"gets":1,"fails":1,"succeeds":1}
,"gets":{"next":1}
,"next":{"entry":1}
,"entry":{"value":1}
,"value":{"interface":1,"routers":1}
,"interface":{"hello":1,"value":1,"index":1}
,"hello":{"interval":1,"packets":1}
,"interval":{"length":1,"seconds":1}
,"length":{"time":1,"object":1}
,"time":{"seconds":1}
,"seconds":{"hello":1,"return":1}
,"packets":{"router":1}
,"router":{"sends":1}
,"sends":{"given":1}
,"given":{"interface":1}
,"routers":{"attached":1}
,"attached":{"common":1}
,"common":{"network":1}
,"network":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf6_get_next_if_hello_interval":1,"*ifindex":1,"*instid":1,"indexlen":1,"*ret)":1}
,"(char":{"*tag":1}
,"*tag":{"int":1}
,"*ifindex":{"int":1}
,"*instid":{"int":1}
,"indexlen":{"int":1,"length":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"tag":1,"ret":1}
,"tag":{"ospfv3":1,"ifindex":1}
,"ospfv3":{"process":1}
,"process":{"tag":1}
,"ifindex":{"interface":1}
,"index":{"instid":1,"output":1}
,"instid":{"instance":1}
,"instance":{"identifier":1}
,"identifier":{"indexlen":1}
,"object":{"index":1}
,"output":{"parameters":1}
,"ret":{"interface":1}
,"return":{"values":1}
,"values":{"ospf6_api_get_error":1}
,"ospf6_api_get_error":{"function":1}
,"fails":{"ospf6_api_get_success":1}
,"ospf6_api_get_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
