var pairs =
{
"pbb_snmp_vip_lookup_by_portnum":{"function":1}
,"function":{"finds":1,"succeeds":1}
,"finds":{"entry":1}
,"entry":{"vip":1}
,"vip":{"table":1}
,"table":{"given":1}
,"given":{"port":1}
,"port":{"syntax":1,"number":1}
,"syntax":{"struct":1}
,"struct":{"vip_tbl":1}
,"vip_tbl":{"*pbb_snmp_vip_lookup_by_portnum":1,"structure":1}
,"*pbb_snmp_vip_lookup_by_portnum":{"(struct":1}
,"(struct":{"avl_tree":1}
,"avl_tree":{"*tree":1,"avl":1}
,"*tree":{"u_int32_t":1}
,"u_int32_t":{"port_num":1}
,"port_num":{"int":1,"base":1}
,"int":{"exact)":1}
,"exact)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"avl_tree":1,"none":1}
,"avl":{"tree":1}
,"tree":{"structure":1}
,"structure":{"port_num":1,"function":1}
,"base":{"port":1}
,"number":{"exact":1}
,"exact":{"exact":1,"value":1}
,"value":{"true":1,"pointer":1}
,"true":{"false":1}
,"false":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"pointer":{"vip_tbl":1}
}
;Search.control.loadWordPairs(pairs);
