var pairs =
{
"gmrp_vlan":{"structure":1,"{u_int16_t":1}
,"structure":{"contains":1,"defined":1}
,"contains":{"vid":1}
,"vid":{"associated":1}
,"associated":{"count":1}
,"count":{"number":1}
,"number":{"packets":1,"packet":1}
,"packets":{"transmitted":1}
,"transmitted":{"received":1,"definition":1}
,"received":{"vlan":1,"transmit_counters":1}
,"vlan":{"following":1,"identifier":1}
,"following":{"data":1}
,"data":{"structure":1}
,"defined":{"nsm\u002Fl2\u002Fgarp\u002Fgmrp.h":1}
,"nsm\u002Fl2\u002Fgarp\u002Fgmrp.h":{"member":1}
,"member":{"definition":1}
,"definition":{"vlanid":1,"struct":1}
,"vlanid":{"vlan":1,"ifdef":1}
,"identifier":{"receive_counters":1}
,"receive_counters":{"hold":1,"[mrp_attr_event_max":1,"[garp_attr_event_max":1}
,"hold":{"number":1}
,"packet":{"received":1,"transmitted":1}
,"transmit_counters":{"holds":1,"[mrp_attr_event_max":1,"[garp_attr_event_max":1}
,"holds":{"number":1}
,"struct":{"gmrp_vlan":1}
,"{u_int16_t":{"vlanid":1}
,"ifdef":{"have_mmrp":1}
,"have_mmrp":{"u_int32_t":1}
,"u_int32_t":{"receive_counters":1,"transmit_counters":1}
,"[mrp_attr_event_max":{"u_int32_t":1,"else":1}
,"else":{"u_int32_t":1}
,"[garp_attr_event_max":{"u_int32_t":1,"endif":1}
,"endif":{"\u002F*have_mmrp":1}
,"\u002F*have_mmrp":{"*\u002F}":1}
}
;Search.control.loadWordPairs(pairs);
