var pairs =
{
"command":{"bind":1,"delete":1,"syntax":1,"mode":1}
,"bind":{"interface":1}
,"interface":{"mpls-tp":1,"mode":1,"eth0":1}
,"mpls-tp":{"layer":1}
,"layer":{"virtual":1,"circuit":1}
,"virtual":{"circuit":1}
,"circuit":{"created":1,"maximum":1}
,"created":{"configure":1}
,"configure":{"mode":1,"terminal":1}
,"mode":{"parameter":1,"interface":1,"examples":1}
,"parameter":{"command":1}
,"delete":{"instance":1}
,"instance":{"command":1}
,"syntax":{"name":1}
,"name":{"(ethernet":1,"name":1,"layer":1}
,"(ethernet":{"vlan":1,"name":1}
,"vlan":{"<2-4094>":1,"identify":1,"command":1}
,"<2-4094>":{"name":1,"parameters":1,"enter":1}
,"parameters":{"name":1}
,"maximum":{"characters":1}
,"characters":{"ethernet":1}
,"ethernet":{"identify":1,"vlan":1}
,"identify":{"object":1}
,"object":{"ethernet":1,"vlan":1}
,"enter":{"vlan":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"mycircuit":1}
,"mycircuit":{"ethernet":1}
}
;Search.control.loadWordPairs(pairs);
