var pairs =
{
"bfd_auth_process_validate":{"function":1,"(struct":1}
,"function":{"decodes":1}
,"decodes":{"validates":1}
,"validates":{"authentication":1}
,"authentication":{"section":1,"session":1}
,"section":{"bfd":1}
,"bfd":{"packet":1,"authentication":1}
,"packet":{"syntax":1,"buffer":1}
,"syntax":{"bool_t":1}
,"bool_t":{"bfd_auth_process_validate":1}
,"(struct":{"bfd_session_fwd":1}
,"bfd_session_fwd":{"*sess":1}
,"*sess":{"u_char":1,"bfd":1}
,"u_char":{"*bfd_pkt_buf)":1}
,"*bfd_pkt_buf)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"*sess":1,"none":1}
,"session":{"*bfd_pkt_buf":1}
,"*bfd_pkt_buf":{"bfd":1}
,"buffer":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"bfd_false":1}
,"bfd_false":{"validation":1}
,"validation":{"failed":1,"success":1}
,"failed":{"bfd_true":1}
,"bfd_true":{"validation":1}
}
;Search.control.loadWordPairs(pairs);
