var pairs =
{
"ripng_aggregate_delete":{"function":1,"(u_int32_t":1}
,"function":{"deletes":1,"called":1}
,"deletes":{"aggregate":1}
,"aggregate":{"advertising":1}
,"advertising":{"routes":1}
,"routes":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"aggregate-address":1}
,"aggregate-address":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ripng_aggregate_delete":1,"rip_instance":1,"plen)":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"int":1,"virtual":1}
,"rip_instance":{"struct":1,"instance":1}
,"struct":{"pal_in6_addr":1}
,"pal_in6_addr":{"*addr":1}
,"*addr":{"int":1}
,"plen)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1,"exist":1}
,"default":{"value":1}
,"value":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"parameter":1}
,"parameter":{"rip_instance":1}
,"instance":{"number":1,"cannot":1}
,"number":{"addr":1}
,"addr":{"aggregated":1}
,"aggregated":{"route":1}
,"route":{"prefix":1,"output":1}
,"prefix":{"plen":1,"length":1}
,"plen":{"prefix":1}
,"length":{"static":1,"range":1}
,"static":{"rip":1}
,"rip":{"route":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"rip_api_set_err_invalid_value":1}
,"rip_api_set_err_invalid_value":{"address":1}
,"address":{"invalid":1}
,"invalid":{"rip_api_set_err_network_not_exist":1}
,"rip_api_set_err_network_not_exist":{"network":1}
,"network":{"exist":1}
,"exist":{"rip_api_set_err_prefix_invalid":1,"rip_api_set_success":1}
,"rip_api_set_err_prefix_invalid":{"prefix":1}
,"range":{"128>":1}
,"128>":{"rip_api_set_err_process_not_exist":1}
,"rip_api_set_err_process_not_exist":{"instance":1}
,"cannot":{"found":1}
,"found":{"rip_api_set_err_vr_not_exist":1}
,"rip_api_set_err_vr_not_exist":{"virtual":1}
,"rip_api_set_success":{"call":1}
,"call":{"successful":1}
}
;Search.control.loadWordPairs(pairs);
