var pairs =
{
"nsm_mpls_set_ftn_src_dst_port_max":{"function":1,"(struct":1}
,"function":{"sets":1,"succeeds":1,"fails":1}
,"sets":{"upper":1}
,"upper":{"end":1}
,"end":{"source":1}
,"source":{"destination":1}
,"destination":{"port":1}
,"port":{"range":1}
,"range":{"syntax":1,"permitted":1}
,"syntax":{"u_int32_t":1}
,"u_int32_t":{"nsm_mpls_set_ftn_src_dst_port_max":1,"ftn_ix":1,"src_dst_port_max)":1}
,"(struct":{"nsm_master":1}
,"nsm_master":{"*nm":1}
,"*nm":{"u_int32_t":1}
,"ftn_ix":{"u_int32_t":1,"index":1}
,"src_dst_port_max)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"nsm":1,"none":1}
,"nsm":{"master":1}
,"master":{"ftn_ix":1}
,"index":{"conceptual":1}
,"conceptual":{"row":1}
,"row":{"ftn":1}
,"ftn":{"table":1}
,"table":{"src_dst_port_max":1}
,"src_dst_port_max":{"upper":1}
,"permitted":{"value":1}
,"value":{"65535":1}
,"65535":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_api_set_success":1}
,"nsm_api_set_success":{"function":1}
,"succeeds":{"nsm_api_set_error":1}
,"nsm_api_set_error":{"function":1}
}
;Search.control.loadWordPairs(pairs);
