var pairs =
{
"lldp_api_set_port_msg_tx_hold":{"function":1,"(u_char*mac":1}
,"function":{"called":1,"succeeds":1}
,"called":{"msg-tx-hold":1}
,"msg-tx-hold":{"parameter":1}
,"parameter":{"determines":1}
,"determines":{"time":1,"final":1}
,"time":{"live":1}
,"live":{"(ttl)":1}
,"(ttl)":{"value":1}
,"value":{"lldpdus":1,"command":1,"determines":1,"syntax":1,"invalid":1}
,"lldpdus":{"transmitted":1}
,"transmitted":{"port":1}
,"port":{"value":1}
,"command":{"multiplied":1}
,"multiplied":{"lldp":1}
,"lldp":{"timer":1,"agent":1}
,"timer":{"msg-tx-interval":1}
,"msg-tx-interval":{"value":1}
,"final":{"ttl":1}
,"ttl":{"value":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"lldp_api_set_port_msg_tx_hold":1}
,"(u_char*mac":{"struct":1}
,"struct":{"interface":1}
,"interface":{"*ifp":1,"structure":1,"found":1}
,"*ifp":{"u_int32_t":1}
,"u_int32_t":{"value)":1}
,"value)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"mac":1,"none":1}
,"mac":{"mac":1,"address":1}
,"address":{"lldp":1}
,"agent":{"ifp":1,"found":1}
,"ifp":{"interface":1}
,"structure":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"lldp_api_success":1}
,"lldp_api_success":{"function":1}
,"succeeds":{"lldp_api_err_invalid_val":1}
,"lldp_api_err_invalid_val":{"value":1}
,"invalid":{"lldp_api_err_lldp_if_not_exist":1}
,"lldp_api_err_lldp_if_not_exist":{"interface":1}
,"found":{"lldp_api_err_onm_if_not_exist":1,"lldp_api_err_agent_not_found":1}
,"lldp_api_err_onm_if_not_exist":{"onmd":1}
,"onmd":{"found":1}
,"lldp_api_err_agent_not_found":{"agent":1}
}
;Search.control.loadWordPairs(pairs);
