var pairs =
{
"show":{"rsvp":1}
,"rsvp":{"version":1,"daemon":1,"protocol":1}
,"version":{"command":1,"rsvp":1,"parameters":1,"resource":1,"rfc2205":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"version":1}
,"daemon":{"current":1}
,"current":{"rsvp":1}
,"syntax":{"show":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"exec":1}
,"exec":{"privileged":1,"modes":1}
,"privileged":{"exec":1}
,"modes":{"example":1}
,"example":{"show":1}
,"resource":{"reservation":1}
,"reservation":{"protocol":1}
,"protocol":{"version":1,"=enabled":1}
,"rfc2205":{"rsvp":1}
,"=enabled":{"(refresh":1}
,"(refresh":{"timer)":1}
,"timer)":{"=30":1}
,"=30":{"seconds":1}
,"seconds":{"(keep":1}
,"(keep":{"multiplier)":1}
,"multiplier)":{"preemption":1}
,"preemption":{"=normal":1}
}
;Search.control.loadWordPairs(pairs);
