var pairs =
{
"efm_oam_remote_loopback_get":{"function":1,"(struct":1}
,"function":{"gets":1,"syntax":1,"succeeds":1}
,"gets":{"remote":1}
,"remote":{"loopback":1}
,"loopback":{"setting":1}
,"setting":{"smi":1}
,"smi":{"calls":1}
,"calls":{"function":1}
,"syntax":{"include":1}
,"include":{"onmd\u002Fsmi\u002Fsmi_onm_server.h":1}
,"onmd\u002Fsmi\u002Fsmi_onm_server.h":{"s_int32_t":1}
,"s_int32_t":{"efm_oam_remote_loopback_get":1}
,"(struct":{"interface":1}
,"interface":{"*ifp":1,"structure":1,"found":1,"efm_oam_err_internal":1}
,"*ifp":{"u_int8_t":1}
,"u_int8_t":{"*enable)":1}
,"*enable)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"enable":1}
,"ifp":{"pointer":1}
,"pointer":{"interface":1}
,"structure":{"output":1}
,"output":{"parameters":1}
,"enable":{"whether":1}
,"whether":{"remote-loopback":1}
,"remote-loopback":{"support":1}
,"support":{"enabled":1}
,"enabled":{"(1)":1,"interface":1}
,"(1)":{"disabled":1}
,"disabled":{"(0)":1}
,"(0)":{"return":1}
,"return":{"values":1}
,"values":{"efm_oam_err_if_not_found":1}
,"efm_oam_err_if_not_found":{"onmd":1}
,"onmd":{"interface":1}
,"found":{"efm_oam_err_not_enabled":1}
,"efm_oam_err_not_enabled":{"efm":1}
,"efm":{"enabled":1}
,"efm_oam_err_internal":{"internal":1}
,"internal":{"error":1}
,"error":{"efm_success":1}
,"efm_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
