var pairs =
{
"isis_if_tag_unset":{"call":1,"(u_int32_t":1}
,"call":{"unsets":1,"successful":1}
,"unsets":{"priority":1}
,"priority":{"tag":1}
,"tag":{"syntax":1}
,"syntax":{"int":1}
,"int":{"isis_if_tag_unset":1,"level)":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1,"*name":1}
,"char":{"*name":1}
,"*name":{"int":1,"interface":1}
,"level)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1,"configured":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"interface":{"name":1,"parameters":1}
,"name":{"level":1}
,"level":{"is-is":1,"level-1":1}
,"is-is":{"instance":1}
,"instance":{"level":1}
,"level-1":{"level-2":1}
,"level-2":{"level-1-2":1}
,"level-1-2":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"isis_api_set_err_vr_not_exist":1}
,"isis_api_set_err_vr_not_exist":{"exist":1}
,"exist":{"isis_api_set_err_invalid_is_type":1}
,"isis_api_set_err_invalid_is_type":{"non-valid":1}
,"non-valid":{"type":1}
,"type":{"isis_api_set_err_if_param_not_configured":1}
,"isis_api_set_err_if_param_not_configured":{"interface":1}
,"configured":{"isis_api_set_success":1}
,"isis_api_set_success":{"call":1}
}
;Search.control.loadWordPairs(pairs);
