var pairs =
{
"show":{"ethernet":1}
,"ethernet":{"cfm":1}
,"cfm":{"mep":1,"maintenance-points":1}
,"mep":{"command":1,"information":1,"mepid":1,"host":1,"<1-8191>":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"cfm":1}
,"information":{"command":1}
,"syntax":{"show":1}
,"mepid":{"domain":1,"specify":1}
,"domain":{"domain_name":1,"name":1,"domain":1,"specify":1,"mpid":1}
,"domain_name":{"(vid":1,"specify":1}
,"(vid":{"vid":1}
,"vid":{"(bridge":1,"specify":1}
,"(bridge":{"<1-32>":1}
,"<1-32>":{"parameters":1,"specify":1}
,"parameters":{"mep":1}
,"host":{"mep":1}
,"specify":{"host":1,"maintenance":1,"vlan":1,"bridge":1}
,"<1-8191>":{"domain":1}
,"name":{"maintenance":1,"domain_name":1,"vid":1}
,"maintenance":{"domain":1}
,"vlan":{"vid":1,"<2-4094>":1}
,"<2-4094>":{"bridge":1}
,"bridge":{"specify":1,"<1-32>":1,"command":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"show":1}
,"maintenance-points":{"remote":1}
,"remote":{"domain":1}
,"mpid":{"bridge":1}
}
;Search.control.loadWordPairs(pairs);
