var pairs =
{
"terminology":{"following":1}
,"following":{"brief":1}
,"brief":{"description":1}
,"description":{"terms":1}
,"terms":{"concepts":1}
,"concepts":{"used":1}
,"used":{"describe":1}
,"describe":{"pim-dm":1}
,"pim-dm":{"protocol":1,"routers":1,"periodic":1,"notifies":1,"expend":1}
,"protocol":{"reverse":1}
,"reverse":{"path":1}
,"path":{"forwarding":1,"network":1,"multicast":1}
,"forwarding":{"reverse":1,"(rpf)":1,"multicast":1}
,"(rpf)":{"optimized":1}
,"optimized":{"form":1}
,"form":{"flooding":1}
,"flooding":{"router":1}
,"router":{"accepts":1,"order":1,"performs":1,"member":1,"reachability":1}
,"accepts":{"packet":1}
,"packet":{"sourcea":1,"arrives":1,"neighbor":1,"once":1,"transmitted":1,"traffic":1}
,"sourcea":{"interface":1,"determines":1}
,"interface":{"if1":1,"router":1,"correct":1,"shortest":1,"sent":1,"group":1}
,"if1":{"if1":1,"interface":1,"forwarded":1}
,"order":{"reach":1}
,"reach":{"sourcea":1}
,"determines":{"whether":1,"shortest":1}
,"whether":{"interface":1}
,"correct":{"consulting":1,"interface":1}
,"consulting":{"unicast":1}
,"unicast":{"routing":1}
,"routing":{"tables":1,"table":1}
,"tables":{"packet":1}
,"arrives":{"interface":1,"correct":1}
,"forwarded":{"routing":1}
,"table":{"lists":1,"determines":1}
,"lists":{"interface":1}
,"shortest":{"path":1}
,"network":{"router\u0027s":1}
,"router\u0027s":{"unicast":1}
,"multicast":{"packets":1,"traffic":1,"group":1}
,"packets":{"router":1,"pim-dm":1}
,"neighbor":{"floods":1}
,"floods":{"packet":1}
,"once":{"meaning":1,"direction":1}
,"meaning":{"(assuming":1}
,"(assuming":{"point-to-point":1}
,"point-to-point":{"links)":1}
,"links)":{"packet":1}
,"transmitted":{"link":1}
,"link":{"once":1}
,"direction":{"forwarding":1}
,"routers":{"forward":1}
,"forward":{"multicast":1}
,"traffic":{"interfaces":1,"arrives":1,"traffic":1,"going":1,"anything":1}
,"interfaces":{"lead":1}
,"lead":{"receivers":1,"downstream":1}
,"receivers":{"explicitly":1,"downstream":1}
,"explicitly":{"joined":1}
,"joined":{"multicast":1}
,"group":{"messages":1,"address":1,"upstream":1,"nexthop":1}
,"messages":{"sent":1}
,"sent":{"group":1,"outgoing":1}
,"address":{"local":1}
,"local":{"subnetwork":1}
,"subnetwork":{"router":1}
,"performs":{"rpf":1}
,"rpf":{"check":1}
,"check":{"forwards":1,"router":1}
,"forwards":{"packet":1}
,"outgoing":{"interfaces":1}
,"downstream":{"receivers":1,"router":1,"downstream":1,"traffic":1}
,"member":{"group":1}
,"upstream":{"upstream":1,"traffic":1,"interface":1}
,"going":{"towards":1}
,"towards":{"source":1}
,"source":{"downstream":1}
,"anything":{"upstream":1}
,"nexthop":{"pim-dm":1,"lookup":1,"available":1,"becomes":1}
,"periodic":{"lookups":1,"lookup":1}
,"lookups":{"prefixes":1,"nsm":1}
,"prefixes":{"check":1,"pertain":1}
,"reachability":{"nexthop":1}
,"lookup":{"mechanism":1,"during":1}
,"mechanism":{"avoids":1}
,"avoids":{"periodic":1}
,"during":{"start-up":1}
,"start-up":{"pim-dm":1}
,"notifies":{"nsm":1,"protocols":1}
,"nsm":{"(network":1,"notifies":1,"proactive":1}
,"(network":{"services":1}
,"services":{"manager)":1}
,"manager)":{"prefixes":1}
,"pertain":{"nsm":1}
,"protocols":{"better":1}
,"better":{"nexthop":1}
,"available":{"nexthop":1}
,"becomes":{"unavailable":1}
,"unavailable":{"pim-dm":1}
,"expend":{"resources":1}
,"resources":{"periodic":1}
,"proactive":{"maintenance":1}
}
;Search.control.loadWordPairs(pairs);
