var pairs =
{
"nsm":{"services":1,"lib\u002Fnsm_message.h":1,"nsm_service_qos_preempt":1}
,"services":{"following":1,"defined":1}
,"following":{"services":1}
,"defined":{"nsm":1}
,"lib\u002Fnsm_message.h":{"service":1}
,"service":{"identifier":1}
,"identifier":{"interface":1,"node":1,"service_global_id_node_id":1}
,"interface":{"nsm_service_interface":1}
,"nsm_service_interface":{"router":1}
,"router":{"nsm_service_route":1,"nsm_service_router_id":1,"nsm_service_user":1}
,"nsm_service_route":{"router":1}
,"nsm_service_router_id":{"virtual":1}
,"virtual":{"routing":1,"router":1}
,"routing":{"forwarding":1}
,"forwarding":{"nsm_service_vrf":1}
,"nsm_service_vrf":{"route":1}
,"route":{"lookup":1}
,"lookup":{"nsm_service_route_lookup":1}
,"nsm_service_route_lookup":{"label":1}
,"label":{"pool":1}
,"pool":{"nsm_service_label":1}
,"nsm_service_label":{"traffic":1}
,"traffic":{"engineering":1}
,"engineering":{"nsm_service_te":1,"link":1}
,"nsm_service_te":{"qos":1}
,"qos":{"nsm_service_qos":1,"preemption":1}
,"nsm_service_qos":{"qos":1}
,"preemption":{"nsm":1}
,"nsm_service_qos_preempt":{"user":1}
,"user":{"management":1}
,"management":{"virtual":1}
,"nsm_service_user":{"hostname":1}
,"hostname":{"(obsolete)":1}
,"(obsolete)":{"nsm_service_hostname":1}
,"nsm_service_hostname":{"mpls":1}
,"mpls":{"nsm_service_mpls_vc":1,"nsm_service_mpls":1}
,"nsm_service_mpls_vc":{"mpls":1}
,"nsm_service_mpls":{"gmpls":1}
,"gmpls":{"nsm_service_gmpls":1}
,"nsm_service_gmpls":{"diffserv":1}
,"diffserv":{"nsm_service_diffserv":1}
,"nsm_service_diffserv":{"vpls":1}
,"vpls":{"nsm_service_vpls":1}
,"nsm_service_vpls":{"ds-te":1}
,"ds-te":{"nsm_service_dste":1}
,"nsm_service_dste":{"ipv4":1}
,"ipv4":{"multicast":1,"pim":1}
,"multicast":{"rib":1,"tunnel":1}
,"rib":{"nsm_service_ipv4_mrib":1,"nsm_service_ipv6_mrib":1}
,"nsm_service_ipv4_mrib":{"ipv4":1}
,"pim":{"nsm_service_ipv4_pim":1,"nsm_service_ipv6_pim":1}
,"nsm_service_ipv4_pim":{"ipv4":1}
,"tunnel":{"nsm_service_ipv4_mcast_tunnel":1}
,"nsm_service_ipv4_mcast_tunnel":{"ipv6":1}
,"ipv6":{"multicast":1,"pim":1}
,"nsm_service_ipv6_mrib":{"ipv6":1}
,"nsm_service_ipv6_pim":{"bridge":1}
,"bridge":{"nsm_service_bridge":1}
,"nsm_service_bridge":{"vlan":1}
,"vlan":{"nsm_service_vlan":1}
,"nsm_service_vlan":{"interior":1}
,"interior":{"gateway":1}
,"gateway":{"protocol":1}
,"protocol":{"shortcut":1}
,"shortcut":{"nsm_service_igp_shortcut":1}
,"nsm_service_igp_shortcut":{"control":1}
,"control":{"adjacency":1,"channel":1}
,"adjacency":{"nsm_service_control_adj":1}
,"nsm_service_control_adj":{"control":1}
,"channel":{"nsm_service_control_channel":1}
,"nsm_service_control_channel":{"traffic":1}
,"link":{"nsm_service_te_link":1,"nsm_service_data_link":1,"subset":1}
,"nsm_service_te_link":{"data":1}
,"data":{"link":1}
,"nsm_service_data_link":{"data":1}
,"subset":{"nsm_service_data_link_sub":1}
,"nsm_service_data_link_sub":{"global":1}
,"global":{"identifier":1}
,"node":{"identifier":1}
,"service_global_id_node_id":{"range":1}
,"range":{"limit":1}
,"limit":{"nsm_service_max":1}
}
;Search.control.loadWordPairs(pairs);
