var pairs =
{
"pal_sock_get_bindtofib":{"function":1,"(pal_sock_handle_t":1}
,"function":{"gets":1,"succeeds":1}
,"gets":{"fib":1}
,"fib":{"associated":1,"fib":1,"identifier":1}
,"associated":{"given":1}
,"given":{"socket":1}
,"socket":{"file":1}
,"file":{"descriptor":1}
,"descriptor":{"syntax":1,"output":1}
,"syntax":{"result_t":1}
,"result_t":{"pal_sock_get_bindtofib":1}
,"(pal_sock_handle_t":{"sock":1}
,"sock":{"fib_id_t":1,"socket":1}
,"fib_id_t":{"*fib)":1}
,"*fib)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"sock":1,"fib":1}
,"output":{"parameters":1}
,"identifier":{"return":1}
,"return":{"value":1}
,"value":{"result_ok":1}
,"result_ok":{"function":1}
,"succeeds":{"result_error":1}
,"result_error":{"generic":1}
,"generic":{"error":1}
,"error":{"occurs":1}
}
;Search.control.loadWordPairs(pairs);
