var pairs =
{
"include":{"file":1}
,"file":{"mld.h":1,"required":1}
,"mld.h":{"file":1}
,"required":{"included":1}
,"included":{"*.c":1}
,"*.c":{"files":1}
,"files":{"outside":1}
,"outside":{"lib\u002Fmld\u002Fdirectory":1}
,"lib\u002Fmld\u002Fdirectory":{"mld-related":1}
,"mld-related":{"functionality":1}
,"functionality":{"referenced":1}
,"referenced":{"function":1}
,"function":{"declaration":1}
,"declaration":{"following":1}
,"following":{"apis":1}
,"apis":{"made":1}
,"made":{"available":1}
,"available":{"including":1}
,"including":{"mld.h":1}
}
;Search.control.loadWordPairs(pairs);
