var pairs =
{
"neighbor":{"version":1,"parameter":1,"command":1,"(a.b.c.d":1,"ipv4":1,"ipv6":1,"peer-group":1,"remote-as":1,"10.10.10.10":1}
,"version":{"command":1,"default":1,"request":1,"using":1,"neighbor":1,"level":1,"(4)":1,"parameters":1,"number":1,"(config)":1}
,"command":{"configure":1,"disables":1,"default":1,"syntax":1,"command":1,"applies":1,"mode":1}
,"configure":{"zebos-xp":1,"terminal":1}
,"zebos-xp":{"accept":1}
,"accept":{"particular":1}
,"particular":{"bgp":1}
,"bgp":{"version":1,"neighbor":1,"peer":1,"(config-router)":1}
,"default":{"system":1,"version":1}
,"system":{"uses":1}
,"uses":{"bgp":1}
,"request":{"dynamically":1}
,"dynamically":{"negotiates":1}
,"negotiates":{"down":1}
,"down":{"version":1}
,"using":{"command":1}
,"disables":{"router\u2019s":1}
,"router\u2019s":{"version-negotiation":1}
,"version-negotiation":{"capability":1}
,"capability":{"forces":1}
,"forces":{"router":1}
,"router":{"specified":1,"mode":1,"bgp":1}
,"specified":{"version":1}
,"parameter":{"command":1,"used":1}
,"level":{"neighbor":1}
,"syntax":{"neighbor":1}
,"(a.b.c.d":{"x:x":1}
,"x:x":{":x:x":1}
,":x:x":{"word)":1,"address":1}
,"word)":{"version":1}
,"(4)":{"neighbor":1}
,"parameters":{"a.b.c.d":1}
,"a.b.c.d":{"address":1}
,"address":{"bgp":1}
,"ipv4":{"format":1}
,"format":{"x:x":1,"word":1}
,"ipv6":{"format":1}
,"word":{"name":1}
,"name":{"bgp":1}
,"peer":{"group":1,"groups":1}
,"group":{"information":1,"bgp":1}
,"information":{"create":1}
,"create":{"peer":1}
,"groups":{"refer":1}
,"refer":{"neighbor":1}
,"peer-group":{"neighbor":1}
,"remote-as":{"commands":1}
,"commands":{"parameter":1}
,"used":{"command":1}
,"applies":{"peers":1}
,"peers":{"group":1}
,"number":{"command":1}
,"mode":{"router":1,"examples":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"(config-router)":{"neighbor":1}
,"10.10.10.10":{"version":1}
}
;Search.control.loadWordPairs(pairs);
