var pairs =
{
"customer":{"edge":1}
,"edge":{"configure":1}
,"configure":{"terminal":1,"mode":1,"bridge":1,"eth1":1,"abc":1,"remote":1,"local":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"vlan":1,"interface":1,"cfm":1}
,"mode":{"(config)":1,"(config-vlan)":1,"(config-if)":1,"hybrid":1,"create":1,"configure":1}
,"(config)":{"bridge":1,"vlan":1,"interface":1,"ethernet":1}
,"bridge":{"protocol":1,"mstp":1,"(config)":1,"name":1,"(config-vlan)":1,"state":1,"group":1,"enter":1}
,"protocol":{"mstp":1}
,"mstp":{"configure":1,"bridge":1}
,"vlan":{"database":1,"configure":1,"bridge":1,"add":1,"interface":1,"mip-creation":1,"(config-ether-cfm)":1,"mac":1,"local-vid":1,"(config-if-eth-cfm-mep)":1}
,"database":{"enter":1}
,"(config-vlan)":{"vlan":1,"exit":1}
,"name":{"abc":1,"test":1}
,"abc":{"create":1,"vlan":1}
,"create":{"vlan":1,"level":1}
,"state":{"enable":1}
,"enable":{"enable":1,"vlan":1,"allow":1,"unicast":1}
,"exit":{"exit":1,"vlan":1,"interface":1,"ether":1,"cfm":1}
,"interface":{"eth1":1,"mode":1,"hybrid":1,"(config-ether-cfm)":1}
,"eth1":{"enter":1,"layer":1,"bridge":1,"(config-if)":1}
,"(config-if)":{"switchport":1,"bridge-group":1,"exit":1,"ethernet":1}
,"switchport":{"configure":1,"mode":1,"hybrid":1}
,"layer":{"port":1}
,"port":{"(config-if)":1}
,"bridge-group":{"configure":1}
,"group":{"(config-if)":1}
,"hybrid":{"interface":1,"(config-if)":1,"allowed":1}
,"allowed":{"vlan":1}
,"add":{"egress-tagged":1}
,"egress-tagged":{"enable":1}
,"allow":{"vlan":1}
,"ethernet":{"cfm":1}
,"cfm":{"domain-name":1,"mode":1,"mep":1}
,"domain-name":{"type":1}
,"type":{"character-string":1}
,"character-string":{"name":1}
,"test":{"level":1,"vlan":1}
,"level":{"mip-creation":1,"domain":1}
,"mip-creation":{"default":1}
,"default":{"bridge":1,"configure":1}
,"domain":{"(config-ether-cfm)":1,"test":1}
,"(config-ether-cfm)":{"service":1,"mep":1,"exit":1}
,"service":{"ma-type":1}
,"ma-type":{"string":1}
,"string":{"ma-name":1}
,"ma-name":{"abc":1}
,"mep":{"crosscheck":1,"interface":1,"down":1,"mode":1,"vlan":1,"remote":1,"(config-if-eth-cfm-mep)":1}
,"crosscheck":{"mpid":1}
,"mpid":{"vlan":1,"active":1}
,"mac":{"000f.1f48.6269":1,"address":1}
,"000f.1f48.6269":{"configure":1}
,"remote":{"mepid":1,"mep":1}
,"mepid":{"mac":1}
,"address":{"remote":1}
,"ether":{"cfm":1}
,"down":{"mpid":1}
,"active":{"true":1}
,"true":{"domain":1}
,"local-vid":{"bridge":1}
,"local":{"mep":1}
,"(config-if-eth-cfm-mep)":{"unicast":1,"exit":1}
,"unicast":{"rmpid":1,"ccm":1}
,"rmpid":{"state":1}
,"ccm":{"messages":1}
,"messages":{"local":1}
}
;Search.control.loadWordPairs(pairs);
