var pairs =
{
"inter-area":{"lsp":1}
,"lsp":{"features":1,"via":1}
,"features":{"rfc":1}
,"rfc":{"5238":1}
,"5238":{"defines":1}
,"defines":{"extensions":1}
,"extensions":{"ldp":1}
,"ldp":{"support":1,"requires":1,"supports":1}
,"support":{"inter-area":1}
,"via":{"label-matching":1}
,"label-matching":{"procedure":1,"message":1}
,"procedure":{"lsr":1,"ldp":1,"allows":1}
,"lsr":{"receives":1,"determines":1,"identifies":1,"withdraws":1}
,"receives":{"label-matching":1}
,"message":{"neighbor":1,"sent":1}
,"neighbor":{"uses":1,"used":1}
,"uses":{"label":1}
,"label":{"mpls":1,"messaging":1,"mapping":1,"mappings":1,"withdraw":1}
,"mpls":{"forwarding":1}
,"forwarding":{"routing":1}
,"routing":{"table":1}
,"table":{"contains":1}
,"contains":{"longest":1,"matching":1}
,"longest":{"match":1}
,"match":{"fec":1,"zebos-xp":1,"lookup":1,"longest":1,"match":1,"new":1,"existing":1,"different":1,"updates":1,"rib":1,"found":1}
,"fec":{"differs":1,"label":1,"elements":1}
,"differs":{"original":1}
,"original":{"label-matching":1}
,"requires":{"exact":1}
,"exact":{"match":1}
,"zebos-xp":{"ldp":1}
,"supports":{"procedures":1}
,"procedures":{"ipv4":1}
,"ipv4":{"ipv6":1}
,"ipv6":{"label":1}
,"messaging":{"label":1}
,"mapping":{"newer":1,"received":1,"messages":1}
,"newer":{"label-mapping":1}
,"label-mapping":{"procedure":1,"messages":1}
,"allows":{"multiple":1}
,"multiple":{"fecs":1}
,"fecs":{"associated":1,"new":1,"originally":1}
,"associated":{"single":1}
,"single":{"rib":1}
,"rib":{"element":1,"prefix":1,"lsr":1}
,"element":{"single":1}
,"prefix":{"change":1,"arrives":1,"better":1,"removed":1,"best":1,"time":1}
,"change":{"propagate":1}
,"propagate":{"label-mapping":1}
,"messages":{"label-withdraw":1,"fec":1,"sent":1,"peers":1}
,"label-withdraw":{"messages":1}
,"received":{"neighbor":1}
,"used":{"mpls":1}
,"matching":{"entry":1}
,"entry":{"longest":1}
,"lookup":{"performed":1,"result":1}
,"performed":{"lookup":1}
,"result":{"may":1}
,"may":{"exact":1}
,"new":{"prefix":1,"label":1,"best":1}
,"arrives":{"rib":1}
,"determines":{"whether":1}
,"whether":{"better":1}
,"better":{"match":1}
,"existing":{"fecs":1}
,"different":{"next":1}
,"next":{"hop":1}
,"hop":{"old":1}
,"old":{"labels":1}
,"labels":{"withdrawn":1,"sends":1}
,"withdrawn":{"new":1}
,"mappings":{"messages":1}
,"sent":{"peers":1,"upstream":1}
,"peers":{"fecs":1,"new":1}
,"originally":{"advertised":1}
,"advertised":{"prefix":1}
,"removed":{"rib":1}
,"identifies":{"fec":1}
,"elements":{"using":1}
,"using":{"rib":1}
,"best":{"match":1}
,"updates":{"new":1}
,"time":{"lsr":1}
,"withdraws":{"old":1}
,"sends":{"new":1}
,"found":{"label":1}
,"withdraw":{"message":1}
,"upstream":{"peers":1}
}
;Search.control.loadWordPairs(pairs);
