var pairs =
{
"adress":{"family":1}
,"family":{"flags":1,"(af)":1}
,"flags":{"following":1,"used":1}
,"following":{"table":1}
,"table":{"lists":1}
,"lists":{"address":1}
,"address":{"family":1}
,"(af)":{"configuration":1}
,"configuration":{"flags":1}
,"used":{"external":1}
,"external":{"bgp":1}
,"bgp":{"functions":1}
,"functions":{"flag":1}
,"flag":{"description":1}
,"description":{"peer_flag_send_community":1}
,"peer_flag_send_community":{"send-community":1}
,"send-community":{"peer_flag_send_ext_community":1,"ext":1}
,"peer_flag_send_ext_community":{"send-community":1}
,"ext":{"peer_flag_nexthop_self":1}
,"peer_flag_nexthop_self":{"next-hop-self":1}
,"next-hop-self":{"peer_flag_reflector_client":1}
,"peer_flag_reflector_client":{"reflector-client":1}
,"reflector-client":{"peer_flag_rserver_client":1}
,"peer_flag_rserver_client":{"route-server-client":1}
,"route-server-client":{"peer_flag_soft_reconfig":1}
,"peer_flag_soft_reconfig":{"soft-reconfiguration":1}
,"soft-reconfiguration":{"peer_flag_as_path_unchanged":1}
,"peer_flag_as_path_unchanged":{"transparent-as":1}
,"transparent-as":{"peer_flag_nexthop_unchanged":1}
,"peer_flag_nexthop_unchanged":{"transparent-next-hop":1}
,"transparent-next-hop":{"peer_flag_med_unchanged":1}
,"peer_flag_med_unchanged":{"transparent-med":1}
,"transparent-med":{"peer_flag_default_originate":1}
,"peer_flag_default_originate":{"default-originate":1}
,"default-originate":{"peer_flag_remove_private_as":1}
,"peer_flag_remove_private_as":{"remove-private-as":1}
,"remove-private-as":{"peer_flag_allowas_in":1}
,"peer_flag_allowas_in":{"allowas-in":1}
,"allowas-in":{"peer_flag_orf_prefix_sm":1}
,"peer_flag_orf_prefix_sm":{"orf":1}
,"orf":{"capability":1}
,"capability":{"send-mode":1,"receive-mode":1}
,"send-mode":{"peer_flag_orf_prefix_rm":1}
,"peer_flag_orf_prefix_rm":{"orf":1}
,"receive-mode":{"peer_flag_max_prefix_warning":1}
,"peer_flag_max_prefix_warning":{"maximum":1}
,"maximum":{"prefix":1}
,"prefix":{"warning-only":1}
,"warning-only":{"peer_flag_as_override":1}
,"peer_flag_as_override":{"override":1}
,"override":{"peer_flag_site_origin":1}
,"peer_flag_site_origin":{"site-origin":1}
,"site-origin":{"peer_flag_grst_capability":1}
,"peer_flag_grst_capability":{"graceful-restart":1}
,"graceful-restart":{"peer_flag_ebgp_vpn_allow":1}
,"peer_flag_ebgp_vpn_allow":{"allow":1}
,"allow":{"ebgp":1}
,"ebgp":{"vpn":1}
}
;Search.control.loadWordPairs(pairs);
