var pairs =
{
"validation":{"enter":1}
,"enter":{"commands":1}
,"commands":{"listed":1}
,"listed":{"section":1}
,"section":{"confirm":1}
,"confirm":{"previous":1}
,"previous":{"configurations":1}
,"configurations":{"show":1}
,"show":{"running-config":1}
,"running-config":{"service":1}
,"service":{"password-encryption":1}
,"password-encryption":{"hostname":1}
,"hostname":{"rtr1":1}
,"rtr1":{"multicast-routing":1}
,"multicast-routing":{"interface":1}
,"interface":{"eth2":1}
,"eth2":{"address":1}
,"address":{"192.168.10.57\u002F24":1}
,"192.168.10.57\u002F24":{"shutdown":1}
,"shutdown":{"ospf":1}
,"ospf":{"cost":1}
,"cost":{"igmp":1}
,"igmp":{"version":1}
,"version":{"pim":1}
,"pim":{"sparse-mode":1}
}
;Search.control.loadWordPairs(pairs);
