var pairs =
{
"rsvp_api_interface_disable":{"call":1,"(struct":1}
,"call":{"disables":1}
,"disables":{"rsvp":1}
,"rsvp":{"interface":1}
,"interface":{"syntax":1,"if_down":1,"administratively":1}
,"syntax":{"void":1}
,"void":{"rsvp_api_interface_disable":1}
,"(struct":{"rsvp_interface":1}
,"rsvp_interface":{"*rsvpif":1}
,"*rsvpif":{"u_char":1}
,"u_char":{"if_down)":1}
,"if_down)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"rsvpif":1,"none":1}
,"rsvpif":{"rsvp":1}
,"if_down":{"indicates":1}
,"indicates":{"interface":1}
,"administratively":{"shut":1}
,"shut":{"down":1}
,"down":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"none":1}
}
;Search.control.loadWordPairs(pairs);
