var pairs =
{
"bgp4":{"commands":1,"configuration":1}
,"commands":{"chapter":1,"address-family":1}
,"chapter":{"describes":1,"bgp":1}
,"describes":{"bgp4":1}
,"configuration":{"commands":1}
,"address-family":{"ipv6":1,"chapter":1}
,"ipv6":{"(see":1,"(a.b.c.d":1,"<1-4294967295>":1,"external":1,"peer-group":1,"unicast":1,"bgp":1}
,"(see":{"address-family":1,"bgp":1,"neighbor":1,"redistribute":1}
,"bgp":{"commands)":1,"g-shut":1,"*ipv6":1,"ipv6":1,"*vrf":1,"x:x":1}
,"commands)":{"aggregate-address":1,"clear":1,"neighbor":1,"network":1}
,"aggregate-address":{"x:x":1}
,"x:x":{":x:x\u002Fm":1,":x:x)":1,":x:x":1}
,":x:x\u002Fm":{"bgp":1}
,"g-shut":{"(see":1,"chapter":1}
,"clear":{"bgp":1,"bpg":1,"ipv6":1}
,"*ipv6":{"clear":1}
,"(a.b.c.d":{"x:x":1}
,":x:x)":{"clear":1}
,"<1-4294967295>":{"clear":1}
,"external":{"clear":1}
,"peer-group":{"clear":1,"(see":1,"chapter":1}
,"unicast":{"dampening":1,"flap-statistics":1,"table-map":1}
,"dampening":{"clear":1}
,"flap-statistics":{"clear":1}
,"bpg":{"ipv6":1}
,"table-map":{"clear":1}
,"*vrf":{"clear":1}
,":x:x":{"vrf":1,"redistribute":1}
,"vrf":{"neighbor":1}
,"neighbor":{"activate":1,"attribute-unchanged":1,"capability":1,"default-originate":1,"distribute-list":1,"filter-list":1,"maximum-prefix":1,"next-hop-self":1,"peer-group":1,"prefix-list":1,"remove-private-as":1,"route-map":1,"route-reflector-client":1,"send-community":1,"soft-reconfiguration":1,"unsuppress-map":1}
,"activate":{"(see":1,"chapter":1}
,"attribute-unchanged":{"(see":1,"chapter":1}
,"capability":{"dynamic":1,"route-refresh":1}
,"dynamic":{"(see":1,"chapter":1}
,"route-refresh":{"(see":1,"chapter":1}
,"default-originate":{"(see":1,"chapter":1}
,"distribute-list":{"(see":1,"chapter":1}
,"filter-list":{"(see":1,"chapter":1}
,"maximum-prefix":{"(see":1,"chapter":1}
,"next-hop-self":{"(see":1,"chapter":1}
,"prefix-list":{"(see":1,"chapter":1}
,"remove-private-as":{"(see":1,"chapter":1}
,"route-map":{"(see":1,"chapter":1}
,"route-reflector-client":{"(see":1,"chapter":1}
,"send-community":{"(see":1,"chapter":1}
,"soft-reconfiguration":{"inbound":1}
,"inbound":{"(see":1,"chapter":1}
,"unsuppress-map":{"(see":1,"chapter":1}
,"network":{"x:x":1}
,"redistribute":{"(see":1,"chapter":1}
}
;Search.control.loadWordPairs(pairs);
