var pairs =
{
"lldp_tx_sm":{"structure":1,"define":1}
,"structure":{"onmd\u002Flldpv2\u002Flldpd.h":1}
,"onmd\u002Flldpv2\u002Flldpd.h":{"used":1}
,"used":{"implement":1}
,"implement":{"state":1}
,"state":{"machine":1,"bool_t":1}
,"machine":{"struct":1}
,"struct":{"lldp_tx_sm":1,"thread":1}
,"define":{"lldp_msg_fast_tx_default":1,"lldp_msg_tx_hold_default":1,"lldp_msg_tx_interval_default":1,"lldp_reinit_delay_default":1,"lldp_tx_credit_max_default":1,"lldp_tx_fast_init_default":1}
,"lldp_msg_fast_tx_default":{"u_int16_t":1}
,"u_int16_t":{"msg_fast_tx":1,"msg_tx_hold":1,"tx_credit_max":1,"tx_fast_init":1,"tx_ttl":1}
,"msg_fast_tx":{"define":1}
,"lldp_msg_tx_hold_default":{"u_int16_t":1}
,"msg_tx_hold":{"define":1}
,"lldp_msg_tx_interval_default":{"u_int32_t":1}
,"u_int32_t":{"msg_tx_interval":1,"reinit_delay":1,"tx_credit":1,"tx_fast":1,"length_errors_total":1}
,"msg_tx_interval":{"define":1}
,"lldp_reinit_delay_default":{"u_int32_t":1}
,"reinit_delay":{"define":1}
,"lldp_tx_credit_max_default":{"u_int16_t":1}
,"tx_credit_max":{"define":1}
,"lldp_tx_fast_init_default":{"u_int16_t":1}
,"tx_fast_init":{"u_int32_t":1}
,"tx_credit":{"u_int32_t":1}
,"tx_fast":{"u_int8_t":1}
,"u_int8_t":{"state":1}
,"bool_t":{"tx_now":1,"tx_tick":1,"local_change":1}
,"tx_now":{"bool_t":1}
,"tx_tick":{"bool_t":1}
,"local_change":{"u_int16_t":1}
,"tx_ttl":{"\u002F*timer":1}
,"\u002F*timer":{"variables":1}
,"variables":{"*\u002Fstruct":1}
,"*\u002Fstruct":{"thread":1}
,"thread":{"*tx_ttr_t":1,"*tx_shutdown_while_t":1,"*tx_one_sec_timer_t":1}
,"*tx_ttr_t":{"struct":1}
,"*tx_shutdown_while_t":{"struct":1}
,"*tx_one_sec_timer_t":{"\u002F*statistical":1}
,"\u002F*statistical":{"counters*\u002Fu_int32_t":1}
,"counters*\u002Fu_int32_t":{"frames_out_total":1}
,"frames_out_total":{"u_int32_t":1}
}
;Search.control.loadWordPairs(pairs);
