var pairs =
{
"isis_get_next_sys_stat_spf_runs":{"call":1}
,"call":{"gets":1}
,"gets":{"number":1}
,"number":{"times":1}
,"times":{"ran":1,"spf":1}
,"ran":{"spf":1,"next":1}
,"spf":{"next":1,"ran":1}
,"next":{"level":1}
,"level":{"syntax":1,"u_int32_t":1,"is-is":1,"index":1,"level":1,"output":1,"return":1}
,"syntax":{"int":1}
,"int":{"isis_get_sys_stat_spf_runs":1}
,"isis_get_sys_stat_spf_runs":{"(u_int32_t":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1,"instance":1}
,"u_int32_t":{"instance":1,"level":1,"*ret)":1}
,"instance":{"u_int32_t":1,"is-is":1,"level":1,"isis_api_get_error":1}
,"*ret)":{"input":1}
,"input":{"parameter":1}
,"parameter":{"vr_id":1,"ret":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1,"isis_api_get_success":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"is-is":{"instance":1,"level":1}
,"index":{"level":1,"found":1}
,"output":{"parameter":1}
,"ret":{"number":1}
,"return":{"value":1}
,"isis_api_get_success":{"next":1}
,"found":{"specified":1}
,"specified":{"instance":1}
,"isis_api_get_error":{"next":1}
}
;Search.control.loadWordPairs(pairs);
