var pairs =
{
"trill_channel_frame_process_egress":{"function":1,"(struct":1}
,"function":{"processes":1,"further":1,"call":1}
,"processes":{"channel":1}
,"channel":{"frame":1,"data":1}
,"frame":{"intended":1,"received":1}
,"intended":{"itself":1}
,"itself":{"addition":1}
,"addition":{"checks":1}
,"checks":{"protocol":1}
,"protocol":{"type":1}
,"type":{"calls":1}
,"calls":{"appropriate":1}
,"appropriate":{"function":1}
,"further":{"processing":1}
,"processing":{"contained":1}
,"contained":{"file":1}
,"file":{"trill_oam.c":1}
,"trill_oam.c":{"syntax":1}
,"syntax":{"int":1}
,"int":{"trill_channel_frame_process_egress":1}
,"(struct":{"trill_channel_packet":1}
,"trill_channel_packet":{"*dpkt":1}
,"*dpkt":{"struct":1,"received":1}
,"struct":{"trill_interface":1}
,"trill_interface":{"*isi)":1}
,"*isi)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"*dpkt":1,"none":1}
,"received":{"channel":1,"output":1}
,"data":{"packet":1}
,"packet":{"*isi":1}
,"*isi":{"pointer":1}
,"pointer":{"interface":1}
,"interface":{"frame":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"indicates":1}
,"indicates":{"function":1}
,"call":{"executed":1}
,"executed":{"properly":1}
,"properly":{"trill_channel_fail":1}
,"trill_channel_fail":{"trill_channel_success":1}
}
;Search.control.loadWordPairs(pairs);
