var pairs =
{
"rbridge":{"commands":1,"(routing":1,"trill":1,"spf-interval-exp":1}
,"commands":{"chapter":1,"add":1}
,"chapter":{"provides":1}
,"provides":{"information":1}
,"information":{"rbridge":1}
,"(routing":{"bridge)":1}
,"bridge)":{"commands":1}
,"add":{"static":1}
,"static":{"fdb":1,"l2-unicast-trill-fdb":1,"multicast-fdb":1,"multicast-trill-fdb":1,"unicast-trill":1}
,"fdb":{"neighbor-nickname":1}
,"neighbor-nickname":{"add":1}
,"l2-unicast-trill-fdb":{"add":1}
,"multicast-fdb":{"d-tree":1}
,"d-tree":{"ingress-nickname":1,"neighbor-nickname":1}
,"ingress-nickname":{"add":1}
,"multicast-trill-fdb":{"ingress-d-tree":1,"multicast-listener":1}
,"ingress-d-tree":{"add":1}
,"multicast-listener":{"add":1}
,"unicast-trill":{"bridge":1}
,"bridge":{"confidence":1,"root-priority":1}
,"confidence":{"channel-protocol":1,"dtree-in-use":1}
,"channel-protocol":{"clear":1}
,"clear":{"rbridge":1}
,"trill":{"clear":1,"counter":1,"interface":1,"mac":1,"rbridge":1,"bridge":1}
,"counter":{"clear":1}
,"interface":{"counter":1}
,"mac":{"confidence":1}
,"dtree-in-use":{"dtree-nickname-to-compute":1}
,"dtree-nickname-to-compute":{"forward-delay":1}
,"forward-delay":{"ignore-lsp-errors":1}
,"ignore-lsp-errors":{"lsp-gen-interval":1}
,"lsp-gen-interval":{"lsp-refresh-interval":1}
,"lsp-refresh-interval":{"max-lsp-lifetime":1}
,"max-lsp-lifetime":{"max-nickname":1}
,"max-nickname":{"mcast-pruning":1}
,"mcast-pruning":{"mtu-probe":1}
,"mtu-probe":{"multipath":1}
,"multipath":{"nickname":1}
,"nickname":{"nickname-priority":1}
,"nickname-priority":{"number-of-dtrees-to-compute":1}
,"number-of-dtrees-to-compute":{"number-of-d-trees-to-use":1}
,"number-of-d-trees-to-use":{"number-of-mtu-probes":1}
,"number-of-mtu-probes":{"oam-protocol":1}
,"oam-protocol":{"rbridge-ping":1}
,"rbridge-ping":{"rbridge-ping":1,"count":1}
,"count":{"rbridge-ping":1,"ping-interval":1}
,"ping-interval":{"rbridge-ping":1,"timeout":1}
,"timeout":{"rbridge-ping-interval":1,"rbridge-mping":1}
,"rbridge-ping-interval":{"rbridge-ping-timeout":1}
,"rbridge-ping-timeout":{"rbridge-traceroute":1}
,"rbridge-traceroute":{"rbridge-traceroute":1,"timeout":1}
,"rbridge-mping":{"rbridge-mtraceroute":1}
,"rbridge-mtraceroute":{"rbridge":1}
,"root-priority":{"show":1}
,"show":{"running-config":1}
,"running-config":{"rbridge":1}
,"spf-interval-exp":{"systemid":1}
,"systemid":{"vlan-pruning":1}
}
;Search.control.loadWordPairs(pairs);
