var pairs =
{
"ethernet":{"specification":1,"transport":1,"standards":1,"uses":1,"100":1,"1000":1}
,"specification":{"lan":1}
,"lan":{"technology":1}
,"technology":{"layer":1}
,"layer":{"(l1)":1,"(l2)":1}
,"(l1)":{"layer":1}
,"(l2)":{"open":1}
,"open":{"systems":1}
,"systems":{"interconnection":1}
,"interconnection":{"(osi)":1}
,"(osi)":{"reference":1}
,"reference":{"model":1}
,"model":{"based":1}
,"based":{"packetized":1}
,"packetized":{"transmissions":1}
,"transmissions":{"physical":1}
,"physical":{"ports":1}
,"ports":{"variety":1}
,"variety":{"electrical":1}
,"electrical":{"optical":1}
,"optical":{"media":1}
,"media":{"ethernet":1}
,"transport":{"several":1}
,"several":{"upper-layer":1}
,"upper-layer":{"protocols":1}
,"protocols":{"popular":1}
,"popular":{"transmission":1}
,"transmission":{"control":1,"speeds":1}
,"control":{"protocol\u002Finternet":1}
,"protocol\u002Finternet":{"protocol":1}
,"protocol":{"(tcp\u002Fip)":1}
,"(tcp\u002Fip)":{"ethernet":1}
,"standards":{"maintained":1}
,"maintained":{"ieee":1}
,"ieee":{"802.3":1}
,"802.3":{"committee":1}
,"committee":{"ethernet":1}
,"uses":{"bus":1}
,"bus":{"topology":1}
,"topology":{"csma\u002Fcd":1}
,"csma\u002Fcd":{"(carrier":1}
,"(carrier":{"sense":1}
,"sense":{"multiple":1}
,"multiple":{"access\u002Fcollision":1}
,"access\u002Fcollision":{"detection)":1}
,"detection)":{"resolve":1}
,"resolve":{"contention":1}
,"contention":{"two":1}
,"two":{"devices":1}
,"devices":{"try":1}
,"try":{"access":1}
,"access":{"network":1}
,"network":{"exactly":1}
,"exactly":{"time":1}
,"time":{"transmission":1}
,"speeds":{"range":1}
,"range":{"mbps":1}
,"mbps":{"fast":1,"gigabit":1}
,"fast":{"ethernet":1}
,"100":{"mbps":1}
,"gigabit":{"ethernet":1}
,"1000":{"mbps":1}
}
;Search.control.loadWordPairs(pairs);
