var pairs =
{
"area":{"stub":1,"routers":1,"router":1,"configure":1,"using":1,"command":1,"border":1,"area":1,"normal":1,"(a.b.c.d":1,"ipv4":1,"decimal":1,"default":1,"defined":1}
,"stub":{"command":1,"area":1,"commands":1,"option":1,"no-summary":1}
,"command":{"define":1,"area":1,"form":1,"syntax":1,"mode":1}
,"define":{"area":1}
,"routers":{"two":1,"attached":1}
,"two":{"stub":1}
,"router":{"configuration":1,"(abr)":1,"mode":1,"ipv6":1}
,"configuration":{"commands":1}
,"commands":{"stub":1,"routers":1}
,"attached":{"stub":1}
,"configure":{"area":1,"terminal":1}
,"using":{"stub":1}
,"option":{"area":1}
,"border":{"router":1}
,"(abr)":{"attached":1}
,"form":{"command":1}
,"normal":{"area":1}
,"syntax":{"area":1}
,"(a.b.c.d":{"<0-4294967295>)":1}
,"<0-4294967295>)":{"stub":1}
,"no-summary":{"area":1,"parameters":1,"stops":1}
,"parameters":{"a.b.c.d":1}
,"a.b.c.d":{"ospf":1}
,"ospf":{"area":1,"(config-router)":1}
,"ipv4":{"address":1}
,"address":{"format":1}
,"format":{"<0-4294967295>":1}
,"<0-4294967295>":{"ospf":1}
,"decimal":{"value":1}
,"value":{"no-summary":1}
,"stops":{"abr":1}
,"abr":{"sending":1}
,"sending":{"summary":1}
,"summary":{"link":1}
,"link":{"advertisements":1}
,"advertisements":{"stub":1}
,"default":{"stub":1}
,"defined":{"command":1}
,"mode":{"router":1,"examples":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"ipv6":{"ospf":1}
,"(config-router)":{"area":1}
}
;Search.control.loadWordPairs(pairs);
