var pairs =
{
"layer":{"(l1)":1,"open":1}
,"(l1)":{"physical":1}
,"physical":{"layer":1}
,"open":{"systems":1}
,"systems":{"interconnection":1}
,"interconnection":{"(osi)":1}
,"(osi)":{"reference":1}
,"reference":{"model":1}
,"model":{"conveys":1}
,"conveys":{"bit":1}
,"bit":{"stream":1}
,"stream":{"electrical":1}
,"electrical":{"impulse":1}
,"impulse":{"light":1}
,"light":{"waves":1}
,"waves":{"radio":1}
,"radio":{"signals":1}
,"signals":{"network":1}
,"network":{"represents":1,"hardware":1,"topology":1}
,"represents":{"basic":1}
,"basic":{"network":1}
,"hardware":{"specifies":1}
,"specifies":{"type":1}
,"type":{"medium":1}
,"medium":{"used":1}
,"used":{"transmission":1}
,"transmission":{"network":1}
}
;Search.control.loadWordPairs(pairs);
