var pairs =
{
"terminology":{"virtual":1}
,"virtual":{"circuits":1,"circuit":1}
,"circuits":{"virtual":1,"mpls":1}
,"mpls":{"lsp":1,"networks":1,"nodes":1,"network":1,"labels":1,"supports":1,"forwarder":1}
,"lsp":{"tunnels":1,"may":1}
,"tunnels":{"used":1}
,"used":{"carry":1,"create":1}
,"carry":{"layer":1}
,"layer":{"protocol":1,"pdu":1,"pdus":1}
,"protocol":{"data":1,"exchange":1,"case":1}
,"data":{"units":1}
,"units":{"(pdu)":1}
,"(pdu)":{"mpls":1}
,"networks":{"ingress":1}
,"ingress":{"egress":1,"node":1}
,"egress":{"nodes":1,"node":1}
,"nodes":{"tunnel":1,"label":1,"using":1}
,"tunnel":{"extended":1,"labels":1,"lsp":1,"lsps":1}
,"extended":{"ldp":1}
,"ldp":{"protocol":1,"used":1,"extensions":1}
,"exchange":{"labels":1}
,"labels":{"create":1,"visible":1,"labels":1,"exchanged":1,"tunnel":1,"required":1,"zebos-xp":1}
,"create":{"virtual":1,"tunnel":1}
,"circuit":{"labels":1,"identified":1,"(vc-id)":1,"virtual":1,"identifier":1,"create":1,"vc-id":1}
,"visible":{"end":1,"intermediate":1}
,"end":{"points":1,"nodes":1}
,"points":{"circuit":1}
,"identified":{"virtual":1}
,"(vc-id)":{"bi-directional":1,"32-bit":1}
,"bi-directional":{"nature":1}
,"nature":{"separate":1}
,"separate":{"label":1}
,"label":{"allocated":1,"direction":1,"distribution":1}
,"allocated":{"direction":1}
,"direction":{"traffic":1}
,"traffic":{"flow":1}
,"flow":{"makes":1,"labels":1}
,"makes":{"possible":1}
,"possible":{"extend":1}
,"extend":{"lan":1}
,"lan":{"shared":1,"service":1}
,"shared":{"wan":1,"public":1,"tunnel":1}
,"wan":{"infrastructure":1}
,"infrastructure":{"enabling":1,"virtual":1}
,"enabling":{"service":1}
,"service":{"providers":1,"(tls)":1}
,"providers":{"provide":1}
,"provide":{"transparent":1}
,"transparent":{"lan":1}
,"(tls)":{"shared":1}
,"public":{"network":1}
,"network":{"infrastructure":1,"ingress":1}
,"identifier":{"(vc-id)":1}
,"32-bit":{"number":1}
,"number":{"uniquely":1}
,"uniquely":{"identifies":1}
,"identifies":{"virtual":1}
,"vc-id":{"needs":1}
,"needs":{"configured":1,"carried":1}
,"configured":{"routers":1}
,"routers":{"forming":1}
,"forming":{"end-points":1}
,"end-points":{"virtual":1}
,"exchanged":{"two":1,"adjacent":1}
,"two":{"end":1}
,"intermediate":{"mpls":1}
,"required":{"transport":1}
,"transport":{"packet":1}
,"packet":{"across":1}
,"across":{"mpls":1}
,"node":{"egress":1,"tunnel":1}
,"may":{"shared":1}
,"adjacent":{"mpls":1}
,"using":{"label":1,"mpls":1}
,"distribution":{"protocol":1}
,"case":{"zebos-xp":1}
,"zebos-xp":{"ldp":1,"mpls":1}
,"lsps":{"layer":1}
,"pdu":{"layer":1,"encapsulated":1}
,"encapsulated":{"using":1,"layer":1}
,"supports":{"ldp":1,"encapsulation":1}
,"extensions":{"ethernet":1}
,"ethernet":{"ppp":1,"vlan":1,"pdus":1}
,"ppp":{"ethernet":1}
,"vlan":{"mpls":1}
,"forwarder":{"supports":1}
,"encapsulation":{"ethernet":1}
,"pdus":{"control":1,"backbone":1}
,"control":{"word":1}
,"word":{"control":1,"refers":1,"optional":1}
,"refers":{"extra":1}
,"extra":{"information":1}
,"information":{"needs":1}
,"carried":{"transportation":1}
,"transportation":{"encapsulated":1}
,"backbone":{"control":1}
,"optional":{"ethernet":1}
}
;Search.control.loadWordPairs(pairs);
