var pairs =
{
"rip2_get_if_conf_auth_type":{"function":1,"(int":1}
,"function":{"returns":1}
,"returns":{"type":1}
,"type":{"authentication":1,"found":1}
,"authentication":{"used":1,"type":1,"simple":1,"return":1}
,"used":{"interface":1}
,"interface":{"syntax":1,"output":1}
,"syntax":{"int":1}
,"int":{"rip2_get_if_conf_auth_type":1,"*value)":1}
,"(int":{"pid":1}
,"pid":{"struct":1,"rip":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"*addr":1}
,"*addr":{"int":1}
,"*value)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"pid":1,"value":1}
,"rip":{"process":1}
,"process":{"addr":1}
,"addr":{"address":1}
,"address":{"specified":1}
,"specified":{"interface":1}
,"output":{"parameters":1}
,"value":{"authentication":1}
,"simple":{"password":1}
,"password":{"md5":1}
,"md5":{"authentication":1}
,"return":{"values":1}
,"values":{"rip_api_get_error":1}
,"rip_api_get_error":{"authentication":1}
,"found":{"rip_api_get_success":1}
,"rip_api_get_success":{"call":1}
,"call":{"finds":1}
,"finds":{"authentication":1}
}
;Search.control.loadWordPairs(pairs);
