var pairs =
{
"debug":{"pim":1}
,"pim":{"command":1,"option":1,"(all":1,"(vrf":1,"events":1,"packets":1,"states":1,"timers":1}
,"command":{"enable":1,"deactivate":1,"syntax":1,"mode":1}
,"enable":{"debugging":1}
,"debugging":{"pim":1,"general":1,"mfc":1,"mib":1,"mtrace":1,"reverse":1,"nsm":1}
,"option":{"command":1}
,"deactivate":{"debugging":1}
,"syntax":{"debug":1}
,"(all":{"events":1}
,"events":{"mfc":1,"events":1,"enable":1}
,"mfc":{"mib":1,"enable":1,"updates":1}
,"mib":{"mtrace":1,"mtracenexthop":1,"enable":1,"entries":1}
,"mtrace":{"nexthop":1,"enable":1,"messages":1}
,"nexthop":{"nsm":1,"enable":1,"cache":1}
,"nsm":{"packet":1,"enable":1}
,"packet":{"state":1,"enable":1}
,"state":{"timer)":1,"enable":1}
,"timer)":{"debug":1,"parameters":1}
,"(vrf":{"name":1}
,"name":{"(all":1,"specify":1,"vpn":1}
,"mtracenexthop":{"nsm":1}
,"parameters":{"vrf":1}
,"vrf":{"vpn":1,"context":1}
,"vpn":{"routing\u002Fforwarding":1}
,"routing\u002Fforwarding":{"instance":1}
,"instance":{"name":1,"enable":1}
,"specify":{"name":1}
,"general":{"configuration":1}
,"configuration":{"virtual":1}
,"virtual":{"routing":1}
,"routing":{"(vr)":1}
,"(vr)":{"vrf":1}
,"context":{"mfc":1}
,"updates":{"mib":1}
,"entries":{"mtrace":1}
,"messages":{"nexthop":1}
,"reverse":{"path":1}
,"path":{"forwarding":1}
,"forwarding":{"(rpf)":1}
,"(rpf)":{"neighbor":1}
,"neighbor":{"nexthop":1}
,"cache":{"handling":1}
,"handling":{"nsm":1}
,"packets":{"state":1}
,"states":{"timer":1}
,"timer":{"enable":1}
,"timers":{"command":1}
,"mode":{"exec":1,"privilege":1,"configure":1,"examples":1}
,"exec":{"mode":1}
,"privilege":{"exec":1}
,"configure":{"mode":1,"terminal":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"debug":1}
}
;Search.control.loadWordPairs(pairs);
