var pairs =
{
"design":{"protocol":1}
,"protocol":{"module":1}
,"module":{"supports":1,"apis":1,"bfd":1,"encodes":1,"using":1,"configures":1,"turn":1,"packet":1,"back":1,"via":1}
,"supports":{"bfd":1}
,"bfd":{"uses":1,"client":1,"base":1,"server":1,"abstraction":1,"hello":1,"used":1}
,"uses":{"bfd":1}
,"client":{"apis":1}
,"apis":{"communicate":1,"connected":1}
,"communicate":{"bfd":1}
,"base":{"module":1}
,"connected":{"exchange":1}
,"exchange":{"information":1}
,"information":{"bfd":1,"passed":1}
,"server":{"module":1}
,"encodes":{"decodes":1}
,"decodes":{"messages":1}
,"messages":{"clients":1}
,"clients":{"configures":1}
,"configures":{"sessions":1,"relevant":1}
,"sessions":{"bfd":1,"configure":1}
,"using":{"bfd":1}
,"abstraction":{"layer":1}
,"layer":{"base":1,"bfd":1,"supported":1}
,"relevant":{"information":1}
,"hello":{"processing":1,"module":1}
,"processing":{"module":1,"fsm-related":1}
,"turn":{"bfd":1}
,"packet":{"processing":1}
,"fsm-related":{"functions":1}
,"functions":{"session":1}
,"session":{"triggers":1}
,"triggers":{"data":1}
,"data":{"plane-related":1}
,"plane-related":{"information":1}
,"passed":{"hello":1}
,"back":{"bfd":1}
,"via":{"abstraction":1}
,"supported":{"allow":1}
,"allow":{"sessions":1}
,"configure":{"remotely":1}
,"remotely":{"bfd":1}
,"used":{"distributed":1}
,"distributed":{"architecture":1}
}
;Search.control.loadWordPairs(pairs);
