var pairs =
{
"nsm_mpls_bfd_api_vccv_trigger":{"function":1,"(struct":1}
,"function":{"starts":1,"succeeds":1}
,"starts":{"stops":1}
,"stops":{"bfd":1}
,"bfd":{"vccv":1,"bccv":1}
,"vccv":{"session":1}
,"session":{"based":1,"already":1,"configuration":1,"exists":1}
,"based":{"specified":1}
,"specified":{"operation":1}
,"operation":{"syntax":1,"output":1}
,"syntax":{"int":1}
,"int":{"nsm_mpls_bfd_api_vccv_trigger":1}
,"(struct":{"nsm_master":1}
,"nsm_master":{"*nm":1}
,"*nm":{"uint32_t":1}
,"uint32_t":{"vc_id":1}
,"vc_id":{"u_char":1,"virtual":1}
,"u_char":{"op)":1}
,"op)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"pointer":1,"none":1}
,"pointer":{"nsm":1}
,"nsm":{"master":1}
,"master":{"structure":1}
,"structure":{"vc_id":1}
,"virtual":{"circuit":1}
,"circuit":{"indicates":1,"found":1}
,"indicates":{"start":1}
,"start":{"stop":1}
,"stop":{"operation":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_err_vc_id_not_found":1}
,"nsm_err_vc_id_not_found":{"virtual":1}
,"found":{"nsm_mpls_bfd_vccv_err_sess_exists":1}
,"nsm_mpls_bfd_vccv_err_sess_exists":{"bfd":1}
,"already":{"exists":1}
,"exists":{"nsm_mpls_bfd_vccv_err_not_configured":1,"nsm_failure":1}
,"nsm_mpls_bfd_vccv_err_not_configured":{"bfd":1}
,"configuration":{"fails":1}
,"fails":{"nsm_mpls_bfd_vccv_err_sess_not_exists":1}
,"nsm_mpls_bfd_vccv_err_sess_not_exists":{"bfd":1}
,"bccv":{"session":1}
,"nsm_failure":{"generic":1}
,"generic":{"error":1}
,"error":{"occurs":1}
,"occurs":{"nsm_success":1}
,"nsm_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
