var pairs =
{
"data-center-bridging":{"command":1,"enable":1}
,"command":{"enable":1,"disable":1,"syntax":1,"enables":1,"mode":1}
,"enable":{"dcb":1,"data-center-bridging":1,"bridge":1,"configure":1}
,"dcb":{"(data":1,"command":1,"default":1,"enabled":1}
,"(data":{"center":1}
,"center":{"bridging)":1}
,"bridging)":{"switch":1}
,"switch":{"(bridge)":1}
,"(bridge)":{"form":1}
,"form":{"command":1}
,"disable":{"dcb":1}
,"syntax":{"data-center-bridging":1}
,"bridge":{"<1-32>":1,"bridge":1,"specify":1,"command":1,"configure":1}
,"<1-32>":{"data-center-bridging":1,"parameters":1}
,"parameters":{"bridge":1}
,"specify":{"bridge":1}
,"enables":{"disables":1}
,"disables":{"dcb":1}
,"default":{"bridge":1,"dcb":1}
,"mode":{"configure":1,"default":1}
,"configure":{"mode":1,"terminal":1}
,"enabled":{"examples":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"data-center-bridging":1}
}
;Search.control.loadWordPairs(pairs);
