var pairs =
{
"ospf_if_dna_set":{"function":1,"(u_int32_t":1}
,"function":{"enables":1,"called":1,"succeeds":1}
,"enables":{"flood":1}
,"flood":{"reduction":1}
,"reduction":{"feature":1}
,"feature":{"interface":1}
,"interface":{"function":1,"name":1,"found":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"ospf":1}
,"ospf":{"flood-reduction":1}
,"flood-reduction":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf_if_dna_set":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1}
,"char":{"*name)":1}
,"*name)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"found":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"name":1}
,"name":{"interface":1,"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf_api_set_err_vr_not_exist":1}
,"ospf_api_set_err_vr_not_exist":{"virtual":1}
,"found":{"ospf_api_set_malloc_err":1,"ospf_api_set_success":1}
,"ospf_api_set_malloc_err":{"specified":1}
,"specified":{"interface":1}
,"ospf_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
