var pairs =
{
"nsm":{"implications":1}
,"implications":{"zebos-xp":1}
,"zebos-xp":{"uses":1,"zebos-xp":1,"first":1}
,"uses":{"tunneling":1}
,"tunneling":{"features":1}
,"features":{"iproute2":1}
,"iproute2":{"utility":1}
,"utility":{"package":1,"command":1}
,"package":{"include":1}
,"include":{"creating":1}
,"creating":{"destroying":1}
,"destroying":{"tunnels":1}
,"tunnels":{"forwarding":1,"tunnels":1,"appear":1,"established":1,"interface":1}
,"forwarding":{"routers":1}
,"routers":{"(or":1}
,"(or":{"virtual":1}
,"virtual":{"routers)":1,"routing":1}
,"routers)":{"connected":1}
,"connected":{"tunnels":1}
,"appear":{"point-to-point":1}
,"point-to-point":{"links":1}
,"links":{"different":1}
,"different":{"vrs":1}
,"vrs":{"support":1}
,"support":{"ip-in-ip":1}
,"ip-in-ip":{"(except":1,"tunnel":1}
,"(except":{"multicast":1}
,"multicast":{"situations)":1}
,"situations)":{"sit":1}
,"sit":{"gre":1}
,"gre":{"types":1}
,"types":{"using":1}
,"using":{"iproute2":1,"command":1,"commands":1}
,"command":{"shell":1,"establishes":1,"lists":1,"reference":1}
,"shell":{"command":1,"starting":1}
,"establishes":{"ip-in-ip":1}
,"tunnel":{"tunl":1}
,"tunl":{"add":1}
,"add":{"mode":1}
,"mode":{"ipip":1}
,"ipip":{"remote":1}
,"remote":{"10.56.9.48":1}
,"10.56.9.48":{"local":1}
,"local":{"10.104.88.5":1}
,"10.104.88.5":{"tunnels":1}
,"established":{"using":1}
,"starting":{"zebos-xp":1}
,"first":{"starts":1}
,"starts":{"show":1}
,"show":{"interface":1}
,"interface":{"command":1,"assigned":1}
,"lists":{"tunnels":1}
,"assigned":{"particular":1}
,"particular":{"using":1}
,"commands":{"described":1}
,"described":{"virtual":1}
,"routing":{"command":1}
}
;Search.control.loadWordPairs(pairs);
