var pairs =
{
"definition":{"struct":1}
,"struct":{"trill":1}
,"trill":{"{\u002F*tag":1,"area":1,"master":1,"runs":1,"defaults":1,"addr*\u002Fvector":1}
,"{\u002F*tag":{"trill":1}
,"area":{"*\u002Fchar":1,"addresses":1,"addr":1}
,"*\u002Fchar":{"*tag":1}
,"*tag":{"\u002F*instance":1}
,"\u002F*instance":{"*\u002Fu_int32_t":1}
,"*\u002Fu_int32_t":{"instance_id":1,"forward_delay":1}
,"instance_id":{"\u002F*pointer":1}
,"\u002F*pointer":{"trill":1,"list":1}
,"master":{"*\u002Fstruct":1}
,"*\u002Fstruct":{"trill_master":1,"trill_bridge*bridge":1,"trill_proto":1,"trill_level":1,"ls_table":1,"list":1,"trill_bridge_static_fdb_config":1,"trill_bridge_static_dtree_config":1,"trill_snoop_table":1,"trill_tlv":1,"thread":1}
,"trill_master":{"*im":1}
,"*im":{"\u002F*the":1}
,"\u002F*the":{"bridge":1}
,"bridge":{"associated":1}
,"associated":{"instance":1}
,"instance":{"*\u002Fstruct":1}
,"trill_bridge*bridge":{"\u002F*trill":1}
,"\u002F*trill":{"start":1,"system":1,"protocols":1,"administrative":1,"inteface":1,"interface":1,"neighbor":1,"snooping":1,"vlan":1}
,"start":{"time":1}
,"time":{"*\u002Fpal_time_t":1}
,"*\u002Fpal_time_t":{"start_time":1}
,"start_time":{"\u002F*trill":1}
,"system":{"*\u002Fu_char":1}
,"*\u002Fu_char":{"system_id":1,"is_type":1,"proto_type":1,"flags":1,"max_area_addrs":1,"confidence_local_recvd":1,"confidence_remote_recvd":1,"confidence_static_config":1,"dtree_config":1}
,"system_id":{"[trill_sysid_length]":1}
,"[trill_sysid_length]":{"\u002F*trill-type":1}
,"\u002F*trill-type":{"*\u002F\u002F*this":1}
,"*\u002F\u002F*this":{"default":1}
,"default":{"trill":1}
,"runs":{"level":1}
,"level":{"*\u002Fu_char":1,"[trill_level_index_max]":1,"tlv":1}
,"is_type":{"\u002F*trill":1}
,"protocols":{"supported":1}
,"supported":{"*\u002F\u002F*-this":1,"*\u002F\u002F*-to":1}
,"*\u002F\u002F*-this":{"proto":1}
,"proto":{"type":1,"[trill_proto_index_max]":1}
,"type":{"field":1}
,"field":{"point":1}
,"point":{"new":1}
,"new":{"prototype":1}
,"prototype":{"is_l2":1}
,"is_l2":{"*\u002Fu_char":1}
,"proto_type":{"\u002F*trill":1}
,"administrative":{"flags":1}
,"flags":{"*\u002Fu_char":1,"define":1,"*\u002Fu_int16_t":1}
,"define":{"trill_flag_shutdown":1,"trill_config_system_id":1,"trill_config_minimum_mtu":1,"trill_config_lsp_refresh_interval":1,"trill_config_max_lsp_lifetime":1,"trill_config_ignore_lsp_errors":1,"trill_config_forward_delay":1,"trill_config_accept_non_adj":1,"trill_config_unicast_enable":1,"trill_config_multicast_enable":1,"trill_autogen_system_id":1,"trill_config_num_of_mtu_probes":1,"trill_config_max_rb_dtrees":1,"trill_config_num_dtrees_use_campus":1,"trill_config_num_dtrees_to_use":1,"trill_config_num_dtrees_to_compute":1}
,"trill_flag_shutdown":{"<<1)":1}
,"<<1)":{"\u002F*config":1,"define":1}
,"\u002F*config":{"flags":1,"variables":1,"flag":1}
,"*\u002Fu_int16_t":{"config":1,"lsp_refresh_interval":1,"max_lsp_lifetime":1,"inter_rb_mtu":1,"max_dtrees":1,"campus_wide_mtu":1,"minimum_mtu":1}
,"config":{"define":1}
,"trill_config_system_id":{"<<0)":1}
,"<<0)":{"define":1}
,"trill_config_minimum_mtu":{"<<1)":1}
,"trill_config_lsp_refresh_interval":{"<<2)":1}
,"<<2)":{"define":1}
,"trill_config_max_lsp_lifetime":{"<<3)":1}
,"<<3)":{"define":1,"u_int16_t":1}
,"trill_config_ignore_lsp_errors":{"<<4)":1}
,"<<4)":{"define":1}
,"trill_config_forward_delay":{"<<5)":1}
,"<<5)":{"define":1}
,"trill_config_accept_non_adj":{"<<6)":1}
,"<<6)":{"define":1}
,"trill_config_unicast_enable":{"<<7)":1}
,"<<7)":{"define":1}
,"trill_config_multicast_enable":{"<<8)":1}
,"<<8)":{"define":1}
,"trill_autogen_system_id":{"<<9)":1}
,"<<9)":{"define":1}
,"trill_config_num_of_mtu_probes":{"<<10)":1}
,"<<10)":{"\u002F*config":1}
,"variables":{"*\u002Fu_char":1}
,"max_area_addrs":{"\u002F*number":1}
,"\u002F*number":{"max":1,"mtu":1}
,"max":{"area":1}
,"addresses":{"--in":1,"-other":1,"gaadr":1,"*\u002Fstruct":1}
,"--in":{"trill":1}
,"defaults":{"one*\u002Fvector":1}
,"one*\u002Fvector":{"area_addrs":1}
,"area_addrs":{"\u002F*manual":1}
,"\u002F*manual":{"area":1}
,"addr*\u002Fvector":{"recv_area_addrs":1}
,"recv_area_addrs":{"\u002F*rcv":1}
,"\u002F*rcv":{"area":1}
,"-other":{"already":1}
,"already":{"manual":1}
,"manual":{"area":1}
,"addr":{"list":1}
,"list":{"*\u002Fu_int16_t":1,"nicknames":1,"*self_nickname":1,"*afl_modified_list":1,"*treerootlist":1,"*dtrees_to_compute":1,"*dtrees_to_use":1}
,"lsp_refresh_interval":{"\u002F*lsp":1}
,"\u002F*lsp":{"refresh":1}
,"refresh":{"interval":1}
,"interval":{"*\u002Fu_int16_t":1}
,"max_lsp_lifetime":{"\u002F*max":1}
,"\u002F*max":{"lsp":1,"number":1}
,"lsp":{"lifetime":1}
,"lifetime":{"*\u002Fu_int32_t":1}
,"forward_delay":{"\u002F*forward":1}
,"\u002F*forward":{"delay":1,"delay*\u002Fu_int16_t":1}
,"delay":{"*\u002Fu_char":1}
,"confidence_local_recvd":{"\u002F*confidence":1}
,"\u002F*confidence":{"local":1,"decapsulated":1,"static":1}
,"local":{"recvd":1}
,"recvd":{"frame":1}
,"frame":{"*\u002Fu_char":1}
,"confidence_remote_recvd":{"\u002F*confidence":1}
,"decapsulated":{"frame":1}
,"confidence_static_config":{"\u002F*confidence":1}
,"static":{"configuration":1,"d-tree":1}
,"configuration":{"*\u002Fu_int16_t":1,"*\u002Fstruct":1}
,"inter_rb_mtu":{"\u002F*originationlsp":1}
,"\u002F*originationlsp":{"buffer":1}
,"buffer":{"size*\u002Fu_int16_t":1}
,"size*\u002Fu_int16_t":{"mtu_probe_counter":1}
,"mtu_probe_counter":{"\u002F*mtu":1}
,"\u002F*mtu":{"probe":1}
,"probe":{"counter":1}
,"counter":{"*\u002Fu_char":1,"status":1,"*changed":1}
,"dtree_config":{"\u002F*config":1}
,"flag":{"dtree":1}
,"dtree":{"parameters":1}
,"parameters":{"*\u002F#":1}
,"*\u002F#":{"define":1,"\u002F*d-tree":1,"endif":1}
,"trill_config_max_rb_dtrees":{"<<0)":1}
,"trill_config_num_dtrees_use_campus":{"<<1)":1}
,"trill_config_num_dtrees_to_use":{"<<2)":1}
,"trill_config_num_dtrees_to_compute":{"<<3)":1}
,"u_int16_t":{"num_of_dtrees_to_compute":1,"confidence_native":1,"confidence_decap":1,"confidence_static":1,"echo_req_timeout":1}
,"num_of_dtrees_to_compute":{"\u002F*no":1}
,"\u002F*no":{"dtrees":1}
,"dtrees":{"compute":1,"campus":1,"*\u002Fstruct":1}
,"compute":{"*\u002Fu_int16_t":1,"*\u002Fstruct":1}
,"max_dtrees":{"\u002F*max":1}
,"number":{"d-trees":1}
,"d-trees":{"compute*\u002Fu_int16_t":1}
,"compute*\u002Fu_int16_t":{"num_dtree_to_use":1}
,"num_dtree_to_use":{"\u002F*no":1}
,"campus":{"wide":1}
,"wide":{"*\u002F\u002F*information":1,"mtu":1}
,"*\u002F\u002F*information":{"per":1}
,"per":{"protocol":1,"vlan":1}
,"protocol":{"*\u002Fstruct":1}
,"trill_proto":{"proto":1}
,"[trill_proto_index_max]":{"\u002F*level":1}
,"\u002F*level":{"context":1}
,"context":{"*\u002Fstruct":1}
,"trill_level":{"level":1}
,"[trill_level_index_max]":{"\u002F*pointer":1}
,"nicknames":{"configured*\u002F\u002F*list":1,"auto":1,"{struct":1,"sorted":1}
,"configured*\u002F\u002F*list":{"nicknames":1}
,"auto":{"generated":1}
,"generated":{"user":1}
,"user":{"configured":1}
,"configured":{"{struct":1,"dtrees":1}
,"{struct":{"trill_nickname}*\u002Fstruct":1,"trill_l2mcast}*\u002Fstruct":1}
,"trill_nickname}*\u002Fstruct":{"list":1,"ls_table":1}
,"*self_nickname":{"\u002F*list":1}
,"\u002F*list":{"campus-wide":1,"snooped":1,"appointed":1,"pointers":1,"nicknames":1,"configured":1}
,"campus-wide":{"nicknames":1}
,"ls_table":{"*nickdatabase":1,"*l2mcasttable":1,"*af_lost_table":1,"*chnl_echo_req_table":1,"*af_lost_table_lsp":1,"*if_table":1,"*nbr_table":1,"*nexthop_table":1,"*l2_mcast_intf_table":1,"*rbridge_vlan_bmp_mrt_table":1,"*l2_mcast_addr_table":1,"*pvlan_table":1,"*trill_snmp_neigh":1,"*trill_snmp_snoopaddr":1,"*trill_snmp_snoopport":1,"*trill_snmp_vlanport":1}
,"*nickdatabase":{"\u002F*list":1}
,"snooped":{"multicast":1}
,"multicast":{"address":1}
,"address":{"{struct":1,"table":1,"tlv":1,"sub":1}
,"trill_l2mcast}*\u002Fstruct":{"ls_table":1}
,"*l2mcasttable":{"\u002F*list":1}
,"appointed":{"forwarder":1}
,"forwarder":{"lost":1}
,"lost":{"status":1,"counter":1}
,"status":{"per":1,"lsps":1,"*\u002F\u002F*campus":1}
,"vlan":{"self":1,"(prefix)":1,"bitmaps":1,"info":1,"port":1}
,"self":{"rb*\u002Fstruct":1}
,"rb*\u002Fstruct":{"ls_table":1}
,"*af_lost_table":{"\u002F*table":1}
,"\u002F*table":{"store":1,"interested":1,"mcast":1}
,"store":{"info":1}
,"info":{"related":1,"table":1}
,"related":{"oam":1,"global":1}
,"oam":{"messages":1}
,"messages":{"sent*\u002Fstruct":1}
,"sent*\u002Fstruct":{"ls_table":1}
,"*chnl_echo_req_table":{"\u002F*af":1}
,"\u002F*af":{"lost":1}
,"lsps":{"systemid":1}
,"systemid":{"vlan":1}
,"(prefix)":{"*\u002Fstruct":1}
,"*af_lost_table_lsp":{"\u002F*list":1}
,"pointers":{"data":1}
,"data":{"af_lost_table_lsp":1}
,"af_lost_table_lsp":{"whose":1}
,"whose":{"afl":1}
,"afl":{"counter":1}
,"*changed":{"*\u002Fstruct":1}
,"*afl_modified_list":{"\u002F*list":1}
,"sorted":{"higher":1}
,"higher":{"priority":1}
,"priority":{"tree":1}
,"tree":{"root":1}
,"root":{"{struct":1,"sub":1}
,"*treerootlist":{"\u002F*list":1}
,"*dtrees_to_compute":{"\u002F*list":1}
,"*dtrees_to_use":{"\u002F*local":1}
,"\u002F*local":{"circuit":1}
,"circuit":{"vector":1}
,"vector":{"*\u002Fvector":1,"*\u002F\u002F*index":1}
,"*\u002Fvector":{"circuit_vec":1,"port_id_vec":1,"group_mac_addr_stlv":1}
,"circuit_vec":{"\u002F*tables":1}
,"\u002F*tables":{"*\u002Fstruct":1}
,"*if_table":{"\u002F*trill":1}
,"inteface":{"table":1}
,"table":{"*\u002Fvector":1,"*\u002Fstruct":1,"*\u002F#":1,"based":1,"snmp":1}
,"port_id_vec":{"\u002F*trill":1}
,"interface":{"vector":1}
,"*\u002F\u002F*index":{"used":1}
,"used":{"port":1}
,"port":{"*\u002Fstruct":1,"table":1}
,"*nbr_table":{"\u002F*global":1}
,"\u002F*global":{"neighbor":1}
,"neighbor":{"table":1}
,"*nexthop_table":{"\u002F*nexthop":1}
,"\u002F*nexthop":{"table":1}
,"\u002F*d-tree":{"pruning":1}
,"pruning":{"related":1}
,"global":{"tables":1,"level":1}
,"tables":{"*\u002Fstruct":1}
,"*l2_mcast_intf_table":{"\u002F*l2":1}
,"\u002F*l2":{"mcast":1}
,"mcast":{"group":1}
,"group":{"address":1,"addresses":1}
,"*rbridge_vlan_bmp_mrt_table":{"\u002F*table":1}
,"interested":{"vlan":1}
,"bitmaps":{"*\u002Fstruct":1}
,"*l2_mcast_addr_table":{"\u002F*table":1}
,"gaadr":{"tlv":1}
,"tlv":{"*\u002Fstruct":1,"here*\u002Fstruct":1,"*\u002Fvector":1}
,"trill_bridge_static_fdb_config":{"*pstatic_fdblist":1}
,"*pstatic_fdblist":{";\u002F*pointer":1}
,";\u002F*pointer":{"static-fdb":1,"static":1}
,"static-fdb":{"configuration":1}
,"trill_bridge_static_dtree_config":{"*pstatic_dtreelist":1}
,"*pstatic_dtreelist":{";\u002F*pointer":1}
,"d-tree":{"configuration":1}
,"trill_snoop_table":{"*table":1}
,"*table":{";\u002F*snoop":1}
,";\u002F*snoop":{"table":1}
,"endif":{"\u002F*tlvs":1,"\u002F*have_snmp*\u002F\u002F*timer":1}
,"\u002F*tlvs":{"*\u002Fstruct":1}
,"trill_tlv":{"*tlv_area_addrs":1,"*tlv_protos":1,"*tlv_group_addr":1,"*stlv_nicknames":1,"*stlv_tree_id":1,"*stlv_tree_use_id":1,"*stlv_channel":1}
,"*tlv_area_addrs":{"\u002F*area":1}
,"\u002F*area":{"addresses":1}
,"*tlv_protos":{"\u002F*protocol":1}
,"\u002F*protocol":{"supported":1}
,"*\u002F\u002F*-to":{"add":1}
,"add":{"global":1}
,"here*\u002Fstruct":{"trill_tlv":1}
,"*tlv_group_addr":{"\u002F*group":1}
,"\u002F*group":{"address":1,"mac":1}
,"group_mac_addr_stlv":{"\u002F*group":1}
,"mac":{"address":1,"snmp*\u002Fstruct":1}
,"sub":{"tlv*\u002Fvector":1,"tlv*\u002Fstruct":1,"tlv*\u002F\u002F*interested":1}
,"tlv*\u002Fvector":{"router_capability_tlv":1,"intvlan_stlv":1}
,"router_capability_tlv":{"\u002F*router":1}
,"\u002F*router":{"capability":1}
,"capability":{"tlv":1}
,"*stlv_nicknames":{"\u002F*nicknames":1}
,"\u002F*nicknames":{"sub":1}
,"tlv*\u002Fstruct":{"trill_tlv":1}
,"*stlv_tree_id":{"\u002F*tree":1}
,"\u002F*tree":{"sub":1}
,"*stlv_tree_use_id":{"\u002F*tree":1}
,"*stlv_channel":{"\u002F*channel":1}
,"\u002F*channel":{"sub":1}
,"tlv*\u002F\u002F*interested":{"vlans":1}
,"vlans":{"spanning":1}
,"spanning":{"tree":1}
,"intvlan_stlv":{"\u002F*threads":1}
,"\u002F*threads":{"*\u002Fstruct":1}
,"thread":{"*t_maxage_walker":1,"*t_af_lost_status":1}
,"*t_maxage_walker":{"\u002F*maxage":1}
,"\u002F*maxage":{"walker":1}
,"walker":{"*\u002Fstruct":1}
,"*t_af_lost_status":{"\u002F*af":1}
,"*\u002F\u002F*campus":{"wide":1}
,"mtu":{"*\u002Fu_int16_t":1,"probes":1}
,"campus_wide_mtu":{"\u002F*minimum":1}
,"\u002F*minimum":{"mtu":1}
,"minimum_mtu":{"\u002F*number":1}
,"probes":{"*\u002Fu_int8_t":1}
,"*\u002Fu_int8_t":{"mtu_probes":1}
,"mtu_probes":{"\u002F*forward":1}
,"delay*\u002Fu_int16_t":{"fwd_delay":1}
,"fwd_delay":{"u_int16_t":1}
,"confidence_native":{"u_int16_t":1}
,"confidence_decap":{"u_int16_t":1}
,"confidence_static":{"u_int32_t":1}
,"u_int32_t":{"max_nickname":1}
,"max_nickname":{"ifdef":1}
,"ifdef":{"have_snmp":1}
,"have_snmp":{"\u002F*per":1}
,"\u002F*per":{"vlan":1}
,"*pvlan_table":{"\u002F*trill":1}
,"based":{"mac":1}
,"snmp*\u002Fstruct":{"ls_table":1}
,"*trill_snmp_neigh":{"\u002F*trill":1}
,"snooping":{"address":1,"port":1}
,"snmp":{"*\u002Fstruct":1}
,"*trill_snmp_snoopaddr":{"\u002F*trill":1}
,"*trill_snmp_snoopport":{"\u002F*trill":1}
,"*trill_snmp_vlanport":{"endif":1}
,"\u002F*have_snmp*\u002F\u002F*timer":{"values":1}
,"values":{"oam*\u002Fu_int16_t":1}
,"oam*\u002Fu_int16_t":{"echo_req_interval":1}
,"echo_req_interval":{"u_int16_t":1}
}
;Search.control.loadWordPairs(pairs);
