var pairs =
{
"show":{"debugging":1}
,"debugging":{"ospf":1,"option":1,"status":1}
,"ospf":{"command":1,"debugging":1,"parameters":1,"ospf":1,"packet":1,"events":1}
,"command":{"display":1,"syntax":1,"mode":1,"lines":1}
,"display":{"ospf":1,"show":1}
,"option":{"command":1}
,"syntax":{"show":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"privileged":1,"example":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"example":{"sample":1}
,"sample":{"output":1}
,"output":{"show":1,"wrap":1}
,"lines":{"output":1}
,"wrap":{"around":1}
,"around":{"wrap":1,"actual":1}
,"actual":{"display":1}
,"status":{"ospf":1}
,"packet":{"link":1}
,"link":{"state":1}
,"state":{"update":1}
,"update":{"debugging":1}
,"events":{"debugging":1}
}
;Search.control.loadWordPairs(pairs);
