var pairs =
{
"clear":{"gmrp":1}
,"gmrp":{"command":1,"statistics":1}
,"command":{"clear":1,"syntax":1,"mode":1}
,"statistics":{"given":1,"clear":1,"bridge":1,"vlanid":1,"vlan":1,"configured":1}
,"given":{"vlan":1}
,"vlan":{"vlans":1,"identifiers":1,"clear":1,"bridge":1}
,"vlans":{"configured":1,"command":1,"bridge":1}
,"configured":{"switch":1,"vlans":1}
,"switch":{"command":1}
,"syntax":{"clear":1}
,"bridge":{"bridge_name":1,"<1-32>":1,"identifier":1,"example":1,"clear":1}
,"bridge_name":{"clear":1,"bridge":1}
,"vlanid":{"<1-4094>":1}
,"<1-4094>":{"clear":1,"bridge":1,"clears":1}
,"<1-32>":{"parameters":1,"specify":1}
,"parameters":{"clears":1}
,"clears":{"identifiers":1,"vlan":1}
,"identifiers":{"bridge_name":1,"<1-32>":1}
,"identifier":{"<1-4094>":1,"default":1}
,"specify":{"bridge":1}
,"default":{"default":1,"clearing":1}
,"clearing":{"configured":1}
,"mode":{"exec":1,"privileged":1,"examples":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"examples":{"example":1}
,"example":{"shows":1}
,"shows":{"clear":1}
}
;Search.control.loadWordPairs(pairs);
