var pairs =
{
"isis_passive_interface_set":{"call":1,"(u_int32_t":1}
,"call":{"implements":1,"successful":1}
,"implements":{"passive":1}
,"passive":{"interface":1,"mode":1,"isis_api_set_err_invalid_cmd_if_clns_only":1}
,"interface":{"command":1,"passive":1,"syntax":1,"name":1,"given":1}
,"command":{"interface":1}
,"mode":{"current":1}
,"current":{"interface":1}
,"syntax":{"int":1}
,"int":{"isis_passive_interface_set":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1,"tag":1}
,"char":{"*tag":1,"*name)":1}
,"*tag":{"char":1}
,"*name)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1,"isis_api_set_err_last_active_if_passive":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"tag":{"is-is":1,"name":1,"isis_api_set_success":1}
,"is-is":{"instance":1,"cannot":1,"enabled":1}
,"instance":{"area":1,"exist":1}
,"area":{"tag":1}
,"name":{"interface":1,"output":1,"exist":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"isis_api_set_err_last_active_if_passive":{"is-is":1}
,"cannot":{"last":1}
,"last":{"active":1}
,"active":{"isis-ip":1}
,"isis-ip":{"interface":1}
,"isis_api_set_err_invalid_cmd_if_clns_only":{"is-is":1}
,"enabled":{"interfaces":1}
,"interfaces":{"present":1}
,"present":{"isis_api_set_err_if_not_exist":1}
,"isis_api_set_err_if_not_exist":{"interface":1}
,"given":{"name":1,"tag":1}
,"exist":{"isis_api_set_err_instance_not_exist":1,"given":1}
,"isis_api_set_err_instance_not_exist":{"is-is":1}
,"isis_api_set_success":{"call":1}
,"successful":{"isis_api_set_err_vr_not_exist":1}
,"isis_api_set_err_vr_not_exist":{"found":1}
}
;Search.control.loadWordPairs(pairs);
