var pairs =
{
"inter-area":{"label":1}
,"label":{"switched":1,"forwarding":1}
,"switched":{"paths":1}
,"paths":{"zebos-xp":1,"(lsp)":1}
,"zebos-xp":{"ldp":1}
,"ldp":{"supports":1}
,"supports":{"inter-area":1}
,"(lsp)":{"span":1}
,"span":{"multiple":1}
,"multiple":{"igp":1}
,"igp":{"(internal":1}
,"(internal":{"gateway":1}
,"gateway":{"protocol)":1}
,"protocol)":{"areas":1}
,"areas":{"autonomous":1}
,"autonomous":{"system":1}
,"system":{"(as)":1}
,"(as)":{"procedure":1}
,"procedure":{"allows":1}
,"allows":{"label":1}
,"forwarding":{"equivalence":1}
,"equivalence":{"class":1}
,"class":{"(fec)":1}
,"(fec)":{"element":1}
,"element":{"matches":1}
,"matches":{"entry":1}
,"entry":{"routing":1}
,"routing":{"information":1}
,"information":{"base":1}
,"base":{"(rib)":1}
,"(rib)":{"instead":1}
,"instead":{"mandating":1}
,"mandating":{"exact":1}
,"exact":{"match":1}
,"match":{"two":1,"(lpm)":1}
,"two":{"entries":1}
,"entries":{"new":1}
,"new":{"feature":1}
,"feature":{"defines":1}
,"defines":{"matching":1}
,"matching":{"longest-match":1}
,"longest-match":{"search":1}
,"search":{"based":1}
,"based":{"longest":1}
,"longest":{"prefix":1}
,"prefix":{"match":1}
}
;Search.control.loadWordPairs(pairs);
