var pairs =
{
"oam_mplstp_api_itut_associate_vc":{"function":1,"(u_int32_t":1}
,"function":{"associates":1,"succeeds":1}
,"associates":{"mpls-tp":1}
,"mpls-tp":{"mpls-tp":1,"maintenance":1}
,"maintenance":{"entity":1}
,"entity":{"service":1}
,"service":{"type":1}
,"type":{"configured":1,"match":1}
,"configured":{"(virtual":1}
,"(virtual":{"circuit)":1}
,"circuit)":{"updates":1}
,"updates":{"allowed":1}
,"allowed":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"oam_mplstp_api_itut_associate_vc":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"instance":1}
,"char":{"*meg_name":1}
,"*meg_name":{"u_int16_t":1}
,"u_int16_t":{"mp_id":1}
,"mp_id":{"u_int32_t":1,"integer":1,"valid":1,"already":1}
,"u_int32_t":{"vcid)":1}
,"vcid)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"instance":{"meg_name":1}
,"meg_name":{"pointer":1,"null":1}
,"pointer":{"meg":1,"containing":1}
,"meg":{"name":1,"entry":1}
,"name":{"mp_id":1,"exceeds":1}
,"integer":{"containing":1}
,"containing":{"vcid":1,"output":1}
,"vcid":{"pointer":1,"zero":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"mplstp_api_success":1}
,"mplstp_api_success":{"function":1}
,"succeeds":{"mplstp_err_vr_not_exists":1}
,"mplstp_err_vr_not_exists":{"virtual":1}
,"virtual":{"router":1}
,"router":{"cannot":1}
,"cannot":{"found":1}
,"found":{"mplstp_err_meg_name_invalid":1,"mplstp_err_me_service_type_not_match":1,"mplstp_err_me_cant_update_service_id":1}
,"mplstp_err_meg_name_invalid":{"meg_name":1}
,"null":{"mplstp_err_meg_name_exceeds_max_len":1}
,"mplstp_err_meg_name_exceeds_max_len":{"meg":1}
,"exceeds":{"maximum":1}
,"maximum":{"length":1}
,"length":{"mplstp_err_invalid_mp_id":1}
,"mplstp_err_invalid_mp_id":{"mp_id":1}
,"valid":{"mplstp_err_me_vc_id_invalid":1}
,"mplstp_err_me_vc_id_invalid":{"vcid":1}
,"zero":{"mplstp_err_meg_entry_not_exists":1}
,"mplstp_err_meg_entry_not_exists":{"meg":1}
,"entry":{"cannot":1}
,"mplstp_err_me_service_type_not_match":{"service":1}
,"match":{"mplstp_err_me_create_failed":1}
,"mplstp_err_me_create_failed":{"memory":1}
,"memory":{"allocation":1}
,"allocation":{"fails":1}
,"fails":{"mplstp_err_me_entry_not_exists":1}
,"mplstp_err_me_entry_not_exists":{"entry":1}
,"mplstp_err_me_cant_update_service_id":{"mp_id":1}
,"already":{"associated":1}
,"associated":{"different":1}
,"different":{"vcid":1}
}
;Search.control.loadWordPairs(pairs);
