var pairs =
{
"elmi":{"commands":1,"ethernet":1,"show":1}
,"commands":{"chapter":1,"clear":1}
,"chapter":{"contains":1}
,"contains":{"ethernet":1}
,"ethernet":{"local":1,"lmi":1}
,"local":{"management":1}
,"management":{"interface":1}
,"interface":{"(elmi)":1,"ethernet":1,"show":1}
,"(elmi)":{"commands":1}
,"clear":{"ethernet":1}
,"lmi":{"statistics":1,"async-msg-interval":1,"interface":1,"global":1,"n391":1,"n393":1,"t391":1,"t392":1,"evc":1,"parameters":1,"uni":1}
,"statistics":{"debug":1,"show":1}
,"debug":{"elmi":1}
,"async-msg-interval":{"ethernet":1}
,"global":{"ethernet":1}
,"n391":{"ethernet":1}
,"n393":{"ethernet":1}
,"t391":{"ethernet":1}
,"t392":{"service":1}
,"service":{"ma-name":1}
,"ma-name":{"show":1}
,"show":{"debugging":1,"ethernet":1}
,"debugging":{"elmi":1}
,"evc":{"show":1,"detail":1,"interface":1,"map":1}
,"detail":{"evc-ref-id":1,"evc":1}
,"evc-ref-id":{"show":1}
,"map":{"show":1}
,"parameters":{"show":1}
}
;Search.control.loadWordPairs(pairs);
