var pairs =
{
"debug":{"mstp":1}
,"mstp":{"command":1,"rstp":1,"debug":1,"cli":1,"packet":1,"protocol":1,"timer":1,"(config)":1}
,"command":{"turn":1,"enables":1,"syntax":1,"mode":1}
,"turn":{"turn":1,"debugging":1}
,"debugging":{"echoing":1,"parameter":1,"command":1,"levels":1}
,"echoing":{"data":1}
,"data":{"console":1}
,"console":{"various":1,"cli":1,"packet":1,"received":1,"detail":1}
,"various":{"levels":1}
,"levels":{"command":1,"console":1}
,"enables":{"mstp":1}
,"rstp":{"stp":1}
,"stp":{"debugging":1}
,"parameter":{"command":1}
,"syntax":{"debug":1}
,"cli":{"debug":1,"echoes":1,"(config)":1}
,"packet":{"debug":1,"echoes":1,"(config)":1}
,"protocol":{"debug":1,"detail":1,"echoes":1,"changes":1}
,"detail":{"debug":1,"parameters":1,"detailed":1,"(config)":1}
,"timer":{"debug":1,"detail":1,"echoes":1,"start":1}
,"parameters":{"echoes":1}
,"echoes":{"spanning-tree":1,"protocol":1,"timer":1}
,"spanning-tree":{"debugging":1,"commands":1,"packets":1}
,"commands":{"console":1}
,"packets":{"console":1,"transmitted":1,"protocol":1}
,"received":{"packets":1}
,"transmitted":{"packets":1}
,"changes":{"console":1}
,"detailed":{"output":1}
,"output":{"timer":1,"command":1}
,"start":{"console":1}
,"mode":{"exec":1}
,"exec":{"privileged":1,"configure":1}
,"privileged":{"exec":1}
,"configure":{"modes":1,"terminal":1}
,"modes":{"examples":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"debug":1}
}
;Search.control.loadWordPairs(pairs);
