var pairs =
{
"configuring":{"interface":1}
,"interface":{"tunnel":1,"enter":1,"mode":1}
,"tunnel":{"two":1,"create":1,"interface":1,"source":1,"destination":1,"ttl":1,"(config-if)":1,"mode":1}
,"two":{"pim-sm":1}
,"pim-sm":{"routers":1}
,"routers":{"following":1,"ipip":1}
,"following":{"shows":1}
,"shows":{"commands":1}
,"commands":{"create":1}
,"create":{"interface":1,"new":1}
,"ipip":{"mode":1,"configure":1}
,"mode":{"configure":1,"(config)":1,"(config-if)":1,"ipip":1,"interface":1}
,"configure":{"terminal":1,"mode":1,"tunnel":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"interface":1}
,"(config)":{"interface":1}
,"new":{"tunnel":1}
,"(config-if)":{"tunnel":1,"pim":1}
,"source":{"10.10.1.52":1,"address":1}
,"10.10.1.52":{"specify":1}
,"specify":{"tunnel":1}
,"address":{"(config-if)":1}
,"destination":{"10.10.3.35":1,"address":1}
,"10.10.3.35":{"specify":1}
,"ttl":{"time-to-live":1}
,"time-to-live":{"tunnel":1}
,"pim":{"sparse-mode":1,"sparse":1}
,"sparse-mode":{"enable":1}
,"enable":{"pim":1}
,"sparse":{"mode":1}
}
;Search.control.loadWordPairs(pairs);
