var pairs =
{
"trill_get_rbridge_trillsz":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"minimum":1}
,"minimum":{"acceptable":1}
,"acceptable":{"inter-rbridge":1}
,"inter-rbridge":{"link":1}
,"link":{"size":1}
,"size":{"campus":1,"return":1}
,"campus":{"proper":1}
,"proper":{"operation":1}
,"operation":{"trill":1}
,"trill":{"is-is":1,"identifier":1,"instance":1}
,"is-is":{"syntax":1}
,"syntax":{"int":1}
,"int":{"trill_get_rbridge_trillsz":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"integer":1}
,"u_int32_t":{"instance":1,"*ret)":1}
,"instance":{"u_int32_t":1,"integer":1,"output":1,"trill_api_get_error":1,"found":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"ret":1}
,"integer":{"contains":1}
,"contains":{"trill":1}
,"identifier":{"instance":1}
,"output":{"parameters":1}
,"ret":{"pointer":1}
,"pointer":{"minimum":1}
,"return":{"value":1}
,"value":{"trill_api_set_success":1}
,"trill_api_set_success":{"valid":1}
,"valid":{"instance":1}
,"trill_api_get_error":{"valid":1}
}
;Search.control.loadWordPairs(pairs);
