var pairs =
{
"enable":{"agentx":1}
,"agentx":{"source":1,"enabled":1,"snmp":1}
,"source":{"code":1}
,"code":{"install":1,".\u002Fconfigure":1,"entering":1,"built":1}
,"install":{"router":1,"enable":1}
,"router":{"software":1}
,"software":{"machine":1}
,"machine":{"unzip":1}
,"unzip":{"source-code":1}
,"source-code":{"tar":1}
,"tar":{"file":1}
,"file":{"change":1}
,"change":{"zebos-xp":1,"directory":1}
,"zebos-xp":{"directory":1}
,"directory":{"run":1,"platform\u002Fplatform":1}
,"run":{"configure":1}
,"configure":{"agentx":1}
,"enabled":{"(apart":1,"default":1}
,"(apart":{"options)":1}
,"options)":{"compile":1}
,"compile":{"code":1}
,".\u002Fconfigure":{"--enable-agentx":1}
,"--enable-agentx":{"change":1}
,"platform\u002Fplatform":{"platform":1}
,"platform":{"used":1}
,"used":{"example":1}
,"example":{"platform\u002Flinux":1}
,"platform\u002Flinux":{"compile":1}
,"entering":{"(this)":1}
,"(this)":{"command":1}
,"command":{"(s)":1}
,"(s)":{"install":1}
,"snmp":{"code":1}
,"built":{"smux":1}
,"smux":{"enabled":1}
}
;Search.control.loadWordPairs(pairs);
