var pairs =
{
"configure":{"terminal":1,"mode":1,"fixed":1,"interface":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"address":1}
,"mode":{"(config)":1,"configuring":1}
,"(config)":{"router":1}
,"router":{"bgp":1,"(10.10.10.10)":1}
,"bgp":{"200":1,"router-id":1,"neighbor":1}
,"200":{"define":1,"specifies":1}
,"define":{"routing":1,"bgp":1}
,"routing":{"process":1,"sessions":1}
,"process":{"number":1,"(config-router)":1}
,"number":{"200":1,"(config-router)":1,"(200)":1}
,"specifies":{"number":1}
,"(config-router)":{"bgp":1,"neighbor":1,"address-family":1}
,"router-id":{"10.10.10.10":1}
,"10.10.10.10":{"configure":1}
,"fixed":{"router":1}
,"(10.10.10.10)":{"bgp4":1}
,"bgp4":{"routing":1}
,"neighbor":{"fe80":1,"(r2)":1,"(config-router)":1,"configure":1,"(fe80":1}
,"fe80":{"remote-as":1,"interface":1,"(config-router)":1,"activate":1}
,"remote-as":{"200":1}
,"(r2)":{"establish":1}
,"establish":{"tcp":1}
,"tcp":{"session":1}
,"session":{"specifying":1}
,"specifying":{"link-local":1}
,"link-local":{"address":1,"neighbor":1}
,"address":{"(fe80":1,"family":1,"prefixes":1,"prefix":1}
,"(fe80":{":2)":1}
,":2)":{"number":1,"enable":1}
,"(200)":{"neighbor":1}
,"interface":{"eth0":1,"name":1}
,"eth0":{"specify":1}
,"specify":{"link-local":1}
,"name":{"neighbor":1}
,"address-family":{"ipv6":1}
,"ipv6":{"enter":1,"address":1}
,"family":{"mode":1}
,"configuring":{"routing":1}
,"sessions":{"ipv6":1}
,"prefixes":{"(config-router-af)":1}
,"(config-router-af)":{"neighbor":1}
,"activate":{"activate":1,"neighbor":1}
,"enable":{"exchange":1}
,"exchange":{"ipv6":1}
,"prefix":{"types":1}
,"types":{"neighbor":1}
}
;Search.control.loadWordPairs(pairs);
