var pairs =
{
"show":{"ipv6":1}
,"ipv6":{"mif":1}
,"mif":{"command":1,"show":1,"ifname":1,"(vrf":1,"interface":1,"owner":1,"wm0":1}
,"command":{"display":1,"syntax":1,"mode":1,"displaying":1}
,"display":{"mrib":1}
,"mrib":{"vif":1}
,"vif":{"table":1}
,"table":{"command":1,"without":1}
,"syntax":{"show":1}
,"ifname":{"show":1,"parameters":1,"interface":1}
,"(vrf":{"name":1}
,"name":{"show":1,"ifname":1,"vrf":1,"command":1}
,"parameters":{"ifname":1}
,"interface":{"name":1,"parameter":1,"mif":1}
,"vrf":{"specify":1,"name":1}
,"specify":{"vrf":1}
,"mode":{"exec":1,"example":1}
,"exec":{"privileged":1,"mode":1}
,"privileged":{"exec":1}
,"example":{"following":1}
,"following":{"sample":1}
,"sample":{"outputs":1}
,"outputs":{"command":1}
,"displaying":{"mrib":1}
,"without":{"interface":1}
,"parameter":{"show":1}
,"owner":{"uptime":1}
,"uptime":{"idx":1}
,"idx":{"module":1}
,"module":{"wm0":1}
,"wm0":{"pim-smv6":1,"interface":1}
,"pim-smv6":{"00:17:18":1,"00:19:06":1}
,"00:17:18":{"register":1,"wm1":1,"show":1}
,"register":{"00:17:18":1}
,"wm1":{"pim-smv6":1}
}
;Search.control.loadWordPairs(pairs);
