var pairs =
{
"contents":{"guide":1}
,"guide":{"contains":1}
,"contains":{"chapters":1}
,"chapters":{"chapter":1}
,"chapter":{"spanning":1,"rstp":1,"mstp":1,"rpvst":1,"disable":1,"maximum":1,"layer":1,"vlan":1,"802.1x":1,"lacp":1,"mc-lag":1,"gmrp":1,"mac":1,"gvrp":1}
,"spanning":{"tree":1}
,"tree":{"protocol":1,"configuration":1}
,"protocol":{"configuration":1}
,"configuration":{"chapter":1}
,"rstp":{"configuration":1}
,"mstp":{"configuration":1}
,"rpvst":{"configuration":1}
,"disable":{"spanning":1}
,"maximum":{"mst":1}
,"mst":{"instances":1}
,"instances":{"configuration":1}
,"layer":{"gateway":1}
,"gateway":{"port":1}
,"port":{"configuration":1}
,"vlan":{"configuration":1}
,"802.1x":{"configuration":1}
,"lacp":{"configuration":1,"peering":1}
,"peering":{"mef":1}
,"mef":{"uni":1}
,"uni":{"chapter":1}
,"mc-lag":{"configuration":1}
,"gmrp":{"configuration":1}
,"mac":{"authentication":1}
,"authentication":{"configuration":1}
,"gvrp":{"configuration":1}
}
;Search.control.loadWordPairs(pairs);
