var pairs =
{
"sub-second":{"detection":1}
,"detection":{"zebos-xp":1,"problem":1}
,"zebos-xp":{"supports":1}
,"supports":{"vrrp":1}
,"vrrp":{"version":1,"support":1,"lead":1,"router":1}
,"version":{"ipv4":1}
,"ipv4":{"ipv6":1}
,"ipv6":{"based":1}
,"based":{"rfc":1}
,"rfc":{"5798":1}
,"5798":{"allows":1}
,"allows":{"vrrp":1}
,"support":{"sub-second":1}
,"problem":{"occur":1}
,"occur":{"routing":1}
,"routing":{"protocols":1,"protocol":1}
,"protocols":{"ospf":1,"slower":1}
,"ospf":{"enabled":1}
,"enabled":{"switches":1}
,"switches":{"protocols":1,"back":1}
,"slower":{"converge":1}
,"converge":{"vrrp":1}
,"lead":{"situation":1}
,"situation":{"route":1}
,"route":{"table":1}
,"table":{"master":1}
,"master":{"vrrp":1,"thus":1}
,"router":{"completely":1}
,"completely":{"populated":1}
,"populated":{"switches":1}
,"back":{"master":1}
,"thus":{"routes":1}
,"routes":{"remote":1}
,"remote":{"networks":1}
,"networks":{"lost":1}
,"lost":{"during":1}
,"during":{"convergence":1}
,"convergence":{"time":1}
,"time":{"routing":1}
,"protocol":{"resulting":1}
,"resulting":{"dropped":1}
,"dropped":{"packets":1}
,"packets":{"traffic":1}
,"traffic":{"destined":1}
,"destined":{"networks":1}
}
;Search.control.loadWordPairs(pairs);
