var pairs =
{
"overview":{"isp":1}
,"isp":{"network":1}
,"network":{"usage":1,"often":1,"addresses":1}
,"usage":{"denial":1}
,"denial":{"service":1}
,"service":{"attack":1}
,"attack":{"outside":1}
,"outside":{"network":1}
,"often":{"packets":1}
,"packets":{"carry":1,"system":1,"unicast":1,"whose":1,"addresses":1}
,"carry":{"spoofed":1}
,"spoofed":{"source":1,"packets":1}
,"source":{"addresses":1,"address":1}
,"addresses":{"spoofed":1,"examining":1,"drops":1,"invalid":1}
,"address":{"maybe":1,"incoming":1,"fit":1}
,"maybe":{"generated":1}
,"generated":{"random":1}
,"random":{"may":1}
,"may":{"belong":1,"able":1}
,"belong":{"interior":1}
,"interior":{"network":1}
,"examining":{"source":1}
,"incoming":{"packets":1}
,"system":{"may":1}
,"able":{"filter":1}
,"filter":{"spoofed":1}
,"unicast":{"rpf":1}
,"rpf":{"check":1}
,"check":{"feature":1}
,"feature":{"exactly":1,"enabled":1}
,"exactly":{"drops":1}
,"drops":{"packets":1}
,"whose":{"source":1}
,"fit":{"legitimately":1}
,"legitimately":{"within":1,"traced":1}
,"within":{"customers":1}
,"customers":{"assigned":1}
,"assigned":{"source":1}
,"invalid":{"example":1}
,"example":{"0.0.0.0\u002F8":1}
,"0.0.0.0\u002F8":{"10.0.0.0\u002F8":1}
,"10.0.0.0\u002F8":{"127.0.0.0\u002F8":1}
,"127.0.0.0\u002F8":{"approach":1}
,"approach":{"malicious":1}
,"malicious":{"traffic":1}
,"traffic":{"effect":1}
,"effect":{"suppressed":1,"multi-homing":1}
,"suppressed":{"attacks":1}
,"attacks":{"legitimately":1}
,"traced":{"back":1}
,"back":{"source.there":1}
,"source.there":{"several":1}
,"several":{"variations":1}
,"variations":{"applying":1}
,"applying":{"ingress":1}
,"ingress":{"filtering":1,"access":1}
,"filtering":{"merits":1,"effect":1,"ingress":1}
,"merits":{"de-merits":1}
,"de-merits":{"applying":1}
,"multi-homing":{"feature":1}
,"enabled":{"proposed":1}
,"proposed":{"ways":1}
,"ways":{"implement":1}
,"implement":{"ingress":1}
,"access":{"lists":1}
,"lists":{"strict":1}
,"strict":{"reverse":1}
,"reverse":{"path":1}
,"path":{"forwarding":1,"reverse":1}
,"forwarding":{"feasible":1,"loose":1}
,"feasible":{"path":1}
,"loose":{"reverse":1}
}
;Search.control.loadWordPairs(pairs);
