var pairs =
{
"protection":{"switching":1,"modes":1,"transport":1}
,"switching":{"itu-t":1,"(ps)":1,"operates":1,"linear":1,"table":1,"directions":1,"architecture":1,"aps":1,"need":1}
,"itu-t":{"g.8031":1}
,"g.8031":{"recommendation":1}
,"recommendation":{"defines":1}
,"defines":{"linear":1}
,"linear":{"(point-to-point)":1,"protection":1,"1:1":1,"linear":1}
,"(point-to-point)":{"(one-plus-one)":1}
,"(one-plus-one)":{"1:1":1}
,"1:1":{"(one-to-one)":1,"protection":1,"aps":1,"linear":1}
,"(one-to-one)":{"protection":1}
,"(ps)":{"architectures":1}
,"architectures":{"linear":1}
,"operates":{"either":1,"bi-directional":1}
,"either":{"uni-directional":1,"usual":1,"working":1}
,"uni-directional":{"bi-directional":1,"protection":1}
,"bi-directional":{"switching":1,"without":1,"protection":1}
,"table":{"below":1}
,"below":{"shows":1}
,"shows":{"possible":1}
,"possible":{"protection":1}
,"modes":{"uni-directional":1}
,"without":{"aps":1}
,"aps":{"messaging":1,"coordination":1}
,"messaging":{"aps":1,"1:1":1,"permanent":1}
,"permanent":{"bridge":1}
,"bridge":{"head":1,"function":1,"selector":1,"source":1}
,"head":{"end":1}
,"end":{"(source)":1,"(sink)":1,"protected":1}
,"(source)":{"need":1,"protected":1}
,"need":{"coordinate":1,"aps":1,"coordinated":1}
,"coordinate":{"selector":1}
,"selector":{"positions":1,"driven":1,"managed":1,"function":1,"linear":1,"bridge":1,"sink":1}
,"positions":{"two":1}
,"two":{"ends":1}
,"ends":{"tail":1}
,"tail":{"end":1}
,"(sink)":{"selector":1,"performs":1}
,"driven":{"entirely":1}
,"entirely":{"defect":1}
,"defect":{"management":1,"identification":1}
,"management":{"example":1}
,"example":{"connectivity":1,"operator":1}
,"connectivity":{"check":1}
,"check":{"messages":1}
,"messages":{"(ccm)":1}
,"(ccm)":{"received":1}
,"received":{"working":1}
,"working":{"entity":1,"transport":1,"protection":1}
,"entity":{"tail-end":1,"capable":1,"required":1,"protection":1,"bi-directional":1,"dedicated":1,"normal":1,"however":1,"using":1,"carries":1,"aps":1}
,"tail-end":{"selector":1}
,"managed":{"operator":1}
,"operator":{"commands":1,"execute":1}
,"commands":{"example":1}
,"execute":{"manual":1}
,"manual":{"switch":1}
,"switch":{"particular":1}
,"particular":{"direction":1}
,"direction":{"transmission":1}
,"transmission":{"head":1}
,"protected":{"entity":1,"domain":1}
,"capable":{"performing":1,"selecting":1}
,"performing":{"bridge":1}
,"function":{"places":1,"capable":1}
,"places":{"copy":1}
,"copy":{"normal":1}
,"normal":{"traffic":1}
,"traffic":{"signal":1,"copied":1,"working":1,"transported":1,"source":1}
,"signal":{"onto":1,"either":1}
,"onto":{"protection":1}
,"transport":{"entity":1,"entities":1}
,"required":{"tail":1}
,"performs":{"selector":1}
,"selecting":{"normal":1}
,"usual":{"working":1}
,"directions":{"act":1,"select":1}
,"act":{"bridge":1}
,"architecture":{"protection":1,"bi-directional":1}
,"dedicated":{"working":1}
,"copied":{"fed":1}
,"fed":{"working":1}
,"entities":{"permanent":1,"transmitted":1,"made":1}
,"domain":{"traffic":1,"selection":1,"linear":1,"selector":1,"selects":1}
,"transmitted":{"simultaneously":1}
,"simultaneously":{"tail":1}
,"selection":{"working":1,"made":1}
,"made":{"based":1,"tail":1}
,"based":{"predetermined":1}
,"predetermined":{"criteria":1}
,"criteria":{"server":1}
,"server":{"defect":1}
,"identification":{"although":1}
,"although":{"selection":1}
,"coordination":{"protocol":1}
,"protocol":{"selectors":1,"linear":1,"necessary":1}
,"selectors":{"directions":1}
,"select":{"entity":1}
,"however":{"uni-directional":1,"normal":1}
,"transported":{"either":1}
,"using":{"selector":1}
,"source":{"protected":1,"sink":1,"selector":1}
,"sink":{"protected":1,"need":1,"select":1}
,"selects":{"entity":1}
,"carries":{"traffic":1}
,"coordinated":{"ensure":1}
,"ensure":{"selector":1}
}
;Search.control.loadWordPairs(pairs);
