var pairs =
{
"virtual":{"private":1,"switch":1}
,"private":{"lan":1,"wire":1}
,"lan":{"service":1}
,"service":{"(vpls)":1,"used":1,"(vpws)":1}
,"(vpls)":{"multipoint-to-multipoint":1}
,"multipoint-to-multipoint":{"layer":1}
,"layer":{"(l2)":1}
,"(l2)":{"vpn":1}
,"vpn":{"service":1}
,"used":{"interconnect":1}
,"interconnect":{"multiple":1}
,"multiple":{"ethernet":1}
,"ethernet":{"lans":1}
,"lans":{"across":1}
,"across":{"multi-protocol":1}
,"multi-protocol":{"label":1}
,"label":{"switching":1}
,"switching":{"(mpls)":1}
,"(mpls)":{"backbone":1}
,"backbone":{"vpls":1}
,"vpls":{"evolved":1,"defined":1}
,"evolved":{"logical":1}
,"logical":{"extension":1,"bridge":1}
,"extension":{"virtual":1}
,"wire":{"service":1}
,"(vpws)":{"based":1}
,"based":{"rfc":1}
,"rfc":{"4447":1}
,"4447":{"vpls":1}
,"defined":{"several":1}
,"several":{"instances":1}
,"instances":{"virtual":1}
,"switch":{"instance":1}
,"instance":{"(vsi)":1}
,"(vsi)":{"interconnected":1}
,"interconnected":{"form":1}
,"form":{"single":1}
,"single":{"logical":1}
,"bridge":{"domain":1}
}
;Search.control.loadWordPairs(pairs);
