var pairs =
{
"show":{"ethernet":1}
,"ethernet":{"cfm":1}
,"cfm":{"active-levels":1}
,"active-levels":{"command":1,"vid":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"active":1}
,"active":{"levels":1,"level":1}
,"levels":{"vid":1}
,"vid":{"specific":1,"vid":1,"(interface":1,"specify":1,"interface":1,"bridge":1}
,"specific":{"interface":1}
,"interface":{"active":1,"specify":1,"if_name":1,"name":1,"eth1":1}
,"level":{"selected":1}
,"selected":{"mip":1}
,"mip":{"creation":1}
,"creation":{"command":1}
,"syntax":{"show":1}
,"(interface":{"if_name":1}
,"if_name":{"((bridge":1,"specify":1}
,"((bridge":{"<1-32>":1}
,"<1-32>":{"backbone)":1,"specify":1}
,"backbone)":{"parameters":1}
,"parameters":{"vid":1}
,"specify":{"vlan":1,"interface":1,"bridge":1}
,"vlan":{"vid":1,"<2-4094>":1}
,"<2-4094>":{"interface":1}
,"name":{"bridge":1}
,"bridge":{"specify":1,"<1-32>":1,"backbone":1,"command":1,"show":1}
,"backbone":{"backbone":1,"bridge":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"show":1}
,"eth1":{"bridge":1}
}
;Search.control.loadWordPairs(pairs);
