var pairs =
{
"oam_mplstp_api_itut_rmep_create":{"function":1,"(u_int32_t":1}
,"function":{"creates":1,"succeeds":1,"fails":1}
,"creates":{"remote":1}
,"remote":{"mep":1}
,"mep":{"mpls-tp":1,"already":1}
,"mpls-tp":{"maintenance":1}
,"maintenance":{"entity":1}
,"entity":{"updates":1}
,"updates":{"allowed":1}
,"allowed":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"oam_mplstp_api_itut_rmep_create":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int16_t":1,"instance":1}
,"u_int16_t":{"rmp_id":1,"mp_id":1}
,"rmp_id":{"char":1,"rmp":1,"valid":1}
,"char":{"*cc":1,"*icc":1,"*meg_name":1,"*local_meg_name)":1}
,"*cc":{"char":1,"country":1}
,"*icc":{"char":1,"carrier":1}
,"*meg_name":{"u_int8_t":1}
,"u_int8_t":{"direction":1}
,"direction":{"u_int16_t":1,"direction":1,"mp_id":1}
,"mp_id":{"char":1,"integer":1,"rmp_id":1}
,"*local_meg_name)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"instance":{"rmp_id":1}
,"rmp":{"*cc":1}
,"country":{"code":1}
,"code":{"*icc":1,"meg_name":1}
,"carrier":{"code":1}
,"meg_name":{"pointer":1,"null":1}
,"pointer":{"meg":1,"containing":1}
,"meg":{"name":1,"entry":1}
,"name":{"direction":1,"output":1,"exceeds":1}
,"integer":{"containing":1}
,"containing":{"*local_meg_name":1,"local":1}
,"*local_meg_name":{"pointer":1}
,"local":{"meg":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"cfm_api_success":1}
,"cfm_api_success":{"function":1}
,"succeeds":{"mplstp_api_failure":1}
,"mplstp_api_failure":{"function":1}
,"fails":{"mplstp_err_vr_not_exists":1,"mplstp_err_me_service_type_not_match":1}
,"mplstp_err_vr_not_exists":{"virtual":1}
,"virtual":{"router":1}
,"router":{"cannot":1}
,"cannot":{"found":1,"converted":1}
,"found":{"mplstp_err_meg_name_invalid":1,"mplstp_err_me_entry_not_exists":1}
,"mplstp_err_meg_name_invalid":{"meg_name":1}
,"null":{"mplstp_err_meg_name_exceeds_max_len":1,"exceeds":1}
,"mplstp_err_meg_name_exceeds_max_len":{"meg":1}
,"exceeds":{"maximum":1}
,"maximum":{"length":1}
,"length":{"mplstp_err_invalid_mp_id":1,"cannot":1}
,"mplstp_err_invalid_mp_id":{"mp_id":1}
,"valid":{"mplstp_err_cc_name_invalid":1}
,"mplstp_err_cc_name_invalid":{"null":1}
,"converted":{"uppercase":1}
,"uppercase":{"mplstp_err_icc_name_invalid":1,"mplstp_err_meg_entry_not_exists":1}
,"mplstp_err_icc_name_invalid":{"icc":1}
,"icc":{"null":1}
,"mplstp_err_meg_entry_not_exists":{"meg":1}
,"entry":{"cannot":1,"exist":1}
,"mplstp_err_me_entry_not_exists":{"entry":1}
,"exist":{"mplstp_err_rmep_entry_exists":1}
,"mplstp_err_rmep_entry_exists":{"remote":1}
,"already":{"exists":1}
,"exists":{"mplstp_err_rmep_create_failed":1}
,"mplstp_err_rmep_create_failed":{"memory":1}
,"memory":{"deallocation":1}
,"deallocation":{"fails":1}
,"mplstp_err_me_service_type_not_match":{"service":1}
,"service":{"type":1}
,"type":{"match":1}
,"match":{"mplstp_err_me_entry_not_exists":1}
}
;Search.control.loadWordPairs(pairs);
