var pairs =
{
"nsm_mpls_api_max_label_val_set":{"function":1,"(struct":1}
,"function":{"sets":1,"succeeds":1}
,"sets":{"maximum":1}
,"maximum":{"label":1}
,"label":{"value":1,"space":1}
,"value":{"interfaces":1,"output":1,"less":1}
,"interfaces":{"syntax":1}
,"syntax":{"int":1}
,"int":{"nsm_mpls_api_max_label_val_set":1}
,"(struct":{"nsm_master":1}
,"nsm_master":{"*nm":1}
,"*nm":{"u_int32_t":1}
,"u_int32_t":{"val)":1}
,"val)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"pointer":1,"none":1}
,"pointer":{"nsm":1}
,"nsm":{"master":1}
,"master":{"structure":1}
,"structure":{"val":1}
,"val":{"maximum":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_success":1}
,"nsm_success":{"function":1}
,"succeeds":{"nsm_err_ls_invalid_max_label":1}
,"nsm_err_ls_invalid_max_label":{"label":1}
,"less":{"minimum":1}
,"minimum":{"allowable":1}
,"allowable":{"nsm_err_ls_in_use":1}
,"nsm_err_ls_in_use":{"label":1}
}
;Search.control.loadWordPairs(pairs);
