var pairs =
{
"intermediate":{"system":1}
,"system":{"intermediate":1,"chapter":1,"(is-is)":1}
,"chapter":{"describes":1,"overview":1}
,"describes":{"interaction":1}
,"interaction":{"intermediate":1,"is-is":1}
,"(is-is)":{"bfd":1}
,"bfd":{"included":1,"information":1}
,"included":{"chapter":1}
,"overview":{"covering":1}
,"covering":{"interaction":1}
,"is-is":{"bfd":1,"command":1}
,"information":{"interfaces":1}
,"interfaces":{"two":1}
,"two":{"protocols":1}
,"protocols":{"along":1}
,"along":{"messages":1}
,"messages":{"exchanged":1}
,"exchanged":{"description":1}
,"description":{"is-is":1}
,"command":{"functions":1}
,"functions":{"support":1}
,"support":{"bfd":1}
}
;Search.control.loadWordPairs(pairs);
