var pairs =
{
"ipv6":{"pim":1}
,"pim":{"register-source":1,"enabled":1,"(vrf":1}
,"register-source":{"command":1,"ifname":1,"x:x":1,"ipv6":1,"parameters":1,"3ffe:406":1}
,"command":{"configure":1,"syntax":1,"mode":1}
,"configure":{"source":1,"mode":1,"terminal":1}
,"source":{"address":1,"host":1,"register":1}
,"address":{"register":1,"address":1,"rpf":1,"reachable":1,"send":1,"usually":1,"physical":1,"advertised":1,"used":1}
,"register":{"packets":1}
,"packets":{"sent":1,"ifname":1,"command":1}
,"sent":{"overriding":1,"reset":1}
,"overriding":{"default":1}
,"default":{"source":1}
,"rpf":{"interface":1}
,"interface":{"toward":1,"address":1,"configured":1,"used":1}
,"toward":{"source":1}
,"host":{"option":1,"configured":1}
,"option":{"remove":1}
,"remove":{"source":1}
,"reset":{"default":1}
,"configured":{"address":1,"require":1}
,"reachable":{"address":1}
,"send":{"corresponding":1}
,"corresponding":{"register-stop":1}
,"register-stop":{"messages":1}
,"messages":{"response":1}
,"response":{"address":1}
,"usually":{"loopback":1}
,"loopback":{"interface":1}
,"physical":{"addresses":1}
,"addresses":{"address":1}
,"advertised":{"unicast":1}
,"unicast":{"routing":1}
,"routing":{"protocols":1}
,"protocols":{"interface":1}
,"require":{"pim":1}
,"enabled":{"command":1}
,"syntax":{"ipv6":1}
,"ifname":{"ipv6":1,"name":1}
,"x:x":{":x:x":1}
,":x:x":{"ipv6":1,"address":1}
,"(vrf":{"name":1}
,"name":{"register-source":1,"specify":1,"vpn":1,"interface":1}
,"parameters":{"vrf":1}
,"vrf":{"vpn":1}
,"vpn":{"routing\u002Fforwarding":1}
,"routing\u002Fforwarding":{"instance":1}
,"instance":{"name":1,"x:x":1}
,"specify":{"name":1}
,"used":{"source":1}
,"mode":{"configure":1,"examples":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"ipv6":1}
,"3ffe:406":{"configure":1}
}
;Search.control.loadWordPairs(pairs);
