var pairs =
{
"match":{"next-hop":1}
,"next-hop":{"command":1,"address":1,"(<1-199>":1,"mylist":1}
,"command":{"specify":1,"disable":1,"syntax":1,"mode":1}
,"specify":{"next-hop":1,"access-list":1}
,"address":{"matched":1}
,"matched":{"route-map":1}
,"route-map":{"route":1,"mode":1,"rmap1":1}
,"route":{"specified":1}
,"specified":{"policies":1,"routing":1}
,"policies":{"specified":1,"enable":1,"overrides":1}
,"routing":{"protocols":1,"tables":1}
,"protocols":{"setting":1}
,"setting":{"policies":1}
,"enable":{"packets":1}
,"packets":{"different":1}
,"different":{"routes":1}
,"routes":{"depending":1}
,"depending":{"length":1}
,"length":{"content":1}
,"content":{"packet":1}
,"packet":{"forwarding":1}
,"forwarding":{"based":1,"specified":1}
,"based":{"configured":1}
,"configured":{"policies":1}
,"overrides":{"packet":1}
,"tables":{"parameter":1}
,"parameter":{"command":1}
,"disable":{"function":1}
,"function":{"command":1}
,"syntax":{"match":1}
,"(<1-199>":{"<1300-2699>":1}
,"<1300-2699>":{"word)":1,"word":1,"specify":1}
,"word)":{"match":1}
,"word":{"parameters":1,"specify":1}
,"parameters":{"word":1}
,"access-list":{"name":1,"number":1}
,"name":{"<1-199>":1}
,"<1-199>":{"specify":1}
,"number":{"(standard":1,"(expanded":1}
,"(standard":{"range)":1}
,"range)":{"<1300-2699>":1,"command":1}
,"(expanded":{"range)":1}
,"mode":{"route-map":1,"examples":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"route-map":1}
,"rmap1":{"permit":1}
,"permit":{"(config-route-map)":1}
,"(config-route-map)":{"match":1}
}
;Search.control.loadWordPairs(pairs);
