var pairs =
{
"configuring":{"layer":1}
,"layer":{"interfaces":1,"ports":1,"interface":1,"port":1}
,"interfaces":{"switch-only":1,"layer":1,"configured":1,"configure":1}
,"switch-only":{"mode":1}
,"mode":{"interfaces":1,"example":1,"(config)":1,"(config-if)":1}
,"ports":{"default":1}
,"default":{"hybrid":1,"interfaces":1}
,"hybrid":{"switch":1}
,"switch":{"router":1}
,"router":{"important":1}
,"important":{"understand":1}
,"understand":{"default":1}
,"configured":{"routed":1}
,"routed":{"interfaces":1}
,"configure":{"layer":1,"using":1,"terminal":1,"mode":1,"enter":1,"eth1":1}
,"interface":{"(switched":1,"mode":1,"eth0":1,"configure":1}
,"(switched":{"interface)":1}
,"interface)":{"explicitly":1}
,"explicitly":{"configure":1}
,"using":{"switchport":1}
,"switchport":{"command":1,"configure":1}
,"command":{"interface":1}
,"example":{"configure":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"interface":1}
,"(config)":{"interface":1}
,"eth0":{"specify":1}
,"specify":{"interface":1}
,"(config-if)":{"switchport":1,"shutdown":1}
,"eth1":{"layer":1}
,"port":{"(config-if)":1}
,"shutdown":{"start":1}
,"start":{"interface":1}
}
;Search.control.loadWordPairs(pairs);
