var pairs =
{
"shortest":{"path":1}
,"path":{"bridging":1,"tree":1,"vlan":1,"spts":1,"trees":1}
,"bridging":{"-vid":1,"q-in-q":1}
,"-vid":{"vlan":1}
,"vlan":{"handled":1,"identifier)":1,"header":1,"headers":1,"spbv":1}
,"handled":{"spbv":1}
,"spbv":{"uses":1,"frame":1,"region":1,"adds":1,"vlan":1,"registrations":1}
,"uses":{"shortest":1,"shared":1}
,"tree":{"(spt)":1,"context":1}
,"(spt)":{"spvid":1,"rooted":1}
,"spvid":{"(shortest":1,"registered":1,"corresponding":1,"egress":1,"translated":1,"frames":1}
,"(shortest":{"path":1}
,"identifier)":{"assigned":1}
,"assigned":{"(manually":1,"spvid-to-spt":1}
,"(manually":{"automatically)":1}
,"automatically)":{"spt":1}
,"spt":{"spvid":1,"bridge":1,"supports":1,"bridges":1,"region":1}
,"registered":{"isis-spb":1}
,"isis-spb":{"control":1,"spbv":1,"provide":1}
,"control":{"plane":1}
,"plane":{"along":1}
,"along":{"shortest":1}
,"rooted":{"spt":1}
,"bridge":{"assigned":1,"path":1,"contain":1,"permits":1}
,"spvid-to-spt":{"mapping":1}
,"mapping":{"information":1}
,"information":{"sent":1}
,"sent":{"bridges":1}
,"bridges":{"using":1,"within":1}
,"using":{"isis-spb":1,"is-is":1}
,"frame":{"format":1,"two":1,"s-tag":1,"translated":1}
,"format":{"based":1,"inserts":1}
,"based":{"ieee":1}
,"ieee":{"802.1ad":1}
,"802.1ad":{"called":1}
,"called":{"provider":1}
,"provider":{"bridging":1}
,"q-in-q":{"frame":1}
,"inserts":{"additional":1}
,"additional":{"vlan":1}
,"header":{"single":1,"ingress":1}
,"single":{"802.1q":1}
,"802.1q":{"(virtual":1}
,"(virtual":{"lans)":1}
,"lans)":{"ethernet":1}
,"ethernet":{"frame":1,"header":1}
,"two":{"types":1}
,"types":{"vlan":1}
,"headers":{"c-tag":1}
,"c-tag":{"(customer":1,"s-tag":1}
,"(customer":{"tag)":1}
,"tag)":{"inner":1,"outer":1}
,"inner":{"tag":1}
,"tag":{"closest":1,"spvid":1}
,"closest":{"payload":1,"ethernet":1}
,"payload":{"portion":1}
,"portion":{"frame":1}
,"s-tag":{"(service":1,"customer":1,"spbv":1,"removed":1}
,"(service":{"tag)":1}
,"outer":{"tag":1}
,"ingress":{"spbv":1}
,"region":{"vid":1,"spvid":1,"mac":1,"symmetric":1,"advertised":1,"using":1}
,"vid":{"c-tag":1,"customer":1}
,"customer":{"frame":1,"frames":1}
,"translated":{"spvid":1,"back":1}
,"corresponding":{"spt":1}
,"supports":{"vid":1}
,"frames":{"contain":1,"forwarded":1}
,"contain":{"c-tag":1,"different":1}
,"adds":{"tag":1}
,"egress":{"spbv":1}
,"back":{"original":1}
,"original":{"vid":1}
,"removed":{"spbv":1}
,"shared":{"learning":1,"vlans":1}
,"learning":{"among":1,"filtering":1,"required":1,"outside":1}
,"among":{"spvids":1}
,"spvids":{"support":1}
,"support":{"given":1}
,"given":{"spbv":1,"spt":1}
,"mac":{"addresses":1,"registration":1}
,"addresses":{"end":1}
,"end":{"stations":1}
,"stations":{"learned":1}
,"learned":{"bridge":1}
,"spts":{"determined":1}
,"determined":{"isis-spb":1}
,"provide":{"symmetric":1}
,"symmetric":{"bidirectional":1,"means":1}
,"bidirectional":{"paths":1}
,"paths":{"pair":1,"directions":1,"used":1,"essential":1}
,"pair":{"spt":1}
,"within":{"spt":1}
,"means":{"paths":1}
,"directions":{"paths":1}
,"used":{"unicast":1}
,"unicast":{"multicast":1}
,"multicast":{"traffic":1,"groups":1}
,"traffic":{"making":1}
,"making":{"congruent":1}
,"congruent":{"congruency":1}
,"congruency":{"paths":1}
,"essential":{"allow":1}
,"allow":{"shared":1}
,"filtering":{"database":1}
,"database":{"shared":1}
,"vlans":{"shared":1,"traditional":1}
,"required":{"frames":1}
,"forwarded":{"given":1,"spt":1}
,"different":{"spvid":1}
,"permits":{"properly":1}
,"properly":{"constructed":1}
,"constructed":{"mesh":1,"unidirectional":1}
,"mesh":{"shortest":1}
,"trees":{"constructed":1}
,"unidirectional":{"vlans":1}
,"traditional":{"flooding":1}
,"flooding":{"learning":1}
,"outside":{"spanning":1}
,"spanning":{"tree":1}
,"context":{"existing":1}
,"existing":{"mac":1}
,"registration":{"protocols":1}
,"protocols":{"multicast":1}
,"groups":{"interoperate":1}
,"interoperate":{"spbv":1}
,"registrations":{"received":1}
,"received":{"edge":1}
,"edge":{"spbv":1}
,"advertised":{"throughout":1}
,"throughout":{"region":1}
}
;Search.control.loadWordPairs(pairs);
