var pairs =
{
"rip":{"authentication":1,"packet":1}
,"authentication":{"string":1,"single":1,"command":1,"commands":1}
,"string":{"command":1,"password":1,"line":1,"parameters":1,"guest":1}
,"command":{"specify":1,"disable":1,"related":1,"syntax":1,"mode":1}
,"specify":{"authentication":1,"password":1}
,"password":{"used":1,"single":1,"configure":1}
,"used":{"key":1}
,"key":{"configure":1,"multiple":1,"interface":1,"command":1}
,"configure":{"authentication":1,"terminal":1}
,"single":{"key":1}
,"multiple":{"keys":1}
,"keys":{"different":1}
,"different":{"times":1}
,"times":{"command":1}
,"interface":{"parameter":1,"mode":1,"eth1":1,"string":1}
,"parameter":{"command":1}
,"disable":{"feature":1}
,"feature":{"appendix":1}
,"appendix":{"routing":1}
,"routing":{"information":1}
,"information":{"protocol":1}
,"protocol":{"authentication":1}
,"related":{"authentication":1}
,"commands":{"command":1}
,"syntax":{"rip":1}
,"line":{"rip":1,"specify":1}
,"parameters":{"line":1}
,"mode":{"interface":1,"examples":1}
,"examples":{"following":1}
,"following":{"example":1}
,"example":{"interface":1}
,"eth1":{"configured":1,"(config-if)":1}
,"configured":{"authentication":1}
,"guest":{"receiving":1}
,"receiving":{"rip":1}
,"packet":{"interface":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"(config-if)":{"rip":1}
}
;Search.control.loadWordPairs(pairs);
