var pairs =
{
"isis_set_sys_type":{"call":1,"(u_int32_t":1}
,"call":{"sets":1}
,"sets":{"system":1}
,"system":{"type":1}
,"type":{"instance":1,"is-is":1}
,"instance":{"is-is":1,"u_int32_t":1,"val":1,"level1is":1,"exist":1,"invalid":1,"already":1,"found":1}
,"is-is":{"protocol":1,"instance":1}
,"protocol":{"syntax":1}
,"syntax":{"int":1}
,"int":{"isis_set_sys_type":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1,"instance":1}
,"u_int32_t":{"instance":1,"val)":1}
,"val)":{"input":1}
,"input":{"parameter":1}
,"parameter":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1,"exist":1}
,"default":{"value":1}
,"value":{"non-vr":1,"isis_api_set_err_vr_not_exist":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"val":{"type":1}
,"level1is":{"level2is":1}
,"level2is":{"level1l2is":1}
,"level1l2is":{"output":1}
,"output":{"parameter":1}
,"none":{"return":1}
,"return":{"value":1}
,"isis_api_set_err_vr_not_exist":{"virtual":1}
,"exist":{"isis_api_set_err_instance_not_exist":1,"isis_api_set_err_invalid_is_type":1}
,"isis_api_set_err_instance_not_exist":{"is-is":1}
,"isis_api_set_err_invalid_is_type":{"type":1}
,"invalid":{"isis_api_set_err_l2_instance_exist":1}
,"isis_api_set_err_l2_instance_exist":{"instance":1}
,"already":{"exists":1}
,"exists":{"isis_api_set_success":1}
,"isis_api_set_success":{"complete":1}
,"complete":{"isis_api_set_error":1,"instance":1}
,"isis_api_set_error":{"complete":1}
}
;Search.control.loadWordPairs(pairs);
