var pairs =
{
"g8031":{"set-nr":1,"configure":1}
,"set-nr":{"command":1,"(null-null":1,"null-null":1}
,"command":{"force":1,"used":1,"syntax":1,"mode":1}
,"force":{"near-end":1}
,"near-end":{"state":1,"far-end":1}
,"state":{"request":1,"machines":1}
,"request":{"(nr)":1}
,"(nr)":{"given":1}
,"given":{"signal":1}
,"signal":{"fields":1,"equals":1}
,"fields":{"command":1}
,"used":{"near-end":1}
,"far-end":{"state":1}
,"machines":{"cannot":1}
,"cannot":{"synchronize":1}
,"synchronize":{"operator":1}
,"operator":{"intervention":1}
,"intervention":{"required":1}
,"required":{"resolve":1}
,"resolve":{"deadlock":1}
,"deadlock":{"command":1}
,"syntax":{"g8031":1}
,"(null-null":{"normal-normal":1}
,"normal-normal":{"null-normal)":1,"requested":1}
,"null-normal)":{"parameters":1}
,"parameters":{"null-null":1}
,"null-null":{"requested":1}
,"requested":{"signal":1}
,"equals":{"null":1,"normal":1}
,"null":{"bridged":1,"normal-normal":1}
,"bridged":{"signal":1}
,"normal":{"bridged":1,"null-normal":1,"command":1}
,"null-normal":{"requested":1}
,"mode":{"g8031":1,"examples":1}
,"configure":{"switching":1,"terminal":1}
,"switching":{"mode":1,"eps-id":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"g8031":1}
,"eps-id":{"bridge":1}
,"bridge":{"(g8031-config-switching)":1}
,"(g8031-config-switching)":{"g8031":1}
}
;Search.control.loadWordPairs(pairs);
