var pairs =
{
"cspf-retry-timer":{"command":1,"<1-600>":1,"parameter":1,"(config)":1}
,"command":{"specify":1,"helps":1,"remove":1,"syntax":1,"mode":1}
,"specify":{"time":1}
,"time":{"retry":1}
,"retry":{"cspf":1,"timer":1}
,"cspf":{"carry":1,"retry":1,"calculations":1}
,"carry":{"request":1}
,"request":{"received":1}
,"received":{"rsvp":1}
,"rsvp":{"command":1}
,"helps":{"identify":1}
,"identify":{"attributes":1}
,"attributes":{"frr":1}
,"frr":{"backup":1}
,"backup":{"lsp":1}
,"lsp":{"facility-backup":1}
,"facility-backup":{"protection":1}
,"protection":{"method":1}
,"method":{"parameter":1}
,"parameter":{"command":1,"<1-600>":1}
,"remove":{"cspf":1}
,"timer":{"command":1}
,"syntax":{"cspf-retry-timer":1}
,"<1-600>":{"cspf-retry-timer":1,"timeout":1}
,"timeout":{"successive":1}
,"successive":{"retries":1}
,"retries":{"seconds":1}
,"seconds":{"default":1}
,"default":{"default":1,"retry-timer":1}
,"retry-timer":{"configuration":1}
,"configuration":{"defined":1}
,"defined":{"cspf":1}
,"calculations":{"timer":1}
,"mode":{"bypass":1,"example":1}
,"bypass":{"mode":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"rsvp-bypass":1}
,"rsvp-bypass":{"(config-bypass)":1}
,"(config-bypass)":{"cspf-retry-timer":1}
}
;Search.control.loadWordPairs(pairs);
