var pairs =
{
"record":{"command":1,"object":1,"parameters":1}
,"command":{"enable":1,"disable":1,"syntax":1,"mode":1}
,"enable":{"recording":1}
,"recording":{"route":1,"routes":1}
,"route":{"taken":1,"record":1}
,"taken":{"path":1}
,"path":{"reservation":1}
,"reservation":{"request":1}
,"request":{"(resv)":1}
,"(resv)":{"messages":1}
,"messages":{"messages":1,"confirm":1}
,"confirm":{"establishment":1}
,"establishment":{"reservations":1}
,"reservations":{"identifies":1}
,"identifies":{"errors":1}
,"errors":{"routes":1}
,"routes":{"recorded":1,"command":1}
,"recorded":{"means":1,"default":1}
,"means":{"route":1}
,"object":{"(rro)":1}
,"(rro)":{"rsvp":1}
,"rsvp":{"message":1,"bypass":1}
,"message":{"no-record":1}
,"no-record":{"command":1}
,"disable":{"recording":1}
,"syntax":{"record":1}
,"parameters":{"none":1}
,"none":{"default":1}
,"default":{"routes":1,"command":1}
,"mode":{"rsvp":1,"examples":1}
,"bypass":{"mode":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"rsvp-bypass":1}
,"rsvp-bypass":{"bypassname":1}
,"bypassname":{"(config-trunk)":1}
,"(config-trunk)":{"record":1}
}
;Search.control.loadWordPairs(pairs);
