var pairs =
{
"mstp_api_set_port_p2p":{"function":1,"(char":1}
,"function":{"sets":1,"succeeds":1,"fails":1}
,"sets":{"link":1}
,"link":{"type":1}
,"type":{"port":1}
,"port":{"syntax":1,"point-to-point":1,"mirror":1}
,"syntax":{"int":1}
,"int":{"mstp_api_set_port_p2p":1,"is_p2p)":1}
,"(char":{"*name":1}
,"*name":{"char":1}
,"char":{"*ifname":1}
,"*ifname":{"int":1}
,"is_p2p)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"name":1,"none":1}
,"name":{"name":1,"bridge":1,"is_p2p":1}
,"bridge":{"ifname":1}
,"ifname":{"interface":1}
,"interface":{"name":1}
,"is_p2p":{"whether":1}
,"whether":{"port":1}
,"point-to-point":{"possible":1}
,"possible":{"values":1}
,"values":{"(unset)":1,"result_ok":1}
,"(unset)":{"smi_mstp_port_p2p":1}
,"smi_mstp_port_p2p":{"(enable":1}
,"(enable":{"p2p)":1}
,"p2p)":{"mstp_admin_link_type_auto":1}
,"mstp_admin_link_type_auto":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"result_ok":{"function":1}
,"succeeds":{"result_error":1}
,"result_error":{"function":1}
,"fails":{"mstp_err_if_pmirror_set":1}
,"mstp_err_if_pmirror_set":{"port":1}
,"mirror":{"enabled":1}
,"enabled":{"interface":1}
}
;Search.control.loadWordPairs(pairs);
