var pairs =
{
"hal_vlan_del_pro_edge_port":{"function":1,"(char":1}
,"function":{"configures":1,"succeeds":1}
,"configures":{"untagged":1}
,"untagged":{"vid":1}
,"vid":{"egress":1}
,"egress":{"provider":1}
,"provider":{"edge":1}
,"edge":{"port":1}
,"port":{"syntax":1,"output":1}
,"syntax":{"int":1}
,"int":{"hal_vlan_del_pro_edge_port":1,"ifindex":1}
,"(char":{"*name":1}
,"*name":{"unsigned":1}
,"unsigned":{"int":1,"short":1}
,"ifindex":{"unsigned":1,"interface":1}
,"short":{"svid)":1}
,"svid)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"name":1,"none":1}
,"name":{"bridge":1,"ifindex":1}
,"bridge":{"name":1}
,"interface":{"index":1}
,"index":{"svid":1}
,"svid":{"vlan":1}
,"vlan":{"provider":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"hal_err_vlan_port_not_exists":1}
,"hal_err_vlan_port_not_exists":{"hal_err_vlan_not_exists":1}
,"hal_err_vlan_not_exists":{"hal_success":1}
,"hal_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
