var pairs =
{
"validation":{"dut":1}
,"dut":{"vrrp":1}
,"vrrp":{"vrrp":1,"version":1,"interface":1}
,"version":{"vmac":1}
,"vmac":{"enabled":1}
,"enabled":{"backward":1,"address":1}
,"backward":{"compatibility":1}
,"compatibility":{"enabled":1}
,"address":{"family":1,"5.5.5.190":1}
,"family":{"ipv4":1}
,"ipv4":{"vrrp":1,"interface":1}
,"interface":{"eth1":1}
,"eth1":{"state":1,"joined":1}
,"state":{"adminup":1}
,"adminup":{"-master":1,"-backup":1}
,"-master":{"virtual":1}
,"virtual":{"address":1}
,"5.5.5.190":{"(not-owner)":1}
,"(not-owner)":{"priority":1}
,"priority":{"100":1}
,"100":{"advertisement":1,"centi":1}
,"advertisement":{"interval":1}
,"interval":{"100":1,"sec":1}
,"centi":{"sec":1}
,"sec":{"master":1,"skew":1,"accept":1,"preempt":1}
,"master":{"advertisement":1}
,"skew":{"time":1}
,"time":{"centi":1}
,"accept":{"mode":1}
,"mode":{"false":1,"true":1}
,"false":{"preempt":1}
,"preempt":{"mode":1}
,"true":{"multicast":1}
,"multicast":{"membership":1}
,"membership":{"ipv4":1}
,"joined":{"sd-1":1}
,"sd-1":{"vrrp":1}
,"-backup":{"virtual":1}
}
;Search.control.loadWordPairs(pairs);
