var pairs =
{
"rsvp_snmp_get_tn_is_if":{"function":1,"(u_int32_t":1}
,"function":{"gets":1,"succeeds":1}
,"gets":{"whether":1}
,"whether":{"tunnel":1}
,"tunnel":{"corresponds":1,"index":1,"instance":1}
,"corresponds":{"interface":1}
,"interface":{"represented":1}
,"represented":{"interfaces":1}
,"interfaces":{"group":1}
,"group":{"table":1}
,"table":{"object":1}
,"object":{"supported":1}
,"supported":{"ret":1}
,"ret":{"always":1,"constant":1}
,"always":{"rsvp_false":1}
,"rsvp_false":{"syntax":1,"return":1}
,"syntax":{"u_int32_t":1}
,"u_int32_t":{"rsvp_snmp_get_tn_is_if":1,"*inst_ix":1,"*ret)":1}
,"(u_int32_t":{"*tn_ix":1}
,"*tn_ix":{"u_int32_t":1}
,"*inst_ix":{"struct":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"*ing_id":1,"*eg_id":1}
,"*ing_id":{"struct":1}
,"*eg_id":{"u_int32_t":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"tn_ix":1,"ret":1}
,"tn_ix":{"tunnel":1}
,"index":{"inst_ix":1,"ing_id":1}
,"inst_ix":{"instance":1}
,"instance":{"index":1,"found":1}
,"ing_id":{"ingress":1}
,"ingress":{"lsr":1}
,"lsr":{"identifier":1}
,"identifier":{"eg_id":1,"output":1}
,"eg_id":{"egress":1}
,"egress":{"lsr":1}
,"output":{"parameters":1}
,"constant":{"rsvpd\u002Frsvpd.h":1}
,"rsvpd\u002Frsvpd.h":{"rsvp_false":1}
,"return":{"value":1}
,"value":{"rsvp_api_get_success":1}
,"rsvp_api_get_success":{"function":1}
,"succeeds":{"rsvp_api_get_error":1}
,"rsvp_api_get_error":{"tunnel":1}
}
;Search.control.loadWordPairs(pairs);
