var pairs =
{
"rsvp_snmp_set_tn_resource_weight":{"function":1,"(int":1}
,"function":{"sets":1,"succeeds":1}
,"sets":{"resource":1}
,"resource":{"weight":1,"table":1,"found":1}
,"weight":{"syntax":1,"output":1}
,"syntax":{"u_int32_t":1}
,"u_int32_t":{"rsvp_snmp_set_tn_resource_weight":1,"resourceweight)":1}
,"(int":{"rs_ix":1}
,"rs_ix":{"u_int32_t":1,"resource":1}
,"resourceweight)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"rs_ix":1,"none":1}
,"table":{"index":1}
,"index":{"resourceweight":1}
,"resourceweight":{"resource":1,"invalid":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"rsvp_api_set_success":1}
,"rsvp_api_set_success":{"function":1}
,"succeeds":{"rsvp_api_set_error":1}
,"rsvp_api_set_error":{"resource":1}
,"found":{"row":1}
,"row":{"staus":1}
,"staus":{"active":1}
,"active":{"tunnel":1,"resourceweight":1}
,"tunnel":{"active":1}
,"invalid":{"value":1}
}
;Search.control.loadWordPairs(pairs);
