var pairs =
{
"validation":{"following":1}
,"following":{"commands":1,"command":1}
,"commands":{"used":1}
,"used":{"verify":1}
,"verify":{"logging":1}
,"logging":{"available":1}
,"available":{"privileged":1}
,"privileged":{"(pvr)":1}
,"(pvr)":{"users":1}
,"users":{"show":1}
,"show":{"vlog":1}
,"vlog":{"show":1,"clients":1,"virtual-routers":1,"terminals":1}
,"clients":{"show":1}
,"virtual-routers":{"show":1}
,"terminals":{"debug":1}
,"debug":{"messages":1}
,"messages":{"viewed":1,"terminal":1}
,"viewed":{"terminal":1}
,"terminal":{"entering":1,"monitor":1,"stopped":1}
,"entering":{"following":1}
,"command":{"terminal":1}
,"monitor":{"viewing":1}
,"viewing":{"debug":1}
,"stopped":{"entering":1}
}
;Search.control.loadWordPairs(pairs);
