var pairs =
{
"bgp":{"as-local-count":1,"100":1}
,"as-local-count":{"command":1,"<2-64>":1,"(config)":1}
,"command":{"number":1,"stop":1,"syntax":1,"mode":1}
,"number":{"times":1}
,"times":{"local-as":1}
,"local-as":{"(autonomous":1,"prepended":1}
,"(autonomous":{"system)":1}
,"system)":{"prepended":1}
,"prepended":{"parameter":1,"command":1}
,"parameter":{"command":1,"<2-64>":1}
,"stop":{"prepending":1}
,"prepending":{"local":1}
,"local":{"count":1}
,"count":{"command":1}
,"syntax":{"bgp":1}
,"<2-64>":{"bgp":1,"parameter":1,"number":1}
,"mode":{"router":1,"examples":1}
,"router":{"mode":1,"bgp":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"100":{"(config-router)":1}
,"(config-router)":{"bgp":1}
}
;Search.control.loadWordPairs(pairs);
