var pairs =
{
"ripng_timers_unset":{"call":1,"(u_int32_t":1}
,"call":{"resets":1,"successful":1}
,"resets":{"three":1}
,"three":{"timers":1}
,"timers":{"default":1}
,"default":{"values":1,"value":1}
,"values":{"update":1,"rip_api_set_err_process_not_exist":1}
,"update":{"timer":1}
,"timer":{"seconds":1,"180":1,"120":1,"syntax":1}
,"seconds":{"timeout":1,"garbage":1,"function":1}
,"timeout":{"timer":1}
,"180":{"seconds":1}
,"garbage":{"timer":1}
,"120":{"seconds":1}
,"function":{"called":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"timer":1}
,"syntax":{"int":1}
,"int":{"ripng_timers_unset":1,"instance)":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"int":1,"virtual":1}
,"instance)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1,"exist":1}
,"value":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"parameter":1}
,"parameter":{"instance":1}
,"instance":{"instance":1,"number":1,"cannot":1}
,"number":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"rip_api_set_err_process_not_exist":{"instance":1}
,"cannot":{"found":1}
,"found":{"rip_api_set_err_vr_not_exist":1}
,"rip_api_set_err_vr_not_exist":{"virtual":1}
,"exist":{"rip_api_set_success":1}
,"rip_api_set_success":{"call":1}
}
;Search.control.loadWordPairs(pairs);
