var pairs =
{
"ospf6_get_nbr_events":{"function":1,"(char":1}
,"function":{"gets":1,"fails":1,"succeeds":1}
,"gets":{"number":1}
,"number":{"times":1,"events":1}
,"times":{"relationship":1}
,"relationship":{"neighbor":1}
,"neighbor":{"changed":1,"return":1}
,"changed":{"state":1}
,"state":{"error":1}
,"error":{"occurred":1}
,"occurred":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf6_get_nbr_events":1,"ifindex":1,"instid":1,"*ret)":1}
,"(char":{"*tag":1}
,"*tag":{"int":1}
,"ifindex":{"int":1,"interface":1}
,"instid":{"struct":1,"instance":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"router_id":1}
,"router_id":{"int":1,"router":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"tag":1,"ret":1}
,"tag":{"ospfv3":1,"ifindex":1}
,"ospfv3":{"process":1}
,"process":{"tag":1}
,"interface":{"index":1}
,"index":{"instid":1}
,"instance":{"identifier":1}
,"identifier":{"router_id":1,"originating":1}
,"router":{"identifier":1,"output":1}
,"originating":{"router":1}
,"output":{"parameters":1}
,"ret":{"number":1}
,"events":{"neighbor":1}
,"return":{"values":1}
,"values":{"ospf6_api_get_error":1}
,"ospf6_api_get_error":{"function":1}
,"fails":{"ospf6_api_get_success":1}
,"ospf6_api_get_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
