var pairs =
{
"ospf_default_metric_set":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"called":1,"succeeds":1}
,"sets":{"default":1}
,"default":{"metric":1}
,"metric":{"redistributed":1,"default":1,"value":1}
,"redistributed":{"routes":1}
,"routes":{"function":1,"1-16777214":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"default-metric":1}
,"default-metric":{"<metric>":1}
,"<metric>":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf_default_metric_set":1,"proc_id":1,"metric)":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"int":1,"virtual":1}
,"proc_id":{"int":1,"process":1}
,"metric)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"found":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"proc_id":1}
,"process":{"ospf":1,"valid":1,"exist":1}
,"ospf":{"instance":1}
,"instance":{"65535>":1}
,"65535>":{"metric":1}
,"1-16777214":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf_api_set_err_process_id_invalid":1,"within":1}
,"ospf_api_set_err_process_id_invalid":{"process":1}
,"valid":{"ospf_api_set_err_process_not_exist":1}
,"ospf_api_set_err_process_not_exist":{"given":1}
,"given":{"process":1,"metric":1}
,"exist":{"ospf_api_set_err_metric_invalid":1}
,"ospf_api_set_err_metric_invalid":{"given":1}
,"within":{"range":1}
,"range":{"ospf_api_set_success":1}
,"ospf_api_set_success":{"function":1}
,"succeeds":{"ospf_api_set_err_vr_not_exist":1}
,"ospf_api_set_err_vr_not_exist":{"virtual":1}
}
;Search.control.loadWordPairs(pairs);
