var pairs =
{
"mstp_api_set_enable_bpdutx":{"function":1,"(char":1}
,"function":{"enables":1,"succeeds":1}
,"enables":{"disables":1}
,"disables":{"bpdu":1}
,"bpdu":{"transmission":1}
,"transmission":{"specified":1,"enabled":1}
,"specified":{"port":1}
,"port":{"syntax":1,"interface":1}
,"syntax":{"result_t":1}
,"result_t":{"mstp_api_set_enable_bpdutx":1}
,"(char":{"*br_name":1}
,"*br_name":{"char":1}
,"char":{"*if_name":1}
,"*if_name":{"bool_t":1}
,"bool_t":{"enabled)":1}
,"enabled)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"br_name":1,"none":1}
,"br_name":{"name":1}
,"name":{"bridge":1,"enabled":1,"exist":1}
,"bridge":{"if_name":1,"name":1}
,"if_name":{"interface":1}
,"interface":{"name":1,"exist":1}
,"enabled":{"whether":1,"=pal_true)":1}
,"whether":{"bpdu":1}
,"=pal_true)":{"disabled":1}
,"disabled":{"=pal_false)":1}
,"=pal_false)":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"result_ok":1}
,"result_ok":{"function":1}
,"succeeds":{"mstp_err_interface_not_found":1}
,"mstp_err_interface_not_found":{"interface":1}
,"exist":{"mstp_err_bridge_not_found":1,"mstp_err_port_not_found":1,"mstp_error_general":1}
,"mstp_err_bridge_not_found":{"bridge":1}
,"mstp_err_port_not_found":{"msti":1}
,"msti":{"port":1}
,"mstp_error_general":{"bad":1}
,"bad":{"passed":1}
}
;Search.control.loadWordPairs(pairs);
