var pairs =
{
"drni_api_set_intra_portal_link":{"function":1,"(u_int16_t":1}
,"function":{"creates":1,"called":1,"succeeds":1}
,"creates":{"intra-portal":1}
,"intra-portal":{"link":1,"port":1}
,"link":{"function":1,"configured":1}
,"called":{"command":1}
,"command":{"intra-portal-link":1}
,"intra-portal-link":{"syntax":1}
,"syntax":{"include":1}
,"include":{"mlagd\u002Fdrni\u002Fdrni_api.h":1}
,"mlagd\u002Fdrni\u002Fdrni_api.h":{"s_int32_t":1}
,"s_int32_t":{"drni_api_set_intra_portal_link":1}
,"(u_int16_t":{"drni_id":1}
,"drni_id":{"char":1,"mc-lag":1,"range":1,"cannot":1}
,"char":{"*ifname":1}
,"*ifname":{"u_int8_t":1}
,"u_int8_t":{"neigh_ps_no)":1}
,"neigh_ps_no)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"drni_id":1,"none":1}
,"mc-lag":{"identifier":1}
,"identifier":{"ifname":1}
,"ifname":{"interface":1,"null":1}
,"interface":{"name":1,"found":1}
,"name":{"intra-portal":1}
,"port":{"(ipp)":1}
,"(ipp)":{"neigh_ps_no":1}
,"neigh_ps_no":{"neighbor":1,"range":1,"already":1,"drni_err_max_ipp_reached":1}
,"neighbor":{"portal":1}
,"portal":{"system":1,"drni_id":1}
,"system":{"number":1}
,"number":{"output":1,"ipps":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"drni_success":1}
,"drni_success":{"function":1}
,"succeeds":{"drni_err_null_pointer":1}
,"drni_err_null_pointer":{"ifname":1}
,"null":{"drni_err_invalid_drni_id":1,"drni_err_ifp_not_found":1}
,"drni_err_invalid_drni_id":{"drni_id":1}
,"range":{"<1-65535>":1,"<1-3>":1}
,"<1-65535>":{"drni_err_invalid_portal_sys_num":1}
,"drni_err_invalid_portal_sys_num":{"neigh_ps_no":1}
,"<1-3>":{"drni_err_master_null":1}
,"drni_err_master_null":{"drni":1}
,"drni":{"master":1}
,"master":{"null":1}
,"drni_err_ifp_not_found":{"interface":1}
,"found":{"drni_err_portal_null":1,"drni_err_portal_sys_num_exist":1}
,"drni_err_portal_null":{"portal":1}
,"cannot":{"found":1}
,"drni_err_portal_sys_num_exist":{"neigh_ps_no":1}
,"already":{"used":1,"configured":1}
,"used":{"drni_err_same_neigh_exist":1}
,"drni_err_same_neigh_exist":{"link":1}
,"configured":{"ipp":1,"drni_err_calloc_failed":1}
,"ipp":{"neigh_ps_no":1}
,"drni_err_max_ipp_reached":{"maximum":1}
,"maximum":{"number":1}
,"ipps":{"already":1}
,"drni_err_calloc_failed":{"memory":1}
,"memory":{"allocation":1}
,"allocation":{"fails":1}
}
;Search.control.loadWordPairs(pairs);
