var pairs =
{
"ripng":{"commands":1}
,"commands":{"chapter":1,"support":1,"aggregate-address":1}
,"chapter":{"provides":1}
,"provides":{"alphabetized":1}
,"alphabetized":{"reference":1}
,"reference":{"routing":1}
,"routing":{"information":1}
,"information":{"protocol":1}
,"protocol":{"next":1}
,"next":{"generation":1}
,"generation":{"(ripng)":1}
,"(ripng)":{"commands":1}
,"support":{"ipv6":1}
,"ipv6":{"includes":1,"rip":1,"router":1,"protocols":1}
,"includes":{"following":1}
,"following":{"commands":1}
,"aggregate-address":{"cisco-metric-behavior":1}
,"cisco-metric-behavior":{"clear":1}
,"clear":{"ipv6":1}
,"rip":{"route":1,"default-information":1,"metric-offset":1,"split-horizon":1,"neighbor":1,"show":1,"interface":1}
,"route":{"debug":1,"route-map":1}
,"debug":{"ipv6":1}
,"default-information":{"originate":1}
,"originate":{"default-metric":1}
,"default-metric":{"distance":1}
,"distance":{"distribute-list":1}
,"distribute-list":{"ipv6":1}
,"metric-offset":{"ipv6":1}
,"split-horizon":{"ipv6":1}
,"router":{"rip":1,"ipv6":1}
,"neighbor":{"offset-list":1}
,"offset-list":{"passive-interface":1}
,"passive-interface":{"recv-buffer-size":1}
,"recv-buffer-size":{"redistribute":1}
,"redistribute":{"route":1}
,"route-map":{"router":1}
,"show":{"debugging":1,"ipv6":1}
,"debugging":{"ipv6":1}
,"protocols":{"rip":1}
,"interface":{"timers":1}
,"timers":{"basic":1}
}
;Search.control.loadWordPairs(pairs);
