var pairs =
{
"satop":{"commands":1,"(structure-agnostic":1}
,"commands":{"chapter":1,"pseudo":1,"interface":1}
,"chapter":{"provides":1}
,"provides":{"reference":1}
,"reference":{"satop":1}
,"(structure-agnostic":{"time":1}
,"time":{"division":1}
,"division":{"multiplexing":1}
,"multiplexing":{"packet)":1,"(tdm)":1}
,"packet)":{"commands":1}
,"pseudo":{"wire":1}
,"wire":{"encapsulation":1}
,"encapsulation":{"time":1}
,"(tdm)":{"bit-streams":1}
,"bit-streams":{"(t1":1}
,"(t1":{"e3)":1}
,"e3)":{"includes":1}
,"includes":{"following":1}
,"following":{"commands":1}
,"interface":{"tdm":1,"show":1}
,"tdm":{"jitter-buffer-size":1,"error-detection-timers":1,"interface":1,"satop-statistics":1,"payload-bytes":1}
,"jitter-buffer-size":{"rtp-header":1}
,"rtp-header":{"show":1}
,"show":{"tdm":1}
,"error-detection-timers":{"show":1}
,"satop-statistics":{"tdm":1}
,"payload-bytes":{"timer":1}
,"timer":{"error-clear":1,"error-set":1}
,"error-clear":{"timer":1}
}
;Search.control.loadWordPairs(pairs);
