var pairs =
{
"elmi_nsm_recv_evc_update":{"decodes":1,"(struct":1}
,"decodes":{"message":1}
,"message":{"attribute":1,"header":1,"pointer":1,"structure":1}
,"attribute":{"updates":1}
,"updates":{"local":1,"data":1}
,"local":{"data":1}
,"data":{"structure":1,"instance":1}
,"structure":{"updates":1,"output":1}
,"instance":{"field":1}
,"field":{"elmi":1}
,"elmi":{"api":1}
,"api":{"s_int32_t":1}
,"s_int32_t":{"elmi_nsm_recv_evc_update":1}
,"(struct":{"nsm_msg_header":1}
,"nsm_msg_header":{"*header":1}
,"*header":{"void":1}
,"void":{"*arg":1,"*message)":1}
,"*arg":{"void":1}
,"*message)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"header":1,"none":1}
,"header":{"pointer":1,"arg":1}
,"pointer":{"nsm":1,"message":1}
,"nsm":{"message":1,"connection":1}
,"arg":{"pointer":1}
,"connection":{"handler":1}
,"handler":{"message":1}
,"output":{"parameters":1}
}
;Search.control.loadWordPairs(pairs);
