var pairs =
{
"l2mrib_if":{"structure":1,"{struct":1}
,"structure":{"l2mribd.h":1}
,"l2mribd.h":{"maintains":1}
,"maintains":{"interface-related":1}
,"interface-related":{"information":1}
,"information":{"updated":1}
,"updated":{"nsm":1}
,"nsm":{"messages":1,"definition":1}
,"messages":{"nsm":1}
,"definition":{"struct":1}
,"struct":{"l2mrib_if":1,"l2mrib_port":1,"l2mrib_vlan":1,"ptree":1}
,"{struct":{"l2mrib_bridge":1}
,"l2mrib_bridge":{"*br":1}
,"*br":{"struct":1}
,"l2mrib_port":{"*l2port":1}
,"*l2port":{"struct":1}
,"l2mrib_vlan":{"*vlan":1}
,"*vlan":{"ifdef":1}
,"ifdef":{"have_igmp_snoop":1,"have_mld_snoop":1}
,"have_igmp_snoop":{"struct":1}
,"ptree":{"*igmpsnp_gmr_tib":1,"*mldsnp_gmr_tib":1}
,"*igmpsnp_gmr_tib":{"endif":1}
,"endif":{"ifdef":1}
,"have_mld_snoop":{"struct":1}
,"*mldsnp_gmr_tib":{"endif":1}
}
;Search.control.loadWordPairs(pairs);
