var pairs =
{
"rpvst_plus_api_set_msti_port_auto_path_cost":{"function":1,"(char":1}
,"function":{"sets":1,"succeeds":1}
,"sets":{"path":1}
,"path":{"cost":1}
,"cost":{"recalculation":1}
,"recalculation":{"automatic":1}
,"automatic":{"mode":1}
,"mode":{"instance":1}
,"instance":{"msti":1,"exist":1}
,"msti":{"related":1,"instance":1}
,"related":{"rpvst":1}
,"rpvst":{"syntax":1}
,"syntax":{"int":1}
,"int":{"rpvst_plus_api_set_msti_port_auto_path_cost":1,"vid)":1}
,"(char":{"*br_name":1}
,"*br_name":{"char":1}
,"char":{"*ifname":1}
,"*ifname":{"int":1}
,"vid)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"br_name":1,"none":1}
,"br_name":{"name":1}
,"name":{"bridge":1,"vid":1}
,"bridge":{"ifname":1,"exist":1}
,"ifname":{"interface":1}
,"interface":{"name":1,"found":1}
,"vid":{"vlan":1}
,"vlan":{"configured":1,"exist":1}
,"configured":{"4094":1}
,"4094":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"result_ok":1}
,"result_ok":{"function":1}
,"succeeds":{"mstp_err_interface_not_found":1}
,"mstp_err_interface_not_found":{"specified":1}
,"specified":{"interface":1,"port":1}
,"found":{"mstp_err_bridge_not_found":1,"mstp_err_rpvst_vlan_config_err":1}
,"mstp_err_bridge_not_found":{"bridge":1}
,"exist":{"mstp_err_instance_not_found":1,"mstp_err_port_not_found":1}
,"mstp_err_instance_not_found":{"msti":1}
,"mstp_err_port_not_found":{"specified":1}
,"port":{"found":1}
,"mstp_err_rpvst_vlan_config_err":{"vlan":1}
}
;Search.control.loadWordPairs(pairs);
