var pairs =
{
"configure":{"port":1}
,"port":{"customer":1,"following":1,"configured":1,"(cnp)":1,"previously":1,"type":1,"list":1}
,"customer":{"network":1}
,"network":{"port":1}
,"following":{"figure":1}
,"figure":{"displays":1}
,"displays":{"flow":1}
,"flow":{"followed":1}
,"followed":{"port":1}
,"configured":{"customer":1}
,"(cnp)":{"configure":1}
,"previously":{"described":1}
,"described":{"bridge":1}
,"bridge":{"port":1}
,"type":{"configuration":1}
,"configuration":{"executed":1}
,"executed":{"immediately":1}
,"immediately":{"sending":1}
,"sending":{"hal":1}
,"hal":{"message":1}
,"message":{"hsl":1}
,"hsl":{"nsm_beb_bridge":1}
,"nsm_beb_bridge":{"port":1}
,"list":{"table":1}
,"table":{"updated":1}
}
;Search.control.loadWordPairs(pairs);
