var pairs =
{
"ospf_nbr_static_poll_interval_set":{"function":1,"(int":1}
,"function":{"sets":1,"called":1,"succeeds":1}
,"sets":{"poll":1}
,"poll":{"interval":1}
,"interval":{"non-broadcast":1,"poll":1,"seconds":1}
,"non-broadcast":{"multi-access":1}
,"multi-access":{"(nbma)":1}
,"(nbma)":{"neighbor":1}
,"neighbor":{"function":1,"poll-interval":1,"address":1,"exist":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"neighbor":1}
,"poll-interval":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf_nbr_static_poll_interval_set":1,"interval)":1}
,"(int":{"proc_id":1}
,"proc_id":{"struct":1,"process":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"addr":1}
,"addr":{"int":1,"nbma":1}
,"interval)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"vr_id":{"virtual":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"found":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"proc_id":1}
,"process":{"ospf":1,"valid":1,"exist":1}
,"ospf":{"instance":1}
,"instance":{"65535>":1}
,"65535>":{"addr":1,"output":1}
,"nbma":{"neighbor":1}
,"address":{"interval":1}
,"seconds":{"65535>":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf_api_set_err_process_id_invalid":1}
,"ospf_api_set_err_process_id_invalid":{"process":1}
,"valid":{"ospf_api_set_err_process_not_exist":1}
,"ospf_api_set_err_process_not_exist":{"given":1}
,"given":{"process":1,"neighbor":1}
,"exist":{"ospf_api_set_success":1}
,"ospf_api_set_success":{"function":1}
,"succeeds":{"ospf_api_set_err_vr_not_exist":1}
,"ospf_api_set_err_vr_not_exist":{"virtual":1}
,"found":{"ospf_api_set_err_nbr_static_not_exist":1}
,"ospf_api_set_err_nbr_static_not_exist":{"given":1}
}
;Search.control.loadWordPairs(pairs);
