var pairs =
{
"introduction":{"orf":1}
,"orf":{"exchanges":1,"capabilities":1,"inbound":1,"capability":1,"mechanism":1,"entries":1}
,"exchanges":{"filtering":1}
,"filtering":{"data":1}
,"data":{"among":1}
,"among":{"routing":1}
,"routing":{"peers":1,"updates":1}
,"peers":{"implements":1,"advertise":1,"routers":1,"outbound":1,"receiving":1}
,"implements":{"behalf":1}
,"behalf":{"others":1}
,"others":{"block":1}
,"block":{"certain":1}
,"certain":{"routing":1}
,"updates":{"exchange":1,"remote":1,"several":1,"neighbor":1,"link":1,"ability":1}
,"exchange":{"accomplished":1}
,"accomplished":{"routers":1}
,"routers":{"peers":1,"detect":1,"push":1,"central":1}
,"advertise":{"respond":1}
,"respond":{"advertisements":1}
,"advertisements":{"orf":1}
,"capabilities":{"routers":1,"peers":1}
,"detect":{"orf":1}
,"push":{"orf":1}
,"inbound":{"prefix":1}
,"prefix":{"filters":1,"list":1}
,"filters":{"installed":1,"bgp":1,"during":1}
,"installed":{"peers":1}
,"outbound":{"filters":1}
,"bgp":{"orf":1,"speaker":1,"session":1}
,"capability":{"three":1,"send":1,"receive":1,"support":1}
,"three":{"configurable":1}
,"configurable":{"modes":1}
,"modes":{"send":1}
,"send":{"receive":1,"mode":1,"remote":1}
,"receive":{"apply":1,"mode":1,"orf":1}
,"apply":{"orf":1}
,"mechanism":{"local":1}
,"local":{"router":1,"bgp":1}
,"router":{"advertises":1,"applies":1}
,"advertises":{"orf":1}
,"mode":{"indicate":1}
,"indicate":{"orf":1,"receive":1}
,"entries":{"(including":1,"peers":1}
,"(including":{"prefix-list":1}
,"prefix-list":{"filters)":1}
,"filters)":{"send":1}
,"remote":{"peer":1,"bgp":1}
,"peer":{"remote":1,"advertises":1,"local":1}
,"receiving":{"route":1}
,"route":{"updates":1,"reflector":1}
,"applies":{"inbound":1}
,"list":{"updates":1}
,"several":{"advantages":1}
,"advantages":{"result":1}
,"result":{"technology":1}
,"technology":{"local":1}
,"speaker":{"consume":1,"handling":1}
,"consume":{"resources":1}
,"resources":{"generate":1}
,"generate":{"unnecessary":1}
,"unnecessary":{"routing":1}
,"neighbor":{"filters":1}
,"during":{"input":1}
,"input":{"less":1}
,"less":{"work":1,"route":1,"sending":1}
,"work":{"remote":1}
,"handling":{"less":1}
,"link":{"bandwidth":1}
,"bandwidth":{"usage":1}
,"usage":{"decreased":1}
,"decreased":{"due":1}
,"due":{"less":1}
,"sending":{"unnecessary":1}
,"ability":{"configure":1}
,"configure":{"neighboring":1}
,"neighboring":{"routers":1}
,"central":{"route":1}
,"reflector":{"bgp":1}
,"session":{"established":1}
,"established":{"zebos-xp":1}
,"zebos-xp":{"checks":1,"finds":1}
,"checks":{"orf":1}
,"support":{"zebos-xp":1,"sends":1}
,"finds":{"support":1}
,"sends":{"refresh_req":1,"industry-standard":1}
,"refresh_req":{"message":1}
,"message":{"sends":1,"possible":1}
,"industry-standard":{"keepalive":1}
,"keepalive":{"message":1}
,"possible":{"messages":1}
,"messages":{"simultaneously":1}
,"simultaneously":{"sent":1}
,"sent":{"tcp":1}
,"tcp":{"buffer":1}
}
;Search.control.loadWordPairs(pairs);
