var pairs =
{
"defense-mode":{"cnpv":1}
,"cnpv":{"command":1,"<0-7>":1,"cnpv":1,"admin":1,"interface":1,"priority":1,"comp":1}
,"command":{"defense":1,"syntax":1,"mode":1}
,"defense":{"mode":1}
,"mode":{"congestion":1,"specify":1,"alternate":1,"lldp":1,"bridge-level":1,"command":1,"defense-mode":1,"disabled":1,"according":1,"qcn":1,"interface":1,"examples":1}
,"congestion":{"notification":1}
,"notification":{"priority":1,"tlvs":1,"disabled":1,"tags":1}
,"priority":{"value":1,"specify":1,"parameters":1,"<0-7>":1,"cncpautoaltpri":1}
,"value":{"(cnpv)":1,"congestion":1,"auto":1}
,"(cnpv)":{"qcn":1}
,"qcn":{"mode":1,"enable":1}
,"specify":{"admin":1,"auto":1,"component":1}
,"admin":{"type":1,"explicitly":1,"edge":1}
,"type":{"explicitly":1}
,"explicitly":{"defense":1,"alternate":1}
,"alternate":{"priority":1,"value":1}
,"auto":{"derive":1,"component)":1,"defense":1}
,"derive":{"defense":1}
,"lldp":{"congestion":1}
,"tlvs":{"addition":1,"alternate":1}
,"addition":{"interface":1}
,"interface":{"mode":1,"edge":1,"cnpv":1,"eth1":1}
,"component":{"defense":1}
,"bridge-level":{"defense":1}
,"syntax":{"qcn":1}
,"<0-7>":{"(admin":1,"auto)":1,"auto":1,"cnpv":1,"alternate":1}
,"(admin":{"(disabled":1}
,"(disabled":{"edge":1}
,"edge":{"interior":1,"interface":1,"alternate-priority":1}
,"interior":{"interior-ready)":1,"interface":1}
,"interior-ready)":{"alternate-priority":1}
,"alternate-priority":{"<0-7>":1,"explicitly":1,"configure":1}
,"auto)":{"interface":1}
,"component)":{"parameters":1}
,"parameters":{"cnpv":1,"input":1}
,"disabled":{"congestion":1,"cnpv":1}
,"input":{"frames":1}
,"frames":{"remapped":1}
,"remapped":{"alternate":1,"value":1}
,"tags":{"output":1}
,"output":{"interior":1,"interior-ready":1,"alternate-priority":1}
,"interior-ready":{"interface":1}
,"according":{"lldp":1}
,"cncpautoaltpri":{"variable":1}
,"variable":{"defined":1}
,"defined":{"802.1qau":1}
,"802.1qau":{"standard":1}
,"standard":{"component":1,"command":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1,"config)":1}
,"(config)":{"qcn":1}
,"enable":{"bridge":1}
,"bridge":{"(config-qcn)":1}
,"(config-qcn)":{"defense-mode":1}
,"config)":{"interface":1}
,"eth1":{"(config-if)":1}
,"(config-if)":{"defense-mode":1}
}
;Search.control.loadWordPairs(pairs);
