var pairs =
{
"bridge":{"rapid-pervlan-spanning-tree":1,"form":1,"command":1,"<1-32>":1,"forwarding":1,"ports":1}
,"rapid-pervlan-spanning-tree":{"command":1,"enable":1}
,"command":{"enable":1,"disable":1,"syntax":1,"mode":1}
,"enable":{"rapid":1,"bridge":1,"(bridge-forward":1,"enables":1,"(config)":1,"bridge-forward":1}
,"rapid":{"per-vlan":1}
,"per-vlan":{"spanning":1}
,"spanning":{"tree":1}
,"tree":{"plus":1,"protocol":1}
,"plus":{"(rpvst":1}
,"(rpvst":{"functionality":1}
,"functionality":{"bridge":1}
,"form":{"command":1}
,"disable":{"rpvst":1}
,"rpvst":{"functionality":1}
,"syntax":{"bridge":1}
,"<1-32>":{"rapid-pervlan-spanning-tree":1,"specify":1}
,"(bridge-forward":{"parameters":1}
,"parameters":{"<1-32>":1}
,"specify":{"bridge-group":1}
,"bridge-group":{"enable":1}
,"enables":{"spanning":1}
,"protocol":{"bridge-forward":1}
,"bridge-forward":{"(optional)":1,"option":1}
,"(optional)":{"puts":1}
,"puts":{"ports":1}
,"ports":{"specified":1,"blocking":1}
,"specified":{"bridge":1}
,"forwarding":{"state":1}
,"state":{"default":1,"command":1}
,"default":{"bridge-forward":1,"behavior":1}
,"option":{"used":1}
,"used":{"parameter":1}
,"parameter":{"default":1}
,"behavior":{"put":1}
,"put":{"bridge":1}
,"blocking":{"state":1}
,"mode":{"configure":1,"examples":1}
,"configure":{"mode":1,"terminal":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"bridge":1}
}
;Search.control.loadWordPairs(pairs);
