var pairs =
{
"esadi":{"l2-learning":1,"protocol":1}
,"l2-learning":{"command":1,"enable":1}
,"command":{"enable":1,"disable":1,"syntax":1,"mode":1}
,"enable":{"layer":1,"vlan":1,"configure":1}
,"layer":{"learning":1}
,"learning":{"feature":1}
,"feature":{"esadi":1}
,"protocol":{"parameter":1,"command":1,"trill":1}
,"parameter":{"command":1}
,"disable":{"layer":1}
,"syntax":{"esadi":1}
,"vlan":{"<1-4094>)":1,"range":1,"(config-rb)":1}
,"<1-4094>)":{"esadi":1,"parameters":1}
,"parameters":{"<1-4094>":1}
,"<1-4094>":{"specify":1}
,"specify":{"actual":1}
,"actual":{"vlan":1}
,"range":{"command":1}
,"mode":{"rbridge":1,"examples":1}
,"rbridge":{"mode":1,"trill":1}
,"examples":{"enable":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"bridge":1,"rbridge":1}
,"bridge":{"protocol":1}
,"trill":{"(config)":1,"(config-rb)":1}
,"(config-rb)":{"esadi":1}
}
;Search.control.loadWordPairs(pairs);
