var pairs =
{
"trill_designated_vlan_nsm_add":{"function":1,"(struct":1}
,"function":{"sends":1}
,"sends":{"designated":1}
,"designated":{"vlan":1}
,"vlan":{"information":1}
,"information":{"nsm":1}
,"nsm":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"trill_designated_vlan_nsm_add":1}
,"(struct":{"trill_interface":1}
,"trill_interface":{"*isi":1}
,"*isi":{"u_int16_t":1}
,"u_int16_t":{"dvlan)":1}
,"dvlan)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"*ifl":1,"none":1}
,"*ifl":{"specifies":1}
,"specifies":{"pointer":1}
,"pointer":{"parent":1}
,"parent":{"interface":1}
,"interface":{"level":1}
,"level":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"trill_api_set_success":1}
,"trill_api_set_success":{"trill_api_set_err_no_nsm_cilent":1}
,"trill_api_set_err_no_nsm_cilent":{"trill_err_memory_alloc_failure":1}
,"trill_err_memory_alloc_failure":{"trill_api_set_err_nsm_send_failed":1}
}
;Search.control.loadWordPairs(pairs);
