var pairs =
{
"mpls-tp":{"oam":1}
,"oam":{"modules":1,"(operations":1,"mpls-based":1}
,"modules":{"mpls-tp":1}
,"(operations":{"administration":1}
,"administration":{"maintenance)":1}
,"maintenance)":{"plays":1}
,"plays":{"significant":1}
,"significant":{"role":1}
,"role":{"providing":1}
,"providing":{"methods":1}
,"methods":{"fault":1}
,"fault":{"management":1,"indication":1}
,"management":{"performance":1}
,"performance":{"monitoring":1}
,"monitoring":{"transport":1,"capabilities":1}
,"transport":{"service":1,"networks":1}
,"service":{"layers":1,"level":1}
,"layers":{"thereby":1}
,"thereby":{"improving":1}
,"improving":{"ability":1}
,"ability":{"support":1}
,"support":{"services":1}
,"services":{"guaranteed":1}
,"guaranteed":{"strict":1}
,"strict":{"service":1}
,"level":{"agreements":1}
,"agreements":{"(slas)":1}
,"(slas)":{"reducing":1}
,"reducing":{"operational":1}
,"operational":{"costs":1}
,"costs":{"oam":1}
,"mpls-based":{"transport":1}
,"networks":{"consists":1}
,"consists":{"comprehensive":1}
,"comprehensive":{"fault":1}
,"indication":{"performance":1}
}
;Search.control.loadWordPairs(pairs);
