var pairs =
{
"ldp_api_set_keepalive_int":{"call":1,"(struct":1}
,"call":{"sets":1}
,"sets":{"keepalive":1}
,"keepalive":{"interval":1}
,"interval":{"entities":1,"permitted":1,"keepalive":1,"flag":1}
,"entities":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ldp_api_set_keepalive_int":1}
,"(struct":{"ldp":1}
,"ldp":{"*ldp":1,"ldp":1,"instance":1}
,"*ldp":{"u_int16_t":1}
,"u_int16_t":{"keepalive_interval":1}
,"keepalive_interval":{"u_char":1,"keepalive":1}
,"u_char":{"interval)":1}
,"interval)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ldp":1,"none":1}
,"instance":{"keepalive_interval":1}
,"permitted":{"range":1,"values":1}
,"range":{"-65535)":1}
,"-65535)":{"interval":1}
,"flag":{"permitted":1}
,"values":{"ldp_keepalive_interval_set":1,"ldp_success":1}
,"ldp_keepalive_interval_set":{"(1)":1}
,"(1)":{"ldp_keepalive_interval_unset":1}
,"ldp_keepalive_interval_unset":{"(0)":1}
,"(0)":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"ldp_success":{"ldp_error":1}
}
;Search.control.loadWordPairs(pairs);
