var pairs =
{
"cfm_pbb_te_tst_set_testing_status":{"function":1,"(struct":1}
,"function":{"sets":1,"fails":1,"succeeds":1}
,"sets":{"testing":1}
,"testing":{"state":1,"cfm_mep_out_of_service_testing":1,"destlevel":1}
,"state":{"mep":1,"values":1}
,"mep":{"pbb-te":1,"<1-8191>":1,"in-service":1,"out-of-service":1}
,"pbb-te":{"bridge":1}
,"bridge":{"syntax":1,"identity":1,"mepid":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"cfm_pbb_te_tst_set_testing_status":1}
,"(struct":{"onmd_bridge":1}
,"onmd_bridge":{"*bridge":1}
,"*bridge":{"u_int32_t":1}
,"u_int32_t":{"mepid":1,"te_sid)":1}
,"mepid":{"u_int8_t":1,"source":1}
,"u_int8_t":{"testing_state":1,"destlevel":1,"*md_name":1}
,"testing_state":{"u_int8_t":1,"testing":1}
,"destlevel":{"u_int8_t":1,"destination":1}
,"*md_name":{"u_int32_t":1}
,"te_sid)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bridge":1}
,"identity":{"bridge":1}
,"source":{"mep":1}
,"<1-8191>":{"testing_state":1}
,"values":{"onmd\u002Fcfm\u002Fcfm_tst.h":1,"cfm_failure":1}
,"onmd\u002Fcfm\u002Fcfm_tst.h":{"cfm_mep_in_service_testing":1}
,"cfm_mep_in_service_testing":{"mep":1}
,"in-service":{"testing":1}
,"cfm_mep_out_of_service_testing":{"mep":1}
,"out-of-service":{"testing":1}
,"destination":{"maintenance":1}
,"maintenance":{"level":1,"domain":1}
,"level":{"md_name":1}
,"md_name":{"maintenance":1}
,"domain":{"name":1}
,"name":{"te_sid":1}
,"te_sid":{"service":1}
,"service":{"instance":1}
,"instance":{"<1-42949675>":1}
,"<1-42949675>":{"return":1}
,"return":{"values":1}
,"cfm_failure":{"function":1}
,"fails":{"cfm_success":1}
,"cfm_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
