var pairs =
{
"definition":{"struct":1}
,"struct":{"ipi_vr":1,"access_master":1,"apbf_rule_group_list":1,"prefix_master":1,"route_map_list":1,"entlogicalentry":1,"list":1,"pbr_rmap_event":1}
,"ipi_vr":{"{\u002F*pointer":1}
,"{\u002F*pointer":{"globals":1}
,"globals":{"*\u002Fstruct":1}
,"*\u002Fstruct":{"lib_globals":1,"pal_in4_addr":1,"if_vr_master":1,"ipi_vrf":1,"host":1,"access_master":1,"prefix_master":1,"list":1,"thread":1,"snmpcommunity":1}
,"lib_globals":{"*zg":1}
,"*zg":{"\u002F*vr":1}
,"\u002F*vr":{"name":1,"*\u002Fu_int32_t":1}
,"name":{"*\u002Fchar":1}
,"*\u002Fchar":{"*name":1}
,"*name":{"\u002F*vr":1}
,"*\u002Fu_int32_t":{"\u002F*router":1,"protos":1}
,"\u002F*router":{"*\u002Fstruct":1}
,"pal_in4_addr":{"router_id":1}
,"router_id":{"u_int8_t":1}
,"u_int8_t":{"flags":1}
,"flags":{"define":1}
,"define":{"lib_flag_delete_vr_config_file":1,"lib_flag_vr_re_created":1,"lib_flag_vr_inactive":1,"lib_flag_vr_no_config":1}
,"lib_flag_delete_vr_config_file":{"<<0)":1}
,"<<0)":{"define":1}
,"lib_flag_vr_re_created":{"<<1)":1}
,"<<1)":{"define":1}
,"lib_flag_vr_inactive":{"<<2)":1}
,"<<2)":{"define":1}
,"lib_flag_vr_no_config":{"<<3)":1}
,"<<3)":{"\u002F*interface":1}
,"\u002F*interface":{"master":1}
,"master":{"*\u002Fstruct":1,"*list":1,"*\u002F#":1,"*\u002Fvoid":1}
,"if_vr_master":{"ifm":1}
,"ifm":{"\u002F*vrfs":1}
,"\u002F*vrfs":{"*\u002Fvector":1,"*\u002Fstruct":1}
,"*\u002Fvector":{"vrf_vec":1,"route_match_vec":1}
,"vrf_vec":{"\u002F*vrfs":1}
,"ipi_vrf":{"*vrf_list":1,"*vrf_in_cxt":1}
,"*vrf_list":{"\u002F*protocol":1}
,"\u002F*protocol":{"bindings":1,"master":1}
,"bindings":{"*\u002Fu_int32_t":1}
,"protos":{"\u002F*host":1}
,"\u002F*host":{"*\u002Fstruct":1}
,"host":{"*host":1}
,"*host":{"\u002F*access":1}
,"\u002F*access":{"list":1}
,"list":{"*\u002Fstruct":1,"*keychain_list":1,"*mappedphyentlist":1}
,"access_master":{"access_master_ipv4":1,"access_master_ipv6":1,"access_master_generic":1}
,"access_master_ipv4":{"ifdef":1}
,"ifdef":{"have_ipv6":1,"have_apbf":1,"have_ha":1,"have_pbr":1}
,"have_ipv6":{"struct":1,"*\u002F#":1}
,"access_master_ipv6":{"endif":1}
,"endif":{"\u002F*def":1,"\u002F*have_apbf":1,"\u002F*have_ipv6":1,"\u002F*have_ha":1,"\u002F*have_pbr":1}
,"\u002F*def":{"have_ipv6":1}
,"*\u002F#":{"ifdef":1,"endif":1}
,"have_apbf":{"\u002F*generic":1}
,"\u002F*generic":{"access-list":1}
,"access-list":{"master":1}
,"*list":{"generic":1}
,"generic":{"acls":1}
,"acls":{"ipv4":1}
,"ipv4":{"ipv6":1}
,"ipv6":{"qualifiers":1}
,"qualifiers":{"*for":1}
,"*for":{"example":1}
,"example":{"src_mac":1}
,"src_mac":{"dst_mac":1}
,"dst_mac":{"vlan":1}
,"vlan":{"*\u002Fstruct":1}
,"access_master_generic":{"struct":1}
,"apbf_rule_group_list":{"apbf_rule_group_master":1}
,"apbf_rule_group_master":{"\u002F*apbf":1}
,"\u002F*apbf":{"rule-group":1}
,"rule-group":{"master":1}
,"\u002F*have_apbf":{"*\u002F\u002F*prefix":1}
,"*\u002F\u002F*prefix":{"list":1}
,"prefix_master":{"prefix_master_ipv4":1,"prefix_master_ipv6":1,"prefix_master_orf":1}
,"prefix_master_ipv4":{"ifdef":1}
,"prefix_master_ipv6":{"endif":1}
,"\u002F*have_ipv6":{"*\u002Fstruct":1}
,"prefix_master_orf":{"\u002F*route":1}
,"\u002F*route":{"map":1}
,"map":{"*\u002Fvector":1}
,"route_match_vec":{"vector":1}
,"vector":{"route_set_vec":1}
,"route_set_vec":{"struct":1}
,"route_map_list":{"route_map_master":1}
,"route_map_master":{"\u002F*key":1}
,"\u002F*key":{"chain":1}
,"chain":{"*\u002Fstruct":1}
,"*keychain_list":{"\u002F*protocol":1}
,"*\u002Fvoid":{"*proto":1}
,"*proto":{"\u002F*config":1}
,"\u002F*config":{"read":1}
,"read":{"event":1}
,"event":{"*\u002Fstruct":1}
,"thread":{"*t_config":1,"*t_if_stat_threshold":1}
,"*t_config":{"\u002F*vrf":1}
,"\u002F*vrf":{"currently":1}
,"currently":{"context":1}
,"context":{"*\u002Fstruct":1}
,"*vrf_in_cxt":{"\u002F*if":1}
,"\u002F*if":{"stats":1}
,"stats":{"update":1}
,"update":{"threshold":1}
,"threshold":{"timer":1}
,"timer":{"*\u002Fstruct":1}
,"*t_if_stat_threshold":{"struct":1}
,"entlogicalentry":{"*entlogical":1}
,"*entlogical":{"struct":1}
,"*mappedphyentlist":{"\u002F*community":1}
,"\u002F*community":{"string":1}
,"string":{"identify":1}
,"identify":{"current":1}
,"current":{"*\u002Fstruct":1}
,"snmpcommunity":{"snmp_community":1}
,"snmp_community":{"ifdef":1}
,"have_ha":{"ha_cdr_ref":1}
,"ha_cdr_ref":{"lib_vr_cdr_ref":1}
,"lib_vr_cdr_ref":{"endif":1}
,"\u002F*have_ha":{"*\u002F#":1}
,"have_pbr":{"struct":1}
,"pbr_rmap_event":{"pbr_event":1}
,"pbr_event":{"endif":1}
,"\u002F*have_pbr":{"*\u002F}":1}
}
;Search.control.loadWordPairs(pairs);
