var pairs =
{
"remote":{"loopback":1}
,"loopback":{"enable":1,"interface":1,"operations":1,"disabled":1,"eth2":1}
,"enable":{"ethernet":1}
,"ethernet":{"oam":1,"remote":1}
,"oam":{"remote":1,"client":1,"remote-loopback":1}
,"interface":{"local":1,"eth2":1,"mode":1}
,"local":{"oam":1}
,"client":{"start":1}
,"start":{"oam":1,"command":1,"turn":1}
,"operations":{"ethernet":1}
,"disabled":{"default":1}
,"default":{"ethernet":1}
,"remote-loopback":{"start":1,"supported":1,"eth2":1,"stop":1}
,"command":{"successful":1}
,"successful":{"node":1}
,"node":{"receive":1}
,"receive":{"least":1}
,"least":{"pdu":1}
,"pdu":{"zebos1":1}
,"zebos1":{"configure":1,"(config)":1,"(config-if)":1}
,"configure":{"terminal":1,"mode":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"interface":1}
,"mode":{"zebos1":1}
,"(config)":{"interface":1}
,"eth2":{"enter":1,"zebos1":1}
,"(config-if)":{"ethernet":1,"end":1}
,"supported":{"enable":1}
,"turn":{"remote-loopback":1}
,"stop":{"turn":1}
,"end":{"exit":1}
,"exit":{"interface":1}
}
;Search.control.loadWordPairs(pairs);
