var pairs =
{
"rib_set_maximum_static_routes":{"function":1,"(int":1}
,"function":{"sets":1,"called":1,"succeeds":1}
,"sets":{"maximum":1}
,"maximum":{"number":1}
,"number":{"static":1,"configured":1}
,"static":{"routes":1}
,"routes":{"function":1,"output":1,"already":1}
,"called":{"max-static-routes":1}
,"max-static-routes":{"command":1}
,"command":{"syntax":1}
,"syntax":{"int":1}
,"int":{"rib_set_maximum_static_routes":1,"num)":1}
,"(int":{"vr_id":1}
,"vr_id":{"int":1,"virtual":1}
,"num)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"identifier":1,"found":1}
,"identifier":{"non-virtual-router":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"num":1}
,"num":{"maximum":1,"rib_api_set_success":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"rib_api_set_err_vr_not_exist":1}
,"rib_api_set_err_vr_not_exist":{"virtual":1}
,"found":{"rib_api_set_err_max_static_route_limit":1}
,"rib_api_set_err_max_static_route_limit":{"number":1}
,"configured":{"static":1}
,"already":{"greater":1}
,"greater":{"num":1}
,"rib_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
