var pairs =
{
"community-list":{"standard":1,"defines":1,"entry":1,"compiled":1,"community":1,"permit":1}
,"standard":{"community-lists":1,"standard":1,"community-list":1,"community":1,"word":1,"clist":1}
,"community-lists":{"specify":1,"expanded":1}
,"specify":{"bgp":1}
,"bgp":{"community":1,"communities":1,"updates":1,"peers":1}
,"community":{"attributes":1,"attribute":1,"values":1,"value":1,"list":1,"permit":1,"aa:nn":1,"number":1}
,"attributes":{"community":1,"specified":1,"regular":1}
,"attribute":{"used":1,"facilitates":1,"bgp":1}
,"used":{"implementing":1}
,"implementing":{"policy":1}
,"policy":{"routing":1}
,"routing":{"optional":1}
,"optional":{"transitive":1}
,"transitive":{"attribute":1}
,"facilitates":{"transfer":1}
,"transfer":{"local":1}
,"local":{"policies":1}
,"policies":{"different":1}
,"different":{"autonomous":1}
,"autonomous":{"systems":1,"system":1}
,"systems":{"includes":1}
,"includes":{"community":1}
,"values":{"bits":1}
,"bits":{"long":1}
,"long":{"two":1}
,"two":{"kinds":1}
,"kinds":{"community-lists":1}
,"expanded":{"standard":1,"community-list":1,"parameter":1}
,"defines":{"community":1}
,"specified":{"format":1}
,"format":{"without":1,"directly":1}
,"without":{"regular":1}
,"regular":{"expressions":1}
,"expressions":{"expanded":1,"command":1}
,"command":{"add":1,"delete":1,"syntax":1,"mode":1}
,"add":{"standard":1}
,"entry":{"standard":1,"command":1}
,"compiled":{"binary":1}
,"binary":{"format":1}
,"directly":{"compared":1}
,"compared":{"bgp":1}
,"communities":{"attribute":1}
,"updates":{"comparison":1}
,"comparison":{"faster":1}
,"faster":{"expanded":1}
,"value":{"match":1,"automatically":1}
,"match":{"standard":1}
,"automatically":{"treated":1}
,"treated":{"expanded":1}
,"parameter":{"command":1}
,"delete":{"standard":1}
,"syntax":{"community-list":1}
,"word":{"(deny":1,"community":1}
,"(deny":{"permit)":1}
,"permit)":{"community-list":1,"[aa:nn":1}
,"[aa:nn":{"local-as":1}
,"local-as":{"no-advertise":1,"advertise":1}
,"no-advertise":{"no-export]":1,"advertise":1}
,"no-export]":{"community-list":1,"parameters":1}
,"parameters":{"word":1}
,"list":{"name":1}
,"name":{"deny":1}
,"deny":{"reject":1}
,"reject":{"community":1}
,"permit":{"accept":1,"7675:80":1,"5675:50":1}
,"accept":{"community":1}
,"aa:nn":{"community":1}
,"number":{"local-as":1}
,"advertise":{"routes":1}
,"routes":{"external":1,"bgp":1,"outside":1}
,"external":{"bgp":1}
,"peers":{"no-advertise":1,"no-export":1}
,"no-export":{"advertise":1,"(config)":1}
,"outside":{"autonomous":1}
,"system":{"boundary":1}
,"boundary":{"command":1}
,"mode":{"configure":1,"examples":1}
,"configure":{"mode":1,"terminal":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"community-list":1}
,"clist":{"permit":1}
,"7675:80":{"7675:90":1}
,"7675:90":{"no-export":1}
,"5675:50":{"no-advertise":1}
}
;Search.control.loadWordPairs(pairs);
