var pairs =
{
"show":{"rsvp":1}
,"rsvp":{"p2mp-session":1,"p2mp":1}
,"p2mp-session":{"name":1}
,"name":{"commands":1,"show":1,"primary-lsp":1,"secondary-lsp":1,"trunk":1,"command":1,"default":1}
,"commands":{"display":1}
,"display":{"information":1}
,"information":{"rsvp":1}
,"p2mp":{"sessions":1}
,"sessions":{"trunk":1}
,"trunk":{"lsp":1,"name":1,"primary":1}
,"lsp":{"sub-lsp":1,"show":1,"(s)":1,"protection":1}
,"sub-lsp":{"command":1}
,"command":{"syntax":1,"mode":1}
,"syntax":{"show":1}
,"primary-lsp":{"show":1,"destination":1,"trunk-name":1}
,"destination":{"a.b.c.d":1,"2.2.2.2":1,"3.3.3.3":1,"4.4.4.4":1}
,"a.b.c.d":{"show":1,"parameters":1}
,"secondary-lsp":{"show":1,"destination":1}
,"parameters":{"name":1}
,"mode":{"privileged":1}
,"privileged":{"exec":1}
,"exec":{"exec":1,"modes":1}
,"modes":{"examples":1}
,"examples":{"example":1}
,"example":{"below":1}
,"below":{"shows":1}
,"shows":{"output":1}
,"output":{"named":1}
,"named":{"trunk":1}
,"primary":{"lsp":1,"----------------------------------oper":1}
,"trunk-name":{"abcd":1}
,"abcd":{"trunk-id":1}
,"trunk-id":{"100":1}
,"100":{"p2mp-id":1}
,"p2mp-id":{"ext-tunnel-id":1}
,"ext-tunnel-id":{"1.1.1.1":1}
,"1.1.1.1":{"role":1,"destination":1}
,"role":{"ingress":1}
,"ingress":{"lsp":1}
,"(s)":{"-----------------------------------lsp_id":1,"--------------------------------------------------------------------------sub-group":1}
,"-----------------------------------lsp_id":{"2000":1}
,"2000":{"lsp-role":1}
,"lsp-role":{"primary":1}
,"----------------------------------oper":{"status":1}
,"status":{"setup":1}
,"setup":{"priority":1}
,"priority":{"hold":1,"tspec":1}
,"hold":{"priority":1}
,"tspec":{"rate":1}
,"rate":{"10k":1}
,"10k":{"fspec":1,"style":1}
,"fspec":{"rate":1}
,"style":{"shared":1}
,"shared":{"explicit":1}
,"explicit":{"filter":1,"path":1}
,"filter":{"traffic":1}
,"traffic":{"type":1}
,"type":{"controlled-load":1,"dste":1,"name":1}
,"controlled-load":{"dste":1}
,"dste":{"class":1}
,"class":{"type":1}
,"default":{"admin":1}
,"admin":{"groups":1}
,"groups":{"none":1}
,"none":{"lsp":1,"retry":1,"explicit":1,"last":1,"node":1}
,"protection":{"none":1}
,"retry":{"count":1,"interval":1}
,"count":{"retry":1}
,"interval":{"seconds":1}
,"seconds":{"remaining":1}
,"remaining":{"inf)":1}
,"inf)":{"s2l-sublsp":1}
,"s2l-sublsp":{"(s)":1}
,"--------------------------------------------------------------------------sub-group":{"sub":1}
,"sub":{"group":1}
,"group":{"originator":1}
,"originator":{"1.1.1.1":1}
,"2.2.2.2":{"--------------------------------------------------------------------------operstatus":1}
,"--------------------------------------------------------------------------operstatus":{"downstream":1}
,"downstream":{"10.10.0.3":1,"20.20.0.3":1}
,"10.10.0.3":{"eth0":1}
,"eth0":{"minimum":1}
,"minimum":{"path":1}
,"path":{"mtu":1,"none":1,"10.10.0.3\u002F32":1}
,"mtu":{"n\u002Fa":1}
,"n\u002Fa":{"cspf":1}
,"cspf":{"usage":1}
,"usage":{"disabled":1}
,"disabled":{"label":1,"configured":1}
,"label":{"-label":1,"recording":1}
,"-label":{"606":1}
,"606":{"record":1}
,"record":{"route":1}
,"route":{"<self>":1}
,"<self>":{".incomplete":1}
,".incomplete":{"label":1}
,"recording":{"disabled":1}
,"configured":{"path":1}
,"10.10.0.3\u002F32":{"strict":1}
,"strict":{"9.10.0.2\u002F32":1,"last":1}
,"9.10.0.2\u002F32":{"strict":1}
,"last":{"recorded":1}
,"recorded":{"error":1}
,"error":{"code":1,"value":1,"originated":1}
,"code":{"none":1}
,"value":{"none":1}
,"node":{"last":1}
,"originated":{"self":1}
,"self":{"--------------------------------------------------------------------------sub-group":1}
,"3.3.3.3":{"--------------------------------------------------------------------------operstatus":1}
,"20.20.0.3":{"eth1":1,"eth2":1}
,"eth1":{"minimum":1}
,"4.4.4.4":{"--------------------------------------------------------------------------operstatus":1}
,"eth2":{"minimum":1}
}
;Search.control.loadWordPairs(pairs);
