var pairs =
{
"synce_api_config_init":{"function":1,"(struct":1}
,"function":{"initializes":1,"implements":1,"succeeds":1}
,"initializes":{"global":1}
,"global":{"synce_config":1,"configure":1}
,"synce_config":{"struct":1,"*sconfig)":1}
,"struct":{"default":1}
,"default":{"values":1}
,"values":{"function":1}
,"implements":{"synce":1}
,"synce":{"command":1,"master":1}
,"command":{"configure":1,"cannot":1}
,"configure":{"mode":1}
,"mode":{"syntax":1,"information":1}
,"syntax":{"include":1}
,"include":{"synced\u002Fsynce_api.h":1}
,"synced\u002Fsynce_api.h":{"s_int16_t":1}
,"s_int16_t":{"synce_api_config_init":1}
,"(struct":{"synce_config":1}
,"*sconfig)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"none":1,"sconfig":1}
,"none":{"output":1}
,"output":{"parameters":1}
,"sconfig":{"global":1}
,"information":{"return":1}
,"return":{"value":1}
,"value":{"result_ok":1}
,"result_ok":{"function":1}
,"succeeds":{"result_error":1}
,"result_error":{"synce":1}
,"master":{"structure":1}
,"structure":{"cannot":1}
,"cannot":{"found":1,"created":1,"allocated":1}
,"found":{"sconfig->":1}
,"sconfig->":{"synce_ifp_tree":1}
,"synce_ifp_tree":{"member":1}
,"member":{"cannot":1}
,"created":{"memory":1}
,"memory":{"clock":1,"external":1}
,"clock":{"source":1}
,"source":{"cannot":1}
,"allocated":{"memory":1}
,"external":{"command":1}
}
;Search.control.loadWordPairs(pairs);
