var pairs =
{
"smi_alarm":{"enumeration":1}
,"enumeration":{"defines":1}
,"defines":{"alarm":1}
,"alarm":{"identifiers":1,"generated":1,"indicates":1,"raised":1}
,"identifiers":{"generated":1}
,"generated":{"smi":1,"cfm":1,"efm":1,"stp":1,"rmon":1,"interface":1,"nsm":1}
,"smi":{"server":1,"client":1}
,"server":{"type":1,"smi_alarm_transport_failure":1,"smi_alarm_smi_server_disconnect":1,"smi_alarm_nsm_vlan_add_to_port":1}
,"type":{"definition":1,"smi_vlan_port_mode":1,"changed":1}
,"definition":{"smi_alarm_memory_failure":1,"typedef":1}
,"smi_alarm_memory_failure":{"memory":1}
,"memory":{"allocation":1}
,"allocation":{"failed":1}
,"failed":{"smi_alarm_hardware_failure":1}
,"smi_alarm_hardware_failure":{"used":1,"smi_alarm_nsm_server_socket_disconnect":1}
,"used":{"smi_alarm_nsm_server_socket_disconnect":1}
,"smi_alarm_nsm_server_socket_disconnect":{"socket":1,"smi_alarm_nsm_client_socket_disconnect":1}
,"socket":{"connection":1}
,"connection":{"protocol":1,"disconnected":1,"hsl":1,"api":1}
,"protocol":{"module":1}
,"module":{"nsm":1,"smi_alarm_efm":1,"smi_alarm_stp":1,"smi_alarm_rmon":1,"smi_alarm_loc":1,"vlan":1}
,"nsm":{"disconnected":1,"smi":1,"generated":1,"module":1}
,"disconnected":{"smi_alarm_nsm_client_socket_disconnect":1,"nsm":1,"smi_alarm_cfm":1,"client":1}
,"smi_alarm_nsm_client_socket_disconnect":{"socket":1,"smi_alarm_transport_failure":1}
,"client":{"server":1}
,"smi_alarm_transport_failure":{"socket":1,"smi_alarm_cfm":1}
,"hsl":{"disconnected":1}
,"smi_alarm_cfm":{"alarm":1,"smi_alarm_efm":1}
,"cfm":{"module":1}
,"smi_alarm_efm":{"alarm":1,"smi_alarm_stp":1}
,"efm":{"module":1}
,"smi_alarm_stp":{"alarm":1,"smi_alarm_rmon":1}
,"stp":{"module":1,"rstp":1}
,"smi_alarm_rmon":{"alarm":1,"smi_alarm_loc":1}
,"rmon":{"module":1}
,"smi_alarm_loc":{"nsm":1,"smi_alarm_smi_server_connect":1}
,"interface":{"down":1}
,"down":{"update":1}
,"update":{"event":1,"fails":1}
,"event":{"smi_alarm_smi_server_connect":1}
,"smi_alarm_smi_server_connect":{"successful":1,"smi_alarm_smi_server_disconnect":1}
,"successful":{"socket":1}
,"api":{"client":1}
,"smi_alarm_smi_server_disconnect":{"socket":1,"smi_alarm_nsm_vlan_add_to_port":1}
,"smi_alarm_nsm_vlan_add_to_port":{"alarm":1,"smi_alarm_nsm_vlan_del_from_port":1}
,"vlan":{"added":1,"deleted":1,"definition":1}
,"added":{"smi_alarm_nsm_vlan_del_from_port":1,"vlan":1}
,"smi_alarm_nsm_vlan_del_from_port":{"alarm":1,"smi_alarm_nsm_vlan_port_mode":1}
,"deleted":{"smi_alarm_nsm_vlan_port_mode":1}
,"smi_alarm_nsm_vlan_port_mode":{"alarm":1,"smi_alarm_nsm_bridge_proto_change":1}
,"indicates":{"port":1}
,"port":{"mode":1}
,"mode":{"aggregated":1}
,"aggregated":{"ports":1}
,"ports":{"type":1,"added":1}
,"smi_vlan_port_mode":{"smi_alarm_nsm_bridge_proto_change":1}
,"smi_alarm_nsm_bridge_proto_change":{"alarm":1,"smi_alarm_nsm_vlan_port_bulk_update":1}
,"raised":{"bridge":1,"bulk":1}
,"bridge":{"type":1}
,"changed":{"stp":1}
,"rstp":{"smi_alarm_nsm_vlan_port_bulk_update":1}
,"smi_alarm_nsm_vlan_port_bulk_update":{"alarm":1,"smi_alarm_smi_max":1}
,"bulk":{"update":1}
,"fails":{"number":1}
,"number":{"ports":1}
,"typedef":{"enum":1}
,"enum":{"_smi_alarm":1}
,"_smi_alarm":{"{smi_alarm_memory_failure":1}
,"{smi_alarm_memory_failure":{"smi_alarm_hardware_failure":1}
,"smi_alarm_smi_max":{"smi_alarm":1}
}
;Search.control.loadWordPairs(pairs);
