var pairs =
{
"isis_distance_ipv6_set":{"call":1,"(u_int32_t":1}
,"call":{"implements":1}
,"implements":{"distance":1}
,"distance":{"command":1,"routes":1,"administrative":1,"output":1,"within":1}
,"command":{"defines":1}
,"defines":{"administrative":1}
,"administrative":{"distance":1}
,"routes":{"ipv6":1}
,"ipv6":{"address":1}
,"address":{"family":1}
,"family":{"syntax":1}
,"syntax":{"int":1}
,"int":{"isis_distance_ipv6_set":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1,"tag":1}
,"char":{"*tag":1}
,"*tag":{"u_int32_t":1}
,"u_int32_t":{"distance)":1}
,"distance)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1,"isis_api_set_err_instance_not_exist":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"tag":{"is-is":1,"distance":1,"isis_api_set_err_vr_not_exist":1}
,"is-is":{"instance":1}
,"instance":{"area":1,"exist":1}
,"area":{"tag":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"isis_api_set_err_instance_not_exist":{"is-is":1}
,"exist":{"given":1,"isis_api_set_err_distance_invalid":1}
,"given":{"tag":1}
,"isis_api_set_err_vr_not_exist":{"exist":1}
,"isis_api_set_err_distance_invalid":{"distance":1}
,"within":{"range":1}
,"range":{"isis_api_set_success":1}
,"isis_api_set_success":{"successful":1}
}
;Search.control.loadWordPairs(pairs);
