var pairs =
{
"ptp_port_clock":{"struct":1,"{u_int16_t":1}
,"struct":{"ptp_port_clock":1,"ptp_port_ds":1,"ptp_transparent_clock_port_default_ds":1,"ptp_foreign_master_ds":1,"ptp_protocol_ds":1,"ptp_timestamp":1,"thread":1}
,"{u_int16_t":{"number_foreign_records":1}
,"number_foreign_records":{"s_int32_t":1}
,"s_int32_t":{"ifindex":1}
,"ifindex":{"u_int8_t":1}
,"u_int8_t":{"mac":1,"transport_type":1}
,"mac":{"[6]":1}
,"[6]":{"\u002F*to":1}
,"\u002F*to":{"*\u002Fpal_sock_handle_t":1}
,"*\u002Fpal_sock_handle_t":{"sockfd":1}
,"sockfd":{"pal_sock_handle_t":1}
,"pal_sock_handle_t":{"sockfd_gen":1}
,"sockfd_gen":{"struct":1}
,"ptp_port_ds":{"ptp_port_ds":1,"struct":1}
,"ptp_transparent_clock_port_default_ds":{"ptp_tc_cport_ds":1}
,"ptp_tc_cport_ds":{"struct":1}
,"ptp_foreign_master_ds":{"ptp_fmds":1}
,"ptp_fmds":{"[ptp_num_foreign_recs]":1}
,"[ptp_num_foreign_recs]":{"struct":1}
,"ptp_protocol_ds":{"ptp_proto_ds":1}
,"ptp_proto_ds":{"struct":1}
,"ptp_timestamp":{"last_sync_send_time":1,"last_pdr_send_time":1,"last_dresp_send_time":1,"last_pdreq_recv_time":1,"last_dreq_recv_time":1,"last_delay_req_send_time":1}
,"last_sync_send_time":{"struct":1}
,"last_pdr_send_time":{"struct":1}
,"last_dresp_send_time":{"struct":1}
,"last_pdreq_recv_time":{"struct":1}
,"last_dreq_recv_time":{"struct":1}
,"last_delay_req_send_time":{"struct":1}
,"thread":{"*ptp_rcv_thread":1,"*ptp_rcv_thread_gen":1}
,"*ptp_rcv_thread":{"struct":1}
,"*ptp_rcv_thread_gen":{"u_int8_t":1}
}
;Search.control.loadWordPairs(pairs);
