var pairs =
{
"spb_api_set_system_id":{"function":1,"(char":1}
,"function":{"sets":1,"implements":1,"succeeds":1}
,"sets":{"network-wide":1}
,"network-wide":{"unique":1}
,"unique":{"identifier":1}
,"identifier":{"isis-spb":1,"xx.xx.xx.xx.xx.xx":1}
,"isis-spb":{"process":1,"system-id":1}
,"process":{"function":1}
,"implements":{"isis-spb":1}
,"system-id":{"command":1}
,"command":{"syntax":1}
,"syntax":{"include":1}
,"include":{"spbd\u002Fisis-spb\u002Fspb_isis_api.h":1}
,"spbd\u002Fisis-spb\u002Fspb_isis_api.h":{"int":1}
,"int":{"spb_api_set_system_id":1}
,"(char":{"*bridge_name":1}
,"*bridge_name":{"char":1}
,"char":{"*tag":1}
,"*tag":{"u_char":1}
,"u_char":{"*system_id)":1}
,"*system_id)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bridge_name":1,"none":1}
,"bridge_name":{"bridge":1}
,"bridge":{"name":1,"instance":1}
,"name":{"tag":1}
,"tag":{"instance":1,"system_id":1,"exist":1}
,"instance":{"area":1,"configuration":1,"tag":1,"spb_isis_set_err_too_many_area_addresses":1}
,"area":{"tag":1}
,"system_id":{"system":1,"null":1,"exceeds":1,"already":1}
,"system":{"identifier":1}
,"xx.xx.xx.xx.xx.xx":{"format":1}
,"format":{"hexadecimal":1}
,"hexadecimal":{"numbers":1,"digits":1}
,"numbers":{"separated":1,"spb_isis_set_err_system_id_cant_changed":1}
,"separated":{"periods":1}
,"periods":{"output":1,"spb_isis_set_err_net_invalid_length":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"spb_api_err_arg_null":1}
,"spb_api_err_arg_null":{"parameter":1}
,"parameter":{"null":1}
,"null":{"spb_isis_api_set_error":1,"bridge":1,"spb_api_err_config_update":1,"spb_api_err_isis_instance_not_found":1,"spb_isis_set_err_net_wrong_format":1,"empty":1}
,"spb_isis_api_set_error":{"isis":1}
,"isis":{"master":1}
,"master":{"null":1}
,"configuration":{"null":1,"exists":1}
,"spb_api_err_config_update":{"isis":1}
,"exists":{"spb_api_err_isis_master_not_found":1}
,"spb_api_err_isis_master_not_found":{"isis":1}
,"spb_api_err_isis_instance_not_found":{"given":1}
,"given":{"instance":1}
,"exist":{"result_error":1}
,"result_error":{"system_id":1}
,"spb_isis_set_err_net_wrong_format":{"system_id":1}
,"empty":{"string":1}
,"string":{"contain":1}
,"contain":{"hexadecimal":1}
,"digits":{"periods":1}
,"spb_isis_set_err_net_invalid_length":{"system_id":1}
,"exceeds":{"maximum":1}
,"maximum":{"length":1}
,"length":{"hexadecimal":1}
,"spb_isis_set_err_system_id_cant_changed":{"different":1}
,"different":{"system_id":1}
,"already":{"instance":1}
,"spb_isis_set_err_too_many_area_addresses":{"addresses":1}
,"addresses":{"spb_isis_api_set_success":1}
,"spb_isis_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
