var pairs =
{
"lldp":{"med-devtype":1,"device":1,"med-devtyp":1}
,"med-devtype":{"command":1,"(net-connect":1,"ep-class1":1}
,"command":{"configure":1,"syntax":1,"mode":1}
,"configure":{"lldp":1,"terminal":1}
,"device":{"type":1,"parameter":1}
,"type":{"network-connectivity\u002Fend-point":1,"command":1,"network-connectivity":1,"end-point":1}
,"network-connectivity\u002Fend-point":{"class1\u002Fend-point":1}
,"class1\u002Fend-point":{"class2\u002Fend-point":1}
,"class2\u002Fend-point":{"class3":1}
,"class3":{"device":1,"default":1}
,"parameter":{"configured":1}
,"configured":{"lldp":1}
,"syntax":{"lldp":1}
,"(net-connect":{"ep-class1":1}
,"ep-class1":{"ep-class2":1,"device":1,"(config-if)":1}
,"ep-class2":{"ep-class3)":1,"device":1}
,"ep-class3)":{"lldp":1,"parameters":1}
,"parameters":{"net-connect":1}
,"net-connect":{"device":1}
,"network-connectivity":{"ep-class1":1}
,"end-point":{"class1":1,"class2":1,"class3":1}
,"class1":{"ep-class2":1}
,"class2":{"ep-class3":1}
,"ep-class3":{"device":1}
,"default":{"none":1}
,"none":{"command":1}
,"mode":{"interface":1,"examples":1}
,"interface":{"mode":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"int":1}
,"int":{"eth0":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"lldp":1,"exit":1}
,"exit":{"configure":1}
,"med-devtyp":{"(config-if)":1}
}
;Search.control.loadWordPairs(pairs);
