var pairs =
{
"show":{"mvrp":1}
,"mvrp":{"machine":1}
,"machine":{"command":1,"state":1,"bridge":1}
,"command":{"display":1,"syntax":1,"mode":1,"displays":1}
,"display":{"mvrp":1}
,"state":{"specific":1,"mvrp-enabled":1,"[0]":1}
,"specific":{"bridge":1}
,"bridge":{"command":1,"bridge_name":1,"identifier":1,"show":1,"port":1}
,"syntax":{"show":1}
,"bridge_name":{"parameter":1,"bridge":1}
,"parameter":{"bridge_name":1}
,"identifier":{"command":1}
,"mode":{"exec":1,"example":1}
,"exec":{"privileged":1,"mode":1}
,"privileged":{"exec":1}
,"example":{"following":1}
,"following":{"sample":1}
,"sample":{"output":1}
,"output":{"command":1}
,"displays":{"mvrp":1}
,"mvrp-enabled":{"bridge":1}
,"port":{"=eth2":1}
,"=eth2":{"applicant":1}
,"applicant":{"state":1}
,"[0]":{"=vo":1,"=in":1}
,"=vo":{"registrar":1}
,"registrar":{"state":1}
}
;Search.control.loadWordPairs(pairs);
