var pairs =
{
"supported":{"modules":1}
,"modules":{"section":1,"support":1,"zebos-xp":1,"nsm":1}
,"section":{"describes":1}
,"describes":{"zebos-xp":1}
,"zebos-xp":{"modules":1,"using":1,"uses":1}
,"support":{"satop":1}
,"satop":{"implementation":1}
,"implementation":{"nsm":1}
,"nsm":{"network":1,"shares":1,"create":1,"services":1,"needs":1}
,"network":{"service":1}
,"service":{"manager":1}
,"manager":{"(nsm)":1}
,"(nsm)":{"manages":1}
,"manages":{"information":1}
,"information":{"related":1,"modules":1,"received":1,"hal":1}
,"related":{"routes":1}
,"routes":{"nsm":1}
,"shares":{"information":1}
,"using":{"asynchronous":1}
,"asynchronous":{"sockets":1}
,"sockets":{"created":1}
,"created":{"startup":1,"process":1}
,"startup":{"handles":1}
,"handles":{"creation":1}
,"creation":{"maintenance":1}
,"maintenance":{"pseudowires":1}
,"pseudowires":{"nsm":1}
,"create":{"virtual":1}
,"virtual":{"interfaces":1,"circuit":1}
,"interfaces":{"attach":1,"virtual":1}
,"attach":{"virtual":1}
,"circuit":{"created":1}
,"process":{"status":1}
,"status":{"information":1}
,"received":{"peers":1}
,"peers":{"ldp":1}
,"ldp":{"label":1,"used":1,"(tldp)":1,"protocol":1}
,"label":{"distribution":1,"(vc\u002Fvpn\u002Fservice":1,"(path":1}
,"distribution":{"protocol":1,"targeted":1}
,"protocol":{"(ldp)":1,"runs":1}
,"(ldp)":{"routing":1}
,"routing":{"component":1,"information":1}
,"component":{"mpls":1}
,"mpls":{"technology":1,"environment":1,"inner":1}
,"technology":{"distributes":1}
,"distributes":{"labels":1}
,"labels":{"mpls":1}
,"environment":{"ldp":1}
,"used":{"distribute":1,"ldp":1,"daemons":1}
,"distribute":{"inner":1}
,"inner":{"label":1}
,"(vc\u002Fvpn\u002Fservice":{"label)":1}
,"label)":{"outer":1,"mpls":1}
,"outer":{"label":1}
,"(path":{"label)":1}
,"targeted":{"ldp":1}
,"(tldp)":{"used":1}
,"runs":{"separate":1}
,"separate":{"daemon":1}
,"daemon":{"zebos-xp":1}
,"uses":{"nsm":1}
,"services":{"obtain":1}
,"obtain":{"routing":1}
,"hal":{"hardware":1,"hsl":1,"error":1}
,"hardware":{"abstraction":1}
,"abstraction":{"layer":1}
,"layer":{"(hal)":1}
,"(hal)":{"module":1}
,"module":{"library":1}
,"library":{"used":1}
,"daemons":{"communicate":1}
,"communicate":{"l2swfw":1}
,"l2swfw":{"hal":1}
,"hsl":{"modules":1}
,"needs":{"interact":1}
,"interact":{"hal":1}
,"error":{"notifications":1}
,"notifications":{"statistics":1}
,"statistics":{"required":1}
,"required":{"implemented":1}
,"implemented":{"part":1}
,"part":{"development":1}
}
;Search.control.loadWordPairs(pairs);
