var pairs =
{
"overview":{"cli":1}
,"cli":{"configure":1,"text-based":1}
,"configure":{"monitor":1}
,"monitor":{"maintain":1}
,"maintain":{"zebos-xp":1}
,"zebos-xp":{"devices":1,"remotely":1}
,"devices":{"cli":1}
,"text-based":{"command":1}
,"command":{"usually":1}
,"usually":{"associated":1}
,"associated":{"specific":1}
,"specific":{"task":1}
,"task":{"give":1}
,"give":{"commands":1}
,"commands":{"described":1,"scripts":1}
,"described":{"manual":1}
,"manual":{"locally":1}
,"locally":{"console":1}
,"console":{"device":1}
,"device":{"running":1}
,"running":{"zebos-xp":1}
,"remotely":{"terminal":1}
,"terminal":{"emulator":1}
,"emulator":{"putty":1}
,"putty":{"xterm":1}
,"xterm":{"commands":1}
,"scripts":{"automate":1}
,"automate":{"configuration":1}
,"configuration":{"tasks":1}
}
;Search.control.loadWordPairs(pairs);
