var pairs =
{
"associate":{"interfaces":1}
,"interfaces":{"vrfs":1,"belong":1,"(connected":1}
,"vrfs":{"vrfs":1,"defined":1,"following":1}
,"defined":{"router":1}
,"router":{"router":1,"needs":1}
,"needs":{"recognize":1}
,"recognize":{"interfaces":1}
,"belong":{"vrf":1}
,"vrf":{"vrf":1,"populated":1,"associate":1,"forwarding":1,"named":1}
,"populated":{"routes":1}
,"routes":{"connected":1}
,"connected":{"sites":1}
,"sites":{"interface":1}
,"interface":{"belong":1,"mode":1,"eth1":1}
,"(connected":{"routers)":1}
,"routers)":{"vrfs":1}
,"following":{"command":1,"example":1}
,"command":{"interface":1,"reference":1}
,"mode":{"(see":1}
,"(see":{"border":1}
,"border":{"gateway":1}
,"gateway":{"protocol":1}
,"protocol":{"command":1}
,"reference":{"details)":1}
,"details)":{"vrf":1}
,"forwarding":{"vrf-name":1,"comb":1}
,"vrf-name":{"following":1}
,"example":{"interface":1}
,"eth1":{"associated":1,"(config-if)":1}
,"associated":{"vrf":1}
,"named":{"comb":1}
,"comb":{"(config)":1}
,"(config)":{"interface":1}
,"(config-if)":{"vrf":1}
}
;Search.control.loadWordPairs(pairs);
