var pairs =
{
"data":{"instance":1,"value":1}
,"instance":{"triggered":1,"(di)":1}
,"triggered":{"update":1}
,"update":{"addition":1}
,"addition":{"triggering":1}
,"triggering":{"full":1}
,"full":{"status":1}
,"status":{"full":1,"continued":1,"inquiry":1,"uni-c":1,"report":1,"procedure":1,"change":1,"elmi":1}
,"continued":{"reports":1,"report":1}
,"reports":{"every":1,"time":1,"including":1,"value":1}
,"every":{"n391":1}
,"n391":{"polling":1}
,"polling":{"cycles":1}
,"cycles":{"data":1,"uni-c":1}
,"(di)":{"used":1}
,"used":{"trigger":1}
,"trigger":{"reports":1}
,"time":{"change":1}
,"change":{"evc":1,"until":1,"information":1,"results":1,"data":1,"sent":1}
,"evc":{"uni":1,"stored":1,"including":1}
,"uni":{"information":1,"evc":1}
,"information":{"eliminates":1,"uni-c":1,"sent":1,"uni":1,"related":1}
,"eliminates":{"delay":1}
,"delay":{"receiving":1}
,"receiving":{"information":1}
,"uni-c":{"experience":1,"uni-c":1,"starts":1,"sends":1,"receives":1,"sets":1,"updating":1,"change":1}
,"experience":{"information":1}
,"sent":{"every":1,"uni-n":1,"first":1}
,"starts":{"restarts":1}
,"restarts":{"sets":1}
,"sets":{"zero":1,"uni-n":1,"value":1}
,"zero":{"(0)":1,"skipped":1}
,"(0)":{"uni-c":1}
,"sends":{"elmi":1}
,"elmi":{"status":1,"full":1,"check":1,"includes":1}
,"inquiry":{"report":1,"triggers":1,"elmi":1}
,"report":{"type":1,"elmi":1,"value":1,"until":1}
,"type":{"full":1}
,"receives":{"full":1}
,"including":{"latest":1,"status":1}
,"latest":{"information":1}
,"stored":{"local":1}
,"local":{"database":1,"uni-c":1,"uni-n":1}
,"database":{"afterwards":1}
,"afterwards":{"local":1}
,"uni-n":{"received":1,"change":1,"value":1,"uni-n":1,"first":1,"changes":1,"responds":1}
,"received":{"full":1,"first":1,"uni-c":1}
,"value":{"sent":1,"full":1,"non-zero":1,"different":1,"received":1,"reflect":1,"zero":1}
,"until":{"status":1}
,"procedure":{"complete":1,"errors":1}
,"complete":{"full":1,"elmi":1}
,"errors":{"results":1}
,"results":{"uni-c":1,"incrementing":1}
,"updating":{"local":1}
,"triggers":{"uni-n":1}
,"first":{"comes":1,"message":1,"full":1}
,"comes":{"sets":1}
,"non-zero":{"value":1}
,"different":{"value":1}
,"message":{"received":1}
,"related":{"either":1}
,"either":{"uni":1}
,"incrementing":{"value":1}
,"reflect":{"change":1}
,"skipped":{"whenever":1}
,"whenever":{"uni-n":1}
,"changes":{"increment":1}
,"increment":{"full":1}
,"check":{"upon":1,"uni-n":1}
,"upon":{"receipt":1}
,"receipt":{"elmi":1}
,"responds":{"status":1}
,"includes":{"current":1}
,"current":{"value":1}
}
;Search.control.loadWordPairs(pairs);
