var pairs =
{
"enable":{"cnpv":1,"bridge":1,"txrx":1,"sample-base":1}
,"cnpv":{"create":1,"cnpv":1,"value":1}
,"create":{"configure":1,"bridge":1}
,"configure":{"terminal":1,"mode":1,"interface":1,"eth1":1,"lldp":1,"congestion":1}
,"terminal":{"enter":1}
,"enter":{"configure":1}
,"mode":{"(config)":1,"eth1":1}
,"(config)":{"bridge":1,"data-center-bridging":1,"qcn":1,"interface":1}
,"bridge":{"protocol":1,"ieee":1,"(config)":1,"enables":1,"(config-qcn)":1,"group":1}
,"protocol":{"ieee":1}
,"ieee":{"vlan-bridge":1,"vlan":1,"802.1":1}
,"vlan-bridge":{"create":1}
,"vlan":{"enabled":1}
,"enabled":{"bridge":1}
,"data-center-bridging":{"enable":1}
,"enables":{"dcb":1,"qcn":1}
,"dcb":{"bridge":1}
,"qcn":{"enable":1,"bridge":1,"enabled":1,"mode":1}
,"(config-qcn)":{"cnpv":1,"exit":1}
,"value":{"qcn":1}
,"exit":{"exit":1,"qcn":1}
,"interface":{"eth1":1}
,"eth1":{"configure":1,"(config-if)":1,"asa":1,"bridge":1}
,"(config-if)":{"switchport":1,"bridge-group":1,"lldp":1,"enable":1}
,"switchport":{"configure":1}
,"asa":{"layer":1}
,"layer":{"port":1}
,"port":{"(config-if)":1}
,"bridge-group":{"configure":1}
,"group":{"(config-if)":1}
,"lldp":{"enable":1,"transmit":1,"tlv":1,"send":1}
,"txrx":{"configure":1}
,"transmit":{"receive":1}
,"receive":{"mode":1}
,"tlv":{"ieee-8021-org-specific":1,"(config-if)":1}
,"ieee-8021-org-specific":{"configure":1}
,"send":{"ieee":1}
,"802.1":{"organizationally":1}
,"organizationally":{"specific":1}
,"specific":{"tlv":1}
,"sample-base":{"10000":1}
,"10000":{"weight":1}
,"weight":{"configure":1}
,"congestion":{"point":1}
}
;Search.control.loadWordPairs(pairs);
