var pairs =
{
"operation":{"elmi":1}
,"elmi":{"protocol":1,"similar":1,"manage":1,"terminates":1,"utilizes":1,"depends":1,"relies":1}
,"protocol":{"enables":1}
,"enables":{"request":1,"device":1}
,"request":{"receive":1}
,"receive":{"status":1}
,"status":{"service":1,"evcs":1}
,"service":{"data":1}
,"data":{"men":1}
,"men":{"enables":1,"users":1,"side":1}
,"device":{"configure":1,"(provider":1,"zebos-xp":1}
,"configure":{"network":1}
,"network":{"access":1}
,"access":{"metro":1}
,"metro":{"ethernet":1}
,"ethernet":{"services":1}
,"services":{"functionality":1,"module)":1}
,"functionality":{"elmi":1,"located":1}
,"similar":{"frame":1}
,"frame":{"relay":1}
,"relay":{"lmi":1}
,"lmi":{"however":1}
,"however":{"unlike":1}
,"unlike":{"fr-lmi":1}
,"fr-lmi":{"elmi":1}
,"manage":{"link":1}
,"link":{"men":1,"management":1,"operate":1}
,"users":{"provide":1}
,"provide":{"link":1}
,"management":{"two":1,"function":1}
,"two":{"interfaces":1}
,"interfaces":{"means":1}
,"means":{"link":1}
,"function":{"ieee":1}
,"ieee":{"802.3":1}
,"802.3":{"elmi":1}
,"terminates":{"uni-c":1}
,"uni-c":{"side":1}
,"side":{"uni-n":1,"elmi":1}
,"uni-n":{"men":1}
,"utilizes":{"point-to-point":1}
,"point-to-point":{"connection":1}
,"connection":{"link":1}
,"operate":{"device":1}
,"(provider":{"edge)":1}
,"edge)":{"device":1}
,"zebos-xp":{"architecture":1}
,"architecture":{"uni":1}
,"uni":{"functionality":1,"furthermore":1}
,"located":{"nsm":1}
,"nsm":{"(network":1,"information":1}
,"(network":{"services":1}
,"module)":{"elmi":1}
,"depends":{"nsm":1}
,"information":{"regarding":1}
,"regarding":{"attributes":1}
,"attributes":{"evc":1}
,"evc":{"uni":1}
,"furthermore":{"elmi":1}
,"relies":{"cfm":1}
,"cfm":{"(connectivity":1,"domain":1}
,"(connectivity":{"fault":1}
,"fault":{"management)":1}
,"management)":{"end-to-end":1}
,"end-to-end":{"status":1}
,"evcs":{"across":1}
,"across":{"cfm":1}
}
;Search.control.loadWordPairs(pairs);
