var pairs =
{
"g8031":{"local-lockout":1,"configure":1}
,"local-lockout":{"command":1,"g8031":1,"parameters":1,"(g8031-config-switching)":1}
,"command":{"prevent":1,"failure":1,"protection":1,"clear":1,"syntax":1,"mode":1}
,"prevent":{"normal":1,"protocol":1,"selected":1}
,"normal":{"traffic":1}
,"traffic":{"signals":1,"signal":1,"indication":1}
,"signals":{"selected":1}
,"selected":{"protection":1}
,"protection":{"entity":1,"transport":1,"switching":1}
,"entity":{"bidirectional":1,"ends":1,"result":1,"commands":1}
,"bidirectional":{"switching":1}
,"switching":{"remote":1,"local":1,"mode":1,"eps-id":1}
,"remote":{"bridge":1}
,"bridge":{"requests":1,"(g8031-config-switching)":1}
,"requests":{"normal":1}
,"signal":{"honored":1,"locked":1,"selected":1,"rejected":1,"degrade":1}
,"honored":{"prevent":1}
,"protocol":{"failures":1}
,"failures":{"result":1}
,"result":{"normal":1,"command":1}
,"locked":{"protection":1}
,"transport":{"entity":1}
,"ends":{"prevent":1}
,"failure":{"either":1,"(sf)":1}
,"either":{"end":1}
,"end":{"command":1}
,"local":{"(near-end)":1}
,"(near-end)":{"request":1}
,"request":{"prevent":1}
,"commands":{"normal":1}
,"rejected":{"normal":1}
,"indication":{"switch":1}
,"switch":{"failure":1}
,"(sf)":{"signal":1}
,"degrade":{"(sd)":1}
,"(sd)":{"applicable":1}
,"applicable":{"ignored":1}
,"ignored":{"form":1}
,"form":{"command":1}
,"clear":{"local-lockout":1}
,"syntax":{"g8031":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"g8031":1,"examples":1}
,"configure":{"switching":1,"terminal":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"g8031":1}
,"eps-id":{"bridge":1}
,"(g8031-config-switching)":{"g8031":1}
}
;Search.control.loadWordPairs(pairs);
