var pairs =
{
"shortest":{"path":1}
,"path":{"bridging":1,"is-is":1,"trees":1,"shortest":1,"spbv":1}
,"bridging":{"overview":1,"ieee":1,"(spb)":1,"-vid":1,"-mac":1}
,"overview":{"chapter":1,"zebos-xp":1}
,"chapter":{"overview":1}
,"zebos-xp":{"implementation":1}
,"implementation":{"shortest":1}
,"ieee":{"802.1aq":1}
,"802.1aq":{"shortest":1,"spb":1}
,"(spb)":{"control":1}
,"control":{"plane":1}
,"plane":{"protocol":1,"algorithms":1}
,"protocol":{"combines":1,"running":1}
,"combines":{"ethernet":1}
,"ethernet":{"data":1}
,"data":{"path":1}
,"is-is":{"(intermediate":1,"link":1,"extensions":1}
,"(intermediate":{"system":1}
,"system":{"intermediate":1}
,"intermediate":{"system)":1}
,"system)":{"link":1}
,"link":{"state":1}
,"state":{"protocol":1,"packets":1}
,"running":{"bridges":1}
,"bridges":{"spb":1}
,"spb":{"depend":1,"area":1,"two":1,"depending":1,"edge":1}
,"depend":{"spanning":1}
,"spanning":{"tree":1}
,"tree":{"protocols":1,"technologies":1}
,"protocols":{"provide":1}
,"provide":{"loop-free":1}
,"loop-free":{"topology":1}
,"topology":{"instead":1,"compute":1}
,"instead":{"uses":1}
,"uses":{"is-is":1,"802.1ad":1,"802.1ah":1}
,"packets":{"(lsps)":1}
,"(lsps)":{"discover":1}
,"discover":{"advertise":1}
,"advertise":{"network":1}
,"network":{"topology":1}
,"compute":{"shortest":1}
,"trees":{"bridges":1}
,"area":{"rfc":1}
,"rfc":{"6329":1}
,"6329":{"describes":1}
,"describes":{"is-is":1}
,"extensions":{"support":1}
,"support":{"802.1aq":1}
,"two":{"types":1}
,"types":{"spb":1}
,"depending":{"type":1}
,"type":{"ethernet":1}
,"-vid":{"(spbv)":1}
,"(spbv)":{"uses":1}
,"802.1ad":{"q-in-q":1}
,"q-in-q":{"data":1}
,"-mac":{"(spbm)":1}
,"(spbm)":{"uses":1}
,"802.1ah":{"mac-in-mac":1}
,"mac-in-mac":{"data":1}
,"spbv":{"spbm":1}
,"spbm":{"share":1,"fully":1}
,"share":{"control":1}
,"algorithms":{"common":1}
,"common":{"routing":1}
,"routing":{"mechanisms":1}
,"mechanisms":{"spbv":1}
,"fully":{"interoperable":1}
,"interoperable":{"spanning":1}
,"technologies":{"(mstp":1}
,"(mstp":{"rstp)":1}
,"rstp)":{"spb":1}
}
;Search.control.loadWordPairs(pairs);
