var pairs =
{
"bfd_api_set_sess_req_min_rx_intvl":{"function":1,"(struct":1}
,"function":{"used":1,"fails":1,"succeeds":1}
,"used":{"session":1}
,"session":{"required":1,"index":1}
,"required":{"minimum":1}
,"minimum":{"receive":1,"bfd":1}
,"receive":{"interval":1}
,"interval":{"snmp":1}
,"snmp":{"request":1,"enable":1,"output":1}
,"request":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"bfd_api_set_sess_req_min_rx_intvl":1}
,"(struct":{"bfd":1}
,"bfd":{"*bfd":1,"pointer":1,"structure":1,"reception":1}
,"*bfd":{"u_int32_t":1}
,"u_int32_t":{"index":1,"min_rx":1}
,"index":{"u_int32_t":1,"session":1,"min_rx":1}
,"min_rx":{"bool_t":1,"minimum":1}
,"bool_t":{"snmp)":1}
,"snmp)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bfd":1}
,"pointer":{"bfd":1}
,"structure":{"index":1}
,"reception":{"milliseconds":1}
,"milliseconds":{"snmp":1}
,"enable":{"snmp":1}
,"output":{"parameter":1}
,"parameter":{"none":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"bfd_failure":1}
,"bfd_failure":{"function":1}
,"fails":{"bfd_success":1}
,"bfd_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
