var pairs =
{
"trill_cli_show_fdb":{"function":1,"(struct":1}
,"function":{"shows":1}
,"shows":{"details":1}
,"details":{"specified":1}
,"specified":{"forwarding":1}
,"forwarding":{"table":1}
,"table":{"unicast":1,"including":1}
,"unicast":{"multicast":1}
,"multicast":{"detail":1}
,"detail":{"called":1,"output":1}
,"called":{"show":1}
,"show":{"trill":1}
,"trill":{"fdb":1}
,"fdb":{"cli":1}
,"cli":{"command":1,"*cli":1,"structure":1}
,"command":{"located":1}
,"located":{"trill_cli.c":1}
,"trill_cli.c":{"file":1}
,"file":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"trill_cli_show_fdb":1}
,"(struct":{"cli":1}
,"*cli":{"char":1,"specifies":1}
,"char":{"*level_str)":1}
,"*level_str)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"*cli":1,"none":1}
,"specifies":{"instance":1,"forwarding":1}
,"instance":{"cli":1}
,"structure":{"values":1}
,"values":{"includes":1}
,"includes":{"1-31":1}
,"1-31":{"*level_str":1}
,"*level_str":{"specifies":1}
,"including":{"unicast":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"cli_success":1}
,"cli_success":{"cli_error":1}
}
;Search.control.loadWordPairs(pairs);
