var pairs =
{
"show":{"ethernet":1}
,"ethernet":{"lmi":1}
,"lmi":{"evc":1}
,"evc":{"command":1,"(bridge":1,"bridge":1,"port":1}
,"command":{"display":1,"syntax":1,"modes":1}
,"display":{"bridge":1}
,"bridge":{"information":1,"indicates":1,"evc":1}
,"information":{"configured":1}
,"configured":{"evcs":1}
,"evcs":{"(ethernet":1}
,"(ethernet":{"virtual":1}
,"virtual":{"connections)":1}
,"connections)":{"command":1}
,"syntax":{"show":1}
,"(bridge":{"<1-32>":1}
,"<1-32>":{"parameters":1,"displays":1}
,"parameters":{"bridge":1}
,"indicates":{"bridge-group":1}
,"bridge-group":{"parameter":1,"used":1}
,"parameter":{"<1-32>":1}
,"displays":{"actual":1}
,"actual":{"bridge-group":1}
,"used":{"bridging":1}
,"bridging":{"command":1}
,"modes":{"executive":1}
,"executive":{"mode":1}
,"mode":{"privileged":1,"examples":1}
,"privileged":{"executive":1}
,"examples":{"show":1}
,"port":{"-------------------------------------------------key":1}
,"-------------------------------------------------key":{"st=status":1}
,"st=status":{"a=active":1}
,"a=active":{"p=partially":1}
,"p=partially":{"active":1}
,"active":{"i=inactive":1,"n_p=new":1,"n_i=new":1,"?=link":1}
,"i=inactive":{"n_a=new":1}
,"n_a=new":{"active":1}
,"n_p=new":{"partially":1}
,"partially":{"active":1}
,"n_i=new":{"active":1}
,"?=link":{"down":1}
}
;Search.control.loadWordPairs(pairs);
