var pairs =
{
"ospf6_redistribute_metric_type_set":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"called":1,"succeeds":1}
,"sets":{"metric":1}
,"metric":{"type":1,"external_metric_type_2":1,"output":1}
,"type":{"redistributed":1,"constants":1,"(see":1,"metric":1,"valid":1}
,"redistributed":{"route":1,"protocol":1}
,"route":{"function":1}
,"called":{"following":1}
,"following":{"commands":1}
,"commands":{"redistribute":1}
,"redistribute":{"metric-type":1,"ospf":1}
,"metric-type":{"default-information":1,"syntax":1}
,"default-information":{"originate":1}
,"originate":{"metric-type":1}
,"syntax":{"int":1}
,"int":{"ospf6_redistribute_metric_type_set":1,"proto":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1}
,"char":{"*tag":1}
,"*tag":{"int":1}
,"proto":{"void":1,"redistributed":1}
,"void":{"*stag":1}
,"*stag":{"u_char":1}
,"u_char":{"mtype)":1}
,"mtype)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"exist":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"tag":1}
,"tag":{"ospfv3":1,"proto":1,"ospf":1,"exist":1}
,"ospfv3":{"process":1,"routes":1}
,"process":{"tag":1,"identifier":1,"exist":1}
,"protocol":{"type":1}
,"constants":{"pal\u002Fapi\u002Fpal_types.def":1,"lib\u002Fospf_common\u002Fospf_const.h":1}
,"pal\u002Fapi\u002Fpal_types.def":{"ipi_route_default":1}
,"ipi_route_default":{"system":1}
,"system":{"ipi_route_kernel":1}
,"ipi_route_kernel":{"kernel":1}
,"kernel":{"routes":1}
,"routes":{"ipi_route_connect":1,"ipi_route_static":1,"ipi_route_rip":1,"ipi_route_ripng":1,"ipi_route_bgp":1,"ipi_route_isis":1,"ipi_route_ospf":1,"ipi_route_ospf6":1,"stag":1}
,"ipi_route_connect":{"connected":1}
,"connected":{"routes":1}
,"ipi_route_static":{"static":1}
,"static":{"routes":1}
,"ipi_route_rip":{"rip":1}
,"rip":{"routes":1}
,"ipi_route_ripng":{"ripng":1}
,"ripng":{"routes":1}
,"ipi_route_bgp":{"bgp":1}
,"bgp":{"routes":1}
,"ipi_route_isis":{"is-is":1}
,"is-is":{"routes":1}
,"ipi_route_ospf":{"ospfv2":1}
,"ospfv2":{"routes":1}
,"ipi_route_ospf6":{"ospfv3":1}
,"stag":{"ospfv3":1}
,"ospf":{"process":1,"instance":1,"external":1}
,"identifier":{"used":1}
,"used":{"redistribute":1}
,"instance":{"ospf":1,"mtype":1}
,"mtype":{"metric":1}
,"(see":{"rfc":1}
,"rfc":{"3101)":1}
,"3101)":{"constants":1}
,"lib\u002Fospf_common\u002Fospf_const.h":{"external_metric_type_1":1}
,"external_metric_type_1":{"ospf":1}
,"external":{"type":1}
,"external_metric_type_2":{"ospf":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf6_api_set_err_vr_not_exist":1}
,"ospf6_api_set_err_vr_not_exist":{"virtual":1}
,"exist":{"ospf6_api_set_err_process_not_exist":1,"ospf6_api_set_err_redistribute_proto_invalid":1,"ospf6_api_set_success":1}
,"ospf6_api_set_err_process_not_exist":{"specified":1}
,"specified":{"process":1}
,"ospf6_api_set_err_redistribute_proto_invalid":{"given":1}
,"given":{"protocol":1,"metric":1,"process":1}
,"valid":{"ospf6_api_set_err_metric_type_invalid":1,"ospf6_api_set_err_redistribute_proto_tag_invalid":1}
,"ospf6_api_set_err_metric_type_invalid":{"given":1}
,"ospf6_api_set_err_redistribute_proto_tag_invalid":{"given":1}
,"ospf6_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
