var pairs =
{
"system":{"operation":1}
,"operation":{"enabling":1}
,"enabling":{"elmi":1}
,"elmi":{"protocol":1,"frames":1}
,"protocol":{"utilizes":1,"running":1}
,"utilizes":{"nsm":1}
,"nsm":{"data":1,"elmi":1,"running":1}
,"data":{"regarding":1,"structure":1,"updates":1}
,"regarding":{"attributes":1}
,"attributes":{"evcs":1,"uni":1}
,"evcs":{"unis":1}
,"unis":{"upon":1}
,"upon":{"receiving":1}
,"receiving":{"information":1,"message":1}
,"information":{"nsm":1,"uni-n":1}
,"running":{"uni-n":1,"device":1}
,"uni-n":{"updates":1,"uni-c":1}
,"updates":{"data":1,"database":1,"related":1}
,"structure":{"sends":1,"executing":1}
,"sends":{"elmi":1,"full":1,"messages":1}
,"frames":{"uni-c":1}
,"uni-c":{"upon":1,"buffers":1,"sends":1}
,"message":{"uni-c":1,"polling":1}
,"buffers":{"received":1}
,"received":{"data":1}
,"database":{"latest":1,"structure":1}
,"latest":{"information":1}
,"full":{"status":1}
,"status":{"inquiry":1,"evc":1}
,"inquiry":{"message":1}
,"polling":{"timer":1}
,"timer":{"starts":1}
,"starts":{"operator":1}
,"operator":{"view":1}
,"view":{"database":1}
,"executing":{"related":1}
,"related":{"cli":1,"bridge":1}
,"cli":{"commands":1}
,"commands":{"addition":1}
,"addition":{"nsm":1}
,"device":{"sends":1}
,"messages":{"requesting":1}
,"requesting":{"updates":1}
,"bridge":{"interface":1}
,"interface":{"vlan":1}
,"vlan":{"requests":1}
,"requests":{"status":1}
,"evc":{"attributes":1}
}
;Search.control.loadWordPairs(pairs);
