var pairs =
{
"trill_static_multicast_listener_set":{"function":1,"(struct":1}
,"function":{"adds":1,"call":1}
,"adds":{"multicast":1}
,"multicast":{"listener":1,"mac":1}
,"listener":{"specified":1}
,"specified":{"neighbor":1}
,"neighbor":{"called":1,"macaddr":1}
,"called":{"add":1}
,"add":{"static":1}
,"static":{"multicast-trill-fdb":1}
,"multicast-trill-fdb":{"multicast-listener":1}
,"multicast-listener":{"mcastmac-address":1}
,"mcastmac-address":{"nbr-nickname":1}
,"nbr-nickname":{"cli":1}
,"cli":{"command":1,"*cli":1,"structure":1}
,"command":{"contained":1}
,"contained":{"trill_api.c":1}
,"trill_api.c":{"file":1}
,"file":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"trill_static_multicast_listener_set":1}
,"(struct":{"cli":1}
,"*cli":{"u_int16_t":1,"specifies":1}
,"u_int16_t":{"neighbor_nck":1,"vlan)":1}
,"neighbor_nck":{"u_char*macaddr":1,"specifies":1}
,"u_char*macaddr":{"u_int16_t":1}
,"vlan)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"*cli":1,"none":1}
,"specifies":{"instance":1,"nickname":1,"multicast":1,"vlan":1}
,"instance":{"cli":1}
,"structure":{"values":1}
,"values":{"includes":1,"trill_api_set_success":1}
,"includes":{"1-31":1}
,"1-31":{"neighbor_nck":1}
,"nickname":{"neighbor":1}
,"macaddr":{"specifies":1}
,"mac":{"address":1}
,"address":{"vlan":1}
,"vlan":{"specifies":1,"<1-4094>":1}
,"<1-4094>":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"trill_api_set_success":{"indicates":1}
,"indicates":{"function":1,"duplicated":1,"memory":1}
,"call":{"worked":1}
,"worked":{"properly":1}
,"properly":{"trill_api_set_err_entry_exist":1}
,"trill_api_set_err_entry_exist":{"indicates":1}
,"duplicated":{"entry":1}
,"entry":{"remove":1,"trill_api_set_err_tag_too_long":1}
,"remove":{"old":1}
,"old":{"data":1}
,"data":{"entry":1}
,"trill_api_set_err_tag_too_long":{"tag":1}
,"tag":{"length":1}
,"length":{"exceeds":1}
,"exceeds":{"characters":1}
,"characters":{"trill_err_memory_alloc_failure":1}
,"trill_err_memory_alloc_failure":{"indicates":1}
,"memory":{"available":1}
}
;Search.control.loadWordPairs(pairs);
