var pairs =
{
"mrib4_igmp_api_if_lmqi_unset":{"function":1,"(struct":1}
,"function":{"unsets":1,"succeeds":1}
,"unsets":{"last-member":1}
,"last-member":{"query-interval":1}
,"query-interval":{"default":1}
,"default":{"value":1}
,"value":{"syntax":1,"output":1}
,"syntax":{"int":1}
,"int":{"mrib4_igmp_api_if_lmqi_unset":1}
,"(struct":{"igmp_instance":1}
,"igmp_instance":{"*igi":1}
,"*igi":{"struct":1}
,"struct":{"interface":1}
,"interface":{"*ifp":1,"is_lmqi":1,"null":1,"layer-2":1,"igmp_err_no_such_iff":1,"specified":1}
,"*ifp":{"bool_t":1}
,"bool_t":{"is_lmqi)":1}
,"is_lmqi)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"igi":1,"none":1}
,"igi":{"pointer":1}
,"pointer":{"igmp":1,"interface":1}
,"igmp":{"instance":1,"protocol":1}
,"instance":{"ifp":1,"specified":1}
,"ifp":{"pointer":1}
,"is_lmqi":{"lmqi":1}
,"lmqi":{"value":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"igmp_err_none":1,"given":1}
,"igmp_err_none":{"function":1}
,"succeeds":{"igmp_err_invalid_value":1}
,"igmp_err_invalid_value":{"igmp":1}
,"specified":{"interface":1,"found":1}
,"null":{"supported":1}
,"supported":{"values":1}
,"given":{"igmp_err_l2_physical_if":1}
,"igmp_err_l2_physical_if":{"specified":1}
,"layer-2":{"interface":1}
,"igmp_err_no_such_iff":{"interface":1}
,"found":{"igmp_err_malformed_arg":1,"igmp_err_no_such_source_rec":1,"igmp_err_buf_too_short":1}
,"igmp_err_malformed_arg":{"argument":1}
,"argument":{"malformed":1}
,"malformed":{"igmp_err_no_such_group_rec":1}
,"igmp_err_no_such_group_rec":{"group":1}
,"group":{"record":1}
,"record":{"found":1}
,"igmp_err_no_such_source_rec":{"source":1}
,"source":{"record":1,"encountered":1}
,"igmp_err_buf_too_short":{"processing":1}
,"processing":{"exceeds":1}
,"exceeds":{"buffer":1}
,"buffer":{"space":1}
,"space":{"igmp_err_no_src_enc":1}
,"igmp_err_no_src_enc":{"source":1}
,"encountered":{"igmp_err_oom":1}
,"igmp_err_oom":{"memory":1}
,"memory":{"allocation":1}
,"allocation":{"error":1}
,"error":{"occurs":1}
,"occurs":{"igmp_err_doom":1}
,"igmp_err_doom":{"igmp":1}
,"protocol":{"fails":1}
,"fails":{"igmp_err_generic":1,"igmp_err_no_valid_config":1}
,"igmp_err_generic":{"operation":1}
,"operation":{"fails":1,"igmp_err_qri_gt_qi":1}
,"igmp_err_no_valid_config":{"invalid":1}
,"invalid":{"configuration":1}
,"configuration":{"operation":1}
,"igmp_err_qri_gt_qi":{"query-response":1}
,"query-response":{"interval":1}
,"interval":{"less":1,"igmp_err_qi_le_qri":1,"greater":1,"result_ok":1}
,"less":{"query":1}
,"query":{"interval":1}
,"igmp_err_qi_le_qri":{"query":1}
,"greater":{"query-response":1}
,"result_ok":{"function":1}
}
;Search.control.loadWordPairs(pairs);
