var pairs =
{
"ldp_api_set_loop_detect_hop_limit":{"call":1,"(struct":1}
,"call":{"sets":1}
,"sets":{"ldp":1}
,"ldp":{"loop-detect":1,"entities":1,"*ldp":1,"ldp":1,"instance":1,"hop-count":1,"loop-detection":1}
,"loop-detect":{"hop":1}
,"hop":{"limit":1}
,"limit":{"ldp":1,"count":1}
,"entities":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ldp_api_set_loop_detect_hop_limit":1}
,"(struct":{"ldp":1}
,"*ldp":{"u_int32_t":1}
,"u_int32_t":{"val":1}
,"val":{"u_char":1,"ldp":1}
,"u_char":{"count)":1}
,"count)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ldp":1,"none":1}
,"instance":{"val":1}
,"hop-count":{"limit":1}
,"count":{"ldp":1,"flag":1}
,"loop-detection":{"count":1}
,"flag":{"allowed":1}
,"allowed":{"values":1}
,"values":{"include":1,"ldp_success":1}
,"include":{"following":1}
,"following":{"ldp_loop_detection_count_set":1}
,"ldp_loop_detection_count_set":{"(1)":1}
,"(1)":{"ldp_loop_detection_count_unset":1}
,"ldp_loop_detection_count_unset":{"(0)":1}
,"(0)":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"ldp_success":{"ldp_error":1}
}
;Search.control.loadWordPairs(pairs);
