var pairs =
{
"show":{"bgp":1}
,"bgp":{"a.b.c.d\u002Fm":1,"route":1,"ipv4":1}
,"a.b.c.d\u002Fm":{"command":1,"show":1,"parameters":1,"prefix":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"bgp":1}
,"route":{"information":1}
,"information":{"network":1}
,"network":{"prefix":1}
,"prefix":{"command":1,"(network\u002Flength)":1}
,"syntax":{"show":1}
,"ipv4":{"(unicast":1,"ipv4":1,"routes":1,"unicast":1}
,"(unicast":{"multicast)":1}
,"multicast)":{"a.b.c.d\u002Fm":1}
,"parameters":{"ipv4":1}
,"routes":{"unicast":1}
,"unicast":{"unicast":1,"prefixes":1,"35.0.0.1\u002F8":1}
,"prefixes":{"multicast":1,"a.b.c.d\u002Fm":1}
,"multicast":{"multicast":1,"prefixes":1}
,"(network\u002Flength)":{"example":1}
,"example":{"35.0.0.0\u002F8":1}
,"35.0.0.0\u002F8":{"command":1}
,"mode":{"privileged":1,"examples":1}
,"privileged":{"exec":1}
,"exec":{"exec":1,"mode":1}
,"examples":{"show":1}
}
;Search.control.loadWordPairs(pairs);
