var pairs =
{
"testing":{"test":1}
,"test":{"feature":1}
,"feature":{"change":1}
,"change":{"address":1}
,"address":{"family":1}
,"family":{"configuration":1}
,"configuration":{"first":1,"conf":1}
,"first":{"router":1}
,"router":{"bgp":1}
,"bgp":{"network":1,"address-family":1}
,"network":{"10.0.0.1":1,"3ffe:506":1}
,"10.0.0.1":{"neighbor":1,"remote-as":1,"capability":1,"activate":1}
,"neighbor":{"10.0.0.1":1}
,"remote-as":{"neighbor":1}
,"capability":{"dynamic":1}
,"dynamic":{"address-family":1}
,"address-family":{"ipv6":1}
,"ipv6":{"unicast":1,"configuration":1,"prefix":1}
,"unicast":{"network":1,"neighbor":1}
,"3ffe:506":{":\u002F32":1}
,":\u002F32":{"neighbor":1}
,"activate":{"exit-address-family":1,"remote":1}
,"exit-address-family":{"remove":1}
,"remove":{"ipv6":1}
,"conf":{"router":1}
,"remote":{"side":1}
,"side":{"receive":1}
,"receive":{"ipv6":1}
,"prefix":{"(3ffe:506":1}
,"(3ffe:506":{":\u002F32)":1}
,":\u002F32)":{"peer":1}
,"peer":{"established":1}
}
;Search.control.loadWordPairs(pairs);
