var pairs =
{
"ldp_api_session_clean_all":{"call":1,"(struct":1}
,"call":{"cleans":1}
,"cleans":{"sessions":1}
,"sessions":{"specific":1,"cleaned":1}
,"specific":{"interface":1}
,"interface":{"syntax":1,"explicit_clean":1}
,"syntax":{"u_char":1}
,"u_char":{"ldp_api_session_clean_all":1,"explicit_clean)":1}
,"(struct":{"ldp_interface":1}
,"ldp_interface":{"*ldpif":1}
,"*ldpif":{"u_char":1}
,"explicit_clean)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ldpif":1,"none":1}
,"ldpif":{"ldp":1}
,"ldp":{"interface":1}
,"explicit_clean":{"flag":1}
,"flag":{"explicit":1}
,"explicit":{"session":1}
,"session":{"cleanup":1}
,"cleanup":{"including":1}
,"including":{"ldp_false":1}
,"ldp_false":{"ldp_true":1,"sessions":1}
,"ldp_true":{"output":1,"sessions":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"ldp_false":1}
,"cleaned":{"ldp_true":1}
}
;Search.control.loadWordPairs(pairs);
