var pairs =
{
"g8032_api_profile_set_timer":{"function":1,"(u_int8_t":1}
,"function":{"sets":1,"implements":1,"succeeds":1}
,"sets":{"timer":1}
,"timer":{"function":1,"command":1,"constants":1,"seconds":1,"microseconds":1}
,"implements":{"timer":1}
,"command":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"g8032_api_profile_set_timer":1}
,"(u_int8_t":{"is_conf":1}
,"is_conf":{"struct":1,"future":1}
,"struct":{"g8032_instance_profile":1}
,"g8032_instance_profile":{"*profile":1}
,"*profile":{"enum":1}
,"enum":{"g8032_timer_type":1,"onmd\u002Fcfm\u002Fg8032v2\u002Fg8032_profile.h":1}
,"g8032_timer_type":{"type":1,"enum":1}
,"type":{"u_int32_t":1,"type":1,"timer":1,"valid":1}
,"u_int32_t":{"timeout_val)":1}
,"timeout_val)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"is_conf":1,"none":1}
,"future":{"profile":1}
,"profile":{"profile":1,"type":1,"null":1}
,"constants":{"g8032_timer_type":1}
,"onmd\u002Fcfm\u002Fg8032v2\u002Fg8032_profile.h":{"g8032_timer_type_wtr":1}
,"g8032_timer_type_wtr":{"wait-to-restore":1}
,"wait-to-restore":{"timer":1}
,"seconds":{"used":1,"g8032_timer_type_guard":1}
,"used":{"verify":1}
,"verify":{"signal":1}
,"signal":{"failure":1}
,"failure":{"intermittent":1}
,"intermittent":{"g8032_timer_type_wtb":1,"link":1}
,"g8032_timer_type_wtb":{"wait-to-block":1}
,"wait-to-block":{"timer":1}
,"g8032_timer_type_guard":{"guard":1}
,"guard":{"timer":1}
,"microseconds":{"blocks":1,"filters":1}
,"blocks":{"latent":1}
,"latent":{"outdated":1}
,"outdated":{"messages":1}
,"messages":{"causing":1}
,"causing":{"unnecessary":1}
,"unnecessary":{"state":1}
,"state":{"changes":1}
,"changes":{"g8032_timer_type_holdoff":1}
,"g8032_timer_type_holdoff":{"hold-off":1}
,"hold-off":{"timer":1}
,"filters":{"intermittent":1}
,"link":{"faults":1}
,"faults":{"timeout_val":1}
,"timeout_val":{"timeout":1}
,"timeout":{"value":1}
,"value":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"g8032_error_none":1}
,"g8032_error_none":{"function":1}
,"succeeds":{"g8032_error_profile_not_found":1}
,"g8032_error_profile_not_found":{"profile":1}
,"null":{"g8032_error_profile_invalid_timer_type":1}
,"g8032_error_profile_invalid_timer_type":{"type":1}
}
;Search.control.loadWordPairs(pairs);
