var pairs =
{
"802":{"family":1,"standards":1}
,"family":{"ieee":1}
,"ieee":{"local":1}
,"local":{"area":1}
,"area":{"network":1}
,"network":{"(lan)":1}
,"(lan)":{"standards":1}
,"standards":{"services":1,"map":1}
,"services":{"protocols":1}
,"protocols":{"specified":1}
,"specified":{"802":1}
,"map":{"layer":1}
,"layer":{"(l1)":1,"(l2)":1}
,"(l1)":{"layer":1,"media":1}
,"(l2)":{"open":1,"802.3":1,"called":1}
,"open":{"systems":1}
,"systems":{"interconnection":1}
,"interconnection":{"(osi)":1}
,"(osi)":{"reference":1}
,"reference":{"model":1}
,"model":{"802.1":1}
,"802.1":{"overview":1}
,"overview":{"architecture":1}
,"architecture":{"lans":1}
,"lans":{"interneworking":1}
,"interneworking":{"802.2":1}
,"802.2":{"logical":1}
,"logical":{"link":1}
,"link":{"control":1}
,"control":{"(llc)":1,"(mac)":1}
,"(llc)":{"sublayer":1}
,"sublayer":{"layer":1}
,"802.3":{"layer":1}
,"media":{"access":1}
,"access":{"control":1}
,"(mac)":{"sublayer":1}
,"called":{"ethernet":1}
}
;Search.control.loadWordPairs(pairs);
