var pairs =
{
"mstp_api_get_l2gp_pseudorootid":{"function":1,"(u_int8_t":1}
,"function":{"gets":1,"succeeds":1}
,"gets":{"pseudo":1}
,"pseudo":{"root":1}
,"root":{"identifier":1}
,"identifier":{"pseudorootid":1,"(of":1}
,"pseudorootid":{"configured":1}
,"configured":{"per":1}
,"per":{"port":1}
,"port":{"basis":1,"interface":1}
,"basis":{"syntax":1}
,"syntax":{"result_t":1}
,"result_t":{"mstp_api_get_l2gp_pseudorootid":1}
,"(u_int8_t":{"*br_name":1}
,"*br_name":{"u_int8_t":1}
,"u_int8_t":{"*if_name":1}
,"*if_name":{"struct":1}
,"struct":{"bridge_id":1}
,"bridge_id":{"*pseudo_rootid)":1,"exist":1}
,"*pseudo_rootid)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"br_name":1,"pseudo_rootid":1}
,"br_name":{"name":1}
,"name":{"bridge":1,"output":1}
,"bridge":{"if_name":1,"bridge_id":1}
,"if_name":{"interface":1}
,"interface":{"name":1,"exist":1}
,"output":{"parameters":1}
,"pseudo_rootid":{"pseudo":1}
,"(of":{"type":1}
,"type":{"bridge_id)":1}
,"bridge_id)":{"return":1}
,"return":{"values":1}
,"values":{"result_ok":1}
,"result_ok":{"function":1}
,"succeeds":{"mstp_err_interface_not_found":1}
,"mstp_err_interface_not_found":{"interface":1}
,"exist":{"mstp_err_bridge_not_found":1,"mstp_err_port_not_found":1,"mstp_error_general":1}
,"mstp_err_bridge_not_found":{"bridge":1}
,"mstp_err_port_not_found":{"msti":1}
,"msti":{"port":1}
,"mstp_error_general":{"bad":1}
,"bad":{"passed":1}
}
;Search.control.loadWordPairs(pairs);
