var pairs =
{
"nsm_dcb_pfc_set_advertise_interface":{"function":1,"(struct":1}
,"function":{"enables":1,"succeeds":1}
,"enables":{"advertise":1}
,"advertise":{"setting":1,"whether":1,"enabled":1}
,"setting":{"pfc":1}
,"pfc":{"interface":1,"enabled":1}
,"interface":{"syntax":1,"*ifp":1,"pointer":1,"found":1,"nsm_dcb_api_set_err_interface_no_ets":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"nsm_dcb_pfc_set_advertise_interface":1}
,"(struct":{"interface":1}
,"*ifp":{"bool_t":1}
,"bool_t":{"advertise)":1}
,"advertise)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"none":1}
,"ifp":{"interface":1}
,"pointer":{"advertise":1}
,"whether":{"advertise":1}
,"enabled":{"disabled":1,"nsm_dcb_api_set_err_no_pfc":1,"nsm_dcb_api_set_err_dcb_interface":1,"interface":1}
,"disabled":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_dcb_api_set_success":1}
,"nsm_dcb_api_set_success":{"function":1}
,"succeeds":{"nsm_bridge_err_notfound":1}
,"nsm_bridge_err_notfound":{"bridge":1}
,"bridge":{"found":1}
,"found":{"nsm_dcb_api_set_err_no_dcbg":1,"dcb":1,"nsm_dcb_api_set_err_interface_no_pfc":1}
,"nsm_dcb_api_set_err_no_dcbg":{"dcb":1}
,"dcb":{"bridge":1,"enabled":1,"interface":1}
,"nsm_dcb_api_set_err_no_pfc":{"pfc":1}
,"nsm_dcb_api_set_err_dcb_interface":{"dcb":1}
,"nsm_dcb_api_set_err_interface_no_pfc":{"pfc":1}
,"nsm_dcb_api_set_err_interface_no_ets":{"ets":1}
,"ets":{"enabled":1}
}
;Search.control.loadWordPairs(pairs);
