var pairs =
{
"lldp_set_port_msg_tx_hold":{"function":1,"(struct":1}
,"function":{"sets":1,"succeeds":1}
,"sets":{"message":1}
,"message":{"transmit":1}
,"transmit":{"hold":1}
,"hold":{"parameter":1,"time":1}
,"parameter":{"determines":1}
,"determines":{"ttl":1}
,"ttl":{"value":1}
,"value":{"lldpus":1,"message":1}
,"lldpus":{"transmitted":1}
,"transmitted":{"port":1}
,"port":{"syntax":1}
,"syntax":{"include":1}
,"include":{"lldp_api.h":1}
,"lldp_api.h":{"s_int32_t":1}
,"s_int32_t":{"lldp_set_port_msg_tx_hold":1}
,"(struct":{"interface":1}
,"interface":{"*ifp":1,"structure":1,"found":1}
,"*ifp":{"u_int32_t":1}
,"u_int32_t":{"value)":1}
,"value)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"none":1}
,"ifp":{"interface":1}
,"structure":{"value":1}
,"time":{"<2-10>":1}
,"<2-10>":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"lldp_api_success":1}
,"lldp_api_success":{"function":1}
,"succeeds":{"lldp_api_err_onm_if_not_exist":1}
,"lldp_api_err_onm_if_not_exist":{"omnd":1}
,"omnd":{"interface":1}
,"found":{"lldp_api_err_lldp_if_not_exist":1}
,"lldp_api_err_lldp_if_not_exist":{"lldp":1}
,"lldp":{"interface":1}
}
;Search.control.loadWordPairs(pairs);
