var pairs =
{
"ldp_snmp_api_set_target_peer_recv":{"call":1,"(struct":1}
,"call":{"sets":1}
,"sets":{"targeted":1}
,"targeted":{"hello":1}
,"hello":{"receive":1}
,"receive":{"flag":1}
,"flag":{"ldp":1,"including":1,"ldp_false":1,"output":1}
,"ldp":{"entity":1}
,"entity":{"syntax":1,"ldp":1,"enable":1}
,"syntax":{"int":1}
,"int":{"ldp_snmp_api_set_target_peer_recv":1}
,"(struct":{"ldp_entity":1}
,"ldp_entity":{"*entity":1}
,"*entity":{"s_int32_t":1}
,"s_int32_t":{"enable)":1}
,"enable)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"entity":1,"none":1}
,"enable":{"targeted":1}
,"including":{"ldp_true":1}
,"ldp_true":{"sets":1}
,"ldp_false":{"unsets":1}
,"unsets":{"targeted":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"ldp_success":1}
,"ldp_success":{"ldp_error":1}
}
;Search.control.loadWordPairs(pairs);
