var pairs =
{
"cfm_pbb_te_throughput_send_frame":{"function":1,"(struct":1}
,"function":{"sends":1,"fails":1,"succeeds":1}
,"sends":{"burst":1}
,"burst":{"frames":1}
,"frames":{"increasing":1}
,"increasing":{"sizes":1}
,"sizes":{"local":1}
,"local":{"remote":1}
,"remote":{"mep":1}
,"mep":{"pbb-te":1,"<1-8191>":1}
,"pbb-te":{"bridge":1}
,"bridge":{"syntax":1,"identity":1,"mepid":1}
,"syntax":{"s_int8_t":1}
,"s_int8_t":{"cfm_pbb_te_throughput_send_frame":1}
,"(struct":{"onmd_bridge":1}
,"onmd_bridge":{"*bridge":1}
,"*bridge":{"u_int32_t":1}
,"u_int32_t":{"mepid":1,"rmepid":1,"te_sid)":1}
,"mepid":{"u_int32_t":1,"source":1}
,"rmepid":{"u_int8_t":1,"remote":1}
,"u_int8_t":{"*md_name":1}
,"*md_name":{"u_int32_t":1}
,"te_sid)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bridge":1}
,"identity":{"bridge":1}
,"source":{"mep":1}
,"<1-8191>":{"rmepid":1,"md_name":1}
,"md_name":{"maintenance":1}
,"maintenance":{"domain":1}
,"domain":{"name":1}
,"name":{"te_sid":1}
,"te_sid":{"service":1}
,"service":{"instance":1}
,"instance":{"<1-42949675>":1}
,"<1-42949675>":{"return":1}
,"return":{"values":1}
,"values":{"cfm_failure":1}
,"cfm_failure":{"function":1}
,"fails":{"cfm_success":1}
,"cfm_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
