var pairs =
{
"contents":{"guide":1}
,"guide":{"contains":1}
,"contains":{"chapters":1}
,"chapters":{"appendices":1}
,"appendices":{"chapter":1}
,"chapter":{"multi-protocol":1,"virtual":1,"bgp":1,"mpls":1,"layer":1,"mpls-tp":1,"diffserv-te":1,"structure":1,"data":1,"static":1,"differentiated":1}
,"multi-protocol":{"label":1}
,"label":{"switching":1}
,"switching":{"overview":1,"chapter":1,"api":1}
,"overview":{"chapter":1}
,"virtual":{"private":1,"circuit":1}
,"private":{"lan":1,"network":1}
,"lan":{"service":1,"services":1}
,"service":{"chapter":1}
,"bgp":{"virtual":1}
,"services":{"chapter":1,"api":1}
,"mpls":{"transport":1,"non-stop":1,"mib":1,"command":1,"pseudowire":1,"messages":1}
,"transport":{"profile":1}
,"profile":{"chapter":1}
,"layer":{"virtual":1}
,"network":{"chapter":1}
,"mpls-tp":{"oam":1,"linear":1,"ring":1,"command":1}
,"oam":{"modules":1,"y-1731":1,"command":1}
,"modules":{"chapter":1}
,"y-1731":{"support":1}
,"support":{"chapter":1}
,"linear":{"protection":1}
,"protection":{"switching":1}
,"ring":{"protection":1}
,"non-stop":{"forwarding":1}
,"forwarding":{"chapter":1,"api":1}
,"circuit":{"chapter":1,"interface":1}
,"diffserv-te":{"chapter":1}
,"structure":{"agnostic":1}
,"agnostic":{"tdm":1}
,"tdm":{"packet":1}
,"packet":{"chapter":1}
,"data":{"structures":1}
,"structures":{"chapter":1}
,"mib":{"api":1}
,"api":{"chapter":1,"appendix":1}
,"command":{"api":1}
,"pseudowire":{"mib":1}
,"static":{"vpls":1}
,"vpls":{"api":1}
,"interface":{"api":1}
,"differentiated":{"services":1}
,"appendix":{"mpls":1,"glossary":1}
,"messages":{"appendix":1}
}
;Search.control.loadWordPairs(pairs);
