var pairs =
{
"debug":{"ipv6":1}
,"ipv6":{"pim":1}
,"pim":{"timer":1,"register":1,"(vrf":1}
,"timer":{"register":1,"option":1,"command":1,"(rst)":1}
,"register":{"command":1,"timer":1,"debug":1,"rst":1,"stop":1}
,"command":{"enable":1,"disable":1,"syntax":1,"mode":1}
,"enable":{"debugging":1}
,"debugging":{"pim":1}
,"option":{"command":1}
,"disable":{"debugging":1}
,"syntax":{"debug":1}
,"rst":{"debug":1,"parameters":1,"turn":1}
,"(vrf":{"name":1}
,"name":{"timer":1,"specify":1,"vpn":1}
,"parameters":{"vrf":1}
,"vrf":{"vpn":1}
,"vpn":{"routing\u002Fforwarding":1}
,"routing\u002Fforwarding":{"instance":1}
,"instance":{"name":1,"rst":1}
,"specify":{"name":1}
,"turn":{"turn":1,"pim":1}
,"stop":{"timer":1}
,"(rst)":{"command":1}
,"mode":{"exec":1,"privilege":1,"configure":1,"example":1}
,"exec":{"mode":1}
,"privilege":{"exec":1}
,"configure":{"mode":1}
,"example":{"debug":1}
}
;Search.control.loadWordPairs(pairs);
