var pairs =
{
"show":{"gmrp":1}
,"gmrp":{"machine":1,"default":1,"state":1}
,"machine":{"command":1,"gmrp":1,"bridge":1}
,"command":{"display":1,"syntax":1,"mode":1,"displaying":1}
,"display":{"state":1}
,"state":{"machine":1,"[0]":1,"[1]":1}
,"default":{"bridge":1}
,"bridge":{"command":1,"bridge_name":1,"identifier":1,"show":1,"port":1}
,"syntax":{"show":1}
,"bridge_name":{"parameter":1,"bridge":1}
,"parameter":{"bridge_name":1}
,"identifier":{"command":1}
,"mode":{"exec":1,"examples":1}
,"exec":{"privileged":1,"mode":1}
,"privileged":{"exec":1}
,"examples":{"following":1}
,"following":{"output":1}
,"output":{"command":1}
,"displaying":{"gmrp":1}
,"port":{"=eth0":1,"=eth1":1}
,"=eth0":{"vlan":1}
,"vlan":{"applicant":1}
,"applicant":{"state":1}
,"[0]":{"=vo":1,"=mt":1}
,"=vo":{"registrar":1}
,"registrar":{"state":1}
,"=mt":{"applicant":1,"port":1}
,"[1]":{"=vo":1,"=mt":1}
,"=eth1":{"vlan":1}
}
;Search.control.loadWordPairs(pairs);
