var pairs =
{
"following":{"configure":1}
,"configure":{"customer":1,"terminal":1,"mode":1,"bridge":1,"eth1":1,"port":1,"crosscheck":1,"interface":1}
,"customer":{"edge":1}
,"edge":{"(ce)":1}
,"(ce)":{"configure":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"interface":1,"cfm":1}
,"mode":{"(config)":1,"(config-if)":1,"trunk":1,"create":1,"configure":1}
,"(config)":{"bridge":1,"interface":1,"ethernet":1,"exit":1}
,"bridge":{"protocol":1,"rstp-vlan":1,"interface":1,"enter":1,"(config-ether-cfm)":1}
,"protocol":{"rstp":1}
,"rstp":{"vlan-bridge":1}
,"vlan-bridge":{"configure":1}
,"rstp-vlan":{"aware":1}
,"aware":{"(config)":1}
,"interface":{"eth1":1,"mode":1,"(config-if)":1,"maintenance":1,"(config-if-eth-cfm-mep)":1}
,"eth1":{"enter":1,"layer":1,"interface":1}
,"(config-if)":{"switchport":1,"bridge-group":1,"exit":1,"ethernet":1}
,"switchport":{"configure":1,"mode":1,"trunk":1}
,"layer":{"port":1}
,"port":{"(config-if)":1,"trunk":1}
,"bridge-group":{"associate":1}
,"associate":{"bridge":1}
,"trunk":{"configure":1,"(config-if)":1,"allowed":1}
,"allowed":{"vlan":1}
,"vlan":{"allow":1}
,"allow":{"vlans":1}
,"vlans":{"eth1":1}
,"exit":{"exit":1,"eth1":1,"domain":1,"cfm":1,"interface":1}
,"ethernet":{"cfm":1}
,"cfm":{"domain-name":1,"mode":1,"mep":1}
,"domain-name":{"type":1}
,"type":{"character-string":1}
,"character-string":{"name":1}
,"name":{"test":1}
,"test":{"level":1}
,"level":{"mip-creation":1,"bridge":1}
,"mip-creation":{"default":1}
,"default":{"bridge":1}
,"create":{"domain":1,"service":1}
,"domain":{"level":1,"configuration":1,"abc":1}
,"(config-ether-cfm)":{"service":1,"mep":1,"exit":1}
,"service":{"ma-type":1,"(config-ether-cfm)":1}
,"ma-type":{"integer":1}
,"integer":{"ma-name":1}
,"ma-name":{"create":1}
,"mep":{"crosscheck":1,"remote":1,"(config-ether-cfm)":1,"down":1,"mode":1}
,"crosscheck":{"mpid":1,"host":1}
,"mpid":{"configure":1,"active":1}
,"host":{"mep":1}
,"remote":{"mep":1}
,"configuration":{"mode":1}
,"down":{"mpid":1}
,"active":{"true":1}
,"true":{"domain":1}
,"abc":{"uni-mep":1}
,"uni-mep":{"bridge":1}
,"maintenance":{"end":1}
,"end":{"point":1}
,"point":{"(mep)":1}
,"(mep)":{"(config-if-eth-cfm-mep)":1}
,"(config-if-eth-cfm-mep)":{"multicast":1,"exit":1}
,"multicast":{"state":1,"continuity":1}
,"state":{"enable":1}
,"enable":{"enable":1,"multicast":1}
,"continuity":{"checking":1}
,"checking":{"(cc)":1}
,"(cc)":{"interface":1}
}
;Search.control.loadWordPairs(pairs);
