var pairs =
{
"nsm_master":{"data":1}
,"data":{"structure":1,"t_kernel_msg_stagger":1}
,"structure":{"contains":1,"defined":1,"resource_counter":1,"vrrp":1,"keeps":1}
,"contains":{"nsm":1}
,"nsm":{"system-wide":1,"pointer":1,"master":1,"start":1,"mpls":1,"arp":1,"configured":1}
,"system-wide":{"settings":1}
,"settings":{"data":1}
,"defined":{"nsm\u002Fnsmd.h":1}
,"nsm\u002Fnsmd.h":{"file":1}
,"file":{"member":1}
,"member":{"description":1}
,"description":{"pointer":1,"module_bits":1}
,"pointer":{"virtual":1,"library":1}
,"virtual":{"router":1}
,"router":{"nsm":1,"support":1,"advertisement":1,"nsm_qos_acl_master":1}
,"library":{"globals":1}
,"globals":{"desc":1}
,"desc":{"description":1}
,"module_bits":{"control":1}
,"control":{"virtual":1}
,"support":{"per":1}
,"per":{"start_time":1,"virtual":1}
,"start_time":{"nsm":1}
,"master":{"start":1,"l2_oam_master":1,"nsm_layer2_master":1,"class_rule_type":1,"arp":1,"ipsec_master":1,"firewall_master":1,"nsm_master_cdr_ref":1,"checkpoint":1,"rib":1}
,"start":{"time":1,"t_sweep":1}
,"time":{"multipath_num":1,"retaining":1,"qos_state":1}
,"multipath_num":{"maximum":1}
,"maximum":{"path":1,"ecmp":1,"static":1,"fib":1,"frame":1}
,"path":{"configuration":1,"limit":1}
,"configuration":{"mp_size":1}
,"mp_size":{"maximum":1}
,"ecmp":{"path":1}
,"limit":{"max_static_routes":1}
,"max_static_routes":{"maximum":1}
,"static":{"routes":1,"max_frame_size":1}
,"routes":{"max_fib_routes":1,"excluding":1,"nsm":1,"t_rib_kernel_sync":1}
,"max_fib_routes":{"maximum":1}
,"fib":{"routes":1}
,"excluding":{"kernel":1}
,"kernel":{"connect":1,"sync":1,"kernel_msg_stagger_list":1,"bridge":1}
,"connect":{"static":1}
,"max_frame_size":{"maximum":1}
,"frame":{"size":1}
,"size":{"permissible":1}
,"permissible":{"fib_retain_time":1}
,"fib_retain_time":{"time":1}
,"retaining":{"stale":1}
,"stale":{"fib":1}
,"t_sweep":{"sweep":1}
,"sweep":{"stale":1,"timer":1}
,"t_rib_kernel_sync":{"rib":1}
,"rib":{"kernel":1,"sweep":1}
,"sync":{"label_pool_table":1}
,"label_pool_table":{"table":1,"label":1}
,"table":{"label":1,"nmpls":1}
,"label":{"pool":1}
,"pool":{"managers":1,"table":1}
,"managers":{"label_pool_table":1}
,"nmpls":{"nsm":1}
,"mpls":{"top":1}
,"top":{"structure":1}
,"resource_counter":{"qos":1}
,"qos":{"resource":1,"state":1}
,"resource":{"counter":1}
,"counter":{"admin_group_array":1}
,"admin_group_array":{"admin":1}
,"admin":{"group":1}
,"group":{"array":1}
,"array":{"rtadv":1}
,"rtadv":{"router":1}
,"advertisement":{"structure":1}
,"vrrp":{"vrrp":1,"global":1}
,"global":{"data":1,"if_params":1}
,"t_kernel_msg_stagger":{"hold":1}
,"hold":{"timer":1}
,"timer":{"stagger":1,"checkpoint":1}
,"stagger":{"writes":1}
,"writes":{"kernel":1}
,"kernel_msg_stagger_list":{"list":1}
,"list":{"storing":1,"lacp_admin_key_mgr":1,"last_change_time":1,"acl":1,"cmap":1,"mac_acl":1,"master":1,"access-list":1,"route":1,"apbf_invalid_nh6":1,"nsm_apbf_nh4_tbr":1,"nsm_apbf_nh4_res":1,"nsm_apbf_nh4_nr":1,"nsm_apbf_nh6_tbr":1,"nsm_apbf_nh6_res":1,"nsm_apbf_nh6_nr":1}
,"storing":{"messages":1}
,"messages":{"need":1}
,"need":{"sent":1}
,"sent":{"kernel":1}
,"bridge":{"new":1,"master":1}
,"new":{"bridge":1}
,"l2_oam_master":{"oam":1}
,"oam":{"master":1}
,"nsm_layer2_master":{"layer":1}
,"layer":{"related":1,"(cal)":1}
,"related":{"information":1}
,"information":{"vmap":1}
,"vmap":{"vlan":1}
,"vlan":{"access":1,"classifier":1}
,"access":{"master":1,"list":1}
,"class_rule_type":{"vlan":1}
,"classifier":{"type":1}
,"type":{"global":1}
,"if_params":{"interface":1}
,"interface":{"parameter":1,"structure":1}
,"parameter":{"list":1}
,"lacp_admin_key_mgr":{"lacp":1}
,"lacp":{"administrator":1}
,"administrator":{"key":1}
,"key":{"manager":1,"element":1}
,"manager":{"ake_list":1}
,"ake_list":{"lacp":1}
,"element":{"psc":1}
,"psc":{"port":1}
,"port":{"selection":1}
,"selection":{"criteria":1}
,"criteria":{"phyentitylist":1}
,"phyentitylist":{"physical":1}
,"physical":{"entity":1}
,"entity":{"list":1}
,"last_change_time":{"disconnect":1}
,"disconnect":{"time":1}
,"qos_state":{"qos":1}
,"state":{"per":1}
,"nsm_qos_acl_master":{"mac":1}
,"mac":{"acl":1,"access":1}
,"acl":{"list":1,"mac":1,"names":1}
,"cmap":{"cmap":1,"list":1,"pmap":1}
,"pmap":{"list":1}
,"mac_acl":{"mac":1}
,"arp":{"nsm":1,"master":1}
,"ipsec_master":{"ipsec":1}
,"ipsec":{"nsm":1}
,"firewall_master":{"firewall":1}
,"firewall":{"master":1}
,"nsm_master_cdr_ref":{"nsm":1}
,"checkpoint":{"abstraction":1}
,"abstraction":{"layer":1}
,"(cal)":{"created":1}
,"created":{"record":1}
,"record":{"reference":1}
,"reference":{"nsm_master_rib_sweep_tmr_cdr_ref":1,"access_group_if":1}
,"nsm_master_rib_sweep_tmr_cdr_ref":{"nsm":1}
,"access_group_if":{"list":1}
,"access-list":{"interface":1}
,"keeps":{"track":1}
,"track":{"acl":1,"route":1}
,"names":{"configured":1}
,"configured":{"interfaces":1,"terminal":1}
,"interfaces":{"nmd_conf":1,"apbf_invalid_nh":1}
,"nmd_conf":{"nsm":1}
,"terminal":{"debug":1}
,"debug":{"flags":1}
,"flags":{"nmd_term":1,"route_map_if":1}
,"nmd_term":{"nsm":1}
,"route_map_if":{"list":1}
,"route":{"map":1,"maps":1}
,"map":{"interface":1}
,"maps":{"configured":1}
,"apbf_invalid_nh":{"ipv4":1}
,"ipv4":{"invalid":1}
,"invalid":{"nexthop":1}
,"nexthop":{"list":1}
,"apbf_invalid_nh6":{"ipv6":1}
,"ipv6":{"invalid":1}
,"nsm_apbf_nh4_tbr":{"resolved":1}
,"resolved":{"list":1}
,"nsm_apbf_nh4_res":{"resolved":1}
,"nsm_apbf_nh4_nr":{"resolved":1}
,"nsm_apbf_nh6_tbr":{"resolved":1}
,"nsm_apbf_nh6_res":{"resolved":1}
,"nsm_apbf_nh6_nr":{"resolved":1}
}
;Search.control.loadWordPairs(pairs);
