var pairs =
{
"virtual":{"ethernet":1,"machines":1,"nics":1,"machine":1,"switches":1,"nic":1}
,"ethernet":{"bridges":1,"bridge":1,"switch":1}
,"bridges":{"virtual":1}
,"bridge":{"(veb)":1}
,"(veb)":{"virtual":1}
,"switch":{"implemented":1,"connecting":1,"administrators":1}
,"implemented":{"virtualized":1}
,"virtualized":{"server":1}
,"server":{"environment":1,"connect":1,"hypervisor":1,"different":1,"vswitch":1,"lack":1}
,"environment":{"veb":1}
,"veb":{"mimics":1}
,"mimics":{"traditional":1}
,"traditional":{"external":1}
,"external":{"layer":1,"network":1,"physical":1,"switch":1,"connectivity":1,"switches":1}
,"layer":{"(l2)":1}
,"(l2)":{"switch":1}
,"connecting":{"vms":1}
,"vms":{"(virtual":1,"single":1,"external":1,"transmits":1,"vswitch":1,"physical":1,"data":1}
,"(virtual":{"machines)":1}
,"machines)":{"vebs":1}
,"vebs":{"communicate":1,"software-based":1}
,"communicate":{"vms":1}
,"single":{"physical":1}
,"physical":{"server":1,"nics":1,"nic":1}
,"connect":{"vms":1,"virtual":1}
,"network":{"shown":1,"hypervisor":1,"external":1,"management":1,"policy":1}
,"shown":{"figure":1}
,"figure":{"1-1":1}
,"1-1":{"common":1}
,"common":{"implementations":1}
,"implementations":{"vebs":1}
,"software-based":{"vswitches":1,"virtual":1}
,"vswitches":{"built":1,"several":1,"limited":1,"often":1,"expands":1,"individually":1}
,"built":{"hypervisors":1}
,"hypervisors":{"vswitch":1}
,"vswitch":{"virtualized":1,"physical":1,"vswitch":1,"uses":1,"forwards":1,"advantages":1,"forward":1,"reducing":1}
,"hypervisor":{"abstracts":1,"implements":1}
,"abstracts":{"shares":1}
,"shares":{"physical":1}
,"nics":{"(network":1,"virtual":1,"physical":1,"data":1}
,"(network":{"interface":1}
,"interface":{"cards)":1}
,"cards)":{"among":1}
,"among":{"multiple":1}
,"multiple":{"virtual":1}
,"machines":{"creating":1}
,"creating":{"virtual":1}
,"machine":{"vswitch":1}
,"nic":{"acts":1,"passes":1,"vswitch":1,"destination":1}
,"acts":{"uplink":1}
,"uplink":{"external":1}
,"implements":{"software-based":1}
,"switches":{"connect":1,"advanced":1}
,"data":{"traffic":1,"monitoring":1,"center":1}
,"traffic":{"received":1,"correct":1,"virtual":1,"two":1,"physical":1,"directly":1,"load":1,"vswitch":1,"visibility":1}
,"received":{"physical":1}
,"passes":{"vswitch":1}
,"uses":{"hypervisor-based":1}
,"hypervisor-based":{"configuration":1}
,"configuration":{"information":1}
,"information":{"forward":1}
,"forward":{"traffic":1,"internal":1}
,"correct":{"vms":1}
,"transmits":{"traffic":1}
,"forwards":{"traffic":1}
,"two":{"ways":1}
,"ways":{"destination":1}
,"destination":{"external":1,"internal":1}
,"different":{"vswitch":1}
,"internal":{"physical":1,"vm-to-vm":1,"network":1}
,"directly":{"back":1,"deployment":1}
,"back":{"using":1}
,"using":{"vswitch":1}
,"advantages":{"good":1}
,"good":{"performance":1}
,"performance":{"vms":1}
,"vm-to-vm":{"traffic":1}
,"deployment":{"without":1}
,"without":{"external":1}
,"administrators":{"provide":1}
,"provide":{"internal":1,"local":1}
,"connectivity":{"vswitches":1}
,"several":{"disadvantages":1}
,"disadvantages":{"consume":1}
,"consume":{"cpu":1}
,"cpu":{"memory":1}
,"memory":{"bandwidth":1,"cycles":1}
,"bandwidth":{"higher":1}
,"higher":{"traffic":1}
,"load":{"greater":1}
,"greater":{"number":1}
,"number":{"cpu":1,"vms":1,"vswitches":1}
,"cycles":{"required":1}
,"required":{"move":1}
,"move":{"traffic":1}
,"reducing":{"ability":1}
,"ability":{"support":1}
,"support":{"larger":1,"features":1}
,"larger":{"numbers":1}
,"numbers":{"vms":1}
,"lack":{"network-based":1,"network":1,"management":1}
,"network-based":{"visibility":1}
,"visibility":{"vswitches":1,"capabilities":1}
,"limited":{"feature":1,"support":1}
,"feature":{"provide":1}
,"local":{"traffic":1}
,"capabilities":{"enterprise":1}
,"enterprise":{"data":1}
,"monitoring":{"security":1}
,"security":{"network":1,"quality":1}
,"management":{"lack":1,"scalability":1}
,"policy":{"enforcement":1}
,"enforcement":{"modern":1}
,"modern":{"external":1}
,"advanced":{"features":1}
,"features":{"port":1,"lack":1}
,"port":{"security":1}
,"quality":{"service":1}
,"service":{"(qos)":1}
,"(qos)":{"access":1}
,"access":{"control":1}
,"control":{"lists":1}
,"lists":{"(acl)":1}
,"(acl)":{"vswitches":1}
,"often":{"limited":1}
,"scalability":{"increase":1}
,"increase":{"number":1}
,"center":{"number":1}
,"expands":{"manage":1}
,"manage":{"standard":1}
,"standard":{"vswitches":1}
}
;Search.control.loadWordPairs(pairs);
