var pairs =
{
"multiple":{"spanning-tree":1,"spanning":1}
,"spanning-tree":{"instance":1,"(mst)":1,"instances":1,"topology":1}
,"instance":{"(msti)":1,"managed":1,"spanning-tree":1,"time":1}
,"(msti)":{"group":1}
,"group":{"vlans":1}
,"vlans":{"spanning-tree":1}
,"managed":{"multiple":1}
,"spanning":{"tree":1}
,"tree":{"protocol":1,"(ist)":1}
,"protocol":{"(mstp)":1}
,"(mstp)":{"within":1}
,"within":{"multiple":1,"mst":1}
,"(mst)":{"region":1}
,"region":{"within":1,"mstp":1}
,"mst":{"region":1}
,"mstp":{"maintains":1}
,"maintains":{"multiple":1}
,"instances":{"instance":1,"msti":1}
,"topology":{"independent":1,"frames":1}
,"independent":{"spanning-tree":1}
,"msti":{"provides":1}
,"provides":{"fully":1}
,"fully":{"connected":1}
,"connected":{"active":1}
,"active":{"topology":1}
,"frames":{"belonging":1}
,"belonging":{"vlan":1}
,"vlan":{"assign":1,"spanning-tree":1}
,"assign":{"vlan":1}
,"time":{"internal":1}
,"internal":{"spanning":1}
,"(ist)":{"special":1}
,"special":{"type":1}
,"type":{"mtsi":1}
}
;Search.control.loadWordPairs(pairs);
