var pairs =
{
"nsm_dcb_create_cp":{"function":1,"(u_int32_t":1}
,"function":{"creates":1,"succeeds":1}
,"creates":{"congestion":1}
,"congestion":{"point":1,"notification":1}
,"point":{"(cp)":1}
,"(cp)":{"congestion":1}
,"notification":{"priority":1,"messages":1}
,"priority":{"value":1}
,"value":{"(cnpv)":1,"used":1}
,"(cnpv)":{"interface":1}
,"interface":{"syntax":1,"name":1,"found":1,"nsm_dcb_api_set_err_no_cnpv_conf":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"nsm_dcb_create_cp":1,"weight":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1}
,"char":{"*ifname":1}
,"*ifname":{"u_int8_t":1}
,"u_int8_t":{"cnpv":1,"flag)":1}
,"cnpv":{"u_int32_t":1,"cnpv":1,"bit":1,"sample_base":1,"interface":1,"configured":1}
,"u_int32_t":{"sample_base":1,"min_hdr_octet":1}
,"sample_base":{"s_int32_t":1,"minimum":1,"weight":1}
,"weight":{"u_int32_t":1,"weight":1,"change":1,"min_hdr_octet":1}
,"min_hdr_octet":{"u_int8_t":1,"minimum":1,"parameters":1}
,"flag)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"setting":1,"none":1}
,"virtual":{"router":1}
,"router":{"ifname":1}
,"ifname":{"interface":1}
,"name":{"cnpv":1}
,"bit":{"values":1,"sample_base":1}
,"values":{"bits":1,"supplying":1}
,"bits":{"applied":1,"parameter":1}
,"applied":{"cnpvs":1}
,"cnpvs":{"default":1}
,"default":{"value":1,"150,000":1,"(1)":1,"zero":1}
,"used":{"bit":1,"calculate":1}
,"minimum":{"number":1}
,"number":{"octets":1}
,"octets":{"enqueue":1,"cp\u2019s":1,"returns":1}
,"enqueue":{"cp\u0027s":1}
,"cp\u0027s":{"queue":1}
,"queue":{"transmissions":1,"length":1,"<-10":1}
,"transmissions":{"congestion":1}
,"messages":{"(cnms)":1}
,"(cnms)":{"<10000-4294967295>":1}
,"<10000-4294967295>":{"default":1}
,"150,000":{"weight":1}
,"change":{"queue":1}
,"length":{"used":1,"moving":1}
,"calculate":{"whether":1}
,"whether":{"queue":1}
,"moving":{"toward":1}
,"toward":{"away":1}
,"away":{"target":1}
,"target":{"number":1}
,"cp\u2019s":{"queue":1}
,"<-10":{"-10>":1}
,"-10>":{"default":1}
,"(1)":{"min_hdr_octet":1}
,"returns":{"msdu":1}
,"msdu":{"(mac":1}
,"(mac":{"service":1}
,"service":{"data":1}
,"data":{"unit)":1}
,"unit)":{"field":1}
,"field":{"cnm":1}
,"cnm":{"generates":1}
,"generates":{"<0-64>":1}
,"<0-64>":{"default":1}
,"zero":{"(0)":1}
,"(0)":{"flag":1}
,"flag":{"specify":1}
,"specify":{"values":1}
,"supplying":{"cnpv":1}
,"setting":{"bits":1}
,"parameter":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"nsm_dcb_api_set_success":1}
,"nsm_dcb_api_set_success":{"function":1}
,"succeeds":{"nsm_dcb_api_set_err_no_nm":1}
,"nsm_dcb_api_set_err_no_nm":{"nsm":1}
,"nsm":{"master":1}
,"master":{"found":1}
,"found":{"nsm_dcb_api_set_err_interface":1,"nsm_bridge_err_notfound":1,"nsm_dcb_api_set_err_no_dcbg":1,"dcb":1,"nsm_dcb_api_set_err_no_mem":1}
,"nsm_dcb_api_set_err_interface":{"interface":1}
,"nsm_bridge_err_notfound":{"bridge":1}
,"bridge":{"found":1}
,"nsm_dcb_api_set_err_no_dcbg":{"dcb":1}
,"dcb":{"bridge":1,"enabled":1,"interface":1}
,"enabled":{"nsm_dcb_api_set_err_no_qcn":1,"nsm_dcb_api_set_err_dcb_interface":1,"hardware":1}
,"nsm_dcb_api_set_err_no_qcn":{"qcn":1}
,"qcn":{"enabled":1}
,"nsm_dcb_api_set_err_dcb_interface":{"dcb":1}
,"nsm_dcb_api_set_err_no_mem":{"error":1}
,"error":{"allocating":1}
,"allocating":{"memory":1}
,"memory":{"nsm_dcb_api_set_err_hw":1}
,"nsm_dcb_api_set_err_hw":{"cannot":1}
,"cannot":{"enabled":1}
,"hardware":{"nsm_dcb_api_set_err_no_cnpv":1}
,"nsm_dcb_api_set_err_no_cnpv":{"configured":1}
,"configured":{"given":1}
,"given":{"cnpv":1}
,"nsm_dcb_api_set_err_no_cnpv_conf":{"given":1}
}
;Search.control.loadWordPairs(pairs);
