var pairs =
{
"ldp_snmp_api_get_adjacency_node":{"call":1,"(struct":1}
,"call":{"gets":1}
,"gets":{"adjacency":1}
,"adjacency":{"node":1}
,"node":{"syntax":1,"adj_node":1,"return":1}
,"syntax":{"static":1}
,"static":{"int":1}
,"int":{"ldp_snmp_api_get_adjacency_node":1}
,"(struct":{"ldp":1}
,"ldp":{"*ldp":1,"ldp":1,"instance":1,"peer":1,"index":1}
,"*ldp":{"struct":1}
,"struct":{"ldp_id":1,"listnode":1}
,"ldp_id":{"*peer_id":1}
,"*peer_id":{"u_int32_t":1}
,"u_int32_t":{"indx":1}
,"indx":{"struct":1,"ldp":1}
,"listnode":{"**ses_node":1,"**adj_node)":1}
,"**ses_node":{"struct":1}
,"**adj_node)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ldp":1,"ses_node":1}
,"instance":{"peer_id":1}
,"peer_id":{"ldp":1}
,"peer":{"indx":1}
,"index":{"output":1}
,"output":{"parameters":1}
,"ses_node":{"session":1}
,"session":{"node":1}
,"adj_node":{"adjacency":1}
,"return":{"values":1}
,"values":{"ldp_success":1}
,"ldp_success":{"ldp_false":1}
}
;Search.control.loadWordPairs(pairs);
