var pairs =
{
"mpls-tp":{"loss-measurement":1}
,"loss-measurement":{"command":1,"(meg-name":1,"meg-name":1}
,"command":{"start":1,"syntax":1,"mode":1}
,"start":{"ietf":1}
,"ietf":{"loss":1}
,"loss":{"measurement":1}
,"measurement":{"command":1,"packets":1}
,"syntax":{"mpls-tp":1}
,"(meg-name":{"name":1}
,"name":{"me-name":1,"meg":1,"1-48":1,"name":1}
,"me-name":{"name)":1,"maintenance":1,"interval":1}
,"name)":{"({duration":1}
,"({duration":{"<5-60>":1}
,"<5-60>":{"interval":1,"duration":1}
,"interval":{"<1-5>}":1,"loss":1}
,"<1-5>}":{"parameters":1}
,"parameters":{"meg-name":1}
,"meg-name":{"maintenance":1,"meg2":1}
,"maintenance":{"entity":1}
,"entity":{"group":1,"(me)":1}
,"group":{"(meg)":1}
,"(meg)":{"name":1}
,"meg":{"name":1}
,"1-48":{"characters":1}
,"characters":{"me-name":1,"<5-60>":1}
,"(me)":{"name":1}
,"duration":{"session":1}
,"session":{"seconds":1}
,"seconds":{"<1-5>":1,"seconds":1,"command":1}
,"<1-5>":{"interval":1}
,"packets":{"millisecond":1}
,"millisecond":{"100":1}
,"100":{"milliseconds":1}
,"milliseconds":{"second":1}
,"second":{"seconds":1}
,"mode":{"exec":1,"examples":1}
,"exec":{"mode":1}
,"examples":{"mpls-tp":1}
,"meg2":{"me-name":1}
}
;Search.control.loadWordPairs(pairs);
