var pairs =
{
"bfd_echo_interval_unset":{"function":1,"(u_int32_t":1}
,"function":{"resets":1,"succeeds":1}
,"resets":{"bfd":1}
,"bfd":{"echo":1,"instance":1}
,"echo":{"mode":1}
,"mode":{"transmission":1}
,"transmission":{"interval":1}
,"interval":{"default":1}
,"default":{"value":1}
,"value":{"sessions":1,"pass":1}
,"sessions":{"interface":1}
,"interface":{"syntax":1,"name":1,"found":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"bfd_echo_interval_unset":1,"proc_id":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"s_int32_t":1,"virtual":1}
,"proc_id":{"char":1,"process":1}
,"char":{"*name)":1}
,"*name)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"pass":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"proc_id":1}
,"process":{"bfd":1}
,"instance":{"65535>":1,"found":1}
,"65535>":{"name":1}
,"name":{"interface":1,"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"bfd_api_set_err_vr_not_exist":1}
,"bfd_api_set_err_vr_not_exist":{"exist":1}
,"exist":{"bfd_api_instance_not_found":1}
,"bfd_api_instance_not_found":{"instance":1}
,"found":{"bfd_api_if_not_found":1,"bfd_api_set_error":1}
,"bfd_api_if_not_found":{"interface":1}
,"bfd_api_set_error":{"generic":1}
,"generic":{"error":1}
,"error":{"occurs":1}
,"occurs":{"bfd_api_set_success":1}
,"bfd_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
