var pairs =
{
"topology":{"basic":1,"three":1}
,"basic":{"topology":1}
,"three":{"routers":1}
,"routers":{"bfd":1}
,"bfd":{"echo":1,"slow":1,"slow-timer":1,"multihop":1,"multihop-peer":1,"single-hop":1,"interval":1}
,"echo":{"function":1,"enable":1,"mode":1,"interval":1}
,"function":{"router":1}
,"router":{"configure":1,"(config)":1,"(config-if)":1}
,"configure":{"terminal":1,"mode":1,"bfd":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"interface":1}
,"mode":{"router":1,"bfd":1}
,"(config)":{"bfd":1,"interface":1}
,"enable":{"bfd":1}
,"slow":{"timer":1}
,"timer":{"router":1,"reception":1}
,"slow-timer":{"1000":1,"milliseconds":1}
,"1000":{"configure":1}
,"milliseconds":{"bfd":1,"hello":1}
,"multihop":{"peer":1}
,"peer":{"timer":1}
,"multihop-peer":{"20.1.1.3":1,"timer":1}
,"20.1.1.3":{"interval":1}
,"interval":{"100":1,"millisecond":1,"router":1,"milliseconds":1}
,"100":{"minrx":1,"multiplier":1,"configure":1}
,"minrx":{"100":1}
,"multiplier":{"configure":1,"bfd":1}
,"reception":{"intervals":1,"interval":1}
,"intervals":{"milliseconds":1}
,"hello":{"multiplier":1}
,"single-hop":{"session":1,"sessions":1}
,"session":{"timer":1}
,"interface":{"eth1":1,"mode":1}
,"eth1":{"enter":1}
,"(config-if)":{"bfd":1}
,"sessions":{"timer":1}
,"millisecond":{"hello":1}
}
;Search.control.loadWordPairs(pairs);
