var pairs =
{
"rsvp_snmp_set_tn_hop_addr_type":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"succeeds":1}
,"sets":{"hop":1}
,"hop":{"address":1,"family":1,"found":1}
,"address":{"type":1}
,"type":{"syntax":1}
,"syntax":{"u_int32_t":1}
,"u_int32_t":{"rsvp_snmp_set_tn_hop_addr_type":1,"*path_ix":1,"*hop_ix":1}
,"(u_int32_t":{"*ero_ix":1}
,"*ero_ix":{"u_int32_t":1}
,"*path_ix":{"u_int32_t":1}
,"*hop_ix":{"u_int8_t":1}
,"u_int8_t":{"family)":1}
,"family)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ero_ix":1,"none":1}
,"ero_ix":{"primary":1}
,"primary":{"index":1}
,"index":{"identifying":1}
,"identifying":{"explicit":1,"group":1,"particular":1}
,"explicit":{"route":1}
,"route":{"object":1}
,"object":{"path_ix":1}
,"path_ix":{"secondary":1}
,"secondary":{"index":1}
,"group":{"hops":1}
,"hops":{"configured":1}
,"configured":{"path":1}
,"path":{"hop_ix":1}
,"hop_ix":{"secondary":1}
,"particular":{"hop":1}
,"family":{"constant":1,"rsvp_ipv4":1}
,"constant":{"rsvpd\u002Frsvp_api.h":1}
,"rsvpd\u002Frsvp_api.h":{"rsvp_ipv4":1}
,"rsvp_ipv4":{"output":1,"hop":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"rsvp_api_set_success":1}
,"rsvp_api_set_success":{"function":1}
,"succeeds":{"rsvp_api_set_error":1}
,"rsvp_api_set_error":{"tunnel":1}
,"tunnel":{"active":1}
,"active":{"family":1}
}
;Search.control.loadWordPairs(pairs);
