var pairs =
{
"mstp_api_get_msti_port_path_cost":{"function":1,"(char":1}
,"function":{"gets":1,"succeeds":1}
,"gets":{"path":1}
,"path":{"cost":1}
,"cost":{"port":1,"path":1,"recommended":1}
,"port":{"msti":1,"found":1}
,"msti":{"syntax":1,"instance":1}
,"syntax":{"int":1}
,"int":{"mstp_api_get_msti_port_path_cost":1,"instance":1}
,"(char":{"*name":1}
,"*name":{"char":1}
,"char":{"*ifname":1}
,"*ifname":{"int":1}
,"instance":{"u_int32_t":1,"mstp":1,"output":1,"exist":1}
,"u_int32_t":{"*cost)":1}
,"*cost)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"name":1,"cost":1}
,"name":{"name":1,"bridge":1,"instance":1}
,"bridge":{"ifname":1,"exist":1}
,"ifname":{"interface":1}
,"interface":{"name":1,"found":1}
,"mstp":{"instance":1}
,"output":{"parameters":1}
,"recommended":{"ieee":1}
,"ieee":{"802.1d":1}
,"802.1d":{"2004":1}
,"2004":{"range":1}
,"range":{"200,000,000":1}
,"200,000,000":{"lower":1}
,"lower":{"values":1}
,"values":{"used":1,"result_ok":1}
,"used":{"higher":1}
,"higher":{"speed":1}
,"speed":{"links":1}
,"links":{"return":1}
,"return":{"values":1}
,"result_ok":{"function":1}
,"succeeds":{"mstp_err_interface_not_found":1}
,"mstp_err_interface_not_found":{"specified":1}
,"specified":{"interface":1,"port":1}
,"found":{"mstp_err_bridge_not_found":1}
,"mstp_err_bridge_not_found":{"bridge":1}
,"exist":{"mstp_err_instance_not_found":1,"mstp_err_port_not_found":1}
,"mstp_err_instance_not_found":{"msti":1}
,"mstp_err_port_not_found":{"specified":1}
}
;Search.control.loadWordPairs(pairs);
