var pairs =
{
"features":{"overcome":1,"mrp":1}
,"overcome":{"limitations":1}
,"limitations":{"garp":1}
,"garp":{"zebos-xp":1,"mrp":1}
,"zebos-xp":{"implements":1}
,"implements":{"mrp":1}
,"mrp":{"according":1,"mrp":1,"application":1,"applicant":1,"mad":1,"attribute":1,"participant":1,"protocol":1}
,"according":{"requirements":1}
,"requirements":{"ieee":1}
,"ieee":{"802.1ak":1}
,"802.1ak":{"(d4.0)":1}
,"(d4.0)":{"specification":1}
,"specification":{"following":1}
,"following":{"points":1}
,"points":{"highlight":1}
,"highlight":{"features":1}
,"application":{"maintains":1,"component":1,"within":1,"bridge":1}
,"maintains":{"instance":1,"registrar":1}
,"instance":{"mrp":1,"order":1}
,"applicant":{"per":1,"application":1,"state":1,"establishes":1}
,"per":{"port":1}
,"port":{"mrp":1,"whenever":1,"forms":1,"role":1,"removed":1}
,"component":{"mrp":1,"propagation":1,"mad":1}
,"mad":{"component":1,"maintains":1}
,"propagation":{"attributes":1,"(map)":1,"store":1}
,"attributes":{"two":1,"single":1}
,"two":{"participants":1,"messages":1}
,"participants":{"application":1}
,"within":{"bridge":1}
,"bridge":{"managed":1,"uses":1,"running":1,"mrppdus":1,"instance":1}
,"managed":{"mrp":1}
,"attribute":{"propagation":1}
,"(map)":{"component":1}
,"registrar":{"applicant":1,"port":1,"state":1}
,"state":{"machine":1,"associated":1,"indicate":1}
,"machine":{"similar":1,"maintained":1,"associated":1}
,"similar":{"garp":1,"joinempty":1}
,"uses":{"map":1}
,"map":{"context":1}
,"context":{"defines":1}
,"defines":{"ports":1}
,"ports":{"declaration":1,"bridge":1}
,"declaration":{"needs":1}
,"needs":{"propagated":1}
,"propagated":{"nature":1}
,"nature":{"attribute":1}
,"store":{"forward":1}
,"forward":{"bridge":1}
,"running":{"rstp":1}
,"rstp":{"mstp":1}
,"mstp":{"role":1}
,"role":{"changes":1,"(from":1}
,"changes":{"faster":1}
,"faster":{"risk":1}
,"risk":{"data":1}
,"data":{"loops":1}
,"loops":{"situation":1,"change":1}
,"situation":{"avoided":1}
,"avoided":{"deleting":1}
,"deleting":{"information":1}
,"information":{"held":1,"needed":1,"changingmember":1,"loops":1,"maintained":1}
,"held":{"mads":1}
,"mads":{"registrar":1}
,"whenever":{"transitions":1}
,"transitions":{"root":1}
,"root":{"alternate":1,"designated)":1}
,"alternate":{"designated":1,"root":1}
,"designated":{"forwarding":1}
,"forwarding":{"case":1}
,"case":{"point-to-point":1}
,"point-to-point":{"links":1}
,"links":{"new":1}
,"new":{"(declare":1,"attribute)":1}
,"(declare":{"new":1}
,"attribute)":{"join":1,"(withdraw":1}
,"join":{"(re-declare":1}
,"(re-declare":{"attribute)":1}
,"(withdraw":{"declaration)":1}
,"declaration)":{"messages":1}
,"messages":{"allowed":1,"shared":1,"sent":1}
,"allowed":{"two":1}
,"shared":{"media":1}
,"media":{"newempty":1}
,"newempty":{"newjoin":1}
,"newjoin":{"similar":1}
,"joinempty":{"joinin":1}
,"joinin":{"carry":1}
,"carry":{"additional":1}
,"additional":{"information":1,"member":1}
,"needed":{"propagate":1}
,"propagate":{"topology":1}
,"topology":{"change":1,"bridge":1}
,"change":{"information":1,"associated":1,"port":1}
,"changingmember":{"additional":1}
,"member":{"state":1,"applicant":1}
,"associated":{"active":1,"attributes":1,"participant":1}
,"active":{"member":1,"topology":1}
,"establishes":{"messages":1}
,"sent":{"state":1}
,"indicate":{"topology":1}
,"single":{"leaveall":1}
,"leaveall":{"state":1}
,"maintained":{"every":1,"registrar":1}
,"every":{"mrp":1}
,"participant":{"manages":1,"although":1}
,"manages":{"events":1}
,"events":{"applicants":1}
,"applicants":{"registrar":1}
,"although":{"mrp":1}
,"protocol":{"exchanges":1}
,"exchanges":{"place":1}
,"place":{"ports":1}
,"mrppdus":{"transmitted":1}
,"transmitted":{"port":1}
,"forms":{"active":1}
,"order":{"avoid":1}
,"avoid":{"information":1}
,"(from":{"alternate":1}
,"designated)":{"information":1}
}
;Search.control.loadWordPairs(pairs);
