var pairs =
{
"hal_auth_mac_set_port_state":{"function":1,"(unsigned":1}
,"function":{"sets":1,"fails":1,"succeeds":1}
,"sets":{"port":1}
,"port":{"auth_mac":1,"index":1,"mode":1,"authentication":1}
,"auth_mac":{"state":1}
,"state":{"syntax":1,"mac-based":1,"output":1}
,"syntax":{"int":1}
,"int":{"hal_auth_mac_set_port_state":1,"index":1,"mode":1}
,"(unsigned":{"int":1}
,"index":{"int":1,"port":1,"mode":1}
,"mode":{"enum":1,"port":1,"state":1}
,"enum":{"hal_auth_mac_port_state":1}
,"hal_auth_mac_port_state":{"state)":1}
,"state)":{"input":1}
,"input":{"parameter":1}
,"parameter":{"index":1,"none":1}
,"mac-based":{"port":1}
,"authentication":{"state":1}
,"output":{"parameter":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"function":1}
,"fails":{"hal_success":1}
,"hal_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
