var pairs =
{
"nsm_msg_qos_clean":{"data":1,"{\u002F*cindex":1}
,"data":{"structure":1}
,"structure":{"sent":1}
,"sent":{"protocols":1}
,"protocols":{"nsm":1}
,"nsm":{"clean":1}
,"clean":{"qos":1}
,"qos":{"defined":1}
,"defined":{"lib\u002Fnsm_message.h":1}
,"lib\u002Fnsm_message.h":{"file":1}
,"file":{"member":1}
,"member":{"description":1}
,"description":{"cindex":1}
,"cindex":{"cindex":1,"protocol_id":1,"\u002F*protocol":1}
,"protocol_id":{"protocol":1,"\u002F*ifindex":1}
,"protocol":{"ifindex":1}
,"ifindex":{"ifindex":1,"definition":1}
,"definition":{"struct":1}
,"struct":{"nsm_msg_qos_clean":1}
,"{\u002F*cindex":{"*\u002Fcindex_t":1}
,"*\u002Fcindex_t":{"cindex":1}
,"\u002F*protocol":{"*\u002Fu_int32_t":1}
,"*\u002Fu_int32_t":{"protocol_id":1,"ifindex":1}
,"\u002F*ifindex":{"*\u002Fu_int32_t":1}
}
;Search.control.loadWordPairs(pairs);
