var pairs =
{
"wtr":{"timer":1}
,"timer":{"command":1,"used":1,"default":1,"<0-720>":1,"parameters":1,"seconds":1,"300":1,"configure":1}
,"command":{"wait-to-restore":1,"syntax":1,"mode":1}
,"wait-to-restore":{"timer":1}
,"used":{"verify":1}
,"verify":{"signal":1}
,"signal":{"failure":1}
,"failure":{"intermittent":1}
,"intermittent":{"form":1}
,"form":{"command":1}
,"default":{"value":1,"default":1}
,"value":{"command":1,"wait-to-restore":1}
,"syntax":{"wtr":1}
,"<0-720>":{"wtr":1,"value":1}
,"parameters":{"<0-720>":1}
,"seconds":{"default":1,"command":1}
,"300":{"seconds":1}
,"mode":{"protection":1,"examples":1}
,"protection":{"group":1}
,"group":{"mode":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"mpls-tp":1}
,"mpls-tp":{"rps":1}
,"rps":{"protection-group":1}
,"protection-group":{"abc":1}
,"abc":{"(config-pg)":1}
,"(config-pg)":{"wtr":1,"wtr-timer":1}
}
;Search.control.loadWordPairs(pairs);
