var pairs =
{
"full":{"status":1}
,"status":{"polling":1,"inquiry":1,"report":1}
,"polling":{"interval":1}
,"interval":{"full":1,"uni-c":1,"specified":1}
,"uni-c":{"sends":1}
,"sends":{"status":1}
,"inquiry":{"uni-n":1,"intermediate":1}
,"uni-n":{"interval":1}
,"specified":{"n391":1}
,"n391":{"n391":1,"specifies":1,"value":1}
,"specifies":{"frequency":1,"full":1}
,"frequency":{"inquiries":1}
,"inquiries":{"expect":1,"ask":1}
,"expect":{"full":1}
,"report":{"example":1,"response":1}
,"example":{"n391":1}
,"value":{"360":1}
,"360":{"specifies":1}
,"response":{"every":1}
,"every":{"360th":1}
,"360th":{"inquiry":1}
,"intermediate":{"inquiries":1}
,"ask":{"keep-alive":1}
,"keep-alive":{"exchange":1}
,"exchange":{"range":1}
,"range":{"65k":1}
,"65k":{"default":1}
,"default":{"value":1}
}
;Search.control.loadWordPairs(pairs);
