var pairs =
{
"slave-only":{"command":1,"mode":1,"(enable":1,"enable":1}
,"command":{"enable":1,"syntax":1,"mode":1}
,"enable":{"disable":1,"clock":1}
,"disable":{"slave-only":1,"clock":1}
,"mode":{"clock":1,"ptp":1,"examples":1}
,"clock":{"command":1,"always":1,"considered":1,"best":1,"algorithm":1,"configure":1}
,"syntax":{"slave-only":1}
,"(enable":{"disable)":1}
,"disable)":{"parameters":1}
,"parameters":{"enable":1}
,"always":{"synchronizes":1}
,"synchronizes":{"clock":1}
,"considered":{"candidate":1}
,"candidate":{"master":1}
,"master":{"clock":1}
,"best":{"master":1}
,"algorithm":{"disable":1,"command":1}
,"ptp":{"clock":1}
,"configure":{"mode":1}
,"examples":{"ena":1}
,"ena":{"config":1}
,"config":{"term":1}
,"term":{"enter":1}
,"enter":{"configuration":1}
,"configuration":{"commands":1}
,"commands":{"per":1}
,"per":{"line":1}
,"line":{"end":1}
,"end":{"cntl\u002Fz":1}
,"cntl\u002Fz":{"(config)":1}
,"(config)":{"ptp-clk":1}
,"ptp-clk":{"ordinary":1}
,"ordinary":{"transport-type":1}
,"transport-type":{"ethernet":1}
,"ethernet":{"(config-ptp-clk)":1}
,"(config-ptp-clk)":{"slave-only":1}
}
;Search.control.loadWordPairs(pairs);
