var pairs =
{
"primary":{"fast-reroute":1}
,"fast-reroute":{"protection":1}
,"protection":{"command":1,"mechanism":1,"methods":1,"(one-to-one":1,"one-to-one":1,"facility":1}
,"command":{"create":1,"used":1,"helps":1,"remove":1,"syntax":1,"mode":1}
,"create":{"fast":1,"frr":1}
,"fast":{"reroute":1}
,"reroute":{"backup":1}
,"backup":{"lsp":1,"assign":1,"(bypass":1}
,"lsp":{"one-to-one":1,"command":1,"either":1,"protection":1}
,"one-to-one":{"protection":1,"facility-backup":1,"one-to-one":1,"configure":1}
,"mechanism":{"command":1,"parameters":1,"facility":1}
,"used":{"create":1}
,"frr":{"facility":1,"backup":1}
,"facility":{"(bypass)":1,"backup":1,"parameters":1,"facility":1,"protection":1}
,"(bypass)":{"backup":1}
,"assign":{"facility":1}
,"(bypass":{"tunnel)":1}
,"tunnel)":{"available":1}
,"available":{"protected":1}
,"protected":{"lsp":1}
,"helps":{"identify":1}
,"identify":{"attributes":1}
,"attributes":{"frr":1}
,"either":{"one-to-one":1}
,"facility-backup":{"protection":1}
,"methods":{"parameter":1}
,"parameter":{"command":1}
,"remove":{"lsp":1}
,"parameters":{"none":1,"one-to-one":1}
,"none":{"command":1}
,"syntax":{"primary":1}
,"(one-to-one":{"facility)":1,"facility":1}
,"facility)":{"primary":1}
,"mode":{"trunk":1,"examples":1}
,"trunk":{"mode":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"rsvp-trunk":1}
,"rsvp-trunk":{"(config-trunk)":1}
,"(config-trunk)":{"primary":1}
}
;Search.control.loadWordPairs(pairs);
