var pairs =
{
"network":{"time":1}
,"time":{"protocol":1,"(utc)":1,"sources":1}
,"protocol":{"chapter":1,"(ntp)":1}
,"chapter":{"reference":1,"contains":1}
,"reference":{"network":1,"clock":1}
,"(ntp)":{"commands":1}
,"commands":{"ntp":1,"clear":1}
,"ntp":{"synchronizes":1,"synchronize":1,"uses":1,"statistics":1,"ntp":1,"authenticate":1,"authentication-key":1,"enable":1,"logging":1,"peer":1,"server":1,"sync-retry":1,"trusted-key":1,"authentication-keys":1,"authentication-status":1,"logging-status":1,"peer-status":1,"peers":1,"trusted-keys":1}
,"synchronizes":{"clocks":1}
,"clocks":{"computer":1}
,"computer":{"systems":1}
,"systems":{"packet-switched":1}
,"packet-switched":{"networks":1}
,"networks":{"ntp":1}
,"synchronize":{"participating":1}
,"participating":{"computers":1}
,"computers":{"within":1}
,"within":{"few":1}
,"few":{"milliseconds":1}
,"milliseconds":{"coordinated":1}
,"coordinated":{"universal":1}
,"universal":{"time":1}
,"(utc)":{"ntp":1}
,"uses":{"hierarchical":1}
,"hierarchical":{"layered":1}
,"layered":{"system":1}
,"system":{"time":1}
,"sources":{"level":1}
,"level":{"hierarchy":1}
,"hierarchy":{"called":1,"chapter":1}
,"called":{"stratum":1}
,"stratum":{"assigned":1}
,"assigned":{"number":1}
,"number":{"starting":1,"represents":1}
,"starting":{"zero":1}
,"zero":{"top":1}
,"top":{"number":1}
,"represents":{"distance":1}
,"distance":{"reference":1}
,"clock":{"used":1}
,"used":{"prevent":1}
,"prevent":{"cyclical":1}
,"cyclical":{"dependencies":1}
,"dependencies":{"hierarchy":1}
,"contains":{"commands":1}
,"clear":{"ntp":1}
,"statistics":{"feature":1,"show":1}
,"feature":{"ntp":1}
,"authenticate":{"ntp":1}
,"authentication-key":{"ntp":1}
,"enable":{"ntp":1}
,"logging":{"ntp":1}
,"peer":{"ntp":1}
,"server":{"ntp":1}
,"sync-retry":{"ntp":1}
,"trusted-key":{"show":1}
,"show":{"ntp":1,"running-config":1}
,"authentication-keys":{"show":1}
,"authentication-status":{"show":1}
,"logging-status":{"show":1}
,"peer-status":{"show":1}
,"peers":{"show":1}
,"trusted-keys":{"show":1}
,"running-config":{"ntp":1}
}
;Search.control.loadWordPairs(pairs);
