var pairs =
{
"efm":{"oam":1}
,"oam":{"commands":1,"protocol":1,"debug":1,"disable":1,"enable":1,"link-monitor":1,"max-rate":1,"min-rate":1,"mode":1,"remote-failure":1,"remote-loopback":1,"timeout":1,"unidirectional-link":1,"show":1,"discovery":1,"eventlog":1,"statistics":1,"status":1}
,"commands":{"ethernet":1,"used":1}
,"ethernet":{"first":1,"oam":1}
,"first":{"mile":1}
,"mile":{"(efm)":1}
,"(efm)":{"provides":1}
,"provides":{"minimal":1}
,"minimal":{"extension":1}
,"extension":{"mac":1}
,"mac":{"layer":1}
,"layer":{"operations":1}
,"operations":{"administration":1,"remote":1}
,"administration":{"maintenance":1}
,"maintenance":{"(oam)":1}
,"(oam)":{"module":1}
,"module":{"supplies":1}
,"supplies":{"mechanism":1}
,"mechanism":{"monitoring":1}
,"monitoring":{"link":1}
,"link":{"operations":1}
,"remote":{"fault":1,"loopback":1}
,"fault":{"detection":1}
,"detection":{"remote":1}
,"loopback":{"control":1}
,"control":{"chapter":1}
,"chapter":{"commands":1}
,"used":{"manage":1}
,"manage":{"ethernet":1}
,"protocol":{"processes":1}
,"processes":{"includes":1}
,"includes":{"following":1}
,"following":{"commands":1}
,"debug":{"ethernet":1}
,"disable":{"ethernet":1}
,"enable":{"ethernet":1}
,"link-monitor":{"event-log-size":1,"frame":1,"frame-period":1,"frame-seconds":1,"high":1,"ethernet":1,"supported":1,"symbol-period":1}
,"event-log-size":{"ethernet":1}
,"frame":{"ethernet":1}
,"frame-period":{"ethernet":1}
,"frame-seconds":{"ethernet":1}
,"high":{"ethernet":1}
,"supported":{"ethernet":1}
,"symbol-period":{"ethernet":1}
,"max-rate":{"ethernet":1}
,"min-rate":{"ethernet":1}
,"mode":{"ethernet":1}
,"remote-failure":{"ethernet":1}
,"remote-loopback":{"(start":1,"{supported":1}
,"(start":{"stop)":1}
,"stop)":{"ethernet":1}
,"{supported":{"timeout}":1}
,"timeout}":{"ethernet":1}
,"timeout":{"ethernet":1}
,"unidirectional-link":{"show":1}
,"show":{"ethernet":1}
,"discovery":{"show":1}
,"eventlog":{"show":1}
,"statistics":{"show":1}
,"status":{"snmp":1}
,"snmp":{"restart":1}
,"restart":{"efm":1}
}
;Search.control.loadWordPairs(pairs);
