var pairs =
{
"show":{"vlan":1}
,"vlan":{"auto":1,"name":1}
,"auto":{"command":1,"show":1,"bridge":1}
,"command":{"display":1,"syntax":1,"mode":1,"using":1}
,"display":{"information":1}
,"information":{"vlans":1}
,"vlans":{"auto-configured":1}
,"auto-configured":{"command":1}
,"syntax":{"show":1}
,"bridge":{"<1-32>":1,"displays":1,"group":1,"vlan":1}
,"<1-32>":{"parameters":1}
,"parameters":{"bridge":1}
,"displays":{"bridge":1}
,"group":{"command":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"following":1}
,"following":{"sample":1}
,"sample":{"output":1}
,"output":{"command":1}
,"using":{"parameter":1}
,"parameter":{"show":1}
,"name":{"state":1}
,"state":{"member":1}
,"member":{"ports":1}
,"ports":{"(u)-untagged":1}
,"(u)-untagged":{"(t)-tagged":1}
,"(t)-tagged":{"============================================================================bridge":1,"============================================================================":1}
,"============================================================================bridge":{"vlan":1}
}
;Search.control.loadWordPairs(pairs);
