var pairs =
{
"nsm_mpls_set_ftn_protocol":{"function":1,"(struct":1}
,"function":{"sets":1,"succeeds":1,"fails":1}
,"sets":{"protocol":1}
,"protocol":{"match":1,"number":1,"protocol":1}
,"match":{"against":1,"(255)":1}
,"against":{"ipv4":1}
,"ipv4":{"protocol":1}
,"number":{"packet":1}
,"packet":{"syntax":1,"permitted":1}
,"syntax":{"u_int32_t":1}
,"u_int32_t":{"nsm_mpls_set_ftn_protocol":1,"ftn_ix":1,"protocol)":1}
,"(struct":{"nsm_master":1}
,"nsm_master":{"*nm":1}
,"*nm":{"u_int32_t":1}
,"ftn_ix":{"u_int32_t":1,"index":1}
,"protocol)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"nsm":1,"none":1}
,"nsm":{"master":1}
,"master":{"ftn_ix":1}
,"index":{"conceptual":1}
,"conceptual":{"row":1}
,"row":{"ftn":1}
,"ftn":{"table":1}
,"table":{"protocol":1}
,"permitted":{"value":1}
,"value":{"match":1}
,"(255)":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_api_set_success":1}
,"nsm_api_set_success":{"function":1}
,"succeeds":{"nsm_api_set_error":1}
,"nsm_api_set_error":{"function":1}
}
;Search.control.loadWordPairs(pairs);
