var pairs =
{
"ipv6":{"current-hoplimit":1}
,"current-hoplimit":{"command":1,"<0-255>":1,"(<0-255>":1,"(config-if)":1}
,"command":{"(neighbor":1,"remove":1,"syntax":1,"mode":1}
,"(neighbor":{"discovery)":1}
,"discovery)":{"advertised":1}
,"advertised":{"hop":1}
,"hop":{"limit":1}
,"limit":{"interface":1,"command":1,"within":1}
,"interface":{"option":1,"mode":1,"eth0":1}
,"option":{"command":1}
,"remove":{"current":1}
,"current":{"hop":1}
,"syntax":{"ipv6":1}
,"<0-255>":{"ipv6":1,"hop":1}
,"(<0-255>":{"parameter":1}
,"parameter":{"<0-255>":1}
,"within":{"range":1}
,"range":{"command":1}
,"mode":{"interface":1,"examples":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"ipv6":1}
}
;Search.control.loadWordPairs(pairs);
