var pairs =
{
"bgp":{"mpls":1,"vpn":1,"used":1,"uses":1}
,"mpls":{"ipv4":1}
,"ipv4":{"vpn":1}
,"vpn":{"zebos-xp":1,"fully":1,"traffic":1,"routes":1}
,"zebos-xp":{"bgp":1,"routing":1}
,"fully":{"scalable":1}
,"scalable":{"implementation":1}
,"implementation":{"ietf":1}
,"ietf":{"2547-bis":1}
,"2547-bis":{"zebos-xp":1}
,"used":{"either":1,"contain":1,"destination":1}
,"either":{"pe\u002Fp":1}
,"pe\u002Fp":{"node":1}
,"node":{"service":1}
,"service":{"provider":1}
,"provider":{"network":1,"edge":1}
,"network":{"cpe":1,"isolation":1,"separate":1}
,"cpe":{"connect":1}
,"connect":{"service":1}
,"edge":{"using":1,"provider":1,"(ce-pe)":1}
,"using":{"ebgp":1}
,"ebgp":{"zebos-xp":1}
,"routing":{"protocols":1}
,"protocols":{"rip":1,"zebos-xp":1}
,"rip":{"ospf":1}
,"ospf":{"extended":1}
,"extended":{"work":1}
,"work":{"customer":1}
,"customer":{"edge":1}
,"(ce-pe)":{"routing":1}
,"uses":{"multiple":1}
,"multiple":{"forwarding":1}
,"forwarding":{"tables":1,"table":1}
,"tables":{"provide":1,"vpn":1}
,"provide":{"network":1}
,"isolation":{"vpn":1}
,"traffic":{"inside":1}
,"inside":{"service":1}
,"separate":{"default":1}
,"default":{"forwarding":1}
,"table":{"used":1,"per":1}
,"contain":{"public":1}
,"public":{"internet":1}
,"internet":{"routes":1}
,"routes":{"site-based":1,"router":1,"packet":1}
,"site-based":{"vrf":1}
,"vrf":{"tables":1,"table":1,"used":1}
,"router":{"maintains":1}
,"maintains":{"vrf":1}
,"per":{"site":1}
,"site":{"shares":1}
,"shares":{"routes":1}
,"packet":{"received":1}
,"received":{"pe-ce":1}
,"pe-ce":{"interface":1}
,"interface":{"corresponding":1}
,"corresponding":{"vrf":1}
,"destination":{"address":1}
,"address":{"lookup":1}
}
;Search.control.loadWordPairs(pairs);
