var pairs =
{
"extcommunity-list":{"<100-199>":1,"125":1}
,"<100-199>":{"command":1,"(deny":1,"extended":1}
,"command":{"create":1,"delete":1,"syntax":1,"mode":1}
,"create":{"expanded":1}
,"expanded":{"extended":1}
,"extended":{"community":1}
,"community":{"list":1,"permit":1,"line":1}
,"list":{"parameter":1,"number":1,"regular":1}
,"parameter":{"command":1}
,"delete":{"community-list":1}
,"community-list":{"entry":1}
,"entry":{"command":1}
,"syntax":{"extcommunity-list":1}
,"(deny":{"permit)":1}
,"permit)":{"line":1}
,"line":{"extcommunity-list":1,"parameters":1,"ordered":1}
,"parameters":{"<100-199>":1}
,"number":{"(expanded)":1}
,"(expanded)":{"deny":1}
,"deny":{"reject":1}
,"reject":{"community":1}
,"permit":{"accept":1,"4567335":1}
,"accept":{"community":1}
,"ordered":{"list":1}
,"regular":{"expression":1}
,"expression":{"command":1}
,"mode":{"configure":1,"examples":1}
,"configure":{"mode":1,"terminal":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"extcommunity-list":1}
,"125":{"permit":1}
}
;Search.control.loadWordPairs(pairs);
