var pairs =
{
"ipv6":{"mld":1,"named":1,"address":1,"access-list":1}
,"mld":{"ssm-map":1,"layer-3":1,"snooping":1,"proxy":1,"(vrf":1}
,"ssm-map":{"static":1}
,"static":{"command":1,"mode":1,"word":1,"mapping":1,"v6grp":1}
,"command":{"specify":1,"applies":1,"remove":1,"syntax":1,"mode":1}
,"specify":{"static":1,"vrf":1,"ipv6":1}
,"mode":{"defining":1,"interface":1,"vlan":1}
,"defining":{"ssm":1}
,"ssm":{"mapping":1,"map":1,"static":1}
,"mapping":{"ssm":1,"statically":1,"group-address":1}
,"statically":{"assigns":1}
,"assigns":{"sources":1}
,"sources":{"mldv1":1}
,"mldv1":{"groups":1}
,"groups":{"translate":1,"memberships":1}
,"translate":{"groups":1}
,"memberships":{"memberships":1,"pim-ssm":1}
,"pim-ssm":{"command":1}
,"applies":{"interfaces":1}
,"interfaces":{"configured":1}
,"configured":{"mld":1}
,"layer-3":{"multicast":1}
,"multicast":{"protocols":1}
,"protocols":{"mld":1}
,"snooping":{"mld":1}
,"proxy":{"parameter":1}
,"parameter":{"command":1}
,"remove":{"ssm":1}
,"map":{"association":1}
,"association":{"command":1}
,"syntax":{"ipv6":1}
,"word":{"x:x":1,"specify":1}
,"x:x":{":x:x":1}
,":x:x":{"ipv6":1,"parameters":1,"specify":1}
,"(vrf":{"name":1}
,"name":{"ssm-map":1,"word":1}
,"parameters":{"vrf":1}
,"vrf":{"specify":1,"name":1}
,"named":{"standard":1}
,"standard":{"access-list":1}
,"access-list":{"x:x":1,"v6grp":1}
,"address":{"command":1}
,"interface":{"mode":1,"example":1}
,"vlan":{"interface":1}
,"example":{"example":1,"shows":1}
,"shows":{"configure":1}
,"configure":{"ssm":1,"terminal":1}
,"group-address":{"ff0e":1}
,"ff0e":{":1\u002F128":1}
,":1\u002F128":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"ipv6":1}
,"v6grp":{"2006":1,"permit":1}
,"2006":{"(config)":1}
,"permit":{"ff0e":1}
}
;Search.control.loadWordPairs(pairs);
