var pairs =
{
"rip2_get_next_if_conf_send":{"function":1,"(int":1}
,"function":{"returns":1}
,"returns":{"router":1}
,"router":{"sends":1,"found":1}
,"sends":{"next":1}
,"next":{"interface":1,"entry":1,"updates":1}
,"interface":{"(typically":1,"index":1,"indexlen":1}
,"(typically":{"updates)":1}
,"updates)":{"address":1}
,"address":{"interface":1,"specified":1}
,"index":{"partial":1,"complete":1}
,"partial":{"match":1}
,"match":{"located":1,"error":1}
,"located":{"table":1,"next":1}
,"table":{"entry":1}
,"entry":{"returned":1,"error":1}
,"returned":{"match":1,"address":1,"next":1,"indexlen":1,"syntax":1}
,"error":{"returned":1}
,"complete":{"match":1}
,"indexlen":{"zero":1,"int":1,"future":1}
,"zero":{"first":1}
,"first":{"entry":1}
,"syntax":{"int":1}
,"int":{"rip2_get_next_if_conf_send":1,"indexlen":1,"*value)":1}
,"(int":{"pid":1}
,"pid":{"struct":1,"rip":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"*addr":1}
,"*addr":{"int":1}
,"*value)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"pid":1,"value":1}
,"rip":{"process":1}
,"process":{"addr":1}
,"addr":{"address":1}
,"specified":{"interface":1}
,"future":{"output":1}
,"output":{"parameters":1}
,"value":{"following":1}
,"following":{"updates":1}
,"updates":{"rip_api_ifconf_send_donotsend":1,"sent":1}
,"rip_api_ifconf_send_donotsend":{"rip_api_ifconf_send_ripversion1":1}
,"rip_api_ifconf_send_ripversion1":{"rip_api_ifconf_send_ripversion2":1}
,"rip_api_ifconf_send_ripversion2":{"rip_api_ifconf_send_rip1compatible":1}
,"rip_api_ifconf_send_rip1compatible":{"return":1}
,"return":{"values":1}
,"values":{"rip_api_get_error":1}
,"rip_api_get_error":{"next":1}
,"sent":{"router":1}
,"found":{"rip_api_get_success":1}
,"rip_api_get_success":{"call":1}
,"call":{"finds":1}
,"finds":{"next":1}
}
;Search.control.loadWordPairs(pairs);
