var pairs =
{
"bfd_echo_mode_set":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"succeeds":1}
,"sets":{"bfd":1}
,"bfd":{"echo":1,"process":1,"instance":1}
,"echo":{"mode":1}
,"mode":{"interfaces":1}
,"interfaces":{"bfd":1}
,"process":{"syntax":1,"bfd":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"bfd_echo_mode_set":1,"proc_id)":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"s_int32_t":1,"virtual":1}
,"proc_id)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"pass":1}
,"pass":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"proc_id":1}
,"proc_id":{"process":1}
,"instance":{"65535>":1,"found":1}
,"65535>":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"bfd_api_instance_not_found":1}
,"bfd_api_instance_not_found":{"instance":1}
,"found":{"bfd_api_set_error":1}
,"bfd_api_set_error":{"generic":1}
,"generic":{"error":1}
,"error":{"occurs":1}
,"occurs":{"bfd_api_set_success":1}
,"bfd_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
