var pairs =
{
"system":{"design":1,"module":1}
,"design":{"following":1,"pbb-te":1}
,"following":{"section":1}
,"section":{"describes":1}
,"describes":{"system":1}
,"pbb-te":{"aps":1}
,"aps":{"load":1,"signaling":1,"automatic":1,"frame":1,"manual":1}
,"load":{"sharing":1}
,"sharing":{"aps":1,"signal":1,"manual":1,"tesi":1,"administrative":1}
,"signaling":{"reception":1,"therefore":1,"sent":1,"received":1}
,"reception":{"aps":1,"changes":1}
,"automatic":{"protection":1}
,"protection":{"switching":1,"group":1,"groups":1,"based":1,"state":1}
,"switching":{"module":1,"aps":1,"part":1,"per":1,"loss":1,"occurs":1,"protection":1}
,"module":{"responsible":1,"(nsm)":1}
,"responsible":{"signaling":1}
,"changes":{"aps":1,"based":1}
,"frame":{"oam":1,"tesi":1}
,"oam":{"frames":1}
,"frames":{"received":1}
,"received":{"cfm":1,"considered":1,"protective":1,"protected":1,"far":1,"switching":1}
,"cfm":{"socket":1}
,"socket":{"upon":1}
,"upon":{"receiving":1}
,"receiving":{"aps":1}
,"tesi":{"tesi":1,"part":1,"performs":1,"specific":1,"switching":1,"administrative":1,"basis":1,"active":1,"aps":1,"belongs":1,"ccm":1,"protection":1,"sent":1}
,"part":{"load":1,"multiple":1}
,"signal":{"received":1}
,"considered":{"protection":1}
,"group":{"looping":1,"aps":1,"load":1,"switching":1,"tesi":1,"lesser":1,"associated":1,"state":1,"current":1,"maps":1}
,"looping":{"protection":1}
,"manual":{"switching":1,"switch":1}
,"multiple":{"protection":1}
,"groups":{"tesi":1,"switching":1,"part":1,"associating":1,"isid":1}
,"switch":{"command":1,"working":1}
,"command":{"tesi":1}
,"performs":{"manual":1}
,"working":{"protection":1}
,"based":{"tesi":1,"state":1}
,"specific":{"protection":1}
,"per":{"te-group":1,"tesi":1,"group":1}
,"te-group":{"coordination":1}
,"coordination":{"protection":1}
,"administrative":{"commands":1,"switching":1}
,"commands":{"manual":1}
,"loss":{"connection":1}
,"connection":{"fail":1}
,"fail":{"start":1}
,"start":{"issued":1}
,"issued":{"per":1,"protection":1}
,"basis":{"example":1}
,"example":{"issued":1}
,"active":{"pg-1":1,"tesi":1,"tesid":1}
,"pg-1":{"addition":1}
,"addition":{"state":1}
,"state":{"change":1,"machines":1}
,"change":{"sent":1,"message":1,"detected":1,"aps":1,"received":1}
,"sent":{"far":1,"onmd":1,"nsm":1}
,"far":{"end":1}
,"end":{"far":1,"request":1,"however":1,"aps":1,"state":1}
,"request":{"received":1}
,"protective":{"tesi":1}
,"therefore":{"far":1}
,"protected":{"tesi":1}
,"belongs":{"two":1}
,"two":{"protection":1}
,"occurs":{"pgs":1}
,"pgs":{"far":1}
,"however":{"protection":1}
,"lesser":{"ccm":1}
,"ccm":{"transmission":1,"avoids":1,"message":1,"convergence":1}
,"transmission":{"interval":1,"data":1,"even":1}
,"interval":{"achieve":1,"ccm":1}
,"achieve":{"lower":1}
,"lower":{"ccm":1}
,"data":{"buffered":1}
,"buffered":{"outgoing":1}
,"outgoing":{"ccm":1}
,"avoids":{"sending":1}
,"sending":{"ccm":1}
,"message":{"every":1,"associating":1,"sent":1}
,"every":{"transmission":1}
,"even":{"change":1}
,"associating":{"protection":1}
,"isid":{"done":1,"associated":1}
,"done":{"network":1}
,"network":{"system":1}
,"(nsm)":{"create":1}
,"create":{"message":1}
,"onmd":{"onmd":1,"mep":1}
,"mep":{"created":1}
,"created":{"tesi":1}
,"convergence":{"checks":1}
,"checks":{"tesi":1}
,"associated":{"working":1,"protection":1}
,"detected":{"side":1}
,"side":{"protection":1}
,"machines":{"changes":1}
,"current":{"active":1}
,"nsm":{"nsm":1,"isid":1}
,"maps":{"egress":1}
,"egress":{"esp-bvid":1}
,"esp-bvid":{"active":1}
}
;Search.control.loadWordPairs(pairs);
