var pairs =
{
"ospf6_router_unset":{"function":1,"(u_int32_t":1}
,"function":{"removes":1,"called":1,"succeeds":1}
,"removes":{"ospfv3":1}
,"ospfv3":{"router":1,"process":1}
,"router":{"instance":1,"ipv6":1,"non-virtual-router":1,"exist":1}
,"instance":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"router":1}
,"ipv6":{"ospf":1}
,"ospf":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf6_router_unset":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1}
,"char":{"*tag)":1}
,"*tag)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"tag":1}
,"tag":{"ospfv3":1,"output":1}
,"process":{"tag":1,"exist":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf6_api_set_err_vr_not_exist":1}
,"ospf6_api_set_err_vr_not_exist":{"virtual":1}
,"exist":{"ospf6_api_set_err_process_not_exist":1,"ospf6_api_set_success":1}
,"ospf6_api_set_err_process_not_exist":{"specified":1}
,"specified":{"process":1}
,"ospf6_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
