var pairs =
{
"isis_get_next_summ_addr_full_metric":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"next":1}
,"next":{"wide":1,"summary":1}
,"wide":{"metric":1}
,"metric":{"value":1}
,"value":{"announce":1,"non-vr":1,"isis_api_get_success":1}
,"announce":{"summary":1}
,"summary":{"address":1}
,"address":{"syntax":1,"summary":1,"prefixlen":1,"indexlen":1,"return":1,"found":1}
,"syntax":{"int":1}
,"int":{"isis_get_next_summ_addr_full_metric":1,"indexlen":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1,"instance":1}
,"u_int32_t":{"*instance":1,"*type":1,"*prefixlen":1,"*ret)":1}
,"*instance":{"u_int32_t":1}
,"*type":{"struct":1}
,"struct":{"prefix":1}
,"prefix":{"u_int32_t":1,"length":1}
,"*prefixlen":{"int":1}
,"indexlen":{"u_int32_t":1,"length":1}
,"*ret)":{"input":1}
,"input":{"parameter":1}
,"parameter":{"vr_id":1,"ret":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"instance":{"is-is":1,"type":1,"isis_api_get_error":1}
,"is-is":{"instance":1}
,"type":{"type":1,"summary":1}
,"prefixlen":{"prefix":1}
,"length":{"summary":1,"index":1}
,"index":{"output":1}
,"output":{"parameter":1}
,"ret":{"wide":1}
,"return":{"value":1}
,"isis_api_get_success":{"summary":1}
,"found":{"specified":1}
,"specified":{"instance":1}
,"isis_api_get_error":{"next":1}
}
;Search.control.loadWordPairs(pairs);
