var pairs =
{
"rsvp_api_trunk_unset_sessions":{"call":1,"(struct":1}
,"call":{"unsets":1}
,"unsets":{"configuration":1}
,"configuration":{"syntax":1}
,"syntax":{"void":1}
,"void":{"rsvp_api_trunk_unset_sessions":1}
,"(struct":{"rsvp_trunk":1}
,"rsvp_trunk":{"*trunk":1}
,"*trunk":{"u_char":1}
,"u_char":{"session_type)":1}
,"session_type)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"trunk":1,"none":1}
,"trunk":{"rsvp":1,"session_type":1}
,"rsvp":{"trunk":1}
,"session_type":{"session":1}
,"session":{"type":1}
,"type":{"rsvp_session_type_undefined":1}
,"rsvp_session_type_undefined":{"rsvp_session_type_primary":1}
,"rsvp_session_type_primary":{"rsvp_session_type_secondary":1}
,"rsvp_session_type_secondary":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"none":1}
}
;Search.control.loadWordPairs(pairs);
