var pairs =
{
"weighted":{"fair":1}
,"fair":{"queuing":1}
,"queuing":{"(wfq)":1}
,"(wfq)":{"queue":1}
,"queue":{"scheduling":1,"weight":1}
,"scheduling":{"discipline":1}
,"discipline":{"queue":1}
,"weight":{"assigned":1}
,"assigned":{"different":1}
,"different":{"percentage":1}
,"percentage":{"output":1}
,"output":{"port":1}
,"port":{"bandwidth":1}
,"bandwidth":{"wfq":1,"flows":1}
,"wfq":{"supports":1,"classifies":1,"provides":1}
,"supports":{"variable-length":1}
,"variable-length":{"packets":1}
,"packets":{"flows":1,"allocated":1,"wfq":1}
,"flows":{"larger":1,"smaller":1}
,"larger":{"packets":1}
,"allocated":{"bandwidth":1}
,"smaller":{"packets":1}
,"classifies":{"traffic":1}
,"traffic":{"high-or":1,"getting":1,"sharing":1,"bursts":1,"discarded":1,"preventing":1,"sustained":1}
,"high-or":{"low-bandwidth":1}
,"low-bandwidth":{"low-bandwidth":1,"traffic":1}
,"getting":{"priority":1}
,"priority":{"high-bandwidth":1,"traffic":1}
,"high-bandwidth":{"traffic":1}
,"sharing":{"left":1}
,"left":{"traffic":1}
,"bursts":{"ahead":1}
,"ahead":{"rate":1}
,"rate":{"interface":1}
,"interface":{"transmit":1}
,"transmit":{"new":1}
,"new":{"high-bandwidth":1}
,"discarded":{"congestive-messages":1}
,"congestive-messages":{"threshold":1}
,"threshold":{"reached":1}
,"reached":{"wfq":1}
,"provides":{"preferential":1}
,"preferential":{"treatment":1}
,"treatment":{"higher":1}
,"higher":{"priority":1}
,"preventing":{"total":1}
,"total":{"starvation":1}
,"starvation":{"lower":1}
,"lower":{"priority":1}
,"sustained":{"overload":1}
,"overload":{"conditions":1}
}
;Search.control.loadWordPairs(pairs);
