var pairs =
{
"cfm_1dm_rx_enable":{"function":1}
,"function":{"called":1,"succeeds":1,"fails":1}
,"called":{"ethernet":1}
,"ethernet":{"cfm":1}
,"cfm":{"1dm":1}
,"1dm":{"receive":1}
,"receive":{"command":1}
,"command":{"enable":1}
,"enable":{"configure":1}
,"configure":{"reception":1}
,"reception":{"one-way":1}
,"one-way":{"frames":1,"sends":1,"delay":1}
,"frames":{"mep":1,"eth-dm":1}
,"mep":{"specific":1,"point-to-point":1,"performs":1,"sends":1,"receives":1,"carry":1,"configured":1,"associated":1,"<1-8191>":1}
,"specific":{"frame":1}
,"frame":{"delay":1,"timestamp":1}
,"delay":{"frame":1,"variation":1,"(1dm)":1,"two-way":1}
,"variation":{"performed":1,"measurements":1}
,"performed":{"two":1}
,"two":{"ways":1}
,"ways":{"one-way":1}
,"sends":{"eth_dm":1,"frames":1}
,"eth_dm":{"frame":1}
,"timestamp":{"calculated":1}
,"calculated":{"time":1}
,"time":{"transmission":1}
,"transmission":{"remote":1}
,"remote":{"mep":1}
,"point-to-point":{"remote":1}
,"performs":{"one-way":1}
,"(1dm)":{"and\u002For":1}
,"and\u002For":{"one-way":1}
,"measurements":{"(dvm)":1,"syntax":1}
,"(dvm)":{"two-way":1}
,"two-way":{"(dmm)":1,"frame":1}
,"(dmm)":{"mep":1}
,"eth-dm":{"request":1,"reply":1}
,"request":{"information":1}
,"information":{"peer":1}
,"peer":{"mep":1}
,"receives":{"frames":1}
,"reply":{"information":1}
,"carry":{"two-way":1}
,"syntax":{"include":1}
,"include":{"cfm_dm.h":1}
,"cfm_dm.h":{"struct":1}
,"struct":{"cfm_1dm_rx":1}
,"cfm_1dm_rx":{"*cfm_1dm_rx_enable":1,"structure":1}
,"*cfm_1dm_rx_enable":{"(struct":1}
,"(struct":{"onmd_bridge":1}
,"onmd_bridge":{"*bridge":1}
,"*bridge":{"u_int8_t":1}
,"u_int8_t":{"*md_name":1}
,"*md_name":{"u_int16_t":1}
,"u_int16_t":{"vid":1,"duration)":1}
,"vid":{"u_int32_t":1,"vlan":1}
,"u_int32_t":{"mpid":1}
,"mpid":{"u_int16_t":1,"host":1}
,"duration)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bridge":1,"none":1}
,"bridge":{"bridge":1,"mep":1}
,"configured":{"md_name":1}
,"md_name":{"name":1}
,"name":{"mep":1}
,"associated":{"vid":1}
,"vlan":{"<1-4094>":1}
,"<1-4094>":{"mpid":1}
,"host":{"mep":1}
,"<1-8191>":{"duration":1}
,"duration":{"duration":1,"seconds":1}
,"seconds":{"<5-60>":1}
,"<5-60>":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"pointer":1}
,"pointer":{"cfm_1dm_rx":1}
,"structure":{"function":1}
,"succeeds":{"null":1}
,"null":{"function":1}
}
;Search.control.loadWordPairs(pairs);
