var pairs =
{
"validation":{"sw1":1}
,"sw1":{"show":1}
,"show":{"evb-bridge":1,"evb":1}
,"evb-bridge":{"bridge":1}
,"bridge":{"parameters":1}
,"parameters":{"evb":1}
,"evb":{"admin":1,"interface":1}
,"admin":{"configuration":1}
,"configuration":{"acktimer":1}
,"acktimer":{"max_retry":1}
,"max_retry":{"resource":1}
,"resource":{"resource":1,"channel":1}
,"channel":{"svid":1}
,"svid":{"pool":1}
,"pool":{"tlv":1}
,"tlv":{"wait":1,"reflective":1}
,"wait":{"delay":1}
,"delay":{"keep":1}
,"keep":{"alive":1}
,"alive":{"cap":1}
,"cap":{"range":1}
,"range":{"mode":1}
,"mode":{"===========================================================================20":1,"relay":1}
,"===========================================================================20":{"167":1}
,"167":{"-4094":1}
,"-4094":{"manual":1}
,"manual":{"operational":1,"sw1":1,"enable":1}
,"operational":{"configuration":1}
,"interface":{"eth1":1}
,"eth1":{"interface":1,"admin":1}
,"reflective":{"cdcp":1}
,"cdcp":{"wait":1}
,"relay":{"================================================================================================20":1}
,"================================================================================================20":{"167":1}
,"enable":{"enable":1,"operational":1}
}
;Search.control.loadWordPairs(pairs);
