var pairs =
{
"neighbor":{"allow-ebgp-vpn":1,"vpn":1,"(a.b.c.d":1,"ipv4":1,"ipv6":1,"peer-group":1,"remote-as":1,"66.66.66.66":1}
,"allow-ebgp-vpn":{"command":1,"neighbor":1,"parameters":1,"(config-router-af)":1}
,"command":{"allow":1,"allows":1,"remove":1,"syntax":1,"command":1,"applies":1,"mode":1}
,"allow":{"ebgp":1}
,"ebgp":{"neighbor":1,"peer":1}
,"vpn":{"peer":1,"functionality":1,"connection":1}
,"peer":{"default":1,"parameter":1,"group":1,"groups":1}
,"default":{"bgp":1}
,"bgp":{"vpn":1,"neighbor":1,"200":1}
,"functionality":{"allowed":1}
,"allowed":{"ibgp":1}
,"ibgp":{"peers":1}
,"peers":{"using":1,"group":1}
,"using":{"neighbor":1}
,"allows":{"vpn":1}
,"connection":{"established":1}
,"established":{"ebgp":1}
,"parameter":{"command":1,"used":1}
,"remove":{"configuration":1}
,"configuration":{"command":1}
,"syntax":{"neighbor":1}
,"(a.b.c.d":{"x:x":1}
,"x:x":{":x:x":1}
,":x:x":{"word)":1,"address":1}
,"word)":{"allow-ebgp-vpn":1}
,"parameters":{"a.b.c.d":1}
,"a.b.c.d":{"address":1}
,"address":{"bgp":1,"family-vpnv4":1,"family-vpnv6":1}
,"ipv4":{"format":1}
,"format":{"x:x":1,"word":1}
,"ipv6":{"format":1}
,"word":{"name":1}
,"name":{"existing":1}
,"existing":{"peer":1}
,"group":{"information":1,"command":1}
,"information":{"create":1}
,"create":{"peer":1}
,"groups":{"refer":1}
,"refer":{"neighbor":1}
,"peer-group":{"neighbor":1}
,"remote-as":{"commands":1,"100":1}
,"commands":{"parameter":1}
,"used":{"command":1}
,"applies":{"peers":1}
,"mode":{"address":1,"examples":1}
,"family-vpnv4":{"mode":1}
,"family-vpnv6":{"mode":1}
,"examples":{"(config)":1}
,"(config)":{"router":1}
,"router":{"bgp":1}
,"200":{"(config-router)":1}
,"(config-router)":{"neighbor":1,"address-family":1}
,"66.66.66.66":{"remote-as":1,"update-source":1,"allow-ebgp-vpn":1,"activate":1}
,"100":{"(config-router)":1}
,"update-source":{"(config-router)":1}
,"address-family":{"vpnv4":1}
,"vpnv4":{"unicast":1}
,"unicast":{"(config-router-af)":1}
,"(config-router-af)":{"neighbor":1,"exit-address-family":1}
,"activate":{"(config-router-af)":1}
}
;Search.control.loadWordPairs(pairs);
