var pairs =
{
"show":{"bgp":1}
,"bgp":{"quote-regexp":1,"(ipv4":1,"ipv4":1}
,"quote-regexp":{"command":1,"word":1,"ipi":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"route":1}
,"route":{"matching":1,"information":1}
,"matching":{"path":1}
,"path":{"quoted":1}
,"quoted":{"regular":1}
,"regular":{"expression":1}
,"expression":{"command":1,"match":1,"ipv4":1}
,"syntax":{"show":1}
,"word":{"show":1,"parameters":1,"regular":1}
,"(ipv4":{"ipv6)":1}
,"ipv6)":{"(unicast":1}
,"(unicast":{"multicast":1,"multicast)":1}
,"multicast":{"quote-regexp":1,"multicast":1,"prefixes":1}
,"ipv4":{"(unicast":1,"ipv4":1,"route":1}
,"multicast)":{"quote-regexp":1}
,"parameters":{"word":1}
,"match":{"paths":1}
,"paths":{"quotes":1}
,"quotes":{"enclose":1}
,"enclose":{"regular":1}
,"information":{"ipv6":1,"unicast":1}
,"ipv6":{"ipv6":1,"route":1}
,"unicast":{"unicast":1,"prefixes":1}
,"prefixes":{"multicast":1,"command":1}
,"mode":{"privileged":1,"exec":1,"example":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"example":{"show":1}
}
;Search.control.loadWordPairs(pairs);
