var pairs =
{
"mcc":{"command":1,"(unicast":1,"frames":1,"unicast":1,"multicast":1}
,"command":{"enable":1,"syntax":1,"mode":1}
,"enable":{"transmission":1}
,"transmission":{"maintenance":1}
,"maintenance":{"communication":1,"entity":1}
,"communication":{"channel":1}
,"channel":{"(mcc)":1}
,"(mcc)":{"frames":1}
,"frames":{"host":1,"rmepid":1,"multicast":1,"command":1}
,"host":{"mep":1}
,"mep":{"specified":1,"unicast":1,"configuration":1}
,"specified":{"unicast":1}
,"unicast":{"address":1,"specify":1,"mcc":1,"frames":1,"rmepid":1}
,"address":{"default":1,"maintenance":1}
,"default":{"multicast":1}
,"multicast":{"address":1,"specify":1,"mcc":1}
,"entity":{"group":1}
,"group":{"(meg)":1}
,"(meg)":{"level":1}
,"level":{"command":1}
,"syntax":{"mcc":1}
,"(unicast":{"rmepid":1}
,"rmepid":{"rmepid":1,"multicast)":1,"specify":1,"(config-cfm-mep)":1}
,"multicast)":{"parameters":1}
,"parameters":{"unicast":1}
,"specify":{"send":1,"integer":1}
,"send":{"unicast":1,"multicast":1}
,"integer":{"identifies":1}
,"identifies":{"remote":1}
,"remote":{"mep":1}
,"mode":{"ethernet":1,"example":1}
,"ethernet":{"cfm":1}
,"cfm":{"mep":1}
,"configuration":{"mode":1}
,"example":{"(config-cfm-mep)":1}
,"(config-cfm-mep)":{"mcc":1}
}
;Search.control.loadWordPairs(pairs);
