var pairs =
{
"max-concurrent-dd":{"command":1,"<1-65535>":1,"parameters":1,"value":1}
,"command":{"limit":1,"useful":1,"limits":1,"remove":1,"syntax":1,"mode":1}
,"limit":{"number":1,"command":1}
,"number":{"database":1,"exchanges":1,"processes":1}
,"database":{"descriptors":1}
,"descriptors":{"(dd)":1}
,"(dd)":{"processed":1}
,"processed":{"concurrently":1}
,"concurrently":{"command":1,"per":1}
,"useful":{"router\u0027s":1}
,"router\u0027s":{"performance":1}
,"performance":{"affected":1}
,"affected":{"simultaneously":1}
,"simultaneously":{"bringing":1}
,"bringing":{"several":1}
,"several":{"ospf":1}
,"ospf":{"adjacencies":1,"instance":1,"100":1}
,"adjacencies":{"command":1,"option":1}
,"limits":{"maximum":1}
,"maximum":{"number":1}
,"exchanges":{"occur":1}
,"occur":{"concurrently":1}
,"per":{"ospf":1}
,"instance":{"thus":1}
,"thus":{"allowing":1}
,"allowing":{"adjacencies":1}
,"option":{"command":1}
,"remove":{"limit":1}
,"syntax":{"max-concurrent-dd":1}
,"<1-65535>":{"max-concurrent-dd":1,"specify":1}
,"parameters":{"<1-65535>":1}
,"specify":{"number":1}
,"processes":{"command":1}
,"mode":{"router":1,"examples":1}
,"router":{"mode":1,"ospf":1}
,"examples":{"following":1}
,"following":{"example":1}
,"example":{"max-concurrent-dd":1}
,"value":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"100":{"(config-router)":1}
,"(config-router)":{"max-concurrent-dd":1}
}
;Search.control.loadWordPairs(pairs);
