var pairs =
{
"nsm_vlan_delete_provider_port":{"function":1,"(struct":1}
,"function":{"deletes":1,"succeeds":1,"fails":1}
,"deletes":{"vlan":1}
,"vlan":{"provider":1,"configured":1,"port":1}
,"provider":{"port":1}
,"port":{"syntax":1,"mode":1,"sub":1}
,"syntax":{"int":1}
,"int":{"nsm_vlan_delete_provider_port":1}
,"(struct":{"interface":1}
,"interface":{"*ifp":1,"pointer":1,"found":1}
,"*ifp":{"nsm_vid_t":1}
,"nsm_vid_t":{"vid":1}
,"vid":{"enum":1,"vlan":1}
,"enum":{"nsm_vlan_port_mode":1}
,"nsm_vlan_port_mode":{"mode":1,"sub_mode":1}
,"mode":{"enum":1,"vlan":1,"(ce":1,"applicable":1}
,"sub_mode":{"bool_t":1,"vlan":1}
,"bool_t":{"iterate_members":1,"notify_kernel)":1}
,"iterate_members":{"bool_t":1,"=pal_true":1}
,"notify_kernel)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"none":1}
,"ifp":{"interface":1}
,"pointer":{"vid":1}
,"configured":{"mode":1}
,"(ce":{"provider-network":1}
,"provider-network":{"trunk":1}
,"trunk":{"access":1,"hybrid)":1}
,"access":{"hybrid)":1}
,"hybrid)":{"sub_mode":1,"iterate_members":1}
,"sub":{"mode":1}
,"applicable":{"ports":1}
,"ports":{"bridge":1}
,"bridge":{"(access":1}
,"(access":{"trunk":1}
,"=pal_true":{"command":1}
,"command":{"given":1}
,"given":{"aggregator":1}
,"aggregator":{"notify_kernel":1}
,"notify_kernel":{"true":1}
,"true":{"hal":1}
,"hal":{"call":1}
,"call":{"called":1}
,"called":{"configuration":1}
,"configuration":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"function":1}
,"succeeds":{"negative":1}
,"negative":{"value":1}
,"value":{"(error)":1}
,"(error)":{"function":1}
,"fails":{"nsm_vlan_err_cvlan_port_reg_exist":1}
,"nsm_vlan_err_cvlan_port_reg_exist":{"nsm_vlan_err_ifp_not_bound":1}
,"nsm_vlan_err_ifp_not_bound":{"nsm":1}
,"nsm":{"local":1}
,"local":{"interface":1}
,"found":{"nsm_vlan_err_vlan_not_in_port":1}
,"nsm_vlan_err_vlan_not_in_port":{"nsm_vlan_err_invalid_mode":1}
,"nsm_vlan_err_invalid_mode":{"nsm_vlan_err_native_vid":1}
}
;Search.control.loadWordPairs(pairs);
