var pairs =
{
"hal_ipv4_mc_vif_addr_add":{"function":1,"(unsigned":1}
,"function":{"adds":1,"fails":1,"succeeds":1}
,"adds":{"address":1}
,"address":{"configured":1,"add":1}
,"configured":{"vif":1}
,"vif":{"syntax":1,"index":1}
,"syntax":{"int":1}
,"int":{"hal_ipv4_mc_vif_addr_add":1,"index":1}
,"(unsigned":{"int":1}
,"index":{"struct":1,"vif":1,"addr":1}
,"struct":{"hal_in4_addr":1}
,"hal_in4_addr":{"*addr":1,"*subnet":1,"*broadcast":1,"*peer)":1}
,"*addr":{"struct":1}
,"*subnet":{"struct":1}
,"*broadcast":{"struct":1}
,"*peer)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"index":1,"none":1}
,"addr":{"address":1}
,"add":{"subnet":1,"broadcast":1,"peer":1,"output":1}
,"subnet":{"subnet":1,"address":1}
,"broadcast":{"broadcast":1,"address":1}
,"peer":{"peer":1,"address":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"hal_ipv4_mc_vif_notexists":1}
,"hal_ipv4_mc_vif_notexists":{"function":1}
,"fails":{"hal_success":1}
,"hal_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
