var pairs =
{
"lldp_master":{"structure":1,"{struct":1}
,"structure":{"onmd\u002Flldp\u002Flldpd.h":1}
,"onmd\u002Flldp\u002Flldpd.h":{"defines":1}
,"defines":{"link":1}
,"link":{"layer":1}
,"layer":{"discover":1}
,"discover":{"protocol":1}
,"protocol":{"master":1}
,"master":{"member":1,"sockfd":1}
,"member":{"name":1}
,"name":{"description":1,"sys_descr":1}
,"description":{"onm":1,"lldp_stats_rem_last_change_time":1}
,"onm":{"omnd":1}
,"omnd":{"master":1}
,"sockfd":{"socket":1,"struct":1}
,"socket":{"lldp_if_list":1}
,"lldp_if_list":{"lldp":1}
,"lldp":{"interface":1,"receive":1,"port":1,"destination":1,"management":1}
,"interface":{"list":1,"count":1}
,"list":{"lldp_rcv_thread":1,"*lldp_if_list":1}
,"lldp_rcv_thread":{"lldp":1}
,"receive":{"thread":1}
,"thread":{"if_cnt":1,"*lldp_rcv_thread":1}
,"if_cnt":{"interface":1,"u_int16_t":1}
,"count":{"syscap":1}
,"syscap":{"system":1,"u_int16_t":1}
,"system":{"capability":1,"name":1,"description":1}
,"capability":{"sys_cap_enabled":1,"lldp_stats_rem_drops":1}
,"sys_cap_enabled":{"enabled":1}
,"enabled":{"system":1}
,"lldp_stats_rem_drops":{"lldp":1}
,"port":{"statistics":1}
,"statistics":{"frame":1,"last":1}
,"frame":{"drops":1,"inserts":1,"deletes":1}
,"drops":{"lldp_stats_rem_inserts":1}
,"lldp_stats_rem_inserts":{"lldp":1}
,"inserts":{"lldp_stats_rem_deletes":1}
,"lldp_stats_rem_deletes":{"lldp":1}
,"deletes":{"sys_name":1}
,"sys_name":{"system":1,"[lldp_name_max_size":1}
,"sys_descr":{"system":1,"[lldp_descr_max_size":1}
,"lldp_stats_rem_last_change_time":{"llpd":1,"u_int32_t":1}
,"llpd":{"statistics":1}
,"last":{"change":1}
,"change":{"time":1}
,"time":{"lldp_dest_addr":1}
,"lldp_dest_addr":{"lldp":1}
,"destination":{"address":1}
,"address":{"mgmt_addr":1,"conf_flag":1}
,"mgmt_addr":{"lldp":1,"\u002F*counters":1}
,"management":{"address":1}
,"conf_flag":{"configuration":1}
,"configuration":{"flag":1}
,"flag":{"struct":1}
,"struct":{"lldp_master":1,"thread":1,"pal_in4_addr":1}
,"{struct":{"onmd_master":1}
,"onmd_master":{"*onm":1}
,"*onm":{"pal_sock_handle_t":1}
,"pal_sock_handle_t":{"sockfd":1}
,"*lldp_rcv_thread":{"\u002F*todo":1}
,"\u002F*todo":{"-should":1}
,"-should":{"moved":1}
,"moved":{"tree":1}
,"tree":{"*\u002Fstruct":1}
,"*\u002Fstruct":{"list":1}
,"*lldp_if_list":{"u_int16_t":1}
,"u_int16_t":{"if_cnt":1,"syscap":1,"syscap_enabled":1}
,"syscap_enabled":{"u_char":1}
,"u_char":{"sys_name":1,"sys_descr":1}
,"[lldp_name_max_size":{"u_char":1}
,"[lldp_descr_max_size":{"struct":1}
,"pal_in4_addr":{"mgmt_addr":1}
,"\u002F*counters":{"*\u002Fpal_time_t":1}
,"*\u002Fpal_time_t":{"lldp_stats_rem_last_change_time":1}
,"u_int32_t":{"lldp_stats_rem_tables_inserts":1,"lldp_stats_rem_tables_deletes":1,"lldp_stats_rem_tables_drops":1,"lldp_state_rem_tables_ageouts":1}
,"lldp_stats_rem_tables_inserts":{"u_int32_t":1}
,"lldp_stats_rem_tables_deletes":{"u_int32_t":1}
,"lldp_stats_rem_tables_drops":{"u_int32_t":1}
,"lldp_state_rem_tables_ageouts":{"define":1}
,"define":{"lldp_conf_mgmt_ip_address":1}
,"lldp_conf_mgmt_ip_address":{"<<0)":1}
,"<<0)":{"u_int8_t":1}
,"u_int8_t":{"conf_flag":1}
}
;Search.control.loadWordPairs(pairs);
