var pairs =
{
"g8032":{"rpl":1,"ring":1,"configure":1}
,"rpl":{"command":1,"(owner":1,"non-owner":1,"owner":1,"none":1,"port":1,"west-interface":1}
,"command":{"g8032":1,"syntax":1,"mode":1}
,"ring":{"protection":1,"node":1,"interface":1}
,"protection":{"link":1}
,"link":{"(rpl)":1}
,"(rpl)":{"command":1}
,"syntax":{"g8032":1}
,"(owner":{"non-owner)":1}
,"non-owner)":{"(east-interface":1}
,"(east-interface":{"west-interface)":1}
,"west-interface)":{"g8032":1}
,"non-owner":{"none":1,"designates":1}
,"none":{"parameters":1,"designates":1}
,"parameters":{"owner":1}
,"owner":{"designates":1,"non-owner":1,"east-interface":1}
,"designates":{"ring":1}
,"node":{"rpl":1,"owning":1}
,"owning":{"rpl":1}
,"port":{"defined":1}
,"defined":{"east-interface":1}
,"east-interface":{"specify":1,"(config)":1}
,"specify":{"east":1,"west":1}
,"east":{"ring":1}
,"interface":{"rpl":1}
,"west-interface":{"specify":1}
,"west":{"ring":1}
,"mode":{"g8032":1,"examples":1}
,"configure":{"switching":1,"terminal":1}
,"switching":{"mode":1,"ring-id":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"g8032":1}
,"ring-id":{"bridge":1}
,"bridge":{"(g8032-config-switching)":1}
,"(g8032-config-switching)":{"g8032":1,"exit":1}
,"exit":{"configure":1}
}
;Search.control.loadWordPairs(pairs);
