var pairs =
{
"ipi_mpls_ilm6_entry_add":{"function":1,"(u_char":1}
,"function":{"adds":1,"used":1}
,"adds":{"specified":1,"entry":1}
,"specified":{"ipv6":1}
,"ipv6":{"ilm":1}
,"ilm":{"entry":1,"table":1}
,"entry":{"ilm":1,"already":1,"requires":1,"function":1,"syntax":1,"fec_prefixlen":1,"pop":1,"owner":1,"status":1,"fails":1}
,"table":{"entry":1,"warning":1}
,"already":{"exists":1}
,"exists":{"ilm":1}
,"warning":{"logged":1}
,"logged":{"request":1}
,"request":{"ignored":1}
,"ignored":{"addition":1}
,"addition":{"ipv6":1}
,"requires":{"specification":1}
,"specification":{"protocol":1}
,"protocol":{"adding":1,"u_int32_t":1,"protocol":1,"owns":1,"module":1}
,"adding":{"operational":1}
,"operational":{"code":1}
,"code":{"mpls":1,"applied":1}
,"mpls":{"forwarder":1}
,"forwarder":{"treating":1}
,"treating":{"packet":1}
,"packet":{"pertaining":1}
,"pertaining":{"ipv6":1}
,"used":{"modify":1,"label_id_out":1,"if_in":1,"fec":1}
,"modify":{"existing":1}
,"existing":{"ipv6":1}
,"syntax":{"int":1}
,"int":{"ipi_mpls_ilm6_entry_add":1}
,"(u_char":{"protocol":1}
,"u_int32_t":{"*label_id_in":1,"*label_id_out":1,"*tunnel_label":1,"*qos_resource_id":1,"nhlfe_ix":1,"vpn_id":1}
,"*label_id_in":{"u_int32_t":1}
,"*label_id_out":{"struct":1}
,"struct":{"if_ident":1,"pal_in6_addr":1,"mpls_nh_fwd":1,"ds_info_fwd":1,"mpls_owner_fwd":1}
,"if_ident":{"*if_in":1,"*if_out":1}
,"*if_in":{"struct":1}
,"*if_out":{"struct":1}
,"pal_in6_addr":{"*fec_addr":1,"*vc_peer)":1}
,"*fec_addr":{"u_char":1}
,"u_char":{"*fec_prefixlen":1,"is_egress":1}
,"*fec_prefixlen":{"struct":1}
,"mpls_nh_fwd":{"*nexthop_addr":1}
,"*nexthop_addr":{"u_char":1}
,"is_egress":{"defined":1,"flag":1}
,"defined":{"(have_gmpls)":1,"(have_packet))":1}
,"(have_gmpls)":{"defined":1}
,"(have_packet))":{"ifdef":1}
,"ifdef":{"have_diffserv":1}
,"have_diffserv":{"struct":1}
,"ds_info_fwd":{"*ds_info":1}
,"*ds_info":{"endif":1}
,"endif":{"\u002F*have_diffserv":1,"\u002F*!":1}
,"\u002F*have_diffserv":{"*\u002F#":1}
,"*\u002F#":{"endif":1}
,"\u002F*!":{"have_gmpls":1}
,"have_gmpls":{"have_packet":1}
,"have_packet":{"*\u002Fchar":1}
,"*\u002Fchar":{"opcode":1}
,"opcode":{"u_int32_t":1,"operational":1}
,"*tunnel_label":{"u_int32_t":1}
,"*qos_resource_id":{"u_int32_t":1,"qos":1}
,"nhlfe_ix":{"struct":1,"nhlfe":1}
,"mpls_owner_fwd":{"*owner":1}
,"*owner":{"u_int32_t":1}
,"vpn_id":{"struct":1,"vpn":1}
,"*vc_peer)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"protocol":1,"data":1,"contains":1}
,"owns":{"entries":1}
,"entries":{"ipi_proto_nsm":1}
,"ipi_proto_nsm":{"ipi_proto_ldp":1}
,"ipi_proto_ldp":{"ipi_proto_bgp":1}
,"ipi_proto_bgp":{"ipi_proto_rsvp":1}
,"ipi_proto_rsvp":{"label_id_in":1}
,"label_id_in":{"incoming":1}
,"incoming":{"label":1,"interface":1}
,"label":{"low-order":1,"tunnel":1}
,"low-order":{"bits":1}
,"bits":{"used":1}
,"label_id_out":{"outgoing":1}
,"outgoing":{"label":1,"interface":1}
,"if_in":{"identifying":1}
,"identifying":{"object":1}
,"object":{"incoming":1,"outgoing":1}
,"interface":{"if_out":1,"fec_addr":1}
,"if_out":{"identifying":1}
,"fec_addr":{"address":1}
,"address":{"fec":1,"next-hop":1,"virtual":1}
,"fec":{"corresponding":1,"nexthop_addr":1,"is_egress":1,"ds_info":1}
,"corresponding":{"ipv6":1}
,"fec_prefixlen":{"length":1}
,"length":{"prefix":1}
,"prefix":{"fec":1}
,"nexthop_addr":{"address":1}
,"next-hop":{"used":1}
,"flag":{"identify":1}
,"identify":{"whether":1}
,"whether":{"lsr":1}
,"lsr":{"egress":1}
,"egress":{"fec":1}
,"ds_info":{"diffserv":1}
,"diffserv":{"related":1,"compilation":1}
,"related":{"lsp":1}
,"lsp":{"information":1}
,"information":{"parameter":1,"specific":1}
,"parameter":{"available":1}
,"available":{"diffserv":1}
,"compilation":{"option":1}
,"option":{"enabled":1}
,"enabled":{"opcode":1}
,"applied":{"ipv6":1}
,"pop":{"swap":1}
,"swap":{"pop_for_vpn":1}
,"pop_for_vpn":{"tunnel_label":1}
,"tunnel_label":{"outgoing":1}
,"tunnel":{"*qos_resource_id":1}
,"qos":{"resource":1}
,"resource":{"identifier":1}
,"identifier":{"nhlfe_ix":1}
,"nhlfe":{"index":1}
,"index":{"ilm":1}
,"owner":{"information":1}
,"specific":{"signalling":1}
,"signalling":{"protocol":1}
,"module":{"vpn_id":1}
,"vpn":{"vc_peer":1}
,"vc_peer":{"address":1}
,"virtual":{"circuit":1}
,"circuit":{"peer":1}
,"peer":{"output":1}
,"output":{"parameters":1}
,"data":{"returned":1,"call":1}
,"returned":{"call":1}
,"call":{"return":1,"returns":1,"parameters":1,"ipv6":1}
,"return":{"value":1}
,"value":{"call":1}
,"returns":{"successfully":1}
,"successfully":{"adds":1}
,"status":{"call":1}
,"contains":{"null":1}
,"null":{"data":1}
}
;Search.control.loadWordPairs(pairs);
