var pairs =
{
"show":{"mpls":1}
,"mpls":{"command":1,"data":1,"parameters":1,"commands":1,"minimum":1,"differentiated":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"mpls":1}
,"data":{"command":1,"class":1}
,"syntax":{"show":1}
,"parameters":{"none":1}
,"none":{"command":1,"custom":1,"log":1,"admin":1,"packets":1}
,"mode":{"exec":1,"privileged":1,"examples":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"examples":{"following":1}
,"following":{"subsection":1}
,"subsection":{"displays":1}
,"displays":{"variety":1}
,"variety":{"show":1}
,"commands":{"show":1}
,"minimum":{"label":1}
,"label":{"configured":1,"maximum":1,"1048575":1,"556":1}
,"configured":{"maximum":1,"1048575":1,"none":1}
,"maximum":{"label":1}
,"1048575":{"per":1,"label-space":1,"custom":1}
,"per":{"label-space":1}
,"label-space":{"information":1,"using":1,"2342":1}
,"information":{"label-space":1}
,"using":{"minimum":1}
,"2342":{"using":1}
,"556":{"maximum":1}
,"custom":{"ingress":1,"egress":1}
,"ingress":{"ttl":1}
,"ttl":{"configured":1}
,"egress":{"ttl":1}
,"log":{"message":1}
,"message":{"detail":1}
,"detail":{"none":1}
,"admin":{"group":1}
,"group":{"detail":1}
,"packets":{"dropped":1}
,"dropped":{"ip:115167":1,"mpls:0":1}
,"ip:115167":{"dropped":1}
,"mpls:0":{"sent":1}
,"sent":{"ip:490943":1}
,"ip:490943":{"labeled:0":1}
,"labeled:0":{"switch":1}
,"switch":{"d:0":1}
,"d:0":{"mpls":1}
,"differentiated":{"services":1}
,"services":{"supported":1,"class":1}
,"supported":{"classes":1}
,"classes":{"data":1}
,"class":{"dscp_value":1,"exp":1}
,"dscp_value":{"000000":1,"exp_value":1}
,"000000":{"mpls":1}
,"exp":{"mapping":1}
,"mapping":{"data":1}
,"exp_value":{"000000":1}
}
;Search.control.loadWordPairs(pairs);
