var pairs =
{
"command":{"api":1,"reference":1}
,"api":{"functions":1}
,"functions":{"section":1}
,"section":{"called":1}
,"called":{"commands":1}
,"commands":{"carrier":1}
,"carrier":{"ethernet":1}
,"ethernet":{"command":1}
,"reference":{"function":1}
,"function":{"description":1}
,"description":{"nsm_bridge_api_port_proto_process":1}
,"nsm_bridge_api_port_proto_process":{"configures":1}
,"configures":{"protocol":1}
,"protocol":{"handling":1}
,"handling":{"customer":1}
,"customer":{"edge\u002Fcustomer":1}
,"edge\u002Fcustomer":{"network":1}
,"network":{"port":1}
,"port":{"nsm_bridge_uni_set_name":1}
,"nsm_bridge_uni_set_name":{"deletes":1}
,"deletes":{"name":1}
,"name":{"uni":1}
,"uni":{"nsm_bridge_uni_type_detect":1,"type":1}
,"nsm_bridge_uni_type_detect":{"enables":1}
,"enables":{"disables":1}
,"disables":{"uni":1}
,"type":{"mode":1}
,"mode":{"interface":1}
,"interface":{"nsm_bridge_uni_unset_name":1}
,"nsm_bridge_uni_unset_name":{"removes":1}
,"removes":{"name":1}
}
;Search.control.loadWordPairs(pairs);
