var pairs =
{
"trill_get_next_rbridgebase_nickname_status":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"status":1}
,"status":{"next":1,"nick-name":1}
,"next":{"nick-name":1}
,"nick-name":{"entry":1}
,"entry":{"syntax":1,"static":1}
,"syntax":{"int":1}
,"int":{"trill_get_next_rbridgebase_nickname_status":1,"index":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"integer":1}
,"u_int32_t":{"*instance":1,"*ret)":1}
,"*instance":{"u_int16_t":1}
,"u_int16_t":{"*nickname":1}
,"*nickname":{"int":1}
,"index":{"u_int32_t":1,"output":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"ret":1}
,"integer":{"contains":1}
,"contains":{"trill":1}
,"trill":{"identifier":1,"instance":1}
,"identifier":{"instance":1}
,"instance":{"integer":1,"nickname":1}
,"nickname":{"nickname":1,"rbridge":1,"trill_api_get_error":1,"found":1}
,"rbridge":{"indexlen":1}
,"indexlen":{"length":1}
,"length":{"index":1}
,"output":{"parameters":1}
,"ret":{"pointer":1}
,"pointer":{"status":1}
,"static":{"dynamic":1}
,"dynamic":{"invalid":1}
,"invalid":{"return":1}
,"return":{"value":1}
,"value":{"trill_api_get_success":1}
,"trill_api_get_success":{"valid":1}
,"valid":{"instance":1}
,"trill_api_get_error":{"valid":1}
}
;Search.control.loadWordPairs(pairs);
