var pairs =
{
"pal_kernel_ipv4_add":{"function":1,"(struct":1}
,"function":{"adds":1}
,"adds":{"new":1}
,"new":{"entry":1}
,"entry":{"kernel":1,"output":1}
,"kernel":{"ipv4":1}
,"ipv4":{"forwarding":1}
,"forwarding":{"table":1}
,"table":{"api":1}
,"api":{"call":1}
,"call":{"result_t":1}
,"result_t":{"pal_kernel_ipv4_add":1}
,"(struct":{"prefix":1}
,"prefix":{"struct":1,"pointer":1}
,"struct":{"rib":1}
,"rib":{"*r)":1,"entry":1}
,"*r)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"pointer":1,"none":1}
,"pointer":{"prefix":1,"rib":1}
,"output":{"parameters":1}
,"none":{"result":1}
,"result":{"value":1}
,"value":{"platform":1}
,"platform":{"dependent":1}
}
;Search.control.loadWordPairs(pairs);
