var pairs =
{
"validation":{"validate":1}
,"validate":{"rtr1":1}
,"rtr1":{"show":1}
,"show":{"vrrp":1}
,"vrrp":{"eth1":1,"version":1,"interface":1}
,"eth1":{"vrrp":1,"state":1,"joined":1}
,"version":{"vmac":1}
,"vmac":{"enabled":1}
,"enabled":{"backward":1}
,"backward":{"compatibility":1}
,"compatibility":{"disabled":1}
,"disabled":{"address":1}
,"address":{"family":1,"2.2.2.1":1}
,"family":{"ipv4":1}
,"ipv4":{"vrrp":1,"interface":1}
,"interface":{"eth1":1}
,"state":{"adminup":1}
,"adminup":{"-master":1,"-backup":1}
,"-master":{"virtual":1}
,"virtual":{"address":1}
,"2.2.2.1":{"(owner)":1,"(not-owner)":1}
,"(owner)":{"priority":1}
,"priority":{"255":1,"advertisement":1}
,"255":{"advertisement":1}
,"advertisement":{"interval":1}
,"interval":{"3000":1,"300":1,"2059":1}
,"3000":{"centi":1}
,"centi":{"sec":1}
,"sec":{"master":1,"skew":1,"accept":1}
,"master":{"advertisement":1}
,"skew":{"time":1}
,"time":{"centi":1,"1415":1}
,"accept":{"mode":1}
,"mode":{"false":1,"true":1}
,"false":{"preempt":1}
,"preempt":{"mode":1}
,"true":{"multicast":1}
,"multicast":{"membership":1}
,"membership":{"ipv4":1}
,"joined":{"rtr2":1}
,"rtr2":{"show":1}
,"-backup":{"virtual":1}
,"(not-owner)":{"priority":1}
,"300":{"centi":1}
,"2059":{"centi":1}
,"1415":{"centi":1}
}
;Search.control.loadWordPairs(pairs);
