var pairs =
{
"area-password":{"command":1,"word":1,"parameters":1,"ipi":1,"mypasswd":1}
,"command":{"authentication":1,"enables":1,"clear":1,"syntax":1,"mode":1}
,"authentication":{"password":1,"level-1":1,"receiving":1}
,"password":{"level-1":1,"isis":1,"command":1,"string":1,"snp":1,"snps":1,"configured":1}
,"level-1":{"area":1,"snp":1,"areas":1}
,"area":{"authentication":1,"password":1,"parameter":1}
,"snp":{"pdus":1,"pdu":1,"(send-only":1,"specify":1,"send-only":1}
,"pdus":{"command":1,"snp":1,"check":1,"receives":1}
,"enables":{"authentication":1}
,"receiving":{"sending":1}
,"sending":{"lsp":1}
,"lsp":{"snp":1}
,"pdu":{"level-1":1,"(snp)":1}
,"areas":{"area":1}
,"isis":{"routers":1,"(config-router)":1}
,"routers":{"area":1}
,"parameter":{"command":1}
,"clear":{"area":1}
,"syntax":{"area-password":1}
,"word":{"area-password":1,"authenticate":1,"specify":1}
,"authenticate":{"snp":1,"specify":1}
,"(send-only":{"validate)":1}
,"validate)":{"area-password":1}
,"parameters":{"word":1}
,"specify":{"password":1,"insert":1,"sequence":1}
,"string":{"authenticate":1}
,"insert":{"password":1}
,"sequence":{"number":1}
,"number":{"pdu":1}
,"(snp)":{"send-only":1}
,"send-only":{"specify":1,"(config)":1}
,"check":{"password":1}
,"receives":{"keyword":1,"default":1}
,"keyword":{"during":1}
,"during":{"software":1}
,"software":{"upgrade":1}
,"upgrade":{"ease":1}
,"ease":{"transition":1}
,"transition":{"validate":1}
,"validate":{"specify":1}
,"snps":{"receives":1}
,"default":{"default":1,"area":1}
,"configured":{"command":1}
,"mode":{"router":1,"examples":1}
,"router":{"mode":1,"isis":1}
,"examples":{"(config)":1}
,"(config)":{"router":1}
,"(config-router)":{"area-password":1}
,"ipi":{"(config-router)":1,"authenticate":1}
,"mypasswd":{"(config)":1}
}
;Search.control.loadWordPairs(pairs);
