var pairs =
{
"handling":{"inter-as":1}
,"inter-as":{"provider":1,"methods":1,"method":1}
,"provider":{"autonomous":1}
,"autonomous":{"system":1}
,"system":{"border":1}
,"border":{"router":1}
,"router":{"(asbr)":1,"preserves":1}
,"(asbr)":{"comply":1}
,"comply":{"bgp":1}
,"bgp":{"graceful":1,"routes":1}
,"graceful":{"restart":1}
,"restart":{"labeled":1,"logic":1,"mechanism":1}
,"labeled":{"ipv4":1}
,"ipv4":{"route":1,"routes":1}
,"route":{"continue":1}
,"continue":{"forwarding":1}
,"forwarding":{"external":1}
,"external":{"bgp":1}
,"routes":{"upon":1,"updates":1}
,"upon":{"control-plane":1}
,"control-plane":{"switchover":1}
,"switchover":{"preserve":1}
,"preserve":{"incoming":1,"labeled":1}
,"incoming":{"outgoing":1}
,"outgoing":{"labels":1}
,"labels":{"depending":1,"mp-ibgp":1,"asbr1":1,"swapped":1,"restart":1}
,"depending":{"options":1}
,"options":{"used":1}
,"used":{"inter-as":1}
,"methods":{"restarting":1}
,"restarting":{"router":1}
,"preserves":{"ilm":1}
,"ilm":{"ftn":1,"table":1}
,"ftn":{"tables":1}
,"tables":{"change":1}
,"change":{"during":1}
,"during":{"asbr":1}
,"asbr":{"restart":1,"down":1}
,"logic":{"detailed":1}
,"detailed":{"previous":1}
,"previous":{"sections":1}
,"sections":{"following":1}
,"following":{"figure":1}
,"figure":{"depicts":1}
,"depicts":{"inter-as":1}
,"method":{"asbr\u2019s":1}
,"asbr\u2019s":{"ilm":1}
,"table":{"contain":1}
,"contain":{"incoming":1}
,"mp-ibgp":{"mp-ebgp":1,"pe1----------------------------asbr1---------------------asbr2--------------------pe2":1,"within":1}
,"mp-ebgp":{"mp-ibgp":1,"two":1}
,"pe1----------------------------asbr1---------------------asbr2--------------------pe2":{"case":1}
,"case":{"asbr1":1}
,"asbr1":{"asbr2":1}
,"asbr2":{"act":1,"vpn":1}
,"act":{"lsrs":1}
,"lsrs":{"preserve":1}
,"vpn":{"labels":1,"information":1}
,"swapped":{"vpn":1}
,"information":{"transferred":1}
,"transferred":{"mp-ibgp":1}
,"within":{"single-hop":1}
,"single-hop":{"mp-ebgp":1}
,"two":{"asbrs":1}
,"asbrs":{"asbr":1}
,"down":{"invokes":1}
,"invokes":{"graceful":1}
,"mechanism":{"preserve":1}
,"updates":{"labels":1}
}
;Search.control.loadWordPairs(pairs);
