var pairs =
{
"efm_oam_link_monitoring_enable_set":{"function":1,"(struct":1}
,"function":{"starts":1,"implements":1,"succeeds":1}
,"starts":{"stops":1}
,"stops":{"link-monitoring":1}
,"link-monitoring":{"support":1,"interface":1}
,"support":{"function":1}
,"implements":{"ethernet":1}
,"ethernet":{"oam":1}
,"oam":{"link-monitor":1}
,"link-monitor":{"command":1}
,"command":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"efm_oam_link_monitoring_enable_set":1}
,"(struct":{"interface":1}
,"interface":{"*ifp":1,"structure":1,"output":1,"null":1,"found":1}
,"*ifp":{"u_int8_t":1}
,"u_int8_t":{"enable)":1}
,"enable)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"none":1}
,"ifp":{"pointer":1}
,"pointer":{"interface":1}
,"structure":{"enable":1}
,"enable":{"whether":1}
,"whether":{"start":1}
,"start":{"stop":1}
,"stop":{"link-monitoring":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"efm_success":1}
,"efm_success":{"function":1}
,"succeeds":{"efm_failure":1}
,"efm_failure":{"interface":1}
,"null":{"efm_oam_err_if_not_found":1}
,"efm_oam_err_if_not_found":{"onmd":1}
,"onmd":{"interface":1}
,"found":{"efm_oam_err_internal":1}
,"efm_oam_err_internal":{"internal":1}
,"internal":{"error":1}
,"error":{"efm_oam_err_not_enabled":1}
,"efm_oam_err_not_enabled":{"efm":1}
,"efm":{"enabled":1}
,"enabled":{"interface":1}
}
;Search.control.loadWordPairs(pairs);
