var pairs =
{
"outbound":{"routing":1}
,"routing":{"filter":1,"peers":1,"updates":1}
,"filter":{"outbound":1,"(orf)":1}
,"(orf)":{"exchanges":1}
,"exchanges":{"filtering":1}
,"filtering":{"data":1}
,"data":{"among":1}
,"among":{"routing":1}
,"peers":{"peer":1}
,"peer":{"implements":1}
,"implements":{"behalf":1}
,"behalf":{"others":1}
,"others":{"block":1}
,"block":{"certain":1}
,"certain":{"routing":1}
,"updates":{"feature":1}
,"feature":{"advantageous":1}
,"advantageous":{"local":1}
,"local":{"bgp":1}
,"bgp":{"speakers":1}
,"speakers":{"consume":1,"less":1}
,"consume":{"less":1}
,"less":{"resources":1,"work":1,"link":1}
,"resources":{"less":1}
,"work":{"required":1}
,"required":{"remote":1,"provides":1}
,"remote":{"bgp":1}
,"link":{"bandwidth":1}
,"bandwidth":{"usage":1}
,"usage":{"required":1}
,"provides":{"ability":1}
,"ability":{"configure":1}
,"configure":{"neighboring":1}
,"neighboring":{"routers":1}
,"routers":{"central":1}
,"central":{"route":1}
,"route":{"reflector":1}
}
;Search.control.loadWordPairs(pairs);
