var pairs =
{
"trill_static_dtree_multicast_unset":{"function":1,"(struct":1}
,"function":{"resets":1,"call":1}
,"resets":{"(removes)":1}
,"(removes)":{"ingress":1}
,"ingress":{"dtree":1}
,"dtree":{"nickname":1,"called":1,"output":1}
,"nickname":{"fdb":1}
,"fdb":{"tree":1}
,"tree":{"longer":1}
,"longer":{"configured":1}
,"configured":{"originate":1}
,"originate":{"native":1}
,"native":{"multicast":1}
,"multicast":{"frames":1}
,"frames":{"dtree":1}
,"called":{"add":1}
,"add":{"static":1}
,"static":{"multicast-trill-fdb":1}
,"multicast-trill-fdb":{"ingress-d-tree":1}
,"ingress-d-tree":{"cli":1}
,"cli":{"command":1,"*cli":1,"structure":1}
,"command":{"contained":1}
,"contained":{"trill_api.c":1}
,"trill_api.c":{"file":1}
,"file":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"trill_static_dtree_multicast_unset":1}
,"(struct":{"cli":1}
,"*cli":{"u_int16_t":1,"specifies":1}
,"u_int16_t":{"dtree_nck)":1}
,"dtree_nck)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"*cli":1,"none":1}
,"specifies":{"instance":1,"name":1}
,"instance":{"cli":1}
,"structure":{"values":1}
,"values":{"includes":1,"trill_api_set_success":1}
,"includes":{"1-31":1}
,"1-31":{"dtree_nck":1}
,"dtree_nck":{"specifies":1}
,"name":{"dtree":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"trill_api_set_success":{"indicates":1}
,"indicates":{"function":1,"specified":1,"nsm":1,"memory":1}
,"call":{"worked":1}
,"worked":{"properly":1}
,"properly":{"trill_api_set_err_noexist":1}
,"trill_api_set_err_noexist":{"indicates":1}
,"specified":{"entry":1}
,"entry":{"exist":1,"remove":1}
,"exist":{"entry":1}
,"remove":{"trill_api_set_err_nsm_send_failed":1}
,"trill_api_set_err_nsm_send_failed":{"indicates":1}
,"nsm":{"sent":1}
,"sent":{"trill_err_memory_alloc_failure":1}
,"trill_err_memory_alloc_failure":{"indicates":1}
,"memory":{"available":1}
}
;Search.control.loadWordPairs(pairs);
