var pairs =
{
"cfm_cc_unicast_disable":{"function":1,"(struct":1}
,"function":{"called":1,"succeeds":1}
,"called":{"ethernet":1}
,"ethernet":{"cfm":1}
,"cfm":{"unicast":1}
,"unicast":{"state":1,"continuity":1}
,"state":{"command":1}
,"command":{"option":1}
,"option":{"disable":1}
,"disable":{"used":1,"point-to-point":1}
,"used":{"disable":1}
,"point-to-point":{"unicast":1}
,"continuity":{"check":1}
,"check":{"messaging":1}
,"messaging":{"(ccm)":1}
,"(ccm)":{"host":1}
,"host":{"mep":1}
,"mep":{"remote":1,"syntax":1,"exists":1,"<1-8191>":1,"found":1}
,"remote":{"mep":1}
,"syntax":{"include":1}
,"include":{"cfm_api.h":1}
,"cfm_api.h":{"s_int32_t":1}
,"s_int32_t":{"cfm_cc_unicast_disable":1}
,"(struct":{"onmd_bridge":1}
,"onmd_bridge":{"*bridge":1}
,"*bridge":{"u_int8_t":1}
,"u_int8_t":{"*md_name":1}
,"*md_name":{"u_int16_t":1}
,"u_int16_t":{"vid":1}
,"vid":{"u_int32_t":1,"vlan":1}
,"u_int32_t":{"mpid":1,"rmpid":1}
,"mpid":{"u_int32_t":1,"host":1}
,"rmpid":{"struct":1,"remote":1}
,"struct":{"interface":1}
,"interface":{"*ifp)":1,"return":1,"index":1}
,"*ifp)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bridge":1}
,"bridge":{"bridge":1,"mep":1,"found":1,"port":1}
,"exists":{"md_name":1}
,"md_name":{"name":1}
,"name":{"vid":1}
,"vlan":{"<1-4094>":1}
,"<1-4094>":{"mpid":1}
,"<1-8191>":{"rmpid":1,"ifp":1}
,"ifp":{"pointer":1}
,"pointer":{"interface":1}
,"return":{"value":1}
,"value":{"cfm_bridge_not_found":1}
,"cfm_bridge_not_found":{"bridge":1}
,"found":{"list":1,"cfm_domain_not_found":1,"cfm_api_err_if_not_bound":1,"cfm_ma_not_found":1,"cfm_mep_not_found":1,"cfm_api_err_mep_not_found":1,"result_ok":1}
,"list":{"found":1}
,"cfm_domain_not_found":{"found":1}
,"cfm_api_err_if_not_bound":{"bridge":1}
,"port":{"found":1,"interface":1}
,"cfm_ma_not_found":{"found":1}
,"cfm_mep_not_found":{"mep":1}
,"cfm_api_err_mep_not_found":{"port":1}
,"index":{"valid":1}
,"valid":{"cfm_api_err_mep_ccm_not_enabled":1}
,"cfm_api_err_mep_ccm_not_enabled":{"ccm":1}
,"ccm":{"unicast-enabled":1}
,"unicast-enabled":{"cfm_rmep_not_found":1}
,"cfm_rmep_not_found":{"rmep":1}
,"rmep":{"found":1}
,"result_ok":{"function":1}
}
;Search.control.loadWordPairs(pairs);
