var pairs =
{
"mpls":{"admin-groups":1,"admin-group":1}
,"admin-groups":{"command":1}
,"command":{"create":1,"remove":1,"syntax":1,"mode":1}
,"create":{"name-to-value":1}
,"name-to-value":{"binding":1}
,"binding":{"administrative":1}
,"administrative":{"group":1,"groups":1}
,"group":{"administrative":1,"command":1,"<0-31>":1}
,"groups":{"configured":1}
,"configured":{"time":1}
,"time":{"parameter":1}
,"parameter":{"command":1}
,"remove":{"named":1}
,"named":{"administrative":1}
,"syntax":{"mpls":1}
,"admin-group":{"name":1,"mygroup":1}
,"name":{"<0-31>":1,"name":1,"administrative":1}
,"<0-31>":{"mpls":1,"parameters":1,"value":1}
,"parameters":{"name":1}
,"value":{"administrative":1}
,"mode":{"configure":1,"example":1}
,"configure":{"mode":1,"terminal":1}
,"example":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"mpls":1}
}
;Search.control.loadWordPairs(pairs);
