var pairs =
{
"dot3oamstatsentry":{"objects":1}
,"objects":{"group":1}
,"group":{"contain":1}
,"contain":{"counts":1}
,"counts":{"oam":1}
,"oam":{"pdus":1}
,"pdus":{"transmitted":1}
,"transmitted":{"received":1}
,"received":{"ethernet":1}
,"ethernet":{"interface":1}
,"interface":{"object":1}
,"object":{"type":1}
,"type":{"syntax":1}
,"syntax":{"access":1}
,"access":{"functions":1}
,"functions":{"dot3oaminformationtx":1}
,"dot3oaminformationtx":{"counter32":1}
,"counter32":{"read-only":1}
,"read-only":{"efm_oam_get_stats_group_attribs":1,"dot3oamuniqueeventnotification-tx":1,"dot3oamuniqueeventnotification-rx":1,"dot3oamduplicateevent-notificationtx":1,"dot3oamduplicateevent-notificationrx":1,"dot3oamloopbackcontroltx":1,"dot3oamloopbackcontrolrx":1,"dot3oamvariablerequesttx":1,"dot3oamvariablerequestrx":1,"dot3oamvariableresponsetx":1,"dot3oamvariableresponserx":1,"dot3oamorgspecifictx":1,"dot3oamorgspecificrx":1,"dot3oamunsupportedcodestx":1,"dot3oamunsupportedcodesrx":1,"dot3oamframeslostduetooam":1}
,"efm_oam_get_stats_group_attribs":{"dot3oaminformationrx":1}
,"dot3oaminformationrx":{"counter32":1}
,"dot3oamuniqueeventnotification-tx":{"counter32":1}
,"dot3oamuniqueeventnotification-rx":{"counter32":1}
,"dot3oamduplicateevent-notificationtx":{"counter32":1}
,"dot3oamduplicateevent-notificationrx":{"counter32":1}
,"dot3oamloopbackcontroltx":{"counter32":1}
,"dot3oamloopbackcontrolrx":{"counter32":1}
,"dot3oamvariablerequesttx":{"counter32":1}
,"dot3oamvariablerequestrx":{"counter32":1}
,"dot3oamvariableresponsetx":{"counter32":1}
,"dot3oamvariableresponserx":{"counter32":1}
,"dot3oamorgspecifictx":{"counter32":1}
,"dot3oamorgspecificrx":{"counter32":1}
,"dot3oamunsupportedcodestx":{"counter32":1}
,"dot3oamunsupportedcodesrx":{"counter32":1}
,"dot3oamframeslostduetooam":{"counter32":1}
}
;Search.control.loadWordPairs(pairs);
