var pairs =
{
"hal_mpls_vc_fib_delete":{"function":1,"(u_int32_t":1}
,"function":{"deletes":1,"fails":1}
,"deletes":{"fib":1}
,"fib":{"entry":1}
,"entry":{"(ftn\u002Film)":1}
,"(ftn\u002Film)":{"identifier":1}
,"identifier":{"match":1,"vc_style":1,"in_label":1}
,"match":{"delete":1}
,"delete":{"operation":1}
,"operation":{"fails":1}
,"fails":{"syntax":1,"none":1}
,"syntax":{"int":1}
,"int":{"hal_mpls_vc_fib_delete":1}
,"(u_int32_t":{"vc_id":1}
,"vc_id":{"u_int32_t":1,"identifier":1}
,"u_int32_t":{"vc_style":1,"vpls_id":1,"in_label":1,"nw_ifindex":1}
,"vc_style":{"u_int32_t":1,"type":1}
,"vpls_id":{"u_int32_t":1,"vpls":1}
,"in_label":{"u_int32_t":1,"incoming":1}
,"nw_ifindex":{"struct":1,"incoming":1}
,"struct":{"hal_in4_addr":1}
,"hal_in4_addr":{"*ftn_vc_peer)":1}
,"*ftn_vc_peer)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vc_id":1,"none":1}
,"type":{"(mesh":1}
,"(mesh":{"spoke)":1}
,"spoke)":{"vpls_id":1}
,"vpls":{"identifier":1}
,"incoming":{"label":1,"interface":1}
,"label":{"nw_ifindex":1,"ftn_vc_peer":1}
,"interface":{"index":1}
,"index":{"incoming":1}
,"ftn_vc_peer":{"address":1}
,"address":{"neighbor":1}
,"neighbor":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"hal_mpls_vpls_fib_delete_err":1}
,"hal_mpls_vpls_fib_delete_err":{"function":1}
}
;Search.control.loadWordPairs(pairs);
