var pairs =
{
"control":{"card":1}
,"card":{"oamd":1,"used":1,"nsm":1,"imish":1,"mplsonm":1}
,"oamd":{"control":1,"provides":1,"existing":1,"sends":1,"module":1}
,"provides":{"infrastructure":1,"flexibility":1,"commands":1}
,"infrastructure":{"configure":1}
,"configure":{"maintain":1,"manage":1}
,"maintain":{"ietf":1,"itu":1}
,"ietf":{"maintenance":1,"itu":1,"meg":1}
,"maintenance":{"entities":1,"transport":1}
,"entities":{"meg":1,"(meg":1,"existing":1}
,"meg":{"association":1,"table":1,"entries":1,"entry":1,"ietf":1,"\u002Fitu":1,"addition":1,"mep":1,"entities":1,"tables":1,"me\u002Fmep":1,"associated":1}
,"association":{"transport":1}
,"transport":{"paths":1,"path":1}
,"paths":{"helps":1,"whenever":1}
,"helps":{"maintain":1}
,"itu":{"maintenance":1,"meg":1}
,"(meg":{"mep":1}
,"mep":{"rmep)":1,"rmep":1}
,"rmep)":{"ietf":1}
,"existing":{"meg":1,"module":1}
,"table":{"control":1}
,"used":{"storing":1,"store":1}
,"storing":{"ietf":1}
,"entries":{"meg_type":1,"again":1}
,"meg_type":{"field":1}
,"field":{"meg":1}
,"entry":{"determine":1,"determines":1}
,"determine":{"whether":1}
,"whether":{"meg":1}
,"\u002Fitu":{"meg":1}
,"addition":{"control":1}
,"manage":{"oam":1}
,"oam":{"maintenance":1,"function":1,"functions":1,"request":1}
,"rmep":{"along":1,"mip":1}
,"along":{"association":1}
,"path":{"information":1,"technologies":1,"technology":1,"mpls-tp":1,"oamd":1}
,"information":{"structure":1,"defined":1,"generic":1,"specific":1,"related":1,"modules":1,"nsm":1,"oamd":1}
,"structure":{"store":1,"holds":1}
,"store":{"itu":1,"ietf":1}
,"mip":{"defined":1}
,"defined":{"inside":1,"oamd":1}
,"inside":{"library":1}
,"library":{"data":1,"me\u002Fmep":1}
,"data":{"structure":1}
,"holds":{"information":1}
,"tables":{"including":1}
,"including":{"mplstp_meg_name_tree":1}
,"mplstp_meg_name_tree":{"mplstp_meg_index_tree":1}
,"mplstp_meg_index_tree":{"mplstp_meg_me_index_tree":1}
,"mplstp_meg_me_index_tree":{"mplstp_provider_if_tree":1}
,"mplstp_provider_if_tree":{"mplstp_provider_if_client_tree":1}
,"mplstp_provider_if_client_tree":{"used":1}
,"again":{"meg_type":1}
,"determines":{"whether":1}
,"me\u002Fmep":{"information":1}
,"generic":{"transport":1}
,"technologies":{"inside":1,"control":1}
,"specific":{"transport":1}
,"technology":{"void":1}
,"void":{"pointer":1}
,"pointer":{"provides":1}
,"flexibility":{"reducing":1}
,"reducing":{"effort":1}
,"effort":{"enhance":1}
,"enhance":{"oam":1}
,"function":{"based":1}
,"based":{"y.1731":1}
,"y.1731":{"different":1,"mpls":1}
,"different":{"transport":1}
,"nsm":{"network":1,"shares":1,"transport":1,"responds":1}
,"network":{"service":1}
,"service":{"manager":1}
,"manager":{"(nsm)":1}
,"(nsm)":{"manages":1}
,"manages":{"information":1}
,"related":{"mpls-tp":1}
,"mpls-tp":{"transport":1,"tunnel":1}
,"tunnel":{"datalink":1}
,"datalink":{"nsm":1}
,"shares":{"information":1}
,"modules":{"zebos-xp":1}
,"zebos-xp":{"using":1,"handles":1,"parses":1}
,"using":{"asynchronous":1,"bfd":1}
,"asynchronous":{"sockets":1}
,"sockets":{"created":1}
,"created":{"startup":1}
,"startup":{"handles":1}
,"handles":{"creation":1,"following":1,"requests":1}
,"creation":{"maintenance":1}
,"whenever":{"new":1}
,"new":{"meg":1}
,"associated":{"transport":1}
,"sends":{"message":1,"on-demand":1}
,"message":{"nsm":1,"oamd":1}
,"responds":{"query":1}
,"query":{"sending":1}
,"sending":{"back":1}
,"back":{"transport":1}
,"imish":{"imish":1,"module":1}
,"module":{"zebos-xp":1,"processing":1,"mplsonm":1,"existing":1,"using":1}
,"following":{"additional":1}
,"additional":{"responsibilities:-provide":1}
,"responsibilities:-provide":{"commands":1}
,"commands":{"triggering":1,"enabling":1}
,"triggering":{"on-demand":1}
,"on-demand":{"y.1731":1,"oam":1,"lbm":1,"test":1}
,"mpls":{"oam":1}
,"functions":{"lbm":1,"ais":1,"control":1,"mplsonm":1}
,"lbm":{"tst":1,"on-demand":1}
,"tst":{"1dm":1}
,"1dm":{"2dm":1}
,"2dm":{"provides":1}
,"enabling":{"proactive":1}
,"proactive":{"y.1731":1}
,"ais":{"lck":1}
,"lck":{"functions":1}
,"mplsonm":{"mplsonm":1,"process":1,"sends":1,"module":1}
,"process":{"handles":1}
,"requests":{"user":1}
,"user":{"on-demand":1,"establishes":1}
,"request":{"message":1,"response":1}
,"processing":{"waits":1}
,"waits":{"reply":1}
,"reply":{"oamd":1}
,"parses":{"on-demand":1}
,"test":{"loss":1}
,"loss":{"measurement":1}
,"measurement":{"delay":1,"received":1}
,"delay":{"measurement":1}
,"received":{"user":1}
,"establishes":{"ipc":1}
,"ipc":{"communication":1}
,"communication":{"oamd":1}
,"bfd":{"client":1}
,"client":{"apis":1}
,"apis":{"send\u002Freceive":1}
,"send\u002Freceive":{"above":1}
,"above":{"mentioned":1}
,"mentioned":{"command\u0027s":1}
,"command\u0027s":{"request":1}
}
;Search.control.loadWordPairs(pairs);
