var pairs =
{
"show":{"running-config":1,"running":1}
,"running-config":{"switch":1}
,"switch":{"command":1,"bridge":1,"dot1x":1,"gmrp":1,"gvrp":1,"lacp":1,"lmi":1,"mstp":1,"radius-server":1,"rpsvt":1,"rstp":1,"ptp":1,"stp":1,"synce":1,"vlan":1}
,"command":{"show":1,"syntax":1,"mode":1}
,"running":{"system":1}
,"system":{"status":1}
,"status":{"configuration":1}
,"configuration":{"details":1}
,"details":{"given":1}
,"given":{"switch":1}
,"syntax":{"show":1}
,"bridge":{"show":1,"display":1,"group":1,"ageing-time":1,"priority":1,"max-age":1}
,"dot1x":{"show":1,"display":1}
,"gmrp":{"show":1,"display":1}
,"gvrp":{"show":1,"display":1}
,"lacp":{"show":1,"display":1}
,"lmi":{"show":1,"display":1}
,"mstp":{"show":1,"display":1}
,"radius-server":{"show":1,"display":1}
,"rpsvt":{"show":1}
,"rstp":{"show":1,"display":1}
,"ptp":{"show":1,"display":1}
,"stp":{"show":1,"display":1,"bridge":1}
,"synce":{"show":1,"display":1,"information":1}
,"vlan":{"parameters":1,"registration":1,"display":1,"command":1}
,"parameters":{"bridge":1}
,"display":{"bridge":1,"802.1x":1,"garp":1,"link":1,"ethernet":1,"multiple":1,"radius":1,"rapid":1,"precision":1,"spanning":1,"synce":1,"values":1}
,"group":{"information":1}
,"information":{"dot1x":1,"gmrp":1,"gvrp":1,"lacp":1,"lmi":1,"mstp":1,"radius-server":1,"rpvst":1,"rstp":1,"ptp":1,"synce":1,"vlan":1}
,"802.1x":{"port-based":1}
,"port-based":{"authentication":1}
,"authentication":{"information":1}
,"garp":{"multicast":1,"vlan":1}
,"multicast":{"registration":1}
,"registration":{"protocol":1}
,"protocol":{"(gmrp)":1,"(gvrp)":1,"(lacp)":1,"(lmi)":1,"(mstp)":1,"(rstp)":1,"(ptp)":1,"(stp)":1}
,"(gmrp)":{"information":1}
,"(gvrp)":{"information":1}
,"link":{"aggregation":1}
,"aggregation":{"control":1}
,"control":{"protocol":1}
,"(lacp)":{"information":1}
,"ethernet":{"local":1}
,"local":{"management":1}
,"management":{"interface":1}
,"interface":{"protocol":1}
,"(lmi)":{"information":1}
,"multiple":{"spanning":1}
,"spanning":{"tree":1}
,"tree":{"protocol":1,"(rpvst":1}
,"(mstp)":{"information":1}
,"radius":{"server":1}
,"server":{"information":1}
,"rpvst":{"display":1}
,"rapid":{"per-vlan":1,"spanning":1}
,"per-vlan":{"spanning":1}
,"(rpvst":{"information":1}
,"(rstp)":{"information":1}
,"precision":{"time":1}
,"time":{"protocol":1}
,"(ptp)":{"stp":1}
,"(stp)":{"information":1}
,"values":{"associated":1}
,"associated":{"single":1}
,"single":{"vlan":1}
,"mode":{"privileged":1,"configure":1,"router-map":1,"example":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"configure":{"mode":1}
,"router-map":{"mode":1}
,"example":{"(config)":1}
,"(config)":{"show":1}
,"ageing-time":{"bridge":1}
,"priority":{"4096":1}
,"4096":{"bridge":1}
}
;Search.control.loadWordPairs(pairs);
