var pairs =
{
"distance":{"command":1,"rip":1,"<1-255>":1,"(<1-255>":1,"value":1,"120":1,"100":1}
,"command":{"administrative":1,"disable":1,"ipv4":1,"(distance)":1,"syntax":1,"mode":1}
,"administrative":{"distance":1}
,"rip":{"option":1,"(config-router)":1}
,"option":{"command":1}
,"disable":{"function":1}
,"function":{"details":1}
,"details":{"command":1}
,"ipv4":{"version":1}
,"version":{"command":1}
,"(distance)":{"command":1}
,"syntax":{"distance":1}
,"<1-255>":{"distance":1,"specify":1}
,"(<1-255>":{"parameter":1}
,"parameter":{"<1-255>":1}
,"specify":{"administrative":1}
,"value":{"default":1}
,"default":{"default":1,"administrative":1}
,"120":{"command":1}
,"mode":{"router":1,"example":1}
,"router":{"mode":1,"ipv6":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"ipv6":{"rip":1}
,"(config-router)":{"distance":1}
}
;Search.control.loadWordPairs(pairs);
