var pairs =
{
"ldp_api_get_loop_detect_hop_limit":{"call":1,"(struct":1}
,"call":{"returns":1}
,"returns":{"loop-detect":1}
,"loop-detect":{"hop-count":1}
,"hop-count":{"limit":1}
,"limit":{"given":1,"ldp_error":1}
,"given":{"entity":1}
,"entity":{"loop":1,"ldp":1,"output":1}
,"loop":{"detection":1}
,"detection":{"enabled":1}
,"enabled":{"syntax":1}
,"syntax":{"u_char":1}
,"u_char":{"ldp_api_get_loop_detect_hop_limit":1}
,"(struct":{"ldp":1}
,"ldp":{"*ldp":1,"ldp":1,"instance":1,"entity":1}
,"*ldp":{"struct":1}
,"struct":{"ldp_entity":1}
,"ldp_entity":{"*entity)":1}
,"*entity)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ldp":1,"none":1}
,"instance":{"entity":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"hop":1}
,"hop":{"count":1}
,"count":{"limit":1}
}
;Search.control.loadWordPairs(pairs);
