var pairs =
{
"bind":{"interface":1}
,"interface":{"configure":1,"eth0":1,"(eth2)":1,"mode":1,"vr1.this":1,"informs":1,"eth1":1,"(eth1)":1,"vr1":1}
,"configure":{"terminal":1,"mode":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"interface":1}
,"mode":{"(config)":1,"(config-if)":1}
,"(config)":{"interface":1}
,"eth0":{"specify":1}
,"specify":{"interface":1}
,"(eth2)":{"configured":1}
,"configured":{"enter":1}
,"(config-if)":{"virtual-router":1,"exit":1}
,"virtual-router":{"forwarding":1}
,"forwarding":{"vr1":1}
,"vr1":{"bind":1}
,"vr1.this":{"command":1}
,"command":{"binds":1}
,"binds":{"interface":1}
,"informs":{"zebos-xp":1}
,"zebos-xp":{"clients":1}
,"clients":{"(config-if)":1}
,"exit":{"exit":1,"interface":1}
,"eth1":{"specify":1}
,"(eth1)":{"configured":1}
}
;Search.control.loadWordPairs(pairs);
