var pairs =
{
"rmon_eventgroup":{"data":1,"{u_int32_t":1}
,"data":{"structure":1}
,"structure":{"rmond\u002Frmon_config.h":1}
,"rmond\u002Frmon_config.h":{"rmon":1}
,"rmon":{"event":1}
,"event":{"group":1,"table":1,"entry":1,"eventowner":1}
,"group":{"member":1}
,"member":{"description":1}
,"description":{"eventindex":1}
,"eventindex":{"index":1,"define":1}
,"index":{"uniquely":1}
,"uniquely":{"identifies":1}
,"identifies":{"entry":1}
,"entry":{"event":1,"eventtype":1,"last":1,"using":1}
,"table":{"eventconf":1}
,"eventconf":{"eventdescription":1,"char":1}
,"eventdescription":{"comment":1,"[rmon_descr_length":1}
,"comment":{"describing":1}
,"describing":{"event":1}
,"eventtype":{"-none":1,"\u002F*1-none":1}
,"-none":{"-log":1}
,"-log":{"-snmp":1,"trap":1}
,"-snmp":{"rap":1}
,"rap":{"-log":1}
,"trap":{"eventcommunity":1,"sent":1}
,"eventcommunity":{"snmp":1,"[rmon_comm_length":1}
,"snmp":{"trap":1,"community":1}
,"sent":{"sent":1,"snmp":1}
,"community":{"eventlasttimesent":1}
,"eventlasttimesent":{"value":1,"char":1}
,"value":{"sysuptime":1}
,"sysuptime":{"time":1}
,"time":{"event":1}
,"last":{"generated":1}
,"generated":{"event":1}
,"eventowner":{"entity":1,"[rmon_owner_name_size":1}
,"entity":{"configured":1}
,"configured":{"entry":1}
,"using":{"resources":1}
,"resources":{"assigned":1}
,"assigned":{"eventstatus":1}
,"eventstatus":{"-valid":1,"\u002F*1-valid":1}
,"-valid":{"-createrequest":1}
,"-createrequest":{"-undercreation":1}
,"-undercreation":{"-invalid":1}
,"-invalid":{"-non-existing":1}
,"-non-existing":{"definition":1}
,"definition":{"struct":1}
,"struct":{"rmon_eventgroup":1}
,"{u_int32_t":{"eventindex":1}
,"define":{"rmon_event_conf_description":1,"rmon_event_conf_owner":1}
,"rmon_event_conf_description":{"<<0)":1}
,"<<0)":{"define":1}
,"rmon_event_conf_owner":{"<<1)":1}
,"<<1)":{"u_int8_t":1}
,"u_int8_t":{"eventconf":1}
,"char":{"eventdescription":1,"eventowner":1}
,"[rmon_descr_length":{"u_int32_t":1}
,"u_int32_t":{"eventtype":1,"eventstatus":1}
,"\u002F*1-none":{"2-log":1}
,"2-log":{"3-snmptrap":1}
,"3-snmptrap":{"4-logandtrap":1}
,"4-logandtrap":{"*\u002Fchar":1}
,"*\u002Fchar":{"eventcommunity":1}
,"[rmon_comm_length":{"s_int32_t":1}
,"s_int32_t":{"eventlasttimesent":1}
,"[rmon_owner_name_size":{"u_int32_t":1}
,"\u002F*1-valid":{"2-createrequest":1}
,"2-createrequest":{"*3-undercreation":1}
,"*3-undercreation":{"4-invalid":1}
,"4-invalid":{"*5-nonexistent":1}
,"*5-nonexistent":{"*\u002F}":1}
}
;Search.control.loadWordPairs(pairs);
