var pairs =
{
"nsm_api_mpls_tp_tnl_unconfig":{"function":1,"(u_int32_t":1}
,"function":{"removes":1,"called":1,"executed":1}
,"removes":{"ietf":1}
,"ietf":{"mpls-tp":1}
,"mpls-tp":{"tunnel":1}
,"tunnel":{"function":1,"source":1,"src_gid":1,"destination":1,"associated":1,"nsm_api_set_err_mpls_tp_tnl_does_not_exist":1,"exist":1,"mapped":1}
,"called":{"mpls-tp":1}
,"source":{"destination":1,"global":1,"node":1}
,"destination":{"command":1,"global":1,"node":1,"identifiers":1}
,"command":{"syntax":1}
,"syntax":{"int":1}
,"int":{"int":1,"nsm_api_mpls_tp_tnl_unconfig":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1}
,"u_int32_t":{"tnl_id":1,"src_gid":1,"src_nid":1,"dst_gid":1,"dst_nid)":1}
,"tnl_id":{"u_int32_t":1,"tunnel":1}
,"src_gid":{"u_int32_t":1,"tunnel":1}
,"src_nid":{"u_int32_t":1}
,"dst_gid":{"u_int32_t":1,"tunnel":1}
,"dst_nid)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"(vr)":1,"exist":1}
,"(vr)":{"instance":1}
,"instance":{"tnl_id":1}
,"global":{"src":1,"dst_nid":1}
,"src":{"tunnel":1}
,"node":{"dst_gid":1,"output":1}
,"dst_nid":{"tunnel":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_api_set_success":1}
,"nsm_api_set_success":{"function":1}
,"executed":{"properly":1}
,"properly":{"nsm_api_set_error":1}
,"nsm_api_set_error":{"internal":1}
,"internal":{"error":1}
,"error":{"nsm_api_set_err_mpls_tp_tnl_assoc_exist":1}
,"nsm_api_set_err_mpls_tp_tnl_assoc_exist":{"tunnel":1}
,"associated":{"tunnel":1,"meg":1}
,"nsm_api_set_err_mpls_tp_tnl_does_not_exist":{"tunnel":1}
,"exist":{"nsm_api_set_err_mpls_tp_tnl_has_meg_config":1}
,"nsm_api_set_err_mpls_tp_tnl_has_meg_config":{"tunnel":1}
,"meg":{"nsm_api_set_err_mpls_tp_tnl_service_map_exist":1}
,"nsm_api_set_err_mpls_tp_tnl_service_map_exist":{"tunnel":1}
,"mapped":{"least":1}
,"least":{"service":1}
,"service":{"nsm_api_set_err_mpls_tp_tnl_src_dst_same":1}
,"nsm_api_set_err_mpls_tp_tnl_src_dst_same":{"tunnel":1}
,"identifiers":{"nsm_api_set_err_vr_not_exist":1}
,"nsm_api_set_err_vr_not_exist":{"virtual":1}
}
;Search.control.loadWordPairs(pairs);
