var pairs =
{
"distribution":{"layer":1}
,"layer":{"network":1,"aggregates":1,"sends":1,"segments":1,"performs":1,"managing":1,"failures":1,"uses":1,"(l3)":1,"layer":1,"(l2)":1,"called":1,"concentration":1}
,"network":{"design":1,"routers":1,"(vlan)":1,"address":1}
,"design":{"model":1}
,"model":{"layer":1}
,"aggregates":{"data":1}
,"data":{"received":1}
,"received":{"access":1}
,"access":{"layer":1,"control":1}
,"sends":{"core":1}
,"core":{"layer":1,"isolating":1,"access":1}
,"segments":{"local":1}
,"local":{"network":1,"area":1}
,"routers":{"multilayer":1}
,"multilayer":{"switches":1}
,"switches":{"distribution":1}
,"performs":{"functions":1}
,"functions":{"including":1}
,"including":{"routing":1}
,"routing":{"subnetworks":1,"filtering":1,"connect":1}
,"subnetworks":{"virtual":1}
,"virtual":{"local":1}
,"area":{"network":1}
,"(vlan)":{"instances":1}
,"instances":{"access":1}
,"managing":{"access":1,"firewalls":1,"queues":1}
,"control":{"routing":1}
,"filtering":{"qos":1}
,"qos":{"policies":1}
,"policies":{"managing":1}
,"firewalls":{"network":1}
,"address":{"translation":1}
,"translation":{"(nat)":1}
,"(nat)":{"managing":1}
,"queues":{"prioritizing":1}
,"prioritizing":{"traffic":1}
,"traffic":{"summarizing":1}
,"summarizing":{"routes":1}
,"routes":{"advertising":1}
,"advertising":{"core":1}
,"isolating":{"core":1}
,"failures":{"disruptions":1}
,"disruptions":{"distribution":1}
,"uses":{"layer":1}
,"(l3)":{"routing":1}
,"connect":{"core":1,"access":1}
,"(l2)":{"switching":1}
,"switching":{"connect":1}
,"called":{"aggregation":1}
,"aggregation":{"layer":1}
,"concentration":{"layer":1}
}
;Search.control.loadWordPairs(pairs);
