var pairs =
{
"primary":{"setup-priority":1,"setup":1}
,"setup-priority":{"command":1,"<0-7>":1,"parameters":1}
,"command":{"configure":1,"revert":1,"syntax":1,"mode":1}
,"configure":{"setup":1,"terminal":1}
,"setup":{"priority":1}
,"priority":{"value":1,"determines":1,"new":1,"existing":1,"higher":1,"parameter":1,"lowest":1}
,"value":{"trunk":1,"command":1,"default":1}
,"trunk":{"case":1,"setup":1,"mode":1}
,"case":{"insufficient":1}
,"insufficient":{"bandwidth":1}
,"bandwidth":{"users":1,"done":1}
,"users":{"remove":1}
,"remove":{"less":1}
,"less":{"important":1}
,"important":{"lsps":1}
,"lsps":{"free":1,"primary":1}
,"free":{"bandwidth":1}
,"done":{"preempting":1}
,"preempting":{"existing":1}
,"existing":{"lsps":1,"lsp":1}
,"determines":{"new":1}
,"new":{"lsp":1}
,"lsp":{"preempt":1,"setup":1,"higher":1,"existing":1,"preempted":1}
,"preempt":{"existing":1}
,"higher":{"hold":1}
,"hold":{"priority":1}
,"preempted":{"note":1}
,"note":{"trunk":1}
,"parameter":{"command":1}
,"revert":{"default":1}
,"default":{"primary":1,"default":1,"setup":1}
,"syntax":{"primary":1}
,"<0-7>":{"primary":1,"priority":1}
,"parameters":{"<0-7>":1}
,"lowest":{"command":1}
,"mode":{"trunk":1,"examples":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"rsvp-trunk":1}
,"rsvp-trunk":{"mytrunk":1}
,"mytrunk":{"(config-trunk)":1}
,"(config-trunk)":{"primary":1}
}
;Search.control.loadWordPairs(pairs);
