var pairs =
{
"efm_oam_sym_period_high_window_get":{"function":1,"(struct":1}
,"function":{"gets":1,"syntax":1,"succeeds":1}
,"gets":{"high":1}
,"high":{"word":1}
,"word":{"8-octet":1}
,"8-octet":{"window":1}
,"window":{"size":1,"high":1}
,"size":{"errored":1}
,"errored":{"symbol":1}
,"symbol":{"period":1}
,"period":{"event":1}
,"event":{"efm":1,"return":1}
,"efm":{"mib":1,"enabled":1}
,"mib":{"support":1}
,"support":{"calls":1}
,"calls":{"function":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"efm_oam_sym_period_high_window_get":1}
,"(struct":{"interface":1}
,"interface":{"*ifp":1,"structure":1,"null":1,"found":1,"efm_oam_err_internal":1}
,"*ifp":{"u_int32_t":1}
,"u_int32_t":{"*window)":1}
,"*window)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"window":1}
,"ifp":{"pointer":1}
,"pointer":{"interface":1}
,"structure":{"output":1}
,"output":{"parameters":1}
,"return":{"efm_failure":1}
,"efm_failure":{"interface":1}
,"null":{"efm_oam_err_if_not_found":1}
,"efm_oam_err_if_not_found":{"onmd":1}
,"onmd":{"interface":1}
,"found":{"efm_oam_err_not_enabled":1}
,"efm_oam_err_not_enabled":{"efm":1}
,"enabled":{"interface":1}
,"efm_oam_err_internal":{"internal":1}
,"internal":{"error":1}
,"error":{"efm_success":1}
,"efm_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
