var pairs =
{
"rsvp_api_s2l_session_param_set":{"call":1,"(struct":1}
,"call":{"sets":1}
,"sets":{"s2l":1}
,"s2l":{"session":1}
,"session":{"parameters":1,"path":1}
,"parameters":{"triggers":1,"orig_session":1,"none":1}
,"triggers":{"fsm":1}
,"fsm":{"syntax":1}
,"syntax":{"void":1}
,"void":{"rsvp_api_s2l_session_param_set":1}
,"(struct":{"rsvp_session":1}
,"rsvp_session":{"*orig_session":1}
,"*orig_session":{"struct":1}
,"struct":{"rsvp_path":1}
,"rsvp_path":{"*path":1}
,"*path":{"bool_t":1}
,"bool_t":{"enable_cspf)":1}
,"enable_cspf)":{"input":1}
,"input":{"parameters":1}
,"orig_session":{"s2l":1}
,"path":{"explicit":1,"(ero)":1}
,"explicit":{"path":1}
,"(ero)":{"enable_cspf":1}
,"enable_cspf":{"rsvp_true":1}
,"rsvp_true":{"enable":1}
,"enable":{"cspf":1}
,"cspf":{"rsvp_false":1,"output":1}
,"rsvp_false":{"disable":1}
,"disable":{"cspf":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"none":1}
}
;Search.control.loadWordPairs(pairs);
