var pairs =
{
"nsm_mpls_set_pw_enet_pw_if_index":{"function":1,"(struct":1}
,"function":{"sets":1,"succeeds":1}
,"sets":{"interface":1}
,"interface":{"index":1}
,"index":{"syntax":1,"virtual":1,"row":1,"output":1}
,"syntax":{"include":1}
,"include":{"nsm\u002Fmpls\u002Fnsm_mpls_vc_snmp.h":1}
,"nsm\u002Fmpls\u002Fnsm_mpls_vc_snmp.h":{"u_int32_t":1}
,"u_int32_t":{"nsm_mpls_set_pw_enet_pw_if_index":1,"pw_ix":1,"pw_instance":1,"pw_ifindex)":1}
,"(struct":{"nsm_master":1}
,"nsm_master":{"*nm":1}
,"*nm":{"u_int32_t":1}
,"pw_ix":{"u_int32_t":1,"index":1}
,"pw_instance":{"u_int32_t":1,"index":1}
,"pw_ifindex)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"pointer":1,"none":1}
,"pointer":{"nsm":1}
,"nsm":{"master":1}
,"master":{"structure":1}
,"structure":{"pw_ix":1}
,"virtual":{"circuit":1}
,"circuit":{"table":1}
,"table":{"pw_instance":1,"pw_ifindex":1}
,"row":{"enet":1}
,"enet":{"table":1}
,"pw_ifindex":{"interface":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"nsm_api_set_error":1}
,"nsm_api_set_error":{"vlan":1}
,"vlan":{"ethernet":1}
,"ethernet":{"tagged":1}
,"tagged":{"nsm_api_set_success":1}
,"nsm_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
