var pairs =
{
"rip":{"bfd":1,"protocol":1}
,"bfd":{"command":1,"function":1,"fall-over":1,"rip_bfd_debug_unset":1}
,"command":{"api":1}
,"api":{"rip":1}
,"protocol":{"module":1}
,"module":{"uses":1}
,"uses":{"following":1}
,"following":{"functions":1}
,"functions":{"bfd":1}
,"function":{"application":1}
,"application":{"rip_bfd_all_interfaces_set":1}
,"rip_bfd_all_interfaces_set":{"sets":1}
,"sets":{"bfd":1}
,"fall-over":{"check":1}
,"check":{"interfaces":1,"specific":1}
,"interfaces":{"specified":1}
,"specified":{"process":1}
,"process":{"rip_bfd_all_interfaces_unset":1,"rip_bfd_neighbor_set":1,"rip_bfd_neighbor_unset":1,"rip_bfd_debug_set":1}
,"rip_bfd_all_interfaces_unset":{"unsets":1}
,"unsets":{"bfd":1}
,"rip_bfd_neighbor_set":{"sets":1}
,"specific":{"neighbor":1}
,"neighbor":{"specified":1}
,"rip_bfd_neighbor_unset":{"unsets":1}
,"rip_bfd_debug_set":{"enables":1}
,"enables":{"debugging":1}
,"debugging":{"rip":1}
,"rip_bfd_debug_unset":{"disables":1}
,"disables":{"debugging":1}
}
;Search.control.loadWordPairs(pairs);
