var pairs =
{
"show":{"bgp":1}
,"bgp":{"cidr-only":1,"ipv4":1,"table":1}
,"cidr-only":{"command":1,"show":1,"parameters":1,"bgp":1}
,"command":{"display":1,"syntax":1,"mode":1,"show":1}
,"display":{"routes":1}
,"routes":{"non-natural":1,"unicast":1}
,"non-natural":{"network":1}
,"network":{"masks":1,"next":1}
,"masks":{"command":1}
,"syntax":{"show":1}
,"ipv4":{"(unicast":1,"ipv4":1,"routes":1}
,"(unicast":{"multicast)":1}
,"multicast)":{"cidr-only":1}
,"parameters":{"ipv4":1}
,"unicast":{"unicast":1,"prefixes":1}
,"prefixes":{"multicast":1,"command":1}
,"multicast":{"multicast":1,"prefixes":1}
,"mode":{"privileged":1,"exec":1,"example":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"example":{"sample":1}
,"sample":{"output":1}
,"output":{"show":1}
,"table":{"version":1}
,"version":{"local":1}
,"local":{"router":1}
,"router":{"10.10.10.50":1}
,"10.10.10.50":{"status":1}
,"status":{"codes":1}
,"codes":{"suppressed":1,"-igp":1}
,"suppressed":{"damped":1}
,"damped":{"history":1}
,"history":{"stale":1}
,"stale":{"*valid":1}
,"*valid":{"best":1}
,"best":{"-internal":1}
,"-internal":{"origin":1}
,"origin":{"codes":1}
,"-igp":{"-egp":1}
,"-egp":{"-incomplete":1}
,"-incomplete":{"network":1}
,"next":{"hop":1}
,"hop":{"metric":1}
,"metric":{"locprf":1}
,"locprf":{"weight":1}
,"weight":{"path":1}
,"path":{"3.3.3.0\u002F24":1}
,"3.3.3.0\u002F24":{"10.10.10.10":1}
,"10.10.10.10":{"total":1}
,"total":{"number":1}
,"number":{"prefixes":1}
}
;Search.control.loadWordPairs(pairs);
