var pairs =
{
"nsm_mpls_get_pw_del_notify":{"function":1,"(struct":1}
,"function":{"gets":1,"succeeds":1}
,"gets":{"delete":1}
,"delete":{"notification":1}
,"notification":{"setting":1}
,"setting":{"syntax":1,"return":1}
,"syntax":{"include":1}
,"include":{"nsm\u002Fmpls\u002Fnsm_mpls_vc_api.h":1}
,"nsm\u002Fmpls\u002Fnsm_mpls_vc_api.h":{"u_int32_t":1}
,"u_int32_t":{"nsm_mpls_get_pw_del_notify":1}
,"(struct":{"nsm_master":1}
,"nsm_master":{"*nm":1}
,"*nm":{"int":1}
,"int":{"*val)":1}
,"*val)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"pointer":1,"val":1}
,"pointer":{"nsm":1,"notification":1}
,"nsm":{"master":1}
,"master":{"structure":1}
,"structure":{"output":1,"null":1}
,"output":{"parameters":1}
,"val":{"pointer":1}
,"return":{"value":1}
,"value":{"nsm_api_get_error":1}
,"nsm_api_get_error":{"pointer":1}
,"null":{"nsm_api_get_success":1}
,"nsm_api_get_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
