var pairs =
{
"nsm_vlan_port_beb_del_cnp_svlan":{"function":1,"(struct":1}
,"function":{"called":1}
,"called":{"delete":1}
,"delete":{"range":1}
,"range":{"svlan":1}
,"svlan":{"mapping":1}
,"mapping":{"isid":1}
,"isid":{"syntax":1,"nsm_vid_t":1,"isis":1}
,"syntax":{"nsm_vlan_port_beb_del_cnp_svlan":1}
,"(struct":{"interface":1}
,"interface":{"*ifp":1,"isid":1}
,"*ifp":{"u_int32_t":1}
,"u_int32_t":{"isid":1}
,"nsm_vid_t":{"start_vid":1,"end_vid)":1}
,"start_vid":{"nsm_vid_t":1,"end_vid":1}
,"end_vid)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"none":1}
,"ifp":{"pointer":1}
,"pointer":{"interface":1}
,"isis":{"value":1}
,"value":{"start_vid":1,"result_success":1}
,"end_vid":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
}
;Search.control.loadWordPairs(pairs);
