var pairs =
{
"offset-list":{"command":1,"word":1,"(word)":1,"accesslist1":1}
,"command":{"add":1,"remove":1,"ipv4":1,"(offset-list)":1,"syntax":1,"mode":1}
,"add":{"offset":1}
,"offset":{"metrics":1,"used":1,"value":1}
,"metrics":{"routes":1,"incoming":1,"outgoing":1,"networks":1}
,"routes":{"learned":1,"indicates":1,"<0-16>":1,"matching":1}
,"learned":{"ripng":1}
,"ripng":{"parameter":1}
,"parameter":{"command":1}
,"remove":{"function":1}
,"function":{"details":1}
,"details":{"command":1}
,"ipv4":{"version":1}
,"version":{"command":1}
,"(offset-list)":{"command":1}
,"syntax":{"offset-list":1}
,"word":{"(in":1,"specify":1}
,"(in":{"out)":1}
,"out)":{"<0-16>":1}
,"<0-16>":{"(ifname":1,"specify":1}
,"(ifname":{"offset-list":1,"parameters":1}
,"(word)":{"<0-16>":1}
,"parameters":{"word":1}
,"specify":{"access-list":1,"offset":1}
,"access-list":{"number":1}
,"number":{"names":1}
,"names":{"apply":1}
,"apply":{"indicates":1}
,"indicates":{"access":1}
,"access":{"list":1}
,"list":{"used":1,"ifname":1,"accesslist1":1}
,"used":{"metrics":1}
,"incoming":{"advertised":1}
,"advertised":{"routes":1}
,"outgoing":{"advertised":1}
,"networks":{"matching":1}
,"matching":{"access":1,"addresses":1}
,"ifname":{"alphanumeric":1}
,"alphanumeric":{"string":1}
,"string":{"specifies":1}
,"specifies":{"interface":1}
,"interface":{"match":1,"defined":1,"eth0":1}
,"match":{"default":1}
,"default":{"default":1,"offset":1}
,"value":{"metric":1,"interface":1}
,"metric":{"value":1}
,"defined":{"operating":1}
,"operating":{"system":1}
,"system":{"command":1}
,"mode":{"router":1,"examples":1}
,"router":{"mode":1,"examines":1,"ipv6":1}
,"examples":{"example":1}
,"example":{"router":1}
,"examines":{"rip":1}
,"rip":{"updates":1,"(config-router)":1}
,"updates":{"sent":1}
,"sent":{"interface":1}
,"eth0":{"adds":1}
,"adds":{"hops":1}
,"hops":{"routes":1}
,"addresses":{"specified":1}
,"specified":{"access":1}
,"accesslist1":{"configure":1,"eth0":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"ipv6":{"rip":1}
,"(config-router)":{"offset-list":1}
}
;Search.control.loadWordPairs(pairs);
