var pairs =
{
"peb2":{"(config)":1}
,"(config)":{"bridge":1,"vlan":1,"interface":1}
,"bridge":{"protocol":1,"provider-mstp":1,"state":1,"associate":1,"create":1}
,"protocol":{"provider-mstp":1}
,"provider-mstp":{"edge":1}
,"edge":{"configure":1,"(config)":1}
,"configure":{"bridge":1}
,"vlan":{"database":1,"type":1,"(config-vlan)":1,"add":1,"mode":1}
,"database":{"enter":1,"(config-vlan)":1}
,"enter":{"vlan":1,"interface":1,"switchport":1,"bridge-group":1}
,"(config-vlan)":{"vlan":1,"ethernet":1}
,"type":{"customer":1,"service":1}
,"customer":{"bridge":1,"vlan":1}
,"state":{"enable":1}
,"enable":{"create":1,"mode":1}
,"create":{"customer":1,"service":1,"map4":1}
,"service":{"point-point":1,"vlan":1}
,"point-point":{"bridge":1}
,"ethernet":{"svlan":1}
,"svlan":{"ovc-id":1,"5to":1}
,"ovc-id":{"ovc2":1}
,"ovc2":{"oep-id":1}
,"oep-id":{"oep4":1}
,"oep4":{"bridge":1,"register":1}
,"associate":{"svlan":1,"map1":1}
,"5to":{"oep":1}
,"oep":{"&create":1,"mapping":1}
,"&create":{"ovc1":1}
,"ovc1":{"(config-mst)":1}
,"(config-mst)":{"oep":1}
,"mapping":{"table":1,"cvlan":1}
,"table":{"map4":1}
,"map4":{"bridge":1,"(config-oep-mapping)":1}
,"(config-oep-mapping)":{"cvlan":1,"exit":1}
,"cvlan":{"oep-id":1,"&oep":1,"(config)":1}
,"register":{"association":1}
,"association":{"mapping":1}
,"&oep":{"(config-oep-mapping)":1}
,"exit":{"(config)":1,"domain":1}
,"interface":{"eth1":1,"mode":1,"eth2":1}
,"eth1":{"enter":1}
,"mode":{"(config-if)":1,"customer-edge":1,"hybrid":1,"provider-network":1}
,"(config-if)":{"switchport":1,"bridge-group":1,"associate":1,"allow":1}
,"switchport":{"enter":1,"mode":1,"customer-edge":1,"provider-network":1}
,"bridge-group":{"enter":1,"(config-if)":1,"mode":1}
,"customer-edge":{"hybrid":1,"accept":1}
,"hybrid":{"switchport":1,"(config-if)":1,"acceptable-frame-type":1,"allowed":1}
,"acceptable-frame-type":{"mode":1}
,"accept":{"frames":1}
,"frames":{"(config-if)":1}
,"allowed":{"vlan":1}
,"add":{"egress-tagged":1}
,"egress-tagged":{"enable":1}
,"map1":{"cvlan":1}
,"eth2":{"exit":1}
,"domain":{"configuration":1}
,"configuration":{"mode":1}
,"provider-network":{"enter":1,"allowed":1,"(config-if)":1}
,"allow":{"vlans":1}
}
;Search.control.loadWordPairs(pairs);
