var pairs =
{
"qemu":{"(quick":1,"emulates":1,"used":1}
,"(quick":{"emulator)":1}
,"emulator)":{"hosted":1}
,"hosted":{"hypervisor":1}
,"hypervisor":{"performs":1}
,"performs":{"hardware":1}
,"hardware":{"virtualization":1}
,"virtualization":{"qemu":1,"extensions":1}
,"emulates":{"cpus":1}
,"cpus":{"dynamic":1}
,"dynamic":{"binary":1}
,"binary":{"translation":1}
,"translation":{"provides":1}
,"provides":{"device":1}
,"device":{"models":1}
,"models":{"enabling":1}
,"enabling":{"run":1}
,"run":{"variety":1,"virtual":1}
,"variety":{"unmodified":1}
,"unmodified":{"guest":1}
,"guest":{"operating":1}
,"operating":{"systems":1}
,"systems":{"qemu":1}
,"used":{"together":1,"purely":1}
,"together":{"kvm":1}
,"kvm":{"(kernel-based":1}
,"(kernel-based":{"virtual":1}
,"virtual":{"machine)":1,"machines":1}
,"machine)":{"run":1}
,"machines":{"near-native":1}
,"near-native":{"speed":1}
,"speed":{"(requiring":1}
,"(requiring":{"hardware":1}
,"extensions":{"x86":1}
,"x86":{"machines)":1}
,"machines)":{"qemu":1}
,"purely":{"cpu":1}
,"cpu":{"emulation":1}
,"emulation":{"user-level":1}
,"user-level":{"processes":1}
,"processes":{"allowing":1}
,"allowing":{"applications":1}
,"applications":{"compiled":1}
,"compiled":{"architecture":1}
,"architecture":{"run":1}
}
;Search.control.loadWordPairs(pairs);
