var pairs =
{
"overview":{"l2vpn":1}
,"l2vpn":{"(layer":1}
,"(layer":{"virtual":1}
,"virtual":{"private":1}
,"private":{"network)":1}
,"network)":{"multi-segment":1}
,"multi-segment":{"pseudowire":1,"pseudowires":1}
,"pseudowire":{"(ms-pw)":1,"domains":1,"status":1}
,"(ms-pw)":{"called":1}
,"called":{"switched":1,"terminating":1,"s-pe":1}
,"switched":{"statically-or":1}
,"statically-or":{"dynamically-configured":1}
,"dynamically-configured":{"two":1}
,"two":{"segments":1,"service":1,"vcs":1}
,"segments":{"function":1,"ms-pw":1}
,"function":{"single":1}
,"single":{"ms-pw":1}
,"ms-pw":{"spans":1,"s-pe":1,"ms-pw":1,"declared":1,"associations":1,"display":1}
,"spans":{"across":1}
,"across":{"multiple":1}
,"multiple":{"cores":1,"domains":1}
,"cores":{"autonomous":1}
,"autonomous":{"systems":1,"system":1}
,"systems":{"different":1,"provider":1,"administrative":1}
,"different":{"carrier":1,"autonomous":1}
,"carrier":{"networks":1}
,"networks":{"multi-segment":1}
,"pseudowires":{"enable":1}
,"enable":{"service":1,"pseudowire":1,"disable":1}
,"service":{"provider":1,"providers":1}
,"provider":{"extend":1,"administrative":1}
,"extend":{"reach":1}
,"reach":{"pseudo-wires":1}
,"pseudo-wires":{"across":1}
,"domains":{"domains":1,"autonomous":1,"end":1}
,"administrative":{"control":1}
,"control":{"igp":1,"two":1,"data":1}
,"igp":{"areas":1}
,"areas":{"autonomous":1}
,"system":{"different":1}
,"providers":{"administratively":1}
,"administratively":{"established":1}
,"established":{"pseudowire":1}
,"end":{"routers":1}
,"routers":{"called":1,"(t-pes)":1,"s-pe":1}
,"terminating":{"routers":1}
,"(t-pes)":{"switching":1}
,"switching":{"routers":1}
,"s-pe":{"routers":1,"router":1,"configure":1,"string":1,"display":1,"ldp":1}
,"router":{"terminates":1,"switches":1}
,"terminates":{"tunnels":1}
,"tunnels":{"preceding":1}
,"preceding":{"succeeding":1}
,"succeeding":{"segments":1}
,"switches":{"control":1}
,"data":{"planes":1}
,"planes":{"preceding":1}
,"declared":{"single-segment":1}
,"single-segment":{"pws":1}
,"pws":{"document":1}
,"document":{"contains":1}
,"contains":{"procedures":1}
,"procedures":{"required":1}
,"required":{"accomplish":1}
,"accomplish":{"following":1}
,"following":{"tasks":1}
,"tasks":{"configure":1}
,"configure":{"signaled":1,"static":1,"targeted":1,"s-pe":1}
,"signaled":{"vcs":1}
,"vcs":{"(virtual":1,"add":1,"bind":1,"s-pe":1}
,"(virtual":{"circuits)":1}
,"circuits)":{"configure":1}
,"static":{"vcs":1}
,"add":{"fib":1}
,"fib":{"entries":1}
,"entries":{"static":1}
,"bind":{"layer":1}
,"layer":{"physical":1}
,"physical":{"interfaces":1}
,"interfaces":{"(switchport)":1,"stitch":1}
,"(switchport)":{"configure":1}
,"targeted":{"ldp":1}
,"ldp":{"sessions":1,"label-switching":1,"module":1}
,"sessions":{"enable":1}
,"status":{"tlv":1,"interface":1}
,"tlv":{"(pw-status-tlv)":1}
,"(pw-status-tlv)":{"enable":1}
,"disable":{"ldp":1}
,"label-switching":{"interfaces":1}
,"stitch":{"two":1}
,"string":{"descriptions":1}
,"descriptions":{"display":1}
,"display":{"details":1,"stitching":1,"status":1,"configuration":1}
,"details":{"ms-pw":1}
,"associations":{"s-pe":1,"configured":1,"ms-pw":1}
,"stitching":{"associations":1}
,"configured":{"s-pe":1}
,"interface":{"label":1}
,"label":{"associations":1}
,"configuration":{"s-pe":1}
}
;Search.control.loadWordPairs(pairs);
