var pairs =
{
"hal_mpls_ftn_entry_add":{"function":1,"(int":1}
,"function":{"adds":1,"used":1,"fails":1,"succeeds":1}
,"adds":{"specified":1,"entry":1}
,"specified":{"ftn":1}
,"ftn":{"entry":1,"table":1,"index":1,"type":1}
,"entry":{"ftn":1,"exists":1,"syntax":1,"value":1,"global":1,"fec_addr":1,"fec_prefix_len":1,"opcode":1,"(hal_mpls_push":1,"index":1}
,"table":{"entry":1,"adds":1,"protocol":1}
,"exists":{"request":1}
,"request":{"ignored":1}
,"ignored":{"function":1}
,"used":{"modify":1,"lsp":1,"carry":1,"fec":1,"vpn_nexthop_addr":1,"vpn":1}
,"modify":{"existing":1}
,"existing":{"entry":1}
,"syntax":{"int":1}
,"int":{"hal_mpls_ftn_entry_add":1}
,"(int":{"vrf":1}
,"vrf":{"u_char":1,"vrf":1,"add":1}
,"u_char":{"protocol":1,"*fec_prefix_len":1,"*dscp_in":1,"ftn_type":1,"lsp_type)":1}
,"protocol":{"struct":1,"identifier":1}
,"struct":{"hal_in4_addr":1,"if_ident":1,"hal_mpls_diffserv":1,"mpls_owner_fwd":1}
,"hal_in4_addr":{"*fec_addr":1,"*tunnel_nhop":1,"*vpn_nhop":1}
,"*fec_addr":{"u_char":1}
,"*fec_prefix_len":{"u_char":1}
,"*dscp_in":{"u_int32_t":1}
,"u_int32_t":{"*tunnel_label":1,"*vpn_label":1,"*tunnel_id":1,"*qos_resource_id":1,"nhlfe_ix":1,"ftn_ix":1,"bypass_ftn_ix":1}
,"*tunnel_label":{"struct":1}
,"*tunnel_nhop":{"struct":1}
,"if_ident":{"*tunnel_if_ident":1,"*vpn_if_ident":1}
,"*tunnel_if_ident":{"u_int32_t":1}
,"*vpn_label":{"struct":1}
,"*vpn_nhop":{"struct":1}
,"*vpn_if_ident":{"u_int32_t":1}
,"*tunnel_id":{"u_int32_t":1}
,"*qos_resource_id":{"ifdef":1}
,"ifdef":{"have_diffserv":1}
,"have_diffserv":{"struct":1}
,"hal_mpls_diffserv":{"*diffserv_info":1}
,"*diffserv_info":{"endif":1}
,"endif":{"\u002F*have_diffserv":1}
,"\u002F*have_diffserv":{"*\u002Fchar":1}
,"*\u002Fchar":{"opcode":1}
,"opcode":{"u_int32_t":1,"opcode":1,"applied":1}
,"nhlfe_ix":{"u_int32_t":1,"next-hop":1}
,"ftn_ix":{"u_char":1,"ftn":1}
,"ftn_type":{"struct":1,"ftn":1}
,"mpls_owner_fwd":{"*owner":1}
,"*owner":{"u_int32_t":1}
,"bypass_ftn_ix":{"u_char":1,"bypass":1}
,"lsp_type)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vrf":1,"none":1}
,"add":{"entry":1}
,"value":{"hal_mpls_global_ftn_table":1,"may":1,"hal_mpls_ftn_add_err":1}
,"hal_mpls_global_ftn_table":{"table":1}
,"global":{"ftn":1}
,"identifier":{"entry":1}
,"fec_addr":{"address":1}
,"address":{"fec":1,"tunnel":1,"vpn":1}
,"fec":{"corresponding":1,"dscp_in":1,"tunnel_nexthop_if":1}
,"corresponding":{"ftn":1}
,"fec_prefix_len":{"length":1}
,"length":{"prefix":1}
,"prefix":{"fec":1}
,"dscp_in":{"dscp":1}
,"dscp":{"code":1}
,"code":{"point":1}
,"point":{"tunnel_label":1}
,"tunnel_label":{"tunnel":1}
,"tunnel":{"lsp":1,"label":1,"qos_resource_id":1}
,"lsp":{"label":1,"next-hop":1,"vpn_label":1,"type":1,"types":1}
,"label":{"lower":1,"tunnel":1,"used":1,"(vc\u002Fvrf":1,"forwarding":1}
,"lower":{"order":1}
,"order":{"bits":1}
,"bits":{"used":1}
,"carry":{"layer":1}
,"layer":{"2\u002Flayer":1}
,"2\u002Flayer":{"vpn":1}
,"vpn":{"labels":1,"(vc\u002Fvrf)":1}
,"labels":{"tunnel_nexthop_addr":1}
,"tunnel_nexthop_addr":{"address":1}
,"next-hop":{"used":1,"label":1}
,"tunnel_nexthop_if":{"nightspot":1}
,"nightspot":{"interface":1}
,"interface":{"tunnel":1,"used":1}
,"vpn_label":{"inner":1}
,"inner":{"label":1}
,"(vc\u002Fvrf":{"label)":1}
,"label)":{"lower":1}
,"vpn_nexthop_addr":{"address":1}
,"(vc\u002Fvrf)":{"peer":1}
,"peer":{"(only":1,"optional":1}
,"(only":{"required":1,"primary":1}
,"required":{"vc\u002Fvrf":1}
,"vc\u002Fvrf":{"lsps)":1,"lsps":1}
,"lsps)":{"vpn_outgoing_if":1}
,"vpn_outgoing_if":{"outgoing":1}
,"outgoing":{"interface":1}
,"optional":{"parameter":1}
,"parameter":{"required":1}
,"lsps":{"may":1}
,"may":{"null":1,"following":1}
,"null":{"tunnel_id":1}
,"tunnel_id":{"tunnel":1}
,"qos_resource_id":{"qos":1}
,"qos":{"resource":1}
,"resource":{"tunnel_ds_info":1}
,"tunnel_ds_info":{"diffserv":1}
,"diffserv":{"information":1}
,"information":{"ftn":1}
,"applied":{"ftn":1}
,"(hal_mpls_push":{"hal_mpls_push_and_lookup":1}
,"hal_mpls_push_and_lookup":{"hal_mpls_dlvr_to_ip)":1}
,"hal_mpls_dlvr_to_ip)":{"nhlfe_ix":1}
,"forwarding":{"entry":1}
,"index":{"ftn_ix":1,"ftn_type":1,"lsp_type":1}
,"type":{"owner":1,"bypass_ftn_ix":1,"value":1,"supported)":1}
,"owner":{"mpls":1,"type":1}
,"mpls":{"owner":1}
,"bypass":{"ftn":1}
,"lsp_type":{"lsp":1}
,"following":{"lsp_type_primary":1}
,"lsp_type_primary":{"lsp_type_secondary":1}
,"lsp_type_secondary":{"lsp_type_backup":1}
,"lsp_type_backup":{"lsp_type_bypass":1}
,"lsp_type_bypass":{"forwarder":1}
,"forwarder":{"support":1}
,"support":{"multiple":1}
,"multiple":{"entries":1,"lsp":1}
,"entries":{"(only":1}
,"primary":{"lsp":1}
,"supported)":{"multiple":1}
,"types":{"turned":1}
,"turned":{"change":1}
,"change":{"define":1}
,"define":{"have_mpls_install_bk_lsp":1}
,"have_mpls_install_bk_lsp":{"undef":1,"nsm_mpls.c":1}
,"undef":{"have_mpls_install_bk_lsp":1}
,"nsm_mpls.c":{"file":1}
,"file":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"hal_mpls_ftn_add_err":{"function":1}
,"fails":{"hal_success":1}
,"hal_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
