var pairs =
{
"enable":{"label":1,"label-switching":1,"primary":1,"rsvp":1,"policer":1}
,"label":{"switching":1,"switched":1}
,"switching":{"-minimal":1,"interface":1}
,"-minimal":{"configuration":1}
,"configuration":{"establish":1,"setup":1,"-nsm":1}
,"establish":{"trunk":1}
,"trunk":{"system":1,"ingress":1,"enable":1,"enter":1,"mode":1,"(config-trunk)":1,"programed":1}
,"system":{"configure":1}
,"configure":{"diffserv-te":1,"trunk":1,"bandwidth":1,"terminal":1,"mode":1,"explicit":1}
,"diffserv-te":{"builds":1}
,"builds":{"support":1}
,"support":{"enable":1}
,"label-switching":{"rsvp-te":1,"enable":1}
,"rsvp-te":{"participating":1}
,"participating":{"interfaces":1}
,"interfaces":{"configure":1}
,"ingress":{"router":1,"ler":1}
,"router":{"best":1,"along":1,"looking":1}
,"best":{"available":1,"nexthop":1}
,"available":{"igp":1,"router":1,"routing":1}
,"igp":{"path":1}
,"path":{"configure":1,"(lsp)":1,"chosen":1,"enter":1,"mode":1,"strict":1,"loose":1,"mypath":1,"used":1}
,"bandwidth":{"needs":1,"100m":1,"(in":1,"per":1,"10m":1,"bits":1}
,"needs":{"trunk":1}
,"primary":{"policer":1,"path":1,"bandwidth":1}
,"policer":{"example":1,"enable":1,"trunk":1}
,"example":{"label":1}
,"switched":{"path":1}
,"(lsp)":{"configured":1}
,"configured":{"using":1}
,"using":{"minimal":1,"best":1}
,"minimal":{"configuration":1}
,"setup":{"using":1}
,"nexthop":{"available":1}
,"along":{"path":1}
,"chosen":{"previous":1}
,"previous":{"router":1}
,"looking":{"best":1}
,"routing":{"table":1}
,"table":{"topology":1}
,"topology":{"minimal":1}
,"-nsm":{"configure":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"interface":1,"path":1,"trunk":1}
,"mode":{"(config)":1,"(config-if)":1,"-rsvp-te":1,"(config-path)":1,"configure":1,"(config-trunk)":1}
,"(config)":{"interface":1,"rsvp-path":1,"rsvp-trunk":1}
,"interface":{"eth0":1,"mode":1,"(config-if)":1}
,"eth0":{"enter":1,"(config-if)":1}
,"(config-if)":{"address":1,"label-switching":1,"enable-rsvp":1,"bandwidth":1,"reservable-bandwidth":1,"exit":1}
,"address":{"10.10.23.63\u002F24":1,"interface":1}
,"10.10.23.63\u002F24":{"address":1}
,"enable-rsvp":{"enable":1}
,"rsvp":{"message":1,"path":1,"trunk":1}
,"message":{"exchange":1}
,"exchange":{"interface":1}
,"100m":{"specify":1}
,"specify":{"maximum":1,"rsvp":1,"ipv4":1}
,"maximum":{"bandwidth":1,"reservable":1}
,"(in":{"bits":1}
,"bits":{"per":1}
,"per":{"second)":1,"interface":1,"second":1}
,"second)":{"used":1}
,"used":{"interface":1,"(config-trunk)":1}
,"reservable-bandwidth":{"70m":1}
,"70m":{"specify":1}
,"reservable":{"bandwidth":1}
,"exit":{"exit":1,"interface":1,"path":1,"trunk":1}
,"-rsvp-te":{"configure":1}
,"rsvp-path":{"mypath":1}
,"mypath":{"create":1,"specify":1}
,"create":{"rsvp":1}
,"(config-path)":{"10.10.23.60":1,"10.10.21.90":1,"exit":1}
,"10.10.23.60":{"strict":1}
,"strict":{"configure":1,"hop":1}
,"explicit":{"route":1}
,"route":{"path":1}
,"hop":{"(config-path)":1}
,"10.10.21.90":{"loose":1}
,"loose":{"configure":1,"hop":1}
,"rsvp-trunk":{"create":1}
,"(config-trunk)":{"primary":1,"192.168.0.90":1,"exit":1}
,"10m":{"reserve":1}
,"reserve":{"bandwidth":1}
,"second":{"current":1}
,"current":{"trunk":1}
,"192.168.0.90":{"specify":1}
,"ipv4":{"egress":1}
,"egress":{"(destination":1}
,"(destination":{"point)":1}
,"point)":{"lsp":1}
,"lsp":{"(config-trunk)":1}
,"programed":{"hardware":1}
,"hardware":{"ingress":1}
,"ler":{"(config-trunk)":1}
}
;Search.control.loadWordPairs(pairs);
