var pairs =
{
"administrative":{"group":1,"groups":1}
,"group":{"constraints":1,"link":1}
,"constraints":{"configure":1,"(also":1}
,"configure":{"administrative":1,"support":1,"required":1}
,"(also":{"known":1}
,"known":{"color":1}
,"color":{"constraints)":1}
,"constraints)":{"level-1":1}
,"level-1":{"level-2":1}
,"level-2":{"l1-l2":1}
,"l1-l2":{"configure":1}
,"support":{"required":1}
,"required":{"admin":1,"administrative":1}
,"admin":{"groups":1,"group":1}
,"groups":{"nsm":1,"participating":1,"used":1}
,"nsm":{"participating":1}
,"participating":{"routers":1,"interfaces":1}
,"routers":{"configure":1}
,"interfaces":{"configuration":1}
,"configuration":{"example":1}
,"example":{"forces":1}
,"forces":{"primary":1}
,"primary":{"lsp":1}
,"lsp":{"setup":1,"mpls-te":1}
,"setup":{"links":1}
,"links":{"belong":1}
,"belong":{"either":1}
,"either":{"admin":1}
,"link":{"belong":1}
,"used":{"setting":1}
,"setting":{"lsp":1}
,"mpls-te":{"topology":1}
}
;Search.control.loadWordPairs(pairs);
