var pairs =
{
"enable-igp-shortcut":{"command":1,"parameters":1}
,"command":{"enable":1,"syntax":1,"mode":1}
,"enable":{"interior":1}
,"interior":{"gateway":1}
,"gateway":{"protocol":1}
,"protocol":{"(igp)":1}
,"(igp)":{"shortcut":1}
,"shortcut":{"igp":1,"link-state":1,"command":1}
,"igp":{"shortcut":1}
,"link-state":{"igps":1}
,"igps":{"calculate":1}
,"calculate":{"routes":1}
,"routes":{"forward":1}
,"forward":{"traffic":1}
,"traffic":{"tunnels":1}
,"tunnels":{"configured":1}
,"configured":{"disable-igp-shortcut":1}
,"disable-igp-shortcut":{"disable":1}
,"disable":{"igp":1}
,"syntax":{"enable-igp-shortcut":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"trunk":1,"example":1}
,"trunk":{"mode":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"rsvp-trunk":1}
,"rsvp-trunk":{"mytrunk":1}
,"mytrunk":{"(config-trunk)":1}
,"(config-trunk)":{"enable-igp-shortcut":1}
}
;Search.control.loadWordPairs(pairs);
