var pairs =
{
"ospf6_get_virt_if_instid":{"function":1,"(char":1}
,"function":{"gets":1,"fails":1,"succeeds":1}
,"gets":{"local":1}
,"local":{"interface":1}
,"interface":{"instance":1,"syntax":1,"return":1}
,"instance":{"identifier":1}
,"identifier":{"assigned":1,"ipv4":1,"originating":1,"ospfv3":1}
,"assigned":{"ospfv3":1}
,"ospfv3":{"process":1,"virtual":1}
,"process":{"given":1,"tag":1}
,"given":{"ospfv3":1}
,"virtual":{"interface":1}
,"syntax":{"int":1}
,"int":{"ospf6_get_virt_if_instid":1,"*ret)":1}
,"(char":{"*tag":1}
,"*tag":{"struct":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"area_id":1,"router_id":1}
,"area_id":{"struct":1,"area":1}
,"router_id":{"int":1,"router":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"tag":1,"ret":1}
,"tag":{"ospfv3":1,"area_id":1}
,"area":{"identifier":1}
,"ipv4":{"address":1}
,"address":{"format":1}
,"format":{"router_id":1}
,"router":{"identifier":1,"output":1}
,"originating":{"router":1}
,"output":{"parameters":1}
,"ret":{"local":1}
,"return":{"values":1}
,"values":{"ospf6_api_get_error":1}
,"ospf6_api_get_error":{"function":1}
,"fails":{"ospf6_api_get_success":1}
,"ospf6_api_get_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
