var pairs =
{
"isis_cspf_set":{"function":1,"(u_int32_t":1,"isis_cspf_unset":1}
,"function":{"creates":1}
,"creates":{"is-is":1}
,"is-is":{"cspf":1,"instance":1}
,"cspf":{"server":1}
,"server":{"syntax":1}
,"syntax":{"int":1}
,"int":{"isis_cspf_set":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1,"tag":1}
,"char":{"*tag)":1}
,"*tag)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1,"isis_api_set_err_vr_not_exist":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"tag":{"is-is":1,"output":1,"isis_api_set_err_te_not_enabled":1}
,"instance":{"area":1,"exist":1}
,"area":{"tag":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"isis_api_set_err_vr_not_exist":{"exist":1}
,"exist":{"isis_api_set_err_instance_not_exist":1,"given":1}
,"isis_api_set_err_instance_not_exist":{"is-is":1}
,"given":{"tag":1,"level":1}
,"isis_api_set_err_te_not_enabled":{"given":1}
,"level":{"configured":1}
,"configured":{"te-enabled":1}
,"te-enabled":{"isis_api_set_success":1}
,"isis_api_set_success":{"call":1}
,"call":{"successful":1,"failed":1}
,"successful":{"isis_api_set_err_cspf_instance_exist":1}
,"isis_api_set_err_cspf_instance_exist":{"isis_api_set_err_cspf_enable_failed":1}
,"isis_api_set_err_cspf_enable_failed":{"call":1}
,"failed":{"reasons":1}
,"reasons":{"isis_api_set_err_cspf_disable_failed":1,"isis_cspf_set":1}
,"isis_api_set_err_cspf_disable_failed":{"call":1}
}
;Search.control.loadWordPairs(pairs);
