var pairs =
{
"cfm_tput_reception":{"structure":1,"{\u002F*back":1}
,"structure":{"onmd\u002Fcfm\u002Fcfm_tst.h":1,"tst_while":1,"*\u002Fstruct":1}
,"onmd\u002Fcfm\u002Fcfm_tst.h":{"defines":1}
,"defines":{"throughput":1}
,"throughput":{"reception":1,"frame_rx_count":1}
,"reception":{"member":1}
,"member":{"description":1}
,"description":{"mep":1}
,"mep":{"back":1,"structure":1}
,"back":{"pointer":1}
,"pointer":{"mep":1}
,"tst_while":{"timer":1}
,"timer":{"thread":1}
,"thread":{"periodically":1,"*tst_while":1}
,"periodically":{"sending":1}
,"sending":{"tst":1}
,"tst":{"frame":1}
,"frame":{"tput_active":1,"count":1,"offset":1,"*\u002Fstruct":1}
,"tput_active":{"active":1,"u_int8_t":1}
,"active":{"throughput":1}
,"frame_rx_count":{"receive":1,"\u002F*storing":1}
,"receive":{"frame":1}
,"count":{"receive_bytes":1}
,"receive_bytes":{"bytes":1,"[cfm_max_tst_tput_frames]":1}
,"bytes":{"received":1}
,"received":{"using":1}
,"using":{"sequence":1}
,"sequence":{"number":1}
,"number":{"frame":1}
,"offset":{"struct":1,"*\u002Fu_int16_t":1}
,"struct":{"cfm_tput_reception":1}
,"{\u002F*back":{"pointer":1}
,"*\u002Fstruct":{"cfm_mep":1,"thread":1}
,"cfm_mep":{"*mep":1}
,"*mep":{"\u002F*timer":1}
,"\u002F*timer":{"thread":1}
,"*tst_while":{"u_int8_t":1}
,"u_int8_t":{"tput_active":1,"frame_rx_count":1}
,"\u002F*storing":{"bytes":1}
,"*\u002Fu_int16_t":{"receive_bytes":1}
}
;Search.control.loadWordPairs(pairs);
