var pairs =
{
"secondary":{"cspf-retry-timer":1}
,"cspf-retry-timer":{"command":1,"<1-600>":1,"parameters":1}
,"command":{"specify":1,"remove":1,"syntax":1,"mode":1}
,"specify":{"time":1}
,"time":{"retry":1}
,"retry":{"cspf":1}
,"cspf":{"carry":1,"calculations":1}
,"carry":{"request":1}
,"request":{"received":1}
,"received":{"rsvp":1}
,"rsvp":{"parameter":1}
,"parameter":{"command":1}
,"remove":{"configuration":1}
,"configuration":{"command":1,"defined":1}
,"syntax":{"secondary":1}
,"<1-600>":{"secondary":1,"timeout":1}
,"parameters":{"<1-600>":1}
,"timeout":{"successive":1}
,"successive":{"retries":1}
,"retries":{"seconds":1}
,"seconds":{"default":1}
,"default":{"default":1,"retry-timer":1}
,"retry-timer":{"configuration":1}
,"defined":{"cspf":1}
,"calculations":{"value":1}
,"value":{"command":1}
,"mode":{"trunk":1,"examples":1}
,"trunk":{"mode":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"rsvp-trunk":1}
,"rsvp-trunk":{"(config-trunk)":1}
,"(config-trunk)":{"secondary":1}
}
;Search.control.loadWordPairs(pairs);
