var pairs =
{
"configure":{"terminal":1,"mode":1,"interface":1,"multi":1,"portal":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"interface":1}
,"mode":{"(config)":1,"(config-if)":1,"trunk":1,"active":1,"configure":1,"automatic":1}
,"(config)":{"bridge":1,"vlan":1,"interface":1,"int":1,"mlag":1}
,"bridge":{"protocol":1,"(config)":1,"state":1,"group":1}
,"protocol":{"ieee":1}
,"ieee":{"vlan-bridge":1}
,"vlan-bridge":{"create":1}
,"create":{"stp":1,"vlans":1}
,"stp":{"bridge":1}
,"vlan":{"2-100":1,"enable":1,"identifiers":1}
,"2-100":{"bridge":1}
,"state":{"enable":1}
,"enable":{"create":1,"vlan":1,"link":1}
,"vlans":{"100":1}
,"100":{"(config)":1}
,"interface":{"eth2":1,"mode":1,"layer":1,"bridge":1,"trunk":1,"(config-if)":1,"channel":1,"bound":1,"connects":1}
,"eth2":{"enter":1}
,"(config-if)":{"switchport":1,"bridge-group":1,"channel-group":1,"exit":1,"mlag":1}
,"switchport":{"configure":1,"mode":1,"trunk":1}
,"layer":{"(config-if)":1}
,"bridge-group":{"associate":1}
,"associate":{"interface":1}
,"group":{"(config-if)":1,"enable":1}
,"trunk":{"switching":1,"mode":1,"allowed":1}
,"switching":{"characteristics":1}
,"characteristics":{"interface":1}
,"allowed":{"vlan":1}
,"identifiers":{"interface":1}
,"channel-group":{"mode":1}
,"active":{"add":1}
,"add":{"interface":1}
,"channel":{"group":1,"port-channel":1}
,"link":{"aggregation":1}
,"aggregation":{"selected":1,"local":1,"features":1}
,"selected":{"aggregation":1}
,"local":{"system":1}
,"system":{"(config-if)":1,"number":1,"(config-mlag)":1,"connected":1}
,"exit":{"exit":1,"interface":1,"enter":1}
,"int":{"po1":1}
,"po1":{"enter":1}
,"mlag":{"assign":1,"instance":1,"configuration":1,"domain":1}
,"assign":{"mlag-id":1,"portal":1}
,"mlag-id":{"port":1}
,"port":{"channel":1}
,"port-channel":{"interface":1}
,"bound":{"mlag":1}
,"instance":{"(config-if)":1}
,"configuration":{"enters":1,"mode":1}
,"enters":{"mlag":1}
,"multi":{"chassis":1}
,"chassis":{"link":1}
,"features":{"(config-mlag)":1}
,"(config-mlag)":{"portal-system-number":1,"portal-name":1,"portal-priority":1,"portal-address":1,"portal-topology":1,"conversation":1,"intra-portal-link":1,"exit":1}
,"portal-system-number":{"assign":1}
,"portal":{"system":1,"address":1,"topology":1,"systems":1}
,"number":{"used":1}
,"used":{"configure":1}
,"address":{"helps":1}
,"helps":{"identify":1}
,"identify":{"mlag":1}
,"domain":{"(config-mlag)":1}
,"portal-name":{"test1":1}
,"test1":{"specify":1}
,"specify":{"locally":1,"priority":1}
,"locally":{"significant":1}
,"significant":{"name":1}
,"name":{"distributed":1}
,"distributed":{"relay":1}
,"relay":{"(config-mlag)":1}
,"portal-priority":{"specify":1}
,"priority":{"value":1}
,"value":{"associated":1}
,"associated":{"portal":1}
,"portal-address":{"0000.0000.0001":1}
,"0000.0000.0001":{"portal":1}
,"portal-topology":{"2-portal":1}
,"2-portal":{"portal":1}
,"topology":{"(config-mlag)":1}
,"conversation":{"alloc-mode":1,"allocation":1}
,"alloc-mode":{"auto":1}
,"auto":{"set5":1}
,"set5":{"conversation":1}
,"allocation":{"mode":1}
,"automatic":{"(config-mlag)":1}
,"intra-portal-link":{"eth1":1}
,"eth1":{"neighbor-portal-system":1}
,"neighbor-portal-system":{"configure":1}
,"connects":{"two":1}
,"two":{"portal":1}
,"systems":{"neighbor":1}
,"neighbor":{"portal":1}
,"connected":{"ipp":1}
,"ipp":{"(config-mlag)":1}
}
;Search.control.loadWordPairs(pairs);
