var pairs =
{
"bridge":{"spbv":1,"(<1-32>":1,"identifier":1,"auto":1}
,"spbv":{"mode":1}
,"mode":{"command":1,"(auto":1,"spb":1,"example":1,"manual":1}
,"command":{"shortest":1,"syntax":1,"mode":1}
,"shortest":{"path":1}
,"path":{"vlan":1}
,"vlan":{"identifier":1}
,"identifier":{"(spvid)":1,"backbone":1}
,"(spvid)":{"allocation":1}
,"allocation":{"mode":1}
,"syntax":{"bridge":1}
,"(<1-32>":{"backbone)":1}
,"backbone)":{"spbv":1}
,"(auto":{"manual)":1}
,"manual)":{"parameters":1}
,"parameters":{"<1-32>":1}
,"<1-32>":{"bridge":1}
,"backbone":{"backbone":1,"bridge":1}
,"auto":{"automatically":1}
,"automatically":{"allocate":1}
,"allocate":{"spvids":1}
,"spvids":{"(default":1,"command":1}
,"(default":{"setting)":1}
,"setting)":{"manual":1}
,"manual":{"manually":1}
,"manually":{"allocate":1}
,"spb":{"mode":1,"configuration":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"spb":1}
,"configuration":{"(config-spb)":1}
,"(config-spb)":{"bridge":1}
}
;Search.control.loadWordPairs(pairs);
