var pairs =
{
"show":{"ldp":1}
,"ldp":{"advertise-labels":1}
,"advertise-labels":{"command":1,"parameter":1,"advertisement":1}
,"command":{"display":1,"syntax":1,"mode":1,"show":1}
,"display":{"access":1}
,"access":{"list":1}
,"list":{"ldp":1}
,"syntax":{"show":1}
,"parameter":{"none":1}
,"none":{"command":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"following":1}
,"following":{"sample":1}
,"sample":{"output":1}
,"output":{"show":1}
,"advertisement":{"spec":1}
,"spec":{"prefix":1}
,"prefix":{"acl":1}
,"acl":{"=pfx1":1}
,"=pfx1":{"peer":1,"prevent":1}
,"peer":{"acl":1}
,"prevent":{"distribution":1}
,"distribution":{"assigned":1}
,"assigned":{"labels":1}
}
;Search.control.loadWordPairs(pairs);
