var pairs =
{
"service":{"datalink":1,"association":1}
,"datalink":{"command":1,"service":1,"ifname":1,"eth1":1}
,"command":{"configure":1,"syntax":1,"mode":1}
,"configure":{"datalink":1,"terminal":1}
,"association":{"maintenance":1}
,"maintenance":{"entity":1}
,"entity":{"group":1}
,"group":{"end":1}
,"end":{"point":1}
,"point":{"(mep)":1,"(mip)":1}
,"(mep)":{"intermediate":1}
,"intermediate":{"point":1}
,"(mip)":{"command":1}
,"syntax":{"service":1}
,"ifname":{"parameters":1,"name":1}
,"parameters":{"ifname":1}
,"name":{"datalink":1}
,"mode":{"itut":1,"examples":1}
,"itut":{"mode":1,"meg":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"itut":1}
,"meg":{"new12":1}
,"new12":{"level":1}
,"level":{"(config-itut-meg)":1}
,"(config-itut-meg)":{"mep-id":1}
,"mep-id":{"(config-itut-mp)":1}
,"(config-itut-mp)":{"service":1}
}
;Search.control.loadWordPairs(pairs);
