var pairs =
{
"mstp_api_get_port_path_cost_method":{"function":1,"(char":1}
,"function":{"gets":1,"succeeds":1}
,"gets":{"type":1}
,"type":{"path":1}
,"path":{"cost":1}
,"cost":{"recalculation":1}
,"recalculation":{"(automatic":1,"automatic":1}
,"(automatic":{"manual)":1}
,"manual)":{"syntax":1}
,"syntax":{"int":1}
,"int":{"mstp_api_get_port_path_cost_method":1}
,"(char":{"*name":1}
,"*name":{"char":1}
,"char":{"*ifname":1}
,"*ifname":{"u_int16_t":1}
,"u_int16_t":{"svid":1}
,"svid":{"u_int8_t":1,"svlan":1}
,"u_int8_t":{"*pathcost_method)":1}
,"*pathcost_method)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"name":1,"pathcost_method":1}
,"name":{"bridge":1,"ifname":1,"svid":1}
,"bridge":{"name":1,"found":1}
,"ifname":{"interface":1}
,"interface":{"name":1,"found":1}
,"svlan":{"identifier":1}
,"identifier":{"output":1}
,"output":{"parameters":1}
,"pathcost_method":{"type":1}
,"automatic":{"manual":1}
,"manual":{"return":1}
,"return":{"values":1}
,"values":{"result_ok":1}
,"result_ok":{"function":1}
,"succeeds":{"mstp_err_interface_not_found":1}
,"mstp_err_interface_not_found":{"specified":1}
,"specified":{"interface":1,"bridge":1,"port":1}
,"found":{"mstp_err_bridge_not_found":1,"mstp_err_port_not_found":1}
,"mstp_err_bridge_not_found":{"specified":1}
,"mstp_err_port_not_found":{"specified":1}
,"port":{"found":1}
}
;Search.control.loadWordPairs(pairs);
