var pairs =
{
"snmp":{"enable\u002Fdisable":1,"during":1,"running":1,"smux":1,"returns":1,"mibs":1,"files":1,"operations":1,"agent":1,"callback":1,"callbacks":1,"path":1}
,"enable\u002Fdisable":{"mibs":1}
,"mibs":{"snmp":1,"supported":1,"counters":1}
,"during":{"initial":1,"configuration":1}
,"initial":{"configuration":1}
,"configuration":{"options":1,"script":1,"zebos-xp":1}
,"options":{"enable\u002Fdisable":1,"either":1}
,"running":{"initial":1,"snmp":1,"returns":1,".\u002Fsnmpd":1}
,"script":{"example":1}
,"example":{"option":1,"bgp":1,"implementation":1,"integer":1}
,"option":{"--with-mib-modules=\u0022":1,"running":1}
,"--with-mib-modules=\u0022":{"smux":1}
,"smux":{"enable":1,"during":1,"agentx":1,"value":1,"return":1}
,"enable":{"snmp":1}
,"zebos-xp":{"mibii\u002Finterface":1,"mib":1,"support":1,"uses":1,"supports":1,"supported":1,"smux":1,"modules":1}
,"mibii\u002Finterface":{"options":1}
,"either":{"enabled":1}
,"enabled":{"disabled":1}
,"disabled":{"values":1}
,"values":{"nsm":1,"specifically":1,"linux":1}
,"nsm":{"snmpc":1,"running":1,"implementation":1}
,"snmpc":{"viewer":1}
,"viewer":{"return":1}
,"return":{"nsm\u0027s":1,"value":1}
,"nsm\u0027s":{"implementation":1}
,"implementation":{"mibii\u002Finterfaces":1,"hal_if_counters":1}
,"mibii\u002Finterfaces":{"mibii\u002Fsystem_mib":1}
,"mibii\u002Fsystem_mib":{"net-snmp\u0027s":1,"nsm":1}
,"net-snmp\u0027s":{"default":1}
,"default":{"module":1,"values":1,"snmp":1}
,"module":{"nsm":1}
,"returns":{"nsm":1,"net-snmp\u0027s":1}
,"specifically":{"override":1}
,"override":{"default":1}
,"linux":{"-tcp":1}
,"-tcp":{"system_mib":1}
,"system_mib":{"option":1}
,".\u002Fsnmpd":{"snmp":1}
,"supported":{"zebos-xp":1,"hardware":1}
,"mib":{"files":1,"file":1,"zebos-xp":1,"structure":1}
,"files":{"located":1,"\u002Fbgpd\u002Fbgp_snmp.h":1}
,"located":{"respective":1,"protocol":1}
,"respective":{"protocol":1}
,"protocol":{"directory":1}
,"directory":{"example":1,"protocolname_snmp.h":1}
,"bgp":{"find":1}
,"find":{"mib":1,"snmp":1}
,"file":{"\u002Fbgpd\u002Fbgp4-mib.txt":1}
,"\u002Fbgpd\u002Fbgp4-mib.txt":{"corresponding":1}
,"corresponding":{"snmp":1}
,"protocolname_snmp.h":{"protocolname_snmp.c":1}
,"protocolname_snmp.c":{"example":1}
,"\u002Fbgpd\u002Fbgp_snmp.h":{"\u002Fbgpd\u002Fbgp_snmp.c":1}
,"\u002Fbgpd\u002Fbgp_snmp.c":{"rmon":1}
,"rmon":{"mib":1,"zebos-xp":1,"related":1}
,"support":{"(hc-rmon":1,"brdc_pkts_rcv":1,"counters":1}
,"(hc-rmon":{"bit":1}
,"bit":{"counters":1}
,"counters":{"rfc":1,"interface-related":1,"zebos-xp":1,"defined":1,"pkts_65_127_octets":1,"hal_if_counters":1,"value":1,"depends":1,"supported":1}
,"rfc":{"2819":1,"2020":1}
,"2819":{"snmp":1,"basis":1,"example":1}
,"operations":{"rmon":1}
,"uses":{"rfc":1}
,"basis":{"counters":1}
,"interface-related":{"counters":1}
,"supports":{"wide":1,"smux":1}
,"wide":{"range":1}
,"range":{"consist":1}
,"consist":{"counters":1}
,"defined":{"rfc":1,"mib-related":1}
,"2020":{"section":1,"apart":1}
,"section":{"3.3.6":1}
,"3.3.6":{"rfc":1}
,"hal_if_counters":{"function":1,"bit":1}
,"function":{"support":1,"parameters":1,"(writemethod)":1,"oid":1}
,"brdc_pkts_rcv":{"brdc_pkts_sent":1}
,"brdc_pkts_sent":{"defined":1}
,"mib-related":{"entry":1}
,"entry":{"interface":1,"variablen":1}
,"interface":{"rfc":1,"mib":1}
,"apart":{"support":1}
,"pkts_65_127_octets":{"pkts_128_255_octets":1}
,"pkts_128_255_octets":{"part":1}
,"part":{"standard":1,"rmon":1}
,"standard":{"interface":1}
,"structure":{"part":1,"completed":1}
,"related":{"mibs":1}
,"value":{"counters":1,"action":1,"variable":1,"example":1,"callback":1}
,"depends":{"underlying":1}
,"underlying":{"hardware":1}
,"hardware":{"possibly":1,"vice":1}
,"possibly":{"extra":1}
,"extra":{"counters":1}
,"vice":{"versa":1}
,"versa":{"default":1}
,"agent":{"zebos-xp":1,"integrate":1,"supports":1}
,"agentx":{"requires":1,"protocol":1}
,"requires":{"explicit":1}
,"explicit":{"enabling":1}
,"enabling":{"explain":1}
,"explain":{"snmp":1}
,"callback":{"function":1}
,"parameters":{"parameters":1,"get\u002Fgetnext":1,"snmp":1}
,"get\u002Fgetnext":{"snmp":1}
,"callbacks":{"follows":1}
,"follows":{"struct":1,"int":1}
,"struct":{"variable":1}
,"variable":{"entry":1,"u_int32_t":1,"used":1,"address":1}
,"variablen":{"array":1}
,"array":{"object":1,"oid":1}
,"object":{"note":1,"u_int32_t":1}
,"note":{"name":1}
,"name":{"field":1}
,"field":{"structure":1}
,"completed":{"fully":1}
,"fully":{"qualified":1}
,"qualified":{"oid":1}
,"oid":{"pretending":1,"*name":1,"request":1,"int":1,"struct":1}
,"pretending":{"prefix":1}
,"prefix":{"common":1}
,"common":{"whole":1}
,"whole":{"array":1}
,"*name":{"oid":1}
,"request":{"size_t":1,"(get\u002Fset)":1,"(getnext)":1}
,"size_t":{"*length":1,"*var_len":1,"var_val_len":1,"length":1}
,"*length":{"length":1}
,"length":{"oid":1,"(in":1,"value":1,"sizeof":1,"length":1}
,"int":{"exact":1,"action":1}
,"exact":{"flag":1,"request":1}
,"flag":{"indicate":1}
,"indicate":{"whether":1}
,"whether":{"exact":1}
,"(get\u002Fset)":{"inexact":1}
,"inexact":{"request":1}
,"(getnext)":{"size_t":1}
,"*var_len":{"length":1}
,"(in":{"bytes)":1}
,"bytes)":{"answer":1}
,"answer":{"returned":1}
,"returned":{"writemethod":1}
,"writemethod":{"pointer":1}
,"pointer":{"function":1}
,"(writemethod)":{"variable":1}
,"u_int32_t":{"vr_id":1}
,"vr_id":{"virtual":1}
,"virtual":{"router":1}
,"router":{"parameters":1,"imi":1}
,"action":{"variable":1,"commit":1}
,"used":{"smux":1}
,"commit":{"free":1}
,"free":{"u_char":1}
,"u_char":{"*var_val":1,"var_val_type":1,"*statp":1}
,"*var_val":{"value":1}
,"address":{"10.2.2.3":1}
,"10.2.2.3":{"u_char":1}
,"var_val_type":{"type":1}
,"type":{"value":1}
,"integer":{"char":1,"length":1}
,"char":{"addresses":1}
,"addresses":{"size_t":1}
,"var_val_len":{"length":1}
,"sizeof":{"(int)":1}
,"(int)":{"u_char":1}
,"*statp":{"variable":1}
,"imi":{"daemon":1}
,"daemon":{"read\u002Fwrite":1}
,"read\u002Fwrite":{"access":1}
,"access":{"zebos.conf":1,"snmp":1}
,"zebos.conf":{"similar":1}
,"similar":{"access":1}
,"path":{"zebos-xp":1}
,"modules":{"act":1}
,"act":{"subagent":1}
,"subagent":{"snmp":1}
,"integrate":{"third-party":1}
,"third-party":{"snmp":1}
}
;Search.control.loadWordPairs(pairs);
