var pairs =
{
"ce-a-2":{"ce-a-2":1,"configure":1,"(config)":1,"(config-vlan)":1,"(config-if)":1}
,"configure":{"terminal":1,"mode":1,"eth1":1,"eth2":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"vlan":1,"interface":1}
,"mode":{"ce-a-2":1,"hybrid":1}
,"(config)":{"bridge":1,"vlan":1,"interface":1}
,"bridge":{"protocol":1,"ce-a-2":1,"state":1}
,"protocol":{"mstp":1}
,"mstp":{"create":1,"bridge":1}
,"create":{"mstp":1,"vlan":1}
,"vlan":{"database":1,"configure":1,"bridge":1,"associate":1}
,"database":{"enter":1}
,"(config-vlan)":{"vlan":1,"exit":1}
,"state":{"enable":1}
,"enable":{"create":1}
,"associate":{"bridge":1,"eth1":1,"eth2":1}
,"exit":{"exit":1,"vlan":1,"interface":1}
,"interface":{"eth1":1,"mode":1,"ce-a-2":1,"bridge":1,"hybrid":1,"allow":1,"eth2":1}
,"eth1":{"enter":1,"layer-2":1,"interface":1}
,"(config-if)":{"switchport":1,"bridge-group":1,"exit":1}
,"switchport":{"configure":1,"mode":1,"hybrid":1}
,"layer-2":{"interface":1}
,"bridge-group":{"associate":1}
,"hybrid":{"configure":1,"mode":1,"allowed":1}
,"allowed":{"vlan":1}
,"allow":{"vlans":1}
,"vlans":{"ce-a-2":1}
,"eth2":{"enter":1,"layer-2":1,"interface":1}
}
;Search.control.loadWordPairs(pairs);
