var pairs =
{
"multi-topology":{"command":1,"(transition":1,"(level-1":1,"level":1,"levels":1,"ipv6":1,"type":1,"transition":1}
,"command":{"configure":1,"topology":1,"wide":1,"syntax":1,"mode":1}
,"configure":{"isis":1}
,"isis":{"topology":1,"multi-topology":1,"(config-router)":1}
,"topology":{"type":1}
,"type":{"parameter":1,"back":1,"single":1,"applies":1,"transition":1}
,"parameter":{"command":1}
,"back":{"default":1}
,"default":{"type":1,"isis":1}
,"single":{"following":1}
,"following":{"table":1,"example":1}
,"table":{"changing":1}
,"changing":{"method":1}
,"method":{"tlv":1}
,"tlv":{"encodes":1,"narrow":1,"encode":1}
,"encodes":{"spf":1}
,"spf":{"calculates":1,"wide":1,"narrow":1,"calculation":1}
,"calculates":{"decision":1}
,"decision":{"metric-style":1}
,"metric-style":{"command":1}
,"wide":{"spf":1,"tlv":1,"wide":1,"transition":1,"tlvs":1}
,"narrow":{"spf":1,"tlv":1,"(default)":1,"transition":1,"tlvs":1}
,"(default)":{"narrow":1}
,"transition":{"wide":1,"transition":1,"specify":1,"levels":1}
,"tlvs":{"spf":1,"lsp":1,"default":1}
,"calculation":{"wide":1,"narrow":1}
,"encode":{"wide":1,"narrow":1}
,"lsp":{"narrow":1,"command":1}
,"syntax":{"multi-topology":1}
,"(transition":{"multi-topology":1,"parameters":1}
,"(level-1":{"level-1-2":1}
,"level-1-2":{"level-2)":1,"specify":1}
,"level-2)":{"(transition":1}
,"parameters":{"level-1":1}
,"level-1":{"specify":1}
,"specify":{"enable":1,"accept":1}
,"enable":{"multi-topology":1}
,"level":{"level-2":1,"level-1-2":1}
,"level-2":{"specify":1}
,"levels":{"transition":1,"command":1,"(config)":1}
,"accept":{"generate":1}
,"generate":{"is-is":1}
,"is-is":{"ipv6":1}
,"ipv6":{"multi-topology":1,"tlvs":1,"mode":1,"unicast":1}
,"applies":{"levels":1}
,"mode":{"address-family":1,"examples":1}
,"address-family":{"ipv6":1}
,"examples":{"following":1}
,"example":{"configures":1}
,"configures":{"isis":1}
,"(config)":{"router":1}
,"router":{"isis":1}
,"(config-router)":{"address-family":1}
,"unicast":{"(config-router-af)":1}
,"(config-router-af)":{"multi-topology":1}
}
;Search.control.loadWordPairs(pairs);
