var pairs =
{
"nsm_bridge_api_port_proto_process":{"function":1,"(struct":1}
,"function":{"configures":1,"called":1,"succeeds":1}
,"configures":{"protocol":1}
,"protocol":{"handling":1,"constants":1,"hal_proto_rstp":1,"hal_proto_mstp":1,"hal_proto_trill":1,"hal_proto_mmrp":1,"hal_proto_gvrp":1,"hal_proto_mvrp":1,"hal_proto_lacp":1,"hal_proto_dot1x":1,"interface":1,"packets":1,"invalid":1}
,"handling":{"customer":1}
,"customer":{"edge\u002Fcustomer":1}
,"edge\u002Fcustomer":{"network":1}
,"network":{"port":1}
,"port":{"function":1,"authentication":1}
,"called":{"l2protocol":1}
,"l2protocol":{"command":1}
,"command":{"syntax":1}
,"syntax":{"int":1}
,"int":{"nsm_bridge_api_port_proto_process":1}
,"(struct":{"interface":1}
,"interface":{"*ifp":1,"pointer":1,"service":1,"configuration":1}
,"*ifp":{"enum":1}
,"enum":{"hal_l2_proto":1,"hal_l2_proto_process":1,"hal\u002Fl2\u002Fhal_bridge.h":1}
,"hal_l2_proto":{"proto":1,"enum":1}
,"proto":{"enum":1,"protocol":1}
,"hal_l2_proto_process":{"process":1,"enum":1}
,"process":{"bool_t":1,"action":1}
,"bool_t":{"iterate_members":1}
,"iterate_members":{"u_int16_t":1,"whether":1}
,"u_int16_t":{"svid":1}
,"svid":{"u_int8_t":1,"svlan":1}
,"u_int8_t":{"cos_id)":1}
,"cos_id)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"none":1}
,"ifp":{"interface":1}
,"pointer":{"proto":1}
,"constants":{"hal_l2_proto":1,"hal_l2_proto_process":1}
,"hal\u002Fl2\u002Fhal_bridge.h":{"hal_proto_stp":1,"hal_l2_proto_tunnel":1}
,"hal_proto_stp":{"spanning-tree":1}
,"spanning-tree":{"protocol":1}
,"hal_proto_rstp":{"rapid":1}
,"rapid":{"spanning-tree":1}
,"hal_proto_mstp":{"multiple":1}
,"multiple":{"spanning-tree":1,"multicast":1,"vlan":1}
,"hal_proto_trill":{"trill":1}
,"trill":{"hal_proto_gmrp":1}
,"hal_proto_gmrp":{"garp":1}
,"garp":{"multicast":1,"vlan":1}
,"multicast":{"address":1,"routing":1}
,"address":{"registration":1}
,"registration":{"protocol":1}
,"hal_proto_mmrp":{"multiple":1}
,"routing":{"protocol":1}
,"hal_proto_gvrp":{"garp":1}
,"vlan":{"registration":1,"hal_l2_proto_peer":1,"setting":1,"iterate_members":1,"found":1}
,"hal_proto_mvrp":{"multiple":1}
,"hal_proto_lacp":{"link":1}
,"link":{"aggregation":1}
,"aggregation":{"control":1}
,"control":{"protocol":1}
,"hal_proto_dot1x":{"ieee":1}
,"ieee":{"802.1x":1}
,"802.1x":{"port":1}
,"authentication":{"process":1}
,"action":{"protocol":1}
,"hal_l2_proto_tunnel":{"tunnel":1}
,"tunnel":{"specified":1}
,"specified":{"protocol":1}
,"service":{"vlan":1,"(cos)":1}
,"hal_l2_proto_peer":{"peer":1}
,"peer":{"specified":1}
,"setting":{"cannot":1}
,"cannot":{"used":1}
,"used":{"gvrp":1}
,"gvrp":{"mvrp":1}
,"mvrp":{"protocols":1}
,"protocols":{"hal_l2_proto_discard":1}
,"hal_l2_proto_discard":{"discard":1}
,"discard":{"specified":1}
,"packets":{"interface":1}
,"whether":{"iterate":1}
,"iterate":{"members":1}
,"members":{"(lacp":1,"pal_false":1,"svid":1}
,"(lacp":{"only)":1}
,"only)":{"pal_true":1}
,"pal_true":{"iterate":1}
,"pal_false":{"iterate":1}
,"svlan":{"identifier":1}
,"identifier":{"cos_id":1,"output":1}
,"cos_id":{"class":1}
,"class":{"service":1}
,"(cos)":{"identifier":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_bridge_err_notfound":1}
,"nsm_bridge_err_notfound":{"operation":1}
,"operation":{"appropriate":1}
,"appropriate":{"interface":1}
,"configuration":{"nsm_vlan_err_vlan_not_found":1,"nsm_bridge_err_invalid_proto":1}
,"nsm_vlan_err_vlan_not_found":{"vlan":1}
,"found":{"nsm_bridge_err_invalid_mode":1}
,"nsm_bridge_err_invalid_mode":{"operation":1}
,"nsm_bridge_err_invalid_proto":{"protocol":1}
,"invalid":{"result_ok":1}
,"result_ok":{"function":1}
}
;Search.control.loadWordPairs(pairs);
