var pairs =
{
"debug":{"ospf":1,"lsa":1,"maximum":1}
,"ospf":{"lsa":1,"link":1}
,"lsa":{"command":1,"({flooding":1,"flooding":1,"generation":1,"installation":1,"refresh":1,"install":1,"maxage":1,"generate":1}
,"command":{"specify":1,"disable":1,"syntax":1,"mode":1}
,"specify":{"debugging":1}
,"debugging":{"options":1}
,"options":{"ospf":1}
,"link":{"state":1}
,"state":{"advertisements":1}
,"advertisements":{"(lsa)":1}
,"(lsa)":{"troubleshooting":1}
,"troubleshooting":{"parameter":1}
,"parameter":{"command":1}
,"disable":{"function":1}
,"function":{"command":1}
,"syntax":{"debug":1}
,"({flooding":{"generate":1}
,"generate":{"install":1,"debug":1}
,"install":{"maxage":1,"debug":1}
,"maxage":{"refresh}":1,"debug":1}
,"refresh}":{"debug":1,"undebug":1,"parameters":1}
,"undebug":{"ospf":1}
,"parameters":{"flooding":1}
,"flooding":{"debug":1,"generate":1}
,"generation":{"install":1}
,"installation":{"maxage":1}
,"maximum":{"age":1}
,"age":{"processing":1}
,"processing":{"refresh":1}
,"refresh":{"debug":1,"command":1}
,"mode":{"privileged":1,"configure":1,"examples":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"configure":{"mode":1}
,"examples":{"debug":1}
}
;Search.control.loadWordPairs(pairs);
