var pairs =
{
"debug":{"ipv6":1,"ospfv3":1,"packets":1,"detail":1}
,"ipv6":{"ospf":1}
,"ospf":{"packet":1}
,"packet":{"command":1,"debugging":1,"({hello":1,"ls-request":1}
,"command":{"specify":1,"disable":1,"syntax":1,"mode":1}
,"specify":{"packet":1}
,"debugging":{"options":1}
,"options":{"ospfv3":1}
,"ospfv3":{"information":1,"hello":1,"database":1,"link":1}
,"information":{"parameter":1,"command":1}
,"parameter":{"command":1}
,"disable":{"function":1}
,"function":{"command":1}
,"syntax":{"debug":1}
,"({hello":{"ls-request":1}
,"ls-request":{"ls-update":1,"debug":1}
,"ls-update":{"ls-ack":1,"debug":1}
,"ls-ack":{"send":1,"debug":1}
,"send":{"recv":1,"debug":1}
,"recv":{"detail}":1,"debug":1}
,"detail}":{"debug":1,"undebug":1,"parameters":1}
,"undebug":{"ipv6":1}
,"parameters":{"hello":1}
,"hello":{"debug":1}
,"database":{"description":1}
,"description":{"ls-request":1}
,"link":{"state":1}
,"state":{"request":1,"update":1,"acknowledgment":1}
,"request":{"ls-update":1}
,"update":{"ls-ack":1}
,"acknowledgment":{"send":1}
,"packets":{"sent":1,"received":1}
,"sent":{"recv":1}
,"received":{"detail":1}
,"detail":{"debug":1,"information":1}
,"mode":{"privileged":1,"configure":1,"examples":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"configure":{"mode":1}
,"examples":{"debug":1}
}
;Search.control.loadWordPairs(pairs);
