var pairs =
{
"ethernet":{"cfm":1}
,"cfm":{"configure":1}
,"configure":{"default-md-level":1,"mode":1,"terminal":1}
,"default-md-level":{"command":1,"level":1,"mip-creation":1}
,"command":{"default":1,"syntax":1,"mode":1}
,"default":{"level":1,"mip":1,"explicit)":1,"specify":1,"bridge":1}
,"level":{"values":1,"table":1,"mip":1,"default":1,"level":1,"mip-creation":1,"specify":1,"default-md-level":1}
,"values":{"subsequent":1,"inherits":1,"object":1}
,"subsequent":{"entries":1}
,"entries":{"default":1}
,"table":{"entry":1}
,"entry":{"explicitly":1}
,"explicitly":{"configured":1}
,"configured":{"values":1}
,"inherits":{"level":1}
,"mip":{"creation":1,"may":1,"created":1}
,"creation":{"permission":1}
,"permission":{"values":1,"none":1,"value":1}
,"object":{"default":1}
,"none":{"command":1,"specify":1}
,"syntax":{"ethernet":1}
,"mip-creation":{"(none":1,"specify":1,"default":1}
,"(none":{"default":1}
,"explicit)":{"((bridge":1}
,"((bridge":{"<1-32>":1}
,"<1-32>":{"backbone)":1,"specify":1}
,"backbone)":{"parameters":1}
,"parameters":{"level":1}
,"specify":{"level":1,"mip":1,"bridge":1}
,"value":{"none":1}
,"may":{"created":1}
,"created":{"vid":1}
,"vid":{"default":1,"bridge":1,"pass":1}
,"bridge":{"explicit":1,"ports":1,"specify":1,"<1-32>":1,"backbone":1,"command":1}
,"explicit":{"specify":1}
,"ports":{"vid":1}
,"pass":{"bridge":1}
,"backbone":{"backbone":1,"bridge":1}
,"mode":{"configure":1,"example":1}
,"example":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"ethernet":1}
}
;Search.control.loadWordPairs(pairs);
