var pairs =
{
"ospf6_get_next_nbr_restart_helper_status":{"function":1,"(char":1}
,"function":{"gets":1,"fails":1,"succeeds":1}
,"gets":{"next":1}
,"next":{"value":1}
,"value":{"indicates":1}
,"indicates":{"whether":1}
,"whether":{"given":1}
,"given":{"router":1}
,"router":{"graceful":1,"identifier":1}
,"graceful":{"restart":1}
,"restart":{"helper":1}
,"helper":{"neighbor":1,"status":1,"spf6_api_restart_helper_none":1,"return":1}
,"neighbor":{"syntax":1,"indexlen":1,"restart":1}
,"syntax":{"int":1}
,"int":{"ospf6_get_next_nbr_restart_helper_status":1,"*ifindex":1,"*instid":1,"indexlen":1,"*ret)":1}
,"(char":{"*tag":1}
,"*tag":{"int":1}
,"*ifindex":{"int":1}
,"*instid":{"struct":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"*router_id":1}
,"*router_id":{"int":1}
,"indexlen":{"int":1,"length":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"tag":1,"ret":1}
,"tag":{"ospfv3":1,"ifindex":1}
,"ospfv3":{"process":1}
,"process":{"tag":1}
,"ifindex":{"interface":1}
,"interface":{"index":1}
,"index":{"instid":1,"output":1}
,"instid":{"instance":1}
,"instance":{"identifier":1}
,"identifier":{"router_id":1,"neighbor":1}
,"router_id":{"router":1}
,"length":{"object":1}
,"object":{"index":1}
,"output":{"parameters":1}
,"ret":{"neighbor":1}
,"status":{"ospf6_api_restart_helper":1}
,"ospf6_api_restart_helper":{"graceful":1}
,"spf6_api_restart_helper_none":{"graceful":1}
,"return":{"values":1}
,"values":{"ospf6_api_get_error":1}
,"ospf6_api_get_error":{"function":1}
,"fails":{"ospf6_api_get_success":1}
,"ospf6_api_get_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
