var pairs =
{
"g8032":{"md-name":1,"ring":1,"ethernet":1,"configure":1}
,"md-name":{"command":1,"md_name":1,"maintenance":1,"test":1}
,"command":{"associate":1,"disassociate":1,"syntax":1,"mode":1}
,"associate":{"g8032":1}
,"ring":{"maintenance":1,"provider":1}
,"maintenance":{"domain":1,"association":1}
,"domain":{"(md)":1,"md_name":1,"name":1}
,"(md)":{"maintenance":1}
,"association":{"(ma)":1,"ma_name":1,"name":1}
,"(ma)":{"form":1}
,"form":{"command":1}
,"disassociate":{"g8032":1}
,"provider":{"backbone":1}
,"backbone":{"bridging":1}
,"bridging":{"supported":1}
,"supported":{"zebic":1}
,"zebic":{"releases":1}
,"releases":{"command":1}
,"syntax":{"g8032":1}
,"ethernet":{"md-name":1}
,"md_name":{"service-id":1,"maintenance":1}
,"service-id":{"ma_name":1,"maintenance":1,"testma":1}
,"ma_name":{"g8032":1,"parameters":1,"maintenance":1}
,"parameters":{"md-name":1}
,"name":{"service-id":1,"command":1}
,"mode":{"g8032":1,"examples":1}
,"configure":{"switching":1,"terminal":1}
,"switching":{"mode":1,"eps-id":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"g8032":1}
,"eps-id":{"bridge":1}
,"bridge":{"(g8032-config-switching)":1}
,"(g8032-config-switching)":{"g8032":1}
,"test":{"service-id":1}
,"testma":{"(g8032-config-switching)":1}
}
;Search.control.loadWordPairs(pairs);
