var pairs =
{
"ethernet":{"cfm":1}
,"cfm":{"lmm":1}
,"lmm":{"counter":1,"frame":1}
,"counter":{"command":1,"mep":1,"simulates":1,"(enable":1,"enable":1,"disable":1}
,"command":{"enable":1,"syntax":1,"mode":1}
,"enable":{"disable":1,"specify":1,"mep":1}
,"disable":{"loss":1,"specify":1,"mep":1}
,"loss":{"measurement":1}
,"measurement":{"message":1}
,"message":{"(lmm)":1}
,"(lmm)":{"frame":1}
,"frame":{"counter":1}
,"mep":{"lmm":1,"mepid":1,"disable":1,"mep":1,"host":1,"<1-8191>":1,"level":1}
,"simulates":{"hardware":1}
,"hardware":{"level":1,"counters":1}
,"level":{"frame":1,"level":1,"(vlan":1,"specify":1,"domain":1,"<0-7>":1,"vlan":1}
,"syntax":{"ethernet":1}
,"(enable":{"disable)":1}
,"disable)":{"mep":1}
,"mepid":{"level":1,"specify":1}
,"(vlan":{"vlanid":1}
,"vlanid":{"bridge":1}
,"bridge":{"<1-32>":1,"specify":1,"command":1,"ethernet":1}
,"<1-32>":{"parameters":1,"specify":1}
,"parameters":{"enable":1}
,"specify":{"install":1,"de-install":1,"host":1,"level":1,"vlan":1,"bridge":1}
,"install":{"hardware":1}
,"counters":{"mep":1}
,"de-install":{"hardware":1}
,"host":{"mep":1}
,"<1-8191>":{"level":1}
,"domain":{"level":1}
,"<0-7>":{"vlan":1}
,"vlan":{"specify":1,"vlan_id":1,"bridge":1}
,"vlan_id":{"specify":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"ethernet":1}
}
;Search.control.loadWordPairs(pairs);
