var pairs =
{
"rsvp-bypass":{"command":1,"bypassname":1,"trunkname":1,"my_bypass":1}
,"command":{"used":1,"helps":1,"delete":1,"syntax":1,"mode":1}
,"used":{"create":1}
,"create":{"new":1}
,"new":{"rsvp":1}
,"rsvp":{"bypass":1}
,"bypass":{"tunnel":1}
,"tunnel":{"modify":1,"command":1,"added":1,"removed":1}
,"modify":{"existing":1}
,"existing":{"rsvp":1}
,"helps":{"identify":1}
,"identify":{"attributes":1}
,"attributes":{"frr":1}
,"frr":{"backup":1}
,"backup":{"lsp":1}
,"lsp":{"facility-backup":1}
,"facility-backup":{"protection":1}
,"protection":{"method":1}
,"method":{"parameter":1}
,"parameter":{"command":1,"bypassname":1}
,"delete":{"configured":1}
,"configured":{"rsvp":1}
,"syntax":{"rsvp-bypass":1}
,"bypassname":{"rsvp-bypass":1,"name":1}
,"trunkname":{"parameter":1,"name":1}
,"name":{"assigned":1}
,"assigned":{"bypass":1}
,"added":{"trunkname":1}
,"removed":{"command":1}
,"mode":{"configure":1,"example":1}
,"configure":{"mode":1,"terminal":1}
,"example":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"rsvp-bypass":1}
,"my_bypass":{"(config-bypass)":1}
}
;Search.control.loadWordPairs(pairs);
