var pairs =
{
"spb_nsm_send_convention_id":{"function":1,"(char":1}
,"function":{"sets":1,"implements":1,"fails":1,"succeeds":1}
,"sets":{"agreement":1}
,"agreement":{"protocol":1,"convention":1,"digest":1}
,"protocol":{"convention":1}
,"convention":{"specifies":1,"command":1,"constants":1}
,"specifies":{"computed":1}
,"computed":{"topology":1}
,"topology":{"digest":1,"information":1}
,"digest":{"determine":1,"match":1,"forward":1,"neighbor":1}
,"determine":{"whether":1}
,"whether":{"neighboring":1}
,"neighboring":{"switch":1}
,"switch":{"operating":1}
,"operating":{"identical":1}
,"identical":{"network":1}
,"network":{"topology":1}
,"information":{"frames":1}
,"frames":{"may":1}
,"may":{"safely":1}
,"safely":{"forwarded":1}
,"forwarded":{"neighbor":1}
,"neighbor":{"function":1,"matches":1}
,"implements":{"bridge":1}
,"bridge":{"(<1-32>":1,"name":1}
,"(<1-32>":{"backbone)":1}
,"backbone)":{"agreement":1}
,"command":{"syntax":1}
,"syntax":{"include":1}
,"include":{"spbd\u002Fspb_nsm.h":1}
,"spbd\u002Fspb_nsm.h":{"s_int32_t":1}
,"s_int32_t":{"spb_nsm_send_convention_id":1}
,"(char":{"*bridge_name":1}
,"*bridge_name":{"u_char":1}
,"u_char":{"value)":1}
,"value)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bridge_name":1,"none":1}
,"bridge_name":{"bridge":1}
,"name":{"value":1}
,"value":{"agreement":1,"less":1}
,"constants":{"spb_convention_id_type":1}
,"spb_convention_id_type":{"enum":1}
,"enum":{"spbd\u002Fspb_types.h":1}
,"spbd\u002Fspb_types.h":{"spb_no_agreement":1}
,"spb_no_agreement":{"action":1}
,"action":{"taken":1}
,"taken":{"topology":1}
,"match":{"spb_loop_free_both":1}
,"spb_loop_free_both":{"transmitter":1}
,"transmitter":{"agreement":1,"forward":1}
,"forward":{"traffic":1,"multicast":1}
,"traffic":{"until":1,"allows":1,"output":1}
,"until":{"topology":1}
,"matches":{"spb_loop_free_mcast_only":1}
,"spb_loop_free_mcast_only":{"transmitter":1}
,"multicast":{"traffic":1}
,"allows":{"unicast":1}
,"unicast":{"traffic":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"less":{"zero":1}
,"zero":{"function":1}
,"fails":{"greater":1}
,"greater":{"zero":1}
}
;Search.control.loadWordPairs(pairs);
