var pairs =
{
"ldp_snmp_fec_entry_add":{"call":1,"(u_int32_t":1}
,"call":{"adds":1}
,"adds":{"specified":1}
,"specified":{"shadow":1}
,"shadow":{"table":1,"entry":1}
,"table":{"entry":1,"syntax":1}
,"entry":{"fec":1,"output":1}
,"fec":{"table":1,"index":1,"shadow":1}
,"syntax":{"int":1}
,"int":{"ldp_snmp_fec_entry_add":1}
,"(u_int32_t":{"index":1}
,"index":{"struct":1,"fec":1,"shadow_entry":1}
,"struct":{"snmp_mplsfecentry_t":1}
,"snmp_mplsfecentry_t":{"*shadow_entry)":1}
,"*shadow_entry)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"index":1,"none":1}
,"shadow_entry":{"snmp":1}
,"snmp":{"fec":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"ldp_success":1}
,"ldp_success":{"ldp_error":1}
}
;Search.control.loadWordPairs(pairs);
