var pairs =
{
"bfd_notify_event":{"bfd_notify_event":1,"enumeration":1,"{bfd_notify_process_new":1}
,"enumeration":{"defines":1}
,"defines":{"bfd":1}
,"bfd":{"notification":1}
,"notification":{"events":1}
,"events":{"constant":1}
,"constant":{"description":1}
,"description":{"bfd_notify_process_new":1}
,"bfd_notify_process_new":{"new":1}
,"new":{"process":1,"link":1,"address":1}
,"process":{"added":1,"deleted":1}
,"added":{"bfd_notify_process_del":1,"bfd_notify_link_del":1,"bfd_notify_address_del":1}
,"bfd_notify_process_del":{"process":1,"bfd_notify_router_id_changed":1}
,"deleted":{"bfd_notify_router_id_changed":1,"bfd_notify_link_up":1,"bfd_notify_max":1}
,"bfd_notify_router_id_changed":{"router":1,"bfd_notify_link_new":1}
,"router":{"identifier":1}
,"identifier":{"changed":1}
,"changed":{"bfd_notify_link_new":1}
,"bfd_notify_link_new":{"new":1,"bfd_notify_link_del":1}
,"link":{"added":1,"deleted":1,"bfd_notify_link_down":1,"down":1}
,"bfd_notify_link_del":{"link":1,"bfd_notify_link_up":1}
,"bfd_notify_link_up":{"link":1,"bfd_notify_link_down":1}
,"bfd_notify_link_down":{"link":1,"bfd_notify_address_new":1}
,"down":{"bfd_notify_address_new":1}
,"bfd_notify_address_new":{"new":1,"bfd_notify_address_del":1}
,"address":{"added":1,"deleted":1}
,"bfd_notify_address_del":{"address":1,"bfd_notify_max":1}
,"bfd_notify_max":{"maximum":1}
,"maximum":{"definition":1}
,"definition":{"enum":1}
,"enum":{"bfd_notify_event":1}
,"{bfd_notify_process_new":{"bfd_notify_process_del":1}
}
;Search.control.loadWordPairs(pairs);
