var pairs =
{
"ospf_network_unset":{"function":1,"(u_int32_t":1}
,"function":{"deletes":1,"called":1,"succeeds":1}
,"deletes":{"network":1}
,"network":{"area":1,"belongs":1,"exist":1,"ospf_api_set_success":1}
,"area":{"configuration":1,"disables":1,"syntax":1,"network":1,"match":1}
,"configuration":{"directive":1}
,"directive":{"matched":1}
,"matched":{"specified":1}
,"specified":{"prefix":1,"network":1}
,"prefix":{"area":1,"length":1}
,"disables":{"interface":1}
,"interface":{"ospf":1,"instance":1}
,"ospf":{"domain":1,"instance":1}
,"domain":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"network":1}
,"syntax":{"int":1}
,"int":{"ospf_network_unset":1,"proc_id":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"int":1,"virtual":1}
,"proc_id":{"struct":1,"process":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"addr":1,"area_id":1}
,"addr":{"u_char":1,"nbma":1}
,"u_char":{"masklen":1}
,"masklen":{"struct":1,"prefix":1}
,"area_id":{"s_int16_t":1,"area":1}
,"s_int16_t":{"id)":1}
,"id)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"found":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"proc_id":1}
,"process":{"ospf":1,"valid":1,"exist":1}
,"instance":{"65535>":1,"255>":1,"outside":1,"match":1}
,"65535>":{"addr":1}
,"nbma":{"neighbor":1}
,"neighbor":{"address":1}
,"address":{"masklen":1}
,"length":{"area_id":1}
,"belongs":{"interface":1}
,"255>":{"default":1}
,"default":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf_api_set_err_process_id_invalid":1}
,"ospf_api_set_err_process_id_invalid":{"process":1}
,"valid":{"ospf_api_set_err_process_not_exist":1}
,"ospf_api_set_err_process_not_exist":{"given":1}
,"given":{"process":1,"instance":1}
,"exist":{"ospf_api_set_err_network_not_exist":1,"ospf_api_set_err_area_id_not_match":1}
,"ospf_api_set_err_network_not_exist":{"specified":1}
,"ospf_api_set_err_area_id_not_match":{"provided":1}
,"provided":{"area":1}
,"match":{"area":1,"configured":1}
,"ospf_api_set_success":{"function":1}
,"succeeds":{"ospf_api_set_err_vr_not_exist":1}
,"ospf_api_set_err_vr_not_exist":{"virtual":1}
,"found":{"ospf_api_set_err_if_instance_id_invalid":1}
,"ospf_api_set_err_if_instance_id_invalid":{"given":1}
,"outside":{"range":1}
,"range":{"ospf_api_set_err_if_inst_id_not_match":1}
,"ospf_api_set_err_if_inst_id_not_match":{"given":1}
,"configured":{"instance":1}
}
;Search.control.loadWordPairs(pairs);
