var pairs =
{
"service":{"ma-type":1,"maintenance":1,"csi_id":1}
,"ma-type":{"command":1,"(primary-vid":1,"string":1}
,"command":{"create":1,"allows":1,"primary":1,"remove":1,"syntax":1,"mode":1}
,"create":{"service":1}
,"maintenance":{"association":1}
,"association":{"(ma)":1,"link-level":1}
,"(ma)":{"without":1,"ma_name":1}
,"without":{"vlan":1,"vid":1}
,"vlan":{"command":1,"vlan_id":1,"vid":1,"integer":1,"specify":1,"<2-4094>":1,"mip-creation":1}
,"allows":{"creation":1}
,"creation":{"maintenance":1,"created":1,"permission":1,"permissions":1}
,"link-level":{"meps":1,"form":1}
,"meps":{"(level":1}
,"(level":{"listen":1}
,"listen":{"vlan":1}
,"vlan_id":{"passed":1,"mip-creation":1,"specify":1}
,"passed":{"command":1}
,"primary":{"vid":1,"vlan":1}
,"vid":{"vlan":1,"associated":1,"vid":1,"cannot":1,"link-level":1,"bridge":1,"pass":1}
,"associated":{"time":1}
,"time":{"creation":1}
,"created":{"without":1,"level":1,"vid":1}
,"cannot":{"added":1}
,"added":{"during":1}
,"during":{"runtime":1}
,"runtime":{"without":1}
,"form":{"command":1}
,"remove":{"command":1}
,"syntax":{"service":1}
,"(primary-vid":{"string":1}
,"string":{"integer":1,"specify":1,"identifies":1,"ma-name":1}
,"integer":{"vpn-id)":1,"specify":1,"identifies":1}
,"vpn-id)":{"ma-name":1}
,"ma-name":{"ma_name":1,"enter":1,"vlan":1}
,"ma_name":{"(vlan":1,"enter":1}
,"(vlan":{"vlan_id":1}
,"mip-creation":{"(none":1,"specify":1,"none":1,"default":1}
,"(none":{"default":1}
,"default":{"explicit":1,"specify":1}
,"explicit":{"defer)":1,"specify":1}
,"defer)":{"service":1,"parameters":1}
,"csi_id":{"(vlan":1,"enter":1}
,"parameters":{"primary-vid":1}
,"primary-vid":{"specify":1}
,"specify":{"primary":1,"integer":1,"character":1,"virtual":1,"vlan":1,"mip":1}
,"identifies":{"string":1,"vpn-id":1,"ma-name":1}
,"character":{"string":1}
,"vpn-id":{"specify":1}
,"virtual":{"private":1}
,"private":{"network":1}
,"network":{"identifies":1}
,"enter":{"maintenance":1,"name":1}
,"name":{"csi_id":1,"vlan":1,"new":1}
,"<2-4094>":{"mip-creation":1}
,"mip":{"creation":1,"may":1,"created":1}
,"permission":{"value":1}
,"value":{"none":1}
,"none":{"specify":1,"(config-ether-cfm)":1}
,"may":{"created":1}
,"level":{"default":1,"mip-creation":1}
,"bridge":{"explicit":1,"ports":1}
,"ports":{"vid":1}
,"pass":{"defer":1}
,"defer":{"specify":1}
,"permissions":{"belongs":1}
,"belongs":{"command":1}
,"mode":{"ethernet":1,"example":1}
,"ethernet":{"cfm":1}
,"cfm":{"mode":1,"domain-name":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"ethernet":1}
,"domain-name":{"type":1}
,"type":{"character-string":1}
,"character-string":{"name":1}
,"new":{"level":1}
,"(config-ether-cfm)":{"service":1}
}
;Search.control.loadWordPairs(pairs);
