var pairs =
{
"isis_distance_source_set":{"call":1,"(u_int32_t":1}
,"call":{"implements":1}
,"implements":{"distance":1}
,"distance":{"command":1,"routes":1,"char":1,"within":1}
,"command":{"define":1}
,"define":{"administrative":1}
,"administrative":{"distance":1}
,"routes":{"specific":1,"permitted":1}
,"specific":{"route":1}
,"route":{"source":1}
,"source":{"and\u002For":1,"access_name":1}
,"and\u002For":{"routes":1}
,"permitted":{"access-list":1}
,"access-list":{"syntax":1,"name":1}
,"syntax":{"int":1}
,"int":{"isis_distance_source_set":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1,"tag":1}
,"char":{"*tag":1,"*sys_id":1,"*access_name)":1}
,"*tag":{"u_int32_t":1}
,"u_int32_t":{"distance":1}
,"*sys_id":{"char":1}
,"*access_name)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1,"isis_api_set_err_instance_not_exist":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"tag":{"is-is":1,"sys_id":1,"isis_api_set_err_vr_not_exist":1}
,"is-is":{"instance":1}
,"instance":{"area":1,"exist":1}
,"area":{"tag":1}
,"sys_id":{"source":1}
,"access_name":{"access-list":1}
,"name":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"isis_api_set_err_instance_not_exist":{"is-is":1}
,"exist":{"given":1,"isis_api_set_err_distance_invalid":1}
,"given":{"tag":1}
,"isis_api_set_err_vr_not_exist":{"exist":1}
,"isis_api_set_err_distance_invalid":{"distance":1}
,"within":{"range":1}
,"range":{"isis_api_set_success":1}
,"isis_api_set_success":{"successful":1}
}
;Search.control.loadWordPairs(pairs);
