var pairs =
{
"forwarding":{"database":1}
,"database":{"callbacks":1,"(fdb)":1}
,"callbacks":{"following":1,"callbacks":1,"description":1}
,"following":{"table":1}
,"table":{"displays":1}
,"displays":{"forwarding":1}
,"description":{"add_fdb":1}
,"add_fdb":{"add":1}
,"add":{"mac":1}
,"mac":{"entry":1,"entries":1,"fdb":1}
,"entry":{"forwarding":1,"fdb":1}
,"(fdb)":{"delete_fdb":1}
,"delete_fdb":{"delete":1}
,"delete":{"mac":1,"specific":1}
,"fdb":{"get_uni_fdb":1,"flush_port_fdb":1,"specific":1}
,"get_uni_fdb":{"dynamic":1}
,"dynamic":{"unicast":1}
,"unicast":{"mac":1}
,"entries":{"fdb":1}
,"flush_port_fdb":{"flush":1}
,"flush":{"fdb":1}
,"specific":{"port":1,"mac":1}
,"port":{"flush_fdb_by_mac":1}
,"flush_fdb_by_mac":{"delete":1}
}
;Search.control.loadWordPairs(pairs);
