var pairs =
{
"exec-timeout":{"command":1,"<0-35791>":1,"(<0-35791>":1}
,"command":{"interval":1,"interpreter":1,"syntax":1,"mode":1}
,"interval":{"command":1}
,"interpreter":{"waits":1}
,"waits":{"user":1,"idle":1}
,"user":{"input":1,"router":1}
,"input":{"detected":1}
,"detected":{"sets":1}
,"sets":{"time":1}
,"time":{"telnet":1}
,"telnet":{"session":1}
,"session":{"waits":1,"times":1,"wait":1,"timeout":1}
,"idle":{"vty":1}
,"vty":{"session":1,"router":1}
,"times":{"value":1}
,"value":{"zero":1,"minutes":1,"seconds":1}
,"zero":{"minutes":1,"seconds":1}
,"minutes":{"zero":1,"<0-2147483>":1,"seconds":1}
,"seconds":{"causes":1,"command":1,"response":1}
,"causes":{"telnet":1}
,"wait":{"indefinitely":1,"interval":1}
,"indefinitely":{"parameter":1}
,"parameter":{"disable":1}
,"disable":{"wait":1}
,"syntax":{"exec-timeout":1}
,"<0-35791>":{"(<0-2147483>":1,"indicate":1}
,"(<0-2147483>":{"exec-timeout":1,"parameters":1}
,"(<0-35791>":{"(<0-2147483>":1}
,"parameters":{"<0-35791>":1}
,"indicate":{"timeout":1}
,"timeout":{"value":1,"minutes":1}
,"<0-2147483>":{"indicate":1}
,"mode":{"line":1,"example":1}
,"line":{"mode":1,"vty":1}
,"example":{"following":1,"telnet":1}
,"following":{"example":1}
,"response":{"user":1}
,"router":{"configure":1,"(config)":1,"(config-line)":1}
,"configure":{"terminal":1}
,"terminal":{"router":1}
,"(config)":{"line":1}
,"(config-line)":{"exec-timeout":1}
}
;Search.control.loadWordPairs(pairs);
