var pairs =
{
"unicast":{"ping":1}
,"ping":{"ping":1,"tool":1,"originating":1,"issue":1,"however":1}
,"tool":{"verifying":1}
,"verifying":{"rbridge":1}
,"rbridge":{"connectivity":1,"transmits":1,"frame":1,"egress":1,"destination":1,"ping":1}
,"connectivity":{"ping":1,"checked":1,"multi-access":1}
,"originating":{"rbridge":1}
,"transmits":{"trill":1}
,"trill":{"data":1,"oam":1}
,"data":{"frames":1,"frame":1,"plane":1,"going":1}
,"frames":{"trill":1}
,"oam":{"message":1,"channel":1}
,"message":{"message":1,"contains":1}
,"contains":{"code":1}
,"code":{"echo":1}
,"echo":{"request":1}
,"request":{"ingress":1,"options":1}
,"ingress":{"rbridge":1}
,"frame":{"originating":1,"mimics":1,"follows":1,"rbridge":1}
,"egress":{"rbridge":1}
,"destination":{"rbridge":1}
,"checked":{"rbridges":1}
,"rbridges":{"implementing":1,"campus":1}
,"implementing":{"ping":1}
,"issue":{"reply":1}
,"reply":{"response":1}
,"response":{"request":1}
,"options":{"defined":1,"frame":1}
,"defined":{"future":1}
,"future":{"drafts":1}
,"drafts":{"may":1}
,"may":{"included":1,"fact":1}
,"included":{"purpose":1}
,"purpose":{"allowing":1}
,"allowing":{"addition":1}
,"addition":{"options":1}
,"mimics":{"data":1}
,"follows":{"path":1}
,"path":{"data":1,"real":1}
,"plane":{"real":1}
,"real":{"data":1}
,"however":{"uses":1}
,"uses":{"oam":1}
,"channel":{"depending":1}
,"depending":{"ecmp":1}
,"ecmp":{"hashing":1}
,"hashing":{"used":1}
,"used":{"rbridges":1}
,"campus":{"may":1}
,"fact":{"share":1}
,"share":{"path":1}
,"going":{"network":1}
,"network":{"chapter":1}
,"chapter":{"shows":1}
,"shows":{"forming":1}
,"forming":{"adjacency":1}
,"adjacency":{"checking":1}
,"checking":{"connectivity":1}
,"multi-access":{"lan":1}
,"lan":{"topology":1}
,"topology":{"configurations":1}
,"configurations":{"assume":1}
,"assume":{"running":1}
,"running":{"trilld":1}
,"trilld":{"nsm":1}
,"nsm":{"imi":1}
,"imi":{"daemons":1}
}
;Search.control.loadWordPairs(pairs);
