var pairs =
{
"ipsec_transform_set_delete":{"function":1,"(u_int32_t":1}
,"function":{"deletes":1,"successful":1}
,"deletes":{"transform":1}
,"transform":{"syntax":1,"name":1,"ipsec_api_success":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"ipsec_transform_set_delete":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1}
,"char":{"*transform_set_name)":1}
,"*transform_set_name)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"transform_set_name":1}
,"transform_set_name":{"transform":1}
,"name":{"output":1,"exist":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"ipsec_err_transform_set_not_found":1}
,"ipsec_err_transform_set_not_found":{"transform":1}
,"exist":{"ipsec_err_transformset_inuse":1}
,"ipsec_err_transformset_inuse":{"transform":1}
,"ipsec_api_success":{"function":1}
,"successful":{"ipsec_api_error":1}
,"ipsec_api_error":{"error":1}
}
;Search.control.loadWordPairs(pairs);
