var pairs =
{
"configure":{"terminal":1,"mode":1,"priority":1,"advertisement":1}
,"terminal":{"enter":1}
,"enter":{"configure":1}
,"mode":{"(config)":1,"specify":1}
,"(config)":{"router":1}
,"router":{"vrrp":1,"(config-router)":1,"case":1}
,"vrrp":{"eth0":1,"instance":1,"session":1}
,"eth0":{"create":1,"(config-router)":1}
,"create":{"new":1}
,"new":{"vrrp":1}
,"instance":{"interface":1}
,"interface":{"eth0":1}
,"(config-router)":{"virtual-ip":1,"priority":1,"preempt":1,"advertisement-interval":1,"enable":1}
,"virtual-ip":{"10.10.10.1":1}
,"10.10.10.1":{"virtual":1}
,"virtual":{"address":1}
,"address":{"vrrp":1}
,"session":{"(config-router)":1,"router":1}
,"priority":{"configure":1,"(less":1,"function":1}
,"(less":{"100)":1}
,"100)":{"backup":1}
,"backup":{"router":1}
,"preempt":{"true":1,"mode":1}
,"true":{"preempt":1}
,"specify":{"highest":1}
,"highest":{"priority":1}
,"function":{"primary":1}
,"primary":{"backup":1}
,"case":{"failure":1}
,"failure":{"(config-router)":1}
,"advertisement-interval":{"100":1}
,"100":{"configure":1,"centi":1}
,"advertisement":{"interval":1}
,"interval":{"100":1}
,"centi":{"seconds":1}
,"seconds":{"(value":1}
,"(value":{"multiple":1}
,"multiple":{"(config-router)":1}
,"enable":{"enable":1,"vrrp":1}
}
;Search.control.loadWordPairs(pairs);
