var pairs =
{
"router":{"helper":1,"ipv6":1,"(1.1.1.1)":1,"mode":1}
,"helper":{"restart":1,"only-reload":1}
,"restart":{"reason":1,"helper":1}
,"reason":{"reload":1}
,"reload":{"configure":1}
,"configure":{"terminal":1,"mode":1,"work":1}
,"terminal":{"enter":1}
,"enter":{"configure":1}
,"mode":{"(config)":1,"enter":1}
,"(config)":{"router":1,"ipv6":1}
,"ipv6":{"ospf":1}
,"ospf":{"create":1,"restart":1}
,"create":{"ospfv3":1}
,"ospfv3":{"routing":1}
,"routing":{"instance":1,"process":1}
,"instance":{"(config-router)":1}
,"(config-router)":{"router-id":1,"exit":1}
,"router-id":{"1.1.1.1":1}
,"1.1.1.1":{"specify":1}
,"specify":{"router":1}
,"(1.1.1.1)":{"ospfv3":1}
,"process":{"(config-router)":1}
,"exit":{"exit":1,"router":1}
,"only-reload":{"configure":1}
,"work":{"helper":1}
}
;Search.control.loadWordPairs(pairs);
