var pairs =
{
"rib_unset_maximum_static_routes":{"function":1,"(int":1}
,"function":{"sets":1,"called":1,"succeeds":1}
,"sets":{"maximum":1}
,"maximum":{"number":1}
,"number":{"static":1}
,"static":{"routes":1}
,"routes":{"max_static_route_default":1}
,"max_static_route_default":{"(4,294,967,294)":1}
,"(4,294,967,294)":{"function":1}
,"called":{"max-static-routes":1}
,"max-static-routes":{"command":1}
,"command":{"syntax":1}
,"syntax":{"int":1}
,"int":{"rib_unset_maximum_static_routes":1}
,"(int":{"vr_id)":1}
,"vr_id)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"vr_id":{"virtual":1}
,"virtual":{"router":1}
,"router":{"identifier":1,"found":1}
,"identifier":{"non-virtual-router":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"rib_api_set_err_vr_not_exist":1}
,"rib_api_set_err_vr_not_exist":{"virtual":1}
,"found":{"rib_api_set_success":1}
,"rib_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
