var pairs =
{
"definition":{"\u002F*pointer":1}
,"\u002F*pointer":{"dcb":1}
,"dcb":{"bridge":1,"flags":1}
,"bridge":{"*\u002Fstruct":1}
,"*\u002Fstruct":{"nsm_dcb_bridge":1,"interface":1,"pfc_config":1,"ets_config":1,"ets_rec":1,"app_config":1,"avl_tree":1}
,"nsm_dcb_bridge":{"*dcbg":1}
,"*dcbg":{"\u002F*interface":1}
,"\u002F*interface":{"pointer":1}
,"pointer":{"*\u002Fstruct":1}
,"interface":{"*ifp":1,"*\u002Fstruct":1,"*\u002Fu_int8_t":1}
,"*ifp":{"struct":1}
,"struct":{"nsm_qcn_cnpv_data":1}
,"nsm_qcn_cnpv_data":{"nsm_qcn_cnpv_data":1,"[nsm_num_cnpv]":1}
,"[nsm_num_cnpv]":{"bool_t":1}
,"bool_t":{"is_cp":1}
,"is_cp":{"\u002F*priority":1}
,"\u002F*priority":{"flow":1}
,"flow":{"control":1}
,"control":{"configuration":1}
,"configuration":{"interface":1}
,"pfc_config":{"*pfc_config_admin":1,"*pfc_config_oper":1}
,"*pfc_config_admin":{"\u002F*admin":1}
,"\u002F*admin":{"params":1,"params*\u002Fstruct":1}
,"params":{"*\u002Fstruct":1,"*\u002Fenum":1}
,"*pfc_config_oper":{"\u002F*operational":1}
,"\u002F*operational":{"params":1}
,"*\u002Fenum":{"nsm_dcb_mode":1}
,"nsm_dcb_mode":{"pfc_mode":1,"ets_mode":1,"app_mode":1}
,"pfc_mode":{"\u002F*ets":1}
,"\u002F*ets":{"configuration":1}
,"ets_config":{"*ets_config_admin":1,"*ets_config_oper":1}
,"*ets_config_admin":{"\u002F*admin":1}
,"params*\u002Fstruct":{"ets_config":1}
,"*ets_config_oper":{"\u002F*operational":1}
,"ets_rec":{"*ets_rec_param":1}
,"*ets_rec_param":{"\u002F*recommendational":1}
,"\u002F*recommendational":{"params":1}
,"ets_mode":{"\u002F*application":1}
,"\u002F*application":{"priority":1}
,"priority":{"configuration":1}
,"app_config":{"*app_config_admin":1,"*app_config_oper":1}
,"*app_config_admin":{"\u002F*admin":1}
,"*app_config_oper":{"\u002F*operational":1}
,"app_mode":{"\u002F*this":1}
,"\u002F*this":{"indicates":1,"maintain":1,"list":1}
,"indicates":{"dcb":1}
,"flags":{"interface":1}
,"*\u002Fu_int8_t":{"dcb_if_flags":1}
,"dcb_if_flags":{"define":1}
,"define":{"nsm_dcb_if_enable":1,"nsm_dcb_if_ets_enable":1,"nsm_dcb_if_pfc_enable":1}
,"nsm_dcb_if_enable":{"<<0)":1}
,"<<0)":{"define":1}
,"nsm_dcb_if_ets_enable":{"<<1)":1}
,"<<1)":{"define":1}
,"nsm_dcb_if_pfc_enable":{"<<2)":1}
,"<<2)":{"\u002F*this":1}
,"maintain":{"number":1}
,"number":{"pfc":1}
,"pfc":{"requests":1,"indications":1}
,"requests":{"sent*\u002Fu_int32_t":1}
,"sent*\u002Fu_int32_t":{"pfc_requests_sent":1}
,"pfc_requests_sent":{"\u002F*this":1}
,"indications":{"received*\u002Fu_int32_t":1}
,"received*\u002Fu_int32_t":{"pfc_indications_rcvd":1}
,"pfc_indications_rcvd":{"\u002F*this":1}
,"list":{"application":1}
,"application":{"priorities":1}
,"priorities":{"interface":1}
,"avl_tree":{"*dcb_appl_pri":1}
}
;Search.control.loadWordPairs(pairs);
