var pairs =
{
"a.b.c.d":{"command":1,"a.b.c.d":1,"parameters":1}
,"command":{"specify":1,"trunk":1,"unset":1,"syntax":1,"mode":1}
,"specify":{"ipv4":1,"address":1,"egress":1}
,"ipv4":{"egress":1}
,"egress":{"lsp":1,"router":1,"definition":1,"defined":1,"address":1}
,"lsp":{"configuring":1,"specify":1,"initialization":1}
,"configuring":{"lsp":1}
,"address":{"egress":1,"command":1}
,"router":{"using":1}
,"using":{"command":1}
,"trunk":{"node":1,"mode":1}
,"node":{"egress":1}
,"definition":{"mandatory":1}
,"mandatory":{"attribute":1}
,"attribute":{"rsvp":1}
,"rsvp":{"session":1}
,"session":{"created":1}
,"created":{"egress":1}
,"defined":{"parameter":1}
,"parameter":{"command":1}
,"unset":{"configured":1}
,"configured":{"egress":1}
,"syntax":{"a.b.c.d":1}
,"parameters":{"none":1}
,"none":{"default":1}
,"default":{"operator":1}
,"operator":{"specify":1}
,"initialization":{"begin":1}
,"begin":{"command":1}
,"mode":{"trunk":1,"examples":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"rsvp-trunk":1}
,"rsvp-trunk":{"mytrunk":1}
,"mytrunk":{"(config-trunk)":1}
,"(config-trunk)":{"10.10.0.5":1}
}
;Search.control.loadWordPairs(pairs);
