var pairs =
{
"igmp":{"command":1,"operation":1,"proxy":1,"related":1,"igmp":1,"parameters":1}
,"command":{"enable":1,"enables":1,"effect":1,"return":1,"syntax":1,"mode":1}
,"enable":{"igmp":1}
,"operation":{"interface":1,"stand-alone":1}
,"interface":{"command":1,"mode":1,"(config-if)":1}
,"enables":{"igmp":1}
,"stand-alone":{"mode":1}
,"mode":{"used":1,"interface":1,"example":1}
,"used":{"learn":1}
,"learn":{"local-membership":1}
,"local-membership":{"information":1}
,"information":{"prior":1}
,"prior":{"enabling":1}
,"enabling":{"multicast":1}
,"multicast":{"routing":1}
,"routing":{"protocol":1}
,"protocol":{"interface":1}
,"effect":{"interfaces":1}
,"interfaces":{"configured":1}
,"configured":{"igmp":1}
,"proxy":{"parameter":1,"service)":1}
,"parameter":{"command":1}
,"return":{"igmp":1}
,"related":{"configuration":1}
,"configuration":{"default":1}
,"default":{"(including":1}
,"(including":{"igmp":1}
,"service)":{"command":1}
,"syntax":{"igmp":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"(config-if)":{"igmp":1}
}
;Search.control.loadWordPairs(pairs);
