var pairs =
{
"trill_instance_bridge_set":{"function":1,"(u_int32_t":1}
,"function":{"creates":1,"call":1}
,"creates":{"specified":1}
,"specified":{"trill":1,"bridge":1}
,"trill":{"rbridge":1,"bridge":1,"interface":1}
,"rbridge":{"instance":1,"trill":1}
,"instance":{"binds":1,"called":1,"output":1,"trill_api_set_err_vr_not_exist":1,"virtual":1}
,"binds":{"bridge":1}
,"bridge":{"instance":1,"cli":1,"exist":1}
,"called":{"rbridge":1}
,"cli":{"command":1}
,"command":{"contained":1}
,"contained":{"trill_api.c":1}
,"trill_api.c":{"file":1}
,"file":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"trill_instance_bridge_set":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"specifies":1}
,"char":{"*name":1}
,"*name":{"char*bridgeid)":1,"specifies":1}
,"char*bridgeid)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"specifies":{"identification":1,"trill":1,"bridge":1}
,"identification":{"virtual":1}
,"virtual":{"router":1}
,"router":{"*name":1}
,"interface":{"bridgeid":1}
,"bridgeid":{"specifies":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"trill_api_set_success":1}
,"trill_api_set_success":{"indicates":1}
,"indicates":{"function":1,"specified":1,"active":1}
,"call":{"executed":1}
,"executed":{"properly":1}
,"properly":{"trill_api_set_bridge_not_exist":1}
,"trill_api_set_bridge_not_exist":{"indicates":1}
,"exist":{"configure":1}
,"configure":{"bridge":1}
,"trill_api_set_err_vr_not_exist":{"indicates":1}
,"active":{"instance":1}
}
;Search.control.loadWordPairs(pairs);
