var pairs =
{
"ipv6":{"ospf":1}
,"ospf":{"dead-interval":1,"hello":1,"compares":1}
,"dead-interval":{"command":1,"<1-65535>":1,"ipv6":1,"instance-id":1,"specify":1}
,"command":{"amount":1,"reset":1,"syntax":1,"mode":1}
,"amount":{"time":1}
,"time":{"router":1}
,"router":{"waits":1}
,"waits":{"receive":1}
,"receive":{"ospf":1}
,"hello":{"packet":1,"packets":1}
,"packet":{"neighbor":1,"dead":1,"discarded":1}
,"neighbor":{"declaring":1,"down":1}
,"declaring":{"neighbor":1}
,"down":{"dead":1}
,"dead":{"interval":1}
,"interval":{"advertised":1,"received":1,"configured":1,"default":1,"<1-65535>":1,"seconds":1}
,"advertised":{"hello":1}
,"packets":{"ospf":1}
,"compares":{"dead":1}
,"received":{"packet":1}
,"configured":{"receiving":1}
,"receiving":{"interface":1}
,"interface":{"intervals":1,"mode":1,"eth0":1}
,"intervals":{"match":1}
,"match":{"hello":1}
,"discarded":{"parameter":1}
,"parameter":{"command":1}
,"reset":{"interval":1}
,"default":{"command":1,"seconds":1}
,"syntax":{"ipv6":1}
,"<1-65535>":{"ipv6":1,"instance-id":1,"specify":1}
,"instance-id":{"<0-255>":1,"specify":1}
,"<0-255>":{"ipv6":1,"parameters":1,"specify":1}
,"parameters":{"dead-interval":1}
,"specify":{"interval":1,"instance":1}
,"seconds":{"default":1,"instance-id":1}
,"instance":{"<0-255>":1,"command":1}
,"mode":{"interface":1,"examples":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"ipv6":1}
}
;Search.control.loadWordPairs(pairs);
