var pairs =
{
"peb1":{"peb1":1,"configure":1,"(config)":1,"(config-vlan)":1,"(config-cvlan-registration)":1,"(config-if)":1}
,"configure":{"terminal":1,"mode":1,"bridge":1,"vlan":1,"interface":1,"provider-network":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"vlan":1,"interface":1}
,"mode":{"peb1":1,"customer-edge":1,"allow":1,"provider-network":1}
,"(config)":{"bridge":1,"vlan":1,"cvlan":1,"interface":1}
,"bridge":{"protocol":1,"provider-mstp":1,"peb1":1,"state":1,"create":1,"assigning":1}
,"protocol":{"provider-mstp":1}
,"provider-mstp":{"edge":1}
,"edge":{"configure":1,"bridge":1}
,"vlan":{"database":1,"configure":1,"type":1,"customer":1,"peb1":1,"service":1,"(point-to-point":1,"registration":1}
,"database":{"enter":1,"peb1":1}
,"(config-vlan)":{"vlan":1,"exit":1,"ethernet":1}
,"type":{"customer":1,"service":1}
,"customer":{"bridge":1,"vlan":1}
,"state":{"enable":1}
,"enable":{"configure":1}
,"service":{"point-point":1,"vlan":1,"frames":1}
,"point-point":{"bridge":1}
,"(point-to-point":{"evc":1}
,"evc":{"associate":1,"peb1":1}
,"associate":{"bridge":1,"map1":1,"interface":1}
,"exit":{"exit":1,"vlan":1,"interface":1}
,"cvlan":{"registration":1,"svlan":1,"(default":1}
,"registration":{"table":1,"map1":1,"table)":1}
,"table":{"map1":1}
,"map1":{"bridge":1,"associate":1,"(the":1}
,"create":{"cvlan":1}
,"(config-cvlan-registration)":{"cvlan":1}
,"svlan":{"map":1,"peb1":1,"evc-id":1,"evc":1}
,"map":{"cvlan":1}
,"(default":{"vlan)":1}
,"vlan)":{"svlan":1}
,"interface":{"eth1":1,"mode":1,"layer":1,"peb1":1,"customer-edge":1,"eth2":1,"bridge":1,"provider-network":1}
,"eth1":{"enter":1}
,"(config-if)":{"switchport":1,"bridge-group":1,"l2protocol":1,"exit":1}
,"switchport":{"configure":1,"mode":1,"customer-edge":1,"provider-network":1}
,"layer":{"interface":1}
,"bridge-group":{"associate":1}
,"customer-edge":{"hybrid":1,"port":1,"vlan":1}
,"hybrid":{"configure":1,"mode":1,"allowed":1}
,"port":{"hybrid":1,"peb1":1,"allow":1}
,"allowed":{"vlan":1}
,"allow":{"vlans":1,"peb1":1}
,"vlans":{"peb1":1}
,"(the":{"cvlan":1}
,"table)":{"interface":1}
,"l2protocol":{"stp":1}
,"stp":{"discard":1,"service":1}
,"discard":{"discard":1,"stp":1}
,"frames":{"peb1":1}
,"eth2":{"enter":1}
,"provider-network":{"configure":1,"port":1,"allowed":1}
,"ethernet":{"svlan":1}
,"evc-id":{"evc1":1}
,"evc1":{"bridge":1}
,"assigning":{"name":1}
,"name":{"svlan":1}
}
;Search.control.loadWordPairs(pairs);
