var pairs =
{
"cfm_pbb_te_send_mcast_lb":{"function":1}
,"function":{"sends":1,"succeeds":1,"fails":1}
,"sends":{"multicast":1}
,"multicast":{"loopback":1,"messages":1}
,"loopback":{"messages":1}
,"messages":{"mep":1,"sent":1,"recursively":1}
,"mep":{"pbb-te":1,"<1-8191>":1}
,"pbb-te":{"bridge":1}
,"bridge":{"service":1,"identity":1,"md_name":1}
,"service":{"instance":1}
,"instance":{"designate":1,"<1-42949675>":1}
,"designate":{"tlv":1}
,"tlv":{"type":1,"indictor":1,"data":1}
,"type":{"tlv":1}
,"indictor":{"specify":1}
,"specify":{"whether":1}
,"whether":{"messages":1}
,"sent":{"recursively":1}
,"recursively":{"syntax":1,"return":1}
,"syntax":{"struct":1}
,"struct":{"cfm_lb":1}
,"cfm_lb":{"*cfm_pbb_te_send_mcast_lb":1,"structure":1}
,"*cfm_pbb_te_send_mcast_lb":{"(struct":1}
,"(struct":{"onmd_bridge":1}
,"onmd_bridge":{"*bridge":1}
,"*bridge":{"u_int8_t":1}
,"u_int8_t":{"*md_name":1,"tlv_type":1,"recursive_mcast)":1}
,"*md_name":{"u_int32_t":1}
,"u_int32_t":{"mepid":1,"te_sid":1}
,"mepid":{"u_int8_t":1,"source":1}
,"tlv_type":{"u_int16_t":1,"type":1}
,"u_int16_t":{"tlv_indicator":1}
,"tlv_indicator":{"u_int32_t":1,"test":1}
,"te_sid":{"u_int8_t":1,"service":1}
,"recursive_mcast)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bridge":1}
,"identity":{"bridge":1}
,"md_name":{"maintenance":1}
,"maintenance":{"domain":1}
,"domain":{"name":1}
,"name":{"mepid":1}
,"source":{"mep":1}
,"<1-8191>":{"tlv_type":1}
,"data":{"requested":1}
,"requested":{"tlv_indicator":1}
,"test":{"pattern":1}
,"pattern":{"values":1}
,"values":{"test_pattern_indicator":1,"pointer":1}
,"test_pattern_indicator":{"enum":1}
,"enum":{"onmd\u002Fcfm\u002Fcfm_lb.h":1}
,"onmd\u002Fcfm\u002Fcfm_lb.h":{"test_tlv_pattern_1":1}
,"test_tlv_pattern_1":{"test_tlv_pattern_2":1}
,"test_tlv_pattern_2":{"test_tlv_pattern_3":1}
,"test_tlv_pattern_3":{"test_tlv_pattern_4":1}
,"test_tlv_pattern_4":{"te_sid":1}
,"<1-42949675>":{"recursive":1}
,"recursive":{"send":1}
,"send":{"multicast":1}
,"return":{"values":1}
,"pointer":{"cfm_lb":1}
,"structure":{"function":1}
,"succeeds":{"null":1}
,"null":{"function":1}
}
;Search.control.loadWordPairs(pairs);
