var pairs =
{
"architecture":{"meg":1,"crucial":1}
,"meg":{"main":1,"oam":1,"configured":1,"entry":1,"created":1}
,"main":{"card":1,"module":1,"line":1}
,"card":{"line":1,"architectures":1}
,"line":{"card":1,"module":1,"modules":1}
,"architectures":{"allow":1}
,"allow":{"fault":1}
,"fault":{"management":1}
,"management":{"logically":1}
,"logically":{"split":1}
,"split":{"two":1}
,"two":{"parts":1}
,"parts":{"control-card":1}
,"control-card":{"line-card-driven":1}
,"line-card-driven":{"modules":1}
,"modules":{"main-card":1,"updates":1,"communicated":1}
,"main-card":{"module":1}
,"module":{"supports":1,"runs":1,"creates":1,"via":1,"start":1}
,"supports":{"configuration":1}
,"configuration":{"reconfiguration":1}
,"reconfiguration":{"removal":1}
,"removal":{"configurations":1}
,"configurations":{"maintenance":1}
,"maintenance":{"meg":1}
,"oam":{"functions":1,"packets.this":1}
,"functions":{"line-card":1,"configured":1}
,"line-card":{"module":1}
,"runs":{"timers":1}
,"timers":{"creates":1}
,"creates":{"sends":1,"meg":1}
,"sends":{"receives":1}
,"receives":{"processes":1}
,"processes":{"oam":1}
,"packets.this":{"architecture":1}
,"crucial":{"time":1}
,"time":{"sensitive":1}
,"sensitive":{"applications":1}
,"applications":{"cc-cv":1}
,"cc-cv":{"protection":1,"lock":1}
,"protection":{"switching":1}
,"switching":{"detecting":1,"coordination":1}
,"detecting":{"faults":1}
,"faults":{"protecting":1}
,"protecting":{"traffic":1}
,"traffic":{"via":1}
,"via":{"backup":1,"distributed":1,"abstraction":1}
,"backup":{"path":1}
,"path":{"achieved":1}
,"achieved":{"quickly":1}
,"quickly":{"possible":1}
,"possible":{"meg":1}
,"configured":{"operational":1,"including":1}
,"operational":{"status":1}
,"status":{"main":1}
,"entry":{"line":1}
,"distributed":{"api":1}
,"api":{"layer":1}
,"layer":{"distributed":1,"acts":1,"main":1,"once":1}
,"acts":{"abstraction":1}
,"abstraction":{"layer":1}
,"updates":{"main":1}
,"communicated":{"via":1}
,"once":{"meg":1}
,"created":{"line":1}
,"start":{"oam":1}
,"including":{"cc-cv":1}
,"lock":{"instruct":1}
,"instruct":{"(li)":1}
,"(li)":{"loopback":1}
,"loopback":{"(lb)":1}
,"(lb)":{"protection":1}
}
;Search.control.loadWordPairs(pairs);
