var pairs =
{
"satop":{"packet":1,"header":1,"control":1}
,"packet":{"format":1,"sent":1,"loss":1}
,"format":{"path":1}
,"path":{"mtu":1}
,"mtu":{"limiting":1}
,"limiting":{"factor":1}
,"factor":{"total":1}
,"total":{"size":1}
,"size":{"satop":1}
,"sent":{"two":1}
,"two":{"pes":1}
,"pes":{"satop":1}
,"header":{"consists":1,"present":1,"immediately":1}
,"consists":{"satop":1}
,"control":{"word":1}
,"word":{"mandatory":1,"cases":1,"allows":1}
,"mandatory":{"may":1}
,"may":{"contain":1}
,"contain":{"rtp":1}
,"rtp":{"header":1}
,"present":{"rtp":1}
,"immediately":{"follow":1}
,"follow":{"satop":1}
,"cases":{"except":1}
,"except":{"udp":1}
,"udp":{"multiplexing":1}
,"multiplexing":{"using":1}
,"using":{"satop":1}
,"allows":{"users":1}
,"users":{"following":1}
,"following":{"detect":1}
,"detect":{"packet":1}
,"loss":{"mis-ordering":1}
,"mis-ordering":{"differentiate":1}
,"differentiate":{"psn":1}
,"psn":{"(packet-switching":1,"bandwidth":1}
,"(packet-switching":{"network)":1}
,"network)":{"attachment":1}
,"attachment":{"circuit":1}
,"circuit":{"problem":1}
,"problem":{"caused":1}
,"caused":{"outage":1}
,"outage":{"emulated":1}
,"emulated":{"service":1}
,"service":{"conserve":1}
,"conserve":{"psn":1}
,"bandwidth":{"transferring":1}
,"transferring":{"invalid":1}
,"invalid":{"data":1}
,"data":{"(ais)":1}
,"(ais)":{"signal":1}
,"signal":{"fault":1}
,"fault":{"detected":1}
,"detected":{"egress":1}
,"egress":{"ingress":1}
}
;Search.control.loadWordPairs(pairs);
