var pairs =
{
"ipsec_peer_ipv6_address_unset":{"function":1,"(struct":1}
,"function":{"unset":1,"successful":1}
,"unset":{"ipv6":1}
,"ipv6":{"peer":1,"address":1}
,"peer":{"address":1}
,"address":{"syntax":1,"output":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"ipsec_peer_ipv6_address_unset":1}
,"(struct":{"ipsec_crypto_map":1}
,"ipsec_crypto_map":{"*crypto_map":1}
,"*crypto_map":{"struct":1}
,"struct":{"pal_in6_addr":1}
,"pal_in6_addr":{"addr)":1}
,"addr)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"crypto_map":1,"none":1}
,"crypto_map":{"cryptographic":1}
,"cryptographic":{"map":1}
,"map":{"used":1}
,"used":{"setup":1}
,"setup":{"ipsec":1}
,"ipsec":{"addr":1}
,"addr":{"ipv6":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"ipsec_api_success":1}
,"ipsec_api_success":{"function":1}
,"successful":{"ipsec_api_error":1}
,"ipsec_api_error":{"error":1}
}
;Search.control.loadWordPairs(pairs);
