var pairs =
{
"hsl_ifmgr_os_callbacks":{"data":1,"{\u002F*interface":1}
,"data":{"structure":1}
,"structure":{"helps":1}
,"helps":{"manage":1}
,"manage":{"interface":1}
,"interface":{"manager":1,"int":1,"definition":1,"pointer":1,"parameters":1,"returns":1}
,"manager":{"callbacks":1,"initialization":1,"deinitialization":1}
,"callbacks":{"defined":1}
,"defined":{"libhsl\u002Fcommon\u002Fhsl_if_os.h":1}
,"libhsl\u002Fcommon\u002Fhsl_if_os.h":{"type":1}
,"type":{"definition":1}
,"definition":{"int":1,"struct":1}
,"int":{"(*os_if_init)":1,"(*os_if_deinit)":1,"(*os_l2_if_flags_set)":1,"(*os_l2_if_flags_unset)":1,"hwaddrlen":1,"(*os_l3_if_unconfigure)":1,"(*os_l3_if_mtu_set)":1,"mtu":1,"(*os_l3_if_duplex_set)":1,"duplex)":1,"(*os_l3_if_autonego_set)":1,"autonego)":1,"(*os_l3_if_hwaddr_set)":1,"mtu)":1}
,"(*os_if_init)":{"(void)":1}
,"(void)":{"interface":1,"\u002F*interface":1,"\u002F*dump":1}
,"initialization":{"int":1,"*\u002Fint":1}
,"(*os_if_deinit)":{"interface":1,"(void)":1}
,"deinitialization":{"void":1,"*\u002Fint":1}
,"void":{"(*os_if_dump)":1,"*(*os_l3_if_configure)":1,"*null":1}
,"(*os_if_dump)":{"(struct":1}
,"(struct":{"hsl_if":1}
,"hsl_if":{"*ifp)":1,"*ifp":1}
,"*ifp)":{"dump":1,"delete":1,"\u002F*set":1}
,"dump":{"int":1}
,"(*os_l2_if_flags_set)":{"(struct":1}
,"*ifp":{"unsigned":1,"char":1,"int":1}
,"unsigned":{"long":1}
,"long":{"flags)":1}
,"flags)":{"port":1,"unset":1,"\u002F*unset":1,"\u002F*create":1}
,"port":{"flags":1}
,"flags":{"int":1,"void":1,"parameters":1,"-flags":1}
,"(*os_l2_if_flags_unset)":{"(struct":1}
,"unset":{"port":1}
,"*(*os_l3_if_configure)":{"(struct":1}
,"char":{"*name":1}
,"*name":{"u_char":1}
,"u_char":{"*hwaddr":1,"*hwaddr)":1}
,"*hwaddr":{"int":1}
,"hwaddrlen":{"hsl_ifindex_t":1,"u_char":1,"-hardware":1}
,"hsl_ifindex_t":{"*ifindex)":1}
,"*ifindex)":{"create":1,"\u002F*delete":1}
,"create":{"interface":1}
,"(*os_l3_if_unconfigure)":{"(struct":1}
,"delete":{"interface":1}
,"(*os_l3_if_mtu_set)":{"(struct":1}
,"mtu":{"mtu":1,"interface":1,"-mtu":1}
,"(*os_l3_if_duplex_set)":{"(struct":1}
,"duplex)":{"duplex":1,"\u002F*set":1}
,"duplex":{"interface":1,"-duplex":1}
,"(*os_l3_if_autonego_set)":{"(struct":1}
,"autonego)":{"auto-negotiation":1,"\u002F*set":1}
,"auto-negotiation":{"interface":1}
,"(*os_l3_if_hwaddr_set)":{"(struct":1}
,"*hwaddr)":{"hardware":1}
,"hardware":{"address":1}
,"address":{"interface":1,"hwaddrlen":1,"length":1}
,"struct":{"hsl_ifmgr_os_callbacks":1}
,"{\u002F*interface":{"manager":1}
,"*\u002Fint":{"(*os_if_init)":1,"(*os_if_deinit)":1,"(*os_l2_if_flags_set)":1,"(*os_l2_if_flags_unset)":1,"(*os_l3_if_unconfigure)":1,"(*os_l3_if_mtu_set)":1,"(*os_l3_if_duplex_set)":1,"(*os_l3_if_autonego_set)":1,"(*os_l3_if_hwaddr_set)":1}
,"\u002F*interface":{"manager":1}
,"\u002F*dump":{"*\u002Fvoid":1}
,"*\u002Fvoid":{"(*os_if_dump)":1,"*(*os_l3_if_configure)":1}
,"\u002F*set":{"port":1,"mtu":1,"duplex":1,"autonego":1,"address":1}
,"parameters":{"-interface":1,"interface":1,"name":1,"ifp":1}
,"-interface":{"pointer":1,"name":1,"index":1}
,"pointer":{"flags":1,"void":1,"returns":1,"mtu":1,"duplex":1,"autonego":1,"hwadderlen":1}
,"-flags":{"*\u002Fint":1}
,"\u002F*unset":{"port":1}
,"\u002F*create":{"interface":1}
,"name":{"-interface":1,"hwaddr":1}
,"hwaddr":{"-hardware":1,"-address":1}
,"-hardware":{"address":1}
,"length":{"ifindex":1,"hwaddr":1}
,"ifindex":{"-interface":1}
,"index":{"interface":1}
,"returns":{"interface":1,"success":1}
,"*null":{"error":1}
,"error":{"*\u002Fvoid":1,"*\u002Fint":1}
,"\u002F*delete":{"interface":1}
,"success":{"error":1}
,"ifp":{"-interface":1}
,"-mtu":{"returns":1}
,"mtu)":{"\u002F*set":1}
,"-duplex":{"returns":1}
,"autonego":{"interface":1,"-autonego":1}
,"-autonego":{"returns":1}
,"hwadderlen":{"-address":1}
,"-address":{"length":1,"*\u002Fint":1}
}
;Search.control.loadWordPairs(pairs);
