var pairs =
{
"smi":{"alarms":1,"server":1,"client":1}
,"alarms":{"handle":1,"smi":1}
,"handle":{"notification":1}
,"notification":{"alarms":1}
,"server":{"define":1}
,"define":{"callback":1}
,"callback":{"function":1,"determine":1}
,"function":{"smi":1,"zebos_smi_client_set_alarm_callback":1,"implementation":1}
,"client":{"application":1,"shown":1}
,"application":{"whose":1}
,"whose":{"signature":1}
,"signature":{"match":1}
,"match":{"typedef":1}
,"typedef":{"smi_alarm_callback_t":1}
,"smi_alarm_callback_t":{"register":1}
,"register":{"callback":1}
,"zebos_smi_client_set_alarm_callback":{"function":1}
,"implementation":{"callback":1}
,"determine":{"alarm":1,"protocol":1}
,"alarm":{"identifier":1,"smi_msg_alarm":1}
,"identifier":{"shown":1}
,"shown":{"smi_alarm":1,"smi_api_module":1}
,"smi_alarm":{"determine":1}
,"protocol":{"client":1}
,"smi_api_module":{"details":1}
,"details":{"alarm":1}
,"smi_msg_alarm":{"structure":1}
}
;Search.control.loadWordPairs(pairs);
