var pairs =
{
"bridge":{"bridge2":1,"protocol":1,"multiple":1,"configure":1,"instance":1}
,"bridge2":{"configure":1,"(config)":1,"(config-mst)":1,"(config-te-msti)":1,"(config-if)":1}
,"configure":{"terminal":1,"mode":1,"vlan":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"multiple":1,"interface":1}
,"mode":{"bridge2":1,"eth1":1,"access":1,"eth2":1}
,"(config)":{"bridge":1,"vlan":1,"spanning-tree":1,"interface":1}
,"protocol":{"mstp":1}
,"mstp":{"add":1}
,"add":{"bridge":1}
,"multiple":{"spanning":1}
,"spanning":{"tree":1}
,"tree":{"table":1,"configuration":1}
,"table":{"bridge2":1}
,"vlan":{"bridge":1,"associate":1,"create":1,"vlans":1,"range":1,"enable":1,"port":1,"interface":1}
,"associate":{"bridge":1,"interface":1}
,"spanning-tree":{"mst":1}
,"mst":{"configuration":1,"instance":1}
,"configuration":{"enter":1,"mode":1}
,"(config-mst)":{"bridge":1}
,"instance":{"vlan":1,"(msti)":1,"assign":1,"bridge2":1}
,"create":{"instance":1}
,"vlans":{"created":1}
,"created":{"associating":1,"bridge2":1}
,"associating":{"mst":1}
,"(msti)":{"vlan":1}
,"range":{"specified":1}
,"specified":{"msti":1}
,"msti":{"created":1}
,"(config-te-msti)":{"exit":1}
,"exit":{"exit":1,"te-msti":1,"interface":1}
,"te-msti":{"configuration":1}
,"interface":{"eth1":1,"mode":1,"bridge-group":1,"access":1,"bridge2":1,"eth2":1}
,"eth1":{"enter":1,"bridge2":1}
,"(config-if)":{"bridge-group":1,"switchport":1,"exit":1}
,"bridge-group":{"associate":1,"bridge2":1,"instance":1}
,"switchport":{"mode":1,"access":1}
,"access":{"switching":1,"mode":1,"vlan":1,"specifying":1}
,"switching":{"characteristics":1}
,"characteristics":{"interface":1}
,"enable":{"vlan":1}
,"port":{"access":1}
,"specifying":{"vlan":1}
,"assign":{"bridge-group":1}
,"eth2":{"enter":1,"bridge2":1}
}
;Search.control.loadWordPairs(pairs);
