var pairs =
{
"link":{"layer":1}
,"layer":{"discovery":1}
,"discovery":{"protocol":1}
,"protocol":{"commands":1,"(lldp)":1,"extension":1}
,"commands":{"commands":1,"chapter":1}
,"chapter":{"support":1}
,"support":{"link":1}
,"(lldp)":{"version":1}
,"version":{"described":1}
,"described":{"ieee":1}
,"ieee":{"802.1ab":1}
,"802.1ab":{"2009":1}
,"2009":{"lldp-med":1}
,"lldp-med":{"protocol":1}
,"extension":{"per":1}
,"per":{"ansi\u002Ftia-1057":1}
,"ansi\u002Ftia-1057":{"april":1}
,"april":{"2006":1}
,"2006":{"enable":1}
,"enable":{"lldpv2":1,"lldp":1}
,"lldpv2":{"lldp":1}
,"lldp":{"(previous":1,"counters":1,"agent":1,"debug":1,"agt-circuit-id":1,"enable":1,"chassis-id-tlv":1,"disable":1,"locally-assigned":1,"management-address-tlv":1,"med-devtype":1,"msg-tx-hold":1,"port-description":1,"port-id-tlv":1,"timer":1,"too-many-neighbors":1,"tlv-select":1,"system-description":1,"system-name":1,"tx-fast-init":1,"tx-max-credit":1,"debugging":1,"interface":1}
,"(previous":{"version)":1}
,"version)":{"disabled":1}
,"disabled":{"vice":1}
,"vice":{"versa":1}
,"versa":{"clear":1}
,"clear":{"lldp":1}
,"counters":{"lldp":1}
,"agent":{"lldp":1}
,"debug":{"lldp":1}
,"agt-circuit-id":{"lldp":1}
,"chassis-id-tlv":{"lldp":1}
,"disable":{"lldp":1}
,"locally-assigned":{"lldp":1}
,"management-address-tlv":{"lldp":1}
,"med-devtype":{"lldp":1}
,"msg-tx-hold":{"lldp":1}
,"port-description":{"lldp":1}
,"port-id-tlv":{"lldp":1}
,"timer":{"lldp":1}
,"too-many-neighbors":{"lldp":1}
,"tlv-select":{"lldp":1,"med":1,"basic-mgmt":1,"ieee-8021-org-specific":1,"ieee-8023-org-specific":1}
,"med":{"lldp":1}
,"basic-mgmt":{"lldp":1}
,"ieee-8021-org-specific":{"lldp":1}
,"ieee-8023-org-specific":{"lldp":1}
,"system-description":{"lldp":1}
,"system-name":{"lldp":1}
,"tx-fast-init":{"lldp":1}
,"tx-max-credit":{"show":1}
,"show":{"lldp":1}
,"debugging":{"show":1}
,"interface":{"snmp":1}
,"snmp":{"restart":1}
,"restart":{"lldp":1}
}
;Search.control.loadWordPairs(pairs);
