var pairs =
{
"customer-spanning-tree":{"provider-edge":1}
,"provider-edge":{"priority":1,"port":1,"svlan":1}
,"priority":{"command":1,"provider-edge":1,"<0-240>":1,"lower":1,"means":1,"values":1}
,"command":{"port":1,"syntax":1,"mode":1}
,"port":{"priority":1,"customer":1,"<0-240>":1}
,"customer":{"spanning":1}
,"spanning":{"tree":1}
,"tree":{"command":1}
,"syntax":{"customer-spanning-tree":1}
,"svlan":{"<1-4094>":1,"identifier":1,"priority":1}
,"<1-4094>":{"priority":1,"specify":1}
,"<0-240>":{"parameters":1,"specify":1}
,"parameters":{"<1-4094>":1}
,"specify":{"svlan":1,"port":1}
,"identifier":{"provider":1}
,"provider":{"edge":1}
,"edge":{"port":1}
,"lower":{"priority":1}
,"means":{"greater":1}
,"greater":{"likelihood":1}
,"likelihood":{"interface":1}
,"interface":{"becoming":1,"mode":1,"eth1":1}
,"becoming":{"root)":1}
,"root)":{"priority":1}
,"values":{"increments":1}
,"increments":{"default":1}
,"default":{"default":1,"priority":1}
,"mode":{"interface":1,"example":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth1":{"(config-if)":1}
,"(config-if)":{"customer-spanning-tree":1}
}
;Search.control.loadWordPairs(pairs);
