var pairs =
{
"isis_nsm_redistribute_unset":{"call":1,"(struct":1}
,"call":{"sends":1}
,"sends":{"redistribute":1}
,"redistribute":{"unset":1}
,"unset":{"message":1}
,"message":{"request":1,"type":1}
,"request":{"nsm":1}
,"nsm":{"syntax":1}
,"syntax":{"void":1}
,"void":{"isis_nsm_redistribute_unset":1}
,"(struct":{"isis_master":1}
,"isis_master":{"*im":1}
,"*im":{"u_char":1,"represents":1}
,"u_char":{"proto":1}
,"proto":{"int":1,"defines":1}
,"int":{"type)":1}
,"type)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"*im":1,"none":1}
,"represents":{"isis":1}
,"isis":{"master":1}
,"master":{"structure":1}
,"structure":{"proto":1}
,"defines":{"ipv4\u002Fipv6":1}
,"ipv4\u002Fipv6":{"type":1}
,"type":{"message":1,"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"none":1}
}
;Search.control.loadWordPairs(pairs);
