var pairs =
{
"vlan":{"type":1,"customer":1,"(cvlan)":1,"<2-4094>":1,"vlan":1,"name":1,"word":1,"bridge":1,"state":1,"enable":1,"configuration":1,"database":1}
,"type":{"customer":1}
,"customer":{"command":1,"vlan":1,"state":1,"name":1,"bridge":1,"above":1}
,"command":{"identify":1,"syntax":1,"supported":1,"mode":1}
,"identify":{"vlan":1}
,"(cvlan)":{"command":1}
,"syntax":{"vlan":1}
,"<2-4094>":{"type":1,"vlan":1}
,"state":{"(enable":1,"indicates":1,"vlan":1,"enable":1}
,"(enable":{"disable)":1}
,"disable)":{"vlan":1,"above":1}
,"name":{"word":1,"vlan":1,"new":1}
,"word":{"(state":1,"name":1}
,"(state":{"(enable":1}
,"above":{"commands":1,"command":1}
,"commands":{"supported":1}
,"supported":{"zebic":1}
,"zebic":{"releases":1}
,"releases":{"vlan":1}
,"bridge":{"<1-32>":1,"bridge":1,"disable":1,"command":1,"name":1}
,"<1-32>":{"vlan":1,"state":1,"name":1,"parameters":1}
,"parameters":{"vlan":1}
,"indicates":{"state":1}
,"enable":{"forward":1}
,"forward":{"frames":1}
,"frames":{"selected":1}
,"selected":{"vlan-aware":1}
,"vlan-aware":{"bridge":1}
,"disable":{"forward":1}
,"mode":{"vlan":1,"examples":1}
,"configuration":{"mode":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"vlan":1}
,"database":{"(config-vlan)":1}
,"(config-vlan)":{"vlan":1}
,"new":{"state":1}
}
;Search.control.loadWordPairs(pairs);
