var pairs =
{
"features":{"zebos-xp":1,"listed":1}
,"zebos-xp":{"supports":1}
,"supports":{"multi-area":1}
,"multi-area":{"adjacency":1}
,"adjacency":{"features":1}
,"listed":{"below":1}
,"below":{"multi-area-adjacency":1}
,"multi-area-adjacency":{"cli":1,"configuration":1,"display":1,"multiple":1}
,"cli":{"abrs":1}
,"abrs":{"establish":1}
,"establish":{"multiple":1}
,"multiple":{"adjacencies":1,"areas":1}
,"adjacencies":{"belonging":1}
,"belonging":{"different":1}
,"different":{"areas":1}
,"areas":{"multi-area-adjacency":1,"interface":1}
,"configuration":{"neighbor":1,"error":1}
,"neighbor":{"discovery":1}
,"discovery":{"defined":1}
,"defined":{"section":1}
,"section":{"2.1":1}
,"2.1":{"rfc":1}
,"rfc":{"5185":1}
,"5185":{"packet":1,"configuration":1}
,"packet":{"transmission":1}
,"transmission":{"reception":1}
,"reception":{"described":1}
,"described":{"sections":1}
,"sections":{"2.2":1}
,"2.2":{"2.3":1}
,"2.3":{"rfc":1}
,"error":{"link":1}
,"link":{"configured":1,"multi-area-adjacency":1}
,"configured":{"virtual":1}
,"virtual":{"link":1}
,"display":{"multi-area-adjacency":1}
}
;Search.control.loadWordPairs(pairs);
