var pairs =
{
"g8032_api_erp_inst_admin_cmd":{"function":1,"(struct":1}
,"function":{"configures":1,"implements":1,"succeeds":1}
,"configures":{"administrative":1}
,"administrative":{"commands":1}
,"commands":{"function":1}
,"implements":{"force-switch":1}
,"force-switch":{"manual-switch":1}
,"manual-switch":{"command":1}
,"command":{"syntax":1,"is_east":1,"east":1,"west":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"g8032_api_erp_inst_admin_cmd":1}
,"(struct":{"g8032_erps_instance":1}
,"g8032_erps_instance":{"*inst":1}
,"*inst":{"enum":1}
,"enum":{"g8032_admin_cmd":1,"onmd\u002Fcfm\u002Fg8032v2\u002Fg8032_api.h":1}
,"g8032_admin_cmd":{"cmd":1,"enum":1}
,"cmd":{"u_int32_t":1,"role":1}
,"u_int32_t":{"is_east)":1}
,"is_east)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"inst":1,"none":1}
,"inst":{"erp":1,"null":1}
,"erp":{"instance":1}
,"instance":{"cmd":1}
,"role":{"constants":1}
,"constants":{"g8032_admin_cmd":1}
,"onmd\u002Fcfm\u002Fg8032v2\u002Fg8032_api.h":{"g8032_admin_cmd_fs":1}
,"g8032_admin_cmd_fs":{"forcefully":1}
,"forcefully":{"block":1}
,"block":{"ring":1}
,"ring":{"port":1}
,"port":{"g8032_admin_cmd_ms":1,"g8032_admin_cmd_clear":1}
,"g8032_admin_cmd_ms":{"manually":1}
,"manually":{"block":1}
,"g8032_admin_cmd_clear":{"cancel":1}
,"cancel":{"command":1}
,"is_east":{"whether":1}
,"whether":{"apply":1}
,"apply":{"command":1}
,"east":{"west":1,"interface":1}
,"west":{"interface":1}
,"interface":{"pal_true":1,"pal_false":1,"output":1}
,"pal_true":{"apply":1}
,"pal_false":{"apply":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"g8032_error_none":1}
,"g8032_error_none":{"function":1}
,"succeeds":{"g8032_error_erps_inst_not_found":1}
,"g8032_error_erps_inst_not_found":{"inst":1}
}
;Search.control.loadWordPairs(pairs);
