var pairs =
{
"command":{"configure":1,"syntax":1,"mode":1}
,"configure":{"route":1}
,"route":{"distinguisher":1}
,"distinguisher":{"mpls":1,"value.asn:nn":1}
,"mpls":{"layer":1}
,"layer":{"virtual":1}
,"virtual":{"circuit\u002Fvpls":1}
,"circuit\u002Fvpls":{"instance":1}
,"instance":{"command":1}
,"syntax":{"asn:nn_or_ip-address:nn":1}
,"asn:nn_or_ip-address:nn":{"parameters":1,"specify":1}
,"parameters":{"asn:nn_or_ip-address:nn":1}
,"specify":{"route":1}
,"value.asn:nn":{"ip-address:nn":1}
,"ip-address:nn":{"command":1}
,"mode":{"vpws":1,"vpls":1,"example":1}
,"vpws":{"mode":1}
,"vpls":{"mode":1}
,"example":{"(config)":1}
,"(config)":{"l2vpn-vpws":1,"l2vpn-vpls":1}
,"l2vpn-vpws":{"vpws1":1}
,"vpws1":{"(config-vpws)":1}
,"(config-vpws)":{"protocol":1,"vc-id":1,"100:10":1}
,"protocol":{"ldp":1}
,"ldp":{"(config-vpws)":1,"autodiscovery-bgp":1}
,"vc-id":{"(config-vpws)":1}
,"100:10":{"(config)":1}
,"l2vpn-vpls":{"vpls1":1}
,"vpls1":{"(config-vpls)":1}
,"(config-vpls)":{"vpn-id":1,"protocol":1,"100:10":1}
,"vpn-id":{"(config-vpls)":1}
,"autodiscovery-bgp":{"(config-vpls)":1}
}
;Search.control.loadWordPairs(pairs);
