var pairs =
{
"hal_mpls_if_update_vrf":{"function":1,"(struct":1}
,"function":{"updates":1,"fails":1,"succeeds":1}
,"updates":{"vrf":1}
,"vrf":{"mpls":1,"vrf":1,"table":1}
,"mpls":{"interface":1}
,"interface":{"points":1,"identifier":1}
,"points":{"syntax":1}
,"syntax":{"int":1}
,"int":{"hal_mpls_if_update_vrf":1,"vrf)":1}
,"(struct":{"if_ident":1}
,"if_ident":{"*if_ident":1,"interface":1}
,"*if_ident":{"int":1}
,"vrf)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"if_ident":1,"none":1}
,"identifier":{"vrf":1,"output":1}
,"table":{"identifier":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"hal_mpls_vrf_err":1}
,"hal_mpls_vrf_err":{"function":1}
,"fails":{"hal_success":1}
,"hal_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
