var pairs =
{
"link":{"layer":1}
,"layer":{"discovery":1}
,"discovery":{"protocol":1}
,"protocol":{"commands":1,"(lldp)":1}
,"commands":{"chapter":1,"lldp":1}
,"chapter":{"describes":1}
,"describes":{"link":1}
,"(lldp)":{"commands":1}
,"lldp":{"debug":1,"lldp":1,"tlv":1,"chassis-id-tlv":1,"disable":1,"enable":1,"locally-assigned":1,"management-address-tlv":1,"msg-tx-hold":1,"system-description":1,"system-name":1,"timer":1,"too-many-neighbors":1,"snmp":1}
,"debug":{"lldp":1}
,"tlv":{"lldp":1}
,"chassis-id-tlv":{"lldp":1}
,"disable":{"lldp":1}
,"enable":{"lldp":1}
,"locally-assigned":{"lldp":1}
,"management-address-tlv":{"lldp":1}
,"msg-tx-hold":{"lldp":1}
,"system-description":{"lldp":1}
,"system-name":{"lldp":1}
,"timer":{"lldp":1}
,"too-many-neighbors":{"show":1}
,"show":{"lldp":1}
,"snmp":{"restart":1}
,"restart":{"lldp":1}
}
;Search.control.loadWordPairs(pairs);
