var pairs =
{
"vpls-vc":{"command":1,"name":1,"vc1":1}
,"command":{"add":1,"syntax":1,"mode":1}
,"add":{"spoke":1,"vpls":1}
,"spoke":{"virtual":1,"name":1,"ethernet":1,"type":1}
,"virtual":{"circuit":1}
,"circuit":{"vpls":1}
,"vpls":{"domain":1,"mode":1,"test":1}
,"domain":{"parameter":1,"secondary":1}
,"parameter":{"remove":1,"name":1}
,"remove":{"configuration":1}
,"configuration":{"command":1}
,"syntax":{"mpls":1}
,"mpls":{"vpls-vc":1,"add":1,"configure":1,"vpls":1}
,"name":{"(ethernet":1,"(secondary":1,"mpls-tp":1,"parameter":1,"enter":1,"name":1}
,"(ethernet":{"vlan":1}
,"vlan":{"vpls-vc":1,"tunnel-name":1,"identify":1,"tnlname":1}
,"(secondary":{"name":1}
,"mpls-tp":{"vpls-vc":1,"tunnel-name":1,"configure":1}
,"tunnel-name":{"tnlname":1,"command":1,"tnl1":1}
,"tnlname":{"vpls-vc":1,"specify":1}
,"enter":{"string":1}
,"string":{"identifies":1}
,"identifies":{"mpls":1,"secondary":1}
,"secondary":{"secondary":1,"spoke":1}
,"ethernet":{"identify":1,"(default)":1,"tunnel-name":1}
,"identify":{"spoke":1}
,"type":{"ethernet":1,"vlan":1}
,"(default)":{"vlan":1}
,"specify":{"mpls-tp":1}
,"mode":{"vpls":1,"example":1}
,"example":{"mpls":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"mpls":1,"exit":1}
,"test":{"(config-vpls)":1}
,"(config-vpls)":{"vpls-vc":1,"exit":1}
,"vc1":{"(config-vpls)":1,"ethernet":1}
,"exit":{"(config)":1,"mpls-tp":1}
,"tnl1":{"(config-vpls)":1}
}
;Search.control.loadWordPairs(pairs);
