var pairs =
{
"bgp_scan_time_set":{"function":1,"(struct":1}
,"function":{"sets":1,"called":1}
,"sets":{"next-hop":1}
,"next-hop":{"scan":1}
,"scan":{"time":1,"interval":1}
,"time":{"function":1,"successfully":1,"interval":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"bgp":1}
,"bgp":{"scan-time":1,"*bgp":1,"bgp":1,"instance":1,"scan":1}
,"scan-time":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"bgp_scan_time_set":1}
,"(struct":{"bgp":1}
,"*bgp":{"u_int32_t":1}
,"u_int32_t":{"scan_interval)":1}
,"scan_interval)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bgp":1,"none":1}
,"instance":{"case":1}
,"case":{"otherwise":1}
,"otherwise":{"null":1}
,"null":{"scan_interval":1}
,"scan_interval":{"scan":1}
,"interval":{"seconds":1,"maximum":1,"(-2)":1}
,"seconds":{"60>":1}
,"60>":{"default":1}
,"default":{"value":1}
,"value":{"output":1,"bgp_api_set_success":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"bgp_api_set_success":{"bgp":1}
,"successfully":{"(0)":1}
,"(0)":{"bgp_api_set_err_invalid_value":1}
,"bgp_api_set_err_invalid_value":{"scan":1}
,"maximum":{"scan":1}
,"(-2)":{"bgp_api_set_err_nht_disable_rib_scan":1}
,"bgp_api_set_err_nht_disable_rib_scan":{"disabling":1}
,"disabling":{"rib-scan":1}
,"rib-scan":{"allowed":1}
,"allowed":{"nht":1}
,"nht":{"enabled":1}
,"enabled":{"(-74)":1}
}
;Search.control.loadWordPairs(pairs);
