var pairs =
{
"garp":{"multicast":1}
,"multicast":{"registration":1,"group":1,"groups":1}
,"registration":{"protocol":1}
,"protocol":{"(gmrp)":1,"(garp)":1,"(mmrp)":1}
,"(gmrp)":{"generic":1}
,"generic":{"attribute":1}
,"attribute":{"registration":1}
,"(garp)":{"application":1}
,"application":{"allows":1}
,"allows":{"switches":1}
,"switches":{"exchange":1,"prune":1}
,"exchange":{"multicast":1}
,"group":{"information":1}
,"information":{"gmrp":1}
,"gmrp":{"switches":1}
,"prune":{"unnecessary":1}
,"unnecessary":{"broadcast":1}
,"broadcast":{"traffic":1}
,"traffic":{"dynamically":1}
,"dynamically":{"create":1}
,"create":{"manage":1}
,"manage":{"multicast":1}
,"groups":{"multiple":1}
,"multiple":{"mac":1}
,"mac":{"registration":1}
}
;Search.control.loadWordPairs(pairs);
