var pairs =
{
"hsl_ifmgr_l2_ethernet_register":{"function":1,"(char":1}
,"function":{"layer":1,"syntax":1}
,"layer":{"port":1}
,"port":{"registration":1}
,"registration":{"function":1}
,"syntax":{"int":1}
,"int":{"hsl_ifmgr_l2_ethernet_register":1}
,"(char":{"*name":1}
,"*name":{"hsl_mac_address_t":1}
,"hsl_mac_address_t":{"mac":1}
,"mac":{"u_int16_t":1,"mac":1,"address":1}
,"u_int16_t":{"mtu":1}
,"mtu":{"u_int32_t":1,"maximum":1}
,"u_int32_t":{"speed":1,"duplex":1,"flags":1}
,"speed":{"u_int32_t":1,"duplex":1}
,"duplex":{"u_int32_t":1,"duplex":1,"mode":1}
,"flags":{"void":1,"ppifp":1}
,"void":{"*sys_info":1}
,"*sys_info":{"struct":1}
,"struct":{"hsl_if":1}
,"hsl_if":{"**ppifp)":1}
,"**ppifp)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"name":1,"sys_info":1}
,"name":{"interface":1,"mac":1}
,"interface":{"name":1}
,"address":{"mtu":1}
,"maximum":{"transmission":1}
,"transmission":{"unit":1}
,"unit":{"speed":1}
,"mode":{"flags":1}
,"ppifp":{"output":1}
,"output":{"parameters":1}
,"sys_info":{"system":1}
,"system":{"information":1}
,"information":{"return":1}
,"return":{"values":1}
}
;Search.control.loadWordPairs(pairs);
