var pairs =
{
"lldpv2_snmp_set_tx_fast_init":{"function":1,"(u_int32_t":1}
,"function":{"called":1,"succeeds":1,"fails":1}
,"called":{"variable":1}
,"variable":{"determines":1}
,"determines":{"number":1}
,"number":{"lldpdus":1,"lldpdu":1}
,"lldpdus":{"transmitted":1}
,"transmitted":{"during":1,"output":1}
,"during":{"transmission":1}
,"transmission":{"mode":1}
,"mode":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"lldpv2_snmp_set_tx_fast_init":1}
,"(u_int32_t":{"initval":1}
,"initval":{"input":1,"specify":1}
,"input":{"parameters":1}
,"parameters":{"initval":1,"none":1}
,"specify":{"number":1}
,"lldpdu":{"transmitted":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"lldp_api_success":1}
,"lldp_api_success":{"function":1}
,"succeeds":{"lldp_api_error":1}
,"lldp_api_error":{"function":1}
}
;Search.control.loadWordPairs(pairs);
