var pairs =
{
"rsvp_snmp_get_hop_path_op_name":{"function":1,"(u_int32_t":1}
,"function":{"gets":1,"succeeds":1}
,"gets":{"path":1}
,"path":{"option":1,"hop_ix":1}
,"option":{"name":1}
,"name":{"description":1,"return":1}
,"description":{"series":1}
,"series":{"hops":1}
,"hops":{"syntax":1,"configured":1}
,"syntax":{"u_int32_t":1}
,"u_int32_t":{"rsvp_snmp_get_hop_path_op_name":1,"*path_ix":1,"*hop_ix":1}
,"(u_int32_t":{"*ero_ix":1}
,"*ero_ix":{"u_int32_t":1}
,"*path_ix":{"u_int32_t":1}
,"*hop_ix":{"char":1}
,"char":{"**ret)":1}
,"**ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ero_ix":1,"ret":1}
,"ero_ix":{"primary":1}
,"primary":{"index":1}
,"index":{"identifying":1}
,"identifying":{"explicit":1,"group":1,"particular":1}
,"explicit":{"route":1}
,"route":{"object":1}
,"object":{"path_ix":1}
,"path_ix":{"secondary":1}
,"secondary":{"index":1}
,"group":{"hops":1}
,"configured":{"path":1}
,"hop_ix":{"secondary":1}
,"particular":{"hop":1}
,"hop":{"output":1,"found":1}
,"output":{"parameters":1}
,"ret":{"path":1}
,"return":{"value":1}
,"value":{"rsvp_api_get_success":1}
,"rsvp_api_get_success":{"function":1}
,"succeeds":{"rsvp_api_get_error":1}
,"rsvp_api_get_error":{"tunnel":1}
,"tunnel":{"hop":1}
}
;Search.control.loadWordPairs(pairs);
