var pairs =
{
"force-switch":{"manual-switch":1,"forcefully":1,"east-interface":1}
,"manual-switch":{"command":1,"manually":1}
,"command":{"configure":1,"syntax":1,"east":1,"west":1,"command":1,"mode":1}
,"configure":{"administrative":1,"switch":1}
,"administrative":{"commands":1}
,"commands":{"command":1}
,"syntax":{"(((force-switch":1}
,"(((force-switch":{"manual-switch)":1}
,"manual-switch)":{"(east-interface":1}
,"(east-interface":{"west-interface))":1}
,"west-interface))":{"clear)":1}
,"clear)":{"parameters":1}
,"parameters":{"force-switch":1}
,"forcefully":{"block":1}
,"block":{"ring":1}
,"ring":{"port":1}
,"port":{"manual-switch":1,"east-interface":1}
,"manually":{"block":1}
,"east-interface":{"apply":1}
,"apply":{"command":1}
,"east":{"interface":1}
,"interface":{"west-interface":1,"clear":1}
,"west-interface":{"apply":1}
,"west":{"interface":1}
,"clear":{"cancel":1}
,"cancel":{"command":1}
,"mode":{"g.8032":1,"examples":1}
,"g.8032":{"configure":1}
,"switch":{"mode":1}
,"examples":{"(g8032-config-switch)":1}
,"(g8032-config-switch)":{"force-switch":1}
}
;Search.control.loadWordPairs(pairs);
