var pairs =
{
"principles":{"operation":1}
,"operation":{"protection":1,"ring":1}
,"protection":{"algorithm":1,"mechanism":1,"switching":1,"protecting":1,"mode":1}
,"algorithm":{"based":1}
,"based":{"transmission":1}
,"transmission":{"local":1}
,"local":{"switch":1}
,"switch":{"requests":1}
,"requests":{"status":1,"r-aps":1,"control":1}
,"status":{"information":1,"(1bit)":1,"dnf":1,"bits)":1}
,"information":{"ring":1,"defined":1,"following":1}
,"ring":{"nodes":1,"node":1,"physical":1,"erp":1,"protection":1,"interconnection":1,"shared":1,"idle":1,"link":1,"prevents":1,"addressed":1}
,"nodes":{"using":1,"normal":1,"connected":1,"protection":1,"ends":1,"link":1,"shared":1,"two":1}
,"using":{"r-aps":1,"ethernet":1,"information":1}
,"r-aps":{"messages":1,"channel":1,"requests":1,"(sf)":1,"(nr)":1,"(nr":1,"y.1731":1,"specific":1}
,"messages":{"controlling":1,"specified":1,"signal":1,"manage":1,"using":1}
,"controlling":{"protection":1}
,"mechanism":{"protection":1,"nodes":1}
,"switching":{"triggered":1,"effect":1,"within":1,"ring":1}
,"triggered":{"detection":1}
,"detection":{"clearing":1}
,"clearing":{"signal":1}
,"signal":{"failure":1,"fault":1}
,"failure":{"via":1,"loss":1,"triggers":1,"non-shared":1}
,"via":{"ethernet":1}
,"ethernet":{"ccm":1,"connectivity":1}
,"ccm":{"remote":1}
,"remote":{"requests":1}
,"channel":{"expiration":1,"erp":1}
,"expiration":{"timers":1}
,"timers":{"r-aps":1}
,"control":{"communication":1}
,"communication":{"states":1}
,"states":{"ring":1}
,"node":{"two":1,"faults":1,"common":1,"shared":1,"(6octets)":1,"(informational)":1}
,"two":{"basic":1,"adjacent":1,"rings":1,"shared":1,"links":1}
,"basic":{"r-aps":1}
,"specified":{"r-aps":1}
,"(sf)":{"r-aps":1}
,"(nr)":{"rpl":1,"indicate":1}
,"rpl":{"owner":1,"blocked":1,"logical":1,"rings":1,"highest":1}
,"owner":{"may":1,"nr)":1}
,"may":{"modify":1,"happen":1,"act":1,"share":1,"shared":1,"connected":1}
,"modify":{"r-aps":1}
,"indicate":{"rpl":1}
,"blocked":{"example":1,"(used":1}
,"example":{"r-aps":1,"two":1}
,"(nr":{"rb)":1}
,"rb)":{"normal":1}
,"normal":{"operation":1,"operational":1}
,"operational":{"state":1}
,"state":{"characteristics":1}
,"characteristics":{"illustrated":1,"interconnected":1}
,"illustrated":{"below":1}
,"below":{"link":1}
,"link":{"node":1,"monitored":1,"fails":1,"may":1,"signal":1,"(when":1,"failed":1,"shared":1,"two":1,"nodes":1}
,"faults":{"detected":1}
,"detected":{"ring":1}
,"physical":{"topology":1}
,"topology":{"nodes":1}
,"connected":{"ring":1,"without":1,"shared":1,"two":1}
,"erp":{"guarantees":1,"uses":1,"r-aps":1}
,"guarantees":{"loops":1}
,"loops":{"blocking":1}
,"blocking":{"rpl":1}
,"logical":{"topology":1}
,"without":{"loop":1}
,"loop":{"link":1,"may":1,"signaling":1}
,"monitored":{"two":1}
,"adjacent":{"nodes":1}
,"connectivity":{"check":1}
,"check":{"messages":1}
,"loss":{"continuity":1}
,"continuity":{"server":1}
,"server":{"layer":1}
,"layer":{"failure":1}
,"triggers":{"ring":1}
,"protecting":{"operation":1}
,"mode":{"means":1}
,"means":{"protection":1}
,"effect":{"signal":1}
,"fault":{"identified":1}
,"identified":{"interconnected":1}
,"interconnected":{"rings":1}
,"rings":{"characteristics":1,"include":1,"protect":1,"share":1,"agnostic":1,"may":1,"node":1}
,"include":{"following":1}
,"following":{"ring":1,"breakdown":1}
,"interconnection":{"require":1}
,"require":{"changes":1}
,"changes":{"single":1}
,"single":{"ring":1}
,"ends":{"shared":1}
,"shared":{"links":1,"link":1,"two":1,"nodes":1,"example":1,"node":1}
,"links":{"need":1,"ring":1,"exist":1,"links":1,"connected":1}
,"need":{"special":1}
,"special":{"provisioning":1}
,"provisioning":{"support":1}
,"support":{"shared":1}
,"fails":{"necessary":1,"rpl":1}
,"necessary":{"prevent":1,"(future":1}
,"prevent":{"formation":1}
,"formation":{"super":1}
,"super":{"loop":1}
,"happen":{"rings":1}
,"protect":{"time":1}
,"time":{"shared":1}
,"act":{"rpl":1}
,"share":{"link":1,"shared":1}
,"non-shared":{"link":1}
,"(when":{"ring":1}
,"idle":{"state)":1}
,"state)":{"trigger":1}
,"trigger":{"protection":1}
,"within":{"ring":1}
,"failed":{"interconnected":1}
,"agnostic":{"event":1}
,"event":{"interconnected":1}
,"common":{"different":1,"fields":1}
,"different":{"rings":1}
,"exist":{"two":1}
,"highest":{"priority":1}
,"priority":{"protects":1}
,"protects":{"ring":1}
,"prevents":{"formation":1}
,"signaling":{"channel":1}
,"uses":{"r-aps":1}
,"manage":{"coordinate":1}
,"coordinate":{"protection":1}
,"addressed":{"separately":1}
,"separately":{"r-aps":1}
,"defined":{"itu-t":1,"r-aps":1}
,"itu-t":{"y.1731":1}
,"y.1731":{"oam":1,"version":1,"flags":1}
,"oam":{"common":1}
,"fields":{"defined":1}
,"version":{"00000":1,"recommendation":1}
,"00000":{"version":1}
,"recommendation":{"opcode":1}
,"opcode":{"defined":1}
,"flags":{"00000000":1}
,"00000000":{"ignored":1}
,"ignored":{"erp":1}
,"specific":{"information":1,"portion":1}
,"breakdown":{"r-aps":1}
,"portion":{"eth-oam":1}
,"eth-oam":{"message":1}
,"message":{"request\u002Fstatus":1,"source":1}
,"request\u002Fstatus":{"(4bits)":1}
,"(4bits)":{"1011":1,"status":1}
,"1011":{"=sf":1}
,"=sf":{"0000":1}
,"0000":{"=nr":1}
,"=nr":{"=future":1}
,"=future":{"status":1}
,"(1bit)":{"rpl":1,"fdb":1}
,"(used":{"rpl":1}
,"nr)":{"status":1}
,"dnf":{"(1bit)":1}
,"fdb":{"flush":1}
,"flush":{"necessary":1}
,"(future":{"development)":1}
,"development)":{"node":1}
,"(6octets)":{"mac":1}
,"mac":{"address":1}
,"address":{"message":1}
,"source":{"node":1}
,"(informational)":{"reserved1":1}
,"reserved1":{"(4bits)":1}
,"bits)":{"reserved2":1}
,"reserved2":{"(24octets)":1}
,"(24octets)":{"(for":1}
,"(for":{"future":1}
,"future":{"development)":1}
}
;Search.control.loadWordPairs(pairs);
