var pairs =
{
"isis_get_next_sys_max_age":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"value":1}
,"value":{"place":1,"non-vr":1}
,"place":{"lsps":1,"remaininglifetime":1}
,"lsps":{"generated":1,"return":1}
,"generated":{"next":1}
,"next":{"instance":1}
,"instance":{"is-is":1,"indexlen":1,"found":1}
,"is-is":{"protocol":1,"instance":1}
,"protocol":{"syntax":1}
,"syntax":{"int":1}
,"int":{"isis_get_next_sys_max_age":1,"indexlen":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1,"instance":1}
,"u_int32_t":{"*instance":1,"*ret)":1}
,"*instance":{"int":1}
,"indexlen":{"u_int32_t":1,"length":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"ret":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"length":{"index":1}
,"index":{"output":1}
,"output":{"parameters":1}
,"ret":{"value":1}
,"remaininglifetime":{"field":1}
,"field":{"lsps":1}
,"return":{"values":1}
,"values":{"isis_api_get_success":1}
,"isis_api_get_success":{"next":1}
,"found":{"isis_api_get_error":1}
,"isis_api_get_error":{"next":1}
}
;Search.control.loadWordPairs(pairs);
