var pairs =
{
"c-vlan":{"s-vlan":1,"tags":1,"component":1}
,"s-vlan":{"components":1,"component":1}
,"components":{"standard":1,"provider":1}
,"standard":{"defines":1,"specifies":1}
,"defines":{"s-tag":1,"specifies":1}
,"s-tag":{"switching":1,"c-vlan":1}
,"switching":{"service":1}
,"service":{"provider":1,"(s-vlan)":1,"instance":1,"instances":1,"vlan":1}
,"provider":{"domain":1,"vlan":1,"assigning":1,"bridge":1,"edge":1,"bridges":1,"network":1}
,"domain":{"differentiates":1}
,"differentiates":{"provides":1}
,"provides":{"format":1,"either":1,"c-tagged":1}
,"format":{"c-vlan":1}
,"tags":{"used":1,"operate":1,"standard":1,"bpdus":1}
,"used":{"customer":1,"provider":1}
,"customer":{"network":1,"(c-vlan)":1,"bridge":1,"interfaces":1,"select":1,"vlan":1,"edge":1,"port":1,"relay":1,"ports":1}
,"network":{"provider":1,"terms":1,"port":1,"ports":1}
,"vlan":{"tags":1,"identifier":1}
,"assigning":{"different":1}
,"different":{"ethernet":1}
,"ethernet":{"types":1}
,"types":{"tag":1}
,"tag":{"existing":1,"named":1}
,"existing":{"tag":1}
,"named":{"tags":1}
,"operate":{"two":1}
,"two":{"tags":1,"bridges":1}
,"specifies":{"functionality":1,"customer":1}
,"functionality":{"two":1}
,"bridges":{"s-vlan":1,"including":1}
,"component":{"switches":1}
,"switches":{"based":1,"customer":1}
,"based":{"s-tag":1,"c-tag":1}
,"c-tag":{"customer-facing":1}
,"customer-facing":{"side":1}
,"side":{"operates":1}
,"operates":{"customer":1,"service":1}
,"(c-vlan)":{"tags":1}
,"bpdus":{"provider-facing":1,"interconnection":1}
,"provider-facing":{"side":1}
,"(s-vlan)":{"tags":1}
,"interconnection":{"customer":1}
,"bridge":{"provider":1,"uses":1,"network":1,"components":1,"port":1,"ports":1}
,"uses":{"virtual":1}
,"virtual":{"port":1}
,"port":{"called":1,"(pep)":1,"(port-based":1,"(cnp)":1,"(pnp)":1,"(ce":1,"provides":1,"customer":1,"provider":1}
,"called":{"provider":1}
,"edge":{"port":1}
,"(pep)":{"standard":1}
,"interfaces":{"provider":1,"offer":1}
,"terms":{"operation":1}
,"operation":{"configuration":1}
,"configuration":{"vlan-aware":1}
,"vlan-aware":{"bridge":1}
,"including":{"interfaces":1}
,"offer":{"following":1}
,"following":{"provide":1}
,"provide":{"access":1}
,"access":{"single":1}
,"single":{"service":1,"customer":1}
,"instance":{"bridge":1}
,"(port-based":{"service)":1}
,"service)":{"allow":1}
,"allow":{"customer":1}
,"select":{"amongst":1}
,"amongst":{"identify":1}
,"identify":{"service":1}
,"instances":{"customer":1,"service":1}
,"identifier":{"(c-vid)":1,"(s-vid)":1}
,"(c-vid)":{"c-tagged":1}
,"c-tagged":{"services":1,"interface":1}
,"services":{"allow":1,"bridge":1,"single":1}
,"(s-vid)":{"s-tagged":1}
,"s-tagged":{"services":1,"port-based":1}
,"ports":{"classified":1,"data":1}
,"classified":{"customer":1}
,"(cnp)":{"provider":1}
,"(pnp)":{"customer":1}
,"(ce":{"port)":1}
,"port)":{"pnp":1}
,"pnp":{"transmits":1}
,"transmits":{"receives":1}
,"receives":{"frames":1}
,"frames":{"multiple":1}
,"multiple":{"customers":1}
,"customers":{"cnp":1}
,"cnp":{"provides":1}
,"either":{"s-tagged":1}
,"port-based":{"services":1}
,"interface":{"single":1}
,"relay":{"entity":1}
,"entity":{"switches":1}
,"data":{"switched":1}
,"switched":{"customer":1}
}
;Search.control.loadWordPairs(pairs);
