var pairs =
{
"primary":{"fast-reroute":1}
,"fast-reroute":{"setup-priority":1}
,"setup-priority":{"command":1,"detour":1,"<0-7>":1,"(<0-7>":1}
,"command":{"configure":1,"helps":1,"remove":1,"syntax":1,"mode":1}
,"configure":{"setup-priority":1,"terminal":1}
,"detour":{"lsp":1}
,"lsp":{"command":1,"either":1,"setup-priority":1}
,"helps":{"identify":1}
,"identify":{"attributes":1}
,"attributes":{"frr":1}
,"frr":{"backup":1}
,"backup":{"lsp":1}
,"either":{"one-to-one":1}
,"one-to-one":{"facility-backup":1}
,"facility-backup":{"protection":1}
,"protection":{"methods":1}
,"methods":{"parameter":1}
,"parameter":{"command":1,"<0-7>":1}
,"remove":{"detour":1}
,"syntax":{"primary":1}
,"<0-7>":{"primary":1,"value":1}
,"(<0-7>":{"parameter":1}
,"value":{"setup":1}
,"setup":{"priority":1}
,"priority":{"command":1}
,"mode":{"trunk":1,"examples":1}
,"trunk":{"mode":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"rsvp-trunk":1}
,"rsvp-trunk":{"(config-trunk)":1}
,"(config-trunk)":{"primary":1}
}
;Search.control.loadWordPairs(pairs);
