var pairs =
{
"neighbor":{"distribute-list":1,"parameter":1,"(a.b.c.d":1,"ipv4":1,"ipv6":1,"peer-group":1,"remote-as":1,"1.2.3.4":1}
,"distribute-list":{"command":1,"per":1,"(<1-199>":1,"mylist":1}
,"command":{"filter":1,"remove":1,"syntax":1,"command":1,"applies":1,"mode":1}
,"filter":{"route":1,"incoming":1,"outgoing":1}
,"route":{"updates":1}
,"updates":{"particular":1}
,"particular":{"bgp":1}
,"bgp":{"neighbor":1,"peer":1,"(config-router)":1}
,"per":{"bgp":1}
,"parameter":{"command":1,"used":1}
,"remove":{"entry":1}
,"entry":{"command":1}
,"syntax":{"neighbor":1}
,"(a.b.c.d":{"x:x":1}
,"x:x":{":x:x":1}
,":x:x":{"word)":1,"address":1}
,"word)":{"distribute-list":1,"(in":1}
,"(<1-199>":{"<1300-2699>":1}
,"<1300-2699>":{"word)":1,"access-list":1}
,"(in":{"out)":1}
,"out)":{"neighbor":1,"parameters":1}
,"parameters":{"a.b.c.d":1}
,"a.b.c.d":{"address":1}
,"address":{"bgp":1,"family":1}
,"ipv4":{"format":1}
,"format":{"x:x":1,"word":1}
,"ipv6":{"format":1}
,"word":{"name":1,"access-list":1}
,"name":{"bgp":1,"filter":1}
,"peer":{"group":1,"groups":1}
,"group":{"information":1,"<1-199>":1}
,"information":{"create":1}
,"create":{"peer":1}
,"groups":{"refer":1}
,"refer":{"neighbor":1}
,"peer-group":{"neighbor":1}
,"remote-as":{"commands":1}
,"commands":{"parameter":1}
,"used":{"command":1}
,"applies":{"peers":1}
,"peers":{"group":1}
,"<1-199>":{"access-list":1}
,"access-list":{"number":1,"name":1}
,"number":{"<1300-2699>":1,"(expanded-range)":1}
,"(expanded-range)":{"word":1}
,"incoming":{"advertised":1}
,"advertised":{"routes":1}
,"routes":{"filter":1,"command":1}
,"outgoing":{"advertised":1}
,"mode":{"router":1,"address":1,"examples":1}
,"router":{"mode":1,"bgp":1}
,"family":{"mode":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"(config-router)":{"neighbor":1}
,"1.2.3.4":{"distribute-list":1}
}
;Search.control.loadWordPairs(pairs);
