var pairs =
{
"ospf6_get_nbr_state":{"function":1,"(char":1}
,"function":{"gets":1,"fails":1,"succeeds":1}
,"gets":{"state":1}
,"state":{"relationship":1}
,"relationship":{"given":1,"neighbor":1}
,"given":{"router":1}
,"router":{"neighbor":1,"identifier":1,"output":1}
,"neighbor":{"syntax":1,"down":1}
,"syntax":{"int":1}
,"int":{"ospf6_get_nbr_state":1,"ifindex":1,"instid":1,"*ret)":1}
,"(char":{"*tag":1}
,"*tag":{"int":1}
,"ifindex":{"int":1,"interface":1}
,"instid":{"struct":1,"instance":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"router_id":1}
,"router_id":{"int":1,"router":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"tag":1,"ret":1}
,"tag":{"ospfv3":1,"ifindex":1}
,"ospfv3":{"process":1}
,"process":{"tag":1}
,"interface":{"index":1}
,"index":{"instid":1}
,"instance":{"identifier":1}
,"identifier":{"router_id":1,"originating":1}
,"originating":{"router":1}
,"output":{"parameters":1}
,"ret":{"state":1}
,"down":{"attempt":1}
,"attempt":{"init":1}
,"init":{"twoway":1}
,"twoway":{"exchangestart":1}
,"exchangestart":{"exchange":1}
,"exchange":{"loading":1}
,"loading":{"full":1}
,"full":{"return":1}
,"return":{"values":1}
,"values":{"ospf6_api_get_error":1}
,"ospf6_api_get_error":{"function":1}
,"fails":{"ospf6_api_get_success":1}
,"ospf6_api_get_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
