var pairs =
{
"hal_dcb_interface_enable":{"function":1,"(char":1}
,"function":{"sends":1}
,"sends":{"hal_msg_dcb_if_enable":1}
,"hal_msg_dcb_if_enable":{"message":1}
,"message":{"hsl":1,"passes":1}
,"hsl":{"enable":1,"syntax":1}
,"enable":{"dcb":1}
,"dcb":{"hardware":1}
,"hardware":{"interface":1}
,"interface":{"message":1,"index":1}
,"passes":{"interface":1}
,"index":{"default":1,"output":1}
,"default":{"configuration":1}
,"configuration":{"parameters":1}
,"parameters":{"hsl":1,"bridge_name":1,"none":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"hal_dcb_interface_enable":1,"ifindex)":1}
,"(char":{"*bridge_name":1}
,"*bridge_name":{"s_int32_t":1}
,"ifindex)":{"input":1}
,"input":{"parameters":1}
,"bridge_name":{"bridge":1}
,"bridge":{"name":1}
,"name":{"ifindex":1}
,"ifindex":{"interface":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"hal_success":1}
}
;Search.control.loadWordPairs(pairs);
