var pairs =
{
"zebhpi":{"zebhpi":1,"(host":1,"standalone":1}
,"(host":{"protocol":1}
,"protocol":{"interface)":1,"client":1,"relay":1,"network":1,"remote":1,"syslog":1}
,"interface)":{"system":1}
,"system":{"management":1,"lightweight":1}
,"management":{"module":1,"protocol":1,"zebhpi":1}
,"module":{"supports":1}
,"supports":{"host":1}
,"host":{"protocols":1,"configuration":1}
,"protocols":{"authentication":1}
,"authentication":{"authorization":1,"dial":1}
,"authorization":{"accounting":1}
,"accounting":{"dynamic":1}
,"dynamic":{"host":1}
,"configuration":{"protocol":1}
,"client":{"dynamic":1}
,"relay":{"domain":1}
,"domain":{"name":1}
,"name":{"system":1}
,"lightweight":{"directory":1}
,"directory":{"access":1}
,"access":{"protocol":1}
,"network":{"time":1,"management":1}
,"time":{"protocol":1}
,"remote":{"authentication":1}
,"dial":{"user":1}
,"user":{"service":1,"management":1}
,"service":{"secure":1}
,"secure":{"shell":1}
,"shell":{"simple":1}
,"simple":{"network":1}
,"syslog":{"tacacs":1}
,"tacacs":{"telnet":1}
,"telnet":{"user":1}
,"standalone":{"package":1}
,"package":{"integrated":1}
,"integrated":{"zebos-xp":1}
}
;Search.control.loadWordPairs(pairs);
