var pairs =
{
"debug":{"ipv6":1,"redistribute":1,"nsm":1}
,"ipv6":{"ospf":1}
,"ospf":{"nsm":1}
,"nsm":{"command":1,"information":1,"{(interface":1,"interface":1}
,"command":{"specify":1,"disable":1,"syntax":1,"mode":1}
,"specify":{"debugging":1}
,"debugging":{"options":1}
,"options":{"ospfv3":1}
,"ospfv3":{"nsm":1}
,"information":{"parameter":1}
,"parameter":{"command":1}
,"disable":{"function":1}
,"function":{"command":1}
,"syntax":{"debug":1}
,"{(interface":{"redistribute)":1}
,"redistribute)":{"debug":1,"undebug":1,"parameters":1}
,"undebug":{"ipv6":1}
,"parameters":{"redistribute":1}
,"redistribute":{"debug":1,"interface":1}
,"interface":{"debug":1,"command":1}
,"mode":{"privileged":1,"configure":1,"examples":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"configure":{"mode":1}
,"examples":{"debug":1}
}
;Search.control.loadWordPairs(pairs);
