var pairs =
{
"feature":{"command":1,"feature":1,"group":1,"word":1,"mode":1,"igmp_if":1,"ospf6":1,"vportmgr":1}
,"command":{"add":1,"syntax":1,"mode":1}
,"add":{"feature":1}
,"group":{"command":1}
,"syntax":{"feature":1}
,"word":{"parameters":1,"protocols\u002Ffeatures":1}
,"parameters":{"word":1}
,"protocols\u002Ffeatures":{"below":1}
,"below":{"bgp":1}
,"bgp":{"hostp":1}
,"hostp":{"igmp":1}
,"igmp":{"igmp_if":1}
,"igmp_if":{"isis":1,"(config-role-featuregrp)":1}
,"isis":{"l2mrib":1}
,"l2mrib":{"ldp":1}
,"ldp":{"mld":1}
,"mld":{"mld_if":1}
,"mld_if":{"mrib":1}
,"mrib":{"mrib4":1}
,"mrib4":{"mrib4_if":1}
,"mrib4_if":{"mrib6":1}
,"mrib6":{"mrib6_if":1}
,"mrib6_if":{"mstp":1}
,"mstp":{"ospf":1}
,"ospf":{"ospf6":1}
,"ospf6":{"pim":1,"(config-role-featuregrp)":1}
,"pim":{"rib":1}
,"rib":{"rip":1}
,"rip":{"ripng":1}
,"ripng":{"rstp":1}
,"rstp":{"rvsp":1}
,"rvsp":{"stp":1}
,"stp":{"trill":1}
,"trill":{"vportmgr":1}
,"vportmgr":{"vrrp":1}
,"vrrp":{"command":1}
,"mode":{"role":1,"example":1}
,"role":{"feature":1,"feature-group":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"role":1}
,"feature-group":{"group-name":1}
,"group-name":{"ann-arbor":1}
,"ann-arbor":{"(config-role-featuregrp)":1}
,"(config-role-featuregrp)":{"feature":1}
}
;Search.control.loadWordPairs(pairs);
