var pairs =
{
"overview":{"mib":1}
,"mib":{"implementation":1,"support":1,"contains":1}
,"implementation":{"mib":1}
,"support":{"vrrp":1}
,"vrrp":{"based":1,"mib":1,"router":1,"routers":1}
,"based":{"draft-ietf-vrrp-unified-mib-06.txt":1}
,"draft-ietf-vrrp-unified-mib-06.txt":{"vrrp":1}
,"contains":{"following":1}
,"following":{"three":1}
,"three":{"groups":1}
,"groups":{"vrrpoperations":1}
,"vrrpoperations":{"group":1}
,"group":{"consists":1}
,"consists":{"objects":1}
,"objects":{"related":1,"containing":1,"definitions":1}
,"related":{"configuration":1}
,"configuration":{"control":1}
,"control":{"vrrp":1}
,"router":{"vrrpstatistics":1}
,"vrrpstatistics":{"group":1}
,"containing":{"information":1}
,"information":{"useful":1}
,"useful":{"monitoring":1}
,"monitoring":{"operation":1}
,"operation":{"vrrp":1}
,"routers":{"vrrpnotifications":1,"send":1}
,"vrrpnotifications":{"group":1}
,"definitions":{"snmp":1}
,"snmp":{"notifications":1}
,"notifications":{"vrrp":1}
}
;Search.control.loadWordPairs(pairs);
