var pairs =
{
"dot3oamloopbackgroup":{"objects":1}
,"objects":{"group":1}
,"group":{"control":1}
,"control":{"loopback":1}
,"loopback":{"state":1,"function":1,"disruptive":1,"requests":1}
,"state":{"local":1}
,"local":{"link":1}
,"link":{"status":1}
,"status":{"loopback":1}
,"function":{"loopback":1}
,"disruptive":{"dot3oamloopbackignorerx":1}
,"dot3oamloopbackignorerx":{"controls":1,"integer":1}
,"controls":{"whether":1}
,"whether":{"loopback":1}
,"requests":{"received":1}
,"received":{"processed":1}
,"processed":{"ignored":1}
,"ignored":{"object":1}
,"object":{"type":1}
,"type":{"syntax":1}
,"syntax":{"access":1}
,"access":{"functions":1}
,"functions":{"dot3oamloopbackstatus":1}
,"dot3oamloopbackstatus":{"integer":1}
,"integer":{"read-write":1}
,"read-write":{"efm_oam_get_loopback_status":1,"efm_oam_get_loopback_ignore_rx":1}
,"efm_oam_get_loopback_status":{"efm_oam_set_loopback_status":1}
,"efm_oam_set_loopback_status":{"dot3oamloopbackignorerx":1}
,"efm_oam_get_loopback_ignore_rx":{"efm_oam_set_loopback_ignore_rx":1}
}
;Search.control.loadWordPairs(pairs);
