var pairs =
{
"system":{"design":1,"pizza":1,"generally":1}
,"design":{"bfd":1}
,"bfd":{"run":1,"generally":1,"base":1,"hello":1}
,"run":{"pizza":1,"bfd":1,"either":1}
,"pizza":{"box":1}
,"box":{"chassis-based":1,"monolithic":1}
,"chassis-based":{"system":1}
,"monolithic":{"version":1}
,"version":{"bfd":1,"hello-sending":1}
,"generally":{"used":1,"advisable":1}
,"used":{"although":1,"chassis-based":1}
,"although":{"distributed":1}
,"distributed":{"version":1,"across":1}
,"hello-sending":{"functionality":1}
,"functionality":{"running":1}
,"running":{"either":1}
,"either":{"separate":1,"software":1}
,"separate":{"process":1}
,"process":{"hardware":1}
,"hardware":{"used":1}
,"advisable":{"run":1}
,"base":{"module":1}
,"module":{"along":1}
,"along":{"control":1}
,"control":{"plane":1,"processor":1}
,"plane":{"processes":1}
,"processes":{"central":1}
,"central":{"control":1}
,"processor":{"bfd":1}
,"hello":{"processing":1}
,"processing":{"modules":1,"run":1}
,"modules":{"distributed":1}
,"across":{"line":1}
,"line":{"cards":1}
,"cards":{"hello":1}
,"software":{"hardware":1}
}
;Search.control.loadWordPairs(pairs);
