var pairs =
{
"clear":{"ssh":1,"known_hosts":1,"trusted":1}
,"ssh":{"hosts":1,"servers":1,"server":1}
,"hosts":{"command":1,"parameters":1}
,"command":{"clear":1,"clears":1,"syntax":1,"mode":1}
,"known_hosts":{"file":1}
,"file":{"command":1,"external":1,"connections":1,"words":1}
,"clears":{"trusted":1}
,"trusted":{"relationships":1,"relationship":1}
,"relationships":{"established":1}
,"established":{"ssh":1}
,"servers":{"during":1}
,"during":{"previous":1}
,"previous":{"connections":1}
,"connections":{"client":1,"server":1}
,"client":{"downloads":1,"stores":1,"accepts":1}
,"downloads":{"file":1}
,"external":{"server":1}
,"server":{"first":1,"keys":1,"server":1}
,"first":{"time":1}
,"time":{"client":1,"example":1}
,"stores":{"server":1}
,"keys":{"known_hosts":1,"stored":1,"first":1,"changed":1}
,"stored":{"known_hosts":1}
,"words":{"trusted":1}
,"relationship":{"created":1,"ssh":1}
,"created":{"client":1}
,"accepts":{"server":1}
,"example":{"need":1}
,"need":{"clear":1}
,"changed":{"command":1}
,"syntax":{"clear":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"configure":1,"examples":1}
,"configure":{"mode":1,"terminal":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"clear":1}
}
;Search.control.loadWordPairs(pairs);
