var pairs =
{
"pim4_api_bidir_enable":{"function":1,"(u_int32_t":1}
,"function":{"enables":1,"executes":1}
,"enables":{"bidirectional":1}
,"bidirectional":{"pim":1}
,"pim":{"syntax":1,"vrf":1}
,"syntax":{"int":1}
,"int":{"pim4_api_bidir_enable":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"vrf_id_t":1,"virtual":1}
,"vrf_id_t":{"vrf_id)":1}
,"vrf_id)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"(0-255)":1}
,"(0-255)":{"vrf_id":1}
,"vrf_id":{"vpn":1}
,"vpn":{"routing\u002Fforwarding":1}
,"routing\u002Fforwarding":{"instance":1}
,"instance":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"pim_api_set_err_wrong_value":1}
,"pim_api_set_err_wrong_value":{"invalid":1}
,"invalid":{"value":1}
,"value":{"given":1}
,"given":{"pim_api_set_err_wrong_vrf":1}
,"pim_api_set_err_wrong_vrf":{"pim":1}
,"vrf":{"interface":1}
,"interface":{"found":1}
,"found":{"pim_api_set_error":1,"pim_api_success":1}
,"pim_api_set_error":{"bsr":1}
,"bsr":{"information":1}
,"information":{"found":1}
,"pim_api_success":{"function":1}
,"executes":{"properly":1}
}
;Search.control.loadWordPairs(pairs);
