var pairs =
{
"overview":{"zebha":1}
,"zebha":{"(high":1,"provides":1,"ensures":1,"system":1,"allows":1,"configuration":1,"high":1}
,"(high":{"availability)":1}
,"availability)":{"module":1}
,"module":{"supports":1}
,"supports":{"protocol":1}
,"protocol":{"modules":1,"recovery":1,"states":1,"(lacp)":1,"(mstp)":1}
,"modules":{"layer":1}
,"layer":{"layer":1,"zebha":1,"routing":1,"forwarding":1}
,"provides":{"control":1}
,"control":{"plane":1,"protocol":1}
,"plane":{"redundancy":1,"cpu":1,"switched":1}
,"redundancy":{"necessary":1,"two":1,"switchover":1}
,"necessary":{"meet":1}
,"meet":{"needs":1}
,"needs":{"network":1,"even":1}
,"network":{"operators":1,"service":1,"operator":1}
,"operators":{"high":1}
,"high":{"network":1,"availability":1}
,"service":{"availability":1,"level":1,"node":1}
,"availability":{"reliable":1,"overview":1,"mean":1,"developer":1}
,"reliable":{"handling":1}
,"handling":{"operational":1}
,"operational":{"application":1,"performance":1}
,"application":{"system":1}
,"system":{"component":1,"downtime":1,"operates":1,"available":1}
,"component":{"failures":1}
,"failures":{"strict":1}
,"strict":{"service":1}
,"level":{"agreements":1,"operational":1}
,"agreements":{"(sla)":1}
,"(sla)":{"requirements":1}
,"requirements":{"network":1}
,"operator":{"customers":1}
,"customers":{"high":1}
,"ensures":{"pre-agreed":1,"system":1}
,"pre-agreed":{"level":1}
,"performance":{"minimizing":1}
,"minimizing":{"system":1}
,"downtime":{"zebha":1}
,"operates":{"redundant":1}
,"redundant":{"nodes":1}
,"nodes":{"provide":1}
,"provide":{"continued":1}
,"continued":{"service":1}
,"node":{"fails":1}
,"fails":{"high":1}
,"mean":{"components":1}
,"components":{"fail":1}
,"fail":{"ensures":1,"zebha":1}
,"available":{"user":1}
,"user":{"needs":1}
,"even":{"components":1}
,"allows":{"simplex-active":1,"rebuilding":1}
,"simplex-active":{"active-standby":1}
,"active-standby":{"control":1}
,"cpu":{"redundancy":1}
,"two":{"types":1}
,"types":{"protocol":1}
,"recovery":{"redundancy":1,"allows":1,"process":1}
,"switchover":{"stateful":1,"(sso)":1}
,"stateful":{"switchover":1}
,"(sso)":{"recovers":1}
,"recovers":{"protocols":1}
,"protocols":{"complete":1,"ospf":1}
,"complete":{"checkpointing":1}
,"checkpointing":{"protocol":1}
,"states":{"performed":1,"layer":1}
,"performed":{"link":1}
,"link":{"aggregation":1}
,"aggregation":{"control":1}
,"(lacp)":{"multiple":1}
,"multiple":{"spanning":1}
,"spanning":{"tree":1}
,"tree":{"protocol":1}
,"(mstp)":{"rib":1}
,"rib":{"daemon":1}
,"daemon":{"interface":1}
,"interface":{"manager":1}
,"manager":{"completely":1}
,"completely":{"checkpointed":1}
,"checkpointed":{"active":1}
,"active":{"standby":1,"controller":1}
,"standby":{"controllers":1}
,"controllers":{"graceful":1}
,"graceful":{"restart":1}
,"restart":{"recovery":1}
,"rebuilding":{"routing":1}
,"routing":{"database":1,"protocols":1,"information":1}
,"database":{"protocol":1}
,"ospf":{"is-is":1}
,"is-is":{"bgp":1}
,"bgp":{"without":1}
,"without":{"withdrawing":1}
,"withdrawing":{"routes":1}
,"routes":{"zebos-xp":1}
,"zebos-xp":{"global":1}
,"global":{"routing":1}
,"information":{"base":1,"zebha":1}
,"base":{"(rib)":1}
,"(rib)":{"during":1}
,"during":{"post-switchover":1}
,"post-switchover":{"recovery":1}
,"process":{"layer":1}
,"forwarding":{"planes":1,"data":1}
,"planes":{"continue":1}
,"continue":{"uninterrupted":1}
,"uninterrupted":{"forwarding":1}
,"data":{"packets":1}
,"packets":{"control":1}
,"switched":{"new":1}
,"new":{"active":1}
,"controller":{"zebha":1}
,"configuration":{"information":1}
,"developer":{"guide":1}
}
;Search.control.loadWordPairs(pairs);
