var pairs =
{
"nsm_dcb_ets_enable_interface":{"function":1,"(u_int32_t":1}
,"function":{"enable":1,"succeeds":1}
,"enable":{"ets":1}
,"ets":{"feature":1}
,"feature":{"dcb":1}
,"dcb":{"interface":1}
,"interface":{"syntax":1,"name":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"nsm_dcb_ets_enable_interface":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1}
,"char":{"*ifname":1}
,"*ifname":{"bool_t":1}
,"bool_t":{"mode)":1}
,"mode)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"ifname":1}
,"ifname":{"interface":1}
,"name":{"mode":1}
,"mode":{"constants":1}
,"constants":{"nsm_dcb_mode":1}
,"nsm_dcb_mode":{"enum":1}
,"enum":{"nsm\u002Fl2\u002Fnsm_dcb.h":1}
,"nsm\u002Fl2\u002Fnsm_dcb.h":{"nsm_dcb_mode_on":1}
,"nsm_dcb_mode_on":{"nsm_dcb_mode_auto":1}
,"nsm_dcb_mode_auto":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_dcb_api_set_success":1}
,"nsm_dcb_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
