var pairs =
{
"functionality":{"feature":1}
,"feature":{"provides":1}
,"provides":{"following":1}
,"following":{"cli":1}
,"cli":{"support":1,"route":1}
,"support":{"ospf":1}
,"ospf":{"domain":1,"bgp":1,"router-type":1}
,"domain":{"identifier":1}
,"identifier":{"enhancement":1,"type":1}
,"enhancement":{"existing":1}
,"existing":{"cli":1}
,"route":{"tagging":1,"tag":1}
,"tagging":{"ospf":1}
,"bgp":{"communication":1,"process":1}
,"communication":{"via":1}
,"via":{"nsm":1}
,"nsm":{"per":1}
,"per":{"section":1}
,"section":{"4.1":1}
,"4.1":{"rfc":1}
,"rfc":{"4577":1}
,"4577":{"sets":1}
,"sets":{"bit":1}
,"bit":{"type-3":1,"lsas":1}
,"type-3":{"type-5":1}
,"type-5":{"lsas":1}
,"lsas":{"sent":1,"received":1}
,"sent":{"processes":1}
,"processes":{"down":1}
,"down":{"(dn)":1}
,"(dn)":{"bit":1}
,"received":{"(rfc":1}
,"(rfc":{"4576)":1}
,"4576)":{"route":1}
,"tag":{"avoid":1}
,"avoid":{"loops":1}
,"loops":{"external":1}
,"external":{"routes":1}
,"routes":{"(type-5":1,"present":1}
,"(type-5":{"lsa)":1}
,"lsa)":{"bgp":1}
,"process":{"send":1}
,"send":{"ospf":1}
,"type":{"ospf":1}
,"router-type":{"extended":1}
,"extended":{"community":1}
,"community":{"attributes":1}
,"attributes":{"store":1}
,"store":{"attribute":1}
,"attribute":{"along":1}
,"along":{"vrf":1}
,"vrf":{"routes":1}
}
;Search.control.loadWordPairs(pairs);
