var pairs =
{
"pal_kernel_virtual_ipv4_add":{"function":1,"(struct":1}
,"function":{"adds":1,"succeeds":1,"fails":1}
,"adds":{"virtual":1}
,"virtual":{"address":1}
,"address":{"given":1,"ifp":1,"vrid":1}
,"given":{"interface":1}
,"interface":{"api":1,"*ifp":1,"owner":1}
,"api":{"call":1}
,"call":{"result_t":1}
,"result_t":{"pal_kernel_virtual_ipv4_add":1}
,"(struct":{"lib_globals":1}
,"lib_globals":{"*lib_node":1}
,"*lib_node":{"struct":1}
,"struct":{"pal_in4_addr":1,"interface":1}
,"pal_in4_addr":{"*vip":1}
,"*vip":{"struct":1}
,"*ifp":{"bool_t":1}
,"bool_t":{"owner":1}
,"owner":{"u_int8_t":1,"owner":1,"status":1}
,"u_int8_t":{"vrid)":1}
,"vrid)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"lib_node":1,"none":1}
,"lib_node":{"global":1}
,"global":{"variables":1}
,"variables":{"vip":1}
,"vip":{"virtual":1}
,"ifp":{"pointer":1}
,"pointer":{"interface":1}
,"status":{"address":1}
,"vrid":{"vrrp":1}
,"vrrp":{"virutal":1}
,"virutal":{"router":1}
,"router":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"result_ok":1,"function":1}
,"result_ok":{"function":1}
,"succeeds":{"value":1}
}
;Search.control.loadWordPairs(pairs);
