var pairs =
{
"vrrp_api_enable_session":{"function":1,"(int":1}
,"function":{"enables":1,"vrrp_enable_sess":1}
,"enables":{"vrrp":1}
,"vrrp":{"session":1,"module":1}
,"session":{"sets":1,"virtual":1,"found":1,"active":1,"enabled":1}
,"sets":{"default":1}
,"default":{"values":1}
,"values":{"receives":1,"vrrp_api_set_err_no_such_session":1}
,"receives":{"application":1}
,"application":{"calls":1}
,"calls":{"enable":1}
,"enable":{"function":1}
,"vrrp_enable_sess":{"defined":1}
,"defined":{"vrrp":1}
,"module":{"syntax":1}
,"syntax":{"int":1}
,"int":{"vrrp_api_enable_session":1,"vrid":1}
,"(int":{"ipi_vrid":1}
,"ipi_vrid":{"u_int8_t":1,"virtual":1}
,"u_int8_t":{"af_type":1}
,"af_type":{"int":1,"address":1}
,"vrid":{"u_int32_t":1,"vrrp":1}
,"u_int32_t":{"ifindex)":1}
,"ifindex)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ipi_vrid":1,"none":1}
,"virtual":{"router":1,"address":1}
,"router":{"af_type":1,"-255)":1}
,"address":{"family":1,"interface":1,"vrrp_api_set_err_prio_mismatch":1}
,"family":{"af_inet":1}
,"af_inet":{"(ipv4)":1}
,"(ipv4)":{"af_inet6":1}
,"af_inet6":{"(ipv6)":1}
,"(ipv6)":{"vrid":1}
,"-255)":{"ifindex":1}
,"ifindex":{"interface":1}
,"interface":{"index":1,"address":1}
,"index":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"vrrp_api_set_err_no_such_session":{"session":1}
,"found":{"vrrp_api_set_err_enabled":1}
,"vrrp_api_set_err_enabled":{"session":1}
,"active":{"vrrp_api_set_err_config_unset":1}
,"vrrp_api_set_err_config_unset":{"virtual":1}
,"vrrp_api_set_err_prio_mismatch":{"priority":1}
,"priority":{"acceptable":1}
,"acceptable":{"vrrp_ok":1}
,"vrrp_ok":{"session":1}
}
;Search.control.loadWordPairs(pairs);
