var pairs =
{
"bridge-group":{"spanning-tree":1,"<1-32>":1}
,"spanning-tree":{"command":1,"configured":1,"disable":1,"(disable":1,"enabled":1,"enable":1}
,"command":{"used":1,"executed":1,"syntax":1,"mode":1}
,"used":{"enable":1}
,"enable":{"disable":1,"command":1,"enable":1,"spanning":1}
,"disable":{"spanning-tree":1,"enable":1,"disable":1,"spanning":1}
,"configured":{"bridge":1,"<1-32":1}
,"bridge":{"bridge":1,"already":1,"group":1}
,"already":{"configured":1}
,"<1-32":{"spanning-tree":1}
,"executed":{"error":1}
,"error":{"returned":1}
,"returned":{"default-bridge":1}
,"default-bridge":{"command":1}
,"syntax":{"bridge-group":1}
,"<1-32>":{"spanning-tree":1,"specify":1}
,"(disable":{"enable)":1}
,"enable)":{"parameters":1}
,"parameters":{"<1-32>":1}
,"specify":{"bridge":1}
,"group":{"disable":1}
,"spanning":{"tree":1}
,"tree":{"interface":1}
,"interface":{"enable":1,"default":1,"mode":1,"eth1":1}
,"default":{"spanning-tree":1,"command":1}
,"enabled":{"default":1}
,"mode":{"interface":1,"example":1}
,"example":{"(config)":1}
,"(config)":{"interface":1}
,"eth1":{"(config-if)":1}
,"(config-if)":{"bridge-group":1}
}
;Search.control.loadWordPairs(pairs);
