var pairs =
{
"nsm_cvlan_reg_tab_entry_delete":{"function":1,"(struct":1}
,"function":{"deletes":1,"succeeds":1}
,"deletes":{"cvlan":1}
,"cvlan":{"registration":1}
,"registration":{"table":1}
,"table":{"entry":1,"syntax":1,"cvlan":1}
,"entry":{"cvlan":1,"deleted":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"nsm_cvlan_reg_tab_entry_delete":1}
,"(struct":{"nsm_cvlan_reg_tab":1}
,"nsm_cvlan_reg_tab":{"*regtab":1}
,"*regtab":{"u_int16_t":1}
,"u_int16_t":{"cvid)":1}
,"cvid)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"regtab":1,"none":1}
,"regtab":{"registration":1}
,"deleted":{"cvid":1,"output":1}
,"cvid":{"cvlan":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"function":1}
,"succeeds":{"nsm_vlan_err_bridge_not_found":1}
,"nsm_vlan_err_bridge_not_found":{"specified":1}
,"specified":{"bridge":1}
,"bridge":{"found":1}
,"found":{"nsm_vlan_err_vlan_not_found":1}
,"nsm_vlan_err_vlan_not_found":{"nsm_pro_vlan_err_cvlan_map_err":1}
,"nsm_pro_vlan_err_cvlan_map_err":{"nsm_vlan_err_svlan_not_found":1}
,"nsm_vlan_err_svlan_not_found":{"nsm_l2_err_none":1}
,"nsm_l2_err_none":{"function":1}
}
;Search.control.loadWordPairs(pairs);
