var pairs =
{
"isis_get_next_sys_log_adj_changes":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"state":1}
,"state":{"log":1,"(up":1,"true":1}
,"log":{"generation":1}
,"generation":{"is-is":1}
,"is-is":{"adjacency":1,"protocol":1,"instance":1}
,"adjacency":{"changes":1}
,"changes":{"state":1}
,"(up":{"down)":1}
,"down)":{"next":1}
,"next":{"instance":1}
,"instance":{"is-is":1,"indexlen":1,"found":1}
,"protocol":{"syntax":1}
,"syntax":{"int":1}
,"int":{"isis_get_next_sys_log_adj_changes":1,"indexlen":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1,"instance":1}
,"u_int32_t":{"*instance":1,"*ret)":1}
,"*instance":{"int":1}
,"indexlen":{"u_int32_t":1,"length":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"ret":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"length":{"index":1}
,"index":{"output":1}
,"output":{"parameters":1}
,"ret":{"state":1}
,"true":{"false":1}
,"false":{"return":1}
,"return":{"values":1}
,"values":{"isis_api_get_success":1}
,"isis_api_get_success":{"next":1}
,"found":{"isis_api_get_error":1}
,"isis_api_get_error":{"next":1}
}
;Search.control.loadWordPairs(pairs);
