var pairs =
{
"unicast":{"command":1,"continuity":1,"rmpid":1}
,"command":{"enable":1,"syntax":1,"mode":1}
,"enable":{"disable":1,"enable":1,"continuity":1}
,"disable":{"unicast":1,"disable":1,"continuity":1}
,"continuity":{"checking":1,"check":1}
,"checking":{"(cc)":1,"state":1}
,"(cc)":{"host":1}
,"host":{"mep":1}
,"mep":{"remote":1,"command":1,"state":1,"configuration":1,"mpid":1}
,"remote":{"mep":1}
,"syntax":{"unicast":1}
,"rmpid":{"rmepid":1,"state":1}
,"rmepid":{"state":1,"remote":1}
,"state":{"(enable":1,"continuity":1,"disable":1,"multicast":1,"enable":1}
,"(enable":{"disable)":1}
,"disable)":{"parameters":1}
,"parameters":{"rmepid":1}
,"check":{"state":1}
,"multicast":{"enable":1,"command":1}
,"mode":{"interface":1,"example":1}
,"interface":{"ethernet":1,"cbp.1":1}
,"ethernet":{"cfm":1}
,"cfm":{"pbb-te":1}
,"pbb-te":{"mep":1}
,"configuration":{"mode":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"interface":1}
,"cbp.1":{"(config-if)":1}
,"(config-if)":{"ethernet":1}
,"mpid":{"domain-name":1}
,"domain-name":{"ipi":1}
,"ipi":{"te-sid":1}
,"te-sid":{"bridge":1}
,"bridge":{"backbone":1}
,"backbone":{"(config-if-cfm-pbb-te-mep)":1}
,"(config-if-cfm-pbb-te-mep)":{"unicast":1}
}
;Search.control.loadWordPairs(pairs);
