var pairs =
{
"show":{"ethernet":1}
,"ethernet":{"lmi":1}
,"lmi":{"statistics":1,"link":1}
,"statistics":{"command":1,"bridge":1,"interface":1,"(bridge":1}
,"command":{"display":1,"syntax":1,"modes":1}
,"display":{"elmi":1}
,"elmi":{"statistics":1,"enabled":1}
,"bridge":{"ports":1,"indicates":1,"e-lmi":1}
,"ports":{"elmi":1}
,"enabled":{"cli":1}
,"cli":{"executed":1}
,"executed":{"uni-c":1}
,"uni-c":{"uni-n":1}
,"uni-n":{"command":1}
,"syntax":{"show":1}
,"interface":{"ifname":1,"indicates":1,"parameter":1,"information":1,"eth1":1}
,"ifname":{"show":1,"displays":1}
,"(bridge":{"<1-32>":1}
,"<1-32>":{"parameters":1,"displays":1}
,"parameters":{"bridge":1}
,"indicates":{"bridge-group":1,"interface":1}
,"bridge-group":{"parameter":1,"used":1}
,"parameter":{"<1-32>":1,"ifname":1}
,"displays":{"actual":1}
,"actual":{"bridge-group":1,"interface":1}
,"used":{"bridging":1}
,"bridging":{"interface":1}
,"information":{"(for":1}
,"(for":{"example":1}
,"example":{"eth1":1}
,"eth1":{"eth2)":1,"ether":1,"e-lmi":1}
,"eth2)":{"command":1}
,"modes":{"executive":1}
,"executive":{"mode":1}
,"mode":{"privileged":1,"examples":1}
,"privileged":{"executive":1}
,"examples":{"show":1}
,"e-lmi":{"statistics":1}
,"ether":{"lmi":1}
,"link":{"status":1}
,"status":{"active":1,"uni":1,"timeouts":1,"response":1,"received":1}
,"active":{"uni":1}
,"uni":{"status":1,"switch-1":1}
,"switch-1":{"reliability":1}
,"reliability":{"errors":1}
,"errors":{"status":1,"invalid":1}
,"timeouts":{"invalid":1}
,"invalid":{"sequence":1,"status":1,"protocol":1,"evc":1,"message":1,"mandatory":1,"non-mandatory":1}
,"sequence":{"number":1,"duplicated":1}
,"number":{"invalid":1}
,"response":{"unsolicited":1}
,"unsolicited":{"status":1}
,"received":{"protocol":1}
,"protocol":{"errors":1,"version":1}
,"version":{"invalid":1}
,"evc":{"reference":1}
,"reference":{"invalid":1}
,"message":{"type":1,"show":1}
,"type":{"sequence":1}
,"duplicated":{"mandatory":1}
,"mandatory":{"missing":1,"invalid":1}
,"missing":{"invalid":1}
,"non-mandatory":{"unrecognized":1}
,"unrecognized":{"unexpected":1}
,"unexpected":{"short":1}
,"short":{"message":1}
}
;Search.control.loadWordPairs(pairs);
