var pairs =
{
"router":{"layer":1}
,"layer":{"(l3)":1}
,"(l3)":{"device":1}
,"device":{"makes":1}
,"makes":{"decisions":1}
,"decisions":{"paths":1}
,"paths":{"network":1}
,"network":{"traffic":1,"find":1}
,"traffic":{"flow":1}
,"flow":{"routers":1}
,"routers":{"dynamic":1}
,"dynamic":{"routing":1}
,"routing":{"protocols":1,"information":1}
,"protocols":{"learn":1}
,"learn":{"network":1}
,"find":{"best":1,"matching":1,"mac":1}
,"best":{"route":1}
,"route":{"forward":1}
,"forward":{"packets":1}
,"packets":{"toward":1}
,"toward":{"final":1}
,"final":{"destination":1}
,"destination":{"find":1,"address":1}
,"matching":{"destination":1}
,"address":{"routing":1,"packet":1,"resolution":1}
,"information":{"base":1}
,"base":{"(rib)":1}
,"(rib)":{"find":1}
,"mac":{"address":1}
,"packet":{"address":1,"send":1,"port":1}
,"resolution":{"protocol":1}
,"protocol":{"(arp)":1}
,"(arp)":{"cache":1}
,"cache":{"write":1}
,"write":{"new":1}
,"new":{"mac":1}
,"send":{"packet":1}
,"port":{"associated":1}
,"associated":{"mac":1}
}
;Search.control.loadWordPairs(pairs);
