var pairs =
{
"nsm_client":{"nsm":1}
,"nsm":{"client":1}
,"client":{"declare":1,"parser":1}
,"declare":{"instance":1}
,"instance":{"data":1}
,"data":{"structure":1}
,"structure":{"defined":1}
,"defined":{"lib\u002Fnsm_client.h":1}
,"lib\u002Fnsm_client.h":{"file":1}
,"file":{"member":1}
,"member":{"description":1}
,"description":{"daemon-specific":1}
,"daemon-specific":{"globals":1}
,"globals":{"service":1}
,"service":{"service":1,"bits":1}
,"bits":{"client_id":1}
,"client_id":{"nsm":1}
,"parser":{"parser":1,"functions":1}
,"functions":{"callback":1,"subcallback":1,"specific":1}
,"callback":{"callback":1,"functions":1,"t_connect":1,"nc_commsg_user_ref":1}
,"subcallback":{"sub":1}
,"sub":{"callback":1}
,"specific":{"need":1}
,"need":{"async":1}
,"async":{"asynchronous":1}
,"asynchronous":{"connection":1}
,"connection":{"disconnect_callback":1}
,"disconnect_callback":{"disconnect":1}
,"disconnect":{"callback":1}
,"t_connect":{"reconnect":1}
,"reconnect":{"thread":1,"interval":1}
,"thread":{"reconnect_interval":1}
,"reconnect_interval":{"reconnect":1}
,"interval":{"seconds":1}
,"seconds":{"debug":1}
,"debug":{"debug":1,"message":1}
,"message":{"flag":1}
,"flag":{"nc_commsg_recv_cb":1}
,"nc_commsg_recv_cb":{"commmsg":1}
,"commmsg":{"receive":1,"user":1}
,"receive":{"callback":1}
,"nc_commsg_user_ref":{"commmsg":1}
,"user":{"context":1}
}
;Search.control.loadWordPairs(pairs);
