var pairs =
{
"hal_bridge_flush_fdb_by_port":{"function":1,"(char":1}
,"function":{"flushes":1,"succeeds":1}
,"flushes":{"forwarding":1}
,"forwarding":{"database":1}
,"database":{"(fdb)":1}
,"(fdb)":{"entries":1}
,"entries":{"port":1}
,"port":{"syntax":1,"interface":1}
,"syntax":{"int":1}
,"int":{"hal_bridge_flush_fdb_by_port":1,"ifindex":1,"instance":1}
,"(char":{"*name":1}
,"*name":{"unsigned":1}
,"unsigned":{"int":1,"short":1}
,"ifindex":{"unsigned":1,"port":1}
,"instance":{"unsigned":1,"vid":1}
,"short":{"vid":1,"svid)":1}
,"vid":{"unsigned":1,"vlan":1}
,"svid)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"name":1,"none":1}
,"name":{"bridge":1,"ifindex":1}
,"bridge":{"name":1}
,"interface":{"index":1}
,"index":{"instance":1}
,"vlan":{"svid":1}
,"svid":{"s-vlan":1}
,"s-vlan":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"hal_err_l2_fdb_no_entry":1}
,"hal_err_l2_fdb_no_entry":{"hal_err_l2_fdb_entry":1}
,"hal_err_l2_fdb_entry":{"hal_success":1}
,"hal_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
