var pairs =
{
"rip":{"send":1,"packets":1,"interface":1,"version":1}
,"send":{"version":1,"rip":1}
,"version":{"command":1,"control":1,"version":1,"compatible":1,"packets":1,"rip":1,"specified":1,"1-compatible)":1,"parameters":1}
,"command":{"send":1,"applies":1,"parameter":1,"global":1,"syntax":1,"mode":1}
,"packets":{"interface":1,"specified":1,"instead":1,"version":1,"configure":1}
,"interface":{"using":1,"broadcast":1,"overrides":1,"specify":1,"1-compatible":1,"default":1,"mode":1,"eth1":1}
,"using":{"version":1}
,"control":{"addition":1,"rules":1}
,"addition":{"version":1}
,"compatible":{"version":1,"packets":1}
,"specified":{"parameter":1,"version":1}
,"parameter":{"1-compatible":1,"command":1}
,"1-compatible":{"version":1,"specify":1}
,"broadcast":{"packets":1}
,"instead":{"multicasting":1}
,"multicasting":{"command":1}
,"applies":{"specific":1}
,"specific":{"interface":1}
,"overrides":{"version":1}
,"global":{"rip":1}
,"rules":{"command":1}
,"syntax":{"rip":1}
,"1-compatible)":{"rip":1}
,"parameters":{"specify":1}
,"specify":{"sending":1}
,"sending":{"rip":1}
,"default":{"version":1}
,"mode":{"interface":1,"examples":1}
,"examples":{"following":1}
,"following":{"example":1}
,"example":{"interface":1}
,"eth1":{"configured":1,"(config-if)":1}
,"configured":{"send":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"(config-if)":{"rip":1}
}
;Search.control.loadWordPairs(pairs);
