var pairs =
{
"mpls-tp":{"tunnels":1,"tunnel":1,"rib":1}
,"tunnels":{"rib":1,"illustrated":1,"associated":1,"consist":1,"forward":1,"may":1,"forming":1,"bidirectional":1}
,"rib":{"map":1,"unidirectional":1}
,"map":{"section":1,"unidirectional":1}
,"section":{"describes":1}
,"describes":{"mpls-tp":1}
,"tunnel":{"mappings":1,"lsp":1,"end-points":1,"originates":1,"terminates":1,"associated":1,"co-routed":1}
,"mappings":{"mpls-tp":1}
,"unidirectional":{".each":1,"tunnels":1}
,".each":{"tunnel":1}
,"lsp":{"holds":1}
,"holds":{"either":1,"forward":1}
,"either":{"ftn":1,"forward":1}
,"ftn":{"ilm":1,"entry":1}
,"ilm":{"entry":1}
,"entry":{"tunnel":1,"reverse":1,"following":1}
,"end-points":{"two":1}
,"two":{"unidirectional":1,"tunnels":1}
,"illustrated":{"following":1}
,"following":{"figure":1}
,"figure":{"tunnel":1,"shows":1,"illustrates":1}
,"originates":{"node":1}
,"node":{"tunnel":1,"rib":1}
,"terminates":{"node":1}
,"associated":{"bidirectional":1,"binding":1}
,"bidirectional":{"associated":1,"tunnels":1,"tunnel":1,"co-routed":1}
,"consist":{"two":1}
,"forward":{"reverse":1,"component":1}
,"reverse":{"forward":1,"tunnels":1,"component":1,"paths":1}
,"may":{"traverse":1}
,"traverse":{"different":1}
,"different":{"sets":1}
,"sets":{"nodes":1}
,"nodes":{"links":1}
,"links":{"tunnel":1,"end-to-end":1}
,"component":{"depending":1,"reverse":1,"endpoints":1,"ftn":1,"ilm":1}
,"depending":{"semantics":1}
,"semantics":{"tunnel":1}
,"binding":{"following":1}
,"shows":{"high":1}
,"high":{"level":1}
,"level":{"design":1}
,"design":{"tunnels":1}
,"forming":{"associated":1}
,"co-routed":{"bidirectional":1,"tunnels":1}
,"paths":{"sharing":1}
,"sharing":{"fate":1}
,"fate":{"nodes":1}
,"end-to-end":{"tunnel":1}
,"endpoints":{"forward":1}
,"illustrates":{"co-routed":1}
}
;Search.control.loadWordPairs(pairs);
