var pairs =
{
"mpls-tp":{"label":1}
,"label":{"switched":1,"map":1,"ilm":1,"process":1}
,"switched":{"path":1}
,"path":{"tunnel":1,"(lsp)":1,"reverse":1,"forward":1,"unidirectional":1}
,"tunnel":{"contain":1,"modes":1,"mode":1}
,"contain":{"primary":1,"following":1}
,"primary":{"label":1,"lsp":1}
,"(lsp)":{".there":1}
,".there":{"primary":1}
,"lsp":{"(backup":1,"ingress":1,"egress":1}
,"(backup":{"lsps":1}
,"lsps":{"supported.)":1,"contain":1,"ilm":1,"egress":1,"ingress":1,"transit\u002Fcore":1,"two":1}
,"supported.)":{"lsps":1}
,"following":{"information":1}
,"information":{"nhlfe":1}
,"nhlfe":{"entry":1,"n.a":1,"ilm":1,"associated":1,"case":1}
,"entry":{"nhlfe":1,"represents":1,"reverse":1,"ilm":1,"specifies":1}
,"represents":{"forward-component":1,"incoming":1}
,"forward-component":{"lsp":1}
,"ingress":{"reverse":1,"ilm":1,"transit":1}
,"reverse":{"component":1,"ilm":1,"components":1,"path":1}
,"component":{"lsp":1,"lsps":1}
,"egress":{"(for":1,"nodes":1,"reverse":1,"forward":1}
,"(for":{"bidirectional":1}
,"bidirectional":{"lsps)":1,"lsps":1}
,"lsps)":{"represented":1}
,"represented":{"three":1}
,"three":{"tuple":1}
,"tuple":{"parameters":1}
,"parameters":{"{out-interface":1,"taken":1}
,"{out-interface":{"out-label":1}
,"out-label":{"next":1}
,"next":{"hop":1}
,"hop":{"mac}":1,"mac":1}
,"mac}":{"parameters":1}
,"taken":{"user":1}
,"user":{"configuration.since":1}
,"configuration.since":{"next":1}
,"mac":{"optional":1,"address":1}
,"optional":{"parameter":1}
,"parameter":{"supplied":1}
,"supplied":{"configuration":1}
,"configuration":{"broadcast":1}
,"broadcast":{"mac":1}
,"address":{"(ff:ff:ff:ff:ff:ff)":1}
,"(ff:ff:ff:ff:ff:ff)":{"assumed":1}
,"assumed":{"ilm":1}
,"ilm":{"entry":1,"represents":1,"logical":1,"entries":1,"n.a":1,"ilm":1,"nhlfe":1}
,"incoming":{"label":1,"interface":1}
,"map":{"ilm":1}
,"logical":{"table":1}
,"table":{"indexed":1,"lists":1}
,"indexed":{"incoming":1}
,"interface":{"label":1}
,"specifies":{"behavior":1}
,"behavior":{"processing":1,"swap":1,"pop":1}
,"processing":{"labeled":1}
,"labeled":{"packets":1}
,"packets":{"arrive":1}
,"arrive":{"mpls":1}
,"mpls":{"core":1}
,"core":{"egress":1,"nodes":1}
,"nodes":{"core":1,"behavior":1,"table":1}
,"swap":{"labels":1}
,"labels":{"egress":1}
,"pop":{"label":1}
,"process":{"native":1}
,"native":{"packet":1}
,"packet":{"bidirectional":1}
,"entries":{"perform":1,"performing":1}
,"perform":{"label-pop":1}
,"label-pop":{"implement":1}
,"implement":{"forward":1}
,"forward":{"component":1,"reverse":1,"path":1}
,"components":{"lsps":1}
,"performing":{"label-swap":1}
,"label-swap":{"implement":1}
,"transit\u002Fcore":{"nodes":1}
,"lists":{"tunnel":1}
,"modes":{"tunnel":1}
,"mode":{"ingress":1}
,"transit":{"egress":1}
,"unidirectional":{"nhlfe":1}
,"n.a":{"ilm":1,"co-routed":1}
,"co-routed":{"nhlfe":1}
,"associated":{"nhlfe":1,"tunnels":1}
,"case":{"associated":1}
,"tunnels":{"fwd":1}
,"fwd":{"rev":1}
,"rev":{"paths":1}
,"paths":{"lsps":1}
,"two":{"different":1}
,"different":{"tunnels":1}
}
;Search.control.loadWordPairs(pairs);
