var pairs =
{
"ldp_snmp_api_get_peer_trans_addr":{"call":1,"(struct":1}
,"call":{"gets":1}
,"gets":{"peer":1}
,"peer":{"transport":1,"output":1,"return":1}
,"transport":{"address":1}
,"address":{"syntax":1,"peer":1}
,"syntax":{"int":1}
,"int":{"ldp_snmp_api_get_peer_trans_addr":1}
,"(struct":{"ldp":1}
,"ldp":{"*ldp":1,"ldp":1,"instance":1,"entity":1,"peer":1}
,"*ldp":{"struct":1}
,"struct":{"ldp_entity":1,"ldp_id":1,"pal_in4_addr":1}
,"ldp_entity":{"*entity":1}
,"*entity":{"struct":1}
,"ldp_id":{"*peer_id":1}
,"*peer_id":{"struct":1}
,"pal_in4_addr":{"*addr)":1}
,"*addr)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ldp":1,"addr":1}
,"instance":{"entity":1}
,"entity":{"ldp":1,"peer_id":1}
,"peer_id":{"ldp":1}
,"output":{"parameters":1}
,"addr":{"transport":1}
,"return":{"values":1}
,"values":{"ldp_success":1}
,"ldp_success":{"ldp_false":1}
}
;Search.control.loadWordPairs(pairs);
