var pairs =
{
"show":{"control-adjacency":1}
,"control-adjacency":{"command":1,"(caname":1,"ca2":1}
,"command":{"used":1,"syntax":1,"mode":1,"show":1}
,"used":{"display":1}
,"display":{"properties":1}
,"properties":{"particular":1}
,"particular":{"control":1}
,"control":{"adjacency":1,"channels":1,"channel":1}
,"adjacency":{"command":1}
,"syntax":{"show":1}
,"(caname":{"parameter":1}
,"parameter":{"caname":1}
,"caname":{"name":1}
,"name":{"control":1}
,"mode":{"exec":1,"example":1}
,"exec":{"mode":1}
,"example":{"following":1,"sample":1}
,"following":{"example":1}
,"sample":{"output":1}
,"output":{"command":1}
,"ca2":{"control-channel":1}
,"control-channel":{"rtr2":1}
,"rtr2":{"description":1}
,"description":{"test":1}
,"test":{"control":1}
,"channels":{"cc1":1}
,"cc1":{"cc2":1,"links":1}
,"cc2":{"primary":1}
,"primary":{"control":1}
,"channel":{"cc1":1}
,"links":{"te1":1}
,"te1":{"te2":1}
,"te2":{"peer-address":1}
,"peer-address":{"3.3.3.3":1}
,"3.3.3.3":{"index":1}
,"index":{"<up":1}
,"<up":{"running>":1}
,"running>":{"lmp":1}
}
;Search.control.loadWordPairs(pairs);
