var pairs =
{
"graceful":{"restart":1,"reset":1}
,"restart":{"graceful":1,"capability":1,"bgp":1,"allows":1,"available":1}
,"reset":{"without":1,"addition":1,"capability":1}
,"without":{"graceful":1}
,"capability":{"during":1,"extends":1,"bgp":1,"provides":1}
,"during":{"bgp":1}
,"bgp":{"restart":1,"peers":1,"route":1,"routing":1,"minimize":1,"router":1,"restarts":1,"mpls":1,"used":1,"distributed":1,"went":1,"down":1}
,"peers":{"detected":1}
,"detected":{"session":1}
,"session":{"gone":1}
,"gone":{"down":1}
,"down":{"back":1,"label-switched":1,"control":1}
,"back":{"zebos-xp":1}
,"zebos-xp":{"invalidated":1,"provides":1}
,"invalidated":{"associated":1}
,"associated":{"portion":1,"label":1}
,"portion":{"forwarding":1}
,"forwarding":{"cache":1,"tables":1,"packets":1,"impacted":1,"states":1}
,"cache":{"bgp":1}
,"route":{"re-computation":1,"withdrawal":1}
,"re-computation":{"generated":1,"generating":1}
,"generated":{"bgp":1}
,"routing":{"updates":1,"caused":1,"information":1,"rebuilding":1,"forwarding":1,"flap":1}
,"updates":{"forwarding":1,"unnecessary":1}
,"tables":{"became":1,"router":1,"bgp":1}
,"became":{"corrupted":1}
,"corrupted":{"unstable":1}
,"unstable":{"zebos-xp":1}
,"provides":{"bgp":1,"save":1}
,"minimize":{"negative":1}
,"negative":{"effects":1}
,"effects":{"routing":1}
,"caused":{"bgp":1,"routing":1}
,"allows":{"restarting":1}
,"restarting":{"bgp":1,"lsr":1}
,"router":{"temporarily":1,"continues":1}
,"temporarily":{"retain":1}
,"retain":{"routing":1}
,"information":{"continue":1}
,"continue":{"forwarding":1}
,"packets":{"bgp":1}
,"restarts":{"even":1}
,"even":{"routing":1}
,"rebuilding":{"routing":1}
,"continues":{"operate":1}
,"operate":{"across":1}
,"across":{"tcp":1,"restart":1}
,"tcp":{"connection":1}
,"connection":{"graceful":1}
,"extends":{"case":1}
,"case":{"configuration":1}
,"configuration":{"change":1}
,"change":{"forces":1}
,"forces":{"peer":1}
,"peer":{"reset":1}
,"addition":{"graceful":1}
,"available":{"bgp":1}
,"mpls":{"bgp":1,"forwarding":1}
,"used":{"distribute":1}
,"distribute":{"mpls-vpn":1}
,"mpls-vpn":{"labels":1}
,"labels":{"without":1,"bgp":1}
,"distributed":{"mpls-vpn":1}
,"withdrawal":{"accompanied":1,"caused":1}
,"accompanied":{"associated":1}
,"label":{"withdrawal":1,"bindings":1}
,"flap":{"bgp":1}
,"generating":{"bgp":1}
,"unnecessary":{"disruption":1}
,"disruption":{"forwarding":1}
,"went":{"down":1}
,"label-switched":{"routers":1}
,"routers":{"(lsrs)":1}
,"(lsrs)":{"cleared":1}
,"cleared":{"fec":1}
,"fec":{"label":1}
,"bindings":{"(for":1}
,"(for":{"vpn":1}
,"vpn":{"routes)":1}
,"routes)":{"learned":1}
,"learned":{"restarting":1}
,"lsr":{"result":1}
,"result":{"mpls":1}
,"impacted":{"across":1}
,"save":{"mpls":1}
,"states":{"nsm":1}
,"nsm":{"synchronizes":1}
,"synchronizes":{"vrf":1}
,"vrf":{"table":1}
,"table":{"bgp":1}
,"control":{"plane":1}
,"plane":{"feature":1}
,"feature":{"supported":1}
,"supported":{"vpnv4":1}
,"vpnv4":{"address":1}
,"address":{"family":1}
}
;Search.control.loadWordPairs(pairs);
