var pairs =
{
"nsm_mpls_if_status_msg_data_t":{"data":1,"{u_int16_t":1}
,"data":{"structure":1}
,"structure":{"defined":1}
,"defined":{"nsm\u002Fmpls\u002Fha\u002Fnsm_mpls_cal.h":1}
,"nsm\u002Fmpls\u002Fha\u002Fnsm_mpls_cal.h":{"file":1}
,"file":{"member":1}
,"member":{"description":1}
,"description":{"label_space":1}
,"label_space":{"label":1,"nsm_mpls_if_status_msg_data_t":1}
,"label":{"space":1}
,"space":{"definition":1}
,"definition":{"typedef":1}
,"typedef":{"struct":1}
,"struct":{"nsm_mpls_if_status_msg_data_t":1}
,"{u_int16_t":{"label_space":1}
}
;Search.control.loadWordPairs(pairs);
