var pairs =
{
"isis_get_next_circ_max_area_addr_mismatches":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"number":1}
,"number":{"times":1}
,"times":{"is-is":1}
,"is-is":{"control":1,"instance":1,"circuit":1}
,"control":{"pdu":1}
,"pdu":{"maximum":1,"max":1}
,"maximum":{"area":1}
,"area":{"address":1}
,"address":{"field":1}
,"field":{"different":1}
,"different":{"system":1}
,"system":{"received":1}
,"received":{"next":1,"return":1}
,"next":{"circuit":1}
,"circuit":{"level":1,"index":1,"type":1}
,"level":{"syntax":1}
,"syntax":{"int":1}
,"int":{"isis_get_next_circ_max_area_addr_mismatches":1,"indexlen":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1,"instance":1}
,"u_int32_t":{"*instance":1,"*circindex":1,"*ret)":1}
,"*instance":{"u_int32_t":1}
,"*circindex":{"u_int32_t*circtype":1}
,"u_int32_t*circtype":{"int":1}
,"indexlen":{"u_int32_t":1,"length":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"ret":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"instance":{"is-is":1,"circindex":1}
,"circindex":{"is-is":1}
,"index":{"circtype":1,"output":1,"isis_api_get_error":1}
,"circtype":{"is-is":1}
,"type":{"indexlen":1,"found":1}
,"length":{"index":1}
,"output":{"parameters":1}
,"ret":{"number":1}
,"max":{"area":1}
,"return":{"values":1}
,"values":{"isis_api_get_success":1}
,"isis_api_get_success":{"next":1}
,"found":{"specified":1}
,"specified":{"circuit":1}
,"isis_api_get_error":{"next":1}
}
;Search.control.loadWordPairs(pairs);
