var pairs =
{
"pim4_api_static_rp_unset":{"function":1,"(u_int32_t":1}
,"function":{"removes":1,"executes":1}
,"removes":{"configuration":1}
,"configuration":{"static":1}
,"static":{"rendezvous":1}
,"rendezvous":{"point":1}
,"point":{"syntax":1,"address":1}
,"syntax":{"int":1}
,"int":{"pim4_api_static_rp_unset":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"vrf_id_t":1,"virtual":1}
,"vrf_id_t":{"vrf_id":1}
,"vrf_id":{"struct":1,"vpn":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"*rp_addr)":1}
,"*rp_addr)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"rp_addr":1}
,"virtual":{"router":1}
,"router":{"vrf_id":1}
,"vpn":{"routing\u002Fforwarding":1}
,"routing\u002Fforwarding":{"instance":1}
,"instance":{"output":1}
,"output":{"parameters":1}
,"rp_addr":{"rendezvous":1}
,"address":{"return":1}
,"return":{"values":1}
,"values":{"pim_api_set_err_wrong_vr":1}
,"pim_api_set_err_wrong_vr":{"pim":1}
,"pim":{"master":1,"vrf":1}
,"master":{"found":1}
,"found":{"pim_api_set_err_wrong_vrf":1,"pim_api_set_success":1}
,"pim_api_set_err_wrong_vrf":{"pim":1}
,"vrf":{"interface":1}
,"interface":{"found":1}
,"pim_api_set_success":{"function":1}
,"executes":{"properly":1}
}
;Search.control.loadWordPairs(pairs);
