var pairs =
{
"pal_kernel_if_ipv4_address_secondary_add":{"function":1,"(struct":1}
,"function":{"sets":1}
,"sets":{"ipv4":1}
,"ipv4":{"secondary":1}
,"secondary":{"address":1}
,"address":{"mask":1,"interface":1,"output":1}
,"mask":{"broadcast":1}
,"broadcast":{"address":1}
,"interface":{"api":1,"*ifp":1,"ifc":1}
,"api":{"call":1}
,"call":{"result_t":1}
,"result_t":{"pal_kernel_if_ipv4_address_secondary_add":1}
,"(struct":{"interface":1}
,"*ifp":{"struct":1}
,"struct":{"connected":1}
,"connected":{"*ifc)":1,"address":1}
,"*ifc)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"none":1}
,"ifp":{"pointer":1}
,"pointer":{"interface":1,"connected":1}
,"ifc":{"pointer":1}
,"output":{"parameters":1}
,"none":{"result":1}
,"result":{"value":1}
,"value":{"platform":1}
,"platform":{"dependent":1}
}
;Search.control.loadWordPairs(pairs);
