var pairs =
{
"scalar":{"variables":1}
,"variables":{"bfd":1}
,"bfd":{"admin":1,"router":1,"process":1,"session":1,"sessions":1,"objects":1}
,"admin":{"status":1}
,"status":{"(bfdadminstatus)":1,"bfd":1}
,"(bfdadminstatus)":{"global":1}
,"global":{"administrative":1}
,"administrative":{"status":1}
,"router":{"value":1}
,"value":{"enabled":1}
,"enabled":{"(1)":1}
,"(1)":{"denotes":1,"enables":1}
,"denotes":{"bfd":1}
,"process":{"active":1}
,"active":{"least":1}
,"least":{"interface":1}
,"interface":{"disabled":1}
,"disabled":{"(2)":1}
,"(2)":{"disables":1}
,"disables":{"interfaces":1}
,"interfaces":{"bfd":1}
,"session":{"notification":1}
,"notification":{"enable":1}
,"enable":{"(bfdsessnotificationsenable)":1}
,"(bfdsessnotificationsenable)":{"object":1}
,"object":{"true":1}
,"true":{"(1)":1}
,"enables":{"emission":1}
,"emission":{"bfdsessup":1}
,"bfdsessup":{"bfdsessdown":1}
,"bfdsessdown":{"notifications":1}
,"notifications":{"otherwise":1,"emitted":1}
,"otherwise":{"notifications":1}
,"emitted":{"mib":1}
,"mib":{"ip-based":1}
,"ip-based":{"bfd":1}
,"sessions":{"bfd":1}
,"objects":{"available":1}
,"available":{"single-hop":1}
,"single-hop":{"multi-hop":1}
,"multi-hop":{"sessions":1}
}
;Search.control.loadWordPairs(pairs);
