var pairs =
{
"igp-te":{"algorithm":1,"(ospf":1}
,"algorithm":{"calculate":1}
,"calculate":{"cspf":1}
,"cspf":{"requires":1}
,"requires":{"router":1}
,"router":{"data":1}
,"data":{"network":1,"traffic":1,"link":1,"store":1}
,"network":{"data":1}
,"traffic":{"engineering":1}
,"engineering":{"data":1,"metric":1}
,"link":{"ospf":1,"type":1,"octets)":1}
,"ospf":{"type-1":1}
,"type-1":{"(router-lsa)":1}
,"(router-lsa)":{"type-2":1}
,"type-2":{"(network-lsa)":1}
,"(network-lsa)":{"type-10":1}
,"type-10":{"(opaque-lsa":1}
,"(opaque-lsa":{"information)":1}
,"information)":{"fill":1}
,"fill":{"roles":1}
,"roles":{"respectively":1}
,"respectively":{"igp-te":1}
,"(ospf":{"is-is)":1}
,"is-is)":{"routers":1}
,"routers":{"exchange":1}
,"exchange":{"following":1}
,"following":{"data":1}
,"store":{"ted":1}
,"ted":{"link":1}
,"type":{"octet)":1}
,"octet)":{"link":1}
,"octets)":{"local":1,"remote":1,"traffic":1,"maximum":1,"unreserved":1,"resource":1}
,"local":{"interface":1}
,"interface":{"address":1}
,"address":{"octets)":1}
,"remote":{"interface":1}
,"metric":{"octets)":1}
,"maximum":{"bandwidth":1,"reservable":1}
,"bandwidth":{"octets)":1,"(32":1}
,"reservable":{"bandwidth":1}
,"unreserved":{"bandwidth":1}
,"(32":{"octets)":1}
,"resource":{"class\u002Fcolor":1}
,"class\u002Fcolor":{"octets)":1}
}
;Search.control.loadWordPairs(pairs);
