var pairs =
{
"show":{"control-channel":1}
,"control-channel":{"command":1,"(ccname":1,"12345":1,"123":1}
,"command":{"display":1,"syntax":1,"mode":1,"===============================control-channel":1}
,"display":{"information":1}
,"information":{"control":1}
,"control":{"channel":1}
,"channel":{"command":1,"specific":1}
,"syntax":{"show":1}
,"(ccname":{"parameter":1}
,"parameter":{"ccname":1}
,"ccname":{"specify":1}
,"specify":{"name":1}
,"name":{"control":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"following":1}
,"following":{"sample":1}
,"sample":{"output":1}
,"output":{"command":1}
,"===============================control-channel":{"newer":1,"new":1}
,"newer":{"gifindex":1}
,"gifindex":{"local-address":1}
,"local-address":{"1.2.3.4":1}
,"1.2.3.4":{"peer-address":1,"control-channel":1}
,"peer-address":{"1.2.3.5":1,"1.2.3.4":1}
,"1.2.3.5":{"control-channel":1}
,"12345":{"interface":1}
,"interface":{"binding":1}
,"binding":{"n\u002Fa":1}
,"n\u002Fa":{"belong":1,"status":1}
,"belong":{"control-adjacency":1}
,"control-adjacency":{"n\u002Fa":1}
,"status":{"down":1}
,"down":{"admin":1,"nsm":1,"last":1,"time":1}
,"admin":{"operational":1}
,"operational":{"down":1}
,"nsm":{"down":1}
,"last":{"time":1,"down":1}
,"time":{"00:00:00":1,"20:17:55":1,"18:49:31":1,"18:49:27":1}
,"00:00:00":{"last":1}
,"20:17:55":{"===============================control-channel":1}
,"new":{"description":1}
,"description":{"control":1,"gifindex":1}
,"specific":{"description":1}
,"123":{"interface":1}
,"18:49:31":{"last":1}
,"18:49:27":{"===============================#":1}
}
;Search.control.loadWordPairs(pairs);
