var pairs =
{
"overview":{"evc":1}
,"evc":{"recognized":1}
,"recognized":{"s-vlan":1}
,"s-vlan":{"packets":1,"tag":1,"bridge":1,"component":1}
,"packets":{"provider":1}
,"provider":{"network":1,"edge":1,"bridge":1}
,"network":{"doubly":1,"enhanced":1,"participate":1}
,"doubly":{"tagged":1}
,"tagged":{"inner":1}
,"inner":{"tag":1}
,"tag":{"called":1,"(customer":1,"(service":1}
,"called":{"c-vlan":1,"s-vlan":1}
,"c-vlan":{"tag":1,"component":1,"components":1}
,"(customer":{"vlan":1}
,"vlan":{"id)":1,"tags":1,"bridge":1}
,"id)":{"outer":1}
,"outer":{"tag":1}
,"(service":{"vlan)":1}
,"vlan)":{"provider":1}
,"enhanced":{"internal":1}
,"internal":{"sub":1,"eiss":1}
,"sub":{"layer":1}
,"layer":{"services":1}
,"services":{"(eiss)":1}
,"(eiss)":{"recognizes":1}
,"recognizes":{"service":1}
,"service":{"customer":1}
,"customer":{"vlan":1,"spanning":1,"device":1}
,"tags":{"rapid":1}
,"rapid":{"spanning":1}
,"spanning":{"tree":1}
,"tree":{"protocol":1,"calculations":1}
,"protocol":{"(rstp)":1}
,"(rstp)":{"edge":1}
,"edge":{"bridges":1,"bridge":1}
,"bridges":{"provider":1}
,"participate":{"customer":1}
,"calculations":{"avoid":1}
,"avoid":{"loops":1}
,"loops":{"due":1}
,"due":{"customer":1}
,"device":{"misconfigurations":1}
,"misconfigurations":{"ieee":1}
,"ieee":{"802.1ad":1}
,"802.1ad":{"standard":1}
,"standard":{"enhances":1}
,"enhances":{"bridging":1}
,"bridging":{"functionality":1}
,"functionality":{"defined":1}
,"defined":{"802.1q":1}
,"802.1q":{"providing":1}
,"providing":{"separate":1}
,"separate":{"instances":1}
,"instances":{"802":1}
,"802":{"mac":1}
,"mac":{"mac":1,"internal":1}
,"eiss":{"multiple":1}
,"multiple":{"customers":1}
,"customers":{"independently":1,"cooperation":1}
,"independently":{"without":1}
,"without":{"requiring":1,"c-vlan":1}
,"requiring":{"customers":1}
,"cooperation":{"achieve":1}
,"achieve":{"objective":1}
,"objective":{"concepts":1}
,"concepts":{"introduced":1}
,"introduced":{"vlan":1}
,"bridge":{"consisting":1,"(peb)":1,"denotes":1,"peb":1}
,"consisting":{"single":1}
,"single":{"c-vlan":1,"s-vlan":1}
,"component":{"s-vlan":1,"without":1,"provider":1,"c-vlan":1}
,"(peb)":{"single":1}
,"components":{"provider":1}
,"denotes":{"s-vlan":1}
}
;Search.control.loadWordPairs(pairs);
