var pairs =
{
"smi_vlan_port_alarm":{"structure":1,"{char":1}
,"structure":{"provides":1}
,"provides":{"information":1}
,"information":{"alarm":1}
,"alarm":{"vlan":1,"definition":1}
,"vlan":{"added":1,"ids":1}
,"added":{"type":1}
,"type":{"definition":1}
,"definition":{"ifname":1,"struct":1}
,"ifname":{"interface":1,"[interface_namsiz":1}
,"interface":{"name":1}
,"name":{"vlan_bmp":1}
,"vlan_bmp":{"vlan":1,"struct":1}
,"ids":{"add":1}
,"add":{"egr_bmp":1,"bulk_alarm":1}
,"egr_bmp":{"egress":1,"struct":1}
,"egress":{"vlan":1}
,"bulk_alarm":{"bulk":1}
,"bulk":{"alarm":1}
,"struct":{"smi_vlan_port_alarm":1,"smi_vlan_bmp":1,"smi_vlan_port_list_bulk_alarm":1}
,"{char":{"ifname":1}
,"[interface_namsiz":{"struct":1}
,"smi_vlan_bmp":{"vlan_bmp":1,"egr_bmp":1}
,"smi_vlan_port_list_bulk_alarm":{"bulk_alarm":1}
}
;Search.control.loadWordPairs(pairs);
