var pairs =
{
"topology":{"diagram":1}
,"diagram":{"depicts":1}
,"depicts":{"two":1}
,"two":{"multi-homed":1,"devices":1}
,"multi-homed":{"devices":1}
,"devices":{"ce1":1,"pe1":1,"ethernet":1}
,"ce1":{"ce2":1}
,"ce2":{"connected":1}
,"connected":{"two":1}
,"pe1":{"pe3":1,"pe2":1,"pe4":1}
,"pe3":{"pe2":1,"pw4":1,"pe4":1}
,"pe2":{"pe4":1,"pw2":1,"pe3":1}
,"pe4":{"respectively":1,"pw3":1,"dual-homed":1}
,"respectively":{"scenario":1}
,"scenario":{"multiple":1}
,"multiple":{"single-segment":1}
,"single-segment":{"ethernet":1}
,"ethernet":{"pseudowires":1}
,"pseudowires":{"need":1}
,"need":{"signaled":1}
,"signaled":{"pw1":1}
,"pw1":{"pe1":1}
,"pw2":{"pe1":1}
,"pw3":{"pe2":1}
,"pw4":{"pe3":1}
,"dual-homed":{"devices":1}
}
;Search.control.loadWordPairs(pairs);
