var pairs =
{
"drni_api_update_gateway_conv":{"function":1,"(u_int16_t":1}
,"function":{"manually":1,"called":1,"succeeds":1}
,"manually":{"allocates":1}
,"allocates":{"removes":1}
,"removes":{"range":1}
,"range":{"gateway":1,"<1-65535>":1,"<1-4096>":1,"<1-3>":1,"<1-4>":1}
,"gateway":{"conversation":1}
,"conversation":{"identifiers":1,"identifier":1}
,"identifiers":{"range":1,"distributed":1}
,"distributed":{"configured":1}
,"configured":{"portal":1}
,"portal":{"system":1,"priority":1,"drni_id":1,"automatic":1}
,"system":{"function":1,"number":1}
,"called":{"command":1}
,"command":{"gateway-conv-id":1}
,"gateway-conv-id":{"<1-4096>":1}
,"<1-4096>":{"(<1-4096>":1,"drni_err_invalid_portal_sys_num":1}
,"(<1-4096>":{"[portal-system":1}
,"[portal-system":{"<1-3>":1}
,"<1-3>":{"priority":1,"drni_err_invalid_portal_priority":1,"drni_err_invalid_priority":1}
,"priority":{"<1-3>]":1,"range":1,"drni_err_calloc_failed":1}
,"<1-3>]":{"syntax":1}
,"syntax":{"include":1}
,"include":{"mlagd\u002Fdrni\u002Fdrni_api.h":1}
,"mlagd\u002Fdrni\u002Fdrni_api.h":{"s_int32_t":1}
,"s_int32_t":{"drni_api_update_gateway_conv":1}
,"(u_int16_t":{"drni_id":1}
,"drni_id":{"int":1,"mc-lag":1,"range":1,"cannot":1}
,"int":{"count":1}
,"count":{"char":1,"number":1}
,"char":{"**config":1}
,"**config":{"u_int8_t":1}
,"u_int8_t":{"flag)":1}
,"flag)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"drni_id":1,"config":1,"flag":1,"none":1}
,"mc-lag":{"identifier":1}
,"identifier":{"count":1,"allocation":1,"invalid":1,"greater":1,"range":1,"configured":1}
,"number":{"command-line":1,"range":1,"priority":1}
,"command-line":{"parameters":1}
,"config":{"config":1,"command-line":1,"null":1}
,"flag":{"whether":1}
,"whether":{"adding":1}
,"adding":{"removing":1}
,"removing":{"gateway":1}
,"allocation":{"constants":1,"mlag_api_del_conv_config":1,"output":1,"drni_err_config_overlaps":1,"fails":1}
,"constants":{"defined":1}
,"defined":{"mlagd\u002Fmlag_api.h":1}
,"mlagd\u002Fmlag_api.h":{"mlag_api_add_conv_config":1}
,"mlag_api_add_conv_config":{"add":1}
,"add":{"gateway":1}
,"mlag_api_del_conv_config":{"remove":1}
,"remove":{"gateway":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"drni_success":1}
,"drni_success":{"function":1}
,"succeeds":{"drni_err_master_null":1}
,"drni_err_master_null":{"drni":1}
,"drni":{"master":1}
,"master":{"null":1}
,"null":{"drni_failure":1,"drni_err_invalid_drni_id":1}
,"drni_failure":{"config":1}
,"drni_err_invalid_drni_id":{"drni_id":1}
,"<1-65535>":{"drni_err_invalid_conv_id":1}
,"drni_err_invalid_conv_id":{"starting":1}
,"starting":{"ending":1}
,"ending":{"conversation":1}
,"invalid":{"drni_err_cvid_unsupported_conv_id":1}
,"drni_err_cvid_unsupported_conv_id":{"starting":1}
,"greater":{"4094":1}
,"4094":{"drni_err_invalid_conv_id":1}
,"drni_err_invalid_portal_sys_num":{"portal":1}
,"drni_err_invalid_portal_priority":{"portal":1}
,"drni_err_invalid_priority":{"priority":1}
,"<1-4>":{"drni_err_portal_null":1}
,"drni_err_portal_null":{"portal":1}
,"cannot":{"found":1}
,"found":{"drni_err_auto_alloc_set":1}
,"drni_err_auto_alloc_set":{"portal":1}
,"automatic":{"conversation":1}
,"drni_err_config_overlaps":{"given":1}
,"given":{"conversation":1}
,"drni_err_calloc_failed":{"memory":1}
,"memory":{"allocation":1}
}
;Search.control.loadWordPairs(pairs);
