var pairs =
{
"rtr2":{"ldp-igp":1}
,"ldp-igp":{"sync":1,"synchronization":1,"sync-delay":1}
,"sync":{"configuration":1,"isis":1,"applicable":1,"command":1,"is-is":1}
,"configuration":{"nsm":1,"default":1}
,"nsm":{"is-is":1}
,"is-is":{"ldp":1,"process":1,"level.120secs":1,"instance":1,"command":1,"<level-type>":1}
,"ldp":{"enabled":1,"converges":1,"converge":1,"convergence":1,"command":1,"process":1}
,"enabled":{"ldp-igp":1}
,"synchronization":{"configured":1,"interface":1}
,"configured":{"(config)":1,"igp":1,"delay":1}
,"(config)":{"interface":1}
,"interface":{"eth1":1,"mode":1,"acting":1}
,"eth1":{"enter":1,"belonging":1}
,"enter":{"interface":1}
,"mode":{"(config-if)":1}
,"(config-if)":{"mpls":1,"exit":1}
,"mpls":{"ldp-igp":1}
,"isis":{"level-1":1}
,"level-1":{"holddown-timer":1,"level-2-only":1}
,"holddown-timer":{"120":1,"value":1,"range":1,"(config-if)":1}
,"120":{"configure":1}
,"configure":{"ldp-igp":1,"without":1}
,"belonging":{"is-is":1}
,"process":{"corresponding":1,"default":1}
,"corresponding":{"is-is":1}
,"level.120secs":{"holddown-timer":1}
,"value":{"igp":1}
,"igp":{"wait":1,"sync":1,"waits":1,"applicable":1}
,"wait":{"until":1}
,"until":{"ldp":1}
,"converges":{"parameters":1}
,"parameters":{"level-1":1}
,"level-2-only":{"level-1-2":1}
,"level-1-2":{"identify":1}
,"identify":{"is-is":1}
,"instance":{"level":1}
,"level":{"interface":1,"sync":1,"given":1}
,"acting":{"level":1}
,"applicable":{"matches":1,"notification":1}
,"matches":{"level":1}
,"given":{"igp":1}
,"command":{"is-is":1,"part":1,"mpls":1,"optional":1}
,"part":{"is-is":1,"ldp":1}
,"default":{"mandatory":1,"option":1,"configured":1}
,"mandatory":{"configuration":1}
,"option":{"note":1}
,"note":{"holddown-timer":1}
,"range":{"2147483":1,"seconds":1}
,"2147483":{"seconds":1}
,"seconds":{"holddown":1,"notification":1,"command":1,"(config-if)":1}
,"holddown":{"timer":1}
,"timer":{"configured":1}
,"waits":{"indefinitely":1}
,"indefinitely":{"ldp":1}
,"converge":{"command":1}
,"<level-type>":{"configure":1}
,"without":{"holddown-timer":1}
,"sync-delay":{"time":1}
,"time":{"delay":1}
,"delay":{"seconds":1}
,"notification":{"ldp":1,"non-convergence":1}
,"convergence":{"igp":1}
,"non-convergence":{"range":1}
,"optional":{"ldp":1}
,"exit":{"exit":1,"interface":1}
}
;Search.control.loadWordPairs(pairs);
