var pairs =
{
"dynamic":{"vlan":1}
,"vlan":{"assignment":1,"vlan":1,"available":1,"added":1,"dut":1,"bridge":1,"creation":1,"attribute":1}
,"assignment":{"support":1,"radius":1}
,"support":{"dynamic":1}
,"radius":{"server":1,"server-configuration":1}
,"server":{"sends":1}
,"sends":{"back":1}
,"back":{"access-accept":1}
,"access-accept":{"messages":1}
,"messages":{"mac":1}
,"mac":{"authentication":1,"undergoing":1,"added":1}
,"authentication":{"successful":1,"added":1,"mac":1}
,"successful":{"message":1,"mac":1,"authentication":1}
,"message":{"carries":1}
,"carries":{"vlan":1}
,"available":{"dut":1}
,"dut":{"port":1,"configure":1,"(config)":1,"(config-if)":1}
,"port":{"removed":1}
,"removed":{"default":1}
,"default":{"vlan":1}
,"added":{"specified":1,"vlan":1,"forwarding":1}
,"specified":{"vlan":1}
,"configure":{"terminal":1,"mode":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"interface":1}
,"mode":{"dut":1}
,"(config)":{"vlan":1,"interface":1}
,"bridge":{"state":1,"specifying":1,"dut":1}
,"state":{"enable":1,"vlan":1,"allows":1}
,"enable":{"enable":1,"state":1,"dynamic":1}
,"specifying":{"enable":1}
,"allows":{"forwarding":1}
,"forwarding":{"frames":1,"database":1}
,"frames":{"vlan":1}
,"interface":{"eth2":1,"mode":1}
,"eth2":{"enter":1}
,"(config-if)":{"auth-mac":1}
,"auth-mac":{"dynamic-vlan-creation":1}
,"dynamic-vlan-creation":{"enable":1,"disable":1}
,"creation":{"dynamic":1,"enabled":1,"disabled":1}
,"enabled":{"authentication":1}
,"undergoing":{"authentication":1}
,"attribute":{"radius":1}
,"server-configuration":{"file":1}
,"file":{"dut":1}
,"disable":{"disable":1,"dynamic":1}
,"disabled":{"successful":1}
,"database":{"default":1}
}
;Search.control.loadWordPairs(pairs);
