var pairs =
{
"vlan":{"prioritization":1}
,"prioritization":{"(802.1p\u002Fq)":1}
,"(802.1p\u002Fq)":{"zebos-xp":1}
,"zebos-xp":{"includes":1}
,"includes":{"priority":1}
,"priority":{"signaling":1,"value":1}
,"signaling":{"traffic":1}
,"traffic":{"data-link":1,"although":1}
,"data-link":{"layer":1}
,"layer":{"ieee":1}
,"ieee":{"802.1q":1,"instead":1}
,"802.1q":{"specifies":1,"standard":1}
,"specifies":{"priority":1,"tag":1}
,"value":{"inclusive":1}
,"inclusive":{"used":1}
,"used":{"qos":1}
,"qos":{"(quality":1}
,"(quality":{"service)":1}
,"service)":{"disciplines":1}
,"disciplines":{"differentiate":1}
,"differentiate":{"traffic":1}
,"although":{"technique":1}
,"technique":{"often":1,"incorporated":1}
,"often":{"called":1}
,"called":{"802.1p":1}
,"802.1p":{"standard":1}
,"standard":{"name":1,"specifies":1}
,"name":{"published":1}
,"published":{"ieee":1}
,"instead":{"technique":1}
,"incorporated":{"802.1q":1}
,"tag":{"inserted":1}
,"inserted":{"ethernet":1}
,"ethernet":{"frame":1}
}
;Search.control.loadWordPairs(pairs);
