var pairs =
{
"cvlan":{"registration":1}
,"registration":{"table":1}
,"table":{"command":1,"mapping":1,"word":1,"bridge":1,"customer1":1}
,"command":{"create":1,"delete":1,"syntax":1,"supported":1,"mode":1}
,"create":{"customer":1}
,"customer":{"vlan":1}
,"vlan":{"(cvlan)":1}
,"(cvlan)":{"registration":1}
,"mapping":{"cvlans":1}
,"cvlans":{"service":1}
,"service":{"provider":1}
,"provider":{"vlans":1}
,"vlans":{"(svlans)":1}
,"(svlans)":{"parameter":1}
,"parameter":{"command":1}
,"delete":{"cvlan":1}
,"syntax":{"cvlan":1}
,"word":{"cvlan":1,"bridge":1,"above":1,"name":1}
,"bridge":{"<1-32>":1,"specify":1,"command":1}
,"<1-32>":{"cvlan":1,"parameters":1,"specify":1}
,"above":{"command":1}
,"supported":{"zebic":1}
,"zebic":{"releases":1}
,"releases":{"cvlan":1}
,"parameters":{"word":1}
,"name":{"cvlan":1}
,"specify":{"bridge":1}
,"mode":{"configure":1,"example":1}
,"configure":{"mode":1,"terminal":1}
,"example":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"cvlan":1}
,"customer1":{"(config-cvlan-registration)":1}
}
;Search.control.loadWordPairs(pairs);
