var pairs =
{
"log":{"syslog":1,"level":1,"command":1}
,"syslog":{"command":1,"enables":1,"file":1,"log":1,"parameters":1}
,"command":{"begin":1,"instructs":1,"syntax":1,"mode":1}
,"begin":{"logging":1}
,"logging":{"information":1,"analyzing":1,"system":1}
,"information":{"system":1}
,"system":{"log":1,"error":1}
,"level":{"debug":1}
,"debug":{"syslog":1,"sessions":1,"output":1}
,"enables":{"centrally":1}
,"centrally":{"logging":1}
,"analyzing":{"configuration":1}
,"configuration":{"events":1}
,"events":{"system":1}
,"error":{"messages":1}
,"messages":{"helps":1}
,"helps":{"monitor":1}
,"monitor":{"interface":1,"sessions":1}
,"interface":{"status":1}
,"status":{"security":1}
,"security":{"alerts":1}
,"alerts":{"cpu":1}
,"cpu":{"process":1}
,"process":{"overloads":1}
,"overloads":{"allows":1}
,"allows":{"real-time":1}
,"real-time":{"capturing":1}
,"capturing":{"client":1}
,"client":{"debug":1}
,"sessions":{"command":1,"syslog":1}
,"instructs":{"vlogd":1}
,"vlogd":{"daemon":1}
,"daemon":{"forward":1}
,"forward":{"pvr":1}
,"pvr":{"debug":1}
,"output":{"active":1}
,"active":{"terminal":1}
,"terminal":{"monitor":1,"(config)":1}
,"file":{"parameter":1}
,"parameter":{"disable":1}
,"disable":{"logging":1}
,"syntax":{"log":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"configure":1,"example":1}
,"configure":{"mode":1,"terminal":1}
,"example":{"configure":1}
,"(config)":{"log":1}
}
;Search.control.loadWordPairs(pairs);
