var pairs =
{
"isis_set_circ_level":{"call":1,"(u_int32_t":1}
,"call":{"sets":1}
,"sets":{"type":1}
,"type":{"packets":1}
,"packets":{"sent":1}
,"sent":{"accepted":1}
,"accepted":{"circuit":1}
,"circuit":{"syntax":1,"index":1,"level1":1,"level":1}
,"syntax":{"int":1}
,"int":{"isis_set_circ_level":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1,"instance":1}
,"u_int32_t":{"instance":1,"circindex":1,"val)":1}
,"instance":{"u_int32_t":1,"is-is":1,"circindex":1}
,"circindex":{"u_int32_t":1,"is-is":1}
,"val)":{"input":1}
,"input":{"parameter":1}
,"parameter":{"vr_id":1}
,"virtual":{"router":1}
,"router":{"default":1,"exist":1}
,"default":{"value":1}
,"value":{"non-vr":1,"isis_api_set_err_vr_not_exist":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"is-is":{"instance":1,"circuit":1}
,"index":{"val":1,"found":1}
,"val":{"level":1}
,"level":{"circuit":1,"output":1,"invalid":1}
,"level1":{"level2":1,"level":1}
,"level2":{"level1":1}
,"output":{"parameters":1}
,"parameters":{"none":1}
,"none":{"return":1}
,"return":{"value":1}
,"isis_api_set_err_vr_not_exist":{"virtual":1}
,"exist":{"isis_api_set_err_invalid_is_type":1,"isis_api_set_err_if_not_enabled":1}
,"isis_api_set_err_invalid_is_type":{"circuit":1}
,"invalid":{"isis_api_set_err_if_not_exist":1}
,"isis_api_set_err_if_not_exist":{"interface":1}
,"interface":{"exist":1,"enabled":1}
,"isis_api_set_err_if_not_enabled":{"interface":1}
,"enabled":{"isis_api_set_success":1}
,"isis_api_set_success":{"complete":1}
,"complete":{"isis_api_set_error":1}
,"isis_api_set_error":{"supported":1}
,"supported":{"circuit":1}
,"found":{"specified":1}
,"specified":{"instance":1}
}
;Search.control.loadWordPairs(pairs);
