var pairs =
{
"vrrp_global":{"data":1}
,"data":{"structure":1,"common":1}
,"structure":{"holds":1}
,"holds":{"data":1}
,"common":{"vrrp":1}
,"vrrp":{"sessions":1,"master":1,"timer":1,"session":1,"forwarding":1,"mac":1}
,"sessions":{"resides":1}
,"resides":{"nsm\u002Fvrrp\u002Fvrrp.h":1}
,"nsm\u002Fvrrp\u002Fvrrp.h":{"file":1}
,"file":{"member":1}
,"member":{"description":1}
,"description":{"back":1}
,"back":{"pointer":1}
,"pointer":{"vrrp":1}
,"master":{"notificationcntl":1}
,"notificationcntl":{"flag":1}
,"flag":{"trap":1,"vrrp_conf_debug":1}
,"trap":{"generation":1}
,"generation":{"enabled":1}
,"enabled":{"disabled":1}
,"disabled":{"t_vrrp_timer":1}
,"t_vrrp_timer":{"vrrp":1}
,"timer":{"sess_tbl_max":1}
,"sess_tbl_max":{"instance":1}
,"instance":{"table":1}
,"table":{"sess_tbl_cnt":1,"sess_tbl":1,"vrrp_sess_cnt":1,"asso_tbl_cnt":1,"asso_tbl":1,"t_vrrp_read":1}
,"sess_tbl_cnt":{"instance":1}
,"sess_tbl":{"instance":1}
,"vrrp_sess_cnt":{"count":1}
,"count":{"vrrp":1}
,"session":{"asso_tbl_max":1}
,"asso_tbl_max":{"maximum":1}
,"maximum":{"size":1}
,"size":{"associated":1}
,"associated":{"table":1}
,"asso_tbl_cnt":{"number":1}
,"number":{"entries":1}
,"entries":{"associated":1}
,"asso_tbl":{"associated":1}
,"t_vrrp_read":{"read":1}
,"read":{"thread":1}
,"thread":{"ipv4":1,"ipv6":1,"promiscous":1}
,"ipv4":{"t_vrrp_ipv6_read":1,"t_vrrp_icmpv6_read":1}
,"t_vrrp_ipv6_read":{"read":1}
,"ipv6":{"t_vrrp_prom":1,"sock":1,"socket":1}
,"t_vrrp_prom":{"read":1}
,"promiscous":{"mode":1}
,"mode":{"ipv4":1,"ipv6":1}
,"t_vrrp_icmpv6_read":{"read":1}
,"sock":{"send\u002Freceive":1}
,"send\u002Freceive":{"socket":1,"sockets":1}
,"socket":{"ibuf":1,"proto_err_reason":1}
,"ibuf":{"stream":1}
,"stream":{"buffer":1}
,"buffer":{"i6buf":1,"icmpv6_buf":1}
,"i6buf":{"stream":1}
,"icmpv6_buf":{"send\u002Freceive":1}
,"sockets":{"l2_sock":1,"sock_net":1,"sock_arp":1,"vrrp_mac":1,"vrrp":1}
,"l2_sock":{"vrrp":1}
,"forwarding":{"(layer":1}
,"(layer":{"sockets":1}
,"sock_net":{"vrrp":1}
,"sock_arp":{"vrrp":1}
,"vrrp_mac":{"vrrp":1}
,"mac":{"ipv6_sock":1}
,"ipv6_sock":{"ipv6":1}
,"proto_err_reason":{"indicates":1}
,"indicates":{"reason":1}
,"reason":{"error":1}
,"error":{"vrrp_term_debug":1}
,"vrrp_term_debug":{"debug":1}
,"debug":{"flag":1}
,"vrrp_conf_debug":{"debug":1}
}
;Search.control.loadWordPairs(pairs);
