var pairs =
{
"configure":{"carrier":1}
,"carrier":{"supporting":1,"(csc)":1,"l3vpn":1}
,"supporting":{"carrier":1}
,"(csc)":{"solutions":1}
,"solutions":{"section":1}
,"section":{"details":1}
,"details":{"use-case":1}
,"use-case":{"deploying":1}
,"deploying":{"carrier":1}
,"l3vpn":{"topology":1}
,"topology":{"prerequisite":1}
,"prerequisite":{"ensuring":1}
,"ensuring":{"csc":1}
,"csc":{"support":1,"enabled":1}
,"support":{"rfc":1}
,"rfc":{"3107":1}
,"3107":{"deals":1}
,"deals":{"carrying":1}
,"carrying":{"label":1}
,"label":{"information":1}
,"information":{"bgp-v4":1}
,"bgp-v4":{"csc":1}
,"enabled":{"configuring":1}
,"configuring":{"ce-pe":1}
,"ce-pe":{"--csc-ce":1}
,"--csc-ce":{"peers":1}
,"peers":{"exchange":1}
,"exchange":{"labels":1}
,"labels":{"thereby":1}
,"thereby":{"interconnect":1}
,"interconnect":{"networks":1}
,"networks":{"via":1}
,"via":{"core":1}
,"core":{"network":1}
,"network":{"running":1}
,"running":{"l3vpn":1}
}
;Search.control.loadWordPairs(pairs);
