var pairs =
{
"isis_if_bfd_disable_unset":{"function":1,"(u_int32_t":1}
,"function":{"unsets":1,"succeeds":1}
,"unsets":{"disable":1,"bfd":1}
,"disable":{"flag":1,"parameter":1}
,"flag":{"bfd":1}
,"bfd":{"fall-over":1,"disable":1}
,"fall-over":{"check":1}
,"check":{"neighbors":1}
,"neighbors":{"specified":1}
,"specified":{"interface":1}
,"interface":{"unsets":1,"syntax":1,"name":1}
,"parameter":{"interface":1}
,"syntax":{"int":1}
,"int":{"isis_if_bfd_disable_unset":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1}
,"char":{"*ifname)":1}
,"*ifname)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"pass":1}
,"pass":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"ifname":1}
,"ifname":{"interface":1}
,"name":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"sis_api_set_err_vr_not_exist":1}
,"sis_api_set_err_vr_not_exist":{"active":1}
,"active":{"instance":1}
,"instance":{"isis_api_set_success":1}
,"isis_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
