var pairs =
{
"protocol":{"constants":1,"types":1}
,"constants":{"protocol":1}
,"types":{"defined":1}
,"defined":{"pal\u002Fapi\u002Fpal_types.def":1}
,"pal\u002Fapi\u002Fpal_types.def":{"constant":1}
,"constant":{"description":1}
,"description":{"ipi_route_bgp":1}
,"ipi_route_bgp":{"bgp":1}
,"bgp":{"routes":1}
,"routes":{"ipi_route_connect":1,"ipi_route_default":1,"ipi_route_kernel":1,"ipi_route_ospf":1,"ipi_route_ospf6":1,"ipi_route_rip":1,"ipi_route_ripng":1,"ipi_route_static":1,"ipi_route_trill":1}
,"ipi_route_connect":{"connected":1}
,"connected":{"routes":1}
,"ipi_route_default":{"system":1}
,"system":{"ipi_route_isis":1}
,"ipi_route_isis":{"is-is":1}
,"is-is":{"routes":1}
,"ipi_route_kernel":{"kernel":1}
,"kernel":{"routes":1}
,"ipi_route_ospf":{"ospfv2":1}
,"ospfv2":{"routes":1}
,"ipi_route_ospf6":{"ospfv3":1}
,"ospfv3":{"routes":1}
,"ipi_route_rip":{"rip":1}
,"rip":{"routes":1}
,"ipi_route_ripng":{"ripng":1}
,"ripng":{"routes":1}
,"ipi_route_static":{"static":1}
,"static":{"routes":1}
,"ipi_route_trill":{"trill":1}
,"trill":{"routes":1}
}
;Search.control.loadWordPairs(pairs);
