var pairs =
{
"show":{"ptp":1}
,"ptp":{"unicast-neighbors":1,"unicast":1,"timescale":1}
,"unicast-neighbors":{"command":1,"parameters":1,"===========================================ptp":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"ptp":1}
,"unicast":{"neighbors":1,"enable":1}
,"neighbors":{"command":1,"fe80":1}
,"syntax":{"show":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"exec":1,"examples":1}
,"exec":{"mode":1}
,"examples":{"following":1}
,"following":{"example":1}
,"example":{"shows":1}
,"shows":{"ptp":1}
,"timescale":{"attributes":1}
,"attributes":{"show":1}
,"===========================================ptp":{"unicast":1}
,"enable":{"configured":1}
,"configured":{"unicast":1}
,"fe80":{":21b:21ff:fe39:6c4a":1,":21b:21ff:fe36:f342":1}
,":21b:21ff:fe39:6c4a":{"fe80":1}
,":21b:21ff:fe36:f342":{"===========================================":1}
}
;Search.control.loadWordPairs(pairs);
