var pairs =
{
"retry-limit":{"command":1,"value":1,"<1-65535>":1,"parameters":1,"256":1}
,"command":{"specify":1,"although":1,"controls":1,"helps":1,"revert":1,"syntax":1,"mode":1}
,"specify":{"retry":1}
,"retry":{"count":1,"command":1}
,"count":{"value":1}
,"value":{"rsvp":1,"affects":1,"command":1,"trunk":1}
,"rsvp":{"bypass":1}
,"bypass":{"trunk":1,"mode":1}
,"trunk":{"session":1,"bypass":1,"incomplete":1}
,"session":{"nonexistent":1,"retry-limit":1,"trunk":1,"try":1}
,"nonexistent":{"state":1}
,"state":{"due":1,"code":1,"regardless":1}
,"due":{"path":1}
,"path":{"error":1}
,"error":{"message":1}
,"message":{"tries":1}
,"tries":{"recreate":1}
,"recreate":{"lsp":1}
,"lsp":{"number":1,"facility-backup":1,"command":1,"indefinitely":1}
,"number":{"times":1}
,"times":{"specified":1,"system":1}
,"specified":{"retry-limit":1}
,"although":{"retry":1}
,"controls":{"trunk":1}
,"affects":{"session":1}
,"incomplete":{"state":1}
,"code":{"keeps":1}
,"keeps":{"trying":1}
,"trying":{"forever":1}
,"forever":{"bring":1}
,"bring":{"complete":1}
,"complete":{"state":1}
,"regardless":{"retry-limit":1}
,"helps":{"identify":1}
,"identify":{"attributes":1}
,"attributes":{"frr":1}
,"frr":{"backup":1}
,"backup":{"lsp":1}
,"facility-backup":{"protection":1}
,"protection":{"method":1}
,"method":{"parameter":1}
,"parameter":{"command":1}
,"revert":{"default":1}
,"default":{"retry-limit":1,"default":1}
,"syntax":{"retry-limit":1}
,"<1-65535>":{"retry-limit":1,"number":1}
,"parameters":{"<1-65535>":1}
,"system":{"try":1}
,"try":{"setting":1,"create":1}
,"setting":{"lsp":1}
,"mode":{"bypass":1,"default":1}
,"create":{"lsp":1}
,"indefinitely":{"example":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"rsvp-bypass":1}
,"rsvp-bypass":{"(config-bypass)":1}
,"(config-bypass)":{"retry-limit":1}
,"256":{"(config)":1}
}
;Search.control.loadWordPairs(pairs);
