var pairs =
{
"snmp":{"api":1,"operations":1}
,"api":{"section":1}
,"section":{"describes":1}
,"describes":{"function":1}
,"function":{"called":1,"description":1}
,"called":{"support":1}
,"support":{"snmp":1}
,"operations":{"function":1}
,"description":{"lldp_snmp_set_msg_tx_interval":1}
,"lldp_snmp_set_msg_tx_interval":{"sets":1}
,"sets":{"interval":1,"time":1,"delay":1}
,"interval":{"lldp":1}
,"lldp":{"frames":1,"disabled":1}
,"frames":{"transmitted":1}
,"transmitted":{"lldp_snmp_set_reinit_delay":1}
,"lldp_snmp_set_reinit_delay":{"sets":1}
,"time":{"lldp":1}
,"disabled":{"port":1}
,"port":{"attempt":1}
,"attempt":{"reinitialize":1}
,"reinitialize":{"lldp_snmp_set_tx_delay":1}
,"lldp_snmp_set_tx_delay":{"sets":1}
,"delay":{"transmission":1}
,"transmission":{"successive":1}
,"successive":{"lldp":1}
}
;Search.control.loadWordPairs(pairs);
