var pairs =
{
"switch":{"switch1":1}
,"switch1":{"configure":1,"(config)":1,"(config-if)":1}
,"configure":{"terminal":1,"mode":1,"bridge":1,"spanning":1,"vlan":1,"eth1":1,"port":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"interface":1}
,"mode":{"switch":1,"rstp":1,"eth1":1,"trunk":1}
,"(config)":{"bridge":1,"spanning-tree":1,"vlan":1,"interface":1}
,"bridge":{"protocol":1,"rstp":1,"configure":1,"switch1":1,"interface":1}
,"protocol":{"rstp":1}
,"rstp":{"vlan-bridge":1,"bridge\u002Fswitch1":1,"configure":1,"switch1":1}
,"vlan-bridge":{"configure":1}
,"bridge\u002Fswitch1":{"(config)":1}
,"spanning-tree":{"mode":1}
,"spanning":{"tree":1}
,"tree":{"mode":1}
,"vlan":{"2-3":1,"associate":1,"add":1,"vlan":1,"interface":1}
,"2-3":{"bridge":1}
,"associate":{"bridge":1}
,"interface":{"eth1":1,"mode":1,"switch1":1}
,"eth1":{"enter":1,"switch1":1,"layer":1}
,"(config-if)":{"switchport":1,"bridge-group":1,"exit":1}
,"switchport":{"configure":1,"mode":1,"trunk":1}
,"layer":{"port":1}
,"port":{"switch1":1,"trunk":1}
,"bridge-group":{"associate":1}
,"trunk":{"configure":1,"switch1":1,"allowed":1}
,"allowed":{"vlan":1}
,"add":{"2,3":1}
,"2,3":{"configure":1}
,"exit":{"exit":1,"interface":1}
}
;Search.control.loadWordPairs(pairs);
