var pairs =
{
"bgp_network_sync_set":{"function":1,"(struct":1}
,"function":{"ensures":1,"called":1}
,"ensures":{"specified":1}
,"specified":{"static":1,"follows":1}
,"static":{"network":1}
,"network":{"prefix":1,"advertised":1,"address":1,"synchronization":1}
,"prefix":{"igp":1}
,"igp":{"reachability":1}
,"reachability":{"nsm":1}
,"nsm":{"rib":1}
,"rib":{"introduced":1,"network":1}
,"introduced":{"bgp":1}
,"bgp":{"rib":1,"routing":1,"*bgp":1,"bgp":1,"instance":1}
,"advertised":{"bgp":1}
,"routing":{"process":1}
,"process":{"specified":1}
,"follows":{"unicast":1}
,"unicast":{"network":1}
,"address":{"without":1,"matches":1,"family":1}
,"without":{"mask":1}
,"mask":{"accepted":1,"derived":1}
,"accepted":{"falls":1}
,"falls":{"natural":1}
,"natural":{"boundary":1,"class-boundary":1}
,"boundary":{"class":1}
,"class":{"class-boundary":1}
,"class-boundary":{"mask":1,"function":1}
,"derived":{"address":1}
,"matches":{"natural":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"network":1}
,"synchronization":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"bgp_network_sync_set":1}
,"(struct":{"bgp":1}
,"*bgp":{"afi_t":1}
,"afi_t":{"afi":1}
,"afi":{"safi_t":1,"address":1}
,"safi_t":{"safi)":1}
,"safi)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bgp":1,"none":1}
,"instance":{"afi":1}
,"family":{"safi":1,"output":1}
,"safi":{"sub":1}
,"sub":{"address":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"bgp_api_set_success":1}
,"bgp_api_set_success":{"call":1}
,"call":{"successful":1}
,"successful":{"(0)":1}
}
;Search.control.loadWordPairs(pairs);
