var pairs =
{
"mrib4_igmp_api_ssm_map_enable_unset":{"function":1,"(struct":1}
,"function":{"unsets":1,"succeeds":1}
,"unsets":{"igmp":1}
,"igmp":{"ssm-map":1,"instance":1}
,"ssm-map":{"enable":1}
,"enable":{"instance":1}
,"instance":{"level":1,"output":1,"specified":1}
,"level":{"syntax":1}
,"syntax":{"int":1}
,"int":{"mrib4_igmp_api_ssm_map_enable_unset":1}
,"(struct":{"igmp_instance":1}
,"igmp_instance":{"*igi)":1}
,"*igi)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"igi":1,"none":1}
,"igi":{"pointer":1}
,"pointer":{"igmp":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"igmp_err_none":1,"given":1}
,"igmp_err_none":{"function":1}
,"succeeds":{"igmp_err_invalid_value":1}
,"igmp_err_invalid_value":{"igmp":1}
,"specified":{"interface":1}
,"interface":{"null":1}
,"null":{"supported":1}
,"supported":{"values":1}
}
;Search.control.loadWordPairs(pairs);
