var pairs =
{
"rsvp-trunk":{"command":1,"trunkname":1,"ipv4":1}
,"command":{"p2mp":1,"mode":1,"syntax":1}
,"p2mp":{"trunk":1,"mode":1,"ipv6":1,"p2mp-enabled":1,"(config-p2mp-trunk)":1}
,"trunk":{"rsvp":1,"mode":1,"properties":1,"ipv4":1,"p2mp":1,"ipv6":1,"command":1}
,"rsvp":{"lsp":1,"p2mp":1}
,"lsp":{"upon":1}
,"upon":{"successful":1}
,"successful":{"execution":1}
,"execution":{"command":1}
,"mode":{"changed":1,"p2mp":1,"subsequent":1,"rsvp":1,"examples":1}
,"changed":{"rsvp":1}
,"subsequent":{"configuration":1}
,"configuration":{"trunk":1}
,"properties":{"command":1}
,"syntax":{"rsvp-trunk":1}
,"trunkname":{"(ipv4":1,"name":1}
,"(ipv4":{"p2mp":1,"ipv6)":1}
,"ipv6":{"p2mp)":1,"ipv6":1,"address":1}
,"p2mp)":{"rsvp-trunk":1}
,"ipv6)":{"parameters":1}
,"parameters":{"trunkname":1}
,"name":{"p2mp":1}
,"ipv4":{"ipv4":1,"address":1,"p2mp":1}
,"address":{"family":1}
,"family":{"trunk":1}
,"p2mp-enabled":{"trunk":1}
,"examples":{"(config)":1}
,"(config)":{"rsvp-trunk":1}
}
;Search.control.loadWordPairs(pairs);
