var pairs =
{
"cisco-metric-behavior":{"command":1,"(enable":1,"parameters":1,"enable":1}
,"command":{"enable":1,"disable":1,"syntax":1,"mode":1}
,"enable":{"metric":1,"enable":1,"updating":1}
,"metric":{"update":1,"consistent":1}
,"update":{"consistent":1,"behavior":1}
,"consistent":{"cisco":1}
,"cisco":{"either":1,"disable":1,"default":1,"metric-behavior":1,"router":1}
,"either":{"disable":1}
,"disable":{"parameter":1,"feature":1,"disable":1,"updating":1}
,"parameter":{"command":1}
,"feature":{"command":1}
,"syntax":{"cisco-metric-behavior":1}
,"(enable":{"disable)":1}
,"disable)":{"cisco-metric-behavior":1}
,"parameters":{"enable":1}
,"updating":{"metric":1}
,"default":{"default":1,"cisco":1}
,"metric-behavior":{"disabled":1}
,"disabled":{"command":1}
,"mode":{"router":1,"example":1,"configure":1}
,"router":{"mode":1,"rip":1}
,"example":{"example":1,"shows":1}
,"shows":{"enable":1}
,"behavior":{"consistent":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"rip":{"(config-router)":1}
,"(config-router)":{"cisco-metric-behavior":1}
}
;Search.control.loadWordPairs(pairs);
