var pairs =
{
"routing":{"information":1,"internal":1,"capabilities":1,"(cidr)":1,"virtual":1,"forwarding":1}
,"information":{"protocol":1,"thus":1,"rip":1}
,"protocol":{"routing":1,"(rip)":1,"developer":1}
,"(rip)":{"version":1}
,"version":{"commonly":1}
,"commonly":{"used":1}
,"used":{"interior":1}
,"interior":{"gateway":1}
,"gateway":{"protocols":1}
,"protocols":{"(igp)":1}
,"(igp)":{"routing":1}
,"internal":{"ipv4":1}
,"ipv4":{"networks":1}
,"networks":{"lesser":1,"connected":1,"zebos-xp":1}
,"lesser":{"extent":1}
,"extent":{"networks":1}
,"connected":{"internet":1}
,"internet":{"rip":1}
,"rip":{"employs":1,"supports":1,"routing":1}
,"employs":{"distributed":1}
,"distributed":{"variant":1}
,"variant":{"bellman-ford":1}
,"bellman-ford":{"algorithm":1}
,"algorithm":{"provide":1}
,"provide":{"distance":1}
,"distance":{"vector":1}
,"vector":{"routing":1}
,"capabilities":{"rip":1}
,"supports":{"subnet":1}
,"subnet":{"information":1}
,"thus":{"allowing":1}
,"allowing":{"classless":1}
,"classless":{"inter-domain":1}
,"inter-domain":{"routing":1}
,"(cidr)":{"ripng":1}
,"ripng":{"contains":1}
,"contains":{"extensions":1}
,"extensions":{"support":1}
,"support":{"ipv6":1,"virtual":1,"full":1,"information":1}
,"ipv6":{"networks":1}
,"zebos-xp":{"rip\u002Fripng":1}
,"rip\u002Fripng":{"features":1}
,"features":{"include":1}
,"include":{"split":1}
,"split":{"horizons":1}
,"horizons":{"poisoned":1}
,"poisoned":{"reverse":1}
,"reverse":{"triggered":1}
,"triggered":{"updates":1}
,"updates":{"ecmp":1}
,"ecmp":{"(equal":1}
,"(equal":{"cost":1}
,"cost":{"multi":1}
,"multi":{"path":1}
,"path":{"routing)":1}
,"routing)":{"support":1}
,"virtual":{"routing":1}
,"forwarding":{"support":1}
,"full":{"mib":1}
,"mib":{"support":1}
,"developer":{"guide":1}
}
;Search.control.loadWordPairs(pairs);
