var pairs =
{
"nsm_tdm_show_statistics":{"function":1,"(struct":1}
,"function":{"display":1}
,"display":{"tdm":1}
,"tdm":{"statistics":1}
,"statistics":{"syntax":1}
,"syntax":{"int":1}
,"int":{"nsm_tdm_show_statistics":1}
,"(struct":{"cli":1}
,"cli":{"*cli":1,"specifies":1,"structure":1}
,"*cli":{"u_int8_t":1}
,"u_int8_t":{"iwf_type":1}
,"iwf_type":{"struct":1,"tunnel":1}
,"struct":{"interface":1}
,"interface":{"*ifp)":1,"pointer":1}
,"*ifp)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"cli":1,"none":1}
,"specifies":{"instance":1}
,"instance":{"cli":1}
,"structure":{"iwf_type":1}
,"tunnel":{"ifp":1}
,"ifp":{"interface":1}
,"pointer":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_success":1}
}
;Search.control.loadWordPairs(pairs);
