var pairs =
{
"efm_oam_protocol_disable":{"function":1,"(struct":1}
,"function":{"disables":1,"implements":1,"syntax":1,"succeeds":1}
,"disables":{"oam":1}
,"oam":{"specified":1,"disable":1,"already":1}
,"specified":{"interface":1}
,"interface":{"function":1,"*ifp)":1,"structure":1,"found":1}
,"implements":{"ethernet":1}
,"ethernet":{"oam":1}
,"disable":{"command":1}
,"command":{"efm":1}
,"efm":{"mib":1}
,"mib":{"support":1}
,"support":{"calls":1}
,"calls":{"function":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"efm_oam_protocol_disable":1}
,"(struct":{"interface":1}
,"*ifp)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"none":1}
,"ifp":{"pointer":1}
,"pointer":{"interface":1}
,"structure":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"efm_oam_err_if_not_found":1}
,"efm_oam_err_if_not_found":{"onmd":1}
,"onmd":{"interface":1}
,"found":{"efm_oam_err_already_disabled":1}
,"efm_oam_err_already_disabled":{"oam":1}
,"already":{"disabled":1}
,"disabled":{"efm_oam_err_internal":1}
,"efm_oam_err_internal":{"internal":1}
,"internal":{"error":1}
,"error":{"efm_success":1}
,"efm_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
