var pairs =
{
"nsm_mpls_api_del_lsp_tunnel":{"function":1,"(struct":1}
,"function":{"deletes":1}
,"deletes":{"lsp":1}
,"lsp":{"tunnel":1}
,"tunnel":{"syntax":1,"found":1,"deleted":1}
,"syntax":{"int":1}
,"int":{"nsm_mpls_api_del_lsp_tunnel":1}
,"(struct":{"nsm_master":1}
,"nsm_master":{"*nm":1}
,"*nm":{"struct":1}
,"struct":{"interface":1}
,"interface":{"*ifp":1,"in_label":1}
,"*ifp":{"u_int32_t":1}
,"u_int32_t":{"in_label)":1}
,"in_label)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"pointer":1,"none":1}
,"pointer":{"nsm":1,"interface":1}
,"nsm":{"master":1}
,"master":{"structure":1}
,"structure":{"ifp":1}
,"ifp":{"pointer":1}
,"in_label":{"incoming":1}
,"incoming":{"label":1}
,"label":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_err_not_found":1}
,"nsm_err_not_found":{"lsp":1}
,"found":{"nsm_success":1}
,"nsm_success":{"lsp":1}
,"deleted":{"successfully":1}
}
;Search.control.loadWordPairs(pairs);
