var pairs =
{
"load":{"ipv6":1}
,"ipv6":{"command":1,"protocol":1,"(ospf":1,"ospf":1}
,"command":{"load":1,"remove":1,"syntax":1,"mode":1}
,"protocol":{"modules":1,"module":1}
,"modules":{"virtual":1}
,"virtual":{"router":1}
,"router":{"parameter":1}
,"parameter":{"command":1}
,"remove":{"specified":1}
,"specified":{"protocol":1}
,"module":{"command":1,"ipv6":1,"rip":1}
,"syntax":{"load":1}
,"(ospf":{"rip)":1}
,"rip)":{"parameters":1}
,"parameters":{"ospf":1}
,"ospf":{"loads":1}
,"loads":{"ospfv3":1,"ripng":1}
,"ospfv3":{"module":1}
,"rip":{"loads":1}
,"ripng":{"module":1}
,"mode":{"mode":1,"examples":1}
,"examples":{"(config)":1}
,"(config)":{"virtual-router":1}
,"virtual-router":{"vr1":1}
,"vr1":{"(config-vr)":1}
,"(config-vr)":{"load":1}
}
;Search.control.loadWordPairs(pairs);
