var pairs =
{
"nhlfe-entry":{"command":1,"configuration":1,"allowed":1,"label":1,"1001":1}
,"command":{"configure":1,"used":1,"reset":1,"syntax":1,"modes":1}
,"configure":{"nhlfe":1}
,"nhlfe":{"entry":1}
,"entry":{"defines":1}
,"defines":{"mpls":1}
,"mpls":{"property":1}
,"property":{"traffic":1}
,"traffic":{"ingresses":1}
,"ingresses":{"mpls-tp":1}
,"mpls-tp":{"cloud":1,"tunnel":1}
,"cloud":{"command":1}
,"used":{"edge":1,"nhlfe-entry":1,"ilm-entry":1,"bw-class":1}
,"edge":{"node":1}
,"node":{"tunnel":1}
,"tunnel":{"(unidirectional\u002Fbidirectional)":1,"provider":1,"removing":1,"associated":1,"constitute":1,"nhlfe-entry":1,"(forward-path":1,"mode":1,"(config)":1,"source":1}
,"(unidirectional\u002Fbidirectional)":{"co-routed":1}
,"co-routed":{"bidirectional":1}
,"bidirectional":{"tunnel":1,"path":1,"lsp":1,"(config-bidir-tnl)":1}
,"provider":{"interface":1}
,"interface":{"used":1,"name":1}
,"configuration":{"used":1,"parameter":1,"unidirectional":1}
,"ilm-entry":{"configuration":1}
,"parameter":{"command":1}
,"reset":{"configuration":1}
,"unidirectional":{"tunnel":1,"bidirectional":1,"(config-unidir-tnl)":1}
,"removing":{"nhlfe-entry":1}
,"allowed":{"tunnel":1}
,"associated":{"unidirectional":1,"bidirectional":1}
,"constitute":{"associated":1}
,"path":{"command":1,"bidirectional":1}
,"syntax":{"unidirectional":1}
,"label":{"ifname":1,"outgoing":1,"value":1}
,"ifname":{"{mac":1,"bidirectional":1,"(forward-path":1,"parameters":1,"outgoing":1}
,"{mac":{"mac":1}
,"mac":{"bw-class":1,"nexthop":1,"address":1}
,"bw-class":{"name}":1,"bandwidth":1}
,"name}":{"nhlfe-entry":1,"(forward-path":1}
,"(forward-path":{"reverse-path)":1}
,"reverse-path)":{"nhlfe-entry":1}
,"parameters":{"label":1}
,"outgoing":{"label":1,"interface":1}
,"value":{"range":1}
,"range":{"<16-1048575>":1}
,"<16-1048575>":{"ifname":1}
,"name":{"maximum":1,"name":1,"bandwidth":1}
,"maximum":{"characters":1}
,"characters":{"mac":1,"forward-path":1}
,"nexthop":{"mac":1}
,"address":{"mac":1,"xxxx:xxxx:xxxx":1,"identified":1,"used":1}
,"xxxx:xxxx:xxxx":{"format":1}
,"format":{"mac":1}
,"identified":{"default":1}
,"default":{"broadcast":1}
,"broadcast":{"mac":1}
,"bandwidth":{"class":1}
,"class":{"name":1,"maximum":1}
,"forward-path":{"forward":1,"nhlfe-entry":1}
,"forward":{"path":1}
,"lsp":{"reverse-path":1,"command":1}
,"reverse-path":{"reverse":1}
,"reverse":{"path":1}
,"modes":{"unidirectional":1}
,"mode":{"examples":1}
,"examples":{"example":1}
,"example":{"below":1}
,"below":{"unidirectional":1,"bidirectional":1}
,"(config)":{"mpls-tp":1}
,"source":{"100":1}
,"100":{"1.1.1.1":1,"3.3.3.3":1}
,"1.1.1.1":{"destination":1}
,"destination":{"100":1}
,"3.3.3.3":{"(config-tnl)":1}
,"(config-tnl)":{"tunnel-mode":1}
,"tunnel-mode":{"unidirectional":1,"bidirectional":1}
,"(config-unidir-tnl)":{"nhlfe-entry":1}
,"1001":{"eth1":1}
,"eth1":{"(config-unidir-tnl)":1,"example":1,"(config-bidir-tnl)":1}
,"(config-bidir-tnl)":{"forward-path":1}
}
;Search.control.loadWordPairs(pairs);
