var pairs =
{
"isis_max_lsp_lifetime_set":{"call":1,"(u_int32_t":1}
,"call":{"implements":1,"successful":1}
,"implements":{"max-lsp-lifetime":1}
,"max-lsp-lifetime":{"command":1}
,"command":{"configure":1}
,"configure":{"maximum":1}
,"maximum":{"lsp":1}
,"lsp":{"lifetime":1}
,"lifetime":{"syntax":1,"seconds":1}
,"syntax":{"int":1}
,"int":{"isis_max_lsp_lifetime_set":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1,"tag":1}
,"char":{"*tag":1}
,"*tag":{"u_int32_t":1}
,"u_int32_t":{"max_lifetime)":1}
,"max_lifetime)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1,"isis_api_set_err_vr_not_exist":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"tag":{"is-is":1,"max_lifetime":1,"isis_api_set_err_invalid_value":1}
,"is-is":{"instance":1}
,"instance":{"area":1,"exist":1}
,"area":{"tag":1}
,"max_lifetime":{"maximum":1,"outside":1}
,"seconds":{"<1-65535>":1}
,"<1-65535>":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"isis_api_set_err_vr_not_exist":{"exist":1}
,"exist":{"isis_api_set_err_instance_not_exist":1,"given":1}
,"isis_api_set_err_instance_not_exist":{"is-is":1}
,"given":{"tag":1,"max_lifetime":1}
,"isis_api_set_err_invalid_value":{"given":1}
,"outside":{"range":1}
,"range":{"isis_api_set_success":1}
,"isis_api_set_success":{"call":1}
}
;Search.control.loadWordPairs(pairs);
