var pairs =
{
"quality":{"service":1}
,"service":{"api":1,"(qos)":1}
,"api":{"following":1,"functions":1}
,"following":{"subsection":1}
,"subsection":{"includes":1}
,"includes":{"quality":1}
,"(qos)":{"functions":1}
,"functions":{"qos":1,"functions":1,"description":1}
,"qos":{"api":1,"hardware":1}
,"description":{"hal_l2_qos_init":1}
,"hal_l2_qos_init":{"function":1}
,"function":{"initializes":1,"deinitializes":1,"sets":1,"gets":1}
,"initializes":{"qos":1}
,"hardware":{"layer":1}
,"layer":{"hal_l2_qos_deinit":1,"hal_l2_qos_default_user_priority_set":1}
,"hal_l2_qos_deinit":{"function":1}
,"deinitializes":{"qos":1}
,"hal_l2_qos_default_user_priority_set":{"function":1}
,"sets":{"default":1,"regenerated":1,"traffic":1}
,"default":{"user":1}
,"user":{"priority":1}
,"priority":{"port":1}
,"port":{"hal_l2_qos_default_user_priority_get":1,"hal_l2_qos_regen_user_priority_set":1,"hal_l2_qos_regen_user_priority_get":1,"hal_l2_qos_traffic_class_set":1,"hal_l2_qos_traffic_class_get":1}
,"hal_l2_qos_default_user_priority_get":{"function":1}
,"gets":{"default":1,"regenerated":1,"traffic":1}
,"hal_l2_qos_regen_user_priority_set":{"function":1}
,"regenerated":{"user":1}
,"hal_l2_qos_regen_user_priority_get":{"function":1}
,"hal_l2_qos_traffic_class_set":{"function":1}
,"traffic":{"class":1}
,"class":{"value":1}
,"value":{"port":1}
,"hal_l2_qos_traffic_class_get":{"function":1}
}
;Search.control.loadWordPairs(pairs);
