var pairs =
{
"nsm_mpls_api_admin_group_del":{"function":1,"(struct":1}
,"function":{"deletes":1,"fails":1}
,"deletes":{"administrative":1}
,"administrative":{"group":1}
,"group":{"syntax":1,"name":1,"value":1,"interface":1,"deleted":1}
,"syntax":{"int":1}
,"int":{"nsm_mpls_api_admin_group_del":1,"val)":1}
,"(struct":{"nsm_master":1}
,"nsm_master":{"*nm":1}
,"*nm":{"char":1}
,"char":{"*name":1}
,"*name":{"int":1}
,"val)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"pointer":1,"none":1}
,"pointer":{"nsm":1}
,"nsm":{"master":1}
,"master":{"structure":1}
,"structure":{"name":1}
,"name":{"administrative":1,"val":1,"greater":1,"already":1}
,"val":{"administrative":1}
,"value":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_failure":1}
,"nsm_failure":{"function":1}
,"fails":{"nsm_err_name_too_long":1}
,"nsm_err_name_too_long":{"given":1}
,"given":{"name":1}
,"greater":{"maximum":1}
,"maximum":{"size":1}
,"size":{"admin_group_err_eexist":1}
,"admin_group_err_eexist":{"given":1}
,"already":{"exists":1}
,"exists":{"nsm_err_name_in_use":1}
,"nsm_err_name_in_use":{"administrative":1}
,"interface":{"configuration":1}
,"configuration":{"nsm_success":1}
,"nsm_success":{"group":1}
,"deleted":{"successfully":1}
}
;Search.control.loadWordPairs(pairs);
