var pairs =
{
"te-link":{"command":1,"telname":1,"new-link":1}
,"command":{"configure":1,"syntax":1,"mode":1}
,"configure":{"link":1,"terminal":1}
,"link":{"name":1}
,"name":{"parameter":1,"command":1}
,"parameter":{"remove":1}
,"remove":{"link":1}
,"syntax":{"te-link":1}
,"telname":{"te-link":1,"parameters":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"control":1,"examples":1}
,"control":{"adjacency":1}
,"adjacency":{"mode":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"control-adjacency":1}
,"control-adjacency":{"new":1}
,"new":{"peer-address":1}
,"peer-address":{"1.2.3.4":1}
,"1.2.3.4":{"static":1}
,"static":{"(config-ca)":1}
,"(config-ca)":{"te-link":1}
,"new-link":{"(config)":1}
}
;Search.control.loadWordPairs(pairs);
