var pairs =
{
"ospf6_get_link_lsdb_age":{"function":1,"(char":1}
,"function":{"gets":1,"fails":1,"succeeds":1}
,"gets":{"age":1}
,"age":{"lsa":1}
,"lsa":{"stored":1,"received":1,"output":1,"seconds":1}
,"stored":{"local":1}
,"local":{"link-scope":1}
,"link-scope":{"lsdb":1}
,"lsdb":{"syntax":1,"router_id":1}
,"syntax":{"int":1}
,"int":{"ospf6_get_link_lsdb_age":1,"ifindex":1,"instid":1,"type":1,"*ret)":1}
,"(char":{"*tag":1}
,"*tag":{"int":1}
,"ifindex":{"int":1,"identifier":1}
,"instid":{"int":1,"instance":1}
,"type":{"struct":1,"type":1,"lsa":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"router_id":1,"ls_id":1}
,"router_id":{"struct":1,"router":1}
,"ls_id":{"int":1,"link":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"tag":1,"ret":1}
,"tag":{"ospfv3":1,"ifindex":1}
,"ospfv3":{"process":1}
,"process":{"tag":1}
,"identifier":{"link":1,"type":1,"originating":1,"lsa":1}
,"link":{"lsa":1,"state":1}
,"received":{"instid":1}
,"instance":{"identifier":1}
,"router":{"identifier":1,"ls_id":1}
,"originating":{"router":1}
,"state":{"identifier":1}
,"output":{"parameters":1}
,"ret":{"age":1}
,"seconds":{"return":1}
,"return":{"values":1}
,"values":{"ospf6_api_get_error":1}
,"ospf6_api_get_error":{"function":1}
,"fails":{"ospf6_api_get_success":1}
,"ospf6_api_get_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
