var pairs =
{
"customer-spanning-tree":{"provider-edge":1}
,"provider-edge":{"path-cost":1,"svlan":1}
,"path-cost":{"command":1,"<1-200000000>":1,"parameters":1,"1000":1}
,"command":{"cost":1,"remove":1,"syntax":1,"mode":1}
,"cost":{"path":1,"assigned":1}
,"path":{"associated":1}
,"associated":{"provider":1}
,"provider":{"edge":1}
,"edge":{"port":1,"spanning":1}
,"port":{"customer":1,"<1-200000000>":1}
,"customer":{"edge":1}
,"spanning":{"tree":1}
,"tree":{"form":1,"command":1}
,"form":{"command":1}
,"remove":{"cost":1}
,"syntax":{"customer-spanning-tree":1}
,"svlan":{"<1-4094>":1,"identifier":1,"path-cost":1}
,"<1-4094>":{"path-cost":1,"specify":1}
,"<1-200000000>":{"customer-spanning-tree":1,"specify":1}
,"parameters":{"<1-4094>":1}
,"specify":{"svlan":1,"cost":1}
,"identifier":{"provider":1}
,"assigned":{"group":1}
,"group":{"command":1}
,"mode":{"interface":1,"examples":1}
,"interface":{"mode":1,"eth1":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth1":{"(config-if)":1}
,"(config-if)":{"customer-spanning-tree":1}
,"1000":{"(config-if)":1}
}
;Search.control.loadWordPairs(pairs);
