var pairs =
{
"missing":{"med":1,"multi":1,"received":1}
,"med":{"missing":1,"updating":1,"remove-recv-med":1,"remove-send-med":1,"update":1,"considered":1,"during":1,"confed":1,"bgp2":1,"route":1,"sent":1}
,"multi":{"exit":1}
,"exit":{"disc":1}
,"disc":{"(med)":1}
,"(med)":{"attribute":1}
,"attribute":{"missing":1}
,"received":{"update":1,"setting":1,"routes":1}
,"update":{"message":1,"messages":1}
,"message":{"zebos-xp":1,"peers":1,"withdraw":1,"med":1,"sent":1}
,"zebos-xp":{"takes":1,"checks":1,"considers":1}
,"takes":{"default":1}
,"default":{"value":1,"flag":1}
,"value":{"med":1}
,"updating":{"database":1}
,"database":{"(no)":1}
,"(no)":{"bgp":1}
,"bgp":{"bestpath":1,"re-do":1}
,"bestpath":{"med":1}
,"remove-recv-med":{"(no)":1,"command":1}
,"remove-send-med":{"commands":1,"command":1}
,"commands":{"remove":1,"executed":1}
,"remove":{"send":1}
,"send":{"med":1}
,"peers":{"(no)":1,"flag":1,"default":1,"bgp_cflag_remove_rcvd":1,"bgp_cflag_remove_send":1}
,"command":{"sets":1,"executed":1}
,"sets":{"bgp_cflag_remove_rcvd":1,"bgp_cflag_remove_send":1}
,"bgp_cflag_remove_rcvd":{"flag":1}
,"flag":{"receiving":1,"flag":1,"med":1,"zebos-xp":1,"higher":1,"flags":1,"trigger":1,"affected":1,"example":1,"sending":1,"reflects":1,"setting":1}
,"receiving":{"update":1}
,"checks":{"whether":1}
,"whether":{"flag":1}
,"considered":{"path":1,"setting":1}
,"path":{"selection":1}
,"selection":{"sent":1,"sends":1,"already\u2011selected":1,"received":1,"med":1,"forwarding":1,"already-selected":1,"aggregates":1}
,"sent":{"update":1,"bgp4":1,"setting":1}
,"considers":{"med":1,"meds":1}
,"during":{"route":1}
,"route":{"selection":1}
,"sends":{"med":1,"update":1}
,"messages":{"peers":1}
,"higher":{"preference":1}
,"preference":{"missing":1}
,"confed":{"flag":1}
,"flags":{"considered":1}
,"setting":{"flag":1,"cause":1,"unsetting":1}
,"trigger":{"notifications":1}
,"notifications":{"update":1}
,"withdraw":{"network":1,"nlri":1}
,"network":{"layer":1}
,"layer":{"reachability":1}
,"reachability":{"information":1}
,"information":{"(nlri)":1}
,"(nlri)":{"already-advertised":1}
,"already-advertised":{"routes":1}
,"routes":{"cause":1,"routes":1,"received":1,"aggregated":1,"flag":1,"sent":1,"however":1,"bgp2":1,"exchanged":1,"learnt":1,"affected":1}
,"cause":{"bgp":1}
,"re-do":{"route":1}
,"already\u2011selected":{"routes":1}
,"affected":{"flag":1,"dynamic":1}
,"example":{"bgp1":1}
,"bgp1":{"------------------bgp2":1,"sends":1}
,"------------------bgp2":{"----------------------bgp3":1}
,"----------------------bgp3":{"bgp4":1}
,"bgp4":{"bgp1":1,"case":1,"(no)":1,"either":1}
,"bgp2":{"bgp3":1,"bgp2":1,"neighbor":1,"bgp":1,"consider":1,"send":1,"considers":1,"sends":1}
,"bgp3":{"sends":1}
,"neighbor":{"a.b.c.d":1}
,"a.b.c.d":{"as-set":1}
,"as-set":{"summary-only":1}
,"summary-only":{"command":1}
,"executed":{"case":1,"bgp2":1,"few":1}
,"case":{"bgp2":1}
,"consider":{"med":1}
,"aggregated":{"bgp2":1}
,"bgp_cflag_remove_send":{"flag":1}
,"sending":{"update":1}
,"reflects":{"forwarding":1}
,"forwarding":{"process":1,"sends":1}
,"process":{"flag":1}
,"nlri":{"already-advertised":1}
,"already-selected":{"routes":1}
,"meds":{"route":1}
,"aggregates":{"routes":1}
,"however":{"bgp2":1}
,"either":{"above-described":1}
,"above-described":{"commands":1}
,"few":{"routes":1}
,"exchanged":{"flag":1}
,"unsetting":{"affect":1}
,"affect":{"routes":1}
,"learnt":{"afterward":1}
,"afterward":{"already-learnt":1}
,"already-learnt":{"routes":1}
,"dynamic":{"execution":1}
,"execution":{"commands":1}
}
;Search.control.loadWordPairs(pairs);
