var pairs =
{
"pseudowire":{"(pw)":1,"transport":1,"originates":1,"(ss-pw)":1,"extends":1,"(ms-pw)":1}
,"(pw)":{"emulation":1}
,"emulation":{"point-to-point":1,"service":1}
,"point-to-point":{"connection":1}
,"connection":{"packet-switching":1}
,"packet-switching":{"network":1}
,"network":{"pseudowire":1,"structure-aware":1,"(cesopsn)":1,"(autonomous":1}
,"transport":{"legacy":1}
,"legacy":{"services":1}
,"services":{"tdm":1}
,"tdm":{"packet-switched":1,"circuit":1,"packet":1}
,"packet-switched":{"network":1}
,"structure-aware":{"tdm":1}
,"circuit":{"emulation":1}
,"service":{"packet-switched":1}
,"(cesopsn)":{"structure-agnostic":1}
,"structure-agnostic":{"tdm":1}
,"packet":{"(satop)":1}
,"(satop)":{"pseudowire":1}
,"originates":{"terminates":1}
,"terminates":{"edge":1}
,"edge":{"single":1}
,"single":{"packet-switched":1}
,"(autonomous":{"system":1}
,"system":{"carrier":1}
,"carrier":{"network)":1,"networks":1}
,"network)":{"called":1}
,"called":{"single-segment":1,"multi-segment":1}
,"single-segment":{"pseudowire":1}
,"(ss-pw)":{"pseudowire":1}
,"extends":{"multiple":1}
,"multiple":{"autonomous":1}
,"autonomous":{"systems":1}
,"systems":{"carrier":1}
,"networks":{"called":1}
,"multi-segment":{"pseudowire":1}
}
;Search.control.loadWordPairs(pairs);
