var pairs =
{
"ospf6_get_if_admin_stat":{"function":1,"(char":1}
,"function":{"gets":1,"fails":1,"succeeds":1}
,"gets":{"administrative":1}
,"administrative":{"status":1}
,"status":{"given":1,"ospfv3":1}
,"given":{"ospfv3":1}
,"ospfv3":{"interface":1,"process":1}
,"interface":{"syntax":1,"index":1,"ospf6_api_status_enabled":1}
,"syntax":{"int":1}
,"int":{"ospf6_get_if_admin_stat":1,"ifindex":1,"instid":1,"*ret)":1}
,"(char":{"*tag":1}
,"*tag":{"int":1}
,"ifindex":{"int":1,"interface":1}
,"instid":{"int":1,"instance":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"tag":1,"ret":1}
,"tag":{"ospfv3":1,"ifindex":1}
,"process":{"tag":1}
,"index":{"instid":1}
,"instance":{"identifier":1}
,"identifier":{"output":1}
,"output":{"parameters":1}
,"ret":{"administrative":1}
,"ospf6_api_status_enabled":{"enabled":1}
,"enabled":{"ospf6_api_status_disabled":1}
,"ospf6_api_status_disabled":{"disabled":1}
,"disabled":{"return":1}
,"return":{"values":1}
,"values":{"ospf6_api_get_error":1}
,"ospf6_api_get_error":{"function":1}
,"fails":{"ospf6_api_get_success":1}
,"ospf6_api_get_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
