var pairs =
{
"client":{"server":1,"restart":1,"once":1,"supplies":1,"terminates":1,"clients":1}
,"server":{"restart":1,"client":1,"process":1,"comes":1,"batch":1,"starts":1,"beforehand":1,"maintains":1,"during":1,"flushes":1}
,"restart":{"scenario":1,"scenarios":1,"case":1,"example":1,"took":1,"bfd":1,"parameters":1,"occurs":1,"period":1}
,"scenario":{"zebos-xp":1}
,"zebos-xp":{"bfd":1}
,"bfd":{"module":1,"server":1,"clients":1,"session":1,"sessions":1,"client-server":1,"client":1}
,"module":{"supports":1}
,"supports":{"bfd":1}
,"scenarios":{"bfd":1}
,"case":{"bfd":1}
,"example":{"bfd":1,"ospfv2":1}
,"process":{"upgraded":1,"bfd":1,"override":1}
,"upgraded":{"bfd":1}
,"clients":{"retry":1,"re-issue":1,"just":1}
,"retry":{"ipc":1}
,"ipc":{"connection":1}
,"connection":{"until":1}
,"until":{"server":1}
,"comes":{"back":1}
,"back":{"accepts":1}
,"accepts":{"connections":1}
,"connections":{"client":1,"established":1}
,"once":{"connections":1}
,"established":{"clients":1}
,"re-issue":{"bfd":1}
,"session":{"requests":1,"client":1}
,"requests":{"server":1}
,"batch":{"process":1}
,"starts":{"maintaining":1}
,"maintaining":{"bfd":1}
,"sessions":{"clients":1,"maintained":1,"overridden":1}
,"just":{"restart":1,"normal":1}
,"took":{"place":1}
,"place":{"bfd":1}
,"client-server":{"restart":1}
,"ospfv2":{"graceful":1}
,"graceful":{"restart":1}
,"supplies":{"restart":1}
,"parameters":{"(such":1}
,"(such":{"grace":1}
,"grace":{"period)":1,"period":1}
,"period)":{"bfd":1}
,"beforehand":{"able":1}
,"able":{"client":1}
,"terminates":{"process":1}
,"maintains":{"bfd":1}
,"occurs":{"just":1}
,"normal":{"start":1}
,"start":{"process":1}
,"override":{"previously":1}
,"previously":{"requested":1}
,"requested":{"sessions":1}
,"maintained":{"server":1}
,"during":{"restart":1}
,"period":{"bfd":1,"expires":1}
,"flushes":{"sessions":1}
,"overridden":{"grace":1}
}
;Search.control.loadWordPairs(pairs);
