var pairs =
{
"rsvp-te":{"graceful":1,"control":1,"reestablishes":1}
,"graceful":{"restart":1}
,"restart":{"rsvp-te":1,"mechanism":1,"control":1,"node":1,"neighboring":1,"capability":1,"time":1,"expects":1,"sender":1,"period":1,"second":1,"during":1,"begins":1,"cannot":1}
,"mechanism":{"helps":1}
,"helps":{"minimize":1}
,"minimize":{"traffic":1}
,"traffic":{"downtime":1,"uninterrupted":1,"(across":1}
,"downtime":{"restart":1}
,"control":{"plane":1}
,"plane":{"forwarding":1,"sender\u2019s":1,"restart":1,"remains":1,"restart)":1,"mpls":1,"ready":1}
,"forwarding":{"state":1,"plane":1}
,"state":{"maintained":1,"valid":1,"lsr":1,"using":1,"established":1,"across":1,"sends":1,"neighbor":1}
,"maintained":{"traffic":1}
,"uninterrupted":{"during":1}
,"during":{"period":1,"phase":1}
,"period":{"restart":1,"rsvp-te":1}
,"node":{"refreshes":1}
,"refreshes":{"rsvp":1}
,"rsvp":{"session":1,"state":1}
,"session":{"states":1}
,"states":{"help":1}
,"help":{"neighboring":1}
,"neighboring":{"lsr":1}
,"lsr":{"forwarding":1,"advertises":1,"continues":1,"detects":1,"retains":1,"restarting":1,"waits":1,"checks":1,"sends":1,"able":1}
,"valid":{"new":1}
,"new":{"resource":1}
,"resource":{"reservations":1}
,"reservations":{"necessary":1}
,"necessary":{"initial":1}
,"initial":{"capability":1}
,"capability":{"exchange":1,"using":1,"preserve":1}
,"exchange":{"first":1}
,"first":{"phase":1}
,"phase":{"rsvp-te":1,"restarting":1,"update":1}
,"advertises":{"graceful":1,"value":1}
,"using":{"restart_cap":1,"preserved":1}
,"restart_cap":{"object":1}
,"object":{"hello":1,"includes":1,"lsr":1}
,"hello":{"messages":1,"communication":1,"message":1}
,"messages":{"restart_cap":1}
,"includes":{"two":1}
,"two":{"parameters":1}
,"parameters":{"restart":1}
,"time":{"recovery":1,"restart":1,"specifies":1,"forwarding":1,"indicates":1,"(zero)":1,"once":1}
,"recovery":{"time":1,"phase":1}
,"specifies":{"duration":1}
,"duration":{"(in":1}
,"(in":{"milliseconds)":1}
,"milliseconds)":{"sender":1}
,"sender":{"expected":1,"advertises":1}
,"expected":{"reestablish":1}
,"reestablish":{"hello":1}
,"communication":{"receiver":1,"neighbors":1,"reestablishment":1,"third":1}
,"receiver":{"restarting":1}
,"restarting":{"rsvp-te":1,"lsr":1,"neighbor":1,"control":1}
,"sender\u2019s":{"control":1}
,"expects":{"indeterminate":1}
,"indeterminate":{"time":1}
,"remains":{"unaffected":1}
,"unaffected":{"across":1}
,"across":{"restart":1,"control-plane":1}
,"value":{"0xffffffff":1,"recovery":1}
,"0xffffffff":{"restart":1}
,"indicates":{"indefinite":1}
,"indefinite":{"restart":1}
,"second":{"phase":1}
,"continues":{"forward":1}
,"forward":{"traffic":1}
,"(across":{"control":1}
,"restart)":{"using":1}
,"preserved":{"mpls":1}
,"mpls":{"forwarding":1}
,"detects":{"neighbor":1}
,"neighbor":{"restarted":1,"previously":1,"addition":1}
,"restarted":{"neighbor":1}
,"previously":{"indicated":1}
,"indicated":{"capability":1}
,"preserve":{"mpls":1,"state":1}
,"retains":{"rsvpte":1}
,"rsvpte":{"control":1}
,"established":{"lsps":1}
,"lsps":{"traverse":1}
,"traverse":{"links":1}
,"links":{"lsr":1}
,"addition":{"lsr":1}
,"waits":{"until":1}
,"until":{"rsvp-te":1}
,"reestablishes":{"hello":1}
,"neighbors":{"reestablishment":1,"restarting":1,"receive":1}
,"reestablishment":{"hello":1}
,"third":{"phase":1}
,"begins":{"restarting":1}
,"ready":{"reestablish":1}
,"checks":{"whether":1}
,"whether":{"able":1}
,"able":{"preserve":1}
,"control-plane":{"restart":1}
,"cannot":{"lsr":1}
,"sends":{"recovery":1,"non-zero":1}
,"(zero)":{"hello":1}
,"message":{"restart_cap":1,"enter":1}
,"non-zero":{"value":1}
,"once":{"neighbors":1}
,"receive":{"hello":1}
,"enter":{"recovery":1}
,"update":{"rsvp":1}
}
;Search.control.loadWordPairs(pairs);
