var pairs =
{
"encapsulating":{"security":1}
,"security":{"payload":1,"(ipsec)":1}
,"payload":{"(esp)":1}
,"(esp)":{"internet":1}
,"internet":{"protocol":1}
,"protocol":{"security":1,"ensures":1}
,"(ipsec)":{"protocol":1}
,"ensures":{"confidentiality":1,"integrity":1}
,"confidentiality":{"encrypting":1}
,"encrypting":{"packets":1}
,"packets":{"encryption":1}
,"encryption":{"algorithm":1}
,"algorithm":{"combines":1,"esp":1}
,"combines":{"data":1}
,"data":{"packet":1}
,"packet":{"key":1,"encrypted":1,"decrypted":1,"using":1}
,"key":{"transform":1}
,"transform":{"packet":1}
,"encrypted":{"form":1}
,"form":{"destination":1}
,"destination":{"packet":1}
,"decrypted":{"using":1}
,"using":{"algorithm":1,"hash":1}
,"esp":{"ensures":1,"supports":1}
,"integrity":{"packet":1}
,"hash":{"message":1}
,"message":{"authentication":1}
,"authentication":{"code":1,"scheme":1,"header":1}
,"code":{"(hmac)":1}
,"(hmac)":{"esp":1}
,"supports":{"authentication":1}
,"scheme":{"used":1}
,"used":{"authentication":1,"conjunction":1}
,"header":{"(ah)":1}
,"(ah)":{"used":1}
}
;Search.control.loadWordPairs(pairs);
