var pairs =
{
"pal_time_strf":{"function":1,"(char":1}
,"function":{"converts":1,"succeeds":1,"fails":1}
,"converts":{"expanded":1}
,"expanded":{"time":1}
,"time":{"string":1}
,"string":{"form":1,"*fmt":1,"return":1}
,"form":{"syntax":1}
,"syntax":{"size_t":1}
,"size_t":{"pal_time_strf":1,"smax":1}
,"(char":{"size_t":1}
,"smax":{"const":1,"maximum":1}
,"const":{"char":1,"struct":1}
,"char":{"*fmt":1}
,"*fmt":{"const":1,"pointer":1}
,"struct":{"pal_tm":1,"output":1}
,"pal_tm":{"*tp)":1}
,"*tp)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"smax":1,"pointer":1}
,"maximum":{"length":1}
,"length":{"string":1}
,"pointer":{"format":1,"struct":1,"put":1}
,"format":{"*tp":1}
,"*tp":{"pointer":1}
,"output":{"parameters":1}
,"put":{"string":1}
,"return":{"values":1}
,"values":{"result_ok":1}
,"result_ok":{"function":1}
,"succeeds":{"error":1}
,"error":{"occurs":1}
,"occurs":{"function":1}
}
;Search.control.loadWordPairs(pairs);
