var pairs =
{
"enable":{"rsvp-te":1,"rsvp":1,"receipt":1,"enable":1,"graceful":1}
,"rsvp-te":{"graceful":1,"process":1}
,"graceful":{"restart":1}
,"restart":{"graceful":1,"supports":1,"capability":1}
,"supports":{"preservation":1}
,"preservation":{"labels":1}
,"labels":{"forwarding":1}
,"forwarding":{"information":1}
,"information":{"rsvp-te":1}
,"process":{"restarts":1}
,"restarts":{"primary":1}
,"primary":{"back-up":1}
,"back-up":{"route":1}
,"route":{"processor":1}
,"processor":{"undergoes":1}
,"undergoes":{"stateful":1}
,"stateful":{"switchover":1}
,"switchover":{"-rsvp-te":1}
,"-rsvp-te":{"configure":1}
,"configure":{"terminal":1,"mode":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"router":1}
,"mode":{"(config)":1,"configure":1,"enable":1}
,"(config)":{"router":1}
,"router":{"rsvp":1,"mode":1,"(config-router)":1}
,"rsvp":{"enter":1,"daemon":1}
,"daemon":{"(config-router)":1}
,"(config-router)":{"neighbor":1,"hello-receipt":1,"graceful-restart":1,"exit":1}
,"neighbor":{"172.16.20.1":1,"exchange":1}
,"172.16.20.1":{"explicitly":1}
,"explicitly":{"specify":1}
,"specify":{"neighbor":1}
,"exchange":{"hello":1}
,"hello":{"messages":1}
,"messages":{"(config-router)":1,"peers":1}
,"hello-receipt":{"enable":1}
,"receipt":{"hello":1}
,"peers":{"(config-router)":1}
,"graceful-restart":{"enable":1}
,"capability":{"router":1}
,"exit":{"exit":1,"router":1}
}
;Search.control.loadWordPairs(pairs);
