var pairs =
{
"trill_api_add_port":{"function":1,"(char*name":1}
,"function":{"adds":1,"call":1}
,"adds":{"port":1}
,"port":{"specified":1}
,"specified":{"bridge":1}
,"bridge":{"instance":1,"*ifname":1}
,"instance":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"trill_api_add_port":1}
,"(char*name":{"char":1}
,"char":{"*ifname)":1}
,"*ifname)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"*name":1,"none":1}
,"*name":{"specifies":1}
,"specifies":{"name":1}
,"name":{"bridge":1,"interface":1}
,"*ifname":{"specifies":1}
,"interface":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"result_ok":1}
,"result_ok":{"indicates":1}
,"indicates":{"function":1,"error":1}
,"call":{"executed":1}
,"executed":{"properly":1}
,"properly":{"result_error":1}
,"result_error":{"indicates":1}
,"error":{"occurred":1}
,"occurred":{"operation":1}
,"operation":{"performed":1}
}
;Search.control.loadWordPairs(pairs);
