var pairs =
{
"pim":{"globals":1,"daemon":1}
,"globals":{"structure":1}
,"structure":{"pim":1,"maintains":1}
,"maintains":{"process-wide":1}
,"process-wide":{"global":1}
,"global":{"variables":1}
,"variables":{"pim":1}
,"daemon":{"process":1}
,"process":{"definition":1}
,"definition":{"struct":1}
,"struct":{"pim_globals":1,"pim4_msdp_globals":1,"pim_mbr":1}
,"pim_globals":{"{u_int32_t":1}
,"{u_int32_t":{"capabilities":1}
,"capabilities":{"define":1}
,"define":{"pim_capability_ipv6":1,"pim_capability_pimsm":1,"pim_capability_pimdm":1,"pim_capability_all":1}
,"pim_capability_ipv6":{"<<0)":1}
,"<<0)":{"define":1}
,"pim_capability_pimsm":{"<<1)":1}
,"<<1)":{"define":1}
,"pim_capability_pimdm":{"<<2)":1}
,"<<2)":{"define":1}
,"pim_capability_all":{"((1":1}
,"((1":{"<<3)":1}
,"<<3)":{"-1)":1}
,"-1)":{"ifdef":1}
,"ifdef":{"have_pim_msdp_api":1,"have_pim_mbr":1}
,"have_pim_msdp_api":{"struct":1}
,"pim4_msdp_globals":{"*msdp":1}
,"*msdp":{"endif":1}
,"endif":{"\u002F*have_pim_msdp_api":1,"\u002F*have_pim_mbr":1}
,"\u002F*have_pim_msdp_api":{"*\u002F#":1}
,"*\u002F#":{"ifdef":1}
,"have_pim_mbr":{"struct":1}
,"pim_mbr":{"*mbr":1}
,"*mbr":{"endif":1}
,"\u002F*have_pim_mbr":{"*\u002F}":1}
}
;Search.control.loadWordPairs(pairs);
