var pairs =
{
"cfm_find_ma_by_isid":{"function":1}
,"function":{"finds":1,"succeeds":1}
,"finds":{"specific":1}
,"specific":{"maintenance":1}
,"maintenance":{"association":1}
,"association":{"syntax":1}
,"syntax":{"include":1}
,"include":{"cfm_pbb_api.h":1}
,"cfm_pbb_api.h":{"struct":1}
,"struct":{"cfm_ma":1}
,"cfm_ma":{"*cfm_find_ma_by_isid":1,"structure":1}
,"*cfm_find_ma_by_isid":{"(struct":1}
,"(struct":{"cfm_md":1}
,"cfm_md":{"*md":1}
,"*md":{"u_int32_t":1}
,"u_int32_t":{"isid)":1}
,"isid)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"name":1,"none":1}
,"name":{"isid":1}
,"isid":{"service":1}
,"service":{"entity":1}
,"entity":{"identifier":1}
,"identifier":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"pointer":1}
,"pointer":{"cfm_ma":1}
,"structure":{"function":1}
,"succeeds":{"null":1}
,"null":{"found":1}
}
;Search.control.loadWordPairs(pairs);
