var pairs =
{
"pim":{"router-id":1,"registers":1,"fall":1,"(vrf":1}
,"router-id":{"command":1,"uniquely":1,"service":1,"received":1,"pim":1,"a.b.c.d":1,"1.1.1.1":1}
,"command":{"configure":1,"override":1,"unconfigure":1,"syntax":1,"mode":1}
,"configure":{"pim":1,"mode":1,"terminal":1}
,"uniquely":{"identify":1}
,"identify":{"router.by":1}
,"router.by":{"default":1}
,"default":{"pim":1}
,"registers":{"nsm":1}
,"nsm":{"router-id":1,"option":1}
,"service":{"command":1}
,"override":{"router-id":1}
,"received":{"nsm":1}
,"option":{"command":1}
,"unconfigure":{"pim":1}
,"fall":{"back":1}
,"back":{"nsm":1}
,"syntax":{"pim":1}
,"(vrf":{"name":1}
,"name":{"router-id":1,"specify":1,"vpn":1}
,"a.b.c.d":{"pim":1,"parameters":1,"specify":1}
,"parameters":{"vrf":1}
,"vrf":{"vpn":1}
,"vpn":{"routing\u002Fforwarding":1}
,"routing\u002Fforwarding":{"instance":1}
,"instance":{"name":1,"a.b.c.d":1}
,"specify":{"name":1,"router":1}
,"router":{"command":1}
,"mode":{"configure":1,"examples":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"pim":1}
,"1.1.1.1":{"(config)":1}
}
;Search.control.loadWordPairs(pairs);
