var pairs =
{
"hal_vlan_set_pro_edge_pvid":{"function":1,"(char":1}
,"function":{"configures":1,"succeeds":1}
,"configures":{"primary":1}
,"primary":{"vid":1}
,"vid":{"(pvid)":1}
,"(pvid)":{"provider":1}
,"provider":{"edge":1}
,"edge":{"port":1}
,"port":{"syntax":1,"pvid":1}
,"syntax":{"int":1}
,"int":{"hal_vlan_set_pro_edge_pvid":1,"ifindex":1}
,"(char":{"*name":1}
,"*name":{"unsigned":1}
,"unsigned":{"int":1,"short":1}
,"ifindex":{"unsigned":1,"interface":1}
,"short":{"svid":1,"pvid)":1}
,"svid":{"unsigned":1,"vlan":1}
,"pvid)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"name":1,"none":1}
,"name":{"bridge":1,"ifindex":1}
,"bridge":{"name":1}
,"interface":{"index":1}
,"index":{"svid":1}
,"vlan":{"provider":1,"used":1}
,"pvid":{"vlan":1}
,"used":{"untagged":1}
,"untagged":{"packets":1}
,"packets":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"hal_err_vlan_port_not_exists":1}
,"hal_err_vlan_port_not_exists":{"hal_err_vlan_not_exists":1}
,"hal_err_vlan_not_exists":{"hal_success":1}
,"hal_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
