var pairs =
{
"virtual-ip":{"command":1,"[a.b.c.d]":1,"parameters":1,"10.10.20.30":1}
,"command":{"virtual":1,"remove":1,"mode":1}
,"virtual":{"address":1,"router":1,"address)":1,"routing":1}
,"address":{"vrrp":1,"used":1,"default":1,"responds":1,"(for":1,"assignment":1,"interface":1,"owner":1}
,"vrrp":{"virtual":1,"owner":1,"eth0":1}
,"router":{"vrrp":1,"mode":1}
,"owner":{"address":1,"virtual":1,"virtual-ip":1,"specify":1,"command":1,"configure":1,"example":1}
,"used":{"end":1}
,"end":{"hosts":1}
,"hosts":{"address":1}
,"default":{"gateway":1}
,"gateway":{"vrrp":1}
,"responds":{"packets":1}
,"packets":{"destined":1}
,"destined":{"virtual":1}
,"(for":{"example":1}
,"example":{"icmp":1,"example":1,"below":1}
,"icmp":{"packets":1}
,"address)":{"parameter":1}
,"parameter":{"command":1}
,"remove":{"virtual":1}
,"assignment":{"syntax":1,"configure":1}
,"syntax":{"description":1}
,"description":{"virtual-ip":1}
,"[a.b.c.d]":{"owner":1}
,"parameters":{"a.b.c.d":1}
,"a.b.c.d":{"specify":1}
,"specify":{"virtual":1,"address":1}
,"interface":{"participates":1}
,"participates":{"virtual":1}
,"routing":{"owner":1}
,"mode":{"router":1,"example":1}
,"below":{"shows":1,"removes":1}
,"shows":{"configure":1}
,"configure":{"router":1,"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"eth0":{"(config-router)":1}
,"(config-router)":{"virtual-ip":1}
,"10.10.20.30":{"owner":1}
,"removes":{"virtual":1}
}
;Search.control.loadWordPairs(pairs);
