var pairs =
{
"rule":{"command":1,"rule":1,"basic":1,"defines":1,"(<1-256>)":1,"number":1,"deny":1,"permit":1}
,"command":{"create":1,"command":1,"group":1,"display":1,"enter":1,"next":1,"remove":1,"syntax":1,"line":1,"separators":1,"mode":1,"show":1}
,"create":{"rule":1,"user-defined":1,"hierarchical":1}
,"basic":{"element":1,"level":1}
,"element":{"role":1}
,"role":{"rule":1,"allows":1,"feature":1,"feature-group":1,"mode":1,"name":1}
,"defines":{"operations":1}
,"operations":{"role":1}
,"allows":{"user":1,"easily":1}
,"user":{"perform":1}
,"perform":{"apply":1}
,"apply":{"rules":1,"function":1}
,"rules":{"following":1,"form":1}
,"following":{"command":1}
,"group":{"commands":1,"default":1,"user-defined":1,"features":1,"create":1,"feature":1,"combines":1,"line":1,"name":1}
,"commands":{"feature":1,"apply":1,"associated":1}
,"feature":{"commands":1,"command":1,"names":1,"group":1,"groups":1,"represents":1,"last":1,"feature":1,"name":1,"mrib6":1}
,"function":{"provided":1}
,"provided":{"device":1}
,"device":{"enter":1}
,"enter":{"show":1}
,"show":{"role":1,"running-config":1}
,"display":{"feature":1,"default":1}
,"names":{"available":1}
,"available":{"feature":1,"parameters":1}
,"default":{"feature":1}
,"user-defined":{"feature":1}
,"features":{"belong":1,"allows":1}
,"belong":{"default":1}
,"groups":{"role":1,"available":1}
,"feature-group":{"group-name":1,"command":1,"feature":1,"ann-arbor":1}
,"group-name":{"command":1}
,"parameters":{"create":1,"<1-256>":1}
,"hierarchical":{"relationship":1}
,"relationship":{"basic":1}
,"level":{"command":1,"feature":1}
,"next":{"level":1}
,"represents":{"commands":1}
,"associated":{"feature":1}
,"last":{"level":1}
,"combines":{"related":1}
,"related":{"features":1}
,"easily":{"manage":1}
,"manage":{"rules":1}
,"form":{"command":1}
,"remove":{"rule":1}
,"syntax":{"rule":1}
,"(<1-256>)":{"(permit":1,"parameters":1}
,"(permit":{"deny)":1}
,"deny)":{"command":1,"(read":1}
,"line":{"rule":1,"command":1,"text":1,"protocols\u002Ffeatures":1,"feature":1}
,"(read":{"read-write)":1}
,"read-write)":{"(feature":1}
,"(feature":{"feature-group)":1}
,"feature-group)":{"line":1}
,"<1-256>":{"rule":1}
,"number":{"permit":1}
,"permit":{"permit":1,"operation":1,"read-write":1,"read":1}
,"operation":{"deny":1,"command":1}
,"deny":{"deny":1,"operation":1,"command":1}
,"text":{"maximum":1}
,"maximum":{"length":1}
,"length":{"128":1}
,"128":{"characters":1}
,"characters":{"spaces":1}
,"spaces":{"semicolon":1}
,"semicolon":{"command":1}
,"separators":{"example":1}
,"example":{"config":1}
,"config":{"int":1}
,"int":{"eth1":1}
,"eth1":{"read":1}
,"read":{"read":1,"access":1,"write":1,"feature-group":1}
,"access":{"read-write":1,"feature":1}
,"read-write":{"read":1,"feature":1}
,"write":{"access":1}
,"name":{"line":1,"command":1,"dearborn":1}
,"protocols\u002Ffeatures":{"below":1}
,"below":{"bgp":1}
,"bgp":{"hostp":1}
,"hostp":{"igmp":1}
,"igmp":{"igmp_if":1}
,"igmp_if":{"isis":1}
,"isis":{"l2mrib":1}
,"l2mrib":{"ldp":1}
,"ldp":{"mld":1}
,"mld":{"mld_if":1}
,"mld_if":{"mrib":1}
,"mrib":{"mrib4":1}
,"mrib4":{"mrib4_if":1}
,"mrib4_if":{"mrib6":1}
,"mrib6":{"mrib6_if":1,"(config-role)":1}
,"mrib6_if":{"mstp":1}
,"mstp":{"ospf":1}
,"ospf":{"ospf6":1}
,"ospf6":{"pim":1}
,"pim":{"rib":1}
,"rib":{"rip":1}
,"rip":{"ripng":1}
,"ripng":{"rstp":1}
,"rstp":{"rvsp":1}
,"rvsp":{"stp":1}
,"stp":{"trill":1}
,"trill":{"vportmgr":1}
,"vportmgr":{"vrrp":1}
,"vrrp":{"feature-group":1}
,"mode":{"role":1,"examples":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"role":1}
,"dearborn":{"(config-role)":1}
,"(config-role)":{"rule":1}
,"running-config":{"(config-role)":1}
}
;Search.control.loadWordPairs(pairs);
