var pairs =
{
"loss-measurement":{"command":1,"(interval":1,"parameters":1,"interval":1}
,"command":{"loss":1,"disable":1,"syntax":1,"mode":1}
,"loss":{"measurement":1}
,"measurement":{"interval":1,"command":1}
,"interval":{"maintenance":1,"milliseconds":1,"(config-ietf-me)":1}
,"maintenance":{"entity":1}
,"entity":{"(me)":1}
,"(me)":{"parameter":1}
,"parameter":{"command":1}
,"disable":{"loss":1}
,"syntax":{"loss-measurement":1}
,"(interval":{"<1-5>":1}
,"<1-5>":{"loss-measurement":1,"loss":1}
,"parameters":{"<1-5>":1}
,"milliseconds":{"100":1,"second":1}
,"100":{"milliseconds":1}
,"second":{"seconds":1}
,"seconds":{"minute":1}
,"minute":{"command":1}
,"mode":{"ietf":1,"examples":1}
,"ietf":{"mode":1,"meg":1}
,"examples":{"(config)":1}
,"(config)":{"ietf":1}
,"meg":{"meg1":1}
,"meg1":{"(config-ietf-meg)":1}
,"(config-ietf-meg)":{"me1":1}
,"me1":{"tunnel":1}
,"tunnel":{"(config-ietf-me)":1,"tun1":1}
,"(config-ietf-me)":{"service":1,"loss-measurement":1}
,"service":{"tunnel":1}
,"tun1":{"(config-ietf-me)":1}
}
;Search.control.loadWordPairs(pairs);
