var pairs =
{
"nsm_api_mpls_tp_tnl_config":{"function":1,"(u_int32_t":1}
,"function":{"creates":1,"called":1,"executed":1}
,"creates":{"ietf":1}
,"ietf":{"mpls-tp":1}
,"mpls-tp":{"tunnel":1,"identifiers":1}
,"tunnel":{"function":1,"source":1,"src_gid":1,"destination":1,"structure":1,"identifier":1}
,"called":{"mpls-tp":1}
,"source":{"destination":1,"global":1,"node":1}
,"destination":{"command":1,"global":1,"node":1,"identifiers":1}
,"command":{"syntax":1}
,"syntax":{"int":1}
,"int":{"nsm_api_mpls_tp_tnl_config":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1}
,"u_int32_t":{"tnl_id":1,"src_gid":1,"src_nid":1,"dst_gid":1,"dst_nid":1}
,"tnl_id":{"u_int32_t":1,"tunnel":1}
,"src_gid":{"u_int32_t":1,"tunnel":1}
,"src_nid":{"u_int32_t":1,"tunnel":1}
,"dst_gid":{"u_int32_t":1,"tunnel":1}
,"dst_nid":{"struct":1,"tunnel":1}
,"struct":{"mpls_tp_tnl":1}
,"mpls_tp_tnl":{"**tnl)":1}
,"**tnl)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"tnl":1}
,"virtual":{"router":1}
,"router":{"(vr)":1,"exist":1}
,"(vr)":{"instance":1}
,"instance":{"tnl_id":1}
,"global":{"src_nid":1,"dst_nid":1}
,"node":{"dst_gid":1,"output":1,"different":1}
,"output":{"parameters":1}
,"tnl":{"mpls-tp":1}
,"structure":{"return":1}
,"return":{"values":1}
,"values":{"nsm_api_set_success":1}
,"nsm_api_set_success":{"function":1}
,"executed":{"properly":1}
,"properly":{"nsm_api_set_error":1}
,"nsm_api_set_error":{"internal":1}
,"internal":{"error":1}
,"error":{"nsm_api_set_err_vr_not_exist":1}
,"nsm_api_set_err_vr_not_exist":{"virtual":1}
,"exist":{"nsm_api_set_err_mpls_tp_id_config_not_exists":1}
,"nsm_api_set_err_mpls_tp_id_config_not_exists":{"mpls-tp":1}
,"identifiers":{"configured":1,"nsm_api_set_err_mpls_tp_tnl_duplicate_tnl_id":1}
,"configured":{"nsm_api_set_err_mpls_tp_tnl_src_dst_same":1}
,"nsm_api_set_err_mpls_tp_tnl_src_dst_same":{"tunnel":1}
,"nsm_api_set_err_mpls_tp_tnl_duplicate_tnl_id":{"tunnel":1}
,"identifier":{"originates":1}
,"originates":{"node":1}
,"different":{"destination":1}
}
;Search.control.loadWordPairs(pairs);
