var pairs =
{
"show":{"protocols":1}
,"protocols":{"command":1,"show":1,"ospf":1,"routing":1}
,"command":{"display":1,"syntax":1,"mode":1,"show":1}
,"display":{"ospf":1}
,"ospf":{"process":1,"parameters":1,"200":1}
,"process":{"parameters":1}
,"parameters":{"statistics":1,"none":1}
,"statistics":{"command":1}
,"syntax":{"show":1}
,"none":{"command":1}
,"mode":{"privileged":1,"usage":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"usage":{"example":1}
,"example":{"output":1}
,"output":{"show":1}
,"routing":{"protocol":1,"networks":1,"information":1}
,"protocol":{"ospf":1}
,"200":{"invalid":1}
,"invalid":{"seconds":1}
,"seconds":{"hold":1}
,"hold":{"down":1}
,"down":{"flushed":1}
,"flushed":{"outgoing":1}
,"outgoing":{"update":1}
,"update":{"filter":1,"distance":1}
,"filter":{"list":1}
,"list":{"interfaces":1}
,"interfaces":{"redistributed":1,"redistributing":1}
,"redistributed":{"kernel":1}
,"kernel":{"filtered":1,"routing":1}
,"filtered":{"filter1":1}
,"filter1":{"incoming":1}
,"incoming":{"update":1}
,"redistributing":{"kernel":1}
,"networks":{"192.30.30.0\u002F24":1}
,"192.30.30.0\u002F24":{"192.40.40.0\u002F24":1}
,"192.40.40.0\u002F24":{"routing":1}
,"information":{"sources":1}
,"sources":{"gatewaydistancelast":1}
,"gatewaydistancelast":{"update":1}
,"distance":{"(default":1}
,"(default":{"110)":1}
,"110)":{"addressmaskdistance":1}
,"addressmaskdistance":{"list":1}
}
;Search.control.loadWordPairs(pairs);
