var pairs =
{
"lsp":{"attributes":1,"egress":1,"tunnel":1,"hop-limit":1,"setup":1,"preempts":1,"already":1,"higher":1,"cannot":1,"session":1,"preempted":1,"value":1,"preempt":1,"attribute":1,"subject":1,"rerouted":1,"connection":1,"case":1,"route":1,"path":1}
,"attributes":{"following":1,"comprise":1,"class":1}
,"following":{"attributes":1}
,"comprise":{"lsp":1}
,"egress":{"address":1,"endpoint":1,"router":1,"routers":1}
,"address":{"specifies":1,"egress":1,"router":1,"ingress":1,"specified":1,"designated":1,"path":1,"signifies":1}
,"specifies":{"address":1,"bandwidth":1,"maximum":1,"resource":1,"routers":1,"lsps":1,"class":1}
,"endpoint":{"lsp":1}
,"tunnel":{"interface":1,"address":1,"end-points":1}
,"interface":{"address":1}
,"router":{"egress":1,"ingress":1,"local":1,"used":1,"address":1,"current":1,"specified":1,"loose":1,"tie-break":1}
,"ingress":{"address":1,"endpoint":1,"egress":1}
,"specified":{"router":1,"color":1}
,"local":{"router":1}
,"used":{"attribute":1,"choose":1}
,"attribute":{"optional":1,"sets":1,"(optional)":1,"determines":1,"disabled":1,"specifies":1,"available":1}
,"optional":{"bandwidth":1,"priority":1,"hold":1,"administrative":1}
,"bandwidth":{"specifies":1,"(in":1,"counted":1}
,"(in":{"bps)":1}
,"bps)":{"lsp":1}
,"hop-limit":{"(optional)":1}
,"(optional)":{"specifies":1,"tie":1}
,"maximum":{"hop":1}
,"hop":{"count":1,"limit":1}
,"count":{"ingress":1,"count":1,"sets":1}
,"routers":{"(including":1,"included":1,"current":1}
,"(including":{"egress)":1}
,"egress)":{"value":1}
,"value":{"ranges":1,"means":1}
,"ranges":{"255":1,"highest":1}
,"255":{"meaning":1,"attribute":1}
,"meaning":{"lsp":1}
,"end-points":{"directly":1}
,"directly":{"connected)":1}
,"connected)":{"default":1}
,"default":{"hop":1,"value":1,"associated":1}
,"limit":{"255":1,"number":1}
,"priority":{"control":1,"sets":1,"preempts":1,"determines":1,"lsp":1,"useful":1,"level":1}
,"control":{"lsp":1,"policies":1}
,"setup":{"pre-emption":1,"priority":1,"attribute":1,"new":1,"lsp":1,"lsps":1,"hold":1}
,"pre-emption":{"infusion":1}
,"infusion":{"recommends":1}
,"recommends":{"two":1}
,"two":{"values":1,"types":1}
,"values":{"setup":1,"0-7":1}
,"sets":{"relative":1,"order":1,"whether":1,"upper":1}
,"relative":{"importance":1}
,"importance":{"lsp":1}
,"order":{"cspf":1}
,"cspf":{"computes":1,"routes":1,"route":1,"computation":1,"makes":1,"path":1,"takes":1}
,"computes":{"paths":1}
,"paths":{"given":1}
,"given":{"lsps":1,"lsp":1}
,"lsps":{"valid":1,"lower":1,"attribute":1,"sharing":1,"setup":1,"consideration":1}
,"valid":{"range":1}
,"range":{"values":1}
,"0-7":{"highest":1}
,"highest":{"priority)":1,"priority":1}
,"priority)":{"sets":1}
,"whether":{"setup":1,"existing":1,"lsp":1}
,"new":{"lsp":1,"resources":1,"route":1}
,"preempts":{"setup":1,"lsps":1}
,"already":{"queue":1}
,"queue":{"lsp":1}
,"higher":{"setup":1}
,"lower":{"priorities":1}
,"priorities":{"default":1,"cspf":1}
,"means":{"lsp":1}
,"cannot":{"preempt":1}
,"preempt":{"setup":1,"lsp":1}
,"hold":{"priority":1,"priorities":1}
,"determines":{"priority":1,"whether":1,"often":1}
,"session":{"holding":1}
,"holding":{"resources":1}
,"resources":{"hold":1,"become":1,"lsp":1,"shared":1}
,"useful":{"deciding":1}
,"deciding":{"whether":1}
,"existing":{"lsp":1}
,"preempted":{"new":1}
,"level":{"default":1}
,"administrative":{"group":1}
,"group":{"(optional)":1}
,"resource":{"class":1,"(link)":1}
,"class":{"filters":1,"(color)":1,"attribute":1,"lsp":1}
,"filters":{"enforce":1,"two":1,"specify":1,"represented":1}
,"enforce":{"admission":1}
,"admission":{"control":1}
,"policies":{"resource":1}
,"(link)":{"assigned":1}
,"assigned":{"class":1}
,"(color)":{"attributes":1}
,"types":{"include":1,"tie-break":1}
,"include":{"filters":1,"computing":1,"exclude)":1}
,"specify":{"groups":1}
,"groups":{"include":1,"exclude":1}
,"computing":{"cspf":1,"desired":1}
,"routes":{"links":1}
,"links":{"match":1,"bandwidth":1,"class":1}
,"match":{"specified":1}
,"color":{"included":1}
,"included":{"path":1,"cspf":1}
,"path":{"computation":1,"attribute":1,"signifies":1,"among":1,"least-filled":1,"most-filled":1,"chosen":1,"(defined":1,"given":1}
,"computation":{"exclude":1,"filters":1,"undertaken":1,"failures":1,"given":1,"desired":1,"ds-te":1}
,"exclude":{"filters":1,"path":1}
,"represented":{"32-bit":1}
,"32-bit":{"vector":1}
,"vector":{"(one":1}
,"(one":{"include":1}
,"exclude)":{"path":1}
,"route":{"computations":1,"lsp":1,"computation":1,"ensures":1}
,"computations":{"router":1}
,"designated":{"either":1}
,"either":{"strict":1}
,"strict":{"loose":1,"address":1}
,"loose":{"strict":1,"address":1}
,"signifies":{"(default)":1,"number":1}
,"(default)":{"router":1}
,"current":{"router":1}
,"number":{"routers":1,"times":1}
,"tie-break":{"method":1,"methods:-least-fill":1}
,"method":{"(optional)":1,"used":1}
,"tie":{"break":1}
,"break":{"method":1}
,"choose":{"path":1}
,"among":{"equal":1}
,"equal":{"cost":1}
,"cost":{"multipaths":1}
,"multipaths":{"three":1}
,"three":{"types":1}
,"methods:-least-fill":{"path":1}
,"least-filled":{"chosen":1}
,"chosen":{"most-fill":1,"random":1}
,"most-fill":{"path":1}
,"most-filled":{"chosen":1}
,"random":{"path":1,"adaptability":1}
,"adaptability":{"attribute":1}
,"subject":{"re-optimization":1}
,"re-optimization":{"change":1,"means":1}
,"change":{"network":1}
,"network":{"conditions":1,"changes":1,"resources":1}
,"conditions":{"i.e":1}
,"i.e":{"new":1}
,"become":{"available":1}
,"available":{"re-optimization":1,"diffserv-te":1}
,"rerouted":{"better":1}
,"better":{"path":1}
,"(defined":{"established":1}
,"established":{"criteria)":1}
,"criteria)":{"case":1}
,"case":{"network":1,"route":1}
,"changes":{"attribute":1}
,"disabled":{"default":1}
,"associated":{"reoptimization":1}
,"reoptimization":{"timer":1}
,"timer":{"determines":1,"timer":1}
,"often":{"cspf":1}
,"undertaken":{"discover":1}
,"discover":{"new":1}
,"connection":{"retry":1}
,"retry":{"timer":1,"count":1}
,"makes":{"attempt":1}
,"attempt":{"compute":1}
,"compute":{"path":1}
,"failures":{"lsp":1,"shared":1}
,"upper":{"limit":1}
,"times":{"cspf":1}
,"shared":{"lsp":1,"links":1}
,"sharing":{"resources":1}
,"desired":{"lsps":1,"route":1,"feature":1}
,"takes":{"lsps":1}
,"consideration":{"computing":1}
,"ensures":{"shared":1}
,"counted":{"twice":1}
,"twice":{"helps":1}
,"helps":{"conservation":1}
,"conservation":{"network":1}
,"diffserv-te":{"feature":1}
,"feature":{"enabled":1,"present":1}
,"enabled":{"specifies":1,"routers":1}
,"present":{"successful":1}
,"successful":{"route":1}
,"ds-te":{"enabled":1}
}
;Search.control.loadWordPairs(pairs);
