var pairs =
{
"cfm_pbb_te_send_traceroute":{"function":1}
,"function":{"sends":1,"succeeds":1,"fails":1}
,"sends":{"traceroute":1}
,"traceroute":{"message":1}
,"message":{"pbb-te":1}
,"pbb-te":{"mep":1}
,"mep":{"te-sid":1,"mip":1}
,"te-sid":{"reverse":1}
,"reverse":{"vlan":1}
,"vlan":{"used":1,"send":1}
,"used":{"remote":1}
,"remote":{"mep":1}
,"mip":{"returned":1}
,"returned":{"syntax":1}
,"syntax":{"struct":1}
,"struct":{"cfm_lt":1}
,"cfm_lt":{"*cfm_pbb_te_send_traceroute":1,"structure":1}
,"*cfm_pbb_te_send_traceroute":{"(struct":1}
,"(struct":{"onmd_bridge":1}
,"onmd_bridge":{"*bridge":1}
,"*bridge":{"u_int8_t":1}
,"u_int8_t":{"*mac":1,"*md_name":1}
,"*mac":{"u_int8_t":1}
,"*md_name":{"u_int32_t":1}
,"u_int32_t":{"te_sid":1}
,"te_sid":{"u_int16_t":1,"service":1}
,"u_int16_t":{"reverse_vid)":1}
,"reverse_vid)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bridge":1}
,"bridge":{"identity":1,"mac":1,"te_sid":1}
,"identity":{"bridge":1}
,"mac":{"mac":1,"address":1}
,"address":{"md_name":1}
,"md_name":{"maintenance":1}
,"maintenance":{"domain":1}
,"domain":{"name":1}
,"name":{"bridge":1}
,"service":{"instance":1}
,"instance":{"<1-42949675>":1}
,"<1-42949675>":{"reverse_vid":1}
,"reverse_vid":{"vlan":1}
,"send":{"response":1}
,"response":{"return":1}
,"return":{"values":1}
,"values":{"pointer":1}
,"pointer":{"cfm_lt":1}
,"structure":{"function":1}
,"succeeds":{"null":1}
,"null":{"function":1}
}
;Search.control.loadWordPairs(pairs);
