var pairs =
{
"nsm_ipv4_if_bfd_static_set":{"function":1,"(u_int32_t":1}
,"function":{"configures":1,"succeeds":1}
,"configures":{"bfd":1}
,"bfd":{"static":1}
,"static":{"route":1}
,"route":{"support":1}
,"support":{"interface":1}
,"interface":{"address":1,"output":1,"exist":1,"associated":1,"nsm_api_set_err_static_bfd_set":1}
,"address":{"family":1}
,"family":{"ipv4":1}
,"ipv4":{"given":1}
,"given":{"syntax":1,"interface":1}
,"syntax":{"int":1}
,"int":{"nsm_ipv4_if_bfd_static_set":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1}
,"char":{"*ifname)":1}
,"*ifname)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1,"routing\u002Fforwarding":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"parameter":1}
,"parameter":{"ifname":1}
,"ifname":{"name":1}
,"name":{"interface":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_api_set_error":1}
,"nsm_api_set_error":{"generic":1}
,"generic":{"error":1}
,"error":{"occurs":1}
,"occurs":{"nsm_api_set_err_vr_not_exist":1}
,"nsm_api_set_err_vr_not_exist":{"exist":1}
,"exist":{"nsm_api_set_err_if_not_exist":1,"nsm":1,"nsm_api_set_success":1}
,"nsm_api_set_err_if_not_exist":{"given":1}
,"nsm":{"interface":1}
,"associated":{"given":1}
,"nsm_api_set_err_static_bfd_set":{"requested":1}
,"requested":{"setting":1}
,"setting":{"already":1}
,"already":{"nsm_api_set_err_vrf_not_exist":1}
,"nsm_api_set_err_vrf_not_exist":{"virtual":1}
,"routing\u002Fforwarding":{"instances":1}
,"instances":{"exist":1}
,"nsm_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
