var pairs =
{
"zebos3":{"(ordinary":1}
,"(ordinary":{"clock)":1}
,"clock)":{"configure":1}
,"configure":{"terminal":1,"mode":1,"ptp":1,"interface":1,"eth2":1}
,"terminal":{"enter":1}
,"enter":{"configure":1}
,"mode":{"(config)":1}
,"(config)":{"bridge":1,"ptp-clk":1,"interface":1}
,"bridge":{"protocol":1,"mstp":1,"(this":1,"group":1}
,"protocol":{"mstp":1}
,"mstp":{"create":1,"bridge":1}
,"create":{"bridge":1}
,"(this":{"step":1}
,"step":{"mandatory":1}
,"mandatory":{"good":1}
,"good":{"practice":1}
,"practice":{"avoid":1}
,"avoid":{"layer":1}
,"layer":{"loops)":1,"port":1}
,"loops)":{"(config)":1}
,"ptp-clk":{"ordinary":1}
,"ordinary":{"transport-type":1,"clock":1}
,"transport-type":{"ethernet":1}
,"ethernet":{"delay-mechanism":1,"(config-ptp-clk)":1}
,"delay-mechanism":{"p2p":1}
,"p2p":{"configure":1}
,"ptp":{"ordinary":1,"configure":1}
,"clock":{"ethernet":1,"port":1}
,"(config-ptp-clk)":{"exit":1}
,"exit":{"exit":1,"ptp":1,"port":1}
,"interface":{"eth2":1}
,"eth2":{"configure":1,"(config-if)":1,"layer":1,"bridge":1,"clock":1}
,"(config-if)":{"switchport":1,"bridge-group":1,"clock-port":1}
,"switchport":{"configure":1}
,"port":{"(config-if)":1,"(config-clk-port)":1,"configure":1}
,"bridge-group":{"configure":1}
,"group":{"(config-if)":1}
,"clock-port":{"configure":1}
,"(config-clk-port)":{"exit":1}
}
;Search.control.loadWordPairs(pairs);
