var pairs =
{
"features":{"stateful":1}
,"stateful":{"recovery":1}
,"recovery":{"stateful":1,"refers":1}
,"refers":{"process":1}
,"process":{"active\u002Fstandby":1,"active":1}
,"active\u002Fstandby":{"controllers":1}
,"controllers":{"running":1,"synchronize":1,"assumes":1,"possible":1,"becomes":1,"active":1,"connected":1}
,"running":{"synchronized":1,"active":1}
,"synchronized":{"mode":1,"active":1,"standby":1}
,"mode":{"respect":1,"active\u002Fstandby":1}
,"respect":{"state":1}
,"state":{"information":1,"nodes":1,"active":1}
,"information":{"redundant":1,"graceful":1,"routing":1}
,"redundant":{"node":1,"physical":1,"link":1}
,"node":{"hot-standby":1,"hides":1,"recovers":1,"saved":1,"(in":1,"required":1,"continuously":1,"amf":1,"become":1}
,"hot-standby":{"mode":1}
,"synchronize":{"configuration":1,"without":1}
,"configuration":{"dynamic":1,"checkpointing":1}
,"dynamic":{"protocol":1}
,"protocol":{"state":1,"dependent":1,"separately":1}
,"graceful":{"restart":1}
,"restart":{"control":1,"due":1,"graceful":1,"rebuild":1,"separate":1,"protocol":1}
,"control":{"plane":1,"data":1}
,"plane":{"restarts":1,"recovered":1,"control":1,"fails":1,"keeps":1}
,"restarts":{"disrupt":1}
,"disrupt":{"data":1}
,"data":{"forwarding":1,"plane":1,"neighbors":1,"states":1}
,"forwarding":{"following":1,"information":1,"data":1}
,"following":{"cases":1}
,"cases":{"due":1}
,"due":{"software":1}
,"software":{"upgrades":1,"bugs":1,"upgrade":1}
,"upgrades":{"planned":1}
,"planned":{"restart":1,"upgrade\u002Fmaintenance":1}
,"bugs":{"unplanned":1}
,"unplanned":{"restart":1}
,"rebuild":{"forwarding":1}
,"routing":{"protocols":1}
,"protocols":{"control":1,"running":1}
,"recovered":{"failure":1}
,"failure":{"steps":1,"nodes":1,"handling":1}
,"steps":{"graceful":1}
,"separate":{"control":1}
,"fails":{"data":1}
,"keeps":{"forwarding":1,"monitoring":1}
,"neighbors":{"restarting":1,"synchronize":1}
,"restarting":{"node":1,"active":1}
,"hides":{"failure":1}
,"nodes":{"node":1,"using":1}
,"recovers":{"neighbors":1}
,"without":{"disrupting":1}
,"disrupting":{"service":1}
,"service":{"graceful":1}
,"dependent":{"means":1}
,"means":{"handled":1}
,"handled":{"protocol":1}
,"separately":{"configuration":1}
,"checkpointing":{"configurations":1}
,"configurations":{"applied":1,"cdb":1,"standby":1}
,"applied":{"successfully":1}
,"successfully":{"active":1}
,"active":{"node":1,"heart-beat":1,"role":1,"standby":1,"controller":1,"split-brain":1,"heart":1}
,"saved":{"check-pointed":1,"configurations":1}
,"check-pointed":{"standby":1}
,"standby":{"node":1,"synchronized":1,"manually":1,"role":1,"controllers":1,"continues":1,"controller":1}
,"cdb":{"used":1}
,"used":{"time":1,"facilitate":1}
,"time":{"restarting":1}
,"(in":{"case":1}
,"case":{"simplex":1,"redundancy":1,"heart-beat":1}
,"simplex":{"mode)":1}
,"mode)":{"check":1,"planned":1}
,"check":{"pointed":1}
,"pointed":{"commands":1}
,"commands":{"keep":1}
,"keep":{"configurations":1}
,"redundancy":{"mode)":1,"model":1,"state":1,"available":1}
,"upgrade\u002Fmaintenance":{"software":1}
,"upgrade":{"manual":1}
,"manual":{"switch-over":1}
,"switch-over":{"used":1}
,"facilitate":{"process":1}
,"required":{"upgraded":1}
,"upgraded":{"made":1,"switched":1}
,"made":{"standby":1}
,"manually":{"upgraded":1}
,"switched":{"back":1}
,"back":{"active":1}
,"heart-beat":{"failure":1,"mechanism":1,"messages":1}
,"handling":{"zebha":1,"solution":1}
,"zebha":{"deployed":1,"need":1}
,"deployed":{"active-standby":1}
,"active-standby":{"redundancy":1}
,"model":{"controllers":1}
,"assumes":{"active":1,"standby":1,"fault":1}
,"role":{"assumes":1,"internal":1}
,"internal":{"data":1}
,"states":{"zebos-xp":1}
,"zebos-xp":{"protocols":1}
,"continuously":{"synchronized":1}
,"amf":{"keeps":1}
,"monitoring":{"redundancy":1}
,"using":{"heart-beat":1}
,"mechanism":{"active":1,"handle":1}
,"possible":{"physical":1}
,"physical":{"link":1,"links":1}
,"link":{"heart-beat":1,"arise":1,"redundancy":1}
,"messages":{"exchanged":1,"cannot":1}
,"exchanged":{"active":1,"controllers":1,"redundant":1}
,"becomes":{"faulty":1}
,"faulty":{"case":1,"therefore":1,"heart-beat":1}
,"cannot":{"exchanged":1}
,"controller":{"assumes":1}
,"fault":{"occurred":1}
,"occurred":{"standby":1}
,"continues":{"active":1}
,"become":{"faulty":1}
,"therefore":{"changes":1}
,"changes":{"state":1}
,"split-brain":{"situation":1}
,"situation":{"desirable":1,"even":1,"wherein":1}
,"desirable":{"normally":1}
,"normally":{"chassis":1}
,"chassis":{"architecture":1}
,"architecture":{"controllers":1}
,"connected":{"via":1}
,"via":{"backplane":1}
,"backplane":{"redundant":1}
,"links":{"supported":1,"becomes":1}
,"supported":{"hardware":1}
,"hardware":{"platform":1}
,"platform":{"zebha":1}
,"need":{"deploy":1}
,"deploy":{"additional":1}
,"additional":{"mechanism":1}
,"handle":{"above":1}
,"above":{"situation":1}
,"even":{"links":1}
,"arise":{"situation":1}
,"wherein":{"controllers":1}
,"heart":{"beat":1}
,"beat":{"failure":1}
,"solution":{"proposed":1}
,"proposed":{"deployments":1}
,"deployments":{"physical":1}
,"available":{"hardware":1}
}
;Search.control.loadWordPairs(pairs);
