var pairs =
{
"secondary":{"label-record":1}
,"label-record":{"command":1,"secondary":1}
,"command":{"record":1,"records":1,"syntax":1,"mode":1}
,"record":{"labels":1}
,"labels":{"exchanged":1}
,"exchanged":{"rsvp":1,"lsp":1}
,"rsvp":{"enabled":1}
,"enabled":{"routers":1}
,"routers":{"during":1}
,"during":{"reservation":1}
,"reservation":{"setup":1}
,"setup":{"process":1}
,"process":{"command":1}
,"records":{"labels":1}
,"lsp":{"ingress":1}
,"ingress":{"egress":1}
,"egress":{"helps":1}
,"helps":{"debugging":1}
,"debugging":{"parameter":1}
,"parameter":{"turn":1}
,"turn":{"recording":1}
,"recording":{"command":1}
,"syntax":{"secondary":1}
,"mode":{"trunk":1,"examples":1}
,"trunk":{"mode":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"rsvp-trunk":1}
,"rsvp-trunk":{"mytrunk":1}
,"mytrunk":{"(config-trunk)":1}
,"(config-trunk)":{"secondary":1}
}
;Search.control.loadWordPairs(pairs);
