var pairs =
{
"international":{"organization":1,"standards":1}
,"organization":{"standardization":1,"international":1}
,"standardization":{"(iso)":1,"different":1}
,"(iso)":{"international":1}
,"standards":{"body":1,"communications":1,"bodies":1,"institute":1,"organization":1}
,"body":{"establishes":1}
,"establishes":{"global":1}
,"global":{"standards":1}
,"communications":{"information":1}
,"information":{"exchange":1}
,"exchange":{"voting":1}
,"voting":{"members":1}
,"members":{"designated":1}
,"designated":{"standards":1}
,"bodies":{"participating":1}
,"participating":{"nations":1}
,"nations":{"american":1}
,"american":{"national":1}
,"national":{"standards":1}
,"institute":{"(ansi)":1}
,"(ansi)":{"u.s":1}
,"u.s":{"member":1}
,"member":{"iso":1}
,"iso":{"open":1,"iso":1,"derived":1}
,"open":{"systems":1}
,"systems":{"interconnection":1}
,"interconnection":{"(osi)":1}
,"(osi)":{"reference":1}
,"reference":{"model":1}
,"model":{"iso\u2019s":1}
,"iso\u2019s":{"widely":1}
,"widely":{"accepted":1}
,"accepted":{"recommendations":1}
,"recommendations":{"sometimes":1}
,"sometimes":{"mistakenly":1}
,"mistakenly":{"referred":1}
,"referred":{"international":1}
,"different":{"acronyms":1,"languages":1}
,"acronyms":{"different":1}
,"languages":{"(ios":1}
,"(ios":{"english":1}
,"english":{"oin":1}
,"oin":{"french":1}
,"french":{"organisation":1}
,"organisation":{"internationale":1}
,"internationale":{"normalisation)":1}
,"normalisation)":{"founders":1}
,"founders":{"gave":1}
,"gave":{"short":1}
,"short":{"form":1}
,"form":{"iso":1}
,"derived":{"greek":1}
,"greek":{"isos":1}
,"isos":{"meaning":1}
,"meaning":{"equal":1}
,"equal":{"http:\u002F\u002Fwww.iso.org\u002Fiso\u002Fhome.html":1}
}
;Search.control.loadWordPairs(pairs);
