var pairs =
{
"compile":{"zebos-xp":1,"available":1,"specific":1}
,"zebos-xp":{"configuring":1,"change":1,"source":1,"modules":1}
,"configuring":{"build":1}
,"build":{"environment":1,"likewise":1}
,"environment":{"compile":1}
,"change":{"directory":1}
,"directory":{"containing":1,"all-lib":1,"nsm":1}
,"containing":{"zebos-xp":1}
,"source":{"code":1}
,"code":{"platform\u002Flinux":1}
,"platform\u002Flinux":{"run":1}
,"run":{"clean":1,"utility":1,"compile":1,"install":1,"all-mpls":1,"all-layer2":1}
,"clean":{"utility":1,"run":1,"cleans":1}
,"utility":{"clean":1,"run":1}
,"available":{"modules":1,"targets":1}
,"modules":{"just":1,"selected":1,"install":1,"daemons":1,"run":1,"need":1,"command":1,"applies":1,"dep":1,"forcedep":1,"clean":1,"<protocol>":1,"authd":1}
,"just":{"compile":1}
,"specific":{"protocols":1}
,"protocols":{"specifying":1}
,"specifying":{"protocol":1}
,"protocol":{"name":1,"daemon":1}
,"name":{"note":1}
,"note":{"install":1}
,"install":{"implies":1,"makes":1,"command":1}
,"implies":{"example":1}
,"example":{"<protocol>":1,"all-pal":1}
,"<protocol>":{"makes":1,"bgpd":1}
,"makes":{"modules":1,"bgp":1,"pal-related":1,"library":1,"nsm":1,"installs":1,"available":1,"dependencies":1,"protocol":1}
,"selected":{"<protocol>":1}
,"bgpd":{"makes":1,"elmid":1}
,"bgp":{"modules":1}
,"daemons":{"choose":1}
,"choose":{"individual":1}
,"individual":{"modules":1,"targets":1}
,"command":{"need":1,"build":1,"displays":1}
,"need":{"mpls":1,"layer":1}
,"mpls":{"forwarder":1}
,"forwarder":{"run":1}
,"all-mpls":{"command":1}
,"likewise":{"choose":1}
,"layer":{"support":1}
,"support":{"run":1,"modules":1}
,"all-layer2":{"layer":1}
,"displays":{"available":1}
,"targets":{"individual":1,"separate":1,"function":1}
,"separate":{"directories":1}
,"directories":{"entering":1}
,"entering":{"target-directory":1}
,"target-directory":{"example":1}
,"all-pal":{"makes":1}
,"pal-related":{"files":1}
,"files":{"pal":1,"lib":1,"distribution":1}
,"pal":{"target":1}
,"target":{"directory":1}
,"all-lib":{"makes":1}
,"library":{"files":1}
,"lib":{"directory":1}
,"nsm":{"makes":1,"daemon":1,"oamd":1}
,"daemon":{"table":1,"(s)":1}
,"table":{"1-7":1}
,"1-7":{"lists":1}
,"lists":{"makefile":1}
,"makefile":{"commands":1}
,"commands":{"application":1,"targets":1}
,"application":{"makefile":1}
,"function":{"comments":1}
,"comments":{"distclean":1}
,"distclean":{"removes":1}
,"removes":{"working":1}
,"working":{"files":1}
,"distribution":{"applies":1}
,"applies":{"top":1}
,"top":{"level":1}
,"level":{"install":1,"makes":1,"available":1}
,"installs":{"binaries":1}
,"binaries":{"samples":1}
,"samples":{"applies":1}
,"dep":{"makes":1}
,"dependencies":{"applies":1,"remade":1}
,"forcedep":{"forces":1}
,"forces":{"dependencies":1}
,"remade":{"applies":1}
,"cleans":{"previous":1}
,"previous":{"applies":1}
,"(s)":{"zebos-xp":1}
,"authd":{"bgpd":1}
,"elmid":{"gvrpd":1}
,"gvrpd":{"isisd":1}
,"isisd":{"isis6d":1}
,"isis6d":{"lagd":1}
,"lagd":{"ldpd":1}
,"ldpd":{"lmpd":1}
,"lmpd":{"mstpd":1}
,"mstpd":{"nsm":1}
,"oamd":{"onmd":1}
,"onmd":{"ospfd":1}
,"ospfd":{"ospf6d":1}
,"ospf6d":{"pimd":1}
,"pimd":{"pim6d":1}
,"pim6d":{"ripd":1}
,"ripd":{"ripngd":1}
,"ripngd":{"rstpd":1}
,"rstpd":{"rsvpd":1}
,"rsvpd":{"stpd":1}
}
;Search.control.loadWordPairs(pairs);
