var pairs =
{
"configuring":{"ets":1}
,"ets":{"parameter":1,"bridge":1}
,"parameter":{"exchange":1}
,"exchange":{"zebos1":1}
,"zebos1":{"configure":1}
,"configure":{"terminal":1,"mode":1,"interface":1,"eth1":1,"lldp":1,"advertise":1,"tcg":1,"bandwidth":1}
,"terminal":{"enter":1}
,"enter":{"configure":1}
,"mode":{"(config)":1,"eth1":1,"configure":1}
,"(config)":{"bridge":1,"data-center-bridging":1,"enhanced-transmission-selection":1,"interface":1}
,"bridge":{"protocol":1,"ieee":1,"(config)":1,"enable":1,"group":1}
,"protocol":{"ieee":1}
,"ieee":{"vlan-bridge":1,"vlan-enabled":1,"802.1":1}
,"vlan-bridge":{"create":1}
,"create":{"bridge":1}
,"vlan-enabled":{"bridge":1}
,"data-center-bridging":{"enable":1}
,"enable":{"bridge":1,"dcb":1,"ets":1,"txrx":1}
,"dcb":{"bridge":1}
,"enhanced-transmission-selection":{"enable":1,"mode":1}
,"interface":{"eth1":1}
,"eth1":{"configure":1,"(config-if)":1,"layer":1,"bridge":1}
,"(config-if)":{"switchport":1,"bridge-group":1,"lldp":1,"enhanced-transmission-selection":1,"traffic-class-group":1,"bandwidth-percentage":1}
,"switchport":{"configure":1}
,"layer":{"port":1}
,"port":{"(config-if)":1}
,"bridge-group":{"configure":1}
,"group":{"(config-if)":1}
,"lldp":{"enable":1,"transmit":1,"tlv":1,"send":1,"messages":1}
,"txrx":{"configure":1}
,"transmit":{"receive":1}
,"receive":{"mode":1}
,"tlv":{"ieee-8021-org-specific":1,"packet":1}
,"ieee-8021-org-specific":{"configure":1}
,"send":{"ieee":1}
,"802.1":{"organizationally":1}
,"organizationally":{"specific":1}
,"specific":{"tlv":1}
,"packet":{"(config-if)":1}
,"advertise":{"flag":1}
,"flag":{"start":1}
,"start":{"sending":1}
,"sending":{"dcbx":1}
,"dcbx":{"tlvs":1}
,"tlvs":{"lldp":1}
,"messages":{"(config-if)":1}
,"traffic-class-group":{"add":1}
,"add":{"priority":1,"priorities":1}
,"priority":{"configure":1}
,"tcg":{"add":1}
,"priorities":{"(config-if)":1}
,"bandwidth-percentage":{"configure":1}
,"bandwidth":{"percentage":1}
,"percentage":{"tcg":1}
}
;Search.control.loadWordPairs(pairs);
