var pairs =
{
"ldp_api_getnext_interface_by_label_space":{"call":1}
,"call":{"returns":1}
,"returns":{"interface":1}
,"interface":{"label-space":1,"*ldp_api_getnext_interface_by_label_space":1,"minimal":1,"null":1}
,"label-space":{"next":1,"syntax":1,"first":1,"interface":1,"greater":1}
,"next":{"given":1}
,"given":{"label-space":1}
,"syntax":{"struct":1}
,"struct":{"interface":1}
,"*ldp_api_getnext_interface_by_label_space":{"(int":1}
,"(int":{"label_space":1}
,"label_space":{"int":1,"label-space":1,"output":1}
,"int":{"first)":1}
,"first)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"label_space":1,"none":1}
,"first":{"boolean":1}
,"boolean":{"value":1}
,"value":{"designating":1,"pointer":1}
,"designating":{"whether":1}
,"whether":{"return":1}
,"return":{"interface":1,"value":1}
,"minimal":{"label-space":1}
,"greater":{"label_space":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"pointer":{"requested":1}
,"requested":{"interface":1}
,"null":{"none":1}
}
;Search.control.loadWordPairs(pairs);
