var pairs =
{
"validation":{"following":1}
,"following":{"show":1,"ping":1,"0002.a5e0.9563":1}
,"show":{"command":1,"ethernet":1}
,"command":{"dut-5":1,"displays":1,"dut-1":1}
,"dut-5":{"displays":1,"show":1,"ping":1}
,"displays":{"information":1,"loopback":1,"detailed":1}
,"information":{"maintenance":1,"configured":1,"domain":1}
,"maintenance":{"points":1,"level":1}
,"points":{"domain":1}
,"domain":{"named":1,"including":1,"type":1}
,"named":{"abc":1}
,"abc":{"associated":1,"isid":1,"bridge":1,"mep":1}
,"associated":{"i-sid":1}
,"i-sid":{"bridge":1}
,"bridge":{"maintenance":1,"mpid":1,"host":1}
,"level":{"dut-5":1,"isid":1,"interface":1,"type":1}
,"ethernet":{"cfm":1,"pbb":1}
,"cfm":{"pbb":1}
,"pbb":{"maintenance-points":1,"multicast":1}
,"maintenance-points":{"remote":1,"local":1}
,"remote":{"domain-name":1,"mac":1}
,"domain-name":{"abc":1}
,"isid":{"bridge":1,"mep-up":1,"tlv":1,"topo-type":1}
,"mpid":{"level":1,"domain_name":1}
,"mep-up":{"remote":1}
,"mac":{"----------------------------------------------------------------3":1,"address":1}
,"----------------------------------------------------------------3":{"0002.a5e0.9563":1}
,"0002.a5e0.9563":{"following":1,"success":1}
,"ping":{"command":1,"ethernet":1}
,"loopback":{"test":1}
,"test":{"information":1}
,"configured":{"elements":1}
,"elements":{"dut-5":1}
,"multicast":{"mepid":1}
,"mepid":{"domain-name":1}
,"tlv":{"data":1}
,"data":{"bridge":1}
,"host":{"mep":1}
,"mep":{"number":1,"domain-name":1,"service":1}
,"number":{"rmeps":1}
,"rmeps":{"replied":1}
,"replied":{"mcast":1}
,"mcast":{"frame":1}
,"frame":{"lbr":1}
,"lbr":{"received":1}
,"received":{"following":1}
,"success":{"rate":1}
,"rate":{"100":1}
,"100":{"(1\u002F1)":1}
,"(1\u002F1)":{"following":1}
,"dut-1":{"displays":1,"show":1}
,"detailed":{"information":1}
,"including":{"maintenance":1}
,"interface":{"type":1}
,"type":{"domain":1,"vlan":1,"domain-type":1}
,"vlan":{"service":1,"isid":1}
,"service":{"instance":1,"default":1}
,"instance":{"topology":1}
,"topology":{"port":1}
,"port":{"continuity":1,"cc-status":1}
,"continuity":{"check":1}
,"check":{"status":1}
,"status":{"mac":1}
,"address":{"dut-1":1}
,"local":{"mep":1}
,"domain_name":{"level":1}
,"domain-type":{"vlan":1}
,"topo-type":{"port":1}
,"cc-status":{"mac-address":1}
,"mac-address":{"--------------------------------------------------------------------------------------23":1}
,"--------------------------------------------------------------------------------------23":{"abc":1}
,"default":{"eth1":1}
,"eth1":{"enabled":1}
,"enabled":{"0002.b3d4.3f25":1}
}
;Search.control.loadWordPairs(pairs);
