var pairs =
{
"elmi_clear_statistics_interface":{"api":1,"(struct":1}
,"api":{"used":1,"call":1}
,"used":{"clear":1}
,"clear":{"elmi":1,"ethernet":1}
,"elmi":{"statistics":1}
,"statistics":{"information":1,"interface":1}
,"information":{"per":1}
,"per":{"interface":1}
,"interface":{"cli":1,"ifname":1}
,"cli":{"command":1,"*cli":1}
,"command":{"clear":1}
,"ethernet":{"lmi":1}
,"lmi":{"statistics":1}
,"ifname":{"api":1}
,"call":{"int":1}
,"int":{"elmi_clear_statistics_interface":1}
,"(struct":{"cli":1}
,"*cli":{"struct":1}
,"struct":{"elmi_ifp":1}
,"elmi_ifp":{"*elmi_if)":1}
,"*elmi_if)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"none":1}
,"none":{"output":1}
,"output":{"parameters":1}
}
;Search.control.loadWordPairs(pairs);
