var pairs =
{
"ethernet":{"cfm":1}
,"cfm":{"dvm":1}
,"dvm":{"mepid":1}
,"mepid":{"command":1,"mepid":1,"(unicast":1,"specify":1,"remote":1,"multicast":1}
,"command":{"configure":1,"syntax":1,"mode":1}
,"configure":{"delay":1}
,"delay":{"variation":1,"measurement":1}
,"variation":{"measurement":1}
,"measurement":{"(dvm)":1,"unicast":1,"rmpid":1,"duration":1}
,"(dvm)":{"host":1}
,"host":{"mep":1}
,"mep":{"command":1,"multicast":1,"duration":1}
,"syntax":{"ethernet":1}
,"(unicast":{"(rmpid":1}
,"(rmpid":{"mepid)":1}
,"mepid)":{"multicast)":1}
,"multicast)":{"duration":1}
,"duration":{"duration":1,"domain":1,"specify":1,"<5-60>":1}
,"domain":{"domain_name":1,"specify":1,"name":1,"new":1}
,"domain_name":{"(vlan":1}
,"(vlan":{"vlan_id":1}
,"vlan_id":{"((interval":1}
,"((interval":{"4))":1}
,"4))":{"(bridge":1}
,"(bridge":{"<1-32>":1}
,"<1-32>":{"parameters":1,"interval":1}
,"parameters":{"mepid":1}
,"specify":{"host":1,"multicast":1,"unicast":1,"mepid":1,"integer":1,"maintenance":1,"bridge":1,"dmm":1,"transmission":1,"primary-vid":1}
,"multicast":{"specify":1,"delay":1,"duration":1}
,"unicast":{"specify":1,"delay":1}
,"rmpid":{"specify":1}
,"remote":{"mep":1}
,"integer":{"sets":1}
,"sets":{"delay":1}
,"<5-60>":{"domain":1}
,"maintenance":{"domain":1}
,"name":{"bridge":1}
,"bridge":{"specify":1,"<1-32>":1}
,"interval":{"specify":1,"<100":1,"<10":1,"second>":1}
,"dmm":{"transmission":1}
,"transmission":{"interval":1}
,"<100":{"ms>":1}
,"ms>":{"specify":1}
,"<10":{"ms>":1,"seconds>":1}
,"second>":{"specify":1}
,"seconds>":{"vlan":1}
,"vlan":{"specify":1}
,"primary-vid":{"command":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"ethernet":1}
,"new":{"interval":1}
}
;Search.control.loadWordPairs(pairs);
