var pairs =
{
"overview":{"oam":1}
,"oam":{"(operations":1,"mpls-tp":1,"functions":1}
,"(operations":{"administration":1}
,"administration":{"maintenance)":1}
,"maintenance)":{"plays":1}
,"plays":{"significant":1}
,"significant":{"role":1}
,"role":{"providing":1}
,"providing":{"methods":1}
,"methods":{"fault":1}
,"fault":{"management":1,"indication":1}
,"management":{"performance":1}
,"performance":{"monitoring":1}
,"monitoring":{"transport":1,"capabilities":1}
,"transport":{"service":1,"profile":1}
,"service":{"layers":1,"level":1}
,"layers":{"order":1}
,"order":{"improve":1}
,"improve":{"ability":1}
,"ability":{"support":1}
,"support":{"services":1}
,"services":{"guaranteed":1}
,"guaranteed":{"strict":1}
,"strict":{"service":1}
,"level":{"agreements":1}
,"agreements":{"(sla)":1}
,"(sla)":{"reducing":1}
,"reducing":{"operational":1}
,"operational":{"costs":1}
,"costs":{"oam":1}
,"mpls-tp":{"consists":1,"oam":1}
,"consists":{"comprehensive":1}
,"comprehensive":{"fault":1}
,"indication":{"performance":1,"route":1}
,"capabilities":{"mpls-tp":1}
,"functions":{"continuity":1,"transport":1}
,"continuity":{"check":1}
,"check":{"connectivity":1}
,"connectivity":{"verification":1}
,"verification":{"(cccv)":1}
,"(cccv)":{"remote":1}
,"remote":{"defect":1}
,"defect":{"indication":1}
,"route":{"tracing":1}
,"tracing":{"alarm":1}
,"alarm":{"reporting":1}
,"reporting":{"lock":1}
,"lock":{"instruct":1,"loopback":1}
,"instruct":{"loopback":1}
,"loopback":{"packet":1,"two":1}
,"packet":{"loss":1}
,"loss":{"delay":1}
,"delay":{"measurement":1}
,"measurement":{"lock":1}
,"two":{"useful":1}
,"useful":{"oam":1}
,"profile":{"network":1}
}
;Search.control.loadWordPairs(pairs);
