var pairs =
{
"associated":{"tunnel":1,"tunnels":1,"via":1,"east":1}
,"tunnel":{"associated":1,"reverse":1,"tunnels":1,"associated-group":1}
,"tunnels":{"support":1,"forward":1,"associated":1,"configured":1}
,"support":{"bidirectional":1}
,"bidirectional":{"data":1}
,"data":{"flow":1}
,"flow":{"two":1}
,"two":{"unidirectional":1,"tunnels":1}
,"unidirectional":{"tunnels":1,"lsp":1}
,"forward":{"tunnel":1,"reverse":1}
,"reverse":{"tunnel":1,"component":1,"components":1}
,"via":{"lsps":1}
,"lsps":{"tunnel":1}
,"associated-group":{"least":1}
,"least":{"unidirectional":1}
,"lsp":{"consists":1}
,"consists":{"either":1}
,"either":{"forward":1,"different":1}
,"component":{"based":1}
,"based":{"association":1}
,"association":{"forward":1}
,"components":{"may":1}
,"may":{"traverse":1}
,"traverse":{"either":1}
,"different":{"nodes":1,"links":1}
,"nodes":{"different":1,"two":1,"non-overlapping":1,"tunnels":1}
,"links":{"node":1}
,"node":{"link":1,"west":1,"overlapping":1}
,"link":{"nodes":1}
,"east":{"node":1}
,"west":{"node":1}
,"overlapping":{"nodes":1}
,"non-overlapping":{"nodes":1}
,"configured":{"unidirectional":1}
}
;Search.control.loadWordPairs(pairs);
