var pairs =
{
"label":{"distribution":1,"mapping":1}
,"distribution":{"protocol":1}
,"protocol":{"label":1,"(ldp)":1}
,"(ldp)":{"two":1}
,"two":{"label-switched":1,"lsrs":1}
,"label-switched":{"routers":1,"paths":1}
,"routers":{"(lsr)":1}
,"(lsr)":{"exchange":1}
,"exchange":{"label":1,"information":1}
,"mapping":{"information":1}
,"information":{"two":1,"bi-directional":1}
,"lsrs":{"called":1,"used":1}
,"called":{"ldp":1}
,"ldp":{"peers":1,"used":1,"works":1,"assigns":1,"interface":1}
,"peers":{"exchange":1}
,"bi-directional":{"ldp":1}
,"used":{"build":1,"forward":1,"forwarding":1}
,"build":{"maintain":1}
,"maintain":{"databases":1}
,"databases":{"lsrs":1}
,"forward":{"traffic":1}
,"traffic":{"mpls":1}
,"mpls":{"networks":1,"forwarder":1}
,"networks":{"ldp":1}
,"works":{"routing":1}
,"routing":{"protocols":1}
,"protocols":{"(rip":1}
,"(rip":{"ospf":1}
,"ospf":{"bgp)":1}
,"bgp)":{"create":1}
,"create":{"label-switched":1}
,"paths":{"(lsp)":1}
,"(lsp)":{"used":1}
,"forwarding":{"packets":1,"equivalence":1,"tables":1}
,"packets":{"lsp":1,"belong":1}
,"lsp":{"path":1,"zebos-xp":1}
,"path":{"taken":1}
,"taken":{"packets":1}
,"belong":{"forwarding":1}
,"equivalence":{"class":1}
,"class":{"(fec)":1}
,"(fec)":{"corresponding":1}
,"corresponding":{"lsp":1}
,"zebos-xp":{"ldp":1}
,"assigns":{"labels":1}
,"labels":{"every":1,"deletes":1,"forwarding":1}
,"every":{"destination":1}
,"destination":{"address":1,"prefix":1}
,"address":{"destination":1}
,"prefix":{"provided":1}
,"provided":{"ribd":1}
,"ribd":{"daemon":1}
,"daemon":{"ldp":1}
,"interface":{"mpls":1}
,"forwarder":{"adds":1}
,"adds":{"labels":1}
,"deletes":{"labels":1}
}
;Search.control.loadWordPairs(pairs);
