var pairs =
{
"banner":{"motd":1,"command":1,"message":1,"displayed":1}
,"motd":{"banner":1,"line":1,"default":1,"parameters":1}
,"command":{"banner":1,"write":1,"available":1,"syntax":1,"mode":1}
,"message":{"day":1,"login":1}
,"day":{"(motd)":1}
,"(motd)":{"login":1}
,"login":{"giving":1,"command":1}
,"giving":{"banner":1}
,"write":{"memory":1,"command":1}
,"memory":{"using":1,"change":1}
,"using":{"write":1}
,"change":{"made":1}
,"made":{"command":1}
,"available":{"log":1}
,"log":{"imish":1}
,"imish":{"next":1}
,"next":{"time":1}
,"time":{"default":1}
,"default":{"following":1,"banner":1,"specify":1,"string":1,"configure":1}
,"following":{"banner":1}
,"displayed":{"logging":1}
,"logging":{"hello":1}
,"hello":{"zebos-xp":1}
,"zebos-xp":{"(version":1}
,"(version":{"4.0051502-main)":1}
,"4.0051502-main)":{"2015":1}
,"2015":{"infusion":1}
,"infusion":{"parameter":1}
,"parameter":{"display":1}
,"display":{"banner":1}
,"syntax":{"banner":1}
,"line":{"banner":1,"specify":1}
,"parameters":{"line":1}
,"specify":{"custom":1,"default":1}
,"custom":{"string":1}
,"string":{"default":1,"command":1}
,"mode":{"configure":1,"examples":1}
,"configure":{"mode":1,"terminal":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"banner":1}
}
;Search.control.loadWordPairs(pairs);
