var pairs =
{
"lldp":{"timer":1,"frames":1}
,"timer":{"command":1,"msg-tx-interval":1,"reinitdelay":1,"tx-delay":1}
,"command":{"interval":1,"syntax":1,"mode":1}
,"interval":{"lldp":1,"value":1}
,"frames":{"transmitted":1}
,"transmitted":{"command":1}
,"syntax":{"lldp":1}
,"msg-tx-interval":{"<5-32768>":1,"message":1,"seconds":1,"configure":1}
,"<5-32768>":{"lldp":1,"message":1}
,"reinitdelay":{"value":1,"reinit":1,"seconds":1,"configure":1}
,"value":{"lldp":1,"<5-32768>":1,"reinitdelay":1,"value":1,"reinit":1,"tx-delay":1,"<1-8192>":1,"range":1,"msg-tx-interval":1}
,"tx-delay":{"<1-8192>":1,"transmit":1,"seconds":1}
,"<1-8192>":{"parameters":1,"transmit":1}
,"parameters":{"msg-tx-interval":1}
,"message":{"transmit":1}
,"transmit":{"interval":1,"delay":1}
,"reinit":{"delay":1}
,"delay":{"value":1}
,"range":{"<=tx-delay":1}
,"<=tx-delay":{"<=((0.25)*msg-tx-interval)":1}
,"<=((0.25)*msg-tx-interval)":{"default":1}
,"default":{"values":1,"value":1}
,"values":{"default":1}
,"seconds":{"default":1,"command":1}
,"mode":{"interface":1,"examples":1}
,"interface":{"mode":1,"eth0":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"lldp":1}
}
;Search.control.loadWordPairs(pairs);
