var pairs =
{
"show":{"pim":1}
,"pim":{"local-members":1,"interfaces":1,"(vrf":1}
,"local-members":{"command":1,"show":1,"ifname":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"information":1,"neighbors":1}
,"information":{"local":1}
,"local":{"membership":1}
,"membership":{"pim":1}
,"interfaces":{"command":1}
,"syntax":{"show":1}
,"ifname":{"show":1,"parameters":1,"display":1}
,"(vrf":{"name":1}
,"name":{"local-members":1,"specify":1,"vpn":1,"command":1}
,"parameters":{"vrf":1}
,"vrf":{"vpn":1}
,"vpn":{"routing\u002Fforwarding":1}
,"routing\u002Fforwarding":{"instance":1}
,"instance":{"name":1,"ifname":1}
,"specify":{"name":1}
,"neighbors":{"interface":1}
,"interface":{"name":1}
,"mode":{"privileged":1,"example":1}
,"privileged":{"exec":1}
,"exec":{"exec":1,"mode":1}
,"example":{"show":1}
}
;Search.control.loadWordPairs(pairs);
