var pairs =
{
"in-service":{"command":1,"testing":1}
,"command":{"enable":1,"syntax":1,"mode":1}
,"enable":{"in-service":1}
,"testing":{"command":1,"parameters":1}
,"syntax":{"in-service":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"ethernet":1,"examples":1}
,"ethernet":{"cfm":1}
,"cfm":{"pbb":1}
,"pbb":{"mep":1}
,"mep":{"configuration":1}
,"configuration":{"mode":1}
,"examples":{"(config-cfm-pbb-mep)":1}
,"(config-cfm-pbb-mep)":{"in-service":1}
}
;Search.control.loadWordPairs(pairs);
