var pairs =
{
"neighbor":{"x:x":1,"ipv6":1,"hello":1,"system":1,"3ffe":1}
,"x:x":{":x:x":1}
,":x:x":{"command":1,"neighbor":1,"parameters":1}
,"command":{"designate":1,"remove":1,"syntax":1,"mode":1}
,"designate":{"neighbor":1}
,"ipv6":{"address":1}
,"address":{"exchanging":1}
,"exchanging":{"hello":1}
,"hello":{"messages":1,"message":1}
,"messages":{"neighbor":1}
,"message":{"explicitly":1}
,"explicitly":{"identified":1}
,"identified":{"rejected":1}
,"rejected":{"parameter":1}
,"parameter":{"command":1}
,"remove":{"neighbor":1}
,"system":{"command":1}
,"syntax":{"neighbor":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"router":1,"examples":1}
,"router":{"mode":1,"rsvp":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"rsvp":{"(config-router)":1}
,"(config-router)":{"neighbor":1}
,"3ffe":{":3:34":1}
}
;Search.control.loadWordPairs(pairs);
