var pairs =
{
"internet":{"key":1,"protocol":1,"security":1}
,"key":{"exchange":1,"management":1}
,"exchange":{"(ike":1,"shared":1}
,"(ike":{"ikev2)":1}
,"ikev2)":{"internet":1}
,"protocol":{"security":1,"used":1,"(isakmp)":1,"runs":1}
,"security":{"(ipsec)":1,"association":1,"policy":1}
,"(ipsec)":{"protocol":1}
,"used":{"security":1,"second":1}
,"association":{"(sa)":1,"key":1}
,"(sa)":{"negotiating":1}
,"negotiating":{"keys":1}
,"keys":{"secret":1,"derived":1}
,"secret":{"ike":1,"cryptographic":1}
,"ike":{"builds":1,"protocol":1}
,"builds":{"upon":1}
,"upon":{"internet":1}
,"management":{"protocol":1}
,"(isakmp)":{"using":1}
,"using":{"x.509":1}
,"x.509":{"certificates":1}
,"certificates":{"authentication":1}
,"authentication":{"diffie":1}
,"diffie":{"hellman":1}
,"hellman":{"key":1}
,"shared":{"session":1}
,"session":{"secret":1}
,"cryptographic":{"keys":1}
,"derived":{"addition":1}
,"addition":{"security":1}
,"policy":{"every":1}
,"every":{"peer":1}
,"peer":{"connect":1}
,"connect":{"manually":1}
,"manually":{"maintained":1}
,"maintained":{"ike":1}
,"runs":{"two":1}
,"two":{"phases":1}
,"phases":{"first":1}
,"first":{"phase":1}
,"phase":{"establishes":1,"negotiate":1}
,"establishes":{"isakmp":1}
,"isakmp":{"used":1}
,"second":{"phase":1}
,"negotiate":{"ipsec":1}
,"ipsec":{"sas":1}
}
;Search.control.loadWordPairs(pairs);
