var pairs =
{
"packet":{"protocol":1,"contains":1,"header":1,"fragmented":1,"often":1,"depends":1,"packet":1,"sent":1,"switching":1}
,"protocol":{"data":1,"creates":1,"user":1,"(udp)":1}
,"data":{"unit":1,"control":1,"packet":1}
,"unit":{"(pdu)":1}
,"(pdu)":{"layer":1}
,"layer":{"(l3)":1}
,"(l3)":{"open":1}
,"open":{"systems":1}
,"systems":{"interconnection":1}
,"interconnection":{"(osi)":1}
,"(osi)":{"reference":1}
,"reference":{"model":1}
,"model":{"packet":1}
,"contains":{"source":1}
,"source":{"destination":1}
,"destination":{"addresses":1}
,"addresses":{"user":1}
,"user":{"data":1,"datagram":1}
,"control":{"information":1}
,"information":{"length":1}
,"length":{"packet":1}
,"header":{"checksum":1}
,"checksum":{"flags":1}
,"flags":{"indicating":1}
,"indicating":{"whether":1}
,"whether":{"packet":1}
,"fragmented":{"user":1}
,"often":{"referred":1}
,"referred":{"payload":1}
,"payload":{"actual":1}
,"actual":{"format":1}
,"format":{"packet":1}
,"depends":{"protocol":1}
,"creates":{"packet":1}
,"sent":{"connectionless":1}
,"connectionless":{"protocol":1}
,"datagram":{"protocol":1,"frame":1}
,"(udp)":{"sometimes":1}
,"sometimes":{"called":1}
,"called":{"datagram":1}
,"frame":{"packet":1}
}
;Search.control.loadWordPairs(pairs);
