var pairs =
{
"dcb-ets":{"functions":1,"(enhanced":1}
,"functions":{"chapter":1}
,"chapter":{"contains":1}
,"contains":{"apis":1}
,"apis":{"dcb-ets":1,"function":1}
,"(enhanced":{"transmission":1}
,"transmission":{"selection)":1}
,"selection)":{"includes":1}
,"includes":{"following":1}
,"following":{"apis":1}
,"function":{"description":1}
,"description":{"hal_dcb_init":1}
,"hal_dcb_init":{"sends":1}
,"sends":{"hal_msg_dcb_init":1,"hal_msg_dcb_deinit":1,"hal_msg_dcb_enable":1,"hal_msg_dcb_disable":1,"hal_msg_dcb_ets_enable":1,"hal_msg_dcb_ets_disable":1,"hal_msg_dcb_if_enable":1,"hal_msg_dcb_if_disable":1,"hal_msg_dcb_ets_if_enable":1,"hal_msg_dcb_ets_if_disable":1,"hal_msg_dcb_ets_select_ets_mode":1,"hal_msg_dcb_ets_tcg_app_prio_set":1,"hal_msg_dcb_ets_tcg_app_prio_unset":1,"hal_msg_dcb_ets_tcg_bw_set":1,"hal_msg_dcb_ets_add_pri_to_tcg":1}
,"hal_msg_dcb_init":{"message":1}
,"message":{"hsl":1}
,"hsl":{"initialize":1,"deinitialize":1,"enable":1,"disable":1,"hal_dcb_ets_set_application_priority":1,"hal_dcb_ets_unset_application_priority":1,"hal_dcb_ets_assign_bw_to_tcgs":1,"hal_dcb_ets_add_pri_to_tcg":1,"hal_dcb_ets_remove_pri_from_tcg":1,"hal_dcb_global_disable":1}
,"initialize":{"dcb":1}
,"dcb":{"hardware":1,"switch":1,"features":1}
,"hardware":{"hal_dcb_deinit":1,"hal_dcb_bridge_enable":1,"hal_dcb_bridge_disable":1,"hal_dcb_ets_bridge_enable":1,"hal_dcb_ets_bridge_disable":1,"hal_dcb_interface_enable":1,"interface":1,"lldp_dcbx_set_capability":1,"nsm_dcb_app_bridge_enable":1}
,"hal_dcb_deinit":{"sends":1}
,"hal_msg_dcb_deinit":{"message":1}
,"deinitialize":{"dcb":1}
,"hal_dcb_bridge_enable":{"sends":1}
,"hal_msg_dcb_enable":{"message":1}
,"enable":{"dcb":1,"ets":1}
,"hal_dcb_bridge_disable":{"sends":1}
,"hal_msg_dcb_disable":{"message":1}
,"disable":{"dcb":1,"ets":1}
,"hal_dcb_ets_bridge_enable":{"sends":1}
,"hal_msg_dcb_ets_enable":{"message":1}
,"ets":{"hardware":1,"feature":1,"switch":1,"interface":1}
,"hal_dcb_ets_bridge_disable":{"sends":1}
,"hal_msg_dcb_ets_disable":{"message":1}
,"hal_dcb_interface_enable":{"sends":1}
,"hal_msg_dcb_if_enable":{"message":1}
,"interface":{"hal_dcb_interface_disable":1,"hal_dcb_ets_interface_enable":1,"hal_dcb_ets_interface_disable":1,"hal_dcb_select_ets_mode":1,"lldp_set_fast_init":1,"nsm_dcb_assign_bw_percentage_to_tcg":1,"nsm_dcb_app_disable_interface":1,"nsm_dcb_app_set_advertise_interface":1,"nsm_dcb_application_priority_set":1,"given":1,"nsm_dcb_disable_interface":1,"nsm_dcb_ets_bridge_enable":1,"nsm_dcb_ets_set_advertise_interface":1,"nsm_dcb_show_appl_priority_table":1,"nsm_dcb_show_tcg_by_bridge":1,"nsm_dcb_show_app_by_bridge":1}
,"hal_dcb_interface_disable":{"sends":1}
,"hal_msg_dcb_if_disable":{"message":1}
,"hal_dcb_ets_interface_enable":{"sends":1}
,"hal_msg_dcb_ets_if_enable":{"message":1}
,"feature":{"dcb":1}
,"hal_dcb_ets_interface_disable":{"sends":1}
,"hal_msg_dcb_ets_if_disable":{"message":1}
,"hal_dcb_select_ets_mode":{"sends":1}
,"hal_msg_dcb_ets_select_ets_mode":{"message":1}
,"hal_dcb_ets_set_application_priority":{"sends":1}
,"hal_msg_dcb_ets_tcg_app_prio_set":{"message":1}
,"hal_dcb_ets_unset_application_priority":{"sends":1}
,"hal_msg_dcb_ets_tcg_app_prio_unset":{"message":1}
,"hal_dcb_ets_assign_bw_to_tcgs":{"sends":1}
,"hal_msg_dcb_ets_tcg_bw_set":{"message":1}
,"hal_dcb_ets_add_pri_to_tcg":{"sends":1}
,"hal_msg_dcb_ets_add_pri_to_tcg":{"message":1}
,"hal_dcb_ets_remove_pri_from_tcg":{"removes":1}
,"removes":{"hal_msg_dcb_ets_add_pri_to_tcg":1,"priorities":1}
,"hal_dcb_global_disable":{"sends":1}
,"switch":{"level":1,"nsm_dcb_app_bridge_disable":1,"nsm_dcb_app_enable_interface":1,"nsm_dcb_bridge_enable":1,"nsm_dcb_init":1,"(bridge)":1}
,"level":{"hardware":1}
,"lldp_dcbx_set_capability":{"enables":1}
,"enables":{"dcbx":1,"fast":1,"application":1,"advertising":1,"dcb":1,"ets":1,"willing":1,"advertise":1}
,"dcbx":{"interface":1}
,"lldp_set_fast_init":{"enables":1}
,"fast":{"initialization":1}
,"initialization":{"lldp":1}
,"lldp":{"nsm_dcb_add_pri_to_tcg":1}
,"nsm_dcb_add_pri_to_tcg":{"adds":1}
,"adds":{"priorities":1}
,"priorities":{"traffic":1}
,"traffic":{"class":1}
,"class":{"group":1,"groups":1}
,"group":{"nsm_dcb_remove_pri_from_tcg":1,"nsm_dcb_max_tcg":1}
,"nsm_dcb_remove_pri_from_tcg":{"removes":1}
,"nsm_dcb_max_tcg":{"sets":1}
,"sets":{"maximum":1,"application":1}
,"maximum":{"number":1}
,"number":{"traffic":1}
,"groups":{"configured":1,"nsm_dcb_delete_tcgs":1,"given":1}
,"configured":{"interface":1,"given":1}
,"nsm_dcb_assign_bw_percentage_to_tcg":{"assigns":1}
,"assigns":{"bandwidth":1}
,"bandwidth":{"traffic":1}
,"nsm_dcb_delete_tcgs":{"deletes":1}
,"deletes":{"tcg":1}
,"tcg":{"related":1}
,"related":{"configuration":1}
,"configuration":{"hardware":1}
,"nsm_dcb_app_bridge_enable":{"enables":1}
,"application":{"priority":1}
,"priority":{"switch":1,"interface":1,"based":1,"table":1,"information":1}
,"nsm_dcb_app_bridge_disable":{"disables":1}
,"disables":{"application":1,"dcb":1,"ets":1}
,"nsm_dcb_app_enable_interface":{"enables":1}
,"nsm_dcb_app_disable_interface":{"disables":1}
,"nsm_dcb_app_set_advertise_interface":{"enables":1}
,"advertising":{"application":1}
,"nsm_dcb_application_priority_set":{"sets":1}
,"based":{"interface":1}
,"given":{"protocol":1,"interface":1,"bridge":1}
,"protocol":{"nsm_dcb_application_priority_unset":1,"nsm_dcb_bridge_disable":1}
,"nsm_dcb_application_priority_unset":{"unsets":1}
,"unsets":{"application":1}
,"nsm_dcb_bridge_disable":{"disables":1}
,"nsm_dcb_bridge_enable":{"enables":1}
,"nsm_dcb_init":{"initializes":1}
,"initializes":{"nsm_dcb_global":1}
,"nsm_dcb_global":{"structure":1}
,"structure":{"nsm_dcb_deinit":1,"nsm_dcb_enable_interface":1}
,"nsm_dcb_deinit":{"de-initializes":1}
,"de-initializes":{"nsm_dcb_global":1}
,"nsm_dcb_enable_interface":{"enables":1}
,"features":{"interface":1}
,"nsm_dcb_disable_interface":{"disables":1}
,"nsm_dcb_ets_bridge_enable":{"enables":1}
,"(bridge)":{"nsm_dcb_ets_bridge_disable":1,"nsm_dcb_ets_set_willing_interface":1}
,"nsm_dcb_ets_bridge_disable":{"disables":1}
,"nsm_dcb_ets_set_willing_interface":{"enables":1}
,"willing":{"setting":1}
,"setting":{"ets":1}
,"nsm_dcb_ets_set_advertise_interface":{"enables":1}
,"advertise":{"setting":1}
,"nsm_dcb_show_appl_priority_table":{"displays":1}
,"displays":{"application":1,"traffic":1}
,"table":{"given":1}
,"nsm_dcb_show_tcg_by_bridge":{"displays":1}
,"bridge":{"nsm_dcb_show_tcg_by_intf":1}
,"nsm_dcb_show_tcg_by_intf":{"displays":1}
,"nsm_dcb_show_app_by_bridge":{"displays":1}
,"information":{"configured":1}
}
;Search.control.loadWordPairs(pairs);
