var pairs =
{
"ethernet":{"oam":1}
,"oam":{"link-monitor":1}
,"link-monitor":{"frame-seconds":1,"high":1}
,"frame-seconds":{"command":1,"event":1,"{threshold":1,"threshold":1,"window":1}
,"command":{"configure":1,"ethernet":1,"reset":1,"syntax":1,"mode":1}
,"configure":{"low":1,"error":1,"terminal":1}
,"low":{"high":1,"threshold":1,"<1-900>}":1,"value":1,"window":1}
,"high":{"threshold":1,"value":1,"low":1}
,"threshold":{"window":1,"exceeded":1,"action":1,"configure":1,"high":1,"errored":1,"value":1,"check":1,"low":1}
,"window":{"frame-seconds":1,"<100-900>}":1,"size":1,"<100-900>":1,"milliseconds":1,"200":1,"threshold":1}
,"event":{"low":1,"generated":1,"window":1}
,"exceeded":{"errored-frame-seconds":1,"action":1}
,"errored-frame-seconds":{"link":1}
,"link":{"event":1}
,"generated":{"high":1}
,"action":{"defined":1,"taken":1}
,"defined":{"command":1}
,"taken":{"form":1}
,"form":{"command":1}
,"reset":{"default":1}
,"default":{"values":1}
,"values":{"command":1}
,"syntax":{"ethernet":1}
,"{threshold":{"{high":1}
,"{high":{"(<1-900>":1,"low}":1}
,"(<1-900>":{"none)":1}
,"none)":{"low":1}
,"<1-900>}":{"window":1}
,"<100-900>}":{"ethernet":1}
,"low}":{"window}":1}
,"window}":{"parameters":1}
,"parameters":{"threshold":1}
,"error":{"threshold":1}
,"value":{"high":1,"none":1,"low":1,"window":1}
,"errored":{"frames":1}
,"frames":{"<1-900>":1}
,"<1-900>":{"high":1,"low":1}
,"none":{"disable":1}
,"disable":{"high":1}
,"check":{"low":1}
,"size":{"frame":1}
,"frame":{"event":1}
,"<100-900>":{"size":1,"command":1}
,"milliseconds":{"<100-900>":1}
,"mode":{"interface":1,"examples":1}
,"interface":{"mode":1,"eth1":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth1":{"(config-if)":1}
,"(config-if)":{"ethernet":1}
,"200":{"(config)":1}
}
;Search.control.loadWordPairs(pairs);
