var pairs =
{
"show":{"mpls":1}
,"mpls":{"diffserv":1,"differentiated":1}
,"diffserv":{"class-to-exp":1}
,"class-to-exp":{"command":1,"parameters":1,"mpls":1}
,"command":{"display":1,"syntax":1,"mode":1,"showing":1}
,"display":{"node":1}
,"node":{"level":1}
,"level":{"phb-exp":1,"show":1}
,"phb-exp":{"mapping":1}
,"mapping":{"command":1,"node":1,"data":1}
,"syntax":{"show":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"following":1}
,"following":{"sample":1}
,"sample":{"output":1}
,"output":{"show":1}
,"showing":{"phb-exp":1}
,"differentiated":{"services":1}
,"services":{"class":1}
,"class":{"exp":1,"dscp_value":1}
,"exp":{"mapping":1}
,"data":{"class":1}
,"dscp_value":{"exp_value":1}
,"exp_value":{"000000":1}
,"000000":{"000000":1,"af12":1}
,"af12":{"001100":1}
}
;Search.control.loadWordPairs(pairs);
