var pairs =
{
"paths":{"rsvp":1,"new":1,"added":1}
,"rsvp":{"maintains":1}
,"maintains":{"list":1}
,"list":{"configured":1,"two":1,"strict":1}
,"configured":{"paths":1}
,"new":{"paths":1}
,"added":{"tail":1}
,"tail":{"list":1}
,"two":{"identifiers":1}
,"identifiers":{"path":1}
,"path":{"16-bit":1,"specifies":1,"right":1,"immediately":1}
,"16-bit":{"identifier":1}
,"identifier":{"generated":1}
,"generated":{"system":1}
,"system":{"string":1}
,"string":{"provided":1}
,"provided":{"operator":1}
,"operator":{"path":1}
,"specifies":{"list":1}
,"strict":{"loose":1,"hop":1}
,"loose":{"hops":1,"hop":1}
,"hops":{"taken":1}
,"taken":{"explicitly-routed":1,"lsp":1}
,"explicitly-routed":{"lsp":1}
,"lsp":{"hop":1,"during":1}
,"hop":{"loose":1,"taken":1,"hop":1,"strict":1,"path":1,"followed":1}
,"during":{"setup":1}
,"setup":{"however":1,"followed":1}
,"however":{"constraint":1}
,"constraint":{"next":1}
,"next":{"hop":1}
,"followed":{"strict":1}
,"right":{"hop":1}
,"immediately":{"following":1}
,"following":{"hop":1}
}
;Search.control.loadWordPairs(pairs);
