var pairs =
{
"stub":{"areas":1,"area":1,"routers":1}
,"areas":{"shown":1,"shielded":1,"ospf":1,"deployed":1}
,"shown":{"figure":1}
,"figure":{"1-3":1}
,"1-3":{"stub":1}
,"shielded":{"external":1}
,"external":{"routes":1}
,"routes":{"receive":1,"stub":1,"minimizes":1,"cannot":1,"every":1}
,"receive":{"information":1}
,"information":{"networks":1}
,"networks":{"belong":1}
,"belong":{"areas":1}
,"ospf":{"autonomous":1}
,"autonomous":{"system":1}
,"system":{"default":1,"typically":1}
,"default":{"summary":1,"route":1}
,"summary":{"route":1}
,"route":{"(address":1,"intra-area":1,"central":1,"ability":1}
,"(address":{"0.0.0.0)":1}
,"0.0.0.0)":{"inserted":1}
,"inserted":{"stub":1}
,"area":{"reach":1,"link":1,"routers":1,"stub":1,"cannot":1,"configured":1,"edge":1,"backbone":1,"multiple":1,"however":1,"follow":1}
,"reach":{"external":1}
,"link":{"state":1}
,"state":{"databases":1}
,"databases":{"contain":1}
,"contain":{"default":1,"asbr":1}
,"intra-area":{"inter-area":1}
,"inter-area":{"routes":1}
,"minimizes":{"size":1}
,"size":{"link-state":1}
,"link-state":{"database":1}
,"database":{"memory":1}
,"memory":{"stub":1}
,"routers":{"stub":1,"within":1,"configuration":1}
,"cannot":{"contain":1,"generated":1}
,"asbr":{"external":1}
,"generated":{"within":1}
,"within":{"stub":1,"area":1}
,"configured":{"stub":1}
,"configuration":{"verified":1}
,"verified":{"exchange":1}
,"exchange":{"adjacency":1}
,"adjacency":{"packets":1}
,"packets":{"stub":1,"exiting":1}
,"edge":{"ospf":1}
,"typically":{"situations":1}
,"situations":{"branch":1}
,"branch":{"office":1}
,"office":{"need":1,"instead":1,"destinations":1}
,"need":{"know":1}
,"know":{"routes":1}
,"every":{"office":1}
,"instead":{"default":1}
,"central":{"office":1}
,"destinations":{"stub":1}
,"deployed":{"single":1}
,"single":{"exit":1}
,"exit":{"point":1,"points":1}
,"point":{"connecting":1}
,"connecting":{"area":1}
,"backbone":{"area":1}
,"multiple":{"exit":1}
,"points":{"stub":1}
,"however":{"guarantee":1}
,"guarantee":{"packets":1}
,"exiting":{"area":1}
,"follow":{"optimal":1}
,"optimal":{"path":1}
,"path":{"abr":1}
,"abr":{"generates":1}
,"generates":{"default":1}
,"ability":{"associate":1}
,"associate":{"traffic":1}
,"traffic":{"specific":1}
,"specific":{"default":1}
}
;Search.control.loadWordPairs(pairs);
