var pairs =
{
"pim":{"vif":1,"mode":1,"hello":1,"process":1,"core":1}
,"vif":{"method":1}
,"method":{"table":1}
,"table":{"pim":1,"hides":1}
,"hides":{"pim":1}
,"mode":{"address-family-specific":1,"address-family":1}
,"address-family-specific":{"method\u002Ffunction":1}
,"method\u002Ffunction":{"call":1}
,"call":{"example":1}
,"example":{"sending":1}
,"sending":{"pim":1}
,"hello":{"packet":1}
,"packet":{"rest":1}
,"rest":{"pim":1}
,"process":{"makes":1}
,"makes":{"pim":1}
,"core":{"code":1}
,"code":{"pim":1}
,"address-family":{"independent":1}
,"independent":{"possible":1}
,"possible":{"definition":1}
,"definition":{"struct":1}
,"struct":{"pim_vif_methods":1,"pim_vif":1,"prefix":1,"connected":1,"pim_sg_prefix":1,"pim_mrt":1,"pim_interface_id":1,"pim_vif_member":1}
,"pim_vif_methods":{"{int":1}
,"{int":{"(*sock_join)":1}
,"(*sock_join)":{"(const":1}
,"(const":{"struct":1}
,"pim_vif":{"*vif)":1,"*vif":1,"*(*lookup_received_vif)":1}
,"*vif)":{"int":1,"bool_t":1,"struct":1,"ifdef":1}
,"int":{"(*sock_leave)":1,"(*add_index)":1,"(*delete_index)":1,"(*add_address)":1,"(*delete_address)":1,"(*start)":1,"(*stop)":1,"(*register_stop)":1,"(*add_success)":1,"(*delete_success)":1,"(*make_passive)":1,"(*hello_timer)":1,"(*dr_selection)":1,"(*send_packet)":1,"(*send_packet_hello)":1,"(*send_packet_register)":1,"(*send_packet_register_stop)":1,"(*send_packet_join)":1,"(*send_packet_prune)":1,"(*send_packet_assert)":1,"(*send_packet_ecmp_redirect)":1,"(*process_packet_ecmp_redirect)":1,"(*process_packet_hello)":1,"(*process_packet_register)":1,"(*process_packet_register_stop)":1,"(*process_packet_jp)":1,"(*process_packet_bsm)":1,"(*process_packet_assert)":1,"(*process_packet_graft)":1,"(*process_packet_graft_ack)":1,"(*process_packet_crp)":1,"(*process_packet_state_refresh)":1,"(*send_add)":1,"(*send_delete)":1,"(*send_mrt_state_refresh_flag_update)":1,"(*process_member)":1,"(*process_nocache)":1,"(*process_wrongvif)":1,"(*process_wholepkt_req)":1,"(*process_nbr_add_alert)":1,"(*process_nbr_delete_alert)":1,"(*process_packet_df_elec)":1,"(*send_packet_df)":1}
,"(*sock_leave)":{"(const":1}
,"(*add_index)":{"(struct":1}
,"(struct":{"pim_vif":1}
,"(*delete_index)":{"(struct":1}
,"bool_t":{"(*is_directly_reachable_addr)":1,"primary_only)":1,"(*update_address)":1,"xg_assert":1}
,"(*is_directly_reachable_addr)":{"(struct":1}
,"*vif":{"const":1,"struct":1,"u_int16_t":1,"u_int32_t":1}
,"const":{"struct":1,"bool_t":1,"u_char":1,"u_int32_t":1}
,"prefix":{"*addr":1,"*(*get_address)":1,"*(*get_address_global)":1,"*dst":1,"*src":1,"*ups_addr":1,"*grp":1,"*nbr_addr":1,"*dst)":1,"*src)":1}
,"*addr":{"const":1}
,"primary_only)":{"int":1}
,"(*add_address)":{"(struct":1}
,"connected":{"*ifc)":1}
,"*ifc)":{"int":1,"bool_t":1}
,"(*delete_address)":{"(struct":1}
,"(*update_address)":{"(struct":1}
,"*(*get_address)":{"(struct":1}
,"*(*get_address_global)":{"(struct":1}
,"(*start)":{"(struct":1}
,"(*stop)":{"(struct":1}
,"(*register_stop)":{"(struct":1}
,"(*add_success)":{"(struct":1}
,"u_int16_t":{"vif_id)":1,"flags)":1}
,"vif_id)":{"int":1}
,"(*delete_success)":{"(struct":1}
,"(*make_passive)":{"(struct":1}
,"(*hello_timer)":{"(struct":1}
,"(*dr_selection)":{"(struct":1}
,"*(*lookup_received_vif)":{"(struct":1}
,"u_int32_t":{"ifindex":1,"length)":1,"reserved2":1,"pref":1,"metric)":1,"message_id)":1}
,"ifindex":{"u_int16_t":1}
,"flags)":{"int":1}
,"(*send_packet)":{"(struct":1}
,"*dst":{"const":1,"u_int8_t":1}
,"u_char":{"*data":1}
,"*data":{"const":1}
,"length)":{"int":1}
,"(*send_packet_hello)":{"(struct":1}
,"(*send_packet_register)":{"(struct":1}
,"reserved2":{"const":1}
,"pim_sg_prefix":{"*sg)":1,"*sg":1}
,"*sg)":{"int":1}
,"(*send_packet_register_stop)":{"(struct":1}
,"*src":{"const":1,"struct":1}
,"(*send_packet_join)":{"(struct":1}
,"*ups_addr":{"struct":1}
,"pim_mrt":{"*mrt)":1}
,"*mrt)":{"int":1}
,"(*send_packet_prune)":{"(struct":1}
,"(*send_packet_assert)":{"(struct":1}
,"*grp":{"const":1}
,"xg_assert":{"const":1}
,"pref":{"const":1}
,"metric)":{"ifdef":1}
,"ifdef":{"have_pim_ecmp_redirect":1,"have_pim_bidir":1}
,"have_pim_ecmp_redirect":{"int":1}
,"(*send_packet_ecmp_redirect)":{"(struct":1}
,"*sg":{"struct":1,"u_int32_t":1}
,"*nbr_addr":{"struct":1}
,"pim_interface_id":{"*iid":1}
,"*iid":{"u_int8_t":1}
,"u_int8_t":{"preference":1,"subtype)":1}
,"preference":{"u_int64_t":1}
,"u_int64_t":{"*metric)":1}
,"*metric)":{"int":1}
,"(*process_packet_ecmp_redirect)":{"(struct":1}
,"*dst)":{"endif":1,"int":1}
,"endif":{"\u002F*have_pim_ecmp_redirect":1,"\u002F*have_pim_bidir":1}
,"\u002F*have_pim_ecmp_redirect":{"*\u002Fint":1}
,"*\u002Fint":{"(*process_packet)":1,"(*process_delete_alert)":1}
,"(*process_packet)":{"(struct":1}
,"(*process_packet_hello)":{"(struct":1}
,"(*process_packet_register)":{"(struct":1}
,"(*process_packet_register_stop)":{"(struct":1}
,"(*process_packet_jp)":{"(struct":1}
,"(*process_packet_bsm)":{"(struct":1}
,"(*process_packet_assert)":{"(struct":1}
,"(*process_packet_graft)":{"(struct":1}
,"(*process_packet_graft_ack)":{"(struct":1}
,"(*process_packet_crp)":{"(struct":1}
,"(*process_packet_state_refresh)":{"(struct":1}
,"(*send_add)":{"(struct":1}
,"(*send_delete)":{"(struct":1}
,"(*send_mrt_state_refresh_flag_update)":{"(struct":1}
,"(*process_member)":{"(struct":1}
,"pim_vif_member":{"*m)":1}
,"*m)":{"int":1}
,"(*process_nocache)":{"(struct":1}
,"(*process_wrongvif)":{"(struct":1}
,"(*process_wholepkt_req)":{"(struct":1}
,"message_id)":{"\u002F*mbr":1}
,"\u002F*mbr":{"alert":1}
,"alert":{"methods":1}
,"methods":{"*\u002Fint":1}
,"(*process_delete_alert)":{"(struct":1}
,"(*process_nbr_add_alert)":{"(struct":1}
,"(*process_nbr_delete_alert)":{"(struct":1}
,"have_pim_bidir":{"int":1}
,"(*process_packet_df_elec)":{"(struct":1}
,"subtype)":{"int":1}
,"(*send_packet_df)":{"(struct":1}
,"*src)":{"endif":1}
,"\u002F*have_pim_bidir":{"*\u002F}":1}
}
;Search.control.loadWordPairs(pairs);
