var pairs =
{
"label":{"distribution":1,"short":1}
,"distribution":{"protocol":1}
,"protocol":{"(ldp)":1,"distributing":1,"(rip)":1,"(bgp)":1,"traffic":1}
,"(ldp)":{"protocol":1}
,"distributing":{"labels":1}
,"labels":{"non-traffic-engineered":1}
,"non-traffic-engineered":{"applications":1}
,"applications":{"ldp":1}
,"ldp":{"allows":1,"works":1}
,"allows":{"routers":1}
,"routers":{"create":1}
,"create":{"label-switched":1,"lsps":1}
,"label-switched":{"path":1}
,"path":{"(lsp)":1,"first":1}
,"(lsp)":{"instances":1}
,"instances":{"network":1}
,"network":{"mapping":1,"layer":1}
,"mapping":{"network":1}
,"layer":{"routing":1,"switched":1}
,"routing":{"information":1,"protocols":1}
,"information":{"directly":1,"protocol":1}
,"directly":{"data-link":1}
,"data-link":{"layer":1}
,"switched":{"paths":1}
,"paths":{"label":1}
,"short":{"fixed-length":1}
,"fixed-length":{"locally-significant":1}
,"locally-significant":{"identifier":1}
,"identifier":{"identifies":1}
,"identifies":{"forwarding":1}
,"forwarding":{"equivalence":1}
,"equivalence":{"class":1}
,"class":{"(fec)":1}
,"(fec)":{"ldp":1}
,"works":{"routing":1}
,"protocols":{"routing":1}
,"(rip)":{"open":1}
,"open":{"shortest":1}
,"shortest":{"path":1}
,"first":{"(ospf)":1}
,"(ospf)":{"border":1}
,"border":{"gateway":1}
,"gateway":{"protocol":1}
,"(bgp)":{"create":1}
,"lsps":{"resource":1}
,"resource":{"reservation":1}
,"reservation":{"protocol":1}
,"traffic":{"engineering":1}
,"engineering":{"(rsvp-te)":1}
}
;Search.control.loadWordPairs(pairs);
