var pairs =
{
"nsm_mpls_set_pw_del_notify":{"function":1,"(struct":1}
,"function":{"enables":1,"succeeds":1}
,"enables":{"disables":1}
,"disables":{"delete":1}
,"delete":{"notification":1}
,"notification":{"syntax":1}
,"syntax":{"include":1}
,"include":{"nsm\u002Fmpls\u002Fnsm_mpls_vc_api.h":1}
,"nsm\u002Fmpls\u002Fnsm_mpls_vc_api.h":{"u_int32_t":1}
,"u_int32_t":{"nsm_mpls_set_pw_del_notify":1}
,"(struct":{"nsm_mpls":1}
,"nsm_mpls":{"*nmpls":1}
,"*nmpls":{"int":1}
,"int":{"val)":1}
,"val)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"nmpls":1,"none":1}
,"nmpls":{"nsm":1}
,"nsm":{"mpls":1}
,"mpls":{"pointer":1}
,"pointer":{"val":1,"null":1}
,"val":{"pal_true":1}
,"pal_true":{"pal_false":1}
,"pal_false":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"nsm_api_set_error":1}
,"nsm_api_set_error":{"nsm":1}
,"null":{"nsm_api_get_success":1}
,"nsm_api_get_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
