var pairs =
{
"bidirectional":{"forwarding":1}
,"forwarding":{"detection":1,"failure":1,"plane":1,"engines":1}
,"detection":{"bidirectional":1,"(bfd)":1,"communication":1,"required":1,"detached":1,"developer":1}
,"(bfd)":{"reduces":1}
,"reduces":{"reliance":1}
,"reliance":{"upon":1}
,"upon":{"relatively":1}
,"relatively":{"slow":1}
,"slow":{"hello":1}
,"hello":{"mechanism":1}
,"mechanism":{"routing":1,"detect":1}
,"routing":{"protocols":1}
,"protocols":{"detect":1,"nsm":1}
,"detect":{"failures":1,"liveliness":1,"forwarding":1}
,"failures":{"hardware":1,"adjacent":1}
,"hardware":{"signaling":1}
,"signaling":{"available":1}
,"available":{"assist":1}
,"assist":{"bfd":1}
,"bfd":{"works":1,"sessions":1,"provides":1,"irrespective":1,"packet-sending":1,"graceful-restart":1,"timers":1,"maintains":1,"bidirectional":1}
,"works":{"bgp":1,"tight":1}
,"bgp":{"ospfv2":1}
,"ospfv2":{"is-is":1}
,"is-is":{"enable":1}
,"enable":{"configure":1}
,"configure":{"bfd":1}
,"sessions":{"sessions":1,"receive":1,"protocol":1}
,"receive":{"bidirectional":1}
,"failure":{"notifications":1}
,"notifications":{"bfd":1}
,"provides":{"following":1}
,"following":{"features":1}
,"features":{"single":1}
,"single":{"mechanism":1}
,"liveliness":{"media":1,"static":1}
,"media":{"protocol":1}
,"protocol":{"layer":1,"next":1,"modules":1,"module":1,"undergoes":1}
,"layer":{"rapid":1}
,"rapid":{"detection":1}
,"communication":{"failures":1}
,"adjacent":{"systems":1}
,"systems":{"quickly":1}
,"quickly":{"establish":1}
,"establish":{"alternative":1}
,"alternative":{"paths":1}
,"paths":{"passive":1}
,"passive":{"active":1}
,"active":{"synchronous":1}
,"synchronous":{"asynchronous":1}
,"asynchronous":{"demand":1}
,"demand":{"modes":1}
,"modes":{"operation":1}
,"operation":{"improved":1}
,"improved":{"system":1}
,"system":{"performance":1}
,"performance":{"faster":1}
,"faster":{"detection":1}
,"required":{"data-plane":1}
,"data-plane":{"reachability":1}
,"reachability":{"detection":1,"protocol":1}
,"detached":{"control-plane":1}
,"control-plane":{"functionality":1}
,"functionality":{"separate":1}
,"separate":{"process":1}
,"process":{"works":1}
,"tight":{"conjunction":1}
,"conjunction":{"routing":1}
,"nsm":{"detect":1}
,"plane":{"reachability":1}
,"next":{"hops":1}
,"hops":{"zebos-xp":1}
,"zebos-xp":{"protocol":1}
,"modules":{"support":1}
,"support":{"bfd":1}
,"irrespective":{"bfd":1}
,"packet-sending":{"operations":1}
,"operations":{"place":1}
,"place":{"interfaces":1}
,"interfaces":{"data":1}
,"data":{"links":1}
,"links":{"extent":1}
,"extent":{"forwarding":1}
,"engines":{"themselves":1}
,"themselves":{"bfd":1}
,"graceful-restart":{"unaware":1}
,"unaware":{"whenever":1}
,"whenever":{"bfd":1}
,"timers":{"expire":1}
,"expire":{"session-down":1}
,"session-down":{"event":1}
,"event":{"triggered":1}
,"triggered":{"protocol":1}
,"module":{"bfd":1}
,"maintains":{"sessions":1}
,"undergoes":{"graceful":1}
,"graceful":{"restart":1}
,"restart":{"fast":1}
,"fast":{"mechanism":1}
,"static":{"next-hops":1}
,"next-hops":{"information":1}
,"information":{"bfd":1}
,"developer":{"guide":1}
}
;Search.control.loadWordPairs(pairs);
