var pairs =
{
"hal_flow_ctrl_pause_watermark_set":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"fails":1,"succeeds":1}
,"sets":{"watermark":1}
,"watermark":{"pause":1}
,"pause":{"flow":1,"output":1}
,"flow":{"control":1}
,"control":{"property":1}
,"property":{"port":1}
,"port":{"syntax":1,"u_int16_t":1,"interface":1}
,"syntax":{"int":1}
,"int":{"hal_flow_ctrl_pause_watermark_set":1}
,"(u_int32_t":{"port":1}
,"u_int16_t":{"wm_pause)":1}
,"wm_pause)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifindex":1,"none":1}
,"ifindex":{"port":1}
,"interface":{"index":1}
,"index":{"wm_pause":1}
,"wm_pause":{"watermark":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"hal_err_flow_control_set":1}
,"hal_err_flow_control_set":{"function":1}
,"fails":{"hal_success":1}
,"hal_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
