var pairs =
{
"show":{"running-config":1,"current":1}
,"running-config":{"interface":1}
,"interface":{"trill":1,"ifname":1,"name":1,"mode":1,"eth1":1}
,"trill":{"command":1,"parameters":1,"interface":1}
,"command":{"show":1,"syntax":1,"mode":1}
,"current":{"running":1}
,"running":{"rbridge":1}
,"rbridge":{"system":1}
,"system":{"configuration":1}
,"configuration":{"command":1}
,"syntax":{"show":1}
,"ifname":{"trill":1,"display":1}
,"parameters":{"ifname":1}
,"display":{"interface":1}
,"name":{"command":1}
,"mode":{"privileged":1,"interface":1,"configure":1,"example":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"configure":{"mode":1}
,"example":{"(config-if)":1}
,"(config-if)":{"show":1}
,"eth1":{"trill":1,"(config-if)":1}
}
;Search.control.loadWordPairs(pairs);
