var pairs =
{
"segment":{"routing":1}
,"routing":{"command":1,"functions":1,"entry":1}
,"command":{"api":1,"reference":1}
,"api":{"chapter":1}
,"chapter":{"describes":1}
,"describes":{"functions":1}
,"functions":{"segment":1,"called":1}
,"called":{"commands":1}
,"commands":{"segment":1}
,"reference":{"guide":1}
,"guide":{"function":1}
,"function":{"description":1}
,"description":{"nsm_sr_api_add_prefix_sid":1}
,"nsm_sr_api_add_prefix_sid":{"adds":1}
,"adds":{"prefix":1}
,"prefix":{"sid":1}
,"sid":{"primary":1}
,"primary":{"address":1}
,"address":{"interface":1}
,"interface":{"nsm_sr_api_delete_prefix_sid":1,"nsm_sr_api_disable":1}
,"nsm_sr_api_delete_prefix_sid":{"deletes":1}
,"deletes":{"prefix":1,"static":1}
,"nsm_sr_api_disable":{"disables":1}
,"disables":{"globally":1}
,"globally":{"device":1}
,"device":{"nsm_sr_api_enable":1,"sr_static_edge_node_set":1}
,"nsm_sr_api_enable":{"enables":1}
,"enables":{"globally":1}
,"sr_static_edge_node_set":{"creates":1}
,"creates":{"static":1}
,"static":{"entries":1,"segment":1}
,"entries":{"ftn":1}
,"ftn":{"ilm":1}
,"ilm":{"tables":1}
,"tables":{"mpls":1}
,"mpls":{"data":1}
,"data":{"plane":1}
,"plane":{"sr_static_edge_node_unset":1,"sr_static_route_set_ipv4":1}
,"sr_static_edge_node_unset":{"deletes":1}
,"sr_static_route_set_ipv4":{"creates":1}
,"entry":{"sr_static_route_unset_ipv4":1}
,"sr_static_route_unset_ipv4":{"deletes":1}
}
;Search.control.loadWordPairs(pairs);
