var pairs =
{
"clear":{"mac":1,"filtering":1,"multicast":1,"static":1,"specified":1}
,"mac":{"address-table":1,"address":1}
,"address-table":{"command":1,"dynamic":1,"(dynamic":1,"(static":1,"static":1,"multicast":1}
,"command":{"clear":1,"issued":1,"syntax":1,"mode":1}
,"filtering":{"database":1}
,"database":{"default":1,"clear":1,"entries":1}
,"default":{"bridge":1}
,"bridge":{"command":1,"<1-32>":1,"clears":1,"group":1,"example":1,"operation":1}
,"issued":{"following":1}
,"following":{"clear":1}
,"entries":{"configured":1,"clear":1,"given":1,"based":1,"multicast":1,"static":1,"cleared":1,"learned":1}
,"configured":{"cli":1,"management":1}
,"cli":{"(static)":1,"clear":1}
,"(static)":{"clear":1}
,"multicast":{"filtering":1,"database":1,"clears":1,"example":1,"vlan":1,"bridge":1}
,"given":{"vlan":1,"interface":1,"mac":1}
,"vlan":{"interface":1,"vid)":1,"clears":1,"value":1,"clear":1,"example":1,"bridge":1}
,"interface":{"clear":1,"ifname":1,"clears":1,"bridge":1,"eth0":1}
,"static":{"multicast":1,"multicast)":1,"clears":1,"example":1,"interface":1,"filtering":1,"address":1,"bridge":1}
,"based":{"mac":1}
,"address":{"command":1,"clear":1,"macaddr":1,"bridge":1,"specified":1,"0202.0202.0202":1}
,"syntax":{"clear":1}
,"dynamic":{"clear":1,"bridge":1,"(address":1,"clears":1,"entries":1,"address":1}
,"<1-32>":{"clear":1,"parameters":1}
,"(address":{"macaddr":1}
,"macaddr":{"interface":1,"filtering":1}
,"ifname":{"(instance":1,"vlan":1}
,"(instance":{"inst":1}
,"inst":{"vlan":1}
,"vid)":{"clear":1,"bridge":1}
,"(dynamic":{"static":1}
,"multicast)":{"cvlan":1,"clear":1,"bridge":1,"(address":1}
,"cvlan":{"vid":1,"clears":1,"value":1}
,"vid":{"clear":1,"svlan":1,"bridge":1}
,"svlan":{"vid":1,"clears":1,"value":1}
,"(static":{"multicast)":1}
,"parameters":{"dynamic":1}
,"clears":{"dynamic":1,"multicast":1,"entries":1,"bridge":1,"mac":1,"mstp":1}
,"management":{"address":1}
,"specified":{"mac":1,"cvlan":1,"svlan":1,"interface":1,"vlan":1}
,"cleared":{"based":1}
,"group":{"value":1}
,"value":{"range":1}
,"range":{"1-32":1,"1-4094":1,"<1-63>":1}
,"1-32":{"bridge":1,"cvlan":1,"instance":1,"command":1}
,"1-4094":{"svlan":1,"interface":1,"bridge":1}
,"instance":{"clears":1,"value":1}
,"mstp":{"instance":1}
,"<1-63>":{"vlan":1}
,"mode":{"privileged":1,"examples":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"examples":{"example":1}
,"example":{"shows":1}
,"shows":{"clear":1}
,"eth0":{"example":1,"bridge":1}
,"0202.0202.0202":{"example":1,"bridge":1}
,"learned":{"bridge":1}
,"operation":{"given":1}
}
;Search.control.loadWordPairs(pairs);
