var pairs =
{
"trill_instance_unset":{"function":1,"(u_int32_t":1}
,"function":{"deletes":1,"call":1}
,"deletes":{"specified":1}
,"specified":{"trill":1,"tag":1}
,"trill":{"router":1,"cli":1}
,"router":{"instance":1,"*name":1}
,"instance":{"called":1,"specified":1,"virtual":1}
,"called":{"rbridge":1}
,"rbridge":{"trill":1}
,"cli":{"command":1}
,"command":{"contained":1}
,"contained":{"trill_api.c":1}
,"trill_api.c":{"file":1}
,"file":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"trill_instance_unset":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"specifies":1}
,"char":{"*name)":1}
,"*name)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"specifies":{"identification":1,"name":1}
,"identification":{"virtual":1}
,"virtual":{"router":1}
,"*name":{"specifies":1}
,"name":{"interface":1}
,"interface":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"trill_api_set_success":1}
,"trill_api_set_success":{"indicates":1}
,"indicates":{"function":1,"active":1}
,"call":{"executed":1}
,"executed":{"properly":1}
,"properly":{"trill_api_set_err_instance_not_exist":1}
,"trill_api_set_err_instance_not_exist":{"indicates":1}
,"active":{"is-is":1,"instance":1}
,"is-is":{"instance":1}
,"tag":{"trill_api_set_err_tag_too_long":1,"length":1}
,"trill_api_set_err_tag_too_long":{"tag":1}
,"length":{"exceeds":1}
,"exceeds":{"characters":1}
,"characters":{"trill_api_set_err_vr_not_exist":1}
,"trill_api_set_err_vr_not_exist":{"indicates":1}
}
;Search.control.loadWordPairs(pairs);
