var pairs =
{
"show":{"ethernet":1}
,"ethernet":{"cfm":1}
,"cfm":{"maintenance-points":1}
,"maintenance-points":{"remote":1}
,"remote":{"command":1,"mep":1,"(mpid":1,"domain":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"detailed":1}
,"detailed":{"information":1}
,"information":{"remote":1}
,"mep":{"continuity":1,"mepid":1,"<1-8191>":1}
,"continuity":{"check":1}
,"check":{"database":1}
,"database":{"command":1}
,"syntax":{"show":1}
,"(mpid":{"mep_id":1}
,"mep_id":{"mac":1}
,"mac":{"mac_address":1,"specify":1,"address":1}
,"mac_address":{"(domain":1}
,"(domain":{"domain_name":1}
,"domain_name":{"level":1,"specify":1}
,"level":{"level_id)":1,"specify":1,"level":1,"<0-7>":1}
,"level_id)":{"(vlan":1}
,"(vlan":{"vlan_id":1}
,"vlan_id":{"(bridge":1,"specify":1}
,"(bridge":{"<1-32>":1}
,"<1-32>":{"parameters":1,"specify":1}
,"parameters":{"mpid":1}
,"mpid":{"remote":1,"bridge":1}
,"mepid":{"specify":1}
,"specify":{"remote":1,"mac":1,"maintenance":1,"vlan":1,"bridge":1}
,"<1-8191>":{"mac":1}
,"address":{"mac":1,"hhhh.hhhh.hhhh":1}
,"hhhh.hhhh.hhhh":{"format":1}
,"format":{"domain":1}
,"domain":{"specify":1,"name":1,"mpid":1}
,"maintenance":{"domain":1,"level":1}
,"name":{"domain_name":1,"level":1}
,"<0-7>":{"vlan":1}
,"vlan":{"specify":1,"vlan_id":1,"<2-4094>":1}
,"<2-4094>":{"bridge":1}
,"bridge":{"specify":1,"<1-32>":1,"command":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"show":1}
}
;Search.control.loadWordPairs(pairs);
