var pairs =
{
"nsm_mpls_dscp_exp_map_add":{"function":1,"(struct":1}
,"function":{"adds":1,"implements":1,"succeeds":1}
,"adds":{"class-to-exp":1}
,"class-to-exp":{"bit":1}
,"bit":{"mapping":1}
,"mapping":{"function":1}
,"implements":{"mpls":1}
,"mpls":{"class-to-exp-bit":1,"found":1}
,"class-to-exp-bit":{"command":1}
,"command":{"syntax":1}
,"syntax":{"int":1}
,"int":{"nsm_mpls_dscp_exp_map_add":1,"exp_val)":1}
,"(struct":{"nsm_master":1}
,"nsm_master":{"*nm":1}
,"*nm":{"char":1}
,"char":{"*name":1}
,"*name":{"int":1}
,"exp_val)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"pointer":1,"none":1}
,"pointer":{"nsm":1}
,"nsm":{"master":1}
,"master":{"name":1}
,"name":{"class":1}
,"class":{"alias":1,"invalid":1,"unsupported":1}
,"alias":{"exp_val":1}
,"exp_val":{"exp":1}
,"exp":{"bits":1}
,"bits":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"nsm_success":1}
,"nsm_success":{"function":1}
,"succeeds":{"nsm_failure":1}
,"nsm_failure":{"mpls":1}
,"found":{"nsm_err_dscp_invalid":1}
,"nsm_err_dscp_invalid":{"class":1}
,"invalid":{"nsm_err_dscp_not_supported":1}
,"nsm_err_dscp_not_supported":{"class":1}
}
;Search.control.loadWordPairs(pairs);
