var pairs =
{
"nsm_bridge_uni_unset_name":{"function":1,"(struct":1}
,"function":{"deletes":1,"called":1,"succeeds":1}
,"deletes":{"name":1}
,"name":{"uni":1,"nsm_invalid_uni_id":1,"match":1,"result_ok":1}
,"uni":{"function":1,"command":1,"svlan_id":1,"name":1}
,"called":{"ethernet":1}
,"ethernet":{"uni":1}
,"command":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"nsm_bridge_uni_unset_name":1}
,"(struct":{"interface":1}
,"interface":{"*ifp":1,"pointer":1,"configuration":1}
,"*ifp":{"char":1}
,"char":{"*uni_name":1,"*evc_id)":1}
,"*uni_name":{"s_int16_t":1}
,"s_int16_t":{"svlan_id":1}
,"svlan_id":{"char":1,"svlan":1}
,"*evc_id)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"none":1}
,"ifp":{"interface":1}
,"pointer":{"uni_name":1}
,"uni_name":{"name":1}
,"svlan":{"identifier":1}
,"identifier":{"<2-4094>":1,"output":1}
,"<2-4094>":{"evc_id":1}
,"evc_id":{"evc":1}
,"evc":{"identifier":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_l2_err_invalid_arg":1}
,"nsm_l2_err_invalid_arg":{"operation":1}
,"operation":{"appropriate":1}
,"appropriate":{"interface":1}
,"configuration":{"nsm_pro_vlan_err_invalid_mode":1,"nsm_no_uni_exist":1}
,"nsm_pro_vlan_err_invalid_mode":{"operation":1}
,"nsm_no_uni_exist":{"uni":1}
,"nsm_invalid_uni_id":{"given":1}
,"given":{"uni":1}
,"match":{"configured":1}
,"configured":{"uni":1}
,"result_ok":{"function":1}
}
;Search.control.loadWordPairs(pairs);
