var pairs =
{
"show":{"ptp":1}
,"ptp":{"port":1,"version":1}
,"port":{"command":1,"parameters":1,"show":1,"===========================================port":1,"clock":1,"number":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"attributes":1}
,"attributes":{"ptp":1}
,"syntax":{"show":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"exec":1,"examples":1}
,"exec":{"mode":1}
,"examples":{"following":1}
,"following":{"example":1}
,"example":{"shows":1}
,"shows":{"attributes":1}
,"===========================================port":{"state":1}
,"state":{"[ptp_listening]":1}
,"[ptp_listening]":{"port":1}
,"clock":{"identity":1}
,"identity":{"ff:fe:0:1b:21:39:6c:4a":1}
,"ff:fe:0:1b:21:39:6c:4a":{"port":1}
,"number":{"min":1}
,"min":{"delay":1}
,"delay":{"req":1,"mechanism:0":1,"request":1}
,"req":{"interval":1}
,"interval":{"(log":1}
,"(log":{"base":1}
,"base":{"peer":1,"announce":1,"delay":1,"ptp":1}
,"peer":{"mean":1,"delay":1}
,"mean":{"path":1}
,"path":{"delay:0":1}
,"delay:0":{"announce":1}
,"announce":{"interval":1,"receipt":1}
,"receipt":{"timeout":1}
,"timeout":{"sync":1}
,"sync":{"interval":1}
,"mechanism:0":{"peer":1}
,"request":{"interval":1}
}
;Search.control.loadWordPairs(pairs);
