var pairs =
{
"secondary":{"no-record":1,"record":1}
,"no-record":{"command":1,"parameters":1}
,"command":{"used":1,"revert":1,"syntax":1,"mode":1}
,"used":{"disable":1}
,"disable":{"recording":1}
,"recording":{"route":1}
,"route":{"taken":1,"record":1}
,"taken":{"path":1}
,"path":{"resv":1}
,"resv":{"messages":1}
,"messages":{"confirms":1}
,"confirms":{"establishment":1}
,"establishment":{"reservations":1}
,"reservations":{"identify":1}
,"identify":{"errors":1}
,"errors":{"routes":1}
,"routes":{"recorded":1}
,"recorded":{"means":1,"default":1}
,"means":{"route":1}
,"record":{"object":1,"command":1}
,"object":{"(rro)":1}
,"(rro)":{"rsvp":1}
,"rsvp":{"message":1}
,"message":{"secondary":1}
,"revert":{"default":1}
,"default":{"settings":1,"routes":1,"command":1}
,"settings":{"command":1}
,"syntax":{"secondary":1}
,"parameters":{"none":1}
,"none":{"default":1}
,"mode":{"trunk":1,"examples":1}
,"trunk":{"mode":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"rsvp-trunk":1}
,"rsvp-trunk":{"mytrunk":1}
,"mytrunk":{"(config-trunk)":1}
,"(config-trunk)":{"secondary":1}
}
;Search.control.loadWordPairs(pairs);
