var pairs =
{
"oam_api_lps_group_delete":{"function":1,"(u_int32_t":1}
,"function":{"deletes":1,"fails":1,"succeeds":1}
,"deletes":{"protection-group":1}
,"protection-group":{"based":1,"name":1,"lookup":1}
,"based":{"protection-group":1}
,"name":{"syntax":1,"output":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"oam_api_lps_group_delete":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"instance":1,"found":1}
,"char":{"*grp_name_str)":1}
,"*grp_name_str)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"instance":{"grp_name_str":1}
,"grp_name_str":{"protection-group":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"oam_api_set_err_invalid_value":1}
,"oam_api_set_err_invalid_value":{"value":1}
,"value":{"invalid":1}
,"invalid":{"oam_api_set_err_psc_grp_name_exceeds_max_len":1}
,"oam_api_set_err_psc_grp_name_exceeds_max_len":{"protection":1}
,"protection":{"group-name":1}
,"group-name":{"exceeds":1}
,"exceeds":{"maximum":1}
,"maximum":{"length":1}
,"length":{"oam_api_set_err_vr_not_exist":1}
,"oam_api_set_err_vr_not_exist":{"vr_id":1}
,"found":{"oam_api_set_error_psc_grp_lookup":1}
,"oam_api_set_error_psc_grp_lookup":{"protection-group":1}
,"lookup":{"fails":1}
,"fails":{"oam_api_lps_set_error":1,"due":1}
,"oam_api_lps_set_error":{"function":1}
,"due":{"internal":1}
,"internal":{"errors":1}
,"errors":{"memory":1}
,"memory":{"failure":1}
,"failure":{"oam_api_lps_set_success":1}
,"oam_api_lps_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
