var pairs =
{
"zebos-xp":{"mpls":1}
,"mpls":{"forwarder":1,"label":1,"divides":1,"supports":1}
,"forwarder":{"mpls":1,"swaps":1}
,"label":{"swapping":1,"routers":1,"values":1,"switching":1,"distribution":1}
,"swapping":{"forwarding":1}
,"forwarding":{"technology":1,"labeled":1}
,"technology":{"every":1}
,"every":{"packet":1}
,"packet":{"contains":1}
,"contains":{"short":1}
,"short":{"fixed-length":1}
,"fixed-length":{"label":1}
,"routers":{"label":1,"(lsrs)":1}
,"values":{"forward":1}
,"forward":{"incoming":1}
,"incoming":{"packets":1,"labels":1}
,"packets":{"destination":1,"mpls":1,"outgoing":1}
,"destination":{"mpls":1}
,"divides":{"functions":1}
,"functions":{"two":1}
,"two":{"distinct":1}
,"distinct":{"categories":1}
,"categories":{"assigning":1}
,"assigning":{"exchanging":1}
,"exchanging":{"labels":1}
,"labels":{"label":1,"outgoing":1,"forwards":1}
,"switching":{"routers":1}
,"(lsrs)":{"label":1}
,"distribution":{"protocol":1}
,"protocol":{"(ldp)":1}
,"(ldp)":{"forwarding":1}
,"labeled":{"packets":1}
,"swaps":{"incoming":1}
,"outgoing":{"labels":1,"interface":1}
,"forwards":{"resulting":1}
,"resulting":{"packets":1}
,"interface":{"mpls":1}
,"supports":{"ethernet":1}
,"ethernet":{"interface":1}
}
;Search.control.loadWordPairs(pairs);
