var pairs =
{
"nsm_vlan_set_acceptable_frame_type":{"function":1,"(struct":1}
,"function":{"sets":1,"fails":1,"succeeds":1}
,"sets":{"acceptable":1}
,"acceptable":{"frame":1,"frames":1}
,"frame":{"types":1}
,"types":{"port":1}
,"port":{"syntax":1,"mode":1}
,"syntax":{"int":1}
,"int":{"nsm_vlan_set_acceptable_frame_type":1,"acceptable_frame_type)":1}
,"(struct":{"interface":1}
,"interface":{"*ifp":1,"pointer":1,"found":1}
,"*ifp":{"enum":1}
,"enum":{"nsm_vlan_port_mode":1}
,"nsm_vlan_port_mode":{"mode":1}
,"mode":{"int":1,"vlan":1,"(trunk":1}
,"acceptable_frame_type)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"none":1}
,"ifp":{"interface":1}
,"pointer":{"mode":1}
,"vlan":{"port":1}
,"(trunk":{"hybrid":1}
,"hybrid":{"access)":1}
,"access)":{"acceptable_frame_type":1}
,"acceptable_frame_type":{"acceptable":1}
,"frames":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1,"value":1}
,"values":{"(error)":1}
,"(error)":{"function":1}
,"fails":{"(error":1}
,"(error":{"found":1}
,"found":{"configuration)":1}
,"configuration)":{"function":1}
,"succeeds":{"return":1}
,"value":{"hal":1}
,"hal":{"(if":1,"used)":1}
,"(if":{"hal":1}
,"used)":{"nsm_vlan_err_ifp_not_bound":1}
,"nsm_vlan_err_ifp_not_bound":{"nsm":1}
,"nsm":{"local":1}
,"local":{"interface":1}
}
;Search.control.loadWordPairs(pairs);
