var pairs =
{
"authentication":{"is-is":1,"inclusion":1,"information":1,"algorithm":1,"type":1,"methods":1,"value":1}
,"is-is":{"protocol":1}
,"protocol":{"specified":1}
,"specified":{"iso":1,"tlv":1}
,"iso":{"10589":1}
,"10589":{"[1]":1}
,"[1]":{"provides":1}
,"provides":{"lsp":1}
,"lsp":{"authentication":1}
,"inclusion":{"authentication":1}
,"information":{"part":1,"encoded":1,"used":1}
,"part":{"lsp":1}
,"encoded":{"type-length-value":1}
,"type-length-value":{"(tlv)":1}
,"(tlv)":{"tuple":1}
,"tuple":{"tlv":1}
,"tlv":{"type":1,"length":1,"depends":1,"value":1}
,"type":{"specified":1,"type":1,"indicates":1,"255":1}
,"length":{"variable":1}
,"variable":{"value":1}
,"value":{"tlv":1,"specifies":1,"authentication":1}
,"depends":{"authentication":1}
,"algorithm":{"related":1}
,"related":{"confidential":1}
,"confidential":{"information":1}
,"used":{"first":1,"routing":1}
,"first":{"octet":1}
,"octet":{"value":1}
,"specifies":{"authentication":1}
,"indicates":{"clear":1}
,"clear":{"text":1}
,"text":{"password":1}
,"password":{"type":1}
,"255":{"used":1}
,"routing":{"domain":1}
,"domain":{"private":1}
,"private":{"authentication":1}
,"methods":{"remainder":1}
,"remainder":{"tlv":1}
}
;Search.control.loadWordPairs(pairs);
