var pairs =
{
"timers":{"lsa":1}
,"lsa":{"arrival":1,"neighbors":1}
,"arrival":{"command":1,"<0-600000>":1,"parameters":1,"5000":1}
,"command":{"sets":1,"restore":1,"syntax":1,"mode":1}
,"sets":{"minimum":1}
,"minimum":{"interval":1,"delay":1}
,"interval":{"accept":1}
,"accept":{"link-state":1}
,"link-state":{"advertisement":1}
,"advertisement":{"(lsa)":1}
,"(lsa)":{"ospf":1}
,"ospf":{"neighbors":1,"100":1}
,"neighbors":{"form":1,"default":1}
,"form":{"command":1}
,"restore":{"default":1}
,"default":{"value":1,"1000":1}
,"value":{"command":1}
,"syntax":{"timers":1}
,"<0-600000>":{"timers":1,"minimum":1}
,"parameters":{"<0-600000>":1}
,"delay":{"milliseconds":1}
,"milliseconds":{"accepting":1,"command":1}
,"accepting":{"lsa":1}
,"1000":{"milliseconds":1}
,"mode":{"router":1,"examples":1}
,"router":{"mode":1,"ospf":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"100":{"(config-router)":1}
,"(config-router)":{"timers":1}
}
;Search.control.loadWordPairs(pairs);
