var pairs =
{
"ldp_api_clear_advert_list":{"call":1,"(struct":1}
,"call":{"clears":1}
,"clears":{"advertise":1}
,"advertise":{"list":1}
,"list":{"syntax":1,"name":1}
,"syntax":{"int":1}
,"int":{"ldp_api_clear_advert_list":1}
,"(struct":{"cli":1}
,"cli":{"*cli":1,"pointer":1,"structure":1}
,"*cli":{"struct":1}
,"struct":{"ldp_adv_list_master":1}
,"ldp_adv_list_master":{"*master":1}
,"*master":{"char":1}
,"char":{"*prefix_acl":1,"*peer_acl)":1}
,"*prefix_acl":{"char":1}
,"*peer_acl)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"cli":1,"none":1}
,"pointer":{"cli":1}
,"structure":{"master":1,"prefix_acl":1}
,"master":{"master":1,"data":1}
,"data":{"structure":1}
,"prefix_acl":{"prefix":1}
,"prefix":{"access":1}
,"access":{"control":1}
,"control":{"list":1}
,"name":{"peer_acl":1,"output":1}
,"peer_acl":{"peer":1}
,"peer":{"access":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"cli_success":1}
,"cli_success":{"clear":1}
,"clear":{"successful":1}
,"successful":{"cli_error":1}
,"cli_error":{"clear":1}
}
;Search.control.loadWordPairs(pairs);
