var pairs =
{
"dcb-pfc":{"functions":1,"(priority-based":1,"hal_dcb_pfc_bridge_disable":1,"hal_dcb_pfc_interface_enable":1,"hal_dcb_pfc_interface_disable":1,"hal_dcb_enable_pfc_priority":1,"hal_dcb_disable_pfc_priority":1,"hal_dcb_set_pfc_cap":1,"switch":1,"interface":1}
,"functions":{"chapter":1}
,"chapter":{"contains":1}
,"contains":{"apis":1}
,"apis":{"dcb-pfc":1,"function":1}
,"(priority-based":{"flow":1}
,"flow":{"control)":1}
,"control)":{"includes":1}
,"includes":{"following":1}
,"following":{"apis":1}
,"function":{"description":1}
,"description":{"hal_dcb_get_pfc_stats":1}
,"hal_dcb_get_pfc_stats":{"sends":1}
,"sends":{"hal_msg_dcb_pfc_stats":1,"hal_msg_dcb_pfc_enable":1,"hal_msg_dcb_pfc_disable":1,"hal_msg_dcb_pfc_if_enable":1,"hal_msg_dcb_pfc_if_disable":1,"hal_msg_dcb_pfc_add_pri":1,"hal_msg_dcb_pfc_del_pri":1,"hal_msg_dcb_pfc_cap_set":1,"hal_msg_dcb_pfc_link_delay_allowance":1}
,"hal_msg_dcb_pfc_stats":{"message":1}
,"message":{"hsl":1}
,"hsl":{"hal_dcb_pfc_bridge_enable":1,"enable":1,"disable":1,"hal_dcb_select_pfc_mode":1,"hal_dcb_set_pfc_lda":1,"nsm_dcb_init_interface":1}
,"hal_dcb_pfc_bridge_enable":{"sends":1}
,"hal_msg_dcb_pfc_enable":{"message":1}
,"enable":{"dcb-pfc":1}
,"hal_dcb_pfc_bridge_disable":{"sends":1}
,"hal_msg_dcb_pfc_disable":{"message":1}
,"disable":{"dcb-pfc":1}
,"hal_dcb_pfc_interface_enable":{"sends":1}
,"hal_msg_dcb_pfc_if_enable":{"message":1}
,"hal_dcb_pfc_interface_disable":{"sends":1}
,"hal_msg_dcb_pfc_if_disable":{"message":1}
,"hal_dcb_enable_pfc_priority":{"sends":1}
,"hal_msg_dcb_pfc_add_pri":{"message":1}
,"hal_dcb_disable_pfc_priority":{"sends":1}
,"hal_msg_dcb_pfc_del_pri":{"message":1}
,"hal_dcb_set_pfc_cap":{"sends":1}
,"hal_msg_dcb_pfc_cap_set":{"message":1}
,"hal_dcb_select_pfc_mode":{"send":1}
,"send":{"hal_msg_dcb_pfc_select_mode":1}
,"hal_msg_dcb_pfc_select_mode":{"message":1}
,"hal_dcb_set_pfc_lda":{"sends":1}
,"hal_msg_dcb_pfc_link_delay_allowance":{"message":1}
,"nsm_dcb_init_interface":{"initializes":1}
,"initializes":{"traffic":1}
,"traffic":{"class":1}
,"class":{"group":1}
,"group":{"settings":1}
,"settings":{"interface":1}
,"interface":{"default":1,"nsm_dcb_pfc_bridge_disable":1,"nsm_dcb_pfc_enable_interface":1,"nsm_dcb_pfc_set_advertise_interface":1,"nsm_dcb_pfc_set_willing_interface":1,"nsm_dcb_add_pfc_priority":1,"nsm_dcb_remove_pfc_priority":1,"nsm_dcb_set_pfc_cap":1,"pfc":1,"nsm_dcb_show_pfc_details_by_bridge":1,"nsm_dcb_show_pfc_stats_by_bridge":1,"check_interface_pfc_state":1,"nsm_dcb_update_pfc_xchg_config":1,"node":1}
,"default":{"values":1}
,"values":{"nsm_dcb_deinit_interface":1}
,"nsm_dcb_deinit_interface":{"de-initializes":1}
,"de-initializes":{"traffic":1}
,"nsm_dcb_pfc_bridge_disable":{"disables":1}
,"disables":{"dcb-pfc":1,"pfc":1}
,"switch":{"level":1}
,"level":{"nsm_dcb_pfc_bridge_enable":1,"nsm_dcb_pfc_disable_interface":1}
,"nsm_dcb_pfc_bridge_enable":{"enables":1}
,"enables":{"dcb-pfc":1,"pfc":1,"advertise":1,"willing":1}
,"nsm_dcb_pfc_disable_interface":{"disables":1}
,"nsm_dcb_pfc_enable_interface":{"enables":1}
,"pfc":{"interface":1,"priorities":1,"nsm_dcb_set_pfc_lda":1,"link":1,"details":1,"requests":1,"state":1,"dcb":1}
,"nsm_dcb_pfc_set_advertise_interface":{"enables":1}
,"advertise":{"setting":1}
,"setting":{"pfc":1}
,"nsm_dcb_pfc_set_willing_interface":{"enables":1}
,"willing":{"setting":1}
,"nsm_dcb_add_pfc_priority":{"enables":1}
,"priorities":{"interface":1,"enabled":1}
,"nsm_dcb_remove_pfc_priority":{"disables":1}
,"nsm_dcb_set_pfc_cap":{"sets":1}
,"sets":{"maximum":1,"pfc":1}
,"maximum":{"number":1}
,"number":{"priorities":1}
,"enabled":{"interface":1}
,"nsm_dcb_set_pfc_lda":{"sets":1}
,"link":{"delay":1}
,"delay":{"allowance":1}
,"allowance":{"interface":1}
,"nsm_dcb_show_pfc_details_by_bridge":{"displays":1}
,"displays":{"pfc":1,"statistics":1}
,"details":{"given":1}
,"given":{"bridge":1,"interface":1}
,"bridge":{"nsm_dcb_show_pfc_details_by_interface":1,"nsm_dcb_show_pfc_stats_by_interface":1}
,"nsm_dcb_show_pfc_details_by_interface":{"displays":1}
,"nsm_dcb_show_pfc_stats_by_bridge":{"displays":1}
,"statistics":{"pfc":1}
,"requests":{"sent":1}
,"sent":{"given":1}
,"nsm_dcb_show_pfc_stats_by_interface":{"displays":1}
,"check_interface_pfc_state":{"checks":1}
,"checks":{"pfc":1}
,"state":{"interface":1}
,"nsm_dcb_update_pfc_xchg_config":{"allows":1}
,"allows":{"dcbx":1}
,"dcbx":{"apply":1,"exchanged":1}
,"apply":{"configuration":1}
,"configuration":{"operating":1,"nsm_dcb_apply_pfc_config":1,"hardware":1,"nsm_dcb_avl_traverse_disable_pfc":1}
,"operating":{"configuration":1}
,"nsm_dcb_apply_pfc_config":{"updates":1}
,"updates":{"dcbx":1,"configuration":1}
,"exchanged":{"parameter":1}
,"parameter":{"updates":1}
,"hardware":{"directly":1}
,"directly":{"local":1}
,"local":{"configuration":1}
,"nsm_dcb_avl_traverse_disable_pfc":{"disables":1}
,"dcb":{"interface":1}
,"node":{"information":1}
}
;Search.control.loadWordPairs(pairs);
