var pairs =
{
"ipi_mpls_vc4_fib_add":{"function":1,"(u_int32_t":1}
,"function":{"adds":1}
,"adds":{"specified":1}
,"specified":{"ipv4":1}
,"ipv4":{"virtual":1}
,"virtual":{"circuit":1}
,"circuit":{"forwarding":1,"configured":1,"style":1,"bounded":1,"network":1,"peer_nhop_addr":1,"peer":1,"tunnel":1,"binding":1}
,"forwarding":{"entry":1}
,"entry":{"mpls":1,"operational":1}
,"mpls":{"forwarder":1}
,"forwarder":{"syntax":1,"fec_prefixlen":1}
,"syntax":{"int":1}
,"int":{"ipi_mpls_vc4_fib_add":1}
,"(u_int32_t":{"vc_id":1}
,"vc_id":{"u_int32_t":1,"identifier":1}
,"u_int32_t":{"vc_style":1,"*vpls_id":1,"*in_label":1,"*out_label":1,"*ac_if_ix":1,"*nw_if_ix":1,"*tunnel_label":1,"*tunnel_oix":1,"*tunnel_nhlfe_ix":1,"*tunnel_ftnix":1,"vlan_id":1}
,"vc_style":{"u_int32_t":1,"virtual":1}
,"*vpls_id":{"u_int32_t":1}
,"*in_label":{"u_int32_t":1}
,"*out_label":{"u_int32_t":1}
,"*ac_if_ix":{"u_int32_t":1}
,"*nw_if_ix":{"struct":1}
,"struct":{"if_ident":1,"pal_in4_addr":1}
,"if_ident":{"*if_in":1,"*if_out":1,"*if_tnl_in":1}
,"*if_in":{"struct":1}
,"*if_out":{"struct":1}
,"*if_tnl_in":{"u_char":1}
,"u_char":{"opcode":1,"*fec_prefixlen":1}
,"opcode":{"struct":1,"virtual":1}
,"pal_in4_addr":{"*peer_addr":1,"*peer_nhop_addr":1,"*fec_addr":1,"*tunnel_nhop":1}
,"*peer_addr":{"struct":1}
,"*peer_nhop_addr":{"struct":1}
,"*fec_addr":{"u_char":1}
,"*fec_prefixlen":{"u_int32_t":1}
,"*tunnel_label":{"struct":1}
,"*tunnel_nhop":{"u_int32_t":1}
,"*tunnel_oix":{"u_int32_t":1}
,"*tunnel_nhlfe_ix":{"u_int32_t":1}
,"*tunnel_ftnix":{"ifdef":1,"pass":1}
,"ifdef":{"have_mpls_tp":1}
,"have_mpls_tp":{"u_int32_t":1}
,"vlan_id":{"u_int8_t":1,"vlan":1}
,"u_int8_t":{"*nh_mac":1}
,"*nh_mac":{"endif\u002F*have_mpls_tp":1,"nexthop":1}
,"endif\u002F*have_mpls_tp":{"*\u002Fu_int8_t":1}
,"*\u002Fu_int8_t":{"is_ms_pw)":1}
,"is_ms_pw)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vc_id":1,"data":1}
,"identifier":{"virtual":1,"in_label":1}
,"configured":{"vc_style":1}
,"style":{"martini":1}
,"martini":{"vpls":1}
,"vpls":{"mesh":1,"spoke":1,"identifier":1}
,"mesh":{"vpls":1}
,"spoke":{"vpls_id":1}
,"vpls_id":{"vpls":1}
,"in_label":{"incoming":1}
,"incoming":{"label":1,"interface":1}
,"label":{"out_label":1,"ac_if_ix":1,"tunnel_nhop":1,"vlan_id":1}
,"out_label":{"outgoing":1}
,"outgoing":{"label":1,"interface":1}
,"ac_if_ix":{"virtual":1}
,"bounded":{"access":1}
,"access":{"interface":1}
,"interface":{"index":1,"if_out":1,"if_tnl_in":1,"opcode":1,"status":1}
,"index":{"nw_if_ix":1,"if_in":1,"virtual":1}
,"nw_if_ix":{"virtual":1}
,"network":{"side":1}
,"side":{"interface":1}
,"if_in":{"identifying":1}
,"identifying":{"object":1}
,"object":{"incoming":1,"outgoing":1,"tunnel":1}
,"if_out":{"identifying":1}
,"if_tnl_in":{"identifying":1}
,"tunnel":{"interface":1,"label":1,"tunnel_oix":1,"ftn":1}
,"operational":{"code":1}
,"code":{"push_for_vc":1}
,"push_for_vc":{"push_and_lookup_for_vc":1}
,"push_and_lookup_for_vc":{"peer_addr":1}
,"peer_addr":{"peer":1}
,"peer":{"address":1,"fec_addr":1}
,"address":{"virtual":1,"reach":1,"referring":1,"prefix":1,"is_ms_pw":1}
,"peer_nhop_addr":{"next-hop":1}
,"next-hop":{"address":1,"virtual":1}
,"reach":{"virtual":1}
,"fec_addr":{"prefix":1}
,"prefix":{"address":1,"length":1}
,"referring":{"ilm":1}
,"ilm":{"entry":1}
,"fec_prefixlen":{"fec":1}
,"fec":{"address":1}
,"length":{"tunnel_label":1}
,"tunnel_label":{"virtual":1}
,"tunnel_nhop":{"next-hop":1}
,"tunnel_oix":{"outgoing":1}
,"ftn":{"tunnel_nhlfe_ix":1,"*tunnel_ftnix":1}
,"tunnel_nhlfe_ix":{"nhlfe":1}
,"nhlfe":{"index":1}
,"pass":{"tunnel":1}
,"vlan":{"*nh_mac":1}
,"nexthop":{"mac":1}
,"mac":{"address":1}
,"is_ms_pw":{"output":1}
,"output":{"parameters":1}
,"data":{"returned":1}
,"returned":{"call":1}
,"call":{"return":1,"virtual":1}
,"return":{"value":1}
,"value":{"status":1}
,"status":{"call":1}
,"binding":{"removed":1}
,"removed":{"interface":1}
}
;Search.control.loadWordPairs(pairs);
