var pairs =
{
"pal_kernel_virtual_ipv4_add":{"function":1,"(struct":1}
,"function":{"adds":1}
,"adds":{"virtual":1}
,"virtual":{"address":1,"ipv4":1,"router":1}
,"address":{"specified":1,"ifp":1,"vrid":1,"successful":1}
,"specified":{"interface":1}
,"interface":{"syntax":1,"*ifp":1,"vip":1}
,"syntax":{"result_t":1}
,"result_t":{"pal_kernel_virtual_ipv4_add":1}
,"(struct":{"lib_globals":1}
,"lib_globals":{"*lib_node":1}
,"*lib_node":{"struct":1}
,"struct":{"pal_in4_addr":1,"interface":1}
,"pal_in4_addr":{"*vip":1}
,"*vip":{"struct":1}
,"*ifp":{"bool_t":1}
,"bool_t":{"owner":1}
,"owner":{"u_int8_t":1,"owner":1,"status":1}
,"u_int8_t":{"vrid)":1}
,"vrid)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"lib_node":1,"none":1}
,"lib_node":{"global":1}
,"global":{"variables":1}
,"variables":{"vip":1}
,"vip":{"virtual":1,"added":1}
,"ipv4":{"address":1}
,"ifp":{"pointer":1}
,"pointer":{"interface":1}
,"added":{"owner":1}
,"status":{"address":1}
,"vrid":{"vrrp":1}
,"vrrp":{"virtual":1}
,"router":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"result_ok":1}
,"result_ok":{"insertion":1}
,"insertion":{"address":1}
,"successful":{"vrrp_failure":1}
,"vrrp_failure":{"error":1}
,"error":{"flags":1}
}
;Search.control.loadWordPairs(pairs);
