var pairs =
{
"root-priority":{"command":1,"<0-65535>":1,"parameters":1,"155":1}
,"command":{"configure":1,"reset":1,"syntax":1,"mode":1}
,"configure":{"nickname":1,"terminal":1}
,"nickname":{"root":1,"root-priority":1,"specify":1,"value":1,"123":1}
,"root":{"priority":1}
,"priority":{"parameter":1,"nickname":1}
,"parameter":{"command":1}
,"reset":{"configuration":1}
,"configuration":{"command":1}
,"syntax":{"root-priority":1}
,"<0-65535>":{"nickname":1,"specify":1}
,"parameters":{"<0-65535>":1}
,"specify":{"actual":1}
,"actual":{"root":1,"nickname":1}
,"value":{"hexadecimal":1}
,"hexadecimal":{"range":1}
,"range":{"command":1}
,"mode":{"rbridge":1,"examples":1}
,"rbridge":{"mode":1,"trill":1}
,"examples":{"enable":1}
,"enable":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"bridge":1,"rbridge":1}
,"bridge":{"protocol":1}
,"protocol":{"trill":1}
,"trill":{"(config)":1,"(config-rb)":1}
,"(config-rb)":{"root-priority":1}
,"155":{"nickname":1}
,"123":{"(config-rb)":1}
}
;Search.control.loadWordPairs(pairs);
