var pairs =
{
"hal_mpls_vpls_if_unbind":{"function":1,"(u_int32_t":1}
,"function":{"unbinds":1,"fails":1,"succeeds":1}
,"unbinds":{"vpls":1}
,"vpls":{"entry":1,"identifier":1,"vlan_id":1}
,"entry":{"interface":1}
,"interface":{"syntax":1,"index":1}
,"syntax":{"int":1}
,"int":{"hal_mpls_vpls_if_unbind":1}
,"(u_int32_t":{"vpls_id":1}
,"vpls_id":{"u_int32_t":1,"vpls":1}
,"u_int32_t":{"ifindex":1}
,"ifindex":{"u_int16_t":1,"interface":1}
,"u_int16_t":{"vlan_id)":1}
,"vlan_id)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vpls_id":1,"none":1}
,"identifier":{"ifindex":1,"output":1}
,"index":{"bound":1}
,"bound":{"vpls":1}
,"vlan_id":{"vlan":1}
,"vlan":{"identifier":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"hal_mpls_vpls_if_bind_err":1}
,"hal_mpls_vpls_if_bind_err":{"function":1}
,"fails":{"hal_success":1}
,"hal_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
