var pairs =
{
"fast":{"reroute":1}
,"reroute":{"terminology":1,"fast":1,"(frr)":1}
,"terminology":{"fast":1}
,"(frr)":{"refers":1}
,"refers":{"redirection":1,"techniques":1}
,"redirection":{"traffic":1}
,"traffic":{"onto":1,"protected":1}
,"onto":{"backup":1}
,"backup":{"lsps":1,"one-to-one":1,"method":1,"(or":1,"facility":1,"lsp":1,"tunnel":1,"scenario":1}
,"lsps":{"event":1,"traverse":1,"link":1,"passing":1,"rejoin":1}
,"event":{"failure":1}
,"failure":{"one-to-one":1,"protected":1,"acts":1}
,"one-to-one":{"backup":1}
,"method":{"creates":1,"backup":1}
,"creates":{"backup":1}
,"(or":{"detour)":1}
,"detour)":{"lsp":1}
,"lsp":{"protected":1,"potential":1,"(bypass":1,"lsr":1,"used":1,"lsp":1,"termed":1,"detour":1,"one-to-one":1,"downstream":1}
,"protected":{"lsp":1,"lsps":1,"merge":1,"given":1}
,"potential":{"point":1,"failure":1}
,"point":{"local":1,"order":1,"merge":1,"(mp)":1}
,"local":{"repair":1}
,"repair":{"(plr)":1,"local":1,"refers":1,"protected":1,"point":1}
,"(plr)":{"facility":1,"lsr":1}
,"facility":{"backup":1,"merge":1}
,"(bypass":{"tunnel)":1}
,"tunnel)":{"created":1}
,"created":{"protect":1}
,"protect":{"protected":1,"lsps":1}
,"traverse":{"plr":1}
,"plr":{"resource":1}
,"resource":{"protected":1}
,"merge":{"point":1}
,"order":{"local":1}
,"techniques":{"used":1}
,"used":{"repair":1,"redirected":1,"backing":1,"protect":1}
,"link":{"node":1}
,"node":{"along":1,"network":1,"detour":1,"backup":1}
,"along":{"path":1}
,"path":{"fails":1,"protected":1}
,"fails":{"point":1}
,"lsr":{"initiates":1,"head":1}
,"initiates":{"frr":1}
,"frr":{"procedures":1}
,"procedures":{"event":1}
,"head":{"end":1}
,"end":{"designated":1}
,"designated":{"backup":1}
,"redirected":{"traffic":1}
,"termed":{"protected":1}
,"given":{"node":1,"protected":1}
,"network":{"least":1}
,"least":{"backup":1}
,"tunnel":{"originating":1,"bypass":1,"used":1}
,"originating":{"node":1}
,"detour":{"lsp":1}
,"backing":{"given":1}
,"scenario":{"bypass":1}
,"bypass":{"tunnel":1,"tunnels":1}
,"passing":{"common":1}
,"common":{"facility":1}
,"(mp)":{"node":1}
,"rejoin":{"path":1}
,"downstream":{"potential":1}
,"acts":{"egress":1}
,"egress":{"bypass":1}
}
;Search.control.loadWordPairs(pairs);
