var pairs =
{
"mpls-tp":{"test":1}
,"test":{"command":1,"signal":1,"(meg-name":1,"pattern":1,"meg-name":1}
,"command":{"send":1,"syntax":1,"mode":1}
,"send":{"itut":1,"test":1}
,"itut":{"test":1}
,"signal":{"command":1}
,"syntax":{"mpls-tp":1}
,"(meg-name":{"name":1}
,"name":{"mep-id":1,"maintenance":1,"1-48":1}
,"mep-id":{"<1-8191>":1,"123":1}
,"<1-8191>":{"(in-service":1,"maintenance":1}
,"(in-service":{"out-of-service)":1}
,"out-of-service)":{"test-pattern":1}
,"test-pattern":{"4))":1,"test":1,"duration":1}
,"4))":{"({duration":1}
,"({duration":{"<5-60>":1}
,"<5-60>":{"interval":1,"duration":1}
,"interval":{"<1-5>}":1,"interval":1,"packets":1}
,"<1-5>}":{"parameters":1}
,"parameters":{"name":1}
,"maintenance":{"entity":1}
,"entity":{"group":1}
,"group":{"(meg)":1,"end":1}
,"(meg)":{"name":1}
,"1-48":{"characters":1}
,"characters":{"<1-8191>":1}
,"end":{"point":1}
,"point":{"(mep)":1}
,"(mep)":{"identifier":1}
,"identifier":{"in-service":1}
,"in-service":{"in-service":1,"testing":1,"test-pattern":1}
,"testing":{"out-of-service":1,"test-pattern":1}
,"out-of-service":{"out-of-service":1,"testing":1}
,"pattern":{"send":1,"abc":1,"1234":1,"a1b2c":1,"1a2b3c":1}
,"abc":{"test":1}
,"1234":{"test":1}
,"a1b2c":{"test":1}
,"1a2b3c":{"<5-60>":1}
,"duration":{"session":1,"interval":1}
,"session":{"seconds":1}
,"seconds":{"interval":1,"seconds":1,"command":1}
,"packets":{"milliseconds":1}
,"milliseconds":{"100":1,"second":1}
,"100":{"milliseconds":1}
,"second":{"seconds":1}
,"mode":{"exec":1,"examples":1}
,"exec":{"mode":1}
,"examples":{"mpls-tp":1}
,"meg-name":{"new":1}
,"new":{"mep-id":1}
,"123":{"in-service":1}
}
;Search.control.loadWordPairs(pairs);
