var pairs =
{
"configure":{"terminal":1,"mode":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"route-map":1}
,"mode":{"(config)":1,"match":1,"return":1}
,"(config)":{"prefix-list":1,"route-map":1,"router":1}
,"prefix-list":{"ipi":1}
,"ipi":{"seq":1,"parameter":1,"map":1,"permit":1,"match":1,"packets":1,"apply":1}
,"seq":{"deny":1,"permit":1}
,"deny":{"1.1.1.0\u002F24":1,"specifies":1}
,"1.1.1.0\u002F24":{"create":1}
,"create":{"entry":1}
,"entry":{"prefix-list":1,"ipi":1}
,"parameter":{"name":1,"specifies":1}
,"name":{"map":1,"matches":1,"route":1}
,"map":{"created":1,"deny":1,"specifies":1,"permit":1,"routes":1}
,"created":{"above":1}
,"above":{"specifies":1}
,"specifies":{"sequence":1,"packets":1,"accept":1,"number":1,"address":1,"access":1}
,"sequence":{"number":1,"denied":1}
,"number":{"position":1,"specifies":1,"(config-router)":1}
,"position":{"specific":1}
,"specific":{"route":1}
,"route":{"map":1}
,"packets":{"rejected":1,"length":1,"first":1}
,"rejected":{"minimum":1}
,"minimum":{"maximum":1}
,"maximum":{"prefix":1}
,"prefix":{"lengths":1}
,"lengths":{"matched":1}
,"matched":{"(config)":1}
,"permit":{"create":1,"parameter":1,"enter":1}
,"accept":{"packets":1}
,"length":{"(config)":1}
,"route-map":{"ipi":1,"mode":1,"name":1}
,"match":{"operation":1,"address":1,"criteria":1}
,"operation":{"(config-route-map)":1}
,"(config-route-map)":{"match":1,"exit":1}
,"address":{"prefix-list":1,"neighbor":1,"bgp":1}
,"criteria":{"case":1}
,"case":{"route-map":1}
,"matches":{"ipi":1}
,"first":{"sequence":1}
,"denied":{"(config-route-map)":1}
,"exit":{"exit":1,"route-map":1}
,"return":{"configure":1}
,"router":{"bgp":1}
,"bgp":{"define":1,"neighbors":1,"neighbor":1}
,"define":{"routing":1,"bgp":1}
,"routing":{"process":1}
,"process":{"establish":1}
,"establish":{"tcp":1}
,"tcp":{"session":1}
,"session":{"number":1,"192.168.10.11":1}
,"(config-router)":{"neighbor":1}
,"neighbor":{"192.168.10.11":1,"(r2)":1,"ipi":1}
,"192.168.10.11":{"remote-as":1,"address":1,"route-map":1,"specifies":1}
,"remote-as":{"define":1}
,"neighbors":{"establish":1}
,"(r2)":{"neighbor\u2019s":1}
,"neighbor\u2019s":{"number":1}
,"apply":{"route":1}
,"routes":{"192.168.10.11":1}
,"access":{"list":1}
,"list":{"applies":1}
,"applies":{"incoming":1}
,"incoming":{"advertisements":1}
}
;Search.control.loadWordPairs(pairs);
