var pairs =
{
"ospfv3":{"commands":1,"flood-reduction":1,"topology":1}
,"commands":{"chapter":1,"includes":1,"abr-type":1}
,"chapter":{"provides":1}
,"provides":{"alphabetized":1}
,"alphabetized":{"reference":1}
,"reference":{"ospfv3":1,"bandwidth":1}
,"includes":{"following":1}
,"following":{"commands":1}
,"abr-type":{"address-family":1}
,"address-family":{"ipv4":1}
,"ipv4":{"unicast":1}
,"unicast":{"area":1}
,"area":{"default-cost":1,"nssa":1,"range":1,"stub":1,"virtual-link":1}
,"default-cost":{"area":1}
,"nssa":{"area":1}
,"range":{"area":1}
,"stub":{"area":1}
,"virtual-link":{"auto-cost":1}
,"auto-cost":{"reference":1}
,"bandwidth":{"capability":1}
,"capability":{"cspf":1,"restart":1}
,"cspf":{"capability":1}
,"restart":{"clear":1,"grace-period":1,"helper":1,"ipv6":1,"ospf6":1}
,"clear":{"ipv6":1}
,"ipv6":{"ospf":1,"router":1,"te-metric":1,"route":1,"ospfv3":1,"vrf":1}
,"ospf":{"process":1,"debug":1,"bfd":1,"events":1,"ifsm":1,"lfa":1,"lsa":1,"nfsm":1,"nsm":1,"packet":1,"retransmission":1,"rib":1,"route":1,"dead-interval":1,"demand-circuit":1,"display":1,"fast-reroute":1,"flood-reduction":1,"link-lsa-suppression":1,"mtu-ignore":1,"neighbor":1,"network":1,"priority":1,"restart":1,"retransmit-interval":1,"transmit-delay":1,"ipv6":1,"graceful":1,"show":1,"database":1,"interface":1,"virtual-links":1}
,"process":{"debug":1}
,"debug":{"ipv6":1}
,"bfd":{"debug":1}
,"events":{"debug":1}
,"ifsm":{"debug":1}
,"lfa":{"debug":1}
,"lsa":{"debug":1}
,"nfsm":{"debug":1}
,"nsm":{"debug":1}
,"packet":{"debug":1}
,"retransmission":{"debug":1}
,"rib":{"debug":1}
,"route":{"default-information":1,"single-line":1,"show":1,"fast-reroute":1}
,"default-information":{"originate":1}
,"originate":{"default-metric":1}
,"default-metric":{"distance":1}
,"distance":{"distribute-list":1}
,"distribute-list":{"enable":1}
,"enable":{"db-summary-opt":1}
,"db-summary-opt":{"exit-address-family":1}
,"exit-address-family":{"fast-reroute":1}
,"fast-reroute":{"keep-all-paths":1,"tie-break":1,"per-prefix":1,"show":1}
,"keep-all-paths":{"fast-reroute":1}
,"tie-break":{"ipv6":1}
,"dead-interval":{"ipv6":1}
,"demand-circuit":{"ipv6":1}
,"display":{"route":1}
,"single-line":{"ipv6":1}
,"per-prefix":{"candidate":1}
,"candidate":{"disable":1}
,"disable":{"ipv6":1}
,"flood-reduction":{"ipv6":1,"passive-interface":1}
,"link-lsa-suppression":{"ipv6":1}
,"mtu-ignore":{"ipv6":1}
,"neighbor":{"ipv6":1,"show":1}
,"network":{"ipv6":1}
,"priority":{"ipv6":1}
,"grace-period":{"ipv6":1}
,"helper":{"ipv6":1}
,"retransmit-interval":{"ipv6":1}
,"transmit-delay":{"ipv6":1}
,"router":{"ospf":1,"ipv6":1}
,"te-metric":{"max-concurrent-dd":1}
,"max-concurrent-dd":{"ospfv3":1}
,"passive-interface":{"redistribute":1}
,"redistribute":{"restart":1}
,"graceful":{"router-id":1}
,"router-id":{"router":1}
,"show":{"debugging":1,"ipv6":1}
,"debugging":{"ipv6":1}
,"database":{"show":1}
,"interface":{"show":1}
,"topology":{"show":1}
,"virtual-links":{"show":1}
,"vrf":{"snmp":1}
,"snmp":{"restart":1}
,"ospf6":{"summary-address":1}
}
;Search.control.loadWordPairs(pairs);
