var pairs =
{
"hal_arp_entry_refresh":{"function":1,"(struct":1}
,"function":{"refreshes":1,"fails":1,"succeeds":1}
,"refreshes":{"arp":1}
,"arp":{"entries":1}
,"entries":{"syntax":1}
,"syntax":{"int":1}
,"int":{"hal_arp_entry_refresh":1}
,"(struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"*ipaddr":1}
,"*ipaddr":{"unsigned":1}
,"unsigned":{"char":1}
,"char":{"*mac_addr":1}
,"*mac_addr":{"u_int32_t":1}
,"u_int32_t":{"ifindex)":1}
,"ifindex)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ipaddr":1,"none":1}
,"ipaddr":{"address":1}
,"address":{"mac_addr":1,"ifindex":1}
,"mac_addr":{"mac":1}
,"mac":{"address":1}
,"ifindex":{"interface":1}
,"interface":{"index":1}
,"index":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"function":1}
,"fails":{"hal_success":1}
,"hal_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
