var pairs =
{
"hello":{"protocol":1,"packet":1,"packets":1}
,"protocol":{"hello":1,"responsible":1,"elects":1}
,"responsible":{"establishing":1}
,"establishing":{"maintaining":1}
,"maintaining":{"neighbor":1}
,"neighbor":{"relationships":1,"heard":1}
,"relationships":{"ensures":1}
,"ensures":{"communication":1}
,"communication":{"neighbors":1,"indicated":1}
,"neighbors":{"bi-directional":1}
,"bi-directional":{"bi-directional":1,"communication":1}
,"indicated":{"router":1}
,"router":{"sees":1,"network":1,"interface":1}
,"sees":{"itself":1}
,"itself":{"listed":1}
,"listed":{"neighbor\u0027s":1}
,"neighbor\u0027s":{"hello":1}
,"packet":{"broadcast":1,"indicates":1}
,"broadcast":{"nbma":1}
,"nbma":{"networks":1}
,"networks":{"hello":1}
,"elects":{"designated":1}
,"designated":{"router":1}
,"network":{"hello":1}
,"packets":{"sent":1}
,"sent":{"functioning":1,"(hellointerval)":1}
,"functioning":{"router":1}
,"interface":{"hello":1}
,"indicates":{"often":1}
,"often":{"neighbor":1}
,"heard":{"remain":1}
,"remain":{"active":1}
,"active":{"(routerdeadinterval)":1}
,"(routerdeadinterval)":{"interval":1}
,"interval":{"hello":1}
,"(hellointerval)":{"hellointerval":1}
,"hellointerval":{"routerdeadinterval":1}
,"routerdeadinterval":{"routers":1}
,"routers":{"attached":1}
,"attached":{"common":1}
,"common":{"network":1}
}
;Search.control.loadWordPairs(pairs);
