var pairs =
{
"ldp":{"convergence":1,"considered":1,"hello":1,"session":1,"identifier":1,"fully":1,"configurable":1,"remains":1,"notifies":1,"becomes":1,"already":1,"non-converged":1,"waits":1}
,"convergence":{"ldp":1,"lost":1,"achieved":1}
,"considered":{"fully":1}
,"fully":{"operational":1}
,"operational":{"link":1,"ldp":1,"state":1}
,"link":{"ldp":1,"label":1,"cost":1}
,"hello":{"adjacency":1,"adjacency)":1}
,"adjacency":{"exists":1}
,"exists":{"associated":1}
,"associated":{"ldp":1}
,"session":{"(matching":1,"present":1,"establishment":1,"down":1}
,"(matching":{"ldp":1}
,"identifier":{"hello":1}
,"adjacency)":{"established":1}
,"established":{"peer":1}
,"peer":{"end":1}
,"end":{"link":1}
,"label":{"bindings":1}
,"bindings":{"exchanged":1}
,"exchanged":{"session":1}
,"present":{"time":1}
,"time":{"latter":1,"again":1}
,"latter":{"condition":1}
,"condition":{"cannot":1}
,"cannot":{"generally":1}
,"generally":{"verified":1}
,"verified":{"router":1}
,"router":{"estimation":1}
,"estimation":{"may":1}
,"may":{"used":1}
,"used":{"implementation":1}
,"implementation":{"strategy":1}
,"strategy":{"employed":1}
,"employed":{"configurable":1}
,"configurable":{"hold-down":1,"delay":1}
,"hold-down":{"timer":1}
,"timer":{"allow":1,"starting":1,"expires":1,"started":1,"restarted":1}
,"allow":{"ldp":1}
,"establishment":{"declaring":1}
,"declaring":{"ldp":1}
,"delay":{"timer":1}
,"starting":{"operational":1}
,"state":{"delay":1}
,"expires":{"ldp":1}
,"remains":{"operational":1}
,"notifies":{"igp":1}
,"igp":{"converged":1,"ldp":1,"link":1,"every":1}
,"converged":{"case":1,"new":1}
,"case":{"multiple":1}
,"multiple":{"sessions":1}
,"sessions":{"interface":1,"become":1}
,"interface":{"delay":1}
,"started":{"last":1}
,"last":{"sessions":1}
,"become":{"operational":1}
,"down":{"longer":1}
,"longer":{"remains":1}
,"becomes":{"non-converged":1}
,"non-converged":{"notifies":1,"however":1}
,"already":{"converged":1,"running":1}
,"new":{"route":1}
,"route":{"subsequent":1}
,"subsequent":{"fec":1}
,"fec":{"added":1}
,"added":{"ldp":1}
,"however":{"immediately":1}
,"immediately":{"notifies":1}
,"cost":{"increases":1}
,"increases":{"existing":1}
,"existing":{"traffic":1}
,"traffic":{"gets":1}
,"gets":{"diverted":1}
,"diverted":{"avoid":1}
,"avoid":{"ldp":1}
,"waits":{"configured":1}
,"configured":{"time":1}
,"again":{"checks":1}
,"checks":{"convergence":1}
,"lost":{"notifies":1}
,"every":{"incremental":1}
,"incremental":{"addition":1}
,"addition":{"fecs":1}
,"fecs":{"convergence":1}
,"achieved":{"timer":1}
,"restarted":{"already":1}
}
;Search.control.loadWordPairs(pairs);
