var pairs =
{
"ospf_vlink_transmit_delay_unset":{"function":1,"(u_int32_t":1}
,"function":{"resets":1,"called":1,"succeeds":1}
,"resets":{"transmit":1}
,"transmit":{"delay":1}
,"delay":{"interface":1}
,"interface":{"seconds":1,"parameters":1}
,"seconds":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"area":1}
,"area":{"virtual-link":1,"network":1}
,"virtual-link":{"transmit-delay":1}
,"transmit-delay":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf_vlink_transmit_delay_unset":1,"proc_id":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"int":1,"virtual":1}
,"proc_id":{"struct":1,"process":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"area_id":1,"peer_id)":1}
,"area_id":{"struct":1,"area":1}
,"peer_id)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1,"configured":1}
,"virtual":{"router":1,"link":1}
,"router":{"non-virtual-router":1,"output":1,"found":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"proc_id":1}
,"process":{"ospf":1,"valid":1,"exist":1}
,"ospf":{"instance":1}
,"instance":{"65535>":1}
,"65535>":{"area_id":1}
,"network":{"belongs":1}
,"belongs":{"peer_id":1}
,"peer_id":{"neighbor":1}
,"neighbor":{"router":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf_api_set_success":1}
,"ospf_api_set_success":{"function":1}
,"succeeds":{"ospf_api_set_err_process_id_invalid":1}
,"ospf_api_set_err_process_id_invalid":{"given":1}
,"given":{"process":1,"virtual":1}
,"valid":{"(outside":1}
,"(outside":{"65535":1}
,"65535":{"bounds)":1}
,"bounds)":{"ospf_api_set_err_if_param_not_configured":1}
,"ospf_api_set_err_if_param_not_configured":{"interface":1}
,"configured":{"ospf_api_set_err_process_not_exist":1}
,"ospf_api_set_err_process_not_exist":{"given":1}
,"exist":{"ospf_api_set_err_vlink_not_exist":1,"ospf_api_set_err_vr_not_exist":1}
,"ospf_api_set_err_vlink_not_exist":{"given":1}
,"link":{"exist":1}
,"ospf_api_set_err_vr_not_exist":{"virtual":1}
}
;Search.control.loadWordPairs(pairs);
