var pairs =
{
"architecture":{"vrrp":1,"model":1}
,"vrrp":{"module":1,"accepts":1,"configuration":1,"mode":1,"sessions":1,"packets":1,"router":1,"finite":1,"functionality":1,"application":1,"information":1,"modify":1}
,"module":{"runs":1,"provides":1,"ipv6":1,"vrrp":1}
,"runs":{"context":1}
,"context":{"nsm":1,"default":1,"addition":1}
,"nsm":{"process":1}
,"process":{"zebos-xp":1}
,"zebos-xp":{"architecture":1,"package":1}
,"model":{"vrrp":1}
,"provides":{"following":1}
,"following":{"main":1,"requirements":1}
,"main":{"functions":1}
,"functions":{"vrrp":1,"related":1}
,"accepts":{"vrrp":1}
,"configuration":{"cli":1,"modified":1,"vrrp":1}
,"cli":{"vr-id":1}
,"vr-id":{"timers":1}
,"timers":{"vrrp":1}
,"mode":{"priority":1,"allows":1,"allowing":1}
,"priority":{"configures":1}
,"configures":{"sessions":1}
,"sessions":{"accordingly":1,"respective":1,"dynamically":1}
,"accordingly":{"brings":1}
,"brings":{"brings":1,"down":1}
,"down":{"ipv4":1}
,"ipv4":{"ipv6":1,"module":1}
,"ipv6":{"sessions":1,"module":1}
,"respective":{"mode":1}
,"allows":{"creation":1}
,"creation":{"deletion":1}
,"deletion":{"vrrp":1}
,"dynamically":{"transmits":1}
,"transmits":{"receives":1}
,"receives":{"vrrp":1,"ipv4":1}
,"packets":{"virtual-router":1}
,"virtual-router":{"peers":1}
,"peers":{"based":1}
,"based":{"time-out":1}
,"time-out":{"value":1}
,"value":{"current":1}
,"current":{"state":1}
,"state":{"vrrp":1,"machine":1}
,"router":{"performs":1,"hardware":1,"run":1}
,"performs":{"functions":1}
,"related":{"vrrp":1}
,"finite":{"state":1}
,"machine":{"(fsm)":1,"rfc":1}
,"(fsm)":{"information":1}
,"information":{"fsm":1,"provide":1}
,"fsm":{"section":1}
,"section":{"protocol":1}
,"protocol":{"state":1}
,"rfc":{"5798":1}
,"5798":{"handles":1,"requirements":1}
,"handles":{"advertisement":1}
,"advertisement":{"messages":1}
,"messages":{"receives":1,"component":1,"type":1,"either":1,"whose":1}
,"functionality":{"available":1}
,"available":{"privileged":1}
,"privileged":{"(pvr)":1}
,"(pvr)":{"context":1}
,"default":{"context":1}
,"addition":{"rfc":1}
,"requirements":{"following":1,"met":1}
,"met":{"zebos-xp":1}
,"package":{"operating":1}
,"operating":{"system":1}
,"system":{"(os)":1,"provide":1}
,"(os)":{"contain":1}
,"contain":{"component":1,"vrrp":1}
,"component":{"supports":1,"pass":1}
,"supports":{"sending":1}
,"sending":{"receiving":1,"gratuitous":1}
,"receiving":{"multicast":1}
,"multicast":{"messages":1}
,"pass":{"messages":1}
,"type":{"112":1}
,"112":{"vrrp":1}
,"application":{"upon":1,"system":1,"forwarding":1,"programming":1}
,"upon":{"receipt":1}
,"receipt":{"method":1}
,"method":{"configuration":1}
,"modified":{"extended":1}
,"extended":{"support":1,"order":1}
,"support":{"configuration":1,"sending":1,"requirement":1}
,"provide":{"one-second":1,"application":1}
,"one-second":{"timer":1}
,"timer":{"signal":1}
,"signal":{"vrrp":1}
,"forwarding":{"(layer":1}
,"(layer":{"mechanism":1}
,"mechanism":{"support":1}
,"gratuitous":{"arp":1}
,"arp":{"messages":1,"table":1}
,"either":{"able":1}
,"able":{"extended":1,"accept":1}
,"order":{"contain":1}
,"programming":{"interfaces":1}
,"interfaces":{"(apis)":1}
,"(apis)":{"allow":1}
,"allow":{"vrrp":1}
,"modify":{"arp":1}
,"table":{"hardware":1}
,"hardware":{"able":1,"support":1}
,"accept":{"(pass":1}
,"(pass":{"up)":1}
,"up)":{"messages":1}
,"whose":{"mac":1}
,"mac":{"address":1,"addresses":1}
,"address":{"match":1}
,"match":{"owned":1}
,"owned":{"physical":1}
,"physical":{"mac":1}
,"addresses":{"router":1}
,"requirement":{"router":1}
,"run":{"promiscuous":1}
,"promiscuous":{"mode":1}
,"allowing":{"software":1}
,"software":{"decision":1}
}
;Search.control.loadWordPairs(pairs);
