var pairs =
{
"ethernet":{"oam":1}
,"oam":{"link-monitor":1}
,"link-monitor":{"command":1,"ethernet":1,"parameters":1}
,"command":{"turn":1,"syntax":1,"mode":1}
,"turn":{"link":1}
,"link":{"monitoring":1,"monitor":1}
,"monitoring":{"interface":1,"command":1,"automatically":1}
,"interface":{"form":1,"mode":1,"eth1":1}
,"form":{"command":1}
,"syntax":{"ethernet":1}
,"parameters":{"none":1}
,"none":{"default":1}
,"default":{"link":1}
,"monitor":{"supported":1}
,"supported":{"link":1}
,"automatically":{"turned":1}
,"turned":{"command":1}
,"mode":{"interface":1,"examples":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth1":{"(config-if)":1}
,"(config-if)":{"ethernet":1}
}
;Search.control.loadWordPairs(pairs);
