var pairs =
{
"rip_if_receive_version_unset":{"function":1,"(u_int32_t":1}
,"function":{"resets":1,"called":1}
,"resets":{"receive":1}
,"receive":{"version":1}
,"version":{"rip":1,"function":1,"syntax":1}
,"rip":{"node":1,"receive":1}
,"node":{"version":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"rip":1}
,"syntax":{"int":1}
,"int":{"rip_if_receive_version_unset":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1,"exist":1}
,"char":{"*ifname)":1}
,"*ifname)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1,"configured":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"parameter":1}
,"parameter":{"ifname":1}
,"ifname":{"interface":1}
,"interface":{"name":1,"parameters":1}
,"name":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"rip_api_set_err_if_param_not_configured":1}
,"rip_api_set_err_if_param_not_configured":{"interface":1}
,"configured":{"rip_api_set_err_vr_not_exist":1}
,"rip_api_set_err_vr_not_exist":{"vr_id":1}
,"exist":{"rip_api_set_success":1}
,"rip_api_set_success":{"call":1}
,"call":{"successful":1}
}
;Search.control.loadWordPairs(pairs);
