var pairs =
{
"isis-spb":{"lsp-interval":1}
,"lsp-interval":{"command":1,"<1-4294967295>":1,"parameters":1,"100":1}
,"command":{"interval":1,"lsp":1,"syntax":1,"mode":1}
,"interval":{"lsp":1,"form":1,"default":1,"milliseconds":1,"command":1}
,"lsp":{"transmissions":1,"transmission":1,"scheduled":1}
,"transmissions":{"flooding":1}
,"flooding":{"event":1}
,"event":{"triggers":1}
,"triggers":{"lsp":1}
,"transmission":{"lsp":1,"interval":1}
,"scheduled":{"transmit":1}
,"transmit":{"interval":1}
,"form":{"command":1}
,"default":{"(33":1,"default":1,"zebos-xp":1}
,"(33":{"milliseconds)":1}
,"milliseconds)":{"command":1}
,"syntax":{"isis-spb":1}
,"<1-4294967295>":{"isis-spb":1,"specify":1}
,"parameters":{"<1-4294967295>":1}
,"specify":{"lsp":1}
,"milliseconds":{"default":1,"interval":1}
,"zebos-xp":{"uses":1}
,"uses":{"milliseconds":1}
,"mode":{"interface":1,"examples":1}
,"interface":{"mode":1,"eth0":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"isis-spb":1}
,"100":{"(config-if)":1}
}
;Search.control.loadWordPairs(pairs);
