var pairs =
{
"topology":{"figure":1}
,"figure":{"12-118":1}
,"12-118":{"used":1}
,"used":{"describe":1}
,"describe":{"vlan":1}
,"vlan":{"interface":1,"connections":1,"interfaces":1,"connection":1,"vlan":1,"ids":1,"tags":1}
,"interface":{"configuration":1,"connected":1,"created":1}
,"configuration":{"example":1}
,"example":{"two":1}
,"two":{"routers":1,"systems":1}
,"routers":{"eth1":1}
,"eth1":{"interface":1}
,"connected":{"directly":1}
,"directly":{"eth2":1}
,"eth2":{"using":1}
,"using":{"crossover":1,"vlan":1}
,"crossover":{"ethernet":1}
,"ethernet":{"cable":1}
,"cable":{"vlan":1}
,"connections":{"eth1.10":1}
,"eth1.10":{"vlan":1}
,"created":{"eth2.10":1,"vlan":1}
,"eth2.10":{"created":1}
,"interfaces":{"configured":1,"(10)":1}
,"configured":{"network":1}
,"network":{"reach":1,"vlan":1}
,"reach":{"using":1}
,"connection":{"vlan":1}
,"(10)":{"two":1}
,"systems":{"different":1}
,"different":{"vlan":1}
,"ids":{"cannot":1}
,"cannot":{"communicate":1}
,"communicate":{"even":1}
,"even":{"network":1}
,"tags":{"packets":1}
,"packets":{"sent":1}
,"sent":{"vlan":1}
}
;Search.control.loadWordPairs(pairs);
