var pairs =
{
"secondary":{"admin-group-name":1,"administrative":1,"paths":1,"(include-any":1,"exclude-any":1,"include-any":1,"include-all":1}
,"admin-group-name":{"command":1,"secondary":1,"parameters":1,"administrative":1}
,"command":{"configure":1,"reference":1,"syntax":1,"mode":1}
,"configure":{"secondary":1,"terminal":1}
,"administrative":{"groups":1,"group":1}
,"groups":{"administrative":1,"manually":1,"used":1}
,"manually":{"assigned":1}
,"assigned":{"attributes":1}
,"attributes":{"describe":1,"included":1}
,"describe":{"color":1}
,"color":{"links":1,"class":1}
,"links":{"links":1,"color":1}
,"class":{"groups":1}
,"used":{"implement":1}
,"implement":{"different":1}
,"different":{"policy-based":1}
,"policy-based":{"lsp":1}
,"lsp":{"setups":1,"path\u2019s":1}
,"setups":{"administrative":1}
,"group":{"attributes":1,"via":1,"administrative":1,"list":1,"name":1}
,"included":{"excluded":1}
,"excluded":{"lsp":1}
,"path\u2019s":{"primary":1}
,"primary":{"secondary":1}
,"paths":{"link":1}
,"link":{"added":1}
,"added":{"specific":1}
,"specific":{"administrative":1}
,"via":{"nsm":1}
,"nsm":{"refer":1}
,"refer":{"network":1}
,"network":{"services":1}
,"services":{"module":1}
,"module":{"command":1}
,"reference":{"details":1}
,"details":{"parameter":1}
,"parameter":{"remove":1}
,"remove":{"previously":1}
,"previously":{"group":1}
,"list":{"command":1}
,"syntax":{"secondary":1}
,"(include-any":{"include-all":1,"exclude-any)":1}
,"include-all":{"exclude-any)":1,"include":1,"myadmingroup":1}
,"exclude-any)":{"admin-group-name":1}
,"parameters":{"include-any":1}
,"include-any":{"include":1,"myadmingroup":1}
,"include":{"attribute":1}
,"attribute":{"include-all":1,"exclude-any":1,"admin-group-name":1}
,"exclude-any":{"exclude":1,"myadmingroup":1}
,"exclude":{"attribute":1}
,"name":{"command":1}
,"mode":{"trunk":1,"examples":1}
,"trunk":{"mode":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"rsvp-trunk":1}
,"rsvp-trunk":{"mytrunk":1}
,"mytrunk":{"(config-trunk)":1}
,"(config-trunk)":{"secondary":1}
,"myadmingroup":{"configure":1}
}
;Search.control.loadWordPairs(pairs);
