var pairs =
{
"ethernet":{"cfm":1}
,"cfm":{"default-mepid":1,"form":1}
,"default-mepid":{"command":1,"mepid":1,"bridge":1}
,"command":{"default":1,"syntax":1,"mode":1}
,"default":{"maintenance":1,"mep":1}
,"maintenance":{"end":1}
,"end":{"point":1}
,"point":{"(mep)":1}
,"(mep)":{"identifier":1}
,"identifier":{"used":1,"command":1,"<1-1000>":1,"backbone":1}
,"used":{"automatic":1}
,"automatic":{"cfm":1}
,"form":{"command":1}
,"mep":{"identifier":1}
,"syntax":{"ethernet":1}
,"mepid":{"bridge":1,"specify":1}
,"bridge":{"(<1-32>":1,"specify":1,"<1-32>":1,"identifier":1,"command":1}
,"(<1-32>":{"backbone)":1}
,"backbone)":{"ethernet":1,"parameters":1}
,"parameters":{"mepid":1}
,"specify":{"default":1,"bridge":1}
,"<1-1000>":{"bridge":1}
,"<1-32>":{"specify":1}
,"backbone":{"backbone":1,"bridge":1}
,"mode":{"configure":1,"example":1}
,"configure":{"mode":1,"terminal":1}
,"example":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"ethernet":1}
}
;Search.control.loadWordPairs(pairs);
