var pairs =
{
"bgp_peer_group":{"structure":1,"{\u002F*peer-group":1}
,"structure":{"located":1,"peer_list":1,"*\u002Fstruct":1}
,"located":{"bgpd\u002Fbgpd.h":1}
,"bgpd\u002Fbgpd.h":{"member":1}
,"member":{"description":1}
,"description":{"name":1}
,"name":{"pointer":1,"bgp":1,"*\u002Fu_int8_t":1}
,"pointer":{"peer":1,"owning":1}
,"peer":{"group":1}
,"group":{"name":1,"client":1,"configuration":1}
,"bgp":{"pointer":1,"structure":1,"*bgp":1}
,"owning":{"bgp":1}
,"peer_list":{"pointer":1}
,"client":{"list":1}
,"list":{"bgp_peer":1,"*\u002Fstruct":1,"*peer_list":1}
,"bgp_peer":{"pointer":1,"*conf":1}
,"configuration":{"\u002F*bgp":1}
,"\u002F*bgp":{"peer-group":1}
,"peer-group":{"structure":1}
,"*\u002Fstruct":{"bgp_peer_group":1,"bgp":1,"list":1,"bgp_peer":1}
,"{\u002F*peer-group":{"name":1}
,"*\u002Fu_int8_t":{"*name":1}
,"*name":{"\u002F*owining":1}
,"\u002F*owining":{"bgp":1}
,"*bgp":{"\u002F*peer-group":1}
,"\u002F*peer-group":{"client":1,"config":1}
,"*peer_list":{"\u002F*peer-group":1}
,"config":{"*\u002Fstruct":1}
}
;Search.control.loadWordPairs(pairs);
