var pairs =
{
"oam_api_lps_debug_event":{"function":1,"(u_int32_t":1}
,"function":{"enables":1,"fails":1,"succeeds":1}
,"enables":{"event":1}
,"event":{"debugging":1,"variable":1,"type":1}
,"debugging":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"oam_api_lps_debug_event":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"lps_debug_event":1,"instance":1,"found":1}
,"lps_debug_event":{"debug_event)":1,"indicating":1}
,"debug_event)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"instance":{"event":1}
,"variable":{"type":1}
,"type":{"lps_debug_event":1,"output":1}
,"indicating":{"event":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"oam_api_set_err_vr_not_exist":1}
,"oam_api_set_err_vr_not_exist":{"vr_id":1}
,"found":{"oam_api_lps_set_error":1}
,"oam_api_lps_set_error":{"function":1}
,"fails":{"due":1}
,"due":{"internal":1}
,"internal":{"errors":1}
,"errors":{"memory":1}
,"memory":{"failure":1}
,"failure":{"oam_api_lps_set_success":1}
,"oam_api_lps_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
