var pairs =
{
"maintenance":{"entity":1}
,"entity":{"server-client":1}
,"server-client":{"relationship":1}
,"relationship":{"server-client":1,"supported":1,"built":1}
,"supported":{"mpls-tp":1}
,"mpls-tp":{"fault-management":1,"lsp":1,"provider":1}
,"fault-management":{"wherein":1}
,"wherein":{"notification":1}
,"notification":{"fault":1}
,"fault":{"detected":1}
,"detected":{"server":1}
,"server":{"layer":1,"subsequently":1}
,"layer":{"mep":1,"meps":1,"provides":1,"lsp":1,"datalink":1}
,"mep":{"reported":1}
,"reported":{"client":1}
,"client":{"layer":1,"server-client":1,"mes":1}
,"meps":{"mpls-tp":1}
,"lsp":{"uses":1,"datalink":1,"becomes":1,"makes":1}
,"uses":{"mpls-tp":1}
,"provider":{"interfaces":1,"interface":1}
,"interfaces":{"(datalink":1}
,"(datalink":{"layers)":1}
,"layers)":{"carry":1}
,"carry":{"traffic":1}
,"traffic":{"across":1}
,"across":{"lsp":1}
,"datalink":{"layer":1,"provider":1}
,"provides":{"service":1}
,"service":{"becomes":1}
,"becomes":{"server":1,"client":1}
,"built":{"dynamically":1}
,"dynamically":{"identifying":1}
,"identifying":{"lsps":1}
,"lsps":{"datalink":1}
,"interface":{"meg":1,"becomes":1,"incoming":1,"maintains":1}
,"meg":{"configured":1,"created":1}
,"configured":{"datalink":1}
,"subsequently":{"new":1}
,"new":{"meg":1,"mes":1}
,"created":{"mpls-tp":1}
,"makes":{"interface":1}
,"incoming":{"interface":1}
,"maintains":{"list":1}
,"list":{"client":1,"created":1}
,"mes":{"new":1,"added":1}
,"added":{"list":1}
}
;Search.control.loadWordPairs(pairs);
