var pairs =
{
"bfd":{"multihop-peer":1,"multihop":1}
,"multihop-peer":{"x:x":1,"10.1.1.1":1}
,"x:x":{":x:x":1}
,":x:x":{"command":1,"interval":1}
,"command":{"configure":1,"reset":1,"syntax":1,"mode":1}
,"configure":{"ipv6":1,"mode":1,"terminal":1}
,"ipv6":{"bfd":1,"multihop":1}
,"multihop":{"peer":1}
,"peer":{"timer":1}
,"timer":{"values":1}
,"values":{"form":1,"command":1}
,"form":{"command":1}
,"reset":{"ipv6":1}
,"syntax":{"bfd":1}
,"interval":{"<50-999>":1,"indicate":1,"parameter":1,"milliseconds":1,"100":1}
,"<50-999>":{"minrx":1,"multiplier":1,"specify":1}
,"minrx":{"<50-999>":1,"indicate":1,"parameter":1,"100":1}
,"multiplier":{"<3-50>":1,"indicate":1,"parameter":1,"value":1}
,"<3-50>":{"bfd":1,"parameters":1,"specify":1}
,"parameters":{"interval":1}
,"indicate":{"interval":1,"minrx":1,"multiplier":1}
,"parameter":{"<50-999>":1,"<3-50>":1}
,"specify":{"actual":1}
,"actual":{"transmit":1,"reception":1,"hello":1}
,"transmit":{"interval":1}
,"milliseconds":{"minrx":1,"multiplier":1}
,"reception":{"interval":1}
,"hello":{"multiplier":1}
,"value":{"command":1,"example":1}
,"mode":{"configure":1,"default":1}
,"default":{"default":1,"multiplier":1}
,"example":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"bfd":1}
,"10.1.1.1":{"interval":1}
,"100":{"minrx":1,"multiplier":1}
}
;Search.control.loadWordPairs(pairs);
