var pairs =
{
"ospf_area_auth_type_set":{"function":1,"(u_int32_t":1}
,"function":{"enables":1,"called":1,"succeeds":1}
,"enables":{"authentication":1}
,"authentication":{"area":1,"syntax":1,"type":1,"required":1,"ospf_auth_cryptographic":1,"output":1}
,"area":{"function":1,"authentication":1,"type":1,"border":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"area":1}
,"syntax":{"int":1}
,"int":{"ospf_area_auth_type_set":1,"proc_id":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"int":1,"virtual":1}
,"proc_id":{"struct":1,"process":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"area_id":1}
,"area_id":{"u_char":1,"ospf":1}
,"u_char":{"type)":1}
,"type)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"ospf_auth_null":1,"found":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"proc_id":1}
,"process":{"ospf":1,"found":1,"valid":1}
,"ospf":{"instance":1,"area":1}
,"instance":{"65535>":1}
,"65535>":{"area_id":1}
,"type":{"authentication":1,"area":1,"supported":1}
,"border":{"router":1}
,"ospf_auth_null":{"authentication":1}
,"required":{"ospf_auth_simple":1}
,"ospf_auth_simple":{"simple":1}
,"simple":{"password":1}
,"password":{"authentication":1}
,"ospf_auth_cryptographic":{"md5":1}
,"md5":{"authentication":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf_api_set_err_auth_type_invalid":1}
,"ospf_api_set_err_auth_type_invalid":{"authentication":1}
,"supported":{"ospf_api_set_err_process_not_exist":1}
,"ospf_api_set_err_process_not_exist":{"process":1}
,"found":{"ospf_api_set_err_process_id_invalid":1,"ospf_api_set_err_area_limit":1}
,"ospf_api_set_err_process_id_invalid":{"process":1}
,"valid":{"ospf_api_set_success":1}
,"ospf_api_set_success":{"function":1}
,"succeeds":{"ospf_api_set_err_vr_not_exist":1}
,"ospf_api_set_err_vr_not_exist":{"virtual":1}
,"ospf_api_set_err_area_limit":{"number":1}
,"number":{"areas":1}
,"areas":{"exceeds":1}
,"exceeds":{"limit":1}
}
;Search.control.loadWordPairs(pairs);
