var pairs =
{
"mld_snooping_set":{"function":1,"(struct":1}
,"function":{"enables":1,"succeeds":1}
,"enables":{"mld":1}
,"mld":{"snooping":1,"instance":1}
,"snooping":{"interfaces":1,"mld":1,"globally":1}
,"interfaces":{"instance":1}
,"instance":{"explicitly":1,"output":1,"specified":1}
,"explicitly":{"(individually)":1}
,"(individually)":{"disabled":1}
,"disabled":{"mld":1}
,"globally":{"enabled":1}
,"enabled":{"default":1}
,"default":{"api":1}
,"api":{"call":1}
,"call":{"s_int32_t":1}
,"s_int32_t":{"mld_snooping_set":1}
,"(struct":{"mld_instance":1}
,"mld_instance":{"*mli)":1}
,"*mli)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"mli":1,"none":1}
,"mli":{"pointer":1}
,"pointer":{"mld":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"mld_err_none":1,"given":1}
,"mld_err_none":{"function":1}
,"succeeds":{"mld_err_invalid_value":1}
,"mld_err_invalid_value":{"mld":1}
,"specified":{"interface":1}
,"interface":{"null":1}
,"null":{"supported":1}
,"supported":{"values":1}
}
;Search.control.loadWordPairs(pairs);
