var pairs =
{
"ospfv3":{"api":1,"functions":1,"area":1,"process":1,"database":1,"flood-reduction":1,"loop-free":1,"lfa":1,"tie-breaker":1,"routers":1,"traffic":1,"router":1}
,"api":{"following":1}
,"following":{"summary":1,"subsections":1}
,"summary":{"ospfv3":1,"list":1,"address":1}
,"functions":{"details":1}
,"details":{"provided":1}
,"provided":{"following":1}
,"subsections":{"function":1}
,"function":{"description":1}
,"description":{"ospf6_address_family_set":1}
,"ospf6_address_family_set":{"sets":1}
,"sets":{"address":1,"abr":1,"format":1,"area":1,"stability":1,"translator":1,"reference":1,"specified":1,"demand-circuit":1,"network":1,"maximum":1,"metric":1,"tag":1,"minimum":1,"retransmit":1}
,"address":{"family":1,"range":1,"ospf6_timers_spf_set":1}
,"family":{"mode":1}
,"mode":{"ipv4":1}
,"ipv4":{"unicast":1}
,"unicast":{"ipv6":1,"ospf6_abr_type_set":1}
,"ipv6":{"unicast":1,"prefix":1,"ospf":1}
,"ospf6_abr_type_set":{"sets":1}
,"abr":{"type":1}
,"type":{"ospf6_abr_type_unset":1,"cisco":1,"nssa":1,"ospf6_if_network_unset":1,"ospf6_if_ipv6_router_set":1,"redistributed":1,"specified":1,"redistribution":1}
,"ospf6_abr_type_unset":{"sets":1}
,"cisco":{"ospf6_area_default_cost_set":1}
,"ospf6_area_default_cost_set":{"configures":1}
,"configures":{"stub":1,"area":1,"specified":1,"router":1,"hello":1,"ospfv3":1,"retransmit":1,"transmit":1,"instance":1,"virtual":1}
,"stub":{"default":1,"no-summary":1,"ospf6_area_stub_unset":1}
,"default":{"cost":1,"lsas":1,"value":1,"metric":1,"(5)":1,"(2)":1,"(16777215)":1,"values":1}
,"cost":{"ospf6_area_default_cost_unset":1,"ospf6_area_format_set":1,"specified":1}
,"ospf6_area_default_cost_unset":{"unsets":1}
,"unsets":{"stub":1,"configured":1,"cspf":1,"demand-circuit":1,"metric":1,"passive":1,"virtual":1}
,"ospf6_area_format_set":{"sets":1}
,"format":{"area":1,"specified":1}
,"area":{"ospf6_area_no_summary_set":1,"stub":1,"ospf6_area_nssa_default_originate_metric_type_set":1,"ospf6_area_nssa_default_originate_set":1,"ospf6_area_nssa_default_originate_unset":1,"ospf6_area_nssa_no_redistribution_set":1,"ospf6_area_nssa_no_redistribution_unset":1,"ospf6_area_nssa_set":1,"nssa":1,"ospf6_area_nssa_translator_role_set":1,"ospf6_area_nssa_translator_role_unset":1,"ospf6_area_nssa_unset":1,"normal":1,"ospf6_area_range_set":1,"range":1,"ospf6_auto_cost_reference_bandwidth_set":1}
,"ospf6_area_no_summary_set":{"configures":1}
,"no-summary":{"ospf6_area_no_summary_unset":1,"ospf6_area_nssa_default_originate_metric_set":1}
,"ospf6_area_no_summary_unset":{"unconfigures":1}
,"unconfigures":{"area":1,"router":1,"ospfv3":1}
,"ospf6_area_nssa_default_originate_metric_set":{"originates":1}
,"originates":{"type-7":1}
,"type-7":{"default":1}
,"lsas":{"specific":1,"nssa":1}
,"specific":{"metric":1}
,"metric":{"nssa":1,"type":1,"external":1,"ospf6_disable_db_summary_opt":1,"ospfv3":1,"redistributed":1}
,"nssa":{"area":1,"ospf6_area_nssa_stability_interval_set":1}
,"ospf6_area_nssa_default_originate_metric_type_set":{"originates":1}
,"ospf6_area_nssa_default_originate_set":{"originates":1}
,"ospf6_area_nssa_default_originate_unset":{"stops":1}
,"stops":{"originating":1,"redistributing":1,"suppressing":1}
,"originating":{"type-7":1}
,"ospf6_area_nssa_no_redistribution_set":{"stops":1}
,"redistributing":{"routes":1}
,"routes":{"nssa":1,"ospf6_default_metric_unset":1,"specified":1,"match":1}
,"ospf6_area_nssa_no_redistribution_unset":{"redistributes":1}
,"redistributes":{"routes":1}
,"ospf6_area_nssa_set":{"sets":1}
,"ospf6_area_nssa_stability_interval_set":{"sets":1}
,"stability":{"interval":1}
,"interval":{"nssa":1,"specified":1}
,"ospf6_area_nssa_translator_role_set":{"sets":1}
,"translator":{"role":1}
,"role":{"nssa":1}
,"ospf6_area_nssa_translator_role_unset":{"removes":1}
,"removes":{"translator":1,"network":1,"route":1,"ospfv3":1,"tag":1,"summary":1}
,"ospf6_area_nssa_unset":{"makes":1}
,"makes":{"area":1}
,"normal":{"area":1}
,"ospf6_area_range_set":{"configures":1}
,"range":{"ipv6":1,"ospf6_area_stub_set":1,"ospf6_summary_address_not_advertise_unset":1,"ospf6_summary_address_set":1,"ospf6_summary_address_tag_set":1}
,"prefix":{"ospf6_area_range_unset":1}
,"ospf6_area_range_unset":{"unsets":1}
,"configured":{"area":1,"default":1,"output":1,"hello":1,"router":1,"retransmit":1,"transmit":1,"ospfv3":1,"instance":1}
,"ospf6_area_stub_set":{"configures":1}
,"specified":{"ospfv3":1,"default":1,"interface":1,"metric":1,"protocol":1,"route":1,"address":1,"virtual":1,"ospf6_vlink_transmit_delay_set":1,"virtual-link":1}
,"ospf6_area_stub_unset":{"makes":1}
,"ospf6_auto_cost_reference_bandwidth_set":{"sets":1}
,"reference":{"bandwidth":1}
,"bandwidth":{"value":1,"default":1}
,"value":{"ospf6_auto_cost_reference_bandwidth_unset":1,"(100000":1,"ospf6_if_cost_unset":1,"match":1,"controlling":1}
,"ospf6_auto_cost_reference_bandwidth_unset":{"sets":1}
,"(100000":{"kbps)":1}
,"kbps)":{"ospf6_capability_cspf_set":1}
,"ospf6_capability_cspf_set":{"enables":1}
,"enables":{"cspf":1,"ospfv3":1,"ospf":1,"disables":1}
,"cspf":{"capability":1}
,"capability":{"ospfv3":1,"specified":1}
,"process":{"ospf6_capability_cspf_unset":1,"ospf6_default_metric_set":1}
,"ospf6_capability_cspf_unset":{"unsets":1}
,"ospf6_default_metric_set":{"sets":1}
,"external":{"routes":1}
,"ospf6_default_metric_unset":{"unsets":1}
,"ospf6_disable_db_summary_opt":{"disables":1}
,"disables":{"ospfv3":1,"configure":1,"ospf":1,"link":1}
,"database":{"summary":1,"descriptors":1}
,"list":{"optimization":1}
,"optimization":{"ospf6_dna_set":1}
,"ospf6_dna_set":{"enables":1}
,"flood-reduction":{"ospf6_dna_unset":1,"ospf6_frr_set":1,"specified":1}
,"ospf6_dna_unset":{"disables":1}
,"ospf6_frr_set":{"enables":1}
,"loop-free":{"alternate":1}
,"alternate":{"ospf6_frr_interface_set":1}
,"ospf6_frr_interface_set":{"disables":1}
,"lfa":{"calculation":1,"ospf6_frr_tie_break_priority_all_unset":1}
,"calculation":{"interface":1}
,"interface":{"ospf6_frr_tie_break_prority_set":1,"ospf6_if_dc_set":1,"ospf6_if_dc_unset":1,"ospf6_if_dead_interval_set":1,"ospf6_if_dead_interval_unset":1,"ospf6_if_dna_set":1,"ospf6_if_dna_unset":1,"ospf6_if_hello_interval_set":1,"ospf6_if_hello_interval_unset":1,"ospf6_if_neighbor_set":1,"ospf6_if_ipv6_router_unset":1,"ospf6_if_link_lsa_suppression_set":1,"ospf6_if_priority_unset":1,"ospf6_if_retransmit_interval_set":1,"ospf6_if_retransmit_interval_unset":1,"ospf6_if_te_metric_set":1,"ospf6_if_te_metric_unset":1,"ospf6_if_transmit_delay_set":1,"ospf6_if_transmit_delay_unset":1,"ospf6_ipv6_ospf_display_route_single_line_set":1,"passive":1,"configuration":1}
,"ospf6_frr_tie_break_prority_set":{"enables":1}
,"tie-breaker":{"attribute":1}
,"attribute":{"lfa":1}
,"ospf6_frr_tie_break_priority_all_unset":{"disables":1}
,"configure":{"tie-breaking":1}
,"tie-breaking":{"priorities":1}
,"priorities":{"ospf6_if_cost_set":1}
,"ospf6_if_cost_set":{"resets":1}
,"resets":{"grace":1,"spf":1}
,"grace":{"period":1}
,"period":{"default":1}
,"ospf6_if_cost_unset":{"unsets":1}
,"output":{"cost":1}
,"ospf6_if_dc_set":{"sets":1}
,"demand-circuit":{"capability":1}
,"ospf6_if_dc_unset":{"unsets":1}
,"ospf6_if_dead_interval_set":{"configures":1}
,"router":{"dead":1,"priority":1,"ospf6_router_set":1,"instance":1}
,"dead":{"interval":1}
,"ospf6_if_dead_interval_unset":{"unconfigures":1}
,"ospf6_if_dna_set":{"enables":1}
,"ospf6_if_dna_unset":{"disables":1}
,"ospf6_if_hello_interval_set":{"configures":1}
,"hello":{"interval":1}
,"ospf6_if_hello_interval_unset":{"unsets":1}
,"ospf6_if_neighbor_set":{"configures":1}
,"routers":{"interconnecting":1}
,"interconnecting":{"non-broadcast":1}
,"non-broadcast":{"networks":1}
,"networks":{"ospf6_if_neighbor_unset":1,"ospf6_if_network_set":1}
,"ospf6_if_neighbor_unset":{"unconfigures":1}
,"ospf6_if_network_set":{"sets":1}
,"network":{"type":1}
,"ospf6_if_network_unset":{"removes":1}
,"ospf6_if_ipv6_router_set":{"enables":1}
,"ospf":{"routing":1,"route":1}
,"routing":{"specified":1}
,"ospf6_if_ipv6_router_unset":{"disables":1}
,"ospf6_if_link_lsa_suppression_set":{"enables":1}
,"link":{"lsa":1,"ospf6_vlink_dead_interval_unset":1,"ospf6_vlink_format_set":1,"configuration":1,"ospf6_vlink_hello_interval_unset":1,"ospf6_vlink_instance_id_set":1,"ospf6_vlink_instance_id_unset":1,"ospf6_vlink_retransmit_interval_set":1,"ospf6_vlink_retransmit_interval_unset":1,"ospf6_vlink_set":1,"specified":1,"ospf6_vlink_transmit_delay_unset":1}
,"lsa":{"(type":1}
,"(type":{"suppression":1}
,"suppression":{"ospf6_if_priority_set":1}
,"ospf6_if_priority_set":{"configures":1}
,"priority":{"specified":1}
,"ospf6_if_priority_unset":{"unsets":1}
,"ospf6_if_retransmit_interval_set":{"configures":1}
,"retransmit":{"interval":1}
,"ospf6_if_retransmit_interval_unset":{"unsets":1}
,"ospf6_if_te_metric_set":{"sets":1}
,"traffic":{"engineering":1}
,"engineering":{"interface":1}
,"ospf6_if_te_metric_unset":{"unsets":1}
,"ospf6_if_transmit_delay_set":{"configures":1}
,"transmit":{"delay":1}
,"delay":{"specified":1,"topology":1,"default":1}
,"ospf6_if_transmit_delay_unset":{"unsets":1}
,"ospf6_ipv6_ospf_display_route_single_line_set":{"shows":1}
,"shows":{"results":1}
,"results":{"show":1}
,"show":{"ipv6":1}
,"route":{"single":1,"multiple":1,"ospf6_redistribute_metric_type_set":1,"ospf6_redistribute_metric_type_unset":1,"default":1,"map":1,"type":1,"maps":1}
,"single":{"line":1}
,"line":{"ospf6_ipv6_ospf_display_route_single_line_unset":1}
,"ospf6_ipv6_ospf_display_route_single_line_unset":{"shows":1}
,"multiple":{"lines":1}
,"lines":{"ospf6_max_concurrent_dd_set":1}
,"ospf6_max_concurrent_dd_set":{"sets":1}
,"maximum":{"number":1,"concurrent":1,"delay":1}
,"number":{"concurrently":1}
,"concurrently":{"processed":1}
,"processed":{"database":1}
,"descriptors":{"ospf6_max_concurrent_dd_unset":1,"default":1}
,"ospf6_max_concurrent_dd_unset":{"sets":1}
,"concurrent":{"database":1}
,"(5)":{"ospf6_passive_if_set":1}
,"ospf6_passive_if_set":{"configures":1}
,"passive":{"ospf6_passive_if_unset":1,"interface":1}
,"ospf6_passive_if_unset":{"unsets":1}
,"configuration":{"ospf6_redistribute_metric_set":1,"ospf6_vlink_hello_interval_set":1}
,"ospf6_redistribute_metric_set":{"sets":1}
,"redistributed":{"route":1,"protocol":1}
,"ospf6_redistribute_metric_type_set":{"sets":1}
,"ospf6_redistribute_metric_type_unset":{"sets":1}
,"(2)":{"ospf6_redistribute_metric_unset":1}
,"ospf6_redistribute_metric_unset":{"sets":1}
,"(16777215)":{"ospf6_redistribute_set":1}
,"ospf6_redistribute_set":{"redistributes":1}
,"protocol":{"ospf6_redistribute_unset":1,"ospf6_routemap_set":1,"ospf6_routemap_unset":1,"ospf6_router_id_set":1}
,"ospf6_redistribute_unset":{"stops":1}
,"ospf6_routemap_set":{"assigns":1}
,"assigns":{"route-map":1}
,"route-map":{"redistributed":1}
,"ospf6_routemap_unset":{"removes":1}
,"map":{"redistributed":1}
,"ospf6_router_id_set":{"unsets":1}
,"redistribution":{"ospf6_router_id_unset":1,"via":1}
,"ospf6_router_id_unset":{"unsets":1}
,"ospf6_router_set":{"initiates":1}
,"initiates":{"ospfv3":1}
,"instance":{"ospf6_router_unset":1,"ospf6_summary_address_not_advertise_set":1,"specified":1}
,"ospf6_router_unset":{"removes":1}
,"ospf6_summary_address_not_advertise_set":{"suppresses":1}
,"suppresses":{"external":1}
,"match":{"specified":1,"value":1}
,"ospf6_summary_address_not_advertise_unset":{"stops":1}
,"suppressing":{"external":1}
,"ospf6_summary_address_set":{"summarizes":1}
,"summarizes":{"external":1}
,"ospf6_summary_address_tag_set":{"sets":1}
,"tag":{"value":1}
,"controlling":{"redistribution":1}
,"via":{"route":1}
,"maps":{"ospf6_summary_address_tag_unset":1,"ospf6_summary_address_unset":1}
,"ospf6_summary_address_tag_unset":{"removes":1}
,"ospf6_summary_address_unset":{"removes":1}
,"ospf6_timers_spf_set":{"sets":1}
,"minimum":{"maximum":1}
,"topology":{"change":1}
,"change":{"ospf6_timers_spf_unset":1}
,"ospf6_timers_spf_unset":{"resets":1}
,"spf":{"minimum":1}
,"values":{"ospf6_vlink_dead_interval_set":1}
,"ospf6_vlink_dead_interval_set":{"configures":1}
,"virtual":{"link":1}
,"ospf6_vlink_dead_interval_unset":{"unsets":1}
,"ospf6_vlink_format_set":{"specifies":1}
,"specifies":{"format":1}
,"ospf6_vlink_hello_interval_set":{"configures":1}
,"ospf6_vlink_hello_interval_unset":{"unsets":1}
,"ospf6_vlink_instance_id_set":{"configures":1}
,"ospf6_vlink_instance_id_unset":{"unsets":1}
,"ospf6_vlink_retransmit_interval_set":{"sets":1}
,"ospf6_vlink_retransmit_interval_unset":{"unsets":1}
,"ospf6_vlink_set":{"configures":1}
,"ospf6_vlink_transmit_delay_set":{"configures":1}
,"ospf6_vlink_transmit_delay_unset":{"unsets":1}
,"virtual-link":{"ospf6_vlink_unset":1}
,"ospf6_vlink_unset":{"unsets":1}
}
;Search.control.loadWordPairs(pairs);
