var pairs =
{
"size":{"considerations":1}
,"considerations":{"rsvp":1}
,"rsvp":{"message":1,"messages":1}
,"message":{"zebos-xp":1,"exceeds":1}
,"zebos-xp":{"rsvp-te":1}
,"rsvp-te":{"assures":1}
,"assures":{"rsvp":1}
,"exceeds":{"maximum":1}
,"maximum":{"transmission":1}
,"transmission":{"unit":1}
,"unit":{"(mtu)":1}
,"(mtu)":{"outgoing":1}
,"outgoing":{"interface":1}
,"interface":{"although":1}
,"although":{"restriction":1}
,"restriction":{"advisable":1}
,"advisable":{"generic":1}
,"generic":{"rsvp":1}
,"messages":{"summary-refresh":1}
,"summary-refresh":{"support":1}
,"support":{"may":1}
,"may":{"hampered":1}
,"hampered":{"due":1}
,"due":{"restrictions":1}
}
;Search.control.loadWordPairs(pairs);
