var pairs =
{
"manual":{"vccv":1,"named":1,"(config)":1}
,"vccv":{"bfd":1,"cc-type":1,"(any":1}
,"bfd":{"enabled":1,"bfd-cv-type":1,"(cv-type)":1}
,"enabled":{"pe1":1}
,"pe1":{"(config)":1,"(config-if)":1}
,"(config)":{"mpls":1,"router":1,"interface":1,"bridge":1,"exit":1}
,"mpls":{"vpls":1,"l2-circuit":1,"l2-circuit-fib-entry":1}
,"vpls":{"100":1}
,"100":{"configure":1,"pe2":1,"3.4.5.6":1,"enable":1,"111":1}
,"configure":{"vpls":1,"status":1,"targeted":1,"label-switching":1,"manual":1,"mpls-l2":1,"mode":1}
,"pe2":{"(config)":1,"loopback":1}
,"router":{"ldp":1}
,"ldp":{"enter":1,"mode":1,"session":1,"provider":1}
,"enter":{"router":1,"interface":1}
,"mode":{"(config-router)":1,"(config)":1,"(config-if)":1,"access":1}
,"(config-router)":{"pw-status-tlv":1,"targeted-peer":1,"exit":1}
,"pw-status-tlv":{"configure":1}
,"status":{"tlv":1,"signaling":1}
,"tlv":{"status":1}
,"signaling":{"(config-router)":1}
,"targeted-peer":{"ipv4":1}
,"ipv4":{"3.4.5.6":1,"enable":1}
,"3.4.5.6":{"configure":1,"manual":1,"eth2":1}
,"targeted":{"ldp":1}
,"session":{"pe2":1}
,"loopback":{"address":1}
,"address":{"(config-router)":1}
,"exit":{"exit":1,"router":1,"interface":1,"configure":1}
,"interface":{"eth2":1,"mode":1,"pe1":1,"eth1":1,"access":1,"(config-if)":1}
,"eth2":{"enter":1,"eth1":1}
,"(config-if)":{"label-switching":1,"enable-ldp":1,"exit":1,"switchport":1,"mpls-l2-circuit":1}
,"label-switching":{"configure":1,"provider":1}
,"provider":{"interface":1}
,"enable-ldp":{"ipv4":1}
,"enable":{"ldp":1,"vccv":1}
,"l2-circuit":{"test":1}
,"test":{"100":1,"pw-id":1,"bind":1}
,"cc-type":{"<2>":1}
,"<2>":{"bfd":1}
,"bfd-cv-type":{"<1>":1}
,"<1>":{"configure":1}
,"named":{"test":1}
,"pw-id":{"100":1}
,"(any":{"cc-type)":1}
,"cc-type)":{"bfd":1}
,"(cv-type)":{"(config)":1}
,"l2-circuit-fib-entry":{"100":1}
,"111":{"222":1}
,"222":{"3.4.5.6":1}
,"eth1":{"configure":1,"enter":1}
,"mpls-l2":{"circuit":1}
,"circuit":{"fib":1}
,"fib":{"entry":1}
,"entry":{"manual":1}
,"bridge":{"protocol":1,"(config)":1}
,"protocol":{"ieee":1}
,"ieee":{"vlan-bridge":1}
,"vlan-bridge":{"specify":1}
,"specify":{"vlan":1}
,"vlan":{"bridge":1}
,"switchport":{"switch":1,"mode":1}
,"switch":{"layer-2":1}
,"layer-2":{"mode":1}
,"access":{"switching":1,"mode":1,"interface":1}
,"switching":{"characteristics":1}
,"characteristics":{"interface":1}
,"mpls-l2-circuit":{"test":1}
,"bind":{"access":1}
}
;Search.control.loadWordPairs(pairs);
