var pairs =
{
"igmp":{"operation":1,"works":1,"enabled":1,"query":1,"querier":1,"membership":1,"group":1,"leave":1,"table":1}
,"operation":{"igmp":1,"once":1,"host":1,"multicast":1}
,"works":{"premise":1}
,"premise":{"three":1}
,"three":{"major":1}
,"major":{"packets":1}
,"packets":{"exchange":1}
,"exchange":{"igmp":1}
,"enabled":{"routers":1,"pim":1,"(which":1}
,"routers":{"hosts":1}
,"hosts":{"interested":1,"want":1}
,"interested":{"joining":1}
,"joining":{"particular":1}
,"particular":{"group":1}
,"group":{"igmp":1,"224.0.0.1":1,"host":1,"just":1,"table":1,"router":1,"state":1,"until":1,"address":1}
,"query":{"operation":1,"message":1,"all-hosts":1,"messages":1,"every":1,"local":1,"called":1,"(called":1,"response":1}
,"once":{"igmp":1}
,"pim":{"enabled":1}
,"(which":{"enables":1}
,"enables":{"igmpv3)":1}
,"igmpv3)":{"interface":1}
,"interface":{"starts":1,"name":1}
,"starts":{"sending":1,"timer":1}
,"sending":{"query":1}
,"message":{"called":1,"router":1,"check":1,"starts":1,"router-1":1,"removing":1}
,"called":{"general":1,"solicited":1,"unsolicited":1,"last":1}
,"general":{"query":1}
,"all-hosts":{"multicast":1}
,"multicast":{"group":1,"data":1,"groups":1,"traffic":1,"group-address":1,"host":1}
,"224.0.0.1":{"periodically":1}
,"periodically":{"discover":1}
,"discover":{"whether":1}
,"whether":{"hosts":1}
,"want":{"receive":1}
,"receive":{"multicast":1,"query":1}
,"data":{"zebos-xp":1}
,"zebos-xp":{"elects":1}
,"elects":{"router":1}
,"router":{"igmp":1,"continues":1,"lower":1,"expires":1,"later":1,"sends":1,"wants":1}
,"querier":{"subnet":1,"timeout":1,"timer":1,"router":1,"sets":1,"lan":1}
,"subnet":{"lowest":1}
,"lowest":{"address":1}
,"address":{"long":1,"resets":1,"drops":1,"less":1,"igmp":1}
,"long":{"router":1}
,"continues":{"receive":1,"send":1}
,"messages":{"router":1}
,"lower":{"address":1}
,"resets":{"timer":1}
,"timer":{"based":1,"router":1,"again":1,"configure":1,"expires":1}
,"based":{"querier":1}
,"timeout":{"value":1}
,"value":{"querier":1}
,"expires":{"becomes":1,"software":1}
,"becomes":{"designated":1,"querier":1}
,"designated":{"querier":1}
,"later":{"receives":1,"sends":1}
,"receives":{"host":1,"query":1,"report":1}
,"host":{"query":1,"receives":1,"membership":1,"joins":1,"immediately":1,"leaves":1,"runs":1,"last":1,"leave":1}
,"drops":{"role":1}
,"role":{"designated":1}
,"sets":{"querier":1}
,"again":{"figure":1}
,"figure":{"above":1}
,"above":{"router-1":1,"host-1":1}
,"router-1":{"eth2":1,"maintains":1}
,"eth2":{"sends":1,"router-1":1,"becomes":1,"multicast":1}
,"sends":{"query":1,"host":1,"membership":1,"igmp":1,"leave":1,"group-specific-query":1}
,"every":{"query-interval":1}
,"query-interval":{"router1-eth2":1}
,"router1-eth2":{"address":1}
,"less":{"router-2":1}
,"router-2":{"eth2":1}
,"lan":{"igmp":1}
,"membership":{"report":1,"reports":1}
,"report":{"operation":1,"multicast":1,"host":1,"inform":1,"figure":1,"router-1":1,"igmp":1}
,"local":{"router":1}
,"groups":{"wants":1,"want":1,"don\u2019t":1}
,"wants":{"receive":1}
,"traffic":{"called":1,"group":1,"upon":1,"response":1}
,"solicited":{"membership":1}
,"joins":{"new":1}
,"new":{"group":1}
,"immediately":{"sends":1}
,"inform":{"local":1}
,"just":{"joined":1}
,"joined":{"without":1}
,"without":{"waiting":1}
,"waiting":{"receive":1}
,"unsolicited":{"membership":1}
,"host-1":{"host-2":1}
,"host-2":{"sends":1}
,"reports":{"router-1":1,"received":1}
,"upon":{"reception":1}
,"reception":{"membership":1}
,"maintains":{"igmp":1}
,"table":{"containing":1}
,"containing":{"multicast":1}
,"group-address":{"interface":1}
,"name":{"receives":1}
,"leave":{"operation":1,"message":1,"group":1}
,"leaves":{"group":1}
,"runs":{"igmpv2":1}
,"igmpv2":{"later":1}
,"check":{"host":1}
,"last":{"host":1,"member":1}
,"(called":{"group-specific-query)":1}
,"group-specific-query)":{"message":1}
,"configure":{"called":1}
,"member":{"query":1}
,"response":{"interval":1,"leave":1}
,"interval":{"reports":1}
,"received":{"timer":1}
,"software":{"removes":1}
,"removes":{"group":1}
,"state":{"router":1,"removed":1}
,"send":{"multicast":1}
,"until":{"state":1}
,"removed":{"figure":1}
,"don\u2019t":{"want":1}
,"group-specific-query":{"message":1}
,"removing":{"multicast":1}
}
;Search.control.loadWordPairs(pairs);
