var pairs =
{
"ldp_snmp_extract_session_data":{"call":1,"(struct":1}
,"call":{"gets":1}
,"gets":{"session-related":1}
,"session-related":{"data":1}
,"data":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ldp_snmp_extract_session_data":1}
,"(struct":{"ldp":1}
,"ldp":{"*ldp":1,"ldp":1,"instance":1,"session":1}
,"*ldp":{"struct":1}
,"struct":{"ldp_session":1,"listnode":1}
,"ldp_session":{"*session":1}
,"*session":{"struct":1}
,"listnode":{"*ln":1}
,"*ln":{"u_int32_t":1}
,"u_int32_t":{"*state":1,"*role":1,"*proto_version":1,"*hold_time_rem":1,"*keep_alive_time":1,"*max_pdu_len":1,"*discont_time":1,"*last_state_change)":1}
,"*state":{"u_int32_t":1}
,"*role":{"u_int32_t":1}
,"*proto_version":{"u_int32_t":1}
,"*hold_time_rem":{"u_int32_t":1}
,"*keep_alive_time":{"u_int32_t":1}
,"*max_pdu_len":{"u_int32_t":1}
,"*discont_time":{"u_int32_t":1}
,"*last_state_change)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ldp":1,"state":1}
,"instance":{"ldp":1,"session":1}
,"session":{"ldp":1,"session":1,"adjacency":1,"role":1,"proto_version":1,"hold_time_rem":1,"keep_alive_time":1,"max_pdu_len":1,"discont_time":1}
,"adjacency":{"output":1}
,"output":{"parameters":1}
,"state":{"state":1,"session":1,"change":1}
,"role":{"role":1,"session":1}
,"proto_version":{"protocol":1}
,"protocol":{"version":1}
,"version":{"session":1}
,"hold_time_rem":{"remaining":1}
,"remaining":{"hold":1}
,"hold":{"time":1}
,"time":{"value":1,"session":1,"last":1}
,"value":{"session":1}
,"keep_alive_time":{"keepalive":1}
,"keepalive":{"time":1}
,"max_pdu_len":{"maximum":1}
,"maximum":{"pdu":1}
,"pdu":{"length":1}
,"length":{"session":1}
,"discont_time":{"discontinue":1}
,"discontinue":{"timer":1}
,"timer":{"last_state_change":1}
,"last_state_change":{"time":1}
,"last":{"state":1}
,"change":{"occurred":1}
,"occurred":{"return":1}
,"return":{"values":1}
,"values":{"ldp_success":1}
,"ldp_success":{"ldp_error":1}
}
;Search.control.loadWordPairs(pairs);
