var pairs =
{
"efm_oam_pdu_timer_get":{"function":1,"(struct":1}
,"function":{"gets":1,"syntax":1,"succeeds":1}
,"gets":{"value":1}
,"value":{"pdu":1,"seconds":1}
,"pdu":{"timer":1}
,"timer":{"smi":1,"value":1}
,"smi":{"calls":1}
,"calls":{"function":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"efm_oam_pdu_timer_get":1}
,"(struct":{"interface":1}
,"interface":{"*ifp":1,"structure":1,"found":1,"efm_oam_err_internal":1}
,"*ifp":{"u_int8_t":1}
,"u_int8_t":{"*secs)":1}
,"*secs)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"secs":1}
,"ifp":{"pointer":1}
,"pointer":{"interface":1}
,"structure":{"output":1}
,"output":{"parameters":1}
,"secs":{"timer":1}
,"seconds":{"return":1}
,"return":{"values":1}
,"values":{"efm_oam_err_if_not_found":1}
,"efm_oam_err_if_not_found":{"onmd":1}
,"onmd":{"interface":1}
,"found":{"efm_oam_err_not_enabled":1}
,"efm_oam_err_not_enabled":{"efm":1}
,"efm":{"enabled":1}
,"enabled":{"interface":1}
,"efm_oam_err_internal":{"internal":1}
,"internal":{"error":1}
,"error":{"efm_success":1}
,"efm_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
