var pairs =
{
"1dm":{"command":1,"(unicast":1,"observed":1,"multicast":1}
,"command":{"configure":1,"syntax":1,"mode":1}
,"configure":{"one-way":1}
,"one-way":{"delay":1}
,"delay":{"measurement":1}
,"measurement":{"(1dm)":1}
,"(1dm)":{"mep":1}
,"mep":{"command":1,"unicast":1,"configuration":1}
,"syntax":{"1dm":1}
,"(unicast":{"(rmpid":1}
,"(rmpid":{"mepid)":1}
,"mepid)":{"multicast)":1}
,"multicast)":{"duration":1}
,"duration":{"duration":1,"((interval":1,"1dm":1}
,"((interval":{"4))":1}
,"4))":{"parameters":1}
,"parameters":{"unicast":1}
,"unicast":{"specify":1,"frames":1}
,"specify":{"unicast":1,"multicast":1}
,"frames":{"sent":1,"multicast":1}
,"sent":{"rmpid":1,"duration":1}
,"rmpid":{"remote":1}
,"remote":{"mep":1}
,"multicast":{"specify":1,"frames":1,"duration":1}
,"observed":{"seconds":1}
,"seconds":{"<5-60>":1,"command":1}
,"<5-60>":{"interval":1}
,"interval":{"transmission":1,"100":1}
,"transmission":{"interval":1}
,"100":{"milliseconds":1}
,"milliseconds":{"milliseconds":1,"second":1}
,"second":{"seconds":1}
,"mode":{"ethernet":1,"examples":1}
,"ethernet":{"cfm":1}
,"cfm":{"pbb-te":1}
,"pbb-te":{"mep":1}
,"configuration":{"mode":1}
,"examples":{"(config-cfm-pbb-te-mep)":1}
,"(config-cfm-pbb-te-mep)":{"1dm":1}
}
;Search.control.loadWordPairs(pairs);
