var pairs =
{
"bridge":{"protocol":1,"mstp":1,"created":1,"<1-32>":1,"bridge":1,"edge":1,"command":1}
,"protocol":{"provider-mstp":1,"(mstp)":1,"rapid":1,"provides":1}
,"provider-mstp":{"command":1,"(edge":1,"edge":1}
,"command":{"create":1,"creates":1,"forms":1,"syntax":1,"mode":1}
,"create":{"provider":1}
,"provider":{"multiple":1}
,"multiple":{"spanning-tree":1,"spanning":1}
,"spanning-tree":{"protocol":1,"topologies":1}
,"(mstp)":{"bridge":1}
,"mstp":{"bridges":1}
,"bridges":{"different":1,"multiple":1}
,"different":{"spanning-tree":1,"vlans":1}
,"topologies":{"different":1}
,"vlans":{"inside":1,"specified":1}
,"inside":{"region":1}
,"region":{"similar":1,"command":1}
,"similar":{"mstp":1}
,"spanning":{"tree":1}
,"tree":{"protocol":1,"associates":1}
,"rapid":{"spanning":1,"reconfiguration":1}
,"provides":{"rapid":1}
,"reconfiguration":{"features":1}
,"features":{"providing":1}
,"providing":{"load-balancing":1}
,"load-balancing":{"capability":1}
,"capability":{"using":1}
,"using":{"command":1}
,"creates":{"instance":1}
,"instance":{"spanning":1,"bridge":1}
,"associates":{"vlans":1}
,"specified":{"instance":1}
,"created":{"command":1}
,"forms":{"separate":1}
,"separate":{"region":1}
,"syntax":{"bridge":1}
,"<1-32>":{"protocol":1,"bridge":1}
,"(edge":{"parameters":1}
,"parameters":{"bridge":1}
,"edge":{"configure":1,"bridge":1}
,"configure":{"edge":1,"mode":1,"terminal":1}
,"mode":{"configure":1,"example":1}
,"example":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"bridge":1}
}
;Search.control.loadWordPairs(pairs);
