var pairs =
{
"zebos2":{"configure":1}
,"configure":{"terminal":1,"mode":1,"synchronous":1,"interface":1,"eth9":1,"eth10":1,"eth11":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"interface":1}
,"mode":{"(config)":1,"(config-synce)":1,"ql-disabled":1,"(config-if-synce)":1,"synchronous":1,"(config-if)":1}
,"(config)":{"synce":1,"interface":1,"int":1}
,"synce":{"enter":1}
,"synchronous":{"ethernet":1,"configure":1,"mode":1}
,"ethernet":{"mode":1}
,"(config-synce)":{"clock-selection":1,"exit":1}
,"clock-selection":{"mode":1}
,"ql-disabled":{"disable":1}
,"disable":{"quality":1}
,"quality":{"level":1}
,"level":{"checking":1}
,"checking":{"(config-synce)":1}
,"exit":{"exit":1,"configure":1,"interface":1}
,"interface":{"eth9":1,"synchronous":1,"input":1,"mode":1,"eth10":1,"eth11":1}
,"eth9":{"configure":1,"(config-if)":1,"layer":1}
,"(config-if)":{"switchport":1,"synce":1,"exit":1}
,"switchport":{"configure":1}
,"layer":{"port":1}
,"port":{"(config-if)":1}
,"(config-if-synce)":{"mode":1,"input-source":1,"exit":1,"switch-source":1,"lockout":1}
,"input-source":{"configure":1}
,"input":{"source":1}
,"source":{"priority":1,"using":1,"selection":1}
,"priority":{"(config-if-synce)":1}
,"int":{"eth10":1,"eth11":1}
,"eth10":{"configure":1,"(config-if)":1,"layer":1}
,"switch-source":{"force":1}
,"force":{"select":1,"external":1}
,"select":{"source":1}
,"using":{"force":1}
,"external":{"command":1}
,"command":{"(config-if-synce)":1}
,"eth11":{"configure":1,"(config-if)":1,"layer":1}
,"lockout":{"remove":1}
,"remove":{"source":1}
,"selection":{"process":1}
,"process":{"(config-if-synce)":1}
}
;Search.control.loadWordPairs(pairs);
