var pairs =
{
"wrapping":{"ring":1,"technique":1,"protection":1}
,"ring":{"protection":1,"node":1,"labels":1,"traffic":1}
,"protection":{"scheme":1,"switching":1,"lsps\u002Ftunnels":1,"lsp\u002Ftunnel":1,"labels":1,"label":1}
,"scheme":{"wrapping":1,"label":1}
,"technique":{"defines":1}
,"defines":{"mechanism":1}
,"mechanism":{"send":1}
,"send":{"automatic":1,"aps":1}
,"automatic":{"protection":1}
,"switching":{"(aps)":1,"revert":1,"working":1,"scheme":1}
,"(aps)":{"request":1}
,"request":{"node":1,"transmitted":1,"aps":1,"cleared":1,"around":1}
,"node":{"detecting":1,"adjacent":1,"detects":1,"traffic":1,"(adjacent":1,"switches":1,"switched":1,"dropped":1,"failure":1,"fails":1}
,"detecting":{"failure":1}
,"failure":{"node":1,"aps":1,"receives":1,"example":1,"working":1,"p-t-p":1,"failure":1,"occurs":1}
,"adjacent":{"(opposite":1}
,"(opposite":{"failure)":1}
,"failure)":{"failure":1,"traffic":1,"switched":1}
,"aps":{"request":1,"communication":1,"protocol":1}
,"transmitted":{"aps":1,"towards":1}
,"communication":{"protocol":1}
,"protocol":{"node":1,"addressed":1}
,"detects":{"failure":1}
,"receives":{"aps":1}
,"addressed":{"node":1}
,"traffic":{"working":1,"travels":1,"flow":1,"switching":1,"lsp":1}
,"working":{"lsps\u002Ftunnels":1,"mpls-tp":1,"protection":1,"labels":1,"label":1}
,"lsps\u002Ftunnels":{"transmitted":1,"opposite":1,"nodes":1,"associated":1,"allow":1,"p-t-p":1}
,"towards":{"failed":1}
,"failed":{"span":1,"links":1}
,"span":{"switched":1}
,"switched":{"protection":1,"back":1}
,"opposite":{"direction":1,"normal":1}
,"direction":{"(away":1,"nodes":1,"counterclockwise":1,"opposite":1}
,"(away":{"failure)":1}
,"travels":{"around":1}
,"around":{"ring":1}
,"(adjacent":{"failure)":1}
,"back":{"onto":1}
,"onto":{"working":1}
,"nodes":{"performed":1,"ring":1,"nodes":1,"send":1}
,"performed":{"protection":1}
,"revert":{"normal":1}
,"normal":{"traffic":1,"working":1,"flow":1}
,"flow":{"failure":1,"labels":1,"traffic":1}
,"cleared":{"normal":1}
,"mpls-tp":{"lsp\u002Ftunnel":1}
,"lsp\u002Ftunnel":{"protection":1,"established":1}
,"established":{"opposite":1}
,"labels":{"assigned":1,"[w1]->":1,"[p1]->":1,"association":1,"used":1}
,"assigned":{"protection":1,"working":1}
,"associated":{"labels":1}
,"allow":{"proper":1}
,"proper":{"traffic":1}
,"p-t-p":{"lsp":1}
,"lsp":{"failure":1,"wrapping":1,"link":1,"working":1,"node":1,"protection":1}
,"example":{"following":1,"p-t-p":1}
,"following":{"example":1}
,"label":{"allocation":1,"[w1]":1,"[p6]":1,"[p4]":1,"[w3]":1,"[p1]":1}
,"allocation":{"p-t-p":1}
,"[w1]->":{"[w2]->":1,"[p6]->":1}
,"[w2]->":{"[w3]->":1}
,"[w3]->":{"protection":1,"p-t-p":1}
,"[p1]->":{"[p2]->":1}
,"[p2]->":{"[p3]->":1}
,"[p3]->":{"[p4]->":1}
,"[p4]->":{"[p5]->":1,"[w3]->":1}
,"[p5]->":{"[p6]->":1}
,"[p6]->":{"working":1,"[p1]->":1}
,"association":{"w1]":1}
,"w1]":{"<->":1}
,"<->":{"[p6]":1,"[p5]":1,"[p4]":1}
,"[p6]":{"[w2]":1,"opposite":1}
,"[w2]":{"<->":1}
,"[p5]":{"[w3]":1}
,"[w3]":{"<->":1,"sent":1}
,"[p4]":{"p-t-p":1,"working":1}
,"link":{"failure":1}
,"occurs":{"nodes":1,"[w1]->":1,"[p1]->":1}
,"switches":{"traffic":1}
,"[w1]":{"protection":1}
,"counterclockwise":{"traffic":1}
,"sent":{"node":1}
,"dropped":{"ring":1}
,"used":{"link":1,"node":1}
,"fails":{"becomes":1}
,"becomes":{"isolated":1}
,"isolated":{"two":1}
,"two":{"failed":1}
,"links":{"nodes":1}
,"[p1]":{"direction":1}
}
;Search.control.loadWordPairs(pairs);
