var pairs =
{
"audience":{"guide":1}
,"guide":{"intended":1}
,"intended":{"developers":1,"target":1}
,"developers":{"build":1}
,"build":{"zebos-xp":1,"environment":1}
,"zebos-xp":{"minimum":1}
,"minimum":{"need":1}
,"need":{"familiar":1}
,"familiar":{"linux":1}
,"linux":{"operating":1}
,"operating":{"systems":1}
,"systems":{"command":1}
,"command":{"line":1}
,"line":{"interfaces":1}
,"interfaces":{"configure":1}
,"configure":{"working":1,"internet":1}
,"working":{"build":1}
,"environment":{"intended":1}
,"target":{"example":1}
,"example":{"server":1}
,"server":{"router":1}
,"router":{"switch":1}
,"switch":{"cross-compilation":1}
,"cross-compilation":{"process":1}
,"process":{"using":1}
,"using":{"configure":1}
,"internet":{"routing":1}
,"routing":{"switching":1}
,"switching":{"software":1}
,"software":{"protocols":1}
}
;Search.control.loadWordPairs(pairs);
