var pairs =
{
"controlled":{"calculation":1}
,"calculation":{"solution":1,"done":1,"computes":1,"deferred":1}
,"solution":{"whenever":1}
,"whenever":{"topology":1}
,"topology":{"change":1}
,"change":{"summary":1}
,"summary":{"external":1}
,"external":{"nssa":1}
,"nssa":{"lsa":1}
,"lsa":{"received":1,"results":1}
,"received":{"incremental":1}
,"incremental":{"spf":1}
,"spf":{"calculated":1,"scheduled":1,"calculation":1}
,"calculated":{"independently":1}
,"independently":{"lsa":1}
,"results":{"increased":1}
,"increased":{"cpu":1}
,"cpu":{"utilization":1}
,"utilization":{"transient":1,"possible":1}
,"transient":{"conditions":1}
,"conditions":{"solve":1}
,"solve":{"problem":1}
,"problem":{"rate":1}
,"rate":{"lsas":1}
,"lsas":{"high":1}
,"high":{"spf":1}
,"scheduled":{"incremental":1,"route":1}
,"done":{"reduces":1}
,"reduces":{"cpu":1}
,"possible":{"spf":1}
,"computes":{"routes":1}
,"routes":{"beginning":1}
,"beginning":{"known":1}
,"known":{"spf":1}
,"route":{"calculation":1}
,"deferred":{"lsas":1}
}
;Search.control.loadWordPairs(pairs);
