var pairs =
{
"nickname":{"command":1,"priority":1,"nickname-priority":1,"parameters":1,"value":1,"root-priority":1}
,"command":{"nickname":1,"reset":1,"syntax":1,"mode":1}
,"priority":{"nickname":1,"d-tree":1}
,"d-tree":{"parameter":1,"command":1}
,"parameter":{"command":1,"<128-255>":1,"<0-65535>":1}
,"reset":{"configuration":1}
,"configuration":{"command":1}
,"syntax":{"nickname":1}
,"nickname-priority":{"<128-255>":1,"indicate":1,"parameter":1,"155":1}
,"<128-255>":{"root-priority":1,"specify":1}
,"root-priority":{"<0-65535>":1,"indicate":1,"parameter":1,"4000":1}
,"<0-65535>":{"nickname":1,"specify":1}
,"parameters":{"specify":1}
,"specify":{"nickname":1,"priority":1,"actual":1}
,"value":{"hexadecimal":1}
,"hexadecimal":{"range":1}
,"range":{"nickname-priority":1}
,"indicate":{"nickname-priority":1,"root-priority":1}
,"actual":{"priority":1}
,"mode":{"rbridge":1,"examples":1}
,"rbridge":{"mode":1,"trill":1}
,"examples":{"enable":1}
,"enable":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"bridge":1,"rbridge":1}
,"bridge":{"protocol":1}
,"protocol":{"trill":1}
,"trill":{"(config)":1,"(config-rb)":1}
,"(config-rb)":{"nickname":1}
,"155":{"root-priority":1}
,"4000":{"(config-rb)":1}
}
;Search.control.loadWordPairs(pairs);
