var pairs =
{
"rip2_get_next_if_conf_address":{"function":1,"(int":1}
,"function":{"returns":1}
,"returns":{"address":1}
,"address":{"next":1,"interface":1,"specified":1,"found":1}
,"next":{"system":1,"entry":1}
,"system":{"indicated":1}
,"indicated":{"subnet":1}
,"subnet":{"address":1,"return":1}
,"interface":{"index":1,"indexlen":1}
,"index":{"partial":1,"complete":1}
,"partial":{"match":1}
,"match":{"located":1,"error":1}
,"located":{"table":1,"next":1}
,"table":{"entry":1}
,"entry":{"returned":1,"error":1}
,"returned":{"match":1,"address":1,"next":1,"indexlen":1,"syntax":1}
,"error":{"returned":1}
,"complete":{"match":1}
,"indexlen":{"zero":1,"struct":1,"future":1}
,"zero":{"first":1}
,"first":{"entry":1}
,"syntax":{"int":1}
,"int":{"rip2_get_next_if_conf_address":1,"indexlen":1}
,"(int":{"pid":1}
,"pid":{"struct":1,"rip":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"*addr":1,"*outaddr)":1}
,"*addr":{"int":1}
,"*outaddr)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"pid":1,"outaddr":1}
,"rip":{"process":1}
,"process":{"addr":1}
,"addr":{"address":1}
,"specified":{"interface":1}
,"future":{"output":1}
,"output":{"parameters":1}
,"outaddr":{"address":1}
,"return":{"values":1}
,"values":{"rip_api_get_error":1}
,"rip_api_get_error":{"address":1}
,"found":{"rip_api_get_success":1}
,"rip_api_get_success":{"call":1}
,"call":{"finds":1}
,"finds":{"address":1}
}
;Search.control.loadWordPairs(pairs);
