var pairs =
{
"edge":{"virtual":1}
,"virtual":{"bridging":1}
,"bridging":{"commands":1,"(evb)":1}
,"commands":{"chapter":1,"bridge":1}
,"chapter":{"describes":1}
,"describes":{"edge":1}
,"(evb)":{"commands":1}
,"bridge":{"protocol":1,"cdcp":1,"ecp-acktimer":1,"ecp-max-retry":1,"resource-wait-delay":1,"tlv-mode":1,"vdp-keep-alive":1}
,"protocol":{"debug":1}
,"debug":{"ecp":1}
,"ecp":{"evb":1,"show":1,"statistics":1}
,"evb":{"bridge":1,"cdcp":1,"reflective-relay":1,"ecp":1,"interface":1,"vdp":1}
,"cdcp":{"channel-capacity":1,"svid-pool-range":1,"evb":1}
,"channel-capacity":{"evb":1}
,"svid-pool-range":{"evb":1}
,"ecp-acktimer":{"evb":1}
,"ecp-max-retry":{"evb":1}
,"resource-wait-delay":{"evb":1}
,"tlv-mode":{"evb":1}
,"vdp-keep-alive":{"evb":1}
,"reflective-relay":{"evb-station":1}
,"evb-station":{"ecp":1}
,"show":{"evb":1,"evb-bridge":1}
,"statistics":{"show":1}
,"interface":{"show":1}
,"vdp":{"vsi-info":1}
,"vsi-info":{"show":1}
,"evb-bridge":{"switchport":1}
,"switchport":{"mode":1}
,"mode":{"sbp":1,"uap":1}
,"sbp":{"switchport":1}
}
;Search.control.loadWordPairs(pairs);
