var pairs =
{
"nsm":{"client":1,"addition":1,"message":1,"connection":1,"elmi":1}
,"client":{"parser":1,"installs":1}
,"parser":{"callback":1,"routine":1,"functions":1,"function":1}
,"callback":{"nsm":1,"function":1}
,"installs":{"parsers":1}
,"parsers":{"message":1}
,"message":{"received":1,"header":1,"pointer":1,"structure":1,"introduced":1}
,"received":{"nsm":1}
,"addition":{"elmi":1}
,"elmi":{"module":1,"new":1,"protocol":1}
,"module":{"registers":1}
,"registers":{"callback":1}
,"function":{"called":1,"follows":1,"nsm_client_create":1,"added":1}
,"called":{"respective":1}
,"respective":{"parser":1}
,"routine":{"prototype":1}
,"prototype":{"callback":1}
,"follows":{"int":1}
,"int":{"nsm_callback":1}
,"nsm_callback":{"(struct":1}
,"(struct":{"nsm_msg_header":1}
,"nsm_msg_header":{"*header":1}
,"*header":{"void":1}
,"void":{"*arg":1,"*message)":1}
,"*arg":{"void":1}
,"*message)":{"header":1}
,"header":{"pointer":1,"arg":1}
,"pointer":{"nsm":1,"message":1}
,"arg":{"pointer":1}
,"connection":{"handler":1}
,"handler":{"message":1}
,"structure":{"function":1}
,"nsm_client_create":{"updated":1}
,"updated":{"parser":1}
,"functions":{"required":1}
,"required":{"communication":1}
,"communication":{"nsm":1}
,"new":{"parser":1,"message":1}
,"added":{"new":1}
,"introduced":{"nsm":1}
}
;Search.control.loadWordPairs(pairs);
