var pairs =
{
"ospf6_set_if_type":{"function":1,"(char":1}
,"function":{"sets":1,"succeeds":1,"fails":1}
,"sets":{"interface":1}
,"interface":{"type":1,"syntax":1,"index":1,"types":1,"invalid":1}
,"type":{"given":1,"interface":1}
,"given":{"ospfv3":1}
,"ospfv3":{"interface":1,"process":1}
,"syntax":{"int":1}
,"int":{"ospf6_set_if_type":1,"ifindex":1,"instid":1,"type)":1}
,"(char":{"*tag":1}
,"*tag":{"int":1}
,"ifindex":{"int":1,"interface":1}
,"instid":{"int":1,"instance":1}
,"type)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"tag":1,"none":1}
,"tag":{"ospfv3":1,"ifindex":1}
,"process":{"tag":1}
,"index":{"instid":1}
,"instance":{"identifier":1}
,"identifier":{"type":1}
,"types":{"ospf_iftype_broadcast":1}
,"ospf_iftype_broadcast":{"broadcast":1}
,"broadcast":{"ospf_iftype_nbma":1}
,"ospf_iftype_nbma":{"non-broadcast":1}
,"non-broadcast":{"multi-access":1}
,"multi-access":{"(nbma)":1}
,"(nbma)":{"ospf_iftype_pointopoint":1}
,"ospf_iftype_pointopoint":{"point-to-point":1}
,"point-to-point":{"ospf_iftype_pointomultipoint":1}
,"ospf_iftype_pointomultipoint":{"point-to-multipoint":1}
,"point-to-multipoint":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"ospf6_api_set_success":1}
,"ospf6_api_set_success":{"function":1}
,"succeeds":{"ospf6_api_set_error":1}
,"ospf6_api_set_error":{"function":1}
,"fails":{"ospf6_api_set_err_vr_not_exist":1}
,"ospf6_api_set_err_vr_not_exist":{"virtual":1}
,"virtual":{"router":1}
,"router":{"exist":1}
,"exist":{"ospf6_api_set_err_if_network_type_invalid":1}
,"ospf6_api_set_err_if_network_type_invalid":{"network":1}
,"network":{"configured":1}
,"configured":{"interface":1}
}
;Search.control.loadWordPairs(pairs);
