var pairs =
{
"show":{"mpls-tp":1}
,"mpls-tp":{"rps":1}
,"rps":{"protection-group":1,"protection":1}
,"protection-group":{"command":1,"parameters":1,"<=================================================================group":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"information":1}
,"information":{"configured":1}
,"configured":{"mpls-tp":1}
,"protection":{"groups":1}
,"groups":{"command":1}
,"syntax":{"show":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"privileged":1,"revertive":1}
,"privileged":{"exec":1}
,"exec":{"exec":1,"modes":1}
,"modes":{"examples":1}
,"examples":{"show":1}
,"<=================================================================group":{"name":1}
,"name":{"abc":1,"def":1}
,"abc":{"oper":1}
,"oper":{"status":1}
,"status":{"revertive":1}
,"revertive":{"mode":1,"wtr":1}
,"wtr":{"timer":1}
,"timer":{"300":1,"sec":1}
,"300":{"sec":1}
,"sec":{"hold-off":1,"primary":1}
,"hold-off":{"timer":1}
,"primary":{"meg":1,"mip-id":1}
,"meg":{"meg1":1,"meg2":1,"meg3":1,"meg4":1}
,"meg1":{"backup":1}
,"backup":{"meg":1,"mip-id":1}
,"meg2":{"primary":1}
,"mip-id":{"backup":1,"group-type":1}
,"group-type":{"itut":1}
,"itut":{"-----------------------------------------------------------------current":1,"----------------------------------------------------------------------current":1}
,"-----------------------------------------------------------------current":{"state":1}
,"state":{"idle":1}
,"idle":{"current":1}
,"current":{"event":1}
,"event":{"-<================================================================<================================================================group":1,"-<===================================================================":1}
,"-<================================================================<================================================================group":{"name":1}
,"def":{"oper":1}
,"meg3":{"backup":1}
,"meg4":{"primary":1}
,"----------------------------------------------------------------------current":{"state":1}
}
;Search.control.loadWordPairs(pairs);
