var pairs =
{
"mrib6_api_multicast_routing_set":{"function":1,"(u_int32_t":1}
,"function":{"starts":1,"used":1,"succeeds":1}
,"starts":{"ipv6":1}
,"ipv6":{"multicast":1,"multicast-routing":1}
,"multicast":{"routing":1}
,"routing":{"router":1}
,"router":{"mribd":1,"vrf_id":1,"used":1}
,"mribd":{"process":1}
,"process":{"function":1}
,"used":{"implement":1,"mrib_api_set_err_wrong_vrf":1,"mrib_api_set_success":1}
,"implement":{"ipv6":1}
,"multicast-routing":{"command":1}
,"command":{"syntax":1}
,"syntax":{"int":1}
,"int":{"mrib6_api_multicast_routing_set":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"vrf_id_t":1,"virtual":1}
,"vrf_id_t":{"vrf_id)":1}
,"vrf_id)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"vrf_id":{"vpn":1}
,"vpn":{"routing\u002Fforwarding":1}
,"routing\u002Fforwarding":{"instance":1}
,"instance":{"output":1,"used":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"mrib_api_set_err_wrong_vr":1}
,"mrib_api_set_err_wrong_vr":{"invalid":1}
,"invalid":{"virtual":1,"vpn":1}
,"mrib_api_set_err_wrong_vrf":{"invalid":1}
,"mrib_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
