var pairs =
{
"rmon_coll_history_interval_set":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"succeeds":1,"fails":1}
,"sets":{"interval":1}
,"interval":{"history":1,"polling":1,"output":1}
,"history":{"control":1}
,"control":{"entry":1}
,"entry":{"interface":1,"index":1}
,"interface":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"rmon_coll_history_interval_set":1}
,"(u_int32_t":{"index":1}
,"index":{"u_int32_t":1,"history":1,"interval":1}
,"u_int32_t":{"interval)":1}
,"interval)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"index":1,"none":1}
,"polling":{"interval":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"result_ok":1}
,"result_ok":{"function":1}
,"succeeds":{"result_error":1}
,"result_error":{"function":1}
}
;Search.control.loadWordPairs(pairs);
