var pairs =
{
"overview":{"rapid":1}
,"rapid":{"per":1}
,"per":{"vlan":1}
,"vlan":{"spanning":1,"defined":1,"runs":1}
,"spanning":{"tree":1}
,"tree":{"plus":1}
,"plus":{"(rpvst":1}
,"(rpvst":{"protocol":1}
,"protocol":{"builds":1}
,"builds":{"individual":1}
,"individual":{"spanning-tree":1}
,"spanning-tree":{"topology":1,"instance":1,"topologies":1}
,"topology":{"vlan":1,"runs":1}
,"defined":{"bridge":1}
,"bridge":{"topology":1}
,"runs":{"rpvst":1,"independent":1}
,"rpvst":{"802.1q":1,"mode":1,"bridges":1,"module":1}
,"802.1q":{"trunks":1,"inter-switch":1}
,"trunks":{"client":1,"rpvst":1}
,"client":{"puts":1}
,"puts":{"switch":1}
,"switch":{"rpvst":1,"support":1}
,"mode":{"switch":1,"vlan":1}
,"support":{"rpvst":1}
,"inter-switch":{"trunks":1}
,"independent":{"spanning-tree":1}
,"instance":{"addition":1}
,"addition":{"rpvst":1}
,"bridges":{"different":1}
,"different":{"spanning-tree":1,"vlans":1}
,"topologies":{"different":1}
,"vlans":{"within":1}
,"within":{"autonomous":1}
,"autonomous":{"switching":1}
,"switching":{"domain":1}
,"domain":{"zebos-xp":1}
,"zebos-xp":{"rpvst":1}
,"module":{"implemented":1}
,"implemented":{"part":1}
,"part":{"mstp":1}
,"mstp":{"module":1}
}
;Search.control.loadWordPairs(pairs);
