var pairs =
{
"xstp":{"callbacks":1}
,"callbacks":{"following":1,"callbacks":1,"description":1}
,"following":{"table":1}
,"table":{"displays":1}
,"displays":{"xstp":1}
,"description":{"set_stp_port_state":1}
,"set_stp_port_state":{"port":1}
,"port":{"stp":1}
,"stp":{"state":1}
,"state":{"blocked":1}
,"blocked":{"listening":1}
,"listening":{"learning":1}
,"learning":{"forwarding":1}
,"forwarding":{"add_instance":1}
,"add_instance":{"add":1}
,"add":{"bridge":1,"vlan":1}
,"bridge":{"instance":1}
,"instance":{"(mstp)":1,"add_vlan_to_instance":1,"delete_vlan_from_instance":1}
,"(mstp)":{"delete_instance":1}
,"delete_instance":{"remove":1}
,"remove":{"bridge":1}
,"add_vlan_to_instance":{"add":1}
,"vlan":{"instance":1}
,"delete_vlan_from_instance":{"delete":1}
,"delete":{"vlan":1}
}
;Search.control.loadWordPairs(pairs);
