var pairs =
{
"mrib4_igmp_api_clear":{"function":1,"(struct":1}
,"function":{"clears":1,"succeeds":1}
,"clears":{"igmp":1}
,"igmp":{"state":1,"instance":1,"information":1,"group":1,"source":1}
,"state":{"information":1}
,"information":{"syntax":1,"null":1}
,"syntax":{"int":1}
,"int":{"mrib4_igmp_api_clear":1}
,"(struct":{"igmp_instance":1}
,"igmp_instance":{"*igi":1}
,"*igi":{"struct":1}
,"struct":{"interface":1,"pal_in4_addr":1}
,"interface":{"*ifp":1,"clear":1,"null":1,"specified":1}
,"*ifp":{"struct":1}
,"pal_in4_addr":{"*pgrp":1,"*psrc)":1}
,"*pgrp":{"struct":1}
,"*psrc)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"igi":1,"none":1}
,"igi":{"pointer":1}
,"pointer":{"igmp":1,"specific":1}
,"instance":{"ifp":1,"cleared":1,"specified":1}
,"ifp":{"pointer":1,"pgrp":1}
,"specific":{"interface":1,"igmp":1}
,"clear":{"igmp":1}
,"null":{"igmp":1,"output":1,"supported":1}
,"group":{"source":1,"address":1,"record":1}
,"source":{"records":1,"address":1,"record":1}
,"records":{"interfaces":1,"cleared":1}
,"interfaces":{"belonging":1}
,"belonging":{"igmp":1}
,"cleared":{"pgrp":1,"null":1,"psrc":1,"cannot":1}
,"pgrp":{"pointer":1,"null":1}
,"address":{"cleared":1}
,"psrc":{"pointer":1}
,"cannot":{"non-null":1}
,"non-null":{"ifp":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"igmp_err_none":1,"given":1}
,"igmp_err_none":{"function":1}
,"succeeds":{"igmp_err_invalid_value":1}
,"igmp_err_invalid_value":{"igmp":1}
,"specified":{"interface":1,"found":1}
,"supported":{"values":1}
,"given":{"igmp_err_no_such_iff":1}
,"igmp_err_no_such_iff":{"interface":1}
,"found":{"igmp_err_no_such_group_rec":1,"igmp_err_no_such_source_rec":1,"igmp_err_oom":1}
,"igmp_err_no_such_group_rec":{"group":1}
,"record":{"found":1}
,"igmp_err_no_such_source_rec":{"source":1}
,"igmp_err_oom":{"memory":1}
,"memory":{"allocation":1}
,"allocation":{"error":1}
,"error":{"occurs":1}
,"occurs":{"igmp_err_malformed_arg":1}
,"igmp_err_malformed_arg":{"argument":1}
,"argument":{"malformed":1}
}
;Search.control.loadWordPairs(pairs);
