var pairs =
{
"ieee8021pbbpiptable":{"contains":1}
,"contains":{"configuration":1}
,"configuration":{"settings":1}
,"settings":{"provider":1}
,"provider":{"instance":1}
,"instance":{"ports":1}
,"ports":{"(pips)":1}
,"(pips)":{"bridge":1}
,"bridge":{"object":1}
,"object":{"type":1}
,"type":{"syntax":1}
,"syntax":{"access":1}
,"access":{"ieee8021pbbpipbmacaddress":1}
,"ieee8021pbbpipbmacaddress":{"macaddress":1}
,"macaddress":{"read-create":1}
,"read-create":{"ieee8021pbbpipname":1,"ieee8021pbbpipicomponentid":1}
,"ieee8021pbbpipname":{"snmpadminstring":1}
,"snmpadminstring":{"read-create":1}
,"ieee8021pbbpipicomponentid":{"ieee8021pbbcomponentidentifier":1}
,"ieee8021pbbcomponentidentifier":{"read-only":1}
,"read-only":{"ieee8021pbbpipvipmap":1}
,"ieee8021pbbpipvipmap":{"octet":1}
,"octet":{"string":1}
,"string":{"read-create":1}
}
;Search.control.loadWordPairs(pairs);
