var pairs =
{
"isis_get_sys_next_circ_index":{"call":1}
,"call":{"gets":1}
,"gets":{"next":1}
,"next":{"isis":1}
,"isis":{"circ":1}
,"circ":{"index":1}
,"index":{"value":1}
,"value":{"instance":1,"non-vr":1,"return":1}
,"instance":{"is-is":1,"u_int32_t":1,"output":1,"found":1}
,"is-is":{"protocol":1,"instance":1}
,"protocol":{"syntax":1}
,"syntax":{"int":1}
,"int":{"isis_get_sys_log_adj_changes":1}
,"isis_get_sys_log_adj_changes":{"(u_int32_t":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1,"instance":1}
,"u_int32_t":{"instance":1,"*ret)":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"ret":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"output":{"parameters":1}
,"ret":{"next":1}
,"return":{"values":1}
,"values":{"isis_api_get_success":1}
,"isis_api_get_success":{"instance":1}
,"found":{"isis_api_get_error":1}
,"isis_api_get_error":{"instance":1}
}
;Search.control.loadWordPairs(pairs);
