var pairs =
{
"mlag":{"configuration":1}
,"configuration":{"command":1,"mode":1,"except":1,"<1-65535>":1,"245":1}
,"command":{"enter":1,"remove":1,"syntax":1,"mode":1}
,"enter":{"mc-lag":1}
,"mc-lag":{"configuration":1,"mapping":1,"identifier":1}
,"mode":{"multi-chassis":1,"configure":1,"examples":1}
,"multi-chassis":{"link":1}
,"link":{"aggregation":1}
,"aggregation":{"features":1,"configuration":1}
,"features":{"form":1}
,"form":{"command":1}
,"remove":{"multi-chassis":1}
,"except":{"port":1}
,"port":{"channel":1}
,"channel":{"mc-lag":1}
,"mapping":{"command":1}
,"syntax":{"mlag":1}
,"<1-65535>":{"mlag":1,"parameters":1,"mc-lag":1}
,"parameters":{"<1-65535>":1}
,"identifier":{"command":1}
,"configure":{"mode":1,"terminal":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"mlag":1}
,"245":{"(config-mlag)":1}
}
;Search.control.loadWordPairs(pairs);
