var pairs =
{
"gmrp":{"extended-filtering":1,"switch":1}
,"extended-filtering":{"command":1,"enable":1,"disable":1}
,"command":{"enable":1,"syntax":1,"mode":1}
,"enable":{"disable":1,"bridge":1,"enables":1,"extended":1}
,"disable":{"extended":1,"bridge":1,"disables":1}
,"extended":{"filtering":1}
,"filtering":{"bridge":1,"disabled":1,"services":1}
,"bridge":{"per":1,"bridge_name":1,"identifier":1,"command":1,"disable":1,"configure":1}
,"per":{"table":1}
,"table":{"8-7":1}
,"8-7":{"ieee802.1q-2003":1}
,"ieee802.1q-2003":{"command":1}
,"syntax":{"gmrp":1}
,"bridge_name":{"gmrp":1,"parameters":1,"bridge":1}
,"parameters":{"enable":1}
,"enables":{"gmrp":1}
,"switch":{"disable":1,"bridge_name":1}
,"disables":{"gmrp":1}
,"identifier":{"default":1}
,"default":{"extended":1}
,"disabled":{"gmrp-enabled":1}
,"gmrp-enabled":{"bridge":1}
,"mode":{"configure":1,"examples":1}
,"configure":{"mode":1,"terminal":1}
,"examples":{"enable":1}
,"services":{"configure":1,"bridge":1}
,"terminal":{"(config)":1}
,"(config)":{"gmrp":1}
}
;Search.control.loadWordPairs(pairs);
