var pairs =
{
"undebug":{"vrrp":1}
,"vrrp":{"events":1,"command":1,"(all":1,"event":1,"packets":1,"example":1,"packet":1}
,"events":{"command":1,"event":1,"undebug":1,"example":1}
,"command":{"disable":1,"syntax":1,"mode":1}
,"disable":{"debugging":1,"debug":1}
,"debugging":{"options":1}
,"options":{"vrrp":1}
,"syntax":{"undebug":1}
,"(all":{"event":1}
,"event":{"packet":1,"specify":1,"troubleshooting":1}
,"packet":{"[send":1,"specify":1,"send":1,"recv":1}
,"[send":{"recv])":1}
,"recv])":{"undebug":1,"parameters":1}
,"parameters":{"specify":1}
,"specify":{"debugging":1,"debug":1}
,"troubleshooting":{"packet":1}
,"packets":{"send":1,"recv":1,"command":1,"sent":1,"received":1}
,"send":{"specify":1,"example":1}
,"debug":{"option":1,"options":1}
,"option":{"sent":1,"received":1}
,"sent":{"packets":1,"undebug":1}
,"recv":{"specify":1}
,"received":{"packets":1,"undebug":1}
,"mode":{"privileged":1,"examples":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"examples":{"undebug":1}
,"example":{"below":1}
,"below":{"shows":1}
,"shows":{"disable":1}
}
;Search.control.loadWordPairs(pairs);
