var pairs =
{
"lldpdu":{"format":1,"frame":1,"tlv":1}
,"format":{"lldpdu":1,"consists":1}
,"frame":{"format":1,"lldpdu":1,"consists":1}
,"consists":{"following":1,"various":1}
,"following":{"fields":1}
,"fields":{"destination":1}
,"destination":{"address":1}
,"address":{"lldp":1,"01:80:c2:00:00:0e":1,"transmitting":1,"ethertype":1}
,"lldp":{"multicast":1,"ethertype":1}
,"multicast":{"destination":1}
,"01:80:c2:00:00:0e":{"source":1}
,"source":{"address":1}
,"transmitting":{"port\u2019s":1}
,"port\u2019s":{"mac":1}
,"mac":{"address":1}
,"ethertype":{"lldp":1,"88-cc":1}
,"88-cc":{"lldpdu":1}
,"various":{"mandatory":1}
,"mandatory":{"optional":1}
,"optional":{"tlvs":1}
,"tlvs":{"last":1}
,"last":{"tlv":1}
,"tlv":{"end":1}
,"end":{"lldpdu":1}
}
;Search.control.loadWordPairs(pairs);
