var pairs =
{
"spb_api_set_ignore_lsp_errors":{"function":1,"(char":1}
,"function":{"tells":1,"implements":1,"succeeds":1}
,"tells":{"spb":1}
,"spb":{"ignore":1}
,"ignore":{"lsps":1}
,"lsps":{"checksum":1}
,"checksum":{"errors":1,"receives":1}
,"errors":{"default":1}
,"default":{"zebos-xp":1}
,"zebos-xp":{"validates":1}
,"validates":{"checksum":1}
,"receives":{"lsp":1}
,"lsp":{"error":1,"dropped":1}
,"error":{"lsp":1}
,"dropped":{"function":1}
,"implements":{"isis-spb":1}
,"isis-spb":{"ignore-lsp-errors":1}
,"ignore-lsp-errors":{"command":1}
,"command":{"syntax":1}
,"syntax":{"include":1}
,"include":{"spbd\u002Fisis-spb\u002Fspb_isis_api.h":1}
,"spbd\u002Fisis-spb\u002Fspb_isis_api.h":{"int":1}
,"int":{"spb_api_set_ignore_lsp_errors":1}
,"(char":{"*bridge_name":1}
,"*bridge_name":{"char":1}
,"char":{"*tag)":1}
,"*tag)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bridge_name":1,"none":1}
,"bridge_name":{"bridge":1,"tag":1}
,"bridge":{"name":1}
,"name":{"tag":1}
,"tag":{"instance":1,"output":1,"null":1,"exist":1}
,"instance":{"area":1,"configuration":1}
,"area":{"tag":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"spb_api_err_arg_null":1}
,"spb_api_err_arg_null":{"bridge_name":1}
,"null":{"spb_isis_api_set_error":1,"port":1,"spb_api_err_config_update":1,"spb_api_err_isis_instance_not_found":1}
,"spb_isis_api_set_error":{"isis":1}
,"isis":{"master":1}
,"master":{"null":1}
,"port":{"instance":1}
,"configuration":{"null":1,"exists":1}
,"spb_api_err_config_update":{"isis":1}
,"exists":{"spb_api_err_isis_master_not_found":1}
,"spb_api_err_isis_master_not_found":{"isis":1}
,"spb_api_err_isis_instance_not_found":{"given":1}
,"given":{"instance":1}
,"exist":{"spb_isis_api_set_success":1}
,"spb_isis_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
