var pairs =
{
"isis_summary_address_unset":{"call":1,"(u_int32_t":1}
,"call":{"implements":1,"successful":1}
,"implements":{"parameter":1}
,"parameter":{"summary-address":1}
,"summary-address":{"command":1}
,"command":{"remove":1}
,"remove":{"summary":1}
,"summary":{"syntax":1}
,"syntax":{"int":1}
,"int":{"isis_summary_address_unset":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1,"tag":1}
,"char":{"*tag":1}
,"*tag":{"struct":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"addr":1}
,"addr":{"u_char":1,"ipv4":1}
,"u_char":{"masklen)":1}
,"masklen)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"tag":{"is-is":1,"addr":1}
,"is-is":{"instance":1}
,"instance":{"tag":1,"exist":1}
,"ipv4":{"network":1}
,"network":{"address":1}
,"address":{"masklen":1}
,"masklen":{"mask":1}
,"mask":{"length":1}
,"length":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"isis_api_set_err_vr_not_exist":1}
,"isis_api_set_err_vr_not_exist":{"exist":1}
,"exist":{"isis_api_set_err_instance_not_exist":1,"isis_api_set_success":1}
,"isis_api_set_err_instance_not_exist":{"is-is":1}
,"isis_api_set_success":{"call":1}
}
;Search.control.loadWordPairs(pairs);
