var pairs =
{
"command":{"api":1,"reference":1}
,"api":{"functions":1}
,"functions":{"section":1}
,"section":{"called":1}
,"called":{"commands":1}
,"commands":{"multicast":1}
,"multicast":{"routing":1,"entry":1}
,"routing":{"information":1}
,"information":{"base":1}
,"base":{"command":1}
,"reference":{"function":1}
,"function":{"description":1}
,"description":{"hal_igmp_snooping_enable":1}
,"hal_igmp_snooping_enable":{"enables":1}
,"enables":{"igmp":1,"mld":1}
,"igmp":{"snooping":1}
,"snooping":{"bridge":1,"interface":1}
,"bridge":{"hal_igmp_snooping_disable":1,"hal_igmp_snooping_if_enable":1,"hal_mld_snooping_disable":1,"hal_mld_snooping_if_enable":1}
,"hal_igmp_snooping_disable":{"disables":1}
,"disables":{"igmp":1,"mld":1}
,"hal_igmp_snooping_if_enable":{"enables":1}
,"interface":{"hal_igmp_snooping_if_disable":1,"hal_igmp_snooping_add_entry":1,"hal_mld_snooping_if_disable":1,"hal_mld_snooping_add_entry":1}
,"hal_igmp_snooping_if_disable":{"disables":1}
,"hal_igmp_snooping_add_entry":{"adds":1}
,"adds":{"multicast":1}
,"entry":{"source":1}
,"source":{"group":1}
,"group":{"given":1}
,"given":{"vlan":1}
,"vlan":{"hal_igmp_snooping_delete_entry":1,"hal_mld_snooping_enable":1,"hal_mld_snooping_delete_entry":1}
,"hal_igmp_snooping_delete_entry":{"deletes":1}
,"deletes":{"multicast":1}
,"hal_mld_snooping_enable":{"enables":1}
,"mld":{"snooping":1}
,"hal_mld_snooping_disable":{"disables":1}
,"hal_mld_snooping_if_enable":{"enables":1}
,"hal_mld_snooping_if_disable":{"disables":1}
,"hal_mld_snooping_add_entry":{"adds":1}
,"hal_mld_snooping_delete_entry":{"deletes":1}
}
;Search.control.loadWordPairs(pairs);
