var pairs =
{
"isis-spb":{"hello-interval":1,"hello-multiplier":1}
,"hello-interval":{"command":1,"<1-65535>":1,"minimal":1,"(level-1":1,"level-1":1}
,"command":{"time":1,"hello":1,"syntax":1,"level-1":1,"mode":1}
,"time":{"interval":1}
,"interval":{"hello":1,"default":1,"seconds":1,"dividing":1,"level-1":1,"level-2":1,"interval":1,"applied":1}
,"hello":{"transmissions":1,"interval":1,"pdu":1,"multiplier":1}
,"transmissions":{"form":1}
,"form":{"command":1}
,"default":{"(10":1,"default":1,"zebos-xp":1}
,"(10":{"seconds)":1}
,"seconds)":{"command":1}
,"syntax":{"isis-spb":1}
,"<1-65535>":{"(level-1":1,"specify":1}
,"(level-1":{"level-2":1}
,"level-2":{"isis-spb":1,"parameters":1,"specify":1,"is-is":1}
,"minimal":{"(level-1":1,"specify":1}
,"parameters":{"<1-65535>":1}
,"specify":{"hello":1,"holding-time":1,"parameter":1,"interval":1}
,"seconds":{"minimal":1,"interval":1}
,"holding-time":{"second":1}
,"second":{"zebos-xp":1}
,"zebos-xp":{"calculates":1,"sends":1,"uses":1}
,"calculates":{"hello":1}
,"dividing":{"hello-multiplier":1}
,"hello-multiplier":{"example":1,"specify":1,"command":1}
,"example":{"hello-multiplier":1}
,"parameter":{"zebos-xp":1}
,"sends":{"hello":1}
,"pdu":{"every":1}
,"every":{"250":1}
,"250":{"milliseconds":1}
,"milliseconds":{"hello":1}
,"multiplier":{"isis-spb":1}
,"level-1":{"specify":1,"is-is":1,"command":1,"(config)":1}
,"is-is":{"hellos":1}
,"hellos":{"level-2":1,"default":1}
,"uses":{"seconds":1}
,"applied":{"level-1":1}
,"mode":{"interface":1,"examples":1}
,"interface":{"mode":1,"eth0":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"isis-spb":1}
}
;Search.control.loadWordPairs(pairs);
