var pairs =
{
"overview":{"elmi":1}
,"elmi":{"ethernet":1,"provides":1,"includes":1,"works":1,"operation":1}
,"ethernet":{"oam":1,"network":1,"virtual":1}
,"oam":{"(operation":1}
,"(operation":{"administration":1}
,"administration":{"management)":1}
,"management)":{"protocol":1}
,"protocol":{"used":1}
,"used":{"communications":1}
,"communications":{"two":1}
,"two":{"user":1,"networks":1}
,"user":{"network":1}
,"network":{"interfaces":1,"configuration":1,"(men)":1,"interface":1}
,"interfaces":{"(that":1}
,"(that":{"uni-c":1,"active":1}
,"uni-c":{"uni-n)":1,"uni-n":1}
,"uni-n)":{"elmi":1}
,"provides":{"uni":1}
,"uni":{"evc":1}
,"evc":{"(ethernet":1,"deleted":1,"(that":1,"attributes":1}
,"(ethernet":{"virtual":1}
,"virtual":{"connection)":1,"connection":1}
,"connection)":{"status":1}
,"status":{"information":1,"configured":1}
,"information":{"customer":1,"enables":1}
,"customer":{"edge":1}
,"edge":{"(ce)":1}
,"(ce)":{"devices":1}
,"devices":{"information":1}
,"enables":{"automatic":1}
,"automatic":{"configuration":1}
,"configuration":{"operation":1,"elmi":1}
,"operation":{"based":1,"elmi":1}
,"based":{"metro":1}
,"metro":{"ethernet":1}
,"includes":{"following":1}
,"following":{"procedures":1}
,"procedures":{"according":1}
,"according":{"mef16":1}
,"mef16":{"specifications":1}
,"specifications":{"notifies":1}
,"notifies":{"device":1}
,"device":{"ethernet":1,"evc":1,"current":1,"elmi":1}
,"connection":{"(evc)":1}
,"(evc)":{"added":1}
,"added":{"notifies":1}
,"deleted":{"notifies":1}
,"current":{"status":1}
,"configured":{"evc":1}
,"active":{"active":1,"partially":1}
,"partially":{"active)":1}
,"active)":{"communicates":1}
,"communicates":{"via":1}
,"via":{"metro":1}
,"(men)":{"user":1}
,"interface":{"(uni)":1}
,"(uni)":{"evc":1}
,"attributes":{"device":1}
,"works":{"router":1}
,"router":{"architectures":1}
,"architectures":{"specific":1}
,"specific":{"hardware":1}
,"hardware":{"platform":1}
,"platform":{"operates":1}
,"operates":{"uni-c":1}
,"uni-n":{"help":1}
,"help":{"facilitate":1}
,"facilitate":{"communication":1}
,"communication":{"two":1}
,"networks":{"figure":1}
,"figure":{"1-1":1}
,"1-1":{"displays":1}
,"displays":{"simple":1}
,"simple":{"diagram":1}
,"diagram":{"elmi":1}
}
;Search.control.loadWordPairs(pairs);
