var pairs =
{
"spanning-tree":{"guard":1}
,"guard":{"command":1,"feature":1,"enabled":1,"root":1}
,"command":{"enable":1,"disable":1,"syntax":1,"mode":1}
,"enable":{"root":1}
,"root":{"guard":1,"spanning-tree":1,"parameters":1,"disable":1}
,"feature":{"port":1,"disables":1,"makes":1}
,"port":{"feature":1,"enabled":1,"root":1,"receives":1,"command":1}
,"disables":{"reception":1}
,"reception":{"superior":1}
,"superior":{"bpdus":1,"bpdu":1}
,"bpdus":{"root":1,"command":1}
,"makes":{"sure":1}
,"sure":{"port":1}
,"enabled":{"designated":1,"port":1}
,"designated":{"port":1}
,"receives":{"superior":1}
,"bpdu":{"listening":1}
,"listening":{"state":1}
,"state":{"(for":1}
,"(for":{"stp)":1,"rstp":1}
,"stp)":{"discarding":1}
,"discarding":{"state":1}
,"rstp":{"mstp)":1}
,"mstp)":{"parameter":1}
,"parameter":{"command":1}
,"disable":{"root":1,"reception":1}
,"syntax":{"spanning-tree":1}
,"parameters":{"root":1}
,"mode":{"interface":1,"example":1}
,"interface":{"mode":1,"eth0":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"spanning-tree":1}
}
;Search.control.loadWordPairs(pairs);
