var pairs =
{
"pe2":{"configure":1,"mtu-s":1,"(config-vpls)":1}
,"configure":{"terminal":1,"mode":1,"status":1,"targeted":1,"vlan":1,"pseudowire":1,"vpls":1,"pw3":1,"pw2":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"router":1,"vlan":1,"vpls":1,"interface":1}
,"mode":{"(config)":1,"(config-router)":1,"return":1,"(config-vlan)":1,"(config-vpls-sig)":1,"(config-vpls)":1,"(config-if)":1,"access":1}
,"(config)":{"router":1,"bridge":1,"vlan":1,"mpls":1,"interface":1}
,"router":{"ldp":1}
,"ldp":{"enter":1,"mode":1,"session":1}
,"(config-router)":{"pw-status-tlv":1,"targeted-peer":1,"exit":1}
,"pw-status-tlv":{"configure":1}
,"status":{"tlv":1,"signaling":1}
,"tlv":{"pseudowire":1}
,"pseudowire":{"status":1,"pw2":1}
,"signaling":{"(config-router)":1,"ldp":1}
,"targeted-peer":{"ipv4":1}
,"ipv4":{"3.3.3.3":1,"4.4.4.4":1}
,"3.3.3.3":{"configure":1}
,"targeted":{"ldp":1}
,"session":{"pe3":1,"mtu-s":1}
,"pe3":{"loopback":1}
,"loopback":{"address":1}
,"address":{"(config-router)":1}
,"4.4.4.4":{"configure":1}
,"mtu-s":{"loopback":1,"(config)":1}
,"exit":{"exit":1,"router":1,"vlan":1,"signaling":1,"vpls":1,"interface":1}
,"return":{"configure":1}
,"bridge":{"protocol":1,"(config)":1,"configure":1}
,"protocol":{"ieee":1}
,"ieee":{"vlan-bridge":1}
,"vlan-bridge":{"specify":1}
,"specify":{"vlan":1}
,"vlan":{"bridge":1,"database":1,"100":1,"configure":1,"vc-spoke":1}
,"database":{"enter":1,"mode":1}
,"(config-vlan)":{"vlan":1,"exit":1}
,"100":{"bridge":1,"(config-vlan)":1}
,"mpls":{"l2-circuit":1,"vpls":1}
,"l2-circuit":{"pw2":1}
,"pw2":{"4.4.4.4":1,"pe2":1,"vlan":1}
,"vpls":{"111":1,"signaling":1,"peer":1,"mode":1,"access":1}
,"111":{"configure":1,"pe2":1}
,"(config-vpls)":{"signaling":1,"vpls-vc":1,"exit":1}
,"(config-vpls-sig)":{"vpls-peer":1,"exit":1}
,"vpls-peer":{"3.3.3.3":1}
,"pw3":{"vpls":1}
,"peer":{"(config-vpls-sig)":1}
,"vpls-vc":{"pw2":1}
,"vc-spoke":{"(config-vpls)":1}
,"interface":{"eth3":1,"mode":1,"access":1,"(config-if)":1}
,"eth3":{"enter":1}
,"(config-if)":{"switchport":1,"mpls-vpls":1,"exit":1}
,"switchport":{"switch":1,"mode":1}
,"switch":{"layer-2":1}
,"layer-2":{"mode":1}
,"access":{"switching":1,"mode":1,"interface":1}
,"switching":{"characteristics":1}
,"characteristics":{"interface":1}
,"mpls-vpls":{"bind":1}
,"bind":{"vpls":1}
}
;Search.control.loadWordPairs(pairs);
