var pairs =
{
"command":{"api":1}
,"api":{"table":1}
,"table":{"contains":1}
,"contains":{"functions":1}
,"functions":{"multi-protocol":1}
,"multi-protocol":{"label":1}
,"label":{"switching":1,"value":1,"space":1}
,"switching":{"commands":1}
,"commands":{"function":1}
,"function":{"description":1}
,"description":{"nsm_gmpls_api_add_lsp_tunnel":1}
,"nsm_gmpls_api_add_lsp_tunnel":{"adds":1}
,"adds":{"lsp":1,"mapped":1,"administrative":1}
,"lsp":{"tunnel":1,"model":1}
,"tunnel":{"nsm_gmpls_api_add_mapped_route":1,"nsm_mpls_api_disable_all_interfaces":1}
,"nsm_gmpls_api_add_mapped_route":{"adds":1}
,"mapped":{"route":1}
,"route":{"nsm_gmpls_api_del_mapped_route":1,"nsm_mpls_api_admin_group_add":1}
,"nsm_gmpls_api_del_mapped_route":{"deletes":1}
,"deletes":{"mapped":1,"administrative":1,"lsp":1}
,"nsm_mpls_api_admin_group_add":{"adds":1}
,"administrative":{"group":1}
,"group":{"nsm_mpls_api_admin_group_del":1,"nsm_mpls_api_del_lsp_tunnel":1}
,"nsm_mpls_api_admin_group_del":{"deletes":1}
,"nsm_mpls_api_del_lsp_tunnel":{"deletes":1}
,"nsm_mpls_api_disable_all_interfaces":{"disables":1}
,"disables":{"interfaces":1,"local":1,"ttl":1}
,"interfaces":{"mpls":1,"nsm_mpls_api_max_label_val_unset":1,"nsm_mpls_api_min_label_val_set":1,"nsm_mpls_api_min_label_val_unset":1,"nsm_mpls_api_pipe_model_update":1}
,"mpls":{"capabilities":1}
,"capabilities":{"nsm_mpls_api_egress_ttl_set":1,"nsm_mpls_api_ingress_ttl_set":1}
,"nsm_mpls_api_egress_ttl_set":{"sets":1}
,"sets":{"custom":1,"maximum":1,"minimum":1,"lsp":1}
,"custom":{"ttl":1}
,"ttl":{"lsps":1,"propagation":1}
,"lsps":{"lsr":1}
,"lsr":{"egress":1}
,"egress":{"nsm_mpls_api_enable_all_interfaces":1,"nsm_mpls_api_local_pkt_handling":1}
,"nsm_mpls_api_enable_all_interfaces":{"enables":1}
,"enables":{"interfaces":1,"disables":1}
,"nsm_mpls_api_ingress_ttl_set":{"sets":1}
,"nsm_mpls_api_local_pkt_handling":{"enables":1}
,"local":{"packet":1}
,"packet":{"handling":1}
,"handling":{"locally":1}
,"locally":{"generated":1}
,"generated":{"tcp":1}
,"tcp":{"packets":1}
,"packets":{"nsm_mpls_api_ls_max_label_val_set":1}
,"nsm_mpls_api_ls_max_label_val_set":{"sets":1}
,"maximum":{"label":1}
,"value":{"label":1,"interfaces":1}
,"space":{"nsm_mpls_api_ls_max_label_val_unset":1,"nsm_mpls_api_ls_min_label_val_set":1,"nsm_mpls_api_ls_min_label_val_unset":1,"nsm_mpls_api_max_label_val_set":1}
,"nsm_mpls_api_ls_max_label_val_unset":{"resets":1}
,"resets":{"maximum":1,"minimum":1}
,"nsm_mpls_api_ls_min_label_val_set":{"sets":1}
,"minimum":{"label":1}
,"nsm_mpls_api_ls_min_label_val_unset":{"resets":1}
,"nsm_mpls_api_max_label_val_set":{"sets":1}
,"nsm_mpls_api_max_label_val_unset":{"resets":1}
,"nsm_mpls_api_min_label_val_set":{"sets":1}
,"nsm_mpls_api_min_label_val_unset":{"resets":1}
,"nsm_mpls_api_pipe_model_update":{"sets":1}
,"model":{"pipe":1}
,"pipe":{"uniform":1}
,"uniform":{"nsm_mpls_api_ttl_propagate_cap_update":1}
,"nsm_mpls_api_ttl_propagate_cap_update":{"enables":1}
,"propagation":{"nsm_mpls_check_valid_interface":1}
,"nsm_mpls_check_valid_interface":{"checks":1}
,"checks":{"interface":1}
,"interface":{"valid":1}
,"valid":{"mpls":1}
}
;Search.control.loadWordPairs(pairs);
