var pairs =
{
"sync":{"interval":1}
,"interval":{"command":1,"interval":1,"parameters":1,"mean":1,"second)":1}
,"command":{"mean":1,"syntax":1,"mode":1}
,"mean":{"time":1}
,"time":{"seconds":1}
,"seconds":{"clock":1,"successive":1,"command":1}
,"clock":{"synchronization":1,"port":1}
,"synchronization":{"messages":1,"(sync)":1}
,"messages":{"master":1,"slaves":1,"command":1,"log":1}
,"master":{"clocks":1}
,"clocks":{"transmit":1}
,"transmit":{"synchronization":1}
,"(sync)":{"messages":1}
,"slaves":{"value":1}
,"value":{"logarithm":1}
,"logarithm":{"base":1}
,"base":{"mean":1,"<-1":1}
,"successive":{"clock":1}
,"syntax":{"sync":1}
,"parameters":{"interval":1}
,"log":{"base":1}
,"<-1":{"default":1}
,"default":{"seconds":1}
,"mode":{"ptp":1,"examples":1}
,"ptp":{"clock":1}
,"port":{"configure":1}
,"configure":{"mode":1}
,"examples":{"following":1}
,"following":{"example":1}
,"example":{"sets":1}
,"sets":{"interval":1}
,"second)":{"ena":1}
,"ena":{"config":1}
,"config":{"term":1}
,"term":{"enter":1}
,"enter":{"configuration":1}
,"configuration":{"commands":1}
,"commands":{"per":1}
,"per":{"line":1}
,"line":{"end":1}
,"end":{"cntl\u002Fz":1}
,"cntl\u002Fz":{"(config)":1}
,"(config)":{"interface":1}
,"interface":{"eth0":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"clock-port":1}
,"clock-port":{"(config-clk-port)":1}
,"(config-clk-port)":{"sync":1}
}
;Search.control.loadWordPairs(pairs);
