var pairs =
{
"peer_weight_set":{"function":1,"(struct":1}
,"function":{"sets":1,"called":1,"successful":1}
,"sets":{"bgp":1}
,"bgp":{"peer\u0027s":1,"peer":1}
,"peer\u0027s":{"weight":1}
,"weight":{"value":1,"syntax":1,"afi_t":1,"weight":1}
,"value":{"function":1,"afi":1,"bgp_api_set_success":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"weight":1}
,"syntax":{"int":1}
,"int":{"peer_weight_set":1}
,"(struct":{"bgp_peer":1}
,"bgp_peer":{"*peer":1}
,"*peer":{"u_int16_t":1}
,"u_int16_t":{"weight":1}
,"afi_t":{"afi":1}
,"afi":{"safi_t":1,"address":1}
,"safi_t":{"safi)":1}
,"safi)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"peer":1,"none":1}
,"peer":{"bgp":1,"weight":1,"peer-group":1}
,"address":{"family":1}
,"family":{"identifier":1}
,"identifier":{"safi":1,"output":1}
,"safi":{"subsequent":1}
,"subsequent":{"address":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"bgp_api_set_success":{"function":1}
,"successful":{"(0)":1}
,"(0)":{"bgp_api_set_err_peer_group_has_the_flag":1}
,"bgp_api_set_err_peer_group_has_the_flag":{"peer":1}
,"peer-group":{"member":1,"configuration":1}
,"member":{"change":1}
,"change":{"peer-group":1}
,"configuration":{"(-19)":1}
}
;Search.control.loadWordPairs(pairs);
