var pairs =
{
"trill_static_unicast_egress_unset":{"function":1,"(struct":1}
,"function":{"removes":1,"call":1}
,"removes":{"static":1}
,"static":{"route":1,"unicast-trill":1}
,"route":{"unicast":1}
,"unicast":{"reaching":1}
,"reaching":{"egress":1}
,"egress":{"router":1,"nxt_nickname":1,"output":1}
,"router":{"bridge":1}
,"bridge":{"(rbridge)":1}
,"(rbridge)":{"called":1}
,"called":{"add":1}
,"add":{"static":1}
,"unicast-trill":{"egress-nickname":1}
,"egress-nickname":{"cli":1}
,"cli":{"command":1,"*cli":1,"structure":1}
,"command":{"contained":1}
,"contained":{"trill_api.c":1}
,"trill_api.c":{"file":1}
,"file":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"trill_static_unicast_egress_unset":1}
,"(struct":{"cli":1}
,"*cli":{"u_int16_t":1,"specifies":1}
,"u_int16_t":{"nickname":1,"nxt_nickname)":1}
,"nickname":{"u_int16_t":1,"specifies":1,"egress":1,"next":1}
,"nxt_nickname)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"*cli":1,"none":1}
,"specifies":{"instance":1,"nickname":1}
,"instance":{"cli":1}
,"structure":{"values":1}
,"values":{"includes":1,"trill_api_set_success":1}
,"includes":{"1-31":1}
,"1-31":{"nickname":1}
,"nxt_nickname":{"specifies":1}
,"next":{"egress":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"trill_api_set_success":{"indicates":1}
,"indicates":{"function":1,"nsm":1,"duplicated":1,"memory":1}
,"call":{"worked":1}
,"worked":{"properly":1}
,"properly":{"trill_api_set_err_nsm_send_failed":1}
,"trill_api_set_err_nsm_send_failed":{"indicates":1}
,"nsm":{"sent":1}
,"sent":{"trill_api_set_err_entry_exist":1}
,"trill_api_set_err_entry_exist":{"indicates":1}
,"duplicated":{"entry":1}
,"entry":{"remove":1,"trill_err_memory_alloc_failure":1}
,"remove":{"old":1}
,"old":{"data":1}
,"data":{"entry":1}
,"trill_err_memory_alloc_failure":{"indicates":1}
,"memory":{"available":1}
}
;Search.control.loadWordPairs(pairs);
