var pairs =
{
"show":{"cli":1}
,"cli":{"command":1,"tree":1,"parameters":1,"exec":1}
,"command":{"display":1,"syntax":1,"mode":1,"modes":1,"executed":1}
,"display":{"cli":1}
,"tree":{"current":1}
,"current":{"mode":1}
,"mode":{"command":1,"show":1,"+-clear":1}
,"syntax":{"show":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"modes":{"example":1}
,"example":{"section":1}
,"section":{"sample":1}
,"sample":{"output":1}
,"output":{"show":1}
,"executed":{"exec":1}
,"exec":{"mode":1}
,"+-clear":{"+-arp-cache":1}
,"+-arp-cache":{"[clear":1}
,"[clear":{"arp-cache]":1,"ethernet":1}
,"arp-cache]":{"+-ethernet":1}
,"+-ethernet":{"+-cfm":1}
,"+-cfm":{"+-errors":1}
,"+-errors":{"+-domain":1}
,"+-domain":{"+-domain_name":1}
,"+-domain_name":{"[clear":1}
,"ethernet":{"cfm":1}
,"cfm":{"errors":1,"maintenance-points":1}
,"errors":{"(domain":1}
,"(domain":{"domain_name":1,"--more--":1}
,"domain_name":{"level":1}
,"level":{"lev":1,"leve":1,"level_id)":1}
,"lev":{"el_id)":1}
,"el_id)":{"(bridge":1}
,"(bridge":{"<1-32>":1}
,"<1-32>":{"|)]":1}
,"|)]":{"+-bridge":1,"+-level":1,"+-maintenance-points":1}
,"+-bridge":{"+-<1-32>":1}
,"+-<1-32>":{"[clear":1}
,"leve":{"l_id)":1}
,"l_id)":{"(bridge":1}
,"+-level":{"+-level_id":1}
,"+-level_id":{"[clear":1}
,"level_id)":{"(bridge":1}
,"+-maintenance-points":{"+-remote":1}
,"+-remote":{"+-domain":1}
,"maintenance-points":{"remote":1}
,"remote":{"(domain":1}
}
;Search.control.loadWordPairs(pairs);
