var pairs =
{
"pbb-te":{"aps":1,"topology":1}
,"aps":{"configuration":1,"load":1,"protection":1}
,"configuration":{"following":1,"setting":1}
,"following":{"section":1}
,"section":{"describes":1}
,"describes":{"configuration":1}
,"setting":{"automatic":1}
,"automatic":{"protection":1}
,"protection":{"switching":1,"groups":1,"tesid":1}
,"switching":{"(aps)":1,"mechanism":1}
,"(aps)":{"pbb-te":1}
,"topology":{"specifically":1}
,"specifically":{"requirement":1}
,"requirement":{"mainly":1}
,"mainly":{"concerns":1}
,"concerns":{"pbb-te":1}
,"load":{"sharing":1}
,"sharing":{"configurations":1,"occurs":1}
,"configurations":{"two":1}
,"two":{"pbb-te":1,"tesids":1,"protection":1}
,"groups":{"(pg1":1,"operate":1}
,"(pg1":{"pg2)":1}
,"pg2)":{"share":1}
,"share":{"two":1}
,"tesids":{"(tesid-1":1}
,"(tesid-1":{"&tesid-2)":1}
,"&tesid-2)":{"pg1":1}
,"pg1":{"uses":1}
,"uses":{"tesid-1":1,"tesid-2":1}
,"tesid-1":{"working":1,"protection":1}
,"working":{"tesid":1}
,"tesid":{"tesid-2":1,"conversely":1,"tesid-1":1,"two":1,"fail":1}
,"tesid-2":{"protection":1,"working":1}
,"conversely":{"pg2":1}
,"pg2":{"uses":1}
,"operate":{"independent":1}
,"independent":{"state":1}
,"state":{"machine":1}
,"machine":{"tesid":1}
,"fail":{"load":1}
,"occurs":{"due":1}
,"due":{"protection":1}
,"mechanism":{"provider":1}
,"provider":{"backbone":1}
,"backbone":{"bridging":1}
,"bridging":{"supported":1}
,"supported":{"zebic":1}
,"zebic":{"releases":1}
}
;Search.control.loadWordPairs(pairs);
