var pairs =
{
"vrrp_api_get_session_by_ifname":{"function":1,"(int":1}
,"function":{"retrieves":1,"succeeds":1}
,"retrieves":{"existing":1}
,"existing":{"vrrp":1}
,"vrrp":{"session":1}
,"session":{"specified":1,"virtual":1,"retrieved":1,"already":1,"cannot":1,"creation\u002Fretrieval":1}
,"specified":{"interface":1}
,"interface":{"creates":1,"name":1,"available":1,"vrrp_api_set_err_seesion_get_or_cre":1}
,"creates":{"new":1}
,"new":{"syntax":1}
,"syntax":{"int":1}
,"int":{"vrrp_api_get_session_by_ifname":1,"vrid":1}
,"(int":{"ipi_vrid":1}
,"ipi_vrid":{"u_int8_t":1,"virtual":1}
,"u_int8_t":{"af_type":1}
,"af_type":{"int":1,"address":1}
,"vrid":{"char":1,"vrrp":1}
,"char":{"*ifname":1}
,"*ifname":{"vrrp_session":1}
,"vrrp_session":{"**pp_sess)":1}
,"**pp_sess)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ipi_vrid":1,"none":1}
,"virtual":{"router":1}
,"router":{"af_type":1,"-255)":1}
,"address":{"family":1}
,"family":{"af_inet":1}
,"af_inet":{"(ipv4)":1}
,"(ipv4)":{"af_inet6":1}
,"af_inet6":{"(ipv6)":1}
,"(ipv6)":{"vrid":1}
,"-255)":{"ifname":1}
,"ifname":{"interface":1}
,"name":{"pp_sess":1}
,"pp_sess":{"pointer":1}
,"pointer":{"newly":1}
,"newly":{"created":1}
,"created":{"vrrp":1}
,"retrieved":{"vrrp":1}
,"already":{"exists":1}
,"exists":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"vrrp_api_set_err_no_such_interface":1}
,"vrrp_api_set_err_no_such_interface":{"interface":1}
,"available":{"vrrp_api_set_err_l2_interface":1}
,"vrrp_api_set_err_l2_interface":{"vrrp":1}
,"cannot":{"enabled":1}
,"enabled":{"interface":1}
,"vrrp_api_set_err_seesion_get_or_cre":{"session":1}
,"creation\u002Fretrieval":{"fails":1}
,"fails":{"vrrp_ok":1}
,"vrrp_ok":{"function":1}
}
;Search.control.loadWordPairs(pairs);
