var pairs =
{
"ospf6_get_if_status":{"function":1,"(char":1}
,"function":{"gets":1,"fails":1,"succeeds":1}
,"gets":{"status":1}
,"status":{"whether":1,"interface":1}
,"whether":{"ospfv3":1}
,"ospfv3":{"configured":1,"process":1}
,"configured":{"given":1}
,"given":{"interface":1}
,"interface":{"syntax":1,"index":1,"row_status_active":1}
,"syntax":{"int":1}
,"int":{"ospf6_get_if_status":1,"ifindex":1,"instid":1,"*ret)":1}
,"(char":{"*tag":1}
,"*tag":{"int":1}
,"ifindex":{"int":1,"interface":1}
,"instid":{"int":1,"instance":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"tag":1,"ret":1}
,"tag":{"ospfv3":1,"ifindex":1}
,"process":{"tag":1}
,"index":{"instid":1}
,"instance":{"identifier":1}
,"identifier":{"output":1}
,"output":{"parameters":1}
,"ret":{"row":1}
,"row":{"status":1,"active":1,"nonexistent":1}
,"row_status_active":{"row":1}
,"active":{"row_status_nonexistent":1}
,"row_status_nonexistent":{"row":1}
,"nonexistent":{"return":1}
,"return":{"values":1}
,"values":{"ospf6_api_get_error":1}
,"ospf6_api_get_error":{"function":1}
,"fails":{"ospf6_api_get_success":1}
,"ospf6_api_get_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
