var pairs =
{
"show":{"mvrp":1}
,"mvrp":{"configuration":1,"configurations":1,"status":1}
,"configuration":{"command":1,"show":1,"bridge":1,"timers":1}
,"command":{"display":1,"syntax":1,"mode":1,"displaying":1}
,"display":{"mvrp":1}
,"configurations":{"bridge":1,"mvrp-enabled":1}
,"bridge":{"command":1,"bridge_name":1,"identifier":1,"show":1,"global":1,"dynamic":1}
,"syntax":{"show":1}
,"bridge_name":{"parameter":1,"bridge":1}
,"parameter":{"bridge_name":1}
,"identifier":{"command":1}
,"mode":{"exec":1,"example":1}
,"exec":{"privileged":1,"mode":1}
,"privileged":{"exec":1}
,"example":{"following":1}
,"following":{"sample":1}
,"sample":{"output":1}
,"output":{"command":1}
,"displaying":{"mvrp":1}
,"mvrp-enabled":{"bridge":1}
,"global":{"mvrp":1}
,"dynamic":{"vlan":1}
,"vlan":{"creation":1}
,"creation":{"enabled":1}
,"enabled":{"port":1,"normal":1}
,"port":{"based":1,"mvrp":1}
,"based":{"mvrp":1}
,"timers":{"(centiseconds)":1}
,"(centiseconds)":{"timers":1,"port":1}
,"status":{"registration":1}
,"registration":{"applicant":1}
,"applicant":{"join":1}
,"join":{"leave":1}
,"leave":{"leaveall":1}
,"leaveall":{"------------------------------------------------------------------------------eth2":1}
,"------------------------------------------------------------------------------eth2":{"enabled":1}
,"normal":{"normal":1,"1000":1}
,"1000":{"eth1":1}
,"eth1":{"enabled":1}
}
;Search.control.loadWordPairs(pairs);
