var pairs =
{
"design":{"zebos-xp":1}
,"zebos-xp":{"eps":1}
,"eps":{"depends":1,"messaging":1,"local":1}
,"depends":{"upon":1}
,"upon":{"architecture":1}
,"architecture":{"types":1,"type":1}
,"types":{"architecture":1}
,"type":{"finite":1}
,"finite":{"state":1}
,"state":{"machine":1}
,"machine":{"associated":1,"responds":1}
,"associated":{"state":1}
,"responds":{"events":1}
,"events":{"occur":1}
,"occur":{"locally":1}
,"locally":{"aps":1,"include":1}
,"aps":{"messages":1,"protocol":1,"communication":1,"frame":1}
,"messages":{"received":1}
,"received":{"far":1,"bridged":1,"aps-specific":1,"request\u002Fstate":1}
,"far":{"end":1}
,"end":{"events":1,"provisioning":1,"received":1,"request":1}
,"include":{"following":1}
,"following":{"lock":1,"logic":1}
,"lock":{"protection":1}
,"protection":{"(lop)":1,"recovers":1,"clear":1,"groups":1,"provided":1,"configuration":1,"switching":1}
,"(lop)":{"forced":1}
,"forced":{"switch":1}
,"switch":{"(fs)":1,"(ms)":1}
,"(fs)":{"manual":1}
,"manual":{"switch":1}
,"(ms)":{"exercise":1}
,"exercise":{"(exr)":1}
,"(exr)":{"working":1}
,"working":{"recovers":1,"signal":1,"protection":1,"transport":1}
,"recovers":{"(w.sf)":1,"(p.sf)":1}
,"(w.sf)":{"protection":1}
,"(p.sf)":{"signal":1}
,"signal":{"fail":1,"received":1,"match":1}
,"fail":{"working":1,"protection":1}
,"clear":{"wait-to-restore":1}
,"wait-to-restore":{"(wtr)":1}
,"(wtr)":{"timer":1}
,"timer":{"expires":1}
,"expires":{"mismatches":1}
,"mismatches":{"failure":1,"either":1,"conveyed":1,"example":1}
,"failure":{"protocol":1}
,"protocol":{"detection":1,"wherever":1,"defects":1}
,"detection":{"various":1}
,"various":{"options":1}
,"options":{"provisioning":1}
,"provisioning":{"protection":1,"mismatches":1,"mismatch":1,"(b-bit":1}
,"groups":{"possibilities":1}
,"possibilities":{"mismatches":1}
,"either":{"end":1}
,"conveyed":{"detected":1}
,"detected":{"information":1}
,"information":{"passed":1,"network":1,"subjected":1,"received":1}
,"passed":{"aps":1,"global":1}
,"wherever":{"applicable":1}
,"applicable":{"sides":1}
,"sides":{"adapt":1}
,"adapt":{"operations":1}
,"operations":{"internetwork":1}
,"internetwork":{"despite":1}
,"despite":{"mismatches":1}
,"example":{"entity":1}
,"entity":{"provisioned":1,"protection":1}
,"provisioned":{"bi-directional":1,"switching":1}
,"bi-directional":{"switching":1}
,"switching":{"fall":1,"allow":1,"aps":1,"without":1,"incomplete":1,"requests":1}
,"fall":{"back":1}
,"back":{"uni-directional":1}
,"uni-directional":{"switching":1}
,"allow":{"internetworking":1}
,"internetworking":{"entity":1}
,"communication":{"fall":1,"operator":1}
,"without":{"aps":1}
,"operator":{"informed":1}
,"informed":{"provisioning":1}
,"mismatch":{"level":1,"reception":1}
,"level":{"protection":1}
,"provided":{"equipment":1}
,"equipment":{"failure":1}
,"defects":{"classified":1}
,"classified":{"follows":1}
,"follows":{"fully":1}
,"fully":{"incompatible":1}
,"incompatible":{"provisioning":1,"b-bit":1}
,"(b-bit":{"mismatch)":1}
,"mismatch)":{"entry":1}
,"entry":{"criteria":1}
,"criteria":{"reception":1,"transmitted":1}
,"reception":{"aps":1}
,"frame":{"incompatible":1,"working":1}
,"b-bit":{"value":1}
,"value":{"working":1}
,"configuration":{"mismatch":1}
,"transport":{"entity":1}
,"incomplete":{"entry":1}
,"transmitted":{"requested":1}
,"requested":{"signal":1}
,"bridged":{"signal":1}
,"match":{"period":1}
,"period":{"longer":1}
,"longer":{"eps":1}
,"messaging":{"local":1}
,"local":{"request":1,"network":1,"protection":1,"priority":1}
,"request":{"processing":1,"information":1,"passed":1}
,"processing":{"following":1,"eps":1}
,"logic":{"local":1,"determines":1}
,"network":{"element":1}
,"element":{"local":1,"receives":1,"far":1}
,"requests":{"(local":1,"top":1}
,"(local":{"requests)":1}
,"requests)":{"active":1}
,"active":{"local":1}
,"priority":{"logic":1,"using":1,"top":1,"local":1}
,"determines":{"requests":1}
,"top":{"priority":1}
,"using":{"order":1}
,"order":{"priority":1}
,"global":{"priority":1}
,"receives":{"aps-specific":1}
,"aps-specific":{"information":1}
,"subjected":{"validity":1}
,"validity":{"check":1}
,"check":{"information":1}
,"request\u002Fstate":{"byte":1}
,"byte":{"far":1}
}
;Search.control.loadWordPairs(pairs);
