var pairs =
{
"lacp_api_cli_show_debug_po_details":{"function":1,"(struct":1}
,"function":{"displays":1,"called":1}
,"displays":{"collection":1}
,"collection":{"port":1}
,"port":{"conversation":1}
,"conversation":{"masks":1}
,"masks":{"function":1}
,"called":{"command":1}
,"command":{"show":1}
,"show":{"debug":1}
,"debug":{"syntax":1}
,"syntax":{"include":1}
,"include":{"mlagd\u002Flacp\u002Flacp_show.h":1}
,"mlagd\u002Flacp\u002Flacp_show.h":{"void":1}
,"void":{"lacp_api_cli_show_debug_po_details":1}
,"(struct":{"cli":1}
,"cli":{"*cli":1,"cli":1,"structure":1}
,"*cli":{"u_int32_t":1}
,"u_int32_t":{"key)":1}
,"key)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"cli":1,"none":1}
,"structure":{"key":1}
,"key":{"mlag":1}
,"mlag":{"identifier":1}
,"identifier":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"none":1}
}
;Search.control.loadWordPairs(pairs);
