var pairs =
{
"timers":{"erp":1,"avoid":1}
,"erp":{"protocol":1}
,"protocol":{"specifies":1}
,"specifies":{"different":1}
,"different":{"timers":1}
,"avoid":{"race":1}
,"race":{"conditions":1}
,"conditions":{"unnecessary":1}
,"unnecessary":{"switching":1,"state":1}
,"switching":{"operations":1}
,"operations":{"signal":1}
,"signal":{"failure":1}
,"failure":{"(sf)":1,"intermittent":1}
,"(sf)":{"condition":1}
,"condition":{"wait-to-restore":1,"exists":1}
,"wait-to-restore":{"(wtr)":1}
,"(wtr)":{"timer":1}
,"timer":{"verifies":1,"used":1,"expires":1}
,"verifies":{"signal":1,"background":1}
,"intermittent":{"force":1,"link":1}
,"force":{"switch":1}
,"switch":{"manual":1,"command":1}
,"manual":{"switch":1}
,"command":{"wait-to-block":1}
,"wait-to-block":{"(wtb)":1}
,"(wtb)":{"timer":1}
,"background":{"condition":1}
,"exists":{"guard":1}
,"guard":{"timer":1}
,"used":{"nodes":1,"underlying":1}
,"nodes":{"changing":1}
,"changing":{"state":1}
,"state":{"block":1,"changes":1}
,"block":{"latent":1}
,"latent":{"outdated":1}
,"outdated":{"messages":1}
,"messages":{"causing":1}
,"causing":{"unnecessary":1}
,"changes":{"hold-off":1}
,"hold-off":{"timer":1}
,"underlying":{"ethernet":1}
,"ethernet":{"layer":1}
,"layer":{"filter":1}
,"filter":{"intermittent":1}
,"link":{"faults":1}
,"faults":{"faults":1,"reported":1}
,"reported":{"ring":1}
,"ring":{"protection":1}
,"protection":{"mechanism":1}
,"mechanism":{"timer":1}
}
;Search.control.loadWordPairs(pairs);
