var pairs =
{
"trill_debug_all_on":{"function":1,"(struct":1}
,"function":{"enables":1,"contained":1}
,"enables":{"debugging":1}
,"debugging":{"trill":1}
,"trill":{"modules":1,"module":1,"cli":1}
,"modules":{"specified":1,"specific":1}
,"specified":{"trill":1}
,"module":{"called":1,"output":1}
,"called":{"debug":1}
,"debug":{"trill":1}
,"cli":{"command":1,"*cli)":1,"structure":1}
,"command":{"function":1}
,"contained":{"trill_cli.c":1}
,"trill_cli.c":{"file":1}
,"file":{"syntax":1}
,"syntax":{"void":1}
,"void":{"trill_debug_all_on":1}
,"(struct":{"cli":1}
,"*cli)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"*cli":1,"none":1}
,"*cli":{"specifies":1}
,"specifies":{"instance":1}
,"instance":{"cli":1}
,"structure":{"modules":1}
,"specific":{"module":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"none":1}
}
;Search.control.loadWordPairs(pairs);
