var pairs =
{
"show":{"running-config":1,"running":1}
,"running-config":{"router":1}
,"router":{"ipv6":1,"configured":1}
,"ipv6":{"vrrp":1}
,"vrrp":{"command":1,"parameters":1,"virtual":1,"router":1,"eth0":1}
,"command":{"show":1,"syntax":1,"mode":1}
,"running":{"configuration":1}
,"configuration":{"vrrp":1,"ipv6":1}
,"syntax":{"show":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"example":1,"below":1}
,"below":{"shows":1}
,"shows":{"running":1}
,"virtual":{"router":1}
,"configured":{"master":1}
,"master":{"owner":1,"circuit-failover":1}
,"owner":{"address":1}
,"address":{"show":1}
,"eth0":{"virtual-ip":1}
,"virtual-ip":{"fe80":1}
,"fe80":{":202:b3ff:fed5:983e":1}
,":202:b3ff:fed5:983e":{"master":1}
,"circuit-failover":{"eth1":1}
,"eth1":{"advertisement-interval":1}
,"advertisement-interval":{"preempt-mode":1}
,"preempt-mode":{"false":1}
,"false":{"enable":1}
}
;Search.control.loadWordPairs(pairs);
