var pairs =
{
"trill_dtree_set":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"call":1}
,"sets":{"dtree":1}
,"dtree":{"originating":1,"output":1}
,"originating":{"multicast":1}
,"multicast":{"traffic":1}
,"traffic":{"called":1}
,"called":{"originating-dtree":1}
,"originating-dtree":{"cli":1}
,"cli":{"command":1}
,"command":{"contained":1}
,"contained":{"trill_api.c":1}
,"trill_api.c":{"file":1}
,"file":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"trill_dtree_set":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"specifies":1}
,"char":{"*tag":1}
,"*tag":{"u_int16_t":1,"specifies":1}
,"u_int16_t":{"dtrees_to_compute)":1}
,"dtrees_to_compute)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"specifies":{"virtual":1,"identification":1,"nickname":1}
,"virtual":{"router":1}
,"router":{"identification":1}
,"identification":{"*tag":1,"rbridge":1}
,"rbridge":{"instance":1}
,"instance":{"dtrees_to_compute":1,"specified":1,"virtual":1}
,"dtrees_to_compute":{"specifies":1}
,"nickname":{"dtree":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"trill_api_set_success":1}
,"trill_api_set_success":{"indicates":1}
,"indicates":{"function":1,"active":1}
,"call":{"executed":1}
,"executed":{"properly":1}
,"properly":{"trill_api_set_err_instance_not_exist":1}
,"trill_api_set_err_instance_not_exist":{"indicates":1}
,"active":{"is-is":1,"instance":1}
,"is-is":{"instance":1}
,"specified":{"tag":1}
,"tag":{"trill_api_set_err_vr_not_exist":1}
,"trill_api_set_err_vr_not_exist":{"indicates":1}
}
;Search.control.loadWordPairs(pairs);
