var pairs =
{
"obtain":{"install":1}
,"install":{"snmp":1,"configure":1,"file":1}
,"snmp":{"already":1,"installed":1,"software":1,"either":1,"smux":1}
,"already":{"snmp":1}
,"installed":{"follow":1}
,"follow":{"steps":1}
,"steps":{"download":1}
,"download":{"snmp":1}
,"software":{"www.net-snmp.org":1,"following":1,"proceed":1}
,"www.net-snmp.org":{"web":1}
,"web":{"site":1}
,"site":{"install":1}
,"configure":{"software":1,"snmp":1}
,"following":{"instructions":1,"sections":1}
,"instructions":{"install":1}
,"file":{"comes":1}
,"comes":{"software":1}
,"proceed":{"following":1}
,"sections":{"configure":1}
,"either":{"smux":1}
,"smux":{"agentx":1}
,"agentx":{"protocol":1,"used":1}
,"protocol":{"cannot":1}
,"cannot":{"configure":1}
}
;Search.control.loadWordPairs(pairs);
