var pairs =
{
"cfm":{"provider":1,"maintenance":1}
,"provider":{"backbone":1}
,"backbone":{"bridges":1,"vlans":1,"service":1}
,"bridges":{"connectivity":1,"(pbb)":1,"zebos-xp":1}
,"connectivity":{"fault":1}
,"fault":{"management":1}
,"management":{"(cfm)":1}
,"(cfm)":{"provider":1}
,"(pbb)":{"supports":1}
,"supports":{"operation":1}
,"operation":{"lan":1}
,"lan":{"segments":1}
,"segments":{"customer":1}
,"customer":{"vlans":1}
,"vlans":{"(c-vlan)":1,"(s-vlan)":1,"(b-vlan)":1}
,"(c-vlan)":{"service":1}
,"service":{"vlans":1,"instances":1,"instance":1,"interface":1}
,"(s-vlan)":{"backbone":1}
,"(b-vlan)":{"backbone":1}
,"instances":{"identified":1}
,"identified":{"service":1}
,"instance":{"(i-sid)":1}
,"(i-sid)":{"cfm":1}
,"maintenance":{"end":1,"intermediate":1,"association":1,"domains":1}
,"end":{"points":1}
,"points":{"(mep)":1,"(mip)":1}
,"(mep)":{"maintenance":1}
,"intermediate":{"points":1}
,"(mip)":{"may":1}
,"may":{"inserted":1}
,"inserted":{"enhanced":1}
,"enhanced":{"internal":1}
,"internal":{"services":1}
,"services":{"sublayer":1}
,"sublayer":{"(e-iss)":1}
,"(e-iss)":{"service":1}
,"interface":{"comply":1}
,"comply":{"ieee":1}
,"ieee":{"802.1ag":1}
,"802.1ag":{"2007":1}
,"2007":{"standard":1}
,"standard":{"multiple":1}
,"multiple":{"bvids":1}
,"bvids":{"per":1}
,"per":{"maintenance":1}
,"association":{"(ma)":1}
,"(ma)":{"link":1}
,"link":{"level":1}
,"level":{"maintenance":1,"name":1}
,"domains":{"(md)":1}
,"(md)":{"supported":1}
,"supported":{"pbb":1,"provider":1}
,"pbb":{"addition":1}
,"addition":{"default":1}
,"default":{"level":1}
,"name":{"format":1}
,"format":{"mip":1}
,"mip":{"creation":1}
,"creation":{"permissions":1}
,"permissions":{"mep":1}
,"mep":{"attributes":1}
,"attributes":{"supported":1}
}
;Search.control.loadWordPairs(pairs);
