var pairs =
{
"pal_kernel_fib_create":{"function":1,"(fib_id_t":1}
,"function":{"creates":1,"succeeds":1}
,"creates":{"fib":1}
,"fib":{"forwarding":1,"syntax":1,"bool_t":1,"fib":1,"identifier":1,"output":1}
,"forwarding":{"plane":1}
,"plane":{"given":1}
,"given":{"fib":1}
,"syntax":{"result_t":1}
,"result_t":{"pal_kernel_fib_create":1}
,"(fib_id_t":{"fib":1}
,"bool_t":{"new_vr":1}
,"new_vr":{"char":1,"flag":1}
,"char":{"*fib_name)":1}
,"*fib_name)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"fib":1,"none":1}
,"identifier":{"new_vr":1}
,"flag":{"indicates":1}
,"indicates":{"new":1}
,"new":{"created":1}
,"created":{"fib_name":1}
,"fib_name":{"name":1}
,"name":{"fib":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"result_ok":1}
,"result_ok":{"function":1}
,"succeeds":{"result_error":1}
,"result_error":{"generic":1}
,"generic":{"error":1}
,"error":{"occurs":1}
}
;Search.control.loadWordPairs(pairs);
