var pairs =
{
"show":{"vrf":1}
,"vrf":{"command":1,"information":1,"show":1,"word":1,"instance":1,"ipi":1}
,"command":{"display":1,"supported":1,"syntax":1,"mode":1}
,"display":{"vrf":1}
,"information":{"command":1}
,"supported":{"rip":1}
,"rip":{"ripng":1,"enabled":1}
,"ripng":{"(ipv4":1}
,"(ipv4":{"ipv6)":1}
,"ipv6)":{"command":1}
,"syntax":{"show":1}
,"word":{"parameters":1,"specify":1}
,"parameters":{"word":1}
,"specify":{"name":1}
,"name":{"vrf":1}
,"instance":{"command":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"show":1}
,"ipi":{"vrf":1,"fib":1,"(id=1)":1}
,"fib":{"router":1}
,"router":{"1.1.1.2":1}
,"1.1.1.2":{"(config)":1}
,"(config)":{"interfaces":1}
,"interfaces":{"eth1":1}
,"eth1":{"eth3":1}
,"eth3":{"vrf":1}
,"(id=1)":{"rip":1}
,"enabled":{"interfaces":1}
}
;Search.control.loadWordPairs(pairs);
