var pairs =
{
"hal_garp_set_bridge_type":{"function":1,"(char":1}
,"function":{"sets":1}
,"sets":{"bridge":1}
,"bridge":{"gmrp\u002Fgvrp":1,"garp_type":1}
,"gmrp\u002Fgvrp":{"enabled":1}
,"enabled":{"disabled":1}
,"disabled":{"syntax":1}
,"syntax":{"void":1}
,"void":{"hal_garp_set_bridge_type":1}
,"(char":{"*bridge_name":1}
,"*bridge_name":{"unsigned":1}
,"unsigned":{"long":1}
,"long":{"garp_type":1}
,"garp_type":{"int":1,"gvrp":1}
,"int":{"enable)":1}
,"enable)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bridge_name":1,"none":1}
,"bridge_name":{"name":1}
,"name":{"bridge":1}
,"gvrp":{"=02":1}
,"=02":{"gmrp":1}
,"gmrp":{"=01":1}
,"=01":{"enable":1}
,"enable":{"true":1}
,"true":{"false":1}
,"false":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"void":1}
}
;Search.control.loadWordPairs(pairs);
