var pairs =
{
"configure":{"terminal":1,"mode":1,"enter":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"interface":1}
,"mode":{"(config)":1,"(config-if)":1}
,"(config)":{"interface":1,"router":1}
,"interface":{"eth1":1,"(eth1)":1,"mode":1,"assign":1,"eth2":1,"(eth2)":1}
,"eth1":{"specify":1}
,"specify":{"interface":1,"router":1}
,"(eth1)":{"configure":1}
,"(config-if)":{"ipv6":1,"exit":1}
,"ipv6":{"router":1,"ospf":1}
,"router":{"ospf":1,"ipv6":1,"(4.4.4.4)":1}
,"ospf":{"area":1,"create":1}
,"area":{"enable":1,"(1)":1}
,"enable":{"ospfv3":1}
,"ospfv3":{"routing":1}
,"routing":{"interface":1,"instance":1,"process":1}
,"assign":{"area":1}
,"(1)":{"(config-if)":1}
,"exit":{"exit":1,"interface":1}
,"eth2":{"specify":1}
,"(eth2)":{"configure":1}
,"create":{"ospfv3":1}
,"instance":{"(config-router)":1}
,"(config-router)":{"router-id":1}
,"router-id":{"4.4.4.4":1}
,"4.4.4.4":{"specify":1}
,"(4.4.4.4)":{"ospfv3":1}
}
;Search.control.loadWordPairs(pairs);
