var pairs =
{
"g8032_api_tcn_propogation":{"function":1,"(bool_t":1}
,"function":{"enables":1,"implements":1,"succeeds":1}
,"enables":{"disables":1}
,"disables":{"tcn":1}
,"tcn":{"(topology":1,"propagation":1}
,"(topology":{"change":1}
,"change":{"notification)":1}
,"notification)":{"propagation":1}
,"propagation":{"interconnected":1,"pal_true":1,"pal_false":1,"inst":1,"already":1}
,"interconnected":{"ring":1}
,"ring":{"function":1}
,"implements":{"tcn-propogation":1}
,"tcn-propogation":{"command":1}
,"command":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"g8032_api_tcn_propogation":1}
,"(bool_t":{"conf":1}
,"conf":{"struct":1}
,"struct":{"g8032_erps_instance":1}
,"g8032_erps_instance":{"*inst)":1}
,"*inst)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"is_conf":1,"none":1}
,"is_conf":{"whether":1}
,"whether":{"enabling":1}
,"enabling":{"disabling":1}
,"disabling":{"tcn":1}
,"pal_true":{"enable":1}
,"enable":{"tcn":1,"propagation":1}
,"pal_false":{"disable":1}
,"disable":{"tcn":1,"propagation":1}
,"inst":{"erps":1,"null":1}
,"erps":{"instance":1}
,"instance":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"g8032_error_none":1}
,"g8032_error_none":{"function":1}
,"succeeds":{"g8032_error_erps_inst_not_found":1}
,"g8032_error_erps_inst_not_found":{"inst":1}
,"null":{"g8032_error_tcn_flag_allready_set":1}
,"g8032_error_tcn_flag_allready_set":{"trying":1}
,"trying":{"enable":1,"disable":1}
,"already":{"enabled":1,"disabled":1}
,"enabled":{"g8032_error_tcn_flag_allready_clear":1}
,"g8032_error_tcn_flag_allready_clear":{"trying":1}
,"disabled":{"g8032_error_major_ring_instance_not_found":1}
,"g8032_error_major_ring_instance_not_found":{"virtual":1}
,"virtual":{"channel":1}
,"channel":{"configured":1}
,"configured":{"g8032_error_not_a_connecting_instance":1}
,"g8032_error_not_a_connecting_instance":{"interconnection":1}
,"interconnection":{"node":1}
,"node":{"sub-ring":1}
}
;Search.control.loadWordPairs(pairs);
