var pairs =
{
"smi_vlan_port_mode_alarm":{"structure":1,"{char":1}
,"structure":{"provides":1}
,"provides":{"information":1}
,"information":{"alarm":1}
,"alarm":{"whenever":1}
,"whenever":{"vlan":1}
,"vlan":{"added":1,"port":1}
,"added":{"type":1}
,"type":{"definition":1,"smi_vlan_port_mode":1}
,"definition":{"ifname":1,"struct":1}
,"ifname":{"interface":1,"[interface_namsiz":1}
,"interface":{"name":1}
,"name":{"port":1}
,"port":{"port":1,"mode":1,"sub":1}
,"mode":{"change":1,"vlan":1,"type":1,"enum":1}
,"change":{"reported":1}
,"reported":{"mode":1}
,"smi_vlan_port_mode":{"sub_mode":1,"definition":1,"mode":1}
,"sub_mode":{"vlan":1}
,"sub":{"mode":1}
,"struct":{"smi_vlan_port_mode_alarm":1}
,"{char":{"ifname":1}
,"[interface_namsiz":{"enum":1}
,"enum":{"smi_vlan_port_mode":1}
}
;Search.control.loadWordPairs(pairs);
