var pairs =
{
"tcp\u002Fip":{"stack":1}
,"stack":{"implications":1,"used":1,"onto":1}
,"implications":{"tcp\u002Fip":1}
,"used":{"vpn":1,"throughout":1}
,"vpn":{"solution":1}
,"solution":{"supports":1}
,"supports":{"following":1}
,"following":{"logical":1,"struct":1}
,"logical":{"(or":1,"interfaces":1}
,"(or":{"virtual)":1}
,"virtual)":{"interfaces":1}
,"interfaces":{"layering":1,"(for":1}
,"layering":{"logical":1}
,"(for":{"tunneling":1}
,"tunneling":{"purposes)":1}
,"purposes)":{"tunnel":1}
,"tunnel":{"support":1,"creation":1,"siocaddtunnel":1,"siocdeltunnel":1,"siocchgtunnel":1,"third":1}
,"support":{"ip-ip":1}
,"ip-ip":{"simple":1}
,"simple":{"internet":1}
,"internet":{"transition":1}
,"transition":{"(sit)":1}
,"(sit)":{"generic":1}
,"generic":{"routing":1}
,"routing":{"encapsulation":1,"interface":1}
,"encapsulation":{"(gre)":1}
,"(gre)":{"tunnels":1}
,"tunnels":{"communication":1,"table":1}
,"communication":{"nsm":1}
,"nsm":{"kernel":1}
,"kernel":{"tunnel":1,"parameters":1,"read":1,"\u002Fip":1}
,"creation":{"manipulation":1}
,"manipulation":{"done":1}
,"done":{"via":1}
,"via":{"ioctl":1,"socket":1}
,"ioctl":{"function":1,"system":1,"call":1,"(socket":1,"options":1}
,"function":{"ioctl":1}
,"system":{"call":1}
,"call":{"ioctl":1,"allows":1,"performed":1,"used":1,"ifreq":1}
,"allows":{"process":1}
,"process":{"different":1}
,"different":{"kernel":1}
,"parameters":{"routing":1,"existing":1}
,"interface":{"levels":1}
,"levels":{"ioctl":1}
,"performed":{"via":1}
,"socket":{"usually":1}
,"usually":{"looks":1}
,"looks":{"ioctl":1}
,"(socket":{"option":1}
,"option":{"pointer)":1,"comment":1}
,"pointer)":{"pointer":1}
,"pointer":{"points":1}
,"points":{"memory":1}
,"memory":{"kernel":1}
,"read":{"write":1}
,"write":{"call":1}
,"throughout":{"zebos-xp":1}
,"zebos-xp":{"mainly":1}
,"mainly":{"create":1}
,"create":{"manipulate":1,"new":1}
,"manipulate":{"tunnels":1}
,"table":{"2-1":1}
,"2-1":{"lists":1}
,"lists":{"ioctl":1}
,"options":{"supported":1,"option":1}
,"supported":{"kernel":1}
,"\u002Fip":{"stack":1}
,"onto":{"vr-vpn":1}
,"vr-vpn":{"feature":1}
,"feature":{"ported":1}
,"ported":{"ioctl":1}
,"comment":{"siocgettunnel":1}
,"siocgettunnel":{"information":1}
,"information":{"configured":1,"stored":1}
,"configured":{"tunnel":1}
,"siocaddtunnel":{"create":1}
,"new":{"tunnel":1}
,"siocdeltunnel":{"delete":1}
,"delete":{"existing":1}
,"existing":{"tunnel":1}
,"siocchgtunnel":{"change":1}
,"change":{"parameters":1}
,"third":{"argument":1}
,"argument":{"passed":1}
,"passed":{"ioctl":1}
,"ifreq":{"structure":1,"ifr":1}
,"structure":{"tunnel-specific":1,"ip_tunnel_parm":1,"references":1,"using":1}
,"tunnel-specific":{"information":1}
,"stored":{"structure":1}
,"ip_tunnel_parm":{"defined":1,"{char":1,"struct":1}
,"defined":{"linux\u002Fif_tunnel.h":1}
,"linux\u002Fif_tunnel.h":{"file":1}
,"file":{"struct":1}
,"struct":{"ip_tunnel_parm":1,"iphdr":1,"ifreq":1}
,"{char":{"name":1}
,"name":{"[ifnamsiz]":1}
,"[ifnamsiz]":{"int":1}
,"int":{"link":1}
,"link":{"__u16":1}
,"__u16":{"i_flags":1,"o_flags":1}
,"i_flags":{"__u16":1}
,"o_flags":{"__u32":1}
,"__u32":{"i_key":1,"o_key":1}
,"i_key":{"__u32":1}
,"o_key":{"struct":1}
,"iphdr":{"iph":1}
,"iph":{"ifreq":1}
,"references":{"structure":1}
,"using":{"code":1}
,"code":{"similar":1}
,"similar":{"following":1}
,"ifr":{"ifr.ifr_ifru.ifru_data":1}
,"ifr.ifr_ifru.ifru_data":{"=(void":1}
,"=(void":{"*)&p":1}
}
;Search.control.loadWordPairs(pairs);
