var pairs =
{
"g8032_api_erp_inst_create":{"function":1,"(u_int8_t":1}
,"function":{"creates":1,"implements":1,"succeeds":1}
,"creates":{"deletes":1}
,"deletes":{"erp":1}
,"erp":{"instance":1}
,"instance":{"function":1,"pal_true":1,"pal_false":1,"br_name":1,"name":1,"specify":1,"return":1,"inst_name":1,"bridge":1,"null":1}
,"implements":{"g8032":1}
,"g8032":{"erp-instance":1}
,"erp-instance":{"command":1}
,"command":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"g8032_api_erp_inst_create":1}
,"(u_int8_t":{"is_conf":1}
,"is_conf":{"u_char":1,"whether":1}
,"u_char":{"*br_name":1,"*inst_name":1}
,"*br_name":{"u_char":1}
,"*inst_name":{"struct":1}
,"struct":{"g8032_erps_instance":1}
,"g8032_erps_instance":{"**inst)":1}
,"**inst)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"is_conf":1,"inst":1}
,"whether":{"creating":1}
,"creating":{"deleting":1,"instance":1}
,"deleting":{"erp":1,"instance":1}
,"pal_true":{"creating":1}
,"pal_false":{"deleting":1}
,"br_name":{"bridge":1}
,"bridge":{"name":1,"g8032_error_bridge_not_found":1,"found":1,"instance":1}
,"name":{"inst_name":1,"output":1}
,"inst_name":{"instance":1,"already":1,"null":1,"attached":1}
,"output":{"parameters":1}
,"inst":{"erp":1}
,"specify":{"null":1}
,"null":{"deleting":1,"g8032_error_erps_inst_have_attached_instances":1}
,"return":{"values":1}
,"values":{"g8032_error_none":1}
,"g8032_error_none":{"function":1}
,"succeeds":{"creating":1}
,"already":{"exists":1}
,"exists":{"g8032_error_max_allowed_erps_instance_configuration":1}
,"g8032_error_max_allowed_erps_instance_configuration":{"254":1}
,"254":{"existing":1}
,"existing":{"instances":1}
,"instances":{"bridge":1,"g8032_error_unknown":1}
,"g8032_error_bridge_not_found":{"bridge":1}
,"found":{"g8032_error_allocation_failed":1}
,"g8032_error_allocation_failed":{"error":1}
,"error":{"allocating":1}
,"allocating":{"memory":1}
,"memory":{"g8032_error_erps_inst_not_found":1}
,"g8032_error_erps_inst_not_found":{"deleting":1}
,"g8032_error_erps_inst_have_attached_instances":{"deleting":1}
,"attached":{"instances":1}
,"g8032_error_unknown":{"deleting":1}
}
;Search.control.loadWordPairs(pairs);
