var pairs =
{
"lldp_api_set_max_credit":{"function":1,"(u_char":1}
,"function":{"called":1,"succeeds":1}
,"called":{"maximum":1}
,"maximum":{"value":1}
,"value":{"transmission":1,"invalid":1}
,"transmission":{"credit":1}
,"credit":{"signifies":1}
,"signifies":{"number":1}
,"number":{"consecutive":1}
,"consecutive":{"lldp":1}
,"lldp":{"frames":1,"agent":1}
,"frames":{"transmitted":1}
,"transmitted":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"lldp_api_set_max_credit":1}
,"(u_char":{"*mac":1}
,"*mac":{"struct":1}
,"struct":{"interface":1}
,"interface":{"*ifp":1,"structure":1,"found":1}
,"*ifp":{"u_int8_t":1}
,"u_int8_t":{"credit)":1}
,"credit)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"mac":1,"none":1}
,"mac":{"mac":1,"address":1}
,"address":{"lldp":1}
,"agent":{"ifp":1,"found":1}
,"ifp":{"interface":1}
,"structure":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"lldp_api_success":1}
,"lldp_api_success":{"function":1}
,"succeeds":{"lldp_api_err_invalid_val":1}
,"lldp_api_err_invalid_val":{"value":1}
,"invalid":{"lldp_api_err_tx_sm_not_found":1}
,"lldp_api_err_tx_sm_not_found":{"lldp_api_err_lldp_if_not_exist":1}
,"lldp_api_err_lldp_if_not_exist":{"interface":1}
,"found":{"lldp_api_err_onm_if_not_exist":1,"lldp_api_err_agent_not_found":1}
,"lldp_api_err_onm_if_not_exist":{"onmd":1}
,"onmd":{"found":1}
,"lldp_api_err_agent_not_found":{"agent":1}
}
;Search.control.loadWordPairs(pairs);
