var pairs =
{
"local":{"area":1}
,"area":{"network":1,"building":1}
,"network":{"(lan)":1,"(wan)":1}
,"(lan)":{"group":1}
,"group":{"computers":1}
,"computers":{"devices":1}
,"devices":{"connected":1}
,"connected":{"communications":1}
,"communications":{"channel":1}
,"channel":{"capable":1}
,"capable":{"sharing":1}
,"sharing":{"resources":1}
,"resources":{"among":1}
,"among":{"several":1}
,"several":{"users":1}
,"users":{"lans":1}
,"lans":{"based":1,"connect":1}
,"based":{"small":1}
,"small":{"physical":1}
,"physical":{"area":1}
,"building":{"floor":1}
,"floor":{"department":1}
,"department":{"lans":1}
,"connect":{"wide":1}
,"wide":{"area":1}
,"(wan)":{"ethernet":1}
,"ethernet":{"popular":1}
,"popular":{"lan":1}
,"lan":{"technology":1}
}
;Search.control.loadWordPairs(pairs);
