var pairs =
{
"zebos_smi_client_stop":{"function":1,"(struct":1}
,"function":{"stops":1,"succeeds":1}
,"stops":{"client":1,"delivery":1}
,"client":{"protocol":1,"socket":1,"stop":1,"separately":1}
,"protocol":{"closes":1,"temporarily":1,"client":1}
,"closes":{"zebos-xp":1}
,"zebos-xp":{"client":1}
,"socket":{"stopping":1}
,"stopping":{"client":1}
,"temporarily":{"stops":1}
,"delivery":{"incoming":1}
,"incoming":{"messages":1}
,"messages":{"however":1,"syntax":1}
,"however":{"stopping":1}
,"stop":{"smi":1,"shown":1,"protocol":1}
,"smi":{"server":1}
,"server":{"sending":1}
,"sending":{"messages":1}
,"syntax":{"int":1}
,"int":{"zebos_smi_client_stop":1,"module)":1}
,"(struct":{"smiclient_globals":1}
,"smiclient_globals":{"*azg":1,"structure":1}
,"*azg":{"int":1}
,"module)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"azg":1,"none":1}
,"azg":{"pointer":1}
,"pointer":{"smiclient_globals":1}
,"structure":{"module":1}
,"module":{"protocol":1,"valid":1}
,"shown":{"smi_api_module":1}
,"smi_api_module":{"stop":1}
,"separately":{"cannot":1}
,"cannot":{"specify":1}
,"specify":{"smi_ac_all":1}
,"smi_ac_all":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"smi_success":1}
,"smi_success":{"function":1}
,"succeeds":{"smi_invalid_val":1}
,"smi_invalid_val":{"module":1}
,"valid":{"value":1}
}
;Search.control.loadWordPairs(pairs);
