var pairs =
{
"ipv6":{"ra-interval":1,"router":1,"prefix":1}
,"ra-interval":{"command":1,"<4-1800>":1,"parameter":1,"(config-if)":1}
,"command":{"specify":1,"reset":1,"syntax":1,"mode":1}
,"specify":{"interval":1}
,"interval":{"ipv6":1,"seconds":1}
,"router":{"advertisements":1}
,"advertisements":{"(ra)":1}
,"(ra)":{"parameter":1}
,"parameter":{"command":1,"<4-1800>":1}
,"reset":{"value":1}
,"value":{"default":1}
,"default":{"command":1,"600":1}
,"syntax":{"ipv6":1}
,"<4-1800>":{"ipv6":1,"interval":1}
,"seconds":{"default":1,"command":1}
,"600":{"seconds":1}
,"mode":{"interface":1,"examples":1}
,"interface":{"mode":1,"eth0":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"ipv6":1}
,"prefix":{"3ffe:ffff:ffff":1}
,"3ffe:ffff:ffff":{":\u002F64":1}
,":\u002F64":{"(config-if)":1}
}
;Search.control.loadWordPairs(pairs);
