var pairs =
{
"path":{"aggregator":1,"reconstruction":1,"four":1,"information":1,"construction":1,"segment":1,"count":1}
,"aggregator":{"reconstruction":1,"attributes":1,"attribute":1}
,"reconstruction":{"following":1,"path":1,"ignores":1,"number":1,"completed":1}
,"following":{"describes":1,"rules":1}
,"describes":{"reconstruction":1}
,"attributes":{"two-byte":1,"as4_path\u002Fas4_aggregator":1,"uses":1,"considered":1,"numbers":1}
,"two-byte":{"bgp":1}
,"bgp":{"receiver":1,"speaker":1,"peer":1,"receiving":1,"ignores":1}
,"receiver":{"affected":1}
,"affected":{"path":1}
,"ignores":{"two":1,"as4_aggregator":1,"as4_path":1}
,"two":{"new":1}
,"new":{"attributes":1}
,"as4_path\u002Fas4_aggregator":{"four-byte":1,"reconstructs":1,"functions":1}
,"four-byte":{"bgp":1,"capability":1,"asn":1,"asns":1}
,"speaker":{"receiving":1}
,"receiving":{"update":1}
,"update":{"message":1,"as4_path\u002Fas4_aggregator":1}
,"message":{"as4_path\u002Fas4_aggregator":1}
,"reconstructs":{"path":1}
,"four":{"bytes":1}
,"bytes":{"peers":1}
,"peers":{"four-byte":1}
,"peer":{"exchanges":1}
,"exchanges":{"four-byte":1}
,"capability":{"messages":1}
,"messages":{"four-byte":1}
,"functions":{"follows":1}
,"follows":{"as_trans":1}
,"as_trans":{"present":1,"as4_aggregator":1,"numbers":1,"as_path":1}
,"present":{"aggregator":1}
,"attribute":{"four-byte":1,"aggregation":1,"considered":1,"contains":1,"less":1,"greater":1,"multiple":1}
,"as4_aggregator":{"as4_path":1,"taken":1}
,"as4_path":{"attributes":1,"attribute":1,"information":1,"70000":1,"first":1,"65356":1,"checked":1,"reconstructed":1,"values":1,"777777":1,"88888":1}
,"uses":{"aggregator":1}
,"aggregation":{"information":1}
,"information":{"case":1,"aggregator":1,"aggregating":1,"example":1,"as4_path":1}
,"case":{"as_path":1,"num":1}
,"as_path":{"attribute":1,"as4_path":1,"23456":1,"taken":1,"asn":1,"as_trans":1,"thus":1,"2,3,6":1,"count":1,"less":1,"prepended":1,"456":1}
,"considered":{"path":1,"according":1}
,"contains":{"as_trans":1}
,"taken":{"information":1,"path":1,"as_path":1}
,"aggregating":{"route":1}
,"route":{"path":1}
,"construction":{"as_path":1}
,"according":{"following":1}
,"rules":{"number":1}
,"number":{"asns":1,"as_trans":1,"as4_path":1}
,"asns":{"as_path":1,"as4_path":1,"remaining":1,"appended":1}
,"less":{"number":1}
,"example":{"as_path":1}
,"23456":{"as4_path":1,"23456":1}
,"70000":{"70001":1,"80000":1}
,"70001":{"70002":1}
,"70002":{"as_path":1}
,"greater":{"number":1}
,"multiple":{"as_trans":1}
,"numbers":{"as_path":1,"as4_path":1,"probably":1,"count":1}
,"asn":{"taken":1,"likewise":1}
,"first":{"four-byte":1}
,"likewise":{"4-octet":1}
,"4-octet":{"asns":1}
,"remaining":{"four-byte":1}
,"appended":{"as_path":1}
,"thus":{"reconstruction":1}
,"completed":{"valid":1}
,"valid":{"as_confed_sequence":1}
,"as_confed_sequence":{"as_confed_set":1}
,"as_confed_set":{"path":1}
,"segment":{"prepended":1,"adjacent":1,"examples":1}
,"prepended":{"either":1,"path":1,"as4":1}
,"either":{"leading":1}
,"leading":{"path":1}
,"adjacent":{"prepended":1}
,"examples":{"as_path":1}
,"2,3,6":{"23456":1}
,"65356":{"77777":1}
,"77777":{"number":1}
,"probably":{"as4-byte":1}
,"as4-byte":{"unmappable":1}
,"unmappable":{"numbers":1}
,"count":{"as_trans":1,"numbers":1,"recomputed":1}
,"checked":{"information":1}
,"reconstructed":{"(this":1}
,"(this":{"case":1}
,"num":{"==as4":1}
,"==as4":{"num)":1}
,"num)":{"number":1}
,"values":{"erroneous":1,"taken":1,"path":1}
,"erroneous":{"action":1}
,"action":{"done":1}
,"done":{"previous":1}
,"previous":{"speakers":1}
,"speakers":{"however":1}
,"however":{"non-as_trans":1}
,"non-as_trans":{"values":1}
,"as4":{"values":1}
,"recomputed":{"examples":1}
,"456":{"23456":1}
,"777777":{"66666":1}
,"66666":{"88888":1}
,"88888":{"as_path":1,"99999":1}
,"99999":{"70000":1}
}
;Search.control.loadWordPairs(pairs);
