var pairs =
{
"vrrp_advt_info":{"data":1}
,"data":{"structure":1}
,"structure":{"holds":1}
,"holds":{"vrrp":1}
,"vrrp":{"packet":1,"checksum":1}
,"packet":{"resides":1}
,"resides":{"vrrp\u002Fvrrp.h":1}
,"vrrp\u002Fvrrp.h":{"file":1}
,"file":{"member":1}
,"member":{"description":1}
,"description":{"ver_type":1}
,"ver_type":{"version":1}
,"version":{"type":1}
,"type":{"vrid":1,"advt_int":1}
,"vrid":{"virtual":1}
,"virtual":{"router":1,"ipv4":1,"ipv6":1}
,"router":{"priority":1,"num_ip_addrs":1}
,"priority":{"priority":1,"number":1}
,"number":{"assigned":1,"addresses":1}
,"assigned":{"virtual":1}
,"num_ip_addrs":{"number":1}
,"addresses":{"backup":1}
,"backup":{"rsvd:4":1}
,"rsvd:4":{"advt_int:12":1}
,"advt_int:12":{"advertisement":1}
,"advertisement":{"interval":1}
,"interval":{"auth_type":1,"cksum":1}
,"auth_type":{"authentication":1}
,"authentication":{"type":1,"data":1}
,"advt_int":{"advertisement":1}
,"cksum":{"vrrp":1}
,"checksum":{"vip_v4":1}
,"vip_v4":{"virtual":1}
,"ipv4":{"address":1}
,"address":{"vip_v6":1,"auth_data":1}
,"vip_v6":{"virtual":1}
,"ipv6":{"address":1}
,"auth_data":{"authentication":1}
}
;Search.control.loadWordPairs(pairs);
