var pairs =
{
"ripng":{"struct":1,"ripng":1,"structure":1,"instance":1,"flags":1,"master":1,"socket":1,"passive":1,"offset":1,"command":1,"version":1,"default":1,"source":1,"*if_table":1,"interface":1,"neighbor":1,"routing":1,"static":1,"aggregate":1,"threads":1,"timer":1,"default-information":1,"enable\u002Fdisable":1,"receive":1,"distribute":1,"rmap":1,"{\u002F*ripng":1,"*\u002Fstruct":1,"global":1,"debug":1,"*top":1,"specific":1,"packet":1,"route":1,"packet.*\u002Fu_int16_t":1}
,"struct":{"ripng":1,"stream":1,"thread":1,"route_map":1,"ripng_master":1,"ripng_info":1,"pal_in6_addr":1,"pal_timeval":1,"ripng_aggregate":1,"ripng_if_param":1,"ripng_offset_list":1,"{char":1}
,"structure":{"source":1,"*\u002Fstruct":1}
,"source":{"file":1,"specific":1}
,"file":{"ripngd\u002Fripngd.h":1,"-ripngd\u002Fripngd.h":1,"ripngd\u002Fripng_route.h":1,"-ripngd\u002Fripng_interface.h":1,"-ripngd\u002Fripng_offset.h":1}
,"ripngd\u002Fripngd.h":{"member":1}
,"member":{"definition":1}
,"definition":{"instance":1,"*vr":1,"ripng":1,"count":1,"*ifname":1}
,"instance":{"ripng":1,"flags":1,"name":1,"*\u002Fint":1,"\u002F*ripng":1,"list":1}
,"flags":{"ripng":1,"*rm":1,"*\u002Fu_char":1,"define":1,"\u002F*ripng":1,"*\u002Fstruct":1,"configuration":1,"terminal":1,"flags":1,"\u002F*garbage":1,"*name":1}
,"*rm":{"pointer":1,"\u002F*ripng":1,"\u002F*configured":1}
,"pointer":{"ripng":1,"*zg":1,"globals":1,"parent":1,"route":1,"*\u002Fstruct":1}
,"master":{"sock":1,"ifrm":1,"redist":1,"*\u002Fstruct":1,"system":1,"config":1}
,"sock":{"ripng":1,"\u002F*ripng":1}
,"socket":{"*name":1,"*\u002Fint":1}
,"*name":{"ripng":1,"\u002F*ripng":1,"struct":1,"\u002F*split":1}
,"name":{"passive_if":1,"*\u002Fchar":1,"ripng_master":1,"split_horizon":1,"direct":1}
,"passive_if":{"ripng":1,"\u002F*ripng":1}
,"passive":{"interface":1}
,"interface":{"vector":1,"table":1,"parameter":1,"route":1,"configuration":1,"name":1}
,"vector":{"*offset_list":1,"*\u002Fvector":1}
,"*offset_list":{"ripng":1,"\u002F*ripng":1}
,"offset":{"list":1}
,"list":{"command":1,"master":1,"*offset_list":1,"*if_table":1,"*\u002Fstruct":1,"*ripng":1,"*if_params":1,"parameters":1,"information":1}
,"command":{"ripng":1,"version":1,"u_char":1}
,"version":{"ripng":1,"distance":1,"\u002F*ripng":1}
,"distance":{"ripng":1,"*distance_table":1,"max_mtu":1,"*\u002Fu_char":1,"\u002F*ripng":1,"*\u002Fstruct":1,"distance":1,"\u002F*each":1,"struct":1}
,"default":{"distance":1,"metric":1}
,"*distance_table":{"ripng":1,"int":1}
,"specific":{"distance":1,"information":1}
,"max_mtu":{"max":1,"\u002F*input\u002Foutput":1}
,"max":{"mtu":1}
,"mtu":{"stream":1}
,"stream":{"*ibuf":1,"*obuf":1}
,"*ibuf":{"stream":1,"struct":1}
,"*obuf":{"input\u002Foutput":1,"\u002F*ripng":1}
,"input\u002Foutput":{"buffer":1}
,"buffer":{"ripng":1,"size":1}
,"*if_table":{"ripng":1,"\u002F*ripng":1}
,"table":{"*nbr_table":1,"*table":1,"*\u002Fstruct":1,"*if_params":1}
,"*nbr_table":{"ripng":1,"\u002F*ripng":1}
,"neighbor":{"table":1}
,"*table":{"ripng":1,"\u002F*ripng":1}
,"routing":{"information":1}
,"information":{"base":1,"*aggregate":1,"*t_read":1,"*\u002Fstruct":1,"source":1,"ifindex":1,"struct":1}
,"base":{"*route":1,"*\u002Fstruct":1}
,"*route":{"ripng":1,"\u002F*ripng":1}
,"static":{"route":1,"ripng":1}
,"route":{"information":1,"map":1,"node":1,"type":1,"nexthop":1,"metric":1,"tag":1,"*t_timeout":1,"*\u002Fu_char":1,"*\u002Funsigned":1,"*\u002F#":1,"count":1}
,"*aggregate":{"ripng":1,"\u002F*ripng":1}
,"aggregate":{"route":1,"sub_type":1,"*\u002Fu_char":1}
,"*t_read":{"*t_update":1,"struct":1}
,"*t_update":{"ripng":1,"\u002F*triggered":1}
,"threads":{"trigger":1,"update_time":1,"*\u002Fstruct":1,"*\u002Fint":1}
,"trigger":{"*t_triggered_update":1,"struct":1}
,"*t_triggered_update":{"*t_triggered_interval":1,"struct":1}
,"*t_triggered_interval":{"triggered":1,"\u002F*ripng":1}
,"triggered":{"update":1}
,"update":{"threads":1}
,"update_time":{"timeout_time":1,"u_int32_t":1}
,"timeout_time":{"garbage_time":1,"u_int32_t":1}
,"garbage_time":{"ripng":1,"\u002F*ripng":1}
,"timer":{"values":1,"metric_set":1,"*\u002Fstruct":1}
,"values":{"default_metric":1,"*\u002Fu_int32_t":1}
,"default_metric":{"ripng":1,"\u002F*ripng":1}
,"metric":{"default_information":1,"consistent":1,"*\u002Fint":1,"redist_map":1,"metric":1,"route":1,"\u002F*tag":1,"direct":1}
,"default_information":{"ripng":1,"\u002F*ripng":1}
,"default-information":{"originate":1}
,"originate":{"metric_type":1,"*\u002Fint":1}
,"metric_type":{"ripng":1,"\u002F*ripng":1}
,"enable\u002Fdisable":{"updating":1}
,"updating":{"metric":1}
,"consistent":{"cisco":1}
,"cisco":{"recvbuf_size":1,"*\u002Fu_char":1}
,"recvbuf_size":{"ripng":1,"\u002F*ripng":1}
,"receive":{"buffer":1}
,"size":{"ripng":1,"*\u002Fu_int32_t":1}
,"distribute":{"list":1}
,"ifrm":{"ripng":1,"\u002F*for":1}
,"rmap":{"master":1}
,"redist":{"redistribute":1,"[ipi_route_max]":1}
,"redistribute":{"redist_map":1,"route":1,"*\u002Fu_char":1}
,"redist_map":{"redistribute":1,"[ipi_route_max]":1}
,"map":{"\u002F*ripng":1,"*\u002Fstruct":1}
,"\u002F*ripng":{"structure":1,"flags":1,"socket":1,"instance":1,"passive":1,"offset-list":1,"parameters.*\u002Fu_char":1,"default":1,"source":1,"interface":1,"neighbor":1,"routing":1,"static":1,"aggregate":1,"threads":1,"timer":1,"default-information":1,"enable\u002Fdisable":1,"receive":1,"distribute":1,"rmap":1,"master":1,"global":1,"debug":1,"specific":1}
,"*\u002Fstruct":{"ripng":1,"ripng_master":1,"list":1,"route_table":1,"stream":1,"thread":1,"distribute_master":1,"if_rmap_master":1,"{char":1,"ipi_vr":1,"lib_globals":1,"{\u002F*debug":1,"debug_ripng":1,"ripng_info":1,"route_node":1,"pal_in6_addr":1,"ripng_if_params":1}
,"{\u002F*ripng":{"instance":1}
,"*\u002Fint":{"instance":1,"sock":1,"trigger":1,"default_metric":1,"default_information":1}
,"*\u002Fu_char":{"flags":1,"distance":1,"metric_type":1,"redist":1,"type":1,"sub_type":1,"metric":1,"metric_set":1,"config":1,"split_horizon":1}
,"define":{"ripng_flag_up":1,"ripng_rtf_fib":1,"ripng_rtf_changed":1,"ripng_if_param_router":1,"ripng_if_param_split_horizon":1,"ripng_split_horizon_poisoned":1,"ripng_split_horizon_none":1,"ripng_split_horizon":1}
,"ripng_flag_up":{"<<0)":1}
,"<<0)":{"\u002F*pointer":1,"define":1}
,"\u002F*pointer":{"ripng":1,"globals":1}
,"ripng_master":{"*rm":1,"ripng":1,"{\u002F*pointer":1}
,"*\u002Fchar":{"*name":1,"*ifname":1}
,"*\u002Fvector":{"passive_if":1}
,"offset-list":{"*\u002Fstruct":1}
,"parameters.*\u002Fu_char":{"command":1}
,"u_char":{"version":1,"flags":1,"metric":1}
,"route_table":{"*distance_table":1,"*if_table":1,"*nbr_table":1,"*table":1,"*route":1,"*aggregate":1}
,"int":{"max_mtu":1,"metric_config":1,"ifindex":1,"suppress":1,"count":1}
,"\u002F*input\u002Foutput":{"buffer":1}
,"thread":{"*t_read":1,"*t_update":1,"*t_triggered_update":1,"*t_triggered_interval":1,"*t_timeout":1,"*t_garbage_collect":1}
,"\u002F*triggered":{"update":1}
,"*\u002Fu_int32_t":{"update_time":1,"recvbuf_size":1}
,"u_int32_t":{"timeout_time":1,"garbage_time":1,"metric":1}
,"distribute_master":{"\u002F*ripng":1}
,"if_rmap_master":{"ifrm":1}
,"\u002F*for":{"redistribute":1,"aggregation":1}
,"[ipi_route_max]":{"\u002F*for":1,"struct":1}
,"{char":{"*name":1,"*ifname":1,"*alist_name":1}
,"route_map":{"*map":1}
,"*map":{"int":1}
,"metric_config":{"u_int32_t":1}
,"system":{"wide":1}
,"wide":{"configuration":1}
,"configuration":{"variables":1,"*\u002Fstruct":1,"parameter":1}
,"variables":{"source":1,"*\u002Fstruct":1,"changed":1}
,"-ripngd\u002Fripngd.h":{"attribute":1,"member":1}
,"attribute":{"definition":1}
,"*vr":{"pointer":1,"\u002F*pointer":1}
,"*zg":{"pointer":1,"\u002F*ripng":1}
,"globals":{"*ripng":1,"*\u002Fstruct":1}
,"*ripng":{"ripng":1,"\u002F*ripng":1}
,"global":{"interface":1}
,"*if_params":{"ripng":1,"\u002F*ripng":1}
,"parameter":{"pool":1,"source":1,"*\u002Fstruct":1}
,"pool":{"debug":1,"*\u002Fstruct":1}
,"debug":{"ripng":1,"flags":1,"struct":1}
,"{\u002F*pointer":{"*\u002Fstruct":1}
,"ipi_vr":{"*vr":1}
,"lib_globals":{"*zg":1}
,"{\u002F*debug":{"flags":1}
,"debug_ripng":{"conf":1,"term":1}
,"conf":{"\u002F*debug":1}
,"\u002F*debug":{"flags":1}
,"terminal":{"*\u002Fstruct":1}
,"term":{"debug":1}
,"ripng_info":{"route\u0027s":1,"{\u002F*parent\u0027s":1}
,"route\u0027s":{"information":1,"type":1}
,"*top":{"pointer":1,"\u002F*back":1}
,"parent":{"*rn":1}
,"*rn":{"back":1,"\u002F*this":1}
,"back":{"pointer":1}
,"node":{"type":1,"*\u002Fstruct":1}
,"type":{"route":1,"static":1,"\u002F*sub":1,"\u002F*ripng":1,"*\u002Fu_char":1}
,"sub_type":{"sub":1,"\u002F*ripng":1}
,"sub":{"type":1}
,"nexthop":{"ripng":1,"struct":1}
,"ifindex":{"interface":1,"\u002F*metric":1}
,"tag":{"tag":1,"field":1,"\u002F*for":1,"struct":1}
,"field":{"ripng":1}
,"packet":{"suppress":1,"struct":1}
,"suppress":{"aggregation":1,"\u002F*flags":1,"suppressed":1,"\u002F*metric":1}
,"aggregation":{"flags":1,"*\u002Funsigned":1}
,"*t_timeout":{"*t_garbage_collect":1,"struct":1}
,"*t_garbage_collect":{"timeout_start_time":1,"struct":1}
,"timeout_start_time":{"garbage":1,"\u002F*route-map":1}
,"garbage":{"collect":1}
,"collect":{"timer":1}
,"metric_set":{"route-map":1,"\u002F*distance":1}
,"route-map":{"features":1}
,"features":{"-this":1}
,"-this":{"variables":1}
,"changed":{"distance":1,"*\u002Fu_char":1}
,"\u002F*each":{"route\u0027s":1}
,"{\u002F*parent\u0027s":{"pointer":1}
,"\u002F*back":{"pointer":1}
,"route_node":{"*rn":1}
,"\u002F*this":{"route\u0027s":1}
,"\u002F*sub":{"type":1}
,"pal_in6_addr":{"nexthop":1,"\u002F*which":1}
,"\u002F*which":{"interface":1}
,"*\u002Funsigned":{"int":1}
,"\u002F*metric":{"route":1}
,"\u002F*tag":{"field":1}
,"packet.*\u002Fu_int16_t":{"tag":1}
,"\u002F*flags":{"ripng":1}
,"*\u002F#":{"define":1}
,"ripng_rtf_fib":{"define":1}
,"ripng_rtf_changed":{"u_char":1}
,"\u002F*garbage":{"collect":1}
,"pal_timeval":{"timeout_start_time":1}
,"\u002F*route-map":{"features":1}
,"\u002F*distance":{"*\u002Fu_char":1}
,"ripng_aggregate":{"aggregated":1,"{\u002F*aggregate":1}
,"aggregated":{"routes":1}
,"routes":{"information":1}
,"ripngd\u002Fripng_route.h":{"member":1}
,"count":{"aggregate":1,"suppress":1,"metric":1,"*\u002Funsigned":1,"\u002F*suppressed":1}
,"suppressed":{"route":1}
,"{\u002F*aggregate":{"route":1}
,"\u002F*suppressed":{"route":1}
,"ripng_if_param":{"ripng":1}
,"-ripngd\u002Fripng_interface.h":{"member":1}
,"*ifname":{"interface":1,"\u002F*pointer":1,"struct":1}
,"config":{"configured":1,"define":1}
,"configured":{"flags":1}
,"split_horizon":{"split":1,"define":1}
,"split":{"horizon":1}
,"horizon":{"type":1}
,"ripng_if_params":{"{\u002F*interface":1}
,"{\u002F*interface":{"name":1}
,"\u002F*configured":{"flags":1}
,"ripng_if_param_router":{"<<0)":1}
,"ripng_if_param_split_horizon":{"<<1)":1}
,"<<1)":{"\u002F*ripng":1}
,"\u002F*split":{"horizon":1}
,"ripng_split_horizon_poisoned":{"define":1}
,"ripng_split_horizon_none":{"define":1}
,"ripng_split_horizon":{"struct":1}
,"ripng_offset_list":{"ripng":1,"{char":1}
,"parameters":{"source":1}
,"-ripngd\u002Fripng_offset.h":{"member":1}
,"direct":{"access":1,"[ripng_offset_list_max]":1}
,"access":{"list":1}
,"*alist_name":{"u_char":1}
}
;Search.control.loadWordPairs(pairs);
