var pairs =
{
"ssh":{"client":1,"network":1,"intended":1,"typically":1,"uses":1,"servers":1,"server":1,"service":1}
,"client":{"server":1,"configuration":1}
,"server":{"host":1,"configuration":1}
,"host":{"configuration":1}
,"configuration":{"overview":1,"enable":1,"remote":1}
,"overview":{"ssh":1}
,"network":{"protocol":1,"internet.ssh":1}
,"protocol":{"allows":1}
,"allows":{"data":1}
,"data":{"exchanged":1,"unsecured":1}
,"exchanged":{"using":1}
,"using":{"secure":1,"associated":1}
,"secure":{"channel":1}
,"channel":{"two":1}
,"two":{"networked":1}
,"networked":{"devices.ssh":1}
,"devices.ssh":{"designed":1}
,"designed":{"replacement":1}
,"replacement":{"telnet":1}
,"telnet":{"insecure":1}
,"insecure":{"remote":1}
,"remote":{"shells":1,"computer":1,"machine":1,"login":1}
,"shells":{"send":1}
,"send":{"information":1}
,"information":{"notably":1}
,"notably":{"passwords":1}
,"passwords":{"plaintext":1}
,"plaintext":{"rendering":1}
,"rendering":{"susceptible":1}
,"susceptible":{"packet":1}
,"packet":{"analysis":1}
,"analysis":{"[2]":1}
,"[2]":{"encryption":1}
,"encryption":{"used":1}
,"used":{"ssh":1,"log":1}
,"intended":{"provide":1}
,"provide":{"confidentiality":1}
,"confidentiality":{"integrity":1}
,"integrity":{"data":1}
,"unsecured":{"network":1}
,"internet.ssh":{"uses":1}
,"uses":{"public-key":1,"client-server":1}
,"public-key":{"cryptography":1}
,"cryptography":{"authenticate":1}
,"authenticate":{"remote":1,"user":1}
,"computer":{"allow":1,"authenticate":1}
,"allow":{"remote":1}
,"user":{"ssh":1}
,"typically":{"used":1}
,"log":{"remote":1}
,"machine":{"execute":1}
,"execute":{"commands":1}
,"commands":{"supports":1,"ssh":1}
,"supports":{"tunneling":1}
,"tunneling":{"forwarding":1}
,"forwarding":{"tcp":1}
,"tcp":{"ports":1,"port":1}
,"ports":{"x11":1}
,"x11":{"connections":1}
,"connections":{"transfer":1}
,"transfer":{"files":1}
,"files":{"using":1}
,"associated":{"sftp":1}
,"sftp":{"scp":1}
,"scp":{"protocols":1}
,"protocols":{"ssh":1}
,"client-server":{"model":1}
,"model":{"standard":1}
,"standard":{"tcp":1}
,"port":{"assigned":1}
,"assigned":{"contacting":1}
,"contacting":{"ssh":1}
,"servers":{"document":1}
,"document":{"covering":1}
,"covering":{"ssh":1}
,"enable":{"ssh":1}
,"service":{"key":1}
,"key":{"generation":1}
,"generation":{"cli":1}
,"cli":{"commands":1}
,"login":{"server":1}
}
;Search.control.loadWordPairs(pairs);
