var pairs =
{
"match":{"ipv6":1}
,"ipv6":{"next-hop":1,"address":1,"access":1}
,"next-hop":{"command":1,"address":1,"(x:x":1,"word":1,"3ffe":1}
,"command":{"specify":1,"valid":1,"disable":1,"syntax":1,"mode":1}
,"specify":{"next-hop":1,"ipv6":1}
,"address":{"matched":1,"next-hop":1}
,"matched":{"route":1}
,"route":{"specified":1}
,"specified":{"policies":1,"routing":1}
,"policies":{"specified":1,"enable":1,"overrides":1}
,"routing":{"protocols":1,"tables":1}
,"protocols":{"setting":1}
,"setting":{"policies":1}
,"enable":{"packets":1}
,"packets":{"different":1}
,"different":{"routes":1}
,"routes":{"depending":1}
,"depending":{"length":1}
,"length":{"content":1}
,"content":{"packet":1}
,"packet":{"forwarding":1}
,"forwarding":{"based":1,"specified":1}
,"based":{"configured":1}
,"configured":{"policies":1}
,"overrides":{"packet":1}
,"tables":{"command":1}
,"valid":{"bgp":1}
,"bgp":{"is-is":1}
,"is-is":{"parameter":1}
,"parameter":{"command":1}
,"disable":{"function":1}
,"function":{"command":1}
,"syntax":{"match":1}
,"(x:x":{":x:x":1}
,":x:x":{"word)":1,"word":1,"specify":1}
,"word)":{"match":1}
,"word":{"parameters":1,"specify":1}
,"parameters":{"x:x":1}
,"x:x":{":x:x":1}
,"access":{"list":1}
,"list":{"name":1}
,"name":{"command":1}
,"mode":{"route-map":1,"examples":1}
,"route-map":{"mode":1,"rmap1":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"route-map":1}
,"rmap1":{"permit":1}
,"permit":{"(config-route-map)":1}
,"(config-route-map)":{"match":1}
}
;Search.control.loadWordPairs(pairs);
