var pairs =
{
"neighbor":{"attribute-unchanged":1,"parameter":1,"(a.b.c.d":1,"ipv4":1,"ipv6":1,"peer-group":1,"remote-as":1,"10.10.0.75":1}
,"attribute-unchanged":{"command":1,"({as-path":1,"(({as-path":1,"as-path":1}
,"command":{"advertise":1,"disable":1,"syntax":1,"command":1,"applies":1,"mode":1}
,"advertise":{"unchanged":1}
,"unchanged":{"bgp":1}
,"bgp":{"attributes":1,"neighbor":1,"peer":1,"(config-router)":1}
,"attributes":{"specified":1}
,"specified":{"neighbor":1}
,"parameter":{"command":1,"used":1}
,"disable":{"function":1}
,"function":{"command":1}
,"syntax":{"neighbor":1}
,"(a.b.c.d":{"x:x":1}
,"x:x":{":x:x":1}
,":x:x":{"word)":1,"address":1}
,"word)":{"attribute-unchanged":1}
,"({as-path":{"next-hop":1}
,"next-hop":{"med":1,"nexthop":1}
,"med":{"neighbor":1,"parameters":1,"multi-exit":1}
,"(({as-path":{"next-hop":1}
,"parameters":{"a.b.c.d":1}
,"a.b.c.d":{"address":1}
,"address":{"bgp":1,"family":1}
,"ipv4":{"format":1}
,"format":{"x:x":1,"word":1}
,"ipv6":{"format":1}
,"word":{"name":1}
,"name":{"bgp":1}
,"peer":{"group":1,"groups":1}
,"group":{"information":1,"as-path":1}
,"information":{"create":1}
,"create":{"peer":1}
,"groups":{"refer":1}
,"refer":{"neighbor":1}
,"peer-group":{"neighbor":1}
,"remote-as":{"commands":1}
,"commands":{"parameter":1}
,"used":{"command":1}
,"applies":{"peers":1}
,"peers":{"group":1}
,"as-path":{"path":1,"med":1}
,"path":{"attribute":1}
,"attribute":{"next-hop":1,"med":1,"command":1}
,"nexthop":{"attribute":1}
,"multi-exit":{"discriminator":1}
,"discriminator":{"attribute":1}
,"mode":{"router":1,"address":1,"example":1}
,"router":{"mode":1,"bgp":1}
,"family":{"mode":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"(config-router)":{"neighbor":1}
,"10.10.0.75":{"attribute-unchanged":1}
}
;Search.control.loadWordPairs(pairs);
