var pairs =
{
"show":{"ethernet":1}
,"ethernet":{"oam":1}
,"oam":{"status":1,"link":1}
,"status":{"command":1,"interface":1,"supported":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"ethernet":1}
,"link":{"monitoring":1,"event":1,"timeout":1}
,"monitoring":{"status":1}
,"interface":{"command":1,"ifname":1,"specify":1,"name":1,"show":1,"eth0":1}
,"syntax":{"show":1}
,"ifname":{"parameter":1,"specify":1}
,"parameter":{"interface":1}
,"specify":{"interface":1}
,"name":{"command":1}
,"mode":{"privileged":1,"example":1,"passive":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"example":{"following":1}
,"following":{"sample":1}
,"sample":{"output":1}
,"output":{"displays":1}
,"displays":{"operational":1}
,"operational":{"discovery":1}
,"discovery":{"state":1}
,"state":{"machine":1}
,"machine":{"link":1}
,"event":{"statistics":1}
,"statistics":{"interface":1}
,"eth0":{"eth0":1,"general":1}
,"general":{"mode":1}
,"passive":{"pdu":1}
,"pdu":{"max":1,"min":1}
,"max":{"rate":1}
,"rate":{"packets":1,"packet":1}
,"packets":{"per":1}
,"per":{"second":1}
,"second":{"pdu":1,"link":1,"(s)":1}
,"min":{"rate":1}
,"packet":{"per":1}
,"timeout":{"seconds":1}
,"seconds":{"high":1,"error":1}
,"high":{"threshold":1}
,"threshold":{"action":1,"error":1,"none":1}
,"action":{"action":1,"link":1}
,"supported":{"(on)":1}
,"(on)":{"symbol":1}
,"symbol":{"period":1,"(s)":1}
,"period":{"error":1}
,"error":{"window":1,"symbol":1,"frame":1,"second":1}
,"window":{"100":1,"1000":1}
,"100":{"million":1,"100":1,"milliseconds":1}
,"million":{"symbols":1}
,"symbols":{"low":1}
,"low":{"threshold":1}
,"(s)":{"high":1}
,"none":{"frame":1}
,"frame":{"error":1,"(s)":1,"period":1,"seconds":1}
,"milliseconds":{"low":1}
,"1000":{"100,000":1,"100":1}
,"100,000":{"frames":1}
,"frames":{"low":1}
}
;Search.control.loadWordPairs(pairs);
