var pairs =
{
"show":{"interface":1}
,"interface":{"(ipv4)":1,"specify":1,"name":1,"brief":1,"ifname":1,"ip-address":1}
,"(ipv4)":{"command":1}
,"command":{"display":1,"command":1,"syntax":1,"mode":1,"show":1}
,"display":{"brief":1,"information":1,"name":1}
,"brief":{"information":1,"show":1,"parameters":1,"brief":1,"summary":1,"command":1,"interface":1}
,"information":{"interfaces":1,"specific":1}
,"interfaces":{"addresses":1}
,"addresses":{"assigned":1}
,"assigned":{"display":1}
,"specific":{"interface":1}
,"specify":{"interface":1}
,"name":{"command":1,"interface":1}
,"syntax":{"show":1}
,"ifname":{"brief":1,"display":1}
,"parameters":{"ifname":1}
,"summary":{"status":1}
,"status":{"configuration":1,"protocol":1}
,"configuration":{"command":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"following":1}
,"following":{"sample":1}
,"sample":{"output":1}
,"output":{"show":1}
,"ip-address":{"status":1}
,"protocol":{"gmpls":1}
,"gmpls":{"type":1}
,"type":{"rpf":1,"127.0.0.1":1}
,"rpf":{"type":1}
,"127.0.0.1":{"mpls":1}
,"mpls":{"none":1,"strict":1}
,"none":{"p1p1":1,"em1":1,"svlan0.1":1,"labeled":1}
,"p1p1":{"unassigned":1}
,"unassigned":{"mpls":1,"down":1}
,"strict":{"p1p2":1}
,"p1p2":{"unassigned":1}
,"down":{"mpls":1}
,"em1":{"10.12.20.27":1}
,"10.12.20.27":{"mpls":1}
,"svlan0.1":{"unassigned":1}
,"labeled":{"bytes":1}
,"bytes":{"0\u002F0\u002F0\u002F0\u002F0":1}
}
;Search.control.loadWordPairs(pairs);
