var pairs =
{
"hal_ipv6_uc_route_delete":{"function":1,"(unsigned":1}
,"function":{"deletes":1,"fails":1,"succeeds":1}
,"deletes":{"ipv6":1}
,"ipv6":{"route":1}
,"route":{"forwarding":1}
,"forwarding":{"plane":1}
,"plane":{"syntax":1}
,"syntax":{"int":1}
,"int":{"hal_ipv6_uc_route_delete":1,"num":1}
,"(unsigned":{"short":1}
,"short":{"fib":1}
,"fib":{"struct":1,"fib":1,"ipaddr":1}
,"struct":{"pal_in6_addr":1,"hal_ipv6uc_nexthop":1}
,"pal_in6_addr":{"*ipaddr":1}
,"*ipaddr":{"unsigned":1}
,"unsigned":{"char":1}
,"char":{"ipmask":1}
,"ipmask":{"int":1,"mask":1}
,"num":{"struct":1,"number":1}
,"hal_ipv6uc_nexthop":{"*nexthops)":1}
,"*nexthops)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"fib":1,"none":1}
,"ipaddr":{"address":1}
,"address":{"ipmask":1}
,"mask":{"length":1}
,"length":{"num":1}
,"number":{"nexthops":1}
,"nexthops":{"nexthops":1,"list":1,"output":1}
,"list":{"nexthops":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"function":1}
,"fails":{"hal_success":1}
,"hal_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
