var pairs =
{
"reception":{"eth-lm":1,"framework":1,"time":1}
,"eth-lm":{"ccm":1,"information":1,"otherwise":1,"used":1}
,"ccm":{"reception":1,"accomplished":1,"frame":1,"frames":1,"transmission":1}
,"accomplished":{"using":1}
,"using":{"mep":1}
,"mep":{"ccm":1,"enable":1,"uses":1,"detects":1}
,"framework":{"eth-lm":1}
,"information":{"received":1,"processed":1}
,"received":{"eth-ccm":1,"ccm":1,"values":1}
,"eth-ccm":{"frame":1}
,"frame":{"information":1,"received":1,"values":1,"previous":1,"frame":1,"lossfar-end":1,"lossnear-end":1,"different":1,"loss":1}
,"processed":{"mep":1}
,"enable":{"dual-ended":1}
,"dual-ended":{"eth-lm":1}
,"otherwise":{"eth-lm":1}
,"used":{"configured":1}
,"configured":{"proactive":1,"mep":1}
,"proactive":{"loss":1}
,"loss":{"measurement":1,"measurements":1}
,"measurement":{"mep":1}
,"uses":{"following":1}
,"following":{"values":1}
,"values":{"near-end":1,"local":1,"represented":1}
,"near-end":{"far-end":1}
,"far-end":{"loss":1}
,"measurements":{"receives":1,"carried":1}
,"receives":{"ccm":1}
,"frames":{"txfcf":1}
,"txfcf":{"rxfcb":1,"[tc]":1,"[tp]":1}
,"rxfcb":{"txfcb":1,"[tc]":1,"[tp]":1}
,"txfcb":{"values":1,"[tc]":1,"[tp]":1}
,"local":{"counter":1}
,"counter":{"rxfcl":1}
,"rxfcl":{"value":1,"[tc]":1,"[tp]":1}
,"value":{"receiving":1,"time":1,"received":1}
,"receiving":{"ccm":1}
,"represented":{"txfcf":1}
,"[tc]":{"rxfcb":1,"txfcb":1,"rxfcl":1,"reception":1,"-txfcb":1,"-rxfcb":1,"-txfcf":1,"-rxfcl":1}
,"time":{"current":1,"previous":1}
,"current":{"frame":1}
,"previous":{"ccm":1,"frame":1}
,"[tp]":{"rxfcb":1,"txfcb":1,"rxfcl":1,"reception":1,"frame":1,"period":1}
,"lossfar-end":{"txfcb":1}
,"-txfcb":{"[tp]":1}
,"-rxfcb":{"[tp]":1}
,"lossnear-end":{"txfcf":1}
,"-txfcf":{"[tp]":1}
,"-rxfcl":{"[tp]":1}
,"period":{"field":1,"mep":1,"defect":1}
,"field":{"value":1}
,"different":{"configured":1}
,"transmission":{"period":1}
,"detects":{"unexpected":1}
,"unexpected":{"period":1}
,"defect":{"condition":1}
,"condition":{"case":1}
,"case":{"frame":1}
}
;Search.control.loadWordPairs(pairs);
