var pairs =
{
"validation":{"command":1}
,"command":{"show":1}
,"show":{"mpls":1}
,"mpls":{"l2-circuit":1,"layer-2":1}
,"l2-circuit":{"includes":1,"vc1":1}
,"includes":{"status":1}
,"status":{"related":1,"ingress":1,"faults":1}
,"related":{"information":1}
,"information":{"static":1}
,"static":{"show":1}
,"vc1":{"mpls":1}
,"layer-2":{"virtual":1}
,"virtual":{"circuit":1}
,"circuit":{"test":1,"group":1,"type":1,"configured":1,"runtime":1}
,"test":{"100":1}
,"100":{"pw-index":1}
,"pw-index":{"endpoint":1}
,"endpoint":{"3.4.5.6":1}
,"3.4.5.6":{"control":1}
,"control":{"word":1}
,"word":{"mpls":1}
,"group":{"none":1}
,"none":{"bound":1}
,"bound":{"interface":1}
,"interface":{"eth1":1}
,"eth1":{"virtual":1}
,"type":{"ethernet":1}
,"ethernet":{"vlan":1}
,"vlan":{"virtual":1}
,"configured":{"primary":1,"active":1}
,"primary":{"virtual":1}
,"active":{"virtual":1,"static-pw-status":1}
,"runtime":{"mode":1}
,"mode":{"active":1}
,"static-pw-status":{"enabled":1}
,"enabled":{"local":1}
,"local":{"refresh":1,"status":1}
,"refresh":{"timer":1}
,"timer":{"sec":1}
,"sec":{"local":1,"remote":1}
,"ingress":{"receive":1}
,"receive":{"fault":1}
,"fault":{"egress":1,"remote":1}
,"egress":{"transmit":1}
,"transmit":{"fault":1}
,"remote":{"refresh":1,"status":1}
,"faults":{"detected":1}
}
;Search.control.loadWordPairs(pairs);
