var pairs =
{
"bridge":{"instance":1,"form":1,"command":1,"(<1-32>":1,"identifier":1,"<1-63>":1,"protocol":1}
,"instance":{"command":1,"bridge":1,"identifier":1,"(<1-63>":1,"spbv":1,"(config-mst)":1}
,"command":{"add":1,"delete":1,"syntax":1,"mode":1}
,"add":{"mst":1}
,"mst":{"instance":1,"configure":1,"configuration":1}
,"form":{"command":1}
,"delete":{"mst":1}
,"identifier":{"bridge":1,"backbone":1,"spbm":1}
,"syntax":{"bridge":1}
,"(<1-32>":{"backbone)":1}
,"backbone)":{"instance":1}
,"(<1-63>":{"spbm":1}
,"spbm":{"spbv)":1,"shortest":1}
,"spbv)":{"bridge":1,"parameters":1}
,"parameters":{"<1-32>":1}
,"<1-32>":{"bridge":1}
,"backbone":{"backbone":1,"bridge":1}
,"<1-63>":{"mst":1}
,"shortest":{"path":1}
,"path":{"bridging":1}
,"bridging":{"-mac":1,"-vid":1}
,"-mac":{"instance":1}
,"spbv":{"shortest":1}
,"-vid":{"instance":1}
,"mode":{"mst":1,"examples":1}
,"configure":{"mode":1,"terminal":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"bridge":1,"spanning-tree":1}
,"protocol":{"mstp":1}
,"mstp":{"(config)":1}
,"spanning-tree":{"mst":1}
,"configuration":{"(config-mst)":1}
,"(config-mst)":{"bridge":1}
}
;Search.control.loadWordPairs(pairs);
