var pairs =
{
"verify":{"unicast":1}
,"unicast":{"source":1,"reverse":1}
,"source":{"reachable-via":1,"reachable":1,"address":1}
,"reachable-via":{"command":1,"{any":1,"parameters":1,"(config-if)":1}
,"command":{"enable":1,"disable":1,"syntax":1,"mode":1}
,"enable":{"unicast":1}
,"reverse":{"path":1}
,"path":{"forwarding":1}
,"forwarding":{"(urpf)":1}
,"(urpf)":{"checking":1}
,"checking":{"interface":1,"command":1,"source":1}
,"interface":{"ipv4":1,"layer":1,"source":1,"packet":1,"mode":1}
,"ipv4":{"interface":1}
,"layer":{"type":1}
,"type":{"form":1}
,"form":{"command":1}
,"disable":{"urpf":1}
,"urpf":{"checking":1}
,"syntax":{"verify":1}
,"{any":{"[allow-default]":1}
,"[allow-default]":{"rx}":1}
,"rx}":{"verify":1}
,"parameters":{"loose":1}
,"loose":{"mode":1}
,"mode":{"source":1,"strict":1,"interface":1,"examples":1}
,"reachable":{"via":1}
,"via":{"interface":1}
,"address":{"packet":1,"otherwise":1}
,"packet":{"appear":1,"received":1}
,"appear":{"routing":1}
,"routing":{"table":1}
,"table":{"allow-default":1}
,"allow-default":{"allow":1}
,"allow":{"default":1}
,"default":{"route":1}
,"route":{"match":1,"considered":1}
,"match":{"checking":1}
,"otherwise":{"default":1}
,"considered":{"loose":1}
,"strict":{"mode":1}
,"received":{"command":1}
,"examples":{"(config-if)":1}
,"(config-if)":{"verify":1}
}
;Search.control.loadWordPairs(pairs);
