var pairs =
{
"type":{"command":1,"local":1,"default":1,"(dynamic":1,"dynamic":1}
,"command":{"type":1,"syntax":1,"mode":1,"configure":1}
,"local":{"cbp":1}
,"cbp":{"(customer":1}
,"(customer":{"backbone":1}
,"backbone":{"port)":1}
,"port)":{"interface":1}
,"interface":{"associated":1}
,"associated":{"tesi":1}
,"tesi":{"(traffic":1,"static":1,"none":1}
,"(traffic":{"engineering":1}
,"engineering":{"service":1}
,"service":{"instance)":1}
,"instance)":{"form":1}
,"form":{"command":1,"ignored":1}
,"default":{"(static)":1}
,"(static)":{"specify":1}
,"specify":{"parameter":1}
,"parameter":{"form":1}
,"ignored":{"command":1}
,"syntax":{"type":1}
,"(dynamic":{"static)":1,"static":1}
,"static)":{"type":1}
,"static":{"parameters":1,"static":1,"tesi":1}
,"parameters":{"dynamic":1}
,"dynamic":{"dynamic":1,"tesi":1}
,"none":{"command":1}
,"mode":{"pbb-te":1,"examples":1}
,"pbb-te":{"configure":1}
,"configure":{"mode":1,"terminal":1,"tesid":1}
,"examples":{"following":1}
,"following":{"example":1}
,"example":{"command":1}
,"terminal":{"(config)":1}
,"(config)":{"pbb-te":1}
,"tesid":{"(pbb-te-config)":1}
,"(pbb-te-config)":{"type":1}
}
;Search.control.loadWordPairs(pairs);
