var pairs =
{
"configure":{"configure":1,"uniquely":1,"terminal":1,"mode":1,"pe2":1,"pe1":1}
,"uniquely":{"identifies":1}
,"identifies":{"layer-2":1}
,"layer-2":{"circuit":1,"circuits":1}
,"circuit":{"among":1}
,"among":{"layer-2":1}
,"circuits":{"routers":1}
,"routers":{"(endpoints)":1}
,"(endpoints)":{"configured":1}
,"configured":{"vc-id":1}
,"vc-id":{"(100":1}
,"(100":{"example)":1}
,"example)":{"pe1":1}
,"pe1":{"configure":1,"example":1}
,"terminal":{"enter":1}
,"enter":{"configure":1}
,"mode":{"(config)":1}
,"(config)":{"mpls":1}
,"mpls":{"l2-circuit":1}
,"l2-circuit":{"100":1}
,"100":{"3.3.3.3":1,"1.1.1.1":1}
,"3.3.3.3":{"configure":1,"endpoint":1}
,"pe2":{"example":1,"configure":1}
,"example":{"name":1}
,"name":{"100":1}
,"endpoint":{"address":1}
,"address":{"pe2":1}
,"1.1.1.1":{"configure":1,"endpoint":1}
}
;Search.control.loadWordPairs(pairs);
