var pairs =
{
"layer":{"protocols":1,"routing":1}
,"protocols":{"zebos-xp":1,"interact":1}
,"zebos-xp":{"supports":1,"offers":1}
,"supports":{"ipv4":1}
,"ipv4":{"ipv6":1}
,"ipv6":{"versions":1}
,"versions":{"border":1}
,"border":{"gateway":1}
,"gateway":{"protocol":1}
,"protocol":{"open":1,"intermediate":1,"bidirectional":1,"modules":1}
,"open":{"shortest":1}
,"shortest":{"path":1}
,"path":{"first":1}
,"first":{"routing":1,"(cspf)":1,"(ospf)":1}
,"routing":{"information":1,"protocols":1,"architecture":1,"(vr)":1}
,"information":{"protocol":1,"base":1}
,"intermediate":{"system":1,"system-to-intermediate":1}
,"system":{"intermediate":1,"virtual":1,"(is-is)":1}
,"virtual":{"router":1,"routing":1}
,"router":{"redundancy":1}
,"redundancy":{"protocol":1}
,"bidirectional":{"forwarding":1}
,"forwarding":{"detection":1}
,"detection":{"figure":1}
,"figure":{"2-4":1}
,"2-4":{"shows":1}
,"shows":{"layer":1}
,"interact":{"unicast":1}
,"unicast":{"routing":1}
,"base":{"daemon":1}
,"daemon":{"network":1,"route":1}
,"network":{"services":1}
,"services":{"module":1}
,"module":{"layer":1,"interface":1}
,"architecture":{"protocol":1}
,"modules":{"communicate":1}
,"communicate":{"network":1}
,"interface":{"updates":1}
,"updates":{"unicast":1,"redistributed":1}
,"route":{"updates":1}
,"redistributed":{"routes":1}
,"routes":{"addition":1}
,"addition":{"standard":1}
,"standard":{"layer":1}
,"offers":{"virtual":1}
,"(vr)":{"support":1}
,"support":{"traffic":1,"open":1}
,"traffic":{"engineering":1}
,"engineering":{"(te)":1}
,"(te)":{"extensions":1}
,"extensions":{"constrained":1}
,"constrained":{"shortest":1}
,"(cspf)":{"topology":1}
,"topology":{"support":1}
,"(ospf)":{"intermediate":1}
,"system-to-intermediate":{"system":1}
,"(is-is)":{"protocols":1}
}
;Search.control.loadWordPairs(pairs);
