var pairs =
{
"rip_restart_set":{"function":1,"(u_int32_t":1}
,"function":{"preserves":1,"executes":1,"called":1}
,"preserves":{"nsm":1,"routes":1}
,"nsm":{"restore":1,"routing":1,"rip":1,"preserves":1}
,"restore":{"rip":1}
,"rip":{"routes":1,"process":1,"shut":1,"until":1,"graceful":1,"restart":1}
,"routes":{"nsm":1,"installed":1}
,"routing":{"table":1}
,"table":{"forces":1}
,"forces":{"rip":1}
,"process":{"restart":1}
,"restart":{"function":1,"rip":1,"grace":1}
,"executes":{"router":1}
,"router":{"immediately":1,"default":1,"passed":1}
,"immediately":{"shuts":1}
,"shuts":{"down":1}
,"down":{"notifies":1,"gracefully":1}
,"notifies":{"nsm":1}
,"shut":{"down":1}
,"gracefully":{"nsm":1}
,"installed":{"rip":1}
,"until":{"grace-period":1}
,"grace-period":{"expires":1}
,"expires":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"restart":1,"available":1}
,"graceful":{"command":1}
,"available":{"configuration":1}
,"configuration":{"option":1}
,"option":{"--enable-restart":1}
,"--enable-restart":{"enabled":1}
,"enabled":{"compiling":1}
,"compiling":{"zebos-xp":1}
,"zebos-xp":{"syntax":1}
,"syntax":{"int":1}
,"int":{"rip_restart_set":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1}
,"u_int32_t":{"seconds)":1}
,"seconds)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"default":{"value":1,"65535":1}
,"value":{"non-vr":1,"rip":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"parameter":1}
,"parameter":{"seconds":1}
,"seconds":{"rip":1,"default":1}
,"grace":{"period":1}
,"period":{"seconds":1,"invalid":1}
,"65535":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"rip_api_set_err_grace_period_invalid":1}
,"rip_api_set_err_grace_period_invalid":{"value":1}
,"invalid":{"rip_api_set_err_vr_not_exist":1,"virtual":1}
,"rip_api_set_err_vr_not_exist":{"invalid":1}
,"passed":{"rip_api_set_success":1}
,"rip_api_set_success":{"call":1}
,"call":{"successful":1}
}
;Search.control.loadWordPairs(pairs);
