var pairs =
{
"g8031_manual_switch_delete_fn":{"function":1,"(u_int32_t":1}
,"function":{"called":1,"succeeds":1}
,"called":{"form":1}
,"form":{"g8031":1}
,"g8031":{"manual":1}
,"manual":{"command":1,"switch":1}
,"command":{"restore":1}
,"restore":{"working":1}
,"working":{"protection":1}
,"protection":{"paths":1,"group":1}
,"paths":{"original":1}
,"original":{"states":1}
,"states":{"syntax":1}
,"syntax":{"enum":1}
,"enum":{"g8031_return_code":1}
,"g8031_return_code":{"g8031_manual_switch_delete_fn":1}
,"(u_int32_t":{"eps_id":1}
,"eps_id":{"u_int8_t":1,"protection":1}
,"u_int8_t":{"*br_name)":1}
,"*br_name)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"eps_id":1,"none":1}
,"group":{"<1-4094>":1,"exist":1}
,"<1-4094>":{"br_name":1}
,"br_name":{"name":1}
,"name":{"bridge":1}
,"bridge":{"output":1,"found":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"g8031_bridge_not_found":1}
,"g8031_bridge_not_found":{"bridge":1}
,"found":{"g8031_protection_group_not_exists":1}
,"g8031_protection_group_not_exists":{"protection":1}
,"exist":{"g8031_state_not_available":1}
,"g8031_state_not_available":{"current":1}
,"current":{"state":1}
,"state":{"available":1,"g8031_success":1}
,"available":{"g8031_fsm_not_in_ms":1}
,"g8031_fsm_not_in_ms":{"manual":1}
,"switch":{"state":1}
,"g8031_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
