var pairs =
{
"isis_set_sys_poll_es_hello_rate":{"call":1,"(u_int32_t":1}
,"call":{"sets":1}
,"sets":{"value":1}
,"value":{"seconds":1,"syntax":1,"non-vr":1,"isis_api_set_success":1}
,"seconds":{"used":1}
,"used":{"suggested":1}
,"suggested":{"configuration":1}
,"configuration":{"timer":1,"default":1}
,"timer":{"ish":1}
,"ish":{"pdus":1}
,"pdus":{"soliciting":1,"output":1}
,"soliciting":{"configuration":1}
,"default":{"value":1}
,"syntax":{"int":1}
,"int":{"isis_set_sys_poll_es_hello_rate":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1,"instance":1}
,"u_int32_t":{"instance":1,"val)":1}
,"instance":{"u_int32_t":1,"is-is":1,"val":1,"found":1}
,"val)":{"input":1}
,"input":{"parameter":1}
,"parameter":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"is-is":{"instance":1}
,"val":{"value":1}
,"output":{"parameter":1}
,"none":{"return":1}
,"return":{"value":1}
,"isis_api_set_success":{"complete":1}
,"complete":{"isis_api_set_error":1,"instance":1}
,"isis_api_set_error":{"complete":1}
}
;Search.control.loadWordPairs(pairs);
