var pairs =
{
"bgp":{"router-id":1,"router":1,"100":1}
,"router-id":{"command":1,"a.b.c.d":1,"bgp":1,"10.1.2.7":1}
,"command":{"manually":1,"used":1,"remove":1,"syntax":1,"mode":1}
,"manually":{"configure":1,"configured":1}
,"configure":{"fixed":1,"terminal":1}
,"fixed":{"router":1}
,"router":{"bgp":1,"identifier":1,"current":1,"command":1,"ipv4":1,"address":1,"mode":1}
,"identifier":{"command":1,"overridden":1}
,"used":{"configure":1}
,"current":{"router":1}
,"overridden":{"peers":1}
,"peers":{"reset":1}
,"reset":{"parameter":1}
,"parameter":{"command":1,"a.b.c.d":1}
,"remove":{"manually":1}
,"configured":{"fixed":1,"router":1,"highest":1}
,"syntax":{"bgp":1}
,"a.b.c.d":{"bgp":1,"parameter":1,"router":1}
,"ipv4":{"address":1}
,"address":{"format":1,"loopback":1,"router-id":1}
,"format":{"default":1}
,"default":{"loopback":1}
,"loopback":{"interface":1}
,"interface":{"configured":1,"loopback":1}
,"highest":{"address":1}
,"mode":{"router":1,"examples":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"100":{"(config-router)":1}
,"(config-router)":{"bgp":1}
,"10.1.2.7":{"(config)":1}
}
;Search.control.loadWordPairs(pairs);
