var pairs =
{
"data":{"plane":1}
,"plane":{"part":1,"built":1,"forwards":1,"logic":1,"frames":1}
,"part":{"switch":1}
,"switch":{"router":1}
,"router":{"architecture":1}
,"architecture":{"forwards":1}
,"forwards":{"frames":1,"traffic":1}
,"frames":{"packets":1}
,"packets":{"arriving":1,"data":1,"device":1}
,"arriving":{"interface":1}
,"interface":{"routers":1}
,"routers":{"switches":1}
,"switches":{"control":1}
,"control":{"plane":1}
,"built":{"process":1}
,"process":{"incoming":1}
,"incoming":{"frames":1}
,"traffic":{"next":1}
,"next":{"hop":1}
,"hop":{"along":1}
,"along":{"path":1}
,"path":{"destination":1}
,"destination":{"according":1}
,"according":{"control":1}
,"logic":{"data":1}
,"device":{"called":1}
,"called":{"forwarding":1}
,"forwarding":{"plane":1}
}
;Search.control.loadWordPairs(pairs);
