var pairs =
{
"validation":{"peb1":1}
,"peb1":{"rtr2":1}
,"rtr2":{"show":1}
,"show":{"ethernet":1}
,"ethernet":{"enni":1}
,"enni":{"ovc":1}
,"ovc":{"attributes":1,"type":1,"ce-vlan":1}
,"attributes":{"ovc-id":1,"interface":1}
,"ovc-id":{"ovc1":1,"-ovc1":1,"ovc2":1,"-ovc2":1}
,"ovc1":{"bridge":1}
,"bridge":{"bridge":1,"name":1}
,"name":{"-----------------%":1}
,"-----------------%":{"ovc-id":1}
,"-ovc1":{"ovc":1}
,"type":{"-point-to-point":1}
,"-point-to-point":{"---------------------------%":1}
,"---------------------------%":{"oep-id":1,"max":1}
,"oep-id":{"-oep1":1,"-oep2":1,"-oep3":1,"-oep4":1}
,"-oep1":{"---------------------------%":1}
,"max":{"oep":1,"ovc":1}
,"oep":{"max":1}
,"ce-vlan":{"preservation":1,"cos":1}
,"preservation":{"-no":1,"pcb1":1,"command":1}
,"-no":{"ce-vlan":1,"s-vlan":1,"pcb2":1,"peb2":1}
,"cos":{"preservation":1}
,"s-vlan":{"preservation":1,"cos":1}
,"pcb1":{"rtr3":1}
,"rtr3":{"show":1}
,"-oep2":{"---------------------------%":1}
,"pcb2":{"rtr4":1}
,"rtr4":{"show":1}
,"ovc2":{"bridge":1}
,"-ovc2":{"ovc":1}
,"-oep3":{"---------------------------%":1}
,"peb2":{"rtr5":1}
,"rtr5":{"show":1}
,"-oep4":{"---------------------------%":1}
,"command":{"show":1}
,"interface":{"eth1":1}
}
;Search.control.loadWordPairs(pairs);
