var pairs =
{
"bgp_peer_remote_as":{"function":1}
,"function":{"creates":1,"called":1,"successful":1}
,"creates":{"new":1}
,"new":{"peer":1}
,"peer":{"function":1,"afi":1,"enabled":1,"peer-group":1,"inside":1,"instance":1,"configured":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"remote-as":1}
,"remote-as":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"bgp_remote_as":1}
,"bgp_remote_as":{"(struct":1}
,"(struct":{"bgp":1}
,"bgp":{"union":1,"bgp":1,"instance":1}
,"union":{"sockunion":1}
,"sockunion":{"*su":1,"format":1}
,"*su":{"as_t":1}
,"as_t":{"*as":1}
,"*as":{"afi_t":1}
,"afi_t":{"afi":1}
,"afi":{"safi_t":1,"address":1}
,"safi_t":{"safi)":1}
,"safi)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bgp":1,"error":1}
,"instance":{"peer\u0027s":1,"match":1,"number":1,"(-45)":1}
,"peer\u0027s":{"address":1}
,"address":{"union":1,"family":1}
,"format":{"number":1}
,"number":{"peer":1,"(-16)":1}
,"family":{"identifier":1,"unconfigured":1}
,"identifier":{"(i_ip":1,"(si_unicast":1}
,"(i_ip":{"i_ip6)":1}
,"i_ip6)":{"safi":1}
,"safi":{"subsequent":1}
,"subsequent":{"address":1}
,"(si_unicast":{"si_multicast)":1}
,"si_multicast)":{"output":1}
,"output":{"parameters":1}
,"error":{"occurs":1}
,"occurs":{"value":1}
,"value":{"used":1,"caller":1,"bgp_api_set_success":1}
,"used":{"return":1}
,"return":{"value":1}
,"caller":{"return":1}
,"bgp_api_set_success":{"function":1}
,"successful":{"(0)":1}
,"(0)":{"bgp_api_set_error":1}
,"bgp_api_set_error":{"peer":1}
,"enabled":{"view":1}
,"view":{"(-1)":1}
,"(-1)":{"bgp_api_set_err_peer_group_member":1}
,"bgp_api_set_err_peer_group_member":{"peer":1}
,"peer-group":{"member":1,"already":1,"vice":1}
,"member":{"peer-group":1}
,"already":{"configuration":1}
,"configuration":{"(-6)":1}
,"(-6)":{"bgp_api_set_err_peer_group_peer_type_different":1}
,"bgp_api_set_err_peer_group_peer_type_different":{"try":1}
,"try":{"create":1}
,"create":{"ibgp":1}
,"ibgp":{"peer":1}
,"inside":{"ebgp":1}
,"ebgp":{"peer-group":1}
,"vice":{"versa":1}
,"versa":{"(-14)":1}
,"(-14)":{"bgp_api_set_err_as_mismatch":1}
,"bgp_api_set_err_as_mismatch":{"mismatch":1,"number":1}
,"mismatch":{"(-16)":1}
,"(-16)":{"bgp_api_set_err_as_mismatch":1,"bgp_api_set_err__unconfigured":1}
,"match":{"master":1}
,"master":{"instance":1}
,"bgp_api_set_err__unconfigured":{"address":1}
,"unconfigured":{"(-25)":1}
,"(-25)":{"bgp_api_set_err_peer_config_in_another_inst":1}
,"bgp_api_set_err_peer_config_in_another_inst":{"peer":1}
,"configured":{"instance":1}
}
;Search.control.loadWordPairs(pairs);
