var pairs =
{
"ospf_if_resync_timeout_set":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"called":1,"succeeds":1}
,"sets":{"timeout":1}
,"timeout":{"interval":1,"re-synchronization":1,"seconds":1}
,"interval":{"re-synchronization":1}
,"re-synchronization":{"out-of-band":1,"occur":1,"timeout":1}
,"out-of-band":{"re-synchronization":1}
,"occur":{"adjacency":1}
,"adjacency":{"reset":1}
,"reset":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"ospf":1}
,"ospf":{"(a.b.c.d":1}
,"(a.b.c.d":{"resync-timeout":1}
,"resync-timeout":{"<1-65535>":1}
,"<1-65535>":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf_if_resync_timeout_set":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1}
,"char":{"*name":1}
,"*name":{"u_int32_t":1}
,"u_int32_t":{"timeout)":1}
,"timeout)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"found":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"name":1}
,"name":{"interface":1,"timeout":1}
,"interface":{"name":1,"configured":1}
,"seconds":{"65535>":1}
,"65535>":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf_api_set_success":1}
,"ospf_api_set_success":{"function":1}
,"succeeds":{"ospf_api_set_err_if_param_not_configured":1}
,"ospf_api_set_err_if_param_not_configured":{"given":1}
,"given":{"interface":1}
,"configured":{"ospf_api_set_err_vr_not_exist":1}
,"ospf_api_set_err_vr_not_exist":{"virtual":1}
}
;Search.control.loadWordPairs(pairs);
