var pairs =
{
"key":{"command":1,"<0-2147483647>":1,"identifier":1,"number":1,"chain":1,"(config-keychain-key)":1}
,"command":{"manage":1,"allows":1,"syntax":1,"mode":1}
,"manage":{"add":1}
,"add":{"delete":1}
,"delete":{"authentication":1}
,"authentication":{"keys":1}
,"keys":{"key-chain":1}
,"key-chain":{"command":1}
,"allows":{"enter":1}
,"enter":{"keychain-key":1}
,"keychain-key":{"mode":1,"command":1}
,"mode":{"password":1,"keychain":1,"examples":1,"configure":1}
,"password":{"key":1}
,"syntax":{"key":1}
,"<0-2147483647>":{"key":1,"parameters":1,"specify":1}
,"parameters":{"<0-2147483647>":1}
,"specify":{"key":1}
,"identifier":{"default":1}
,"default":{"default":1,"isis":1}
,"isis":{"uses":1}
,"uses":{"level-1-2":1,"level-1":1}
,"level-1-2":{"level-2":1,"instance":1}
,"level-2":{"instance":1}
,"instance":{"level-1-2":1,"otherwise":1}
,"otherwise":{"uses":1}
,"level-1":{"command":1}
,"keychain":{"mode":1}
,"examples":{"following":1}
,"following":{"example":1}
,"example":{"configures":1}
,"configures":{"key":1}
,"number":{"shows":1}
,"shows":{"change":1}
,"change":{"keychain-key":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"key":1}
,"chain":{"mychain":1}
,"mychain":{"(config-keychain)":1}
,"(config-keychain)":{"key":1}
}
;Search.control.loadWordPairs(pairs);
