var pairs =
{
"mrib":{"services":1,"provides":1,"assigns":1,"notifies":1,"generates":1}
,"services":{"mrib":1,"communicates":1}
,"provides":{"following":1,"index":1}
,"following":{"services":1}
,"communicates":{"multicast":1}
,"multicast":{"forwarding":1,"protocol":1,"routing":1,"traffic":1}
,"forwarding":{"information":1,"entries":1,"statistics":1}
,"information":{"base":1,"multicast":1}
,"base":{"(mfib)":1}
,"(mfib)":{"acts":1}
,"acts":{"proxy":1}
,"proxy":{"multicast":1}
,"protocol":{"modules":1,"multicast":1,"module":1}
,"modules":{"programming":1,"maintains":1,"polls":1}
,"programming":{"handling":1}
,"handling":{"events":1}
,"events":{"mfib":1}
,"mfib":{"maintains":1,"multicast":1}
,"maintains":{"database":1,"keep-alive":1}
,"database":{"interfaces":1,"forwarding":1}
,"interfaces":{"multicast":1,"provides":1}
,"routing":{"enabled":1}
,"enabled":{"mrib":1}
,"assigns":{"unique":1}
,"unique":{"index":1}
,"index":{"interfaces":1,"information":1}
,"entries":{"multicast":1}
,"polls":{"mfib":1}
,"statistics":{"entry":1,"polling)":1}
,"entry":{"maintains":1,"requested":1,"stops":1}
,"keep-alive":{"timer":1}
,"timer":{"entry":1,"expires":1}
,"requested":{"protocol":1}
,"traffic":{"entry":1}
,"stops":{"(based":1}
,"(based":{"statistics":1}
,"polling)":{"mrib":1}
,"notifies":{"multicast":1}
,"module":{"keep-alive":1,"acknowledges":1}
,"expires":{"pim-sm":1}
,"pim-sm":{"mrib":1}
,"generates":{"pim":1}
,"pim":{"register":1}
,"register":{"message":1}
,"message":{"multicast":1}
,"acknowledges":{"wholepkt":1}
,"wholepkt":{"mfib":1}
}
;Search.control.loadWordPairs(pairs);
