var pairs =
{
"isis_get_prot_supp_exist_state":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"state":1}
,"state":{"supported":1,"manually":1}
,"supported":{"protocol":1}
,"protocol":{"syntax":1,"u_int32_t":1,"supported":1,"129":1,"active":1,"found":1}
,"syntax":{"int":1}
,"int":{"isis_get_prot_supp_exist_state":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1,"instance":1}
,"u_int32_t":{"instance":1,"protocol":1,"*ret)":1}
,"instance":{"u_int32_t":1,"is-is":1,"protocol":1,"isis_api_get_error":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"ret":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"is-is":{"instance":1}
,"129":{"iso8473":1}
,"iso8473":{"204":1}
,"204":{"142":1}
,"142":{"ipv6":1}
,"ipv6":{"output":1}
,"output":{"parameters":1}
,"ret":{"state":1}
,"manually":{"configured":1}
,"configured":{"supported":1}
,"active":{"(default)":1}
,"(default)":{"service":1}
,"service":{"ready":1}
,"ready":{"create":1}
,"create":{"create":1,"wait":1}
,"wait":{"destroy":1}
,"destroy":{"return":1}
,"return":{"values":1}
,"values":{"isis_api_get_success":1}
,"isis_api_get_success":{"supported":1}
,"found":{"specified":1}
,"specified":{"instance":1}
,"isis_api_get_error":{"supported":1}
}
;Search.control.loadWordPairs(pairs);
