var pairs =
{
"show":{"vrf":1}
,"vrf":{"command":1,"show":1,"word":1,"name":1,"information":1,"instance":1,"ipi":1}
,"command":{"list":1,"syntax":1,"mode":1,"displaying":1}
,"list":{"information":1,"-----------------------------------------------------------------qa":1}
,"information":{"vrfs":1,"process":1,"vrf":1}
,"vrfs":{"command":1}
,"syntax":{"show":1}
,"word":{"parameter":1,"specify":1}
,"parameter":{"word":1}
,"specify":{"vrf":1}
,"name":{"command":1,"ospf":1}
,"mode":{"exec":1,"privileged":1,"examples":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"examples":{"following":1}
,"following":{"sample":1}
,"sample":{"output":1}
,"output":{"show":1}
,"displaying":{"vrf":1}
,"process":{"ids":1}
,"ids":{"ospf":1}
,"ospf":{"instances":1,"pid":1}
,"instances":{"show":1}
,"pid":{"interface":1}
,"interface":{"list":1}
,"-----------------------------------------------------------------qa":{"eth0":1}
,"eth0":{"eth1":1}
,"eth1":{"ipi":1}
,"ipi":{"eth2":1,"show":1,"vrf":1,"(id=3)":1}
,"eth2":{"following":1}
,"instance":{"named":1}
,"named":{"ipi":1}
,"(id=3)":{"ospf":1}
}
;Search.control.loadWordPairs(pairs);
