var pairs =
{
"isis_get_next_circ_3way_enabled":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"status":1}
,"status":{"next":1,"circuit":1}
,"next":{"circuit":1,"supported":1}
,"circuit":{"enabled":1,"index":1}
,"enabled":{"3way":1}
,"3way":{"handshake":1}
,"handshake":{"syntax":1,"isistruthvaluetrue":1}
,"syntax":{"int":1}
,"int":{"isis_get_next_circ_3way_enabled":1,"indexlen":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1,"instance":1}
,"u_int32_t":{"*instance":1,"*circindex":1,"*ret)":1}
,"*instance":{"u_int32_t":1}
,"*circindex":{"int":1}
,"indexlen":{"u_int32_t":1,"length":1}
,"*ret)":{"input":1}
,"input":{"parameter":1}
,"parameter":{"vr_id":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1,"isis_api_get_success":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"instance":{"is-is":1,"circindex":1,"isis_api_get_error":1}
,"is-is":{"instance":1,"circuit":1}
,"circindex":{"is-is":1}
,"index":{"indexlen":1,"output":1,"found":1}
,"length":{"index":1}
,"output":{"parameters":1}
,"parameters":{"ret":1}
,"ret":{"status":1}
,"isistruthvaluetrue":{"isistruthvaluefalse":1}
,"isistruthvaluefalse":{"(default)":1}
,"(default)":{"return":1}
,"return":{"value":1}
,"isis_api_get_success":{"next":1}
,"supported":{"circuit":1}
,"found":{"specified":1}
,"specified":{"instance":1}
,"isis_api_get_error":{"next":1}
}
;Search.control.loadWordPairs(pairs);
