var pairs =
{
"rip_if_send_version_type_set":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"called":1}
,"sets":{"sending":1}
,"sending":{"rip":1}
,"rip":{"packets":1,"send":1,"version":1}
,"packets":{"interface":1}
,"interface":{"using":1,"name":1}
,"using":{"version":1}
,"version":{"control":1,"1-compatible)":1,"type":1,"ri_rip_version_2":1,"ri_rip_version_1_and_2":1,"ri_rip_version_1_compatible":1,"uni\u002Fbroadcast":1,"outside":1,"syntax":1}
,"control":{"(version":1}
,"(version":{"type)":1}
,"type)":{"function":1,"input":1}
,"called":{"following":1}
,"following":{"command":1,"ri_rip_version_1":1}
,"command":{"rip":1}
,"send":{"version":1}
,"1-compatible)":{"syntax":1}
,"syntax":{"int":1}
,"int":{"rip_if_send_version_type_set":1,"type)":1,"type":1,"retval":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1,"exist":1}
,"char":{"*ifname":1}
,"*ifname":{"int":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"parameter":1}
,"parameter":{"ifname":1}
,"ifname":{"interface":1}
,"name":{"int":1}
,"type":{"version":1,"following":1}
,"ri_rip_version_1":{"rip":1}
,"ri_rip_version_2":{"rip":1}
,"ri_rip_version_1_and_2":{"rip":1}
,"ri_rip_version_1_compatible":{"rip":1}
,"uni\u002Fbroadcast":{"address":1}
,"address":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"rip_api_set_err_version_invalid":1}
,"rip_api_set_err_version_invalid":{"version":1}
,"outside":{"range":1}
,"range":{"ri_rip_unspec":1}
,"ri_rip_unspec":{"ri_rip_version_max":1}
,"ri_rip_version_max":{"specified":1}
,"specified":{"ripd.h":1}
,"ripd.h":{"rip_api_set_err_vr_not_exist":1}
,"rip_api_set_err_vr_not_exist":{"vr_id":1}
,"exist":{"rip_api_set_success":1}
,"rip_api_set_success":{"call":1}
,"call":{"successful":1}
,"successful":{"usage":1}
,"usage":{"notes":1}
,"notes":{"command":1}
,"retval":{"retval=rip_if_send_version_type_set":1}
,"retval=rip_if_send_version_type_set":{"(ifname":1}
,"(ifname":{"ri_rip_version_1_and_2)":1}
}
;Search.control.loadWordPairs(pairs);
