var pairs =
{
"neighbor":{"g-shut":1,"bgp":1,"shut":1,"whose":1,"(a.b.c.d":1,"ipv4":1,"ipv6":1,"tag":1,"1.1.1.2":1}
,"g-shut":{"command":1,"neighbor":1,"parameters":1,"configure":1}
,"command":{"start":1,"bring":1,"graceful":1,"syntax":1,"mode":1}
,"start":{"graceful":1}
,"graceful":{"shutdown":1}
,"shutdown":{"bgp":1,"timer":1,"capability":1}
,"bgp":{"session":1,"neighbor":1,"100":1}
,"session":{"specified":1,"neighbor":1,"path":1,"again":1,"shut":1}
,"specified":{"bgp":1}
,"shut":{"down":1}
,"down":{"graceful":1,"using":1}
,"timer":{"expires":1}
,"expires":{"alternate":1}
,"alternate":{"path":1}
,"path":{"available":1,"made":1,"longer":1}
,"available":{"traffic":1,"seconds":1}
,"traffic":{"flow":1,"dropped":1}
,"flow":{"prior":1}
,"prior":{"actual":1}
,"actual":{"shutdown":1}
,"made":{"available":1}
,"seconds":{"configured":1}
,"configured":{"time":1}
,"time":{"path":1}
,"longer":{"available":1}
,"dropped":{"parameter":1}
,"parameter":{"command":1}
,"bring":{"session":1}
,"again":{"specified":1}
,"whose":{"bgp":1}
,"using":{"neighbor":1}
,"capability":{"supported":1}
,"supported":{"ibgp":1}
,"ibgp":{"sessions":1}
,"sessions":{"command":1}
,"syntax":{"neighbor":1}
,"(a.b.c.d":{"x:x":1}
,"x:x":{":x:x":1}
,":x:x":{"word)":1,"neighbor":1}
,"word)":{"g-shut":1}
,"parameters":{"a.b.c.d":1}
,"a.b.c.d":{"neighbor":1}
,"ipv4":{"address":1}
,"address":{"x:x":1,"word":1}
,"ipv6":{"address":1}
,"word":{"neighbor":1}
,"tag":{"default":1}
,"default":{"disabled":1}
,"disabled":{"command":1}
,"mode":{"router":1,"examples":1}
,"router":{"mode":1,"bgp":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"100":{"(config-router)":1}
,"(config-router)":{"neighbor":1}
,"1.1.1.2":{"g-shut":1}
}
;Search.control.loadWordPairs(pairs);
