var pairs =
{
"mstp_bridge":{"data":1,"{\u002F*housekeeping":1,"*next":1,"**pprev":1,"*cn_br":1}
,"data":{"structure":1}
,"structure":{"defined":1}
,"defined":{"mstpd\u002Fmstp_types.h":1}
,"mstpd\u002Fmstp_types.h":{"member":1}
,"member":{"definition":1}
,"definition":{"next":1,"struct":1}
,"next":{"housekeeping":1}
,"housekeeping":{"variables":1}
,"variables":{"(of":1,"*\u002Fstruct":1,"*\u002Fu_int32_t":1}
,"(of":{"type":1}
,"type":{"mstp_bridge)":1,"mstp_port)":1,"route_table)":1,"mstp_config_info)":1,"bridge":1,"whose":1,"rlist_info)":1,"mac_addr)":1,"bridge_id)":1,"bridge_id":1,"bridge_type":1,"mstp_bridge_instance)":1,"thread)":1,"mstp_protection_bmp)":1,"\u002F*list":1,"-none\u002Fring":1,"8021.d":1}
,"mstp_bridge)":{"pprev":1,"port_list":1}
,"pprev":{"housekeeping":1}
,"port_list":{"mstp":1}
,"mstp":{"port":1,"bridge":1,"protection":1}
,"port":{"related":1,"(by":1,"(cist":1,"interface":1,"index":1,"mstp_bridge_cdr_ref":1,"bridge":1,"cvlan":1,"svlan":1,"*\u002Fstruct":1,"used":1,"*\u002Fu_int16_t":1}
,"related":{"information":1,"parameters":1}
,"information":{"(of":1}
,"mstp_port)":{"vlan_table":1}
,"vlan_table":{"vlan":1}
,"vlan":{"tree":1,"instance":1,"*\u002Fbool_t":1}
,"tree":{"indexed":1}
,"indexed":{"vid":1,"port":1}
,"vid":{"(of":1,"*\u002Fstruct":1}
,"route_table)":{"config":1}
,"config":{"configuration":1,"char":1}
,"configuration":{"information":1}
,"mstp_config_info)":{"name":1}
,"name":{"bridge":1,"size":1,"[l2_bridge_name_len":1}
,"bridge":{"name":1,"type":1,"(of":1,"-id":1,"max":1,"hello":1,"forward":1,"priority":1,"cn_bridge":1,"is_default":1,"default":1,"instance":1,"topology_change_timer_cdr_ref":1,"*is":1}
,"size":{"(l2_bridge_name_len":1}
,"(l2_bridge_name_len":{"type":1}
,"whose":{"value":1,"values":1}
,"value":{"nsm_bridge_type_stp":1}
,"nsm_bridge_type_stp":{"nsm_bridge_type_stp_vlanaware":1}
,"nsm_bridge_type_stp_vlanaware":{"nsm_bridge_type_rstp":1}
,"nsm_bridge_type_rstp":{"nsm_bridge_type_rstp_vlanaware":1}
,"nsm_bridge_type_rstp_vlanaware":{"nsm_bridge_type_mstp":1}
,"nsm_bridge_type_mstp":{"nsm_bridge_type_provider_rstp":1}
,"nsm_bridge_type_provider_rstp":{"nsm_bridge_type_provider_mstp":1}
,"nsm_bridge_type_provider_mstp":{"nsm_bridge_type_ce":1}
,"nsm_bridge_type_ce":{"nsm_bridge_type_rpvst_plus":1}
,"nsm_bridge_type_rpvst_plus":{"nsm_bridge_type_backbone_rstp":1}
,"nsm_bridge_type_backbone_rstp":{"nsm_bridge_type_backbone_mstp":1}
,"nsm_bridge_type_backbone_mstp":{"vlan_list":1}
,"vlan_list":{"fid_list":1}
,"fid_list":{"list":1}
,"list":{"vlans":1,"*svid_list":1}
,"vlans":{"added":1}
,"added":{"common":1}
,"common":{"instance":1}
,"instance":{"(of":1,"map":1,"*\u002Fstruct":1,"just":1}
,"rlist_info)":{"low_port":1}
,"low_port":{"index":1,"\u002F*since":1}
,"index":{"lowest":1,"(cist":1,"instance_list":1}
,"lowest":{"numbered":1,"indexed":1}
,"numbered":{"port":1}
,"(by":{"index)":1,"ifindex)":1}
,"index)":{"bridge_addr":1}
,"bridge_addr":{"bridge\u0027s":1,"struct":1}
,"bridge\u0027s":{"mac":1}
,"mac":{"address":1,"addr":1}
,"address":{"(of":1}
,"mac_addr)":{"cist_bridge_id":1}
,"cist_bridge_id":{"cist":1,"\u002F*mstp":1}
,"cist":{"bridge":1,"level":1}
,"bridge_id)":{"cist_designated_root":1}
,"cist_designated_root":{"designated":1,"struct":1}
,"designated":{"root":1,"bridge":1}
,"root":{"type":1,"priority":1,"path":1,"port":1,"times)":1,"(configuration":1,"timer":1,"times":1}
,"-id":{"(cist":1}
,"(cist":{"root":1}
,"priority":{"vectors)":1,"(configuration":1,"diff":1,"vector":1}
,"vectors)":{"cist_reg_root":1,"cist_rcvd_reg_root":1,"cist_designated_bridge":1,"external_root_path_cost":1,"internal_root_path_cost":1,"cist_root_port_id":1,"cist_root_port_ifindex":1,"bpdu_recv_port_ifindex":1,"root_port":1,"alternate_port":1,"cist_max_age":1}
,"cist_reg_root":{"reg":1,"struct":1}
,"reg":{"root":1}
,"bridge_id":{"(cist":1,"cist_bridge_id":1,"cist_designated_root":1,"cist_reg_root":1,"cist_rcvd_reg_root":1}
,"cist_rcvd_reg_root":{"received":1,"u_int32_t":1}
,"received":{"reg":1}
,"cist_designated_bridge":{"designated":1}
,"bridge_type":{"(cist":1}
,"external_root_path_cost":{"external":1,"u_int32_t":1}
,"external":{"root":1}
,"path":{"cost":1}
,"cost":{"(cist":1,"method":1}
,"internal_root_path_cost":{"internal":1,"u_int16_t":1}
,"internal":{"root":1}
,"cist_root_port_id":{"root":1,"u_int32_t":1}
,"cist_root_port_ifindex":{"roof":1,"u_int32_t":1}
,"roof":{"port":1}
,"interface":{"index":1}
,"bpdu_recv_port_ifindex":{"receive":1,"struct":1}
,"receive":{"port":1}
,"root_port":{"root":1}
,"alternate_port":{"alternate":1}
,"alternate":{"port":1}
,"cist_max_age":{"max":1,"s_int32_t":1}
,"max":{"age":1,"hops":1}
,"age":{"(working":1,"(configuration":1,"count":1}
,"(working":{"values":1}
,"values":{"-cist":1,"-bridge":1,"rpvst_max_instances":1,"mstp_topology_none":1}
,"-cist":{"root":1}
,"times)":{"cist_message_age":1,"cist_hello_time":1,"cist_forward_delay":1,"hop_count":1,"force_version":1,"bridge_max_age":1,"bridge_hello_time":1,"bridge_forward_delay":1,"bridge_max_hops":1,"cist_bridge_priority":1,"recent_root":1,"br_all_rr_timer_cnt":1}
,"cist_message_age":{"message":1,"s_int32_t":1}
,"message":{"age":1}
,"cist_hello_time":{"hello":1,"s_int32_t":1}
,"hello":{"time":1,"timer":1}
,"time":{"(working":1,"(configuration":1,"forward":1,"ce_bridge":1}
,"cist_forward_delay":{"forward":1,"s_int32_t":1}
,"forward":{"delay":1}
,"delay":{"(working":1,"(configuration":1,"time":1}
,"hop_count":{"hop":1,"u_char":1}
,"hop":{"count":1}
,"count":{"(working":1,"ageing_time":1,"bpduguard":1,"*\u002Fu_int32_t":1}
,"force_version":{"force":1,"\u002F*configuration":1}
,"force":{"version":1}
,"version":{"(working":1}
,"bridge_max_age":{"bridge":1,"s_int32_t":1}
,"(configuration":{"values":1}
,"-bridge":{"times)":1}
,"bridge_hello_time":{"bridge":1,"s_int32_t":1}
,"bridge_forward_delay":{"bridge":1,"s_int32_t":1}
,"bridge_max_hops":{"bridge":1,"u_int32_t":1}
,"hops":{"(configuration":1}
,"cist_bridge_priority":{"bridge":1,"u_int32_t":1}
,"recent_root":{"recent":1,"\u002F*recent":1,"timer":1}
,"recent":{"root":1}
,"br_all_rr_timer_cnt":{"recent":1,"\u002F*how":1}
,"timer":{"count":1,"(of":1,"tcn_timer_cdr_ref":1,"mstpprotectionbmp":1,"fired":1,"*\u002Fha_cdr_ref":1,"*\u002F#":1}
,"ageing_time":{"long":1,"u_char":1}
,"long":{"dynamic":1}
,"dynamic":{"entries":1}
,"entries":{"kept":1}
,"kept":{"(default":1,"default":1}
,"(default":{"300secs)":1}
,"300secs)":{"learning_enabled":1}
,"learning_enabled":{"bpdu":1,"\u002F*bpdu":1}
,"bpdu":{"flag":1,"customer":1,"*\u002Fenum":1,"vlan":1}
,"flag":{"mstp_enabled":1,"mstp_brforward":1,"topology_change":1,"topology_change_detected":1,"bridge_enabled":1,"is_vlan_aware":1,"reselect":1,"ageing_time_is_fwd_delay":1,"represent":1,"new":1}
,"mstp_enabled":{"bpdu":1}
,"mstp_brforward":{"bpdu":1}
,"topology_change":{"bpdu":1}
,"topology_change_detected":{"bpdu":1}
,"bridge_enabled":{"bpdu":1}
,"is_vlan_aware":{"bpdu":1}
,"reselect":{"bpdu":1}
,"ageing_time_is_fwd_delay":{"flag":1}
,"represent":{"whether":1,"stale":1}
,"whether":{"ageing":1,"bridge":1}
,"ageing":{"time":1}
,"ce_bridge":{"flag":1}
,"cn_bridge":{"flag":1}
,"is_default":{"flag":1}
,"default":{"ha_stale":1,"300s":1}
,"ha_stale":{"flag":1}
,"stale":{"path_cost_method":1}
,"path_cost_method":{"used":1,"s_int16_t":1}
,"used":{"path":1,"support":1,"*keep":1,"rpvst_plus":1,"802.1q":1}
,"method":{"port_index":1,"short\u002Flong":1}
,"port_index":{"port":1,"ifdef":1}
,"instance_list":{"hold":1}
,"hold":{"rpvst":1,"timer":1}
,"rpvst":{"mst":1,"vlan":1}
,"mst":{"bridge":1}
,"mstp_bridge_instance)":{"max_instances":1}
,"max_instances":{"maximum":1,"s_int16_t":1}
,"maximum":{"instances":1}
,"instances":{"whose":1}
,"rpvst_max_instances":{"(if":1}
,"(if":{"rpvst)":1,"mst)":1}
,"rpvst)":{"mst_max_instances":1}
,"mst_max_instances":{"(if":1}
,"mst)":{"num_ports":1}
,"num_ports":{"number":1,"\u002F*statistics":1}
,"number":{"ports":1,"topology":1}
,"ports":{"time_last_topo_change":1}
,"time_last_topo_change":{"holds":1,"u_int32_t":1}
,"holds":{"statistics":1}
,"statistics":{"last":1,"cist":1}
,"last":{"topology":1}
,"topology":{"change":1,"changes":1,"type":1}
,"change":{"l2gp_pathcost_control":1,"timer":1}
,"l2gp_pathcost_control":{"l2gp":1}
,"l2gp":{"path-cost":1}
,"path-cost":{"control":1}
,"control":{"num_topo_changes":1}
,"num_topo_changes":{"number":1,"u_int32_t":1}
,"changes":{"total_num_topo_changes":1,"max_age_count":1}
,"total_num_topo_changes":{"total":1,"u_int32_t":1}
,"total":{"number":1}
,"max_age_count":{"max":1,"\u002F*l2":1}
,"bpduguard":{"layer":1,"s_int32_t":1}
,"layer":{"security":1}
,"security":{"related":1}
,"parameters":{"errdisable_timeout_interval":1,"errdisable_timeout_enable":1,"bpdu_filter":1,"oper_cisco":1,"admin_cisco":1,"transmit_hold_count":1,"topology_type":1,"*\u002Funsigned":1}
,"errdisable_timeout_interval":{"layer":1,"unsigned":1}
,"errdisable_timeout_enable":{"layer":1,"unsigned":1}
,"bpdu_filter":{"layer":1,"unsigned":1}
,"oper_cisco":{"layer":1,"unsigned":1}
,"admin_cisco":{"layer":1,"unsigned":1}
,"transmit_hold_count":{"layer":1,"\u002F*topology":1}
,"topology_type":{"topology":1,"struct":1}
,"mstp_topology_none":{"mstp_topology_ring":1}
,"mstp_topology_ring":{"topology_change_timer":1}
,"topology_change_timer":{"topology":1}
,"thread)":{"tcn_timer":1,"tc_initiator":1}
,"tcn_timer":{"tcn":1}
,"tcn":{"timer":1}
,"tc_initiator":{"statistics":1}
,"level":{"tc_flag":1,"tc_last_rcvd_from":1,"vlan_instance_map":1}
,"tc_flag":{"statistics":1}
,"tc_last_rcvd_from":{"statistics":1}
,"vlan_instance_map":{"rpvst":1}
,"map":{"cust_bpdu_process":1}
,"cust_bpdu_process":{"processing":1}
,"processing":{"customer":1}
,"customer":{"bpdu":1,"edge":1}
,"edge":{"port":1}
,"mstp_bridge_cdr_ref":{"cdr":1}
,"cdr":{"reference":1}
,"reference":{"mstp":1,"topology":1,"tcn":1}
,"topology_change_timer_cdr_ref":{"cdr":1}
,"tcn_timer_cdr_ref":{"cdr":1}
,"mstpprotectionbmp":{"mstp":1}
,"protection":{"bmp":1}
,"bmp":{"(of":1}
,"mstp_protection_bmp)":{"definition":1}
,"struct":{"mstp_bridge":1,"mstp_port":1,"mstp_config_info":1,"rlist_info":1,"bridge_id":1,"mstp_port*root_port":1,"mstp_port*alternate_port":1,"mstp_bridge_instance":1,"thread":1,"list":1}
,"{\u002F*housekeeping":{"variables":1}
,"*\u002Fstruct":{"mstp_bridge":1,"route_table":1,"rlist_info":1,"mac_addr":1,"bridge_id":1,"mstp_vlan_bmp":1}
,"*next":{"struct":1}
,"**pprev":{"struct":1}
,"mstp_port":{"*port_list":1}
,"*port_list":{"\u002F*vlan":1}
,"\u002F*vlan":{"tree":1,"membership":1}
,"route_table":{"*vlan_table":1}
,"*vlan_table":{"struct":1}
,"mstp_config_info":{"config":1}
,"char":{"name":1,"bpduguard":1,"errdisable_timeout_enable":1,"bpdu_filter":1,"oper_cisco":1,"admin_cisco":1,"transmit_hold_count":1}
,"[l2_bridge_name_len":{"u_int8_t":1}
,"u_int8_t":{"type":1,"spanning_tree_disable":1}
,"\u002F*list":{"vlans":1}
,"rlist_info":{"*vlan_list":1,"*fid_list":1}
,"*vlan_list":{"struct":1}
,"*fid_list":{"\u002F*index":1}
,"\u002F*index":{"lowest":1}
,"ifindex)":{"*\u002Fs_int32_t":1}
,"*\u002Fs_int32_t":{"low_port":1,"cist_max_age":1,"bridge_max_age":1,"ageing_time":1}
,"\u002F*since":{"priority":1}
,"diff":{"instance":1}
,"just":{"store":1}
,"store":{"mac":1}
,"addr":{"*i.e":1,"lowest":1}
,"*i.e":{"addr":1}
,"*is":{"calculated":1}
,"calculated":{"instance":1}
,"mac_addr":{"bridge_addr":1}
,"\u002F*mstp":{"-cist":1}
,"vector":{"sec":1}
,"sec":{"13.23.3":1,"17.17.7":1,"17.17.4":1}
,"13.23.3":{"ieee":1}
,"ieee":{"802.1s":1}
,"802.1s":{"*\u002Fstruct":1}
,"u_int32_t":{"external_root_path_cost":1,"internal_root_path_cost":1,"cist_root_port_ifindex":1,"bpdu_recv_port_ifindex":1,"cist_bridge_priority":1,"recent_root":1,"num_topo_changes":1,"total_num_topo_changes":1,"max_age_count":1,"conf_bpdu_rcvd":1,"tcn_bpdu_sent":1,"tcn_bpdu_rcvd":1,"src_mac_count":1,"similar_bpdu_cnt":1,"msg_age_timer_cnt":1,"total_src_mac_count":1}
,"u_int16_t":{"cist_root_port_id":1}
,"mstp_port*root_port":{"struct":1}
,"mstp_port*alternate_port":{"\u002F*working":1}
,"\u002F*working":{"values":1}
,"times":{"sec":1}
,"17.17.7":{"*\u002Fs_int32_t":1}
,"s_int32_t":{"cist_message_age":1,"cist_hello_time":1,"cist_forward_delay":1,"hop_count":1,"bridge_hello_time":1,"bridge_forward_delay":1,"bridge_max_hops":1,"errdisable_timeout_interval":1}
,"u_char":{"force_version":1,"learning_enabled":1,"mstp_brforward:1":1,"topology_change:1":1,"topology_change_detected:1":1,"bridge_enabled:1":1,"is_vlan_aware:1":1,"reselect:1":1,"ageing_time_is_fwd_delay:1":1,"ce_bridge:1":1,"cn_bridge:1":1,"is_default:1":1,"ha_stale:1":1}
,"\u002F*configuration":{"values-bridge":1}
,"values-bridge":{"times":1}
,"17.17.4":{"*\u002Fs_int32_t":1}
,"\u002F*recent":{"root":1}
,"*\u002Fu_int32_t":{"br_all_rr_timer_cnt":1,"cist_forward_transitions":1,"conf_bpdu_sent":1}
,"\u002F*how":{"long":1}
,"300s":{"*\u002Fs_int32_t":1}
,"\u002F*bpdu":{"flags":1,"type":1,"counters":1}
,"flags":{"-see":1}
,"-see":{"802.1d":1}
,"802.1d":{"*\u002Fu_char":1}
,"*\u002Fu_char":{"mstp_enabled:1":1}
,"mstp_enabled:1":{"u_char":1}
,"mstp_brforward:1":{"u_char":1}
,"topology_change:1":{"u_char":1}
,"topology_change_detected:1":{"u_char":1}
,"bridge_enabled:1":{"u_char":1}
,"is_vlan_aware:1":{"u_char":1}
,"reselect:1":{"u_char":1}
,"ageing_time_is_fwd_delay:1":{"u_char":1}
,"ce_bridge:1":{"(defined":1}
,"(defined":{"have_i_beb)":1,"have_i_beb":1}
,"have_i_beb)":{"u_char":1}
,"cn_bridge:1":{"endif":1}
,"endif":{"u_char":1,"\u002F*have_ha":1,"\u002F*have_rpvst_plus":1,"\u002F*only":1}
,"is_default:1":{"ifdef":1}
,"ifdef":{"have_ha":1,"have_rpvst_plus":1}
,"have_ha":{"u_char":1,"ha_cdr_ref":1}
,"ha_stale:1":{"endif":1}
,"\u002F*have_ha":{"*\u002F\u002F*used":1,"*\u002F\u002F*statistics":1}
,"*\u002F\u002F*used":{"path":1}
,"short\u002Flong":{"*\u002Fu_int8_t":1}
,"*\u002Fu_int8_t":{"path_cost_method":1}
,"s_int16_t":{"port_index":1,"num_ports":1}
,"have_rpvst_plus":{"struct":1,"\u002F*hello":1}
,"mstp_bridge_instance":{"*instance_list":1}
,"*instance_list":{"[rpvst_max_instances]":1,"[mst_max_instances]":1}
,"[rpvst_max_instances]":{"else":1}
,"else":{"struct":1}
,"[mst_max_instances]":{"endif":1}
,"\u002F*have_rpvst_plus":{"*\u002Fu_int16_t":1,"*\u002F#":1}
,"*\u002Fu_int16_t":{"max_instances":1,"svid":1,"vid_tag":1}
,"\u002F*statistics":{"*\u002Fpal_time_t":1,"*\u002Fu_int32_t":1}
,"*\u002Fpal_time_t":{"time_last_topo_change":1}
,"\u002F*l2":{"security":1}
,"*\u002Funsigned":{"char":1}
,"unsigned":{"char":1}
,"\u002F*topology":{"type":1}
,"-none\u002Fring":{"-currently":1}
,"-currently":{"used":1}
,"support":{"rrstp":1}
,"rrstp":{"*\u002Fenum":1}
,"*\u002Fenum":{"mstp_topology":1,"rpvst_bpdu_event":1,"rpvst_bpdu_type":1}
,"mstp_topology":{"topology_type":1}
,"thread":{"*topology_change_timer":1,"*tcn_timer":1,"*hold_timer":1}
,"*topology_change_timer":{"struct":1}
,"*tcn_timer":{"struct":1}
,"*hold_timer":{"\u002F*statistics":1}
,"cist_forward_transitions":{"\u002F*vlan":1}
,"membership":{"port":1}
,"cvlan":{"case":1}
,"case":{"*ce":1,"port":1}
,"*ce":{"port":1}
,"svlan":{"case":1}
,"mstp_vlan_bmp":{"vlanmemberbmp":1,"svlanmemberbmp":1}
,"vlanmemberbmp":{"\u002F*svlan":1}
,"\u002F*svlan":{"membership":1,"provider":1}
,"*keep":{"track":1}
,"track":{"logical":1}
,"logical":{"port":1}
,"svlanmemberbmp":{"\u002F*svlan":1}
,"provider":{"edge":1}
,"svid":{"u_int8_t":1}
,"spanning_tree_disable":{"(defined":1}
,"have_i_beb":{"struct":1}
,"*cn_br":{"uint32_t":1}
,"uint32_t":{"isid":1,"pip_port":1}
,"isid":{"uint32_t":1}
,"pip_port":{"\u002F*if_index":1}
,"\u002F*if_index":{"*\u002Fuint32_t":1}
,"*\u002Fuint32_t":{"bvid":1}
,"bvid":{"struct":1}
,"*svid_list":{"endif":1}
,"\u002F*only":{"used":1}
,"rpvst_plus":{"*\u002F#":1}
,"*\u002F#":{"ifdef":1,"endif":1}
,"\u002F*hello":{"timer":1}
,"fired":{"rcvd":1}
,"rcvd":{"superior":1}
,"superior":{"bpdu":1}
,"rpvst_bpdu_event":{"rpvst_event":1}
,"rpvst_event":{"\u002F*bpdu":1}
,"8021.d":{"(cist)":1}
,"(cist)":{"sstp":1}
,"sstp":{"(for":1,"bpdus":1}
,"(for":{"vlan)":1}
,"vlan)":{"*\u002Fenum":1}
,"rpvst_bpdu_type":{"rpvst_bpdu_type":1,"\u002F*set":1}
,"\u002F*set":{"flag":1}
,"new":{"bpdu":1}
,"*\u002Fbool_t":{"newinfosstp":1}
,"newinfosstp":{"\u002F*vid":1}
,"\u002F*vid":{"used":1}
,"802.1q":{"tag":1}
,"tag":{"sstp":1}
,"bpdus":{"*\u002Fu_int16_t":1}
,"vid_tag":{"int":1}
,"int":{"default_vlan":1}
,"default_vlan":{"endif":1}
,"ha_cdr_ref":{"mstp_instance_port_cdr_ref":1}
,"mstp_instance_port_cdr_ref":{"\u002F*cdr":1}
,"\u002F*cdr":{"ref":1}
,"ref":{"mstp_instance_port":1,"errdisable":1,"port_timer":1,"edge_delay":1,"forward_delay":1,"hello":1,"migrate":1,"recent_backup":1,"message_age":1,"recent_root":1,"timer":1,"hold":1}
,"mstp_instance_port":{"*\u002Fha_cdr_ref":1}
,"*\u002Fha_cdr_ref":{"errdisable_timer_cdr_ref":1,"port_timer_cdr_ref":1,"edge_delay_timer_cdr_ref":1,"forward_delay_timer_cdr_ref":1,"hello_timer_cdr_ref":1,"migrate_timer_cdr_ref":1,"recent_backup_timer_cdr_ref":1,"message_age_timer_cdr_ref":1,"recent_root_timer_cdr_ref":1,"tc_timer_cdr_ref":1,"hold_timer_cdr_ref":1}
,"errdisable_timer_cdr_ref":{"\u002F*cdr":1}
,"errdisable":{"timer":1}
,"port_timer_cdr_ref":{"\u002F*cdr":1}
,"port_timer":{"*\u002Fha_cdr_ref":1}
,"edge_delay_timer_cdr_ref":{"\u002F*cdr":1}
,"edge_delay":{"timer":1}
,"forward_delay_timer_cdr_ref":{"\u002F*cdr":1}
,"forward_delay":{"timer":1}
,"hello_timer_cdr_ref":{"\u002F*cdr":1}
,"migrate_timer_cdr_ref":{"\u002F*cdr":1}
,"migrate":{"timer":1}
,"recent_backup_timer_cdr_ref":{"\u002F*cdr":1}
,"recent_backup":{"timer":1}
,"message_age_timer_cdr_ref":{"\u002F*cdr":1}
,"message_age":{"timer":1}
,"recent_root_timer_cdr_ref":{"\u002F*cdr":1}
,"tc_timer_cdr_ref":{"\u002F*cdr":1}
,"hold_timer_cdr_ref":{"\u002F*cdr":1}
,"*\u002F\u002F*statistics":{"variables":1}
,"conf_bpdu_sent":{"u_int32_t":1}
,"conf_bpdu_rcvd":{"u_int32_t":1}
,"tcn_bpdu_sent":{"u_int32_t":1}
,"tcn_bpdu_rcvd":{"u_int32_t":1}
,"src_mac_count":{"u_int32_t":1}
,"similar_bpdu_cnt":{"u_int32_t":1}
,"msg_age_timer_cnt":{"u_int32_t":1}
,"total_src_mac_count":{"\u002F*bpdu":1}
,"counters":{"*\u002Fut_int64_t":1}
,"*\u002Fut_int64_t":{"bpdu_discards_rx":1}
,"bpdu_discards_rx":{"ut_int64_t":1}
,"ut_int64_t":{"bpdu_discards_tx":1,"bpdu_guard_events":1,"enablebpdurx_discards_count":1,"enablebpdutx_discards_count":1}
,"bpdu_discards_tx":{"ut_int64_t":1}
,"bpdu_guard_events":{"ut_int64_t":1}
,"enablebpdurx_discards_count":{"ut_int64_t":1}
}
;Search.control.loadWordPairs(pairs);
