var pairs =
{
"show":{"bgp":1}
,"bgp":{"neighbors":1,"(ipv4":1,"ipv4":1,"neighbor":1,"version":1,"state":1}
,"neighbors":{"routes":1,"command":1,"(a.b.c.d":1,"10.10.10.2":1}
,"routes":{"command":1,"learned":1,"show":1,"parameters":1,"bgp":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"accepted":1}
,"accepted":{"routes":1,"prefixes":1}
,"learned":{"neighbors":1}
,"syntax":{"show":1}
,"(a.b.c.d":{"x:x":1}
,"x:x":{":x:x)":1,":x:x":1}
,":x:x)":{"routes":1}
,"(ipv4":{"ipv6)":1}
,"ipv6)":{"(unicast":1}
,"(unicast":{"multicast":1,"multicast)":1}
,"multicast":{"neighbors":1,"multicast":1,"prefixes":1}
,"ipv4":{"(unicast":1,"address":1,"ipv4":1,"addresses":1,"unicast":1}
,"multicast)":{"neighbors":1}
,"parameters":{"a.b.c.d":1}
,"a.b.c.d":{"ipv4":1}
,"address":{"x:x":1,"ipv4":1,"family":1}
,":x:x":{"ipv6":1}
,"ipv6":{"address":1,"ipv6":1,"addresses":1,"unicast":1}
,"addresses":{"ipv6":1,"unicast":1}
,"unicast":{"unicast":1,"prefixes":1,"advertised":1,"community":1}
,"prefixes":{"multicast":1,"command":1,"announced":1}
,"mode":{"privileged":1,"exec":1,"example":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"example":{"following":1}
,"following":{"output":1}
,"output":{"displays":1}
,"displays":{"detailed":1}
,"detailed":{"information":1}
,"information":{"neighbor":1}
,"neighbor":{"show":1,"fe80":1,"capabilities":1,"(both)":1}
,"10.10.10.2":{"routes":1}
,"fe80":{":203:47ff:feb0:d72b":1}
,":203:47ff:feb0:d72b":{"remote":1}
,"remote":{"local":1,"router":1}
,"local":{"internal":1}
,"internal":{"link":1}
,"link":{"bgp":1}
,"version":{"remote":1}
,"router":{"10.10.10.50":1}
,"10.10.10.50":{"bgp":1}
,"state":{"=established":1}
,"=established":{"00:02:01":1}
,"00:02:01":{"last":1}
,"last":{"read":1}
,"read":{"00:00:01":1}
,"00:00:01":{"hold":1}
,"hold":{"time":1}
,"time":{"180":1,"advertisement":1}
,"180":{"keepalive":1}
,"keepalive":{"interval":1}
,"interval":{"seconds":1}
,"seconds":{"neighbor":1,"address":1}
,"capabilities":{"route":1}
,"route":{"refresh":1}
,"refresh":{"advertised":1,"request":1}
,"advertised":{"received":1}
,"received":{"(old":1,"address":1,"received":1,"messages":1,"sent":1}
,"(old":{"new)":1}
,"new)":{"address":1}
,"family":{"ipv4":1,"ipv6":1}
,"messages":{"notifications":1}
,"notifications":{"queue":1}
,"queue":{"sent":1,"route":1}
,"sent":{"messages":1,"minimum":1,"neighbor":1}
,"request":{"received":1}
,"minimum":{"time":1}
,"advertisement":{"runs":1}
,"runs":{"seconds":1}
,"community":{"attribute":1}
,"attribute":{"sent":1}
,"(both)":{"accepted":1}
,"announced":{"prefixes":1}
}
;Search.control.loadWordPairs(pairs);
