var pairs =
{
"one-to-one":{"backup":1,"protection":1}
,"backup":{"scenario":1,"frr":1,"lsp":1,"path":1,"ftn":1,"ilm":1}
,"scenario":{"section":1,"lsp":1}
,"section":{"provides":1}
,"provides":{"overview":1}
,"overview":{"events":1}
,"events":{"actions":1}
,"actions":{"taken":1}
,"taken":{"modules":1}
,"modules":{"support":1}
,"support":{"frr":1}
,"frr":{"procedures":1,"mechanism":1,"object":1}
,"procedures":{"using":1}
,"using":{"one-to-one":1,"related":1,"attribute":1,"fast":1}
,"lsp":{"configured":1,"using":1,"created":1,"attributes":1,"contain":1,"signal":1,"downstream":1,"signaling":1,"backup":1,"operational":1,"transit":1,"event":1,"failure":1}
,"configured":{"ingress":1}
,"ingress":{"node":1,"adds":1}
,"node":{"using":1,"instances":1,"path":1,"may":1}
,"related":{"fast":1,"one-to-one":1}
,"fast":{"reroute":1}
,"reroute":{"commands":1,"(frr)":1}
,"commands":{"fast-reroute":1,"related":1}
,"fast-reroute":{"protection":1}
,"protection":{"command":1,"method":1}
,"command":{"used":1,"reference":1,"details":1}
,"used":{"designate":1,"downstream":1}
,"designate":{"one-to-one":1}
,"mechanism":{"desired":1}
,"desired":{"operator":1,"attributes":1}
,"operator":{"desired":1}
,"attributes":{"lsp":1,"assigned":1,"protected":1,"signaled":1,"signaling":1}
,"attribute":{"commands":1}
,"method":{"rsvp-te":1}
,"rsvp-te":{"command":1}
,"reference":{"one-to-one":1}
,"details":{"attributes":1}
,"assigned":{"backup":1}
,"created":{"attributes":1,"protected":1}
,"protected":{"lsp":1,"detour":1}
,"signaled":{"detour":1,"protected":1}
,"detour":{"lsps":1,"lsp":1}
,"lsps":{"signaled":1,"ingress":1,"may":1,"waiting":1}
,"(frr)":{"object":1}
,"object":{"two":1,"used":1,"changes":1}
,"two":{"sessions":1}
,"sessions":{"created":1}
,"instances":{"stored":1}
,"stored":{"trunk":1}
,"trunk":{"node":1}
,"path":{"messages":1,"protected":1,"computation":1,"primary":1}
,"messages":{"protected":1}
,"contain":{"frr":1}
,"downstream":{"nodes":1,"failure":1}
,"nodes":{"along":1,"wait":1,"links":1,"add":1}
,"along":{"path":1}
,"signal":{"local":1}
,"local":{"detours":1}
,"detours":{"detour":1}
,"may":{"merge":1,"recompute":1}
,"merge":{"protected":1}
,"failure":{"frr":1,"corresponding":1}
,"changes":{"plr":1}
,"plr":{"propagate":1,"gather":1,"sends":1}
,"propagate":{"new":1}
,"new":{"attributes":1,"optimal":1}
,"signaling":{"detour":1}
,"wait":{"resv":1}
,"resv":{"message":1}
,"message":{"protected":1,"ingress":1}
,"waiting":{"required":1}
,"required":{"plr":1}
,"gather":{"information":1}
,"information":{"nodes":1}
,"links":{"traversed":1}
,"traversed":{"protected":1}
,"computation":{"once":1}
,"once":{"detour":1}
,"operational":{"ingress":1}
,"adds":{"backup":1}
,"ftn":{"entry":1}
,"entry":{"primary":1,"created":1,"ilm":1}
,"primary":{"ftn":1,"lsp":1}
,"transit":{"nodes":1}
,"add":{"backup":1}
,"ilm":{"entry":1}
,"event":{"primary":1}
,"corresponding":{"secondary":1}
,"secondary":{"(ftn":1}
,"(ftn":{"ilm)":1}
,"ilm)":{"entries":1}
,"entries":{"installed":1}
,"installed":{"mpls":1}
,"mpls":{"forwarder":1}
,"forwarder":{"nsm":1}
,"nsm":{"plr":1}
,"sends":{"error":1}
,"error":{"message":1}
,"recompute":{"new":1}
,"optimal":{"path":1}
}
;Search.control.loadWordPairs(pairs);
