var pairs =
{
"bfd":{"support":1,"virtual":1,"enhanced":1,"control":1}
,"support":{"vccv":1,"bfd":1}
,"vccv":{"support":1,"mpls":1}
,"virtual":{"circuit":1}
,"circuit":{"connectivity":1}
,"connectivity":{"verification":1}
,"verification":{"(vccv)":1}
,"(vccv)":{"sessions":1}
,"sessions":{"bfd":1,"session":1}
,"enhanced":{"handle":1}
,"handle":{"following":1}
,"following":{"capabilities":1}
,"capabilities":{"creating":1}
,"creating":{"new":1}
,"new":{"trees":1}
,"trees":{"bfd-vccv":1}
,"bfd-vccv":{"sessions":1}
,"session":{"forwarding":1}
,"forwarding":{"entries":1}
,"entries":{"sending":1}
,"sending":{"bfd":1}
,"control":{"packets":1}
,"packets":{"related":1,"lsp":1}
,"related":{"vccv":1}
,"mpls":{"forwarder":1}
,"forwarder":{"send":1}
,"send":{"packets":1}
,"lsp":{"necessary":1}
,"necessary":{"label":1}
,"label":{"encapsulation":1}
}
;Search.control.loadWordPairs(pairs);
