var pairs =
{
"show":{"trill":1}
,"trill":{"esadi-instance":1,"esadi":1}
,"esadi-instance":{"command":1,"(vlan":1,"vlan":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"instance":1,"vlan":1}
,"instance":{"information":1}
,"information":{"trill":1}
,"esadi":{"command":1}
,"syntax":{"show":1}
,"(vlan":{"<1-4094>":1}
,"<1-4094>":{"parameters":1,"display":1}
,"parameters":{"<1-4094>":1}
,"vlan":{"identifier":1,"esadi-priority":1}
,"identifier":{"command":1}
,"mode":{"exec":1,"privilege":1,"examples":1}
,"exec":{"mode":1}
,"privilege":{"exec":1}
,"examples":{"show":1}
,"esadi-priority":{"csnp-timer":1}
,"csnp-timer":{"state":1}
,"state":{"confidence":1}
,"confidence":{"drb-system-id":1}
,"drb-system-id":{"------------------------------------------------------------------------------123":1}
,"------------------------------------------------------------------------------123":{"300":1}
}
;Search.control.loadWordPairs(pairs);
