var pairs =
{
"rsvp_snmp_set_tn_role":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"succeeds":1}
,"sets":{"role":1}
,"role":{"tunnel":1,"constant":1,"ingress":1,"valid":1}
,"tunnel":{"entry\u002Finstance":1,"index":1,"instance":1}
,"entry\u002Finstance":{"represents":1}
,"represents":{"syntax":1}
,"syntax":{"u_int32_t":1}
,"u_int32_t":{"rsvp_snmp_set_tn_role":1,"*inst_ix":1,"role)":1}
,"(u_int32_t":{"*tn_ix":1}
,"*tn_ix":{"u_int32_t":1}
,"*inst_ix":{"struct":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"*ing_id":1,"*eg_id":1}
,"*ing_id":{"struct":1}
,"*eg_id":{"u_int32_t":1}
,"role)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"tn_ix":1,"none":1}
,"tn_ix":{"tunnel":1}
,"index":{"inst_ix":1,"ing_id":1}
,"inst_ix":{"instance":1}
,"instance":{"index":1,"found":1}
,"ing_id":{"ingress":1}
,"ingress":{"lsr":1,"role":1}
,"lsr":{"identifier":1}
,"identifier":{"eg_id":1,"role":1}
,"eg_id":{"egress":1}
,"egress":{"lsr":1}
,"constant":{"session_role_type":1}
,"session_role_type":{"enum":1}
,"enum":{"rsvpd\u002Frsvpd.h":1}
,"rsvpd\u002Frsvpd.h":{"rsvp_snmp_tn_role_ingress":1}
,"rsvp_snmp_tn_role_ingress":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"rsvp_api_set_success":1,"tunnel":1}
,"rsvp_api_set_success":{"function":1}
,"succeeds":{"rsvp_api_set_error":1}
,"rsvp_api_set_error":{"trunk":1}
,"trunk":{"owner":1}
,"owner":{"snmp":1}
,"snmp":{"session":1}
,"session":{"role":1}
,"valid":{"value":1}
}
;Search.control.loadWordPairs(pairs);
