var pairs =
{
"trill_set_rbridgebase_nickname_priority":{"call":1,"(u_int32_t":1}
,"call":{"rbridge\u0027s":1}
,"rbridge\u0027s":{"priority":1}
,"priority":{"hold":1,"output":1}
,"hold":{"nickname":1}
,"nickname":{"syntax":1,"int":1,"nickname":1,"rbridge":1,"trill_api_set_error":1,"found":1}
,"syntax":{"int":1}
,"int":{"trill_set_rbridgebase_nickname_priority":1,"val)":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"integer":1}
,"u_int32_t":{"instance":1}
,"instance":{"u_int16_t":1,"integer":1,"nickname":1}
,"u_int16_t":{"nickname":1}
,"val)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"integer":{"contains":1}
,"contains":{"trill":1}
,"trill":{"identifier":1,"instance":1}
,"identifier":{"instance":1}
,"rbridge":{"val":1}
,"val":{"rbridge\u0027s":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"trill_api_set_success":1}
,"trill_api_set_success":{"valid":1}
,"valid":{"instance":1}
,"trill_api_set_error":{"valid":1}
}
;Search.control.loadWordPairs(pairs);
