var pairs =
{
"ptp_bridge_add_port":{"function":1,"(char":1}
,"function":{"adds":1}
,"adds":{"clock":1}
,"clock":{"port":1}
,"port":{"bridge":1,"added":1}
,"bridge":{"syntax":1,"ifp":1,"interface":1}
,"syntax":{"include":1}
,"include":{"ptpd\u002Fptp_bridge.h":1}
,"ptpd\u002Fptp_bridge.h":{"s_int16_t":1}
,"s_int16_t":{"ptp_bridge_add_port":1}
,"(char":{"*bridge_name":1}
,"*bridge_name":{"struct":1}
,"struct":{"interface":1}
,"interface":{"*ifp)":1,"output":1,"null":1}
,"*ifp)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bridge_name":1,"none":1}
,"bridge_name":{"name":1}
,"name":{"bridge":1}
,"ifp":{"pointer":1}
,"pointer":{"interface":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"result_ok":1}
,"result_ok":{"port":1}
,"added":{"result_error":1}
,"result_error":{"bridge":1}
,"null":{"ptp":1}
,"ptp":{"associated":1}
,"associated":{"interface":1}
}
;Search.control.loadWordPairs(pairs);
