var pairs =
{
"nsm_mpls_set_xc_lspid":{"function":1,"(struct":1}
,"function":{"sets":1,"succeeds":1,"fails":1}
,"sets":{"label":1}
,"label":{"switched":1}
,"switched":{"path":1}
,"path":{"given":1}
,"given":{"cross":1}
,"cross":{"connect":1}
,"connect":{"syntax":1,"index":1}
,"syntax":{"u_int32_t":1}
,"u_int32_t":{"nsm_mpls_set_xc_lspid":1,"xc_ix":1,"inseg_ix":1,"outseg_ix)":1}
,"(struct":{"nsm_master":1}
,"nsm_master":{"*nm":1}
,"*nm":{"u_int32_t":1}
,"xc_ix":{"u_int32_t":1,"cross":1}
,"inseg_ix":{"u_int32_t":1,"insegment":1}
,"outseg_ix)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"nsm":1,"none":1}
,"nsm":{"master":1}
,"master":{"outseg_ix":1}
,"outseg_ix":{"outsegment":1}
,"outsegment":{"index":1}
,"index":{"inseg_ix":1,"xc_ix":1,"output":1}
,"insegment":{"index":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_api_set_success":1}
,"nsm_api_set_success":{"function":1}
,"succeeds":{"nsm_api_set_error":1}
,"nsm_api_set_error":{"function":1}
}
;Search.control.loadWordPairs(pairs);
