var pairs =
{
"bridge":{"spbv":1,"(<1-32>":1,"identifier":1,"bvlan":1}
,"spbv":{"bvlan":1}
,"bvlan":{"spvid":1,"<1-4094>":1,"base":1}
,"spvid":{"command":1,"base":1,"<1-4094>":1,"shortest":1}
,"command":{"map":1,"unmap":1,"syntax":1,"mode":1}
,"map":{"shortest":1}
,"shortest":{"path":1}
,"path":{"vlan":1}
,"vlan":{"identifier":1,"form":1,"command":1,"<1-4094>":1}
,"identifier":{"(spvid)":1,"backbone":1,"spvid":1,"command":1}
,"(spvid)":{"base":1}
,"base":{"vlan":1}
,"form":{"command":1}
,"unmap":{"spvid":1}
,"syntax":{"bridge":1}
,"(<1-32>":{"backbone)":1}
,"backbone)":{"spbv":1}
,"<1-4094>":{"spvid":1,"bridge":1,"parameters":1,"base":1,"shortest":1}
,"parameters":{"<1-32>":1}
,"<1-32>":{"bridge":1}
,"backbone":{"backbone":1,"bridge":1}
,"mode":{"spb":1,"example":1}
,"spb":{"mode":1,"configuration":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"spb":1}
,"configuration":{"(config-spb)":1}
,"(config-spb)":{"bridge":1}
}
;Search.control.loadWordPairs(pairs);
