var pairs =
{
"trill_get_next_rbridgebase_port_desigvlan":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"vlan-id":1}
,"vlan-id":{"vlan":1,"return":1}
,"vlan":{"used":1}
,"used":{"link":1}
,"link":{"trill":1}
,"trill":{"frames":1,"identifier":1,"instance":1}
,"frames":{"syntax":1}
,"syntax":{"int":1}
,"int":{"trill_get_next_rbridgebase_port_desigvlan":1,"indexlen":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"integer":1}
,"u_int32_t":{"*instance":1,"*baseport":1,"*ret)":1}
,"*instance":{"u_int32_t":1}
,"*baseport":{"int":1}
,"indexlen":{"u_int32_t":1,"length":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"ret":1}
,"integer":{"contains":1}
,"contains":{"trill":1,"rbridge":1}
,"identifier":{"instance":1}
,"instance":{"integer":1,"baseport":1,"port":1}
,"baseport":{"port":1}
,"port":{"number":1}
,"number":{"entry":1,"trill_api_get_error":1,"found":1}
,"entry":{"contains":1}
,"rbridge":{"management":1}
,"management":{"information":1}
,"information":{"indexlen":1}
,"length":{"index":1}
,"index":{"output":1}
,"output":{"parameters":1}
,"ret":{"pointer":1}
,"pointer":{"vlan-id":1}
,"return":{"value":1}
,"value":{"trill_api_get_success":1}
,"trill_api_get_success":{"valid":1}
,"valid":{"instance":1}
,"trill_api_get_error":{"valid":1}
}
;Search.control.loadWordPairs(pairs);
