var pairs =
{
"normal":{"restart":1,"conditions":1}
,"restart":{"normal":1,"restarting":1,"state":1}
,"conditions":{"ospf":1}
,"ospf":{"routers":1}
,"routers":{"automatically":1,"continue":1}
,"automatically":{"route":1}
,"route":{"around":1}
,"around":{"restarting":1}
,"restarting":{"router":1,"particularly":1}
,"router":{"graceful":1,"announces":1,"adjacent":1,"control":1,"back":1,"+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+":1}
,"graceful":{"restart":1,"restarting":1}
,"announces":{"entering":1}
,"entering":{"restart":1}
,"state":{"grace":1,"layout":1}
,"grace":{"linked-state":1,"lsa":1}
,"linked-state":{"advertisement":1}
,"advertisement":{"(lsa)":1}
,"(lsa)":{"neighboring":1}
,"neighboring":{"routers":1}
,"continue":{"announce":1}
,"announce":{"restarting":1}
,"adjacent":{"router":1}
,"control":{"back":1}
,"back":{"online":1}
,"online":{"router":1,"time":1}
,"time":{"lost":1,"prepare":1}
,"lost":{"reconstructing":1}
,"reconstructing":{"forwarding":1}
,"forwarding":{"tables":1}
,"tables":{"across":1,"restartable":1}
,"across":{"topology":1}
,"topology":{"graceful":1}
,"particularly":{"suited":1}
,"suited":{"planned":1}
,"planned":{"network":1}
,"network":{"outages":1,"little":1}
,"outages":{"work":1,"generally":1}
,"work":{"unplanned":1}
,"unplanned":{"outages":1}
,"generally":{"network":1}
,"little":{"time":1}
,"prepare":{"save":1}
,"save":{"tables":1}
,"restartable":{"state":1}
,"layout":{"grace":1}
,"lsa":{"contains":1}
,"contains":{"several":1}
,"several":{"fields":1}
,"fields":{"+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+":1}
,"+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+":{"age":1,"+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+":1,"advertising":1,"sequence":1,"checksum":1,"+-tlvs":1}
,"age":{"options":1}
,"options":{"+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+":1}
,"advertising":{"router":1}
,"sequence":{"number":1}
,"number":{"+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+":1}
,"checksum":{"length":1}
,"length":{"+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+":1}
}
;Search.control.loadWordPairs(pairs);
