var pairs =
{
"authentication":{"send-only":1,"mode":1,"key-chain":1,"smoothly":1,"inserted":1}
,"send-only":{"command":1,"option":1,"feature":1,"(level-1":1,"level-1":1}
,"command":{"send-only":1,"configuring":1,"enable":1,"disable":1,"unset":1,"syntax":1,"mode":1}
,"option":{"instance":1,"applies":1,"command":1,"disabled":1}
,"instance":{"level":1}
,"level":{"command":1,"specified":1}
,"configuring":{"authentication":1}
,"mode":{"authentication":1,"key":1,"router":1,"examples":1}
,"key-chain":{"implementation":1,"level-1":1,"level-2":1}
,"implementation":{"authentication":1}
,"smoothly":{"routers":1}
,"routers":{"time":1,"communicate":1}
,"time":{"keys":1}
,"keys":{"configured":1}
,"configured":{"router":1,"command":1,"send-only":1}
,"router":{"authentication":1,"specify":1,"mode":1,"isis":1}
,"inserted":{"packets":1}
,"packets":{"sent":1,"received":1}
,"sent":{"checked":1}
,"checked":{"packets":1}
,"received":{"routers":1}
,"communicate":{"configured":1}
,"enable":{"authentication":1}
,"key":{"chain":1}
,"chain":{"router":1}
,"specify":{"authentication":1}
,"disable":{"send-only":1}
,"feature":{"neither":1,"applies":1}
,"neither":{"level-1":1}
,"level-1":{"level-2":1,"specify":1,"pdus":1,"(config-router)":1}
,"level-2":{"keyword":1,"authentication":1,"parameters":1,"specify":1,"pdus":1}
,"keyword":{"configured":1}
,"applies":{"levels.the":1,"levels":1}
,"levels.the":{"send-only":1}
,"levels":{"level":1}
,"specified":{"parameter":1}
,"parameter":{"command":1}
,"unset":{"send-only":1}
,"syntax":{"authentication":1}
,"(level-1":{"level-2":1}
,"parameters":{"level-1":1}
,"pdus":{"level-2":1,"default":1}
,"default":{"option":1,"command":1}
,"disabled":{"default":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"isis":{"(config-router)":1}
,"(config-router)":{"authentication":1}
}
;Search.control.loadWordPairs(pairs);
