var pairs =
{
"pim6_api_vif_state_refresh_originate_interval_set":{"function":1,"(u_int32_t":1}
,"function":{"configures":1,"executes":1}
,"configures":{"state":1}
,"state":{"refresh":1}
,"refresh":{"originates":1,"interval":1}
,"originates":{"interval":1}
,"interval":{"pim-dm":1,"seconds":1}
,"pim-dm":{"syntax":1}
,"syntax":{"int":1}
,"int":{"pim6_api_vif_state_refresh_originate_interval_set":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1}
,"char":{"*ifname":1}
,"*ifname":{"u_int16_t":1}
,"u_int16_t":{"sec)":1}
,"sec)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"ifname":1}
,"ifname":{"name":1}
,"name":{"interface":1}
,"interface":{"sec":1,"found":1}
,"sec":{"state":1}
,"seconds":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"pim_api_set_err_wrong_value":1,"given":1}
,"pim_api_set_err_wrong_value":{"invalid":1}
,"invalid":{"value":1}
,"given":{"pim_api_set_err_wrong_vrf":1}
,"pim_api_set_err_wrong_vrf":{"pim":1}
,"pim":{"vrf":1}
,"vrf":{"interface":1}
,"found":{"pim_api_set_success":1}
,"pim_api_set_success":{"function":1}
,"executes":{"properly":1}
}
;Search.control.loadWordPairs(pairs);
