var pairs =
{
"ospf_if_conf_ldp_igp_sync":{"function":1,"(u_int32_t":1}
,"function":{"enables":1}
,"enables":{"ldp-ospf":1}
,"ldp-ospf":{"synchronization":1}
,"synchronization":{"current":1,"enabled":1,"output":1,"parameters":1,"re-configured":1}
,"current":{"interface":1}
,"interface":{"syntax":1,"*ifp":1,"ldp-ospf":1,"exist":1}
,"syntax":{"int":1}
,"int":{"ospf_if_conf_ldp_igp_sync":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"struct":1,"virtual":1}
,"struct":{"interface":1}
,"*ifp":{"u_int32_t":1}
,"u_int32_t":{"holddown_timer)":1}
,"holddown_timer)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1,"allocate":1,"ospf_api_set_err_if_sync_exist":1}
,"virtual":{"router":1}
,"router":{"ifp":1}
,"ifp":{"pointer":1}
,"pointer":{"interface":1}
,"enabled":{"holddown":1}
,"holddown":{"timer":1}
,"timer":{"sets":1,"synchronization":1,"ospf_api_set_error":1}
,"sets":{"hold-down":1}
,"hold-down":{"timer":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"ospf_api_set_success":1}
,"ospf_api_set_success":{"call":1}
,"call":{"successful":1,"failed":1}
,"successful":{"ospf_api_set_err_vr_not_exist":1}
,"ospf_api_set_err_vr_not_exist":{"ospf":1}
,"ospf":{"master":1}
,"master":{"present":1}
,"present":{"ospf_api_set_err_if_not_exist":1}
,"ospf_api_set_err_if_not_exist":{"interface":1}
,"exist":{"ospf_api_set_err_if_sync_not_exist":1}
,"ospf_api_set_err_if_sync_not_exist":{"call":1}
,"failed":{"retrieve":1}
,"retrieve":{"existing":1}
,"existing":{"synchronization":1}
,"allocate":{"memory":1}
,"memory":{"new":1}
,"new":{"parameters":1}
,"ospf_api_set_err_if_sync_exist":{"synchronization":1}
,"re-configured":{"hold-down":1}
,"ospf_api_set_error":{"ldp":1}
,"ldp":{"session":1}
,"session":{"state":1}
,"state":{"query":1}
,"query":{"successfully":1}
,"successfully":{"sent":1}
}
;Search.control.loadWordPairs(pairs);
