var pairs =
{
"internal":{"architecture":1}
,"architecture":{"mpls":1}
,"mpls":{"forwarder":1,"labels":1,"vrf":1}
,"forwarder":{"processes":1,"handles":1,"made":1}
,"processes":{"incoming":1}
,"incoming":{"packets":1,"interface":1}
,"packets":{"network":1,"interface":1,"based":1,"exceeding":1,"(ip":1,"label":1,"dropped":1}
,"network":{"interfaces":1}
,"interfaces":{"primary":1,"table":1,"may":1,"tables":1,"system":1,"flexibility":1}
,"primary":{"function":1}
,"function":{"forward":1}
,"forward":{"traffic":1}
,"traffic":{"data":1}
,"data":{"paths":1}
,"paths":{"created":1}
,"created":{"label":1,"per":1,"vrf":1}
,"label":{"distribution":1,"map)":1,"space":1}
,"distribution":{"protocols":1}
,"protocols":{"ldp":1}
,"ldp":{"rsvp-te":1}
,"rsvp-te":{"mpls":1}
,"handles":{"following":1}
,"following":{"functions":1,"separate":1}
,"functions":{"receiving":1}
,"receiving":{"ip\u002Fmpls":1,"layer-2":1}
,"ip\u002Fmpls":{"unicast":1}
,"unicast":{"packets":1}
,"interface":{"queues":1,"mpls":1,"bound":1,"may":1,"contains":1,"enabled":1}
,"queues":{"receiving":1,"forwarding":1}
,"layer-2":{"packets":1,"frames":1}
,"forwarding":{"labeled\u002Funlabeled":1}
,"labeled\u002Funlabeled":{"unicast":1,"layer-2":1}
,"based":{"address":1,"incoming":1}
,"address":{"mpls":1}
,"labels":{"forwarding":1,"fragmenting":1}
,"frames":{"based":1}
,"fragmenting":{"packets":1}
,"exceeding":{"mtu":1}
,"mtu":{"size":1}
,"size":{"outgoing":1}
,"outgoing":{"interface":1}
,"made":{"following":1}
,"separate":{"entities":1}
,"entities":{"global":1}
,"global":{"ftn":1}
,"ftn":{"(fec":1,"table":1}
,"(fec":{"next-hop-label-forwarding-entry)":1}
,"next-hop-label-forwarding-entry)":{"table":1}
,"table":{"kernel":1,"processing":1,"multiple":1,"interface":1,"ilm":1,"created":1,"interfaces":1}
,"kernel":{"interfaces":1,"interface":1}
,"processing":{"non-labeled":1}
,"non-labeled":{"packets":1}
,"(ip":{"packets)":1}
,"packets)":{"kernel":1}
,"bound":{"vrf":1}
,"vrf":{"table":1,"tables":1,"interface":1,"labeled":1}
,"multiple":{"kernel":1}
,"may":{"global":1,"table":1,"vrf":1}
,"ilm":{"(incoming":1,"table":1}
,"(incoming":{"label":1}
,"map)":{"tables":1}
,"tables":{"kernel":1,"process":1}
,"process":{"labeled":1,"non-labeled":1}
,"labeled":{"packets":1}
,"space":{"interface":1}
,"contains":{"positive":1}
,"positive":{"integer":1}
,"integer":{"ilm":1}
,"per":{"label-space":1}
,"label-space":{"used":1,"ilm":1}
,"used":{"therefore":1}
,"therefore":{"interfaces":1}
,"system":{"using":1}
,"using":{"label-space":1}
,"flexibility":{"enabled":1}
,"enabled":{"either":1,"mpls":1}
,"either":{"mpls":1}
}
;Search.control.loadWordPairs(pairs);
