var pairs =
{
"isis_get_sys_max_lsp_gen_interval":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"maximum":1}
,"maximum":{"interval":1}
,"interval":{"seconds":1,"generated":1}
,"seconds":{"generated":1}
,"generated":{"lsps":1}
,"lsps":{"instance":1,"900":1}
,"instance":{"is-is":1,"u_int32_t":1,"output":1,"found":1}
,"is-is":{"protocol":1,"instance":1}
,"protocol":{"syntax":1}
,"syntax":{"int":1}
,"int":{"isis_get_sys_max_lsp_gen_interval":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1,"instance":1}
,"u_int32_t":{"instance":1,"*ret)":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"ret":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1,"return":1}
,"value":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"output":{"parameters":1}
,"ret":{"maximum":1}
,"900":{"returned":1}
,"returned":{"default":1}
,"return":{"values":1}
,"values":{"isis_api_get_success":1}
,"isis_api_get_success":{"instance":1}
,"found":{"isis_api_get_error":1}
,"isis_api_get_error":{"instance":1}
}
;Search.control.loadWordPairs(pairs);
