var pairs =
{
"isis_clear_ip_isis_route":{"syntax":1,"(u_int32_t":1}
,"syntax":{"int":1}
,"int":{"isis_clear_ip_isis_route":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1,"tag":1}
,"char":{"*tag":1,"*str)":1}
,"*tag":{"char":1}
,"*str)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"tag":{"is-is":1,"*str":1}
,"is-is":{"instance":1}
,"instance":{"area":1,"exist":1}
,"area":{"tag":1}
,"*str":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"isis_api_set_err_vr_not_exist":1}
,"isis_api_set_err_vr_not_exist":{"exist":1}
,"exist":{"isis_api_set_err_invalid_value":1,"isis_api_set_error":1}
,"isis_api_set_err_invalid_value":{"given":1}
,"given":{"interval":1}
,"interval":{"outside":1}
,"outside":{"range":1}
,"range":{"isis_api_set_err_instance_not_exist":1}
,"isis_api_set_err_instance_not_exist":{"isis":1}
,"isis":{"instance":1}
,"isis_api_set_error":{"ldp":1}
,"ldp":{"session":1}
,"session":{"state":1}
,"state":{"query":1}
,"query":{"successfully":1}
,"successfully":{"sent":1}
,"sent":{"isis_api_set_success":1}
,"isis_api_set_success":{"call":1}
,"call":{"successful":1}
}
;Search.control.loadWordPairs(pairs);
