var pairs =
{
"mpls-tp":{"ring":1}
,"ring":{"protection":1,"topologies":1}
,"protection":{"switching":1,"mechanism":1}
,"switching":{"mpls-tp":1,"(mrps)":1,"statistical":1}
,"(mrps)":{"built":1}
,"built":{"ring":1}
,"topologies":{"similar":1,"synchronous":1}
,"similar":{"topologies":1}
,"synchronous":{"optical":1,"digital":1}
,"optical":{"networking":1}
,"networking":{"(sonet)":1}
,"(sonet)":{"synchronous":1}
,"digital":{"hierarchy":1}
,"hierarchy":{"(sdh)":1}
,"(sdh)":{"networks.the":1}
,"networks.the":{"mrps":1}
,"mrps":{"topology":1}
,"topology":{"provides":1}
,"provides":{"effective":1}
,"effective":{"fast":1}
,"fast":{"recovery":1}
,"recovery":{"time":1}
,"time":{"efficient":1}
,"efficient":{"protection":1}
,"mechanism":{"high":1}
,"high":{"bandwidth":1}
,"bandwidth":{"utilization":1}
,"utilization":{"using":1}
,"using":{"packet":1}
,"packet":{"switching":1}
,"statistical":{"multiplexing":1}
}
;Search.control.loadWordPairs(pairs);
