var pairs =
{
"admin-group":{"command":1,"name":1,"ipi":1}
,"command":{"create":1,"adds":1,"disable":1,"command":1,"unavailable":1,"syntax":1,"mode":1}
,"create":{"administrative":1}
,"administrative":{"group":1,"groups":1}
,"group":{"used":1,"name":1,"previously":1,"created":1,"interface":1,"added":1,"ipi":1}
,"used":{"links":1,"interface":1}
,"links":{"link":1}
,"link":{"member":1,"interface":1}
,"member":{"administrative":1}
,"groups":{"used":1,"per":1}
,"interface":{"mode":1,"group":1,"added":1,"eth0":1}
,"mode":{"command":1,"interfaces":1,"parameter":1,"interface":1,"example":1}
,"adds":{"link":1}
,"name":{"name":1,"group":1,"admin-group":1,"parameters":1,"specify":1,"admin":1}
,"previously":{"configured":1}
,"configured":{"multiple":1}
,"multiple":{"groups":1}
,"per":{"interface":1}
,"created":{"configure":1}
,"configure":{"mode":1,"terminal":1}
,"interfaces":{"added":1}
,"added":{"group":1,"command":1}
,"parameter":{"command":1}
,"disable":{"command":1}
,"unavailable":{"running":1}
,"running":{"imish":1}
,"imish":{"command":1}
,"syntax":{"admin-group":1}
,"parameters":{"name":1}
,"specify":{"name":1}
,"admin":{"group":1}
,"example":{"following":1,"eth0":1}
,"following":{"example":1}
,"eth0":{"interface":1,"(config-if)":1}
,"ipi":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"(config-if)":{"admin-group":1}
}
;Search.control.loadWordPairs(pairs);
