var pairs =
{
"fast":{"reroute":1}
,"reroute":{"commands":1,"backup":1}
,"commands":{"commands":1,"required":1,"necessary":1}
,"required":{"configure":1}
,"configure":{"backup":1}
,"backup":{"lsp":1,"specify":1,"protection":1}
,"lsp":{"support":1,"either":1,"identification":1,"facility":1}
,"support":{"rsvp":1}
,"rsvp":{"signaled":1,"bypass":1}
,"signaled":{"lsps":1}
,"lsps":{"rsvp-te":1}
,"rsvp-te":{"command":1}
,"command":{"reference":1}
,"reference":{"guide":1}
,"guide":{"contains":1}
,"contains":{"commands":1}
,"necessary":{"create":1}
,"create":{"new":1,"fast":1}
,"new":{"rsvp":1}
,"bypass":{"tunnel":1,"tunnels":1}
,"tunnel":{"modify":1,"display":1}
,"modify":{"existing":1}
,"existing":{"rsvp":1}
,"display":{"detailed":1}
,"detailed":{"information":1}
,"information":{"bypass":1}
,"tunnels":{"create":1}
,"specify":{"protection":1}
,"protection":{"type":1,"method":1,"assign":1}
,"type":{"(one-to-one":1}
,"(one-to-one":{"facility":1}
,"facility":{"backup)":1,"backup":1}
,"backup)":{"assign":1}
,"assign":{"attributes":1}
,"attributes":{"frr":1}
,"frr":{"backup":1}
,"either":{"one-to-one":1}
,"one-to-one":{"facility":1,"protection":1}
,"method":{"backup":1,"one-to-one":1}
,"identification":{"method":1}
}
;Search.control.loadWordPairs(pairs);
