var pairs =
{
"isis":{"mesh-group":1}
,"mesh-group":{"command":1,"<1-4294967295>":1,"blocked":1,"parameters":1,"(config)":1}
,"command":{"mesh":1,"syntax":1,"mode":1}
,"mesh":{"group":1,"groups":1}
,"group":{"current":1,"number":1,"blocked":1}
,"current":{"interface":1}
,"interface":{"parameter":1,"command":1,"interface":1,"configured":1,"receives":1,"mode":1,"eth0":1,"eth2":1}
,"parameter":{"unset":1}
,"unset":{"mesh":1}
,"syntax":{"isis":1}
,"<1-4294967295>":{"isis":1,"specify":1}
,"blocked":{"isis":1,"specify":1,"standard":1,"(config)":1}
,"parameters":{"<1-4294967295>":1}
,"specify":{"mesh":1,"block":1}
,"number":{"blocked":1}
,"block":{"lsps":1}
,"lsps":{"current":1}
,"configured":{"mesh":1}
,"standard":{"lsp":1}
,"lsp":{"database":1}
,"database":{"synchronization":1}
,"synchronization":{"process":1}
,"process":{"applied":1}
,"applied":{"interface":1}
,"receives":{"csnp":1}
,"csnp":{"psnp":1}
,"psnp":{"default":1}
,"default":{"default":1,"mesh":1}
,"groups":{"enabled":1}
,"enabled":{"interface":1}
,"mode":{"interface":1,"examples":1}
,"examples":{"(config)":1}
,"(config)":{"interface":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"isis":1}
,"eth2":{"(config-if)":1}
}
;Search.control.loadWordPairs(pairs);
