var pairs =
{
"mstp_api_get_enable_bpdurx":{"function":1,"(char":1}
,"function":{"gets":1,"succeeds":1}
,"gets":{"setting":1}
,"setting":{"specifies":1}
,"specifies":{"whether":1}
,"whether":{"bpdu":1}
,"bpdu":{"receipt":1}
,"receipt":{"enabled":1}
,"enabled":{"specified":1,"whether":1,"=pal_true)":1}
,"specified":{"port":1}
,"port":{"syntax":1,"interface":1}
,"syntax":{"result_t":1}
,"result_t":{"mstp_api_get_enable_bpdurx":1}
,"(char":{"*br_name":1}
,"*br_name":{"char":1}
,"char":{"*if_name":1}
,"*if_name":{"bool_t":1}
,"bool_t":{"*enabled)":1}
,"*enabled)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"br_name":1,"enabled":1}
,"br_name":{"name":1,"exist":1}
,"name":{"bridge":1,"output":1}
,"bridge":{"if_name":1,"br_name":1}
,"if_name":{"interface":1}
,"interface":{"name":1,"exist":1}
,"output":{"parameters":1}
,"=pal_true)":{"disabled":1}
,"disabled":{"=pal_false)":1}
,"=pal_false)":{"return":1}
,"return":{"values":1}
,"values":{"result_ok":1}
,"result_ok":{"function":1}
,"succeeds":{"mstp_err_interface_not_found":1}
,"mstp_err_interface_not_found":{"interface":1}
,"exist":{"mstp_err_bridge_not_found":1,"mstp_err_port_not_found":1,"mstp_error_general":1}
,"mstp_err_bridge_not_found":{"bridge":1}
,"mstp_err_port_not_found":{"msti":1}
,"msti":{"port":1}
,"mstp_error_general":{"bad":1}
,"bad":{"passed":1}
}
;Search.control.loadWordPairs(pairs);
