var pairs =
{
"show":{"static-channel-group":1}
,"static-channel-group":{"command":1,"parameters":1,"static":1}
,"command":{"display":1,"syntax":1,"mode":1,"show":1}
,"display":{"types":1}
,"types":{"load-balancing":1}
,"load-balancing":{"port":1}
,"port":{"selection":1}
,"selection":{"criteria":1}
,"criteria":{"(psc)":1}
,"(psc)":{"used":1}
,"used":{"configured":1}
,"configured":{"static":1}
,"static":{"aggregators":1,"aggregator":1}
,"aggregators":{"command":1}
,"syntax":{"show":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"privileged":1,"examples":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"examples":{"following":1}
,"following":{"example":1}
,"example":{"output":1}
,"output":{"command":1}
,"aggregator":{"sa200":1,"sa201":1}
,"sa200":{"source":1}
,"source":{"destination":1}
,"destination":{"mac":1,"address":1}
,"mac":{"address":1}
,"address":{"static":1}
,"sa201":{"destination":1}
}
;Search.control.loadWordPairs(pairs);
