var pairs =
{
"ethernet":{"cfm":1}
,"cfm":{"pbb-te":1}
,"pbb-te":{"out-of-service":1}
,"out-of-service":{"command":1,"testing":1,"lck-level":1}
,"command":{"configure":1,"syntax":1,"mode":1}
,"configure":{"tesi":1,"mep":1}
,"tesi":{"out-of-service":1}
,"testing":{"command":1,"mep":1,"configure":1,"domain-name":1}
,"syntax":{"ethernet":1}
,"lck-level":{"level":1,"testing":1}
,"level":{"testing":1,"lck":1,"enter":1}
,"mep":{"mepid":1,"testing":1,"identity":1,"configured":1,"domain-name":1}
,"mepid":{"domain-name":1}
,"domain-name":{"domain_name":1,"specify":1,"abc":1}
,"domain_name":{"te-sid":1}
,"te-sid":{"te_sid":1,"service":1,"bridge":1}
,"te_sid":{"bridge":1}
,"bridge":{"backbone":1,"identify":1,"group":1,"command":1}
,"backbone":{"parameters":1,"specify":1,"bridge":1}
,"parameters":{"lck-level":1}
,"lck":{"frames":1,"level":1}
,"frames":{"generated":1}
,"generated":{"level":1}
,"enter":{"lck":1}
,"identity":{"mep":1}
,"configured":{"testing":1}
,"specify":{"name":1,"backbone":1}
,"name":{"maintenance":1,"backbone":1}
,"maintenance":{"domain":1}
,"domain":{"te-sid":1}
,"service":{"instance":1}
,"instance":{"bridge":1}
,"identify":{"bridge":1}
,"group":{"name":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"ethernet":1}
,"abc":{"te-sid":1}
}
;Search.control.loadWordPairs(pairs);
