var pairs =
{
"mip":{"creation":1}
,"creation":{"mip":1,"indirectly":1,"mips":1}
,"indirectly":{"controlled":1}
,"controlled":{"default":1}
,"default":{"level":1}
,"level":{"object":1,"managed":1}
,"object":{"following":1,"change":1,"associated":1}
,"following":{"conditions":1}
,"conditions":{"trigger":1}
,"trigger":{"management":1}
,"management":{"entity":1}
,"entity":{"evaluate":1}
,"evaluate":{"creation":1}
,"mips":{"vid":1}
,"vid":{"bridge":1,"(s)":1}
,"bridge":{"port":1,"initialized":1}
,"port":{"bridge":1,"mep":1,"change":1,"(applies":1}
,"initialized":{"mep":1}
,"mep":{"created":1}
,"created":{"deleted":1}
,"deleted":{"vid":1}
,"(s)":{"bridge":1,"cannot":1}
,"change":{"occurs":1}
,"occurs":{"state":1,"default":1,"managed":1}
,"state":{"vid":1}
,"cannot":{"pass":1}
,"pass":{"frames":1}
,"frames":{"bridge":1}
,"(applies":{"mas":1}
,"mas":{"associated":1}
,"associated":{"vid)":1,"vid":1}
,"vid)":{"change":1}
,"managed":{"object":1}
}
;Search.control.loadWordPairs(pairs);
