var pairs =
{
"loop-detection-path-vec-count":{"command":1,"<1-255>":1,"parameters":1,"123":1}
,"command":{"loop":1,"sets":1,"ensures":1,"syntax":1,"mode":1}
,"loop":{"detection":1,"command":1,"detected":1}
,"detection":{"vec":1,"specifies":1,"count":1,"hop":1}
,"vec":{"(vector)":1}
,"(vector)":{"count":1}
,"count":{"determines":1,"command":1}
,"determines":{"maximum":1}
,"maximum":{"supported":1,"length":1}
,"supported":{"path":1}
,"path":{"vectors":1,"vector":1,"data":1}
,"vectors":{"command":1,"loop":1}
,"sets":{"maximum":1}
,"specifies":{"permitted":1}
,"permitted":{"path":1}
,"vector":{"length":1,"reached":1}
,"length":{"lsr":1,"behaves":1}
,"lsr":{"detects":1}
,"detects":{"path":1}
,"reached":{"maximum":1}
,"behaves":{"containing":1}
,"containing":{"message":1}
,"message":{"traversed":1}
,"traversed":{"loop":1}
,"ensures":{"loop":1}
,"detected":{"establishing":1}
,"establishing":{"label":1}
,"label":{"switched":1}
,"switched":{"path":1}
,"data":{"passed":1}
,"passed":{"lsp":1}
,"lsp":{"parameter":1}
,"parameter":{"revert":1}
,"revert":{"default":1}
,"default":{"loop":1}
,"syntax":{"loop-detection-path-vec-count":1}
,"<1-255>":{"loop-detection-path-vec-count":1,"indicates":1}
,"parameters":{"<1-255>":1}
,"indicates":{"loop":1}
,"hop":{"count":1}
,"mode":{"router":1,"example":1}
,"router":{"mode":1,"ldp":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"ldp":{"(config-router)":1}
,"(config-router)":{"loop-detection-path-vec-count":1}
,"123":{"(config-router)":1}
}
;Search.control.loadWordPairs(pairs);
