var pairs =
{
"peer_port_unset":{"function":1,"(struct":1}
,"function":{"unsets":1,"called":1,"successful":1}
,"unsets":{"bgp":1}
,"bgp":{"port":1,"peer":1}
,"port":{"number":1,"syntax":1}
,"number":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"port":1}
,"syntax":{"int":1}
,"int":{"peer_port_unset":1}
,"(struct":{"bgp_peer":1}
,"bgp_peer":{"peer)":1}
,"peer)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"peer":1,"none":1}
,"peer":{"bgp":1,"output":1,"peer-group":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"bgp_api_set_success":1}
,"bgp_api_set_success":{"function":1}
,"successful":{"(0)":1}
,"(0)":{"bgp_api_set_err_peer_group_has_the_flag":1}
,"bgp_api_set_err_peer_group_has_the_flag":{"peer":1}
,"peer-group":{"member":1,"configuration":1}
,"member":{"change":1}
,"change":{"peer-group":1}
,"configuration":{"(-19)":1}
}
;Search.control.loadWordPairs(pairs);
