var pairs =
{
"radius-server":{"host":1}
,"host":{"command":1,"(a.b.c.d":1,"name":1,"203.0.113.15":1}
,"command":{"configure":1,"remove":1,"syntax":1,"mode":1}
,"configure":{"radius":1,"mode":1,"terminal":1}
,"radius":{"server":1}
,"server":{"accounting":1,"command":1,"x:x":1,"hostname":1,"retransmit":1,"reverting":1,"declaring":1,"idle-time":1,"<0-1440>":1}
,"accounting":{"authentication":1}
,"authentication":{"form":1,"<0-5>":1}
,"form":{"command":1}
,"remove":{"radius":1}
,"syntax":{"radius-server":1}
,"(a.b.c.d":{"x:x":1}
,"x:x":{":x:x":1}
,":x:x":{"hostname)":1,"ipv6":1}
,"hostname)":{"radius-server":1,"retransmit":1,"timeout":1,"test":1}
,"retransmit":{"<0-5>":1,"number":1,"count":1}
,"<0-5>":{"radius-server":1,"range":1}
,"timeout":{"<1-60>":1,"long":1,"failure":1,"period":1}
,"<1-60>":{"(retransmit":1,"range":1}
,"(retransmit":{"<0-5>":1}
,"test":{"(idle-time":1,"parameters":1,"packets":1}
,"(idle-time":{"<0-1440>":1}
,"<0-1440>":{"password":1,"range":1}
,"password":{"word":1,"user":1,"(maximum":1}
,"word":{"username":1,"user":1}
,"username":{"word)":1,"user":1}
,"word)":{"radius-server":1,"parameters":1}
,"parameters":{"a.b.c.d":1,"sending":1}
,"a.b.c.d":{"ipv4":1}
,"ipv4":{"address":1}
,"address":{"radius":1}
,"ipv6":{"address":1}
,"hostname":{"dns":1}
,"dns":{"host":1}
,"name":{"radius":1,"word":1,"(maximum":1}
,"number":{"times":1}
,"times":{"try":1}
,"try":{"connect":1}
,"connect":{"radius":1}
,"reverting":{"local":1}
,"local":{"authentication":1}
,"range":{"retransmit":1,"timeout":1,"time":1}
,"count":{"timeout":1}
,"long":{"wait":1}
,"wait":{"response":1}
,"response":{"radius":1}
,"declaring":{"timeout":1}
,"failure":{"<1-60>":1}
,"period":{"seconds":1}
,"seconds":{"test":1}
,"sending":{"test":1}
,"packets":{"radius":1}
,"idle-time":{"time":1}
,"time":{"interval":1}
,"interval":{"monitor":1,"minutes":1}
,"monitor":{"server":1}
,"minutes":{"password":1}
,"user":{"password":1,"name":1}
,"(maximum":{"characters)":1}
,"characters)":{"username":1,"command":1}
,"mode":{"configure":1,"examples":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"radius-server":1}
}
;Search.control.loadWordPairs(pairs);
