var pairs =
{
"show":{"pim":1}
,"pim":{"ecmp-bundle":1,"(vrf":1}
,"ecmp-bundle":{"command":1,"(word":1,"name":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"ecmp":1}
,"ecmp":{"bundle":1}
,"bundle":{"information":1,"name":1}
,"information":{"command":1}
,"syntax":{"show":1}
,"(vrf":{"name":1}
,"name":{"ecmp-bundle":1,"specify":1,"vpn":1,"command":1,"ecmpbundle":1}
,"(word":{"show":1,"parameters":1}
,"parameters":{"vrf":1}
,"vrf":{"vpn":1}
,"vpn":{"routing\u002Fforwarding":1}
,"routing\u002Fforwarding":{"instance":1}
,"instance":{"name":1,"word":1}
,"specify":{"name":1}
,"word":{"ecmp":1}
,"mode":{"privileged":1,"examples":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"examples":{"show":1}
,"ecmpbundle":{"interface":1}
,"interface":{"<ecmp":1}
,"<ecmp":{"redirect":1}
,"redirect":{"status>":1}
,"status>":{"eth2":1}
,"eth2":{"allowed":1}
,"allowed":{"eth3":1}
,"eth3":{"allowed":1}
}
;Search.control.loadWordPairs(pairs);
