var pairs =
{
"ospf_timers_spf_set":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"called":1,"succeeds":1}
,"sets":{"minimum":1}
,"minimum":{"maximum":1,"spf":1}
,"maximum":{"delay":1,"spf":1}
,"delay":{"topology":1,"time":1}
,"topology":{"change":1}
,"change":{"either":1,"starts":1}
,"either":{"received":1}
,"received":{"lsa":1}
,"lsa":{"self":1}
,"self":{"detected":1}
,"detected":{"spf":1}
,"spf":{"calculation":1,"exp":1,"hold":1}
,"calculation":{"run":1,"function":1}
,"run":{"delay":1}
,"time":{"ospf":1,"milliseconds":1}
,"ospf":{"receives":1,"instance":1}
,"receives":{"topology":1}
,"starts":{"spf":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"timers":1}
,"timers":{"spf":1}
,"exp":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf_timers_spf_set":1,"proc_id":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"int":1,"virtual":1}
,"proc_id":{"u_int32_t":1,"process":1}
,"u_int32_t":{"min_delay":1,"max_delay)":1}
,"min_delay":{"u_int32_t":1,"minimum":1}
,"max_delay)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"found":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"proc_id":1}
,"process":{"ospf":1,"valid":1,"exist":1}
,"instance":{"65535>":1}
,"65535>":{"min_delay":1}
,"hold":{"delay":1}
,"milliseconds":{"500":1,"max_delay":1,"50000":1,"(50":1}
,"500":{"milliseconds":1}
,"max_delay":{"maximum":1}
,"50000":{"milliseconds":1}
,"(50":{"seconds)":1}
,"seconds)":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf_api_set_success":1}
,"ospf_api_set_success":{"function":1}
,"succeeds":{"ospf_api_set_err_process_id_invalid":1}
,"ospf_api_set_err_process_id_invalid":{"given":1}
,"given":{"process":1}
,"valid":{"(outside":1}
,"(outside":{"65535":1}
,"65535":{"bounds)":1}
,"bounds)":{"ospf_api_set_err_process_not_exist":1}
,"ospf_api_set_err_process_not_exist":{"given":1}
,"exist":{"ospf_api_set_err_vr_not_exist":1}
,"ospf_api_set_err_vr_not_exist":{"virtual":1}
}
;Search.control.loadWordPairs(pairs);
