var pairs =
{
"ldp_snmp_api_set_fec_type":{"call":1,"(struct":1}
,"call":{"sets":1}
,"sets":{"fec":1}
,"fec":{"type":1,"index":1,"present":1,"route":1,"shadow":1,"pointer":1,"output":1}
,"type":{"given":1,"shadow_entry":1}
,"given":{"fec":1}
,"index":{"fec":1}
,"present":{"either":1}
,"either":{"fec":1}
,"route":{"table":1}
,"table":{"fec":1,"syntax":1}
,"shadow":{"entry":1}
,"entry":{"table":1,"value":1}
,"syntax":{"int":1}
,"int":{"ldp_snmp_api_set_fec_type":1}
,"(struct":{"ldp":1}
,"ldp":{"*ldp":1,"ldp":1,"instance":1}
,"*ldp":{"s_int32_t":1}
,"s_int32_t":{"fectype":1}
,"fectype":{"struct":1,"fec":1}
,"struct":{"snmp_mplsfecentry_t":1,"ldp_fec":1}
,"snmp_mplsfecentry_t":{"*shadow_entry":1}
,"*shadow_entry":{"struct":1}
,"ldp_fec":{"*fec)":1}
,"*fec)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ldp":1,"none":1}
,"instance":{"fectype":1}
,"shadow_entry":{"snmp":1}
,"snmp":{"fec":1}
,"value":{"null":1}
,"null":{"fec":1}
,"pointer":{"fec":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"ldp_success":1}
,"ldp_success":{"ldp_error":1}
}
;Search.control.loadWordPairs(pairs);
