var pairs =
{
"ospf_if_hello_interval_unset":{"function":1,"(u_int32_t":1}
,"function":{"resets":1,"called":1,"succeeds":1}
,"resets":{"hello":1}
,"hello":{"interval":1}
,"interval":{"current":1}
,"current":{"interface":1}
,"interface":{"default":1,"name":1,"configured":1}
,"default":{"value":1}
,"value":{"specified":1,"ospf_api_set_success":1}
,"specified":{"ospf_hello_interval_default":1}
,"ospf_hello_interval_default":{"(refer":1}
,"(refer":{"ospf_interface.h)":1}
,"ospf_interface.h)":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"ospf":1}
,"ospf":{"hello-interval":1}
,"hello-interval":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf_if_hello_interval_unset":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1}
,"char":{"*name)":1}
,"*name)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"found":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"name":1}
,"name":{"interface":1,"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"ospf_api_set_success":{"function":1}
,"succeeds":{"ospf_api_set_err_if_param_not_configured":1}
,"ospf_api_set_err_if_param_not_configured":{"given":1}
,"given":{"interface":1}
,"configured":{"ospf_api_set_err_vr_not_exist":1}
,"ospf_api_set_err_vr_not_exist":{"virtual":1}
}
;Search.control.loadWordPairs(pairs);
