var pairs =
{
"ospf_nbr_static_config_check":{"function":1,"(u_int32_t":1}
,"function":{"checks":1,"succeeds":1}
,"checks":{"neighbor":1}
,"neighbor":{"configuration":1,"address":1}
,"configuration":{"state":1,"ospf_api_set_err_nbr_nbma_config_invalid":1,"ospf_api_set_err_nbr_p2mp_config_required":1}
,"state":{"multi-area":1,"output":1}
,"multi-area":{"adjacency":1,"networks":1}
,"adjacency":{"feature":1}
,"feature":{"function":1}
,"networks":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf_nbr_static_config_check":1,"proc_id":1,"config)":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"int":1,"virtual":1}
,"proc_id":{"struct":1,"process":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"addr":1}
,"addr":{"int":1,"nbma":1}
,"config)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"found":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"proc_id":1}
,"process":{"ospf":1,"valid":1,"exist":1}
,"ospf":{"instance":1}
,"instance":{"65535>":1}
,"65535>":{"addr":1}
,"nbma":{"neighbor":1,"point-to-multipoint":1,"network":1}
,"address":{"a.b.c.d":1}
,"a.b.c.d":{"config":1}
,"config":{"configuration":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf_api_set_success":1}
,"ospf_api_set_success":{"function":1}
,"succeeds":{"ospf_api_set_err_vr_not_exist":1}
,"ospf_api_set_err_vr_not_exist":{"virtual":1}
,"found":{"ospf_api_set_err_process_id_invalid":1}
,"ospf_api_set_err_process_id_invalid":{"process":1}
,"valid":{"ospf_api_set_err_process_not_exist":1}
,"ospf_api_set_err_process_not_exist":{"given":1}
,"given":{"process":1}
,"exist":{"ospf_api_set_err_nbr_config_invalid":1}
,"ospf_api_set_err_nbr_config_invalid":{"network":1}
,"network":{"nbma":1,"point-to-multipoint":1,"required":1,"ospf_api_set_err_nbr_p2mp_config_invalid":1}
,"point-to-multipoint":{"required":1,"network":1,"broadcast":1}
,"required":{"configuration":1,"poll":1}
,"ospf_api_set_err_nbr_nbma_config_invalid":{"network":1}
,"ospf_api_set_err_nbr_p2mp_config_required":{"cost":1}
,"cost":{"option":1}
,"option":{"configured":1}
,"configured":{"point-to-multipoint":1}
,"broadcast":{"network":1}
,"ospf_api_set_err_nbr_p2mp_config_invalid":{"network":1}
,"poll":{"priority":1}
,"priority":{"option":1}
}
;Search.control.loadWordPairs(pairs);
