var pairs =
{
"keyboard":{"operations":1,"keyboard":1}
,"operations":{"table":1,"perform":1,"key":1}
,"table":{"1-4":1}
,"1-4":{"lists":1}
,"lists":{"operations":1}
,"perform":{"keyboard":1}
,"key":{"combination":1}
,"combination":{"operation":1}
,"operation":{"left":1}
,"left":{"arrow":1,"command":1}
,"arrow":{"ctrl":1,"ctrl-f":1}
,"ctrl":{"moves":1,"repeatedly":1,"directly":1,"deletes":1,"pastes":1,"alt":1,"ctrl":1,"cursor":1,"transposes":1,"ignores":1,"ends":1,"clears":1,"scroll":1}
,"moves":{"character":1,"back":1,"forward":1,"end":1,"beginning":1}
,"character":{"left":1,"right":1,"previous":1,"ctrl":1}
,"command":{"extends":1,"prompt":1,"history":1}
,"extends":{"beyond":1}
,"beyond":{"single":1}
,"single":{"line":1}
,"line":{"press":1,"right":1,"esc":1,"ctrl":1,"redisplays":1}
,"press":{"left":1,"ctrl":1,"right":1}
,"repeatedly":{"scroll":1}
,"scroll":{"toward":1,"backward":1,"forward":1}
,"toward":{"beginning":1,"end":1}
,"beginning":{"line":1}
,"directly":{"beginning":1,"end":1}
,"right":{"arrow":1,"command":1}
,"ctrl-f":{"moves":1}
,"end":{"line":1}
,"esc":{"moves":1}
,"back":{"word":1}
,"word":{"esc":1,"ctrl":1}
,"forward":{"word":1,"command":1}
,"deletes":{"line":1,"cursor":1,"current":1}
,"cursor":{"previous":1,"end":1,"ctrl":1}
,"previous":{"whitespace":1,"character":1}
,"whitespace":{"alt":1}
,"alt":{"deletes":1,"ctrl":1}
,"current":{"word":1,"character":1,"line":1}
,"pastes":{"text":1}
,"text":{"previously":1}
,"previously":{"deleted":1}
,"deleted":{"ctrl":1}
,"transposes":{"current":1}
,"ignores":{"current":1}
,"redisplays":{"command":1}
,"prompt":{"ctrl":1}
,"ends":{"configuration":1}
,"configuration":{"mode":1}
,"mode":{"returns":1,"ctrl":1}
,"returns":{"exec":1}
,"exec":{"mode":1}
,"clears":{"screen":1}
,"screen":{"arrow":1}
,"backward":{"command":1}
,"history":{"down":1}
,"down":{"arrow":1}
}
;Search.control.loadWordPairs(pairs);
