var pairs =
{
"neighbor":{"password":1,"(a.b.c.d":1,"ipv4":1,"ipv6":1,"10.10.0.73":1}
,"password":{"command":1,"bgp":1,"<word>":1,"(maximum":1,"ipi":1}
,"command":{"enable":1,"delete":1,"syntax":1,"mode":1}
,"enable":{"message":1}
,"message":{"digest5":1}
,"digest5":{"(md5)":1}
,"(md5)":{"authentication":1}
,"authentication":{"tcp":1,"two":1,"configured":1,"command":1}
,"tcp":{"connection":1}
,"connection":{"two":1,"peers":1,"established":1}
,"two":{"bgp":1}
,"bgp":{"peers":1,"neighbor":1,"peer":1,"(config-router)":1}
,"peers":{"configuring":1,"means":1,"verified":1,"otherwise":1}
,"configuring":{"md5":1}
,"md5":{"authentication":1}
,"means":{"segment":1}
,"segment":{"sent":1}
,"sent":{"tcp":1}
,"verified":{"md5":1}
,"configured":{"password":1}
,"otherwise":{"connection":1}
,"established":{"parameter":1}
,"parameter":{"command":1}
,"delete":{"md5":1}
,"syntax":{"neighbor":1}
,"(a.b.c.d":{"x:x":1}
,"x:x":{":x:x":1}
,":x:x":{"word)":1,"address":1}
,"word)":{"password":1}
,"<word>":{"neighbor":1,"parameters":1}
,"parameters":{"a.b.c.d":1}
,"a.b.c.d":{"address":1}
,"address":{"bgp":1}
,"ipv4":{"format":1}
,"format":{"x:x":1,"word":1}
,"ipv6":{"format":1}
,"word":{"name":1,"password":1}
,"name":{"bgp":1}
,"peer":{"group":1}
,"group":{"word":1}
,"(maximum":{"length":1}
,"length":{"charecters)":1}
,"charecters)":{"command":1}
,"mode":{"router":1,"example":1}
,"router":{"mode":1,"bgp":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"(config-router)":{"neighbor":1}
,"10.10.0.73":{"password":1}
,"ipi":{"(config-router)":1}
}
;Search.control.loadWordPairs(pairs);
