var pairs =
{
"rip2_get_if_conf_auth_key":{"function":1,"(int":1}
,"function":{"returns":1}
,"returns":{"value":1}
,"value":{"used":1,"noauthentication":1,"return":1,"rip_api_get_success":1}
,"used":{"authentication":1}
,"authentication":{"key":1}
,"key":{"whenever":1,"authentication":1,"value":1}
,"whenever":{"corresponding":1}
,"corresponding":{"instance":1}
,"instance":{"rip2_get_if_conf_auth_type":1}
,"rip2_get_if_conf_auth_type":{"value":1}
,"noauthentication":{"syntax":1}
,"syntax":{"int":1}
,"int":{"rip2_get_if_conf_auth_key":1}
,"(int":{"pid":1}
,"pid":{"struct":1,"rip":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"*addr":1}
,"*addr":{"char":1}
,"char":{"**key)":1}
,"**key)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"pid":1,"key":1}
,"rip":{"process":1}
,"process":{"addr":1}
,"addr":{"address":1}
,"address":{"specified":1}
,"specified":{"interface":1}
,"interface":{"output":1}
,"output":{"parameters":1}
,"return":{"values":1}
,"values":{"rip_api_get_error":1}
,"rip_api_get_error":{"call":1}
,"call":{"find":1,"finds":1}
,"find":{"authentication":1}
,"rip_api_get_success":{"call":1}
,"finds":{"authentication":1}
}
;Search.control.loadWordPairs(pairs);
