var pairs =
{
"rip_if_receive_version_type_set":{"function":1,"(u_int32_t":1}
,"function":{"enables":1,"called":1}
,"enables":{"receiving":1}
,"receiving":{"specified":1,"versions":1}
,"specified":{"version":1}
,"version":{"rip":1,"receiving":1,"function":1,"syntax":1,"type":1,"ri_rip_version_2":1,"ri_rip_version_1_and_2":1,"ri_rip_version_1_compatible":1,"uni\u002Fbroadcast":1}
,"rip":{"packets":1,"receive":1,"version":1}
,"packets":{"(version":1}
,"(version":{"version":1}
,"versions":{"rip":1}
,"called":{"following":1}
,"following":{"cli":1,"ri_rip_version_1":1}
,"cli":{"commands":1}
,"commands":{"rip":1}
,"receive":{"version":1}
,"syntax":{"int":1}
,"int":{"rip_if_receive_version_type_set":1,"type)":1,"type":1,"retval":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1,"exist":1}
,"char":{"*ifname":1}
,"*ifname":{"int":1,"interface":1}
,"type)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"parameter":1}
,"parameter":{"char":1}
,"interface":{"name":1}
,"name":{"string":1}
,"string":{"int":1}
,"type":{"version":1,"following":1}
,"ri_rip_version_1":{"rip":1}
,"ri_rip_version_2":{"rip":1}
,"ri_rip_version_1_and_2":{"rip":1}
,"ri_rip_version_1_compatible":{"rip":1}
,"uni\u002Fbroadcast":{"address":1}
,"address":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"rip_api_set_err_vr_not_exist":1}
,"rip_api_set_err_vr_not_exist":{"vr_id":1}
,"exist":{"rip_api_set_success":1}
,"rip_api_set_success":{"call":1}
,"call":{"successful":1}
,"successful":{"usage":1}
,"usage":{"notes":1}
,"notes":{"command":1}
,"command":{"rip":1}
,"retval":{"retval=rip_if_receive_version_type_set":1}
,"retval=rip_if_receive_version_type_set":{"(ifname":1}
,"(ifname":{"ri_rip_version_1_and_2)":1}
}
;Search.control.loadWordPairs(pairs);
