var pairs =
{
"clear":{"bgp":1,"peers":1,"incoming":1,"outgoing":1}
,"bgp":{"<1-4294967295>":1,"connection":1,"500":1}
,"<1-4294967295>":{"vpnv6":1,"clear":1}
,"vpnv6":{"command":1,"unicast":1}
,"command":{"reset":1,"syntax":1,"mode":1}
,"reset":{"bgp":1}
,"connection":{"vpn":1}
,"vpn":{"peers":1}
,"peers":{"specified":1,"number":1}
,"specified":{"autonomous":1}
,"autonomous":{"system":1}
,"system":{"command":1}
,"syntax":{"clear":1}
,"unicast":{"clear":1,"soft":1}
,"soft":{"clear":1,"parameters":1,"reconfig":1}
,"parameters":{"<1-4294967295>":1}
,"number":{"clear":1}
,"incoming":{"advertised":1,"outgoing":1}
,"advertised":{"routes":1}
,"routes":{"clear":1,"soft":1}
,"outgoing":{"advertised":1,"routes":1}
,"reconfig":{"inbound":1,"outbound":1}
,"inbound":{"update":1}
,"update":{"soft":1,"command":1}
,"outbound":{"update":1}
,"mode":{"privileged":1,"examples":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"examples":{"clear":1}
,"500":{"vpnv6":1}
}
;Search.control.loadWordPairs(pairs);
