var pairs =
{
"cfm_pbb_te_mcc_send":{"function":1,"(struct":1}
,"function":{"sends":1,"succeeds":1}
,"sends":{"maintenance":1}
,"maintenance":{"communication":1,"domain":1}
,"communication":{"channel":1}
,"channel":{"(mcc)":1}
,"(mcc)":{"frames":1}
,"frames":{"local":1,"transmit":1}
,"local":{"remote":1}
,"remote":{"mep":1}
,"mep":{"pbb-te":1,"<1-8191>":1,"found":1}
,"pbb-te":{"bridge":1}
,"bridge":{"syntax":1,"identity":1,"md_name":1,"found":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"cfm_pbb_te_mcc_send":1}
,"(struct":{"onmd_bridge":1}
,"onmd_bridge":{"*bridge":1}
,"*bridge":{"u_int8_t":1}
,"u_int8_t":{"*md_name":1,"frame_type)":1}
,"*md_name":{"u_int32_t":1}
,"u_int32_t":{"te_sid":1,"mepid":1,"rmepid":1}
,"te_sid":{"u_int32_t":1,"service":1}
,"mepid":{"u_int32_t":1,"source":1}
,"rmepid":{"u_int8_t":1,"remote":1}
,"frame_type)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bridge":1}
,"identity":{"bridge":1}
,"md_name":{"maintenance":1}
,"domain":{"name":1}
,"name":{"te_sid":1}
,"service":{"instance":1}
,"instance":{"<1-42949675>":1}
,"<1-42949675>":{"mepid":1}
,"source":{"mep":1}
,"<1-8191>":{"rmepid":1,"frame_type":1}
,"frame_type":{"type":1}
,"type":{"mcc":1}
,"mcc":{"frames":1}
,"transmit":{"values":1}
,"values":{"onmd\u002Fcfm\u002Fcfmd.h":1,"cfm_bridge_not_found":1}
,"onmd\u002Fcfm\u002Fcfmd.h":{"cfm_ucast_frame":1}
,"cfm_ucast_frame":{"unicast":1}
,"unicast":{"cfm_mcast_frame":1}
,"cfm_mcast_frame":{"multicast":1}
,"multicast":{"return":1}
,"return":{"values":1}
,"cfm_bridge_not_found":{"bridge":1}
,"found":{"cfm_md_list_not_found":1,"cfm_domain_not_found":1,"cfm_ma_not_found":1,"cfm_mep_not_found":1,"cfm_api_err_pbb_te_sid_not_pt_to_pt":1,"cfm_api_err_pbb_te_esp_not_found":1}
,"cfm_md_list_not_found":{"list":1}
,"list":{"found":1}
,"cfm_domain_not_found":{"found":1}
,"cfm_ma_not_found":{"found":1}
,"cfm_mep_not_found":{"mep":1}
,"cfm_api_err_pbb_te_sid_not_pt_to_pt":{"te-sid":1}
,"te-sid":{"point-to-point":1}
,"point-to-point":{"cfm_memory_not_allocated":1}
,"cfm_memory_not_allocated":{"memory":1}
,"memory":{"allocation":1}
,"allocation":{"fails":1}
,"fails":{"cfm_rmep_not_found":1}
,"cfm_rmep_not_found":{"rmep":1}
,"rmep":{"found":1}
,"cfm_api_err_pbb_te_esp_not_found":{"packet":1}
,"packet":{"sent":1}
,"sent":{"invalid":1}
,"invalid":{"mac":1}
,"mac":{"cfm_api_err_none":1}
,"cfm_api_err_none":{"function":1}
}
;Search.control.loadWordPairs(pairs);
