var pairs =
{
"routing":{"protocol":1,"information":1,"device":1,"protocols":1,"routers":1,"distance-vector":1,"link-state":1,"type":1,"(cidr)":1}
,"protocol":{"processes":1,"usually":1,"shares":1,"(bgp)":1,"(rip)":1,"(egp)":1,"(igp)":1}
,"processes":{"algorithms":1}
,"algorithms":{"messages":1}
,"messages":{"used":1}
,"used":{"exchange":1}
,"exchange":{"routing":1,"information":1,"allows":1}
,"information":{"populate":1,"base":1,"devices":1,"first":1,"topology":1,"protocol":1}
,"populate":{"local":1}
,"local":{"routing":1}
,"base":{"(rib)":1}
,"(rib)":{"best":1}
,"best":{"path":1}
,"path":{"source":1,"first":1}
,"source":{"destination":1}
,"destination":{"term":1}
,"term":{"routing":1}
,"usually":{"implies":1}
,"implies":{"dynamic":1}
,"dynamic":{"routing":1}
,"device":{"reports":1}
,"reports":{"changes":1}
,"changes":{"shares":1}
,"shares":{"information":1}
,"devices":{"network":1,"directly":1,"networks":1}
,"network":{"router":1,"routers":1,"primary":1,"table":1}
,"router":{"starts":1}
,"starts":{"knowledge":1}
,"knowledge":{"devices":1}
,"directly":{"attached":1}
,"attached":{"routing":1}
,"first":{"immediate":1,"(ospf)":1}
,"immediate":{"neighbors":1}
,"neighbors":{"throughout":1}
,"throughout":{"network":1}
,"routers":{"learn":1,"exchange":1,"automatically":1}
,"learn":{"topology":1,"new":1}
,"topology":{"network":1,"change":1}
,"primary":{"benefit":1}
,"benefit":{"dynamic":1}
,"protocols":{"static":1,"supported":1,"border":1}
,"static":{"routing":1}
,"change":{"exchange":1}
,"allows":{"routers":1}
,"automatically":{"learn":1}
,"new":{"devices":1}
,"networks":{"find":1}
,"find":{"alternate":1}
,"alternate":{"paths":1}
,"paths":{"link":1}
,"link":{"failure":1}
,"failure":{"current":1}
,"current":{"network":1}
,"table":{"3-2":1}
,"3-2":{"summarizes":1}
,"summarizes":{"characteristics":1}
,"characteristics":{"dynamic":1}
,"supported":{"zebos-xp":1}
,"zebos-xp":{"dynamic":1}
,"border":{"gateway":1}
,"gateway":{"protocol":1}
,"(bgp)":{"routing":1}
,"(rip)":{"open":1}
,"open":{"shortest":1}
,"shortest":{"path":1}
,"(ospf)":{"intermediate":1}
,"intermediate":{"system":1}
,"system":{"intermediate":1,"(is-is)":1}
,"(is-is)":{"algorithm":1}
,"algorithm":{"path-vector":1}
,"path-vector":{"routing":1}
,"distance-vector":{"routing":1}
,"link-state":{"routing":1}
,"type":{"exterior":1}
,"exterior":{"gateway":1}
,"(egp)":{"interior":1}
,"interior":{"gateway":1}
,"(igp)":{"interior":1,"classless":1}
,"classless":{"interdomain":1}
,"interdomain":{"routing":1}
,"(cidr)":{"rip":1}
,"rip":{"rip":1,"scalable":1}
,"scalable":{"speed":1}
,"speed":{"convergence":1}
,"convergence":{"moderate":1}
,"moderate":{"slow":1}
,"slow":{"fast":1}
,"fast":{"fast":1,"resource":1}
,"resource":{"high":1}
,"high":{"low":1,"high":1,"configuration":1}
,"low":{"high":1}
,"configuration":{"ease":1}
,"ease":{"complex":1}
,"complex":{"simple":1,"complex":1}
,"simple":{"complex":1}
}
;Search.control.loadWordPairs(pairs);
