var pairs =
{
"ldp":{"hello-interval":1,"defines":1,"process":1}
,"hello-interval":{"command":1,"value":1,"<1-21845>":1,"parameters":1,"specific":1,"635":1}
,"command":{"interval":1,"specify":1,"interface-specific":1,"overrides":1,"parameter":1,"revert":1,"syntax":1,"mode":1}
,"interval":{"sending":1,"hello":1,"seconds":1}
,"sending":{"multicast":1}
,"multicast":{"hello":1,"address":1}
,"hello":{"packets":1,"packet":1,"adjacency":1}
,"packets":{"via":1,"sent":1}
,"via":{"interface":1}
,"interface":{"ldp":1,"mode":1,"configure":1,"eth0":1}
,"defines":{"mechanism":1}
,"mechanism":{"discovering":1}
,"discovering":{"adjacent":1}
,"adjacent":{"label":1}
,"label":{"switching":1}
,"switching":{"routers":1,"(adjacencies)":1}
,"routers":{"(lsr)":1}
,"(lsr)":{"participate":1}
,"participate":{"label":1}
,"(adjacencies)":{"whenever":1}
,"whenever":{"new":1}
,"new":{"router":1}
,"router":{"comes":1,"directly":1}
,"comes":{"sends":1}
,"sends":{"hello":1}
,"packet":{"specified":1,"receipt":1,"lsr":1}
,"specified":{"multicast":1}
,"address":{"announcing":1}
,"announcing":{"itself":1}
,"itself":{"network":1}
,"network":{"every":1,"receives":1}
,"every":{"router":1}
,"directly":{"connected":1}
,"connected":{"network":1}
,"receives":{"packet":1}
,"receipt":{"hello":1}
,"lsr":{"creates":1,"command":1,"using":1}
,"creates":{"hello":1}
,"adjacency":{"lsr":1}
,"specify":{"interval":1}
,"sent":{"optimum":1}
,"optimum":{"performance":1}
,"performance":{"hello-interval":1}
,"value":{"one-third":1,"command":1,"lsr":1,"main":1}
,"one-third":{"hold-time":1}
,"hold-time":{"value":1}
,"interface-specific":{"command":1}
,"overrides":{"value":1}
,"using":{"global":1}
,"global":{"hello-interval":1}
,"parameter":{"command":1}
,"revert":{"hello-interval":1}
,"main":{"ldp":1}
,"process":{"command":1}
,"syntax":{"ldp":1}
,"<1-21845>":{"ldp":1,"specify":1}
,"parameters":{"<1-21845>":1}
,"seconds":{"command":1}
,"mode":{"interface":1,"examples":1}
,"examples":{"example":1}
,"example":{"shows":1}
,"shows":{"hello-interval":1}
,"specific":{"interface":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"ldp":1}
,"635":{"(config-if)":1}
}
;Search.control.loadWordPairs(pairs);
