var pairs =
{
"efm":{"oam":1,"oam)":1}
,"oam":{"sublayer":1,"mac":1,"request":1}
,"sublayer":{"efm":1,"provides":1,"resides":1,"mac":1,"example":1,"supports":1,"turn":1,"communicates":1,"passes":1,"decodes":1,"loopback":1}
,"oam)":{"sublayer":1}
,"provides":{"mechanisms":1}
,"mechanisms":{"monitoring":1}
,"monitoring":{"link":1}
,"link":{"operations":1}
,"operations":{"example":1}
,"example":{"remote":1,"mac":1}
,"remote":{"fault":1}
,"fault":{"detection":1,"conditions":1}
,"detection":{"loopback":1}
,"loopback":{"controls":1,"fames":1}
,"controls":{"enables":1}
,"enables":{"network":1}
,"network":{"monitors":1}
,"monitors":{"dynamically":1}
,"dynamically":{"track":1}
,"track":{"health":1}
,"health":{"connections":1}
,"connections":{"locate":1}
,"locate":{"failing":1}
,"failing":{"links":1}
,"links":{"fault":1}
,"conditions":{"oam":1}
,"resides":{"superior":1}
,"superior":{"sublayer":1}
,"mac":{"client":1,"control":1,"clients":1,"physical":1}
,"client":{"subordinate":1,"frames":1}
,"subordinate":{"sublayer":1,"layers":1}
,"control":{"layer":1,"(optional)":1,"function":1}
,"layer":{"oam":1,"multiplexer":1,"parser":1}
,"supports":{"interlayer":1}
,"interlayer":{"service":1}
,"service":{"interfaces":1}
,"interfaces":{"interfaces":1,"supported":1}
,"supported":{"oam":1}
,"clients":{"oam":1}
,"turn":{"oam":1}
,"communicates":{"subordinate":1}
,"layers":{"mac":1}
,"(optional)":{"mac":1}
,"physical":{"layer":1}
,"multiplexer":{"oam":1,"function":1}
,"passes":{"properly":1,"oampdus":1}
,"properly":{"formed":1}
,"formed":{"oam":1}
,"request":{"underlying":1}
,"underlying":{"layer":1}
,"parser":{"oam":1}
,"decodes":{"frames":1}
,"frames":{"received":1,"superior":1}
,"received":{"subordinate":1}
,"oampdus":{"control":1}
,"function":{"mac":1}
,"fames":{"multiplexer":1}
}
;Search.control.loadWordPairs(pairs);
