var pairs =
{
"ospf6_get_next_if_metric_value":{"function":1,"(char":1}
,"function":{"gets":1,"fails":1,"succeeds":1}
,"gets":{"next":1}
,"next":{"entry":1}
,"entry":{"metric":1}
,"metric":{"value":1}
,"value":{"assigned":1,"return":1}
,"assigned":{"given":1}
,"given":{"interface":1}
,"interface":{"syntax":1,"index":1}
,"syntax":{"int":1}
,"int":{"ospf6_get_next_if_metric_value":1,"*ifindex":1,"*instid":1,"indexlen":1,"*ret)":1}
,"(char":{"*tag":1}
,"*tag":{"int":1}
,"*ifindex":{"int":1}
,"*instid":{"int":1}
,"indexlen":{"int":1,"length":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"tag":1,"ret":1}
,"tag":{"ospfv3":1,"ifindex":1}
,"ospfv3":{"process":1}
,"process":{"tag":1}
,"ifindex":{"interface":1}
,"index":{"instid":1,"output":1}
,"instid":{"instance":1}
,"instance":{"identifier":1}
,"identifier":{"indexlen":1}
,"length":{"object":1}
,"object":{"index":1}
,"output":{"parameters":1}
,"ret":{"metric":1}
,"return":{"values":1}
,"values":{"ospf6_api_get_error":1}
,"ospf6_api_get_error":{"function":1}
,"fails":{"ospf6_api_get_success":1}
,"ospf6_api_get_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
