var pairs =
{
"mpls-tp":{"layer":1}
,"layer":{"virtual":1,"circuit":1}
,"virtual":{"circuit":1}
,"circuit":{"mpls-tp":1,"(vc)":1,"transported":1}
,"(vc)":{"point-to-point":1}
,"point-to-point":{"layer-2":1}
,"layer-2":{"connection":1}
,"connection":{"transported":1}
,"transported":{"multi-protocol":1,"single":1}
,"multi-protocol":{"label":1}
,"label":{"switching":1,"switched":1}
,"switching":{"transport":1}
,"transport":{"profile":1}
,"profile":{"(mpls-tp)":1}
,"(mpls-tp)":{"service":1}
,"service":{"provider\u2019s":1}
,"provider\u2019s":{"network":1}
,"network":{"layer":1}
,"single":{"label":1}
,"switched":{"path":1}
,"path":{"(lsp)":1}
,"(lsp)":{"tunnel":1}
,"tunnel":{"two":1}
,"two":{"provider":1}
,"provider":{"edge":1}
,"edge":{"(pe)":1}
,"(pe)":{"routers":1}
}
;Search.control.loadWordPairs(pairs);
