var pairs =
{
"build":{"insmod":1}
,"insmod":{"hsl.o":1}
,"hsl.o":{"lot":1,"prefix":1}
,"lot":{"unresolved":1}
,"unresolved":{"symbols":1}
,"symbols":{"hsl.o":1,"bcmx_\u0022":1}
,"prefix":{"bcmx_\u0022":1}
,"bcmx_\u0022":{"resolve":1,"encountered":1}
,"resolve":{"unresolved":1}
,"encountered":{"available":1}
,"available":{"modules":1}
,"modules":{"linux-kernel-bde.o":1,"inserted":1,"--enable-l2lern":1}
,"linux-kernel-bde.o":{"linux-uk-proxy.o":1,"debug=2":1}
,"linux-uk-proxy.o":{"linux-bcm-diag-full.o":1,"$insmod":1}
,"linux-bcm-diag-full.o":{"above":1,"debug=2":1}
,"above":{"mentioned":1}
,"mentioned":{"modules":1}
,"inserted":{"starting":1}
,"starting":{".\u002Fbcm.user.proxy":1}
,".\u002Fbcm.user.proxy":{"$insmod":1}
,"$insmod":{"linux-kernel-bde.o":1,"linux-uk-proxy.o":1,"linux-bcm-diag-full.o":1}
,"debug=2":{"forceirq=2":1,"purpose":1}
,"forceirq=2":{"$insmod":1}
,"purpose":{"enable_tcp_message":1,"msoft-float":1}
,"enable_tcp_message":{"option":1}
,"option":{"happen":1,"disabled":1,"used":1,"--enable-tcp-message":1,"option":1,"turns":1}
,"happen":{"option":1}
,"disabled":{"--enable-tcp-message":1,"following":1,"software":1}
,"--enable-tcp-message":{"option":1,"tcp\u002Fip":1}
,"used":{"during":1,"interprocess":1,"enable":1}
,"during":{"compilation":1}
,"compilation":{"default":1}
,"default":{"option":1}
,"following":{"further":1}
,"further":{"describes":1}
,"describes":{"option":1}
,"tcp\u002Fip":{"sockets":1}
,"sockets":{"used":1}
,"interprocess":{"communication":1}
,"communication":{"daemons":1}
,"daemons":{"--disable-tcp-message":1,"purpose":1,"changes":1}
,"--disable-tcp-message":{"unix":1}
,"unix":{"domain":1}
,"domain":{"sockets":1}
,"msoft-float":{"option":1}
,"turns":{"software":1}
,"software":{"emulation":1,"learning":1}
,"emulation":{"floating-point":1}
,"floating-point":{"operations":1}
,"operations":{"turned":1,"meaning":1}
,"turned":{"underlying":1}
,"underlying":{"hardware":1}
,"hardware":{"support":1,"learning":1}
,"support":{"floating-point":1}
,"meaning":{"have_vrrp_link_addr":1}
,"have_vrrp_link_addr":{"vrrp":1}
,"vrrp":{"link-address":1,"router":1,"configuration":1}
,"link-address":{"virtual":1}
,"virtual":{"address":1}
,"address":{"added":1}
,"added":{"interface":1}
,"interface":{"allows":1}
,"allows":{"users":1}
,"users":{"connect":1}
,"connect":{"current":1}
,"current":{"master":1}
,"master":{"vrrp":1}
,"router":{"regardless":1}
,"regardless":{"whether":1}
,"whether":{"please":1}
,"please":{"refer":1}
,"refer":{"vrrp":1,"nsn\u002Fnsm_mac_acl_cli.c":1}
,"configuration":{"guide":1}
,"guide":{"details":1}
,"details":{"clean":1}
,"clean":{"layer-2":1,"layer2_module.o":1,"instead":1,"nsm":1}
,"layer-2":{"module":1,"object":1}
,"module":{"object":1}
,"object":{"files":1}
,"files":{"clean-layer2":1,"doing":1,"protocol":1,"\u002Fpal\u002Flinux\u002Fimi\u002F":1,"need":1}
,"clean-layer2":{"clean":1}
,"layer2_module.o":{"files":1}
,"doing":{"clean":1}
,"instead":{"clean-layer2":1}
,"protocol":{"modules":1}
,"--enable-l2lern":{"option":1}
,"enable":{"mac":1}
,"mac":{"access":1}
,"access":{"lists":1}
,"lists":{"bridges":1}
,"bridges":{"refer":1}
,"nsn\u002Fnsm_mac_acl_cli.c":{"commands":1}
,"commands":{"option":1}
,"learning":{"takes":1}
,"takes":{"place":1}
,"place":{"enabled":1,"bridge":1}
,"enabled":{"hardware":1}
,"bridge":{"modify":1}
,"modify":{"files":1}
,"\u002Fpal\u002Flinux\u002Fimi\u002F":{"necessary":1}
,"necessary":{"run":1}
,"run":{"config.sh":1}
,"config.sh":{"file":1,"again":1}
,"file":{"again":1}
,"again":{"daemons":1}
,"changes":{"zebos\u002Fpal\u002Flinux\u002Fimi\u002Fpal_*.c":1,"effect":1}
,"zebos\u002Fpal\u002Flinux\u002Fimi\u002Fpal_*.c":{"files":1}
,"need":{"clean":1,"run":1}
,"nsm":{"imi":1}
,"imi":{"imish":1}
,"imish":{"platform\u002Flinux":1}
,"platform\u002Flinux":{"folder":1}
,"folder":{"changes":1}
,"effect":{"need":1}
}
;Search.control.loadWordPairs(pairs);
