var pairs =
{
"vpls-mtu":{"command":1,"<576-65535>":1,"(<576-65535>":1,"6506":1}
,"command":{"maximum":1,"remove":1,"syntax":1,"mode":1}
,"maximum":{"transmission":1}
,"transmission":{"unit":1}
,"unit":{"(mtu)":1}
,"(mtu)":{"size":1}
,"size":{"given":1,"signaled":1,"setting":1,"allowed":1}
,"given":{"vpls":1}
,"vpls":{"instance":1,"routers":1,"mode":1,"test":1}
,"instance":{"size":1,"command":1}
,"signaled":{"peer":1}
,"peer":{"vpls":1}
,"routers":{"parameter":1}
,"parameter":{"command":1,"<576-65535>":1}
,"remove":{"mtu":1}
,"mtu":{"size":1}
,"setting":{"command":1}
,"syntax":{"vpls-mtu":1}
,"<576-65535>":{"vpls-mtu":1,"range":1}
,"(<576-65535>":{"parameter":1}
,"range":{"mtu":1}
,"allowed":{"vpls":1}
,"mode":{"vpls":1,"example":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"mpls":1}
,"mpls":{"vpls":1}
,"test":{"(config-vpls)":1}
,"(config-vpls)":{"vpls-mtu":1,"exit":1}
,"6506":{"(config-vpls)":1}
}
;Search.control.loadWordPairs(pairs);
