var pairs =
{
"ldp_snmp_api_getnext_adjacency":{"call":1,"(struct":1}
,"call":{"gets":1}
,"gets":{"parameters":1}
,"parameters":{"next":1,"ldp":1,"hold_rem":1}
,"next":{"adjacency":1}
,"adjacency":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ldp_snmp_api_getnext_adjacency":1}
,"(struct":{"ldp":1}
,"ldp":{"*ldp":1,"ldp":1,"instance":1,"entity":1,"peer":1,"index":1}
,"*ldp":{"struct":1}
,"struct":{"ldp_id":1}
,"ldp_id":{"*entity_id":1,"*peer_id":1}
,"*entity_id":{"s_int32_t":1}
,"s_int32_t":{"*entity_indx":1,"*hold_time":1}
,"*entity_indx":{"struct":1}
,"*peer_id":{"u_int32_t":1,"ldp":1}
,"u_int32_t":{"*indx":1,"*hold_rem":1,"*adj_type)":1}
,"*indx":{"u_int32_t":1}
,"*hold_rem":{"s_int32_t":1}
,"*hold_time":{"u_int32_t":1}
,"*adj_type)":{"input":1}
,"input":{"parameters":1}
,"instance":{"entity_id":1}
,"entity_id":{"ldp":1}
,"entity":{"entity_indx":1,"index":1}
,"entity_indx":{"ldp":1}
,"index":{"*peer_id":1,"output":1}
,"peer":{"indx":1}
,"indx":{"ldp":1}
,"output":{"parameters":1}
,"hold_rem":{"remaining":1}
,"remaining":{"hold":1}
,"hold":{"time":1}
,"time":{"adjacent":1}
,"adjacent":{"session":1}
,"session":{"hold_time":1,"adj_type":1,"type":1}
,"hold_time":{"hold":1}
,"adj_type":{"adjacent":1}
,"type":{"either":1}
,"either":{"leaf_mplsldphelloadjtype_link":1}
,"leaf_mplsldphelloadjtype_link":{"leaf_mplsldphelloadjtype_targeted":1}
,"leaf_mplsldphelloadjtype_targeted":{"return":1}
,"return":{"values":1}
,"values":{"ldp_success":1}
,"ldp_success":{"ldp_false":1}
}
;Search.control.loadWordPairs(pairs);
