var pairs =
{
"show":{"mpls":1}
,"mpls":{"out-segment-table":1}
,"out-segment-table":{"command":1,"parameters":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"detailed":1}
,"detailed":{"information":1}
,"information":{"out-segment":1}
,"out-segment":{"entries":1}
,"entries":{"(also":1}
,"(also":{"known":1}
,"known":{"nhlfe)":1}
,"nhlfe)":{"table":1}
,"table":{"command":1}
,"syntax":{"show":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"show":1}
}
;Search.control.loadWordPairs(pairs);
