var pairs =
{
"clear":{"command":1,"attribute":1,"(ccm-ltm-priority":1,"(config-if-eth-cfm-mep))":1,"active":1}
,"command":{"clear":1,"syntax":1,"mode":1}
,"attribute":{"values":1,"cleared":1}
,"values":{"link-level":1}
,"link-level":{"mep":1}
,"mep":{"attribute":1,"tx-lbm-status":1,"tx-lbm-destination-is-mepid":1,"tx-lbm-messages":1,"ltm":1,"source":1,"tx-ltm-ttl":1,"down":1}
,"cleared":{"reset":1,"reset-fng-time":1}
,"reset":{"default":1,"fng":1}
,"default":{"value":1}
,"value":{"command":1,"fng-alarm-time":1,"ltm":1}
,"syntax":{"clear":1}
,"(ccm-ltm-priority":{"lowest-priority-defect":1}
,"lowest-priority-defect":{"fng-alarm-time":1,"lowest":1}
,"fng-alarm-time":{"reset-fng-time":1,"time":1}
,"reset-fng-time":{"active":1,"reset":1}
,"active":{"tx-lbm-status":1,"administrative":1,"true":1}
,"tx-lbm-status":{"tx-lbm-destination-mac":1,"transmit":1}
,"tx-lbm-destination-mac":{"tx-lbm-destination-mepid":1,"destination":1}
,"tx-lbm-destination-mepid":{"tx-lbm-destination-is-mepid":1,"transmit":1}
,"tx-lbm-destination-is-mepid":{"tx-lbm-messages":1,"transmit":1}
,"tx-lbm-messages":{"tx-lbm-data-tlv":1,"transmit":1}
,"tx-lbm-data-tlv":{"tx-lbm-vlan-priority":1,"transmit":1}
,"tx-lbm-vlan-priority":{"tx-lbm-vlan-drop-enable":1,"transmit":1}
,"tx-lbm-vlan-drop-enable":{"tx-lbm-time-out-value":1,"enable":1}
,"tx-lbm-time-out-value":{"ccm-ltm-flags":1,"loopback":1}
,"ccm-ltm-flags":{"tx-ltm-target-mac":1,"transmit":1}
,"tx-ltm-target-mac":{"tx-ltm-target-mepid":1,"mac":1}
,"tx-ltm-target-mepid":{"tx-ltm-target-is-mepid":1,"target":1}
,"tx-ltm-target-is-mepid":{"tx-ltm-ttl":1,"ltm":1}
,"tx-ltm-ttl":{"tx-ltm-egress-id":1,"ttl":1}
,"tx-ltm-egress-id":{"tx-lbr-time-out-value":1,"transmit":1}
,"tx-lbr-time-out-value":{"all)":1,"loopback":1}
,"all)":{"parameters":1}
,"parameters":{"ccm-ltm-priority":1}
,"ccm-ltm-priority":{"ccm":1}
,"ccm":{"linktrace":1}
,"linktrace":{"message":1}
,"message":{"priority":1,"status":1,"timeout":1}
,"priority":{"lowest-priority-defect":1,"defect":1,"tx-lbm-vlan-drop-enable":1}
,"lowest":{"priority":1}
,"defect":{"value":1,"absent":1}
,"time":{"defect":1,"active":1}
,"absent":{"alarm":1}
,"alarm":{"cleared":1}
,"fng":{"time":1}
,"administrative":{"state":1}
,"state":{"mep":1}
,"transmit":{"loopback":1,"lbm":1,"ltm":1}
,"loopback":{"message":1,"reception":1}
,"status":{"tx-lbm-destination-mac":1}
,"destination":{"mac":1,"mep":1,"source":1}
,"mac":{"address":1}
,"address":{"lbm":1,"tx-ltm-target-mac":1,"target":1}
,"lbm":{"tx-lbm-destination-mepid":1,"destination":1,"tx-lbm-data-tlv":1,"data":1,"vlan":1}
,"source":{"mep":1}
,"data":{"tlv":1}
,"tlv":{"tx-lbm-vlan-priority":1}
,"vlan":{"priority":1,"tx-lbm-time-out-value":1,"bridge":1}
,"enable":{"drop":1}
,"drop":{"transmit":1}
,"timeout":{"ccm-ltm-flags":1,"attributes":1}
,"ltm":{"target":1,"transmission":1,"egress":1}
,"target":{"mac":1,"mep":1}
,"transmission":{"tx-ltm-target-mepid":1,"tx-ltm-target-is-mepid":1,"target":1,"tx-ltm-egress-id":1}
,"ttl":{"value":1}
,"egress":{"tx-lbr-time-out-value":1}
,"reception":{"timeout":1}
,"attributes":{"command":1}
,"mode":{"interface":1,"examples":1}
,"interface":{"mode":1,"eth1":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth1":{"(config-if)":1}
,"(config-if)":{"ethernet":1}
,"ethernet":{"cfm":1}
,"cfm":{"mep":1}
,"down":{"mpid":1}
,"mpid":{"active":1}
,"true":{"domain":1}
,"domain":{"abc":1}
,"abc":{"vlan":1}
,"bridge":{"(config-if-eth-cfm-mep)":1}
,"(config-if-eth-cfm-mep)":{"clear":1}
,"(config-if-eth-cfm-mep))":{"clear":1}
}
;Search.control.loadWordPairs(pairs);
