var pairs =
{
"ldp":{"keepalive-timeout":1,"peers":1,"process":1}
,"keepalive-timeout":{"command":1,"<30-65535>":1,"parameters":1,"635":1}
,"command":{"keep-alive":1,"time":1,"interface-specific":1,"overrides":1,"parameter":1,"syntax":1,"mode":1}
,"keep-alive":{"time-out":1,"messages":1,"timer":1,"packet":1,"interval":1}
,"time-out":{"value":1,"main":1,"timer":1}
,"value":{"rejecting":1,"three":1,"command":1,"lsr":1,"seconds":1}
,"rejecting":{"session":1}
,"session":{"peer":1}
,"peer":{"command":1,"question":1}
,"time":{"period":1,"keep-alive":1}
,"period":{"lsr":1}
,"lsr":{"wait":1,"using":1}
,"wait":{"successive":1}
,"successive":{"keep-alive":1}
,"messages":{"ldp":1}
,"peers":{"keep-alive":1}
,"timer":{"reset":1,"specific":1}
,"reset":{"every":1}
,"every":{"time":1}
,"packet":{"received":1}
,"received":{"peer":1}
,"question":{"optimum":1}
,"optimum":{"performance":1}
,"performance":{"value":1}
,"three":{"times":1}
,"times":{"keep-alive":1}
,"interval":{"value":1}
,"interface-specific":{"command":1}
,"overrides":{"value":1}
,"using":{"global":1}
,"global":{"keepalive-timeout":1}
,"parameter":{"revert":1}
,"revert":{"keep-alive":1}
,"main":{"ldp":1}
,"process":{"command":1}
,"syntax":{"ldp":1}
,"<30-65535>":{"ldp":1,"specify":1}
,"parameters":{"<30-65535>":1}
,"specify":{"value":1}
,"seconds":{"command":1}
,"mode":{"interface":1,"example":1}
,"interface":{"mode":1,"configure":1,"eth0":1}
,"example":{"example":1,"shows":1}
,"shows":{"keep-alive":1}
,"specific":{"interface":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"ldp":1}
,"635":{"(config-if)":1}
}
;Search.control.loadWordPairs(pairs);
