var pairs =
{
"mld":{"snooping":1}
,"snooping":{"mrouter":1,"vlan":1}
,"mrouter":{"command":1,"interface":1}
,"command":{"statically":1,"remove":1,"syntax":1,"mode":1}
,"statically":{"configure":1}
,"configure":{"specified":1,"terminal":1}
,"specified":{"vlan":1}
,"vlan":{"constituent":1,"parameter":1,"interface":1}
,"constituent":{"interface":1}
,"interface":{"multicast":1,"mld":1,"command":1,"ifname":1,"mode":1,"example":1,"vlan1.1":1,"fe8":1}
,"multicast":{"router":1}
,"router":{"interface":1,"configure":1}
,"parameter":{"command":1}
,"remove":{"static":1}
,"static":{"configuration":1}
,"configuration":{"interface":1}
,"syntax":{"mld":1}
,"ifname":{"mld":1,"parameters":1,"specify":1}
,"parameters":{"ifname":1}
,"specify":{"name":1,"next-hop":1}
,"name":{"interface":1}
,"mode":{"interface":1,"vlan":1}
,"example":{"example":1,"shows":1}
,"shows":{"specify":1}
,"next-hop":{"interface":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"vlan1.1":{"(config-if)":1}
,"(config-if)":{"mld":1}
}
;Search.control.loadWordPairs(pairs);
