var pairs =
{
"step":{"configure":1}
,"configure":{"bandwidth":1}
,"bandwidth":{"constraint":1,"configure":1,"constraints":1,"divided":1,"100m":1}
,"constraint":{"enable":1,"class":1}
,"enable":{"label":1}
,"label":{"switching":1}
,"switching":{"interface":1}
,"interface":{"eth1":1,"reserve":1,"bandwidth":1}
,"eth1":{"corresponding":1,"interface":1,"label-switching":1}
,"corresponding":{"address":1}
,"address":{"interface":1}
,"reserve":{"bandwidth":1}
,"class":{"type":1,"types":1}
,"type":{"eth1":1}
,"constraints":{"defined":1}
,"defined":{"100":1,"class":1}
,"100":{"reservable":1}
,"reservable":{"bandwidth":1}
,"divided":{"among":1}
,"among":{"defined":1}
,"types":{"priority":1}
,"priority":{"assignments":1}
,"assignments":{"guarantee":1}
,"guarantee":{"data":1}
,"data":{"voice-low":1,"cannot":1,"default":1,"20m":1}
,"voice-low":{"default":1,"however":1,"pre-empt":1,"20m":1}
,"default":{"lsps":1,"data":1,"10m":1}
,"lsps":{"cannot":1,"r1-nsm":1}
,"cannot":{"pre-empt":1}
,"pre-empt":{"voice-high":1,"voice-low":1,"data":1}
,"voice-high":{"lsp":1,"voice-low":1,"50m":1}
,"lsp":{"similarly":1}
,"similarly":{"default":1}
,"however":{"voice-high":1}
,"r1-nsm":{"interface":1}
,"label-switching":{"ip-address":1}
,"ip-address":{"172.168.1.1\u002F24":1}
,"172.168.1.1\u002F24":{"bandwidth":1}
,"100m":{"reservable-bandwidth":1,"bandwidth-constraint":1}
,"reservable-bandwidth":{"100m":1}
,"bandwidth-constraint":{"voice-high":1,"voice-low":1,"data":1,"default":1}
,"50m":{"bandwidth-constraint":1}
,"20m":{"bandwidth-constraint":1}
,"10m":{"enable-rsvp":1}
}
;Search.control.loadWordPairs(pairs);
