var pairs =
{
"bgp":{"g-shut-capable":1,"neighbor":1,"sessions":1,"100":1}
,"g-shut-capable":{"command":1,"bgp":1,"parameters":1,"configure":1}
,"command":{"enable":1,"disable":1,"syntax":1,"mode":1}
,"enable":{"graceful":1}
,"graceful":{"shutdown":1}
,"shutdown":{"capability":1,"state":1,"initiated":1}
,"capability":{"router":1,"border":1,"cannot":1,"disabled":1}
,"router":{"level":1,"bgp":1,"details":1,"graceful":1,"mode":1}
,"level":{"available":1,"command":1}
,"available":{"graceful-shutdown":1}
,"graceful-shutdown":{"related":1}
,"related":{"commands":1}
,"commands":{"router":1}
,"neighbor":{"levels":1}
,"levels":{"parameter":1}
,"parameter":{"command":1}
,"disable":{"graceful":1}
,"details":{"graceful":1}
,"border":{"gateway":1}
,"gateway":{"protocol":1}
,"protocol":{"developer":1}
,"developer":{"guide":1}
,"guide":{"graceful":1}
,"cannot":{"disabled":1}
,"disabled":{"router":1}
,"state":{"until":1}
,"until":{"comes":1}
,"comes":{"state--after":1}
,"state--after":{"graceful":1}
,"initiated":{"impacted":1}
,"impacted":{"bgp":1}
,"sessions":{"again":1}
,"again":{"command":1}
,"syntax":{"bgp":1}
,"parameters":{"none":1}
,"none":{"default":1}
,"default":{"default":1,"graceful":1}
,"mode":{"router":1,"examples":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"100":{"(config-router)":1}
,"(config-router)":{"bgp":1}
}
;Search.control.loadWordPairs(pairs);
