var pairs =
{
"unicast":{"ptp":1,"neighbor":1,"interface":1,"neighbors":1,"enable":1}
,"ptp":{"configuration":1,"ordinary":1,"configure":1,"data":1,"port":1,"version":1,"unicast-neighbors":1,"unicast":1}
,"configuration":{"zebos1":1}
,"zebos1":{"configure":1,"show":1}
,"configure":{"terminal":1,"mode":1,"ptp":1,"priority":1,"interface":1,"eth1":1}
,"terminal":{"enter":1}
,"enter":{"configure":1}
,"mode":{"(config)":1,"validation":1}
,"(config)":{"bridge":1,"interface":1}
,"bridge":{"protocol":1,"mstp":1,"group":1}
,"protocol":{"mstp":1}
,"mstp":{"create":1,"bridge*(config)":1}
,"create":{"bridge":1}
,"bridge*(config)":{"ptp-clk":1}
,"ptp-clk":{"ordinary":1}
,"ordinary":{"transport-type":1,"clock":1}
,"transport-type":{"ethernet":1}
,"ethernet":{"delay-mechanism":1,"(this":1,"5254.fe00.ce45":1,"4545.89e4.8765":1}
,"delay-mechanism":{"p2p":1}
,"p2p":{"configure":1}
,"clock":{"ethernet":1,"port":1,"(ordinary)":1,"identity":1,"quality":1}
,"(this":{"step":1}
,"step":{"mandatory":1,"flag":1}
,"mandatory":{"good":1}
,"good":{"practice":1}
,"practice":{"avoid":1}
,"avoid":{"layer":1}
,"layer":{"loops)":1,"port":1}
,"loops)":{"(config-ptp-clk)":1}
,"(config-ptp-clk)":{"priority1":1,"priority2":1,"exit":1}
,"priority1":{"configure":1,"priority2:1":1}
,"priority":{"(config-ptp-clk)":1,"default":1}
,"priority2":{"configure":1}
,"exit":{"exit":1,"ptp":1,"port":1}
,"interface":{"eth1":1}
,"eth1":{"configure":1,"(config-if)":1,"layer":1,"bridge":1,"clock":1,"(config-clk-port)":1,"ptp":1}
,"(config-if)":{"switchport":1,"bridge-group":1,"clock-port":1}
,"switchport":{"configure":1}
,"port":{"(config-if)":1,"(config-clk-port)":1,"configure":1,"data":1,"===========================================port":1,"clock":1,"number":1}
,"bridge-group":{"configure":1}
,"group":{"(config-if)":1}
,"clock-port":{"configure":1}
,"(config-clk-port)":{"unicast-neighbor-add":1,"ptp-unicast-enable":1,"ptp-unicast-disable":1,"unicast-neighbor-del":1,"exit":1}
,"unicast-neighbor-add":{"addr-type":1}
,"addr-type":{"ethernet":1}
,"5254.fe00.ce45":{"adding":1}
,"adding":{"unicast":1}
,"neighbor":{"(config-clk-port)":1}
,"ptp-unicast-enable":{"max-table-size":1}
,"max-table-size":{"enabling":1}
,"enabling":{"unicast":1}
,"ptp-unicast-disable":{"disable":1}
,"disable":{"unicast":1}
,"unicast-neighbor-del":{"addr-type":1}
,"4545.89e4.8765":{"deleting":1}
,"deleting":{"unicast":1}
,"validation":{"verify":1}
,"verify":{"priority":1,"message":1,"unicast":1}
,"default":{"data":1,"clock":1}
,"data":{"zebos1":1,"default":1}
,"show":{"ptp":1}
,"(ordinary)":{"two":1}
,"two":{"step":1}
,"flag":{":yes":1}
,":yes":{"clock":1}
,"identity":{"ff:fe:52:54:0:ed:a9:5":1}
,"ff:fe:52:54:0:ed:a9:5":{"number":1,"port":1}
,"number":{"ports:1":1,"min":1}
,"ports:1":{"priority1":1}
,"priority2:1":{"domain":1}
,"domain":{"number:0":1}
,"number:0":{"slave":1}
,"slave":{"only:no":1}
,"only:no":{"clock":1}
,"quality":{"class":1}
,"class":{"248":1}
,"248":{"accuracy:254":1}
,"accuracy:254":{"offset":1}
,"offset":{"(log":1}
,"(log":{"variance)":1,"base":1}
,"variance)":{":ffff":1}
,":ffff":{"verify":1}
,"message":{"intervals":1}
,"intervals":{"port":1}
,"===========================================port":{"state":1}
,"state":{"[ptp_listening]":1}
,"[ptp_listening]":{"port":1}
,"min":{"delay":1}
,"delay":{"req":1,"mechanism":1,"request":1}
,"req":{"interval":1}
,"interval":{"(log":1}
,"base":{"peer":1,"announce":1,"delay":1,"ptp":1}
,"peer":{"mean":1,"peer":1,"delay":1}
,"mean":{"path":1}
,"path":{"delay:0":1}
,"delay:0":{"announce":1}
,"announce":{"interval":1,"receipt":1}
,"receipt":{"timeout":1}
,"timeout":{"sync":1}
,"sync":{"interval":1}
,"mechanism":{"peer":1}
,"request":{"interval":1}
,"version":{"verify":1}
,"neighbors":{"added":1,"5454.23e4.edfc":1}
,"added":{"show":1}
,"unicast-neighbors":{"===========================================%":1}
,"===========================================%":{"interface":1}
,"enable":{"configured":1}
,"configured":{"unicast":1}
,"5454.23e4.edfc":{"===========================================":1}
}
;Search.control.loadWordPairs(pairs);
