var pairs =
{
"oam_mplstp_api_itut_config_fng":{"function":1,"(u_int32_t":1}
,"function":{"enables":1,"implements":1,"fails":1,"succeeds":1}
,"enables":{"fault":1}
,"fault":{"alarm":1}
,"alarm":{"feature":1,"time":1}
,"feature":{"function":1}
,"implements":{"fault-alarm":1}
,"fault-alarm":{"command":1}
,"command":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"oam_mplstp_api_itut_config_fng":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"instance":1}
,"char":{"*meg_name":1}
,"*meg_name":{"u_int16_t":1}
,"u_int16_t":{"mp_id":1}
,"mp_id":{"u_int8_t":1,"priority":1,"valid":1}
,"u_int8_t":{"priority":1}
,"priority":{"u_int32_t":1,"priority":1,"alarm_time":1,"valid":1}
,"u_int32_t":{"alarm_time":1,"reset_time)":1}
,"alarm_time":{"u_int32_t":1,"alarm":1}
,"reset_time)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"instance":{"meg_name":1}
,"meg_name":{"meg":1}
,"meg":{"name":1,"entry":1}
,"name":{"mp_id":1}
,"time":{"reset_time":1,"output":1}
,"reset_time":{"reset":1}
,"reset":{"time":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"mplstp_err_vr_not_exists":1}
,"mplstp_err_vr_not_exists":{"virtual":1}
,"virtual":{"router":1}
,"router":{"cannot":1}
,"cannot":{"found":1}
,"found":{"mplstp_err_meg_entry_not_exists":1,"mplstp_err_me_entry_not_exists":1,"mplstp_err_cc_enabled":1}
,"mplstp_err_meg_entry_not_exists":{"meg":1}
,"entry":{"cannot":1}
,"mplstp_err_me_entry_not_exists":{"entry":1}
,"mplstp_err_cc_enabled":{"continuity":1}
,"continuity":{"checking":1}
,"checking":{"already":1}
,"already":{"enabled":1}
,"enabled":{"mplstp_err_inavlid_fng_priority":1}
,"mplstp_err_inavlid_fng_priority":{"priority":1}
,"valid":{"mplstp_err_invalid_mp_id":1,"mplstp_api_failure":1}
,"mplstp_err_invalid_mp_id":{"mp_id":1}
,"mplstp_api_failure":{"function":1}
,"fails":{"mplstp_api_success":1}
,"mplstp_api_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
