var pairs =
{
"ospf6_passive_if_unset":{"function":1,"(u_int32_t":1}
,"function":{"unsets":1,"called":1,"succeeds":1}
,"unsets":{"passive":1}
,"passive":{"interface":1}
,"interface":{"configuration":1,"name":1}
,"configuration":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"passive-interface":1}
,"passive-interface":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf6_passive_if_unset":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1}
,"char":{"*tag":1,"*name)":1}
,"*tag":{"char":1}
,"*name)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"exist":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"tag":1}
,"tag":{"ospfv3":1,"name":1}
,"ospfv3":{"process":1}
,"process":{"tag":1,"exist":1}
,"name":{"interface":1,"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf6_api_set_err_vr_not_exist":1}
,"ospf6_api_set_err_vr_not_exist":{"virtual":1}
,"exist":{"ospf6_api_set_err_process_not_exist":1,"ospf6_api_set_success":1}
,"ospf6_api_set_err_process_not_exist":{"specified":1}
,"specified":{"process":1}
,"ospf6_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
