var pairs =
{
"show":{"mpls":1,"ldp":1}
,"mpls":{"ldp":1}
,"ldp":{"graceful-restart":1,"session":1}
,"graceful-restart":{"command":1,"related":1,"parameter":1,"peer":1}
,"command":{"show":1,"syntax":1,"mode":1}
,"session":{"graceful-restart":1}
,"related":{"values":1}
,"values":{"command":1}
,"syntax":{"show":1}
,"parameter":{"none":1}
,"none":{"command":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"following":1}
,"following":{"sample":1}
,"sample":{"output":1}
,"output":{"show":1}
,"peer":{"address":1}
,"address":{"name":1}
,"name":{"restart":1}
,"restart":{"state":1}
,"state":{"timers":1}
,"timers":{"running":1}
,"running":{"192.168.201.3":1}
,"192.168.201.3":{"eth3":1}
,"eth3":{"capable":1}
,"capable":{"operational":1}
,"operational":{"192.168.201.4":1}
,"192.168.201.4":{"eth4":1}
,"eth4":{"capable":1}
}
;Search.control.loadWordPairs(pairs);
