var pairs =
{
"data":{"flow":1}
,"flow":{"description":1,"connectivity":1,"port":1,"frames":1,"points":1,"double-tagged":1}
,"description":{"following":1}
,"following":{"section":1,"frame":1}
,"section":{"describes":1}
,"describes":{"different":1}
,"different":{"logical":1,"untagged":1}
,"logical":{"frame":1}
,"frame":{"flow":1,"port":1,"default":1,"sent":1,"frame":1,"double-tagged":1,"c-vid":1,"relayed":1,"c-tagged":1,"system":1,"simply":1,"contains":1,"based":1,"forwarded":1,"tagged":1,"nsm":1,"untagged":1,"s-tag":1,"put":1,"c-tag":1,"egress":1}
,"connectivity":{"fault":1}
,"fault":{"management":1}
,"management":{"(cfm)":1}
,"(cfm)":{"support":1}
,"support":{"provider":1}
,"provider":{"edge":1}
,"edge":{"bridge":1}
,"bridge":{"(peb)":1}
,"(peb)":{"port":1}
,"port":{"receives":1,"configured":1,"equals":1,"member":1,"port":1,"s-vlan":1,"mip\u002Fmep":1,"frames":1,"untagged_vid":1,"onmd":1,"following":1,"sends":1,"list":1,"identified":1,"c-vid":1,"default":1,"used":1,"egress":1,"c-tag":1,"untagged":1,"incoming":1,"c-vlan":1}
,"receives":{"untagged":1,"tagged":1}
,"untagged":{"frames":1,"frame":1,"c-vid":1,"vid":1,"vlan":1,"egress-tagged":1}
,"frames":{"following":1,"port":1,"c-tagged":1,"relayed":1,"(s-tagged)":1,"seen":1,"coming":1,"containing":1}
,"configured":{"untagged":1,"port":1,"s-vlan":1,"send":1,"single-tagged":1,"different":1,"double-tagged":1,"frames":1,"frame":1}
,"c-vid":{"customer":1,"(maintenance":1,"equals":1,"frame":1,"software":1,"header":1,"port":1}
,"customer":{"equipment":1}
,"equipment":{"sends":1,"frame":1}
,"sends":{"untagged":1,"tagged":1,"s-tagged":1,"double-tagged":1,"frame":1,"maintenance":1}
,"default":{"vid":1}
,"vid":{"port":1,"frame":1}
,"equals":{"port\u2019s":1,"vid":1,"port":1}
,"port\u2019s":{"untagged":1}
,"sent":{"onmd":1,"customer":1,"port":1}
,"onmd":{"otherwise":1,"(ce":1,"software":1}
,"otherwise":{"relayed":1,"frame":1}
,"relayed":{"software":1,"ports":1,"double-tagged":1,"port":1}
,"software":{"forwarder":1}
,"forwarder":{"onmd":1,"builds":1,"adds":1,"puts":1}
,"(ce":{"port)":1}
,"port)":{"check":1}
,"check":{"done":1,"mep\u002Fmips":1,"note":1}
,"done":{"port":1,"frame":1}
,"member":{"s-vlan":1}
,"s-vlan":{"s-vlan":1,"configured":1,"therefore":1,"untagged":1,"mapping":1,"port":1,"configured)":1,"mip\u002Fmep":1}
,"therefore":{"system":1}
,"system":{"retrieves":1,"check":1,"loops":1,"checks":1}
,"retrieves":{"port":1}
,"vlan":{"equals":1,"configured":1}
,"double-tagged":{"means":1,"onmd":1,"frames":1,"frame":1}
,"means":{"port":1}
,"send":{"untagged":1}
,"mip\u002Fmep":{"responds":1,"check":1}
,"responds":{"frames":1}
,"c-tagged":{"port":1,"frame":1}
,"ports":{"s-vlan":1}
,"single-tagged":{"frames":1}
,"(s-tagged)":{"seen":1}
,"seen":{"core":1}
,"core":{"port":1,"software":1,"mip\u002Fmep":1}
,"tagged":{"frame":1,"c-tag":1}
,"(maintenance":{"c-vid)":1}
,"c-vid)":{"customer":1}
,"untagged_vid":{"frame":1}
,"builds":{"c-tag":1}
,"c-tag":{"frame":1,"relayed":1,"given":1,"based":1,"mip\u002Fmep":1,"port":1,"sends":1}
,"mep\u002Fmips":{"s-vlan":1}
,"mapping":{"c-vid":1,"found":1}
,"simply":{"relayed":1}
,"adds":{"s-tag":1,"c-vid":1}
,"s-tag":{"frame":1,"stripped":1}
,"coming":{"port":1}
,"s-tagged":{"frame":1}
,"loops":{"s-vlan":1}
,"list":{"(that":1}
,"(that":{"ports":1}
,"configured)":{"once":1}
,"once":{"port":1}
,"identified":{"system":1}
,"checks":{"whether":1}
,"whether":{"frame":1}
,"contains":{"c-tag":1}
,"puts":{"tag":1}
,"tag":{"frame":1}
,"based":{"port":1,"configuration":1}
,"containing":{"c-tag":1}
,"given":{"cfm":1}
,"cfm":{"flow":1}
,"points":{"frame":1,"(ltm)":1}
,"forwarded":{"cfm":1}
,"(ltm)":{"port":1}
,"used":{"(c-vid)":1}
,"(c-vid)":{"frame":1}
,"configuration":{"port":1}
,"egress":{"tagging":1}
,"tagging":{"configured":1}
,"nsm":{"software":1}
,"header":{"otherwise":1}
,"egress-tagged":{"untagged":1}
,"stripped":{"frame":1}
,"put":{"port":1}
,"note":{"done":1}
,"maintenance":{"c-tagged":1}
,"incoming":{"c-vid":1}
,"c-vlan":{"mapping":1}
,"found":{"check":1}
}
;Search.control.loadWordPairs(pairs);
