var pairs =
{
"dot1x":{"quiet-period":1,"protocol":1}
,"quiet-period":{"command":1,"time":1,"interval":1,"<1-65535>":1,"parameter":1,"200":1}
,"command":{"quiet-period":1,"configured":1,"syntax":1,"mode":1}
,"time":{"interval":1,"tries":1,"provided":1}
,"interval":{"switch":1,"time":1,"entering":1}
,"switch":{"cannot":1,"remains":1}
,"cannot":{"authenticate":1}
,"authenticate":{"client":1}
,"client":{"switch":1}
,"remains":{"idle":1}
,"idle":{"quiet-period":1}
,"tries":{"again":1}
,"again":{"administratively":1}
,"administratively":{"changing":1}
,"changing":{"quiet-period":1}
,"entering":{"lower":1}
,"lower":{"number":1}
,"number":{"default":1}
,"default":{"faster":1,"(60":1,"default":1,"dot1x":1}
,"faster":{"response":1}
,"response":{"time":1}
,"provided":{"parameter":1}
,"parameter":{"command":1,"<1-65535>":1}
,"configured":{"quiet":1}
,"quiet":{"period":1}
,"period":{"default":1}
,"(60":{"seconds)":1}
,"seconds)":{"command":1}
,"syntax":{"dot1x":1}
,"<1-65535>":{"dot1x":1,"seconds":1}
,"seconds":{"retrial":1}
,"retrial":{"authentication":1}
,"authentication":{"default":1}
,"protocol":{"version":1}
,"version":{"command":1}
,"mode":{"interface":1,"example":1}
,"interface":{"mode":1,"eth0":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"dot1x":1}
}
;Search.control.loadWordPairs(pairs);
