var pairs =
{
"ldp_snmp_api_get_peer":{"call":1,"(struct":1}
,"call":{"gets":1}
,"gets":{"peer":1}
,"peer":{"parameters":1,"output":1,"value":1,"peertransaddrtype":1,"return":1}
,"parameters":{"syntax":1,"ldp":1,"adv_mode":1}
,"syntax":{"int":1}
,"int":{"ldp_snmp_api_get_peer":1}
,"(struct":{"ldp":1}
,"ldp":{"*ldp":1,"ldp":1,"instance":1,"entity":1,"peer":1}
,"*ldp":{"struct":1}
,"struct":{"ldp_id":1,"pal_in4_addr":1}
,"ldp_id":{"*entity_id":1,"*peer_id":1}
,"*entity_id":{"s_int32_t":1}
,"s_int32_t":{"entity_indx":1,"*peertransaddrtype":1}
,"entity_indx":{"struct":1,"ldp":1}
,"*peer_id":{"u_int32_t":1}
,"u_int32_t":{"*adv_mode":1,"*path_vector_limit":1}
,"*adv_mode":{"u_int32_t":1}
,"*path_vector_limit":{"s_int32_t":1}
,"*peertransaddrtype":{"struct":1}
,"pal_in4_addr":{"*peertransaddr)":1}
,"*peertransaddr)":{"input":1}
,"input":{"parameters":1}
,"instance":{"entity_id":1}
,"entity_id":{"ldp":1}
,"entity":{"entity_indx":1,"index":1}
,"index":{"peer_id":1}
,"peer_id":{"ldp":1}
,"output":{"parameters":1}
,"adv_mode":{"advertisement":1}
,"advertisement":{"mode":1}
,"mode":{"peer":1}
,"value":{"used":1}
,"used":{"either":1,"snmp_ag_addr_type_ipv4":1}
,"either":{"leaf_mplsldppeerlabeldistmethod_downstreamondemand":1}
,"leaf_mplsldppeerlabeldistmethod_downstreamondemand":{"leaf_mplsldppeerlabeldistmethod_downstreamunsolicited":1}
,"leaf_mplsldppeerlabeldistmethod_downstreamunsolicited":{"path_vector_limit":1}
,"path_vector_limit":{"path":1}
,"path":{"vector":1}
,"vector":{"limit":1}
,"limit":{"peer":1}
,"peertransaddrtype":{"transport":1}
,"transport":{"address":1}
,"address":{"type":1,"peer":1}
,"type":{"peer":1}
,"snmp_ag_addr_type_ipv4":{"peertransaddr":1}
,"peertransaddr":{"transport":1}
,"return":{"values":1}
,"values":{"ldp_success":1}
,"ldp_success":{"ldp_false":1}
}
;Search.control.loadWordPairs(pairs);
