var pairs =
{
"ilm":{"table":1}
,"table":{"ilm":1,"needs":1}
,"needs":{"support":1}
,"support":{"concept":1}
,"concept":{"associated":1}
,"associated":{"backup":1}
,"backup":{"nhlfe":1,"entry":1,"lsp":1}
,"nhlfe":{"entries":1,"information":1}
,"entries":{"given":1}
,"given":{"incoming":1}
,"incoming":{"label":1}
,"label":{"entry":1,"nexthop":1}
,"entry":{"backup":1,"contains":1}
,"contains":{"nhlfe":1}
,"information":{"(such":1}
,"(such":{"outgoing":1}
,"outgoing":{"label":1}
,"nexthop":{"interface)":1}
,"interface)":{"signaled":1}
,"signaled":{"backup":1}
,"lsp":{"data":1}
,"data":{"installed":1}
,"installed":{"forwarder":1}
,"forwarder":{"event":1}
,"event":{"failure":1}
,"failure":{"protected":1}
,"protected":{"lsp":1}
}
;Search.control.loadWordPairs(pairs);
