var pairs =
{
"ldp_interface":{"data":1,"{\u002F*primary":1}
,"data":{"structure":1,"**when":1}
,"structure":{"defined":1,"*\u002Fstruct":1}
,"defined":{"ldpd\u002Fldp_interface.h":1}
,"ldpd\u002Fldp_interface.h":{"file":1}
,"file":{"definition":1}
,"definition":{"struct":1}
,"struct":{"ldp_interface":1,"thread":1}
,"{\u002F*primary":{"address":1}
,"address":{"*\u002Fstruct":1,"*\u002Fu_char":1}
,"*\u002Fstruct":{"pal_in4_addr":1,"pal_in6_addr":1,"interface":1,"thread":1,"ls_to_addr":1,"label_space_data":1}
,"pal_in4_addr":{"primary_addr":1}
,"primary_addr":{"ifdef":1}
,"ifdef":{"have_ipv6":1}
,"have_ipv6":{"\u002F*primary":1,"struct":1,"u_char":1}
,"\u002F*primary":{"ipv6":1}
,"ipv6":{"address":1,"enabled":1}
,"pal_in6_addr":{"primary_addr6":1}
,"primary_addr6":{"endif":1}
,"endif":{"\u002F*have_ipv6":1}
,"\u002F*have_ipv6":{"*\u002F\u002F*interface":1,"*\u002F\u002F*pointer":1,"*\u002F\u002F*flag":1}
,"*\u002F\u002F*interface":{"structure":1}
,"interface":{"*ifp":1,"*\u002Fu_int16_t":1,"dont":1,"affected":1,"structure":1,"enabled":1}
,"*ifp":{"u_int32_t":1}
,"u_int32_t":{"config_seq_num":1}
,"config_seq_num":{"\u002F*accept":1}
,"\u002F*accept":{"socket":1}
,"socket":{"tcp":1}
,"tcp":{"connects":1}
,"connects":{"*\u002Fint":1}
,"*\u002Fint":{"accept_sock":1,"accept_count":1}
,"accept_sock":{"\u002F*thread":1}
,"\u002F*thread":{"read":1}
,"read":{"accept":1}
,"accept":{"sock":1,"*\u002Fint":1}
,"sock":{"*\u002Fstruct":1}
,"thread":{"*t_accept":1,"*t_hello":1,"*ipv6_t_hello":1}
,"*t_accept":{"\u002F*count":1}
,"\u002F*count":{"passive":1}
,"passive":{"sessions":1}
,"sessions":{"waiting":1}
,"waiting":{"accept":1}
,"accept_count":{"\u002F*timer":1}
,"\u002F*timer":{"configuration":1}
,"configuration":{"*\u002Fu_int32_t":1,"*\u002Fu_int16_t":1}
,"*\u002Fu_int32_t":{"reconnect_timeout":1,"pdu_length":1,"config":1}
,"reconnect_timeout":{"\u002F*pdu":1}
,"\u002F*pdu":{"length":1}
,"length":{"*\u002Fu_int32_t":1}
,"pdu_length":{"\u002F*ldp":1}
,"\u002F*ldp":{"configuration":1}
,"config":{"define":1}
,"define":{"ldp_if_config_hello_interval":1,"ldp_if_config_hold_time":1,"ldp_if_config_keepalive_interval":1,"ldp_if_config_keepalive_timeout":1,"ldp_if_config_adv_mode":1,"ldp_if_config_label_retention_mode":1,"ldp_if_config_label_type":1,"ldp_if_config_no_multicast_hellos":1,"ldp_if_config_reconnect_timeout":1,"ldp_if_config_recovery_time":1,"ldp_if_config_hold_time_sync":1,"ldp_if_config_max_pdu_length":1,"ldp_if_config_sync_delay_interval":1,"ldp_if_flag_no_multicast_hellos":1,"ldp_if_flag_bind_mpls_vc":1,"ldp_if_flag_bind_vpls":1,"ldp_if_flag_addrs_advertised":1,"ldp_if_flag_shutdown":1,"ldp_ipv4_enable":1,"ldp_ipv6_enable":1,"ldp_igp_sync_enable":1,"ldp_if_ipv4_enable":1,"ldp_if_ipv6_enable":1,"ldp_if_igp_sync_enable":1}
,"ldp_if_config_hello_interval":{"<<0)":1}
,"<<0)":{"define":1}
,"ldp_if_config_hold_time":{"<<1)":1}
,"<<1)":{"define":1}
,"ldp_if_config_keepalive_interval":{"<<2)":1}
,"<<2)":{"define":1,"\u002F*flag":1}
,"ldp_if_config_keepalive_timeout":{"<<3)":1}
,"<<3)":{"define":1}
,"ldp_if_config_adv_mode":{"<<6)":1}
,"<<6)":{"define":1}
,"ldp_if_config_label_retention_mode":{"<<7)":1}
,"<<7)":{"define":1}
,"ldp_if_config_label_type":{"<<8)":1}
,"<<8)":{"define":1}
,"ldp_if_config_no_multicast_hellos":{"<<9)":1}
,"<<9)":{"define":1}
,"ldp_if_config_reconnect_timeout":{"<<10)":1}
,"<<10)":{"define":1}
,"ldp_if_config_recovery_time":{"<<11)":1}
,"<<11)":{"define":1}
,"ldp_if_config_hold_time_sync":{"<<12)":1}
,"<<12)":{"define":1}
,"ldp_if_config_max_pdu_length":{"<<13)":1}
,"<<13)":{"define":1}
,"ldp_if_config_sync_delay_interval":{"<<14)":1}
,"<<14)":{"\u002F*type":1}
,"\u002F*type":{"interface":1}
,"*\u002Fu_int16_t":{"interface_type":1,"hello_interval":1}
,"interface_type":{"\u002F*timer":1}
,"hello_interval":{"u_int16_t":1}
,"u_int16_t":{"hold_time":1,"hold_time_for_sync":1,"keepalive_interval":1,"keepalive_timeout":1,"sync_delay_interval":1}
,"hold_time":{"u_int16_t":1}
,"hold_time_for_sync":{"u_int16_t":1}
,"keepalive_interval":{"u_int16_t":1}
,"keepalive_timeout":{"u_int16_t":1}
,"sync_delay_interval":{"\u002F*threads":1}
,"\u002F*threads":{"*\u002Fstruct":1}
,"*t_hello":{"ifdef":1}
,"*ipv6_t_hello":{"endif":1}
,"*\u002F\u002F*pointer":{"labelspace-to-address":1}
,"labelspace-to-address":{"object":1}
,"object":{"*\u002Fstruct":1}
,"ls_to_addr":{"*l_addr":1}
,"*l_addr":{"\u002F**storage":1}
,"\u002F**storage":{"label":1}
,"label":{"space":1}
,"space":{"data":1,"*data":1}
,"**when":{"receive":1}
,"receive":{"update":1}
,"update":{"interface":1}
,"dont":{"know":1}
,"know":{"*which":1}
,"*which":{"interface":1}
,"affected":{"until":1}
,"until":{"it\u0027s":1}
,"it\u0027s":{"late":1}
,"late":{"*therefore":1}
,"*therefore":{"need":1}
,"need":{"store":1}
,"store":{"backup":1}
,"backup":{"copy":1}
,"copy":{"label":1}
,"*data":{"protocol":1}
,"protocol":{"specific":1}
,"specific":{"interface":1}
,"label_space_data":{"ls_data":1}
,"ls_data":{"\u002F*flags":1}
,"\u002F*flags":{"*\u002Fu_char":1}
,"*\u002Fu_char":{"flags":1,"if_active":1,"adv_mode":1,"retention_mode":1,"label_merge_cap":1,"addrflag":1,"enable_interface":1,"enable_family":1}
,"flags":{"define":1}
,"ldp_if_flag_no_multicast_hellos":{"<<0)":1}
,"ldp_if_flag_bind_mpls_vc":{"<<1)":1}
,"ldp_if_flag_bind_vpls":{"<<2)":1}
,"ldp_if_flag_addrs_advertised":{"<<3)":1}
,"ldp_if_flag_shutdown":{"<<4)":1}
,"<<4)":{"\u002F*interface":1}
,"\u002F*interface":{"activation":1}
,"activation":{"status":1}
,"status":{"*\u002Fu_char":1}
,"if_active":{"\u002F*advertisement":1}
,"\u002F*advertisement":{"mode":1}
,"mode":{"*\u002Fu_char":1}
,"adv_mode":{"\u002F*label":1}
,"\u002F*label":{"retention":1,"merge":1}
,"retention":{"mode":1}
,"retention_mode":{"\u002F*label":1}
,"merge":{"capability":1}
,"capability":{"*\u002Fu_char":1}
,"label_merge_cap":{"\u002F*flag":1}
,"\u002F*flag":{"test":1,"tell":1}
,"test":{"primary":1}
,"primary":{"address":1}
,"addrflag":{"ifdef":1}
,"u_char":{"addrflag6":1}
,"addrflag6":{"endif":1}
,"*\u002F\u002F*flag":{"tell":1}
,"tell":{"whether":1}
,"whether":{"interface":1,"ipv4":1}
,"enabled":{"user":1}
,"user":{"*\u002Fu_char":1}
,"enable_interface":{"define":1}
,"ldp_ipv4_enable":{"<<0)":1}
,"ldp_ipv6_enable":{"<<1)":1}
,"ldp_igp_sync_enable":{"<<2)":1}
,"ipv4":{"ipv6":1}
,"enable_family":{"define":1}
,"ldp_if_ipv4_enable":{"<<0)":1}
,"ldp_if_ipv6_enable":{"<<1)":1}
,"ldp_if_igp_sync_enable":{"<<2)":1}
}
;Search.control.loadWordPairs(pairs);
