var pairs =
{
"bgp":{"bestpath":1,"100":1}
,"bestpath":{"as-path":1}
,"as-path":{"ignore":1}
,"ignore":{"command":1,"bgp":1,"parameters":1,"(config)":1}
,"command":{"prevent":1,"allow":1,"syntax":1,"mode":1}
,"prevent":{"router":1}
,"router":{"considering":1,"consider":1,"mode":1,"bgp":1}
,"considering":{"autonomous":1}
,"autonomous":{"system":1}
,"system":{"(as)":1}
,"(as)":{"path":1}
,"path":{"length":1,"route":1}
,"length":{"factor":1,"choosing":1}
,"factor":{"algorithm":1}
,"algorithm":{"choosing":1}
,"choosing":{"best":1}
,"best":{"path":1}
,"route":{"parameter":1,"command":1}
,"parameter":{"command":1}
,"allow":{"router":1}
,"consider":{"path":1}
,"syntax":{"bgp":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"router":1,"examples":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"100":{"(config-router)":1}
,"(config-router)":{"bgp":1}
}
;Search.control.loadWordPairs(pairs);
