var pairs =
{
"rip_if_split_horizon_unset":{"function":1,"(u_int32_t":1}
,"function":{"disables":1,"called":1}
,"disables":{"split":1}
,"split":{"horizon":1}
,"horizon":{"behavior":1}
,"behavior":{"default":1}
,"default":{"configuration":1,"value":1}
,"configuration":{"split-horizon":1}
,"split-horizon":{"poisoned":1,"syntax":1,"type":1}
,"poisoned":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"rip":1}
,"rip":{"split-horizon":1}
,"syntax":{"int":1}
,"int":{"rip_if_split_horizon_unset":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1,"exist":1}
,"char":{"*ifname)":1}
,"*ifname)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"value":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"parameter":1}
,"parameter":{"ifname":1}
,"ifname":{"interface":1}
,"interface":{"name":1}
,"name":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"rip_api_set_err_split_horizon_invalid":1}
,"rip_api_set_err_split_horizon_invalid":{"split-horizon":1}
,"type":{"invalid":1}
,"invalid":{"rip_api_set_err_vr_not_exist":1}
,"rip_api_set_err_vr_not_exist":{"vr_id":1}
,"exist":{"rip_api_set_success":1}
,"rip_api_set_success":{"call":1}
,"call":{"successful":1}
}
;Search.control.loadWordPairs(pairs);
