var pairs =
{
"show":{"gvrp":1}
,"gvrp":{"statistics":1,"show":1}
,"statistics":{"command":1,"bridge":1,"show":1,"ifname":1}
,"command":{"display":1,"syntax":1,"mode":1,"displaying":1}
,"display":{"gvrp-related":1}
,"gvrp-related":{"statistics":1}
,"bridge":{"modify":1,"port":1}
,"modify":{"lines":1}
,"lines":{"displayed":1}
,"displayed":{"(output":1}
,"(output":{"modifier":1,"redirection":1}
,"modifier":{"token)":1}
,"token)":{"save":1,"command":1}
,"save":{"output":1}
,"output":{"file":1,"command":1}
,"file":{"(output":1}
,"redirection":{"token)":1}
,"syntax":{"show":1}
,"ifname":{"parameter":1,"displays":1}
,"parameter":{"ifname":1}
,"displays":{"name":1}
,"name":{"port":1}
,"port":{"command":1,"joinempty":1}
,"mode":{"exec":1,"example":1}
,"exec":{"privileged":1,"mode":1}
,"privileged":{"exec":1}
,"example":{"following":1}
,"following":{"output":1}
,"displaying":{"statistical":1}
,"statistical":{"summary":1}
,"summary":{"gvrp":1}
,"joinempty":{"joinin":1}
,"joinin":{"leaveempty":1}
,"leaveempty":{"leavein":1}
,"leavein":{"empty":1}
,"empty":{"------------------------------------------------------------------------------eth5":1}
,"------------------------------------------------------------------------------eth5":{"eth4":1}
}
;Search.control.loadWordPairs(pairs);
