var pairs =
{
"hal_l2_dlf_bcast_discards_get":{"function":1,"(unsigned":1}
,"function":{"gets":1,"succeeds":1}
,"gets":{"number":1}
,"number":{"discarded":1}
,"discarded":{"destination":1,"frames":1}
,"destination":{"lookup":1}
,"lookup":{"failures":1}
,"failures":{"syntax":1}
,"syntax":{"int":1}
,"int":{"hal_l2_dlf_bcast_discards_get":1,"ifindex":1,"*discards)":1}
,"(unsigned":{"int":1}
,"ifindex":{"unsigned":1,"port":1}
,"unsigned":{"int":1}
,"*discards)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifindex":1,"discards":1}
,"port":{"interface":1}
,"interface":{"index":1}
,"index":{"output":1}
,"output":{"parameters":1}
,"discards":{"number":1}
,"frames":{"return":1}
,"return":{"value":1}
,"value":{"hal_err_ratelimit_mcast":1}
,"hal_err_ratelimit_mcast":{"hal_success":1}
,"hal_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
