var pairs =
{
"software-defined":{"networking":1}
,"networking":{"(sdn)":1}
,"(sdn)":{"approach":1}
,"approach":{"designing":1}
,"designing":{"building":1}
,"building":{"operating":1}
,"operating":{"networks":1}
,"networks":{"decouples":1}
,"decouples":{"control":1}
,"control":{"plane":1,"underlying":1}
,"plane":{"data":1,"control":1,"centralized":1}
,"data":{"plane":1}
,"centralized":{"form":1}
,"form":{"controller":1}
,"controller":{"system":1}
,"system":{"communication":1,"network":1,"consist":1}
,"communication":{"controller":1}
,"network":{"device":1,"apis":1}
,"device":{"uses":1}
,"uses":{"standard":1}
,"standard":{"protocol":1}
,"protocol":{"openflow":1}
,"openflow":{"agents":1}
,"agents":{"controller":1}
,"consist":{"multiple":1}
,"multiple":{"domain":1}
,"domain":{"specific":1}
,"specific":{"clustered":1}
,"clustered":{"controllers":1}
,"controllers":{"sdn":1}
,"sdn":{"architecture":1}
,"architecture":{"usually":1}
,"usually":{"includes":1}
,"includes":{"apis":1}
,"apis":{"developers":1,"standards-based":1}
,"developers":{"control":1}
,"underlying":{"network":1}
,"standards-based":{"vendor-specific":1}
}
;Search.control.loadWordPairs(pairs);
