var pairs =
{
"oam_api_lps_switchover":{"function":1,"(u_int32_t":1}
,"function":{"triggers":1,"fails":1,"succeeds":1}
,"triggers":{"switchover":1}
,"switchover":{"event":1,"triggered":1}
,"event":{"identified":1,"output":1,"switchover":1,"triggered":1}
,"identified":{"protection-group":1}
,"protection-group":{"name":1,"lookup":1,"oam_api_set_error_backup_me_not_set":1,"oam_api_lower_prio_cmd_not_allowed":1}
,"name":{"syntax":1,"switch_over":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"oam_api_lps_switchover":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"instance":1}
,"char":{"*grp_name_str":1}
,"*grp_name_str":{"lps_switch_over":1}
,"lps_switch_over":{"switch_over)":1}
,"switch_over)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"instance":{"grp_name_str":1}
,"grp_name_str":{"protection-group":1}
,"switch_over":{"identifies":1}
,"identifies":{"switchover":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"oam_api_set_error_psc_grp_lookup":1}
,"oam_api_set_error_psc_grp_lookup":{"protection-group":1}
,"lookup":{"fails":1}
,"fails":{"oam_api_set_error_primary_me_not_set":1,"due":1}
,"oam_api_set_error_primary_me_not_set":{"primary":1}
,"primary":{"configured":1}
,"configured":{"protection-group":1}
,"oam_api_set_error_backup_me_not_set":{"backup":1}
,"backup":{"configured":1}
,"oam_api_lower_prio_cmd_not_allowed":{"lower-priority":1}
,"lower-priority":{"event":1}
,"triggered":{"oam_api_manual_switch_already_exists":1,"already":1}
,"oam_api_manual_switch_already_exists":{"manual":1}
,"manual":{"switchover":1}
,"already":{"exists":1}
,"exists":{"oam_api_force_switch_already_exists":1,"oam_api_set_error_mode_scheme_mismatch":1}
,"oam_api_force_switch_already_exists":{"force":1}
,"force":{"switchover":1}
,"oam_api_set_error_mode_scheme_mismatch":{"mode":1}
,"mode":{"scheme":1}
,"scheme":{"mismatch":1}
,"mismatch":{"oam_api_lps_set_error":1}
,"oam_api_lps_set_error":{"function":1}
,"due":{"internal":1}
,"internal":{"errors":1}
,"errors":{"memory":1}
,"memory":{"failure":1}
,"failure":{"oam_api_lps_set_success":1}
,"oam_api_lps_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
