var pairs =
{
"contents":{"guide":1}
,"guide":{"contains":1}
,"contains":{"chapters":1}
,"chapters":{"chapter":1}
,"chapter":{"introduction":1,"bfd":1,"data":1,"oam":1,"network":1,"border":1,"intermediate":1,"open":1,"routing":1,"virtual":1}
,"introduction":{"chapter":1}
,"bfd":{"software":1,"application":1,"mpls":1,"authentication":1,"command":1,"mib":1}
,"software":{"architecture":1}
,"architecture":{"chapter":1}
,"application":{"protocol":1}
,"protocol":{"modules":1,"chapter":1}
,"modules":{"chapter":1}
,"data":{"structures":1}
,"structures":{"chapter":1}
,"oam":{"bfd":1}
,"mpls":{"chapter":1}
,"network":{"services":1}
,"services":{"module":1}
,"module":{"chapter":1}
,"border":{"gateway":1}
,"gateway":{"protocol":1}
,"intermediate":{"system":1}
,"system":{"intermediate":1,"chapter":1}
,"open":{"shortest":1}
,"shortest":{"path":1}
,"path":{"first":1}
,"first":{"chapter":1}
,"routing":{"information":1}
,"information":{"protocol":1}
,"authentication":{"chapter":1}
,"virtual":{"router":1}
,"router":{"chapter":1}
,"command":{"api":1}
,"api":{"chapter":1}
,"mib":{"support":1}
}
;Search.control.loadWordPairs(pairs);
