var pairs =
{
"vrf":{"isid":1,"(virtual":1,"command":1,"word":1,"instance":1,"vpn2":1}
,"isid":{"command":1,"<1-16777214>":1}
,"command":{"create":1,"remove":1,"supported":1,"syntax":1,"mode":1}
,"create":{"vrf":1}
,"(virtual":{"routing":1}
,"routing":{"forwarding)":1}
,"forwarding)":{"instance":1}
,"instance":{"associated":1,"identifier)":1,"name":1,"identifier":1}
,"associated":{"i-sid":1}
,"i-sid":{"(service":1}
,"(service":{"instance":1}
,"identifier)":{"needs":1}
,"needs":{"advertise":1}
,"advertise":{"routes":1}
,"routes":{"spb":1}
,"spb":{"network":1}
,"network":{"form":1}
,"form":{"command":1}
,"remove":{"vrf":1}
,"supported":{"zebic":1}
,"zebic":{"releases":1}
,"releases":{"command":1}
,"syntax":{"vrf":1}
,"word":{"isid":1,"parameters":1,"vrf":1}
,"<1-16777214>":{"vrf":1,"service":1}
,"parameters":{"word":1}
,"name":{"<1-16777214>":1}
,"service":{"instance":1}
,"identifier":{"command":1}
,"mode":{"configure":1,"examples":1}
,"configure":{"mode":1,"terminal":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"vrf":1}
,"vpn2":{"isid":1}
}
;Search.control.loadWordPairs(pairs);
