var pairs =
{
"rsvp_api_session_unset_local_protect":{"call":1,"(struct":1}
,"call":{"disables":1}
,"disables":{"local":1}
,"local":{"protection":1}
,"protection":{"session":1}
,"session":{"syntax":1,"session":1,"output":1}
,"syntax":{"void":1}
,"void":{"rsvp_api_session_unset_local_protect":1}
,"(struct":{"rsvp_session":1}
,"rsvp_session":{"*session)":1}
,"*session)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"session":1,"none":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"none":1}
}
;Search.control.loadWordPairs(pairs);
