var pairs =
{
"routing":{"process":1,"usually":1,"information":1}
,"process":{"finding":1}
,"finding":{"path":1}
,"path":{"destination":1}
,"destination":{"transmit":1}
,"transmit":{"protocol":1}
,"protocol":{"data":1}
,"data":{"unit":1}
,"unit":{"(pdu)":1}
,"(pdu)":{"network":1}
,"network":{"routing":1,"until":1}
,"usually":{"controlled":1}
,"controlled":{"routing":1}
,"information":{"base":1}
,"base":{"(rib)":1}
,"(rib)":{"defines":1}
,"defines":{"pdu":1}
,"pdu":{"router":1,"sent":1,"reaches":1}
,"router":{"needs":1,"network":1}
,"needs":{"know":1}
,"know":{"pdu":1,"care":1}
,"sent":{"next":1}
,"next":{"hop":1,"router":1}
,"hop":{"know":1,"plus":1}
,"care":{"happens":1}
,"happens":{"afterward":1}
,"afterward":{"next":1}
,"plus":{"responsibility":1}
,"responsibility":{"next":1}
,"until":{"pdu":1}
,"reaches":{"destination":1}
}
;Search.control.loadWordPairs(pairs);
