var pairs =
{
"constrained":{"shortest":1}
,"shortest":{"path":1}
,"path":{"first":1}
,"first":{"rsvp-te":1,"(cspf)":1,"developer":1}
,"rsvp-te":{"communicates":1}
,"communicates":{"constrained":1}
,"(cspf)":{"module":1}
,"module":{"via":1}
,"via":{"ipc":1}
,"ipc":{"obtain":1}
,"obtain":{"optimum":1}
,"optimum":{"explicit":1}
,"explicit":{"route":1}
,"route":{"(er)":1}
,"(er)":{"based":1}
,"based":{"specified":1}
,"specified":{"constraints":1}
,"constraints":{"uses":1}
,"uses":{"traffic":1}
,"traffic":{"engineering":1}
,"engineering":{"database":1}
,"database":{"(ted)":1}
,"(ted)":{"pre-existing":1}
,"pre-existing":{"label":1}
,"label":{"switched":1}
,"switched":{"paths":1}
,"paths":{"(lsp)":1}
,"(lsp)":{"resulting":1}
,"resulting":{"used":1}
,"used":{"traffic-engineered":1}
,"traffic-engineered":{"lsp":1}
,"lsp":{"aboiut":1}
,"aboiut":{"cspf":1}
,"cspf":{"open":1}
,"open":{"shortest":1}
,"developer":{"guide":1}
}
;Search.control.loadWordPairs(pairs);
