var pairs =
{
"rip_max_route_unset":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"called":1}
,"sets":{"threshold":1}
,"threshold":{"value":1,"percentage":1}
,"value":{"default":1,"non-vr":1}
,"default":{"threshold":1,"value":1}
,"percentage":{"maximum-prefix":1,"function":1}
,"maximum-prefix":{"checking":1,"syntax":1}
,"checking":{"rip_route_threshold_default":1}
,"rip_route_threshold_default":{"(see":1}
,"(see":{"ripd.h)":1}
,"ripd.h)":{"default":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"maximum-prefix":1}
,"syntax":{"int":1}
,"int":{"rip_max_route_unset":1,"instance)":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"int":1,"virtual":1,"exist":1}
,"instance)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"parameter":1}
,"parameter":{"instance":1}
,"instance":{"number":1,"output":1,"cannot":1}
,"number":{"instance":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"rip_api_set_err_process_not_exist":1}
,"rip_api_set_err_process_not_exist":{"instance":1}
,"cannot":{"found":1}
,"found":{"rip_api_set_err_vr_not_exist":1}
,"rip_api_set_err_vr_not_exist":{"vr_id":1}
,"exist":{"rip_api_set_success":1}
,"rip_api_set_success":{"call":1}
,"call":{"successful":1}
}
;Search.control.loadWordPairs(pairs);
