var pairs =
{
"ospf_domain_id_unset":{"function":1,"(u_int32_t":1}
,"function":{"removes":1,"called":1,"succeeds":1}
,"removes":{"ospf":1}
,"ospf":{"domain":1,"instance":1}
,"domain":{"function":1,"type>":1,"type":1,"address":1,"value":1,"primary":1}
,"called":{"following":1}
,"following":{"command":1,"type-as":1}
,"command":{"domain-id":1}
,"domain-id":{"type":1}
,"type":{"<ospf":1,"domain":1,"following":1,"null":1}
,"<ospf":{"domain":1}
,"type>":{"value":1}
,"value":{"<domain":1,"domain":1,"entered":1,"ospf_api_set_success":1,"given":1}
,"<domain":{"value>":1}
,"value>":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf_domain_id_unset":1,"proc_id":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"int":1,"virtual":1}
,"proc_id":{"char":1,"process":1}
,"char":{"*type":1}
,"*type":{"u_int8_t":1}
,"u_int8_t":{"*value":1}
,"*value":{"bool_t":1}
,"bool_t":{"is_primary_did)":1}
,"is_primary_did)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"found":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"proc_id":1}
,"process":{"ospf":1,"invalid":1,"found":1}
,"instance":{"65535>":1}
,"65535>":{"type":1}
,"type-as":{"format":1}
,"format":{"type-as4":1,"type-back-comp":1,"domain":1}
,"type-as4":{"as4":1}
,"as4":{"format":1}
,"type-back-comp":{"backward":1}
,"backward":{"compatibility":1}
,"compatibility":{"note":1}
,"note":{"type":1}
,"null":{"case":1,"domain":1}
,"case":{"null":1}
,"address":{"format":1}
,"entered":{"cli":1,"domain":1}
,"cli":{"is_primary_did":1}
,"is_primary_did":{"boolean":1}
,"boolean":{"flag":1}
,"flag":{"identify":1}
,"identify":{"whether":1}
,"whether":{"entered":1}
,"primary":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"ospf_api_set_success":{"function":1}
,"succeeds":{"ospf_api_set_err_vr_not_exist":1}
,"ospf_api_set_err_vr_not_exist":{"virtual":1}
,"found":{"ospf_api_set_err_process_id_invalid":1,"ospf_api_set_err_wrong_value":1}
,"ospf_api_set_err_process_id_invalid":{"process":1}
,"invalid":{"ospf_api_set_err_process_not_exist":1,"value":1,"hex":1}
,"ospf_api_set_err_process_not_exist":{"process":1}
,"ospf_api_set_err_wrong_value":{"invalid":1}
,"given":{"ospf_api_set_err_invalid_hex_value":1}
,"ospf_api_set_err_invalid_hex_value":{"invalid":1}
,"hex":{"value":1}
}
;Search.control.loadWordPairs(pairs);
