var pairs =
{
"evaluating":{"pbb-te":1}
,"pbb-te":{"mips":1}
,"mips":{"managed":1,"indirectly":1,"every":1}
,"managed":{"objects":1,"object":1}
,"objects":{"control":1}
,"control":{"creation":1}
,"creation":{"mips":1,"permissions":1}
,"indirectly":{"rather":1}
,"rather":{"explicitly":1}
,"explicitly":{"meps":1}
,"meps":{"every":1}
,"every":{"defined":1,"bridge":1}
,"defined":{"bridge":1}
,"bridge":{"cause":1,"port":1,"initialized":1}
,"cause":{"management":1}
,"management":{"entity":1}
,"entity":{"create":1,"re-evaluate":1}
,"create":{"mips":1}
,"port":{"bridge":1,"following":1,"mep":1,"change":1}
,"following":{"conditions":1}
,"conditions":{"trigger":1}
,"trigger":{"management":1}
,"re-evaluate":{"mip":1}
,"mip":{"creation":1}
,"permissions":{"given":1}
,"given":{"vid":1}
,"vid":{"(or":1,"(s)":1}
,"(or":{"list":1}
,"list":{"vids)":1}
,"vids)":{"bridge":1}
,"initialized":{"mep":1}
,"mep":{"created":1}
,"created":{"deleted":1}
,"deleted":{"vid":1}
,"(s)":{"bridge":1,"allocated":1,"cannot":1}
,"allocated":{"service":1}
,"service":{"instance":1}
,"instance":{"bridge":1}
,"change":{"occurs":1}
,"occurs":{"whether":1,"default":1,"maintenance":1}
,"whether":{"vid":1}
,"cannot":{"pass":1}
,"pass":{"bridge":1}
,"default":{"level":1}
,"level":{"managed":1}
,"object":{"change":1,"associated":1}
,"maintenance":{"association":1}
,"association":{"managed":1}
,"associated":{"vid":1}
}
;Search.control.loadWordPairs(pairs);
