var pairs =
{
"contents":{"guide":1}
,"guide":{"contains":1}
,"contains":{"chapters":1}
,"chapters":{"appendices":1}
,"appendices":{"chapter":1}
,"chapter":{"introduction":1,"graceful":1,"optimization":1,"multiple":1,"pe-ce":1,"passive":1,"multi-area":1,"constrained":1,"loop-free":1,"demand":1,"data":1,"ospfv2":1,"ospfv3":1}
,"introduction":{"chapter":1}
,"graceful":{"restart":1}
,"restart":{"chapter":1}
,"optimization":{"chapter":1}
,"multiple":{"instances":1}
,"instances":{"chapter":1}
,"pe-ce":{"bgp\u002Fmpls":1}
,"bgp\u002Fmpls":{"vpns":1}
,"vpns":{"chapter":1}
,"passive":{"interface":1}
,"interface":{"chapter":1}
,"multi-area":{"adjacency":1}
,"adjacency":{"chapter":1}
,"constrained":{"shortest":1}
,"shortest":{"path":1}
,"path":{"first":1}
,"first":{"chapter":1}
,"loop-free":{"alternate":1}
,"alternate":{"fast":1}
,"fast":{"reroute":1}
,"reroute":{"chapter":1}
,"demand":{"circuit":1}
,"circuit":{"chapter":1}
,"data":{"structures":1}
,"structures":{"constants":1}
,"constants":{"chapter":1}
,"ospfv2":{"command":1,"snmp":1}
,"command":{"api":1}
,"api":{"chapter":1,"appendix":1}
,"ospfv3":{"command":1,"snmp":1}
,"snmp":{"api":1}
,"appendix":{"message":1,"source":1}
,"message":{"tlv":1}
,"tlv":{"types":1}
,"types":{"appendix":1}
,"source":{"code":1}
}
;Search.control.loadWordPairs(pairs);
