var pairs =
{
"mrib6_api_clear_mroute_all":{"function":1,"(u_int32_t":1}
,"function":{"clears":1,"used":1,"succeeds":1}
,"clears":{"multicast":1}
,"multicast":{"entry":1}
,"entry":{"mrib\u002Fmfib":1}
,"mrib\u002Fmfib":{"function":1}
,"used":{"implement":1,"mrib_api_set_err_wrong_vrf":1,"mrib_api_set_success":1}
,"implement":{"clear":1}
,"clear":{"ipv6":1}
,"ipv6":{"mroute":1}
,"mroute":{"*command":1}
,"*command":{"syntax":1}
,"syntax":{"int":1}
,"int":{"mrib6_api_clear_mroute_all":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"vrf_id_t":1,"virtual":1}
,"vrf_id_t":{"vrf_id)":1}
,"vrf_id)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"vrf_id":1,"used":1}
,"vrf_id":{"vpn":1}
,"vpn":{"routing\u002Fforwarding":1}
,"routing\u002Fforwarding":{"instance":1}
,"instance":{"output":1,"used":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"mrib_api_set_err_wrong_vr":1}
,"mrib_api_set_err_wrong_vr":{"invalid":1}
,"invalid":{"virtual":1,"vpn":1}
,"mrib_api_set_err_wrong_vrf":{"invalid":1}
,"mrib_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
