var pairs =
{
"rip2_get_next_peer_address":{"function":1,"(int":1}
,"function":{"returns":1}
,"returns":{"address":1}
,"address":{"next":1,"syntax":1,"indexlen":1,"peer":1,"rip_api_get_success":1}
,"next":{"peer":1}
,"peer":{"using":1,"address":1,"return":1}
,"using":{"source":1}
,"source":{"address":1}
,"syntax":{"int":1}
,"int":{"rip2_get_next_peer_address":1,"indexlen":1}
,"(int":{"pid":1}
,"pid":{"struct":1,"rip":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"*addr":1,"*outaddr)":1}
,"*addr":{"int":1}
,"indexlen":{"struct":1,"future":1}
,"*outaddr)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"pid":1,"outaddr":1}
,"rip":{"process":1}
,"process":{"addr":1}
,"addr":{"peer":1}
,"future":{"output":1}
,"output":{"parameters":1}
,"outaddr":{"address":1}
,"return":{"values":1}
,"values":{"rip_api_get_error":1}
,"rip_api_get_error":{"call":1}
,"call":{"find":1,"finds":1}
,"find":{"address":1}
,"rip_api_get_success":{"call":1}
,"finds":{"address":1}
}
;Search.control.loadWordPairs(pairs);
