var pairs =
{
"topology":{"diagram":1}
,"diagram":{"shows":1}
,"shows":{"minimum":1}
,"minimum":{"configuration":1}
,"configuration":{"required":1}
,"required":{"enable":1}
,"enable":{"ospf":1}
,"ospf":{"lsa":1,"topology":1}
,"lsa":{"throttling":1}
,"throttling":{"timers":1}
,"timers":{"feature":1}
,"feature":{"two":1}
,"two":{"routers":1}
,"routers":{"area":1}
,"area":{"connecting":1,"possible":1}
,"connecting":{"network":1}
,"network":{"10.10.10.0\u002F24":1}
,"10.10.10.0\u002F24":{"configure":1}
,"configure":{"interface":1,"different":1}
,"interface":{"belongs":1}
,"belongs":{"area":1}
,"possible":{"however":1}
,"however":{"configure":1}
,"different":{"interfaces":1,"areas":1}
,"interfaces":{"router":1}
,"router":{"belong":1}
,"belong":{"different":1}
,"areas":{"basic":1}
,"basic":{"ospf":1}
}
;Search.control.loadWordPairs(pairs);
