var pairs =
{
"vlog":{"users":1}
,"users":{"two":1,"users":1,"pvr":1,"may":1}
,"two":{"types":1}
,"types":{"vlog":1}
,"pvr":{"users":1,"debugging":1,"terminal":1,"debug":1,"vrs":1}
,"may":{"enable":1}
,"enable":{"disable":1}
,"disable":{"debugging":1,"pvr":1}
,"debugging":{"view":1,"pvr":1}
,"view":{"debug":1,"pvr":1}
,"debug":{"messages":1,"output":1}
,"messages":{"log":1,"specified":1}
,"log":{"debug":1,"file":1}
,"specified":{"log":1}
,"file":{"specify":1,"name":1}
,"specify":{"log":1,"local":1}
,"name":{"otherwise":1,"used":1}
,"otherwise":{"default":1}
,"default":{"name":1}
,"used":{"pvr":1}
,"terminal":{"session":1}
,"session":{"view":1}
,"output":{"log":1,"pvr":1}
,"vrs":{"log":1}
,"local":{"global":1}
,"global":{"log":1}
}
;Search.control.loadWordPairs(pairs);
