var pairs =
{
"ethernet":{"cfm":1}
,"cfm":{"out-of-service":1}
,"out-of-service":{"command":1,"testing":1,"lck-level":1}
,"command":{"used":1,"syntax":1,"mode":1}
,"used":{"configure":1,"bridging":1}
,"configure":{"interface":1,"mep":1,"terminal":1}
,"interface":{"out-of-service":1,"mode":1,"eth1et":1}
,"testing":{"command":1,"mep":1,"specify":1}
,"syntax":{"ethernet":1}
,"lck-level":{"level":1,"specify":1,"testing":1}
,"level":{"testing":1,"lck":1}
,"mep":{"mepid":1,"testing":1,"specify":1,"domain":1}
,"mepid":{"domain":1}
,"domain":{"domain_name":1,"specify":1,"bridge":1,"abc":1}
,"domain_name":{"(vlan":1}
,"(vlan":{"vlan_id":1}
,"vlan_id":{"(bridge":1}
,"(bridge":{"<1-32>":1}
,"<1-32>":{"parameters":1,"vlan":1}
,"parameters":{"lck-level":1}
,"specify":{"level":1,"configure":1,"integer":1,"name":1,"bridge":1}
,"lck":{"frames":1}
,"frames":{"sent":1}
,"sent":{"testing":1}
,"integer":{"identifies":1}
,"identifies":{"host":1,"vlan":1}
,"host":{"mep":1}
,"name":{"maintenance":1,"used":1}
,"maintenance":{"domain":1}
,"bridge":{"specify":1,"group":1}
,"group":{"name":1}
,"bridging":{"<1-32>":1}
,"vlan":{"specify":1,"command":1,"bridge":1}
,"mode":{"interface":1,"examples":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth1et":{"cfm":1}
,"abc":{"vlan":1}
}
;Search.control.loadWordPairs(pairs);
