var pairs =
{
"route":{"messages":1,"lookup":1}
,"messages":{"message":1}
,"message":{"constant":1}
,"constant":{"source":1}
,"source":{"nsm_msg_route_preserve":1}
,"nsm_msg_route_preserve":{"sent":1}
,"sent":{"protocol":1,"nsm":1}
,"protocol":{"nsm":1,"restarts":1,"redistribution":1,"response":1}
,"nsm":{"graceful":1,"specified":1,"remove":1,"nsm_msg_route_ipv4":1,"adding":1,"protocol":1,"mark":1}
,"graceful":{"restart":1}
,"restart":{"protocol":1}
,"restarts":{"retains":1}
,"retains":{"routes":1}
,"routes":{"nsm":1,"sent":1}
,"specified":{"period":1}
,"period":{"nsm_msg_route_stale_remove":1}
,"nsm_msg_route_stale_remove":{"sent":1}
,"remove":{"stale":1}
,"stale":{"routes":1}
,"nsm_msg_route_ipv4":{"sent":1}
,"adding":{"deleting":1}
,"deleting":{"ipv4":1,"ipv6":1}
,"ipv4":{"routes":1}
,"redistribution":{"requested":1}
,"requested":{"protocol":1}
,"response":{"route":1}
,"lookup":{"nsm_msg_route_ipv6":1,"nsm_msg_route_clean":1}
,"nsm_msg_route_ipv6":{"sent":1}
,"ipv6":{"routes":1}
,"nsm_msg_route_clean":{"(reserved":1}
,"(reserved":{"future":1}
,"future":{"use)":1}
,"use)":{"nsm_msg_route_stale_mark":1}
,"nsm_msg_route_stale_mark":{"sent":1}
,"mark":{"stale":1}
}
;Search.control.loadWordPairs(pairs);
