var pairs =
{
"pimv6":{"commands":1}
,"commands":{"chapter":1,"protocol-independent":1}
,"chapter":{"describes":1}
,"describes":{"commands":1}
,"protocol-independent":{"multicast":1}
,"multicast":{"(pim)":1}
,"(pim)":{"clear":1}
,"clear":{"ipv6":1}
,"ipv6":{"mroute":1,"pim":1}
,"mroute":{"clear":1,"show":1}
,"pim":{"sparse-mode":1,"debug":1,"packet":1,"timer":1,"accept-register":1,"anycast-rp":1,"bidir-enable":1,"bidir-neighbor-filter":1,"bidir-offer-interval":1,"bidir-offer-limit":1,"bind":1,"bsr-border":1,"bsr-candidate":1,"cisco-register-checksum":1,"ipv6":1,"passive":1,"dense-group":1,"dr-priority":1,"ecmp-bundle":1,"exclude-genid":1,"hello-holdtime":1,"hello-interval":1,"ignore-rp-set-priority":1,"jp-timer":1,"neighbor-filter":1,"propagation-delay":1,"register-rate-limit":1,"register-rp-reachability":1,"register-source":1,"register-suppression":1,"router-id":1,"rp-address":1,"rp-candidate":1,"rp-register-kat":1,"spt-threshold":1,"ssm":1,"state-refresh":1,"unicast-bsm":1,"show":1,"interface":1,"mroute":1,"neighbor":1,"nexthop":1,"bsr-router":1,"local-members":1,"rp-hash":1,"mapping":1,"undebug":1}
,"sparse-mode":{"bsr":1}
,"bsr":{"debug":1}
,"debug":{"ipv6":1}
,"packet":{"debug":1}
,"timer":{"assert":1,"hello":1,"register":1}
,"assert":{"debug":1}
,"hello":{"debug":1}
,"register":{"ipv6":1}
,"accept-register":{"ipv6":1}
,"anycast-rp":{"ipv6":1}
,"bidir-enable":{"ipv6":1}
,"bidir-neighbor-filter":{"ipv6":1}
,"bidir-offer-interval":{"ipv6":1}
,"bidir-offer-limit":{"ipv6":1}
,"bind":{"ecmp-bundle":1}
,"ecmp-bundle":{"ipv6":1,"show":1}
,"bsr-border":{"ipv6":1}
,"bsr-candidate":{"ipv6":1}
,"cisco-register-checksum":{"ipv6":1}
,"passive":{"ipv6":1}
,"dense-group":{"ipv6":1}
,"dr-priority":{"ipv6":1}
,"exclude-genid":{"ipv6":1}
,"hello-holdtime":{"ipv6":1}
,"hello-interval":{"ipv6":1}
,"ignore-rp-set-priority":{"ipv6":1}
,"jp-timer":{"ipv6":1}
,"neighbor-filter":{"ipv6":1}
,"propagation-delay":{"ipv6":1}
,"register-rate-limit":{"ipv6":1}
,"register-rp-reachability":{"ipv6":1}
,"register-source":{"ipv6":1}
,"register-suppression":{"ipv6":1}
,"router-id":{"ipv6":1}
,"rp-address":{"ipv6":1}
,"rp-candidate":{"ipv6":1}
,"rp-register-kat":{"ipv6":1}
,"spt-threshold":{"ipv6":1}
,"ssm":{"ipv6":1}
,"state-refresh":{"origination-interval":1}
,"origination-interval":{"ipv6":1}
,"unicast-bsm":{"show":1}
,"show":{"debugging":1,"ipv6":1}
,"debugging":{"ipv6":1}
,"interface":{"show":1}
,"neighbor":{"show":1}
,"nexthop":{"show":1}
,"bsr-router":{"show":1}
,"local-members":{"show":1}
,"rp-hash":{"show":1}
,"mapping":{"snmp":1}
,"snmp":{"restart":1}
,"restart":{"pim":1}
,"undebug":{"ipv6":1}
}
;Search.control.loadWordPairs(pairs);
