var pairs =
{
"ospf_disable_ext_multi_inst":{"function":1,"(u_int32_t":1}
,"function":{"disables":1,"called":1,"succeeds":1}
,"disables":{"support":1}
,"support":{"multiple":1,"enabled":1}
,"multiple":{"ospf":1}
,"ospf":{"instances":1}
,"instances":{"subnet":1}
,"subnet":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"enable":1}
,"enable":{"ext-ospf-multi-inst":1}
,"ext-ospf-multi-inst":{"syntax":1}
,"syntax":{"s_int8_t":1}
,"s_int8_t":{"ospf_disable_ext_multi_inst":1}
,"(u_int32_t":{"vr_id)":1}
,"vr_id)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"vr_id":{"virtual":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"found":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf_api_set_success":1}
,"ospf_api_set_success":{"function":1}
,"succeeds":{"ospf_api_set_err_vr_not_exist":1}
,"ospf_api_set_err_vr_not_exist":{"virtual":1}
,"found":{"ospf_api_set_err_ext_multi_inst_not_enabled":1}
,"ospf_api_set_err_ext_multi_inst_not_enabled":{"multiple-instance":1}
,"multiple-instance":{"support":1}
}
;Search.control.loadWordPairs(pairs);
