var pairs =
{
"isis-spb":{"hello-multiplier":1,"hello-interval":1}
,"hello-multiplier":{"command":1,"<2-100>":1,"(level-1":1}
,"command":{"multiplier":1,"form":1,"syntax":1,"mode":1}
,"multiplier":{"hello":1,"default":1,"value":1,"level-1":1,"level-2":1,"multiplier":1,"applied":1}
,"hello":{"holding":1,"interval":1,"multiplier":1}
,"holding":{"time":1}
,"time":{"hello":1,"calculated":1}
,"calculated":{"multiplying":1}
,"multiplying":{"hello":1}
,"interval":{"value":1,"isis-spb":1}
,"value":{"hello":1,"level-1":1}
,"hello-interval":{"command":1}
,"form":{"command":1}
,"default":{"(3)":1,"default":1,"zebos-xp":1}
,"(3)":{"command":1}
,"syntax":{"isis-spb":1}
,"<2-100>":{"(level-1":1,"specify":1}
,"(level-1":{"level-2":1}
,"level-2":{"isis-spb":1,"parameters":1,"specify":1,"is-is":1}
,"parameters":{"<2-100>":1}
,"specify":{"hello":1,"multiplier":1}
,"level-1":{"specify":1,"is-is":1,"command":1}
,"is-is":{"hellos":1}
,"hellos":{"level-2":1,"default":1}
,"zebos-xp":{"uses":1}
,"uses":{"multiplier":1}
,"applied":{"level-1":1}
,"mode":{"interface":1,"example":1}
,"interface":{"mode":1,"eth0":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"isis-spb":1}
}
;Search.control.loadWordPairs(pairs);
