var pairs =
{
"architecture":{"nsm":1}
,"nsm":{"supports":1,"maintains":1}
,"supports":{"ethernet":1,"protection":1,"ccm":1}
,"ethernet":{"protection":1}
,"protection":{"bridge":1,"fsm":1,"behavior":1}
,"bridge":{"links":1,"vlan":1}
,"links":{"vlan-related":1}
,"vlan-related":{"configuration":1}
,"configuration":{"nsm":1,"information":1}
,"maintains":{"centralized":1}
,"centralized":{"bridge":1}
,"vlan":{"interface":1}
,"interface":{"configuration":1}
,"information":{"distributed":1}
,"distributed":{"zebos-xp":1}
,"zebos-xp":{"onmd":1}
,"onmd":{"(oam":1,"module":1}
,"(oam":{"network":1}
,"network":{"management":1}
,"management":{"daemon)":1}
,"daemon)":{"module.the":1}
,"module.the":{"onmd":1}
,"module":{"supports":1}
,"fsm":{"aps":1}
,"aps":{"messaging":1}
,"messaging":{"functions":1,"state":1}
,"functions":{"onmd":1}
,"ccm":{"aps":1}
,"state":{"machines":1}
,"machines":{"driven":1}
,"driven":{"signal":1}
,"signal":{"failure":1}
,"failure":{"(sf)":1}
,"(sf)":{"events":1}
,"events":{"realize":1}
,"realize":{"protection":1}
,"behavior":{"specified":1}
,"specified":{"itu-t":1}
,"itu-t":{"g.8031":1}
,"g.8031":{"recommendation":1}
,"recommendation":{"figure":1}
,"figure":{"8-1":1}
,"8-1":{"page":1}
,"page":{"198":1}
,"198":{"shows":1}
,"shows":{"relationships":1}
,"relationships":{"among":1}
,"among":{"entities":1}
,"entities":{"layer":1}
,"layer":{"switching":1,"architecture":1}
,"switching":{"environment":1}
,"environment":{"eps":1}
,"eps":{"layer":1}
}
;Search.control.loadWordPairs(pairs);
