var pairs =
{
"segment":{"identifiers":1,"identifier":1,"srgb":1,"absolute":1}
,"identifiers":{"segments":1}
,"segments":{"identified":1}
,"identified":{"segment":1,"20-bit":1}
,"identifier":{"(sid)":1}
,"(sid)":{"unsigned":1}
,"unsigned":{"32-bit":1}
,"32-bit":{"integer":1}
,"integer":{"mpls":1,"leaving":1}
,"mpls":{"data":1}
,"data":{"plane":1}
,"plane":{"used":1}
,"used":{"segments":1}
,"20-bit":{"integer":1}
,"leaving":{"left-most":1}
,"left-most":{"bits":1}
,"bits":{"sid":1}
,"sid":{"unused":1,"absolute":1}
,"unused":{"sid":1}
,"absolute":{"value":1}
,"value":{"(label)":1}
,"(label)":{"allocated":1}
,"allocated":{"segment":1}
,"srgb":{"across":1}
,"across":{"entire":1}
,"entire":{"domain":1}
,"domain":{"nodes":1}
,"nodes":{"identify":1}
,"identify":{"segment":1}
}
;Search.control.loadWordPairs(pairs);
