var pairs =
{
"neighbor":{"prefix-list":1,"distribute-list":1,"direction":1,"(a.b.c.d":1,"ipv4":1,"ipv6":1,"peer-group":1,"remote-as":1,"10.10.10.10":1}
,"prefix-list":{"command":1,"word":1,"list1":1}
,"command":{"specify":1,"alternative":1,"used":1,"remove":1,"syntax":1,"command":1,"applies":1,"mode":1}
,"specify":{"prefix":1}
,"prefix":{"list":1,"match":1,"entry":1}
,"list":{"filtering":1,"matches":1,"match":1,"permits":1,"route":1,"sequence":1,"efficiency":1,"apply":1,"incoming":1,"outgoing":1}
,"filtering":{"bgp":1,"prefix":1,"neighbor":1}
,"bgp":{"advertisements":1,"neighbor":1,"peer":1,"(config-router)":1}
,"advertisements":{"filtering":1,"apply":1,"command":1}
,"matches":{"prefixes":1,"denies":1}
,"prefixes":{"routes":1,"given":1}
,"routes":{"listed":1}
,"listed":{"prefix":1,"top":1}
,"match":{"route":1,"entries":1,"prefix":1,"router":1,"deny":1}
,"route":{"used":1,"denied":1}
,"used":{"empty":1,"filtering":1,"command":1}
,"empty":{"prefix":1}
,"permits":{"prefixes":1}
,"given":{"prefix":1}
,"entries":{"prefix":1}
,"denied":{"access":1}
,"access":{"multiple":1,"list":1}
,"multiple":{"entries":1}
,"entry":{"smallest":1,"command":1}
,"smallest":{"sequence":1}
,"sequence":{"number":1}
,"number":{"considered":1,"once":1}
,"considered":{"real":1}
,"real":{"match":1}
,"router":{"begins":1,"need":1,"mode":1,"bgp":1}
,"begins":{"search":1}
,"search":{"top":1}
,"top":{"prefix":1,"neighbor":1}
,"once":{"match":1}
,"deny":{"occurs":1,"30.0.0.0\u002F24":1}
,"occurs":{"router":1}
,"need":{"rest":1}
,"rest":{"prefix":1}
,"efficiency":{"common":1}
,"common":{"matches":1}
,"denies":{"listed":1}
,"distribute-list":{"command":1}
,"alternative":{"command":1}
,"direction":{"parameter":1}
,"parameter":{"command":1,"used":1}
,"remove":{"entry":1}
,"syntax":{"neighbor":1}
,"(a.b.c.d":{"x:x":1}
,"x:x":{":x:x":1}
,":x:x":{"word)":1,"address":1}
,"word)":{"prefix-list":1}
,"word":{"(in":1,"name":1}
,"(in":{"out)":1}
,"out)":{"neighbor":1,"parameters":1}
,"parameters":{"a.b.c.d":1}
,"a.b.c.d":{"address":1}
,"address":{"bgp":1,"family":1}
,"ipv4":{"format":1}
,"format":{"x:x":1,"word":1}
,"ipv6":{"format":1}
,"name":{"bgp":1,"access":1}
,"peer":{"group":1,"groups":1}
,"group":{"information":1,"word":1}
,"information":{"create":1}
,"create":{"peer":1}
,"groups":{"refer":1}
,"refer":{"neighbor":1}
,"peer-group":{"neighbor":1}
,"remote-as":{"commands":1}
,"commands":{"parameter":1}
,"applies":{"peers":1}
,"peers":{"group":1}
,"apply":{"access":1}
,"incoming":{"advertisements":1}
,"outgoing":{"advertisements":1}
,"mode":{"router":1,"address":1,"examples":1}
,"family":{"mode":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"prefix-list":1,"router":1}
,"list1":{"deny":1}
,"30.0.0.0\u002F24":{"(config)":1}
,"(config-router)":{"neighbor":1}
,"10.10.10.10":{"prefix-list":1}
}
;Search.control.loadWordPairs(pairs);
