var pairs =
{
"spanning-tree":{"instance":1}
,"instance":{"restricted-tcn":1,"true":1,"<1-63>":1,"range":1}
,"restricted-tcn":{"command":1,"spanning-tree":1}
,"command":{"restricted":1,"syntax":1,"mode":1}
,"restricted":{"tcn":1}
,"tcn":{"value":1}
,"value":{"instance":1,"false":1}
,"true":{"command":1}
,"syntax":{"spanning-tree":1}
,"<1-63>":{"restricted-tcn":1,"restricted_tcn":1,"specify":1}
,"restricted_tcn":{"parameters":1}
,"parameters":{"<1-63>":1}
,"specify":{"instance":1}
,"range":{"default":1}
,"default":{"default":1,"restricted":1}
,"false":{"command":1}
,"mode":{"interface":1,"example":1}
,"interface":{"mode":1,"eth0":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"spanning-tree":1}
}
;Search.control.loadWordPairs(pairs);
