var pairs =
{
"service":{"advanced-vty":1}
,"advanced-vty":{"command":1,"service":1,"parameters":1}
,"command":{"multiple":1,"feature":1,"command":1,"syntax":1,"mode":1}
,"multiple":{"options":1}
,"options":{"listed":1}
,"listed":{"tab":1}
,"tab":{"key":1}
,"key":{"pressed":1}
,"pressed":{"completing":1}
,"completing":{"command":1}
,"feature":{"applies":1}
,"applies":{"commands":1}
,"commands":{"option":1}
,"option":{"parameter":1}
,"parameter":{"options":1}
,"syntax":{"service":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"configure":1,"examples":1}
,"configure":{"mode":1,"terminal":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"service":1}
}
;Search.control.loadWordPairs(pairs);
