var pairs =
{
"ospf6_get_next_area_aggregate_route_tag":{"function":1,"(char":1}
,"function":{"gets":1,"fails":1,"succeeds":1}
,"gets":{"next":1}
,"next":{"entry":1}
,"entry":{"aggregate":1}
,"aggregate":{"route":1,"applies":1}
,"route":{"tag":1}
,"tag":{"advertised":1,"ospfv3":1,"area_id":1,"return":1}
,"advertised":{"summarized":1}
,"summarized":{"as-external":1}
,"as-external":{"lsa":1}
,"lsa":{"summarizing":1}
,"summarizing":{"nssa-lsas":1}
,"nssa-lsas":{"as-external-lsas":1}
,"as-external-lsas":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf6_get_next_area_aggregate_route_tag":1,"*area_lsdb_type":1,"*prefix_type":1,"*prefix_len":1,"indexlen":1,"*ret)":1}
,"(char":{"*tag":1}
,"*tag":{"struct":1}
,"struct":{"pal_in4_addr":1,"pal_in6_addr":1}
,"pal_in4_addr":{"*area_id":1}
,"*area_id":{"int":1}
,"*area_lsdb_type":{"int":1}
,"*prefix_type":{"struct":1}
,"pal_in6_addr":{"*prefix":1}
,"*prefix":{"int":1}
,"*prefix_len":{"int":1}
,"indexlen":{"int":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"tag":1,"ret":1}
,"ospfv3":{"process":1}
,"process":{"tag":1}
,"area_id":{"area":1}
,"area":{"identifier":1,"lsdb":1}
,"identifier":{"ipv4":1}
,"ipv4":{"address":1}
,"address":{"format":1,"aggregate":1}
,"format":{"area_lsdb_type":1}
,"area_lsdb_type":{"area":1}
,"lsdb":{"type":1}
,"type":{"given":1,"ospfv3areaaggregateprefix":1}
,"given":{"address":1}
,"applies":{"prefix_type":1}
,"prefix_type":{"prefix":1}
,"prefix":{"type":1,"ipv6":1,"prefix_len":1,"(in":1,"shorter":1}
,"ospfv3areaaggregateprefix":{"object":1}
,"object":{"prefix":1}
,"ipv6":{"prefix":1}
,"prefix_len":{"length":1}
,"length":{"prefix":1,"index":1}
,"(in":{"bits)":1}
,"bits)":{"prefix":1}
,"shorter":{"bits":1}
,"bits":{"index_len":1}
,"index_len":{"length":1}
,"index":{"output":1}
,"output":{"parameters":1}
,"ret":{"aggregate":1}
,"return":{"values":1}
,"values":{"ospf6_api_get_error":1}
,"ospf6_api_get_error":{"function":1}
,"fails":{"ospf6_api_get_success":1}
,"ospf6_api_get_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
