var pairs =
{
"mpls":{"tables":1}
,"tables":{"following":1,"(as":1}
,"following":{"subsection":1,"information":1,"operations":1}
,"subsection":{"describes":1}
,"describes":{"supported":1}
,"supported":{"tabled":1}
,"tabled":{"used":1}
,"used":{"mpls-nsf":1,"forwarding":1}
,"mpls-nsf":{"ftn":1}
,"ftn":{"table":1,"entry":1}
,"table":{"ftn":1,"maps":1,"used":1,"ilm":1,"nhlfe":1,"contains":1,"cross-connect":1,"connects":1,"referenced":1,"addition":1,"index":1,"hosts":1,"reference":1}
,"maps":{"fec":1,"incoming":1}
,"fec":{"nhlfe":1}
,"nhlfe":{"objects":1,"table":1,"entries":1}
,"objects":{"table":1,"zebos-xp":1}
,"forwarding":{"packets":1,"labeled":1}
,"packets":{"arrive":1}
,"arrive":{"unlabeled":1}
,"unlabeled":{"need":1}
,"need":{"labeled":1}
,"labeled":{"forwarded":1,"packet":1}
,"forwarded":{"ilm":1}
,"ilm":{"table":1,"entries":1}
,"incoming":{"label":1}
,"label":{"nhlfe":1,"stack":1,"top":1,"(swap)":1,"push":1,"onto":1,"outgoing":1,"zebos-xp":1}
,"zebos-xp":{"rib":1,"table":1}
,"rib":{"entry":1}
,"entry":{"structure":1,"pointer":1}
,"structure":{"located":1}
,"located":{"ilm_entry":1}
,"ilm_entry":{"file":1}
,"file":{"nhlfe":1}
,"packet":{"table":1,"operation":1,"including":1}
,"contains":{"following":1}
,"information":{"nexthop":1}
,"nexthop":{"packet":1}
,"operation":{"required":1}
,"required":{"perform":1}
,"perform":{"label":1}
,"stack":{"packet":1,"specified":1,"replace":1,"cross-connect":1}
,"including":{"following":1}
,"operations":{"replace":1}
,"replace":{"label":1}
,"top":{"label":1}
,"specified":{"new":1}
,"new":{"label":1}
,"(swap)":{"pop":1}
,"pop":{"label":1}
,"push":{"specified":1}
,"onto":{"label":1}
,"cross-connect":{"(xc)":1,"table":1}
,"(xc)":{"table":1}
,"connects":{"incoming":1}
,"outgoing":{"label":1}
,"referenced":{"linked":1}
,"linked":{"tables":1}
,"(as":{"previously":1}
,"previously":{"described)":1}
,"described)":{"ftn":1}
,"pointer":{"reference":1}
,"reference":{"table":1,"nhlfe":1}
,"addition":{"ilm":1}
,"entries":{"cross-connect":1}
,"index":{"table":1}
,"hosts":{"nhlfe":1}
}
;Search.control.loadWordPairs(pairs);
