var pairs =
{
"ripng":{"api":1,"functions":1,"routing":1,"static":1}
,"api":{"functions":1}
,"functions":{"table":1,"details":1}
,"table":{"below":1,"ripng_timers_set":1}
,"below":{"summary":1}
,"summary":{"ripng":1}
,"details":{"provided":1}
,"provided":{"following":1}
,"following":{"subsections":1}
,"subsections":{"function":1}
,"function":{"description":1}
,"description":{"ripng_aggregate_add":1}
,"ripng_aggregate_add":{"aggregates":1}
,"aggregates":{"rip":1}
,"rip":{"route":1,"routing":1,"split-horizon":1,"router":1,"ripng_offset_list_unset":1,"updates":1,"broadcasts":1,"udp":1,"routes":1,"ripng_route_default_delete":1,"ripng_route_delete":1,"timer":1}
,"route":{"announcements":1,"rip":1,"ripng_route_type_delete":1}
,"announcements":{"ripng_aggregate_delete":1}
,"ripng_aggregate_delete":{"deletes":1}
,"deletes":{"aggregate":1}
,"aggregate":{"advertising":1}
,"advertising":{"routes":1}
,"routes":{"ripng_cisco_metric_behavior_set":1,"ripng_default_metric_unset":1,"ripng_distance_set_default":1,"learned":1,"ripng_route_default_add":1}
,"ripng_cisco_metric_behavior_set":{"sets":1}
,"sets":{"metric":1,"routing":1,"administrative":1,"specified":1}
,"metric":{"update":1,"value":1}
,"update":{"cisco":1}
,"cisco":{"ripng_cisco_metric_behavior_unset":1,"ripng_default_metric_set":1}
,"ripng_cisco_metric_behavior_unset":{"unsets":1}
,"unsets":{"metric":1,"metrics":1,"redistribute":1,"configured":1}
,"ripng_default_metric_set":{"sets":1}
,"routing":{"protocol":1,"specified":1,"neighbor":1,"interface":1,"protocols":1,"table":1}
,"protocol":{"specified":1}
,"specified":{"metric":1,"value":1,"neighbor":1,"size":1,"data":1,"time":1}
,"value":{"redistributed":1,"ripng_distance_unset_default":1}
,"redistributed":{"routes":1}
,"ripng_default_metric_unset":{"unsets":1}
,"metrics":{"assigned":1,"routes":1}
,"assigned":{"redistributed":1}
,"ripng_distance_set_default":{"sets":1}
,"administrative":{"distance":1}
,"distance":{"specified":1,"default":1}
,"ripng_distance_unset_default":{"resets":1}
,"resets":{"administrative":1,"size":1,"three":1}
,"default":{"value:120":1,"route":1,"values":1}
,"value:120":{"ripng_enable_nbr_add":1}
,"ripng_enable_nbr_add":{"enables":1}
,"enables":{"rip":1,"ripng":1}
,"neighbor":{"ripng_enable_nbr_delete":1,"ripng_if_ipv6_router_set":1}
,"ripng_enable_nbr_delete":{"disables":1}
,"disables":{"rip":1,"ripng":1,"split":1,"blocking":1,"configuration":1}
,"ripng_if_ipv6_router_set":{"enables":1}
,"interface":{"ripng_if_ipv6_router_unset":1,"ripng_if_split_horizon_poisoned_set":1,"ripng_recvbuf_size_set":1}
,"ripng_if_ipv6_router_unset":{"disables":1}
,"ripng_if_split_horizon_poisoned_set":{"enables":1}
,"split-horizon":{"poisoned":1,"behavior":1}
,"poisoned":{"reverse":1}
,"reverse":{"behavior":1}
,"behavior":{"ripng_if_split_horizon_set":1,"ripng_if_split_horizon_unset":1,"ripng_instance_set":1}
,"ripng_if_split_horizon_set":{"enables":1}
,"ripng_if_split_horizon_unset":{"disables":1}
,"split":{"horizon":1}
,"horizon":{"behavior":1}
,"ripng_instance_set":{"establishes":1}
,"establishes":{"instance":1}
,"instance":{"ipv6":1}
,"ipv6":{"rip":1,"router":1}
,"router":{"ripng_instance_unset":1,"ripng_offset_list_set":1}
,"ripng_instance_unset":{"removes":1}
,"removes":{"instance":1,"offset":1}
,"ripng_offset_list_set":{"adds":1}
,"adds":{"offset":1}
,"offset":{"metrics":1,"list":1}
,"learned":{"rip":1}
,"ripng_offset_list_unset":{"removes":1}
,"list":{"ripng_passive_if_add":1}
,"ripng_passive_if_add":{"suppresses":1}
,"suppresses":{"rip":1}
,"updates":{"ripng_passive_if_delete":1}
,"ripng_passive_if_delete":{"disables":1}
,"blocking":{"rip":1}
,"broadcasts":{"interface":1}
,"ripng_recvbuf_size_set":{"sets":1}
,"size":{"rip":1}
,"udp":{"buffer":1}
,"buffer":{"ripng_recvbuf_size_unset":1,"ripng_redistribute_metric_set":1}
,"ripng_recvbuf_size_unset":{"resets":1}
,"ripng_redistribute_metric_set":{"redistributes":1}
,"redistributes":{"information":1}
,"information":{"routing":1}
,"protocols":{"ripng_redistribute_metric_rmap_set":1,"ripng_redistribute_rmap_set":1,"ripng_redistribute_set":1,"ripng_redistribute_unset":1}
,"ripng_redistribute_metric_rmap_set":{"redistributes":1}
,"ripng_redistribute_rmap_set":{"redistributes":1}
,"ripng_redistribute_set":{"redistributes":1}
,"ripng_redistribute_unset":{"unsets":1}
,"redistribute":{"configuration":1}
,"configuration":{"ripng_route_add":1,"default":1}
,"ripng_route_add":{"configures":1}
,"configures":{"static":1}
,"static":{"rip":1,"route":1}
,"ripng_route_default_add":{"generates":1}
,"generates":{"default":1}
,"ripng_route_default_delete":{"disables":1}
,"ripng_route_delete":{"unsets":1}
,"configured":{"ripng":1}
,"ripng_route_type_delete":{"clears":1}
,"clears":{"specified":1}
,"data":{"ripng":1}
,"ripng_timers_set":{"sets":1}
,"time":{"per":1}
,"per":{"rip":1}
,"timer":{"ripng_timers_unset":1}
,"ripng_timers_unset":{"resets":1}
,"three":{"timers":1}
,"timers":{"default":1}
}
;Search.control.loadWordPairs(pairs);
