var pairs =
{
"loopback":{"protocol":1,"messages":1,"response":1,"responses":1,"message":1}
,"protocol":{"pbb-te":1}
,"pbb-te":{"transmitting":1,"destination_address":1,"mip":1,"services":1,"meps":1,"mips":1}
,"transmitting":{"loopback":1}
,"messages":{"loopback":1,"(lbm)":1}
,"(lbm)":{"transmitted":1}
,"transmitted":{"mep":1,"pbb-te":1,"lbr":1}
,"mep":{"associated":1,"root":1,"reverse":1,"leaf":1,"receives":1}
,"associated":{"pbb-te":1,"values":1,"point-to-multipoint":1}
,"destination_address":{"parameter":1,"received":1}
,"parameter":{"mac":1,"provided":1,"used":1,"transmitted":1}
,"mac":{"address":1,"field":1,"pbb-te":1,"reverse":1,"=esp-sa":1,"reply":1,"esp-da":1,"(or":1,"leaf":1,"=esp-da":1,"loopback":1,"(in":1,"respond":1}
,"address":{"indicated":1,"associated":1,"lbm":1,"mac":1,"mip":1,"field":1,"esp-mac":1,"otherwise":1,"individual":1,"value":1,"group":1,"vlan_identifier":1,"=mip":1}
,"indicated":{"value":1,"esp-mac":1}
,"value":{"esp-mac":1,"point-to-point":1,"carried":1,"source_address":1,"primary":1}
,"esp-mac":{"field":1,"value":1,"point-to-multipoint":1,"component":1,"lbm":1}
,"field":{"ma\u0027s":1,"enable":1,"monitored":1,"included":1,"contains":1,"mac":1,"case":1,"contained":1,"matches":1,"(in":1}
,"ma\u0027s":{"component":1}
,"component":{"esp":1,"esps":1}
,"esp":{"mep\u0027s":1,"service":1,"list":1,"uses":1,"group":1,"payload":1}
,"mep\u0027s":{"mac":1,"address":1}
,"enable":{"intermediate":1}
,"intermediate":{"mips":1}
,"mips":{"selectively":1,"destination_address":1,"value":1}
,"selectively":{"intercept":1}
,"intercept":{"lbms":1}
,"lbms":{"targeting":1,"received":1,"except":1}
,"targeting":{"pbb-te":1}
,"mip":{"tlv":1,"mac":1,"lbm":1,"forwards":1,"associated":1,"loopback":1,"destination_address":1,"pbb-te":1,"mip":1,"contains":1}
,"tlv":{"inserted":1,"lbm":1,"included":1,"follows":1,"used":1,"pbb-te":1,"containing":1,"received":1,"added":1,"contains":1,"loopback":1}
,"inserted":{"first":1}
,"first":{"tlv":1}
,"lbm":{"pbb-te":1,"destination":1,"associated":1,"targeted":1,"carries":1,"group":1,"source_address":1,"lbm\u002Flbr":1,"point-to-multipoint":1,"reply":1,"cbp-a":1,"forwarded":1,"case":1,"mep":1,"validate":1}
,"included":{"lbm":1,"mep":1}
,"destination":{"address":1}
,"values":{"esp-mac":1,"esp-da":1}
,"monitored":{"ma\u0027s":1,"ma\u2019s":1}
,"esps":{"format":1,"otherwise":1,"service":1}
,"format":{"pbb-te":1}
,"follows":{"type":1}
,"type":{"used":1,"length":1}
,"used":{"mas":1,"target":1,"vlan_identifier":1,"loopback":1,"lbrs":1,"mip":1}
,"mas":{"monitoring":1}
,"monitoring":{"pbb-te":1}
,"services":{"enables":1}
,"enables":{"intermediate":1}
,"target":{"address":1}
,"esp-da":{"field":1,"=reverse":1,"group":1}
,"ma\u2019s":{"component":1}
,"otherwise":{"present":1,"value":1}
,"present":{"mip":1}
,"targeted":{"reverse":1}
,"reverse":{"vid":1,"mac":1}
,"vid":{"parameter":1,"vlan_identifier":1,"field":1,"=one":1}
,"provided":{"used":1}
,"vlan_identifier":{"loopback":1,"used":1}
,"response":{"(lbr)":1,"destination_address":1,"mip":1}
,"(lbr)":{"reverse":1}
,"point-to-multipoint":{"service":1,"esp":1,"lbm":1}
,"service":{"instance":1}
,"instance":{"mep":1,"validity":1}
,"root":{"mep":1,"initiates":1}
,"contains":{"esp-mac":1,"type":1,"esp-sa":1,"esp-da":1}
,"point-to-point":{"esps":1}
,"leaf":{"mep":1,"initiates":1,"(cbp-c)":1}
,"validity":{"test":1}
,"test":{"lbms":1}
,"received":{"pbb-te":1,"lbm":1,"lbms":1,"lbr":1,"lbm\u0027s":1}
,"meps":{"processed":1,"value":1,"discard":1}
,"processed":{"discarded":1}
,"discarded":{"received":1}
,"carries":{"pbb-te":1}
,"forwards":{"received":1}
,"except":{"carrying":1}
,"carrying":{"pbb-te":1}
,"containing":{"mip":1}
,"responses":{"transmitted":1}
,"case":{"pbb-te":1,"leaf":1}
,"lbr":{"value":1,"esp-mac":1}
,"carried":{"reverse":1}
,"contained":{"pbb-te":1}
,"group":{"mac":1,"mac)":1}
,"source_address":{"received":1,"lbrs":1}
,"lbrs":{"transmitted":1}
,"individual":{"mac":1}
,"lbm\u0027s":{"destination":1}
,"primary":{"vid":1}
,"lbm\u002Flbr":{"frame":1}
,"frame":{"flow":1,"root":1,"pbb-te":1}
,"flow":{"figure":1}
,"figure":{"below":1}
,"below":{"consider":1}
,"consider":{"point-to-multipoint":1}
,"reply":{"requested":1,"sent":1}
,"requested":{"mip":1}
,"added":{"frame":1}
,"initiates":{"point-to-multipoint":1}
,"cbp-a":{"(root":1,"mip":1}
,"(root":{"mep)":1}
,"mep)":{"sends":1}
,"sends":{"lbm":1}
,"length":{"=14":1}
,"=14":{"reverse":1}
,"=one":{"esp":1}
,"list":{"te-sid":1}
,"te-sid":{"used":1}
,"=mip":{"mac":1}
,"=esp-sa":{"cbp-a":1}
,"matches":{"mip-1":1}
,"mip-1":{"mac":1,"lbm":1,"part":1}
,"sent":{"mip-1":1}
,"forwarded":{"case":1}
,"discard":{"frame":1}
,"esp-sa":{"=group":1,"=reverse":1,"received":1}
,"=group":{"mac":1}
,"=reverse":{"mac":1}
,"(or":{"cbp-a\u0027s":1}
,"cbp-a\u0027s":{"mac)":1}
,"mac)":{"mip-1":1,"esp-sa":1,"esp-da":1}
,"part":{"point-to-multipoint":1}
,"uses":{"group":1}
,"(cbp-c)":{"initiating":1}
,"initiating":{"loopback":1}
,"message":{"pbb-te":1}
,"=esp-da":{"point-to-multipoint":1}
,"(in":{"example":1}
,"example":{"group":1}
,"respond":{"cbp-c":1}
,"cbp-c":{"point-to-multipoint":1}
,"payload":{"esp-sa":1}
,"receives":{"lbm":1}
}
;Search.control.loadWordPairs(pairs);
