var pairs =
{
"secondary":{"no-cspf":1,"cspf":1}
,"no-cspf":{"command":1,"parameters":1}
,"command":{"disable":1,"revert":1,"syntax":1,"mode":1,"trunk":1}
,"disable":{"constrained":1,"cspf":1}
,"constrained":{"shortest":1}
,"shortest":{"path":1}
,"path":{"first":1,"lsp":1,"specified":1}
,"first":{"(cspf)":1}
,"(cspf)":{"server":1}
,"server":{"explicit":1,"computes":1}
,"explicit":{"route":1,"routes":1,"path":1}
,"route":{"egress":1}
,"egress":{"rsvp":1}
,"rsvp":{"sessions":1}
,"sessions":{"cspf":1}
,"cspf":{"turned":1,"computation":1,"server":1,"considers":1,"nodes":1,"command":1,"primary":1}
,"turned":{"globally":1}
,"globally":{"cannot":1}
,"cannot":{"enabled":1}
,"enabled":{"lsp":1}
,"lsp":{"used":1,"cspf":1,"links":1,"established":1,"configure":1}
,"used":{"per":1,"turn":1}
,"per":{"lsp":1}
,"turn":{"cspf":1}
,"computation":{"specific":1}
,"specific":{"lsp":1}
,"computes":{"paths":1}
,"paths":{"lsps":1}
,"lsps":{"subject":1,"cspf":1,"manually":1}
,"subject":{"various":1}
,"various":{"constraints":1}
,"constraints":{"bandwidth":1}
,"bandwidth":{"hop":1}
,"hop":{"count":1}
,"count":{"administrative":1}
,"administrative":{"groups":1}
,"groups":{"priority":1}
,"priority":{"explicit":1}
,"routes":{"computing":1}
,"computing":{"paths":1}
,"considers":{"topology":1}
,"topology":{"network":1}
,"network":{"attributes":1,"load":1}
,"attributes":{"defined":1}
,"defined":{"lsp":1}
,"links":{"attempts":1}
,"attempts":{"minimize":1}
,"minimize":{"congestion":1}
,"congestion":{"intelligently":1}
,"intelligently":{"balancing":1}
,"balancing":{"network":1}
,"load":{"disable":1}
,"nodes":{"support":1}
,"support":{"required":1}
,"required":{"traffic":1}
,"traffic":{"engineering":1}
,"engineering":{"extensions":1}
,"extensions":{"configure":1}
,"configure":{"lsps":1,"terminal":1}
,"manually":{"explicit":1}
,"established":{"along":1}
,"along":{"path":1}
,"specified":{"operator":1}
,"operator":{"secondary":1}
,"revert":{"default":1}
,"default":{"settings":1}
,"settings":{"command":1}
,"syntax":{"secondary":1}
,"parameters":{"none":1}
,"none":{"command":1}
,"mode":{"trunk":1,"example":1,"disable":1}
,"trunk":{"mode":1}
,"example":{"example":1,"shows":1}
,"shows":{"using":1}
,"using":{"no-cspf":1}
,"primary":{"lsp":1}
,"terminal":{"(config)":1}
,"(config)":{"rsvp-trunk":1}
,"rsvp-trunk":{"mytrunk":1}
,"mytrunk":{"(config-trunk)":1}
,"(config-trunk)":{"secondary":1}
}
;Search.control.loadWordPairs(pairs);
