var pairs =
{
"pbb-te":{"configurations":1}
,"configurations":{"configurations":1,"chapter":1}
,"chapter":{"illustrate":1}
,"illustrate":{"provider":1}
,"provider":{"backbone":1}
,"backbone":{"bridging":1}
,"bridging":{"traffic":1,"supported":1}
,"traffic":{"engineering":1}
,"engineering":{"different":1}
,"different":{"network":1}
,"network":{"topologies":1}
,"topologies":{"examples":1}
,"examples":{"provided":1}
,"provided":{"ethernet":1}
,"ethernet":{"switched":1}
,"switched":{"path":1}
,"path":{"automated":1}
,"automated":{"protection":1}
,"protection":{"switching":1}
,"switching":{"unicast":1}
,"unicast":{"connectivity":1}
,"connectivity":{"fault":1}
,"fault":{"management":1}
,"management":{"multicast":1,"provider":1}
,"multicast":{"connectivity":1}
,"supported":{"zebic":1}
,"zebic":{"releases":1}
}
;Search.control.loadWordPairs(pairs);
