var pairs =
{
"isis_get_lsp_attributes":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"flags":1}
,"flags":{"carried":1}
,"carried":{"lsp":1}
,"lsp":{"syntax":1,"belongs":1,"lsp":1,"output":1,"return":1,"found":1}
,"syntax":{"int":1}
,"int":{"isis_get_lsp_attributes":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1,"instance":1}
,"u_int32_t":{"instance":1,"level":1,"*ret)":1}
,"instance":{"u_int32_t":1,"is-is":1,"level":1}
,"level":{"struct":1,"is-is":1,"lsp":1,"isis_api_get_error":1}
,"struct":{"isis_lspid":1}
,"isis_lspid":{"lspid":1}
,"lspid":{"u_int32_t":1,"lsp":1}
,"*ret)":{"input":1}
,"input":{"parameter":1}
,"parameter":{"vr_id":1,"ret":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1,"isis_api_get_success":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"is-is":{"instance":1,"level":1}
,"belongs":{"lspid":1}
,"output":{"parameter":1}
,"ret":{"flags":1}
,"return":{"value":1}
,"isis_api_get_success":{"lsp":1}
,"found":{"specified":1}
,"specified":{"instance":1}
,"isis_api_get_error":{"lsp":1}
}
;Search.control.loadWordPairs(pairs);
