var pairs =
{
"designated":{"routers":1,"router":1}
,"routers":{"multi-access":1}
,"multi-access":{"(ethernet)":1,"network":1}
,"(ethernet)":{"network":1}
,"network":{"elects":1,"segment":1,"causes":1,"link":1,"bdr":1}
,"elects":{"designated":1}
,"router":{"(dr)":1,"(bdr)":1,"connected":1,"assumes":1}
,"(dr)":{"backup":1}
,"backup":{"designated":1}
,"(bdr)":{"performs":1}
,"performs":{"two":1}
,"two":{"key":1}
,"key":{"functions":1}
,"functions":{"network":1}
,"segment":{"forms":1}
,"forms":{"adjacencies":1}
,"adjacencies":{"routers":1,"designated":1}
,"causes":{"become":1}
,"become":{"focal":1}
,"focal":{"point":1}
,"point":{"forwarding":1}
,"forwarding":{"link-state":1}
,"link-state":{"advertisements":1}
,"advertisements":{"generates":1,"listing":1}
,"generates":{"network":1}
,"link":{"advertisements":1}
,"listing":{"router":1}
,"connected":{"multi-access":1}
,"bdr":{"forms":1}
,"assumes":{"functionality":1}
,"functionality":{"fails":1}
}
;Search.control.loadWordPairs(pairs);
