var pairs =
{
"esp":{"ingress":1,"(ethernet":1,"command":1,"multicast":1,"tesi":1}
,"ingress":{"remote-mac":1,"path":1,"esp":1,"(multicast":1,"multicast":1}
,"remote-mac":{"command":1,"remote_mac":1,"specify":1,"1111.1111.1111":1}
,"command":{"esp":1,"remove":1,"syntax":1,"mode":1}
,"(ethernet":{"switched":1}
,"switched":{"path)":1}
,"path)":{"ingress":1}
,"path":{"tesi":1}
,"tesi":{"form":1,"(pbb-te-esp-if-config)":1}
,"form":{"command":1}
,"remove":{"ingress":1}
,"syntax":{"esp":1}
,"(multicast":{"mcast-mac":1}
,"mcast-mac":{"mult_sa":1,"indicate":1,"1111.1111.1111":1}
,"mult_sa":{"remote-mac":1,"add":1}
,"remote_mac":{"vlan":1,"add":1}
,"vlan":{"vlanid":1,"vlan":1,"command":1,"(pbb-te-esp-if-config)":1,"configure":1}
,"vlanid":{"esp":1,"parameters":1,"vlan":1}
,"parameters":{"multicast":1}
,"multicast":{"indicate":1,"mcast-mac":1}
,"indicate":{"esp":1,"receive":1}
,"receive":{"mac":1}
,"mac":{"address":1}
,"address":{"mult_sa":1,"hhhh.hhhh.hhhh":1,"remote":1}
,"add":{"receive":1,"remote":1}
,"hhhh.hhhh.hhhh":{"format":1}
,"format":{"remote-mac":1,"vlan":1}
,"specify":{"mac":1}
,"remote":{"cbp":1,"mac":1}
,"cbp":{"(customer":1}
,"(customer":{"backbone":1}
,"backbone":{"port)":1}
,"port)":{"remote_mac":1}
,"mode":{"pbb-te":1,"examples":1}
,"pbb-te":{"configure":1}
,"configure":{"switching":1,"terminal":1,"esp":1}
,"switching":{"mode":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"interface":{"cbp.1":1}
,"cbp.1":{"(config-if)":1}
,"(config-if)":{"shutdown":1,"pbb-te":1}
,"shutdown":{"(config-if)":1}
,"(pbb-te-esp-if-config)":{"esp":1}
,"1111.1111.1111":{"vlan":1,"remote-mac":1}
}
;Search.control.loadWordPairs(pairs);
