var pairs =
{
"mstp_api_set_forward_delay":{"function":1,"(char":1}
,"function":{"sets":1,"succeeds":1,"fails":1}
,"sets":{"forward":1}
,"forward":{"delay":1}
,"delay":{"interval":1}
,"interval":{"(in":1,"seconds":1}
,"(in":{"seconds)":1}
,"seconds)":{"bridge":1}
,"bridge":{"syntax":1,"forward_delay":1}
,"syntax":{"int":1}
,"int":{"mstp_api_set_forward_delay":1}
,"(char":{"*name":1}
,"*name":{"s_int32_t":1}
,"s_int32_t":{"forward_delay)":1}
,"forward_delay)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"name":1,"none":1}
,"name":{"name":1,"bridge":1}
,"forward_delay":{"bridge\u0027s":1}
,"bridge\u0027s":{"forward":1}
,"seconds":{"value":1}
,"value":{"range":1}
,"range":{"mstp_min_bridge_fwd_delay":1}
,"mstp_min_bridge_fwd_delay":{"mstp_max_bridge_fwd_delay":1}
,"mstp_max_bridge_fwd_delay":{"defined":1}
,"defined":{"mstpd\u002Fmstp_config.h":1}
,"mstpd\u002Fmstp_config.h":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"result_ok":1}
,"result_ok":{"function":1}
,"succeeds":{"result_error":1}
,"result_error":{"function":1}
}
;Search.control.loadWordPairs(pairs);
