var pairs =
{
"g8032_api_update_rpl":{"function":1,"(u_int8_t":1}
,"function":{"updates":1,"fails":1,"succeeds":1}
,"updates":{"ring":1}
,"ring":{"protection":1,"exists":1,"is_east":1,"instance":1,"g8032_cfm_mep_notfound":1}
,"protection":{"link":1,"ring":1}
,"link":{"owner":1}
,"owner":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"g8032_api_update_rpl":1}
,"(u_int8_t":{"*br_name":1}
,"*br_name":{"u_int32_t":1}
,"u_int32_t":{"ring_id":1,"node_type)":1}
,"ring_id":{"bool_t":1,"protection":1}
,"bool_t":{"is_east":1}
,"is_east":{"u_int8_t":1,"whether":1}
,"u_int8_t":{"non_owner_set_val":1}
,"non_owner_set_val":{"u_int32_t":1,"value":1}
,"node_type)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"br_name":1,"none":1}
,"br_name":{"bridge":1}
,"bridge":{"name":1}
,"name":{"protection":1}
,"exists":{"ring_id":1}
,"whether":{"node":1}
,"node":{"east":1,"affected":1}
,"east":{"non_owner_set_val":1}
,"value":{"non-owner":1}
,"non-owner":{"status":1}
,"status":{"node_type":1}
,"node_type":{"type":1}
,"type":{"node":1}
,"affected":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"g8032_ring_null":1}
,"g8032_ring_null":{"ring":1}
,"instance":{"found":1}
,"found":{"g8032_interface_mismatch":1,"g8032_failure":1}
,"g8032_interface_mismatch":{"mismatch":1}
,"mismatch":{"interface":1}
,"interface":{"configured":1}
,"configured":{"ring":1}
,"g8032_cfm_mep_notfound":{"mep":1}
,"mep":{"found":1}
,"g8032_failure":{"function":1}
,"fails":{"g8032_api_err_none":1}
,"g8032_api_err_none":{"function":1}
}
;Search.control.loadWordPairs(pairs);
