var pairs =
{
"show":{"storm-control":1}
,"storm-control":{"command":1,"(ifname":1,"eth1":1}
,"command":{"display":1,"syntax":1,"mode":1,"displaying":1}
,"display":{"storm":1}
,"storm":{"control":1}
,"control":{"information":1}
,"information":{"interfaces":1,"show":1}
,"interfaces":{"particular":1}
,"particular":{"interface":1}
,"interface":{"command":1}
,"syntax":{"show":1}
,"(ifname":{"parameters":1}
,"parameters":{"ifname":1}
,"ifname":{"name":1}
,"name":{"interface":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"following":1}
,"following":{"sample":1}
,"sample":{"output":1}
,"output":{"command":1}
,"displaying":{"storm":1}
,"eth1":{"port":1}
,"port":{"bcastlevel":1}
,"bcastlevel":{"bcastdiscards":1}
,"bcastdiscards":{"mcastlevel":1}
,"mcastlevel":{"mcastdiscards":1}
,"mcastdiscards":{"dlflevel":1}
,"dlflevel":{"dlfdiscards":1}
,"dlfdiscards":{"fe14":1}
,"fe14":{"64290164":1}
,"64290164":{"100":1}
,"100":{"64290164":1}
}
;Search.control.loadWordPairs(pairs);
