var pairs =
{
"nsm_ovc_info":{"structure":1,"u_int8_t":1,"*ovc_info":1}
,"structure":{"nsm\u002Fl2\u002Fnsm_pro_vlan.h":1}
,"nsm\u002Fl2\u002Fnsm_pro_vlan.h":{"struct":1}
,"struct":{"nsm_ovc_info":1,"nsm_oep_map_trans_key":1,"nsm_oep_info":1,"nsm_vlan_bmp":1,"list":1,"nsm_oep_map_tab":1,"nsm_bridge":1,"avl_tree":1}
,"u_int8_t":{"*ovc_id":1,"*oep_id":1,"preserve_vlan":1,"type":1}
,"*ovc_id":{"u_int8_t":1}
,"*oep_id":{"u_int8_t":1}
,"preserve_vlan":{"u_int16_t":1}
,"u_int16_t":{"num_ovcs":1,"vid":1,"ovc_vid":1,"svid":1,"ovc_type":1}
,"num_ovcs":{"define":1}
,"define":{"nsm_cvlan_cos_preserve":1,"nsm_cvlan_id_preserve":1,"nsm_svlan_cos_preserve":1,"nsm_svlan_id_preserve":1,"nsm_oep_map_type_invalid":1,"nsm_oep_map_type_uni":1,"nsm_oep_map_type_enni":1,"nsm_oep_map_tab_name_max":1}
,"nsm_cvlan_cos_preserve":{"<<0)":1}
,"<<0)":{"define":1}
,"nsm_cvlan_id_preserve":{"<<1)":1}
,"<<1)":{"define":1}
,"nsm_svlan_cos_preserve":{"<<2)":1}
,"<<2)":{"define":1,"struct":1}
,"nsm_svlan_id_preserve":{"<<3)":1}
,"<<3)":{"struct":1}
,"nsm_oep_map_trans_key":{"u_int16_t":1}
,"vid":{"u_int16_t":1}
,"ovc_vid":{"struct":1}
,"nsm_oep_info":{"struct":1}
,"nsm_vlan_bmp":{"ennisvlanbmp":1}
,"ennisvlanbmp":{"struct":1}
,"*ovc_info":{"struct":1}
,"list":{"*port_list":1}
,"*port_list":{"u_int16_t":1,"struct":1}
,"svid":{"\u002F*required":1}
,"\u002F*required":{"add":1}
,"add":{"map":1}
,"map":{"uni":1}
,"uni":{"*\u002F+":1}
,"*\u002F+":{"u_int16_t":1}
,"ovc_type":{"struct":1}
,"nsm_oep_map_tab":{"u_int8_t":1}
,"type":{"define":1}
,"nsm_oep_map_type_invalid":{"<<0)":1}
,"nsm_oep_map_type_uni":{"<<1)":1}
,"nsm_oep_map_type_enni":{"<<2)":1}
,"nsm_bridge":{"*bridge":1}
,"*bridge":{"struct":1}
,"avl_tree":{"*oep_map":1,"*oep_tree":1}
,"*oep_map":{"struct":1}
,"*oep_tree":{"define":1}
,"nsm_oep_map_tab_name_max":{"char":1}
,"char":{"name":1}
,"name":{"[nsm_oep_map_tab_name_max":1}
}
;Search.control.loadWordPairs(pairs);
