var pairs =
{
"vrrp":{"module":1,"requirements":1,"pal":1}
,"module":{"architecture":1}
,"architecture":{"vrrp":1}
,"requirements":{"involve":1}
,"involve":{"lower-level":1}
,"lower-level":{"operating":1}
,"operating":{"system":1,"system-dependent":1}
,"system":{"calls":1,"implementation":1}
,"calls":{"implemented":1}
,"implemented":{"correctly":1}
,"correctly":{"result":1}
,"result":{"functionality":1}
,"functionality":{"differs":1,"resides":1}
,"differs":{"platform":1}
,"platform":{"platform":1,"majority":1}
,"majority":{"implementation":1}
,"implementation":{"made":1,"details":1}
,"made":{"os-independent":1}
,"os-independent":{"however":1}
,"however":{"possible":1}
,"possible":{"areas":1}
,"areas":{"operating":1}
,"system-dependent":{"functionality":1}
,"resides":{"various":1}
,"various":{"pal":1}
,"pal":{"files":1,"api":1}
,"files":{"api":1,".\u005Cvrrp":1}
,"api":{"established":1,"definitions":1}
,"established":{"vrrp":1}
,"definitions":{"reside":1}
,"reside":{"\u002Fpal\u002F<platform>\u002Fpal_kernel.c":1}
,"\u002Fpal\u002F<platform>\u002Fpal_kernel.c":{"<platform>":1}
,"<platform>":{"linux":1}
,"linux":{"ose":1}
,"ose":{"openbsd":1}
,"openbsd":{"system":1}
,"details":{"following":1}
,"following":{"files":1}
,".\u005Cvrrp":{"directory":1}
,"directory":{"vrrp.c":1}
,"vrrp.c":{"vrrp.h":1}
,"vrrp.h":{"vrrp_api.c":1}
,"vrrp_api.c":{"vrrp_api.h":1}
,"vrrp_api.h":{"vrrp_cli.c":1}
,"vrrp_cli.c":{"vrrp_fe.c":1}
,"vrrp_fe.c":{"vrrp_init.c":1}
,"vrrp_init.c":{"vrrp_init.h":1}
,"vrrp_init.h":{"vrrp_ip.c":1}
,"vrrp_ip.c":{"vrrp_sys.c":1}
,"vrrp_sys.c":{"vrrp.tbl":1}
}
;Search.control.loadWordPairs(pairs);
