var pairs =
{
"spb_api_spvid_unconfig":{"function":1,"(char":1}
,"function":{"unmaps":1,"implements":1,"succeeds":1}
,"unmaps":{"shortest":1}
,"shortest":{"path":1}
,"path":{"vlan":1}
,"vlan":{"identifier":1,"function":1,"cannot":1}
,"identifier":{"(spvid)":1,"<3996-4095>":1,"<1-4094>":1}
,"(spvid)":{"base":1}
,"base":{"vlan":1}
,"implements":{"bridge":1}
,"bridge":{"(<1-32>":1,"name":1,"instance":1,"given":1,"edge":1,"spb_api_err_spbv_automode":1}
,"(<1-32>":{"backbone)":1}
,"backbone)":{"spbv":1}
,"spbv":{"bvlan":1,"supported":1}
,"bvlan":{"<1-4094>":1}
,"<1-4094>":{"command":1,"output":1}
,"command":{"syntax":1}
,"syntax":{"include":1}
,"include":{"spbd\u002Fspb_api.h":1}
,"spbd\u002Fspb_api.h":{"int":1}
,"int":{"spb_api_spvid_unconfig":1}
,"(char":{"*bridge_name":1}
,"*bridge_name":{"u_int16_t":1}
,"u_int16_t":{"mt_id":1}
,"mt_id":{"spb_vid_t":1,"multi-topology":1,"exist":1}
,"spb_vid_t":{"bvid)":1}
,"bvid)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bridge_name":1,"none":1}
,"bridge_name":{"bridge":1,"null":1}
,"name":{"mt_id":1}
,"multi-topology":{"identifier":1}
,"<3996-4095>":{"bvid":1}
,"bvid":{"base":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"spb_api_err_bridge_name_is_null":1}
,"spb_api_err_bridge_name_is_null":{"bridge_name":1}
,"null":{"spb_api_err_bridge_instance_not_found":1,"result_error":1}
,"spb_api_err_bridge_instance_not_found":{"bridge":1}
,"instance":{"null":1,"result_ok":1}
,"result_error":{"spbv":1}
,"supported":{"bridge":1}
,"given":{"mt_id":1}
,"exist":{"backbone":1}
,"backbone":{"vlan":1}
,"cannot":{"found":1}
,"found":{"spb_api_err_spbv_not_edge_bridge":1}
,"spb_api_err_spbv_not_edge_bridge":{"bridge":1}
,"edge":{"bridge":1}
,"spb_api_err_spbv_automode":{"spvid":1}
,"spvid":{"automatic":1}
,"automatic":{"allocation":1}
,"allocation":{"enabled":1}
,"enabled":{"bridge":1}
,"result_ok":{"function":1}
}
;Search.control.loadWordPairs(pairs);
