var pairs =
{
"isis_set_sys_log_adj_changes":{"call":1,"(u_int32_t":1}
,"call":{"sets":1}
,"sets":{"state":1}
,"state":{"log":1,"(up":1,"true":1}
,"log":{"generation":1}
,"generation":{"is-is":1}
,"is-is":{"adjacency":1,"instance":1}
,"adjacency":{"changes":1}
,"changes":{"state":1}
,"(up":{"down)":1}
,"down)":{"syntax":1}
,"syntax":{"int":1}
,"int":{"isis_set_sys_log_adj_changes":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1,"instance":1}
,"u_int32_t":{"instance":1,"val)":1}
,"instance":{"u_int32_t":1,"is-is":1,"val":1}
,"val)":{"input":1}
,"input":{"parameter":1}
,"parameter":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1,"isis_api_set_success":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"val":{"state":1}
,"true":{"false":1}
,"false":{"output":1}
,"output":{"parameter":1}
,"none":{"return":1}
,"return":{"value":1}
,"isis_api_set_success":{"complete":1}
,"complete":{"isis_api_get_error":1}
,"isis_api_get_error":{"found":1}
}
;Search.control.loadWordPairs(pairs);
