var pairs =
{
"lmm":{"command":1,"(unicast":1,"observed":1,"unicast":1}
,"command":{"configure":1,"syntax":1,"mode":1}
,"configure":{"loss":1}
,"loss":{"measurement":1}
,"measurement":{"messaging":1}
,"messaging":{"(lmm)":1}
,"(lmm)":{"mep":1}
,"mep":{"command":1,"unicast":1,"configuration":1}
,"syntax":{"lmm":1}
,"(unicast":{"rmepid":1}
,"rmepid":{"rmepid":1,"multicast)":1,"remote":1,"duration":1}
,"multicast)":{"duration":1}
,"duration":{"<5-60>":1,"duration":1,"lmm":1,"interval":1}
,"<5-60>":{"(interval":1,"seconds":1}
,"(interval":{"parameters":1}
,"parameters":{"unicast":1}
,"unicast":{"specify":1,"frames":1,"rmepid":1}
,"specify":{"unicast":1,"multicast":1}
,"frames":{"sent":1,"multicast":1}
,"sent":{"rmepid":1,"duration":1}
,"remote":{"mep":1}
,"multicast":{"specify":1,"frames":1}
,"observed":{"range":1}
,"range":{"<5-60>":1}
,"seconds":{"interval":1,"command":1}
,"interval":{"transmission":1,"100":1}
,"transmission":{"interval":1}
,"100":{"milliseconds":1}
,"milliseconds":{"milliseconds":1,"second":1}
,"second":{"seconds":1}
,"mode":{"ethernet":1,"examples":1}
,"ethernet":{"cfm":1}
,"cfm":{"pbb-te":1}
,"pbb-te":{"mep":1}
,"configuration":{"mode":1}
,"examples":{"(config-cfm-pbb-te-mep)":1}
,"(config-cfm-pbb-te-mep)":{"lmm":1}
}
;Search.control.loadWordPairs(pairs);
