var pairs =
{
"show":{"ldp":1}
,"ldp":{"interface":1,"identifier":1}
,"interface":{"command":1,"label-switching":1,"show":1,"ifname":1,"interface":1,"ldp":1,"eth1":1,"type":1}
,"command":{"display":1,"syntax":1,"mode":1,"displaying":1}
,"display":{"list":1}
,"list":{"interfaces":1}
,"interfaces":{"current":1,"lsr":1}
,"current":{"lsr":1}
,"lsr":{"indicate":1,"show":1}
,"indicate":{"whether":1}
,"whether":{"given":1}
,"given":{"interface":1}
,"label-switching":{"command":1,"merge":1}
,"syntax":{"show":1}
,"ifname":{"parameter":1,"displays":1,"command":1}
,"parameter":{"ifname":1}
,"displays":{"name":1,"list":1}
,"name":{"interface":1}
,"mode":{"exec":1,"privileged":1,"examples":1,"downstream":1,"liberal":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"examples":{"following":1}
,"following":{"output":1,"sample":1}
,"output":{"displays":1,"show":1}
,"identifier":{"label-switching":1}
,"merge":{"capability":1,"capable":1}
,"capability":{"eth0":1,"merge":1}
,"eth0":{"10.10.0.11:0":1}
,"10.10.0.11:0":{"disabled":1,"enabled":1}
,"disabled":{"n\u002Fa":1}
,"n\u002Fa":{"10.10.0.11:0":1,"eth1":1,"following":1}
,"eth1":{"10.10.0.11:0":1,"show":1,"status":1}
,"enabled":{"merge":1,"primary":1}
,"capable":{"eth2":1,"vmnet1":1,"hello":1}
,"eth2":{"10.10.0.11:0":1}
,"vmnet1":{"10.10.0.11:0":1}
,"sample":{"output":1}
,"displaying":{"information":1}
,"information":{"specified":1}
,"specified":{"interface":1}
,"status":{"enabled":1}
,"primary":{"address":1}
,"address":{"192.168.3.4":1}
,"192.168.3.4":{"interface":1}
,"type":{"ethernet":1}
,"ethernet":{"label":1}
,"label":{"merge":1,"retention":1}
,"hello":{"interval":1}
,"interval":{"targeted":1,"hold":1,"keepalive":1}
,"targeted":{"hello":1,"hold":1}
,"hold":{"time":1}
,"time":{"targeted":1,"keepalive":1}
,"keepalive":{"interval":1,"timeout":1}
,"timeout":{"advertisement":1}
,"advertisement":{"mode":1}
,"downstream":{"demand":1}
,"demand":{"label":1}
,"retention":{"mode":1}
,"liberal":{"administrative":1}
,"administrative":{"groups":1}
,"groups":{"ipi1":1}
}
;Search.control.loadWordPairs(pairs);
