var pairs =
{
"spb_api_set_ipvpn":{"function":1,"(u_int8_t":1}
,"function":{"enables":1,"implements":1,"succeeds":1}
,"enables":{"disables":1}
,"disables":{"ipvpn":1}
,"ipvpn":{"spb":1,"enabled":1,"traffic":1,"enable":1,"disable":1,"pal_true":1,"pal_false":1,"output":1,"initialization":1}
,"spb":{"ipvpn":1,"network":1}
,"enabled":{"virtual":1}
,"virtual":{"route":1}
,"route":{"forwarder":1}
,"forwarder":{"(vrf)":1}
,"(vrf)":{"identified":1}
,"identified":{"i-sid":1}
,"i-sid":{"(service":1,"portion":1}
,"(service":{"instance":1}
,"instance":{"identifier)":1,"tag":1,"configuration":1}
,"identifier)":{"ipvpn":1}
,"traffic":{"within":1}
,"within":{"spb":1}
,"network":{"uses":1}
,"uses":{"i-sid":1}
,"portion":{"service":1}
,"service":{"instance":1}
,"tag":{"(i-tag)":1}
,"(i-tag)":{"without":1}
,"without":{"c-mac":1}
,"c-mac":{"header":1}
,"header":{"called":1}
,"called":{"short":1}
,"short":{"i-tag":1}
,"i-tag":{"function":1}
,"implements":{"ipvpn":1}
,"enable":{"ipvpn":1,"whether":1,"disable":1}
,"disable":{"commands":1,"ipvpn":1}
,"commands":{"syntax":1}
,"syntax":{"include":1}
,"include":{"spbd\u002Fisis-spb\u002Fspb_isis_api.h":1}
,"spbd\u002Fisis-spb\u002Fspb_isis_api.h":{"int":1}
,"int":{"spb_api_set_ipvpn":1}
,"(u_int8_t":{"enable)":1}
,"enable)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"enable":1,"none":1}
,"whether":{"enable":1}
,"pal_true":{"enable":1}
,"pal_false":{"disable":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"result_error":1}
,"result_error":{"backbone":1}
,"backbone":{"bridge":1}
,"bridge":{"null":1,"found":1}
,"null":{"spb_api_err_config_update":1,"port":1}
,"spb_api_err_config_update":{"backbone":1}
,"port":{"instance":1}
,"configuration":{"exists":1}
,"exists":{"spb_api_err_bridge_not_found":1}
,"spb_api_err_bridge_not_found":{"backbone":1}
,"found":{"spb_api_err_ipvpn_init_failed":1}
,"spb_api_err_ipvpn_init_failed":{"ipvpn":1}
,"initialization":{"fails":1}
,"fails":{"result_ok":1}
,"result_ok":{"function":1}
}
;Search.control.loadWordPairs(pairs);
