var pairs =
{
"ospf_graceful_restart_planned_set":{"function":1,"(struct":1}
,"function":{"allows":1,"called":1}
,"allows":{"configure":1}
,"configure":{"ospf":1}
,"ospf":{"planned":1,"hitless":1,"structure":1,"sso":1}
,"planned":{"(s\u002Fw)":1}
,"(s\u002Fw)":{"restarts":1}
,"restarts":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"restart":1}
,"restart":{"ospf":1}
,"hitless":{"(grace-period":1}
,"(grace-period":{"<1-1800>":1}
,"<1-1800>":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf_graceful_restart_planned_set":1}
,"(struct":{"ospf_master":1}
,"ospf_master":{"*om)":1}
,"*om)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"pointer":1,"none":1}
,"pointer":{"master":1}
,"master":{"ospf":1}
,"structure":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf_api_set_err_gr_not_supported":1}
,"ospf_api_set_err_gr_not_supported":{"ospf":1}
,"sso":{"enabled":1}
}
;Search.control.loadWordPairs(pairs);
