var pairs =
{
"trill_set_rbridge_dtree_priority":{"call":1,"(u_int32_t":1}
,"call":{"sets":1}
,"sets":{"distribution":1}
,"distribution":{"tree":1}
,"tree":{"root":1}
,"root":{"priority":1}
,"priority":{"rbridge":1}
,"rbridge":{"syntax":1,"dtree":1}
,"syntax":{"int":1}
,"int":{"trill_set_rbridge_dtree_priority":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"integer":1}
,"u_int32_t":{"instance":1,"val)":1}
,"instance":{"u_int32_t":1,"integer":1,"val":1,"trill_api_get_error":1,"found":1}
,"val)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"integer":{"contains":1}
,"contains":{"trill":1}
,"trill":{"identifier":1,"instance":1}
,"identifier":{"instance":1}
,"val":{"priority":1}
,"dtree":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"trill_api_set_success":1}
,"trill_api_set_success":{"valid":1}
,"valid":{"instance":1}
,"trill_api_get_error":{"valid":1}
}
;Search.control.loadWordPairs(pairs);
