var pairs =
{
"ethernet":{"cfm":1}
,"cfm":{"automatic":1,"given":1}
,"automatic":{"bridge":1,"configuration":1}
,"bridge":{"command":1,"give":1,"form":1,"(<1-32>":1,"specify":1,"<1-32>":1,"identifier":1}
,"command":{"automatically":1,"need":1,"disable":1,"syntax":1,"mode":1}
,"automatically":{"configure":1}
,"configure":{"cfm":1,"maintenance":1,"mode":1,"terminal":1}
,"given":{"bridge":1}
,"give":{"command":1}
,"need":{"configure":1}
,"maintenance":{"domain":1,"association":1,"end":1}
,"domain":{"(md)":1}
,"(md)":{"maintenance":1}
,"association":{"(ma)":1}
,"(ma)":{"maintenance":1}
,"end":{"points":1}
,"points":{"(meps)":1}
,"(meps)":{"vlans\u002Fi-sids":1}
,"vlans\u002Fi-sids":{"associated":1}
,"associated":{"bridge":1}
,"form":{"command":1}
,"disable":{"automatic":1}
,"configuration":{"command":1}
,"syntax":{"ethernet":1}
,"(<1-32>":{"backbone)":1}
,"backbone)":{"ethernet":1,"parameters":1}
,"parameters":{"bridge":1}
,"specify":{"bridge":1}
,"<1-32>":{"specify":1}
,"identifier":{"backbone":1}
,"backbone":{"backbone":1,"bridge":1}
,"mode":{"configure":1,"example":1}
,"example":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"ethernet":1}
}
;Search.control.loadWordPairs(pairs);
