var pairs =
{
"efm_oam_show_discovery":{"function":1,"(struct":1}
,"function":{"gets":1,"implements":1}
,"gets":{"discovery":1}
,"discovery":{"information":1,"interface":1}
,"information":{"interface":1}
,"interface":{"function":1,"ifname":1,"*ifp":1,"structure":1}
,"implements":{"show":1}
,"show":{"ethernet":1}
,"ethernet":{"oam":1}
,"oam":{"discovery":1}
,"ifname":{"command":1}
,"command":{"syntax":1}
,"syntax":{"void":1}
,"void":{"efm_oam_show_discovery":1}
,"(struct":{"interface":1}
,"*ifp":{"structure":1}
,"structure":{"cli":1,"output":1,"return":1}
,"cli":{"*cli)":1,"pointer":1,"structure":1}
,"*cli)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"cli":1}
,"ifp":{"pointer":1}
,"pointer":{"interface":1,"cli":1}
,"output":{"parameters":1}
,"return":{"values":1}
,"values":{"none":1}
}
;Search.control.loadWordPairs(pairs);
