var pairs =
{
"nsm_mpls_set_ftn_mask":{"function":1,"(struct":1}
,"function":{"sets":1,"succeeds":1,"fails":1}
,"sets":{"bitmap":1}
,"bitmap":{"indicates":1}
,"indicates":{"fields":1}
,"fields":{"(source":1}
,"(source":{"address":1}
,"address":{"range":1}
,"range":{"destination":1,"source":1,"ipv4":1}
,"destination":{"address":1,"port":1}
,"source":{"port":1}
,"port":{"range":1}
,"ipv4":{"protocol":1}
,"protocol":{"field":1}
,"field":{"dscp)":1}
,"dscp)":{"active":1}
,"active":{"ftn":1}
,"ftn":{"syntax":1,"table":1,"entry":1}
,"syntax":{"u_int32_t":1}
,"u_int32_t":{"nsm_mpls_set_ftn_mask":1,"ftn_ix":1,"ftn_mask)":1}
,"(struct":{"nsm_master":1}
,"nsm_master":{"*nm":1}
,"*nm":{"u_int32_t":1}
,"ftn_ix":{"u_int32_t":1,"index":1}
,"ftn_mask)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"nsm":1,"none":1}
,"nsm":{"master":1}
,"master":{"ftn_ix":1}
,"index":{"conceptual":1}
,"conceptual":{"row":1}
,"row":{"ftn":1}
,"table":{"ftn_mask":1}
,"ftn_mask":{"bit":1}
,"bit":{"map":1}
,"map":{"indicating":1}
,"indicating":{"fields":1}
,"entry":{"permitted":1}
,"permitted":{"value":1}
,"value":{"nsm_mpls_ftn_mask_destaddress":1}
,"nsm_mpls_ftn_mask_destaddress":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_api_set_success":1}
,"nsm_api_set_success":{"function":1}
,"succeeds":{"nsm_api_set_error":1}
,"nsm_api_set_error":{"function":1}
}
;Search.control.loadWordPairs(pairs);
