var pairs =
{
"validation":{"pe1":1}
,"pe1":{"pe1":1,"bfd":1}
,"bfd":{"session":1,"gtsm":1}
,"session":{"sess-idx":1,"detail":1,"state":1}
,"sess-idx":{"remote-disc":1}
,"remote-disc":{"lower-layer":1}
,"lower-layer":{"sess-type":1}
,"sess-type":{"sess-state":1}
,"sess-state":{"up-time":1}
,"up-time":{"remote-addr":1}
,"remote-addr":{"mpls-tp":1}
,"mpls-tp":{"single-hop":1,"version":1,"lsp":1}
,"single-hop":{"00:00:09":1,"00:00:26":1}
,"00:00:09":{"number":1}
,"number":{"sessions":1}
,"sessions":{"pe1":1,"pe2":1}
,"detail":{"======================================================session":1}
,"======================================================session":{"index":1}
,"index":{"lower":1}
,"lower":{"layer":1}
,"layer":{"mpls-tp":1}
,"version":{"session":1}
,"state":{"local":1}
,"local":{"discriminator":1}
,"discriminator":{"remote":1,"meg":1}
,"remote":{"discriminator":1}
,"meg":{"name":1}
,"name":{"meg-1":1,"me-1":1}
,"meg-1":{"name":1}
,"me-1":{"path":1}
,"path":{"type":1}
,"type":{"mpls-tp":1,"sess":1}
,"lsp":{"options":1}
,"options":{"diagnostics":1}
,"diagnostics":{"none":1}
,"none":{"timers":1}
,"timers":{"milliseconds":1}
,"milliseconds":{"min":1}
,"min":{"min":1,"multiplier":1}
,"multiplier":{"neg":1}
,"neg":{"neg":1,"detect":1}
,"detect":{"mult":1}
,"mult":{"storage":1}
,"storage":{"type":1}
,"sess":{"down":1,"discontinue":1}
,"down":{"time":1}
,"time":{"00:00:00":1}
,"00:00:00":{"sess":1,"bfd":1}
,"discontinue":{"time":1}
,"gtsm":{"disabled":1}
,"disabled":{"counters":1}
,"counters":{"values":1}
,"values":{"pkt":1}
,"pkt":{"0000000000000000":1}
,"0000000000000000":{"pkt":1,"count":1}
,"count":{"uptime":1}
,"uptime":{"00:00:42":1,"00:00:31":1}
,"00:00:42":{"protocol":1}
,"protocol":{"client":1}
,"client":{"info":1,"flags":1}
,"info":{"nsm->":1}
,"nsm->":{"client":1}
,"flags":{"----------------------------------------------------------number":1}
,"----------------------------------------------------------number":{"sessions":1}
,"pe2":{"pe2":1,"bfd":1}
,"00:00:26":{"number":1}
,"00:00:31":{"protocol":1}
}
;Search.control.loadWordPairs(pairs);
