var pairs =
{
"display_ptp_clock_foreign_master_dataset":{"function":1,"(struct":1}
,"function":{"gets":1}
,"gets":{"attributes":1}
,"attributes":{"foreign":1}
,"foreign":{"master":1,"masters":1}
,"master":{"clocks":1,"recognized":1}
,"clocks":{"ordinary":1,"boundary":1,"sending":1}
,"ordinary":{"clocks":1}
,"boundary":{"clocks":1}
,"sending":{"announce":1}
,"announce":{"messages":1}
,"messages":{"clock":1}
,"clock":{"current":1,"syntax":1,"pointer":1,"port":1}
,"current":{"master":1}
,"recognized":{"clock":1}
,"syntax":{"include":1}
,"include":{"ptpd\u002Fptp_cli.h":1}
,"ptpd\u002Fptp_cli.h":{"void":1}
,"void":{"display_ptp_clock_foreign_master_dataset":1}
,"(struct":{"cli*cli":1}
,"cli*cli":{"struct":1}
,"struct":{"ptp_port_clock":1}
,"ptp_port_clock":{"*clock)":1}
,"*clock)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"clock":1,"cli":1}
,"pointer":{"clock":1}
,"port":{"output":1}
,"output":{"parameters":1}
,"cli":{"attributes":1}
,"masters":{"return":1}
,"return":{"values":1}
,"values":{"none":1}
}
;Search.control.loadWordPairs(pairs);
