var pairs =
{
"protocol":{"data":1,"open":1}
,"data":{"unit":1,"transmitted":1}
,"unit":{"(pdu)":1,"data":1,"(bpdu)":1}
,"(pdu)":{"unit":1}
,"transmitted":{"composite":1}
,"composite":{"protocol":1}
,"open":{"systems":1}
,"systems":{"interconnection":1}
,"interconnection":{"(osi)":1}
,"(osi)":{"reference":1}
,"reference":{"model":1}
,"model":{"actual":1}
,"actual":{"name":1}
,"name":{"used":1}
,"used":{"pdu":1}
,"pdu":{"depends":1}
,"depends":{"layer":1}
,"layer":{"layer":1,"(l4)":1,"(l3)":1,"(l2)":1,"(l1)":1}
,"(l4)":{"segment":1}
,"segment":{"layer":1}
,"(l3)":{"packet":1}
,"packet":{"layer":1}
,"(l2)":{"frame":1}
,"frame":{"layer":1}
,"(l1)":{"stream":1}
,"stream":{"symbol":1,"bit":1,"bridge":1}
,"symbol":{"stream":1}
,"bit":{"stream":1}
,"bridge":{"protocol":1}
,"(bpdu)":{"sometimes":1}
,"sometimes":{"called":1}
,"called":{"datagram":1}
}
;Search.control.loadWordPairs(pairs);
