var pairs =
{
"pim6_api_static_rp_unset":{"function":1,"(u_int32_t":1}
,"function":{"removes":1,"executes":1}
,"removes":{"static":1}
,"static":{"configuration":1}
,"configuration":{"syntax":1}
,"syntax":{"int":1}
,"int":{"pim6_api_static_rp_unset":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"vrf_id_t":1,"virtual":1}
,"vrf_id_t":{"vrf_id":1}
,"vrf_id":{"struct":1,"vpn":1}
,"struct":{"pal_in6_addr":1}
,"pal_in6_addr":{"*rp_addr)":1}
,"*rp_addr)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"rp_addr":1}
,"virtual":{"router":1}
,"router":{"vrf_id":1}
,"vpn":{"routing\u002Fforwarding":1}
,"routing\u002Fforwarding":{"instance":1}
,"instance":{"output":1}
,"output":{"parameters":1}
,"rp_addr":{"address":1}
,"address":{"return":1}
,"return":{"value":1}
,"value":{"pim_api_set_err_wrong_vr":1}
,"pim_api_set_err_wrong_vr":{"pim_api_set_err_wrong_vrf":1}
,"pim_api_set_err_wrong_vrf":{"pim":1}
,"pim":{"vrf":1}
,"vrf":{"interface":1}
,"interface":{"found":1}
,"found":{"pim_api_set_success":1}
,"pim_api_set_success":{"function":1}
,"executes":{"properly":1}
}
;Search.control.loadWordPairs(pairs);
