var pairs =
{
"backbone":{"edge":1,"bridging":1,"mac":1,"vlan":1}
,"edge":{"bridge":1}
,"bridge":{"(beb)":1}
,"(beb)":{"device":1}
,"device":{"encapsulates":1}
,"encapsulates":{"customer":1}
,"customer":{"frames":1,"space":1,"mac":1}
,"frames":{"transmission":1}
,"transmission":{"across":1}
,"across":{"provider":1}
,"provider":{"backbone":1,"space":1}
,"bridging":{"(pbb)":1,"provider":1,"customer":1}
,"(pbb)":{"network":1}
,"network":{"two":1}
,"two":{"types":1}
,"types":{"b-beb":1}
,"b-beb":{"type":1}
,"type":{"beb)":1}
,"beb)":{"contains":1}
,"contains":{"b-component":1,"i-component":1}
,"b-component":{"bridging":1}
,"space":{"based":1}
,"based":{"backbone":1,"customer":1}
,"mac":{"address":1}
,"address":{"(b-mac)":1,"(c-mac)":1}
,"(b-mac)":{"backbone":1}
,"vlan":{"(b-vlan)":1,"(s-vlan)":1}
,"(b-vlan)":{"information":1}
,"information":{"i-beb":1}
,"i-beb":{"type":1}
,"i-component":{"bridging":1}
,"(c-mac)":{"service":1}
,"service":{"vlan":1}
,"(s-vlan)":{"information":1}
}
;Search.control.loadWordPairs(pairs);
