var pairs =
{
"pal_log_stop":{"function":1,"(struct":1}
,"function":{"stops":1}
,"stops":{"logging":1}
,"logging":{"finishes":1,"output":1}
,"finishes":{"pending":1}
,"pending":{"transactions":1}
,"transactions":{"shutting":1}
,"shutting":{"down":1}
,"down":{"logging":1}
,"output":{"manager":1,"devices":1,"parameters":1}
,"manager":{"breaking":1,"called":1}
,"breaking":{"previously":1}
,"previously":{"created":1}
,"created":{"connections":1}
,"connections":{"output":1}
,"devices":{"frees":1}
,"frees":{"resources":1}
,"resources":{"allocated":1}
,"allocated":{"logging":1}
,"called":{"during":1}
,"during":{"shutdown":1}
,"shutdown":{"process":1}
,"process":{"api":1}
,"api":{"call":1}
,"call":{"result_t":1}
,"result_t":{"pal_log_stop":1}
,"(struct":{"lib_globals":1}
,"lib_globals":{"*lib_node)":1}
,"*lib_node)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"log":1,"none":1}
,"log":{"log":1,"file":1}
,"file":{"output":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"platform":1}
,"platform":{"dependent":1}
}
;Search.control.loadWordPairs(pairs);
