var pairs =
{
"virtual":{"circuit":1}
,"circuit":{"messages":1,"(vc)":1}
,"messages":{"virtual":1,"defined":1,"ilm":1,"ftn":1}
,"defined":{"sections":1}
,"sections":{"follow":1}
,"follow":{"ftn":1}
,"ftn":{"add":1,"entry":1,"delete":1,"entries":1}
,"add":{"request":1,"reply":1}
,"request":{"message":1,"protocols":1}
,"message":{"adds":1,"contains":1,"protocol":1,"nsm":1,"deletes":1,"ftn":1,"protocols":1,"message":1,"contain":1,"corresponding":1,"ilm":1}
,"adds":{"ftn":1}
,"entry":{"mpls-based":1}
,"mpls-based":{"layer-2":1}
,"layer-2":{"virtual":1,"vcs":1}
,"(vc)":{"every":1}
,"every":{"message":1}
,"contains":{"message":1,"incoming":1}
,"protocol":{"protocol-specific":1,"lookup":1}
,"protocol-specific":{"lookup":1}
,"lookup":{"key":1}
,"key":{"nsm":1,"ilm":1,"used":1}
,"nsm":{"returns":1,"install":1,"remove":1,"sends":1}
,"returns":{"parameters":1}
,"parameters":{"elements":1,"corresponding":1}
,"elements":{"corresponding":1}
,"corresponding":{"ftn":1,"ilm":1}
,"reply":{"notification":1,"nsm":1}
,"notification":{"messages":1}
,"ilm":{"add":1,"entries":1,"delete":1}
,"protocols":{"send":1,"serves":1,"serve":1}
,"send":{"message":1}
,"install":{"ilm":1}
,"entries":{"mpls":1,"every":1,"contains":1}
,"mpls":{"layer-2":1}
,"vcs":{"every":1}
,"delete":{"request":1}
,"remove":{"ftn":1}
,"deletes":{"ilm":1}
,"incoming":{"label":1}
,"label":{"interface":1}
,"interface":{"along":1}
,"along":{"message":1}
,"used":{"corresponding":1}
,"sends":{"message":1}
,"serves":{"confirmation":1}
,"confirmation":{"corresponding":1}
,"contain":{"message":1}
,"serve":{"confirmation":1}
}
;Search.control.loadWordPairs(pairs);
