var pairs =
{
"rsvp_snmp_set_tn_xc_pointer":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"always":1}
,"sets":{"pointer":1}
,"pointer":{"row":1}
,"row":{"mplsxctable":1}
,"mplsxctable":{"tunnel":1}
,"tunnel":{"object":1,"index":1,"output":1}
,"object":{"supported":1}
,"supported":{"function":1}
,"always":{"returns":1,"rsvp_api_set_error":1}
,"returns":{"rsvp_api_set_error":1}
,"rsvp_api_set_error":{"syntax":1}
,"syntax":{"u_int32_t":1}
,"u_int32_t":{"rsvp_snmp_set_tn_xc_pointer":1,"*inst_ix":1}
,"(u_int32_t":{"*tn_ix":1}
,"*tn_ix":{"u_int32_t":1}
,"*inst_ix":{"struct":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"*ing_id":1,"*eg_id":1}
,"*ing_id":{"struct":1}
,"*eg_id":{"oid":1}
,"oid":{"*xc_ptr)":1}
,"*xc_ptr)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"tn_ix":1,"none":1}
,"tn_ix":{"tunnel":1}
,"index":{"inst_ix":1,"ing_id":1}
,"inst_ix":{"instance":1}
,"instance":{"index":1}
,"ing_id":{"ingress":1}
,"ingress":{"lsr":1}
,"lsr":{"identifier":1}
,"identifier":{"eg_id":1,"xc_ptr":1}
,"eg_id":{"egress":1}
,"egress":{"lsr":1}
,"xc_ptr":{"pointer":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"always":1}
}
;Search.control.loadWordPairs(pairs);
