var pairs =
{
"using":{"priority":1}
,"priority":{"procedure":1,"zebos3":1,"zebos2":1}
,"procedure":{"below":1}
,"below":{"zebos1":1}
,"zebos1":{"zebos3":1,"having":1}
,"zebos3":{"figure":1,"having":1,"quality":1,"(with":1}
,"figure":{"1-1":1}
,"1-1":{"configured":1}
,"configured":{"output":1,"accept":1}
,"output":{"sources":1}
,"sources":{"zebos1":1}
,"having":{"priority":1}
,"zebos2":{"configured":1,"chooses":1}
,"accept":{"frequency":1}
,"frequency":{"either":1,"source":1}
,"either":{"zebos1":1}
,"quality":{"level":1}
,"level":{"used":1}
,"used":{"clock":1}
,"clock":{"selection":1}
,"selection":{"criteria":1}
,"criteria":{"(an":1}
,"(an":{"explicit":1}
,"explicit":{"setting)":1}
,"setting)":{"zebos2":1}
,"chooses":{"zebos3":1}
,"(with":{"higher":1}
,"higher":{"priority)":1}
,"priority)":{"frequency":1}
}
;Search.control.loadWordPairs(pairs);
