var pairs =
{
"aaa":{"group":1}
,"group":{"server":1,"enter":1,"configuration":1,"command":1,"tacacs":1,"ldap":1,"word":1,"name":1}
,"server":{"command":1,"group":1,"(radius":1,"ldap":1}
,"command":{"create":1,"remove":1,"syntax":1,"mode":1}
,"create":{"server":1}
,"enter":{"server":1}
,"configuration":{"mode":1}
,"mode":{"form":1,"configure":1,"examples":1}
,"form":{"command":1}
,"remove":{"server":1}
,"syntax":{"aaa":1}
,"(radius":{"tacacs":1}
,"tacacs":{"ldap)":1,"tacacs":1,"server":1}
,"ldap)":{"word":1}
,"word":{"aaa":1,"parameters":1,"server":1}
,"parameters":{"radius":1}
,"radius":{"radius":1,"server":1}
,"ldap":{"ldap":1,"server":1,"ldapgroup6":1}
,"name":{"maximum":1}
,"maximum":{"127":1}
,"127":{"characters":1}
,"characters":{"command":1}
,"configure":{"mode":1,"terminal":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"aaa":1}
,"ldapgroup6":{"(config-ldap)":1}
}
;Search.control.loadWordPairs(pairs);
