var pairs =
{
"ethernet":{"cfm":1,"service":1}
,"cfm":{"pbb":1}
,"pbb":{"mep":1,"form":1}
,"mep":{"command":1,"pbb":1,"create":1,"remove":1,"(down":1,"mepid":1,"domain-name":1,"secondary":1,"isid":1,"cbp":1,"down":1,"mpid":1}
,"command":{"create":1,"delete":1,"syntax":1,"mode":1}
,"create":{"mep":1,"configure":1}
,"form":{"command":1}
,"delete":{"mep":1}
,"configure":{"link-level":1}
,"link-level":{"mep":1}
,"remove":{"enter":1}
,"enter":{"vlan":1,"local":1}
,"vlan":{"command":1,"identify":1,"vlan_id":1,"local-vid":1,"backbone":1}
,"syntax":{"ethernet":1}
,"(down":{"up)":1}
,"up)":{"mpid":1}
,"mpid":{"mepid":1,"identity":1,"domain-name":1}
,"mepid":{"domain-name":1,"source":1}
,"domain-name":{"name":1,"abc":1,"isid":1}
,"name":{"(((vlan":1,"maintenance":1}
,"(((vlan":{"vlan_id":1}
,"vlan_id":{"(local-vid":1,"vlan":1}
,"(local-vid":{"vid":1}
,"vid":{"|))":1,"mep":1,"vid":1,"enter":1}
,"|))":{"isid":1}
,"isid":{"isid)":1,"isid":1,"(bridge":1,"identify":1,"specify":1,"mep":1,"bridge":1}
,"isid)":{"(cbp-service-domain":1}
,"(cbp-service-domain":{"isid":1}
,"(bridge":{"<1-32>":1}
,"<1-32>":{"backbone)":1,"bridge":1}
,"backbone)":{"ethernet":1,"parameters":1}
,"parameters":{"down":1}
,"down":{"mep\u2019s":1,"mpid":1}
,"mep\u2019s":{"direction":1}
,"direction":{"flow":1}
,"flow":{"down":1,"mpid":1}
,"identity":{"source":1}
,"source":{"mep":1}
,"maintenance":{"domain":1}
,"domain":{"domain_name":1,"vlan":1,"isid":1}
,"domain_name":{"name":1}
,"identify":{"vlan":1,"associated":1,"bridge":1}
,"local-vid":{"local":1}
,"local":{"vid":1}
,"secondary":{"vid":1}
,"associated":{"service":1}
,"service":{"instance":1,"domain":1}
,"instance":{"isid":1,"<1-16777214>":1}
,"specify":{"ethernet":1}
,"<1-16777214>":{"cbp-service-domain":1,"bridge":1}
,"cbp-service-domain":{"isid":1}
,"cbp":{"service":1}
,"bridge":{"identify":1,"<1-32>":1,"backbone":1,"(config-if)":1}
,"backbone":{"identify":1,"command":1,"(config-if)":1}
,"mode":{"interface":1,"examples":1}
,"interface":{"mode":1,"eth1":1}
,"examples":{"(config)":1}
,"(config)":{"interface":1}
,"eth1":{"(config-if)":1}
,"(config-if)":{"ethernet":1}
,"abc":{"bridge":1,"vlan":1}
}
;Search.control.loadWordPairs(pairs);
