var pairs =
{
"disable-ldp":{"command":1,"alone":1,"(ipv4":1,"following":1,"ipv4":1,"ipv6":1}
,"command":{"disable":1,"disables":1,"syntax":1,"mode":1}
,"disable":{"isis":1}
,"isis":{"ipv4":1,"ipv6":1}
,"ipv4":{"isis":1,"interface":1,"disables":1,"following":1}
,"ipv6":{"specified":1,"parameters":1,"disables":1,"interface":1}
,"specified":{"interface":1}
,"interface":{"command":1,"clears":1,"disable-ldp":1,"enable-ldp":1,"(see":1,"ipv6":1,"mode":1,"eth0":1}
,"disables":{"transmission":1,"ipv4":1,"ipv6":1,"isis":1}
,"transmission":{"hello":1}
,"hello":{"packets":1}
,"packets":{"current":1}
,"current":{"interface":1}
,"clears":{"created":1}
,"created":{"sessions":1}
,"sessions":{"adjacencies":1}
,"adjacencies":{"interface":1}
,"alone":{"disable":1}
,"enable-ldp":{"enable":1,"information)":1}
,"enable":{"ldp":1}
,"ldp":{"interface":1}
,"(see":{"enable-ldp":1}
,"information)":{"command":1}
,"syntax":{"disable-ldp":1}
,"(ipv4":{"disable-ldp":1,"ipv6":1}
,"parameters":{"ipv4":1}
,"mode":{"interface":1,"examples":1}
,"examples":{"following":1}
,"following":{"example":1}
,"example":{"disables":1}
,"eth0":{"configure":1,"(config-if)":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"(config-if)":{"disable-ldp":1}
}
;Search.control.loadWordPairs(pairs);
