var pairs =
{
"pim-ecmp":{"redirect":1,"feature":1}
,"redirect":{"configuration":1,"(rfc":1,"supported":1}
,"configuration":{"protocol":1}
,"protocol":{"independent":1}
,"independent":{"multicast":1}
,"multicast":{"(pim)":1}
,"(pim)":{"router":1}
,"router":{"uses":1,"order":1}
,"uses":{"reverse":1}
,"reverse":{"path":1}
,"path":{"forwarding":1,"algorithms":1,"preferences":1,"selection":1}
,"forwarding":{"(rpf)":1,"state":1}
,"(rpf)":{"procedure":1}
,"procedure":{"select":1,"ecmps":1}
,"select":{"upstream":1,"path":1}
,"upstream":{"interface":1}
,"interface":{"router":1,"identifier":1}
,"order":{"build":1}
,"build":{"forwarding":1}
,"state":{"equal-cost":1}
,"equal-cost":{"multipaths":1}
,"multipaths":{"(ecmps)":1}
,"(ecmps)":{"existing":1}
,"existing":{"implementations":1}
,"implementations":{"often":1}
,"often":{"hash":1}
,"hash":{"algorithms":1}
,"algorithms":{"select":1,"allow":1}
,"allow":{"spread":1}
,"spread":{"traffic":1}
,"traffic":{"among":1}
,"among":{"ecmps":1}
,"ecmps":{"according":1,"allows":1}
,"according":{"administrative":1}
,"administrative":{"metrics":1}
,"metrics":{"usually":1,"data":1}
,"usually":{"leads":1}
,"leads":{"inefficient":1}
,"inefficient":{"ineffective":1}
,"ineffective":{"network":1}
,"network":{"resources":1}
,"resources":{"pim":1}
,"pim":{"ecmp":1,"hello":1,"pim-dm":1}
,"ecmp":{"redirect":1,"selection":1,"path":1}
,"(rfc":{"6754)":1}
,"6754)":{"provides":1}
,"provides":{"mechanism":1}
,"mechanism":{"improve":1}
,"improve":{"rpf":1}
,"rpf":{"procedure":1}
,"allows":{"ecmp":1}
,"selection":{"based":1,"pim":1}
,"based":{"administratively":1}
,"administratively":{"selected":1}
,"selected":{"metrics":1}
,"data":{"transmission":1}
,"transmission":{"delays":1}
,"delays":{"path":1}
,"preferences":{"routing":1}
,"routing":{"metric":1}
,"metric":{"interface":1}
,"identifier":{"option":1}
,"option":{"used":1}
,"used":{"pim":1}
,"hello":{"messages":1}
,"messages":{"tiebreaker":1}
,"tiebreaker":{"during":1}
,"during":{"ecmp":1}
,"supported":{"bidirectional":1,"zebic":1}
,"bidirectional":{"pim":1}
,"pim-dm":{"pim-smdm":1}
,"pim-smdm":{"pim-ecmp":1}
,"feature":{"supported":1}
}
;Search.control.loadWordPairs(pairs);
