var pairs =
{
"valid":{"label":1}
,"label":{"ranges":1,"forwarder":1,"value":1,"stack":1,"beneath":1,"pushed":1}
,"ranges":{"scheme":1,"detailed":1}
,"scheme":{"labels":1}
,"labels":{"several":1,"label":1}
,"several":{"labels":1}
,"detailed":{"explanation":1}
,"explanation":{"rfc":1}
,"rfc":{"3032":1}
,"3032":{"section":1}
,"section":{"2.1":1}
,"2.1":{"range":1}
,"range":{"0-3":1,"4-15":1}
,"0-3":{"following":1}
,"following":{"uses":1}
,"uses":{"ipv4":1,"next":1}
,"ipv4":{"explicit":1,"header":1}
,"explicit":{"null":1}
,"null":{"label":1}
,"forwarder":{"receives":1,"uses":1}
,"receives":{"packet":1}
,"packet":{"label":1,"ipv4":1,"based":1}
,"value":{"bottom":1,"bases":1,"top":1}
,"bottom":{"label":1}
,"stack":{"stack":1,"pops":1,"forwarder":1,"router":1,"further":1,"forwards":1,"lsr":1,"range":1}
,"pops":{"label":1,"stack":1}
,"bases":{"forwarding":1}
,"forwarding":{"packet":1,"required":1}
,"header":{"router":1,"implicit":1}
,"router":{"alert":1}
,"alert":{"label":1}
,"top":{"label":1,"stack":1}
,"next":{"label":1}
,"beneath":{"stack":1}
,"pushed":{"top":1}
,"further":{"forwarding":1}
,"required":{"ipv6":1}
,"ipv6":{"explicit":1,"header":1}
,"forwards":{"packet":1}
,"based":{"ipv6":1}
,"implicit":{"null":1}
,"lsr":{"pops":1}
,"4-15":{"future":1}
}
;Search.control.loadWordPairs(pairs);
