var pairs =
{
"interactions":{"zebos-xp":1}
,"zebos-xp":{"components":1}
,"components":{"integrated":1}
,"integrated":{"management":1}
,"management":{"interface":1}
,"interface":{"shell":1}
,"shell":{"(imish)":1}
,"(imish)":{"interacts":1}
,"interacts":{"directly":1}
,"directly":{"imi":1}
,"imi":{"module":1,"nsm":1}
,"module":{"provides":1,"virtual":1}
,"provides":{"service":1}
,"service":{"passes":1,"network":1}
,"passes":{"request":1}
,"request":{"service":1}
,"network":{"services":1}
,"services":{"manager":1}
,"manager":{"(nsm)":1}
,"(nsm)":{"imish":1}
,"imish":{"offloads":1,"imi":1,"vty":1,"instance":1,"connection":1}
,"offloads":{"processing":1}
,"processing":{"nsm":1}
,"nsm":{"module":1,"basic":1,"vty":1}
,"virtual":{"teletype":1,"router":1}
,"teletype":{"terminal":1}
,"terminal":{"(vty)":1}
,"(vty)":{"requires":1}
,"requires":{"direct":1}
,"direct":{"interaction":1}
,"interaction":{"nsm":1}
,"basic":{"virtual":1}
,"router":{"architecture":1}
,"architecture":{"including":1}
,"including":{"imish":1}
,"vty":{"throughout":1,"library":1}
,"throughout":{"system":1}
,"system":{"virtual-router":1}
,"virtual-router":{"(vr-id)":1}
,"(vr-id)":{"tracked":1}
,"tracked":{"per-user":1}
,"per-user":{"basis":1}
,"basis":{"permits":1}
,"permits":{"virtualization":1}
,"virtualization":{"shielded":1}
,"shielded":{"user":1}
,"user":{"vr-id":1,"connects":1}
,"vr-id":{"determined":1,"during":1,"simply":1,"whenever":1}
,"determined":{"during":1}
,"during":{"login":1,"session":1}
,"login":{"(based":1}
,"(based":{"address":1}
,"address":{"user":1}
,"connects":{"to)":1}
,"to)":{"maintained":1}
,"maintained":{"vty":1}
,"library":{"imish":1}
,"instance":{"keeps":1}
,"keeps":{"vr-id":1}
,"session":{"passed":1}
,"passed":{"header":1,"daemons":1}
,"header":{"messages":1,"provided":1}
,"messages":{"line":1,"field":1,"header":1,"passed":1}
,"line":{"messages":1}
,"field":{"used":1}
,"used":{"show":1}
,"show":{"messages":1}
,"provided":{"vr-id":1}
,"simply":{"encoded":1}
,"encoded":{"decoded":1}
,"decoded":{"beginning":1}
,"beginning":{"message":1}
,"message":{"addition":1}
,"addition":{"imish":1}
,"connection":{"necessary":1}
,"necessary":{"maintain":1}
,"maintain":{"vr-id":1}
,"whenever":{"messages":1}
,"daemons":{"configuration":1}
,"configuration":{"get\u002Fset":1}
,"get\u002Fset":{"purposes":1}
}
;Search.control.loadWordPairs(pairs);
