var pairs =
{
"rsvp_snmp_get_next_hop_ip_pref_len":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"appropriate":1}
,"appropriate":{"prefix":1}
,"prefix":{"length":1}
,"length":{"next":1,"output":1,"return":1}
,"next":{"hop":1,"explicit":1,"group":1}
,"hop":{"syntax":1,"ix_len":1,"ret":1,"found":1}
,"syntax":{"u_int32_t":1}
,"u_int32_t":{"rsvp_snmp_get_next_hop_ip_pref_len":1,"*path_ix":1,"*hop_ix":1,"ix_len":1,"*ret)":1}
,"(u_int32_t":{"*ero_ix":1}
,"*ero_ix":{"u_int32_t":1}
,"*path_ix":{"u_int32_t":1}
,"*hop_ix":{"u_int32_t":1}
,"ix_len":{"u_int32_t":1,"index":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ero_ix":1}
,"ero_ix":{"primary":1}
,"primary":{"index":1}
,"index":{"identifying":1,"length":1,"next":1}
,"identifying":{"explicit":1,"group":1,"particular":1,"next":1}
,"explicit":{"route":1}
,"route":{"object":1}
,"object":{"path_ix":1}
,"path_ix":{"secondary":1}
,"secondary":{"index":1}
,"group":{"hops":1}
,"hops":{"configured":1}
,"configured":{"path":1}
,"path":{"hop_ix":1}
,"hop_ix":{"secondary":1}
,"particular":{"hop":1}
,"output":{"parameters":1}
,"ret":{"prefix":1}
,"return":{"value":1}
,"value":{"rsvp_api_get_success":1}
,"rsvp_api_get_success":{"function":1}
,"function":{"succeeds":1}
,"succeeds":{"rsvp_api_get_error":1}
,"rsvp_api_get_error":{"tunnel":1}
,"tunnel":{"hop":1}
}
;Search.control.loadWordPairs(pairs);
