var pairs =
{
"show":{"bgp":1}
,"bgp":{"filter-list":1,"(ipv4":1,"(ipv6)":1,"ipv4":1}
,"filter-list":{"command":1,"word":1,"mylist":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"routes":1}
,"routes":{"match":1,"ipv6":1,"unicast":1}
,"match":{"regular":1}
,"regular":{"expression":1}
,"expression":{"filter":1}
,"filter":{"list":1}
,"list":{"command":1,"ipv4":1}
,"syntax":{"show":1}
,"word":{"show":1,"parameters":1,"regular-expression":1}
,"(ipv4":{"ipv6)":1}
,"ipv6)":{"(unicast":1}
,"(unicast":{"multicast)":1}
,"multicast)":{"filter-list":1}
,"(ipv6)":{"filter-list":1}
,"ipv4":{"(unicast":1,"ipv4":1,"routes":1}
,"parameters":{"word":1}
,"regular-expression":{"filter":1}
,"ipv6":{"ipv6":1,"routes":1}
,"unicast":{"unicast":1,"prefixes":1}
,"prefixes":{"multicast":1,"command":1}
,"multicast":{"multicast":1,"prefixes":1}
,"mode":{"privileged":1,"exec":1,"example":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"example":{"show":1}
}
;Search.control.loadWordPairs(pairs);
