var pairs =
{
"multi-momed":{"redundancy":1}
,"redundancy":{"logic":1}
,"logic":{"diagram":1}
,"diagram":{"next":1}
,"next":{"page":1}
,"page":{"depicts":1}
,"depicts":{"two":1}
,"two":{"multi-homed":1,"devices":1}
,"multi-homed":{"devices":1}
,"devices":{"connected":1,"access":1,"executing":1}
,"connected":{"two":1}
,"access":{"circuits":1}
,"circuits":{"(ac)":1}
,"(ac)":{"scenario":1}
,"scenario":{"ce1":1}
,"ce1":{"dual-homed":1}
,"dual-homed":{"pe1":1,"pe3":1}
,"pe1":{"pe2":1,"pe3":1,"pe4":1}
,"pe2":{"ce2":1,"pe3":1,"pe4":1}
,"ce2":{"dual-homed":1}
,"pe3":{"consequence":1,"pw2":1,"pw4":1}
,"consequence":{"multiple":1}
,"multiple":{"pseudowires":1}
,"pseudowires":{"need":1}
,"need":{"signaled":1}
,"signaled":{"pw1":1}
,"pw1":{"pe1":1}
,"pw2":{"pe1":1}
,"pe4":{"pw4":1,"simultaneously":1}
,"pw4":{"pe2":1}
,"simultaneously":{"node":1}
,"node":{"chosen":1,"acts":1,"standby":1,"solution":1,"runtime-mode":1}
,"chosen":{"active":1}
,"active":{"node":1,"standby":1}
,"acts":{"standby":1}
,"standby":{"protocol":1,"node":1,"status":1}
,"protocol":{"required":1}
,"required":{"communicate":1}
,"communicate":{"pes":1}
,"pes":{"designate":1}
,"designate":{"active":1}
,"solution":{"zebos-xp":1}
,"zebos-xp":{"ldp":1}
,"ldp":{"provides":1}
,"provides":{"command":1}
,"command":{"simulates":1,"results":1}
,"simulates":{"switchover":1}
,"switchover":{"devices":1}
,"executing":{"command":1}
,"results":{"node":1}
,"runtime-mode":{"changes":1}
,"changes":{"active":1}
}
;Search.control.loadWordPairs(pairs);
