var pairs =
{
"bridge":{"configure":1,"protocol":1,"vlan":1,"name":1,"(config-vlan)":1,"group":1,"enter":1}
,"configure":{"terminal":1,"mode":1,"bridge":1,"eth1":1,"eth2":1,"mep":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"vlan":1,"interface":1,"cfm":1}
,"mode":{"(config)":1,"(config-vlan)":1,"(config-if)":1,"trunk":1,"create":1,"configure":1}
,"(config)":{"bridge":1,"vlan":1,"interface":1,"ethernet":1}
,"protocol":{"ieee":1}
,"ieee":{"vlan-bridge":1}
,"vlan-bridge":{"configure":1}
,"vlan":{"aware":1,"database":1,"configure":1,"bridge":1,"allow":1,"mip-creation":1,"becomes":1,"enable":1,"local-vid":1,"(config-if-eth-cfm-mep)":1}
,"aware":{"(config)":1}
,"database":{"enter":1}
,"(config-vlan)":{"vlan":1,"exit":1}
,"name":{"ipi5":1,"ipi10":1,"customer":1}
,"ipi5":{"create":1}
,"create":{"vlan":1,"domain":1}
,"ipi10":{"create":1}
,"exit":{"exit":1,"vlan":1,"interface":1,"cfm":1}
,"interface":{"eth1":1,"mode":1,"trunk":1,"eth2":1}
,"eth1":{"enter":1,"layer":1,"bridge":1,"(config-if)":1}
,"(config-if)":{"switchport":1,"bridge-group":1,"exit":1,"ethernet":1}
,"switchport":{"configure":1,"mode":1,"trunk":1}
,"layer":{"port":1}
,"port":{"(config-if)":1}
,"bridge-group":{"configure":1}
,"group":{"(config-if)":1}
,"trunk":{"interface":1,"(config-if)":1,"allowed":1}
,"allowed":{"vlan":1}
,"allow":{"vlans":1}
,"vlans":{"interface":1}
,"eth2":{"enter":1,"layer":1,"bridge":1,"(config-if)":1}
,"ethernet":{"cfm":1}
,"cfm":{"domain-name":1,"mode":1,"mep":1}
,"domain-name":{"type":1}
,"type":{"character-string":1}
,"character-string":{"name":1}
,"customer":{"level":1,"vlan":1}
,"level":{"mip-creation":1}
,"mip-creation":{"default":1}
,"default":{"bridge":1,"create":1}
,"domain":{"(config-ether-cfm)":1,"customer":1}
,"(config-ether-cfm)":{"service":1,"mep":1,"exit":1}
,"service":{"ma-type":1}
,"ma-type":{"integer":1}
,"integer":{"ma-name":1}
,"ma-name":{"vlan":1}
,"becomes":{"part":1}
,"part":{"ring":1}
,"ring":{"(config-ether-cfm)":1}
,"mep":{"crosscheck":1,"neighbor":1,"down":1,"mode":1,"405":1,"domain":1,"300":1}
,"crosscheck":{"mpid":1}
,"mpid":{"305":1,"405":1,"300":1}
,"305":{"vlan":1,"(config-ether-cfm)":1}
,"enable":{"crosschecking":1,"start":1}
,"crosschecking":{"mep":1}
,"neighbor":{"mpid":1}
,"405":{"vlan":1,"(config-ether-cfm)":1,"active":1,"down":1}
,"down":{"mpid":1,"mep":1}
,"active":{"true":1}
,"true":{"domain":1}
,"local-vid":{"bridge":1}
,"(config-if-eth-cfm-mep)":{"multicast":1,"exit":1}
,"multicast":{"state":1,"mepid":1}
,"state":{"enable":1}
,"start":{"multicast":1}
,"mepid":{"405":1,"300":1}
,"300":{"active":1,"down":1,"vlan":1}
}
;Search.control.loadWordPairs(pairs);
