var pairs =
{
"mpls-tp":{"tunnels":1,"framework":1}
,"tunnels":{"types":1,"unidirectional":1,"based":1}
,"types":{"tunnel":1,"tunnels":1}
,"tunnel":{"top":1,"may":1,"co-routed":1,"associated":1}
,"top":{"level":1}
,"level":{"container":1}
,"container":{"mpls":1}
,"mpls":{"transport":1}
,"transport":{"paths":1,"operating":1}
,"paths":{"(referred":1}
,"(referred":{"lsps)":1}
,"lsps)":{"source":1}
,"source":{"destination":1}
,"destination":{"label":1,"tunnel":1}
,"label":{"switched":1}
,"switched":{"path":1}
,"path":{"(lsp)":1}
,"(lsp)":{"logical":1}
,"logical":{"transport":1}
,"operating":{"source":1}
,"may":{"least":1}
,"least":{"lsp":1}
,"lsp":{"tunnels":1}
,"unidirectional":{"bidirectional":1,"tunnel":1}
,"bidirectional":{"depending":1,"tunnel":1}
,"depending":{"underlying":1}
,"underlying":{"lsps":1}
,"lsps":{"mpls-tp":1}
,"framework":{"(rfc":1}
,"(rfc":{"5921)":1}
,"5921)":{"defines":1}
,"defines":{"three":1}
,"three":{"types":1}
,"based":{"direction":1}
,"direction":{"property":1}
,"property":{"unidirectional":1}
,"co-routed":{"bidirectional":1}
,"associated":{"bidirectional":1}
}
;Search.control.loadWordPairs(pairs);
