var pairs =
{
"isis_nsm_recv_service":{"function":1,"(struct":1}
,"function":{"service":1}
,"service":{"reply":1}
,"reply":{"received":1}
,"received":{"syntax":1}
,"syntax":{"int":1}
,"int":{"isis_nsm_recv_service":1}
,"(struct":{"nsm_msg_header":1}
,"nsm_msg_header":{"*header":1}
,"*header":{"void":1}
,"void":{"*arg":1,"*message)":1}
,"*arg":{"void":1}
,"*message)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"*il":1,"none":1}
,"*il":{"pointer":1}
,"pointer":{"level":1}
,"level":{"context":1}
,"context":{"is-is":1}
,"is-is":{"instance":1}
,"instance":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
}
;Search.control.loadWordPairs(pairs);
