var pairs =
{
"vrrp_set_oper_rowstatus":{"function":1,"(int":1}
,"function":{"sets":1,"succeeds":1,"fails":1}
,"sets":{"operational":1}
,"operational":{"row":1}
,"row":{"status":1}
,"status":{"vrrp":1,"-active":1}
,"vrrp":{"virtual":1}
,"virtual":{"router":1}
,"router":{"syntax":1,"aftype":1,"-255)":1}
,"syntax":{"int":1}
,"int":{"vrrp_set_oper_rowstatus":1,"val)":1}
,"(int":{"ipi_vrid":1}
,"ipi_vrid":{"u_int8_t":1,"virtual":1}
,"u_int8_t":{"aftype":1,"vrid":1}
,"aftype":{"u_int8_t":1,"address":1}
,"vrid":{"u_int32_t":1,"vrrp":1}
,"u_int32_t":{"ifindex":1}
,"ifindex":{"int":1,"interface":1}
,"val)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ipi_vrid":1,"none":1}
,"address":{"family":1}
,"family":{"type":1}
,"type":{"(af_inet":1}
,"(af_inet":{"af_inet6)":1}
,"af_inet6)":{"vrid":1}
,"-255)":{"ifindex":1}
,"interface":{"index":1}
,"index":{"val":1}
,"val":{"value":1}
,"value":{"new":1}
,"new":{"row":1}
,"-active":{"-notinservice":1}
,"-notinservice":{"-createandgo":1}
,"-createandgo":{"-createandwait":1}
,"-createandwait":{"-destroy":1}
,"-destroy":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"vrrp_api_set_success":1}
,"vrrp_api_set_success":{"function":1}
,"succeeds":{"vrrp_api_set_error":1}
,"vrrp_api_set_error":{"function":1}
}
;Search.control.loadWordPairs(pairs);
