var pairs =
{
"vrrp_api_advt_interval":{"function":1,"(int":1}
,"function":{"sets":1}
,"sets":{"advertisement":1}
,"advertisement":{"interval":1}
,"interval":{"session":1,"application":1,"advertisement":1,"centiseconds":1,"seconds":1,"multiple":1,"vrrp":1}
,"session":{"receives":1,"value":1,"syntax":1,"virtual":1,"found":1,"already":1}
,"receives":{"interval":1}
,"application":{"configures":1}
,"configures":{"appropriate":1}
,"appropriate":{"session":1}
,"value":{"value":1,"vrrp":1,"100":1,"second":1}
,"vrrp":{"routers":1,"session":1,"input":1,"range":1}
,"routers":{"participating":1}
,"participating":{"session":1}
,"syntax":{"int":1}
,"int":{"vrrp_api_advt_interval":1,"vrid":1,"interval)":1}
,"(int":{"ipi_vrid":1}
,"ipi_vrid":{"u_int8_t":1,"virtual":1}
,"u_int8_t":{"af_type":1}
,"af_type":{"int":1,"address":1}
,"vrid":{"u_int32_t":1,"vrrp":1}
,"u_int32_t":{"ifindex":1}
,"ifindex":{"int":1,"interface":1}
,"interval)":{"input":1}
,"input":{"parameters":1,"accepted":1}
,"parameters":{"ipi_vrid":1,"none":1}
,"virtual":{"router":1}
,"router":{"af_type":1,"-255)":1}
,"address":{"family":1}
,"family":{"af_inet":1}
,"af_inet":{"(ipv4)":1}
,"(ipv4)":{"af_inet6":1}
,"af_inet6":{"(ipv6)":1}
,"(ipv6)":{"vrid":1}
,"-255)":{"ifindex":1}
,"interface":{"index":1}
,"index":{"interval":1}
,"centiseconds":{"vrrp":1,"advertisement":1,"vrrp_api_set_err_no_such_session":1}
,"accepted":{"multiples":1}
,"multiples":{"range":1}
,"range":{"4095":1,"255":1}
,"4095":{"default":1}
,"default":{"value":1}
,"100":{"centiseconds":1}
,"seconds":{"vrrp":1}
,"255":{"default":1}
,"second":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"vrrp_api_set_err_advt_intvl_not_factor_of_five":1}
,"vrrp_api_set_err_advt_intvl_not_factor_of_five":{"advertisement":1}
,"multiple":{"centiseconds":1}
,"vrrp_api_set_err_no_such_session":{"session":1}
,"found":{"vrrp_api_set_err_enabled":1}
,"vrrp_api_set_err_enabled":{"session":1}
,"already":{"active":1}
,"active":{"vrrp_ok":1}
,"vrrp_ok":{"interval":1}
}
;Search.control.loadWordPairs(pairs);
