var pairs =
{
"rsvp_snmp_get_tn_resource_meanburstsize":{"function":1,"(int":1}
,"function":{"gets":1,"succeeds":1}
,"gets":{"mean":1}
,"mean":{"burst":1}
,"burst":{"size":1}
,"size":{"bytes":1}
,"bytes":{"syntax":1,"return":1}
,"syntax":{"u_int32_t":1}
,"u_int32_t":{"rsvp_snmp_get_tn_resource_meanburstsize":1,"*ret)":1}
,"(int":{"rs_ix":1}
,"rs_ix":{"u_int32_t":1,"resource":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"rs_ix":1,"ret":1}
,"resource":{"table":1}
,"table":{"index":1,"found":1}
,"index":{"output":1}
,"output":{"parameters":1}
,"ret":{"mean":1}
,"return":{"value":1}
,"value":{"rsvp_api_get_success":1}
,"rsvp_api_get_success":{"function":1}
,"succeeds":{"rsvp_api_get_error":1}
,"rsvp_api_get_error":{"resource":1}
}
;Search.control.loadWordPairs(pairs);
