var pairs =
{
"hal_bridge_set_port_state":{"function":1,"(char":1}
,"function":{"sets":1,"succeeds":1}
,"sets":{"port":1}
,"port":{"state":1,"syntax":1,"interface":1}
,"state":{"bridge":1,"port":1,"output":1}
,"bridge":{"port":1,"name":1}
,"syntax":{"int":1}
,"int":{"hal_bridge_set_port_state":1,"ifindex":1,"instance":1,"state)":1}
,"(char":{"*bridge_name":1}
,"*bridge_name":{"int":1}
,"ifindex":{"int":1,"port":1}
,"instance":{"int":1,"instance":1,"number":1}
,"state)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bridge_name":1,"none":1}
,"bridge_name":{"bridge":1}
,"name":{"ifindex":1}
,"interface":{"index":1}
,"index":{"instance":1}
,"number":{"state":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"hal_err_bridge_port_not_exists":1}
,"hal_err_bridge_port_not_exists":{"hal_success":1}
,"hal_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
