var pairs =
{
"synce_api_manual_source":{"function":1,"(struct":1}
,"function":{"manually":1,"implements":1,"succeeds":1}
,"manually":{"selects":1,"command":1}
,"selects":{"synchronization":1}
,"synchronization":{"source":1}
,"source":{"function":1,"synce_err_ifp_lockout_enabled":1}
,"implements":{"switch-source":1}
,"switch-source":{"manually":1}
,"command":{"syntax":1}
,"syntax":{"include":1}
,"include":{"synced\u002Fsynce_api.h":1}
,"synced\u002Fsynce_api.h":{"s_int16_t":1}
,"s_int16_t":{"synce_api_manual_source":1}
,"(struct":{"interface":1}
,"interface":{"*ifp)":1,"output":1,"synce_err_ifp_async_mode":1,"input":1,"synce_err_ifp_signal_fail_active":1,"synce_err_ifp_ql_dnu":1,"synce_err_esmc_not_active_on_if":1,"synce_err_force_active_on_if":1,"synce_err_ql_not_greatest":1,"greater":1}
,"*ifp)":{"input":1}
,"input":{"parameters":1,"source":1}
,"parameters":{"ifp":1,"none":1}
,"ifp":{"interface":1,"ifp->":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"synce_failure":1}
,"synce_failure":{"synce":1}
,"synce":{"master":1,"disabled":1,"mode":1,"interfaces":1}
,"master":{"structure":1}
,"structure":{"cannot":1}
,"cannot":{"found":1}
,"found":{"synce_err_ifp_not_found":1}
,"synce_err_ifp_not_found":{"ifp":1}
,"ifp->":{"info":1}
,"info":{"null":1}
,"null":{"synce_err_ifp_synce_disabled":1}
,"synce_err_ifp_synce_disabled":{"synce":1}
,"disabled":{"interface":1}
,"synce_err_ifp_async_mode":{"synce":1}
,"mode":{"non-synchronous":1}
,"non-synchronous":{"synce_err_if_not_input_source":1}
,"synce_err_if_not_input_source":{"interface":1}
,"synce_err_ifp_lockout_enabled":{"lockout":1}
,"lockout":{"interface":1}
,"synce_err_ifp_signal_fail_active":{"signal":1}
,"signal":{"fail":1}
,"fail":{"active":1}
,"active":{"interface":1}
,"synce_err_ifp_ql_dnu":{"quality":1}
,"quality":{"level":1}
,"level":{"ql-dnu":1,"interface":1,"synce":1,"valid":1}
,"ql-dnu":{"ql-dus":1}
,"ql-dus":{"interface":1}
,"synce_err_esmc_not_active_on_if":{"esmc":1}
,"esmc":{"active":1}
,"synce_err_force_active_on_if":{"forceful":1}
,"forceful":{"selection":1}
,"selection":{"active":1}
,"synce_err_ql_not_greatest":{"quality":1}
,"greater":{"quality":1}
,"interfaces":{"synce_success":1}
,"synce_success":{"function":1}
,"succeeds":{"synce_err_ifp_priority_dis":1}
,"synce_err_ifp_priority_dis":{"priority":1}
,"priority":{"synce_err_ql_not_valid":1}
,"synce_err_ql_not_valid":{"quality":1}
,"valid":{"interface":1}
}
;Search.control.loadWordPairs(pairs);
