var pairs =
{
"operational":{"codes":1,"code":1}
,"codes":{"mpls":1}
,"mpls":{"forwarder":1,"shim":1,"packet":1}
,"forwarder":{"supports":1,"creates":1,"sets":1,"pops":1,"swaps":1,"forwards":1}
,"supports":{"following":1}
,"following":{"operational":1}
,"code":{"(opcodes)":1}
,"(opcodes)":{"designate":1}
,"designate":{"handling":1}
,"handling":{"labeled":1}
,"labeled":{"unlabeled":1,"packet":1}
,"unlabeled":{"packets":1,"packet":1}
,"packets":{"push":1}
,"push":{"upon":1}
,"upon":{"finding":1}
,"finding":{"opcode":1}
,"opcode":{"ftn":1,"ilm":1,"vrf":1,"added":1}
,"ftn":{"entry":1,"table":1}
,"entry":{"mpls":1,"push_and_lookup":1,"fec":1,"found":1,"push_and_lookup_for_vc":1,"virtual":1,"swap_and_lookup":1}
,"creates":{"mpls":1}
,"shim":{"top":1,"labeled":1}
,"top":{"packet":1,"ethernet":1}
,"packet":{"pushes":1,"pop":1,"label":1,"forwarded":1,"accordingly":1,"dropped":1,"dlvr_to_ip":1,"based":1,"resulting":1}
,"pushes":{"specified":1}
,"specified":{"label":1,"ilm":1,"ftn":1,"global":1}
,"label":{"creating":1,"shim":1,"last":1,"stack":1,"new":1,"forwards":1,"tries":1,"modified":1,"labeled":1,"onto":1}
,"creating":{"ethernet":1}
,"ethernet":{"frame":1}
,"frame":{"forwarder":1,"type":1,"pushes":1,"encapsulated":1,"forwarded":1}
,"sets":{"frame":1}
,"type":{"eth_p_mpls_uc":1}
,"eth_p_mpls_uc":{"uni-cast":1}
,"uni-cast":{"mpls":1}
,"pop":{"upon":1}
,"ilm":{"entry":1,"entries":1}
,"pops":{"specified":1}
,"last":{"label":1,"stack":1}
,"stack":{"packet":1,"ensuing":1}
,"forwarded":{"swap":1,"based":1,"push_for_vc":1,"pop_for_vc":1}
,"swap":{"upon":1}
,"swaps":{"specified":1}
,"new":{"outgoing":1}
,"outgoing":{"label":1,"interface":1}
,"forwards":{"labeled":1,"packet":1}
,"accordingly":{"pop_for_vpn":1}
,"pop_for_vpn":{"upon":1}
,"ensuing":{"unlabeled":1}
,"based":{"destination":1}
,"destination":{"(next-hop":1}
,"(next-hop":{"and\u002For":1}
,"and\u002For":{"out-going":1}
,"out-going":{"interface)":1}
,"interface)":{"specified":1}
,"push_and_lookup":{"upon":1}
,"vrf":{"entry":1}
,"tries":{"lookup":1}
,"lookup":{"ftn":1}
,"fec":{"question":1}
,"question":{"global":1}
,"global":{"ftn":1}
,"table":{"ftn":1}
,"found":{"packet":1}
,"dropped":{"creating":1,"successful":1}
,"dlvr_to_ip":{"upon":1}
,"push_and_lookup_for_vc":{"upon":1}
,"virtual":{"circuit":1}
,"circuit":{"end-point":1}
,"end-point":{"specified":1}
,"successful":{"modified":1}
,"modified":{"frame":1}
,"encapsulated":{"inside":1}
,"inside":{"ethernet":1}
,"push_for_vc":{"upon":1}
,"pop_for_vc":{"upon":1}
,"resulting":{"layer-2":1}
,"layer-2":{"pdu":1}
,"pdu":{"transmitted":1}
,"transmitted":{"outgoing":1}
,"interface":{"specified":1}
,"swap_and_lookup":{"opcode":1}
,"added":{"ilm":1}
,"entries":{"used":1}
,"used":{"pushing":1}
,"pushing":{"additional":1}
,"additional":{"label":1}
,"onto":{"incoming":1}
,"incoming":{"packet":1}
}
;Search.control.loadWordPairs(pairs);
