var pairs =
{
"synchronization":{"command":1,"internal":1,"used":1,"may":1,"synchronization":1,"parameters":1,"disabled":1,"ibgp":1,"following":1}
,"command":{"enable":1,"used":1,"syntax":1,"mode":1}
,"enable":{"igp":1}
,"igp":{"synchronization":1,"(for":1,"reachability":1}
,"internal":{"bgp":1,"gateway":1}
,"bgp":{"(ibgp)":1,"router":1,"autonomous":1,"(config-router)":1}
,"(ibgp)":{"learned":1}
,"learned":{"routes":1,"ibgp":1}
,"routes":{"internal":1,"learned":1,"present":1,"router":1,"ipv6-unicast":1}
,"gateway":{"protocol":1}
,"protocol":{"(igp)":1}
,"(igp)":{"system":1}
,"system":{"router":1,"speak":1,"transit":1}
,"router":{"configuration":1,"advertise":1,"mode":1,"bgp":1}
,"configuration":{"mode":1}
,"mode":{"address-family":1,"synchronization":1,"router":1,"address":1,"configure":1}
,"address-family":{"configuration":1,"ipv6":1}
,"used":{"bgp":1}
,"advertise":{"routes":1}
,"ibgp":{"neighbors":1,"routes":1}
,"neighbors":{"unless":1,"without":1}
,"unless":{"routes":1}
,"present":{"igp":1,"command":1}
,"(for":{"example":1}
,"example":{"ospf)":1,"enables":1}
,"ospf)":{"synchronization":1}
,"may":{"enabled":1}
,"enabled":{"routers":1}
,"routers":{"autonomous":1}
,"autonomous":{"system":1,"systems":1}
,"speak":{"bgp":1}
,"transit":{"autonomous":1}
,"systems":{"synchronization":1}
,"without":{"waiting":1}
,"waiting":{"igp":1}
,"reachability":{"present":1}
,"syntax":{"synchronization":1}
,"parameters":{"none":1}
,"none":{"default":1}
,"default":{"igp":1}
,"disabled":{"command":1}
,"address":{"family":1}
,"family":{"modes":1,"configure":1}
,"modes":{"examples":1}
,"examples":{"following":1}
,"following":{"example":1}
,"enables":{"igp":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"(config-router)":{"synchronization":1,"address-family":1}
,"ipv6-unicast":{"address":1}
,"ipv6":{"unicast":1}
,"unicast":{"(config-af)":1}
,"(config-af)":{"synchronization":1}
}
;Search.control.loadWordPairs(pairs);
