var pairs =
{
"definition":{"struct":1}
,"struct":{"trill_bridge":1,"trill_port":1}
,"trill_bridge":{"{\u002F*housekeeping":1,"*next":1,"**pprev":1}
,"{\u002F*housekeeping":{"variables":1}
,"variables":{"*\u002Fstruct":1}
,"*\u002Fstruct":{"trill_bridge":1,"route_table":1,"rlist_info":1,"trill":1}
,"*next":{"struct":1}
,"**pprev":{"struct":1}
,"trill_port":{"*port_list":1}
,"*port_list":{"char":1}
,"char":{"name":1}
,"name":{"[l2_bridge_name_len":1}
,"[l2_bridge_name_len":{"u_int32_t":1}
,"u_int32_t":{"instance_id":1}
,"instance_id":{"u_int8_t":1}
,"u_int8_t":{"type":1}
,"type":{"\u002F*vlan":1}
,"\u002F*vlan":{"tree":1}
,"tree":{"indexed":1}
,"indexed":{"vid":1}
,"vid":{"*\u002Fstruct":1}
,"route_table":{"*vlan_table":1}
,"*vlan_table":{"\u002F*list":1}
,"\u002F*list":{"vlans":1}
,"vlans":{"added":1}
,"added":{"common":1}
,"common":{"instance":1}
,"instance":{"*\u002Fstruct":1}
,"rlist_info":{"*vlan_list":1}
,"*vlan_list":{"\u002F*pointer":1}
,"\u002F*pointer":{"trill":1}
,"trill":{"instance":1,"*trill_inst":1}
,"*trill_inst":{"\u002F*ageing":1}
,"\u002F*ageing":{"timer":1}
,"timer":{",-this":1,"-this":1}
,",-this":{"maintained":1}
,"maintained":{"nsm":1}
,"nsm":{"module*\u002Fu_int16_t":1,"module":1}
,"module*\u002Fu_int16_t":{"ageing_timer":1}
,"ageing_timer":{"\u002F*forward":1}
,"\u002F*forward":{"timer":1}
,"-this":{"maintained":1}
,"module":{"*\u002Fu_char":1}
,"*\u002Fu_char":{"forward_delay":1}
,"forward_delay":{"u_char":1}
,"u_char":{"is_default:1":1}
,"is_default:1":{"s_int16_t":1}
,"s_int16_t":{"num_ports":1}
}
;Search.control.loadWordPairs(pairs);
