var pairs =
{
"nsm_svlan_set_max_uni":{"function":1,"(struct":1}
,"function":{"sets":1,"succeeds":1}
,"sets":{"maximum":1}
,"maximum":{"number":1}
,"number":{"unis":1}
,"unis":{"allowed":1,"output":1}
,"allowed":{"uni":1}
,"uni":{"list":1}
,"list":{"service":1}
,"service":{"attribute":1}
,"attribute":{"two":1}
,"two":{"evc":1,"nsm_vlan_err_max_uni_m2m":1}
,"evc":{"type":1,"identifier":1}
,"type":{"point-to-point":1}
,"point-to-point":{"api":1,"max_uni":1}
,"api":{"s_int32_t":1}
,"s_int32_t":{"nsm_svlan_set_max_uni":1}
,"(struct":{"nsm_bridge_master":1}
,"nsm_bridge_master":{"*master":1}
,"*master":{"u_int8_t":1}
,"u_int8_t":{"*bridge_name":1,"*evc_id":1}
,"*bridge_name":{"u_int16_t":1}
,"u_int16_t":{"svid":1,"max_uni)":1}
,"svid":{"u_int8_t":1}
,"*evc_id":{"u_int16_t":1}
,"max_uni)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"master":1,"none":1}
,"master":{"bridge":1,"bridge_name":1}
,"bridge":{"master":1,"name":1,"found":1,"configured":1,"nsm_vlan_err_bridge_not_vlan_aware":1,"vlan":1}
,"bridge_name":{"bridge":1}
,"name":{"svlan":1}
,"svlan":{"svlan":1,"identifier":1,"multipoint-to-multipoint":1}
,"identifier":{"evc_id":1,"max_uni":1}
,"evc_id":{"evc":1}
,"max_uni":{"maximum":1,"two":1,"less":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_vlan_err_bridge_not_found":1}
,"nsm_vlan_err_bridge_not_found":{"bridge":1}
,"found":{"nsm_vlan_err_not_edge_bridge":1,"nsm_vlan_err_max_uni_pt_to_pt":1}
,"nsm_vlan_err_not_edge_bridge":{"bridge":1}
,"configured":{"edge":1}
,"edge":{"bridge":1}
,"nsm_vlan_err_bridge_not_vlan_aware":{"bridge":1}
,"vlan":{"aware":1,"found":1,"point-to-point":1}
,"aware":{"nsm_vlan_err_vlan_not_found":1}
,"nsm_vlan_err_vlan_not_found":{"vlan":1}
,"nsm_vlan_err_max_uni_pt_to_pt":{"vlan":1}
,"nsm_vlan_err_max_uni_m2m":{"svlan":1}
,"multipoint-to-multipoint":{"max_uni":1}
,"less":{"result_ok":1}
,"result_ok":{"function":1}
}
;Search.control.loadWordPairs(pairs);
