var pairs =
{
"backup":{"meg":1,"maintenance":1,"entity":1}
,"meg":{"command":1,"ietf":1,"itu-t":1,"name":1,"meg":1,"meg1":1}
,"command":{"configure":1,"form":1,"remove":1,"syntax":1,"mode":1}
,"configure":{"backup":1,"terminal":1}
,"maintenance":{"entity":1}
,"entity":{"group":1,"either":1,"identifier":1,"end":1}
,"group":{"(meg)":1,"command":1,"point":1,"end":1,"mode":1}
,"(meg)":{"protection":1}
,"protection":{"group":1}
,"either":{"ietf":1}
,"ietf":{"itu-t":1,"maintenance":1}
,"itu-t":{"identifier":1,"maintenance":1}
,"identifier":{"command":1,"form":1,"name":1,"maximum":1,"<1-8191>":1}
,"form":{"parameter":1,"mep-id":1,"command":1}
,"parameter":{"configure":1}
,"mep-id":{"parameter":1,"<1-8191>":1,"itu-t":1,"configure":1}
,"end":{"group":1,"point":1}
,"point":{"identifier":1}
,"remove":{"backup":1}
,"syntax":{"backup":1}
,"name":{"name":1,"backup":1,"mep-id":1,"meg":1,"maximum":1,"ietf":1}
,"<1-8191>":{"backup":1,"parameters":1,"itu-t":1}
,"parameters":{"meg":1}
,"maximum":{"characters":1}
,"characters":{"ietf":1,"mep-id":1}
,"mode":{"protection":1,"examples":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"mpls-tp":1}
,"mpls-tp":{"lps":1}
,"lps":{"protection-group":1}
,"protection-group":{"abc":1}
,"abc":{"(config-pg)":1}
,"(config-pg)":{"backup":1}
,"meg1":{"me1":1,"mep-id":1}
,"me1":{"(config-pg)":1}
}
;Search.control.loadWordPairs(pairs);
