var pairs =
{
"cfm_ais_enable":{"function":1,"(struct":1}
,"function":{"called":1,"succeeds":1}
,"called":{"ethernet":1}
,"ethernet":{"cfm":1}
,"cfm":{"ais":1}
,"ais":{"status":1,"frames":1,"defect":1}
,"status":{"command":1}
,"command":{"enable":1}
,"enable":{"option":1}
,"option":{"used":1}
,"used":{"configure":1}
,"configure":{"alarm":1}
,"alarm":{"indicator":1}
,"indicator":{"signaling":1}
,"signaling":{"(ais)":1}
,"(ais)":{"frames":1}
,"frames":{"bridge":1,"md_name":1,"remote":1}
,"bridge":{"syntax":1,"bridge":1,"host":1,"found":1}
,"syntax":{"include":1}
,"include":{"cfm_ais.h":1}
,"cfm_ais.h":{"s_int8_t":1}
,"s_int8_t":{"cfm_ais_enable":1,"destlevel":1}
,"(struct":{"onmd_bridge":1}
,"onmd_bridge":{"*bridge":1}
,"*bridge":{"u_int32_t":1}
,"u_int32_t":{"mepid":1}
,"mepid":{"u_int8_t":1,"source":1}
,"u_int8_t":{"ais_type":1,"*md_name":1,"*rmac":1,"defect_type":1}
,"ais_type":{"u_int8_t":1,"unicast":1}
,"*md_name":{"u_int8_t":1}
,"*rmac":{"s_int8_t":1}
,"destlevel":{"u_int16_t":1,"level":1}
,"u_int16_t":{"vid":1}
,"vid":{"u_int8_t":1,"vlan":1}
,"defect_type":{"struct":1,"constants":1}
,"struct":{"interface":1}
,"interface":{"*ifp)":1,"return":1}
,"*ifp)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bridge":1}
,"host":{"mep":1}
,"mep":{"exists":1,"<1-8191>":1,"address":1,"cfm_api_err_ais_defect_cond_all":1}
,"exists":{"mepid":1,"vid":1}
,"source":{"mep":1}
,"<1-8191>":{"ais_type":1}
,"unicast":{"multicast":1,"frames":1}
,"multicast":{"ais":1}
,"md_name":{"maintenance":1}
,"maintenance":{"domain":1}
,"domain":{"name":1}
,"name":{"rmac":1}
,"rmac":{"unicast":1}
,"remote":{"mep":1}
,"address":{"mac":1}
,"mac":{"format":1}
,"format":{"destlevel":1}
,"level":{"mep":1}
,"vlan":{"<1-4094>":1}
,"<1-4094>":{"defect_type":1}
,"constants":{"onmd\u002Fcfm\u002Fcfm_ais.h":1}
,"onmd\u002Fcfm\u002Fcfm_ais.h":{"cfm_ais_defect_type_all":1}
,"cfm_ais_defect_type_all":{"cfm_ais_defect_type_loc":1}
,"cfm_ais_defect_type_loc":{"cfm_ais_defect_type_mismerge":1}
,"cfm_ais_defect_type_mismerge":{"cfm_ais_defect_type_unexp_mep":1}
,"cfm_ais_defect_type_unexp_mep":{"cfm_ais_defect_type_unexp_meg_lvl":1}
,"cfm_ais_defect_type_unexp_meg_lvl":{"cfm_ais_defect_type_unexp_period":1}
,"cfm_ais_defect_type_unexp_period":{"ifp":1}
,"ifp":{"pointer":1}
,"pointer":{"interface":1}
,"return":{"value":1}
,"value":{"cfm_failure":1}
,"cfm_failure":{"bridge":1}
,"found":{"cfm_api_err_ais_link_level_mep":1}
,"cfm_api_err_ais_link_level_mep":{"link":1}
,"link":{"local":1}
,"local":{"mep":1}
,"cfm_api_err_ais_defect_cond_all":{"ais":1}
,"defect":{"condition":1}
,"condition":{"configured":1}
,"configured":{"cfm_success":1}
,"cfm_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
