var pairs =
{
"contents":{"document":1}
,"document":{"contains":1}
,"contains":{"chapters":1}
,"chapters":{"appendices":1}
,"appendices":{"chapter":1}
,"chapter":{"ethernet":1,"cfm":1,"link":1,"provider":1,"mef":1,"user":1,"pbb-te":1,"service":1,"g.8032":1,"dual-ended":1}
,"ethernet":{"cfm":1,"first":1,"protection":1,"switched":1}
,"cfm":{"configurations":1,"pbb":1,"support":1}
,"configurations":{"chapter":1}
,"pbb":{"configurations":1}
,"first":{"mile":1}
,"mile":{"oam":1}
,"oam":{"configuration":1}
,"configuration":{"chapter":1}
,"link":{"layer":1}
,"layer":{"discovery":1}
,"discovery":{"protocol":1}
,"protocol":{"configuration":1}
,"provider":{"bridging":1,"backbone":1}
,"bridging":{"configuration":1}
,"mef":{"uni":1,"enni":1}
,"uni":{"configuration":1}
,"enni":{"configuration":1}
,"user":{"network":1}
,"network":{"interface":1}
,"interface":{"configuration":1}
,"backbone":{"bridging":1}
,"protection":{"switching":1}
,"switching":{"configuration":1}
,"pbb-te":{"configurations":1,"ethernet":1,"aps":1}
,"switched":{"path":1}
,"path":{"configuration":1}
,"aps":{"configuration":1}
,"service":{"oam":1}
,"g.8032":{"erps":1}
,"erps":{"version":1}
,"version":{"chapter":1}
,"dual-ended":{"lmm":1}
,"lmm":{"configurations":1}
,"support":{"peb":1}
,"peb":{"configuration":1}
}
;Search.control.loadWordPairs(pairs);
