var pairs =
{
"overview":{"msdp":1}
,"msdp":{"routers":1,"peering":1,"peers":1,"(source-active)":1,"peer":1}
,"routers":{"pim-sm":1}
,"pim-sm":{"domain":1}
,"domain":{"msdp":1,"using":1,"first":1,"checks":1}
,"peering":{"relationship":1,"first":1,"rps":1}
,"relationship":{"msdp":1}
,"peers":{"domain":1,"rps":1,"(except":1}
,"using":{"tcp":1,"msdp":1}
,"tcp":{"connection":1}
,"connection":{"msdp":1}
,"first":{"step":1,"learns":1}
,"step":{"towards":1}
,"towards":{"exchanging":1,"originating":1,"source":1}
,"exchanging":{"inter-domain":1}
,"inter-domain":{"multicast":1}
,"multicast":{"source":1}
,"source":{"information":1,"address":1,"group":1,"sends":1}
,"information":{"using":1}
,"(source-active)":{"messages":1}
,"messages":{"pim-sm":1,"establish":1}
,"learns":{"new":1}
,"new":{"sender":1,"message":1}
,"sender":{"(via":1}
,"(via":{"pim":1}
,"pim":{"register":1}
,"register":{"messages)":1}
,"messages)":{"constructs":1}
,"constructs":{"message":1}
,"message":{"sends":1,"contains":1,"received":1,"msdp":1,"otherwise":1,"peer":1}
,"sends":{"msdp":1,"address":1,"join":1}
,"rps":{"intend":1,"either":1}
,"intend":{"originate":1}
,"originate":{"receive":1}
,"receive":{"messages":1}
,"establish":{"msdp":1}
,"either":{"directly":1}
,"directly":{"via":1}
,"via":{"intermediate":1}
,"intermediate":{"msdp":1}
,"peer":{"message":1,"rpf":1,"receives":1,"towards":1,"domain":1}
,"contains":{"fields":1}
,"fields":{"source":1}
,"address":{"data":1,"message":1,"carried":1}
,"data":{"source":1}
,"group":{"address":1}
,"received":{"msdp":1,"message)":1}
,"rpf":{"check":1}
,"check":{"peer-rpf":1,"compares":1}
,"peer-rpf":{"check":1}
,"compares":{"address":1}
,"carried":{"message":1}
,"receives":{"non-rpf":1,"new":1}
,"non-rpf":{"peer":1}
,"originating":{"drops":1}
,"drops":{"message":1}
,"otherwise":{"forwards":1}
,"forwards":{"message":1}
,"(except":{"received":1}
,"message)":{"receives":1}
,"checks":{"receivers":1,"entry":1}
,"receivers":{"interested":1}
,"interested":{"traffic":1}
,"traffic":{"checks":1}
,"entry":{"non-empty":1}
,"non-empty":{"outgoing":1,"sends":1}
,"outgoing":{"list":1}
,"list":{"outgoing":1,"non-empty":1}
,"join":{"towards":1}
}
;Search.control.loadWordPairs(pairs);
