var pairs =
{
"embedded":{"multicast":1,"interface":1}
,"multicast":{"group":1,"address":1}
,"group":{"address":1,"flgs":1}
,"address":{"format":1,"embeds":1,"case":1}
,"format":{"rfc":1,"specifying":1}
,"rfc":{"3956":1}
,"3956":{"specifies":1}
,"specifies":{"modification":1}
,"modification":{"unicast-prefix-based":1}
,"unicast-prefix-based":{"address":1}
,"specifying":{"second":1}
,"second":{"high-order":1}
,"high-order":{"bit":1}
,"bit":{"(r-bit)":1,"flag":1}
,"(r-bit)":{"follows":1}
,"follows":{"11111111":1}
,"11111111":{"flgs":1}
,"flgs":{"scop":1,"four":1}
,"scop":{"rsvd":1}
,"rsvd":{"riid":1}
,"riid":{"plen":1}
,"plen":{"network":1}
,"network":{"prefix":1}
,"prefix":{"group":1,"ff70":1}
,"four":{"flags":1}
,"flags":{"highest-order":1}
,"highest-order":{"bit":1}
,"flag":{"indicates":1}
,"indicates":{"multicast":1}
,"embeds":{"address":1}
,"case":{"effect":1}
,"effect":{"implies":1}
,"implies":{"prefix":1}
,"ff70":{":\u002F12":1}
,":\u002F12":{"means":1}
,"means":{"last":1}
,"last":{"bits":1}
,"bits":{"previously":1}
,"previously":{"field":1}
,"field":{"interpreted":1}
,"interpreted":{"embedded":1}
}
;Search.control.loadWordPairs(pairs);
