var pairs =
{
"hal_dcb_bridge_enable":{"function":1,"(char":1}
,"function":{"sends":1}
,"sends":{"hal_msg_dcb_enable":1}
,"hal_msg_dcb_enable":{"message":1}
,"message":{"hsl":1}
,"hsl":{"enable":1}
,"enable":{"dcb":1}
,"dcb":{"hardware":1}
,"hardware":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"hal_dcb_bridge_enable":1}
,"(char":{"*bridge_name)":1}
,"*bridge_name)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bridge_name":1,"none":1}
,"bridge_name":{"bridge":1}
,"bridge":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"hal_success":1}
}
;Search.control.loadWordPairs(pairs);
