var pairs =
{
"pe4":{"configure":1,"(config-router)":1}
,"configure":{"terminal":1,"mode":1,"transport-address":1,"manual":1,"mpls":1,"bridge-group":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"router":1,"interface":1}
,"mode":{"(config)":1,"(config-router)":1,"(config-if)":1,"access":1}
,"(config)":{"router":1,"interface":1,"mpls":1,"bridge":1}
,"router":{"ldp":1}
,"ldp":{"enter":1,"mode":1,"provider":1}
,"(config-router)":{"transport-address":1,"exit":1}
,"transport-address":{"ipv4":1,"pe4":1}
,"ipv4":{"4.4.4.4":1,"enable":1}
,"4.4.4.4":{"configure":1}
,"exit":{"exit":1,"router":1,"interface":1}
,"interface":{"eth1":1,"mode":1,"pe1":1,"eth2":1}
,"eth1":{"enter":1,"eth2":1}
,"(config-if)":{"label-switching":1,"enable-ldp":1,"exit":1,"switchport":1,"bridge-group":1,"mpls-l2-circuit":1}
,"label-switching":{"enable":1,"provider":1}
,"enable":{"label-switching":1,"ldp":1}
,"provider":{"interface":1}
,"pe1":{"(config-if)":1}
,"enable-ldp":{"ipv4":1}
,"mpls":{"l2-circuit":1,"l2-circuit-fib-entry":1}
,"l2-circuit":{"2.2.2.2":1,"fib":1}
,"2.2.2.2":{"manual":1,"eth1":1}
,"manual":{"configure":1,"named":1,"(config)":1}
,"named":{"pw-id":1}
,"pw-id":{"(config)":1}
,"l2-circuit-fib-entry":{"8000":1}
,"8000":{"7000":1}
,"7000":{"2.2.2.2":1}
,"eth2":{"configure":1,"enter":1,"access":1}
,"fib":{"entry":1}
,"entry":{"manual":1}
,"bridge":{"protocol":1,"vlan":1}
,"protocol":{"ieee":1}
,"ieee":{"vlan-bridge":1}
,"vlan-bridge":{"specify":1}
,"specify":{"bridge":1}
,"vlan":{"(config)":1}
,"switchport":{"switch":1,"mode":1}
,"switch":{"layer-2":1}
,"layer-2":{"mode":1}
,"bridge-group":{"configure":1,"(config-if)":1}
,"access":{"switching":1,"mode":1,"interface":1}
,"switching":{"characteristics":1}
,"characteristics":{"eth2":1}
,"mpls-l2-circuit":{"bind":1}
,"bind":{"access":1}
}
;Search.control.loadWordPairs(pairs);
