var pairs =
{
"sw1":{"sw1":1,"configure":1,"(config)":1,"(config-vlan)":1,"(config-if)":1}
,"configure":{"terminal":1,"mode":1,"evb":1,"vlan":1,"service":1,"switchport":1,"tlv":1,"acknowledgement":1,"maximum":1,"vdp":1,"resource-wait-delay":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"interface":1}
,"mode":{"sw1":1,"sbp":1,"automatic":1}
,"(config)":{"bridge":1,"vlan":1,"int":1,"lldp":1,"evb":1,"exit":1}
,"bridge":{"protocol":1,"state":1,"sw1":1,"group":1,"tlv-mode":1,"ecp-acktimer":1,"ecp-max-retry":1,"vdp-keep-alive":1,"resource-wait-delay":1,"cdcp":1}
,"protocol":{"evb":1,"sw1":1}
,"evb":{"configure":1,"bridge":1,"cdcp":1,"reflective-relay":1}
,"vlan":{"database":1,"type":1,"associate":1,"mode":1}
,"database":{"configure":1,"sw1":1}
,"(config-vlan)":{"vlan":1,"exit":1}
,"type":{"service":1}
,"service":{"multipoint-multipoint":1,"vlan":1}
,"multipoint-multipoint":{"bridge":1}
,"state":{"enable":1}
,"enable":{"configure":1,"bridge":1,"enable":1,"cdcp":1,"reflective":1,"txrx":1,"lldp":1}
,"associate":{"bridge":1}
,"exit":{"exit":1,"vlan":1,"interface":1,"configure":1}
,"int":{"eth1":1}
,"eth1":{"enter":1}
,"interface":{"mode":1,"sw1":1}
,"(config-if)":{"switchport":1,"bridge-group":1,"evb":1,"lldp":1,"exit":1}
,"switchport":{"configure":1,"switch":1,"mode":1}
,"switch":{"layer":1}
,"layer":{"mode":1}
,"bridge-group":{"enable":1}
,"group":{"sw1":1}
,"sbp":{"configure":1,"evb":1}
,"cdcp":{"enable":1,"interface":1,"channel-capacity":1,"svid-pool-range":1}
,"reflective-relay":{"enable":1}
,"reflective":{"relay":1}
,"relay":{"interface":1}
,"lldp":{"enable":1,"sw1":1,"tlv":1}
,"txrx":{"enable":1}
,"tlv":{"ieee-8021-org-specific":1,"sw1":1,"mode":1}
,"ieee-8021-org-specific":{"specify":1}
,"specify":{"lldp":1,"channel":1,"svid":1}
,"tlv-mode":{"auto":1}
,"auto":{"configure":1}
,"automatic":{"sw1":1}
,"ecp-acktimer":{"configure":1}
,"acknowledgement":{"time":1}
,"time":{"sw1":1}
,"ecp-max-retry":{"configure":1}
,"maximum":{"number":1}
,"number":{"retries":1}
,"retries":{"sw1":1}
,"vdp-keep-alive":{"configure":1}
,"vdp":{"keep-alive":1}
,"keep-alive":{"time":1}
,"resource-wait-delay":{"configure":1,"time":1}
,"channel-capacity":{"167":1}
,"167":{"specify":1}
,"channel":{"capacity":1}
,"capacity":{"sw1":1}
,"svid-pool-range":{"4094":1}
,"4094":{"specify":1}
,"svid":{"pool":1}
,"pool":{"range":1}
,"range":{"sw1":1}
}
;Search.control.loadWordPairs(pairs);
