var pairs =
{
"synce_api_set_if_type_priority":{"function":1,"(u_int8_t":1}
,"function":{"sets":1,"implements":1,"succeeds":1}
,"sets":{"interface":1}
,"interface":{"input":1,"synchronous":1,"*ifp)":1,"type":1,"output":1,"synce_err_ifp_async_mode":1}
,"input":{"source":1,"parameters":1}
,"source":{"output":1,"function":1,"considered":1}
,"output":{"source":1,"parameters":1}
,"implements":{"input-source":1}
,"input-source":{"output-source":1}
,"output-source":{"commands":1}
,"commands":{"interface":1}
,"synchronous":{"ethernet":1}
,"ethernet":{"mode":1}
,"mode":{"syntax":1,"non-synchronous":1}
,"syntax":{"include":1}
,"include":{"synced\u002Fsynce_api.h":1}
,"synced\u002Fsynce_api.h":{"s_int16_t":1}
,"s_int16_t":{"synce_api_set_if_type_priority":1}
,"(u_int8_t":{"priority":1}
,"priority":{"u_int8_t":1,"priority":1,"<0-255>":1,"already":1}
,"u_int8_t":{"synce_if_type":1}
,"synce_if_type":{"struct":1,"synce_if_type_output_source":1,"interface":1}
,"struct":{"interface":1}
,"*ifp)":{"input":1}
,"parameters":{"priority":1,"none":1}
,"<0-255>":{"highest":1}
,"highest":{"255":1}
,"255":{"lowest":1}
,"lowest":{"means":1}
,"means":{"source":1}
,"considered":{"clock":1}
,"clock":{"selection":1}
,"selection":{"algorithm":1}
,"algorithm":{"value":1}
,"value":{"ignored":1,"synce_err_ifp_not_found":1}
,"ignored":{"synce_if_type":1}
,"synce_if_type_output_source":{"synce_if_type":1,"ifp":1}
,"type":{"constants":1,"priority":1}
,"constants":{"synced\u002Fsynce_types.h":1}
,"synced\u002Fsynce_types.h":{"synce_if_type_input_source":1}
,"synce_if_type_input_source":{"synce_if_type_output_source":1}
,"ifp":{"interface":1,"ifp->":1}
,"none":{"return":1}
,"return":{"value":1}
,"synce_err_ifp_not_found":{"ifp":1}
,"ifp->":{"info":1}
,"info":{"null":1}
,"null":{"synce_err_ifp_synce_disabled":1}
,"synce_err_ifp_synce_disabled":{"synce":1}
,"synce":{"disabled":1,"mode":1}
,"disabled":{"interface":1}
,"synce_err_ifp_async_mode":{"synce":1}
,"non-synchronous":{"synce_err_priority_set":1}
,"synce_err_priority_set":{"interface":1}
,"already":{"given":1}
,"given":{"values":1}
,"values":{"result_ok":1}
,"result_ok":{"function":1}
}
;Search.control.loadWordPairs(pairs);
