var pairs =
{
"neighbor":{"soo":1,"(a.b.c.d":1,"ipv4":1,"ipv6":1,"peer-group":1,"remote-as":1,"10.10.0.1":1}
,"soo":{"command":1,"as:nn_or_ip:nn":1,"parameters":1,"100:1":1}
,"command":{"enable":1,"ensures":1,"disable":1,"syntax":1,"command":1,"applies":1,"mode":1}
,"enable":{"site-of-origin":1}
,"site-of-origin":{"(soo)":1}
,"(soo)":{"feature":1}
,"feature":{"customer":1,"command":1}
,"customer":{"multi-homed":1}
,"multi-homed":{"isp":1}
,"isp":{"command":1}
,"ensures":{"advertise":1}
,"advertise":{"routes":1}
,"routes":{"back":1}
,"back":{"parameter":1}
,"parameter":{"command":1,"used":1}
,"disable":{"feature":1}
,"syntax":{"neighbor":1}
,"(a.b.c.d":{"x:x":1}
,"x:x":{":x:x":1}
,":x:x":{"word)":1,"address":1}
,"word)":{"soo":1}
,"as:nn_or_ip:nn":{"neighbor":1}
,"parameters":{"a.b.c.d":1}
,"a.b.c.d":{"address":1}
,"address":{"bgp":1,"arbitrary":1,"family":1}
,"bgp":{"neighbor":1,"100":1}
,"ipv4":{"format":1,"vrf":1}
,"format":{"x:x":1,"word":1}
,"ipv6":{"format":1}
,"word":{"name":1}
,"name":{"existing":1}
,"existing":{"peer":1}
,"peer":{"group":1,"groups":1}
,"group":{"information":1,"asn:nn_or_ip-address:nn":1}
,"information":{"create":1}
,"create":{"peer":1}
,"groups":{"refer":1}
,"refer":{"neighbor":1}
,"peer-group":{"neighbor":1}
,"remote-as":{"commands":1}
,"commands":{"parameter":1}
,"used":{"command":1}
,"applies":{"peers":1}
,"peers":{"group":1}
,"asn:nn_or_ip-address:nn":{"specify":1}
,"specify":{"number":1,"32-bit":1}
,"number":{"arbitrary":1,"(for":1}
,"arbitrary":{"number":1}
,"(for":{"example":1}
,"example":{"100:1)":1,"192.16.10.1:1)":1}
,"100:1)":{"otherwise":1}
,"otherwise":{"specify":1}
,"32-bit":{"address":1}
,"192.16.10.1:1)":{"command":1}
,"mode":{"address":1,"examples":1}
,"family":{"vrf":1}
,"vrf":{"mode":1,"vrf_a":1}
,"examples":{"(config)":1}
,"(config)":{"router":1}
,"router":{"bgp":1}
,"100":{"(config-router)":1}
,"(config-router)":{"address-family":1}
,"address-family":{"ipv4":1}
,"vrf_a":{"(config-router-af)":1}
,"(config-router-af)":{"neighbor":1}
,"10.10.0.1":{"soo":1}
}
;Search.control.loadWordPairs(pairs);
