var pairs =
{
"configure":{"terminal":1,"mode":1,"bridge":1,"virtual":1,"eth1":1,"address":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"vlan":1,"interface":1,"privileged":1}
,"mode":{"(config)":1,"(config-if)":1,"trunk":1,"login":1,"con":1}
,"(config)":{"bridge":1,"vlan":1,"exit":1,"int":1,"switchport":1,"bridge-group":1,"virtual-router":1,"vrf":1,"address":1}
,"bridge":{"protocol":1,"(config-vr)":1,"state":1}
,"protocol":{"ieee":1}
,"ieee":{"vlan-bridge":1}
,"vlan-bridge":{"configure":1}
,"(config-vr)":{"vlan":1}
,"vlan":{"database":1,"bridge":1,"(config)":1,"add":1,"eth1":1,"1.2":1}
,"database":{"enter":1,"mode":1}
,"state":{"enable":1}
,"enable":{"enable":1,"vlan":1}
,"exit":{"vlan":1,"exit":1,"interface":1,"router":1,"configure":1,"vrf":1}
,"(config-if)":{"virtual-router":1,"exit":1,"switchport":1,"int":1,"vrf":1}
,"virtual-router":{"forwarding":1,"vr1":1}
,"forwarding":{"vr1":1,"vrf1":1}
,"vr1":{"configure":1,"(config-if)":1,"associate":1,"(config-router)":1,"log":1,"enter":1}
,"virtual":{"router":1}
,"router":{"vr1":1,"mode":1}
,"interface":{"mode":1,"(config)":1,"(config-if)":1,"vr1":1,"vrf2":1}
,"int":{"eth1":1,"vlan":1,"vlan1.2":1}
,"eth1":{"enter":1,"layer":1,"bridge-group":1,"trunk":1,"interface":1}
,"switchport":{"eth1":1,"mode":1,"trunk":1}
,"layer":{"interface":1}
,"bridge-group":{"associate":1,"(config-if)":1}
,"associate":{"eth1":1,"vlan":1,"vlan1.2":1}
,"trunk":{"configure":1,"port":1,"allowed":1}
,"port":{"(config-if)":1}
,"allowed":{"vlan":1}
,"add":{"allow":1}
,"allow":{"vlan":1}
,"1.2":{"enter":1,"interface":1}
,"(config-router)":{"exit":1}
,"login":{"virtual-router":1}
,"log":{"virtual":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"con":{"enter":1}
,"vrf":{"vrf1":1,"mode":1,"forwarding":1}
,"vrf1":{"create":1,"(config-vrf)":1,"associate":1}
,"create":{"vrf1":1}
,"(config-vrf)":{"exit":1}
,"vlan1.2":{"enter":1,"interface":1}
,"vrf2":{"(config)":1}
,"address":{"2.2.2.1\u002F24":1,"vlan1.2":1}
,"2.2.2.1\u002F24":{"configure":1}
}
;Search.control.loadWordPairs(pairs);
