var pairs =
{
"ospf":{"resync-timeout":1,"(a.b.c.d":1,"re-synchronization":1}
,"resync-timeout":{"command":1,"<1-65535>":1,"parameters":1,"specify":1}
,"command":{"interval":1,"return":1,"syntax":1,"mode":1}
,"interval":{"adjacency":1,"period":1}
,"adjacency":{"reset":1}
,"reset":{"out-of-band":1}
,"out-of-band":{"re-synchronization":1}
,"re-synchronization":{"occurred":1,"timeout":1}
,"occurred":{"interval":1}
,"period":{"starts":1}
,"starts":{"time":1}
,"time":{"restart":1}
,"restart":{"signal":1}
,"signal":{"received":1}
,"received":{"neighbor":1}
,"neighbor":{"parameter":1}
,"parameter":{"command":1}
,"return":{"default":1}
,"default":{"value":1}
,"value":{"command":1,"interface":1,"seconds":1}
,"syntax":{"ospf":1}
,"(a.b.c.d":{"resync-timeout":1}
,"<1-65535>":{"ospf":1,"specify":1}
,"parameters":{"a.b.c.d":1}
,"a.b.c.d":{"address":1}
,"address":{"interface":1}
,"interface":{"resync-timeout":1,"<1-65535>":1,"seconds":1,"mode":1,"configure":1,"eth0":1}
,"specify":{"re-synchronization":1}
,"timeout":{"value":1}
,"seconds":{"command":1,"eth0":1}
,"mode":{"interface":1,"examples":1}
,"examples":{"following":1}
,"following":{"example":1}
,"example":{"shows":1}
,"shows":{"setting":1}
,"setting":{"ospf":1}
,"eth0":{"interface":1,"(config-if)":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"(config-if)":{"ospf":1}
}
;Search.control.loadWordPairs(pairs);
