var pairs =
{
"route":{"aggregation":1,"advertised":1}
,"aggregation":{"aggregation":1,"process":1,"reduces":1,"routes":1}
,"process":{"combining":1,"reduce":1}
,"combining":{"characteristics":1}
,"characteristics":{"several":1}
,"several":{"different":1}
,"different":{"routes":1}
,"routes":{"single":1,"aggregated":1,"identical":1}
,"single":{"route":1}
,"advertised":{"aggregation":1}
,"reduces":{"amount":1}
,"amount":{"information":1,"routing":1}
,"information":{"bgp":1,"placed":1}
,"bgp":{"speaker":1}
,"speaker":{"store":1}
,"store":{"exchange":1}
,"exchange":{"speakers":1}
,"speakers":{"part":1}
,"part":{"decision":1}
,"decision":{"process":1}
,"reduce":{"amount":1}
,"routing":{"information":1}
,"placed":{"adj-ribs-out":1}
,"adj-ribs-out":{"general":1}
,"general":{"rule":1}
,"rule":{"route":1}
,"aggregated":{"corresponding":1}
,"corresponding":{"attributes":1}
,"attributes":{"routes":1}
}
;Search.control.loadWordPairs(pairs);
