var pairs =
{
"clear":{"bgp":1,"incoming":1,"outgoing":1}
,"bgp":{"x:x":1,"connection":1,"3ffe":1}
,"x:x":{":x:x":1}
,":x:x":{"vpnv6":1}
,"vpnv6":{"command":1,"bgp":1,"unicast":1}
,"command":{"reset":1,"syntax":1,"mode":1}
,"reset":{"vpnv6":1}
,"connection":{"specific":1}
,"specific":{"address":1}
,"address":{"command":1}
,"syntax":{"clear":1}
,"unicast":{"clear":1,"soft":1}
,"soft":{"clear":1,"parameters":1,"reconfig":1}
,"parameters":{"clear":1}
,"incoming":{"advertised":1,"outgoing":1}
,"advertised":{"routes":1}
,"routes":{"clear":1,"soft":1}
,"outgoing":{"advertised":1,"routes":1}
,"reconfig":{"inbound":1,"outbound":1}
,"inbound":{"update":1}
,"update":{"soft":1,"command":1}
,"outbound":{"update":1}
,"mode":{"privileged":1,"examples":1}
,"privileged":{"exec":1}
,"exec":{"mode":1}
,"examples":{"clear":1}
,"3ffe":{"vpnv6":1}
}
;Search.control.loadWordPairs(pairs);
