var pairs =
{
"loop":{"detection":1,"detected":1}
,"detection":{"loop":1,"enabled":1,"mechanism":1}
,"enabled":{"detect":1}
,"detect":{"routing":1}
,"routing":{"loops":1}
,"loops":{"lsps":1}
,"lsps":{"two":1}
,"two":{"methods":1}
,"methods":{"supported":1}
,"supported":{"loop":1}
,"mechanism":{"hop":1}
,"hop":{"count":1}
,"count":{"during":1,"lsp":1,"incriminated":1,"exceeds":1}
,"during":{"setup":1}
,"setup":{"lsp":1,"messages":1,"process":1}
,"lsp":{"lsp":1,"passes":1,"setup":1,"establishment":1}
,"passes":{"hop":1}
,"messages":{"hop":1,"lsr":1,"ensures":1}
,"incriminated":{"node":1}
,"node":{"router":1}
,"router":{"participating":1}
,"participating":{"lsp":1}
,"establishment":{"hop":1,"adds":1}
,"exceeds":{"maximum":1}
,"maximum":{"configured":1}
,"configured":{"value":1}
,"value":{"lsp":1}
,"process":{"stopped":1}
,"stopped":{"notification":1}
,"notification":{"message":1}
,"message":{"passed":1,"originator":1,"sends":1,"back":1}
,"passed":{"back":1,"part":1,"lsp":1}
,"back":{"message":1,"originator":1}
,"originator":{"path":1,"messages":1}
,"path":{"vector":1,"data":1}
,"vector":{"path":1,"contains":1,"lsr":1,"drops":1}
,"contains":{"list":1}
,"list":{"lsr":1}
,"lsr":{"identifiers":1,"participating":1,"identifier":1,"finds":1}
,"identifiers":{"passed":1}
,"part":{"lsp":1}
,"adds":{"lsr":1}
,"identifier":{"path":1}
,"finds":{"identifier":1}
,"drops":{"message":1}
,"sends":{"message":1}
,"ensures":{"loop":1}
,"detected":{"establishing":1}
,"establishing":{"label":1}
,"label":{"switched":1}
,"switched":{"path":1}
,"data":{"passed":1}
}
;Search.control.loadWordPairs(pairs);
