var pairs =
{
"nsm_sr_api_delete_prefix_sid":{"function":1,"(u_int32_t":1}
,"function":{"deletes":1,"syntax":1,"succeeds":1}
,"deletes":{"prefix":1}
,"prefix":{"segment":1}
,"segment":{"identifier":1}
,"identifier":{"(sid)":1,"<0-255>":1,"output":1}
,"(sid)":{"primary":1}
,"primary":{"address":1}
,"address":{"interface":1}
,"interface":{"sid":1,"name":1,"configured":1}
,"sid":{"corresponds":1}
,"corresponds":{"mpls":1}
,"mpls":{"label":1}
,"label":{"prefix-sid":1}
,"prefix-sid":{"value":1}
,"value":{"command":1}
,"command":{"calls":1}
,"calls":{"function":1}
,"syntax":{"int":1}
,"int":{"nsm_sr_api_delete_prefix_sid":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1,"exist":1}
,"char":{"*ifname":1}
,"*ifname":{"u_int32_t":1}
,"u_int32_t":{"sid_value)":1}
,"sid_value)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"identifier":1}
,"<0-255>":{"ifname":1}
,"ifname":{"interface":1,"exist":1}
,"name":{"sid_value":1}
,"sid_value":{"segment":1,"cannot":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_success":1}
,"nsm_success":{"function":1}
,"succeeds":{"nsm_api_set_err_vr_not_exist":1}
,"nsm_api_set_err_vr_not_exist":{"vr_id":1}
,"exist":{"nsm_err_internal":1,"nsm_sr_err_command_not_configured":1}
,"nsm_err_internal":{"internal":1}
,"internal":{"error":1}
,"error":{"nsm_sr_err_invalid_interface":1}
,"nsm_sr_err_invalid_interface":{"ifname":1}
,"nsm_sr_err_command_not_configured":{"interface":1}
,"configured":{"sid_value":1}
,"cannot":{"found":1}
}
;Search.control.loadWordPairs(pairs);
