var pairs =
{
"bridge":{"agreement":1,"(<1-32>":1,"identifier":1}
,"agreement":{"convention":1,"protocol":1,"matching":1,"digest":1}
,"convention":{"command":1,"specifies":1,"default":1,"<1-3>":1,"parameters":1,"identifier":1}
,"command":{"agreement":1,"syntax":1,"mode":1}
,"protocol":{"convention":1}
,"specifies":{"computed":1}
,"computed":{"topology":1}
,"topology":{"digest":1,"information":1}
,"digest":{"determine":1,"match":1,"forward":1,"neighbor":1}
,"determine":{"whether":1}
,"whether":{"neighboring":1}
,"neighboring":{"switch":1}
,"switch":{"operating":1}
,"operating":{"identical":1}
,"identical":{"network":1}
,"network":{"topology":1}
,"information":{"frames":1}
,"frames":{"may":1}
,"may":{"safely":1}
,"safely":{"forwarded":1}
,"forwarded":{"neighbor":1}
,"neighbor":{"form":1,"matches":1}
,"form":{"command":1}
,"default":{"(2)":1,"default":1,"agreement":1}
,"(2)":{"command":1}
,"syntax":{"bridge":1}
,"(<1-32>":{"backbone)":1}
,"backbone)":{"agreement":1}
,"<1-3>":{"bridge":1}
,"parameters":{"<1-32>":1}
,"<1-32>":{"bridge":1}
,"identifier":{"backbone":1,"agreement":1}
,"backbone":{"backbone":1,"bridge":1}
,"matching":{"action":1}
,"action":{"taken":1}
,"taken":{"topology":1}
,"match":{"loop":1}
,"loop":{"free":1}
,"free":{"transmitter":1,"multicast":1}
,"transmitter":{"agreement":1,"forward":1}
,"forward":{"traffic":1,"multicast":1}
,"traffic":{"until":1,"allows":1,"default":1}
,"until":{"topology":1}
,"matches":{"loop":1}
,"multicast":{"transmitter":1,"traffic":1}
,"allows":{"unicast":1}
,"unicast":{"traffic":1}
,"mode":{"spb":1,"example":1}
,"spb":{"mode":1}
,"example":{"(spb-config)":1}
,"(spb-config)":{"bridge":1}
}
;Search.control.loadWordPairs(pairs);
