var pairs =
{
"interface":{"table":1}
,"table":{"rip2ifstatentry":1}
,"rip2ifstatentry":{"attribute":1}
,"attribute":{"syntax":1}
,"syntax":{"access":1}
,"access":{"function":1}
,"function":{"rip2ifstataddress":1}
,"rip2ifstataddress":{"ipaddress":1}
,"ipaddress":{"read-only":1,"read-create":1}
,"read-only":{"rip2_get_if_stat_addr":1,"rip2_get_if_stat_rcv_bad_packets":1,"rip2_get_if_stat_rcv_bad_routes":1,"rip2_get_if_stat_sent_updates":1,"rip2_get_if_conf_address":1}
,"rip2_get_if_stat_addr":{"rip2_get_next_if_stat_addr":1}
,"rip2_get_next_if_stat_addr":{"rip2ifstatrcvbadpackets":1}
,"rip2ifstatrcvbadpackets":{"counter32":1}
,"counter32":{"read-only":1}
,"rip2_get_if_stat_rcv_bad_packets":{"rip2_get_if_stat_rcv_bad_packets":1,"rip2ifstatrcvbadroutes":1}
,"rip2ifstatrcvbadroutes":{"counter32":1}
,"rip2_get_if_stat_rcv_bad_routes":{"rip2_get_next_if_stat_rcv_bad_routes":1}
,"rip2_get_next_if_stat_rcv_bad_routes":{"rip2ifstatsentupdates":1}
,"rip2ifstatsentupdates":{"counter32":1}
,"rip2_get_if_stat_sent_updates":{"rip2_get_next_if_stat_sent_updates":1}
,"rip2_get_next_if_stat_sent_updates":{"rip2ifstatstatus":1}
,"rip2ifstatstatus":{"rowstatus":1}
,"rowstatus":{"read-create":1}
,"read-create":{"rip2_get_if_stat_status":1,"rip2_get_if_conf_domain":1,"rip2_get_if_conf_auth_type":1,"rip2_get_if_conf_auth_key":1,"rip2_get_if_conf_send":1,"rip2_get_if_conf_receive":1,"rip2_get_if_conf_default_metric":1,"rip2_get_if_conf_status":1,"rip2_get_if_conf_src_address":1}
,"rip2_get_if_stat_status":{"rip2_get_next_if_stat_status":1}
,"rip2_get_next_if_stat_status":{"rip2_set_if_stat_status":1}
,"rip2_set_if_stat_status":{"rip2ifconfaddress":1}
,"rip2ifconfaddress":{"ipaddress":1}
,"rip2_get_if_conf_address":{"rip2_get_next_if_conf_address":1}
,"rip2_get_next_if_conf_address":{"rip2ifconfdomain":1}
,"rip2ifconfdomain":{"routetag":1}
,"routetag":{"read-create":1}
,"rip2_get_if_conf_domain":{"rip2_get_next_if_conf_domain":1}
,"rip2_get_next_if_conf_domain":{"rip2_set_if_conf_domain":1}
,"rip2_set_if_conf_domain":{"rip2ifconfauthtype":1}
,"rip2ifconfauthtype":{"integer":1}
,"integer":{"read-create":1}
,"rip2_get_if_conf_auth_type":{"rip2_get_next_if_conf_auth_type":1}
,"rip2_get_next_if_conf_auth_type":{"rip2_set_if_conf_auth_type":1}
,"rip2_set_if_conf_auth_type":{"rip2ifconfauthkey":1}
,"rip2ifconfauthkey":{"octet":1}
,"octet":{"string":1}
,"string":{"read-create":1}
,"rip2_get_if_conf_auth_key":{"rip2_get_next_if_conf_auth_key":1}
,"rip2_get_next_if_conf_auth_key":{"rip2_set_if_conf_auth_key":1}
,"rip2_set_if_conf_auth_key":{"rip2ifconfsend":1}
,"rip2ifconfsend":{"integer":1}
,"rip2_get_if_conf_send":{"rip2_get_next_if_conf_send":1}
,"rip2_get_next_if_conf_send":{"rip2_set_if_conf_send":1}
,"rip2_set_if_conf_send":{"rip2ifconfreceive":1}
,"rip2ifconfreceive":{"integer":1}
,"rip2_get_if_conf_receive":{"rip2_get_next_if_conf_receive":1}
,"rip2_get_next_if_conf_receive":{"rip2_set_if_conf_receive":1}
,"rip2_set_if_conf_receive":{"rip2ifconfdefaultmetric":1}
,"rip2ifconfdefaultmetric":{"integer":1}
,"rip2_get_if_conf_default_metric":{"rip2_get_next_if_conf_default_metric":1}
,"rip2_get_next_if_conf_default_metric":{"rip2_get_next_if_conf_default_metric":1,"rip2ifconfstatus":1}
,"rip2ifconfstatus":{"rowstatus":1}
,"rip2_get_if_conf_status":{"rip2_get_next_if_conf_status":1}
,"rip2_get_next_if_conf_status":{"rip2_set_if_conf_status":1}
,"rip2_set_if_conf_status":{"rip2ifconfsrcaddress":1}
,"rip2ifconfsrcaddress":{"ipaddress":1}
,"rip2_get_if_conf_src_address":{"rip2_get_next_if_conf_src_address":1}
,"rip2_get_next_if_conf_src_address":{"rip2_set_if_conf_src_address":1}
}
;Search.control.loadWordPairs(pairs);
