var pairs =
{
"ospf6_set_area_aggregate_status":{"function":1,"(char":1}
,"function":{"sets":1,"fails":1,"succeeds":1}
,"sets":{"status":1}
,"status":{"whether":1,"status":1,"aggregate":1}
,"whether":{"management":1}
,"management":{"table":1}
,"table":{"permitted":1}
,"permitted":{"facilitating":1}
,"facilitating":{"actions":1}
,"actions":{"row":1}
,"row":{"creation":1,"row_status_createandwait":1,"wait":1,"output":1}
,"creation":{"construction":1}
,"construction":{"destruction":1}
,"destruction":{"syntax":1}
,"syntax":{"iint":1}
,"iint":{"ospf6_set_area_aggregate_status":1}
,"(char":{"*tag":1}
,"*tag":{"struct":1}
,"struct":{"pal_in4_addr":1,"pal_in6_addr":1}
,"pal_in4_addr":{"area_id":1}
,"area_id":{"int":1,"area":1}
,"int":{"area_lsdb_type":1,"prefix_type":1,"prefix_len":1}
,"area_lsdb_type":{"int":1,"area":1}
,"prefix_type":{"struct":1,"prefix":1}
,"pal_in6_addr":{"prefix":1}
,"prefix":{"int":1,"type":1,"ipv6":1,"prefix_len":1,"(in":1,"shorter":1}
,"prefix_len":{"u_int32_t":1,"length":1}
,"u_int32_t":{"status)":1}
,"status)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"tag":1,"none":1}
,"tag":{"ospfv3":1,"area_id":1}
,"ospfv3":{"process":1}
,"process":{"tag":1,"exist":1}
,"area":{"identifier":1,"lsdb":1,"backbone":1}
,"identifier":{"ipv4":1}
,"ipv4":{"address":1}
,"address":{"format":1,"aggregate":1,"exist":1}
,"format":{"area_lsdb_type":1}
,"lsdb":{"type":1}
,"type":{"given":1,"ospfv3areaaggregateprefix":1}
,"given":{"address":1}
,"aggregate":{"applies":1,"row_status_active":1}
,"applies":{"prefix_type":1}
,"ospfv3areaaggregateprefix":{"object":1}
,"object":{"prefix":1}
,"ipv6":{"prefix":1}
,"length":{"prefix":1}
,"(in":{"bits)":1}
,"bits)":{"prefix":1}
,"shorter":{"bits":1}
,"bits":{"status":1}
,"row_status_active":{"active":1}
,"active":{"row_status_notinservice":1,"row":1}
,"row_status_notinservice":{"service":1}
,"service":{"row_status_notready":1}
,"row_status_notready":{"ready":1}
,"ready":{"row_status_createandgo":1}
,"row_status_createandgo":{"create":1}
,"create":{"active":1,"row":1}
,"row_status_createandwait":{"create":1}
,"wait":{"state":1}
,"state":{"row_status_destroy":1}
,"row_status_destroy":{"delete":1}
,"delete":{"row":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"ospf6_api_set_error":1}
,"ospf6_api_set_error":{"function":1}
,"fails":{"ospf6_api_set_success":1}
,"ospf6_api_set_success":{"function":1}
,"succeeds":{"ospf6_api_set_err_vr_not_exist":1}
,"ospf6_api_set_err_vr_not_exist":{"virtual":1}
,"virtual":{"router":1}
,"router":{"exist":1}
,"exist":{"ospf6_api_set_err_area_is_backbone":1,"ospf6_api_set_err_process_not_exist":1,"ospf6_api_set_err_summary_address_not_exist":1}
,"ospf6_api_set_err_area_is_backbone":{"specified":1}
,"specified":{"area":1,"process":1}
,"backbone":{"ospf6_api_set_err_vr_not_exist":1}
,"ospf6_api_set_err_process_not_exist":{"specified":1}
,"ospf6_api_set_err_summary_address_not_exist":{"summary":1}
,"summary":{"address":1}
}
;Search.control.loadWordPairs(pairs);
