var pairs =
{
"nsm_qos_serv_clean_for":{"function":1,"(struct":1}
,"function":{"cleans":1}
,"cleans":{"protocols":1}
,"protocols":{"ifindex":1}
,"ifindex":{"zero":1,"interface":1}
,"zero":{"clean":1}
,"clean":{"affected":1,"indicated":1}
,"affected":{"interfaces":1}
,"interfaces":{"otherwise":1}
,"otherwise":{"clean":1}
,"indicated":{"interface":1}
,"interface":{"syntax":1,"index":1}
,"syntax":{"void":1}
,"void":{"nsm_qos_serv_clean_for":1}
,"(struct":{"nsm_master":1}
,"nsm_master":{"*nm":1}
,"*nm":{"u_char":1}
,"u_char":{"protocol":1}
,"protocol":{"u_int32_t":1,"protocol":1,"ifindex":1}
,"u_int32_t":{"ifindex)":1}
,"ifindex)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"pointer":1,"none":1}
,"pointer":{"nsm":1}
,"nsm":{"master":1}
,"master":{"structure":1}
,"structure":{"protocol":1}
,"index":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"none":1}
}
;Search.control.loadWordPairs(pairs);
