var pairs =
{
"ospf6_frr_tie_break_prority_set":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"called":1,"succeeds":1}
,"sets":{"unsets":1}
,"unsets":{"priority":1}
,"priority":{"type":1,"<1-4>":1,"repair":1,"value":1,"default":1}
,"type":{"fast":1,"repair":1,"specified":1}
,"fast":{"reroute":1}
,"reroute":{"repair":1}
,"repair":{"path":1,"paths":1}
,"path":{"function":1,"constants":1,"selected":1,"interface_disjoint":1,"protected":1,"different":1,"computed":1,"next-hop":1,"type":1,"priority":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"(no)":1}
,"(no)":{"fast-reroute":1}
,"fast-reroute":{"tie-break":1}
,"tie-break":{"<protection-type>":1}
,"<protection-type>":{"index":1}
,"index":{"<1-4>":1,"bool_t":1,"tiebreak":1,"ospf6_frr_tie_break_unset":1}
,"<1-4>":{"default":1,"lower":1}
,"default":{"priorities":1,"value":1}
,"priorities":{"primary_path":1}
,"primary_path":{"interface_disoint":1,"multiple":1}
,"interface_disoint":{"node_protecting":1}
,"node_protecting":{"broadcast_interface_disjoint":1,"bypass":1}
,"broadcast_interface_disjoint":{"syntax":1,"interface":1}
,"syntax":{"ospf6_frr_tie_break_prority_set":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char*tag":1,"virtual":1}
,"char*tag":{"enum":1}
,"enum":{"ospf6_frr_pref":1}
,"ospf6_frr_pref":{"val":1}
,"val":{"u_int32_t":1,"type":1,"default":1}
,"u_int32_t":{"index":1}
,"bool_t":{"isset)":1}
,"isset)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"protect":1,"next":1,"protected":1,"found":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"tag":1}
,"tag":{"osfv3":1,"val":1,"cannot":1}
,"osfv3":{"process":1}
,"process":{"tag":1}
,"constants":{"ospf6d\u002Fospf6d.h":1,"ospf6d\u002Fospf6_api.h":1}
,"ospf6d\u002Fospf6d.h":{"primary_path":1}
,"multiple":{"loop-free":1}
,"loop-free":{"alternate":1}
,"alternate":{"paths":1,"next":1}
,"paths":{"primary":1,"protect":1}
,"primary":{"path":1,"gateway":1}
,"selected":{"frr":1}
,"frr":{"node-protecting":1}
,"node-protecting":{"link-protecting":1}
,"link-protecting":{"node_protecting":1}
,"bypass":{"primary-path":1}
,"primary-path":{"gateway":1}
,"gateway":{"router":1,"fails":1}
,"protect":{"router":1,"links":1}
,"next":{"hop":1}
,"hop":{"primary":1,"rerouting":1}
,"interface_disjoint":{"select":1}
,"select":{"point-to-point":1}
,"point-to-point":{"interfaces":1}
,"interfaces":{"alternate":1,"however":1,"repair":1}
,"rerouting":{"primary":1}
,"fails":{"thus":1}
,"thus":{"protecting":1}
,"protecting":{"interface":1}
,"interface":{"broadcast_interface_disjoint":1,"connected":1,"primary":1}
,"connected":{"broadcast":1}
,"broadcast":{"network":1,"interfaces":1}
,"network":{"repair":1}
,"links":{"repair":1}
,"protected":{"primary":1,"link":1}
,"different":{"next-hop":1,"router":1,"value":1}
,"next-hop":{"interfaces":1,"gateways":1}
,"however":{"broadcast":1}
,"computed":{"via":1}
,"via":{"interface":1}
,"gateways":{"different":1}
,"link":{"index":1}
,"tiebreak":{"priority":1}
,"lower":{"value":1}
,"value":{"higher":1,"different":1,"constants":1,"specified":1,"output":1,"ospf6_api_set_err_vr_not_exist":1}
,"higher":{"preference":1}
,"preference":{"isset":1}
,"isset":{"whether":1}
,"whether":{"priority":1}
,"specified":{"val":1,"index":1}
,"ospf6d\u002Fospf6_api.h":{"ospf6_frr_tie_break_set":1}
,"ospf6_frr_tie_break_set":{"repair":1}
,"ospf6_frr_tie_break_unset":{"repair":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"ospf6_api_set_err_vr_not_exist":{"virtual":1}
,"found":{"ospf6_api_set_err_process_not_exist":1,"ospf6_api_set_success":1}
,"ospf6_api_set_err_process_not_exist":{"tag":1}
,"cannot":{"found":1}
,"ospf6_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
