var pairs =
{
"show":{"vlan":1}
,"vlan":{"classifier":1,"group":1}
,"classifier":{"command":1,"groups":1,"rules":1,"rule":1,"group":1,"interface":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"information":1}
,"information":{"configured":1,"<1-16>":1,"interface":1,"group":1,"command":1}
,"configured":{"vlan":1}
,"groups":{"interfaces":1,"configured":1,"vlan":1,"show":1}
,"interfaces":{"configured":1,"vlan":1}
,"group":{"groups":1,"rule":1,"interface":1,"(<1-16>":1,"displays":1,"activated":1,"information":1,"vlan":1,"add":1,"show":1}
,"rules":{"either":1,"shown":1}
,"either":{"group":1}
,"rule":{"specified":1,"shown":1,"(<1-256>":1,"displays":1,"<1-256>":1,"information":1,"example":1,"show":1,"vlan":1}
,"specified":{"configured":1,"specific":1}
,"shown":{"either":1,"command":1}
,"specific":{"configured":1}
,"syntax":{"show":1}
,"interface":{"ifname":1,"displays":1,"information":1,"group":1,"fe2":1,"fe3":1,"fe5":1,"fe7":1}
,"ifname":{"show":1}
,"(<1-16>":{"show":1}
,"(<1-256>":{"parameters":1}
,"parameters":{"group":1}
,"displays":{"group":1,"interface":1,"vlan":1,"rule":1,"groups":1,"interfaces":1}
,"activated":{"information":1}
,"<1-16>":{"displays":1}
,"<1-256>":{"displays":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"example":1,"displays":1}
,"add":{"rule":1}
,"fe2":{"vlan":1}
,"fe3":{"vlan":1,"example":1}
,"fe5":{"vlan":1}
,"fe7":{"example":1}
}
;Search.control.loadWordPairs(pairs);
