var pairs =
{
"message-ack":{"command":1,"message-ack":1,"parameters":1,"(config)":1}
,"command":{"enable":1,"disable":1,"syntax":1,"mode":1}
,"enable":{"message":1}
,"message":{"acknowledgement":1}
,"acknowledgement":{"messages":1,"disabled":1}
,"messages":{"sent":1}
,"sent":{"neighbors":1}
,"neighbors":{"known":1,"command":1}
,"known":{"support":1}
,"support":{"refresh":1}
,"refresh":{"reduction":1}
,"reduction":{"parameter":1}
,"parameter":{"command":1}
,"disable":{"message":1}
,"syntax":{"message-ack":1}
,"parameters":{"none":1}
,"none":{"default":1}
,"default":{"message":1,"command":1}
,"disabled":{"default":1}
,"mode":{"router":1,"examples":1}
,"router":{"mode":1,"rsvp":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"rsvp":{"(config-router)":1}
,"(config-router)":{"message-ack":1}
}
;Search.control.loadWordPairs(pairs);
