var pairs =
{
"configure":{"terminal":1,"mode":1,"routing":1,"(config-if)":1}
,"terminal":{"enter":1}
,"enter":{"configure":1}
,"mode":{"(config)":1,"return":1}
,"(config)":{"router":1,"interface":1}
,"router":{"ospf":1,"mode":1}
,"ospf":{"100":1,"runs":1,"message-digest-key":1,"authentication":1,"packet":1,"authentication-key":1}
,"100":{"configure":1}
,"routing":{"process":1}
,"process":{"specify":1,"(100)":1,"unique":1,"(config-router)":1}
,"specify":{"process":1,"interface":1,"ospf":1}
,"(100)":{"process":1}
,"unique":{"positive":1}
,"positive":{"integer":1}
,"integer":{"identifying":1}
,"identifying":{"routing":1}
,"(config-router)":{"network":1,"area":1,"exit":1}
,"network":{"10.10.10.0\u002F24":1,"10.10.11.0\u002F24":1}
,"10.10.10.0\u002F24":{"area":1}
,"area":{"(config-router)":1,"define":1,"(0)":1,"authentication":1}
,"10.10.11.0\u002F24":{"area":1}
,"define":{"interfaces":1}
,"interfaces":{"ospf":1}
,"runs":{"associate":1}
,"associate":{"area":1}
,"(0)":{"interface":1}
,"interface":{"(area":1,"eth0":1,"(eth0)":1,"mode":1,"eth1":1,"(eth2)":1,"(eth1)":1}
,"(area":{"specifies":1}
,"specifies":{"backbone":1}
,"backbone":{"area)":1}
,"area)":{"(config-router)":1}
,"authentication":{"message-digest":1,"area":1,"key":1,"enable":1,"current":1,"password":1}
,"message-digest":{"enable":1}
,"enable":{"md5":1,"ospf":1}
,"md5":{"authentication":1,"test":1,"key":1}
,"exit":{"exit":1,"router":1,"interface":1}
,"return":{"configure":1}
,"eth0":{"specify":1}
,"(eth0)":{"configure":1}
,"(config-if)":{"ospf":1,"exit":1}
,"message-digest-key":{"md5":1}
,"test":{"register":1,"ospf":1,"specify":1,"neighboring":1}
,"register":{"md5":1}
,"key":{"test":1,"(config-if)":1}
,"eth1":{"specify":1}
,"(eth2)":{"configure":1}
,"packet":{"text":1}
,"text":{"authentication":1}
,"current":{"interface":1}
,"(eth1)":{"(config-if)":1}
,"authentication-key":{"test":1}
,"password":{"test":1}
,"neighboring":{"routers":1}
}
;Search.control.loadWordPairs(pairs);
