var pairs =
{
"no-refresh-resv-parsing":{"command":1,"parameters":1}
,"command":{"disable":1,"minimize":1,"syntax":1,"mode":1}
,"disable":{"parsing":1}
,"parsing":{"refresh":1,"enabled":1}
,"refresh":{"resv":1,"reservation":1}
,"resv":{"messages":1}
,"messages":{"received":1,"check":1}
,"received":{"upstream":1}
,"upstream":{"nodes":1}
,"nodes":{"enable":1}
,"enable":{"command":1}
,"minimize":{"message":1}
,"message":{"processing":1}
,"processing":{"rsvp":1}
,"rsvp":{"sure":1,"router":1}
,"sure":{"particular":1}
,"particular":{"router":1}
,"router":{"need":1,"required":1,"mode":1,"configure":1,"(config)":1,"rsvp":1,"(config-router)":1}
,"need":{"parse":1}
,"parse":{"refresh":1}
,"check":{"changes":1}
,"changes":{"lsps":1}
,"lsps":{"passing":1}
,"passing":{"router":1}
,"required":{"updated":1}
,"updated":{"simultaneously":1}
,"simultaneously":{"command":1}
,"syntax":{"no-refresh-resv-parsing":1}
,"parameters":{"none":1}
,"none":{"default":1}
,"default":{"refresh":1}
,"reservation":{"parsing":1}
,"enabled":{"command":1}
,"mode":{"router":1,"example":1}
,"example":{"router":1}
,"configure":{"terminal":1}
,"terminal":{"router":1}
,"(config)":{"router":1}
,"(config-router)":{"no-refresh-resv-parsing":1}
}
;Search.control.loadWordPairs(pairs);
