var pairs =
{
"cli":{"structure":1,"elements":1,"functions":1,"element":1,"index_sub":1,"mode":1,"status":1,"tree":1,"count":1,"command":1,"{\u002F*cli":1,"*\u002Fvoid":1,"int":1,"s_int32_t":1}
,"structure":{"contains":1}
,"contains":{"cli":1}
,"elements":{"used":1}
,"used":{"cli":1,"cli_out":1,"imi":1}
,"functions":{"defined":1}
,"defined":{"lib\u002Fcli.h":1}
,"lib\u002Fcli.h":{"file":1}
,"file":{"member":1}
,"member":{"description":1}
,"description":{"cel":1}
,"cel":{"cli":1}
,"element":{"str":1,"*\u002Fstruct":1}
,"str":{"user":1}
,"user":{"input":1}
,"input":{"string":1,"source":1}
,"string":{"out_func":1,"definition":1,"*\u002Fchar":1,"*\u002Fcfg_vect_t":1}
,"out_func":{"output":1,"\u002F*output":1}
,"output":{"function":1,"function\u0027s":1}
,"function":{"used":1,"cleanup":1,"show_func":1,"type":1,"*\u002Fint":1}
,"cli_out":{"out_val":1,"*\u002Fcli_out_func":1,"message":1}
,"out_val":{"output":1}
,"function\u0027s":{"first":1}
,"first":{"argument":1}
,"argument":{"line":1,"afi":1,"*\u002Fvoid":1}
,"line":{"arbitrary":1,"auth":1,"index":1,"*\u002Fvoid":1,"*\u002Fint":1}
,"arbitrary":{"information":1}
,"information":{"line":1,"self":1,"current":1,"safi":1,"port_range":1}
,"auth":{"authorization":1,"\u002F*input":1}
,"authorization":{"required":1}
,"required":{"source":1,"*\u002Fint":1}
,"source":{"input":1,"line_type":1,"*\u002Fint":1,"define":1}
,"line_type":{"line":1,"int":1}
,"index":{"real":1}
,"real":{"cli":1}
,"index_sub":{"real":1}
,"mode":{"real":1,"\u002F*current":1}
,"status":{"current":1,"flags":1,"*\u002Fenum":1,"\u002F*flags":1}
,"current":{"cli":1,"arbitrary":1,"node":1}
,"flags":{"flags":1,"self":1,"define":1}
,"self":{"arbitrary":1,"privilege":1}
,"privilege":{"privilege":1,"level":1,"struct":1}
,"level":{"ctree":1}
,"ctree":{"cli":1}
,"tree":{"global":1}
,"global":{"variable":1}
,"variable":{"global":1,"lines":1,"*\u002Fstruct":1}
,"lines":{"terminal":1,"\u002F*call":1}
,"terminal":{"length":1}
,"length":{"callback":1,"*\u002Fint":1}
,"callback":{"call":1}
,"call":{"back":1}
,"back":{"function":1}
,"cleanup":{"call":1}
,"show_func":{"call":1}
,"type":{"type":1,"cli":1,"u_int32_t":1}
,"count":{"total":1,"current":1,"void":1}
,"total":{"count":1}
,"node":{"arg":1}
,"arg":{"look":1}
,"look":{"argument":1}
,"afi":{"address":1,"safi_t":1}
,"address":{"family":1}
,"family":{"information":1}
,"safi":{"specific":1,"ifdef":1}
,"specific":{"address":1}
,"port_range":{"layer":1,"endif":1}
,"layer":{"handling":1}
,"handling":{"vector":1,"*\u002Fu_int64_t":1}
,"vector":{"used":1}
,"imi":{"encode":1}
,"encode":{"single":1}
,"single":{"cli":1}
,"command":{"string":1}
,"definition":{"struct":1}
,"struct":{"cli":1,"cli_tree":1,"ipi_vr":1}
,"{\u002F*cli":{"element":1}
,"*\u002Fstruct":{"cli_element":1,"lib_globals":1}
,"cli_element":{"*cel":1}
,"*cel":{"\u002F*user":1}
,"\u002F*user":{"input":1}
,"*\u002Fchar":{"*str":1,"*out_snoop_buf":1}
,"*str":{"\u002F*output":1}
,"\u002F*output":{"function":1,"function\u0027s":1}
,"*\u002Fcli_out_func":{"out_func":1}
,"*\u002Fvoid":{"*out_val":1,"*line":1,"*index":1}
,"*out_val":{"\u002F*alternate":1}
,"\u002F*alternate":{"storage":1}
,"storage":{"cli_out":1}
,"message":{"*\u002Fchar":1}
,"*out_snoop_buf":{"\u002F*arbitrary":1}
,"\u002F*arbitrary":{"information":1}
,"*line":{"\u002F*auth":1}
,"\u002F*auth":{"required":1}
,"*\u002Fint":{"auth":1,"source":1,"line_type":1,"lines":1,"(*callback)":1}
,"\u002F*input":{"source":1}
,"define":{"cli_source_user":1,"cli_source_file":1,"cli_from_pvr":1}
,"cli_source_user":{"define":1}
,"cli_source_file":{"\u002F*for":1}
,"\u002F*for":{"line":1}
,"int":{"min":1,"max":1,"mode":1,"(*cleanup)":1,"type":1}
,"min":{"int":1}
,"max":{"\u002F*real":1}
,"\u002F*real":{"cli":1}
,"*index":{"void":1}
,"void":{"*index_sub":1,"*self":1,"*current":1,"*arg":1}
,"*index_sub":{"int":1}
,"\u002F*current":{"cli":1}
,"*\u002Fenum":{"{cli_normal":1}
,"{cli_normal":{"cli_close":1}
,"cli_close":{"cli_more":1}
,"cli_more":{"cli_continue":1}
,"cli_continue":{"cli_more_continue":1}
,"cli_more_continue":{"cli_wait":1}
,"cli_wait":{"status":1}
,"\u002F*flags":{"*\u002Fu_char":1}
,"*\u002Fu_char":{"flags":1}
,"cli_from_pvr":{"<<0)":1}
,"<<0)":{"void":1}
,"*self":{"u_char":1}
,"u_char":{"privilege":1}
,"cli_tree":{"*ctree":1}
,"*ctree":{"\u002F*global":1}
,"\u002F*global":{"variable":1}
,"lib_globals":{"*zg":1}
,"*zg":{"struct":1}
,"ipi_vr":{"*vr":1}
,"*vr":{"\u002F*terminal":1}
,"\u002F*terminal":{"length":1}
,"\u002F*call":{"back":1}
,"(*callback)":{"(struct":1}
,"(struct":{"cli":1}
,"(*cleanup)":{"(struct":1}
,"s_int32_t":{"(*show_func)":1}
,"(*show_func)":{"(struct":1}
,"u_int32_t":{"count":1}
,"*current":{"void":1}
,"*arg":{"afi_t":1}
,"afi_t":{"afi":1}
,"safi_t":{"safi":1}
,"ifdef":{"have_custom1":1}
,"have_custom1":{"\u002F*l2":1}
,"\u002F*l2":{"handling":1}
,"*\u002Fu_int64_t":{"port_range":1}
,"endif":{"\u002F*have_custom1":1}
,"\u002F*have_custom1":{"*\u002F\u002F*vector":1}
,"*\u002F\u002F*vector":{"used":1}
,"*\u002Fcfg_vect_t":{"*cv":1}
,"*cv":{"\u002F*parse":1}
,"\u002F*parse":{"result":1}
,"result":{"saved":1}
,"saved":{"non-interactive":1}
,"non-interactive":{"shells":1}
,"shells":{"*\u002Funsigned":1}
,"*\u002Funsigned":{"parse_result":1}
}
;Search.control.loadWordPairs(pairs);
