var pairs =
{
"isis_get_next_circ_level_hello_timer":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"next":1}
,"next":{"isis":1,"level":1}
,"isis":{"circ":1}
,"circ":{"level":1}
,"level":{"hello":1,"lans":1,"used":1,"is-is":1,"index":1,"level":1,"indexlen":1}
,"hello":{"time":1}
,"time":{"period":1}
,"period":{"milliseconds":1,"hellos":1}
,"milliseconds":{"iih":1}
,"iih":{"pdus":1}
,"pdus":{"multiaccess":1}
,"multiaccess":{"networks":1}
,"networks":{"next":1,"level":1}
,"lans":{"value":1}
,"value":{"level":1,"non-vr":1}
,"used":{"period":1}
,"hellos":{"l1l2":1}
,"l1l2":{"point-to-point":1,"point":1}
,"point-to-point":{"circuits":1}
,"circuits":{"syntax":1,"return":1}
,"syntax":{"int":1}
,"int":{"isis_get_next_circ_level_hello_timer":1,"indexlen":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1,"instance":1}
,"u_int32_t":{"*instance":1,"*circindex":1,"*level":1,"*ret)":1}
,"*instance":{"u_int32_t":1}
,"*circindex":{"u_int32_t":1}
,"*level":{"int":1}
,"indexlen":{"u_int32_t":1,"length":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"ret":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"instance":{"is-is":1,"circindex":1}
,"is-is":{"instance":1,"circuit":1,"level":1}
,"circindex":{"is-is":1}
,"circuit":{"index":1}
,"index":{"level":1,"output":1,"found":1,"isis_api_get_error":1}
,"length":{"index":1}
,"output":{"parameters":1}
,"ret":{"period":1}
,"point":{"point":1,"circuits":1}
,"return":{"values":1}
,"values":{"isis_api_get_success":1}
,"isis_api_get_success":{"next":1}
,"found":{"specified":1}
,"specified":{"circuit":1}
,"isis_api_get_error":{"next":1}
}
;Search.control.loadWordPairs(pairs);
