var pairs =
{
"hsl_vlan_port":{"data":1,"{hsl_vid_t":1}
,"data":{"structure":1}
,"structure":{"helps":1}
,"helps":{"manage":1}
,"manage":{"vlan":1}
,"vlan":{"port":1,"identifier":1,"exists":1,"definition":1,"*\u002Fvoid":1}
,"port":{"functions":1}
,"functions":{"defined":1}
,"defined":{"libhsl\u002Fl2\u002Fhsl_vlan.h":1}
,"libhsl\u002Fl2\u002Fhsl_vlan.h":{"type":1}
,"type":{"definition":1}
,"definition":{"hsl_vid_t":1,"struct":1}
,"hsl_vid_t":{"vid":1}
,"vid":{"vlan":1,"\u002F*vlan":1}
,"identifier":{"hsl_avl_tree":1}
,"hsl_avl_tree":{"*port_tree":1,"*vlan_tre":1,"*vlan_tree":1}
,"*port_tree":{"tree":1,"\u002F*tree":1}
,"tree":{"ports":1,"secondary":1}
,"ports":{"vlan":1}
,"exists":{"hsl_avl_tree":1,"*\u002F#":1}
,"*vlan_tre":{"tree":1}
,"secondary":{"vlans":1}
,"vlans":{"attached":1}
,"attached":{"primary":1}
,"primary":{"vlan":1}
,"struct":{"hsl_vlan_port":1,"hsl_avl_tree":1,"hsl_vlan_access_map":1}
,"{hsl_vid_t":{"vid":1}
,"\u002F*vlan":{"*\u002Fstruct":1}
,"*\u002Fstruct":{"hsl_avl_tree":1}
,"\u002F*tree":{"ports":1,"secondary":1}
,"*\u002F#":{"ifdef":1}
,"ifdef":{"have_pvlan":1,"have_l2lern":1}
,"have_pvlan":{"enum":1}
,"enum":{"hal_pvlan_type":1}
,"hal_pvlan_type":{"vlan_type":1}
,"vlan_type":{"struct":1}
,"*vlan_tree":{"\u002F*tree":1}
,"*\u002Fvoid":{"*system_info":1}
,"*system_info":{"endif":1}
,"endif":{"\u002F*have_pvlan":1,"\u002F*have_l2lern":1}
,"\u002F*have_pvlan":{"*\u002F#":1}
,"have_l2lern":{"struct":1}
,"hsl_vlan_access_map":{"*hsl_vacc_map":1}
,"*hsl_vacc_map":{"endif":1}
,"\u002F*have_l2lern":{"*\u002F}":1}
}
;Search.control.loadWordPairs(pairs);
