var pairs =
{
"trigger":{"remote":1}
,"remote":{"psc":1,"remote":1,"working":1}
,"psc":{"events":1,"packet":1,"fsm":1}
,"events":{"bfd":1,"follows":1}
,"bfd":{"module":1}
,"module":{"detects":1}
,"detects":{"local":1}
,"local":{"signal":1,"event":1,"local":1,"working":1}
,"signal":{"fail":1}
,"fail":{"clear":1,"event":1}
,"clear":{"signal":1,"reversion":1}
,"event":{"switchover":1,"checked":1,"(signal":1,"clear":1,"psc":1}
,"switchover":{"api":1,"timer":1}
,"api":{"flag":1,"following":1,"invoked":1}
,"flag":{"value":1}
,"value":{"enable":1,"equal":1,"taken":1}
,"enable":{"disable":1}
,"disable":{"invoked":1}
,"invoked":{"api":1,"inform":1}
,"following":{"hold-off":1,"action":1}
,"hold-off":{"timer":1}
,"timer":{"configured":1,"started":1,"local":1,"message":1,"stopped":1,"getting":1,"expiry":1}
,"configured":{"hold-off":1,"value":1}
,"started":{"upon":1,"timeout":1,"configured":1}
,"upon":{"expiration":1}
,"expiration":{"hold-off":1,"timer":1}
,"checked":{"event":1}
,"(signal":{"fail)":1}
,"fail)":{"following":1}
,"action":{"taken":1}
,"taken":{"hal":1,"care":1}
,"hal":{"api":1}
,"inform":{"hsl":1}
,"hsl":{"switchover":1}
,"timeout":{"value":1}
,"equal":{"rapid-transmit":1}
,"rapid-transmit":{"interval":1}
,"interval":{"upon":1}
,"message":{"generator":1,"message":1,"type":1}
,"generator":{"forms":1}
,"forms":{"psc":1}
,"packet":{"send":1}
,"send":{"sink":1}
,"sink":{"mep":1}
,"mep":{"timer":1}
,"stopped":{"once":1,"events":1}
,"once":{"expired":1}
,"expired":{"third":1,"generate":1}
,"third":{"time":1}
,"time":{"control":1}
,"control":{"card":1}
,"card":{"oamd":1}
,"oamd":{"executes":1,"sends":1}
,"executes":{"fsm":1}
,"fsm":{"changes":1,"timer":1}
,"changes":{"state":1}
,"state":{"appropriately":1}
,"appropriately":{"event":1}
,"reversion":{"mode":1}
,"mode":{"protection":1}
,"protection":{"group":1}
,"group":{"revertive":1}
,"revertive":{"wtr":1}
,"wtr":{"timer":1}
,"care":{"psc":1}
,"getting":{"expired":1}
,"generate":{"wtr":1}
,"expiry":{"event":1}
,"follows":{"local":1}
,"working":{"protect":1}
,"protect":{"remote":1,"control":1}
,"sends":{"nsm_msg_mpls_tp_aps":1}
,"nsm_msg_mpls_tp_aps":{"message":1}
,"type":{"oam_nsm_mplstp_aps_event":1}
,"oam_nsm_mplstp_aps_event":{"nsm":1}
}
;Search.control.loadWordPairs(pairs);
