var pairs =
{
"isis_if_retransmit_interval_set":{"call":1,"(u_int32_t":1}
,"call":{"implements":1,"successful":1}
,"implements":{"isis":1}
,"isis":{"retransmit-interval":1}
,"retransmit-interval":{"command":1}
,"command":{"configure":1}
,"configure":{"lsp":1}
,"lsp":{"retransmission":1}
,"retransmission":{"interval":1}
,"interval":{"syntax":1,"interval":1,"value":1,"outside":1}
,"syntax":{"int":1}
,"int":{"isis_if_retransmit_interval_set":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1,"name":1}
,"char":{"*name":1}
,"*name":{"u_int32_t":1}
,"u_int32_t":{"interval)":1}
,"interval)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1,"seconds":1,"isis_api_set_err_vr_not_exist":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"name":{"interface":1,"interval":1,"exist":1,"enabled":1}
,"interface":{"name":1,"given":1}
,"seconds":{"<0-65535>":1}
,"<0-65535>":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"isis_api_set_err_vr_not_exist":{"exist":1}
,"exist":{"isis_api_set_err_invalid_value":1,"isis_api_set_err_if_not_enabled":1}
,"isis_api_set_err_invalid_value":{"given":1}
,"given":{"interval":1,"name":1}
,"outside":{"range":1}
,"range":{"isis_api_set_err_if_not_exist":1}
,"isis_api_set_err_if_not_exist":{"interface":1}
,"isis_api_set_err_if_not_enabled":{"interface":1}
,"enabled":{"is-is":1}
,"is-is":{"isis_api_set_success":1}
,"isis_api_set_success":{"call":1}
}
;Search.control.loadWordPairs(pairs);
