var pairs =
{
"maintenance":{"domains":1,"domain":1}
,"domains":{"five":1,"(md)":1}
,"five":{"distinct":1}
,"distinct":{"categories":1}
,"categories":{"maintenance":1}
,"(md)":{"used":1}
,"used":{"cfm":1}
,"cfm":{"functions":1,"frames":1,"maintenance":1}
,"functions":{"pbb":1,"within":1,"accept":1}
,"pbb":{"service":1,"network":1,"commands":1}
,"service":{"vlan":1,"instance":1}
,"vlan":{"domain":1}
,"domain":{"service":1,"b-vlan":1,"lan":1,"link":1,"s-vlan":1,"backbone":1,"cfm":1,"may":1,"manages":1,"support":1,"provided":1}
,"instance":{"domain":1,"ports":1,"port":1,"cfm":1}
,"b-vlan":{"domain":1,"maintenance":1,"occurs":1}
,"lan":{"links":1,"link":1}
,"links":{"domain":1,"within":1}
,"link":{"level":1,"generated":1}
,"level":{"domain":1,"maintenance":1}
,"s-vlan":{"maintenance":1,"visible":1,"cfm":1}
,"visible":{"within":1}
,"within":{"i-component":1,"pbb":1,"pbbn":1,"single":1,"pip":1}
,"i-component":{"customer":1,"s-vlan":1}
,"customer":{"frames":1,"cfm":1,"backbone":1,"network":1}
,"frames":{"encapsulated":1,"virtual":1,"visible":1,"sent":1}
,"encapsulated":{"customer":1,"along":1,"appear":1}
,"along":{"customer":1}
,"virtual":{"instance":1}
,"ports":{"(vip)":1}
,"(vip)":{"within":1}
,"appear":{"just":1}
,"just":{"data":1}
,"data":{"frame":1}
,"frame":{"within":1,"flow":1}
,"network":{"(pbbn)":1,"port":1}
,"(pbbn)":{"means":1}
,"means":{"activate":1,"command":1}
,"activate":{"cfm":1}
,"pbbn":{"past":1,"i-tag":1,"b-vlan":1,"extend":1,"lan":1,"example":1,"(forming":1}
,"past":{"vip":1}
,"vip":{"service":1,"b-vlan":1}
,"backbone":{"service":1,"port":1}
,"i-tag":{"processed":1}
,"processed":{"i-tags":1,"customer":1}
,"i-tags":{"processed":1}
,"port":{"(cbp)":1,"(pip)":1,"(pnp)":1,"(cnp)":1,"access":1,"trunk":1}
,"(cbp)":{"provider":1}
,"provider":{"instance":1,"network":1}
,"(pip)":{"backbone":1}
,"may":{"extend":1,"optionally":1}
,"extend":{"e-nni":1,"interconnected":1,"outside":1}
,"e-nni":{"boundaries":1}
,"boundaries":{"eight":1,"pbbn":1}
,"eight":{"levels":1}
,"levels":{"extend":1}
,"interconnected":{"pbbns":1}
,"pbbns":{"until":1,"(cbp-to-cbp":1}
,"until":{"terminate":1}
,"terminate":{"vip":1}
,"manages":{"b-vlans":1}
,"b-vlans":{"within":1}
,"single":{"pbbn":1}
,"occurs":{"once":1}
,"once":{"pbbn":1}
,"outside":{"boundaries":1}
,"example":{"provider":1}
,"(pnp)":{"cbp":1}
,"cbp":{"pip":1,"two":1,"pnp":1}
,"pip":{"cbp":1}
,"two":{"pbbns":1}
,"(cbp-to-cbp":{"pip-to-cbp)":1}
,"pip-to-cbp)":{"enter":1}
,"enter":{"exit":1}
,"exit":{"pbbn":1}
,"(forming":{"cnp)":1}
,"cnp)":{"may":1}
,"optionally":{"monitored":1}
,"monitored":{"lan":1}
,"generated":{"terminated":1}
,"terminated":{"within":1}
,"pnp":{"customer":1}
,"(cnp)":{"link":1}
,"support":{"link-level":1}
,"link-level":{"maintenance":1,"defined":1,"frame":1,"mep":1}
,"provided":{"extension":1}
,"extension":{"link-level":1}
,"defined":{"chapter":1}
,"chapter":{"connectivity":1}
,"connectivity":{"fault":1}
,"fault":{"management":1}
,"management":{"pbb":1,"untagged":1}
,"commands":{"functions":1}
,"accept":{"either":1}
,"either":{"isid":1}
,"isid":{"vid":1,"equal":1}
,"vid":{"passed":1,"equal":1}
,"passed":{"operator":1}
,"operator":{"means":1}
,"command":{"pass":1}
,"pass":{"vid":1}
,"equal":{"isid":1,"(vid=0":1}
,"(vid=0":{"isid=0)":1}
,"isid=0)":{"subsequently":1}
,"subsequently":{"identified":1}
,"identified":{"based":1}
,"based":{"md-type":1}
,"md-type":{"determined":1}
,"determined":{"whether":1}
,"whether":{"domain-type":1,"port":1}
,"domain-type":{"link-level":1}
,"flow":{"allowances":1}
,"allowances":{"sending":1}
,"sending":{"receiving":1}
,"receiving":{"implemented":1}
,"implemented":{"link-level":1}
,"mep":{"described":1}
,"described":{"chapter":1}
,"untagged":{"frames":1}
,"sent":{"received":1}
,"received":{"irrespective":1}
,"irrespective":{"whether":1}
,"access":{"port":1}
,"trunk":{"port":1}
}
;Search.control.loadWordPairs(pairs);
