var pairs =
{
"isis_get_next_is_adj_extended_circ_id":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"next":1}
,"next":{"four-byte":1,"adjacent":1}
,"four-byte":{"extended":1}
,"extended":{"circuit":1}
,"circuit":{"learned":1,"index":1,"isis_api_get_error":1}
,"learned":{"neighbor":1}
,"neighbor":{"during":1}
,"during":{"3-way":1}
,"3-way":{"handshake":1}
,"handshake":{"syntax":1,"output":1}
,"syntax":{"int":1}
,"int":{"isis_get_next_is_adj_extended_circ_id":1,"indexlen":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1,"instance":1}
,"u_int32_t":{"*instance":1,"*circindex":1,"*adjindex":1,"*ret)":1}
,"*instance":{"u_int32_t":1}
,"*circindex":{"u_int32_t":1}
,"*adjindex":{"int":1}
,"indexlen":{"u_int32_t":1,"length":1}
,"*ret)":{"input":1}
,"input":{"parameter":1}
,"parameter":{"vr_id":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1,"isis_api_get_success":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"instance":{"is-is":1,"circindex":1}
,"is-is":{"instance":1,"circuit":1,"adjacent":1}
,"circindex":{"is-is":1}
,"index":{"adjindex":1,"indexlen":1,"output":1,"found":1}
,"adjindex":{"is-is":1}
,"adjacent":{"index":1}
,"length":{"index":1}
,"output":{"parameters":1,"always":1}
,"parameters":{"ret":1}
,"ret":{"four-byte":1}
,"always":{"return":1}
,"return":{"value":1}
,"isis_api_get_success":{"next":1}
,"found":{"specified":1}
,"specified":{"circuit":1}
,"isis_api_get_error":{"next":1}
}
;Search.control.loadWordPairs(pairs);
