var pairs =
{
"cfm_add_ma":{"function":1,"(struct":1}
,"function":{"adds":1,"succeeds":1}
,"adds":{"maintenance":1}
,"maintenance":{"association":1,"domain":1}
,"association":{"(ma)":1}
,"(ma)":{"maintenance":1}
,"domain":{"(md)":1}
,"(md)":{"syntax":1}
,"syntax":{"include":1}
,"include":{"cfm_api.h":1}
,"cfm_api.h":{"s_int32_t":1}
,"s_int32_t":{"cfm_add_ma":1}
,"(struct":{"cfm_md":1}
,"cfm_md":{"*md":1}
,"*md":{"u_char":1}
,"u_char":{"*ma_name":1}
,"*ma_name":{"u_int16_t":1}
,"u_int16_t":{"vid":1}
,"vid":{"u_int8_t":1,"vlan":1,"cfm_def_mhf_default":1,"bridge":1,"pass":1,"configured":1,"cfm_api_err_ma_exists":1}
,"u_int8_t":{"mip_permission":1,"ma_name_type)":1}
,"mip_permission":{"u_int8_t":1,"following":1}
,"ma_name_type)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"pointer":1,"none":1}
,"pointer":{"ma_name":1}
,"ma_name":{"name":1}
,"name":{"vid":1,"following":1,"cfm_ma_char_string":1,"cfm_ma_two_octet_interger":1,"<0-65535>":1,"output":1,"valid":1}
,"vlan":{"<1-4094>":1,"name":1,"configured":1,"already":1}
,"<1-4094>":{"mip_permission":1}
,"following":{"values":1}
,"values":{"cfm_mhf_creation":1,"onmd\u002Fcfm\u002Fcfmd.h":1,"cfm_api_err_internal":1}
,"cfm_mhf_creation":{"enum":1}
,"enum":{"onmd\u002Fcfm\u002Fcfmd.h":1}
,"onmd\u002Fcfm\u002Fcfmd.h":{"cfm_def_mhf_none":1,"cfm_ma_primary_vid":1}
,"cfm_def_mhf_none":{"mhfs":1}
,"mhfs":{"created":1,"controlled":1}
,"created":{"vid":1,"lower":1}
,"cfm_def_mhf_default":{"mhfs":1}
,"bridge":{"port":1,"ports":1}
,"port":{"vid":1}
,"pass":{"cfm_def_mhf_explicit":1,"mep":1}
,"cfm_def_mhf_explicit":{"mhfs":1}
,"ports":{"vid":1}
,"mep":{"created":1}
,"lower":{"level":1}
,"level":{"cfm_def_mhf_defer":1}
,"cfm_def_mhf_defer":{"creation":1}
,"creation":{"mhfs":1}
,"controlled":{"variable":1}
,"variable":{"dot1agcfmmacompmhfcreation":1}
,"dot1agcfmmacompmhfcreation":{"ma_name_type":1}
,"ma_name_type":{"format":1}
,"format":{"name":1}
,"cfm_ma_primary_vid":{"primary":1}
,"primary":{"vlan":1}
,"cfm_ma_char_string":{"string":1}
,"string":{"name":1}
,"cfm_ma_two_octet_interger":{"integer":1}
,"integer":{"name":1}
,"<0-65535>":{"cfm_ma_rfc_2685_vpn_id":1}
,"cfm_ma_rfc_2685_vpn_id":{"vpn":1}
,"vpn":{"name":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"cfm_api_err_internal":{"exist":1}
,"exist":{"cfm_api_err_vlan_not_found":1}
,"cfm_api_err_vlan_not_found":{"vlan":1}
,"configured":{"cfm_api_err_vid_configured_for_vlan":1,"secondary":1,"cfm_api_err_ma_exists":1}
,"cfm_api_err_vid_configured_for_vlan":{"vid":1}
,"secondary":{"vid":1}
,"cfm_api_err_ma_exists":{"vlan":1,"already":1}
,"already":{"configured":1,"exists":1}
,"exists":{"cfm_api_err_mem":1}
,"cfm_api_err_mem":{"memory":1}
,"memory":{"allocation":1}
,"allocation":{"fails":1}
,"fails":{"cfm_api_err_invalid_ma_name_length":1,"cfm_api_err_none":1}
,"cfm_api_err_invalid_ma_name_length":{"length":1}
,"length":{"name":1}
,"valid":{"cfm_api_err_invalid_ma_name_type":1,"cfm_api_err_invalid_ma_name":1,"cfm_api_err_hw_failure":1}
,"cfm_api_err_invalid_ma_name_type":{"type":1}
,"type":{"name":1}
,"cfm_api_err_invalid_ma_name":{"name":1}
,"cfm_api_err_hw_failure":{"hardware":1}
,"hardware":{"fails":1}
,"cfm_api_err_none":{"function":1}
}
;Search.control.loadWordPairs(pairs);
