var pairs =
{
"rsvp":{"hello-timeout":1,"node":1}
,"hello-timeout":{"command":1,"<1-65535>":1,"parameters":1,"value":1,"550":1}
,"command":{"determines":1,"used":1,"applies":1,"syntax":1,"mode":1}
,"determines":{"long":1}
,"long":{"rsvp":1}
,"node":{"wait":1}
,"wait":{"hello":1}
,"hello":{"message":1,"timeout":1}
,"message":{"declaring":1,"peer":1,"seconds":1}
,"declaring":{"neighbor":1}
,"neighbor":{"down":1}
,"down":{"lsr":1}
,"lsr":{"received":1,"resets":1}
,"received":{"hello":1}
,"peer":{"connected":1,"interface-specific":1}
,"connected":{"interface":1}
,"interface":{"within":1,"mode":1,"eth0":1}
,"within":{"specified":1}
,"specified":{"duration":1}
,"duration":{"lsr":1}
,"resets":{"sessions":1}
,"sessions":{"shared":1}
,"shared":{"particular":1}
,"particular":{"peer":1}
,"interface-specific":{"command":1}
,"used":{"global":1}
,"global":{"hello-timeout":1}
,"applies":{"parameter":1}
,"parameter":{"revert":1}
,"revert":{"default":1}
,"default":{"hello":1,"default":1,"hello-timeout":1}
,"timeout":{"value":1}
,"value":{"command":1,"seconds":1}
,"syntax":{"rsvp":1}
,"<1-65535>":{"rsvp":1,"time":1}
,"parameters":{"<1-65535>":1}
,"time":{"receive":1}
,"receive":{"hello":1}
,"seconds":{"default":1,"command":1}
,"mode":{"interface":1,"examples":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"rsvp":1}
,"550":{"(config)":1}
}
;Search.control.loadWordPairs(pairs);
