var pairs =
{
"hardware":{"callbacks":1,"fib":1,"hw_prefix_add_exception":1,"packets":1,"hw_nh_add":1,"hw_nh_delete":1,"hw_nh_hit":1,"hw_add_connected_route":1,"hw_delete_connected_route":1,"hw_get_max_multipath":1}
,"callbacks":{"following":1,"callback":1}
,"following":{"table":1}
,"table":{"displays":1}
,"displays":{"hardware":1}
,"callback":{"description":1}
,"description":{"hw_fib_init":1}
,"hw_fib_init":{"initialize":1}
,"initialize":{"hardware":1}
,"fib":{"hw_fib_deinit":1,"hw_fib_dump":1,"entries":1}
,"hw_fib_deinit":{"de-initialize":1}
,"de-initialize":{"hardware":1}
,"hw_fib_dump":{"show":1}
,"show":{"hardware":1}
,"entries":{"hw_prefix_add":1}
,"hw_prefix_add":{"add":1}
,"add":{"prefix":1,"exception":1,"next":1,"ipv4":1}
,"prefix":{"hardware":1,"trapped":1}
,"hw_prefix_add_exception":{"add":1}
,"exception":{"prefix":1}
,"packets":{"matching":1}
,"matching":{"prefix":1}
,"trapped":{"cpu":1}
,"cpu":{"hw_prefix_delete":1}
,"hw_prefix_delete":{"delete":1}
,"delete":{"prefix":1,"next":1,"ipv4":1}
,"hw_nh_add":{"add":1}
,"next":{"hop":1}
,"hop":{"hardware":1}
,"hw_nh_delete":{"delete":1}
,"hw_nh_hit":{"check":1}
,"check":{"next-hop":1}
,"next-hop":{"usage":1}
,"usage":{"hardware":1}
,"hw_add_connected_route":{"add":1}
,"ipv4":{"connected":1}
,"connected":{"route":1,"hardware":1}
,"route":{"hardware":1}
,"hw_delete_connected_route":{"delete":1}
,"hw_get_max_multipath":{"maximum":1}
,"maximum":{"number":1}
,"number":{"multipaths":1}
,"multipaths":{"hardware":1}
}
;Search.control.loadWordPairs(pairs);
