var pairs =
{
"features":{"bfd":1,"low-overhead":1}
,"bfd":{"provides":1,"irrespective":1,"packet-sending":1,"graceful-restart":1,"timers":1,"maintains":1,"state":1}
,"provides":{"following":1}
,"following":{"features":1}
,"low-overhead":{"short-duration":1}
,"short-duration":{"detection":1}
,"detection":{"failures":1,"communication":1,"required":1,"detached":1,"times":1}
,"failures":{"along":1,"adjacent":1}
,"along":{"path":1}
,"path":{"adjacent":1}
,"adjacent":{"forwarding":1,"systems":1}
,"forwarding":{"engines":1,"plane":1}
,"engines":{"rapid":1,"themselves":1}
,"rapid":{"detection":1}
,"communication":{"failures":1}
,"systems":{"quickly":1}
,"quickly":{"establish":1}
,"establish":{"alternative":1}
,"alternative":{"paths":1}
,"paths":{"single":1}
,"single":{"mechanism":1}
,"mechanism":{"detect":1}
,"detect":{"liveliness":1,"forwarding":1}
,"liveliness":{"media":1,"static":1}
,"media":{"protocol":1}
,"protocol":{"layer":1,"next":1,"modules":1,"module":1,"undergoes":1}
,"layer":{"passive":1}
,"passive":{"active":1}
,"active":{"synchronous":1}
,"synchronous":{"asynchronous":1}
,"asynchronous":{"demand":1}
,"demand":{"modes":1}
,"modes":{"operation":1}
,"operation":{"improved":1}
,"improved":{"system":1}
,"system":{"performance":1}
,"performance":{"faster":1}
,"faster":{"detection":1,"mechanism":1}
,"required":{"data-plane":1}
,"data-plane":{"reachability":1}
,"reachability":{"detection":1,"protocol":1}
,"detached":{"control-plane":1}
,"control-plane":{"functionality":1}
,"functionality":{"sub-second":1}
,"sub-second":{"detection":1}
,"times":{"similar":1}
,"similar":{"provided":1}
,"provided":{"sonet\u002Fsdh":1}
,"sonet\u002Fsdh":{"networks":1}
,"networks":{"separate":1}
,"separate":{"process":1}
,"process":{"zebos-xp":1}
,"zebos-xp":{"works":1}
,"works":{"conjunction":1}
,"conjunction":{"routing":1}
,"routing":{"protocols":1}
,"protocols":{"nsm":1}
,"nsm":{"detect":1}
,"plane":{"reachability":1}
,"next":{"hops":1}
,"hops":{"protocol":1}
,"modules":{"support":1}
,"support":{"bfd":1}
,"irrespective":{"bfd":1}
,"packet-sending":{"operations":1}
,"operations":{"place":1}
,"place":{"interfaces":1}
,"interfaces":{"data":1}
,"data":{"links":1}
,"links":{"extent":1}
,"extent":{"forwarding":1}
,"themselves":{"bfd":1}
,"graceful-restart":{"unaware":1}
,"unaware":{"whenever":1}
,"whenever":{"bfd":1}
,"timers":{"expire":1}
,"expire":{"session-down":1}
,"session-down":{"event":1}
,"event":{"triggered":1}
,"triggered":{"protocol":1}
,"module":{"bfd":1}
,"maintains":{"sessions":1}
,"sessions":{"protocol":1}
,"undergoes":{"graceful":1}
,"graceful":{"restart":1}
,"restart":{"bfd":1}
,"state":{"machine":1}
,"machine":{"interactions":1}
,"interactions":{"defined":1}
,"defined":{"ietf":1}
,"ietf":{"drafts":1}
,"drafts":{"supported":1}
,"supported":{"faster":1}
,"static":{"next-hops":1}
}
;Search.control.loadWordPairs(pairs);
