var pairs =
{
"ethernet":{"cfm":1,"loopback":1,"test":1}
,"cfm":{"throughput-measurement":1}
,"throughput-measurement":{"unicast":1}
,"unicast":{"command":1,"ethernet":1,"mepid":1,"frames":1}
,"command":{"configure":1,"syntax":1,"mode":1}
,"configure":{"frame":1}
,"frame":{"throughput":1,"transmission":1,"dropped":1,"size":1}
,"throughput":{"host":1,"defined":1,"measured":1,"measurements":1}
,"host":{"mep":1}
,"mep":{"remote":1,"throughput":1,"rmepid":1,"unicast":1}
,"remote":{"mep":1}
,"defined":{"maximum":1}
,"maximum":{"rate":1}
,"rate":{"frame":1,"(up":1,"frames":1,"dependent":1}
,"transmission":{"frame":1}
,"dropped":{"throughput":1,"general":1}
,"measured":{"sending":1}
,"sending":{"frames":1}
,"frames":{"increasing":1,"received":1,"start":1,"data":1,"domain":1}
,"increasing":{"rate":1}
,"(up":{"theoretical":1}
,"theoretical":{"maximum)":1}
,"maximum)":{"graphing":1}
,"graphing":{"percentage":1}
,"percentage":{"frames":1}
,"received":{"reporting":1}
,"reporting":{"rate":1}
,"start":{"dropped":1}
,"general":{"rate":1}
,"dependent":{"frame":1}
,"size":{"unicast":1}
,"loopback":{"(eth-lb)":1}
,"(eth-lb)":{"ethernet":1}
,"test":{"(eth-tst)":1}
,"(eth-tst)":{"frames":1}
,"data":{"field":1}
,"field":{"used":1}
,"used":{"performing":1}
,"performing":{"throughput":1}
,"measurements":{"command":1}
,"syntax":{"ethernet":1}
,"mepid":{"mepid":1,"rmepid":1,"specify":1}
,"rmepid":{"rmepid":1,"domain":1,"specify":1}
,"domain":{"domain_name":1,"specify":1,"ascii":1,"vlan":1}
,"domain_name":{"(vlan":1}
,"(vlan":{"vlan_id":1}
,"vlan_id":{"(bridge":1}
,"(bridge":{"<1-32>":1}
,"<1-32>":{"parameters":1,"command":1}
,"parameters":{"mepid":1}
,"specify":{"integer":1,"name":1,"bridge":1}
,"integer":{"identifies":1}
,"identifies":{"host":1,"remote":1,"vlan":1}
,"name":{"maintenance":1}
,"maintenance":{"domain":1}
,"ascii":{"format":1}
,"format":{"vlan":1}
,"vlan":{"specify":1,"bridge":1}
,"bridge":{"specify":1,"range":1}
,"range":{"<1-32>":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"ethernet":1}
}
;Search.control.loadWordPairs(pairs);
