var pairs =
{
"pim":{"hello-holdtime":1}
,"hello-holdtime":{"command":1,"configured":1,"updated":1,"<1-65535>":1,"parameter":1,"seconds":1,"123":1}
,"command":{"configure":1,"remove":1,"syntax":1,"mode":1}
,"configure":{"hello":1,"terminal":1}
,"hello":{"holdtime":1}
,"holdtime":{"default":1}
,"default":{"(3.5":1}
,"(3.5":{"*hello_interval":1,"*current":1,"*hello_interval)":1}
,"*hello_interval":{"seconds)":1}
,"seconds)":{"configuring":1}
,"configuring":{"hello-holdtime":1}
,"configured":{"value":1,"hello_holdtime":1,"less":1,"hello-holdtime":1}
,"value":{"less":1,"reset":1,"every":1,"modified":1,"maintained":1}
,"less":{"current":1}
,"current":{"hello_interval":1}
,"hello_interval":{"refused":1,"updated":1,"value":1}
,"refused":{"removing":1}
,"removing":{"configured":1}
,"hello_holdtime":{"value":1,"configured":1}
,"reset":{"(3.5":1}
,"*current":{"hello_interval)":1}
,"hello_interval)":{"value":1}
,"every":{"time":1}
,"time":{"hello_interval":1}
,"updated":{"hello-holdtime":1,"according":1}
,"according":{"rules":1}
,"rules":{"below":1}
,"below":{"hello_holdtime":1}
,"modified":{"(3.5":1}
,"*hello_interval)":{"otherwise":1}
,"otherwise":{"configured":1}
,"maintained":{"option":1}
,"option":{"command":1}
,"remove":{"configured":1}
,"syntax":{"pim":1}
,"<1-65535>":{"pim":1,"range":1}
,"parameter":{"<1-65535>":1}
,"range":{"values":1}
,"values":{"hello-holdtime":1}
,"seconds":{"command":1}
,"mode":{"interface":1,"examples":1}
,"interface":{"mode":1,"eth0":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"pim":1}
,"123":{"(config)":1}
}
;Search.control.loadWordPairs(pairs);
