var pairs =
{
"vrrp_api_walk_sessions":{"function":1,"(int":1}
,"function":{"walks":1,"num_sess":1,"completes":1}
,"walks":{"vrrp":1}
,"vrrp":{"session":1,"sessions":1}
,"session":{"table":1}
,"table":{"executes":1,"vrrp_found":1}
,"executes":{"user-provided":1}
,"user-provided":{"callback":1}
,"callback":{"non-empty":1,"vrrp_api_sess_walk_fun_t":1}
,"non-empty":{"entry":1}
,"entry":{"syntax":1}
,"syntax":{"int":1}
,"int":{"vrrp_api_walk_sessions":1,"*num_sess)":1}
,"(int":{"ipi_vrid":1}
,"ipi_vrid":{"void":1,"virtual":1}
,"void":{"*ref":1}
,"*ref":{"vrrp_api_sess_walk_fun_t":1}
,"vrrp_api_sess_walk_fun_t":{"efun":1,"type":1}
,"efun":{"int":1,"callback":1,"function":1}
,"*num_sess)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ipi_vrid":1,"ref":1}
,"virtual":{"router":1}
,"router":{"vrrp_api_sess_walk_fun_t":1}
,"type":{"output":1}
,"output":{"parameters":1}
,"ref":{"reference":1}
,"reference":{"returned":1}
,"returned":{"efun":1}
,"num_sess":{"pointer":1}
,"pointer":{"total":1}
,"total":{"number":1}
,"number":{"vrrp":1}
,"sessions":{"processed":1}
,"processed":{"return":1}
,"return":{"values":1}
,"values":{"vrrp_ok":1}
,"vrrp_ok":{"function":1}
,"completes":{"successful":1}
,"successful":{"walk":1}
,"walk":{"table":1}
,"vrrp_found":{"search":1}
,"search":{"single":1,"found":1}
,"single":{"instance":1}
,"instance":{"succeeds":1}
,"succeeds":{"vrrp_failure":1}
,"vrrp_failure":{"object":1}
,"object":{"search":1}
}
;Search.control.loadWordPairs(pairs);
