var pairs =
{
"smi_stp_alarm_info":{"structure":1,"{\u002F*interface":1}
,"structure":{"defines":1}
,"defines":{"stp":1}
,"stp":{"alarm":1}
,"alarm":{"type":1}
,"type":{"definition":1}
,"definition":{"ifname":1,"struct":1}
,"ifname":{"interface":1,"[smi_interface_namsiz":1}
,"interface":{"name":1}
,"name":{"flags":1}
,"flags":{"flags":1,"definition":1}
,"struct":{"smi_stp_alarm_info":1}
,"{\u002F*interface":{"name*\u002Fchar":1}
,"name*\u002Fchar":{"ifname":1}
,"[smi_interface_namsiz":{"\u002F*stp":1}
,"\u002F*stp":{"detected":1,"resets":1}
,"detected":{"bpdu":1,"root":1}
,"bpdu":{"guard":1,"filter":1}
,"guard":{"violation":1}
,"violation":{"*\u002F#":1,"alarm*\u002F#":1}
,"*\u002F#":{"define":1}
,"define":{"smi_stp_bpdu_guard_violate_set":1,"smi_stp_root_guard_violate_set":1,"smi_stp_bpdu_filter_violate_set":1,"smi_stp_bpdu_guard_violate_unset":1,"smi_stp_root_guard_violate_unset":1,"smi_stp_bpdu_filter_violate_unset":1}
,"smi_stp_bpdu_guard_violate_set":{"<<0":1}
,"<<0":{"\u002F*stp":1}
,"root":{"guard":1}
,"smi_stp_root_guard_violate_set":{"<<1":1}
,"<<1":{"\u002F*stp":1}
,"filter":{"violation":1}
,"smi_stp_bpdu_filter_violate_set":{"<<2":1}
,"<<2":{"\u002F*stp":1}
,"resets":{"bpdu":1,"root":1}
,"alarm*\u002F#":{"define":1}
,"smi_stp_bpdu_guard_violate_unset":{"<<3":1}
,"<<3":{"\u002F*stp":1}
,"smi_stp_root_guard_violate_unset":{"<<4":1}
,"<<4":{"\u002F*stp":1}
,"smi_stp_bpdu_filter_violate_unset":{"<<5":1}
,"<<5":{"u_int8_t":1}
,"u_int8_t":{"flags":1}
}
;Search.control.loadWordPairs(pairs);
