var pairs =
{
"trill_get_rbridge_confidence_native":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"confidence":1}
,"confidence":{"level":1}
,"level":{"associated":1}
,"associated":{"mac":1}
,"mac":{"addresses":1}
,"addresses":{"learned":1,"return":1}
,"learned":{"native":1}
,"native":{"frames":1}
,"frames":{"syntax":1}
,"syntax":{"int":1}
,"int":{"trill_get_rbridge_confidence_native":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"integer":1}
,"u_int32_t":{"instance":1,"*ret)":1}
,"instance":{"u_int32_t":1,"integer":1,"output":1,"trill_api_get_error":1,"found":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"ret":1}
,"integer":{"contains":1}
,"contains":{"trill":1}
,"trill":{"identifier":1,"instance":1}
,"identifier":{"instance":1}
,"output":{"parameters":1}
,"ret":{"pointer":1}
,"pointer":{"confidence":1}
,"return":{"value":1}
,"value":{"trill_api_get_success":1}
,"trill_api_get_success":{"valid":1}
,"valid":{"instance":1}
,"trill_api_get_error":{"valid":1}
}
;Search.control.loadWordPairs(pairs);
