var pairs =
{
"ethernet":{"cfm":1}
,"cfm":{"domain-name":1,"domain":1}
,"domain-name":{"command":1,"type":1,"based":1}
,"command":{"define":1,"remove":1,"syntax":1,"mode":1}
,"define":{"cfm":1}
,"domain":{"particular":1,"command":1,"domain_name":1,"name":1}
,"particular":{"level":1}
,"level":{"bridge":1,"level":1,"mip-creation":1,"specify":1,"<0-7>":1}
,"bridge":{"form":1,"explicit":1,"specify":1,"<1-32>":1,"command":1,"(config-ether-cfm)":1}
,"form":{"command":1}
,"remove":{"domain":1}
,"syntax":{"ethernet":1}
,"type":{"((no-name":1,"mac":1,"itu-t":1,"specify":1,"no-name":1,"maintenance":1,"character-string":1}
,"((no-name":{"name":1}
,"name":{"no_name)":1,"domain_name)":1,"domain_name))":1,"domain_name":1,"type":1,"specify":1,"no_name":1,"dns-based":1,"domain-name":1,"character-string":1,"character":1,"mac":1,"itut-t":1,"itu-t":1,"level":1,"abc":1}
,"no_name)":{"(dns-based":1}
,"(dns-based":{"name":1}
,"domain_name)":{"(character-string":1}
,"(character-string":{"name":1}
,"domain_name))":{"level":1}
,"mip-creation":{"(none":1,"specify":1,"default":1}
,"(none":{"default":1}
,"default":{"explicit)":1,"specify":1,"bridge":1}
,"explicit)":{"(bridge":1}
,"(bridge":{"<1-32>":1}
,"<1-32>":{"ethernet":1,"parameters":1,"specify":1}
,"mac":{"name":1,"address":1}
,"domain_name":{"level":1,"enter":1}
,"itu-t":{"name":1,"carrier":1}
,"parameters":{"type":1}
,"specify":{"name":1,"level":1,"mip":1,"bridge":1}
,"no-name":{"name":1}
,"maintenance":{"domain":1}
,"no_name":{"enter":1}
,"enter":{"name":1,"domain":1}
,"dns-based":{"name":1}
,"based":{"domain_name":1}
,"character-string":{"name":1}
,"character":{"string":1}
,"string":{"domain_name":1}
,"address":{"2-octet":1}
,"2-octet":{"integer":1}
,"integer":{"domain_name":1}
,"itut-t":{"name":1}
,"carrier":{"code":1}
,"code":{"(icc)":1}
,"(icc)":{"format":1}
,"format":{"domain_name":1}
,"<0-7>":{"mip-creation":1}
,"mip":{"creation":1,"may":1,"created":1}
,"creation":{"permission":1}
,"permission":{"value":1}
,"value":{"none":1}
,"none":{"specify":1}
,"may":{"created":1}
,"created":{"vid":1}
,"vid":{"default":1,"bridge":1,"ports":1,"pass":1}
,"explicit":{"specify":1}
,"ports":{"vid":1}
,"pass":{"bridge":1}
,"mode":{"configure":1,"examples":1}
,"configure":{"mode":1}
,"examples":{"(config)":1}
,"(config)":{"ethernet":1}
,"abc":{"level":1}
}
;Search.control.loadWordPairs(pairs);
