var pairs =
{
"l1-l2":{"area":1}
,"area":{"routing":1,"mainly":1,"backbone":1,"connecting":1,"configured":1,"configure":1}
,"routing":{"multiple":1}
,"multiple":{"instances":1}
,"instances":{"is-is":1,"configuration":1}
,"is-is":{"supports":1}
,"supports":{"two-level":1}
,"two-level":{"hierarchy":1}
,"hierarchy":{"handling":1}
,"handling":{"scaling":1}
,"scaling":{"functionality":1}
,"functionality":{"large":1}
,"large":{"networks":1}
,"networks":{"level-1":1,"level-2":1}
,"level-1":{"(l1)":1,"areas":1,"routers":1,"area":1}
,"(l1)":{"area":1}
,"mainly":{"leaf":1}
,"leaf":{"networks":1}
,"level-2":{"(l2)":1,"area":1}
,"(l2)":{"area":1}
,"backbone":{"area":1,"level-2":1}
,"connecting":{"level-1":1}
,"areas":{"example":1,"backbone":1}
,"example":{"configured":1}
,"configured":{"level-1":1,"level-1-2":1}
,"routers":{"reside":1,"connect":1,"single":1}
,"reside":{"level-1":1}
,"level-1-2":{"routers":1,"router":1}
,"connect":{"two":1}
,"two":{"level-1":1}
,"configure":{"level-1-2":1}
,"single":{"multiple":1}
,"configuration":{"shows":1}
,"shows":{"multiple-instance":1}
,"multiple-instance":{"version":1,"l1-l2":1}
,"version":{"level-1-2":1}
,"router":{"multiple-instance":1}
}
;Search.control.loadWordPairs(pairs);
