var pairs =
{
"isis_get_circ_ifindex":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"value":1}
,"value":{"interface":1,"non-vr":1}
,"interface":{"index":1,"circuit":1}
,"index":{"interface":1,"output":1,"corresponds":1,"return":1,"found":1}
,"circuit":{"corresponds":1,"index":1}
,"corresponds":{"syntax":1,"circuit":1}
,"syntax":{"int":1}
,"int":{"isis_get_circ_ifindex":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1,"instance":1}
,"u_int32_t":{"instance":1,"circindex":1,"*ret)":1}
,"instance":{"u_int32_t":1,"is-is":1,"circindex":1,"isis_api_get_error":1}
,"circindex":{"u_int32_t":1,"is-is":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"ret":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"is-is":{"instance":1,"circuit":1}
,"output":{"parameters":1}
,"ret":{"interface":1}
,"return":{"values":1}
,"values":{"isis_api_get_success":1}
,"isis_api_get_success":{"supported":1}
,"supported":{"circuit":1}
,"found":{"specified":1}
,"specified":{"instance":1}
,"isis_api_get_error":{"supported":1}
}
;Search.control.loadWordPairs(pairs);
