var pairs =
{
"ethernet":{"cfm":1,"operations":1}
,"cfm":{"configurations":1,"transparent":1,"extensions":1}
,"configurations":{"chapter":1,"using":1}
,"chapter":{"contains":1}
,"contains":{"examples":1}
,"examples":{"ethernet":1}
,"operations":{"management":1}
,"management":{"(oam)":1,"(cfm)":1,"detects":1,"cfm":1,"fault":1}
,"(oam)":{"configurations":1,"module":1}
,"using":{"connectivity":1}
,"connectivity":{"fault":1,"failures":1}
,"fault":{"management":1,"monitoring":1}
,"(cfm)":{"protocol":1}
,"protocol":{"connectivity":1,"standard":1}
,"detects":{"verifies":1}
,"verifies":{"isolates":1}
,"isolates":{"notifies":1}
,"notifies":{"connectivity":1}
,"failures":{"virtual":1}
,"virtual":{"bridged":1}
,"bridged":{"lan":1}
,"lan":{"(b-vlan)":1}
,"(b-vlan)":{"based":1}
,"based":{"protocol":1}
,"standard":{"specified":1}
,"specified":{"ieee":1}
,"ieee":{"802.1ag":1}
,"802.1ag":{"2007":1}
,"2007":{"provides":1}
,"provides":{"discovery":1}
,"discovery":{"verification":1}
,"verification":{"paths":1}
,"paths":{"802.1":1}
,"802.1":{"bridges":1}
,"bridges":{"lans":1}
,"lans":{"part":1}
,"part":{"operation":1}
,"operation":{"administration":1}
,"administration":{"management":1}
,"module":{"zebos-xp":1}
,"zebos-xp":{"cfm":1}
,"transparent":{"customer":1}
,"customer":{"data":1}
,"data":{"transported":1}
,"transported":{"network":1}
,"network":{"capable":1}
,"capable":{"providing":1}
,"providing":{"maximum":1}
,"maximum":{"fault":1}
,"extensions":{"support":1}
,"support":{"enhanced":1}
,"enhanced":{"fault":1}
,"monitoring":{"performance":1}
,"performance":{"measurement":1}
,"measurement":{"supports":1}
,"supports":{"requirements":1}
,"requirements":{"itu":1}
,"itu":{"y.1731":1}
,"y.1731":{"standard":1}
}
;Search.control.loadWordPairs(pairs);
