var pairs =
{
"receiving":{"processing":1}
,"processing":{"bfd":1}
,"bfd":{"packets":1,"control":1,"bfd":1,"channel":1,"packet":1,"session":1,"discriminator":1,"tree":1}
,"packets":{"following":1,"received":1}
,"following":{"steps":1}
,"steps":{"provide":1}
,"provide":{"summary":1}
,"summary":{"bfd":1}
,"received":{"processed":1,"mpls-tp":1,"label":1}
,"processed":{"oamd":1}
,"oamd":{"module":1}
,"module":{"receives":1}
,"receives":{"bfd":1}
,"control":{"packet":1}
,"packet":{"forwarder":1,"verified":1,"gal\u002Fvc":1,"source":1,"sanity":1,"inspected":1,"validated":1,"dropped":1,"received":1,"accepted":1}
,"forwarder":{"packet":1}
,"verified":{"packet":1,"remote":1}
,"gal\u002Fvc":{"label":1}
,"label":{"ach":1,"in-interface":1}
,"ach":{"header":1}
,"header":{"follow":1,"valid":1}
,"follow":{"label":1}
,"valid":{"channel":1,"bfd":1}
,"channel":{"type":1}
,"type":{"channel":1,"lsp":1,"bfd":1}
,"lsp":{"ping":1}
,"ping":{"bfd":1}
,"source":{"mep":1}
,"mep":{"tlv":1,"packet":1,"information":1}
,"tlv":{"packet":1,"valid":1}
,"sanity":{"verified":1}
,"remote":{"discriminator":1}
,"discriminator":{"field":1,"non-zero":1,"tree":1,"zero":1}
,"field":{"packet":1}
,"inspected":{"remote":1}
,"non-zero":{"value":1}
,"value":{"used":1}
,"used":{"find":1,"fetch":1}
,"find":{"bfd":1}
,"session":{"bfd":1,"found":1,"moved":1,"mpls-tp":1}
,"tree":{"session":1,"bfd":1}
,"found":{"packet":1}
,"validated":{"against":1}
,"against":{"configured":1}
,"configured":{"mep":1,"meg":1}
,"information":{"mep":1,"nsm":1,"meg":1}
,"moved":{"down":1}
,"down":{"state":1}
,"state":{"session":1}
,"dropped":{"remote":1,"meg":1,"bfd":1}
,"zero":{"packet":1}
,"mpls-tp":{"tunnel":1,"bfd":1}
,"tunnel":{"in-label":1,"information":1}
,"in-label":{"in-interface":1}
,"in-interface":{"values":1}
,"values":{"used":1}
,"fetch":{"tunnel":1,"information":1,"bfd":1}
,"nsm":{"packet":1,"returns":1}
,"returns":{"tunnel":1}
,"meg":{"names":1}
,"names":{"configured":1,"present":1,"used":1}
,"present":{"packet":1,"meg":1}
,"accepted":{"processed":1}
}
;Search.control.loadWordPairs(pairs);
