var pairs =
{
"clear":{"rbridge":1,"trill":1}
,"rbridge":{"trill":1}
,"trill":{"mac":1,"mac-address-table":1}
,"mac":{"command":1,"address":1}
,"command":{"reset":1,"syntax":1,"mode":1}
,"reset":{"trill":1}
,"address":{"command":1,"table":1}
,"syntax":{"clear":1}
,"mac-address-table":{"(vlan":1,"vlan":1,"egress-nickname":1,"bridge":1}
,"(vlan":{"<1-4094>":1}
,"<1-4094>":{"egress-nickname":1,"specify":1}
,"egress-nickname":{"all)":1,"bridge":1}
,"all)":{"bridge":1}
,"bridge":{"<1-32>":1,"group":1,"clear":1}
,"<1-32>":{"parameters":1,"specify":1}
,"parameters":{"<1-4094>":1}
,"specify":{"actual":1,"clear":1,"bridge":1}
,"actual":{"vlan":1,"egress":1}
,"vlan":{"identifier":1,"bridge":1}
,"identifier":{"specify":1}
,"egress":{"nickname":1}
,"nickname":{"specify":1}
,"table":{"<1-32>":1}
,"group":{"command":1}
,"mode":{"exec":1,"privilege":1,"examples":1}
,"exec":{"mode":1}
,"privilege":{"exec":1}
,"examples":{"clear":1}
}
;Search.control.loadWordPairs(pairs);
