var pairs =
{
"radius":{"server":1,"enable":1,"accounting":1}
,"server":{"accounting":1,"host":1,"ipv4":1,"config":1,"configured":1,"password":1}
,"accounting":{"following":1,"measure":1,"login":1,"radius":1,"purpose":1,"process":1,"validation":1}
,"following":{"authentication":1}
,"authentication":{"user":1}
,"user":{"configure":1,"consumes":1,"present":1,"created":1,"corresponding":1}
,"configure":{"accounting":1,"terminal":1,"mode":1}
,"measure":{"resources":1}
,"resources":{"user":1}
,"consumes":{"during":1}
,"during":{"access":1}
,"access":{"radius":1}
,"host":{"configuration":1,"10.16.19.2":1,"machine":1}
,"configuration":{"dut":1}
,"dut":{"configure":1,"user":1}
,"terminal":{"enter":1}
,"enter":{"configure":1}
,"mode":{"(config)":1}
,"(config)":{"radius-server":1,"aaa":1,"username-remote":1}
,"radius-server":{"host":1,"show":1}
,"10.16.19.2":{"key":1}
,"key":{"testing":1,"key":1,"present":1}
,"testing":{"specify":1}
,"specify":{"radius":1}
,"ipv4":{"address":1}
,"address":{"configured":1}
,"configured":{"shared":1,"(config)":1}
,"shared":{"key":1}
,"present":{"server":1,"radius":1}
,"config":{"file":1}
,"file":{"(config)":1,"verify":1}
,"aaa":{"accounting":1,"show":1}
,"login":{"default":1}
,"default":{"group":1}
,"group":{"radius":1}
,"enable":{"accounting":1}
,"username-remote":{"test":1}
,"test":{"password":1}
,"password":{"test12345":1,"accounting":1,"check":1,"enters":1}
,"test12345":{"create":1}
,"create":{"username":1}
,"username":{"password":1}
,"purpose":{"user":1}
,"verify":{"radius":1}
,"process":{"ssh":1}
,"ssh":{"telnet":1}
,"telnet":{"form":1}
,"form":{"host":1}
,"machine":{"dut":1}
,"created":{"provide":1}
,"provide":{"radius":1}
,"check":{"whether":1}
,"whether":{"client":1}
,"client":{"validates":1}
,"validates":{"user":1}
,"corresponding":{"username":1}
,"enters":{"imish":1}
,"imish":{"via":1}
,"via":{"radius":1}
,"validation":{"commands":1}
,"commands":{"show":1}
,"show":{"radius-server":1,"running-config":1}
,"running-config":{"aaa":1,"radius":1}
}
;Search.control.loadWordPairs(pairs);
