var pairs =
{
"miscellaneous":{"commands":1}
,"commands":{"rtr1":1}
,"rtr1":{"(config)":1,"(g8032-config-switch)":1}
,"(config)":{"g8032":1,"bridge":1}
,"g8032":{"erp-instance":1,"physical-ring":1,"profile":1}
,"erp-instance":{"major":1}
,"major":{"bridge":1}
,"bridge":{"enter":1,"g8032":1,"delete":1}
,"enter":{"g.8032":1}
,"g.8032":{"configure":1}
,"configure":{"switch":1}
,"switch":{"mode":1}
,"mode":{"rtr1":1}
,"(g8032-config-switch)":{"virtual-channel":1,"non-virtual-channel":1,"sub-ring":1,"tcn-propogation":1,"version":1,"exit":1,"raps-channel":1,"data-traffic":1}
,"virtual-channel":{"attached-to-instance":1,"delete":1}
,"attached-to-instance":{"mi1":1}
,"mi1":{"create":1}
,"create":{"virtual":1,"non":1}
,"virtual":{"channel":1}
,"channel":{"attach":1,"rtr1":1}
,"attach":{"instance":1}
,"instance":{"rtr1":1}
,"delete":{"virtual":1,"non":1,"sub-ring":1,"raps-channel":1,"data-traffic":1,"physical":1,"erp":1,"g8032":1}
,"non-virtual-channel":{"create":1,"delete":1}
,"non":{"virtual":1}
,"sub-ring":{"delete":1,"rtr1":1}
,"tcn-propogation":{"enable":1,"disable":1}
,"enable":{"enable":1,"tcn-propagation":1}
,"tcn-propagation":{"rtr1":1}
,"disable":{"disable":1,"tcn-propagation":1}
,"version":{"version":1,"rtr1":1}
,"exit":{"exit":1,"g.8032":1}
,"raps-channel":{"delete":1,"rtr1":1}
,"data-traffic":{"delete":1,"rtr1":1}
,"physical-ring":{"delete":1}
,"physical":{"ring":1}
,"ring":{"rtr1":1}
,"erp":{"instance":1}
,"profile":{"bridge":1}
}
;Search.control.loadWordPairs(pairs);
