var pairs =
{
"mrib_snmp_api_get_next_vif_outmcastoctets":{"function":1,"(const":1}
,"function":{"gets":1,"succeeds":1,"fails":1}
,"gets":{"number":1}
,"number":{"octets":1}
,"octets":{"multicast":1,"sent":1}
,"multicast":{"packets":1,"next":1}
,"packets":{"sent":1,"return":1}
,"sent":{"next":1,"multicast":1}
,"next":{"interface":1,"hop":1}
,"interface":{"syntax":1}
,"syntax":{"int":1}
,"int":{"mrib_snmp_api_get_next_vif_outmcastoctets":1}
,"(const":{"u_int32_t":1}
,"u_int32_t":{"vr_id":1}
,"vr_id":{"const":1,"virtual":1}
,"const":{"vrf_id_t":1}
,"vrf_id_t":{"vrf_id":1}
,"vrf_id":{"struct":1,"vpn":1}
,"struct":{"mrib_snmp_api_vif_index":1}
,"mrib_snmp_api_vif_index":{"*index":1}
,"*index":{"ut_int64_t":1}
,"ut_int64_t":{"*val)":1}
,"*val)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"index":1}
,"virtual":{"router":1}
,"router":{"vrf_id":1}
,"vpn":{"routing\u002Fforwarding":1}
,"routing\u002Fforwarding":{"instance":1}
,"instance":{"output":1}
,"output":{"parameters":1}
,"index":{"index":1,"entry":1}
,"entry":{"multicast":1}
,"hop":{"table":1}
,"table":{"val":1}
,"val":{"number":1}
,"return":{"values":1}
,"values":{"mrib_api_get_success":1}
,"mrib_api_get_success":{"function":1}
,"succeeds":{"mrib_api_get_error":1}
,"mrib_api_get_error":{"function":1}
}
;Search.control.loadWordPairs(pairs);
