var pairs =
{
"ipi_mpls_vrf_end":{"function":1,"(int":1}
,"function":{"unbinds":1}
,"unbinds":{"specified":1}
,"specified":{"interface":1}
,"interface":{"vrf":1,"deleted":1}
,"vrf":{"table":1}
,"table":{"interfaces":1,"question":1,"removed":1,"output":1,"deleted":1}
,"interfaces":{"bound":1}
,"bound":{"vrf":1}
,"question":{"vrf":1}
,"removed":{"mpls":1}
,"mpls":{"forwarder":1}
,"forwarder":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ipi_mpls_vrf_end":1}
,"(int":{"vrf_ident)":1}
,"vrf_ident)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vrf_ident":1,"data":1}
,"vrf_ident":{"identifier":1}
,"identifier":{"virtual":1}
,"virtual":{"route":1}
,"route":{"forwarding":1}
,"forwarding":{"table":1}
,"output":{"parameters":1}
,"data":{"returned":1}
,"returned":{"call":1}
,"call":{"return":1,"vrf":1,"interface":1}
,"return":{"value":1}
,"value":{"status":1}
,"status":{"call":1}
,"deleted":{"status":1}
}
;Search.control.loadWordPairs(pairs);
