var pairs =
{
"interaction":{"nsm":1}
,"nsm":{"signaling":1,"interacts":1}
,"signaling":{"protocols":1,"protocol":1}
,"protocols":{"nsm":1,"passes":1}
,"interacts":{"minimally":1}
,"minimally":{"signaling":1}
,"passes":{"following":1}
,"following":{"information":1}
,"information":{"signaling":1}
,"protocol":{"application":1,"decide":1}
,"application":{"determine":1}
,"determine":{"whether":1}
,"whether":{"requesting":1,"requested":1}
,"requesting":{"reservation":1}
,"reservation":{"feasible":1}
,"feasible":{"bandwidth":1}
,"bandwidth":{"per":1,"actually":1,"bandwidth":1}
,"per":{"interface":1,"priority":1}
,"interface":{"allows":1}
,"allows":{"signaling":1}
,"decide":{"whether":1}
,"requested":{"bandwidth":1}
,"actually":{"possible":1}
,"possible":{"maximum":1}
,"maximum":{"reservable":1}
,"reservable":{"bandwidth":1}
,"priority":{"level":1}
}
;Search.control.loadWordPairs(pairs);
