var pairs =
{
"overview":{"l2gp":1}
,"l2gp":{"solution":1,"regular":1,"configuration":1}
,"solution":{"helps":1,"user":1,"implements":1}
,"helps":{"separate":1}
,"separate":{"different":1}
,"different":{"stp":1}
,"stp":{"domains":1,"algorithm":1,"hello":1}
,"domains":{"solution":1}
,"user":{"configures":1}
,"configures":{"ports":1}
,"ports":{"layer-two":1,"port":1,"communicating":1,"connect":1,"configured":1}
,"layer-two":{"gateway":1}
,"gateway":{"ports":1,"port":1}
,"port":{"defining":1,"bridged":1,"avoiding":1,"forwarding":1,"bridge":1,"designated":1,"l2gp":1}
,"defining":{"border":1}
,"border":{"domain":1}
,"domain":{"stp":1,"result":1}
,"algorithm":{"active":1}
,"active":{"l2gp":1}
,"implements":{"stp":1}
,"hello":{"protocol":1}
,"protocol":{"defines":1}
,"defines":{"l2gp":1}
,"regular":{"port":1}
,"bridged":{"network":1}
,"network":{"redundantly":1,"(pbbn)":1}
,"redundantly":{"attached":1}
,"attached":{"provider":1}
,"provider":{"backbone":1}
,"backbone":{"bridged":1}
,"(pbbn)":{"layer":1}
,"layer":{"two":1}
,"two":{"gateway":1}
,"communicating":{"within":1}
,"within":{"region":1}
,"region":{"without":1}
,"without":{"influence":1}
,"influence":{"pbbn":1}
,"pbbn":{"ports":1,"single":1,"instance":1}
,"connect":{"pbbn":1}
,"single":{"layer":1}
,"avoiding":{"bridging":1}
,"bridging":{"loops":1}
,"loops":{"pbbn":1}
,"instance":{"figure":1}
,"figure":{"5-1":1}
,"5-1":{"example":1}
,"example":{"l2gp":1}
,"configuration":{"configuration":1,"ports":1}
,"configured":{"bridge":1}
,"bridge":{"ids":1,"domain":1,"continually":1}
,"ids":{"router":1}
,"router":{"router":1,"respectively":1,"better":1}
,"respectively":{"router":1}
,"better":{"router":1,"bridge":1}
,"result":{"port":1}
,"forwarding":{"(root)":1}
,"(root)":{"port":1}
,"continually":{"receives":1}
,"receives":{"best":1}
,"best":{"bpdus":1}
,"bpdus":{"port":1}
,"designated":{"discarding":1}
,"discarding":{"port":1}
}
;Search.control.loadWordPairs(pairs);
