var pairs =
{
"validation":{"show":1}
,"show":{"ietf":1,"mpls-tp":1}
,"ietf":{"meg":1}
,"meg":{"brief":1,"index":1}
,"brief":{"command":1,"maintenance":1}
,"command":{"displays":1,"initiate":1}
,"displays":{"delay-measurement":1,"configuration":1}
,"delay-measurement":{"enabled":1,"meg-name":1,"session":1}
,"enabled":{"command":1,"pe1":1}
,"initiate":{"proactive":1}
,"proactive":{"success":1}
,"success":{"show":1}
,"mpls-tp":{"delay-measurement":1}
,"meg-name":{"meg1":1}
,"meg1":{"me-name":1,"meg":1}
,"me-name":{"me1":1}
,"me1":{"command":1,"index":1,"codes":1}
,"configuration":{"errors":1}
,"errors":{"statistics":1}
,"statistics":{"pe1":1}
,"pe1":{"pe1":1,"ietf":1,"mpls-tp":1}
,"maintenance":{"entity":1}
,"entity":{"group":1,"me1":1}
,"group":{"meg1":1}
,"index":{"service":1,"tunnel":1}
,"service":{"type":1}
,"type":{"tunnel":1,"mep":1}
,"tunnel":{"location":1,"name":1}
,"location":{"per-node":1}
,"per-node":{"------------------------------------------------------------------------------maintenance":1}
,"------------------------------------------------------------------------------maintenance":{"entity":1}
,"name":{"tunnel-1":1}
,"tunnel-1":{"type":1}
,"mep":{"oper":1}
,"oper":{"status":1}
,"status":{"------------------------------------------------------------------------------cc-cv":1}
,"------------------------------------------------------------------------------cc-cv":{"disabled":1}
,"disabled":{"loopback":1,"lock":1,"fault-management":1,"loss-measurement":1,"delay-measurement":1}
,"loopback":{"disabled":1}
,"lock":{"disabled":1}
,"fault-management":{"disabled":1}
,"loss-measurement":{"disabled":1}
,"codes":{"-request":1}
,"-request":{"sent":1}
,"sent":{"-invalid":1}
,"-invalid":{"data":1,"destination":1,"message":1}
,"data":{"format":1}
,"format":{"-initialization":1,"-authentication":1}
,"-initialization":{"progress":1}
,"progress":{"-data":1}
,"-data":{"reset":1}
,"reset":{"occurred":1}
,"occurred":{"-resource":1}
,"-resource":{"temporarily":1,"unavailable":1,"released":1}
,"temporarily":{"unavailable":1}
,"unavailable":{"-unspecified":1,"-resource":1}
,"-unspecified":{"error":1}
,"error":{"-unsupported":1,"active":1}
,"-unsupported":{"version":1,"control":1,"data":1,"mandatory":1,"query":1}
,"version":{"-unsupported":1}
,"control":{"code":1}
,"code":{"-unsupported":1}
,"-authentication":{"failure":1}
,"failure":{"-invalid":1}
,"destination":{"node":1}
,"node":{"-connection":1}
,"-connection":{"mismatch":1}
,"mismatch":{"-unsupported":1}
,"mandatory":{"tlv":1}
,"tlv":{"-unsupported":1}
,"query":{"interval":1}
,"interval":{"-admin":1}
,"-admin":{"block":1}
,"block":{"-resource":1}
,"released":{"-invalid":1}
,"message":{"-protocol":1}
,"-protocol":{"error":1}
,"active":{"delay-measurement":1}
}
;Search.control.loadWordPairs(pairs);
