var pairs =
{
"zebos_smi_client_set_alarm_callback":{"function":1,"(smi_alarm_callback_t":1}
,"function":{"registers":1,"called":1,"syntax":1,"invoked":1}
,"registers":{"callback":1}
,"callback":{"function":1,"callback":1}
,"called":{"alarms":1}
,"alarms":{"generated":1,"chapter":1,"call":1}
,"generated":{"smi":1}
,"smi":{"server":1,"alarms":1,"client":1}
,"server":{"smi":1,"smi_alarm_callback_t":1}
,"chapter":{"handling":1}
,"handling":{"alarms":1}
,"call":{"zebos_smi_client_create":1}
,"zebos_smi_client_create":{"calling":1}
,"calling":{"function":1}
,"syntax":{"void":1}
,"void":{"zebos_smi_client_set_alarm_callback":1}
,"(smi_alarm_callback_t":{"callback)":1}
,"callback)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"callback":1,"none":1}
,"invoked":{"smi":1}
,"client":{"side":1}
,"side":{"alarm":1}
,"alarm":{"received":1}
,"received":{"smi":1}
,"smi_alarm_callback_t":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"none":1}
}
;Search.control.loadWordPairs(pairs);
