var pairs =
{
"creating":{"bfd":1}
,"bfd":{"session":1,"sessions":1,"control":1,"packet":1,"receives":1,"packets":1}
,"session":{"following":1,"add":1,"bfd":1,"up\u002Fdown":1,"made":1}
,"following":{"steps":1}
,"steps":{"provide":1}
,"provide":{"overview":1}
,"overview":{"bfd":1}
,"sessions":{"created":1}
,"created":{"pointer":1}
,"pointer":{"meg":1}
,"meg":{"name":1,"configurations":1,"names":1}
,"name":{"name":1,"used":1,"upon":1,"oamd":1}
,"used":{"input":1,"find":1}
,"input":{"parameters":1,"label":1,"interface":1}
,"parameters":{"network":1}
,"network":{"service":1}
,"service":{"module":1}
,"module":{"(nsm)":1,"containing":1,"tunnel":1}
,"(nsm)":{"sends":1}
,"sends":{"bidirectional":1,"bfd":1}
,"bidirectional":{"forwarding":1}
,"forwarding":{"detection":1}
,"detection":{"(bfd)":1}
,"(bfd)":{"session":1}
,"add":{"message":1}
,"message":{"oamd":1,"oam":1}
,"oamd":{"module":1,"creates":1}
,"containing":{"meg":1}
,"upon":{"receiving":1}
,"receiving":{"session":1,"first":1,"notification":1}
,"oam":{"adds":1}
,"adds":{"entry":1}
,"entry":{"new":1}
,"new":{"mpls-tp":1}
,"mpls-tp":{"tree":1,"nodes":1}
,"tree":{"indexed":1}
,"indexed":{"meg":1}
,"creates":{"sends":1}
,"control":{"packets":1}
,"packets":{"peer":1,"receiving":1}
,"peer":{"point":1,"using":1}
,"point":{"procedure":1}
,"procedure":{"ingress":1}
,"ingress":{"egress":1}
,"egress":{"nodes":1}
,"nodes":{"mpls-tp":1,"meg":1}
,"configurations":{"monitoring":1}
,"monitoring":{"transport":1}
,"transport":{"path":1}
,"path":{"node":1}
,"node":{"receiving":1}
,"first":{"bfd":1}
,"packet":{"fetch":1,"sending":1}
,"fetch":{"tunnel":1}
,"tunnel":{"pseudowire":1,"information":1,"down":1}
,"pseudowire":{"(pw)":1}
,"(pw)":{"information":1}
,"information":{"nsm":1,"returned":1,"communicated":1}
,"nsm":{"based":1,"contains":1,"module":1}
,"based":{"input":1}
,"label":{"input":1,"respectively":1}
,"interface":{"virtual":1}
,"virtual":{"circuit":1}
,"circuit":{"(vc)":1}
,"(vc)":{"label":1}
,"respectively":{"tunnel":1}
,"returned":{"nsm":1}
,"contains":{"meg":1}
,"names":{"used":1}
,"find":{"associated":1}
,"associated":{"bfd":1}
,"up\u002Fdown":{"state":1}
,"state":{"communicated":1}
,"communicated":{"nsm":1,"peer":1}
,"down":{"bfd":1,"notification":1,"administrator":1,"diagnostic":1}
,"receives":{"down":1}
,"notification":{"stops":1,"bfd":1}
,"stops":{"sending":1}
,"sending":{"bfd":1,"resumed":1}
,"resumed":{"bfd":1}
,"made":{"down":1}
,"administrator":{"side":1}
,"side":{"information":1}
,"using":{"admin":1}
,"admin":{"down":1}
,"diagnostic":{"code":1}
}
;Search.control.loadWordPairs(pairs);
