var pairs =
{
"initialization":{"(\u005Cpimd\u005Cpim_main.c":1}
,"(\u005Cpimd\u005Cpim_main.c":{"\u005Cpimd\u005Cpimd.c":1}
,"\u005Cpimd\u005Cpimd.c":{"\u005Cpimd\u005Cpimd.h)":1}
,"\u005Cpimd\u005Cpimd.h)":{"main":1}
,"main":{"starts":1}
,"starts":{"pim":1,"initializes":1,"pimd":1}
,"pim":{"process":1,"pim":1,"feature":1,"instance":1}
,"process":{"command":1}
,"command":{"line":1}
,"line":{"argument":1}
,"argument":{"string":1}
,"string":{"meaning":1}
,"meaning":{"--daemon":1}
,"--daemon":{"runs":1}
,"runs":{"daemon":1}
,"daemon":{"mode":1}
,"mode":{"--config_file":1}
,"--config_file":{"configuration":1}
,"configuration":{"file":1}
,"file":{"name":1,"initialized":1}
,"name":{"--vty_port":1}
,"--vty_port":{"vty\u0027s":1}
,"vty\u0027s":{"port":1}
,"port":{"number":1}
,"number":{"--version":1}
,"--version":{"print":1}
,"print":{"program":1}
,"program":{"version":1}
,"version":{"--help":1}
,"--help":{"display":1}
,"display":{"help":1}
,"help":{"exit":1}
,"exit":{"main":1}
,"initializes":{"following":1}
,"following":{"global":1}
,"global":{"objects":1,"variables":1}
,"objects":{"pim":1}
,"feature":{"capabilities":1}
,"capabilities":{"check":1}
,"check":{"signal":1}
,"signal":{"handler":1}
,"handler":{"access-list":1}
,"access-list":{"master":1}
,"master":{"thread":1}
,"thread":{"common":1}
,"common":{"library":1}
,"library":{"functions":1}
,"functions":{"global":1,"including":1}
,"variables":{"reads":1}
,"reads":{"config":1}
,"config":{"file":1}
,"initialized":{"pim-related":1}
,"pim-related":{"system":1}
,"system":{"support":1}
,"support":{"functions":1}
,"including":{"debug":1}
,"debug":{"cli":1}
,"cli":{"nsm)":1}
,"nsm)":{"creates":1}
,"creates":{"pim":1}
,"instance":{"starts":1}
,"pimd":{"daemon":1}
}
;Search.control.loadWordPairs(pairs);
