var pairs =
{
"efm_oam_get_oper_status":{"function":1,"(struct":1}
,"function":{"gets":1,"syntax":1,"succeeds":1}
,"gets":{"status":1}
,"status":{"discovery":1}
,"discovery":{"phase":1,"constants":1}
,"phase":{"oam":1,"determine":1}
,"oam":{"clients":1,"entities":1,"capabilities":1,"capability":1,"disabled":1,"pdus":1,"capable":1,"entity":1}
,"clients":{"link":1}
,"link":{"during":1,"begin":1,"detected":1,"fault":1}
,"during":{"initialization":1}
,"initialization":{"failure":1}
,"failure":{"two":1}
,"two":{"oam":1}
,"entities":{"link":1,"accepted":1}
,"begin":{"discovery":1}
,"determine":{"oam":1}
,"capabilities":{"efm":1}
,"efm":{"mib":1}
,"mib":{"support":1}
,"support":{"calls":1}
,"calls":{"function":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"efm_oam_get_oper_status":1}
,"(struct":{"interface":1}
,"interface":{"*ifp":1,"structure":1,"oper_link_fault":1,"operating":1,"half-duplex":1,"found":1}
,"*ifp":{"u_int32_t":1}
,"u_int32_t":{"*oper_status)":1}
,"*oper_status)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"oper_status":1}
,"ifp":{"pointer":1}
,"pointer":{"interface":1}
,"structure":{"output":1}
,"output":{"parameters":1}
,"oper_status":{"result":1}
,"result":{"discovery":1}
,"constants":{"enum":1}
,"enum":{"efm_oam_oper_status":1}
,"efm_oam_oper_status":{"onmd\u002Fefm-oam\u002Fefm_types.h":1}
,"onmd\u002Fefm-oam\u002Fefm_types.h":{"oper_active_send_local":1}
,"oper_active_send_local":{"active":1}
,"active":{"mode":1}
,"mode":{"actively":1,"waiting":1}
,"actively":{"trying":1}
,"trying":{"discover":1}
,"discover":{"whether":1}
,"whether":{"peer":1}
,"peer":{"oam":1,"device":1,"accepted":1,"oper_send_local_remote_ok":1}
,"capability":{"made":1}
,"made":{"determination":1}
,"determination":{"oper_disabled":1}
,"oper_disabled":{"oam":1}
,"disabled":{"interface":1}
,"oper_link_fault":{"link":1}
,"detected":{"fault":1}
,"fault":{"transmitting":1,"indication":1}
,"transmitting":{"oam":1}
,"pdus":{"link":1}
,"indication":{"interface":1}
,"operating":{"oper_nonoper_half_duplex":1}
,"oper_nonoper_half_duplex":{"interface":1}
,"half-duplex":{"operation":1,"interfaces)":1}
,"operation":{"(oam":1}
,"(oam":{"functions":1}
,"functions":{"designed":1}
,"designed":{"work":1}
,"work":{"completely":1}
,"completely":{"half-duplex":1}
,"interfaces)":{"oper_operational":1}
,"oper_operational":{"local":1}
,"local":{"remote":1,"oam":1}
,"remote":{"oam":1}
,"accepted":{"peering":1,"rejected":1}
,"peering":{"oper_passive_wait":1,"oper_peering_remotely_rejected":1,"oper_send_local_remote":1,"return":1}
,"oper_passive_wait":{"passive":1}
,"passive":{"mode":1}
,"waiting":{"peer":1}
,"device":{"oam":1}
,"capable":{"oper_peering_locally_rejected":1}
,"oper_peering_locally_rejected":{"local":1}
,"entity":{"rejected":1,"discovered":1,"accepted":1}
,"rejected":{"peering":1,"configuration":1}
,"oper_peering_remotely_rejected":{"remote":1}
,"oper_send_local_remote":{"local":1}
,"discovered":{"peer":1}
,"configuration":{"peer":1}
,"oper_send_local_remote_ok":{"local":1}
,"return":{"efm_success":1}
,"efm_success":{"function":1}
,"succeeds":{"efm_oam_err_if_not_found":1}
,"efm_oam_err_if_not_found":{"onmd":1}
,"onmd":{"interface":1}
}
;Search.control.loadWordPairs(pairs);
