var pairs =
{
"neighbor":{"advertisement-interval":1,"(a.b.c.d":1,"ipv4":1,"ipv6":1,"peer-group":1,"remote-as":1,"10.10.0.3":1}
,"advertisement-interval":{"command":1,"<0-65535>":1,"neighbor":1,"value":1}
,"command":{"minimum":1,"interval":1,"syntax":1,"command":1,"applies":1,"mode":1}
,"minimum":{"interval":1,"advertisement":1}
,"interval":{"sending":1,"bgp":1,"seconds":1,"time":1}
,"sending":{"bgp":1}
,"bgp":{"routing":1,"dampening":1,"neighbor":1,"peer":1,"(config-router)":1}
,"routing":{"updates":1}
,"updates":{"reduce":1,"sent":1}
,"reduce":{"flapping":1}
,"flapping":{"routes":1}
,"routes":{"internet":1,"parameter":1}
,"internet":{"minimum":1}
,"advertisement":{"interval":1}
,"sent":{"per":1}
,"per":{"interval":1}
,"seconds":{"bgp":1,"command":1}
,"dampening":{"used":1}
,"used":{"control":1,"command":1}
,"control":{"effects":1}
,"effects":{"flapping":1}
,"parameter":{"command":1,"used":1}
,"time":{"default":1}
,"default":{"command":1}
,"syntax":{"neighbor":1}
,"(a.b.c.d":{"x:x":1}
,"x:x":{":x:x":1}
,":x:x":{"word)":1,"address":1}
,"word)":{"advertisement-interval":1}
,"<0-65535>":{"neighbor":1,"parameters":1,"advertisement-interval":1}
,"parameters":{"a.b.c.d":1}
,"a.b.c.d":{"address":1}
,"address":{"bgp":1}
,"ipv4":{"format":1}
,"format":{"x:x":1,"word":1}
,"ipv6":{"format":1}
,"word":{"name":1}
,"name":{"bgp":1}
,"peer":{"group":1,"groups":1}
,"group":{"information":1,"<0-65535>":1}
,"information":{"create":1}
,"create":{"peer":1}
,"groups":{"refer":1}
,"refer":{"neighbor":1}
,"peer-group":{"neighbor":1}
,"remote-as":{"commands":1}
,"commands":{"parameter":1}
,"applies":{"peers":1}
,"peers":{"group":1}
,"value":{"seconds":1}
,"mode":{"router":1,"example":1}
,"router":{"mode":1,"bgp":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"(config-router)":{"neighbor":1}
,"10.10.0.3":{"advertisement-interval":1}
}
;Search.control.loadWordPairs(pairs);
