var pairs =
{
"ospf6_max_concurrent_dd_unset":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"called":1,"succeeds":1}
,"sets":{"maximum":1}
,"maximum":{"concurrent":1}
,"concurrent":{"database":1}
,"database":{"descriptors":1}
,"descriptors":{"default":1}
,"default":{"value":1}
,"value":{"(5)":1,"ospf6_api_set_success":1}
,"(5)":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"ospf6_max_concurrent_dd_set":1}
,"ospf6_max_concurrent_dd_set":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf6_max_concurrent_dd_unset":1,"proc_id)":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"int":1,"virtual":1}
,"proc_id)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"found":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"tag":1}
,"tag":{"ospfv3":1,"output":1}
,"ospfv3":{"process":1}
,"process":{"tag":1,"exist":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"ospf6_api_set_success":{"function":1}
,"succeeds":{"ospf6_api_set_err_process_not_exist":1}
,"ospf6_api_set_err_process_not_exist":{"given":1}
,"given":{"process":1}
,"exist":{"ospf6_api_set_err_vr_not_exist":1}
,"ospf6_api_set_err_vr_not_exist":{"virtual":1}
}
;Search.control.loadWordPairs(pairs);
