var pairs =
{
"rsvp_api_p2mp_session_unset_bandwidth":{"call":1,"(struct":1}
,"call":{"removes":1,"fails":1,"successful":1}
,"removes":{"configured":1}
,"configured":{"bandwidth":1}
,"bandwidth":{"p2mp":1}
,"p2mp":{"session":1}
,"session":{"syntax":1,"output":1}
,"syntax":{"int":1}
,"int":{"rsvp_api_p2mp_session_unset_bandwidth":1}
,"(struct":{"rsvp_p2mp_session":1}
,"rsvp_p2mp_session":{"*orig_session)":1}
,"*orig_session)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"orig_session":1,"none":1}
,"orig_session":{"p2mp":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"rsvp_failure":1}
,"rsvp_failure":{"call":1}
,"fails":{"rsvp_success":1}
,"rsvp_success":{"call":1}
}
;Search.control.loadWordPairs(pairs);
