var pairs =
{
"hsl_bcm_tx_queue":{"data":1,"{u_char":1}
,"data":{"structure":1}
,"structure":{"helps":1}
,"helps":{"manage":1}
,"manage":{"bcm":1}
,"bcm":{"transmitted":1,"packet":1}
,"transmitted":{"queue":1}
,"queue":{"functions":1}
,"functions":{"defined":1}
,"defined":{"hsl\u002Fbroadcom\u002Fhsl_bcm_pkt.h":1}
,"hsl\u002Fbroadcom\u002Fhsl_bcm_pkt.h":{"type":1}
,"type":{"definition":1}
,"definition":{"*pkt_list":1,"struct":1}
,"*pkt_list":{"bcm":1,"\u002F*bcm":1}
,"packet":{"list":1}
,"list":{"aligned":1,"size":1,"definition":1,"*\u002F}":1}
,"aligned":{"bcm_pkt_t":1}
,"bcm_pkt_t":{"*free_pkt_list":1,"total":1,"*\u002Fu_char":1,"*\u002Fint":1}
,"*free_pkt_list":{"free":1,"\u002F*free":1}
,"free":{"list":1}
,"total":{"total":1,"list":1,"\u002F*total":1}
,"size":{"count":1,"*\u002Fint":1}
,"count":{"current":1,"pkt_sem":1,"\u002F*current":1,"*\u002Fipi_sem_id":1}
,"current":{"count":1}
,"pkt_sem":{"semaphore":1,"\u002F*semaphore":1}
,"semaphore":{"protect":1}
,"protect":{"list":1}
,"struct":{"hsl_bcm_tx_queue":1}
,"{u_char":{"*pkt_list":1}
,"\u002F*bcm":{"packet":1}
,"*\u002Fu_char":{"*free_pkt_list":1}
,"\u002F*free":{"list":1}
,"*\u002Fint":{"total":1,"count":1}
,"\u002F*total":{"list":1}
,"\u002F*current":{"count":1}
,"*\u002Fipi_sem_id":{"pkt_sem":1}
,"\u002F*semaphore":{"protect":1}
}
;Search.control.loadWordPairs(pairs);
