var pairs =
{
"trill_port_vlan_add_event":{"function":1,"(u_int32_t":1}
,"function":{"adds":1}
,"adds":{"vlan":1}
,"vlan":{"specified":1,"identification":1}
,"specified":{"port":1}
,"port":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"trill_port_vlan_add_event":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"specifies":1}
,"char":{"*name":1}
,"*name":{"u_int32_t":1,"specifies":1}
,"u_int32_t":{"ifindex":1}
,"ifindex":{"u_int16_t":1,"specifies":1}
,"u_int16_t":{"vid)":1}
,"vid)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"specifies":{"identification":1,"name":1,"interface":1,"vlan":1}
,"identification":{"virtual":1,"output":1}
,"virtual":{"router":1}
,"router":{"*name":1}
,"name":{"bridge":1}
,"bridge":{"ifindex":1}
,"interface":{"index":1}
,"index":{"vid":1}
,"vid":{"specifies":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"result_error":1}
,"result_error":{"indicates":1}
,"indicates":{"error":1}
,"error":{"occurred":1}
,"occurred":{"operation":1}
,"operation":{"performed":1}
}
;Search.control.loadWordPairs(pairs);
