var pairs =
{
"crypto":{"ipsec":1,"map":1,"command":1}
,"ipsec":{"security-association":1,"security":1}
,"security-association":{"lifetime":1}
,"lifetime":{"command":1,"values":1,"default":1,"seconds":1,"specify":1,"value":1,"new":1,"defined":1}
,"command":{"global":1,"reset":1,"syntax":1,"mode":1,"clear":1}
,"global":{"configuration":1,"lifetime":1,"value":1}
,"configuration":{"mode":1}
,"mode":{"change":1,"configure":1,"usage":1}
,"change":{"global":1}
,"values":{"used":1,"configured":1,"ignored":1}
,"used":{"negotiating":1}
,"negotiating":{"ipsec":1}
,"security":{"associations":1,"association":1}
,"associations":{"form":1,"shared":1,"time":1,"during":1,"router":1,"local":1,"example":1}
,"form":{"command":1}
,"reset":{"lifetime":1}
,"default":{"value":1}
,"value":{"command":1,"security":1,"request":1,"lifetime":1,"proposed":1,"overrides":1,"clear":1}
,"syntax":{"crypto":1}
,"seconds":{"[lifetime]":1,"parameters":1,"specify":1,"security":1,"defaults":1,"15000":1}
,"[lifetime]":{"crypto":1}
,"parameters":{"seconds":1}
,"specify":{"number":1,"lifetime":1,"global":1}
,"number":{"seconds":1}
,"association":{"live":1,"range":1,"negotiation":1,"database":1}
,"live":{"expiring":1}
,"expiring":{"lifetime":1}
,"range":{"<120-2592000>":1}
,"<120-2592000>":{"seconds":1}
,"defaults":{"none":1}
,"none":{"command":1}
,"configure":{"mode":1}
,"usage":{"ipsec":1}
,"shared":{"secret":1}
,"secret":{"keys":1}
,"keys":{"keys":1,"security":1}
,"time":{"together":1}
,"together":{"assuming":1}
,"assuming":{"particular":1}
,"particular":{"crypto":1}
,"map":{"entry":1,"local":1}
,"entry":{"lifetime":1}
,"configured":{"router":1,"lifetime":1}
,"router":{"requests":1,"receives":1}
,"requests":{"new":1}
,"new":{"security":1}
,"during":{"security":1}
,"negotiation":{"specify":1,"request":1}
,"request":{"peer":1}
,"peer":{"value":1,"smaller":1,"locally":1}
,"receives":{"negotiation":1}
,"smaller":{"lifetime":1}
,"proposed":{"peer":1}
,"locally":{"configured":1}
,"local":{"lifetime":1,"value":1}
,"defined":{"crypto":1}
,"overrides":{"global":1}
,"clear":{"crypto":1,"part":1}
,"part":{"security":1}
,"database":{"lifetime":1}
,"ignored":{"manually":1}
,"manually":{"established":1}
,"established":{"security":1}
,"example":{"zebos":1}
,"zebos":{"(config)":1}
,"(config)":{"crypto":1}
,"15000":{"zebos":1}
}
;Search.control.loadWordPairs(pairs);
