var pairs =
{
"mpls-tp":{"associate":1,"tunnel":1}
,"associate":{"command":1,"two":1,"fwd-tunnel":1}
,"command":{"associate":1,"remove":1,"syntax":1,"mode":1}
,"two":{"tunnels":1,"unidirectional":1}
,"tunnels":{"form":1,"starting":1,"parameter":1}
,"form":{"composite":1}
,"composite":{"associated":1}
,"associated":{"bidirectional":1}
,"bidirectional":{"tunnel":1}
,"tunnel":{"configuration":1,"association":1,"name":1,"source":1}
,"configuration":{"requirements":1,"command":1}
,"requirements":{"two":1}
,"unidirectional":{"tunnels":1,"(config-unidir-tnl)":1}
,"starting":{"terminating":1}
,"terminating":{"node":1}
,"node":{"configured":1}
,"configured":{"east":1}
,"east":{"(ingress)":1}
,"(ingress)":{"west":1}
,"west":{"(egress)":1}
,"(egress)":{"nodes":1}
,"nodes":{"end":1}
,"end":{"points":1}
,"points":{"(nodes)":1}
,"(nodes)":{"unidirectional":1}
,"parameter":{"command":1}
,"remove":{"associated":1}
,"syntax":{"mpls-tp":1}
,"fwd-tunnel":{"name":1,"configure":1,"assoc-tnl1-fwd":1,"assoc-tnl-fwd":1}
,"name":{"rev-tunnel":1,"mpls-tp":1,"parameters":1,"forward":1,"maximum":1,"reverse":1}
,"rev-tunnel":{"name":1,"configure":1,"assoc-tnl1-rev":1,"assoc-tnl-rev":1}
,"parameters":{"fwd-tunnel":1}
,"configure":{"forward":1,"reverse-tunnel":1,"mode":1,"terminal":1}
,"forward":{"tunnel":1}
,"association":{"name":1}
,"maximum":{"characters":1}
,"characters":{"rev-tunnel":1,"command":1}
,"reverse-tunnel":{"association":1}
,"reverse":{"tunnel":1}
,"mode":{"configure":1,"examples":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"mpls-tp":1}
,"source":{"100":1}
,"100":{"1.1.1.1":1,"3.3.3.3":1}
,"1.1.1.1":{"destination":1,"(config-tnl)":1}
,"destination":{"100":1}
,"3.3.3.3":{"(config-tnl)":1,"destination":1}
,"(config-tnl)":{"tunnel-name":1,"tunnel-mode":1}
,"tunnel-name":{"assoc-tnl-fwd":1,"assoc-tnl-rev":1}
,"assoc-tnl-fwd":{"(config-tnl)":1,"rev-tunnel":1}
,"tunnel-mode":{"unidirectional":1}
,"(config-unidir-tnl)":{"nhfle-entry":1,"ilm-entry":1}
,"nhfle-entry":{"1001":1}
,"1001":{"eth1":1}
,"eth1":{"configure":1,"(config)":1}
,"assoc-tnl-rev":{"(config-tnl)":1}
,"ilm-entry":{"2002":1}
,"2002":{"eth1":1}
,"assoc-tnl1-fwd":{"rev-tunnel":1}
,"assoc-tnl1-rev":{"(config)":1}
}
;Search.control.loadWordPairs(pairs);
