var pairs =
{
"trill_api_add_bridge_master":{"function":1,"(struct":1}
,"function":{"adds":1,"call":1}
,"adds":{"bridge":1}
,"bridge":{"instances":1,"specifies":1,"structure":1}
,"instances":{"trill":1}
,"trill":{"master":1,"specified":1,"bridge":1}
,"master":{"trill":1,"syntax":1}
,"specified":{"bridges":1}
,"bridges":{"added":1}
,"added":{"trill":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"trill_api_add_bridge_master":1}
,"(struct":{"trill_bridge*bridge)":1}
,"trill_bridge*bridge)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bridge":1,"none":1}
,"specifies":{"instance":1}
,"instance":{"trill":1}
,"structure":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"result_ok":1}
,"result_ok":{"indicates":1}
,"indicates":{"function":1,"error":1}
,"call":{"executed":1}
,"executed":{"properly":1}
,"properly":{"result_error":1}
,"result_error":{"indicates":1}
,"error":{"occurred":1}
,"occurred":{"operation":1}
,"operation":{"performed":1}
}
;Search.control.loadWordPairs(pairs);
