var pairs =
{
"interface":{"api":1,"index":1,"name":1,"hsl_ifmgr_unset_acceptable_packet_types":1,"hsl_ifmgr_isbound":1,"bound":1,"interface":1,"pointer":1,"child":1,"given":1,"hsl_ifmgr_unset_flags2":1,"hsl_ifmgr_create_interface":1,"manager":1,"hsl_ifmgr_set_duplex":1,"hsl_ifmgr_set_autonego":1,"hsl_ifmgr_set_bandwidth":1,"hsl_ifmgr_set_hwaddr":1,"hsl_ifmgr_set_arp_ageing_timeout":1,"hsl_ifmgr_get_if_counters":1,"statistics":1}
,"api":{"functions":1}
,"functions":{"following":1,"hsl":1,"functions":1,"description":1}
,"following":{"table":1}
,"table":{"subsection":1}
,"subsection":{"includes":1}
,"includes":{"interface":1}
,"hsl":{"interface":1}
,"description":{"hsl_ifmgr_lookup_by_index":1}
,"hsl_ifmgr_lookup_by_index":{"finds":1}
,"finds":{"interface":1}
,"index":{"hsl_ifmgr_lookup_by_name":1}
,"hsl_ifmgr_lookup_by_name":{"finds":1}
,"name":{"hsl_ifmgr_set_acceptable_packet_types":1}
,"hsl_ifmgr_set_acceptable_packet_types":{"sets":1}
,"sets":{"packet":1,"flags":1,"mtu":1,"duplex":1,"auto-negotiations":1,"bandwidth":1,"hardware":1,"arp":1,"port":1}
,"packet":{"types":1}
,"types":{"accepted":1}
,"accepted":{"interface":1}
,"hsl_ifmgr_unset_acceptable_packet_types":{"unsets":1}
,"unsets":{"packet":1,"flags":1}
,"hsl_ifmgr_isbound":{"indicates":1}
,"indicates":{"whether":1}
,"whether":{"interface":1}
,"bound":{"hsl_ifmgr_bind":1}
,"hsl_ifmgr_bind":{"binds":1}
,"binds":{"interface":1}
,"pointer":{"hsl_ifmgr_bind2":1,"hsl_ifmgr_unbind":1,"hsl_ifmgr_unbind2":1,"hsl_ifmgr_bindings_add":1,"hsl_ifmgr_set_flags":1,"hsl_ifmgr_unset_flags":1}
,"hsl_ifmgr_bind2":{"binds":1}
,"hsl_ifmgr_unbind":{"unbinds":1}
,"unbinds":{"interface":1}
,"hsl_ifmgr_unbind2":{"unbinds":1}
,"hsl_ifmgr_bindings_add":{"binds":1}
,"child":{"ports":1}
,"ports":{"hsl_ifmgr_bindings_remove_all":1}
,"hsl_ifmgr_bindings_remove_all":{"remove":1}
,"remove":{"bindings":1}
,"bindings":{"hsl_ifmgr_set_flags2":1}
,"hsl_ifmgr_set_flags2":{"sets":1}
,"flags":{"interface":1}
,"given":{"interface":1}
,"hsl_ifmgr_set_flags":{"sets":1}
,"hsl_ifmgr_unset_flags2":{"unsets":1}
,"hsl_ifmgr_unset_flags":{"unsets":1}
,"hsl_ifmgr_create_interface":{"registers":1}
,"registers":{"interface":1}
,"manager":{"hsl_ifmgr_delete_interface":1,"hsl_ifmgr_delete_interface_api":1,"hsl_ifmgr_set_mtu":1}
,"hsl_ifmgr_delete_interface":{"deletes":1}
,"deletes":{"interface":1}
,"hsl_ifmgr_delete_interface_api":{"removes":1}
,"removes":{"interface":1}
,"hsl_ifmgr_set_mtu":{"sets":1}
,"mtu":{"interface":1}
,"hsl_ifmgr_set_duplex":{"sets":1}
,"duplex":{"interface":1}
,"hsl_ifmgr_set_autonego":{"sets":1}
,"auto-negotiations":{"interface":1}
,"hsl_ifmgr_set_bandwidth":{"sets":1}
,"bandwidth":{"interface":1}
,"hsl_ifmgr_set_hwaddr":{"sets":1}
,"hardware":{"address":1}
,"address":{"interface":1}
,"hsl_ifmgr_set_arp_ageing_timeout":{"sets":1}
,"arp":{"ageing":1}
,"ageing":{"time":1}
,"time":{"value":1}
,"value":{"interface":1}
,"hsl_ifmgr_get_if_counters":{"sets":1}
,"port":{"router":1,"hsl_ifmgr_collect_if_stat":1}
,"router":{"port":1}
,"hsl_ifmgr_collect_if_stat":{"processes":1}
,"processes":{"interface":1}
,"statistics":{"collection":1}
}
;Search.control.loadWordPairs(pairs);
