var pairs =
{
"show":{"vrf":1}
,"vrf":{"command":1,"show":1,"word":1,"ipi":1}
,"command":{"shows":1,"syntax":1,"mode":1}
,"shows":{"routing":1}
,"routing":{"information":1}
,"information":{"vrf":1}
,"syntax":{"show":1}
,"word":{"parameter":1,"displays":1}
,"parameter":{"word":1}
,"displays":{"name":1}
,"name":{"used":1}
,"used":{"identify":1}
,"identify":{"vrf":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"show":1}
,"ipi":{"vrf":1,"(id=1)":1}
,"(id=1)":{"default":1}
,"default":{"1:2":1}
,"1:2":{"interfaces":1}
,"interfaces":{"eth2":1}
,"eth2":{"export":1}
,"export":{"vpn":1}
,"vpn":{"route-target":1}
,"route-target":{"communities":1}
,"communities":{"rt:100:1":1}
,"rt:100:1":{"import":1}
,"import":{"vpn":1,"route-map":1}
}
;Search.control.loadWordPairs(pairs);
