var pairs =
{
"lock":{"feature":1,"interval":1,"data":1,"packet":1}
,"feature":{"applies":1}
,"applies":{"tunnel":1}
,"tunnel":{"configurations":1,"configure":1,"meg":1,"name":1}
,"configurations":{"example":1}
,"example":{"server":1}
,"server":{"layer":1}
,"layer":{"oam":1,"corouted":1,"transit":1,"(pe2)":1}
,"oam":{"data":1}
,"data":{"link":1}
,"link":{"client":1,"(config-itut-meg)":1,"eth3":1,"server":1}
,"client":{"layer":1}
,"corouted":{"tunnel":1}
,"configure":{"terminal":1,"mode":1,"interface":1,"meg":1,"service":1,"mep":1,"remote":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"interface":1}
,"mode":{"(config)":1,"eth1":1}
,"(config)":{"interface":1,"itut":1}
,"interface":{"eth3":1,"mode":1,"provider":1,"name":1}
,"eth3":{"enter":1,"associate":1,"(config-itut-mp)":1,"oper":1}
,"eth1":{"(config-if)":1}
,"(config-if)":{"mpls-tp":1,"exit":1}
,"mpls-tp":{"provider-interface":1}
,"provider-interface":{"30.1.1.1":1}
,"30.1.1.1":{"configure":1,"(config-if)":1}
,"provider":{"local":1,"interface":1}
,"local":{"identifier":1}
,"identifier":{"30.1.1.1":1,"2222":1}
,"exit":{"exit":1,"interface":1}
,"itut":{"meg":1}
,"meg":{"meg-d":1,"name":1,"brief":1,"index":1,"level":1}
,"meg-d":{"level":1,"configure":1}
,"level":{"configure":1,"(config-itut-meg)":1,"enable":1,"---------------------------------------------------------------------------mp-id":1}
,"name":{"meg-d":1,"eth3":1,"tnl_co":1}
,"(config-itut-meg)":{"service":1,"mep-id":1}
,"service":{"type":1,"datalink":1}
,"type":{"datalink":1,"data":1,"tunnel":1,"mep":1}
,"datalink":{"configure":1,"eth3":1,"meg":1}
,"mep-id":{"2222":1}
,"2222":{"configure":1,"(config-itut-mp)":1,"provider":1}
,"mep":{"identifier":1,"validation":1,"tunnel":1}
,"(config-itut-mp)":{"service":1,"lock":1,"rmep-id":1}
,"associate":{"data":1}
,"interval":{"level":1,"maintenance":1}
,"enable":{"lock":1}
,"transit":{"node":1}
,"node":{"client":1}
,"(pe2)":{"initiated":1}
,"initiated":{"(config-itut-mp)":1}
,"rmep-id":{"3333":1}
,"3333":{"icc":1}
,"icc":{"airtel":1}
,"airtel":{"umc":1}
,"umc":{"meg-d":1}
,"remote":{"mep":1}
,"validation":{"itut":1}
,"brief":{"maintenance":1}
,"maintenance":{"entity":1}
,"entity":{"group":1}
,"group":{"inairtel\u002Fmeg-d":1,"pe1":1,"inairtel\u002Fmeg-c":1}
,"inairtel\u002Fmeg-d":{"meg":1,",3333":1}
,"index":{"service":1}
,"---------------------------------------------------------------------------mp-id":{"2222":1,"type":1}
,"oper":{"status":1}
,"status":{"rmep":1}
,"rmep":{"inairtel\u002Fmeg-d":1,"inairtel\u002Fmeg-c":1}
,",3333":{"---------------------------------------------------------------------------lock":1}
,"---------------------------------------------------------------------------lock":{"valid":1}
,"valid":{"(refresh":1}
,"(refresh":{"interval":1}
,"pe1":{"itut":1}
,"inairtel\u002Fmeg-c":{"meg":1,"---------------------------------------------------------------------------remote":1}
,"tnl_co":{"oper":1}
,"---------------------------------------------------------------------------remote":{"lock":1}
,"packet":{"received":1}
}
;Search.control.loadWordPairs(pairs);
