var pairs =
{
"hal_ipv4_arp_add":{"function":1}
,"function":{"adds":1,"fails":1,"succeeds":1}
,"adds":{"ipv4":1}
,"ipv4":{"arp":1}
,"arp":{"entry":1,"output":1}
,"entry":{"syntax":1}
,"syntax":{"int":1}
,"int":{"hal_arp_entry_add":1}
,"hal_arp_entry_add":{"(struct":1}
,"(struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"*ipaddr":1}
,"*ipaddr":{"unsigned":1}
,"unsigned":{"char":1}
,"char":{"*mac_addr":1}
,"*mac_addr":{"u_int32_t":1}
,"u_int32_t":{"ifindex":1}
,"ifindex":{"u_int8_t":1,"interface":1}
,"u_int8_t":{"is_proxy_arp)":1}
,"is_proxy_arp)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ipaddr":1,"none":1}
,"ipaddr":{"address":1}
,"address":{"mac_addr":1,"ifindex":1}
,"mac_addr":{"mac":1}
,"mac":{"address":1}
,"interface":{"index":1}
,"index":{"is_proxy_arp":1}
,"is_proxy_arp":{"proxy":1}
,"proxy":{"arp":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"hal_ip_fib_not_exist":1}
,"hal_ip_fib_not_exist":{"function":1}
,"fails":{"hal_success":1}
,"hal_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
