var pairs =
{
"nsm_dcb_show_pfc_stats_by_bridge":{"function":1,"(struct":1}
,"function":{"displays":1,"succeeds":1}
,"displays":{"statistics":1}
,"statistics":{"pfc":1}
,"pfc":{"requests":1,"enabled":1}
,"requests":{"sent":1}
,"sent":{"given":1}
,"given":{"bridge":1}
,"bridge":{"syntax":1,"output":1,"found":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"nsm_dcb_show_pfc_stats_by_bridge":1}
,"(struct":{"cli":1}
,"cli":{"*cli":1,"cli":1,"structure":1}
,"*cli":{"char":1}
,"char":{"*bridge_name)":1}
,"*bridge_name)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"cli":1,"none":1}
,"structure":{"bridge_name":1}
,"bridge_name":{"bridge":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_dcb_api_set_success":1}
,"nsm_dcb_api_set_success":{"function":1}
,"succeeds":{"nsm_dcb_api_set_err_no_nm":1}
,"nsm_dcb_api_set_err_no_nm":{"nsm":1}
,"nsm":{"master":1}
,"master":{"found":1}
,"found":{"nsm_bridge_err_notfound":1,"nsm_dcb_api_set_err_no_dcbg":1,"nsm_dcb_api_set_err_no_pfc":1}
,"nsm_bridge_err_notfound":{"bridge":1}
,"nsm_dcb_api_set_err_no_dcbg":{"dcb":1}
,"dcb":{"bridge":1}
,"nsm_dcb_api_set_err_no_pfc":{"pfc":1}
}
;Search.control.loadWordPairs(pairs);
