var pairs =
{
"nsm_ovc_bw_profiling":{"function":1,"(struct":1}
,"function":{"configures":1,"succeeds":1}
,"configures":{"bandwidth":1}
,"bandwidth":{"profile":1}
,"profile":{"syntax":1,"parameter":1,"per":1,"configured":1,"active":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"nsm_ovc_bw_profiling":1}
,"(struct":{"interface":1}
,"interface":{"*ifp":1,"pointer":1,"information":1}
,"*ifp":{"struct":1}
,"struct":{"nsm_ingress_egress_ovc_svid":1}
,"nsm_ingress_egress_ovc_svid":{"*dual":1}
,"*dual":{"u_int64_t":1}
,"u_int64_t":{"cir":1,"eir":1}
,"cir":{"u_int32_t":1,"committed":1}
,"u_int32_t":{"cbs":1,"ebs":1}
,"cbs":{"u_int64_t":1,"committed":1}
,"eir":{"u_int32_t":1,"excess":1}
,"ebs":{"u_int8_t":1,"excess":1}
,"u_int8_t":{"coupling_flag":1,"color_mode":1,"bw_profile_type":1,"bw_profile_parameter)":1}
,"coupling_flag":{"u_int8_t":1,"whether":1}
,"color_mode":{"u_int8_t":1}
,"bw_profile_type":{"u_int8_t":1,"ingress":1}
,"bw_profile_parameter)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifp":1,"none":1}
,"ifp":{"interface":1}
,"pointer":{"dual":1,"nsm_ingress_egress_svid":1}
,"dual":{"pointer":1}
,"nsm_ingress_egress_svid":{"cir":1}
,"committed":{"information":1,"burst":1}
,"information":{"rate":1,"found":1}
,"rate":{"cbs":1,"eir":1,"ebs":1,"coupling_flag":1}
,"burst":{"rate":1}
,"excess":{"information":1,"burst":1}
,"whether":{"coupling":1,"color-aware":1}
,"coupling":{"flag":1}
,"flag":{"enabled":1}
,"enabled":{"disabled":1,"pal_false":1}
,"disabled":{"pal_true":1,"color-mode":1}
,"pal_true":{"enabled":1,"color-aware":1}
,"pal_false":{"disabled":1,"color-blind":1}
,"color-mode":{"whether":1}
,"color-aware":{"color-blind":1,"pal_false":1}
,"color-blind":{"pal_true":1,"bw_profile_type":1}
,"ingress":{"egress":1}
,"egress":{"constants":1}
,"constants":{"nsm\u002Fl2\u002Fnsm_vlan.h":1}
,"nsm\u002Fl2\u002Fnsm_vlan.h":{"nsm_ingress_policing":1,"nsm_bw_parameter_cir":1}
,"nsm_ingress_policing":{"nsm_egress_shaping":1}
,"nsm_egress_shaping":{"bw_profile_parameter":1}
,"bw_profile_parameter":{"bandwidth":1}
,"parameter":{"constants":1}
,"nsm_bw_parameter_cir":{"nsm_bw_parameter_cbs":1}
,"nsm_bw_parameter_cbs":{"nsm_bw_parameter_eir":1}
,"nsm_bw_parameter_eir":{"nsm_bw_parameter_ebs":1}
,"nsm_bw_parameter_ebs":{"nsm_bw_parameter_coupling_flag":1}
,"nsm_bw_parameter_coupling_flag":{"nsm_bw_parameter_color_mode":1}
,"nsm_bw_parameter_color_mode":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_vlan_err_ifp_not_bound":1,"already":1}
,"nsm_vlan_err_ifp_not_bound":{"interface":1}
,"found":{"nsm_l2_err_invalid_arg":1}
,"nsm_l2_err_invalid_arg":{"port":1}
,"port":{"configured":1}
,"configured":{"switching":1,"customer":1,"nsm_err_bw_profile_per_ovc_configured":1,"nsm_err_cos_already_configured":1,"part":1,"ovc":1}
,"switching":{"nsm_pro_vlan_err_invalid_mode":1}
,"nsm_pro_vlan_err_invalid_mode":{"port":1}
,"customer":{"edge":1}
,"edge":{"nsm_err_bw_profile_per_uni_configured":1}
,"nsm_err_bw_profile_per_uni_configured":{"bandwidth":1}
,"per":{"uni":1,"ovc":1,"cos":1}
,"uni":{"configured":1}
,"nsm_err_bw_profile_per_ovc_configured":{"bandwidth":1}
,"ovc":{"configured":1,"per":1}
,"nsm_err_cos_already_configured":{"cos":1}
,"cos":{"values":1,"nsm_l2_err_mem":1,"nsm_err_bw_profile_active":1}
,"already":{"configured":1}
,"part":{"cos":1}
,"nsm_l2_err_mem":{"nsm_err_bw_profile_per_cos_configured":1}
,"nsm_err_bw_profile_per_cos_configured":{"bandwidth":1}
,"nsm_err_bw_profile_active":{"bandwidth":1}
,"active":{"result_ok":1}
,"result_ok":{"function":1}
}
;Search.control.loadWordPairs(pairs);
