var pairs =
{
"pim":{"bsr-candidate":1,"(vrf":1}
,"bsr-candidate":{"command":1,"ifname":1,"(ifname":1,"eth0":1}
,"command":{"give":1,"disable":1,"syntax":1,"mode":1}
,"give":{"router":1}
,"router":{"candidate":1}
,"candidate":{"bsr":1,"command":1}
,"bsr":{"status":1,"candidate":1}
,"status":{"using":1}
,"using":{"specified":1}
,"specified":{"address":1}
,"address":{"interface":1}
,"interface":{"option":1,"<0-32>":1}
,"option":{"command":1}
,"disable":{"function":1}
,"function":{"command":1}
,"syntax":{"pim":1}
,"ifname":{"pim":1,"<0-32>":1,"specify":1}
,"<0-32>":{"pim":1,"<0-255>":1,"specify":1}
,"<0-255>":{"pim":1,"specify":1}
,"(vrf":{"name":1}
,"name":{"bsr-candidate":1,"specify":1,"vpn":1,"interface":1}
,"(ifname":{"pim":1,"parameters":1}
,"parameters":{"vrf":1}
,"vrf":{"vpn":1}
,"vpn":{"routing\u002Fforwarding":1}
,"routing\u002Fforwarding":{"instance":1}
,"instance":{"name":1,"ifname":1}
,"specify":{"name":1,"hash":1,"priority":1}
,"hash":{"mask":1}
,"mask":{"length":1}
,"length":{"selection":1}
,"selection":{"<0-255>":1}
,"priority":{"bsr":1}
,"mode":{"configure":1,"example":1}
,"configure":{"mode":1,"terminal":1}
,"example":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"pim":1}
}
;Search.control.loadWordPairs(pairs);
