var pairs =
{
"mib":{"overview":1,"contains":1,"definitions":1}
,"overview":{"rip-2":1}
,"rip-2":{"mib":1,"counters":1,"interfaces":1,"peer":1}
,"contains":{"global":1,"mib":1}
,"global":{"counters":1}
,"counters":{"used":1,"rip-2":1,"group":1}
,"used":{"detecting":1}
,"detecting":{"rip":1}
,"rip":{"incompatibilities":1}
,"incompatibilities":{"via":1}
,"via":{"interface-specific":1}
,"interface-specific":{"statistics":1}
,"statistics":{"configuration":1}
,"configuration":{"information":1}
,"information":{"relationships":1,"stored":1}
,"relationships":{"information":1}
,"stored":{"interface":1}
,"interface":{"peer":1,"table":1}
,"peer":{"tables":1,"table":1,"group":1}
,"tables":{"ripv2-mib.txt":1}
,"ripv2-mib.txt":{"file":1}
,"file":{"contains":1,"divided":1}
,"definitions":{"snmp":1,"rfc":1}
,"snmp":{"(based":1}
,"(based":{"definitions":1}
,"rfc":{"1724)":1}
,"1724)":{"file":1}
,"divided":{"three":1}
,"three":{"sections":1}
,"sections":{"global":1}
,"group":{"interface":1}
,"table":{"rip-2":1}
,"interfaces":{"groups":1}
,"groups":{"peer":1}
}
;Search.control.loadWordPairs(pairs);
