var pairs =
{
"internet":{"protocol":1,"key":1}
,"protocol":{"security":1,"suite":1}
,"security":{"(ipsec)":1,"payload":1}
,"(ipsec)":{"protocol":1}
,"suite":{"securing":1}
,"securing":{"communications":1}
,"communications":{"authenticating":1}
,"authenticating":{"encrypting":1}
,"encrypting":{"packets":1}
,"packets":{"during":1}
,"during":{"communication":1}
,"communication":{"session":1}
,"session":{"authentication":1}
,"authentication":{"header":1}
,"header":{"(ah)":1}
,"(ah)":{"encapsulating":1}
,"encapsulating":{"security":1}
,"payload":{"(esp)":1}
,"(esp)":{"main":1}
,"main":{"wire-level":1}
,"wire-level":{"protocols":1}
,"protocols":{"used":1}
,"used":{"ipsec":1,"however":1}
,"ipsec":{"either":1,"compliant":1}
,"either":{"esp":1}
,"esp":{"used":1}
,"however":{"two":1}
,"two":{"devices":1}
,"devices":{"share":1}
,"share":{"public":1}
,"public":{"key":1}
,"key":{"internet":1,"exchange":1}
,"exchange":{"(ike":1}
,"(ike":{"ikev2)":1}
,"ikev2)":{"rfc":1}
,"rfc":{"2401":1}
,"2401":{"specifies":1}
,"specifies":{"base":1}
,"base":{"architecture":1}
,"architecture":{"ipsec":1}
,"compliant":{"systems":1}
,"systems":{"rfcs":1}
,"rfcs":{"2402":1}
,"2402":{"2406":1}
,"2406":{"2407":1}
,"2407":{"provide":1}
,"provide":{"details":1}
,"details":{"ipsec":1}
}
;Search.control.loadWordPairs(pairs);
