var pairs =
{
"g8032":{"configure":1}
,"configure":{"switching":1,"mode":1,"terminal":1}
,"switching":{"command":1,"mode":1,"ring-id":1}
,"command":{"enter":1,"syntax":1,"mode":1}
,"enter":{"g8032":1}
,"mode":{"ethernet":1,"configure":1,"examples":1}
,"ethernet":{"ring":1}
,"ring":{"protection":1}
,"protection":{"group":1}
,"group":{"provider":1,"ringid":1,"<1-65535>":1}
,"provider":{"backbone":1}
,"backbone":{"bridging":1,"backbone":1,"bridge":1}
,"bridging":{"supported":1}
,"supported":{"zebic":1}
,"zebic":{"releases":1}
,"releases":{"command":1}
,"syntax":{"g8032":1}
,"ring-id":{"ringid":1,"ethernet":1,"bridge":1}
,"ringid":{"bridge":1,"ethernet":1}
,"bridge":{"<1-32>":1,"(<1-32>":1,"bridge":1,"backbone":1,"command":1,"(g8032-config-switching)":1}
,"<1-32>":{"g8032":1,"bridge":1}
,"(<1-32>":{"backbone)":1}
,"backbone)":{"parameters":1}
,"parameters":{"ring-id":1}
,"<1-65535>":{"bridge":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"g8032":1}
}
;Search.control.loadWordPairs(pairs);
