var pairs =
{
"ldp_api_get_default_label_retention_mode":{"call":1,"(struct":1}
,"call":{"gets":1}
,"gets":{"default":1}
,"default":{"label":1}
,"label":{"retention":1}
,"retention":{"mode":1}
,"mode":{"syntax":1,"value":1,"output":1,"liberal":1,"conservative":1}
,"syntax":{"int":1}
,"int":{"ldp_api_get_default_label_retention_mode":1,"mode)":1}
,"(struct":{"ldp":1}
,"ldp":{"*ldp":1,"ldp":1,"instance":1}
,"*ldp":{"int":1}
,"mode)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ldp":1,"none":1}
,"instance":{"mode":1,"found":1}
,"value":{"label":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"liberal_retention_mode":1}
,"liberal_retention_mode":{"retention":1}
,"liberal":{"conservative_retention_mode":1}
,"conservative_retention_mode":{"retention":1}
,"conservative":{"ldp_error":1}
,"ldp_error":{"ldp":1}
}
;Search.control.loadWordPairs(pairs);
