var pairs =
{
"ospf_unset_frr_tie_break_prority_all":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"called":1,"succeeds":1}
,"sets":{"priority":1}
,"priority":{"types":1}
,"types":{"fast":1}
,"fast":{"reroute":1}
,"reroute":{"repair":1}
,"repair":{"paths":1}
,"paths":{"default":1}
,"default":{"values":1,"priorities":1}
,"values":{"function":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"fast-reroute":1}
,"fast-reroute":{"tie-break":1}
,"tie-break":{"default":1}
,"priorities":{"primary_path":1}
,"primary_path":{"interface_disjoint":1}
,"interface_disjoint":{"node_protecting":1}
,"node_protecting":{"broadcast_interface_disjoint":1}
,"broadcast_interface_disjoint":{"syntax":1}
,"syntax":{"int32_t":1}
,"int32_t":{"ospf_unset_frr_tie_break_prority_all":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"int":1,"virtual":1}
,"int":{"proc_id)":1}
,"proc_id)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"found":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"proc_id":1}
,"proc_id":{"process":1}
,"process":{"ospf":1,"valid":1,"exist":1}
,"ospf":{"instance":1}
,"instance":{"65535>":1}
,"65535>":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf_api_set_success":1}
,"ospf_api_set_success":{"function":1}
,"succeeds":{"ospf_api_set_err_process_id_invalid":1}
,"ospf_api_set_err_process_id_invalid":{"given":1}
,"given":{"process":1}
,"valid":{"(outside":1}
,"(outside":{"65535":1}
,"65535":{"bounds)":1}
,"bounds)":{"ospf_api_set_err_process_not_exist":1}
,"ospf_api_set_err_process_not_exist":{"given":1}
,"exist":{"ospf_api_set_err_vr_not_exist":1}
,"ospf_api_set_err_vr_not_exist":{"virtual":1}
}
;Search.control.loadWordPairs(pairs);
