var pairs =
{
"maintenance":{"communication":1}
,"communication":{"channel":1}
,"channel":{"ethernet":1,"(mcc)":1}
,"ethernet":{"maintenance":1}
,"(mcc)":{"used":1}
,"used":{"perform":1}
,"perform":{"remote":1}
,"remote":{"management":1,"mep":1}
,"management":{"pair":1}
,"pair":{"meps":1}
,"meps":{"zebos-xp":1}
,"zebos-xp":{"mcc":1}
,"mcc":{"implementation":1,"remote":1,"frame":1}
,"implementation":{"handles":1}
,"handles":{"just":1}
,"just":{"messaging":1}
,"messaging":{"function":1}
,"function":{"means":1}
,"means":{"mcc":1}
,"mep":{"identified":1}
,"identified":{"mcc":1}
,"frame":{"payload":1}
,"payload":{"handling":1}
,"handling":{"done":1}
}
;Search.control.loadWordPairs(pairs);
