var pairs =
{
"itut":{"meg":1,"maintenance":1}
,"meg":{"command":1,"mode":1,"umc":1,"code":1,"new12":1}
,"command":{"configure":1,"changes":1,"remove":1,"syntax":1,"mode":1}
,"configure":{"itut":1,"mode":1,"terminal":1}
,"maintenance":{"entity":1}
,"entity":{"group":1}
,"group":{"(meg)":1}
,"(meg)":{"monitor":1}
,"monitor":{"mpls-tp":1}
,"mpls-tp":{"path":1}
,"path":{"running":1}
,"running":{"oam":1}
,"oam":{"functions":1}
,"functions":{"command":1}
,"changes":{"itut":1}
,"mode":{"parameter":1,"configure":1,"examples":1}
,"parameter":{"command":1}
,"remove":{"meg":1}
,"syntax":{"itut":1}
,"umc":{"(level":1,"parameters":1,"unique":1}
,"(level":{"<0-7>":1}
,"<0-7>":{"itut":1,"level":1}
,"parameters":{"umc":1}
,"unique":{"meg":1}
,"code":{"1-5":1}
,"1-5":{"characters":1}
,"characters":{"excluding":1}
,"excluding":{"forward":1}
,"forward":{"slash":1}
,"slash":{"(\u002F)":1}
,"(\u002F)":{"<0-7>":1}
,"level":{"command":1,"(config-itut-meg)":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"itut":1}
,"new12":{"level":1}
,"(config-itut-meg)":{"(config)":1}
}
;Search.control.loadWordPairs(pairs);
