var pairs =
{
"ethernet":{"protection":1,"path":1}
,"protection":{"switching":1,"per-vlan":1}
,"switching":{"zebos-xp":1,"(aps)":1}
,"zebos-xp":{"supports":1}
,"supports":{"point-to-point":1}
,"point-to-point":{"ethernet":1}
,"path":{"protection":1}
,"per-vlan":{"basis":1}
,"basis":{"accordance":1}
,"accordance":{"requirements":1}
,"requirements":{"itu-t":1}
,"itu-t":{"g.8031":1}
,"g.8031":{"recommendation":1}
,"recommendation":{"single":1}
,"single":{"physical":1}
,"physical":{"port":1}
,"port":{"protected":1,"vlans":1}
,"protected":{"vlans":1}
,"vlans":{"non-protected":1,"(non-protected":1,"managed":1,"spanning":1}
,"non-protected":{"vlans":1}
,"(non-protected":{"vlans":1}
,"managed":{"spanning":1}
,"spanning":{"tree":1}
,"tree":{"protocol.)":1,"control":1}
,"protocol.)":{"allows":1}
,"allows":{"port":1}
,"control":{"others":1}
,"others":{"automated":1}
,"automated":{"protection":1}
,"(aps)":{"control":1}
}
;Search.control.loadWordPairs(pairs);
