var pairs =
{
"trill_get_next_rbridge_trillnbr_mtu":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"mtu":1}
,"mtu":{"size":1}
,"size":{"neighbor":1,"return":1}
,"neighbor":{"is-is":1}
,"is-is":{"communication":1}
,"communication":{"purposes":1}
,"purposes":{"syntax":1}
,"syntax":{"int":1}
,"int":{"trill_get_next_rbridge_trillnbr_mtu":1,"indexlen":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"integer":1}
,"u_int32_t":{"*instance":1,"*ret)":1}
,"*instance":{"struct":1}
,"struct":{"trill_mac_addr":1}
,"trill_mac_addr":{"*macaddr":1}
,"*macaddr":{"int":1}
,"indexlen":{"u_int32_t":1,"integer":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"ret":1}
,"integer":{"contains":1,"containing":1}
,"contains":{"trill":1}
,"trill":{"identifier":1,"instance":1}
,"identifier":{"instance":1}
,"instance":{"integer":1,"macaddr":1}
,"macaddr":{"octet":1,"trill_api_get_error":1,"found":1}
,"octet":{"string":1}
,"string":{"containing":1}
,"containing":{"mac":1,"length":1,"mtu":1}
,"mac":{"address":1}
,"address":{"indexlen":1}
,"length":{"index":1}
,"index":{"output":1}
,"output":{"parameters":1}
,"ret":{"integer":1}
,"return":{"value":1}
,"value":{"trill_api_get_success":1}
,"trill_api_get_success":{"valid":1}
,"valid":{"instance":1}
,"trill_api_get_error":{"valid":1}
}
;Search.control.loadWordPairs(pairs);
