var pairs =
{
"ipv6":{"ospf":1}
,"ospf":{"demand-circuit":1}
,"demand-circuit":{"command":1,"(instance-id":1,"(config-if)":1}
,"command":{"enable":1,"disable":1,"syntax":1,"mode":1}
,"enable":{"hello":1}
,"hello":{"suppression":1}
,"suppression":{"lsa":1,"sent":1,"command":1}
,"lsa":{"suppression":1}
,"sent":{"ospfv3":1}
,"ospfv3":{"interface":1}
,"interface":{"hello\u2019s":1,"mode":1,"eth1":1}
,"hello\u2019s":{"lsa\u2019s":1}
,"lsa\u2019s":{"suppressed":1}
,"suppressed":{"point-to-point":1,"broadcast":1}
,"point-to-point":{"point-to-multipoint":1}
,"point-to-multipoint":{"links":1}
,"links":{"lsa\u2019s":1}
,"broadcast":{"link":1}
,"link":{"parameter":1}
,"parameter":{"command":1}
,"disable":{"hello":1}
,"syntax":{"ipv6":1}
,"(instance-id":{"<0-255>)":1}
,"<0-255>)":{"ipv6":1,"parameters":1}
,"parameters":{"instance-id":1}
,"instance-id":{"specify":1}
,"specify":{"instance":1}
,"instance":{"<0-255>":1,"command":1}
,"<0-255>":{"specify":1}
,"mode":{"interface":1,"examples":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth1":{"(config-if)":1}
,"(config-if)":{"ipv6":1}
}
;Search.control.loadWordPairs(pairs);
