var pairs =
{
"mrib_snmp_api_get_next_mrt_rttype":{"function":1,"(const":1}
,"function":{"gets":1,"succeeds":1,"fails":1}
,"gets":{"reason":1}
,"reason":{"next":1,"unicast":1}
,"next":{"given":1,"hop":1}
,"given":{"route":1}
,"route":{"placed":1,"normally":1,"explicitly":1}
,"placed":{"(logical)":1,"unicast":1,"mrib":1}
,"(logical)":{"mrib":1}
,"mrib":{"value":1,"(instead":1,"routing":1}
,"value":{"unicast":1,"multicast":1}
,"unicast":{"means":1,"rib":1,"multicast":1}
,"means":{"route":1}
,"normally":{"placed":1}
,"rib":{"placed":1}
,"(instead":{"addition)":1}
,"addition)":{"due":1}
,"due":{"local":1}
,"local":{"configuration":1}
,"configuration":{"running":1}
,"running":{"pim":1}
,"pim":{"rip":1}
,"rip":{"value":1}
,"multicast":{"means":1,"routing":1,"next":1,"return":1}
,"explicitly":{"added":1}
,"added":{"mrib":1}
,"routing":{"protocol":1,"syntax":1}
,"protocol":{"static":1}
,"static":{"multicast":1}
,"syntax":{"int":1}
,"int":{"mrib_snmp_api_get_next_mrt_rttype":1}
,"(const":{"u_int32_t":1}
,"u_int32_t":{"vr_id":1,"*val)":1}
,"vr_id":{"const":1,"virtual":1}
,"const":{"vrf_id_t":1}
,"vrf_id_t":{"vrf_id":1}
,"vrf_id":{"struct":1,"vpn":1}
,"struct":{"mrib_snmp_api_mrt_index":1}
,"mrib_snmp_api_mrt_index":{"*index":1}
,"*index":{"u_int32_t":1}
,"*val)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"index":1}
,"virtual":{"router":1}
,"router":{"vrf_id":1}
,"vpn":{"routing\u002Fforwarding":1}
,"routing\u002Fforwarding":{"instance":1}
,"instance":{"output":1}
,"output":{"parameters":1}
,"index":{"index":1,"entry":1}
,"entry":{"multicast":1}
,"hop":{"table":1}
,"table":{"val":1}
,"val":{"reason":1}
,"return":{"values":1}
,"values":{"mrib_api_get_success":1}
,"mrib_api_get_success":{"function":1}
,"succeeds":{"mrib_api_get_error":1}
,"mrib_api_get_error":{"function":1}
}
;Search.control.loadWordPairs(pairs);
