var pairs =
{
"mplstunnelresourcetable":{"table":1}
,"table":{"indicates":1,"tunnels":1,"object":1}
,"indicates":{"resources":1}
,"resources":{"required":1,"pointing":1,"point":1}
,"required":{"tunnel":1}
,"tunnel":{"multiple":1}
,"multiple":{"tunnels":1}
,"tunnels":{"share":1}
,"share":{"resources":1}
,"pointing":{"entry":1}
,"entry":{"table":1}
,"point":{"separate":1}
,"separate":{"entries":1}
,"entries":{"table":1}
,"object":{"type":1}
,"type":{"syntax":1}
,"syntax":{"access":1}
,"access":{"functions":1}
,"functions":{"mplstunnelresourceindexnext":1}
,"mplstunnelresourceindexnext":{"unsigned32":1}
,"unsigned32":{"read-only":1,"read-create":1}
,"read-only":{"rsvp_snmp_get_tn_resource_ix_next":1}
,"rsvp_snmp_get_tn_resource_ix_next":{"mplstunnelresourcemaxrate":1}
,"mplstunnelresourcemaxrate":{"mplsbitrate":1}
,"mplsbitrate":{"read-create":1}
,"read-create":{"rsvp_snmp_get_tn_resource_maxrate":1,"rsvp_snmp_get_tn_resource_meanrate":1,"rsvp_snmp_get_tn_resource_maxburstsize":1,"rsvp_snmp_get_tn_resource_meanburstsize":1,"rsvp_snmp_get_tn_resource_exburstsize":1,"rsvp_snmp_get_tn_resource_frequency":1,"rsvp_snmp_get_tn_resource_weight":1,"rsvp_snmp_get_tn_resource_rowstatus":1,"rsvp_snmp_get_tn_resource_storagetype":1}
,"rsvp_snmp_get_tn_resource_maxrate":{"rsvp_snmp_get_next_tn_resource_maxrate":1}
,"rsvp_snmp_get_next_tn_resource_maxrate":{"rsvp_snmp_set_tn_resource_maxrate":1}
,"rsvp_snmp_set_tn_resource_maxrate":{"mplstunnelresourcemeanrate":1}
,"mplstunnelresourcemeanrate":{"mplsbitrate":1}
,"rsvp_snmp_get_tn_resource_meanrate":{"rsvp_snmp_get_next_tn_resource_meanrate":1}
,"rsvp_snmp_get_next_tn_resource_meanrate":{"rsvp_snmp_set_tn_resource_meanrate":1}
,"rsvp_snmp_set_tn_resource_meanrate":{"mplstunnelresourcemaxburstsize":1}
,"mplstunnelresourcemaxburstsize":{"mplsburstsize":1}
,"mplsburstsize":{"read-create":1}
,"rsvp_snmp_get_tn_resource_maxburstsize":{"rsvp_snmp_get_next_tn_resource_maxburstsize":1}
,"rsvp_snmp_get_next_tn_resource_maxburstsize":{"rsvp_snmp_set_tn_resource_maxburstsize":1}
,"rsvp_snmp_set_tn_resource_maxburstsize":{"mplstunnelresourcemeanburstsize":1}
,"mplstunnelresourcemeanburstsize":{"mplsburstsize":1}
,"rsvp_snmp_get_tn_resource_meanburstsize":{"rsvp_snmp_get_next_tn_resource_meanburstsize":1}
,"rsvp_snmp_get_next_tn_resource_meanburstsize":{"rsvp_snmp_set_tn_resource_meanburstsize":1}
,"rsvp_snmp_set_tn_resource_meanburstsize":{"mplstunnelresourceexburstsize":1}
,"mplstunnelresourceexburstsize":{"mplsburstsize":1}
,"rsvp_snmp_get_tn_resource_exburstsize":{"rsvp_snmp_get_next_tn_resource_exburstsize":1}
,"rsvp_snmp_get_next_tn_resource_exburstsize":{"rsvp_snmp_set_tn_resource_exburstsize":1}
,"rsvp_snmp_set_tn_resource_exburstsize":{"mplstunnelresourcefrequency":1}
,"mplstunnelresourcefrequency":{"integer":1}
,"integer":{"read-create":1}
,"rsvp_snmp_get_tn_resource_frequency":{"rsvp_snmp_get_next_tn_resource_frequency":1}
,"rsvp_snmp_get_next_tn_resource_frequency":{"rsvp_snmp_set_tn_resource_frequency":1}
,"rsvp_snmp_set_tn_resource_frequency":{"mplstunnelresourceweight":1}
,"mplstunnelresourceweight":{"unsigned32":1}
,"rsvp_snmp_get_tn_resource_weight":{"rsvp_snmp_get_next_tn_resource_weight":1}
,"rsvp_snmp_get_next_tn_resource_weight":{"rsvp_snmp_set_tn_resource_weight":1}
,"rsvp_snmp_set_tn_resource_weight":{"mplstunnelresourcerowstatus":1}
,"mplstunnelresourcerowstatus":{"rowstatus":1}
,"rowstatus":{"read-create":1}
,"rsvp_snmp_get_tn_resource_rowstatus":{"rsvp_snmp_get_next_tn_resource_rowstatus":1}
,"rsvp_snmp_get_next_tn_resource_rowstatus":{"rsvp_snmp_set_tn_resource_rowstatus":1}
,"rsvp_snmp_set_tn_resource_rowstatus":{"mplstunnelresourcestoragetype":1}
,"mplstunnelresourcestoragetype":{"storagetype":1}
,"storagetype":{"read-create":1}
,"rsvp_snmp_get_tn_resource_storagetype":{"rsvp_snmp_get_next_tn_resource_storagetype":1}
,"rsvp_snmp_get_next_tn_resource_storagetype":{"rsvp_snmp_set_tn_resource_storagetype":1}
}
;Search.control.loadWordPairs(pairs);
