var pairs =
{
"subnet":{"multiple":1,"configured":1}
,"multiple":{"ospf":1,"areas":1}
,"ospf":{"areas":1,"enabled":1}
,"areas":{"multiple":1,"subnet":1,"area":1,"multi-area-adjacency":1}
,"configured":{"two":1}
,"two":{"routers":1}
,"routers":{"diagram":1,"multi-area":1,"(abrs)":1}
,"diagram":{"below":1}
,"below":{"ospf":1}
,"enabled":{"area":1}
,"area":{"area":1,"link":1,"border":1,"virtual":1}
,"link":{"available":1,"provides":1,"restriction":1}
,"available":{"two":1}
,"multi-area":{"adjacency":1}
,"adjacency":{"allows":1,"multiple":1,"reaches":1,"packets":1}
,"allows":{"establishing":1}
,"establishing":{"adjacency":1}
,"border":{"routers":1}
,"(abrs)":{"specified":1}
,"specified":{"interface":1}
,"interface":{"abr":1}
,"abr":{"associated":1}
,"associated":{"multiple":1}
,"multi-area-adjacency":{"internally":1}
,"internally":{"implements":1}
,"implements":{"point-to-point":1}
,"point-to-point":{"functionality":1,"link":1}
,"functionality":{"once":1}
,"once":{"adjacency":1}
,"reaches":{"full":1}
,"full":{"state":1}
,"state":{"point-to-point":1}
,"provides":{"topological":1}
,"topological":{"path":1}
,"path":{"area":1}
,"virtual":{"link":1}
,"restriction":{"multi\u2011area":1}
,"multi\u2011area":{"adjacency":1}
,"packets":{"always":1}
,"always":{"backbone":1}
,"backbone":{"subnet":1}
}
;Search.control.loadWordPairs(pairs);
