var pairs =
{
"establish":{"rsvp":1}
,"rsvp":{"trunks":1,"trunk":1,"daemon":1}
,"trunks":{"using":1,"configured":1}
,"using":{"cspf":1}
,"cspf":{"cspf":1,"((constraint-based":1,"server":1,"returns":1,"enabled":1}
,"((constraint-based":{"shortest":1}
,"shortest":{"path":1}
,"path":{"first)":1,"rsvp":1,"network":1,"called":1,"sends":1,"message":1}
,"first)":{"used":1}
,"used":{"calculate":1}
,"calculate":{"path":1}
,"trunk":{"rsvp":1,"cspf-enabled":1}
,"daemon":{"(rsvpd)":1,"explicit":1}
,"(rsvpd)":{"sends":1}
,"sends":{"request":1,"path":1}
,"request":{"cspf":1}
,"server":{"compute":1}
,"compute":{"path":1}
,"network":{"reach":1}
,"reach":{"destination":1}
,"destination":{"cspf":1}
,"returns":{"hop-by-hop":1}
,"hop-by-hop":{"path":1}
,"called":{"explicit":1}
,"explicit":{"route":1}
,"route":{"rsvp":1,"object":1}
,"object":{"(ero)":1}
,"(ero)":{"router":1}
,"router":{"along":1}
,"along":{"path":1}
,"message":{"nexthop":1}
,"nexthop":{"specified":1}
,"specified":{"ero":1}
,"ero":{"zebos-xp":1}
,"zebos-xp":{"cspf":1}
,"enabled":{"default":1}
,"default":{"trunk":1}
,"cspf-enabled":{"automatically":1}
,"automatically":{"configuration":1}
,"configuration":{"assumes":1,"done":1}
,"assumes":{"basic":1}
,"basic":{"mpls":1}
,"mpls":{"configuration":1}
,"done":{"prior":1}
,"prior":{"configuration.there":1}
,"configuration.there":{"two":1}
,"two":{"rsvp":1}
,"configured":{"l1-2":1}
,"l1-2":{"l1-2":1,"mpls-te":1}
,"mpls-te":{"topology":1}
}
;Search.control.loadWordPairs(pairs);
