var pairs =
{
"pal_tzval":{"data":1,"{s_int32_t":1}
,"data":{"structure":1}
,"structure":{"provides":1}
,"provides":{"time":1}
,"time":{"zone":1,"(gmt)":1,"(dst)":1}
,"zone":{"information":1}
,"information":{"defined":1}
,"defined":{"pal\u002Fdummy\u002Fpal_time.h":1}
,"pal\u002Fdummy\u002Fpal_time.h":{"type":1}
,"type":{"definition":1}
,"definition":{"tz_minuteswest":1,"struct":1}
,"tz_minuteswest":{"minutes":1,"\u002F*how":1}
,"minutes":{"west":1,"*west*of":1}
,"west":{"greenwich":1}
,"greenwich":{"mean":1}
,"mean":{"time":1}
,"(gmt)":{"tz_dsttime":1}
,"tz_dsttime":{"nonzero":1,"\u002F*nonzero":1}
,"nonzero":{"ever":1}
,"ever":{"daylight":1,"dst":1}
,"daylight":{"savings":1}
,"savings":{"time":1}
,"(dst)":{"definition":1}
,"struct":{"pal_tzval":1}
,"{s_int32_t":{"tz_minuteswest":1}
,"\u002F*how":{"minutes":1}
,"*west*of":{"gmt":1}
,"gmt":{"*\u002Fint":1}
,"*\u002Fint":{"tz_dsttime":1}
,"\u002F*nonzero":{"ever":1}
,"dst":{"*\u002F}":1}
}
;Search.control.loadWordPairs(pairs);
