var pairs =
{
"routing":{"information":1,"forwarding":1,"protocol":1}
,"information":{"protocol":1,"rip":1,"ce-router":1,"advertised":1,"learned":1}
,"protocol":{"vpn":1,"process":1}
,"vpn":{"commands":1,"rip":1,"service":1,"customer":1}
,"commands":{"chapter":1,"commands":1,"available":1,"vpn":1,"display":1,"address-family":1}
,"chapter":{"provides":1,"contains":1}
,"provides":{"information":1}
,"rip":{"vpn":1,"provider":1,"receive":1,"pe-ce":1,"commands":1,"debug":1,"interface":1,"vrf":1}
,"available":{"rip":1,"router":1,"address":1}
,"provider":{"edge":1}
,"edge":{"(pe)":1,"(ce)":1}
,"(pe)":{"customer":1}
,"customer":{"edge":1,"interface":1}
,"(ce)":{"feature":1}
,"feature":{"supported":1,"address":1}
,"supported":{"using":1,"chapter":1}
,"using":{"commands":1,"standard":1}
,"receive":{"information":1}
,"ce-router":{"places":1}
,"places":{"connected":1}
,"connected":{"virtual":1}
,"virtual":{"routing":1}
,"forwarding":{"(vrf)":1}
,"(vrf)":{"receiving":1}
,"receiving":{"interface":1}
,"interface":{"information":1,"associated":1,"mode":1,"vrf":1}
,"advertised":{"across":1}
,"across":{"mpls\u002Fvpn":1}
,"mpls\u002Fvpn":{"backbone":1}
,"backbone":{"pe-routers":1}
,"pe-routers":{"provide":1}
,"provide":{"vpn":1}
,"service":{"pe-router":1}
,"pe-router":{"needs":1}
,"needs":{"configured":1}
,"configured":{"routing":1}
,"learned":{"vpn":1}
,"associated":{"particular":1}
,"particular":{"vrf":1}
,"vrf":{"achieved":1,"information":1,"address-family":1,"exit-address-family":1,"show":1}
,"achieved":{"using":1}
,"standard":{"routing":1}
,"process":{"(rip":1}
,"(rip":{"ospf":1}
,"ospf":{"bgp":1}
,"bgp":{"static":1}
,"static":{"routes":1}
,"routes":{"etc)":1}
,"etc)":{"enable":1}
,"enable":{"rip":1}
,"pe-ce":{"feature":1}
,"address":{"family":1}
,"family":{"sub-mode":1,"mode":1}
,"sub-mode":{"used":1}
,"used":{"rip":1}
,"router":{"interface":1}
,"mode":{"available":1,"additionally":1}
,"additionally":{"rip":1}
,"debug":{"commands":1}
,"display":{"additional":1}
,"additional":{"vrf":1}
,"contains":{"following":1}
,"following":{"commands":1}
,"address-family":{"ipv4":1,"ipv6":1}
,"ipv4":{"vrf":1}
,"ipv6":{"vrf":1}
,"exit-address-family":{"show":1}
,"show":{"rip":1,"vrf":1}
}
;Search.control.loadWordPairs(pairs);
