var pairs =
{
"validation":{"dut":1}
,"dut":{"show":1}
,"show":{"dot1x":1}
,"dot1x":{"802.1x":1}
,"802.1x":{"port-based":1,"info":1}
,"port-based":{"authentication":1}
,"authentication":{"enabled":1}
,"enabled":{"radius":1}
,"radius":{"server":1,"message":1,"client":1}
,"server":{"address":1,"[root@xsupplicant1":1}
,"address":{"10.10.10.40:1812":1,"configured":1,"0008.c73b.05ce":1}
,"10.10.10.40:1812":{"next":1}
,"next":{"radius":1}
,"message":{"radius":1}
,"client":{"address":1}
,"configured":{"802.1x":1}
,"info":{"interface":1}
,"interface":{"eth0":1}
,"eth0":{"supplicant":1}
,"supplicant":{"name":1,"address":1}
,"name":{"testuser":1}
,"testuser":{"supplicant":1}
,"0008.c73b.05ce":{"portenabled":1}
,"portenabled":{"true":1}
,"true":{"-portcontrol":1}
,"-portcontrol":{"auto":1}
,"auto":{"portstatus":1,"pae":1}
,"portstatus":{"authorized":1}
,"authorized":{"-currentid":1}
,"-currentid":{"reauthenticate":1}
,"reauthenticate":{"disabled":1}
,"disabled":{"reauthperiod":1}
,"reauthperiod":{"3600":1}
,"3600":{"abort:f":1}
,"abort:f":{"fail:f":1}
,"fail:f":{"start:f":1}
,"start:f":{"timeout:f":1}
,"timeout:f":{"success:t":1}
,"success:t":{"pae":1}
,"pae":{"state":1,"reauthcount":1,"quietperiod":1}
,"state":{"authenticated":1,"idle":1}
,"authenticated":{"-portmode":1}
,"-portmode":{"auto":1}
,"reauthcount":{"-rxrespid":1}
,"-rxrespid":{"pae":1}
,"quietperiod":{"-reauthmax":1}
,"-reauthmax":{"-txperiod":1}
,"-txperiod":{"state":1}
,"idle":{"-reqcount":1}
,"-reqcount":{"-idfromserver":1}
,"-idfromserver":{"supptimeout":1}
,"supptimeout":{"-servertimeout":1}
,"-servertimeout":{"-maxreq":1}
,"-maxreq":{"admincontrolleddirections":1}
,"admincontrolleddirections":{"-opercontrolleddirections":1}
,"-opercontrolleddirections":{"bridgedetected":1}
,"bridgedetected":{"false":1}
,"false":{"rxkey":1,"keyavailable":1,"-keytxenabled":1,"xsupplicant":1}
,"rxkey":{"false":1}
,"keyavailable":{"false":1}
,"-keytxenabled":{"false":1}
,"xsupplicant":{"able":1}
,"able":{"ping":1}
,"ping":{"radius":1,"10.10.10.40":1,"3.3.3.1":1}
,"[root@xsupplicant1":{"root]":1}
,"root]":{"ping":1}
,"10.10.10.40":{"ping":1,"icmp_seq=1":1,"icmp_seq=2":1}
,"3.3.3.1":{"(3.3.3.1)":1}
,"(3.3.3.1)":{"(84)":1}
,"(84)":{"bytes":1}
,"bytes":{"data":1,"10.10.10.40":1}
,"data":{"bytes":1}
,"icmp_seq=1":{"ttl=64":1}
,"ttl=64":{"time=0.606":1,"time=0.551":1}
,"time=0.606":{"bytes":1}
,"icmp_seq=2":{"ttl=64":1}
}
;Search.control.loadWordPairs(pairs);
