var pairs =
{
"ipv6":{"ospf":1}
,"ospf":{"cost":1,"indicates":1}
,"cost":{"command":1,"(or":1,"default":1,"<1-65535>":1,"ipv6":1,"instance-id":1,"specify":1}
,"command":{"specify":1,"reset":1,"syntax":1,"mode":1}
,"specify":{"link-cost":1,"link-state":1,"instance":1}
,"link-cost":{"described":1}
,"described":{"lsas":1}
,"lsas":{"cost":1}
,"(or":{"metric)":1}
,"metric)":{"interface":1}
,"interface":{"ospf":1,"value":1,"mode":1,"eth0":1}
,"indicates":{"overhead":1}
,"overhead":{"required":1}
,"required":{"send":1}
,"send":{"packets":1}
,"packets":{"across":1}
,"across":{"certain":1}
,"certain":{"interface":1}
,"value":{"taken":1,"instance-id":1}
,"taken":{"describe":1}
,"describe":{"link":1}
,"link":{"state":1}
,"state":{"information":1}
,"information":{"used":1}
,"used":{"route":1}
,"route":{"calculation":1}
,"calculation":{"parameter":1}
,"parameter":{"command":1}
,"reset":{"cost":1}
,"default":{"command":1,"value":1}
,"syntax":{"ipv6":1}
,"<1-65535>":{"ipv6":1,"instance-id":1,"specify":1}
,"instance-id":{"<0-255>":1,"specify":1}
,"<0-255>":{"ipv6":1,"parameters":1,"specify":1}
,"parameters":{"cost":1}
,"link-state":{"metric":1}
,"metric":{"<1-65535>":1,"default":1}
,"instance":{"<0-255>":1,"command":1}
,"mode":{"interface":1,"examples":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"ipv6":1}
}
;Search.control.loadWordPairs(pairs);
