var pairs =
{
"bridge-group":{"spanning-tree":1,"<1-32>":1,"specify":1}
,"spanning-tree":{"command":1,"(disable":1,"specify":1,"enable":1,"disable":1}
,"command":{"enable":1,"syntax":1,"mode":1}
,"enable":{"disable":1,"enable":1,"spanning":1,"(config)":1}
,"disable":{"spanning":1,"disable":1}
,"spanning":{"tree":1}
,"tree":{"interface":1,"disable":1}
,"interface":{"command":1,"enable":1,"mode":1,"eth0":1}
,"syntax":{"bridge-group":1}
,"<1-32>":{"spanning-tree":1,"specify":1}
,"(disable":{"enable)":1}
,"enable)":{"parameters":1}
,"parameters":{"bridge-group":1}
,"specify":{"bridge":1,"whether":1}
,"bridge":{"group":1}
,"group":{"<1-32>":1,"spanning-tree":1}
,"whether":{"enable":1}
,"mode":{"interface":1,"examples":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"eth0":{"(config-if)":1}
,"(config-if)":{"bridge-group":1}
}
;Search.control.loadWordPairs(pairs);
