var pairs =
{
"enable-ldp":{"command":1,"ipv4":1,"(ipv6":1,"ipv6":1}
,"command":{"enable":1,"enables":1,"nsm":1,"reference":1,"command":1,"syntax":1,"mode":1}
,"enable":{"ldp":1,"ldp-igp":1,"ipv4":1,"ipv6":1}
,"ldp":{"ipv4":1,"ipv6":1,"adjacencies":1,"sessions":1}
,"ipv4":{"ldp":1,"ipv6":1,"(igp-sync":1,"enable":1,"interface":1,"following":1}
,"ipv6":{"ldp":1,"specified":1,"interface":1,"enable":1,"following":1}
,"specified":{"interface":1}
,"interface":{"command":1,"ldp":1,"adjacencies":1,"nsm":1,"network":1,"ipv4":1,"ipv6":1,"mode":1,"eth0":1}
,"enables":{"transmission":1,"ldp":1}
,"transmission":{"hello":1}
,"hello":{"packets":1}
,"packets":{"current":1}
,"current":{"interface":1}
,"adjacencies":{"ldp":1,"session":1}
,"sessions":{"created":1}
,"created":{"parameter":1}
,"parameter":{"enable":1}
,"session":{"formed":1}
,"formed":{"either":1}
,"either":{"address":1}
,"address":{"families":1}
,"families":{"corresponding":1}
,"corresponding":{"interface":1}
,"nsm":{"enabled":1,"interface":1}
,"enabled":{"label-switching":1}
,"label-switching":{"using":1,"command":1}
,"using":{"label-switching":1}
,"network":{"services":1}
,"services":{"module":1}
,"module":{"command":1}
,"reference":{"details":1}
,"details":{"label-switching":1}
,"syntax":{"enable-ldp":1}
,"(igp-sync":{"no-igp-sync":1}
,"no-igp-sync":{"enable-ldp":1,"parameters":1,"disable":1}
,"(ipv6":{"both)":1}
,"both)":{"(igp-sync":1}
,"parameters":{"igp-sync":1}
,"igp-sync":{"enable":1}
,"ldp-igp":{"synchronization":1}
,"synchronization":{"no-igp-sync":1,"enable":1}
,"disable":{"ldp-igp":1}
,"mode":{"interface":1,"examples":1}
,"examples":{"following":1}
,"following":{"example":1}
,"example":{"enables":1}
,"eth0":{"configure":1,"(config-if)":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"interface":1}
,"(config-if)":{"enable-ldp":1}
}
;Search.control.loadWordPairs(pairs);
