var pairs =
{
"maximum-prefix":{"command":1,"<1-65535>":1,"parameters":1,"150":1}
,"command":{"configure":1,"disable":1,"syntax":1,"mode":1}
,"configure":{"maximum":1,"terminal":1}
,"maximum":{"prefix":1,"number":1,"routes":1}
,"prefix":{"parameter":1}
,"parameter":{"command":1}
,"disable":{"limiting":1}
,"limiting":{"number":1}
,"number":{"rip":1}
,"rip":{"routes":1,"(config-router)":1}
,"routes":{"routing":1,"allowed":1,"generate":1}
,"routing":{"table":1}
,"table":{"command":1}
,"syntax":{"maximum-prefix":1}
,"<1-65535>":{"(<1-100>":1,"maximum":1}
,"(<1-100>":{"maximum-prefix":1}
,"parameters":{"<1-65535>":1}
,"allowed":{"<1-100>":1}
,"<1-100>":{"percentage":1}
,"percentage":{"maximum":1}
,"generate":{"warning":1}
,"warning":{"default":1}
,"default":{"threshold":1,"none":1}
,"threshold":{"default":1}
,"none":{"command":1}
,"mode":{"router":1,"examples":1}
,"router":{"mode":1,"rip":1}
,"examples":{"configure":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"(config-router)":{"maximum-prefix":1}
}
;Search.control.loadWordPairs(pairs);
