var pairs =
{
"vpls-peer":{"command":1,"a.b.c.d":1,"97.97.97.97":1}
,"command":{"add":1,"triggers":1,"syntax":1,"mode":1}
,"add":{"peer":1}
,"peer":{"vpls":1,"command":1,"node":1}
,"vpls":{"domain":1,"virtual":1,"peer":1,"signaling":1,"test":1}
,"domain":{"command":1}
,"triggers":{"label":1}
,"label":{"distribution":1}
,"distribution":{"protocol":1}
,"protocol":{"(ldp)":1}
,"(ldp)":{"signaling":1}
,"signaling":{"default":1,"mode":1,"ldp":1}
,"default":{"parameter":1}
,"parameter":{"delete":1}
,"delete":{"vpls":1}
,"virtual":{"circuit":1}
,"circuit":{"specific":1,"created":1,"agi":1,"name":1,"saii":1,"taii":1,"command":1}
,"specific":{"peer":1}
,"syntax":{"vpls-peer":1}
,"a.b.c.d":{"((agi":1,"address":1,"ipv4":1}
,"((agi":{"name":1}
,"name":{"saii":1,"taii":1,"agi":1}
,"saii":{"name":1,"specify":1,"fec129":1,"value":1}
,"taii":{"name)":1,"specify":1,"fec129":1,"value":1}
,"name)":{"((tunnel-id":1}
,"((tunnel-id":{"<1-65535>":1}
,"<1-65535>":{"(forward":1,"tunnel":1}
,"(forward":{"reverse":1}
,"reverse":{"|))":1,"tunnel":1}
,"|))":{"vpls-peer":1,"parameters":1}
,"parameters":{"a.b.c.d":1}
,"address":{"vpls":1,"end-point":1}
,"node":{"mesh":1}
,"mesh":{"virtual":1}
,"created":{"tunnel-id":1}
,"tunnel-id":{"tunnel-identifier":1,"(config-vpls)":1}
,"tunnel-identifier":{"<1-65535>":1}
,"tunnel":{"within":1,"direction":1,"identifier":1}
,"within":{"range":1}
,"range":{"forward":1}
,"forward":{"tunnel":1}
,"direction":{"-forward":1,"-reverse":1}
,"-forward":{"tunnel":1}
,"identifier":{"(default":1,"a.b.c.d":1}
,"(default":{"setting)":1}
,"setting)":{"reverse":1}
,"-reverse":{"tunnel":1}
,"ipv4":{"address":1}
,"end-point":{"fec129":1}
,"fec129":{"mpls":1}
,"mpls":{"layer-2":1,"vpls":1}
,"layer-2":{"virtual":1}
,"agi":{"specify":1,"fec129":1,"value":1}
,"specify":{"value":1}
,"value":{"used":1,"fec129":1}
,"used":{"agi":1,"saii":1,"taii":1}
,"mode":{"vpls":1,"examples":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"mpls":1,"exit":1}
,"test":{"100":1}
,"100":{"(config-vpls)":1}
,"(config-vpls)":{"signaling":1,"exit":1}
,"ldp":{"(config-vpls-sig)":1}
,"(config-vpls-sig)":{"vpls-peer":1}
,"97.97.97.97":{"(config-vpls-sig)":1,"tunnel-id":1}
,"exit":{"(config)":1}
}
;Search.control.loadWordPairs(pairs);
