var pairs =
{
"vpn":{"routing":1,"services":1,"packet":1}
,"routing":{"process":1,"forwarding":1,"data":1,"information":1}
,"process":{"zebos-xp":1,"follows":1}
,"zebos-xp":{"mpls-vpn":1}
,"mpls-vpn":{"routing":1}
,"follows":{"steps":1}
,"steps":{"service":1}
,"service":{"providers":1}
,"providers":{"provide":1}
,"provide":{"vpn":1}
,"services":{"routers":1}
,"routers":{"communicate":1,"via":1,"mp-bgp":1,"prepend":1}
,"communicate":{"directly":1}
,"directly":{"routers":1}
,"via":{"ethernet":1}
,"ethernet":{"link":1}
,"link":{"router":1}
,"router":{"maintains":1,"learns":1,"(usually":1,"allocates":1,"network":1,"penultimate":1,"pops":1,"egress":1}
,"maintains":{"routing":1}
,"forwarding":{"table":1,"across":1}
,"table":{"(vrf)":1,"packets":1,"(associated":1,"specifying":1,"(ilm)":1}
,"(vrf)":{"customer":1}
,"customer":{"guarantees":1}
,"guarantees":{"isolation":1}
,"isolation":{"allows":1}
,"allows":{"usage":1}
,"usage":{"uncoordinated":1}
,"uncoordinated":{"private":1}
,"private":{"addresses":1}
,"addresses":{"packet":1,"exchanged":1,"multi-protocol":1}
,"packet":{"received":1,"forwarding":1,"forwarded":1,"based":1,"bgp-specific":1,"appropriate":1}
,"received":{"vrf":1}
,"vrf":{"mapped":1,"table":1,"(even":1}
,"mapped":{"site":1,"connections":1}
,"site":{"used":1,"single":1}
,"used":{"determine":1,"allocate":1,"key":1}
,"determine":{"routing":1}
,"data":{"multiple":1}
,"multiple":{"connections":1}
,"connections":{"site":1,"router":1}
,"single":{"vrf":1,"label":1}
,"learns":{"prefix":1}
,"prefix":{"converts":1,"prepending":1}
,"converts":{"vpn-ipv4":1}
,"vpn-ipv4":{"prefix":1,"addresses":1}
,"prepending":{"8-byte":1}
,"8-byte":{"route":1}
,"route":{"distinguisher":1,"vrf":1}
,"distinguisher":{"(rd)":1}
,"(rd)":{"ensures":1}
,"ensures":{"even":1}
,"even":{"two":1}
,"two":{"customers":1,"separate":1}
,"customers":{"address":1}
,"address":{"two":1,"maintained":1}
,"separate":{"routes":1}
,"routes":{"address":1}
,"maintained":{"vpn-ipv4":1}
,"exchanged":{"routers":1}
,"mp-bgp":{"unique":1}
,"unique":{"router":1,"label":1}
,"(usually":{"loopback":1}
,"loopback":{"address)":1}
,"address)":{"used":1}
,"allocate":{"label":1}
,"label":{"enable":1,"every":1,"stack":1,"vrf":1,"global":1,"ldp-specific":1,"used":1,"label":1,"swapped":1,"forwards":1,"egress":1,"performs":1,"lookup":1}
,"enable":{"vpn":1}
,"across":{"backbone":1,"provider":1}
,"backbone":{"based":1}
,"based":{"routing":1,"top":1}
,"information":{"stored":1}
,"stored":{"vrf":1}
,"packets":{"forwarded":1}
,"forwarded":{"destination":1,"across":1,"next":1}
,"destination":{"using":1}
,"using":{"mpls":1}
,"mpls":{"router":1}
,"allocates":{"unique":1}
,"every":{"route":1}
,"(even":{"next":1}
,"next":{"hop)":1,"hop":1}
,"hop)":{"propagates":1}
,"propagates":{"labels":1}
,"labels":{"together":1,"mapping":1}
,"together":{"12-byte":1}
,"12-byte":{"vpn-ipv4":1}
,"multi-protocol":{"bgp":1}
,"bgp":{"ingress":1,"next":1}
,"ingress":{"routers":1}
,"prepend":{"two-level":1}
,"two-level":{"label":1}
,"stack":{"vpn":1,"contains":1,"top":1}
,"provider":{"network":1,"router":1}
,"network":{"label":1,"switches":1}
,"contains":{"bgp-specific":1}
,"bgp-specific":{"label":1}
,"(associated":{"incoming":1}
,"incoming":{"interface)":1,"interface\u2019s":1,"labels":1}
,"interface)":{"specifying":1}
,"specifying":{"bgp":1,"next":1}
,"hop":{"ldp-specific":1,"provider":1,"router":1}
,"ldp-specific":{"label":1}
,"global":{"ftn":1}
,"ftn":{"table":1}
,"switches":{"vpn":1}
,"top":{"label":1}
,"key":{"lookup":1}
,"lookup":{"incoming":1,"outbound":1}
,"interface\u2019s":{"incoming":1}
,"mapping":{"table":1}
,"(ilm)":{"outbound":1}
,"outbound":{"label":1,"interface":1}
,"swapped":{"packet":1}
,"penultimate":{"router":1}
,"pops":{"ldp-specific":1,"bgp-specific":1}
,"forwards":{"packet":1}
,"egress":{"router":1}
,"performs":{"single":1}
,"interface":{"sends":1}
,"sends":{"packet":1}
,"appropriate":{"router":1}
}
;Search.control.loadWordPairs(pairs);
