var pairs =
{
"max-lsp-lifetime":{"command":1,"greater":1,"<350-65535>":1,"parameters":1,"1200":1,"1500":1}
,"command":{"maximum":1,"syntax":1,"mode":1}
,"maximum":{"lsp":1}
,"lsp":{"lifetime":1}
,"lifetime":{"max-lsp-lifetime":1,"default":1,"seconds":1}
,"greater":{"lsp-refresh-interval":1}
,"lsp-refresh-interval":{"parameter":1}
,"parameter":{"lifetime":1}
,"default":{"command":1,"default":1,"max-lsp-lifetime":1}
,"syntax":{"max-lsp-lifetime":1}
,"<350-65535>":{"max-lsp-lifetime":1,"specify":1}
,"parameters":{"<350-65535>":1}
,"specify":{"maximum":1}
,"seconds":{"default":1,"command":1}
,"1200":{"seconds":1}
,"mode":{"router":1,"examples":1}
,"router":{"mode":1,"isis":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"isis":{"(config-router)":1}
,"(config-router)":{"max-lsp-lifetime":1}
,"1500":{"(config)":1}
}
;Search.control.loadWordPairs(pairs);
