var pairs =
{
"hsl_ifmgr_l3_create":{"function":1,"(char":1}
,"function":{"creates":1}
,"creates":{"layer":1}
,"layer":{"interface":1}
,"interface":{"syntax":1,"name":1}
,"syntax":{"int":1}
,"int":{"hsl_ifmgr_l3_create":1,"hwaddrlen":1,"send_notification":1}
,"(char":{"*ifname":1}
,"*ifname":{"u_char":1}
,"u_char":{"*hwaddr":1}
,"*hwaddr":{"int":1}
,"hwaddrlen":{"int":1,"hardware":1}
,"send_notification":{"void":1,"indicates":1}
,"void":{"*data":1}
,"*data":{"struct":1}
,"struct":{"hsl_if":1}
,"hsl_if":{"**ppifp)":1}
,"**ppifp)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ifname":1,"none":1}
,"ifname":{"interface":1}
,"name":{"hwaddr":1}
,"hwaddr":{"hardware":1}
,"hardware":{"address":1}
,"address":{"hwaddrlen":1,"length":1}
,"length":{"send_notification":1}
,"indicates":{"whether":1}
,"whether":{"send":1}
,"send":{"notification":1}
,"notification":{"protocol":1}
,"protocol":{"modules":1}
,"modules":{"data":1}
,"data":{"ppifp":1}
,"ppifp":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
}
;Search.control.loadWordPairs(pairs);
