var pairs =
{
"trill_channel_echo_reply_send":{"function":1,"(struct":1}
,"function":{"checks":1}
,"checks":{"parameters":1}
,"parameters":{"part":1,"*dpkt":1,"none":1}
,"part":{"given":1}
,"given":{"flow":1}
,"flow":{"chart":1}
,"chart":{"calls":1}
,"calls":{"syntax":1}
,"syntax":{"int":1}
,"int":{"trill_channel_echo_reply_send":1}
,"(struct":{"trill_channel_packet":1}
,"trill_channel_packet":{"*dpkt":1}
,"*dpkt":{"struct":1,"received":1}
,"struct":{"trill_interface":1}
,"trill_interface":{"*isi":1}
,"*isi":{"u_int32_t":1,"pointer":1}
,"u_int32_t":{"seq_num)":1}
,"seq_num)":{"input":1}
,"input":{"parameters":1}
,"received":{"channel":1,"seq_num":1}
,"channel":{"data":1}
,"data":{"packet":1}
,"packet":{"*isi":1}
,"pointer":{"interface":1,"sequence":1}
,"interface":{"frame":1}
,"frame":{"received":1}
,"seq_num":{"specifies":1}
,"specifies":{"pointer":1}
,"sequence":{"number":1}
,"number":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"trill_channel_success":1}
,"trill_channel_success":{"trill_channel_fail":1}
}
;Search.control.loadWordPairs(pairs);
