var pairs =
{
"trill_get_rbridgebase_port_stproot":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"bridge":1}
,"bridge":{"identifier":1}
,"identifier":{"root":1,"instance":1}
,"root":{"spanning":1}
,"spanning":{"tree":1}
,"tree":{"syntax":1}
,"syntax":{"int":1}
,"int":{"trill_get_rbridgebase_port_stproot":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"integer":1}
,"u_int32_t":{"instance":1,"baseport":1}
,"instance":{"u_int32_t":1,"integer":1,"baseport":1,"port":1}
,"baseport":{"u_char":1,"port":1}
,"u_char":{"**ret)":1}
,"**ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"ret":1}
,"integer":{"contains":1}
,"contains":{"trill":1,"rbridge":1}
,"trill":{"identifier":1,"instance":1}
,"port":{"number":1}
,"number":{"entry":1,"trill_api_get_error":1,"found":1}
,"entry":{"contains":1}
,"rbridge":{"management":1}
,"management":{"information":1}
,"information":{"output":1}
,"output":{"parameters":1}
,"ret":{"pointer":1}
,"pointer":{"stproot":1}
,"stproot":{"bridge-id":1}
,"bridge-id":{"size":1,"return":1}
,"size":{"length":1}
,"length":{"bridge-id":1}
,"return":{"value":1}
,"value":{"trill_api_get_success":1}
,"trill_api_get_success":{"valid":1}
,"valid":{"instance":1}
,"trill_api_get_error":{"valid":1}
}
;Search.control.loadWordPairs(pairs);
