var pairs =
{
"oam":{"protocol":1,"state":1,"remote":1,"client":1}
,"protocol":{"data":1}
,"data":{"units":1,"field":1}
,"units":{"oampdu":1}
,"oampdu":{"implemented":1,"identified":1,"lf_info":1}
,"implemented":{"zebos-xp":1}
,"zebos-xp":{"efm":1}
,"efm":{"include":1}
,"include":{"information":1}
,"information":{"oampdu":1,"remote":1,"passed":1,"sent":1}
,"identified":{"code":1,"corresponding":1}
,"code":{"field":1}
,"field":{"0x00":1,"local_pdu":1,"0x01":1,"table":1,"0x04":1,"loopback":1,"0xfe":1}
,"0x00":{"used":1,"-not":1}
,"used":{"send":1,"alert":1,"control":1,"organization-specific":1}
,"send":{"oam":1}
,"state":{"information":1,"based":1}
,"remote":{"client":1,"clients":1,"client\u2019s":1,"loopback":1}
,"client":{"data":1,"0x01":1,"organization-specific":1}
,"local_pdu":{"oampdu":1,"lf_info":1}
,"lf_info":{"means":1}
,"means":{"information":1}
,"passed":{"local_pdu":1}
,"sent":{"event":1}
,"event":{"notification":1,"name":1,"description":1,"critical":1,"occurred":1}
,"notification":{"oampdu":1}
,"0x01":{"used":1,"enable":1}
,"alert":{"remote":1}
,"clients":{"introduced":1}
,"introduced":{"link":1}
,"link":{"events":1,"fault":1}
,"events":{"events":1,"identified":1,"bits":1}
,"corresponding":{"bits":1}
,"bits":{"flag":1,"event":1}
,"flag":{"field":1}
,"table":{"below":1}
,"below":{"provides":1,"details":1}
,"provides":{"details":1}
,"details":{"events":1,"loopback":1}
,"name":{"event":1}
,"description":{"critical":1,"0x00":1}
,"critical":{"event":1}
,"occurred":{"critical":1,"dying":1,"-an":1,"link":1}
,"dying":{"gasp":1}
,"gasp":{"-an":1}
,"-an":{"unrecoverable":1}
,"unrecoverable":{"local":1}
,"local":{"failure":1}
,"failure":{"occurred":1}
,"fault":{"-local":1,"loopback":1}
,"-local":{"device":1}
,"device":{"receive":1}
,"receive":{"path":1}
,"path":{"detected":1}
,"detected":{"fault":1}
,"loopback":{"control":1,"state":1,"command":1,"oampdus":1,"0x02":1,"0x03-0xff":1}
,"control":{"oampdu":1,"remote":1}
,"0x04":{"used":1}
,"client\u2019s":{"oam":1}
,"based":{"value":1}
,"value":{"remote":1}
,"command":{"data":1,"description":1}
,"oampdus":{"handled":1,"command":1}
,"handled":{"refer":1}
,"refer":{"table":1}
,"-not":{"transmitted":1}
,"transmitted":{"ignored":1}
,"ignored":{"reception":1}
,"reception":{"oam":1}
,"enable":{"oam":1}
,"0x02":{"disable":1}
,"disable":{"oam":1}
,"0x03-0xff":{"-not":1}
,"organization-specific":{"oampdu":1,"extensions":1}
,"0xfe":{"used":1}
}
;Search.control.loadWordPairs(pairs);
