var pairs =
{
"validation":{"peb1":1}
,"peb1":{"show":1,"peb1":1,"eth1":1}
,"show":{"cvlan":1,"run":1,"running-config":1}
,"cvlan":{"registration":1,"svlan":1}
,"registration":{"table":1,"map1":1}
,"table":{"bridge":1,"name":1,"map1":1}
,"bridge":{"bridge":1,"table":1,"protocol":1,"name":1,"state":1,"vlan":1,"cvlan":1,"800008002725e07a":1,"ffff080027731b56":1}
,"name":{"port":1,"vlan0002":1,"vlan0003":1,"vlan0004":1,"vlan0005":1,"vlan0006":1,"vlan0007":1}
,"port":{"list":1,"number":1,"8004":1,"auto":1}
,"list":{"=========================1":1}
,"=========================1":{"map1":1}
,"map1":{"eth1":1,"bridge":1,"l2protocol":1}
,"eth1":{"cvlan":1,"switchport":1,"peb1":1,"port":1,"designated":1,"configured":1,"root":1,"message":1,"hello":1,"forward":1,"forward-transitions":1,"version":1,"portfast":1,"bpdu-guard":1,"bpdu-filter":1,"auto-edge":1}
,"svlan":{"================2":1,"evc-id":1,"cvlan":1,"interface":1}
,"================2":{"show":1}
,"run":{"peb1":1}
,"running-config":{"bridge":1}
,"protocol":{"provider-mstp":1,"-received":1}
,"provider-mstp":{"edge":1}
,"edge":{"spanning-tree":1}
,"spanning-tree":{"mode":1,"mst":1,"status":1}
,"mode":{"provider-rstp":1,"customer-edge":1,"provider-network":1}
,"provider-rstp":{"ethernet":1}
,"ethernet":{"cfm":1,"svlan":1}
,"cfm":{"enable":1}
,"enable":{"vlan":1,"ethernet":1,"spanning-tree":1}
,"vlan":{"database":1,"type":1,"switchport":1,"registration":1,"remove":1}
,"database":{"vlan":1}
,"type":{"customer":1,"service":1,"explicit":1,"point-to-point":1}
,"customer":{"bridge":1}
,"vlan0002":{"vlan":1}
,"state":{"enable":1}
,"vlan0003":{"vlan":1}
,"vlan0004":{"vlan":1}
,"vlan0005":{"vlan":1}
,"service":{"point-point":1}
,"point-point":{"bridge":1}
,"vlan0006":{"vlan":1}
,"evc-id":{"evc1":1}
,"evc1":{"bridge":1}
,"vlan0007":{"vlan":1}
,"mst":{"configuration":1}
,"configuration":{"cvlan":1}
,"interface":{"eth1":1,"eth2":1}
,"switchport":{"bridge-group":1,"mode":1,"customer-edge":1,"provider-network":1}
,"bridge-group":{"switchport":1}
,"customer-edge":{"hybrid":1,"vlan":1}
,"hybrid":{"switchport":1,"acceptable-frame-type":1,"allowed":1}
,"acceptable-frame-type":{"switchport":1}
,"allowed":{"vlan":1}
,"l2protocol":{"stp":1,"gmrp":1,"mmrp":1,"gvrp":1,"mvrp":1,"lacp":1,"dot1x":1,"efm":1,"elmi":1,"lldp":1,"ptp":1,"synce":1,"pause":1}
,"stp":{"peer":1}
,"peer":{"l2protocol":1}
,"gmrp":{"peer":1}
,"mmrp":{"peer":1}
,"gvrp":{"peer":1}
,"mvrp":{"peer":1}
,"lacp":{"peer":1}
,"dot1x":{"peer":1}
,"efm":{"peer":1}
,"elmi":{"peer":1}
,"lldp":{"discard":1}
,"discard":{"l2protocol":1,"shutdown":1}
,"ptp":{"peer":1}
,"synce":{"peer":1}
,"pause":{"discard":1}
,"shutdown":{"interface":1,"lldp-agent":1}
,"eth2":{"switchport":1,"cb1":1,"port":1,"designated":1,"configured":1,"cist":1,"regional":1,"message":1,"forward-transitions":1,"version":1,"portfast":1,"bpdu-guard":1,"bpdu-filter":1,"root":1,"auto-edge":1}
,"provider-network":{"switchport":1,"allowed":1}
,"remove":{"switchport":1,"shutdown":1}
,"lldp-agent":{"dcbx":1}
,"dcbx":{"enable":1}
,"status":{"eth2":1,"eth1":1}
,"cb1":{"portfast":1}
,"portfast":{"bpdu-filter":1,"bpdu-guard":1,"errdisable":1,"configured":1,"eth2":1,"eth1":1}
,"bpdu-filter":{"disabled":1,"default":1,"eth2":1,"eth1":1}
,"disabled":{"portfast":1}
,"bpdu-guard":{"disabled":1,"default":1,"eth2":1,"eth1":1}
,"errdisable":{"timeout":1}
,"timeout":{"disabled":1,"interval":1}
,"interval":{"300":1}
,"300":{"sec":1}
,"sec":{"eth2":1}
,"number":{"-ifindex":1}
,"-ifindex":{"-port":1}
,"-port":{"8004":1,"2fff":1}
,"8004":{"-role":1,"-cist":1,"-priority":1}
,"-role":{"designated":1,"rootport":1}
,"designated":{"-state":1,"external":1,"port":1,"bridge":1,"path":1}
,"-state":{"forwarding":1}
,"forwarding":{"eth2":1,"eth1":1}
,"external":{"path":1}
,"path":{"cost":1}
,"cost":{"-internal":1,"eth2":1,"20000":1,"eth1":1}
,"-internal":{"path":1}
,"configured":{"path":1,"-current":1,"link":1}
,"20000":{"-add":1}
,"-add":{"type":1}
,"explicit":{"ref":1}
,"ref":{"count":1}
,"count":{"eth2":1,"eth1":1}
,"-cist":{"priority":1}
,"priority":{"128":1}
,"128":{"eth2":1}
,"cist":{"root":1,"hello":1,"forward":1}
,"root":{"800008002725e07a":1,"guard":1}
,"800008002725e07a":{"eth2":1,"eth1":1}
,"regional":{"root":1}
,"message":{"age":1}
,"age":{"-max":1,"eth2":1,"timer":1,"eth1":1}
,"-max":{"age":1}
,"hello":{"time":1}
,"time":{"-forward":1}
,"-forward":{"delay":1}
,"delay":{"eth2":1,"eth1":1}
,"forward":{"timer":1}
,"timer":{"-msg":1,"-hello":1,"-topo":1,"eth2":1,"eth1":1}
,"-msg":{"age":1}
,"-hello":{"timer":1}
,"-topo":{"change":1}
,"change":{"timer":1}
,"forward-transitions":{"eth2":1,"eth1":1}
,"version":{"multiple":1,"rapid":1}
,"multiple":{"spanning":1}
,"spanning":{"tree":1}
,"tree":{"protocol":1}
,"-received":{"none":1,"mstp":1}
,"none":{"-send":1}
,"-send":{"mstp":1,"rstp":1}
,"mstp":{"eth2":1,"-send":1}
,"-current":{"portfast":1,"bpdu-guard":1,"bpdu-filter":1,"root":1,"point-to-point":1,"port":1}
,"default":{"-current":1}
,"guard":{"configured":1,"eth2":1,"eth1":1}
,"link":{"type":1}
,"point-to-point":{"-current":1,"eth2":1,"eth1":1}
,"auto-edge":{"configured":1}
,"auto":{"edge":1}
,"2fff":{"-role":1}
,"rootport":{"-state":1}
,"-priority":{"eth1":1}
,"ffff080027731b56":{"eth1":1}
,"rapid":{"spanning":1}
,"rstp":{"eth1":1}
}
;Search.control.loadWordPairs(pairs);
