var pairs =
{
"hop-limit":{"command":1,"hop-limit":1,"compared":1,"configured":1,"value":1,"<1-255>":1,"parameter":1,"(config)":1}
,"command":{"specify":1,"helps":1,"revert":1,"syntax":1,"mode":1}
,"specify":{"limit":1}
,"limit":{"hops":1,"255":1}
,"hops":{"rsvp":1,"configured":1,"path":1,"command":1}
,"rsvp":{"bypass":1}
,"bypass":{"trunk":1,"mode":1}
,"trunk":{"upon":1,"processed":1}
,"upon":{"configuration":1}
,"configuration":{"arbitrary":1}
,"arbitrary":{"hop-limit":1}
,"compared":{"number":1}
,"number":{"hops":1,"acceptable":1}
,"configured":{"primary":1,"number":1,"path":1,"trunk":1}
,"primary":{"path":1}
,"path":{"primary":1,"configured":1,"exceeds":1,"messages":1}
,"exceeds":{"hop-limit":1}
,"messages":{"sent":1}
,"sent":{"existing":1,"command":1}
,"existing":{"session":1}
,"session":{"torn":1}
,"torn":{"down":1}
,"down":{"primary":1}
,"processed":{"normally":1}
,"normally":{"path":1}
,"helps":{"identify":1}
,"identify":{"attributes":1}
,"attributes":{"frr":1}
,"frr":{"backup":1}
,"backup":{"lsp":1}
,"lsp":{"facility-backup":1}
,"facility-backup":{"protection":1}
,"protection":{"method":1}
,"method":{"parameter":1}
,"parameter":{"command":1,"<1-255>":1}
,"revert":{"default":1}
,"default":{"hop-limit":1,"default":1,"hop":1}
,"value":{"command":1}
,"syntax":{"hop-limit":1}
,"<1-255>":{"hop-limit":1,"number":1}
,"acceptable":{"hops":1}
,"mode":{"bypass":1,"default":1}
,"hop":{"limit":1}
,"255":{"example":1}
,"example":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"rsvp-bypass":1}
,"rsvp-bypass":{"(config-bypass)":1}
,"(config-bypass)":{"hop-limit":1}
}
;Search.control.loadWordPairs(pairs);
