var pairs =
{
"nsm_bridge":{"data":1,"next":1,"previous":1}
,"data":{"structure":1}
,"structure":{"represents":1,"defined":1,"bridge":1}
,"represents":{"nsm":1}
,"nsm":{"bridge":1,"dcb":1}
,"bridge":{"(switch)":1,"ageing_time":1,"identifier":1,"mac":1,"learning":1,"avl_tree":1,"listener":1,"master":1,"gmrp_list":1,"gmrp_bridge":1,"gmrp_ext_filter:1":1,"evc_tree":1}
,"(switch)":{"data":1}
,"defined":{"nsm\u002Fl2\u002Fnsm_bridge.h":1}
,"nsm\u002Fl2\u002Fnsm_bridge.h":{"file":1}
,"file":{"member":1}
,"member":{"description":1}
,"description":{"next":1}
,"next":{"nsm_bridge":1,"node":1}
,"node":{"pprev":1,"name":1}
,"pprev":{"nsm_bridge":1}
,"previous":{"node":1}
,"name":{"name":1,"type":1}
,"type":{"type":1,"is_default":1,"-none\u002Fring":1,"enabled":1}
,"is_default":{"default":1}
,"default":{"bridge":1}
,"ageing_time":{"aging":1}
,"aging":{"time":1}
,"time":{"fdb":1}
,"fdb":{"entries":1,"list":1}
,"entries":{"enable":1}
,"enable":{"spanning":1,"provider_edge":1,"backbone_edge":1,"bridge_id":1,"extended":1}
,"spanning":{"tree":1}
,"tree":{"enable":1,"vip_port_map":1,"raps_tree":1,"dcbg":1,"routed_vlan_tree":1,"routed":1}
,"provider_edge":{"provider":1}
,"provider":{"edge":1}
,"edge":{"enable":1,"switching":1}
,"backbone_edge":{"back":1}
,"back":{"none":1,"pointer":1}
,"none":{"edge":1}
,"bridge_id":{"bridge":1}
,"identifier":{"bridge_mac":1}
,"bridge_mac":{"bridge":1}
,"mac":{"pbb_te_group_tree":1}
,"pbb_te_group_tree":{"pbb":1}
,"pbb":{"group":1}
,"group":{"avl":1}
,"avl":{"tree":1}
,"vip_port_map":{"vip":1}
,"vip":{"port":1}
,"port":{"map":1,"list":1,"manager":1}
,"map":{"learning":1}
,"learning":{"indicates":1,"bridge":1}
,"indicates":{"whether":1}
,"whether":{"bridge":1}
,"avl_tree":{"port_tree":1}
,"port_tree":{"port":1}
,"list":{"port_id_mgr":1,"bridge_listener_list":1,"vlan_table":1,"vlan_listener_list":1,"bvlan_table":1,"stp_decoupled_bvlan_table":1,"event":1}
,"port_id_mgr":{"snpm":1}
,"snpm":{"port":1}
,"manager":{"static_fdb_list":1}
,"static_fdb_list":{"static":1}
,"static":{"fdb":1}
,"bridge_listener_list":{"bridge":1}
,"listener":{"list":1}
,"vlan_table":{"vlan":1}
,"vlan":{"table":1,"listener":1,"list":1,"decoupled":1,"num":1}
,"table":{"stp_decoupled_vlan_tabl":1,"svlan_table":1,"stp_decoupled_svlan_table":1,"pro_edge_swctx_table":1,"cvlan_reg_tab_list":1}
,"stp_decoupled_vlan_tabl":{"vlan":1}
,"svlan_table":{"svlan":1}
,"svlan":{"table":1}
,"stp_decoupled_svlan_table":{"decoupled":1}
,"decoupled":{"svlan":1,"list":1}
,"pro_edge_swctx_table":{"pro":1}
,"pro":{"edge":1}
,"switching":{"context":1}
,"context":{"table":1}
,"cvlan_reg_tab_list":{"cvlan":1}
,"cvlan":{"list":1}
,"vlan_listener_list":{"vlan":1}
,"bvlan_table":{"bridged":1}
,"bridged":{"vlan":1}
,"stp_decoupled_bvlan_table":{"stp":1}
,"stp":{"bridged":1}
,"event":{"thread":1,"master":1}
,"thread":{"event":1}
,"master":{"back":1,"gvrp":1}
,"pointer":{"bridge":1,"configuration":1}
,"gvrp":{"gvrp":1,"structure":1}
,"gmrp_list":{"gmrp":1}
,"gmrp":{"structure":1,"bridge":1}
,"gmrp_bridge":{"gmrp":1}
,"gmrp_ext_filter:1":{"enable":1}
,"extended":{"filtering":1}
,"filtering":{"option":1}
,"option":{"vlan_num_deletes":1}
,"vlan_num_deletes":{"vlan":1}
,"num":{"deletes":1}
,"deletes":{"br_conf":1}
,"br_conf":{"pointer":1}
,"configuration":{"store":1}
,"store":{"traffic_class_enabled":1}
,"traffic_class_enabled":{"traffic":1}
,"traffic":{"class":1}
,"class":{"status":1,"service":1}
,"status":{"topology_type":1}
,"topology_type":{"topology":1}
,"topology":{"type":1}
,"-none\u002Fring":{"-currently":1}
,"-currently":{"used":1}
,"used":{"support":1}
,"support":{"rstp":1}
,"rstp":{"num_cosq":1}
,"num_cosq":{"number":1}
,"number":{"class":1,"mst":1}
,"service":{"queues":1}
,"queues":{"eps_tree":1}
,"eps_tree":{"eps":1}
,"eps":{"tree":1}
,"raps_tree":{"raps":1}
,"raps":{"tree":1}
,"dcbg":{"nsm":1}
,"dcb":{"bridge":1}
,"evc_tree":{"evc":1}
,"evc":{"avl":1}
,"routed_vlan_tree":{"avl":1}
,"routed":{"vlans":1}
,"vlans":{"max_mst_instances":1}
,"max_mst_instances":{"maximum":1}
,"maximum":{"number":1}
,"mst":{"instances":1}
,"instances":{"uni_type_mode":1}
,"uni_type_mode":{"uni":1}
,"uni":{"type":1}
,"enabled":{"disabled":1}
,"disabled":{"bridge":1}
}
;Search.control.loadWordPairs(pairs);
