var pairs =
{
"snmp":{"api":1,"operations":1}
,"api":{"section":1}
,"section":{"describes":1}
,"describes":{"function":1}
,"function":{"called":1,"description":1}
,"called":{"support":1}
,"support":{"snmp":1}
,"operations":{"function":1}
,"description":{"lldpv2_snmp_set_msg_tx_interval":1}
,"lldpv2_snmp_set_msg_tx_interval":{"sets":1}
,"sets":{"interval":1,"value":1,"delay":1,"maximum":1,"variable":1,"administratively":1}
,"interval":{"lldp":1,"transmissions":1}
,"lldp":{"frames":1,"tlvs":1,"agent":1,"notifications":1,"lldpv2_snmp_get_admin_status":1}
,"frames":{"transmitted":1}
,"transmitted":{"lldpv2_snmp_set_port_msg_tx_hold":1,"during":1,"time":1}
,"lldpv2_snmp_set_port_msg_tx_hold":{"sets":1}
,"value":{"message":1,"reinit":1}
,"message":{"transmit":1}
,"transmit":{"hold":1}
,"hold":{"parameter":1}
,"parameter":{"lldpv2_snmp_set_msg_fast_tx":1}
,"lldpv2_snmp_set_msg_fast_tx":{"sets":1}
,"during":{"fast":1,"transmission":1,"normal":1}
,"fast":{"transmission":1}
,"transmission":{"period":1,"mode":1,"periods":1}
,"period":{"lldpv2_snmp_set_port_reinit_delay":1}
,"lldpv2_snmp_set_port_reinit_delay":{"sets":1}
,"delay":{"value":1,"lldpv2_snmp_set_max_credit":1}
,"reinit":{"delay":1}
,"lldpv2_snmp_set_max_credit":{"sets":1}
,"maximum":{"number":1}
,"number":{"consecutive":1,"lldpdus":1}
,"consecutive":{"lldpdus":1}
,"lldpdus":{"transmitted":1}
,"time":{"lldpv2_snmp_set_tx_fast_init":1}
,"lldpv2_snmp_set_tx_fast_init":{"sets":1}
,"variable":{"determines":1}
,"determines":{"number":1}
,"mode":{"lldpv2_snmp_set_tlvs":1}
,"lldpv2_snmp_set_tlvs":{"specifies":1}
,"specifies":{"basic":1}
,"basic":{"lldp":1}
,"tlvs":{"lldpv2_snmp_set_admin_status":1,"whose":1}
,"lldpv2_snmp_set_admin_status":{"sets":1}
,"administratively":{"desired":1}
,"desired":{"status":1}
,"status":{"local":1}
,"local":{"lldp":1}
,"agent":{"lldpv2_snmp_set_ntfy_interval":1,"enabled":1}
,"lldpv2_snmp_set_ntfy_interval":{"sets":1}
,"transmissions":{"lldp":1,"allowed":1}
,"notifications":{"during":1,"agent":1}
,"normal":{"transmission":1}
,"periods":{"lldpv2_snmp_set_ntfy_enable":1}
,"lldpv2_snmp_set_ntfy_enable":{"configures":1}
,"configures":{"whether":1}
,"whether":{"notifications":1}
,"enabled":{"lldpv2_snmp_get_tlvs":1}
,"lldpv2_snmp_get_tlvs":{"returns":1}
,"returns":{"basic":1,"administratively":1}
,"whose":{"transmissions":1}
,"allowed":{"local":1}
,"lldpv2_snmp_get_admin_status":{"returns":1}
}
;Search.control.loadWordPairs(pairs);
