var pairs =
{
"cli":{"data":1,"element":1,"index_sub":1,"mode":1,"status":1,"tree":1,"count":1}
,"data":{"structure":1}
,"structure":{"represents":1,"defined":1}
,"represents":{"command":1}
,"command":{"user":1,"string":1}
,"user":{"given":1,"input":1}
,"given":{"data":1}
,"defined":{"lib\u002Fcli.h":1}
,"lib\u002Fcli.h":{"file":1}
,"file":{"member":1}
,"member":{"description":1}
,"description":{"cel":1}
,"cel":{"cli":1}
,"element":{"str":1}
,"str":{"user":1}
,"input":{"string":1,"source":1}
,"string":{"out_func":1}
,"out_func":{"output":1}
,"output":{"function":1,"function\u0027s":1}
,"function":{"used":1,"cleanup":1,"show_func":1,"type":1}
,"used":{"cli_out":1,"imi":1}
,"cli_out":{"out_val":1}
,"out_val":{"output":1}
,"function\u0027s":{"first":1}
,"first":{"argument":1}
,"argument":{"line":1,"afi":1}
,"line":{"arbitrary":1,"auth":1,"min":1,"minimum":1,"maximum":1}
,"arbitrary":{"information":1}
,"information":{"line":1,"self":1,"current":1,"safi":1,"port_range":1}
,"auth":{"authorization":1}
,"authorization":{"required":1}
,"required":{"source":1}
,"source":{"input":1,"line_type":1}
,"line_type":{"line":1}
,"min":{"line":1}
,"minimum":{"max":1}
,"max":{"line":1}
,"maximum":{"index":1}
,"index":{"real":1}
,"real":{"cli":1}
,"index_sub":{"real":1}
,"mode":{"real":1}
,"status":{"current":1,"flags":1}
,"current":{"cli":1,"arbitrary":1,"node":1}
,"flags":{"flags":1,"self":1}
,"self":{"arbitrary":1,"privilege":1}
,"privilege":{"privilege":1,"level":1}
,"level":{"ctree":1}
,"ctree":{"cli":1}
,"tree":{"daemon-spefic":1}
,"daemon-spefic":{"library":1}
,"library":{"globals":1}
,"globals":{"global":1}
,"global":{"variable":1}
,"variable":{"lines":1}
,"lines":{"terminal":1}
,"terminal":{"length":1}
,"length":{"callback":1}
,"callback":{"call":1}
,"call":{"back":1}
,"back":{"function":1}
,"cleanup":{"call":1}
,"show_func":{"call":1}
,"type":{"type":1,"cli":1}
,"count":{"total":1,"current":1}
,"total":{"count":1}
,"node":{"arg":1}
,"arg":{"look":1}
,"look":{"argument":1}
,"afi":{"address":1}
,"address":{"family":1}
,"family":{"information":1}
,"safi":{"specific":1}
,"specific":{"address":1}
,"port_range":{"layer":1}
,"layer":{"handling":1}
,"handling":{"vector":1}
,"vector":{"used":1}
,"imi":{"encode":1}
,"encode":{"single":1}
,"single":{"command":1}
}
;Search.control.loadWordPairs(pairs);
