var pairs =
{
"functions":{"functions":1,"chapter":1}
,"chapter":{"used":1}
,"used":{"link":1}
,"link":{"aggregation":1,"drni_api_set_ipp_periodic_time":1,"drni_api_update_gateway_conv":1,"lacp":1}
,"aggregation":{"function":1}
,"function":{"description":1}
,"description":{"drni_api_dbg_show_ipp_details":1}
,"drni_api_dbg_show_ipp_details":{"displays":1}
,"displays":{"information":1,"mc-lag":1,"portal":1,"drcpdu":1,"collection":1,"port":1}
,"information":{"intra-portal":1,"mc-lag":1}
,"intra-portal":{"port":1,"link":1}
,"port":{"drni_api_dbg_show_portal_detail":1,"conversation":1,"lacp_unset_system_priority":1,"channel":1}
,"drni_api_dbg_show_portal_detail":{"displays":1}
,"mc-lag":{"drni_api_mac_address_is_valid":1,"gateway":1,"configuration":1,"portal":1,"instance":1}
,"drni_api_mac_address_is_valid":{"validates":1}
,"validates":{"mac":1}
,"mac":{"address":1}
,"address":{"drni_api_set_conv_alloc_mode":1,"portal":1,"type":1}
,"drni_api_set_conv_alloc_mode":{"sets":1}
,"sets":{"conversation":1,"timeout":1,"mac":1,"name":1,"portal":1,"number":1,"topology":1,"address":1,"priority":1,"lacp":1,"system":1,"load-balancing":1}
,"conversation":{"identifier":1,"identifiers":1,"masks":1}
,"identifier":{"allocation":1,"lacp_api_set_aggregation_port_destination_addr_type":1,"interface":1,"port":1}
,"allocation":{"mode":1,"lacp_api_discard_wrong_conversation":1}
,"mode":{"drni_api_set_intra_portal_link":1,"aggregator":1}
,"drni_api_set_intra_portal_link":{"creates":1}
,"creates":{"intra-portal":1,"mc-lag":1}
,"drni_api_set_ipp_periodic_time":{"sets":1}
,"timeout":{"drcpdu":1,"per-port":1}
,"drcpdu":{"exchange":1,"statistics":1}
,"exchange":{"drni_api_set_portal_address":1}
,"drni_api_set_portal_address":{"sets":1}
,"portal":{"system":1,"drni_api_set_portal_priority":1,"priority":1,"drni_api_set_portal_topology":1,"conversation":1,"configuration":1}
,"system":{"drni_api_set_portal_name":1,"drni_api_set_portal_system_number":1,"portal":1,"drni_api_unset_intra_portal_link":1,"drni_set_destination_address_type":1,"priority":1}
,"drni_api_set_portal_name":{"sets":1}
,"name":{"portal":1}
,"drni_api_set_portal_priority":{"sets":1}
,"priority":{"portal":1,"level":1,"port":1}
,"drni_api_set_portal_system_number":{"sets":1}
,"number":{"system":1}
,"drni_api_set_portal_topology":{"sets":1}
,"topology":{"portal":1}
,"drni_api_unset_intra_portal_link":{"removes":1}
,"removes":{"intra-portal":1,"range":1,"mlag":1}
,"drni_api_update_gateway_conv":{"allocates":1}
,"allocates":{"removes":1}
,"range":{"gateway":1,"port":1}
,"gateway":{"conversation":1}
,"identifiers":{"drni_clear_statistics_all":1,"drni_show_mlag_summary":1,"drni_show_portal_summary":1,"drni_show_statistics_all":1,"nsm_lacp_aggregator_psc_set":1}
,"drni_clear_statistics_all":{"clears":1}
,"clears":{"drcpdu":1}
,"statistics":{"portal":1,"lacp_api_cli_show_debug_po_details":1}
,"drni_set_destination_address_type":{"sets":1}
,"type":{"sending":1}
,"sending":{"drcpdus":1,"lacpdus":1}
,"drcpdus":{"ipp":1}
,"ipp":{"drni_show_gateway_conv_detail":1}
,"drni_show_gateway_conv_detail":{"displays":1}
,"drni_show_mlag_summary":{"displays":1}
,"configuration":{"status":1}
,"status":{"drni_show_portal_detail":1,"drni_show_port_conv_detail":1}
,"drni_show_portal_detail":{"displays":1}
,"drni_show_portal_summary":{"displays":1}
,"drni_show_port_conv_detail":{"displays":1}
,"drni_show_statistics_all":{"displays":1}
,"lacp_api_cli_show_debug_po_details":{"displays":1}
,"collection":{"port":1}
,"masks":{"lacp_api_cli_show_etherchannel_port_conv":1}
,"lacp_api_cli_show_etherchannel_port_conv":{"displays":1}
,"lacp_api_discard_wrong_conversation":{"enables":1}
,"enables":{"disables":1}
,"disables":{"discarding":1}
,"discarding":{"frames":1}
,"frames":{"incorrect":1}
,"incorrect":{"port":1}
,"lacp_api_set_aggregation_port_destination_addr_type":{"sets":1}
,"lacpdus":{"lacp_find_link_by_name":1}
,"lacp_find_link_by_name":{"search":1}
,"search":{"link":1}
,"lacp":{"control":1,"channel":1,"timeout":1}
,"control":{"lacp_set_channel_priority":1}
,"lacp_set_channel_priority":{"sets":1}
,"level":{"lacp":1}
,"channel":{"lacp_set_channel_timeout":1,"lacp_unset_channel_priority":1,"priority":1,"mlag_api_set_mlag_instance":1}
,"lacp_set_channel_timeout":{"sets":1}
,"per-port":{"basis":1}
,"basis":{"lacp_set_system_priority":1}
,"lacp_set_system_priority":{"sets":1}
,"lacp_unset_channel_priority":{"unsets":1}
,"unsets":{"lacp":1,"system":1}
,"lacp_unset_system_priority":{"unsets":1}
,"mlag_api_set_mlag_instance":{"creates":1}
,"instance":{"mlag_api_unset_mlag_instance":1,"mlag_api_update_port_conv":1}
,"mlag_api_unset_mlag_instance":{"deletes":1}
,"deletes":{"mc-lag":1,"aggregator":1}
,"mlag_api_update_port_conv":{"allocates":1}
,"nsm_lacp_aggregator_psc_set":{"sets":1}
,"load-balancing":{"mode":1}
,"aggregator":{"nsm_lacp_api_add_aggregator_member":1,"member":1}
,"nsm_lacp_api_add_aggregator_member":{"adds":1}
,"adds":{"aggregator":1}
,"member":{"nsm_lacp_api_delete_aggregator_member":1,"nsm_mlag_api_add_aggregator_member":1}
,"nsm_lacp_api_delete_aggregator_member":{"deletes":1}
,"nsm_mlag_api_add_aggregator_member":{"assigns":1}
,"assigns":{"mlag":1}
,"mlag":{"identifier":1}
,"interface":{"(port":1}
,"(port":{"channel)":1}
,"channel)":{"nsm_mlag_api_delete_aggregator_member":1}
,"nsm_mlag_api_delete_aggregator_member":{"removes":1}
}
;Search.control.loadWordPairs(pairs);
