var pairs =
{
"ethernet":{"cfm":1}
,"cfm":{"ais":1}
,"ais":{"interval":1,"instances":1,"seconds":1}
,"interval":{"command":1,"alarm":1,"tx_interval":1,"transmission":1,"ais":1,"mpid":1}
,"command":{"configure":1,"syntax":1,"mode":1}
,"configure":{"transmission":1}
,"transmission":{"interval":1}
,"alarm":{"indicator":1}
,"indicator":{"signal":1}
,"signal":{"(ais)":1}
,"(ais)":{"frames":1}
,"frames":{"maintenance":1}
,"maintenance":{"end":1}
,"end":{"point":1}
,"point":{"domain":1}
,"domain":{"domain":1,"vlan":1,"domain_name":1,"specify":1,"bridge":1,"abc":1}
,"vlan":{"bridge":1,"specify":1}
,"bridge":{"identities":1,"specify":1,"<1-32>":1}
,"identities":{"internal":1}
,"internal":{"counter":1}
,"counter":{"maintained":1,"fixed":1}
,"maintained":{"number":1}
,"number":{"ais":1}
,"instances":{"running":1}
,"running":{"maximum":1}
,"maximum":{"value":1}
,"value":{"counter":1}
,"fixed":{"eight":1}
,"eight":{"command":1}
,"syntax":{"ethernet":1}
,"tx_interval":{"mpid":1,"enter":1}
,"mpid":{"mepid":1,"specify":1,"domain":1}
,"mepid":{"domain":1}
,"domain_name":{"(vlan":1}
,"(vlan":{"vlan_id":1}
,"vlan_id":{"(bridge":1}
,"(bridge":{"<1-32>":1}
,"<1-32>":{"parameters":1,"vlan":1}
,"parameters":{"interval":1}
,"seconds":{"tx_interval":1,"transmission":1}
,"enter":{"seconds":1}
,"specify":{"host":1,"name":1,"bridge":1,"primary-vid":1}
,"host":{"mep":1}
,"mep":{"domain":1}
,"name":{"domain":1}
,"primary-vid":{"command":1}
,"mode":{"exec":1,"privileged":1,"example":1}
,"exec":{"mode":1}
,"privileged":{"exec":1}
,"example":{"ethernet":1}
,"abc":{"vlan":1}
}
;Search.control.loadWordPairs(pairs);
