var pairs =
{
"api":{"reference":1,"function":1}
,"reference":{"section":1}
,"section":{"describes":1}
,"describes":{"smi":1}
,"smi":{"client":1}
,"client":{"function":1,"applications":1,"zebos_smi_client_create":1,"zebos_smi_client_start":1,"connection":1,"zebos_smi_client_set_alarm_callback":1}
,"function":{"following":1,"click":1,"description":1}
,"following":{"table":1}
,"table":{"list":1}
,"list":{"functions":1}
,"functions":{"smi":1}
,"applications":{"navigate":1}
,"navigate":{"topic":1}
,"topic":{"function":1}
,"click":{"hyperlink":1}
,"hyperlink":{"api":1}
,"description":{"zebos_smi_client_lib_create":1}
,"zebos_smi_client_lib_create":{"allocates":1}
,"allocates":{"initializes":1}
,"initializes":{"memory":1}
,"memory":{"smi":1,"allocated":1}
,"zebos_smi_client_create":{"creates":1}
,"creates":{"protocol":1}
,"protocol":{"client":1,"clients":1}
,"zebos_smi_client_start":{"starts":1}
,"starts":{"protocol":1}
,"clients":{"zebos_smi_client_stop":1}
,"zebos_smi_client_stop":{"closes":1}
,"closes":{"client":1}
,"connection":{"zebos_smi_client_delete":1}
,"zebos_smi_client_delete":{"cancels":1}
,"cancels":{"pending":1}
,"pending":{"read":1}
,"read":{"messages":1}
,"messages":{"releases":1}
,"releases":{"memory":1}
,"allocated":{"client":1}
,"zebos_smi_client_set_alarm_callback":{"registers":1}
,"registers":{"alarm":1}
,"alarm":{"callback":1}
,"callback":{"function":1}
}
;Search.control.loadWordPairs(pairs);
