var pairs =
{
"trill_enable_channel_protocol_unset":{"function":1,"(u_int32_t":1}
,"function":{"enables":1,"call":1}
,"enables":{"channel":1}
,"channel":{"protocol":1}
,"protocol":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"trill_enable_channel_protocol_unset":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"specifies":1}
,"char":{"*tag)":1}
,"*tag)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"specifies":{"identification":1,"tag":1}
,"identification":{"virtual":1}
,"virtual":{"router":1}
,"router":{"*tag":1}
,"*tag":{"specifies":1}
,"tag":{"interface":1,"trill_api_set_err_vr_not_exist":1}
,"interface":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"trill_api_set_success":1}
,"trill_api_set_success":{"indicates":1}
,"indicates":{"function":1,"active":1}
,"call":{"executed":1}
,"executed":{"properly":1}
,"properly":{"trill_api_set_err_instance_not_exist":1}
,"trill_api_set_err_instance_not_exist":{"indicates":1}
,"active":{"is-is":1,"instance":1}
,"is-is":{"instance":1}
,"instance":{"specified":1,"virtual":1}
,"specified":{"tag":1}
,"trill_api_set_err_vr_not_exist":{"indicates":1}
}
;Search.control.loadWordPairs(pairs);
