var pairs =
{
"configuration":{"steps":1}
,"steps":{"enable":1}
,"enable":{"igmp":1}
,"igmp":{"snooping":1,"report":1}
,"snooping":{"interface":1,"globally":1,"bridge":1}
,"interface":{"add":1,"configured":1,"bridge":1}
,"add":{"bridge":1}
,"bridge":{"spanning-tree":1,"group":1}
,"spanning-tree":{"table":1}
,"table":{"specify":1}
,"specify":{"interface":1}
,"configured":{"associate":1}
,"associate":{"interface":1}
,"group":{"enable":1,"configure":1}
,"globally":{"enable":1}
,"configure":{"ports":1}
,"ports":{"connected":1,"default":1}
,"connected":{"routers":1}
,"routers":{"multicast":1}
,"multicast":{"router":1}
,"router":{"ports":1}
,"default":{"igmp":1}
,"report":{"suppression":1}
,"suppression":{"enabled":1}
,"enabled":{"switch":1}
}
;Search.control.loadWordPairs(pairs);
