var pairs =
{
"ldp_snmp_api_set_transport_addr_kind":{"call":1,"(struct":1}
,"call":{"sets":1}
,"sets":{"transport":1}
,"transport":{"address":1}
,"address":{"kind":1}
,"kind":{"used":1}
,"used":{"ldp":1}
,"ldp":{"entity":1}
,"entity":{"syntax":1,"ldp":1,"intval":1,"return":1}
,"syntax":{"int":1}
,"int":{"ldp_snmp_api_set_transport_addr_kind":1}
,"(struct":{"ldp_entity":1}
,"ldp_entity":{"*entity":1}
,"*entity":{"s_int32_t":1}
,"s_int32_t":{"intval)":1}
,"intval)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"entity":1}
,"intval":{"value":1}
,"value":{"label":1}
,"label":{"retention":1}
,"retention":{"mode":1}
,"mode":{"output":1}
,"output":{"parameters":1}
,"return":{"values":1}
,"values":{"ldp_success":1}
,"ldp_success":{"ldp_error":1}
}
;Search.control.loadWordPairs(pairs);
