var pairs =
{
"ripng_redistribute_metric_rmap_set":{"function":1,"(u_int32_t":1}
,"function":{"implements":1,"called":1}
,"implements":{"redistribute":1}
,"redistribute":{"metric":1}
,"metric":{"route":1,"redistribution":1,"syntax":1,"char":1,"metric":1,"value":1}
,"route":{"map":1,"kernel":1}
,"map":{"command":1,"redistributes":1,"configured":1,"name":1}
,"command":{"specify":1,"redistribute":1}
,"specify":{"metric":1}
,"redistributes":{"routes":1}
,"routes":{"learned":1,"function":1}
,"learned":{"routing":1}
,"routing":{"protocols":1}
,"protocols":{"(ospf":1}
,"(ospf":{"is-is":1}
,"is-is":{"bgp)":1}
,"bgp)":{"ripng":1}
,"ripng":{"kernel":1,"uses":1}
,"kernel":{"connected":1}
,"connected":{"static":1}
,"static":{"distributed":1,"ospf":1}
,"distributed":{"ripng":1}
,"uses":{"route":1}
,"configured":{"sets":1}
,"sets":{"metric":1}
,"redistribution":{"routes":1}
,"called":{"following":1}
,"following":{"command":1}
,"syntax":{"int":1}
,"int":{"ripng_redistribute_metric_rmap_set":1,"instance":1,"metric":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"int":1,"virtual":1,"exist":1}
,"instance":{"char":1,"number":1,"type_str":1,"found":1}
,"char":{"*type_str":1,"*name)":1}
,"*type_str":{"int":1}
,"*name)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1,"16>":1,"range":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"parameter":1}
,"parameter":{"instance":1}
,"number":{"instance":1}
,"type_str":{"type":1,"name":1}
,"type":{"route":1}
,"ospf":{"bgp":1}
,"bgp":{"metric":1}
,"16>":{"name":1}
,"name":{"route":1,"output":1,"null":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"rip_api_set_err_invalid_value":1}
,"rip_api_set_err_invalid_value":{"type_str":1}
,"null":{"rip_api_set_err_metric_invalid":1}
,"rip_api_set_err_metric_invalid":{"metric":1}
,"range":{"ripng_metric_infinity":1}
,"ripng_metric_infinity":{"rip_api_set_err_process_not_exist":1}
,"rip_api_set_err_process_not_exist":{"instance":1}
,"found":{"rip_api_set_err_vr_not_exist":1}
,"rip_api_set_err_vr_not_exist":{"vr_id":1}
,"exist":{"rip_api_set_success":1}
,"rip_api_set_success":{"successful":1}
}
;Search.control.loadWordPairs(pairs);
