var pairs =
{
"lldpv2_snmp_set_ntfy_interval":{"function":1,"(u_int32_t":1}
,"function":{"called":1,"succeeds":1,"fails":1}
,"called":{"interval":1}
,"interval":{"transmissions":1,"value":1}
,"transmissions":{"lldp":1}
,"lldp":{"notifications":1}
,"notifications":{"during":1}
,"during":{"normal":1}
,"normal":{"transmission":1}
,"transmission":{"periods":1}
,"periods":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"lldpv2_snmp_set_ntfy_interval":1}
,"(u_int32_t":{"ntfy_interval)":1}
,"ntfy_interval)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ntfy_interval":1,"none":1}
,"ntfy_interval":{"specify":1}
,"specify":{"notification":1}
,"notification":{"interval":1}
,"value":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"lldp_api_success":1}
,"lldp_api_success":{"function":1}
,"succeeds":{"lldp_api_error":1}
,"lldp_api_error":{"function":1}
}
;Search.control.loadWordPairs(pairs);
