var pairs =
{
"ospf6_restart_helper_grace_period_set":{"function":1,"(u_int32_t":1}
,"function":{"sets":1,"called":1,"succeeds":1}
,"sets":{"configured":1}
,"configured":{"maximum":1}
,"maximum":{"grace":1}
,"grace":{"period":1}
,"period":{"neighbor":1,"1800>":1,"ospf6_api_set_success":1}
,"neighbor":{"act":1}
,"act":{"helper":1}
,"helper":{"function":1,"max-grace-period":1}
,"called":{"following":1}
,"following":{"command":1}
,"command":{"ipv6":1}
,"ipv6":{"ospf":1}
,"ospf":{"restart":1}
,"restart":{"helper":1}
,"max-grace-period":{"syntax":1}
,"syntax":{"int":1}
,"int":{"ospf6_restart_helper_grace_period_set":1,"seconds)":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"int":1,"virtual":1}
,"seconds)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"non-virtual-router":1,"exist":1}
,"non-virtual-router":{"implementation":1}
,"implementation":{"specify":1}
,"specify":{"seconds":1}
,"seconds":{"grace":1}
,"1800>":{"output":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"ospf6_api_set_err_vr_not_exist":1}
,"ospf6_api_set_err_vr_not_exist":{"virtual":1}
,"exist":{"ospf6_api_set_err_grace_period_invalid":1}
,"ospf6_api_set_err_grace_period_invalid":{"invalid":1}
,"invalid":{"grace":1}
,"ospf6_api_set_success":{"function":1}
}
;Search.control.loadWordPairs(pairs);
