var pairs =
{
"distribute-list":{"command":1,"word":1,"list1":1}
,"command":{"filter":1,"redistributes":1,"disable":1,"syntax":1,"mode":1}
,"filter":{"networks":1,"incoming":1,"outgoing":1}
,"networks":{"routing":1}
,"routing":{"updates":1,"protocols":1,"table":1}
,"updates":{"command":1,"filter":1,"kernel":1,"based":1}
,"redistributes":{"routing":1,"running":1}
,"protocols":{"ospf":1}
,"ospf":{"routing":1,"(<1-65535>":1,"specify":1,"process":1,"processes":1,"100":1}
,"table":{"parameter":1}
,"parameter":{"command":1}
,"disable":{"function":1}
,"function":{"command":1}
,"syntax":{"distribute-list":1}
,"word":{"(kernel":1,"distribute-list":1,"parameters":1,"specify":1}
,"(kernel":{"connected":1}
,"connected":{"static":1,"specify":1,"routes":1}
,"static":{"rip":1,"specify":1,"routes":1}
,"rip":{"bgp":1,"specify":1,"routes":1}
,"bgp":{"isis":1,"specify":1,"routes":1,"routing":1,"(config-router)":1}
,"isis":{"ospf":1,"specify":1}
,"(<1-65535>":{"|))":1}
,"|))":{"distribute-list":1}
,"parameters":{"word":1}
,"specify":{"name":1,"kernel":1,"connected":1,"static":1,"rip":1,"bgp":1,"is-is":1,"ospf":1}
,"name":{"access":1}
,"access":{"list":1}
,"list":{"filter":1,"list1":1}
,"incoming":{"routing":1}
,"outgoing":{"routing":1}
,"kernel":{"specify":1,"routes":1}
,"routes":{"connected":1,"static":1,"rip":1,"bgp":1,"isis":1,"ospf":1}
,"is-is":{"routes":1}
,"process":{"<1-65535>":1}
,"<1-65535>":{"specify":1,"specified":1}
,"specified":{"command":1}
,"running":{"ospf":1}
,"processes":{"command":1}
,"mode":{"router":1,"examples":1}
,"router":{"mode":1,"ospf":1}
,"examples":{"following":1}
,"following":{"example":1}
,"example":{"shows":1}
,"shows":{"distribution":1}
,"distribution":{"bgp":1}
,"based":{"access":1}
,"list1":{"(network":1,"permit":1,"bgp":1}
,"(network":{"172.10.0.0)":1}
,"172.10.0.0)":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"access-list":1,"router":1}
,"access-list":{"list1":1}
,"permit":{"172.10.0.0\u002F16":1}
,"172.10.0.0\u002F16":{"(config)":1}
,"100":{"(config-router)":1}
,"(config-router)":{"distribute-list":1,"redistribute":1}
,"redistribute":{"bgp":1}
}
;Search.control.loadWordPairs(pairs);
