var pairs =
{
"pal_kernel_gratuitous_arp_send":{"function":1,"(struct":1}
,"function":{"sends":1}
,"sends":{"given":1}
,"given":{"gratuitous":1,"interface":1}
,"gratuitous":{"arp":1}
,"arp":{"message":1}
,"message":{"given":1,"ifp":1}
,"interface":{"api":1,"*ifp)":1,"output":1}
,"api":{"call":1}
,"call":{"result_t":1}
,"result_t":{"pal_kernel_gratuitous_arp_send":1}
,"(struct":{"lib_globals":1}
,"lib_globals":{"*lib_node":1}
,"*lib_node":{"struct":1}
,"struct":{"stream":1,"interface":1}
,"stream":{"*ap":1}
,"*ap":{"struct":1}
,"*ifp)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"lib_node":1,"none":1}
,"lib_node":{"global":1}
,"global":{"variables":1}
,"variables":{"gratuitous":1}
,"ifp":{"pointer":1}
,"pointer":{"interface":1}
,"output":{"parameters":1}
,"none":{"result":1}
,"result":{"value":1}
,"value":{"platform":1}
,"platform":{"dependent":1}
}
;Search.control.loadWordPairs(pairs);
