var pairs =
{
"nsm_dcb_bridge_disable":{"function":1,"(u_int32_t":1}
,"function":{"disables":1,"succeeds":1}
,"disables":{"dcb":1}
,"dcb":{"switch":1,"default":1,"bridge":1,"already":1,"cannot":1}
,"switch":{"(bridge)":1}
,"(bridge)":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"nsm_dcb_bridge_disable":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1}
,"char":{"*bridge_name)":1}
,"*bridge_name)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"bridge_name":1}
,"bridge_name":{"bridge":1}
,"bridge":{"null":1,"output":1,"default":1,"found":1}
,"null":{"function":1}
,"default":{"bridge":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_dcb_api_set_success":1}
,"nsm_dcb_api_set_success":{"function":1}
,"succeeds":{"nsm_dcb_api_set_err_no_nm":1}
,"nsm_dcb_api_set_err_no_nm":{"nsm":1}
,"nsm":{"master":1}
,"master":{"found":1}
,"found":{"nsm_bridge_err_notfound":1,"nsm_dcb_api_set_err_no_dcbg":1,"nsm_dcb_api_set_err_dcb_exists":1}
,"nsm_bridge_err_notfound":{"given":1}
,"given":{"bridge":1}
,"nsm_dcb_api_set_err_no_dcbg":{"dcb":1}
,"nsm_dcb_api_set_err_dcb_exists":{"dcb":1}
,"already":{"disabled":1}
,"disabled":{"nsm_dcb_api_set_err_hw_no_support":1,"hardware":1}
,"nsm_dcb_api_set_err_hw_no_support":{"dcb":1}
,"cannot":{"disabled":1}
}
;Search.control.loadWordPairs(pairs);
