var pairs =
{
"nterfaces":{"vrrp":1}
,"vrrp":{"interacts":1,"layer":1,"protocol":1,"requires":1}
,"interacts":{"following":1,"nsm":1,"sending":1,"passing":1}
,"following":{"zebos-xp":1}
,"zebos-xp":{"components":1,"cli":1}
,"components":{"vrrp":1}
,"nsm":{"hsl":1}
,"hsl":{"imi":1}
,"imi":{"management":1}
,"management":{"interface":1,"zebos-xp":1,"vrrp":1}
,"interface":{"snmp":1,"(cli)":1}
,"snmp":{"agent":1,"vrrp":1,"cli":1}
,"agent":{"network":1}
,"network":{"services":1}
,"services":{"module":1}
,"module":{"(nsm)":1}
,"(nsm)":{"corresponds":1}
,"corresponds":{"system":1,"forwarding":1}
,"system":{"layer":1}
,"layer":{"forwarding":1,"configuration":1,"vrrp":1,"setting":1}
,"forwarding":{"engine":1,"layer":1}
,"engine":{"(fe)":1}
,"(fe)":{"corresponds":1}
,"configuration":{"management":1,"command":1,"application":1}
,"cli":{"snmp":1}
,"protocol":{"interacts":1,"(arp)":1}
,"sending":{"receiving":1,"gratuitous":1}
,"receiving":{"advertisement":1}
,"advertisement":{"messages":1}
,"messages":{"(ip":1,"configuration":1}
,"(ip":{"multicast)":1}
,"multicast)":{"may":1}
,"may":{"require":1}
,"require":{"interaction":1}
,"interaction":{"initialization":1}
,"initialization":{"system":1}
,"requires":{"support":1,"configuration":1}
,"support":{"system":1}
,"setting":{"timer":1}
,"timer":{"message":1}
,"message":{"passing":1}
,"passing":{"queuing":1,"table":1}
,"queuing":{"facilities":1}
,"facilities":{"forwarding":1}
,"table":{"information":1}
,"information":{"sending":1}
,"gratuitous":{"address":1}
,"address":{"resolution":1}
,"resolution":{"protocol":1}
,"(arp)":{"messages":1}
,"command":{"line":1}
,"line":{"interface":1}
,"(cli)":{"exists":1}
,"exists":{"configuration":1}
,"application":{"methods":1}
,"methods":{"snmp":1}
}
;Search.control.loadWordPairs(pairs);
