var pairs =
{
"virtual":{"circuit":1}
,"circuit":{"service":1,"(config-itut-meg)":1,"101":1}
,"service":{"pe1":1,"type":1,"101":1}
,"pe1":{"(oam)":1,"itut":1}
,"(oam)":{"configure":1}
,"configure":{"terminal":1,"mode":1,"meg":1,"service":1,"mep":1,"remote":1,"name":1}
,"terminal":{"enter":1}
,"enter":{"configure":1}
,"mode":{"(config)":1}
,"(config)":{"itut":1}
,"itut":{"meg":1}
,"meg":{"meg-v":1,"name":1,"brief":1,"index":1,"level":1}
,"meg-v":{"configure":1,"(config-itut-meg)":1}
,"name":{"meg-v":1,"meg-1":1,"me-1":1}
,"(config-itut-meg)":{"service":1,"mep-id":1}
,"type":{"configure":1,"virtual":1,"meg":1}
,"mep-id":{"1111":1,"4444":1}
,"1111":{"configure":1,"(config-itut-mp)":1,"icc":1,"101":1}
,"mep":{"identifier":1,"pe2":1,"validation":1}
,"identifier":{"1111":1}
,"(config-itut-mp)":{"service":1,"rmep-id":1}
,"101":{"associate":1,"(config-itut-mp)":1,"oper":1}
,"associate":{"virtual":1}
,"rmep-id":{"4444":1,"1111":1}
,"4444":{"icc":1,"configure":1,"101":1}
,"icc":{"airtel":1}
,"airtel":{"umc":1}
,"umc":{"meg-v":1}
,"remote":{"mep":1}
,"pe2":{"(oam)":1}
,"meg-1":{"(config-itut-meg)":1}
,"me-1":{"(config-itut-mp)":1}
,"validation":{"pe1":1}
,"brief":{"maintenance":1}
,"maintenance":{"entity":1}
,"entity":{"group":1}
,"group":{"inairtel\u002Fmeg-v":1}
,"inairtel\u002Fmeg-v":{"meg":1,",4444":1,",1111":1}
,"index":{"service":1}
,"level":{"---------------------------------------------------------------------------mp-id":1}
,"---------------------------------------------------------------------------mp-id":{"1111":1,"4444":1}
,"oper":{"status":1}
,"status":{"rmep":1}
,"rmep":{"inairtel\u002Fmeg-v":1}
,",4444":{"---------------------------------------------------------------------------pe2":1}
,"---------------------------------------------------------------------------pe2":{"itut":1}
,",1111":{"---------------------------------------------------------------------------":1}
}
;Search.control.loadWordPairs(pairs);
