var pairs =
{
"ethernet":{"synchronization":1}
,"synchronization":{"message":1,"status":1}
,"message":{"channel":1,"(ssm)":1,"sent":1,"types":1}
,"channel":{"itu-t":1,"(esmc)":1}
,"itu-t":{"g.8264":1}
,"g.8264":{"defines":1}
,"defines":{"ethernet":1}
,"(esmc)":{"protocol":1}
,"protocol":{"carries":1,"(ossp)":1}
,"carries":{"synchronization":1}
,"status":{"message":1}
,"(ssm)":{"nodes":1}
,"nodes":{"synchronize":1}
,"synchronize":{"frequency":1}
,"frequency":{"esmc":1}
,"esmc":{"based":1,"messages":1}
,"based":{"ieee":1}
,"ieee":{"802.3":1}
,"802.3":{"organization":1}
,"organization":{"specific":1}
,"specific":{"slow":1}
,"slow":{"protocol":1}
,"(ossp)":{"two":1}
,"two":{"types":1}
,"types":{"esmc":1,"contain":1}
,"messages":{"information":1}
,"information":{"message":1}
,"sent":{"once":1,"immediately":1}
,"once":{"per":1}
,"per":{"second":1}
,"second":{"acts":1}
,"acts":{"heartbeat":1}
,"heartbeat":{"event":1}
,"event":{"message":1,"causes":1}
,"immediately":{"event":1}
,"causes":{"ssm":1}
,"ssm":{"value":1}
,"value":{"change":1}
,"change":{"message":1}
,"contain":{"ssm":1}
}
;Search.control.loadWordPairs(pairs);
