var pairs =
{
"cspf":{"modifications":1,"extended":1,"computation":1}
,"modifications":{"rsvp-te":1}
,"rsvp-te":{"fast":1}
,"fast":{"reroute":1}
,"reroute":{"rsvp-te":1,"feature":1}
,"feature":{"cspf":1}
,"extended":{"support":1}
,"support":{"path":1}
,"path":{"constraint":1,"tlv":1,"type":1}
,"constraint":{"exclude":1}
,"exclude":{"route":1,"path":1}
,"route":{"new":1,"request":1,"address":1,"link":1,"node":1,"computation":1}
,"new":{"tlv":1}
,"tlv":{"(exclude":1,"contains":1,"+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+":1,"type":1,"refer":1,"types":1,"data":1}
,"(exclude":{"path)":1}
,"path)":{"added":1}
,"added":{"route":1}
,"request":{"message":1}
,"message":{"tlv":1}
,"contains":{"ipv4":1,"flag":1}
,"ipv4":{"ipv6":1,"exclude":1}
,"ipv6":{"addresses":1}
,"addresses":{"avoided":1,"following":1}
,"avoided":{"cspf":1,"exclude":1,"route":1}
,"computation":{"engine":1}
,"engine":{"computing":1,"default":1}
,"computing":{"constrained":1}
,"constrained":{"route":1}
,"address":{"contains":1,"avoided":1,"belongs":1,"address":1,"node":1}
,"flag":{"specifying":1}
,"specifying":{"whether":1}
,"whether":{"link":1}
,"link":{"node":1,"exclude":1,"-the":1,"identified":1}
,"node":{"node":1,"itself":1,"exclude":1,"-the":1,"specified":1,"considered":1}
,"itself":{"excluded":1}
,"excluded":{"ipv4":1}
,"+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+":{"tlv":1,"type":1,"+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+":1}
,"type":{"(0x0110)":1,"address1":1,"address2":1,"two-byte":1,"tlv":1,"exclude":1,"indicates":1}
,"(0x0110)":{"length":1}
,"length":{"+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+":1,"two-byte":1}
,"address1":{"+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+":1}
,"address2":{"+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+":1}
,"two-byte":{"unsigned":1}
,"unsigned":{"integer":1}
,"integer":{"identifies":1,"specifies":1}
,"identifies":{"type":1}
,"refer":{"appendix":1}
,"appendix":{"message":1}
,"types":{"tlv":1,"length":1}
,"specifies":{"number":1}
,"number":{"addresses":1}
,"following":{"data":1}
,"data":{"actual":1,"calculated":1}
,"actual":{"size":1}
,"size":{"tlv":1,"=length":1}
,"calculated":{"formula":1}
,"formula":{"size":1}
,"=length":{"path":1}
,"-the":{"presence":1}
,"presence":{"path":1}
,"indicates":{"link":1,"node":1}
,"identified":{"specified":1}
,"specified":{"address":1}
,"belongs":{"avoided":1}
,"default":{"value":1}
,"value":{"address":1}
,"considered":{"remaining":1}
,"remaining":{"fields":1}
,"fields":{"variable":1}
,"variable":{"length":1}
}
;Search.control.loadWordPairs(pairs);
