var pairs =
{
"virtual":{"router":1,"routers":1}
,"router":{"(vr)":1,"multiple":1,"independently":1,"time":1}
,"(vr)":{"virtual":1,"feature":1}
,"feature":{"logically":1}
,"logically":{"subdivides":1}
,"subdivides":{"physical":1}
,"physical":{"router":1}
,"multiple":{"virtual":1,"vrfs":1,"routing":1}
,"routers":{"virtual":1}
,"independently":{"monitored":1}
,"monitored":{"managed":1}
,"managed":{"network":1}
,"network":{"administrator":1}
,"administrator":{"multiple":1}
,"vrfs":{"(virtual":1,"zebos-xp":1}
,"(virtual":{"routing":1}
,"routing":{"forwarding":1,"tables":1,"protocols":1}
,"forwarding":{"instances)":1}
,"instances)":{"supporting":1}
,"supporting":{"multiple":1}
,"tables":{"(ribs)":1}
,"(ribs)":{"co-existing":1}
,"co-existing":{"within":1}
,"within":{"router":1}
,"time":{"single":1}
,"single":{"instance":1}
,"instance":{"zebos-xp":1}
,"zebos-xp":{"manages":1,"offers":1}
,"manages":{"vrs":1}
,"vrs":{"vrfs":1}
,"offers":{"support":1}
,"support":{"ipv4":1}
,"ipv4":{"ipv6":1}
,"ipv6":{"routing":1}
}
;Search.control.loadWordPairs(pairs);
