var pairs =
{
"show":{"application-priority":1}
,"application-priority":{"bridge":1}
,"bridge":{"command":1,"(switch)":1,"<1-32>":1,"bridge":1,"admin":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"application":1}
,"application":{"priority":1}
,"priority":{"table":1}
,"table":{"bridge":1}
,"(switch)":{"command":1}
,"syntax":{"show":1}
,"<1-32>":{"parameter":1,"bridge":1}
,"parameter":{"<1-32>":1}
,"mode":{"exec":1,"example":1,"advertise":1}
,"exec":{"mode":1}
,"example":{"show":1}
,"admin":{"configuration":1,"config":1}
,"configuration":{"intf":1}
,"intf":{"admin":1}
,"config":{"protocol":1}
,"protocol":{"protoid":1}
,"protoid":{"priorities":1}
,"priorities":{"mode":1}
,"advertise":{"==============================================================================eth1":1}
,"==============================================================================eth1":{"ethertype":1}
,"ethertype":{"eth1":1,"arp":1}
,"eth1":{"ethertype":1,"udp":1,"tcp":1}
,"arp":{"eth1":1}
,"udp":{"telnet":1}
,"telnet":{"eth1":1}
,"tcp":{"telnet":1}
}
;Search.control.loadWordPairs(pairs);
