var pairs =
{
"zebos2":{"verify":1,"ptp":1}
,"verify":{"transparent":1,"port":1}
,"transparent":{"data":1,"clock":1}
,"data":{"zebos2":1,"transparent":1}
,"ptp":{"data":1,"port":1}
,"clock":{"(transparent)":1,"identity":1,"clock":1}
,"(transparent)":{"clock":1}
,"identity":{"ff:fe:52:54:0:ac:10:9":1}
,"ff:fe:52:54:0:ac:10:9":{"number":1,"port":1}
,"number":{"ports":1,"delay":1}
,"ports":{"delay":1}
,"delay":{"mechanism":1,"request":1}
,"mechanism":{"peer":1}
,"peer":{"peer":1,"primary":1,"mean":1}
,"primary":{"domain":1}
,"domain":{"verify":1}
,"port":{"data":1,"===========================================%":1,"number":1}
,"===========================================%":{"transparent":1}
,"request":{"interval":1}
,"interval":{"(log":1}
,"(log":{"base":1}
,"base":{"peer":1}
,"mean":{"path":1}
,"path":{"delay:0":1}
,"delay:0":{"faulty":1}
,"faulty":{"flag":1}
,"flag":{"===========================================%":1}
}
;Search.control.loadWordPairs(pairs);
