var pairs =
{
"show":{"g8032":1}
,"g8032":{"profile":1}
,"profile":{"command":1,"profilename":1,"name":1,"profile1":1}
,"command":{"display":1,"syntax":1,"mode":1}
,"display":{"details":1}
,"details":{"profile":1}
,"syntax":{"show":1}
,"profilename":{"bridge":1,"profile":1}
,"bridge":{"(<1-32>":1,"bridge":1,"<1-32>":1,"identifier":1,"command":1,"profile":1}
,"(<1-32>":{"backbone)":1}
,"backbone)":{"parameters":1}
,"parameters":{"profilename":1}
,"name":{"bridge":1}
,"<1-32>":{"bridge":1}
,"identifier":{"backbone":1}
,"backbone":{"backbone":1,"bridge":1}
,"mode":{"configure":1,"examples":1}
,"configure":{"mode":1}
,"examples":{"(config)":1}
,"(config)":{"show":1}
,"profile1":{"bridge":1,"=========wait-to-restore":1}
,"=========wait-to-restore":{"mins":1}
,"mins":{"hold":1}
,"hold":{"timer":1}
,"timer":{"secs":1,"500":1}
,"secs":{"guard":1}
,"guard":{"timer":1}
,"500":{"wait-to-block":1}
,"wait-to-block":{"5500":1}
,"5500":{"protection":1}
,"protection":{"type":1}
,"type":{"revertive":1}
}
;Search.control.loadWordPairs(pairs);
