var pairs =
{
"pim6_api_vif_dr_priority_unset":{"function":1,"(u_int32_t":1}
,"function":{"remove":1,"executes":1}
,"remove":{"configuration":1}
,"configuration":{"pim":1}
,"pim":{"vif":1,"vrf":1}
,"vif":{"priority":1,"found":1}
,"priority":{"returns":1}
,"returns":{"default":1}
,"default":{"setting":1}
,"setting":{"syntax":1}
,"syntax":{"int":1}
,"int":{"pim6_api_vif_dr_priority_unset":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1}
,"char":{"*ifname)":1}
,"*ifname)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"ifname":1}
,"ifname":{"name":1}
,"name":{"interface":1}
,"interface":{"output":1,"found":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"value":1}
,"value":{"pim_api_set_err_wrong_value":1,"given":1}
,"pim_api_set_err_wrong_value":{"invalid":1}
,"invalid":{"value":1}
,"given":{"pim_api_set_err_wrong_vrf":1}
,"pim_api_set_err_wrong_vrf":{"pim":1}
,"vrf":{"interface":1}
,"found":{"pim_api_set_err_vif_not_exist":1,"pim_api_set_success":1}
,"pim_api_set_err_vif_not_exist":{"vif":1}
,"pim_api_set_success":{"function":1}
,"executes":{"properly":1}
,"properly":{"function":1}
}
;Search.control.loadWordPairs(pairs);
