var pairs =
{
"regular":{"expressions":1,"expression":1}
,"expressions":{"table":1,"regular":1}
,"table":{"a-1":1}
,"a-1":{"shows":1}
,"shows":{"regular":1}
,"expression":{"special":1,"characters":1}
,"special":{"characters":1}
,"characters":{"used":1,"combination":1,"symbol":1,"negates":1}
,"used":{"bgp":1,"beginning":1}
,"bgp":{"commands":1}
,"commands":{"characters":1}
,"combination":{"build":1}
,"build":{"complex":1}
,"complex":{"regular":1}
,"symbol":{"character":1}
,"character":{"meaning":1,"(including":1}
,"meaning":{"caret":1}
,"caret":{"matches":1}
,"matches":{"beginning":1,"end":1,"single":1,"none":1,"sequences":1,"spaces":1}
,"beginning":{"input":1,"string":1,"end":1}
,"input":{"string":1}
,"string":{"used":1,"characters":1,"period":1,"brackets":1}
,"negates":{"pattern":1}
,"pattern":{"match":1,"plus":1,"question":1,"_underscore":1}
,"match":{"$dollar":1}
,"$dollar":{"sign":1}
,"sign":{"matches":1}
,"end":{"input":1,"points":1}
,"period":{"matches":1}
,"single":{"character":1}
,"(including":{"white":1}
,"white":{"spaces)":1}
,"spaces)":{"*asterisk":1}
,"*asterisk":{"matches":1}
,"none":{"sequences":1,"occurrence":1}
,"sequences":{"pattern":1}
,"plus":{"sign":1}
,"question":{"mark":1}
,"mark":{"matches":1}
,"occurrence":{"pattern":1}
,"_underscore":{"matches":1}
,"spaces":{"commas":1}
,"commas":{"braces":1}
,"braces":{"parenthesis":1}
,"parenthesis":{"beginning":1}
,"brackets":{"range":1}
,"range":{"single-characters":1}
,"single-characters":{"-hyphen":1}
,"-hyphen":{"separates":1}
,"separates":{"end":1}
,"points":{"range":1}
}
;Search.control.loadWordPairs(pairs);
