var pairs =
{
"direct":{"ldp":1,"session":1}
,"ldp":{"session":1,"enter":1,"interface":1}
,"session":{"example":1,"topology":1,"md5":1}
,"example":{"md5":1}
,"md5":{"authentication":1,"configure":1,"password":1}
,"authentication":{"configured":1,"password":1}
,"configured":{"direct":1,"(config-if)":1}
,"topology":{"direct":1}
,"configure":{"terminal":1,"mode":1,"md5":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"router":1}
,"mode":{"(config)":1,"(config-router)":1,"return":1,"configure":1}
,"(config)":{"router":1,"interface":1}
,"router":{"ldp":1,"mode":1}
,"(config-router)":{"neighbor":1,"exit":1}
,"neighbor":{"10.10.10.2":1,"10.10.10.1":1}
,"10.10.10.2":{"auth":1,"(config-router)":1}
,"auth":{"md5":1}
,"password":{"pwd1":1}
,"pwd1":{"configure":1,"neighbor":1}
,"exit":{"exit":1,"router":1,"interface":1}
,"return":{"configure":1}
,"interface":{"eth1":1,"(eth1)":1,"mode":1}
,"eth1":{"specify":1,"(config-if)":1}
,"specify":{"interface":1}
,"(eth1)":{"configured":1}
,"(config-if)":{"label-switching":1,"enable-ldp":1,"exit":1}
,"label-switching":{"enable":1}
,"enable":{"label":1,"ldp":1}
,"label":{"switching":1}
,"switching":{"interface":1}
,"enable-ldp":{"ipv4":1}
,"ipv4":{"enable":1}
,"10.10.10.1":{"auth":1,"(config-router)":1}
}
;Search.control.loadWordPairs(pairs);
