var pairs =
{
"nsm_dcb_app_bridge_enable":{"function":1,"(u_int32_t":1}
,"function":{"enables":1,"succeeds":1}
,"enables":{"application":1}
,"application":{"priority":1}
,"priority":{"switch":1,"already":1}
,"switch":{"(bridge)":1}
,"(bridge)":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"nsm_dcb_app_bridge_enable":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"char":1,"virtual":1}
,"char":{"*bridge_name)":1}
,"*bridge_name)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"none":1}
,"virtual":{"router":1}
,"router":{"bridge_name":1}
,"bridge_name":{"bridge":1}
,"bridge":{"output":1,"found":1,"vlan-aware":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"nsm_dcb_api_set_success":1}
,"nsm_dcb_api_set_success":{"function":1}
,"succeeds":{"nsm_dcb_api_set_err_no_nm":1}
,"nsm_dcb_api_set_err_no_nm":{"nsm":1}
,"nsm":{"master":1}
,"master":{"found":1}
,"found":{"nsm_dcb_api_set_err_interface":1,"nsm_dcb_api_set_err_no_dcbg":1,"nsm_dcb_api_set_err_no_vlan":1,"dcb":1}
,"nsm_dcb_api_set_err_interface":{"interface":1}
,"interface":{"null":1,"found":1}
,"null":{"nsm_bridge_err_notfound":1}
,"nsm_bridge_err_notfound":{"bridge":1}
,"nsm_dcb_api_set_err_no_dcbg":{"dcb":1}
,"dcb":{"bridge":1,"interface":1,"enabled":1}
,"nsm_dcb_api_set_err_no_vlan":{"bridge":1}
,"vlan-aware":{"nsm_dcb_api_set_err_dcb_interface":1}
,"nsm_dcb_api_set_err_dcb_interface":{"dcb":1}
,"enabled":{"nsm_dcb_api_set_err_app_exists":1,"bridge":1}
,"nsm_dcb_api_set_err_app_exists":{"application":1}
,"already":{"enabled":1}
}
;Search.control.loadWordPairs(pairs);
