var pairs =
{
"t-pe1":{"configure":1}
,"configure":{"terminal":1,"mode":1,"pseudowire":1,"endpoints":1,"bridge":1,"fib":1}
,"terminal":{"enter":1}
,"enter":{"configure":1,"interface":1}
,"mode":{"(config)":1,"(config-if)":1,"access":1}
,"(config)":{"mpls":1,"bridge":1,"interface":1,"exit":1}
,"mpls":{"l2-circuit":1,"l2-circuit-fib-entry":1}
,"l2-circuit":{"vc1":1}
,"vc1":{"101":1,"pseudowire":1,"ethernet":1}
,"101":{"200":1,"100":1}
,"200":{"2.2.2.2":1,"tp-tunnel":1}
,"2.2.2.2":{"666":1}
,"666":{"grp1":1}
,"grp1":{"manual":1}
,"manual":{"configure":1}
,"pseudowire":{"router":1,"name":1,"endpoints":1,"access":1,"(config)":1}
,"router":{"vc1":1,"(config-if)":1}
,"name":{"configure":1}
,"endpoints":{"note":1,"(config)":1}
,"note":{"pseudowire":1}
,"bridge":{"protocol":1,"(config)":1,"(config-if)":1}
,"protocol":{"ieee":1}
,"ieee":{"vlan-bridge":1}
,"vlan-bridge":{"configure":1}
,"interface":{"eth1":1,"mode":1,"switchport":1,"bridge":1,"access":1,"mpls-tp":1,"(config-if)":1,"edge":1}
,"eth1":{"enter":1,"configure":1}
,"(config-if)":{"switchport":1,"bridge-group":1,"mpls-tp":1,"mpls":1,"exit":1}
,"switchport":{"interface":1,"(config-if)":1,"mode":1}
,"bridge-group":{"associate":1}
,"associate":{"interface":1}
,"access":{"interface":1,"port":1}
,"port":{"(config-if)":1}
,"mpls-tp":{"service-interface":1,"service":1}
,"service-interface":{"type":1}
,"type":{"layer-2":1}
,"layer-2":{"555":1}
,"555":{"interface":1}
,"service":{"interface":1}
,"ethernet":{"bind":1}
,"bind":{"pseudowire":1}
,"edge":{"node":1}
,"node":{"router":1}
,"exit":{"exit":1,"interface":1,"configure":1}
,"l2-circuit-fib-entry":{"101":1}
,"100":{"200":1}
,"tp-tunnel":{"tn1":1}
,"tn1":{"eth1":1}
,"fib":{"entry":1}
,"entry":{"configured":1}
,"configured":{"pseudowire":1}
}
;Search.control.loadWordPairs(pairs);
