var pairs =
{
"trill_get_rbridgebase_port_stprootchanges":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"number":1}
,"number":{"times":1,"entry":1,"trill_api_get_error":1,"found":1}
,"times":{"change":1}
,"change":{"root":1}
,"root":{"bridge":1}
,"bridge":{"seen":1,"counter":1}
,"seen":{"spanning":1}
,"spanning":{"tree":1}
,"tree":{"bpdus":1}
,"bpdus":{"received":1}
,"received":{"port":1}
,"port":{"syntax":1,"number":1}
,"syntax":{"int":1}
,"int":{"trill_get_rbridgebase_port_stprootchanges":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"integer":1}
,"u_int32_t":{"instance":1,"baseport":1,"*ret)":1}
,"instance":{"u_int32_t":1,"integer":1,"baseport":1,"port":1}
,"baseport":{"u_int32_t":1,"port":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"ret":1}
,"integer":{"contains":1}
,"contains":{"trill":1,"rbridge":1}
,"trill":{"identifier":1,"instance":1}
,"identifier":{"instance":1}
,"entry":{"contains":1}
,"rbridge":{"management":1}
,"management":{"information":1}
,"information":{"output":1}
,"output":{"parameters":1}
,"ret":{"pointer":1}
,"pointer":{"root":1}
,"counter":{"return":1}
,"return":{"value":1}
,"value":{"trill_api_get_success":1}
,"trill_api_get_success":{"valid":1}
,"valid":{"instance":1}
,"trill_api_get_error":{"valid":1}
}
;Search.control.loadWordPairs(pairs);
