var pairs =
{
"neighbor":{"capability":1,"(a.b.c.d":1,"ipv4":1,"ipv6":1,"peer-group":1,"remote-as":1,"10.10.10.1":1}
,"capability":{"route-refresh":1,"support":1,"supported":1}
,"route-refresh":{"command":1,"neighbor":1,"parameters":1}
,"command":{"advertise":1,"disable":1,"syntax":1,"command":1,"applies":1,"mode":1}
,"advertise":{"peer":1}
,"peer":{"route":1,"re-advertises":1,"group":1,"groups":1}
,"route":{"refresh":1}
,"refresh":{"capability":1}
,"support":{"route":1}
,"supported":{"router":1}
,"router":{"dynamically":1,"mode":1,"bgp":1}
,"dynamically":{"request":1}
,"request":{"peer":1}
,"re-advertises":{"adj-rib-out":1}
,"adj-rib-out":{"parameter":1}
,"parameter":{"command":1,"used":1}
,"disable":{"function":1}
,"function":{"command":1}
,"syntax":{"neighbor":1}
,"(a.b.c.d":{"x:x":1}
,"x:x":{":x:x":1}
,":x:x":{"word)":1,"address":1}
,"word)":{"capability":1}
,"parameters":{"a.b.c.d":1}
,"a.b.c.d":{"address":1}
,"address":{"bgp":1}
,"bgp":{"neighbor":1,"peer":1,"(config-router)":1}
,"ipv4":{"format":1}
,"format":{"x:x":1,"word":1}
,"ipv6":{"format":1}
,"word":{"name":1}
,"name":{"bgp":1}
,"group":{"information":1,"command":1}
,"information":{"create":1}
,"create":{"peer":1}
,"groups":{"refer":1}
,"refer":{"neighbor":1}
,"peer-group":{"neighbor":1}
,"remote-as":{"commands":1}
,"commands":{"parameter":1}
,"used":{"command":1}
,"applies":{"peers":1}
,"peers":{"group":1}
,"mode":{"router":1,"examples":1}
,"examples":{"configure":1}
,"configure":{"terminal":1}
,"terminal":{"(config)":1}
,"(config)":{"router":1}
,"(config-router)":{"neighbor":1}
,"10.10.10.1":{"capability":1}
}
;Search.control.loadWordPairs(pairs);
