var pairs =
{
"verification":{"validation":1}
,"validation":{"enter":1}
,"enter":{"commands":1}
,"commands":{"listed":1,"ib-beb-1":1}
,"listed":{"sections":1}
,"sections":{"below":1}
,"below":{"confirm":1}
,"confirm":{"configurations":1}
,"configurations":{"verify":1}
,"verify":{"cfm":1,"aps":1,"switchover":1}
,"cfm":{"configuration":1,"pbb-te":1}
,"configuration":{"aps":1,"ib-beb-1":1}
,"aps":{"ib-beb-1":1,"configuration":1}
,"ib-beb-1":{"ib-beb-1":1,"show":1,"ib-beb-2":1,"check":1,"(config)":1,"(config-if)":1,"shut":1}
,"show":{"ethernet":1,"pbb-te":1}
,"ethernet":{"cfm":1}
,"pbb-te":{"maintenance-points":1,"aps-group":1}
,"maintenance-points":{"remote":1}
,"remote":{"domain-name":1,"mac":1}
,"domain-name":{"abc":1}
,"abc":{"te-sid":1}
,"te-sid":{"bridge":1}
,"bridge":{"backbone":1,"apsid":1}
,"backbone":{"mpid":1}
,"mpid":{"level":1}
,"level":{"tesid":1}
,"tesid":{"mep-up":1}
,"mep-up":{"remote":1}
,"mac":{"rdi":1}
,"rdi":{"te-mismatch":1}
,"te-mismatch":{"-------------------------------------------------------------------------------------70":1,"-------------------------------------------------------------------------------------40":1}
,"-------------------------------------------------------------------------------------70":{"0005.1111.1212":1}
,"0005.1111.1212":{"false":1}
,"false":{"ib-beb-1":1}
,"ib-beb-2":{"ib-beb-2":1,"show":1,"verify":1}
,"-------------------------------------------------------------------------------------40":{"0005.1111.1211":1}
,"0005.1111.1211":{"true":1}
,"true":{"ib-beb-2":1}
,"aps-group":{"bridge":1}
,"apsid":{"working-path":1}
,"working-path":{"protection-path":1}
,"protection-path":{"current-state":1}
,"current-state":{"active-path":1}
,"active-path":{"---------------------------------------------------------------------------------------backbone":1,"--------------------------------------------------------------------------------------backbone":1}
,"---------------------------------------------------------------------------------------backbone":{"no-request":1}
,"no-request":{"ib-beb-2":1,"verify":1,"eth1":1}
,"switchover":{"process":1,"takes":1,"using":1}
,"process":{"eth1":1}
,"eth1":{"down":1,"ib-beb-1":1}
,"down":{"ib-beb-1":1,"active":1}
,"check":{"switchover":1}
,"takes":{"place":1}
,"place":{"correctly":1}
,"correctly":{"working-tesi":1}
,"working-tesi":{"down":1}
,"(config)":{"interface":1}
,"interface":{"eth1":1}
,"(config-if)":{"shutdown":1,"end":1}
,"shutdown":{"ib-beb-1":1}
,"end":{"verify":1}
,"using":{"following":1}
,"following":{"commands":1}
,"--------------------------------------------------------------------------------------backbone":{"working":1,"no-request":1}
,"working":{"ib-beb-1":1}
,"shut":{"down":1}
,"active":{"path":1}
,"path":{"becomes":1}
,"becomes":{"protection-tesi":1}
}
;Search.control.loadWordPairs(pairs);
