var pairs =
{
"rsvp_snmp_get_tn_row_status":{"function":1,"(u_int32_t":1}
,"function":{"gets":1,"succeeds":1}
,"gets":{"row":1}
,"row":{"status":1}
,"status":{"tunnel":1}
,"tunnel":{"syntax":1,"index":1,"instance":1}
,"syntax":{"u_int32_t":1}
,"u_int32_t":{"rsvp_snmp_get_tn_row_status":1,"*inst_ix":1,"*ret)":1}
,"(u_int32_t":{"*tn_ix":1}
,"*tn_ix":{"u_int32_t":1}
,"*inst_ix":{"struct":1}
,"struct":{"pal_in4_addr":1}
,"pal_in4_addr":{"*ing_id":1,"*eg_id":1}
,"*ing_id":{"struct":1}
,"*eg_id":{"u_int32_t":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"tn_ix":1,"ret":1}
,"tn_ix":{"tunnel":1}
,"index":{"inst_ix":1,"ing_id":1}
,"inst_ix":{"instance":1}
,"instance":{"index":1,"found":1}
,"ing_id":{"ingress":1}
,"ingress":{"lsr":1}
,"lsr":{"identifier":1}
,"identifier":{"eg_id":1,"output":1}
,"eg_id":{"egress":1}
,"egress":{"lsr":1}
,"output":{"parameters":1}
,"ret":{"constants":1}
,"constants":{"rsvpd\u002Frsvp_snmp.h":1}
,"rsvpd\u002Frsvp_snmp.h":{"rsvp_snmp_row_status_active":1}
,"rsvp_snmp_row_status_active":{"rsvp_snmp_row_status_notinservice":1}
,"rsvp_snmp_row_status_notinservice":{"rsvp_snmp_row_status_notready":1}
,"rsvp_snmp_row_status_notready":{"rsvp_snmp_row_status_createandgo":1}
,"rsvp_snmp_row_status_createandgo":{"rsvp_snmp_row_status_createandwait":1}
,"rsvp_snmp_row_status_createandwait":{"rsvp_snmp_row_status_destroy":1}
,"rsvp_snmp_row_status_destroy":{"return":1}
,"return":{"value":1}
,"value":{"rsvp_api_get_success":1}
,"rsvp_api_get_success":{"function":1}
,"succeeds":{"rsvp_api_get_error":1}
,"rsvp_api_get_error":{"tunnel":1}
}
;Search.control.loadWordPairs(pairs);
