var pairs =
{
"debug":{"ipv6":1}
,"ipv6":{"pim":1}
,"pim":{"timer":1,"joinprune":1,"(vrf":1}
,"timer":{"joinprune":1,"(et)":1,"(jt)":1,"(kat)":1,"(ot)":1,"((ppt)":1}
,"joinprune":{"command":1,"timers":1,"debug":1,"kat":1,"ppt":1,"expiry":1,"upstream":1,"keep":1,"prunepending":1}
,"command":{"enable":1,"disable":1,"syntax":1,"mode":1}
,"enable":{"debugging":1}
,"debugging":{"various":1,"pim":1}
,"various":{"pim":1}
,"timers":{"option":1,"command":1}
,"option":{"command":1}
,"disable":{"debugging":1}
,"syntax":{"debug":1}
,"kat":{"debug":1,"turn":1}
,"ppt":{"debug":1,"parameters":1,"turn":1}
,"(vrf":{"name":1}
,"name":{"timer":1,"specify":1,"vpn":1}
,"parameters":{"vrf":1}
,"vrf":{"vpn":1}
,"vpn":{"routing\u002Fforwarding":1}
,"routing\u002Fforwarding":{"instance":1}
,"instance":{"name":1,"turn":1}
,"specify":{"name":1}
,"turn":{"turn":1,"pim":1}
,"expiry":{"timer":1}
,"(et)":{"turn":1}
,"upstream":{"join":1,"override":1}
,"join":{"timer":1}
,"(jt)":{"kat":1}
,"keep":{"alive":1}
,"alive":{"timer":1}
,"(kat)":{"turn":1}
,"override":{"timer":1}
,"(ot)":{"ppt":1}
,"prunepending":{"timer":1}
,"((ppt)":{"command":1}
,"mode":{"exec":1,"privilege":1,"configure":1,"example":1}
,"exec":{"mode":1}
,"privilege":{"exec":1}
,"configure":{"mode":1}
,"example":{"debug":1}
}
;Search.control.loadWordPairs(pairs);
