var pairs =
{
"system":{"implementation":1}
,"implementation":{"support":1,"elmi":1}
,"support":{"mef-16":1,"elmi":1}
,"mef-16":{"specification":1}
,"specification":{"elmi":1}
,"elmi":{"implemented":1,"opens":1,"protocol":1,"depends":1,"incorporates":1,"onmd":1,"uses":1,"lacp":1,"initialization":1}
,"implemented":{"separate":1}
,"separate":{"daemon":1,"socket":1}
,"daemon":{"called":1}
,"called":{"elmid":1,"elmi":1}
,"elmid":{"during":1}
,"during":{"operation":1}
,"operation":{"elmi":1}
,"opens":{"separate":1}
,"socket":{"(af_elmi)":1}
,"(af_elmi)":{"kernel":1}
,"kernel":{"send":1}
,"send":{"receive":1}
,"receive":{"control":1}
,"control":{"packets":1,"protocol)":1}
,"packets":{"furthermore":1}
,"furthermore":{"elmi":1}
,"protocol":{"operates":1,"server":1,"includes":1,"specific":1}
,"operates":{"uni-c":1}
,"uni-c":{"uni-n":1}
,"uni-n":{"uni":1}
,"uni":{"functionality":1,"attributes":1}
,"functionality":{"located":1}
,"located":{"nsm":1}
,"nsm":{"elmi":1,"information":1,"client":1,"server":1}
,"depends":{"upon":1}
,"upon":{"nsm":1}
,"information":{"regarding":1}
,"regarding":{"evc":1}
,"evc":{"uni":1}
,"attributes":{"elmi":1}
,"incorporates":{"two":1}
,"two":{"client\u002Fserver":1}
,"client\u002Fserver":{"modules":1}
,"modules":{"called":1,"implementation":1}
,"onmd":{"(oam":1,"server":1,"module":1,"modules":1}
,"(oam":{"network":1}
,"network":{"management":1}
,"management":{"daemon)":1}
,"daemon)":{"client":1}
,"client":{"elmi":1,"operating":1,"interaction":1}
,"server":{"client":1,"operating":1,"onm":1,"relay":1}
,"operating":{"elmi":1,"onmd":1}
,"module":{"elmi":1,"frame":1}
,"uses":{"socket-based":1}
,"socket-based":{"messaging":1}
,"messaging":{"interact":1}
,"interact":{"onmd":1,"imi":1}
,"includes":{"following":1}
,"following":{"components":1}
,"components":{"nsm":1}
,"interaction":{"nsm":1,"onmd":1}
,"onm":{"client":1}
,"relay":{"status":1}
,"status":{"evcs":1}
,"evcs":{"lacp":1}
,"lacp":{"ports":1,"(link":1}
,"ports":{"support":1,"base":1}
,"(link":{"aggregation":1}
,"aggregation":{"control":1}
,"protocol)":{"ports":1}
,"base":{"module":1}
,"frame":{"handling":1}
,"handling":{"support":1,"configuration":1}
,"initialization":{"procedure":1}
,"procedure":{"frame":1}
,"configuration":{"manager":1}
,"manager":{"interact":1}
,"imi":{"imish":1}
,"imish":{"elmi":1}
,"specific":{"configuration":1}
}
;Search.control.loadWordPairs(pairs);
