var pairs =
{
"g8032_api_erp_inst_set_ring_id":{"function":1,"(struct":1}
,"function":{"sets":1,"implements":1,"succeeds":1}
,"sets":{"ring":1}
,"ring":{"identifier":1}
,"identifier":{"function":1,"output":1}
,"implements":{"ring-id":1}
,"ring-id":{"command":1,"range":1}
,"command":{"syntax":1}
,"syntax":{"s_int32_t":1}
,"s_int32_t":{"g8032_api_erp_inst_set_ring_id":1}
,"(struct":{"g8032_erps_instance":1}
,"g8032_erps_instance":{"*inst":1}
,"*inst":{"u_int8_t":1}
,"u_int8_t":{"ring_id)":1}
,"ring_id)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"inst":1,"none":1}
,"inst":{"erp":1,"null":1}
,"erp":{"instance":1}
,"instance":{"ring_id":1}
,"ring_id":{"ring":1}
,"output":{"parameters":1}
,"none":{"return":1}
,"return":{"values":1}
,"values":{"g8032_error_invalid_ring_id":1}
,"g8032_error_invalid_ring_id":{"ring-id":1}
,"range":{"<1-254>":1}
,"<1-254>":{"g8032_error_none":1}
,"g8032_error_none":{"function":1}
,"succeeds":{"g8032_error_erps_inst_not_found":1}
,"g8032_error_erps_inst_not_found":{"inst":1}
}
;Search.control.loadWordPairs(pairs);
