var pairs =
{
"isis_get_circ_level_priority":{"call":1,"(u_int32_t":1}
,"call":{"gets":1}
,"gets":{"priority":1}
,"priority":{"becoming":1,"return":1}
,"becoming":{"lan":1}
,"lan":{"designated":1}
,"designated":{"level":1}
,"level":{"syntax":1,"u_int32_t":1,"is-is":1,"index":1,"level":1,"output":1}
,"syntax":{"int":1}
,"int":{"isis_get_circ_level_priority":1}
,"(u_int32_t":{"vr_id":1}
,"vr_id":{"u_int32_t":1,"virtual":1,"instance":1}
,"u_int32_t":{"instance":1,"circindex":1,"level":1,"*ret)":1}
,"instance":{"u_int32_t":1,"is-is":1,"circindex":1}
,"circindex":{"u_int32_t":1,"is-is":1}
,"*ret)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"vr_id":1,"ret":1}
,"virtual":{"router":1}
,"router":{"default":1}
,"default":{"value":1}
,"value":{"non-vr":1}
,"non-vr":{"implementation":1}
,"implementation":{"pass":1}
,"pass":{"vr_id":1}
,"is-is":{"instance":1,"circuit":1,"level":1,"priority":1}
,"circuit":{"index":1}
,"index":{"level":1,"found":1,"isis_api_get_error":1}
,"output":{"parameters":1}
,"ret":{"sub-range":1}
,"sub-range":{"is-is":1}
,"return":{"values":1}
,"values":{"isis_api_get_success":1}
,"isis_api_get_success":{"supported":1}
,"supported":{"level":1}
,"found":{"specified":1}
,"specified":{"circuit":1}
,"isis_api_get_error":{"supported":1}
}
;Search.control.loadWordPairs(pairs);
