var pairs =
{
"ospfv3":{"cspf":1,"using":1}
,"cspf":{"zebos-xp":1}
,"zebos-xp":{"supports":1}
,"supports":{"traffic":1}
,"traffic":{"engineering":1}
,"engineering":{"extensions":1}
,"extensions":{"ospf":1}
,"ospf":{"version":1}
,"version":{"(ospfv3)":1}
,"(ospfv3)":{"tlvs":1}
,"tlvs":{"sub":1,"intra-area-te":1,"extend":1,"sub-tlvs":1}
,"sub":{"tlvs":1}
,"intra-area-te":{"link":1}
,"link":{"state":1}
,"state":{"advertisement":1}
,"advertisement":{"(lsa)":1}
,"(lsa)":{"used":1}
,"used":{"constrained-based":1}
,"constrained-based":{"spf":1}
,"spf":{"calculation":1}
,"calculation":{"tlvs":1}
,"extend":{"capabilities":1}
,"capabilities":{"ipv6":1}
,"ipv6":{"networks":1}
,"networks":{"functions":1}
,"functions":{"defined":1}
,"defined":{"rfc":1}
,"rfc":{"4203":1,"3270":1}
,"4203":{"rfc":1}
,"3270":{"extended":1}
,"extended":{"ospfv3":1}
,"using":{"tlvs":1}
,"sub-tlvs":{"described":1}
,"described":{"ietf":1}
,"ietf":{"draft":1}
,"draft":{"draft-ietf-ospf-ospfv3-traffic-09.txt":1}
}
;Search.control.loadWordPairs(pairs);
